ESPResSo: registration.hpp File Reference
actor/registration.hpp File Reference
#include "actor/visitors.hpp"
#include <boost/optional.hpp>
#include <boost/variant.hpp>
#include <memory>
Functions
template<typename Variant , typename T >
void add_actor (boost::optional< Variant > &active_actor, std::shared_ptr< T > const &actor, void(&on_actor_change)(), bool(&flag_all_reduce)(bool))
Register an actor in a thread-safe manner.
template<typename Variant , typename T >
void remove_actor (boost::optional< Variant > &active_actor, std::shared_ptr< T > const &actor, void(&on_actor_change)())
Function Documentation
add_actor()
template<typename Variant , typename T > void add_actor (boost::optional< Variant > & active_actor, std::shared_ptr< T > const & actor, void(&)() on_actor_change, bool(&)(bool) flag_all_reduce)
Register an actor in a thread-safe manner.
Definition at line 32 of file actor/registration.hpp.
Referenced by ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >::do_call_method(), ScriptInterface::Dipoles::Actor< DipolarDirectSumGpu, ::DipolarDirectSumGpu >::do_call_method(), and ScriptInterface::Coulomb::ICCStar::do_call_method().
remove_actor()
template<typename Variant , typename T > void remove_actor (boost::optional< Variant > & active_actor, std::shared_ptr< T > const & actor, void(&)() on_actor_change)
Definition at line 54 of file actor/registration.hpp.
References ScriptInterface::none.
Referenced by ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >::do_call_method(), ScriptInterface::Dipoles::Actor< DipolarDirectSumGpu, ::DipolarDirectSumGpu >::do_call_method(), and ScriptInterface::Coulomb::ICCStar::do_call_method().