ESPResSo: angle_common.hpp File Reference
angle_common.hpp File Reference
Common code for functions calculating angle forces.
#include "config/config.hpp"
#include <utils/Vector.hpp>
#include <algorithm>
#include <cmath>
#include <tuple>
Functions
double calc_cosine (Utils::Vector3d const &vec1, Utils::Vector3d const &vec2, bool sanitize_cosine=false)
Compute the cosine of the angle between three particles.
template<typename ForceFactor >
std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > angle_generic_force (Utils::Vector3d const &vec1, Utils::Vector3d const &vec2, ForceFactor forceFactor, bool sanitize_cosine)
Compute a three-body angle interaction force.
Variables
constexpr auto tiny_cos_angle_value {0.9999999999}
Tiny angle cutoff for cosine calculations.
Detailed Description
Common code for functions calculating angle forces.
Definition in file angle_common.hpp.
Function Documentation
angle_generic_force()
template<typename ForceFactor > std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > angle_generic_force (Utils::Vector3d const & vec1, Utils::Vector3d const & vec2, ForceFactor forceFactor, bool sanitize_cosine)
Compute a three-body angle interaction force.
See the details in General expressions for the forces. The \(K(\theta_{ijk}) \) term is provided as a lambda function in forceFactor.
Parameters
[in] vec1 Vector from central particle to left particle.
[in] vec2 Vector from central particle to right particle.
[in] forceFactor Angle force term.
[in] sanitize_cosine Sanitize the cosine of the angle.
Template Parameters
ForceFactor Function evaluating the angle force term for a given angle.
Returns
Forces on the second, first and third particles, in that order.
Definition at line 75 of file angle_common.hpp.
References stream, and tiny_cos_angle_value.
Referenced by AngleCosineBond::forces(), AngleCossquareBond::forces(), AngleHarmonicBond::forces(), and TabulatedAngleBond::forces().
calc_cosine()
double calc_cosine (Utils::Vector3d const & vec1, Utils::Vector3d const & vec2, bool sanitize_cosine = false) inline
Compute the cosine of the angle between three particles.
Parameters
[in] vec1 Vector from central particle to left particle.
[in] vec2 Vector from central particle to right particle.
[in] sanitize_cosine Sanitize the cosine of the angle.
Returns
\(\vec{r_{ij}} \), \(\vec{r_{kj}} \), \(\left\|\vec{r_{ij}}\right\|^{-1} \), \(\left\|\vec{r_{kj}}\right\|^{-1} \), \(\cos(\theta_{ijk}) \)
Definition at line 49 of file angle_common.hpp.
References stream, and tiny_cos_angle_value.
Referenced by AngleCosineBond::energy(), AngleCossquareBond::energy(), AngleHarmonicBond::energy(), and TabulatedAngleBond::energy().
Variable Documentation
tiny_cos_angle_value
constexpr auto tiny_cos_angle_value {0.9999999999} inline constexpr
Tiny angle cutoff for cosine calculations.
Definition at line 37 of file angle_common.hpp.
Referenced by angle_generic_force(), calc_cosine(), and Observables::BondAngles::evaluate().