ESPResSo: bonds.cpp File Reference
bonds.cpp File Reference
#include "cell_system/CellStructure.hpp"
#include "system/System.hpp"
#include <vector>
Functions
bool add_bond (System::System &system, int bond_id, std::vector< int > const &particle_ids)
Add a bond to a particle.
Function Documentation
add_bond()
bool add_bond (System::System & system, int bond_id, std::vector< int > const & particle_ids)
Add a bond to a particle.
The caller is responsible for calling System::System::on_particle_change().
Definition at line 25 of file bonds.cpp.
References Particle::bonds(), and stream.
Referenced by CollisionDetection::add_bind_centers(), ScriptInterface::Particles::ParticleHandle::do_call_method(), and ScriptInterface::Particles::set_particles_bonds().