ESPResSo: BondList.hpp File Reference
BondList.hpp File Reference
#include <utils/compact_vector.hpp>
#include <boost/container/vector.hpp>
#include <boost/iterator/iterator_facade.hpp>
#include <boost/serialization/access.hpp>
#include <boost/serialization/array.hpp>
#include <boost/version.hpp>
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <memory>
#include <span>
#include <type_traits>
Classes
class BondView
Immutable view on a bond.
class BondList
Bond storage.
class BondList::Iterator
Functions
bool pair_bond_exists_on (BondList const &bonds, int partner_id, int bond_id)
Check if there is a specific bond in a bond list.
Function Documentation
pair_bond_exists_on()
bool pair_bond_exists_on (BondList const & bonds, int partner_id, int bond_id) inline
Check if there is a specific bond in a bond list.
Parameters
bonds List of bonds to check
partner_id Id of the bond partner
bond_id Id of the bond parameters.
Returns
True iff there is a bond to the specified id of the specified type.
Definition at line 238 of file BondList.hpp.
References BondList::begin(), BondList::end(), and stream.
Referenced by PairCriteria::BondCriterion::decide(), and CollisionDetection::detect_collision_common().