ESPResSo: BoxGeometry.hpp File Reference
BoxGeometry.hpp File Reference
#include "algorithm/periodic_fold.hpp"
#include "lees_edwards/LeesEdwardsBC.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sgn.hpp>
#include <bitset>
#include <cassert>
#include <cmath>
#include <limits>
#include <utility>
Classes
class BoxGeometry
Enumerations
enum BoxType { BoxType::CUBOID = 0, BoxType::LEES_EDWARDS = 1 }
Functions
std::pair< double, int > fold_coordinate (double pos, int image_box, double const &length)
Fold a coordinate to primary simulation box.
void fold_position (Utils::Vector3d &pos, Utils::Vector3i &image_box, const BoxGeometry &box)
Fold particle coordinates to primary simulation box.
Utils::Vector3d folded_position (const Utils::Vector3d &p, const BoxGeometry &box)
Fold particle coordinates to primary simulation box.
Enumeration Type Documentation
BoxType
enum BoxType strong
Enumerator
CUBOID
LEES_EDWARDS
Definition at line 73 of file BoxGeometry.hpp.
Function Documentation
fold_coordinate()
std::pair<double, int> fold_coordinate (double pos, int image_box, double const & length) inline
Fold a coordinate to primary simulation box.
Parameters
pos coordinate to fold
image_box image box offset
length box length
Definition at line 236 of file BoxGeometry.hpp.
References anonymous_namespace{Correlator.cpp}::min(), Algorithm::periodic_fold(), and pos.
Referenced by fold_position().
fold_position()
void fold_position (Utils::Vector3d & pos, Utils::Vector3i & image_box, const BoxGeometry & box) inline
Fold particle coordinates to primary simulation box.
Lees-Edwards offset is ignored.
Parameters
[in,out] pos coordinate to fold
[in,out] image_box image box offset
[in] box box parameters (side lengths, periodicity)
Definition at line 257 of file BoxGeometry.hpp.
References fold_coordinate(), BoxGeometry::length(), BoxGeometry::periodic(), and pos.
Referenced by anonymous_namespace{RegularDecomposition.cpp}::fold_and_reset(), local_insert_particle(), local_move_particle(), AtomDecomposition::resort(), and VirtualSitesRelative::update().
folded_position()
Utils::Vector3d folded_position (const Utils::Vector3d & p, const BoxGeometry & box) inline
Fold particle coordinates to primary simulation box.
Parameters
p coordinate to fold
box box parameters (side lengths, periodicity)
Returns
Folded coordinates.
Definition at line 272 of file BoxGeometry.hpp.
References BoxGeometry::length(), BoxGeometry::periodic(), and Algorithm::periodic_fold().
Referenced by Constraints::Constraints< ParticleRange, Constraint >::add_energy(), Constraints::Constraints< ParticleRange, Constraint >::add_forces(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), Observables::CylindricalDensityProfile::evaluate(), Observables::DensityProfile::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::FluxDensityProfile::evaluate(), Observables::ForceDensityProfile::evaluate(), is_valid_position(), DipolarDirectSumWithReplica::kernel(), lb_lbfluid_get_interpolated_density(), lb_lbfluid_get_interpolated_velocity(), map_position_node_array(), pack_particles(), CoulombScafacosImpl::update_particle_data(), DipolarScafacosImpl::update_particle_data(), and Writer::H5md::File::write().