ESPResSo: buckingham.hpp File Reference
buckingham.hpp File Reference
Routines to calculate the Buckingham potential between particle pairs.
#include "config/config.hpp"
#include "nonbonded_interaction_data.hpp"
#include <cmath>
Functions
double buck_force_r (double A, double B, double C, double D, double r)
Resultant Force due to a Buckingham potential between two particles at interatomic separation r greater than or equal to discont.
double buck_energy_r (double A, double B, double C, double D, double shift, double r)
Potential Energy due to a Buckingham potential between two particles at interatomic separation r greater than or equal to discont.
double buck_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate Buckingham force factor.
double buck_pair_energy (IA_parameters const &ia_params, double dist)
Calculate Buckingham energy.
Detailed Description
Routines to calculate the Buckingham potential between particle pairs.
Implementation in buckingham.cpp.
Definition in file buckingham.hpp.
Function Documentation
buck_energy_r()
double buck_energy_r (double A, double B, double C, double D, double shift, double r) inline
Potential Energy due to a Buckingham potential between two particles at interatomic separation r greater than or equal to discont.
Definition at line 46 of file buckingham.hpp.
References stream.
Referenced by buck_pair_energy(), and Buckingham_Parameters::Buckingham_Parameters().
buck_force_r()
double buck_force_r (double A, double B, double C, double D, double r) inline
Resultant Force due to a Buckingham potential between two particles at interatomic separation r greater than or equal to discont.
Definition at line 40 of file buckingham.hpp.
References stream.
Referenced by buck_pair_force_factor(), and Buckingham_Parameters::Buckingham_Parameters().
buck_pair_energy()
double buck_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate Buckingham energy.
Definition at line 72 of file buckingham.hpp.
References buck_energy_r(), and stream.
Referenced by calc_non_bonded_pair_energy().
buck_pair_force_factor()
double buck_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate Buckingham force factor.
Definition at line 52 of file buckingham.hpp.
References buck_force_r(), and stream.
Referenced by calc_central_radial_force().