ESPResSo: CellStructure.cpp File Reference
CellStructure.cpp File Reference
#include "cell_system/CellStructure.hpp"
#include "cell_system/AtomDecomposition.hpp"
#include "cell_system/HybridDecomposition.hpp"
#include "cell_system/ParticleDecomposition.hpp"
#include "cell_system/RegularDecomposition.hpp"
#include "BoxGeometry.hpp"
#include "LocalBox.hpp"
#include "Particle.hpp"
#include "aosoa_pack.hpp"
#include "cell_system/CellStructureType.hpp"
#include "communication.hpp"
#include "custom_verlet_list.hpp"
#include "ghosts.hpp"
#include "integrators/Propagation.hpp"
#include "lees_edwards/lees_edwards.hpp"
#include "particle_enumeration.hpp"
#include "particle_reduction.hpp"
#include "system/System.hpp"
#include <utils/Vector.hpp>
#include <utils/contains.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
#include <caliper/cali.h>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <Cabana_Core.hpp>
#include <Cabana_NeighborList.hpp>
#include <Kokkos_Core.hpp>
#include <omp.h>
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <iterator>
#include <memory>
#include <numbers>
#include <optional>
#include <ranges>
#include <set>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>
Classes
struct anonymous_namespace{CellStructure.cpp}::UpdateParticleIndexVisitor
Apply a ParticleChange to a particle index.
Namespaces
namespace anonymous_namespace{CellStructure.cpp}
Functions
static auto estimate_max_counts (double pair_cutoff, std::size_t number_of_unique_particles, double local_box_volume, std::size_t num_local_particles)
unsigned map_data_parts (unsigned data_parts)
Map the data parts flags from cells to those used internally by the ghost communication.
Function Documentation
estimate_max_counts()
static auto estimate_max_counts (double pair_cutoff, std::size_t number_of_unique_particles, double local_box_volume, std::size_t num_local_particles) static
Definition at line 106 of file CellStructure.cpp.
References stream.
Referenced by CellStructure::rebuild_local_properties().
map_data_parts()
unsigned map_data_parts (unsigned data_parts)
Map the data parts flags from cells to those used internally by the ghost communication.
Parameters
data_parts data parts flags
Returns
ghost communication flags
Definition at line 361 of file CellStructure.cpp.
References GHOSTTRANS_BONDS, GHOSTTRANS_FORCE, GHOSTTRANS_MOMENTUM, GHOSTTRANS_NONE, GHOSTTRANS_POSITION, GHOSTTRANS_PROPRTS, GHOSTTRANS_RATTLE, and stream.
Referenced by CellStructure::ghosts_update(), and HybridDecomposition::resort().