ESPResSo: walberla::pystencils::InitialPDFsSetterSinglePrecision Class Reference
walberla::pystencils::InitialPDFsSetterSinglePrecision Class Reference
#include <InitialPDFsSetterSinglePrecision.h>
Public Member Functions
InitialPDFsSetterSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, float rho_0)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< InitialPDFsSetterSinglePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterSinglePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID forceID
BlockDataID pdfsID
BlockDataID velocityID
float rho_0_
Detailed Description
Definition at line 53 of file InitialPDFsSetterSinglePrecision.h.
Constructor & Destructor Documentation
InitialPDFsSetterSinglePrecision()
walberla::pystencils::InitialPDFsSetterSinglePrecision::InitialPDFsSetterSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, float rho_0) inline
Definition at line 55 of file InitialPDFsSetterSinglePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::InitialPDFsSetterSinglePrecision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 95 of file InitialPDFsSetterSinglePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecision::getSweep () inline
Definition at line 82 of file InitialPDFsSetterSinglePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecision::getSweep (const shared_ptr< InitialPDFsSetterSinglePrecision > & kernel) inline static
Definition at line 69 of file InitialPDFsSetterSinglePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecision::getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterSinglePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 73 of file InitialPDFsSetterSinglePrecision.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 87 of file InitialPDFsSetterSinglePrecision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::InitialPDFsSetterSinglePrecision::operator() (IBlock * block) inline
Definition at line 66 of file InitialPDFsSetterSinglePrecision.h.
References block(), and run().
run()
void walberla::pystencils::InitialPDFsSetterSinglePrecision::run (IBlock * block)
Definition at line 82 of file InitialPDFsSetterSinglePrecision.cpp.
References block(), forceID, walberla::pystencils::internal_b8085d63d6b7e842485134abbac511e8::initialpdfssettersingleprecision_initialpdfssettersingleprecision(), pdfsID, RESTRICT, rho_0_, velocity(), and velocityID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::InitialPDFsSetterSinglePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 122 of file InitialPDFsSetterSinglePrecision.cpp.
References block(), forceID, walberla::pystencils::internal_b8085d63d6b7e842485134abbac511e8::initialpdfssettersingleprecision_initialpdfssettersingleprecision(), pdfsID, RESTRICT, rho_0_, velocity(), and velocityID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
forceID
BlockDataID walberla::pystencils::InitialPDFsSetterSinglePrecision::forceID
Definition at line 98 of file InitialPDFsSetterSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
pdfsID
BlockDataID walberla::pystencils::InitialPDFsSetterSinglePrecision::pdfsID
Definition at line 99 of file InitialPDFsSetterSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
rho_0_
float walberla::pystencils::InitialPDFsSetterSinglePrecision::rho_0_
Definition at line 101 of file InitialPDFsSetterSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
velocityID
BlockDataID walberla::pystencils::InitialPDFsSetterSinglePrecision::velocityID
Definition at line 100 of file InitialPDFsSetterSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
InitialPDFsSetterSinglePrecision.h
InitialPDFsSetterSinglePrecision.cpp