ESPResSo: walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards Class Reference
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards Class Reference
#include <StreamCollideSweepDoublePrecisionLeesEdwards.h>
Public Member Functions
StreamCollideSweepDoublePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s)
~StreamCollideSweepDoublePrecisionLeesEdwards ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getGrid_size () const
double getOmega_shear () const
double getV_s () const
void setGrid_size (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwards > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwards > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
Constructor & Destructor Documentation
StreamCollideSweepDoublePrecisionLeesEdwards()
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::StreamCollideSweepDoublePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s) inline
Definition at line 57 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
~StreamCollideSweepDoublePrecisionLeesEdwards()
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::~StreamCollideSweepDoublePrecisionLeesEdwards () inline
Definition at line 64 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 105 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
getGrid_size()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getGrid_size () const inline
Definition at line 108 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getOmega_shear () const inline
Definition at line 109 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getSweep () inline
Definition at line 92 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwards > & kernel) inline static
Definition at line 78 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwards > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 83 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 97 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
References runOnCellInterval().
getV_s()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::getV_s () const inline
Definition at line 110 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
operator()()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::run (IBlock * block)
Definition at line 123 of file StreamCollideSweepDoublePrecisionLeesEdwards.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_654880d20ef2a4dee16898b514dd6bf5::streamcollidesweepdoubleprecisionleesedwards_streamcollidesweepdoubleprecisionleesedwards().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 174 of file StreamCollideSweepDoublePrecisionLeesEdwards.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_654880d20ef2a4dee16898b514dd6bf5::streamcollidesweepdoubleprecisionleesedwards_streamcollidesweepdoubleprecisionleesedwards().
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::setGrid_size (const double value) inline
Definition at line 111 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::setOmega_shear (const double value) inline
Definition at line 112 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
setV_s()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwards::setV_s (const double value) inline
Definition at line 113 of file StreamCollideSweepDoublePrecisionLeesEdwards.h.
The documentation for this class was generated from the following files:
StreamCollideSweepDoublePrecisionLeesEdwards.h
StreamCollideSweepDoublePrecisionLeesEdwards.cpp