ESPResSo: Accumulators::MeanVarianceCalculator Class Reference
Accumulators::MeanVarianceCalculator Class Reference
#include <MeanVarianceCalculator.hpp>
Public Member Functions
MeanVarianceCalculator (::System::System const *system, int delta_N, std::shared_ptr< Observables::Observable > obs)
void update (boost::mpi::communicator const &comm) override
std::vector< double > mean ()
std::vector< double > variance ()
std::vector< double > std_error ()
std::string get_internal_state () const final
void set_internal_state (std::string const &) final
std::vector< std::size_t > shape () const override
Public Member Functions inherited from Accumulators::AccumulatorBase
AccumulatorBase (::System::System const *system, int delta_N)
virtual ~AccumulatorBase ()=default
int & delta_N ()
bool has_same_system_handle (::System::System const *system) const
void override_system_handle (::System::System const *system)
Additional Inherited Members
Protected Attributes inherited from Accumulators::AccumulatorBase
void const * m_system
for bookkeeping purposes
Detailed Description
Definition at line 34 of file core/accumulators/MeanVarianceCalculator.hpp.
Constructor & Destructor Documentation
MeanVarianceCalculator()
Accumulators::MeanVarianceCalculator::MeanVarianceCalculator (::System::System const * system, int delta_N, std::shared_ptr< Observables::Observable > obs) inline
Definition at line 38 of file core/accumulators/MeanVarianceCalculator.hpp.
Member Function Documentation
get_internal_state()
std::string Accumulators::MeanVarianceCalculator::get_internal_state () const final virtual
Implements Accumulators::AccumulatorBase.
Definition at line 53 of file MeanVarianceCalculator.cpp.
References stream.
mean()
std::vector< double > Accumulators::MeanVarianceCalculator::mean ()
Definition at line 43 of file MeanVarianceCalculator.cpp.
References Utils::Accumulator::mean().
set_internal_state()
void Accumulators::MeanVarianceCalculator::set_internal_state (std::string const & state) final virtual
Implements Accumulators::AccumulatorBase.
Definition at line 62 of file MeanVarianceCalculator.cpp.
References Accumulators::AccumulatorBase::m_system, and stream.
shape()
std::vector< std::size_t > Accumulators::MeanVarianceCalculator::shape () const inline override virtual
Implements Accumulators::AccumulatorBase.
Definition at line 48 of file core/accumulators/MeanVarianceCalculator.hpp.
std_error()
std::vector< double > Accumulators::MeanVarianceCalculator::std_error ()
Definition at line 49 of file MeanVarianceCalculator.cpp.
References Utils::Accumulator::std_error().
update()
void Accumulators::MeanVarianceCalculator::update (boost::mpi::communicator const & comm) override virtual
Implements Accumulators::AccumulatorBase.
Definition at line 35 of file MeanVarianceCalculator.cpp.
variance()
std::vector< double > Accumulators::MeanVarianceCalculator::variance ()
Definition at line 45 of file MeanVarianceCalculator.cpp.
References Utils::Accumulator::variance().
The documentation for this class was generated from the following files:
core/accumulators/MeanVarianceCalculator.hpp
MeanVarianceCalculator.cpp