ESPResSo: FdElectrostatics Class Reference
FdElectrostatics Class Reference
Classes
struct Grid
struct InputParameters
struct Parameters
Public Member Functions
~FdElectrostatics ()
FdElectrostatics (InputParameters inputParameters, cudaStream_t stream)
void calculatePotential ()
void calculatePotential (cufftComplex *charge_potential)
Grid getGrid ()
Detailed Description
Definition at line 24 of file fd-electrostatics.cuh.
Constructor & Destructor Documentation
~FdElectrostatics()
FdElectrostatics::~FdElectrostatics ()
Definition at line 88 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::Parameters::charge_potential, cuda_safe_mem, and FdElectrostatics::Parameters::greensfcn.
FdElectrostatics()
FdElectrostatics::FdElectrostatics (InputParameters inputParameters, cudaStream_t stream)
Definition at line 96 of file fd-electrostatics_cuda.cu.
References calculate_dim_grid(), FdElectrostatics::Parameters::charge_potential, createGreensfcn(), cuda_safe_mem, FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, FdElectrostatics::InputParameters::dim_z, fde_parameters_gpu, FdElectrostatics::Parameters::greensfcn, KERNELCALL_stream, stream, and threads_per_block.
Member Function Documentation
calculatePotential() [1/2]
void FdElectrostatics::calculatePotential ()
Definition at line 191 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::Parameters::charge_potential.
Referenced by ek_integrate_electrostatics().
calculatePotential() [2/2]
void FdElectrostatics::calculatePotential (cufftComplex * charge_potential)
Definition at line 195 of file fd-electrostatics_cuda.cu.
References calculate_dim_grid(), FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, FdElectrostatics::InputParameters::dim_z, KERNELCALL, multiplyGreensfcn(), and threads_per_block.
getGrid()
FdElectrostatics::Grid FdElectrostatics::getGrid ()
Definition at line 217 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::InputParameters::agrid, FdElectrostatics::Parameters::charge_potential, FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, and FdElectrostatics::InputParameters::dim_z.
Referenced by ek_init().
The documentation for this class was generated from the following files:
fd-electrostatics.cuh
fd-electrostatics_cuda.cu