ESPResSo: walberla::pystencils::CollideSweepDoublePrecisionThermalized Class Reference
walberla::pystencils::CollideSweepDoublePrecisionThermalized Class Reference
#include <CollideSweepDoublePrecisionThermalized.h>
Public Member Functions
CollideSweepDoublePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepDoublePrecisionThermalized > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionThermalized > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepDoublePrecisionThermalized.h.
Constructor & Destructor Documentation
CollideSweepDoublePrecisionThermalized()
walberla::pystencils::CollideSweepDoublePrecisionThermalized::CollideSweepDoublePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file CollideSweepDoublePrecisionThermalized.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 103 of file CollideSweepDoublePrecisionThermalized.h.
getBlock_offset_0()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalized::getBlock_offset_0 () const inline
Definition at line 112 of file CollideSweepDoublePrecisionThermalized.h.
getBlock_offset_1()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalized::getBlock_offset_1 () const inline
Definition at line 113 of file CollideSweepDoublePrecisionThermalized.h.
getBlock_offset_2()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalized::getBlock_offset_2 () const inline
Definition at line 114 of file CollideSweepDoublePrecisionThermalized.h.
getKt()
double walberla::pystencils::CollideSweepDoublePrecisionThermalized::getKt () const inline
Definition at line 115 of file CollideSweepDoublePrecisionThermalized.h.
getOmega_bulk()
double walberla::pystencils::CollideSweepDoublePrecisionThermalized::getOmega_bulk () const inline
Definition at line 116 of file CollideSweepDoublePrecisionThermalized.h.
getOmega_even()
double walberla::pystencils::CollideSweepDoublePrecisionThermalized::getOmega_even () const inline
Definition at line 117 of file CollideSweepDoublePrecisionThermalized.h.
getOmega_odd()
double walberla::pystencils::CollideSweepDoublePrecisionThermalized::getOmega_odd () const inline
Definition at line 118 of file CollideSweepDoublePrecisionThermalized.h.
getOmega_shear()
double walberla::pystencils::CollideSweepDoublePrecisionThermalized::getOmega_shear () const inline
Definition at line 119 of file CollideSweepDoublePrecisionThermalized.h.
getSeed()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalized::getSeed () const inline
Definition at line 120 of file CollideSweepDoublePrecisionThermalized.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalized::getSweep () inline
Definition at line 90 of file CollideSweepDoublePrecisionThermalized.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalized::getSweep (const shared_ptr< CollideSweepDoublePrecisionThermalized > & kernel) inline static
Definition at line 77 of file CollideSweepDoublePrecisionThermalized.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionThermalized > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 81 of file CollideSweepDoublePrecisionThermalized.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 95 of file CollideSweepDoublePrecisionThermalized.h.
References runOnCellInterval().
getTime_step()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalized::getTime_step () const inline
Definition at line 121 of file CollideSweepDoublePrecisionThermalized.h.
operator()()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::operator() (IBlock * block) inline
Definition at line 74 of file CollideSweepDoublePrecisionThermalized.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::run (IBlock * block)
Definition at line 420 of file CollideSweepDoublePrecisionThermalized.cpp.
References block(), walberla::pystencils::internal_0d943397135d13b4628c5752888935d7::collidesweepdoubleprecisionthermalized_collidesweepdoubleprecisionthermalized(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 463 of file CollideSweepDoublePrecisionThermalized.cpp.
References block(), walberla::pystencils::internal_0d943397135d13b4628c5752888935d7::collidesweepdoubleprecisionthermalized_collidesweepdoubleprecisionthermalized(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setBlock_offset_0 (const uint32_t value) inline
Definition at line 122 of file CollideSweepDoublePrecisionThermalized.h.
setBlock_offset_1()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setBlock_offset_1 (const uint32_t value) inline
Definition at line 125 of file CollideSweepDoublePrecisionThermalized.h.
setBlock_offset_2()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setBlock_offset_2 (const uint32_t value) inline
Definition at line 128 of file CollideSweepDoublePrecisionThermalized.h.
setKt()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setKt (const double value) inline
Definition at line 131 of file CollideSweepDoublePrecisionThermalized.h.
setOmega_bulk()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setOmega_bulk (const double value) inline
Definition at line 132 of file CollideSweepDoublePrecisionThermalized.h.
setOmega_even()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setOmega_even (const double value) inline
Definition at line 133 of file CollideSweepDoublePrecisionThermalized.h.
setOmega_odd()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setOmega_odd (const double value) inline
Definition at line 134 of file CollideSweepDoublePrecisionThermalized.h.
setOmega_shear()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setOmega_shear (const double value) inline
Definition at line 135 of file CollideSweepDoublePrecisionThermalized.h.
setSeed()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setSeed (const uint32_t value) inline
Definition at line 136 of file CollideSweepDoublePrecisionThermalized.h.
setTime_step()
void walberla::pystencils::CollideSweepDoublePrecisionThermalized::setTime_step (const uint32_t value) inline
Definition at line 137 of file CollideSweepDoublePrecisionThermalized.h.
The documentation for this class was generated from the following files:
CollideSweepDoublePrecisionThermalized.h
CollideSweepDoublePrecisionThermalized.cpp