ESPResSo: walberla::LBWalberlaImpl< FloatType, Architecture > Class Template Reference
walberla::LBWalberlaImpl< FloatType, Architecture > Class Template Reference
Class that runs and controls the LB on waLBerla.
#include <LBWalberlaImpl.hpp>
Classes
class DensityVTKWriter
struct FieldTrait
struct GhostComm
class PressureTensorVTKWriter
class VelocityVTKWriter
class VTKWriter
Public Types
using Stencil = stencil::D3Q19
Stencil for collision and streaming operations.
using StencilFull = stencil::D3Q27
Stencil for ghost communication (includes domain corners).
using BlockStorage = LatticeWalberla::Lattice_T
Lattice model (e.g.
using PdfField = FieldTrait< FloatType, Architecture >::PdfField
using VectorField = FieldTrait< FloatType, Architecture >::VectorField
using FlagField = BoundaryModel::FlagField
Public Types inherited from LatticeModel
using units_map = std::unordered_map< std::string, double >
Public Member Functions
template<typename T >
FloatType FloatType_c (T t) const
std::size_t stencil_size () const noexcept override
bool is_double_precision () const noexcept override
LBWalberlaImpl (std::shared_ptr< LatticeWalberla > lattice, double viscosity, double density)
void integrate () override
void ghost_communication () override
void ghost_communication_pdf () override
void ghost_communication_vel () override
void ghost_communication_laf () override
void ghost_communication_boundary ()
void ghost_communication_full ()
void apply_lees_edwards_interpolation ()
void set_collision_model (double kT, unsigned int seed) override
void set_collision_model (std::unique_ptr< LeesEdwardsPack > &&lees_edwards_pack) override
void check_lebc (unsigned int shear_direction, unsigned int shear_plane_normal) const override
void set_viscosity (double viscosity) override
double get_viscosity () const noexcept override
double get_density () const noexcept override
template<typename T >
void zero_centered_transform_impl (T &data, auto const factor) const
void zero_centered_to_lb_in_place (auto &data) const
void zero_centered_to_md_in_place (auto &data) const
auto zero_centered_to_lb (auto const &data) const
auto zero_centered_to_md (auto const &data) const
std::optional< Utils::Vector3d > get_node_velocity (Utils::Vector3i const &node, bool consider_ghosts=false) const override
bool set_node_velocity (Utils::Vector3i const &node, Utils::Vector3d const &v) override
std::vector< double > get_slice_velocity (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_velocity (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &velocity) override
bool is_gpu () const noexcept override
std::function< bool(Utils::Vector3d const &)> make_lattice_position_checker (bool consider_points_in_halo) const override
void add_forces_at_pos (std::vector< Utils::Vector3d > const &pos, std::vector< Utils::Vector3d > const &forces) override
auto make_force_interpolation_kernel () const
auto make_velocity_interpolation_kernel () const
auto make_density_interpolation_kernel () const
std::vector< Utils::Vector3d > get_velocities_at_pos (std::vector< Utils::Vector3d > const &pos) override
std::vector< double > get_densities_at_pos (std::vector< Utils::Vector3d > const &pos) override
std::optional< Utils::Vector3d > get_velocity_at_pos (Utils::Vector3d const &pos, bool consider_points_in_halo=false) const override
std::optional< double > get_density_at_pos (Utils::Vector3d const &pos, bool consider_points_in_halo=false) const override
bool add_force_at_pos (Utils::Vector3d const &pos, Utils::Vector3d const &force) override
std::optional< Utils::Vector3d > get_node_force_to_be_applied (Utils::Vector3i const &node) const override
std::optional< Utils::Vector3d > get_node_last_applied_force (Utils::Vector3i const &node, bool consider_ghosts=false) const override
bool set_node_last_applied_force (Utils::Vector3i const &node, Utils::Vector3d const &force) override
std::vector< double > get_slice_last_applied_force (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_last_applied_force (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &force) override
std::optional< std::vector< double > > get_node_population (Utils::Vector3i const &node, bool consider_ghosts=false) const override
bool set_node_population (Utils::Vector3i const &node, std::vector< double > const &population) override
std::vector< double > get_slice_population (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_population (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &population) override
std::optional< double > get_node_density (Utils::Vector3i const &node, bool consider_ghosts=false) const override
bool set_node_density (Utils::Vector3i const &node, double density) override
std::vector< double > get_slice_density (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_density (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &density) override
std::optional< Utils::Vector3d > get_node_velocity_at_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const override
bool set_node_velocity_at_boundary (Utils::Vector3i const &node, Utils::Vector3d const &velocity) override
std::vector< std::optional< Utils::Vector3d > > get_slice_velocity_at_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_velocity_at_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< std::optional< Utils::Vector3d > > const &velocity) override
std::optional< Utils::Vector3d > get_node_boundary_force (Utils::Vector3i const &node) const override
bool remove_node_from_boundary (Utils::Vector3i const &node) override
std::optional< bool > get_node_is_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const override
std::vector< bool > get_slice_is_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void reallocate_ubb_field () override
void on_boundary_add ()
void clear_boundaries () override
void update_boundary_from_shape (std::vector< int > const &raster_flat, std::vector< double > const &data_flat) override
std::optional< Utils::VectorXd< 9 > > get_node_pressure_tensor (Utils::Vector3i const &node) const override
std::vector< double > get_slice_pressure_tensor (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
Utils::Vector3i flat_index_to_node (int index) const
Utils::Vector3i get_neighbor_node (Utils::Vector3i const &node, int dir) const
Utils::Vector3d get_boundary_force_from_shape (std::vector< int > const &raster_flat) const override
Utils::Vector3d get_boundary_force () const override
Utils::VectorXd< 9 > get_pressure_tensor () const override
Utils::Vector3d get_momentum () const override
void set_external_force (Utils::Vector3d const &ext_force) override
Utils::Vector3d get_external_force () const noexcept override
double get_kT () const noexcept override
unsigned int get_seed () const noexcept override
std::optional< uint64_t > get_rng_state () const override
void set_rng_state (uint64_t counter) override
LatticeWalberla const & get_lattice () const noexcept override
std::size_t get_velocity_field_id () const noexcept override
std::size_t get_force_field_id () const noexcept override
void register_vtk_field_filters (walberla::vtk::VTKOutput &vtk_obj) override
void register_vtk_field_writers (walberla::vtk::VTKOutput &vtk_obj, LatticeModel::units_map const &units, int flag_observables) override
~LBWalberlaImpl () override=default
Public Member Functions inherited from LBWalberlaBase
~LBWalberlaBase () override=default
Public Member Functions inherited from LatticeModel
virtual ~LatticeModel ()=default
std::shared_ptr< VTKHandle > create_vtk (int delta_N, int initial_count, int flag_observables, units_map const &units_conversion, std::string const &identifier, std::string const &base_folder, std::string const &prefix, bool force_pvtu)
Create a VTK observable.
void write_vtk (std::string const &vtk_uid)
Write a VTK observable to disk.
void switch_vtk (std::string const &vtk_uid, bool status)
Toggle a VTK observable on/off.
Protected Types
using StreamCollisionModelLeesEdwards = detail::KernelTrait< FloatType, Architecture >::StreamCollisionModelLeesEdwards
using StreamCollisionModelThermalized = detail::KernelTrait< FloatType, Architecture >::StreamCollisionModelThermalized
using UpdateVelFromPDF = detail::KernelTrait< FloatType, Architecture >::UpdateVelFromPDF
using InitialPDFsSetter = detail::KernelTrait< FloatType, Architecture >::InitialPDFsSetter
using DynamicUBB = detail::BoundaryHandlingTrait< FloatType, Architecture >::DynamicUBB
using BoundaryModel = BoundaryHandling< FloatType, Vector3< FloatType >, DynamicUBB >
using CollisionModel = std::variant< StreamCollisionModelThermalized, StreamCollisionModelLeesEdwards >
using _PdfField = FieldTrait< FloatType >::PdfField
using _VectorField = FieldTrait< FloatType >::VectorField
using RegularFullCommunicator = FieldTrait< FloatType, Architecture >::template RegularCommScheme< stencil::D3Q27 >
Full communicator.
using BoundaryFullCommunicator = FieldTrait< FloatType, Architecture >::template BoundaryCommScheme< stencil::D3Q27 >
using PDFStreamingCommunicator = FieldTrait< FloatType, Architecture >::template RegularCommScheme< Stencil >
Regular communicator.
template<class Field >
using PackInfo = FieldTrait< FloatType, Architecture >::template PackInfo< Field >
Protected Member Functions
template<typename Field >
auto add_to_storage (std::string const tag)
Convenience function to add a field with a custom allocator.
void setup_streaming_communicator ()
void integrate_vtk_writers () override
Protected Attributes
FloatType m_viscosity
FloatType m_density
kinematic viscosity
FloatType m_kT
unsigned int m_seed
double m_zc_to_md
double m_zc_to_lb
BlockDataID m_pdf_field_id
BlockDataID m_pdf_tmp_field_id
BlockDataID m_flag_field_id
BlockDataID m_last_applied_force_field_id
BlockDataID m_force_to_be_applied_id
BlockDataID m_velocity_field_id
BlockDataID m_vel_tmp_field_id
FlagUID const Boundary_flag {"boundary"}
Flag for boundary cells.
bool m_has_boundaries {false}
std::shared_ptr< LatticeWalberla > m_lattice
std::shared_ptr< BoundaryModel > m_boundary
std::shared_ptr< BoundaryFullCommunicator > m_boundary_communicator
std::shared_ptr< RegularFullCommunicator > m_full_communicator
std::shared_ptr< RegularFullCommunicator > m_pdf_communicator
std::shared_ptr< RegularFullCommunicator > m_vel_communicator
std::shared_ptr< RegularFullCommunicator > m_laf_communicator
std::shared_ptr< PDFStreamingCommunicator > m_pdf_streaming_communicator
std::bitset< GhostComm::SIZE > m_pending_ghost_comm
ResourceObserver m_mpi_cart_comm_observer
std::shared_ptr< CollisionModel > m_collision_model
std::shared_ptr< ResetForce< PdfField, VectorField > > m_reset_force
std::shared_ptr< UpdateVelFromPDF > m_update_velocities_from_pdf
std::shared_ptr< LeesEdwardsPack > m_lees_edwards_callbacks
std::shared_ptr< InterpolateAndShiftAtBoundary< _PdfField, FloatType > > m_lees_edwards_pdf_interpol_sweep
std::shared_ptr< InterpolateAndShiftAtBoundary< _VectorField, FloatType > > m_lees_edwards_vel_interpol_sweep
std::shared_ptr< InterpolateAndShiftAtBoundary< _VectorField, FloatType > > m_lees_edwards_last_applied_force_interpol_sweep
Protected Attributes inherited from LatticeModel
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_auto
VTK writers that are executed automatically.
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_manual
VTK writers that are executed manually.
Detailed Description
template<typename FloatType, lbmpy::Arch Architecture>
class walberla::LBWalberlaImpl< FloatType, Architecture >
Class that runs and controls the LB on waLBerla.
Definition at line 93 of file LBWalberlaImpl.hpp.
Member Typedef Documentation
_PdfField
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::_PdfField = FieldTrait<FloatType>::PdfField protected
Definition at line 167 of file LBWalberlaImpl.hpp.
_VectorField
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::_VectorField = FieldTrait<FloatType>::VectorField protected
Definition at line 168 of file LBWalberlaImpl.hpp.
BlockStorage
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::BlockStorage = LatticeWalberla::Lattice_T
Lattice model (e.g.
blockforest).
Definition at line 118 of file LBWalberlaImpl.hpp.
BoundaryFullCommunicator
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::BoundaryFullCommunicator = FieldTrait<FloatType, Architecture>::template BoundaryCommScheme<stencil::D3Q27> protected
Definition at line 334 of file LBWalberlaImpl.hpp.
BoundaryModel
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::BoundaryModel = BoundaryHandling<FloatType, Vector3<FloatType>, DynamicUBB> protected
Definition at line 107 of file LBWalberlaImpl.hpp.
CollisionModel
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::CollisionModel = std::variant<StreamCollisionModelThermalized, StreamCollisionModelLeesEdwards> protected
Definition at line 109 of file LBWalberlaImpl.hpp.
DynamicUBB
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::DynamicUBB = detail::BoundaryHandlingTrait<FloatType, Architecture>::DynamicUBB protected
Definition at line 105 of file LBWalberlaImpl.hpp.
FlagField
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::FlagField = BoundaryModel::FlagField
Definition at line 173 of file LBWalberlaImpl.hpp.
InitialPDFsSetter
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::InitialPDFsSetter = detail::KernelTrait<FloatType, Architecture>::InitialPDFsSetter protected
Definition at line 103 of file LBWalberlaImpl.hpp.
PackInfo
template<typename FloatType , lbmpy::Arch Architecture> template<class Field > using walberla::LBWalberlaImpl< FloatType, Architecture >::PackInfo = FieldTrait<FloatType, Architecture>::template PackInfo<Field> protected
Definition at line 344 of file LBWalberlaImpl.hpp.
PdfField
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::PdfField = FieldTrait<FloatType, Architecture>::PdfField
Definition at line 171 of file LBWalberlaImpl.hpp.
PDFStreamingCommunicator
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::PDFStreamingCommunicator = FieldTrait<FloatType, Architecture>::template RegularCommScheme<Stencil> protected
Regular communicator.
We use the same directions as the stencil during integration.
Definition at line 341 of file LBWalberlaImpl.hpp.
RegularFullCommunicator
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::RegularFullCommunicator = FieldTrait<FloatType, Architecture>::template RegularCommScheme<stencil::D3Q27> protected
Full communicator.
We use the D3Q27 directions to update cells along the diagonals during a full ghost communication. This is needed to properly update the corners of the ghost layer when setting cell velocities or populations.
Definition at line 331 of file LBWalberlaImpl.hpp.
Stencil
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::Stencil = stencil::D3Q19
Stencil for collision and streaming operations.
Definition at line 114 of file LBWalberlaImpl.hpp.
StencilFull
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::StencilFull = stencil::D3Q27
Stencil for ghost communication (includes domain corners).
Definition at line 116 of file LBWalberlaImpl.hpp.
StreamCollisionModelLeesEdwards
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::StreamCollisionModelLeesEdwards = detail::KernelTrait<FloatType, Architecture>::StreamCollisionModelLeesEdwards protected
Definition at line 95 of file LBWalberlaImpl.hpp.
StreamCollisionModelThermalized
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::StreamCollisionModelThermalized = detail::KernelTrait<FloatType, Architecture>::StreamCollisionModelThermalized protected
Definition at line 98 of file LBWalberlaImpl.hpp.
UpdateVelFromPDF
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::UpdateVelFromPDF = detail::KernelTrait<FloatType, Architecture>::UpdateVelFromPDF protected
Definition at line 101 of file LBWalberlaImpl.hpp.
VectorField
template<typename FloatType , lbmpy::Arch Architecture> using walberla::LBWalberlaImpl< FloatType, Architecture >::VectorField = FieldTrait<FloatType, Architecture>::VectorField
Definition at line 172 of file LBWalberlaImpl.hpp.
Constructor & Destructor Documentation
LBWalberlaImpl()
template<typename FloatType , lbmpy::Arch Architecture> walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl (std::shared_ptr< LatticeWalberla > lattice, double viscosity, double density) inline
Definition at line 450 of file LBWalberlaImpl.hpp.
References block(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_flag_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_force_to_be_applied_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_full_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_laf_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_tmp_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_reset_force, walberla::LBWalberlaImpl< FloatType, Architecture >::m_update_velocities_from_pdf, walberla::LBWalberlaImpl< FloatType, Architecture >::m_vel_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_vel_tmp_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::setup_boundary_handle(), walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator(), and stream.
~LBWalberlaImpl()
template<typename FloatType , lbmpy::Arch Architecture> walberla::LBWalberlaImpl< FloatType, Architecture >::~LBWalberlaImpl () override default
Member Function Documentation
add_force_at_pos()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::add_force_at_pos (Utils::Vector3d const & pos, Utils::Vector3d const & force) inline override virtual
Implements LBWalberlaBase.
Definition at line 1209 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, and walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel().
add_forces_at_pos()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::add_forces_at_pos (std::vector< Utils::Vector3d > const & pos, std::vector< Utils::Vector3d > const & forces) inline override virtual
Implements LBWalberlaBase.
Definition at line 967 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::Interpolation::add_force(), block(), lbmpy::CPU, walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), lbmpy::GPU, walberla::LBWalberlaImpl< FloatType, Architecture >::m_force_to_be_applied_id, walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb_in_place().
add_to_storage()
template<typename FloatType , lbmpy::Arch Architecture> template<typename Field > auto walberla::LBWalberlaImpl< FloatType, Architecture >::add_to_storage (std::string const tag) inline protected
Convenience function to add a field with a custom allocator.
When vectorization is off, let waLBerla decide which memory allocator to use. When vectorization is on, the aligned memory allocator is required, otherwise cpu_vectorize_info["assume_aligned"] will trigger assertions. That is because for single-precision kernels the waLBerla heuristic in src/field/allocation/FieldAllocator.h will fall back to StdFieldAlloc, yet AllocateAligned is needed for intrinsics to work.
Definition at line 390 of file LBWalberlaImpl.hpp.
References block(), lbmpy::CPU, walberla::lbm::accessor::Population::initialize(), walberla::lbm::accessor::Vector::initialize(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, and stream.
apply_lees_edwards_interpolation()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::apply_lees_edwards_interpolation () inline
Definition at line 692 of file LBWalberlaImpl.hpp.
References LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_full().
check_lebc()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::check_lebc (unsigned int shear_direction, unsigned int shear_plane_normal) const inline override virtual
Implements LBWalberlaBase.
Definition at line 774 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_callbacks, and stream.
clear_boundaries()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::clear_boundaries () inline override virtual
Implements LBWalberlaBase.
Definition at line 1681 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_has_boundaries, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator(), and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB.
flat_index_to_node()
template<typename FloatType , lbmpy::Arch Architecture> Utils::Vector3i walberla::LBWalberlaImpl< FloatType, Architecture >::flat_index_to_node (int index) const inline
Definition at line 1749 of file LBWalberlaImpl.hpp.
References LatticeWalberla::get_grid_dimensions(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force_from_shape().
FloatType_c()
template<typename FloatType , lbmpy::Arch Architecture> template<typename T > FloatType walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c (T t) const inline
Definition at line 192 of file LBWalberlaImpl.hpp.
References stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_writers(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_viscosity().
get_boundary_force()
template<typename FloatType , lbmpy::Arch Architecture> Utils::Vector3d walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force () const inline override virtual
Implements LBWalberlaBase.
Definition at line 1802 of file LBWalberlaImpl.hpp.
References block(), LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, stream, walberla::to_vector3d(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
get_boundary_force_from_shape()
template<typename FloatType , lbmpy::Arch Architecture> Utils::Vector3d walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force_from_shape (std::vector< int > const & raster_flat) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1771 of file LBWalberlaImpl.hpp.
References block(), walberla::LBWalberlaImpl< FloatType, Architecture >::flat_index_to_node(), LatticeWalberla::get_block_corner(), LatticeWalberla::get_blocks(), LatticeWalberla::get_grid_dimensions(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_neighbor_node(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
get_densities_at_pos()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_densities_at_pos (std::vector< Utils::Vector3d > const & pos) inline override virtual
Implements LBWalberlaBase.
Definition at line 1143 of file LBWalberlaImpl.hpp.
References block(), lbmpy::CPU, walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::lbm::accessor::Interpolation::get_rho(), lbmpy::GPU, walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), and stream.
get_density()
template<typename FloatType , lbmpy::Arch Architecture> double walberla::LBWalberlaImpl< FloatType, Architecture >::get_density () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 793 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_density.
get_density_at_pos()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_density_at_pos (Utils::Vector3d const & pos, bool consider_points_in_halo = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1198 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, and stream.
get_external_force()
template<typename FloatType , lbmpy::Arch Architecture> Utils::Vector3d walberla::LBWalberlaImpl< FloatType, Architecture >::get_external_force () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 1840 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_reset_force, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
get_force_field_id()
template<typename FloatType , lbmpy::Arch Architecture> std::size_t walberla::LBWalberlaImpl< FloatType, Architecture >::get_force_field_id () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 1880 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_force_to_be_applied_id.
get_kT()
template<typename FloatType , lbmpy::Arch Architecture> double walberla::LBWalberlaImpl< FloatType, Architecture >::get_kT () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 1844 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_kT.
get_lattice()
template<typename FloatType , lbmpy::Arch Architecture> LatticeWalberla const & walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice () const inline override virtual noexcept
Implements LatticeModel.
Definition at line 1872 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::add_forces_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::apply_lees_edwards_interpolation(), walberla::LBWalberlaImpl< FloatType, Architecture >::clear_boundaries(), walberla::LBWalberlaImpl< FloatType, Architecture >::flat_index_to_node(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force_from_shape(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_densities_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_neighbor_node(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_boundary_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocities_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_laf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_pdf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_vel(), walberla::LBWalberlaImpl< FloatType, Architecture >::remove_node_from_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape().
get_momentum()
template<typename FloatType , lbmpy::Arch Architecture> Utils::Vector3d walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum () const inline override virtual
Implements LBWalberlaBase.
Definition at line 1823 of file LBWalberlaImpl.hpp.
References block(), LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::lbm::accessor::MomentumDensity::reduce(), stream, and walberla::to_vector3d().
get_neighbor_node()
template<typename FloatType , lbmpy::Arch Architecture> Utils::Vector3i walberla::LBWalberlaImpl< FloatType, Architecture >::get_neighbor_node (Utils::Vector3i const & node, int dir) const inline
Definition at line 1759 of file LBWalberlaImpl.hpp.
References LatticeWalberla::get_grid_dimensions(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::lbm::DynamicUBBDoublePrecision::neighborOffset, and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force_from_shape().
get_node_boundary_force()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_boundary_force (Utils::Vector3i const & node) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1616 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, and stream.
get_node_density()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1443 of file LBWalberlaImpl.hpp.
References density, walberla::lbm::accessor::Density::get(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, and stream.
get_node_force_to_be_applied()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied (Utils::Vector3i const & node) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1219 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::Vector::get(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_force_to_be_applied_id, stream, walberla::to_vector3d(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
get_node_is_boundary()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< bool > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_is_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1636 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity().
get_node_last_applied_force()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1231 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::Vector::get(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::LAF, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, stream, walberla::to_vector3d(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_boundary_force().
get_node_population()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< std::vector< double > > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_population (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1334 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::Population::get(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, and stream.
get_node_pressure_tensor()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::VectorXd< 9 > > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor (Utils::Vector3i const & node) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1703 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::PressureTensor::get(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, stream, and walberla::to_vector9d().
get_node_velocity()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 831 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::Vector::get(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_has_boundaries, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, stream, walberla::to_vector3d(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
get_node_velocity_at_boundary()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1528 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, stream, walberla::to_vector3d(), and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity().
get_pressure_tensor()
template<typename FloatType , lbmpy::Arch Architecture> Utils::VectorXd< 9 > walberla::LBWalberlaImpl< FloatType, Architecture >::get_pressure_tensor () const inline override virtual
Implements LBWalberlaBase.
Definition at line 1810 of file LBWalberlaImpl.hpp.
References block(), LatticeWalberla::get_blocks(), LatticeWalberla::get_grid_dimensions(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, Utils::product(), walberla::lbm::accessor::PressureTensor::reduce(), stream, and walberla::to_vector9d().
get_rng_state()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< uint64_t > walberla::LBWalberlaImpl< FloatType, Architecture >::get_rng_state () const inline override virtual
Implements LBWalberlaBase.
Definition at line 1852 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_collision_model, walberla::LBWalberlaImpl< FloatType, Architecture >::m_kT, and stream.
get_seed()
template<typename FloatType , lbmpy::Arch Architecture> unsigned int walberla::LBWalberlaImpl< FloatType, Architecture >::get_seed () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 1848 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_seed.
get_slice_density()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1471 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::lbm::accessor::Density::get(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, and stream.
get_slice_is_boundary()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< bool > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_is_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1647 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, and stream.
get_slice_last_applied_force()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1264 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::lbm::accessor::Vector::get(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md_in_place().
get_slice_population()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1375 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::lbm::accessor::Population::get(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::stencil_size(), and stream.
get_slice_pressure_tensor()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1715 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::lbm::accessor::PressureTensor::get(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, and stream.
get_slice_velocity()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< double > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 873 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::lbm::accessor::Vector::get(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, and stream.
get_slice_velocity_at_boundary()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< std::optional< Utils::Vector3d > > walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1553 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, stream, and walberla::to_vector3d().
get_velocities_at_pos()
template<typename FloatType , lbmpy::Arch Architecture> std::vector< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocities_at_pos (std::vector< Utils::Vector3d > const & pos) inline override virtual
Implements LBWalberlaBase.
Definition at line 1097 of file LBWalberlaImpl.hpp.
References block(), lbmpy::CPU, walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::lbm::accessor::Interpolation::get_vel(), lbmpy::GPU, walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), walberla::lbm::accessor::Vector::set_from_list(), and stream.
get_velocity_at_pos()
template<typename FloatType , lbmpy::Arch Architecture> std::optional< Utils::Vector3d > walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocity_at_pos (Utils::Vector3d const & pos, bool consider_points_in_halo = false) const inline override virtual
Implements LBWalberlaBase.
Definition at line 1185 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), stream, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
get_velocity_field_id()
template<typename FloatType , lbmpy::Arch Architecture> std::size_t walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocity_field_id () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 1876 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id.
get_viscosity()
template<typename FloatType , lbmpy::Arch Architecture> double walberla::LBWalberlaImpl< FloatType, Architecture >::get_viscosity () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 789 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_viscosity.
ghost_communication()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication () inline override virtual
Implements LBWalberlaBase.
Definition at line 627 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_laf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_pdf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_vel(), ResourceObserver::is_valid(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::clear_boundaries(), and walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape().
ghost_communication_boundary()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_boundary () inline
Definition at line 673 of file LBWalberlaImpl.hpp.
References ResourceObserver::is_valid(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication().
ghost_communication_full()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_full () inline
Definition at line 681 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::apply_lees_edwards_interpolation(), ResourceObserver::is_valid(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::LAF, walberla::LBWalberlaImpl< FloatType, Architecture >::m_full_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
ghost_communication_laf()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_laf () inline override virtual
Implements LBWalberlaBase.
Definition at line 661 of file LBWalberlaImpl.hpp.
References LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), ResourceObserver::is_valid(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::LAF, walberla::LBWalberlaImpl< FloatType, Architecture >::m_laf_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication().
ghost_communication_pdf()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_pdf () inline override virtual
Implements LBWalberlaBase.
Definition at line 637 of file LBWalberlaImpl.hpp.
References LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), ResourceObserver::is_valid(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_communicator, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication().
ghost_communication_vel()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_vel () inline override virtual
Implements LBWalberlaBase.
Definition at line 649 of file LBWalberlaImpl.hpp.
References LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), ResourceObserver::is_valid(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_vel_communicator, stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication().
integrate()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::integrate () inline override virtual
Implements LBWalberlaBase.
Definition at line 622 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::integrate_vtk_writers().
integrate_vtk_writers()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::integrate_vtk_writers () inline override protected virtual
Implements LatticeModel.
Definition at line 611 of file LBWalberlaImpl.hpp.
References LatticeModel::m_vtk_auto, and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::integrate().
is_double_precision()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::is_double_precision () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 200 of file LBWalberlaImpl.hpp.
is_gpu()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::is_gpu () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 954 of file LBWalberlaImpl.hpp.
References lbmpy::GPU, and stream.
make_density_interpolation_kernel()
template<typename FloatType , lbmpy::Arch Architecture> auto walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel () const inline
Definition at line 1069 of file LBWalberlaImpl.hpp.
References block(), density, walberla::lbm::accessor::Density::get(), walberla::get_block_extended(), walberla::interpolate_bspline_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, stream, and walberla::to_cell().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_densities_at_pos(), and walberla::LBWalberlaImpl< FloatType, Architecture >::get_density_at_pos().
make_force_interpolation_kernel()
template<typename FloatType , lbmpy::Arch Architecture> auto walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel () const inline
Definition at line 1010 of file LBWalberlaImpl.hpp.
References walberla::lbm::accessor::Vector::add(), block(), walberla::get_block_extended(), walberla::interpolate_bspline_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_force_to_be_applied_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_zc_to_lb, stream, and walberla::to_cell().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::add_force_at_pos(), and walberla::LBWalberlaImpl< FloatType, Architecture >::add_forces_at_pos().
make_lattice_position_checker()
template<typename FloatType , lbmpy::Arch Architecture> std::function< bool(Utils::Vector3d const &)> walberla::LBWalberlaImpl< FloatType, Architecture >::make_lattice_position_checker (bool consider_points_in_halo) const inline override virtual
Implements LBWalberlaBase.
Definition at line 959 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, and stream.
make_velocity_interpolation_kernel()
template<typename FloatType , lbmpy::Arch Architecture> auto walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel () const inline
Definition at line 1037 of file LBWalberlaImpl.hpp.
References block(), walberla::lbm::accessor::Vector::get(), walberla::get_block_extended(), walberla::interpolate_bspline_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_has_boundaries, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, stream, walberla::to_cell(), and walberla::to_vector3d().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocities_at_pos(), and walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocity_at_pos().
on_boundary_add()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::on_boundary_add () inline
Definition at line 1673 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_has_boundaries, walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator(), and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape().
reallocate_ubb_field()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::reallocate_ubb_field () inline override virtual
Implements LBWalberlaBase.
Definition at line 1671 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape().
register_vtk_field_filters()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_filters (walberla::vtk::VTKOutput & vtk_obj) inline override virtual
Implements LatticeModel.
Definition at line 1884 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::Boundary_flag, walberla::LBWalberlaImpl< FloatType, Architecture >::m_flag_field_id, and stream.
register_vtk_field_writers()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_writers (walberla::vtk::VTKOutput & vtk_obj, LatticeModel::units_map const & units, int flag_observables) inline override virtual
Implements LatticeModel.
Definition at line 1973 of file LBWalberlaImpl.hpp.
References density, walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c(), lbmpy::GPU, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, pressure_tensor, stream, velocity_vector, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
remove_node_from_boundary()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::remove_node_from_boundary (Utils::Vector3i const & node) inline override virtual
Implements LBWalberlaBase.
Definition at line 1624 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, and stream.
set_collision_model() [1/2]
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model (double kT, unsigned int seed) inline override virtual
Implements LBWalberlaBase.
Definition at line 699 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c(), LatticeWalberla::get_blocks(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_collision_model, walberla::LBWalberlaImpl< FloatType, Architecture >::m_kT, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_seed, walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb().
set_collision_model() [2/2]
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model (std::unique_ptr< LeesEdwardsPack > && lees_edwards_pack) inline override virtual
Implements LBWalberlaBase.
Definition at line 714 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), lbmpy::GPU, walberla::LBWalberlaImpl< FloatType, Architecture >::m_collision_model, walberla::LBWalberlaImpl< FloatType, Architecture >::m_kT, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_callbacks, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_last_applied_force_interpol_sweep, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_pdf_interpol_sweep, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_vel_interpol_sweep, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_tmp_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_vel_tmp_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator(), and stream.
set_external_force()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_external_force (Utils::Vector3d const & ext_force) inline override virtual
Implements LBWalberlaBase.
Definition at line 1836 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_reset_force, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb().
set_node_density()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density (Utils::Vector3i const & node, double density) inline override virtual
Implements LBWalberlaBase.
Definition at line 1457 of file LBWalberlaImpl.hpp.
References density, walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, walberla::lbm::accessor::Density::set(), and stream.
set_node_last_applied_force()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force (Utils::Vector3i const & node, Utils::Vector3d const & force) inline override virtual
Implements LBWalberlaBase.
Definition at line 1244 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::LAF, walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::lbm::accessor::Force::set(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
set_node_population()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population (Utils::Vector3i const & node, std::vector< double > const & population) inline override virtual
Implements LBWalberlaBase.
Definition at line 1351 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c(), walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, walberla::lbm::accessor::Population::set(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
set_node_velocity()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity (Utils::Vector3i const & node, Utils::Vector3d const & v) inline override virtual
Implements LBWalberlaBase.
Definition at line 851 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, walberla::lbm::accessor::Velocity::set(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
set_node_velocity_at_boundary()
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary (Utils::Vector3i const & node, Utils::Vector3d const & velocity) inline override virtual
Implements LBWalberlaBase.
Definition at line 1538 of file LBWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::on_boundary_add(), stream, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB, and velocity().
set_rng_state()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_rng_state (uint64_t counter) inline override virtual
Implements LBWalberlaBase.
Definition at line 1861 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_collision_model, walberla::LBWalberlaImpl< FloatType, Architecture >::m_kT, and stream.
set_slice_density()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & density) inline override virtual
Implements LBWalberlaBase.
Definition at line 1500 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), density, walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, walberla::lbm::accessor::Density::set(), and stream.
set_slice_last_applied_force()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & force) inline override virtual
Implements LBWalberlaBase.
Definition at line 1296 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::LAF, walberla::LBWalberlaImpl< FloatType, Architecture >::m_density, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::lbm::accessor::Force::set(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL.
set_slice_population()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & population) inline override virtual
Implements LBWalberlaBase.
Definition at line 1406 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::lbm::accessor::Population::set(), walberla::LBWalberlaImpl< FloatType, Architecture >::stencil_size(), and stream.
set_slice_velocity()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & velocity) inline override virtual
Implements LBWalberlaBase.
Definition at line 918 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::PDF, walberla::lbm::accessor::Velocity::set(), Utils::Vector< T, N >::size(), stream, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::VEL, and velocity().
set_slice_velocity_at_boundary()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< std::optional< Utils::Vector3d > > const & velocity) inline override virtual
Implements LBWalberlaBase.
Definition at line 1583 of file LBWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::get_block_and_cell(), walberla::get_block_interval(), walberla::get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::on_boundary_add(), Utils::Vector< T, N >::size(), stream, walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB, and velocity().
set_viscosity()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::set_viscosity (double viscosity) inline override virtual
Implements LBWalberlaBase.
Definition at line 785 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::FloatType_c(), and walberla::LBWalberlaImpl< FloatType, Architecture >::m_viscosity.
setup_streaming_communicator()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator () inline protected
Definition at line 429 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_collision_model, walberla::LBWalberlaImpl< FloatType, Architecture >::m_has_boundaries, walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_streaming_communicator, and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::clear_boundaries(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::on_boundary_add(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
stencil_size()
template<typename FloatType , lbmpy::Arch Architecture> std::size_t walberla::LBWalberlaImpl< FloatType, Architecture >::stencil_size () const inline override virtual noexcept
Implements LBWalberlaBase.
Definition at line 196 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population().
update_boundary_from_shape()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape (std::vector< int > const & raster_flat, std::vector< double > const & data_flat) inline override virtual
Implements LBWalberlaBase.
Definition at line 1690 of file LBWalberlaImpl.hpp.
References walberla::fill_3D_vector_array(), LatticeWalberla::get_grid_dimensions(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication(), walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary, walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm, walberla::LBWalberlaImpl< FloatType, Architecture >::on_boundary_add(), walberla::LBWalberlaImpl< FloatType, Architecture >::reallocate_ubb_field(), walberla::set_boundary_from_grid(), stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::GhostComm::UBB.
zero_centered_to_lb()
template<typename FloatType , lbmpy::Arch Architecture> auto walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb (auto const & data) const inline
Definition at line 817 of file LBWalberlaImpl.hpp.
References stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb_in_place().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_external_force().
zero_centered_to_lb_in_place()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb_in_place (auto & data) const inline
Definition at line 809 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_zc_to_lb, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_transform_impl().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::add_forces_at_pos(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb().
zero_centered_to_md()
template<typename FloatType , lbmpy::Arch Architecture> auto walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md (auto const & data) const inline
Definition at line 823 of file LBWalberlaImpl.hpp.
References stream, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md_in_place().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force_from_shape(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_external_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), and walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_writers().
zero_centered_to_md_in_place()
template<typename FloatType , lbmpy::Arch Architecture> void walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md_in_place (auto & data) const inline
Definition at line 813 of file LBWalberlaImpl.hpp.
References walberla::LBWalberlaImpl< FloatType, Architecture >::m_zc_to_md, and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_transform_impl().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md().
zero_centered_transform_impl()
template<typename FloatType , lbmpy::Arch Architecture> template<typename T > void walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_transform_impl (T & data, auto const factor) const inline
Definition at line 798 of file LBWalberlaImpl.hpp.
References stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb_in_place(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md_in_place().
Member Data Documentation
Boundary_flag
template<typename FloatType , lbmpy::Arch Architecture> FlagUID const walberla::LBWalberlaImpl< FloatType, Architecture >::Boundary_flag {"boundary"} protected
Flag for boundary cells.
Definition at line 316 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_filters().
m_boundary
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<BoundaryModel> walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary protected
Definition at line 323 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force_from_shape(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_boundary_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocities_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::reallocate_ubb_field(), walberla::LBWalberlaImpl< FloatType, Architecture >::remove_node_from_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape().
m_boundary_communicator
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<BoundaryFullCommunicator> walberla::LBWalberlaImpl< FloatType, Architecture >::m_boundary_communicator protected
Definition at line 348 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
m_collision_model
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<CollisionModel> walberla::LBWalberlaImpl< FloatType, Architecture >::m_collision_model protected
Definition at line 358 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_rng_state(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_rng_state(), and walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator().
m_density
template<typename FloatType , lbmpy::Arch Architecture> FloatType walberla::LBWalberlaImpl< FloatType, Architecture >::m_density protected
kinematic viscosity
Definition at line 293 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_densities_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force().
m_flag_field_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_flag_field_id protected
Definition at line 302 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), and walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_filters().
m_force_to_be_applied_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_force_to_be_applied_id protected
Definition at line 305 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::add_forces_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_force_field_id(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), and walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel().
m_full_communicator
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<RegularFullCommunicator> walberla::LBWalberlaImpl< FloatType, Architecture >::m_full_communicator protected
Definition at line 349 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_full(), and walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
m_has_boundaries
template<typename FloatType , lbmpy::Arch Architecture> bool walberla::LBWalberlaImpl< FloatType, Architecture >::m_has_boundaries {false} protected
Definition at line 317 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::clear_boundaries(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::on_boundary_add(), and walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator().
m_kT
template<typename FloatType , lbmpy::Arch Architecture> FloatType walberla::LBWalberlaImpl< FloatType, Architecture >::m_kT protected
Definition at line 294 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_kT(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_rng_state(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_rng_state().
m_laf_communicator
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<RegularFullCommunicator> walberla::LBWalberlaImpl< FloatType, Architecture >::m_laf_communicator protected
Definition at line 352 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_laf(), and walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
m_last_applied_force_field_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_last_applied_force_field_id protected
Definition at line 304 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator().
m_lattice
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<LatticeWalberla> walberla::LBWalberlaImpl< FloatType, Architecture >::m_lattice protected
Definition at line 320 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::add_force_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::add_to_storage(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_density_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_lattice(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocity_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_lattice_position_checker(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_writers(), and walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator().
m_lees_edwards_callbacks
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<LeesEdwardsPack> walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_callbacks protected
Definition at line 367 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::check_lebc(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_lees_edwards_last_applied_force_interpol_sweep
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<InterpolateAndShiftAtBoundary<_VectorField, FloatType> > walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_last_applied_force_interpol_sweep protected
Definition at line 373 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_lees_edwards_pdf_interpol_sweep
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<InterpolateAndShiftAtBoundary<_PdfField, FloatType> > walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_pdf_interpol_sweep protected
Definition at line 369 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_lees_edwards_vel_interpol_sweep
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<InterpolateAndShiftAtBoundary<_VectorField, FloatType> > walberla::LBWalberlaImpl< FloatType, Architecture >::m_lees_edwards_vel_interpol_sweep protected
Definition at line 371 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_mpi_cart_comm_observer
template<typename FloatType , lbmpy::Arch Architecture> ResourceObserver walberla::LBWalberlaImpl< FloatType, Architecture >::m_mpi_cart_comm_observer protected
Definition at line 355 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_full(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_laf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_pdf(), and walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_vel().
m_pdf_communicator
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<RegularFullCommunicator> walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_communicator protected
Definition at line 350 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_pdf(), and walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
m_pdf_field_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_field_id protected
Definition at line 300 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_densities_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_writers(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator().
m_pdf_streaming_communicator
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<PDFStreamingCommunicator> walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_streaming_communicator protected
Definition at line 353 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::setup_streaming_communicator().
m_pdf_tmp_field_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_pdf_tmp_field_id protected
Definition at line 301 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_pending_ghost_comm
template<typename FloatType , lbmpy::Arch Architecture> std::bitset<GhostComm::SIZE> walberla::LBWalberlaImpl< FloatType, Architecture >::m_pending_ghost_comm protected
Definition at line 354 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::clear_boundaries(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_density_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocity_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_full(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_laf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_pdf(), walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_vel(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape().
m_reset_force
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<ResetForce<PdfField, VectorField> > walberla::LBWalberlaImpl< FloatType, Architecture >::m_reset_force protected
Definition at line 361 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_external_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_external_force().
m_seed
template<typename FloatType , lbmpy::Arch Architecture> unsigned int walberla::LBWalberlaImpl< FloatType, Architecture >::m_seed protected
Definition at line 295 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_seed(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_update_velocities_from_pdf
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<UpdateVelFromPDF> walberla::LBWalberlaImpl< FloatType, Architecture >::m_update_velocities_from_pdf protected
Definition at line 364 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
m_vel_communicator
template<typename FloatType , lbmpy::Arch Architecture> std::shared_ptr<RegularFullCommunicator> walberla::LBWalberlaImpl< FloatType, Architecture >::m_vel_communicator protected
Definition at line 351 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::ghost_communication_vel(), and walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
m_vel_tmp_field_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_vel_tmp_field_id protected
Definition at line 308 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model().
m_velocity_field_id
template<typename FloatType , lbmpy::Arch Architecture> BlockDataID walberla::LBWalberlaImpl< FloatType, Architecture >::m_velocity_field_id protected
Definition at line 307 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocities_at_pos(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocity_field_id(), walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::register_vtk_field_writers(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_collision_model(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity().
m_viscosity
template<typename FloatType , lbmpy::Arch Architecture> FloatType walberla::LBWalberlaImpl< FloatType, Architecture >::m_viscosity protected
Definition at line 292 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_viscosity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_viscosity().
m_zc_to_lb
template<typename FloatType , lbmpy::Arch Architecture> double walberla::LBWalberlaImpl< FloatType, Architecture >::m_zc_to_lb protected
Definition at line 297 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel(), and walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_lb_in_place().
m_zc_to_md
template<typename FloatType , lbmpy::Arch Architecture> double walberla::LBWalberlaImpl< FloatType, Architecture >::m_zc_to_md protected
Definition at line 296 of file LBWalberlaImpl.hpp.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::zero_centered_to_md_in_place().
The documentation for this class was generated from the following file:
LBWalberlaImpl.hpp