ESPResSo: walberla::pystencils::PackInfoVecDoublePrecisionCUDA Class Reference
walberla::pystencils::PackInfoVecDoublePrecisionCUDA Class Reference
#include <PackInfoVecDoublePrecisionCUDA.h>
Public Member Functions
PackInfoVecDoublePrecisionCUDA (BlockDataID fieldID_)
~PackInfoVecDoublePrecisionCUDA () override=default
void pack (stencil::Direction dir, unsigned char *buffer, IBlock *block, gpuStream_t stream) override
void communicateLocal (stencil::Direction, const IBlock *, IBlock *, gpuStream_t) override
void unpack (stencil::Direction dir, unsigned char *buffer, IBlock *block, gpuStream_t stream) override
uint_t size (stencil::Direction dir, IBlock *block) override
Detailed Description
Definition at line 39 of file PackInfoVecDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
PackInfoVecDoublePrecisionCUDA()
walberla::pystencils::PackInfoVecDoublePrecisionCUDA::PackInfoVecDoublePrecisionCUDA (BlockDataID fieldID_) inline
Definition at line 42 of file PackInfoVecDoublePrecisionCUDA.h.
~PackInfoVecDoublePrecisionCUDA()
walberla::pystencils::PackInfoVecDoublePrecisionCUDA::~PackInfoVecDoublePrecisionCUDA () override default
Member Function Documentation
communicateLocal()
void walberla::pystencils::PackInfoVecDoublePrecisionCUDA::communicateLocal (stencil::Direction , const IBlock * , IBlock * , gpuStream_t) inline override
Definition at line 47 of file PackInfoVecDoublePrecisionCUDA.h.
References stream.
pack()
void walberla::pystencils::PackInfoVecDoublePrecisionCUDA::pack (stencil::Direction dir, unsigned char * buffer, IBlock * block, gpuStream_t stream) override
Definition at line 103 of file PackInfoVecDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
size()
uint_t walberla::pystencils::PackInfoVecDoublePrecisionCUDA::size (stencil::Direction dir, IBlock * block) override
Definition at line 212 of file PackInfoVecDoublePrecisionCUDA.cu.
References block(), and stream.
unpack()
void walberla::pystencils::PackInfoVecDoublePrecisionCUDA::unpack (stencil::Direction dir, unsigned char * buffer, IBlock * block, gpuStream_t stream) override
Definition at line 157 of file PackInfoVecDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
The documentation for this class was generated from the following files:
PackInfoVecDoublePrecisionCUDA.h
PackInfoVecDoublePrecisionCUDA.cu