ESPResSo: Accumulators::AutoUpdateAccumulators Class Reference
Accumulators::AutoUpdateAccumulators Class Reference
#include <AutoUpdateAccumulators.hpp>
Public Member Functions
void operator() (boost::mpi::communicator const &comm, int steps)
Update accumulators.
int next_update () const
bool contains (AccumulatorBase const *) const
void add (AccumulatorBase *)
void remove (AccumulatorBase *)
Public Member Functions inherited from System::Leaf< AutoUpdateAccumulators >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< AutoUpdateAccumulators >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< AutoUpdateAccumulators >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 30 of file core/accumulators/AutoUpdateAccumulators.hpp.
Member Function Documentation
add()
void Accumulators::AutoUpdateAccumulators::add (AccumulatorBase * acc)
Definition at line 63 of file AutoUpdateAccumulators.cpp.
References contains(), System::Leaf< AutoUpdateAccumulators >::get_system(), Accumulators::AccumulatorBase::has_same_system_handle(), and Accumulators::AccumulatorBase::override_system_handle().
contains()
bool Accumulators::AutoUpdateAccumulators::contains (AccumulatorBase const * acc) const
Definition at line 79 of file AutoUpdateAccumulators.cpp.
Referenced by add(), and remove().
next_update()
int Accumulators::AutoUpdateAccumulators::next_update () const
Definition at line 46 of file AutoUpdateAccumulators.cpp.
operator()()
void Accumulators::AutoUpdateAccumulators::operator() (boost::mpi::communicator const & comm, int steps)
Update accumulators.
Checks for all auto update accumulators if they need to be updated and if so does.
Definition at line 32 of file AutoUpdateAccumulators.cpp.
remove()
void Accumulators::AutoUpdateAccumulators::remove (AccumulatorBase * acc)
Definition at line 74 of file AutoUpdateAccumulators.cpp.
References contains().
The documentation for this class was generated from the following files:
core/accumulators/AutoUpdateAccumulators.hpp
AutoUpdateAccumulators.cpp