ESPResSo: walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA Class Reference
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA Class Reference
#include <StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h>
Public Member Functions
StreamCollideSweepLeesEdwardsDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, double omega_bulk, double omega_even, double omega_odd, double omega_shear, double v_s)
~StreamCollideSweepLeesEdwardsDoublePrecisionCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
int64_t getLebc_bot_index () const
int64_t getLebc_top_index () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
double getV_s () const
void setLebc_bot_index (const int64_t value)
void setLebc_top_index (const int64_t value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepLeesEdwardsDoublePrecisionCUDA()
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, double omega_bulk, double omega_even, double omega_odd, double omega_shear, double v_s) inline
Definition at line 57 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
~StreamCollideSweepLeesEdwardsDoublePrecisionCUDA()
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::~StreamCollideSweepLeesEdwardsDoublePrecisionCUDA () inline
Definition at line 66 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 116 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getLebc_bot_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getLebc_bot_index () const inline
Definition at line 119 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getLebc_top_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getLebc_top_index () const inline
Definition at line 120 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getOmega_bulk () const inline
Definition at line 121 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getOmega_even () const inline
Definition at line 122 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getOmega_odd () const inline
Definition at line 123 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getOmega_shear () const inline
Definition at line 124 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionCUDA > & kernel) inline static
Definition at line 84 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 101 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 89 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 106 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
References runOnCellInterval(), and stream.
getV_s()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::getV_s () const inline
Definition at line 125 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 79 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 298 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 355 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setLebc_bot_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setLebc_bot_index (const int64_t value) inline
Definition at line 126 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
setLebc_top_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setLebc_top_index (const int64_t value) inline
Definition at line 129 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setOmega_bulk (const double value) inline
Definition at line 132 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setOmega_even (const double value) inline
Definition at line 133 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setOmega_odd (const double value) inline
Definition at line 134 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setOmega_shear (const double value) inline
Definition at line 135 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
setV_s()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionCUDA::setV_s (const double value) inline
Definition at line 136 of file StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.h
StreamCollideSweepLeesEdwardsDoublePrecisionCUDA.cu