ESPResSo: walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture > Class Template Reference
walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture > Class Template Reference
Class that runs and controls the EK on waLBerla.
#include <EKinWalberlaImpl.hpp>
Classes
class DensityVTKWriter
struct FieldTrait
class FluxVTKWriter
struct GhostComm
class VTKWriter
Public Types
using Stencil = stencil::D3Q27
Stencil for collision and streaming operations.
using BlockStorage = LatticeWalberla::Lattice_T
Lattice model (e.g.
using FluxField = typename FieldTrait< FloatType, Architecture >::FluxField
using DensityField = typename FieldTrait< FloatType, Architecture >::DensityField
Public Types inherited from LatticeModel
using units_map = std::unordered_map< std::string, double >
Public Member Functions
template<typename T >
FloatType FloatType_c (T t)
std::size_t stencil_size () const noexcept override
bool is_double_precision () const noexcept override
EKinWalberlaImpl (std::shared_ptr< LatticeWalberla > lattice, double diffusion, double kT, double valency, Utils::Vector3d const &ext_efield, double density, bool advection, bool friction_coupling, bool thermalized, unsigned int seed)
double get_diffusion () const noexcept override
double get_kT () const noexcept override
double get_valency () const noexcept override
bool get_advection () const noexcept override
bool get_friction_coupling () const noexcept override
Utils::Vector3d get_ext_efield () const noexcept override
bool is_thermalized () const noexcept override
unsigned int get_seed () const noexcept override
std::optional< uint64_t > get_rng_state () const override
void set_diffusion (double diffusion) override
void set_kT (double kT) override
void set_valency (double valency) override
void set_advection (bool advection) override
void set_friction_coupling (bool friction_coupling) override
void set_rng_state (uint64_t counter) override
void set_ext_efield (Utils::Vector3d const &field) override
void ghost_communication () override
void ghost_communication_boundary ()
void integrate (std::size_t potential_id, std::size_t velocity_id, std::size_t force_id, double lb_density) override
std::size_t get_density_id () const noexcept override
bool set_node_density (Utils::Vector3i const &node, double density) override
std::optional< double > get_node_density (Utils::Vector3i const &node, bool consider_ghosts=false) const override
std::vector< double > get_slice_density (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_density (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &density) override
std::optional< Utils::Vector3d > get_node_flux_vector (Utils::Vector3i const &node, bool consider_ghosts=false) const override
std::vector< double > get_slice_flux_vector (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void clear_flux_boundaries () override
void clear_density_boundaries () override
bool set_node_flux_boundary (Utils::Vector3i const &node, Utils::Vector3d const &flux) override
std::optional< Utils::Vector3d > get_node_flux_at_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const override
bool remove_node_from_flux_boundary (Utils::Vector3i const &node) override
bool set_node_density_boundary (Utils::Vector3i const &node, double density) override
std::optional< double > get_node_density_at_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const override
void set_slice_density_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< std::optional< double > > const &density) override
std::vector< std::optional< double > > get_slice_density_at_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
void set_slice_flux_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< std::optional< Utils::Vector3d > > const &flux) override
std::vector< std::optional< Utils::Vector3d > > get_slice_flux_at_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
std::vector< bool > get_slice_is_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
bool remove_node_from_density_boundary (Utils::Vector3i const &node) override
std::optional< bool > get_node_is_flux_boundary (Utils::Vector3i const &node, bool consider_ghosts) const override
std::optional< bool > get_node_is_density_boundary (Utils::Vector3i const &node, bool consider_ghosts) const override
std::optional< bool > get_node_is_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const override
void update_flux_boundary_from_shape (const std::vector< int > &raster_flat, const std::vector< double > &data_flat) override
void update_density_boundary_from_shape (const std::vector< int > &raster_flat, const std::vector< double > &data_flat) override
void reallocate_flux_boundary_field ()
void reallocate_density_boundary_field ()
LatticeWalberla const & get_lattice () const noexcept override
bool is_gpu () const noexcept override
void register_vtk_field_filters (walberla::vtk::VTKOutput &vtk_obj) override
void register_vtk_field_writers (walberla::vtk::VTKOutput &vtk_obj, LatticeModel::units_map const &units, int flag_observables) override
~EKinWalberlaImpl () override=default
Public Member Functions inherited from EKinWalberlaBase
~EKinWalberlaBase () override=default
Public Member Functions inherited from LatticeModel
virtual ~LatticeModel ()=default
std::shared_ptr< VTKHandle > create_vtk (int delta_N, int initial_count, int flag_observables, units_map const &units_conversion, std::string const &identifier, std::string const &base_folder, std::string const &prefix, bool force_pvtu)
Create a VTK observable.
void write_vtk (std::string const &vtk_uid)
Write a VTK observable to disk.
void switch_vtk (std::string const &vtk_uid, bool status)
Toggle a VTK observable on/off.
Protected Types
using FlagField = walberla::FlagField< walberla::uint8_t >
using _FluxField = typename FieldTrait< FloatType >::FluxField
using _DensityField = typename FieldTrait< FloatType >::DensityField
using FullCommunicator = typename FieldTrait< FloatType, Architecture >::template RegularCommScheme< typename stencil::D3Q27 >
using BoundaryFullCommunicator = typename FieldTrait< FloatType, Architecture >::template BoundaryCommScheme< typename stencil::D3Q27 >
template<class Field >
using PackInfo = typename FieldTrait< FloatType, Architecture >::template PackInfo< Field >
Protected Member Functions
template<typename Field >
auto add_to_storage (std::string const tag, FloatType value)
Convenience function to add a field with a custom allocator.
void reset_density_boundary_handling (std::shared_ptr< BlockStorage > const &blocks)
void reset_flux_boundary_handling (std::shared_ptr< BlockStorage > const &blocks)
void integrate_vtk_writers () override
Protected Attributes
BlockDataID m_density_field_id
BlockDataID m_flux_field_id
BlockDataID m_flag_field_density_id
BlockDataID m_flag_field_flux_id
FlagUID const Domain_flag {"domain"}
Flag for domain cells, i.e.
FlagUID const Boundary_flag {"boundary"}
Flag for boundary cells.
std::shared_ptr< LatticeWalberla > m_lattice
Block forest.
std::unique_ptr< BoundaryModelDensity > m_boundary_density
std::shared_ptr< BoundaryModelFlux > m_boundary_flux
std::unique_ptr< DiffusiveFluxKernel > m_diffusive_flux
std::unique_ptr< DiffusiveFluxKernelElectrostatic > m_diffusive_flux_electrostatic
std::unique_ptr< ContinuityKernel > m_continuity
std::shared_ptr< FullCommunicator > m_full_communication
std::shared_ptr< BoundaryFullCommunicator > m_boundary_communicator
std::bitset< GhostComm::SIZE > m_pending_ghost_comm
ResourceObserver m_mpi_cart_comm_observer
Protected Attributes inherited from LatticeModel
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_auto
VTK writers that are executed automatically.
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_manual
VTK writers that are executed manually.
Detailed Description
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU>
class walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >
Class that runs and controls the EK on waLBerla.
Definition at line 71 of file EKinWalberlaImpl.hpp.
Member Typedef Documentation
_DensityField
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::_DensityField = typename FieldTrait<FloatType>::DensityField protected
Definition at line 169 of file EKinWalberlaImpl.hpp.
_FluxField
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::_FluxField = typename FieldTrait<FloatType>::FluxField protected
Definition at line 168 of file EKinWalberlaImpl.hpp.
BlockStorage
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::BlockStorage = LatticeWalberla::Lattice_T
Lattice model (e.g.
blockforest).
Definition at line 112 of file EKinWalberlaImpl.hpp.
BoundaryFullCommunicator
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::BoundaryFullCommunicator = typename FieldTrait<FloatType, Architecture>::template BoundaryCommScheme< typename stencil::D3Q27> protected
Definition at line 299 of file EKinWalberlaImpl.hpp.
DensityField
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::DensityField = typename FieldTrait<FloatType, Architecture>::DensityField
Definition at line 173 of file EKinWalberlaImpl.hpp.
FlagField
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FlagField = walberla::FlagField<walberla::uint8_t> protected
Definition at line 128 of file EKinWalberlaImpl.hpp.
FluxField
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FluxField = typename FieldTrait<FloatType, Architecture>::FluxField
Definition at line 172 of file EKinWalberlaImpl.hpp.
FullCommunicator
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FullCommunicator = typename FieldTrait<FloatType, Architecture>::template RegularCommScheme< typename stencil::D3Q27> protected
Definition at line 296 of file EKinWalberlaImpl.hpp.
PackInfo
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> template<class Field > using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::PackInfo = typename FieldTrait<FloatType, Architecture>::template PackInfo<Field> protected
Definition at line 307 of file EKinWalberlaImpl.hpp.
Stencil
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> using walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::Stencil = stencil::D3Q27
Stencil for collision and streaming operations.
Definition at line 110 of file EKinWalberlaImpl.hpp.
Constructor & Destructor Documentation
EKinWalberlaImpl()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl (std::shared_ptr< LatticeWalberla > lattice, double diffusion, double kT, double valency, Utils::Vector3d const & ext_efield, double density, bool advection, bool friction_coupling, bool thermalized, unsigned int seed) inline
Definition at line 311 of file EKinWalberlaImpl.hpp.
References density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_communicator, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_continuity, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_density_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_flux_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flux_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_full_communication, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling(), walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::setup_boundary_handle(), and stream.
~EKinWalberlaImpl()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::~EKinWalberlaImpl () override default
Member Function Documentation
add_to_storage()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> template<typename Field > auto walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::add_to_storage (std::string const tag, FloatType value) inline protected
Convenience function to add a field with a custom allocator.
When vectorization is off, let waLBerla decide which memory allocator to use. When vectorization is on, the aligned memory allocator is required, otherwise cpu_vectorize_info["assume_aligned"] will trigger assertions. That is because for single-precision kernels the waLBerla heuristic in src/field/allocation/FieldAllocator.h will fall back to StdFieldAlloc, yet AllocateAligned is needed for intrinsics to work.
Definition at line 252 of file EKinWalberlaImpl.hpp.
References block(), lbmpy::CPU, walberla::ek::accessor::Scalar::initialize(), walberla::ek::accessor::Flux::initialize(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice, and stream.
clear_density_boundaries()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_density_boundaries () inline override virtual
Implements EKinWalberlaBase.
Definition at line 826 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling().
clear_flux_boundaries()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_flux_boundaries () inline override virtual
Implements EKinWalberlaBase.
Definition at line 821 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling().
FloatType_c()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> template<typename T > FloatType walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c (T t) inline
Definition at line 181 of file EKinWalberlaImpl.hpp.
References stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_writers(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_diffusion(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_ext_efield(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_kT(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density_boundary(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_valency().
get_advection()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_advection () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 377 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate().
get_density_id()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::size_t walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_density_id () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 668 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id.
get_diffusion()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> double walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_diffusion () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 370 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate().
get_ext_efield()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> Utils::Vector3d walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_ext_efield () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 383 of file EKinWalberlaImpl.hpp.
get_friction_coupling()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_friction_coupling () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 380 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate().
get_kT()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> double walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_kT () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 373 of file EKinWalberlaImpl.hpp.
get_lattice()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> LatticeWalberla const & walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice () const inline override virtual noexcept
Implements LatticeModel.
Definition at line 1097 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_density_boundaries(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_flux_boundaries(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_density_boundary_from_shape(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape().
get_node_density()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< double > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 686 of file EKinWalberlaImpl.hpp.
References walberla::ek::accessor::Scalar::get(), walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, and stream.
get_node_density_at_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< double > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density_at_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 876 of file EKinWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, and stream.
get_node_flux_at_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< Utils::Vector3d > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_at_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 843 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, stream, and walberla::to_vector3d().
get_node_flux_vector()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< Utils::Vector3d > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_vector (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 762 of file EKinWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::ek::accessor::Flux::get_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flux_field_id, stream, and walberla::to_vector3d().
get_node_is_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< bool > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 1061 of file EKinWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, and stream.
get_node_is_density_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< bool > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_density_boundary (Utils::Vector3i const & node, bool consider_ghosts) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 1051 of file EKinWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, and stream.
get_node_is_flux_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< bool > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_flux_boundary (Utils::Vector3i const & node, bool consider_ghosts) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 1040 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
get_rng_state()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::optional< uint64_t > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_rng_state () const inline override virtual
Implements EKinWalberlaBase.
Definition at line 393 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux, and stream.
get_seed()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> unsigned int walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_seed () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 390 of file EKinWalberlaImpl.hpp.
get_slice_density()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::vector< double > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 699 of file EKinWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::ek::accessor::Scalar::get(), LatticeWalberla::get_block_corner(), walberla::get_block_interval(), LatticeWalberla::get_blocks(), walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, and stream.
get_slice_density_at_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::vector< std::optional< double > > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density_at_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 915 of file EKinWalberlaImpl.hpp.
References walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), LatticeWalberla::get_local_grid_range(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, and stream.
get_slice_flux_at_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::vector< std::optional< Utils::Vector3d > > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_at_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 975 of file EKinWalberlaImpl.hpp.
References walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), LatticeWalberla::get_local_grid_range(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, stream, and walberla::to_vector3d().
get_slice_flux_vector()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::vector< double > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 775 of file EKinWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), LatticeWalberla::get_block_corner(), walberla::get_block_interval(), LatticeWalberla::get_blocks(), walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::ek::accessor::Flux::get_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flux_field_id, and stream.
get_slice_is_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::vector< bool > walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_is_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements EKinWalberlaBase.
Definition at line 1005 of file EKinWalberlaImpl.hpp.
References walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), LatticeWalberla::get_local_grid_range(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, and stream.
get_valency()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> double walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_valency () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 374 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate().
ghost_communication()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication () inline override virtual
Implements EKinWalberlaBase.
Definition at line 458 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::DENS, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication_boundary(), ResourceObserver::is_valid(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
ghost_communication_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication_boundary () inline
Definition at line 467 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, ResourceObserver::is_valid(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_communicator, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication().
integrate()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate (std::size_t potential_id, std::size_t velocity_id, std::size_t force_id, double lb_density) inline override virtual
Implements EKinWalberlaBase.
Definition at line 615 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::DENS, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_advection(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_diffusion(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_friction_coupling(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_valency(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate_vtk_writers(), ResourceObserver::is_valid(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_mpi_cart_comm_observer, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
integrate_vtk_writers()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate_vtk_writers () inline override protected virtual
Implements LatticeModel.
Definition at line 604 of file EKinWalberlaImpl.hpp.
References LatticeModel::m_vtk_auto, and stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate().
is_double_precision()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::is_double_precision () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 189 of file EKinWalberlaImpl.hpp.
is_gpu()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::is_gpu () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 1101 of file EKinWalberlaImpl.hpp.
References lbmpy::GPU, and stream.
is_thermalized()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::is_thermalized () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 386 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux.
reallocate_density_boundary_field()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reallocate_density_boundary_field () inline
Definition at line 1093 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_density_boundary_from_shape().
reallocate_flux_boundary_field()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reallocate_flux_boundary_field () inline
Definition at line 1091 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape().
register_vtk_field_filters()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_filters (walberla::vtk::VTKOutput & vtk_obj) inline override virtual
Implements LatticeModel.
Definition at line 1105 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::Boundary_flag, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_density_id, and stream.
register_vtk_field_writers()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_writers (walberla::vtk::VTKOutput & vtk_obj, LatticeModel::units_map const & units, int flag_observables) inline override virtual
Implements LatticeModel.
Definition at line 1203 of file EKinWalberlaImpl.hpp.
References density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), flux, lbmpy::GPU, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flux_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice, and stream.
remove_node_from_density_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_density_boundary (Utils::Vector3i const & node) inline override virtual
Implements EKinWalberlaBase.
Definition at line 1029 of file EKinWalberlaImpl.hpp.
References walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, and stream.
remove_node_from_flux_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_flux_boundary (Utils::Vector3i const & node) inline override virtual
Implements EKinWalberlaBase.
Definition at line 853 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
reset_density_boundary_handling()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling (std::shared_ptr< BlockStorage > const & blocks) inline protected
Definition at line 281 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_density_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice, stream, and walberla::to_cell().
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_density_boundaries(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl().
reset_flux_boundary_handling()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling (std::shared_ptr< BlockStorage > const & blocks) inline protected
Definition at line 289 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_flux_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flux_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice, stream, and walberla::to_cell().
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_flux_boundaries(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl().
set_advection()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_advection (bool advection) inline override virtual
Implements EKinWalberlaBase.
Definition at line 424 of file EKinWalberlaImpl.hpp.
References stream.
set_diffusion()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_diffusion (double diffusion) inline override virtual
Implements EKinWalberlaBase.
Definition at line 402 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux_electrostatic, and stream.
set_ext_efield()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_ext_efield (Utils::Vector3d const & field) inline override virtual
Implements EKinWalberlaBase.
Definition at line 446 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux_electrostatic.
set_friction_coupling()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_friction_coupling (bool friction_coupling) inline override virtual
Implements EKinWalberlaBase.
Definition at line 426 of file EKinWalberlaImpl.hpp.
References stream.
set_kT()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_kT (double kT) inline override virtual
Implements EKinWalberlaBase.
Definition at line 411 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux_electrostatic.
set_node_density()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density (Utils::Vector3i const & node, double density) inline override virtual
Implements EKinWalberlaBase.
Definition at line 673 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::DENS, density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, walberla::ek::accessor::Scalar::set(), and stream.
set_node_density_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density_boundary (Utils::Vector3i const & node, double density) inline override virtual
Implements EKinWalberlaBase.
Definition at line 863 of file EKinWalberlaImpl.hpp.
References density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, and stream.
set_node_flux_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> bool walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_flux_boundary (Utils::Vector3i const & node, Utils::Vector3d const & flux) inline override virtual
Implements EKinWalberlaBase.
Definition at line 830 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, flux, walberla::get_block_and_cell(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
set_rng_state()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_rng_state (uint64_t counter) inline override virtual
Implements EKinWalberlaBase.
Definition at line 430 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux_electrostatic, and stream.
set_slice_density()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & density) inline override virtual
Implements EKinWalberlaBase.
Definition at line 733 of file EKinWalberlaImpl.hpp.
References block(), walberla::copy_block_buffer(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::DENS, density, LatticeWalberla::get_block_corner(), walberla::get_block_interval(), LatticeWalberla::get_blocks(), walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, walberla::ek::accessor::Scalar::set(), and stream.
set_slice_density_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< std::optional< double > > const & density) inline override virtual
Implements EKinWalberlaBase.
Definition at line 885 of file EKinWalberlaImpl.hpp.
References density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), walberla::get_block_and_cell(), walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), LatticeWalberla::get_local_grid_range(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, and stream.
set_slice_flux_boundary()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_flux_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< std::optional< Utils::Vector3d > > const & flux) inline override virtual
Implements EKinWalberlaBase.
Definition at line 944 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, flux, walberla::get_block_and_cell(), walberla::get_interval(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), LatticeWalberla::get_local_grid_range(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, and stream.
set_valency()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_valency (double valency) inline override virtual
Implements EKinWalberlaBase.
Definition at line 417 of file EKinWalberlaImpl.hpp.
References walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FloatType_c(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux_electrostatic, and stream.
stencil_size()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::size_t walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::stencil_size () const inline override virtual noexcept
Implements EKinWalberlaBase.
Definition at line 185 of file EKinWalberlaImpl.hpp.
References stream.
update_density_boundary_from_shape()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_density_boundary_from_shape (const std::vector< int > & raster_flat, const std::vector< double > & data_flat) inline override virtual
Implements EKinWalberlaBase.
Definition at line 1081 of file EKinWalberlaImpl.hpp.
References walberla::fill_3D_scalar_array(), LatticeWalberla::get_grid_dimensions(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reallocate_density_boundary_field(), walberla::set_boundary_from_grid(), and stream.
update_flux_boundary_from_shape()
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape (const std::vector< int > & raster_flat, const std::vector< double > & data_flat) inline override virtual
Implements EKinWalberlaBase.
Definition at line 1071 of file EKinWalberlaImpl.hpp.
References walberla::fill_3D_vector_array(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::GhostComm::FLB, LatticeWalberla::get_grid_dimensions(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reallocate_flux_boundary_field(), walberla::set_boundary_from_grid(), and stream.
Member Data Documentation
Boundary_flag
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> FlagUID const walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::Boundary_flag {"boundary"} protected
Flag for boundary cells.
Definition at line 219 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_filters().
Domain_flag
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> FlagUID const walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::Domain_flag {"domain"} protected
Flag for domain cells, i.e.
all cells.
Definition at line 217 of file EKinWalberlaImpl.hpp.
m_boundary_communicator
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::shared_ptr<BoundaryFullCommunicator> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_communicator protected
Definition at line 303 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication_boundary().
m_boundary_density
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::unique_ptr<BoundaryModelDensity> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_density protected
Definition at line 224 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reallocate_density_boundary_field(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density_boundary(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_density_boundary_from_shape().
m_boundary_flux
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::shared_ptr<BoundaryModelFlux> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_boundary_flux protected
Definition at line 225 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reallocate_flux_boundary_field(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_flux_boundary(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape().
m_continuity
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::unique_ptr<ContinuityKernel> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_continuity protected
Definition at line 230 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl().
m_density_field_id
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> BlockDataID walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_density_field_id protected
Definition at line 204 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_density_id(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_writers(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density().
m_diffusive_flux
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::unique_ptr<DiffusiveFluxKernel> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux protected
Definition at line 227 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_rng_state(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::is_thermalized(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_diffusion(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_rng_state().
m_diffusive_flux_electrostatic
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::unique_ptr<DiffusiveFluxKernelElectrostatic> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_diffusive_flux_electrostatic protected
Definition at line 229 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_diffusion(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_ext_efield(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_kT(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_rng_state(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_valency().
m_flag_field_density_id
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> BlockDataID walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_density_id protected
Definition at line 208 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_filters(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling().
m_flag_field_flux_id
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> BlockDataID walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flag_field_flux_id protected
Definition at line 209 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling().
m_flux_field_id
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> BlockDataID walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_flux_field_id protected
Definition at line 206 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_writers(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling().
m_full_communication
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::shared_ptr<FullCommunicator> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_full_communication protected
Definition at line 302 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl().
m_lattice
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::shared_ptr<LatticeWalberla> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_lattice protected
Block forest.
Definition at line 222 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::add_to_storage(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_lattice(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::register_vtk_field_writers(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling().
m_mpi_cart_comm_observer
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> ResourceObserver walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_mpi_cart_comm_observer protected
Definition at line 305 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication_boundary(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate().
m_pending_ghost_comm
template<std::size_t FluxCount = 13, typename FloatType = double, lbmpy::Arch Architecture = lbmpy::Arch::CPU> std::bitset<GhostComm::SIZE> walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::m_pending_ghost_comm protected
Definition at line 304 of file EKinWalberlaImpl.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::clear_flux_boundaries(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::ghost_communication_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_flux_boundary(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape().
The documentation for this class was generated from the following file:
EKinWalberlaImpl.hpp