ESPResSo: walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision Class Reference
walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision Class Reference
#include <DiffusiveFluxKernelWithElectrostatic_double_precision.h>
Public Member Functions
DiffusiveFluxKernelWithElectrostatic_double_precision (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, double kT, double z)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getD () const
double getF_ext_0 () const
double getF_ext_1 () const
double getF_ext_2 () const
double getKt () const
double getZ () const
void setD (const double value)
void setF_ext_0 (const double value)
void setF_ext_1 (const double value)
void setF_ext_2 (const double value)
void setKt (const double value)
void setZ (const double value)
void setPhiID (BlockDataID phiID_)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelWithElectrostatic_double_precision()
walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::DiffusiveFluxKernelWithElectrostatic_double_precision (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, double kT, double z) inline
Definition at line 55 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 98 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getD()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getD () const inline
Definition at line 101 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getF_ext_0()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getF_ext_0 () const inline
Definition at line 102 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getF_ext_1()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getF_ext_1 () const inline
Definition at line 103 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getF_ext_2()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getF_ext_2 () const inline
Definition at line 104 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getKt()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getKt () const inline
Definition at line 105 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getSweep () inline
Definition at line 85 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision > & kernel) inline static
Definition at line 69 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 75 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 90 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
References runOnCellInterval(), and stream.
getZ()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::getZ () const inline
Definition at line 106 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::operator() (IBlock * block) inline
Definition at line 67 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::run (IBlock * block)
Definition at line 98 of file DiffusiveFluxKernelWithElectrostatic_double_precision.cpp.
References block(), walberla::pystencils::internal_32fac7f834b08f4a768ccef85dadf7a1::diffusivefluxkernelwithelectrostatic_double_precision_diffusivefluxkernelwithelectrostatic_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 135 of file DiffusiveFluxKernelWithElectrostatic_double_precision.cpp.
References block(), walberla::pystencils::internal_32fac7f834b08f4a768ccef85dadf7a1::diffusivefluxkernelwithelectrostatic_double_precision_diffusivefluxkernelwithelectrostatic_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setD()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setD (const double value) inline
Definition at line 107 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
setF_ext_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setF_ext_0 (const double value) inline
Definition at line 108 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
setF_ext_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setF_ext_1 (const double value) inline
Definition at line 109 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
setF_ext_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setF_ext_2 (const double value) inline
Definition at line 110 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
setKt()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setKt (const double value) inline
Definition at line 111 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
setPhiID()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setPhiID (BlockDataID phiID_) inline
Definition at line 119 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
References stream.
setZ()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision::setZ (const double value) inline
Definition at line 112 of file DiffusiveFluxKernelWithElectrostatic_double_precision.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelWithElectrostatic_double_precision.h
DiffusiveFluxKernelWithElectrostatic_double_precision.cpp