ESPResSo: ScriptInterface::Coulomb::CoulombP3MGPU Class Reference
ScriptInterface::Coulomb::CoulombP3MGPU Class Reference
#include <CoulombP3MGPU.hpp>
Public Member Functions
CoulombP3MGPU ()
void do_construct (VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >
Actor ()
Variant do_call_method (std::string const &name, VariantMap const &params) override
std::shared_ptr< CoreActorClass > actor ()
std::shared_ptr< CoreActorClass const > actor () const
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >
using SIActorClass = CoulombP3MGPU
using CoreActorClass = ::CoulombP3MGPU
using ObjectClass = Actor< CoulombP3MGPU, ::CoulombP3MGPU >
Protected Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >
void on_bind_system (::System::System &) override
void set_charge_neutrality_tolerance (VariantMap const &params)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes inherited from ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >
std::shared_ptr< CoreActorClass > m_actor
Detailed Description
Definition at line 39 of file CoulombP3MGPU.hpp.
Constructor & Destructor Documentation
CoulombP3MGPU()
ScriptInterface::Coulomb::CoulombP3MGPU::CoulombP3MGPU () inline
Definition at line 43 of file CoulombP3MGPU.hpp.
References ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >::actor(), ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_construct()
void ScriptInterface::Coulomb::CoulombP3MGPU::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 77 of file CoulombP3MGPU.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >::m_actor, ScriptInterface::Context::parallel_try_catch(), params, and ScriptInterface::Coulomb::Actor< CoulombP3MGPU, ::CoulombP3MGPU >::set_charge_neutrality_tolerance().
The documentation for this class was generated from the following file:
CoulombP3MGPU.hpp