ESPResSo: VerletCriterion< CutoffGetter > Class Template Reference
VerletCriterion< CutoffGetter > Class Template Reference
Returns true if the particles are to be considered for short range interactions.
#include <VerletCriterion.hpp>
Public Member Functions
VerletCriterion (System::System const &system, double skin, double max_cut, double coulomb_cut=0., double dipolar_cut=0., double collision_detection_cutoff=0.)
template<typename Distance >
bool operator() (const Particle &p1, const Particle &p2, Distance const &dist) const
Detailed Description
template<typename CutoffGetter = GetNonbondedCutoff>
class VerletCriterion< CutoffGetter >
Returns true if the particles are to be considered for short range interactions.
Definition at line 45 of file VerletCriterion.hpp.
Constructor & Destructor Documentation
VerletCriterion()
template<typename CutoffGetter = GetNonbondedCutoff> VerletCriterion< CutoffGetter >::VerletCriterion (System::System const & system, double skin, double max_cut, double coulomb_cut = 0., double dipolar_cut = 0., double collision_detection_cutoff = 0.) inline
Definition at line 59 of file VerletCriterion.hpp.
Member Function Documentation
operator()()
template<typename CutoffGetter = GetNonbondedCutoff> template<typename Distance > bool VerletCriterion< CutoffGetter >::operator() (const Particle & p1, const Particle & p2, Distance const & dist) const inline
Definition at line 69 of file VerletCriterion.hpp.
References Particle::dipm(), Distance::dist2, INACTIVE_CUTOFF, Particle::q(), Utils::sqr(), and Particle::type().
The documentation for this class was generated from the following file:
VerletCriterion.hpp