ESPResSo: Observables::ParticleDipoleFields Class Reference
Observables::ParticleDipoleFields Class Reference
Extract particle dipole fields.
#include <ParticleDipoleFields.hpp>
Public Member Functions
std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, const ParticleObservables::traits< Particle > &traits) const override
Public Member Functions inherited from Observables::ParticleObservable< ParticleObservables::DipoleFields >
std::vector< std::size_t > shape () const override
std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, ParticleObservables::traits< Particle > const &traits) const override
PidObservable (std::vector< int > ids)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > const & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Detailed Description
Extract particle dipole fields.
For \(n\) particles, return \(3 n\) dipole fields ordered as \((h_d1_x, h_d1_y, h_d1_z, \dots, h_dn_x, h_dn_y, h_dn_z)\).
Definition at line 35 of file ParticleDipoleFields.hpp.
Member Function Documentation
evaluate()
std::vector<double> Observables::ParticleDipoleFields::evaluate (boost::mpi::communicator const & comm, ParticleReferenceRange const & local_particles, const ParticleObservables::traits< Particle > & traits) const inline override virtual
Implements Observables::PidObservable.
Definition at line 41 of file ParticleDipoleFields.hpp.
References System::System::calculate_long_range_fields(), Observables::ParticleObservable< ObsType >::evaluate(), and System::get_system().
The documentation for this class was generated from the following file:
ParticleDipoleFields.hpp