ESPResSo: walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards Class Reference
walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards Class Reference
#include <CollideSweepDoublePrecisionLeesEdwards.h>
Public Member Functions
CollideSweepDoublePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getGrid_size () const
double getOmega_shear () const
double getV_s () const
void setGrid_size (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepDoublePrecisionLeesEdwards > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionLeesEdwards > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepDoublePrecisionLeesEdwards.h.
Constructor & Destructor Documentation
CollideSweepDoublePrecisionLeesEdwards()
walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::CollideSweepDoublePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s) inline
Definition at line 57 of file CollideSweepDoublePrecisionLeesEdwards.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 98 of file CollideSweepDoublePrecisionLeesEdwards.h.
getGrid_size()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getGrid_size () const inline
Definition at line 101 of file CollideSweepDoublePrecisionLeesEdwards.h.
getOmega_shear()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getOmega_shear () const inline
Definition at line 102 of file CollideSweepDoublePrecisionLeesEdwards.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getSweep () inline
Definition at line 85 of file CollideSweepDoublePrecisionLeesEdwards.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getSweep (const shared_ptr< CollideSweepDoublePrecisionLeesEdwards > & kernel) inline static
Definition at line 72 of file CollideSweepDoublePrecisionLeesEdwards.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionLeesEdwards > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 76 of file CollideSweepDoublePrecisionLeesEdwards.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 90 of file CollideSweepDoublePrecisionLeesEdwards.h.
References runOnCellInterval().
getV_s()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::getV_s () const inline
Definition at line 103 of file CollideSweepDoublePrecisionLeesEdwards.h.
operator()()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::operator() (IBlock * block) inline
Definition at line 69 of file CollideSweepDoublePrecisionLeesEdwards.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::run (IBlock * block)
Definition at line 158 of file CollideSweepDoublePrecisionLeesEdwards.cpp.
References block(), walberla::pystencils::internal_607d8a5c7ac58c25acf09ad94bb82cf4::collidesweepdoubleprecisionleesedwards_collidesweepdoubleprecisionleesedwards(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 192 of file CollideSweepDoublePrecisionLeesEdwards.cpp.
References block(), walberla::pystencils::internal_607d8a5c7ac58c25acf09ad94bb82cf4::collidesweepdoubleprecisionleesedwards_collidesweepdoubleprecisionleesedwards(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::setGrid_size (const double value) inline
Definition at line 104 of file CollideSweepDoublePrecisionLeesEdwards.h.
setOmega_shear()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::setOmega_shear (const double value) inline
Definition at line 105 of file CollideSweepDoublePrecisionLeesEdwards.h.
setV_s()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwards::setV_s (const double value) inline
Definition at line 106 of file CollideSweepDoublePrecisionLeesEdwards.h.
The documentation for this class was generated from the following files:
CollideSweepDoublePrecisionLeesEdwards.h
CollideSweepDoublePrecisionLeesEdwards.cpp