ESPResSo: walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision Class Reference
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision Class Reference
#include <StreamCollideSweepLeesEdwardsDoublePrecision.h>
Public Member Functions
StreamCollideSweepLeesEdwardsDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, double omega_bulk, double omega_even, double omega_odd, double omega_shear, double v_s)
~StreamCollideSweepLeesEdwardsDoublePrecision ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
int64_t getLebc_bot_index () const
int64_t getLebc_top_index () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
double getV_s () const
void setLebc_bot_index (const int64_t value)
void setLebc_top_index (const int64_t value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
Constructor & Destructor Documentation
StreamCollideSweepLeesEdwardsDoublePrecision()
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::StreamCollideSweepLeesEdwardsDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, double omega_bulk, double omega_even, double omega_odd, double omega_shear, double v_s) inline
Definition at line 55 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
~StreamCollideSweepLeesEdwardsDoublePrecision()
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::~StreamCollideSweepLeesEdwardsDoublePrecision () inline
Definition at line 64 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 105 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getLebc_bot_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getLebc_bot_index () const inline
Definition at line 108 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getLebc_top_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getLebc_top_index () const inline
Definition at line 109 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getOmega_bulk () const inline
Definition at line 110 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getOmega_even () const inline
Definition at line 111 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getOmega_odd () const inline
Definition at line 112 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getOmega_shear () const inline
Definition at line 113 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getSweep () inline
Definition at line 92 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecision > & kernel) inline static
Definition at line 78 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 83 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 97 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
References runOnCellInterval(), and stream.
getV_s()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::getV_s () const inline
Definition at line 114 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
operator()()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::run (IBlock * block)
Definition at line 307 of file StreamCollideSweepLeesEdwardsDoublePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_1215ae06312aaf63d726636be94fdda3::streamcollidesweepleesedwardsdoubleprecision_streamcollidesweepleesedwardsdoubleprecision().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 362 of file StreamCollideSweepLeesEdwardsDoublePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_1215ae06312aaf63d726636be94fdda3::streamcollidesweepleesedwardsdoubleprecision_streamcollidesweepleesedwardsdoubleprecision().
Referenced by getSweepOnCellInterval().
setLebc_bot_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setLebc_bot_index (const int64_t value) inline
Definition at line 115 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
setLebc_top_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setLebc_top_index (const int64_t value) inline
Definition at line 118 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setOmega_bulk (const double value) inline
Definition at line 121 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setOmega_even (const double value) inline
Definition at line 122 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setOmega_odd (const double value) inline
Definition at line 123 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setOmega_shear (const double value) inline
Definition at line 124 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
setV_s()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecision::setV_s (const double value) inline
Definition at line 125 of file StreamCollideSweepLeesEdwardsDoublePrecision.h.
The documentation for this class was generated from the following files:
StreamCollideSweepLeesEdwardsDoublePrecision.h
StreamCollideSweepLeesEdwardsDoublePrecision.cpp