ESPResSo: walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX Class Reference
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX Class Reference
#include <StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h>
Public Member Functions
StreamCollideSweepLeesEdwardsDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, double omega_bulk, double omega_even, double omega_odd, double omega_shear, double v_s)
~StreamCollideSweepLeesEdwardsDoublePrecisionAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
int64_t getLebc_bot_index () const
int64_t getLebc_top_index () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
double getV_s () const
void setLebc_bot_index (const int64_t value)
void setLebc_top_index (const int64_t value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepLeesEdwardsDoublePrecisionAVX()
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::StreamCollideSweepLeesEdwardsDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, double omega_bulk, double omega_even, double omega_odd, double omega_shear, double v_s) inline
Definition at line 55 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
~StreamCollideSweepLeesEdwardsDoublePrecisionAVX()
walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::~StreamCollideSweepLeesEdwardsDoublePrecisionAVX () inline
Definition at line 64 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 106 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getLebc_bot_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getLebc_bot_index () const inline
Definition at line 109 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getLebc_top_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getLebc_top_index () const inline
Definition at line 110 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getOmega_bulk () const inline
Definition at line 111 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getOmega_even () const inline
Definition at line 112 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getOmega_odd () const inline
Definition at line 113 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getOmega_shear () const inline
Definition at line 114 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getSweep () inline
Definition at line 93 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionAVX > & kernel) inline static
Definition at line 79 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsDoublePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
References runOnCellInterval(), and stream.
getV_s()
double walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::getV_s () const inline
Definition at line 115 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::run (IBlock * block)
Definition at line 542 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_08be08b6e7ea45132a735524ef494de6::streamcollidesweepleesedwardsdoubleprecisionavx_streamcollidesweepleesedwardsdoubleprecisionavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 600 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_08be08b6e7ea45132a735524ef494de6::streamcollidesweepleesedwardsdoubleprecisionavx_streamcollidesweepleesedwardsdoubleprecisionavx().
Referenced by getSweepOnCellInterval().
setLebc_bot_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setLebc_bot_index (const int64_t value) inline
Definition at line 116 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
setLebc_top_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setLebc_top_index (const int64_t value) inline
Definition at line 119 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setOmega_bulk (const double value) inline
Definition at line 122 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setOmega_even (const double value) inline
Definition at line 123 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setOmega_odd (const double value) inline
Definition at line 124 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setOmega_shear (const double value) inline
Definition at line 125 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
setV_s()
void walberla::pystencils::StreamCollideSweepLeesEdwardsDoublePrecisionAVX::setV_s (const double value) inline
Definition at line 126 of file StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepLeesEdwardsDoublePrecisionAVX.h
StreamCollideSweepLeesEdwardsDoublePrecisionAVX.cpp