ESPResSo: LB::ParticleCoupling Class Reference
LB::ParticleCoupling Class Reference
#include <particle_coupling.hpp>
Public Member Functions
ParticleCoupling (LBThermostat const &thermostat, LB::Solver &lb, BoxGeometry const &box_geo, LocalBox const &local_box, double time_step)
Utils::Vector3d get_noise_term (Particle const &p) const
void kernel (Particle &p)
auto lb_drift_velocity_offset (Particle const &p) const
Calculate particle drift velocity offset due to ENGINE and ELECTROHYDRODYNAMICS.
Detailed Description
Definition at line 83 of file particle_coupling.hpp.
Constructor & Destructor Documentation
ParticleCoupling()
LB::ParticleCoupling::ParticleCoupling (LBThermostat const & thermostat, LB::Solver & lb, BoxGeometry const & box_geo, LocalBox const & local_box, double time_step) inline
Definition at line 93 of file particle_coupling.hpp.
References LB::Solver::get_kT(), LB::Solver::get_lattice_speed(), Utils::sqr(), and Utils::sqrt().
Member Function Documentation
get_noise_term()
Utils::Vector3d LB::ParticleCoupling::get_noise_term (Particle const & p) const
Definition at line 162 of file particle_coupling.cpp.
References LBThermostat::gamma, Utils::gamma(), Utils::hadamard_product(), Particle::id(), lb_handle_particle_anisotropy(), BaseThermostat::rng_counter(), BaseThermostat::rng_seed(), and Utils::sqrt().
Referenced by kernel().
kernel()
void LB::ParticleCoupling::kernel (Particle & p)
Definition at line 174 of file particle_coupling.cpp.
References add_md_force(), Particle::calc_director(), BoxGeometry::folded_position(), Particle::force(), LBThermostat::gamma, LB::Solver::get_agrid(), get_noise_term(), in_local_domain(), in_local_halo(), lb_drag_force(), lb_drift_velocity_offset(), Particle::pos(), pos, positions_in_halo(), and Particle::swimming().
lb_drift_velocity_offset()
auto LB::ParticleCoupling::lb_drift_velocity_offset (Particle const & p) const inline
Calculate particle drift velocity offset due to ENGINE and ELECTROHYDRODYNAMICS.
Definition at line 116 of file particle_coupling.hpp.
References Particle::mu_E().
Referenced by kernel().
The documentation for this class was generated from the following files:
particle_coupling.hpp
particle_coupling.cpp