ESPResSo: walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX Class Reference
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX Class Reference
#include <StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h>
Public Member Functions
StreamCollideSweepDoublePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s)
~StreamCollideSweepDoublePrecisionLeesEdwardsAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getGrid_size () const
double getOmega_shear () const
double getV_s () const
void setGrid_size (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepDoublePrecisionLeesEdwardsAVX()
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::StreamCollideSweepDoublePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s) inline
Definition at line 57 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
~StreamCollideSweepDoublePrecisionLeesEdwardsAVX()
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::~StreamCollideSweepDoublePrecisionLeesEdwardsAVX () inline
Definition at line 65 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 107 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
getGrid_size()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getGrid_size () const inline
Definition at line 110 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getOmega_shear () const inline
Definition at line 111 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getSweep () inline
Definition at line 94 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsAVX > & kernel) inline static
Definition at line 80 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 85 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 99 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
References runOnCellInterval(), and stream.
getV_s()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::getV_s () const inline
Definition at line 112 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::operator() (IBlock * block) inline
Definition at line 77 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::run (IBlock * block)
Definition at line 183 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_7a9c3e1332986727943ef5a2aa109600::streamcollidesweepdoubleprecisionleesedwardsavx_streamcollidesweepdoubleprecisionleesedwardsavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 237 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_7a9c3e1332986727943ef5a2aa109600::streamcollidesweepdoubleprecisionleesedwardsavx_streamcollidesweepdoubleprecisionleesedwardsavx().
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::setGrid_size (const double value) inline
Definition at line 113 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::setOmega_shear (const double value) inline
Definition at line 114 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
setV_s()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsAVX::setV_s (const double value) inline
Definition at line 115 of file StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepDoublePrecisionLeesEdwardsAVX.h
StreamCollideSweepDoublePrecisionLeesEdwardsAVX.cpp