ESPResSo: ScriptInterface::Observables::RDF Class Reference
ScriptInterface::Observables::RDF Class Reference
#include <RDF.hpp>
Public Member Functions
RDF ()
void do_construct (VariantMap const &params) override
std::shared_ptr<::Observables::RDF > rdf_observable () const
std::shared_ptr<::Observables::Observable > observable () const override
Public Member Functions inherited from ScriptInterface::AutoParameters< RDF, Observable >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< RDF, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 36 of file script_interface/observables/RDF.hpp.
Constructor & Destructor Documentation
RDF()
ScriptInterface::Observables::RDF::RDF () inline
Definition at line 39 of file script_interface/observables/RDF.hpp.
References ScriptInterface::AutoParameters< RDF, Observable >::add_parameters(), rdf_observable(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_construct()
void ScriptInterface::Observables::RDF::do_construct (VariantMap const & params) inline override
Definition at line 53 of file script_interface/observables/RDF.hpp.
References stream.
observable()
std::shared_ptr<::Observables::Observable > ScriptInterface::Observables::RDF::observable () const inline override
Definition at line 66 of file script_interface/observables/RDF.hpp.
rdf_observable()
std::shared_ptr<::Observables::RDF > ScriptInterface::Observables::RDF::rdf_observable () const inline
Definition at line 62 of file script_interface/observables/RDF.hpp.
Referenced by RDF().
The documentation for this class was generated from the following file:
script_interface/observables/RDF.hpp