ESPResSo: ScriptInterface::Integrators::StokesianDynamics Class Reference
ScriptInterface::Integrators::StokesianDynamics Class Reference
#include <StokesianDynamics.hpp>
Public Member Functions
StokesianDynamics ()
void do_construct (VariantMap const &params) override
void activate () override
::StokesianDynamicsParameters const & get_instance () const
Public Member Functions inherited from ScriptInterface::AutoParameters< StokesianDynamics, Integrator >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< StokesianDynamics, Integrator >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 39 of file StokesianDynamics.hpp.
Constructor & Destructor Documentation
StokesianDynamics()
ScriptInterface::Integrators::StokesianDynamics::StokesianDynamics ()
Definition at line 39 of file StokesianDynamics.cpp.
References ScriptInterface::AutoParameters< StokesianDynamics, Integrator >::add_parameters(), StokesianDynamicsParameters::flags, FTS, get_instance(), LUBRICATION, ScriptInterface::make_unordered_map_of_variants(), PAIR_MOBILITY, ScriptInterface::AutoParameter::read_only, SELF_MOBILITY, and StokesianDynamicsParameters::viscosity.
Member Function Documentation
activate()
void ScriptInterface::Integrators::StokesianDynamics::activate () override
Definition at line 93 of file StokesianDynamics.cpp.
References get_instance(), INTEG_METHOD_SD, System::System::propagation, and register_integrator().
do_construct()
void ScriptInterface::Integrators::StokesianDynamics::do_construct (VariantMap const & params) override
Definition at line 71 of file StokesianDynamics.cpp.
References FTS, ScriptInterface::get_value(), PAIR_MOBILITY, params, and SELF_MOBILITY.
get_instance()
::StokesianDynamicsParameters const & ScriptInterface::Integrators::StokesianDynamics::get_instance () const inline
Definition at line 48 of file StokesianDynamics.hpp.
Referenced by activate(), and StokesianDynamics().
The documentation for this class was generated from the following files:
StokesianDynamics.hpp
StokesianDynamics.cpp