ESPResSo: walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA Class Reference
walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA Class Reference
#include <CollideSweepSinglePrecisionLeesEdwardsCUDA.h>
Public Member Functions
CollideSweepSinglePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getGrid_size () const
float getOmega_shear () const
float getV_s () const
void setGrid_size (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
Constructor & Destructor Documentation
CollideSweepSinglePrecisionLeesEdwardsCUDA()
walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::CollideSweepSinglePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s) inline
Definition at line 59 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 108 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getGrid_size()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getGrid_size () const inline
Definition at line 111 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getOmega_shear()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getOmega_shear () const inline
Definition at line 112 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getSweep (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsCUDA > & kernel) inline static
Definition at line 77 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 93 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 82 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 98 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References runOnCellInterval(), and stream.
getV_s()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::getV_s () const inline
Definition at line 113 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
operator()()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 73 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 157 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 193 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::setGrid_size (const float value) inline
Definition at line 114 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
setOmega_shear()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::setOmega_shear (const float value) inline
Definition at line 115 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
setV_s()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsCUDA::setV_s (const float value) inline
Definition at line 116 of file CollideSweepSinglePrecisionLeesEdwardsCUDA.h.
The documentation for this class was generated from the following files:
CollideSweepSinglePrecisionLeesEdwardsCUDA.h
CollideSweepSinglePrecisionLeesEdwardsCUDA.cu