ESPResSo: walberla::lbm::DynamicUBBDoublePrecision Class Reference
walberla::lbm::DynamicUBBDoublePrecision Class Reference
#include <DynamicUBBDoublePrecision.h>
Classes
struct IndexInfo
class IndexVectors
Public Member Functions
DynamicUBBDoublePrecision (const shared_ptr< StructuredBlockForest > &blocks, BlockDataID pdfsID_, std::function< Vector3< float64 >(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> &velocityCallback)
void run (IBlock *block)
void operator() (IBlock *block)
void inner (IBlock *block)
void outer (IBlock *block)
Vector3< double > getForce (IBlock *)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getInnerSweep ()
std::function< void(IBlock *)> getOuterSweep ()
template<typename FlagField_T >
void fillFromFlagField (const shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (const shared_ptr< StructuredBlockForest > &blocks, IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
Public Attributes
BlockDataID pdfsID
Detailed Description
Definition at line 53 of file DynamicUBBDoublePrecision.h.
Constructor & Destructor Documentation
DynamicUBBDoublePrecision()
walberla::lbm::DynamicUBBDoublePrecision::DynamicUBBDoublePrecision (const shared_ptr< StructuredBlockForest > & blocks, BlockDataID pdfsID_, std::function< Vector3< float64 >(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> & velocityCallback) inline
Definition at line 92 of file DynamicUBBDoublePrecision.h.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::lbm::DynamicUBBDoublePrecision::fillFromFlagField (const shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 133 of file DynamicUBBDoublePrecision.h.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::lbm::DynamicUBBDoublePrecision::fillFromFlagField (const shared_ptr< StructuredBlockForest > & blocks, IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 142 of file DynamicUBBDoublePrecision.h.
References walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::ALL, block(), walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::indexVector(), walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::INNER, inner(), walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::OUTER, and walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::syncGPU().
getForce()
Vector3< double > walberla::lbm::DynamicUBBDoublePrecision::getForce (IBlock *) inline
Definition at line 113 of file DynamicUBBDoublePrecision.h.
getInnerSweep()
std::function< void(IBlock *)> walberla::lbm::DynamicUBBDoublePrecision::getInnerSweep () inline
Definition at line 124 of file DynamicUBBDoublePrecision.h.
References inner().
getOuterSweep()
std::function< void(IBlock *)> walberla::lbm::DynamicUBBDoublePrecision::getOuterSweep () inline
Definition at line 128 of file DynamicUBBDoublePrecision.h.
References outer().
getSweep()
std::function< void(IBlock *)> walberla::lbm::DynamicUBBDoublePrecision::getSweep () inline
Definition at line 120 of file DynamicUBBDoublePrecision.h.
References run().
inner()
void walberla::lbm::DynamicUBBDoublePrecision::inner (IBlock * block)
Definition at line 111 of file DynamicUBBDoublePrecision.cpp.
References block(), and walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::INNER.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::lbm::DynamicUBBDoublePrecision::operator() (IBlock * block) inline
Definition at line 107 of file DynamicUBBDoublePrecision.h.
References block(), and run().
outer()
void walberla::lbm::DynamicUBBDoublePrecision::outer (IBlock * block)
Definition at line 115 of file DynamicUBBDoublePrecision.cpp.
References block(), and walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::OUTER.
Referenced by getOuterSweep().
run()
void walberla::lbm::DynamicUBBDoublePrecision::run (IBlock * block)
Definition at line 107 of file DynamicUBBDoublePrecision.cpp.
References walberla::lbm::DynamicUBBDoublePrecision::IndexVectors::ALL, and block().
Referenced by getSweep(), and operator()().
Member Data Documentation
pdfsID
BlockDataID walberla::lbm::DynamicUBBDoublePrecision::pdfsID
Definition at line 578 of file DynamicUBBDoublePrecision.h.
The documentation for this class was generated from the following files:
DynamicUBBDoublePrecision.h
DynamicUBBDoublePrecision.cpp