ESPResSo: walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision Class Reference
walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision Class Reference
#include <DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h>
Public Member Functions
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, double kT, uint32_t seed, uint32_t time_step, double z)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
double getD () const
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getF_ext_0 () const
double getF_ext_1 () const
double getF_ext_2 () const
uint32_t getField_size_0 () const
uint32_t getField_size_1 () const
uint32_t getField_size_2 () const
double getKt () const
uint32_t getSeed () const
uint32_t getTime_step () const
double getZ () const
void setD (const double value)
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setF_ext_0 (const double value)
void setF_ext_1 (const double value)
void setF_ext_2 (const double value)
void setField_size_0 (const uint32_t value)
void setField_size_1 (const uint32_t value)
void setField_size_2 (const uint32_t value)
void setKt (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
void setZ (const double value)
void setPhiID (BlockDataID phiID_)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision()
walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, double kT, uint32_t seed, uint32_t time_step, double z) inline
Definition at line 55 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 106 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getBlock_offset_0 () const inline
Definition at line 116 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getBlock_offset_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getBlock_offset_1 () const inline
Definition at line 117 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getBlock_offset_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getBlock_offset_2 () const inline
Definition at line 118 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getD()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getD () const inline
Definition at line 115 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getF_ext_0()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getF_ext_0 () const inline
Definition at line 119 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getF_ext_1()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getF_ext_1 () const inline
Definition at line 120 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getF_ext_2()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getF_ext_2 () const inline
Definition at line 121 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getField_size_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getField_size_0 () const inline
Definition at line 122 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getField_size_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getField_size_1 () const inline
Definition at line 123 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getField_size_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getField_size_2 () const inline
Definition at line 124 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getKt()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getKt () const inline
Definition at line 125 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getSeed()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getSeed () const inline
Definition at line 126 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getSweep () inline
Definition at line 93 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision > & kernel) inline static
Definition at line 76 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 82 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getTime_step () const inline
Definition at line 127 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
getZ()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::getZ () const inline
Definition at line 128 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::operator() (IBlock * block) inline
Definition at line 73 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::run (IBlock * block)
Definition at line 477 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.cpp.
References block(), walberla::pystencils::internal_1ba80591fca01bd4852b82a8b7a2ca49::diffusivefluxkernelwithelectrostaticthermalized_double_precision_diffusivefluxkernelwithelectrostaticthermalized_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 524 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.cpp.
References block(), walberla::pystencils::internal_1ba80591fca01bd4852b82a8b7a2ca49::diffusivefluxkernelwithelectrostaticthermalized_double_precision_diffusivefluxkernelwithelectrostaticthermalized_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setBlock_offset_0 (const uint32_t value) inline
Definition at line 130 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setBlock_offset_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setBlock_offset_1 (const uint32_t value) inline
Definition at line 133 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setBlock_offset_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setBlock_offset_2 (const uint32_t value) inline
Definition at line 136 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setD()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setD (const double value) inline
Definition at line 129 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setF_ext_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setF_ext_0 (const double value) inline
Definition at line 139 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setF_ext_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setF_ext_1 (const double value) inline
Definition at line 140 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setF_ext_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setF_ext_2 (const double value) inline
Definition at line 141 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setField_size_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setField_size_0 (const uint32_t value) inline
Definition at line 142 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setField_size_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setField_size_1 (const uint32_t value) inline
Definition at line 143 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setField_size_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setField_size_2 (const uint32_t value) inline
Definition at line 144 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setKt()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setKt (const double value) inline
Definition at line 145 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setPhiID()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setPhiID (BlockDataID phiID_) inline
Definition at line 155 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
References stream.
setSeed()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setSeed (const uint32_t value) inline
Definition at line 146 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setTime_step()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setTime_step (const uint32_t value) inline
Definition at line 147 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
setZ()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision::setZ (const double value) inline
Definition at line 148 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.h
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision.cpp