ESPResSo: EspressoSystemStandAlone Class Reference
EspressoSystemStandAlone Class Reference
Manager for a stand-alone ESPResSo system.
#include <EspressoSystemStandAlone.hpp>
Public Member Functions
EspressoSystemStandAlone (int argc, char **argv)
void set_box_l (Utils::Vector3d const &box_l) const
void set_node_grid (Utils::Vector3i const &node_grid) const
void set_time_step (double time_step) const
void set_skin (double new_skin) const
Detailed Description
Manager for a stand-alone ESPResSo system.
The system is default-initialized, MPI-ready and has no script interface.
Definition at line 27 of file EspressoSystemStandAlone.hpp.
Constructor & Destructor Documentation
EspressoSystemStandAlone()
EspressoSystemStandAlone::EspressoSystemStandAlone (int argc, char ** argv)
Definition at line 35 of file EspressoSystemStandAlone.cpp.
References Communication::init(), Communication::mpi_env, mpi_init(), mpi_loop(), and set_virtual_sites().
Member Function Documentation
set_box_l()
void EspressoSystemStandAlone::set_box_l (Utils::Vector3d const & box_l) const
Definition at line 53 of file EspressoSystemStandAlone.cpp.
References mpi_set_box_length().
set_node_grid()
void EspressoSystemStandAlone::set_node_grid (Utils::Vector3i const & node_grid) const
Definition at line 59 of file EspressoSystemStandAlone.cpp.
References mpi_set_node_grid(), and node_grid.
set_skin()
void EspressoSystemStandAlone::set_skin (double new_skin) const
Definition at line 72 of file EspressoSystemStandAlone.cpp.
References mpi_set_skin().
set_time_step()
void EspressoSystemStandAlone::set_time_step (double time_step) const
Definition at line 66 of file EspressoSystemStandAlone.cpp.
References mpi_set_time_step(), and time_step.
The documentation for this class was generated from the following files:
EspressoSystemStandAlone.hpp
EspressoSystemStandAlone.cpp