ESPResSo: ScriptInterface::Accumulators::Correlator Class Reference
ScriptInterface::Accumulators::Correlator Class Reference
#include <Correlator.hpp>
Public Member Functions
Correlator ()
void do_construct (VariantMap const &args) override
std::shared_ptr<::Accumulators::Correlator > correlator ()
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
std::shared_ptr<::Accumulators::AccumulatorBase > accumulator () override
std::shared_ptr< const ::Accumulators::AccumulatorBase > accumulator () const override
Public Member Functions inherited from ScriptInterface::Accumulators::AccumulatorBase
AccumulatorBase ()
Variant call_method (std::string const &method, VariantMap const &parameters)
Public Member Functions inherited from ScriptInterface::AutoParameters< AccumulatorBase >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::AutoParameters< AccumulatorBase >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 42 of file script_interface/accumulators/Correlator.hpp.
Constructor & Destructor Documentation
Correlator()
ScriptInterface::Accumulators::Correlator::Correlator () inline
Definition at line 46 of file script_interface/accumulators/Correlator.hpp.
References ScriptInterface::AutoParameters< AccumulatorBase >::add_parameters().
Member Function Documentation
accumulator() [1/2]
std::shared_ptr<const ::Accumulators::AccumulatorBase> ScriptInterface::Accumulators::Correlator::accumulator () const inline override virtual
Implements ScriptInterface::Accumulators::AccumulatorBase.
Definition at line 121 of file script_interface/accumulators/Correlator.hpp.
accumulator() [2/2]
std::shared_ptr<::Accumulators::AccumulatorBase> ScriptInterface::Accumulators::Correlator::accumulator () inline override virtual
Implements ScriptInterface::Accumulators::AccumulatorBase.
Definition at line 116 of file script_interface/accumulators/Correlator.hpp.
correlator()
std::shared_ptr<::Accumulators::Correlator> ScriptInterface::Accumulators::Correlator::correlator () inline
Definition at line 80 of file script_interface/accumulators/Correlator.hpp.
Referenced by do_call_method().
do_call_method()
Variant ScriptInterface::Accumulators::Correlator::do_call_method (std::string const & method, VariantMap const & parameters) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 84 of file script_interface/accumulators/Correlator.hpp.
References ScriptInterface::Accumulators::AccumulatorBase::call_method(), ScriptInterface::ObjectHandle::context(), correlator(), ScriptInterface::Context::is_head_node(), and ScriptInterface::Context::parallel_try_catch().
do_construct()
void ScriptInterface::Accumulators::Correlator::do_construct (VariantMap const & args) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 60 of file script_interface/accumulators/Correlator.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Context::parallel_try_catch(), and ScriptInterface::set_from_args().
The documentation for this class was generated from the following file:
script_interface/accumulators/Correlator.hpp