ESPResSo: walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA Class Reference
walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA Class Reference
#include <DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h>
Public Member Functions
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, double kT, uint32_t seed, uint32_t time_step, double z)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
double getD () const
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getF_ext_0 () const
double getF_ext_1 () const
double getF_ext_2 () const
uint32_t getField_size_0 () const
uint32_t getField_size_1 () const
uint32_t getField_size_2 () const
double getKt () const
uint32_t getSeed () const
uint32_t getTime_step () const
double getZ () const
void setD (const double value)
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setF_ext_0 (const double value)
void setF_ext_1 (const double value)
void setF_ext_2 (const double value)
void setField_size_0 (const uint32_t value)
void setField_size_1 (const uint32_t value)
void setField_size_2 (const uint32_t value)
void setKt (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
void setZ (const double value)
void setPhiID (BlockDataID phiID_)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 56 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA()
walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, double kT, uint32_t seed, uint32_t time_step, double z) inline
Definition at line 58 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 116 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getBlock_offset_0 () const inline
Definition at line 126 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getBlock_offset_1 () const inline
Definition at line 127 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getBlock_offset_2 () const inline
Definition at line 128 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getD()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getD () const inline
Definition at line 125 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getF_ext_0()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getF_ext_0 () const inline
Definition at line 129 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getF_ext_1()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getF_ext_1 () const inline
Definition at line 130 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getF_ext_2()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getF_ext_2 () const inline
Definition at line 131 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getField_size_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getField_size_0 () const inline
Definition at line 132 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getField_size_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getField_size_1 () const inline
Definition at line 133 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getField_size_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getField_size_2 () const inline
Definition at line 134 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getKt()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getKt () const inline
Definition at line 135 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getSeed()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getSeed () const inline
Definition at line 136 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA > & kernel) inline static
Definition at line 81 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 101 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 88 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 106 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getTime_step () const inline
Definition at line 137 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
getZ()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::getZ () const inline
Definition at line 138 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 77 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 476 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 529 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 140 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setBlock_offset_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 143 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setBlock_offset_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 146 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setD()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setD (const double value) inline
Definition at line 139 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setF_ext_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setF_ext_0 (const double value) inline
Definition at line 149 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setF_ext_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setF_ext_1 (const double value) inline
Definition at line 150 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setF_ext_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setF_ext_2 (const double value) inline
Definition at line 151 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setField_size_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setField_size_0 (const uint32_t value) inline
Definition at line 152 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setField_size_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setField_size_1 (const uint32_t value) inline
Definition at line 153 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setField_size_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setField_size_2 (const uint32_t value) inline
Definition at line 154 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setKt()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setKt (const double value) inline
Definition at line 155 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setPhiID()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setPhiID (BlockDataID phiID_) inline
Definition at line 165 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
References stream.
setSeed()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setSeed (const uint32_t value) inline
Definition at line 156 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setTime_step()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setTime_step (const uint32_t value) inline
Definition at line 157 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
setZ()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA::setZ (const double value) inline
Definition at line 158 of file DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.h
DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA.cu