ESPResSo: walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX Class Reference
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX Class Reference
#include <StreamCollideSweepThermalizedDoublePrecisionAVX.h>
Public Member Functions
StreamCollideSweepThermalizedDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepThermalizedDoublePrecisionAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepThermalizedDoublePrecisionAVX()
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::StreamCollideSweepThermalizedDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 55 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
~StreamCollideSweepThermalizedDoublePrecisionAVX()
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::~StreamCollideSweepThermalizedDoublePrecisionAVX () inline
Definition at line 65 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 107 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getBlock_offset_0 () const inline
Definition at line 116 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getBlock_offset_1 () const inline
Definition at line 117 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getBlock_offset_2 () const inline
Definition at line 118 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getKt()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getKt () const inline
Definition at line 119 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getOmega_bulk () const inline
Definition at line 120 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getOmega_even () const inline
Definition at line 121 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getOmega_odd () const inline
Definition at line 122 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getOmega_shear () const inline
Definition at line 123 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getSeed () const inline
Definition at line 124 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getSweep () inline
Definition at line 94 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getSweep (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionAVX > & kernel) inline static
Definition at line 80 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 85 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 99 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::getTime_step () const inline
Definition at line 125 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::operator() (IBlock * block) inline
Definition at line 77 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::run (IBlock * block)
Definition at line 773 of file StreamCollideSweepThermalizedDoublePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_b312c2da0affb0ff73dd81300a784e62::streamcollidesweepthermalizeddoubleprecisionavx_streamcollidesweepthermalizeddoubleprecisionavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 836 of file StreamCollideSweepThermalizedDoublePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_b312c2da0affb0ff73dd81300a784e62::streamcollidesweepthermalizeddoubleprecisionavx_streamcollidesweepthermalizeddoubleprecisionavx().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setBlock_offset_0 (const uint32_t value) inline
Definition at line 126 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setBlock_offset_1 (const uint32_t value) inline
Definition at line 129 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setBlock_offset_2 (const uint32_t value) inline
Definition at line 132 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setKt()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setKt (const double value) inline
Definition at line 135 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setOmega_bulk (const double value) inline
Definition at line 136 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setOmega_even (const double value) inline
Definition at line 137 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setOmega_odd (const double value) inline
Definition at line 138 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setOmega_shear (const double value) inline
Definition at line 139 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setSeed()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setSeed (const uint32_t value) inline
Definition at line 140 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionAVX::setTime_step (const uint32_t value) inline
Definition at line 141 of file StreamCollideSweepThermalizedDoublePrecisionAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepThermalizedDoublePrecisionAVX.h
StreamCollideSweepThermalizedDoublePrecisionAVX.cpp