ESPResSo: ScriptInterface::Integrators::Integrator Class Reference
ScriptInterface::Integrators::Integrator Class Reference abstract
#include <Integrator.hpp>
Public Member Functions
Variant do_call_method (std::string const &name, VariantMap const &params) override
virtual Variant integrate (VariantMap const &params)
virtual void activate ()=0
virtual void deactivate ()
Public Member Functions inherited from ScriptInterface::System::Leaf
void bind_system (std::shared_ptr<::System::System > const &system)
void detach_system ()
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
virtual Utils::Span< const boost::string_ref > valid_parameters () const
Get required and optional parameters for class.
auto get_valid_parameters () const
virtual Variant get_parameter (const std::string &name) const
Get single parameter.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
virtual std::vector< std::pair< std::string, Variant > > serialize_parameters () const
Serialize parameters.
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::System::Leaf
auto const & get_system () const
auto & get_system ()
Protected Attributes inherited from ScriptInterface::System::Leaf
std::weak_ptr<::System::System > m_system
Detailed Description
Definition at line 32 of file Integrator.hpp.
Member Function Documentation
activate()
virtual void ScriptInterface::Integrators::Integrator::activate () pure virtual
deactivate()
virtual void ScriptInterface::Integrators::Integrator::deactivate () inline virtual
Definition at line 38 of file Integrator.hpp.
References ScriptInterface::System::Leaf::detach_system().
do_call_method()
Variant Integrator::do_call_method (std::string const & name, VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 56 of file Integrator.cpp.
References integrate(), ScriptInterface::ObjectHandle::name(), ScriptInterface::none, and params.
integrate()
Variant Integrator::integrate (VariantMap const & params) virtual
Definition at line 33 of file Integrator.cpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::System::Leaf::get_system(), INTEG_REUSE_FORCES_ALWAYS, INTEG_REUSE_FORCES_CONDITIONALLY, ScriptInterface::Context::parallel_try_catch(), and params.
Referenced by do_call_method().
The documentation for this class was generated from the following files:
Integrator.hpp
Integrator.cpp