ESPResSo: walberla::pystencils::FixedFlux_double_precision Class Reference
walberla::pystencils::FixedFlux_double_precision Class Reference
#include <FixedFlux_double_precision.h>
Classes
struct IndexInfo
class IndexVectors
Public Member Functions
FixedFlux_double_precision (const std::shared_ptr< StructuredBlockForest > &blocks, BlockDataID fluxID_, std::function< Vector3< double >(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> &fluxCallback)
void run (IBlock *block)
void operator() (IBlock *block)
void inner (IBlock *block)
void outer (IBlock *block)
Vector3< double > getForce (IBlock *)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getInnerSweep ()
std::function< void(IBlock *)> getOuterSweep ()
template<typename FlagField_T >
void fillFromFlagField (const std::shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (const shared_ptr< StructuredBlockForest > &blocks, IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
Public Attributes
BlockDataID fluxID
Detailed Description
Definition at line 52 of file FixedFlux_double_precision.h.
Constructor & Destructor Documentation
FixedFlux_double_precision()
walberla::pystencils::FixedFlux_double_precision::FixedFlux_double_precision (const std::shared_ptr< StructuredBlockForest > & blocks, BlockDataID fluxID_, std::function< Vector3< double >(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> & fluxCallback) inline
Definition at line 94 of file FixedFlux_double_precision.h.
References stream.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::pystencils::FixedFlux_double_precision::fillFromFlagField (const shared_ptr< StructuredBlockForest > & blocks, IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 144 of file FixedFlux_double_precision.h.
References walberla::pystencils::FixedFlux_double_precision::IndexVectors::ALL, block(), walberla::pystencils::FixedFlux_double_precision::IndexVectors::indexVector(), walberla::pystencils::FixedFlux_double_precision::IndexVectors::INNER, inner(), walberla::pystencils::FixedFlux_double_precision::IndexVectors::OUTER, and stream.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::pystencils::FixedFlux_double_precision::fillFromFlagField (const std::shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 135 of file FixedFlux_double_precision.h.
References block(), and stream.
getForce()
Vector3< double > walberla::pystencils::FixedFlux_double_precision::getForce (IBlock *) inline
Definition at line 115 of file FixedFlux_double_precision.h.
References stream.
getInnerSweep()
std::function< void(IBlock *)> walberla::pystencils::FixedFlux_double_precision::getInnerSweep () inline
Definition at line 126 of file FixedFlux_double_precision.h.
References inner().
getOuterSweep()
std::function< void(IBlock *)> walberla::pystencils::FixedFlux_double_precision::getOuterSweep () inline
Definition at line 130 of file FixedFlux_double_precision.h.
References outer().
getSweep()
std::function< void(IBlock *)> walberla::pystencils::FixedFlux_double_precision::getSweep () inline
Definition at line 122 of file FixedFlux_double_precision.h.
References run().
inner()
void walberla::pystencils::FixedFlux_double_precision::inner (IBlock * block)
Definition at line 198 of file FixedFlux_double_precision.cpp.
References block(), and walberla::pystencils::FixedFlux_double_precision::IndexVectors::INNER.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::pystencils::FixedFlux_double_precision::operator() (IBlock * block) inline
Definition at line 109 of file FixedFlux_double_precision.h.
References block(), and run().
outer()
void walberla::pystencils::FixedFlux_double_precision::outer (IBlock * block)
Definition at line 202 of file FixedFlux_double_precision.cpp.
References block(), and walberla::pystencils::FixedFlux_double_precision::IndexVectors::OUTER.
Referenced by getOuterSweep().
run()
void walberla::pystencils::FixedFlux_double_precision::run (IBlock * block)
Definition at line 194 of file FixedFlux_double_precision.cpp.
References walberla::pystencils::FixedFlux_double_precision::IndexVectors::ALL, and block().
Referenced by getSweep(), and operator()().
Member Data Documentation
fluxID
BlockDataID walberla::pystencils::FixedFlux_double_precision::fluxID
Definition at line 748 of file FixedFlux_double_precision.h.
The documentation for this class was generated from the following files:
FixedFlux_double_precision.h
FixedFlux_double_precision.cpp