ESPResSo: CommunicationEnvironment Class Reference
CommunicationEnvironment Class Reference
#include <communication.hpp>
Public Member Functions
CommunicationEnvironment ()
CommunicationEnvironment (std::shared_ptr< boost::mpi::environment > mpi_env)
~CommunicationEnvironment ()
auto & mpiCallbacks () const
auto mpiCallbacksHandle ()
auto get_mpi_env () const
auto is_mpi_gpu_aware () const
Detailed Description
Definition at line 67 of file core/communication.hpp.
Constructor & Destructor Documentation
CommunicationEnvironment() [1/2]
CommunicationEnvironment::CommunicationEnvironment ()
Definition at line 90 of file communication.cpp.
CommunicationEnvironment() [2/2]
CommunicationEnvironment::CommunicationEnvironment (std::shared_ptr< boost::mpi::environment > mpi_env) explicit
Definition at line 93 of file communication.cpp.
References comm_cart, communicator, cuda_on_program_start(), fft_on_program_start(), Communicator::full_initialization(), get_env_variable(), ErrorHandling::init_error_handling(), kokkos_handle, walberla::mpi_init(), and stream.
~CommunicationEnvironment()
CommunicationEnvironment::~CommunicationEnvironment ()
Definition at line 148 of file communication.cpp.
References ErrorHandling::deinit_error_handling(), kokkos_handle, and walberla::mpi_deinit().
Member Function Documentation
get_mpi_env()
auto CommunicationEnvironment::get_mpi_env () const inline
Definition at line 80 of file core/communication.hpp.
is_mpi_gpu_aware()
auto CommunicationEnvironment::is_mpi_gpu_aware () const inline
Definition at line 81 of file core/communication.hpp.
mpiCallbacks()
auto & CommunicationEnvironment::mpiCallbacks () const inline
Definition at line 78 of file core/communication.hpp.
mpiCallbacksHandle()
auto CommunicationEnvironment::mpiCallbacksHandle () inline
Definition at line 79 of file core/communication.hpp.
The documentation for this class was generated from the following files:
core/communication.hpp
communication.cpp