ESPResSo: walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX Class Reference
walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX Class Reference
#include <CollideSweepSinglePrecisionLeesEdwardsAVX.h>
Public Member Functions
CollideSweepSinglePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getGrid_size () const
float getOmega_shear () const
float getV_s () const
void setGrid_size (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
Constructor & Destructor Documentation
CollideSweepSinglePrecisionLeesEdwardsAVX()
walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::CollideSweepSinglePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s) inline
Definition at line 57 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 99 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
getGrid_size()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getGrid_size () const inline
Definition at line 102 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
getOmega_shear()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getOmega_shear () const inline
Definition at line 103 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getSweep () inline
Definition at line 86 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getSweep (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsAVX > & kernel) inline static
Definition at line 72 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionLeesEdwardsAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 77 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 91 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
References runOnCellInterval().
getV_s()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::getV_s () const inline
Definition at line 104 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
operator()()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::operator() (IBlock * block) inline
Definition at line 70 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::run (IBlock * block)
Definition at line 261 of file CollideSweepSinglePrecisionLeesEdwardsAVX.cpp.
References block(), walberla::pystencils::internal_9a18f2f4073cdcc5365cdfddb752069e::collidesweepsingleprecisionleesedwardsavx_collidesweepsingleprecisionleesedwardsavx(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 298 of file CollideSweepSinglePrecisionLeesEdwardsAVX.cpp.
References block(), walberla::pystencils::internal_9a18f2f4073cdcc5365cdfddb752069e::collidesweepsingleprecisionleesedwardsavx_collidesweepsingleprecisionleesedwardsavx(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::setGrid_size (const float value) inline
Definition at line 105 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
setOmega_shear()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::setOmega_shear (const float value) inline
Definition at line 106 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
setV_s()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwardsAVX::setV_s (const float value) inline
Definition at line 107 of file CollideSweepSinglePrecisionLeesEdwardsAVX.h.
The documentation for this class was generated from the following files:
CollideSweepSinglePrecisionLeesEdwardsAVX.h
CollideSweepSinglePrecisionLeesEdwardsAVX.cpp