ESPResSo: PairCriteria::EnergyCriterion Class Reference
PairCriteria::EnergyCriterion Class Reference
True if the short-range energy is larger than a cutoff value.
#include <EnergyCriterion.hpp>
Public Member Functions
EnergyCriterion (System::System const &system)
bool decide (Particle const &p1, Particle const &p2) const override
double get_cut_off ()
void set_cut_off (double c)
Public Member Functions inherited from PairCriteria::PairCriterion
bool decide (int id1, int id2) const
Make a decision based on particle ids.
virtual ~PairCriterion ()=default
Detailed Description
True if the short-range energy is larger than a cutoff value.
Definition at line 34 of file core/pair_criteria/EnergyCriterion.hpp.
Constructor & Destructor Documentation
EnergyCriterion()
PairCriteria::EnergyCriterion::EnergyCriterion (System::System const & system) inline
Definition at line 36 of file core/pair_criteria/EnergyCriterion.hpp.
Member Function Documentation
decide()
bool PairCriteria::EnergyCriterion::decide (Particle const & p1, Particle const & p2) const inline override virtual
Implements PairCriteria::PairCriterion.
Definition at line 37 of file core/pair_criteria/EnergyCriterion.hpp.
References System::System::bonded_ias, System::System::box_geo, calc_non_bonded_pair_energy(), System::System::coulomb, get_ptr(), System::System::nonbonded_ias, Coulomb::Solver::pair_energy_kernel(), and stream.
get_cut_off()
double PairCriteria::EnergyCriterion::get_cut_off () inline
Definition at line 52 of file core/pair_criteria/EnergyCriterion.hpp.
set_cut_off()
void PairCriteria::EnergyCriterion::set_cut_off (double c) inline
Definition at line 53 of file core/pair_criteria/EnergyCriterion.hpp.
The documentation for this class was generated from the following file:
core/pair_criteria/EnergyCriterion.hpp