ESPResSo: walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision Class Reference
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision Class Reference
#include <StreamCollideSweepLeesEdwardsSinglePrecision.h>
Public Member Functions
StreamCollideSweepLeesEdwardsSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, float omega_bulk, float omega_even, float omega_odd, float omega_shear, float v_s)
~StreamCollideSweepLeesEdwardsSinglePrecision ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
int64_t getLebc_bot_index () const
int64_t getLebc_top_index () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
float getV_s () const
void setLebc_bot_index (const int64_t value)
void setLebc_top_index (const int64_t value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
Constructor & Destructor Documentation
StreamCollideSweepLeesEdwardsSinglePrecision()
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::StreamCollideSweepLeesEdwardsSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, float omega_bulk, float omega_even, float omega_odd, float omega_shear, float v_s) inline
Definition at line 55 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
~StreamCollideSweepLeesEdwardsSinglePrecision()
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::~StreamCollideSweepLeesEdwardsSinglePrecision () inline
Definition at line 64 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 105 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getLebc_bot_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getLebc_bot_index () const inline
Definition at line 108 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getLebc_top_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getLebc_top_index () const inline
Definition at line 109 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getOmega_bulk () const inline
Definition at line 110 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getOmega_even () const inline
Definition at line 111 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getOmega_odd () const inline
Definition at line 112 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getOmega_shear () const inline
Definition at line 113 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getSweep () inline
Definition at line 92 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecision > & kernel) inline static
Definition at line 78 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 83 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 97 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
References runOnCellInterval(), and stream.
getV_s()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::getV_s () const inline
Definition at line 114 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
operator()()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::run (IBlock * block)
Definition at line 307 of file StreamCollideSweepLeesEdwardsSinglePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_a263151a09bd9903959d48e17aef88f9::streamcollidesweepleesedwardssingleprecision_streamcollidesweepleesedwardssingleprecision().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 362 of file StreamCollideSweepLeesEdwardsSinglePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_a263151a09bd9903959d48e17aef88f9::streamcollidesweepleesedwardssingleprecision_streamcollidesweepleesedwardssingleprecision().
Referenced by getSweepOnCellInterval().
setLebc_bot_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setLebc_bot_index (const int64_t value) inline
Definition at line 115 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
setLebc_top_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setLebc_top_index (const int64_t value) inline
Definition at line 118 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setOmega_bulk (const float value) inline
Definition at line 121 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setOmega_even (const float value) inline
Definition at line 122 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setOmega_odd (const float value) inline
Definition at line 123 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setOmega_shear (const float value) inline
Definition at line 124 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
setV_s()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecision::setV_s (const float value) inline
Definition at line 125 of file StreamCollideSweepLeesEdwardsSinglePrecision.h.
The documentation for this class was generated from the following files:
StreamCollideSweepLeesEdwardsSinglePrecision.h
StreamCollideSweepLeesEdwardsSinglePrecision.cpp