ESPResSo: VirtualSitesRelative Class Reference
VirtualSitesRelative Class Reference
Virtual sites implementation for rigid bodies.
#include <VirtualSitesRelative.hpp>
Public Member Functions
VirtualSitesRelative ()=default
void update () const override
Update positions and velocities of virtual sites.
void back_transfer_forces_and_torques () const override
Back-transfer forces (and torques) to non-virtual particles.
Utils::Matrix< double, 3, 3 > pressure_tensor () const override
Pressure contribution.
Public Member Functions inherited from VirtualSites
VirtualSites ()=default
virtual ~VirtualSites ()=default
virtual void after_force_calc ()
Called after force calculation (and before rattle/shake)
virtual void after_lb_propagation (double)
void set_have_quaternion (const bool &have_quaternion)
Enable/disable quaternion calculations for vs.
bool have_quaternions () const
Detailed Description
Virtual sites implementation for rigid bodies.
Definition at line 32 of file core/virtual_sites/VirtualSitesRelative.hpp.
Constructor & Destructor Documentation
VirtualSitesRelative()
VirtualSitesRelative::VirtualSitesRelative () default
Member Function Documentation
back_transfer_forces_and_torques()
void VirtualSitesRelative::back_transfer_forces_and_torques () const override virtual
Back-transfer forces (and torques) to non-virtual particles.
Reimplemented from VirtualSites.
Definition at line 148 of file VirtualSitesRelative.cpp.
References cell_structure, connection_vector(), get_reference_particle(), CellStructure::ghost_particles(), CellStructure::ghosts_reduce_forces(), init_forces_ghosts(), CellStructure::local_particles(), and vector_product().
pressure_tensor()
Utils::Matrix< double, 3, 3 > VirtualSitesRelative::pressure_tensor () const override virtual
Pressure contribution.
Reimplemented from VirtualSites.
Definition at line 168 of file VirtualSitesRelative.cpp.
References cell_structure, constraint_stress(), get_reference_particle(), and CellStructure::local_particles().
update()
void VirtualSitesRelative::update () const override virtual
Update positions and velocities of virtual sites.
Reimplemented from VirtualSites.
Definition at line 104 of file VirtualSitesRelative.cpp.
References box_geo, cell_structure, CellStructure::check_resort_required(), connection_vector(), Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, fold_position(), BoxGeometry::get_mi_vector(), get_reference_particle(), CellStructure::ghosts_update(), VirtualSites::have_quaternions(), image_shift(), LEES_EDWARDS, BoxGeometry::lees_edwards_bc(), CellStructure::local_particles(), Cells::particles(), Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), LeesEdwardsBC::shear_direction, skin, BoxGeometry::type(), and velocity().
The documentation for this class was generated from the following files:
core/virtual_sites/VirtualSitesRelative.hpp
VirtualSitesRelative.cpp