ESPResSo: ScriptInterface::Particles::ParticleHandle Class Reference
ScriptInterface::Particles::ParticleHandle Class Reference
#include <ParticleHandle.hpp>
Public Member Functions
ParticleHandle ()
Variant do_call_method (std::string const &name, VariantMap const &params) override
void do_construct (VariantMap const &params) override
void attach (std::weak_ptr<::System::System > system)
Public Member Functions inherited from ScriptInterface::AutoParameters< ParticleHandle >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Friends
class ParticleModifier
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::AutoParameters< ParticleHandle >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 128 of file ParticleHandle.hpp.
Constructor & Destructor Documentation
ParticleHandle()
ScriptInterface::Particles::ParticleHandle::ParticleHandle ()
Definition at line 182 of file ParticleHandle.cpp.
References ScriptInterface::Particles::bitfield_from_flag(), System::System::box_geo, Particle::calc_dip(), convert_dip_to_quat(), Utils::convert_director_to_quaternion(), Utils::convert_quaternion_to_director(), convert_vector_body_to_space(), convert_vector_space_to_body(), Particle::dip_fld(), Particle::dipm(), ParticleProperties::VirtualSitesRelativeParameters::distance, ScriptInterface::Particles::error_msg(), Particle::ext_force(), Particle::ext_torque(), Particle::fixed(), Particle::force(), Particle::gamma(), Particle::gamma_rot(), ScriptInterface::Particles::get_gamma_safe(), get_particle_data(), get_particle_node(), ScriptInterface::Particles::get_quaternion_safe(), is_valid_propagation_combination(), Particle::lees_edwards_flag(), Particle::lees_edwards_offset(), Particle::magnetic_anisotropy_energy(), Particle::magnetic_anisotropy_field_inv(), Particle::mass(), Particle::mol_id(), Particle::mu_E(), System::System::nonbonded_ias, Particle::omega(), on_particle_type_change(), ScriptInterface::Particles::particle_checks(), Particle::propagation(), propagation_bitmask_to_string(), Particle::q(), Particle::quat(), ScriptInterface::Particles::quat2vector(), Particle::rinertia(), Particle::rotation(), Particle::saturation_magnetization(), set_particle_pos(), Particle::stoner_wohlfarth_dt_incr(), Particle::stoner_wohlfarth_is_enabled(), Particle::stoner_wohlfarth_phi_0(), Particle::stoner_wohlfarth_tau0_inv(), stream, ParticleParametersSwimming::swimming, Particle::swimming(), Particle::torque(), Particle::type(), Particle::v(), and Particle::vs_relative().
Member Function Documentation
attach()
void ScriptInterface::Particles::ParticleHandle::attach (std::weak_ptr<::System::System > system) inline
Definition at line 171 of file ParticleHandle.hpp.
References stream.
do_call_method()
Variant ScriptInterface::Particles::ParticleHandle::do_call_method (std::string const & name, VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Reimplemented in ScriptInterface::Particles::ParticleModifier.
Definition at line 543 of file ParticleHandle.cpp.
References add_bond(), Utils::Vector< T, N >::as_vector(), System::System::bonded_ias, Particle::bonds(), calculate_vs_relate_to_params(), convert_vector_body_to_space(), convert_vector_space_to_body(), Particle::exclusions(), get_cell_structure(), get_particle_data(), get_pid_for_vs_com(), ScriptInterface::Particles::get_real_particle(), Particle::has_exclusion(), Particle::is_virtual(), ScriptInterface::Particles::local_add_exclusion(), ScriptInterface::Particles::local_remove_exclusion(), local_rotate_particle(), ScriptInterface::make_vector_of_variants(), System::System::on_particle_change(), ScriptInterface::Particles::particle_exclusion_sanity_checks(), ScriptInterface::Particles::quat2vector(), remove_particle(), PropagationMode::ROT_VS_RELATIVE, ScriptInterface::Particles::sanity_checks_rotation(), stream, PropagationMode::TRANS_VS_CENTER_OF_MASS, and PropagationMode::TRANS_VS_RELATIVE.
Referenced by ScriptInterface::Particles::ParticleModifier::do_call_method().
do_construct()
void ScriptInterface::Particles::ParticleHandle::do_construct (VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Reimplemented in ScriptInterface::Particles::ParticleModifier.
Definition at line 836 of file ParticleHandle.cpp.
References get_cell_structure(), get_maximal_particle_id(), make_new_particle(), ScriptInterface::Particles::particle_checks(), remove_particle(), ScriptInterface::Particles::sanity_checks_rotation(), and stream.
Friends And Related Symbol Documentation
ParticleModifier
friend class ParticleModifier friend
Definition at line 164 of file ParticleHandle.hpp.
The documentation for this class was generated from the following files:
ParticleHandle.hpp
ParticleHandle.cpp