ESPResSo: LeesEdwards::LeesEdwards Class Reference
LeesEdwards::LeesEdwards Class Reference
#include <lees_edwards.hpp>
Public Member Functions
auto get_protocol () const
Get currently active Lees-Edwards protocol.
void set_protocol (std::shared_ptr< ActiveProtocol > protocol)
Set a new Lees-Edwards protocol.
void unset_protocol ()
Delete the currently active Lees-Edwards protocol.
void update_box_params (BoxGeometry &box_geo, double sim_time)
Update the Lees-Edwards parameters of the box geometry for the current simulation time.
Public Member Functions inherited from System::Leaf< LeesEdwards >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< LeesEdwards >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< LeesEdwards >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 94 of file lees_edwards.hpp.
Member Function Documentation
get_protocol()
auto LeesEdwards::LeesEdwards::get_protocol () const inline
Get currently active Lees-Edwards protocol.
Definition at line 99 of file lees_edwards.hpp.
set_protocol()
void LeesEdwards::LeesEdwards::set_protocol (std::shared_ptr< ActiveProtocol > protocol)
Set a new Lees-Edwards protocol.
Definition at line 110 of file integrate.cpp.
References LEES_EDWARDS, Cells::RESORT_LOCAL, and stream.
unset_protocol()
void LeesEdwards::LeesEdwards::unset_protocol ()
Delete the currently active Lees-Edwards protocol.
Definition at line 121 of file integrate.cpp.
References CUBOID, Cells::RESORT_LOCAL, and stream.
update_box_params()
void LeesEdwards::LeesEdwards::update_box_params (BoxGeometry & box_geo, double sim_time)
Update the Lees-Edwards parameters of the box geometry for the current simulation time.
Definition at line 102 of file integrate.cpp.
References LeesEdwards::get_pos_offset(), LeesEdwards::get_shear_velocity(), LEES_EDWARDS, BoxGeometry::lees_edwards_update(), stream, and BoxGeometry::type().
The documentation for this class was generated from the following files:
lees_edwards.hpp
integrate.cpp