ESPResSo: CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig > Class Template Reference
CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig > Class Template Reference
#include <p3m_heffte.impl.hpp>
Public Member Functions
CoulombTuningAlgorithm (System::System &system, auto &input_p3m, double prefactor, int timings, decltype(m_tune_limits) tune_limits)
void on_solver_change () const override
void setup_logger (bool verbose) override
std::optional< std::string > layer_correction_veto_r_cut (double r_cut) const override
std::optional< std::string > fft_decomposition_veto (Utils::Vector3i const &mesh_size_r_space) const override
std::tuple< double, double, double, double > calculate_accuracy (Utils::Vector3i const &mesh, int cao, double r_cut_iL) const override
void determine_mesh_limits () override
TuningAlgorithm::Parameters get_time () override
Public Member Functions inherited from TuningAlgorithm
TuningAlgorithm (System::System &system, double prefactor, int timings)
virtual ~TuningAlgorithm ()=default
void determine_r_cut_limits ()
Determine a sensible range for the real-space cutoff.
void determine_cao_limits (int initial_cao)
Determine a sensible range for the charge assignment order.
void commit (Utils::Vector3i const &mesh, int cao, double r_cut_iL, double alpha_L)
Write tuned parameters to the P3M parameter struct.
void tune ()
Protected Member Functions
P3MParameters & get_params () override
Protected Member Functions inherited from TuningAlgorithm
auto get_n_trials ()
void increment_n_trials ()
void reset_n_trials ()
double get_m_time (Utils::Vector3i const &mesh, int &tuned_cao, double &tuned_r_cut_iL, double &tuned_alpha_L, double &tuned_accuracy)
Get the optimal alpha and the corresponding computation time for a fixed mesh.
double get_mc_time (Utils::Vector3i const &mesh, int cao, double &tuned_r_cut_iL, double &tuned_alpha_L, double &tuned_accuracy)
Get the optimal alpha and the corresponding computation time for a fixed mesh and cao.
Static Protected Member Functions
static constexpr std::tuple< int, int, int > get_memory_layout ()
Additional Inherited Members
Protected Attributes inherited from TuningAlgorithm
System::System & m_system
double m_prefactor
std::unique_ptr< TuningLogger > m_logger = nullptr
int cao_min = -1
int cao_max = -1
int cao_best = -1
double m_r_cut_iL_min = -1.
double m_r_cut_iL_max = -1.
Static Protected Attributes inherited from TuningAlgorithm
static auto constexpr time_granularity = 5.
Granularity of the time measurement (milliseconds).
static auto constexpr max_n_consecutive_trials = 40
Maximal number of consecutive trials that don't improve runtime.
static auto constexpr time_sentinel = std::numeric_limits<double>::max()
Value for invalid time measurements.
Detailed Description
template<typename FloatType, Arch Architecture, class FFTConfig>
class CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >
Definition at line 839 of file p3m_heffte.impl.hpp.
Constructor & Destructor Documentation
CoulombTuningAlgorithm()
template<typename FloatType , Arch Architecture, class FFTConfig > CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::CoulombTuningAlgorithm (System::System & system, auto & input_p3m, double prefactor, int timings, decltype(m_tune_limits) tune_limits) inline
Definition at line 859 of file p3m_heffte.impl.hpp.
Member Function Documentation
calculate_accuracy()
template<typename FloatType , Arch Architecture, class FFTConfig > std::tuple< double, double, double, double > CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::calculate_accuracy (Utils::Vector3i const & mesh, int cao, double r_cut_iL) const inline override virtual
Implements TuningAlgorithm.
Definition at line 933 of file p3m_heffte.impl.hpp.
References P3MParameters::accuracy, comm_cart, CUDA, Utils::Vector< T, N >::data(), Utils::Vector< T, N >::norm(), p3m_k_space_error(), p3m_k_space_error_gpu(), p3m_real_space_error(), P3MStateCommon< FloatType >::params, stream, CoulombP3MState< FloatType, FFTConfig >::sum_q2, CoulombP3MState< FloatType, FFTConfig >::sum_qpart, and this_node.
determine_mesh_limits()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::determine_mesh_limits () inline override virtual
Implements TuningAlgorithm.
Definition at line 973 of file p3m_heffte.impl.hpp.
References Utils::Vector< T, N >::broadcast(), P3MParameters::mesh, P3MStateCommon< FloatType >::params, stream, and CoulombP3MState< FloatType, FFTConfig >::sum_qpart.
fft_decomposition_veto()
template<typename FloatType , Arch Architecture, class FFTConfig > std::optional< std::string > CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::fft_decomposition_veto (Utils::Vector3i const & mesh_size_r_space) const inline override virtual
Reimplemented from TuningAlgorithm.
Definition at line 891 of file p3m_heffte.impl.hpp.
References comm_cart, CUDA, CoulombP3MState< FloatType, FFTConfig >::fft, CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::get_memory_layout(), and stream.
get_memory_layout()
template<typename FloatType , Arch Architecture, class FFTConfig > static constexpr std::tuple< int, int, int > CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::get_memory_layout () inline static constexpr protected
Definition at line 850 of file p3m_heffte.impl.hpp.
References stream.
Referenced by CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::fft_decomposition_veto().
get_params()
template<typename FloatType , Arch Architecture, class FFTConfig > P3MParameters & CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::get_params () inline override protected virtual
Implements TuningAlgorithm.
Definition at line 848 of file p3m_heffte.impl.hpp.
References P3MStateCommon< FloatType >::params.
get_time()
template<typename FloatType , Arch Architecture, class FFTConfig > TuningAlgorithm::Parameters CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::get_time () inline override virtual
Implements TuningAlgorithm.
Definition at line 1016 of file p3m_heffte.impl.hpp.
References Utils::Vector< T, N >::broadcast(), P3MParameters::mesh, TuningAlgorithm::Parameters::mesh, P3MStateCommon< FloatType >::params, and stream.
layer_correction_veto_r_cut()
template<typename FloatType , Arch Architecture, class FFTConfig > std::optional< std::string > CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::layer_correction_veto_r_cut (double r_cut) const inline override virtual
Implements TuningAlgorithm.
Definition at line 883 of file p3m_heffte.impl.hpp.
References System::System::coulomb, Coulomb::Solver::impl, TuningAlgorithm::m_system, and stream.
on_solver_change()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::on_solver_change () const inline override virtual
Implements TuningAlgorithm.
Definition at line 865 of file p3m_heffte.impl.hpp.
References TuningAlgorithm::m_system, and System::System::on_coulomb_change().
setup_logger()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::setup_logger (bool verbose) inline override virtual
Implements TuningAlgorithm.
Definition at line 867 of file p3m_heffte.impl.hpp.
References P3MParameters::accuracy, System::System::box_geo, TuningLogger::Coulomb, CUDA, TuningAlgorithm::m_logger, TuningAlgorithm::m_prefactor, TuningAlgorithm::m_system, P3MStateCommon< FloatType >::params, stream, CoulombP3MState< FloatType, FFTConfig >::sum_q2, CoulombP3MState< FloatType, FFTConfig >::sum_qpart, and this_node.
The documentation for this class was generated from the following file:
p3m_heffte.impl.hpp