ESPResSo: walberla::pystencils::FrictionCouplingKernel_double_precision Class Reference
walberla::pystencils::FrictionCouplingKernel_double_precision Class Reference
#include <FrictionCouplingKernel_double_precision.h>
Public Member Functions
FrictionCouplingKernel_double_precision (BlockDataID fID_, BlockDataID jID_, double D, double kT, double rho_lb)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getD () const
double getKt () const
double getRho_lb () const
void setD (const double value)
void setKt (const double value)
void setRho_lb (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< FrictionCouplingKernel_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< FrictionCouplingKernel_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file FrictionCouplingKernel_double_precision.h.
Constructor & Destructor Documentation
FrictionCouplingKernel_double_precision()
walberla::pystencils::FrictionCouplingKernel_double_precision::FrictionCouplingKernel_double_precision (BlockDataID fID_, BlockDataID jID_, double D, double kT, double rho_lb) inline
Definition at line 55 of file FrictionCouplingKernel_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::FrictionCouplingKernel_double_precision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file FrictionCouplingKernel_double_precision.h.
getD()
double walberla::pystencils::FrictionCouplingKernel_double_precision::getD () const inline
Definition at line 97 of file FrictionCouplingKernel_double_precision.h.
getKt()
double walberla::pystencils::FrictionCouplingKernel_double_precision::getKt () const inline
Definition at line 98 of file FrictionCouplingKernel_double_precision.h.
getRho_lb()
double walberla::pystencils::FrictionCouplingKernel_double_precision::getRho_lb () const inline
Definition at line 99 of file FrictionCouplingKernel_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_double_precision::getSweep () inline
Definition at line 81 of file FrictionCouplingKernel_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_double_precision::getSweep (const shared_ptr< FrictionCouplingKernel_double_precision > & kernel) inline static
Definition at line 68 of file FrictionCouplingKernel_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_double_precision::getSweepOnCellInterval (const shared_ptr< FrictionCouplingKernel_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file FrictionCouplingKernel_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file FrictionCouplingKernel_double_precision.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::FrictionCouplingKernel_double_precision::operator() (IBlock * block) inline
Definition at line 65 of file FrictionCouplingKernel_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::FrictionCouplingKernel_double_precision::run (IBlock * block)
Definition at line 62 of file FrictionCouplingKernel_double_precision.cpp.
References block(), walberla::pystencils::internal_828cb3fbc90c26a23ae54639862a1401::frictioncouplingkernel_double_precision_frictioncouplingkernel_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::FrictionCouplingKernel_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 91 of file FrictionCouplingKernel_double_precision.cpp.
References block(), walberla::pystencils::internal_828cb3fbc90c26a23ae54639862a1401::frictioncouplingkernel_double_precision_frictioncouplingkernel_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setD()
void walberla::pystencils::FrictionCouplingKernel_double_precision::setD (const double value) inline
Definition at line 100 of file FrictionCouplingKernel_double_precision.h.
setKt()
void walberla::pystencils::FrictionCouplingKernel_double_precision::setKt (const double value) inline
Definition at line 101 of file FrictionCouplingKernel_double_precision.h.
setRho_lb()
void walberla::pystencils::FrictionCouplingKernel_double_precision::setRho_lb (const double value) inline
Definition at line 102 of file FrictionCouplingKernel_double_precision.h.
The documentation for this class was generated from the following files:
FrictionCouplingKernel_double_precision.h
FrictionCouplingKernel_double_precision.cpp