ESPResSo: EspressoSystemInterface Class Reference
EspressoSystemInterface Class Reference
CUDA implementation of SystemInterface.
#include <EspressoSystemInterface.hpp>
Public Member Functions
EspressoSystemInterface ()=default
~EspressoSystemInterface () override=default
void init () override
void update () override
float * rGpuBegin () override
bool hasRGpu () override
void requestRGpu () override
float * dipGpuBegin () override
bool hasDipGpu () override
void requestDipGpu () override
float * qGpuBegin () override
bool hasQGpu () override
void requestQGpu () override
void requestParticleStructGpu ()
void requestParticleStructGpuParallel ()
float * fGpuBegin () override
bool hasFGpu () override
void requestFGpu () override
float * torqueGpuBegin () override
bool hasTorqueGpu () override
void requestTorqueGpu () override
float * eGpu () override
Utils::Vector3d box () const override
std::size_t npart_gpu () const override
Public Member Functions inherited from SystemInterface
SystemInterface ()=default
virtual ~SystemInterface ()=default
Static Public Member Functions
static EspressoSystemInterface & Instance ()
Protected Member Functions
void gatherParticles ()
void split_particle_struct ()
void enableParticleCommunication ()
void enableParticleCommunicationParallel ()
void reallocDeviceMemory (std::size_t n)
Static Protected Attributes
static EspressoSystemInterface * m_instance = nullptr
Detailed Description
CUDA implementation of SystemInterface.
When data is synchronized between host and device memory, a subset of the Particle struct is copied from each particle on the host to the corresponding CUDA_particle_data struct on the device via EspressoSystemInterface::gatherParticles(). Once the transfer is complete, the particle AoS on the device is copied (or "split") to a SoA via EspressoSystemInterface::split_particle_struct().
Definition at line 40 of file EspressoSystemInterface.hpp.
Constructor & Destructor Documentation
EspressoSystemInterface()
EspressoSystemInterface::EspressoSystemInterface () default
Referenced by Instance().
~EspressoSystemInterface()
EspressoSystemInterface::~EspressoSystemInterface () override default
Member Function Documentation
box()
Utils::Vector3d EspressoSystemInterface::box () const override virtual
Implements SystemInterface.
Definition at line 69 of file EspressoSystemInterface.cpp.
References box_geo, and BoxGeometry::length().
dipGpuBegin()
float* EspressoSystemInterface::dipGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 66 of file EspressoSystemInterface.hpp.
eGpu()
float* EspressoSystemInterface::eGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 117 of file EspressoSystemInterface.hpp.
References gpu_get_energy_pointer().
Referenced by CoulombMMM1DGpu::add_long_range_energy().
enableParticleCommunication()
void EspressoSystemInterface::enableParticleCommunication () protected
Definition at line 44 of file EspressoSystemInterface.cpp.
References cuda_bcast_global_part_params(), gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_pointer(), gpu_init_particle_comm(), reallocDeviceMemory(), and this_node.
Referenced by requestDipGpu(), requestFGpu(), requestParticleStructGpu(), requestQGpu(), requestRGpu(), and requestTorqueGpu().
enableParticleCommunicationParallel()
void EspressoSystemInterface::enableParticleCommunicationParallel () protected
Definition at line 54 of file EspressoSystemInterface.cpp.
References cuda_bcast_global_part_params_parallel(), gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_pointer(), gpu_init_particle_comm(), reallocDeviceMemory(), and this_node.
Referenced by requestParticleStructGpuParallel().
fGpuBegin()
float* EspressoSystemInterface::fGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 99 of file EspressoSystemInterface.hpp.
References gpu_get_particle_force_pointer().
Referenced by CoulombMMM1DGpu::add_long_range_forces().
gatherParticles()
void EspressoSystemInterface::gatherParticles () protected
Definition at line 30 of file EspressoSystemInterface.cpp.
References cell_structure, copy_part_data_to_gpu(), gpu_get_global_particle_vars_pointer_host(), gpu_get_particle_pointer(), CellStructure::local_particles(), reallocDeviceMemory(), split_particle_struct(), and this_node.
Referenced by init(), and update().
hasDipGpu()
bool EspressoSystemInterface::hasDipGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 67 of file EspressoSystemInterface.hpp.
Referenced by requestDipGpu().
hasFGpu()
bool EspressoSystemInterface::hasFGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 100 of file EspressoSystemInterface.hpp.
Referenced by requestFGpu().
hasQGpu()
bool EspressoSystemInterface::hasQGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 78 of file EspressoSystemInterface.hpp.
Referenced by requestQGpu().
hasRGpu()
bool EspressoSystemInterface::hasRGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 57 of file EspressoSystemInterface.hpp.
Referenced by requestRGpu().
hasTorqueGpu()
bool EspressoSystemInterface::hasTorqueGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 109 of file EspressoSystemInterface.hpp.
Referenced by requestTorqueGpu().
init()
void EspressoSystemInterface::init () override virtual
Implements SystemInterface.
Definition at line 65 of file EspressoSystemInterface.cpp.
References gatherParticles().
Referenced by CoulombMMM1DGpu::tune().
Instance()
static EspressoSystemInterface& EspressoSystemInterface::Instance () inline static
Definition at line 45 of file EspressoSystemInterface.hpp.
References EspressoSystemInterface(), and m_instance.
Referenced by DipolarDirectSumGpu::add_long_range_forces(), DipolarBarnesHutGpu::add_long_range_forces(), calculate_energy_local(), cuda_bcast_global_part_params_local(), cuda_bcast_global_part_params_parallel(), force_calc(), DipolarDirectSumGpu::long_range_energy(), DipolarBarnesHutGpu::long_range_energy(), p3m_gpu_init(), CoulombP3MGPU::request_gpu(), and CoulombMMM1DGpu::tune().
npart_gpu()
std::size_t EspressoSystemInterface::npart_gpu () const inline override virtual
Reimplemented from SystemInterface.
Definition at line 127 of file EspressoSystemInterface.hpp.
References gpu_get_particle_pointer().
Referenced by CoulombMMM1DGpu::add_long_range_energy(), and CoulombMMM1DGpu::add_long_range_forces().
qGpuBegin()
float* EspressoSystemInterface::qGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 77 of file EspressoSystemInterface.hpp.
Referenced by CoulombMMM1DGpu::add_long_range_energy(), and CoulombMMM1DGpu::add_long_range_forces().
reallocDeviceMemory()
void EspressoSystemInterface::reallocDeviceMemory (std::size_t n) protected
Definition at line 102 of file EspressoSystemInterface_cuda.cu.
References cuda_safe_mem.
Referenced by enableParticleCommunication(), enableParticleCommunicationParallel(), and gatherParticles().
requestDipGpu()
void EspressoSystemInterface::requestDipGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 68 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), and hasDipGpu().
requestFGpu()
void EspressoSystemInterface::requestFGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 101 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), and hasFGpu().
requestParticleStructGpu()
void EspressoSystemInterface::requestParticleStructGpu () inline
Definition at line 87 of file EspressoSystemInterface.hpp.
References enableParticleCommunication().
Referenced by cuda_bcast_global_part_params_local().
requestParticleStructGpuParallel()
void EspressoSystemInterface::requestParticleStructGpuParallel () inline
Definition at line 93 of file EspressoSystemInterface.hpp.
References enableParticleCommunicationParallel().
Referenced by cuda_bcast_global_part_params_parallel().
requestQGpu()
void EspressoSystemInterface::requestQGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 79 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), and hasQGpu().
requestRGpu()
void EspressoSystemInterface::requestRGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 58 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), and hasRGpu().
requestTorqueGpu()
void EspressoSystemInterface::requestTorqueGpu () inline override virtual
Reimplemented from SystemInterface.
Definition at line 110 of file EspressoSystemInterface.hpp.
References enableParticleCommunication(), and hasTorqueGpu().
rGpuBegin()
float* EspressoSystemInterface::rGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 56 of file EspressoSystemInterface.hpp.
Referenced by CoulombMMM1DGpu::add_long_range_energy(), and CoulombMMM1DGpu::add_long_range_forces().
split_particle_struct()
void EspressoSystemInterface::split_particle_struct () protected
Definition at line 126 of file EspressoSystemInterface_cuda.cu.
References block(), gpu_get_particle_pointer(), split_kernel_dip(), split_kernel_q(), split_kernel_r(), and split_kernel_rq().
Referenced by gatherParticles().
torqueGpuBegin()
float* EspressoSystemInterface::torqueGpuBegin () inline override virtual
Reimplemented from SystemInterface.
Definition at line 108 of file EspressoSystemInterface.hpp.
References gpu_get_particle_torque_pointer().
update()
void EspressoSystemInterface::update () override virtual
Implements SystemInterface.
Definition at line 67 of file EspressoSystemInterface.cpp.
References gatherParticles().
Member Data Documentation
m_instance
EspressoSystemInterface * EspressoSystemInterface::m_instance = nullptr static protected
Definition at line 136 of file EspressoSystemInterface.hpp.
Referenced by Instance().
The documentation for this class was generated from the following files:
EspressoSystemInterface.hpp
EspressoSystemInterface.cpp
EspressoSystemInterface_cuda.cu