ESPResSo: Observables::ProfileObservable Class Reference
Observables::ProfileObservable Class Reference
Cartesian profile observable.
#include <ProfileObservable.hpp>
Public Member Functions
ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
std::vector< std::size_t > shape () const override
auto n_bins () const
auto limits () const
std::array< std::vector< double >, 3 > edges () const
Calculate the bin edges for each dimension.
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
virtual std::vector< double > operator() (boost::mpi::communicator const &comm) const =0
Calculate the set of values measured by the observable.
std::size_t n_values () const
Size of the flat array returned by the observable.
Detailed Description
Cartesian profile observable.
Definition at line 36 of file core/observables/ProfileObservable.hpp.
Constructor & Destructor Documentation
ProfileObservable()
Observables::ProfileObservable::ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z) inline
Definition at line 44 of file core/observables/ProfileObservable.hpp.
References stream.
Member Function Documentation
edges()
std::array< std::vector< double >, 3 > Observables::ProfileObservable::edges () const inline
Calculate the bin edges for each dimension.
Definition at line 75 of file core/observables/ProfileObservable.hpp.
References Utils::make_lin_space(), and stream.
limits()
auto Observables::ProfileObservable::limits () const inline
Definition at line 72 of file core/observables/ProfileObservable.hpp.
Referenced by Observables::CylindricalLBProfileObservable::calculate_sampling_positions(), Observables::CylindricalDensityProfile::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::DensityProfile::evaluate(), Observables::FluxDensityProfile::evaluate(), Observables::ForceDensityProfile::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfile::operator()(), and Observables::LBVelocityProfile::operator()().
n_bins()
auto Observables::ProfileObservable::n_bins () const inline
Definition at line 70 of file core/observables/ProfileObservable.hpp.
Referenced by Observables::CylindricalLBProfileObservable::calculate_sampling_positions(), Observables::CylindricalDensityProfile::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::DensityProfile::evaluate(), Observables::FluxDensityProfile::evaluate(), Observables::ForceDensityProfile::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfile::operator()(), Observables::LBVelocityProfile::operator()(), Observables::CylindricalFluxDensityProfile::shape(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::shape(), Observables::CylindricalLBVelocityProfile::shape(), Observables::CylindricalLBVelocityProfileAtParticlePositions::shape(), Observables::CylindricalVelocityProfile::shape(), Observables::FluxDensityProfile::shape(), Observables::ForceDensityProfile::shape(), and Observables::LBVelocityProfile::shape().
shape()
std::vector< std::size_t > Observables::ProfileObservable::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 66 of file core/observables/ProfileObservable.hpp.
The documentation for this class was generated from the following file:
core/observables/ProfileObservable.hpp