ESPResSo: walberla::pystencils::Dirichlet_single_precision Class Reference
walberla::pystencils::Dirichlet_single_precision Class Reference
#include <Dirichlet_single_precision.h>
Classes
struct IndexInfo
class IndexVectors
Public Member Functions
Dirichlet_single_precision (const std::shared_ptr< StructuredBlockForest > &blocks, BlockDataID fieldID_, std::function< float(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> &dirichletCallback)
void run (IBlock *block)
void operator() (IBlock *block)
void inner (IBlock *block)
void outer (IBlock *block)
Vector3< float > getForce (IBlock *)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getInnerSweep ()
std::function< void(IBlock *)> getOuterSweep ()
template<typename FlagField_T >
void fillFromFlagField (const std::shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (const shared_ptr< StructuredBlockForest > &blocks, IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
Public Attributes
BlockDataID fieldID
Detailed Description
Definition at line 52 of file Dirichlet_single_precision.h.
Constructor & Destructor Documentation
Dirichlet_single_precision()
walberla::pystencils::Dirichlet_single_precision::Dirichlet_single_precision (const std::shared_ptr< StructuredBlockForest > & blocks, BlockDataID fieldID_, std::function< float(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> & dirichletCallback) inline
Definition at line 91 of file Dirichlet_single_precision.h.
References stream.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::pystencils::Dirichlet_single_precision::fillFromFlagField (const shared_ptr< StructuredBlockForest > & blocks, IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 142 of file Dirichlet_single_precision.h.
References walberla::pystencils::Dirichlet_single_precision::IndexVectors::ALL, block(), walberla::pystencils::Dirichlet_single_precision::IndexVectors::indexVector(), walberla::pystencils::Dirichlet_single_precision::IndexVectors::INNER, inner(), walberla::pystencils::Dirichlet_single_precision::IndexVectors::OUTER, and stream.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::pystencils::Dirichlet_single_precision::fillFromFlagField (const std::shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 133 of file Dirichlet_single_precision.h.
References block(), and stream.
getForce()
Vector3< float > walberla::pystencils::Dirichlet_single_precision::getForce (IBlock *) inline
Definition at line 113 of file Dirichlet_single_precision.h.
References stream.
getInnerSweep()
std::function< void(IBlock *)> walberla::pystencils::Dirichlet_single_precision::getInnerSweep () inline
Definition at line 124 of file Dirichlet_single_precision.h.
References inner().
getOuterSweep()
std::function< void(IBlock *)> walberla::pystencils::Dirichlet_single_precision::getOuterSweep () inline
Definition at line 128 of file Dirichlet_single_precision.h.
References outer().
getSweep()
std::function< void(IBlock *)> walberla::pystencils::Dirichlet_single_precision::getSweep () inline
Definition at line 120 of file Dirichlet_single_precision.h.
References run().
inner()
void walberla::pystencils::Dirichlet_single_precision::inner (IBlock * block)
Definition at line 94 of file Dirichlet_single_precision.cpp.
References block(), and walberla::pystencils::Dirichlet_single_precision::IndexVectors::INNER.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::pystencils::Dirichlet_single_precision::operator() (IBlock * block) inline
Definition at line 107 of file Dirichlet_single_precision.h.
References block(), and run().
outer()
void walberla::pystencils::Dirichlet_single_precision::outer (IBlock * block)
Definition at line 98 of file Dirichlet_single_precision.cpp.
References block(), and walberla::pystencils::Dirichlet_single_precision::IndexVectors::OUTER.
Referenced by getOuterSweep().
run()
void walberla::pystencils::Dirichlet_single_precision::run (IBlock * block)
Definition at line 90 of file Dirichlet_single_precision.cpp.
References walberla::pystencils::Dirichlet_single_precision::IndexVectors::ALL, and block().
Referenced by getSweep(), and operator()().
Member Data Documentation
fieldID
BlockDataID walberla::pystencils::Dirichlet_single_precision::fieldID
Definition at line 202 of file Dirichlet_single_precision.h.
The documentation for this class was generated from the following files:
Dirichlet_single_precision.h
Dirichlet_single_precision.cpp