ESPResSo: Observables::FluxDensityProfile Class Reference
Observables::FluxDensityProfile Class Reference
#include <FluxDensityProfile.hpp>
Public Member Functions
std::vector< std::size_t > shape () const override
std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, const ParticleObservables::traits< Particle > &traits) const override
PidProfileObservable (std::vector< int > const &ids, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
Public Member Functions inherited from Observables::PidProfileObservable
PidProfileObservable (std::vector< int > const &ids, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > const & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Public Member Functions inherited from Observables::ProfileObservable
ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
std::vector< std::size_t > shape () const override
auto n_bins () const
auto limits () const
std::array< std::vector< double >, 3 > edges () const
Calculate the bin edges for each dimension.
Detailed Description
Definition at line 35 of file FluxDensityProfile.hpp.
Member Function Documentation
evaluate()
std::vector< double > Observables::FluxDensityProfile::evaluate (boost::mpi::communicator const & comm, ParticleReferenceRange const & local_particles, const ParticleObservables::traits< Particle > & traits) const inline override virtual
Implements Observables::PidObservable.
Definition at line 44 of file FluxDensityProfile.hpp.
References System::System::box_geo, System::get_system(), Observables::ProfileObservable::limits(), Observables::ProfileObservable::n_bins(), and stream.
PidProfileObservable()
Observables::PidProfileObservable::PidProfileObservable (std::vector< int > const & ids, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z) inline
Definition at line 32 of file core/observables/PidProfileObservable.hpp.
shape()
std::vector< std::size_t > Observables::FluxDensityProfile::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 38 of file FluxDensityProfile.hpp.
References Observables::ProfileObservable::n_bins().
The documentation for this class was generated from the following file:
FluxDensityProfile.hpp