ESPResSo: ScriptInterface::ObjectHandle Class Reference
ScriptInterface::ObjectHandle Class Reference
Base class for interface handles.
#include <ObjectHandle.hpp>
Public Member Functions
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
virtual void do_construct (VariantMap const &params)
VariantMap get_parameters () const
Get current parameters.
virtual std::vector< std::string_view > valid_parameters () const
Get required and optional parameters for class.
virtual bool has_parameter (std::string const &needle) const
virtual Variant get_parameter (std::string const &name) const
Get single parameter.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
virtual void do_set_parameter (const std::string &, const Variant &)
Local implementation of set_parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
virtual Variant do_call_method (const std::string &, const VariantMap &)
Local implementation of call_method.
std::string serialize () const
virtual std::vector< std::pair< std::string, Variant > > serialize_parameters () const
Serialize parameters.
Static Public Member Functions
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Private Member Functions
virtual std::string get_internal_state () const
virtual void set_internal_state (std::string const &)
Friends
class Context
Detailed Description
Base class for interface handles.
Definition at line 37 of file ObjectHandle.hpp.
Constructor & Destructor Documentation
ObjectHandle() [1/2]
ScriptInterface::ObjectHandle::ObjectHandle () default
ObjectHandle() [2/2]
ScriptInterface::ObjectHandle::ObjectHandle (ObjectHandle const &) delete
~ObjectHandle()
virtual ScriptInterface::ObjectHandle::~ObjectHandle () virtual default
Member Function Documentation
call_method()
Variant ScriptInterface::ObjectHandle::call_method (const std::string & name, const VariantMap & params)
Call a method on the object.
Can only be called on the head node.
Definition at line 55 of file ObjectHandle.cpp.
References do_call_method(), fe_trap::make_shared_scoped(), name(), and stream.
Referenced by ScriptInterface::Interactions::NonBondedInteractions::do_call_method(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_call_method(), ScriptInterface::System::set_bonds(), ScriptInterface::System::set_exclusions(), ScriptInterface::Accumulators::AccumulatorBase::set_internal_state(), and ScriptInterface::Interactions::NonBondedInteractions::set_internal_state().
construct()
void ScriptInterface::ObjectHandle::construct (VariantMap const & params) inline
Construct the handled object.
This function is called on object creation with user provided parameters. This can be used if the SO has required parameters, it represents some type that can not reasonably be default constructed, or if the core implementation has to be chosen by a parameter. It is guaranteed that no getter or setter functions from this interface is called before construction (only name() and valid_parameters()), and it is only called once.
The default implementation just calls set_parameter for every parameter.
Parameters
params The parameters to the constructor. Only parameters that are valid for a default-constructed object are valid.
Definition at line 77 of file ObjectHandle.hpp.
References do_construct().
context()
Context * ScriptInterface::ObjectHandle::context () const inline
Responsible context.
Definition at line 57 of file ObjectHandle.hpp.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), ScriptInterface::Coulomb::Container::Container(), ScriptInterface::LB::Container::Container(), ScriptInterface::System::CudaInitHandle::CudaInitHandle(), ScriptInterface::Observables::Observable::do_call_method(), ScriptInterface::Accumulators::ContactTimes::do_call_method(), ScriptInterface::Accumulators::Correlator::do_call_method(), ScriptInterface::Accumulators::MeanVarianceCalculator::do_call_method(), ScriptInterface::Accumulators::TimeSeries::do_call_method(), ScriptInterface::ClusterAnalysis::ClusterStructure::do_call_method(), ScriptInterface::walberla::EKIndexedReaction::do_call_method(), ScriptInterface::Interactions::NonBondedInteractions::do_call_method(), ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method(), ScriptInterface::Coulomb::ICCStar::do_call_method(), ScriptInterface::walberla::VTKHandleBase< Field >::do_call_method(), ScriptInterface::Analysis::Analysis::do_call_method(), ScriptInterface::Particles::Polymer::do_call_method(), ScriptInterface::System::CudaInitHandle::do_call_method(), ScriptInterface::CellSystem::CellSystem::do_call_method(), ScriptInterface::Coulomb::CoulombScafacos::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_call_method(), ScriptInterface::LeesEdwards::LeesEdwards::do_call_method(), ScriptInterface::Particles::ParticleList::do_call_method(), ScriptInterface::Particles::ParticleSlice::do_call_method(), ScriptInterface::ReactionMethods::ReactionAlgorithm::do_call_method(), ScriptInterface::ReactionMethods::WidomInsertion::do_call_method(), ScriptInterface::Thermostat::Thermostat::do_call_method(), ScriptInterface::walberla::EKPoissonSolverNode::do_call_method(), ScriptInterface::walberla::EKPoissonSolverSlice::do_call_method(), ScriptInterface::walberla::EKSpeciesNode::do_call_method(), ScriptInterface::walberla::EKSpeciesSlice::do_call_method(), ScriptInterface::walberla::LBFluid::do_call_method(), ScriptInterface::walberla::LBFluidNode::do_call_method(), ScriptInterface::walberla::LBFluidSlice::do_call_method(), ScriptInterface::Accumulators::Correlator::do_construct(), ScriptInterface::walberla::LatticeWalberla::do_construct(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct(), ScriptInterface::Accumulators::ContactTimes::do_construct(), ScriptInterface::Coulomb::CoulombMMM1D::do_construct(), ScriptInterface::Coulomb::CoulombP3M::do_construct(), ScriptInterface::Coulomb::CoulombScafacos::do_construct(), ScriptInterface::Coulomb::DebyeHueckel::do_construct(), ScriptInterface::Coulomb::ElectrostaticLayerCorrection::do_construct(), ScriptInterface::Coulomb::ICCStar::do_construct(), ScriptInterface::Coulomb::ReactionField::do_construct(), ScriptInterface::Interactions::BondedInteraction::do_construct(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_construct(), ScriptInterface::Dipoles::DipolarDirectSum::do_construct(), ScriptInterface::Dipoles::DipolarLayerCorrection::do_construct(), ScriptInterface::Dipoles::DipolarP3M< Architecture >::do_construct(), ScriptInterface::Dipoles::DipolarScafacos::do_construct(), ScriptInterface::Observables::CylindricalLBProfileObservable< CoreCylLBObs >::do_construct(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct(), ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_construct(), ScriptInterface::Observables::PairwiseDistances< CoreObs >::do_construct(), ScriptInterface::Observables::PidObservable< CorePidObs >::do_construct(), ScriptInterface::Observables::PidProfileObservable< CoreObs >::do_construct(), ScriptInterface::Particles::ParticleSlice::do_construct(), ScriptInterface::ReactionMethods::ConstantpHEnsemble::do_construct(), ScriptInterface::ReactionMethods::ReactionEnsemble::do_construct(), ScriptInterface::ReactionMethods::SingleReaction::do_construct(), ScriptInterface::ReactionMethods::WidomInsertion::do_construct(), ScriptInterface::walberla::EKSpecies::do_construct(), ScriptInterface::walberla::LBFluid::do_construct(), ScriptInterface::walberla::VTKHandleBase< Field >::do_construct(), ScriptInterface::walberla::EKSpecies::EKSpecies(), ScriptInterface::walberla::EKSpecies::flux_boundary_ghost_layer_size_sanity_check(), ScriptInterface::Thermostat::Interface< CoreClass >::get_member_handle(), ScriptInterface::ReactionMethods::ReactionAlgorithm::get_reaction_index(), ScriptInterface::Integrators::Integrator::integrate(), ScriptInterface::Integrators::IntegratorHandle::IntegratorHandle(), ScriptInterface::Thermostat::Interface< CoreClass >::Interface(), ScriptInterface::walberla::LBFluid::LBFluid(), ScriptInterface::Thermostat::LBThermostat::LBThermostat(), ScriptInterface::LeesEdwards::LeesEdwards::LeesEdwards(), ScriptInterface::Thermostat::Interface< CoreClass >::make_autogamma(), ScriptInterface::Thermostat::Interface< CoreClass >::make_autoparameter(), ScriptInterface::Integrators::IntegratorHandle::on_bind_system(), ScriptInterface::Thermostat::Thermostat::on_bind_system(), ScriptInterface::ReactionMethods::ReactionAlgorithm::ReactionAlgorithm(), ScriptInterface::walberla::LatticeSlice< FieldSerializer >::scatter_3d(), ScriptInterface::Interactions::NonBondedInteractions::set_internal_state(), ScriptInterface::Thermostat::Thermostat::setup_thermostat(), ScriptInterface::LatticeIndices::throw_invalid_index(), and ScriptInterface::ReactionMethods::WidomInsertion::WidomInsertion().
deserialize()
ObjectRef ScriptInterface::ObjectHandle::deserialize (const std::string & state, Context & ctx) static
Make object from serialized state.
Definition at line 95 of file ObjectHandle.cpp.
References stream.
Referenced by ScriptInterface::ContextManager::deserialize(), and ScriptInterface::Interactions::NonBondedInteractions::set_internal_state().
do_call_method()
virtual Variant ScriptInterface::ObjectHandle::do_call_method (const std::string & , const VariantMap &) inline virtual
Local implementation of call_method.
If not overridden by the implementation, this does nothing.
Reimplemented in ScriptInterface::Writer::H5md, ScriptInterface::Constraints::ExternalField< Coupling, Field >, ScriptInterface::Constraints::ExternalPotential< Coupling, Field >, ScriptInterface::Observables::Observable, ScriptInterface::Accumulators::AccumulatorBase, ScriptInterface::Accumulators::ContactTimes, ScriptInterface::Accumulators::Correlator, ScriptInterface::Accumulators::MeanVarianceCalculator, ScriptInterface::Accumulators::TimeSeries, ScriptInterface::ClusterAnalysis::Cluster, ScriptInterface::ClusterAnalysis::ClusterStructure, ScriptInterface::PairCriteria::PairCriterion, ScriptInterface::Profiler::Caliper, ScriptInterface::walberla::EKIndexedReaction, ScriptInterface::walberla::EKSpecies, ScriptInterface::Interactions::NonBondedInteractions, ScriptInterface::walberla::LatticeModel< Method, VTKHandle >, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >, ScriptInterface::walberla::LatticeModel<::walberla::PoissonSolver, EKPoissonVTKHandle >, ScriptInterface::Constraints::ShapeBasedConstraint, ScriptInterface::Coulomb::Container, ScriptInterface::Coulomb::ICCStar, ScriptInterface::LB::Container, ScriptInterface::Dipoles::Container, ScriptInterface::ReactionMethods::SingleReaction, ScriptInterface::walberla::VTKHandleBase< Field >, ScriptInterface::walberla::VTKHandleBase<::EKinWalberlaBase >, ScriptInterface::walberla::VTKHandleBase<::LBWalberlaBase >, ScriptInterface::walberla::VTKHandleBase<::walberla::PoissonSolver >, ScriptInterface::Analysis::Analysis, ScriptInterface::Analysis::ObservableStat, ScriptInterface::CodeInfo::CodeInfo, ScriptInterface::CodeInfo::CodeVersion, ScriptInterface::MPIIO::MPIIOScript, ScriptInterface::Particles::Polymer, ScriptInterface::System::CudaInitHandle, ScriptInterface::System::System, ScriptInterface::CellSystem::CellSystem, ScriptInterface::CellSystem::CheckpointerContext, ScriptInterface::Coulomb::Actor< SIClass, CoreClass >, ScriptInterface::Coulomb::Actor< CoulombMMM1D, ::CoulombMMM1D >, ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >, ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >, ScriptInterface::Coulomb::Actor< DebyeHueckel, ::DebyeHueckel >, ScriptInterface::Coulomb::Actor< ElectrostaticLayerCorrection, ::ElectrostaticLayerCorrection >, ScriptInterface::Coulomb::Actor< ReactionField, ::ReactionField >, ScriptInterface::Coulomb::CoulombScafacos, ScriptInterface::Galilei::Galilei, ScriptInterface::Integrators::Integrator, ScriptInterface::Interactions::BondedInteraction, ScriptInterface::Interactions::IBMVolCons, ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >, ScriptInterface::Interactions::InteractionPotentialInterface<::BMHTF_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Buckingham_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::DPD_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Gaussian_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::GayBerne_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Hat_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Hertzian_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJ_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJcos2_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJcos_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJGen_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Morse_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::SoftSphere_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >, ScriptInterface::Interactions::InteractionPotentialInterface<::Thole_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >, ScriptInterface::Interactions::InteractionWCA, ScriptInterface::Interactions::InteractionLJcos2, ScriptInterface::Interactions::InteractionTabulated, ScriptInterface::Interactions::NonBondedInteractionHandle, ScriptInterface::LeesEdwards::LeesEdwards, ScriptInterface::Dipoles::Actor< SIClass, CoreClass >, ScriptInterface::Dipoles::Actor< DipolarDirectSum, ::DipolarDirectSum >, ScriptInterface::Dipoles::Actor< DipolarLayerCorrection, ::DipolarLayerCorrection >, ScriptInterface::Dipoles::Actor< DipolarP3M< Architecture >, ::DipolarP3M >, ScriptInterface::Dipoles::Actor< DipolarScafacos, ::DipolarScafacos >, ScriptInterface::Dipoles::DipolarScafacos, ScriptInterface::Particles::ParticleHandle, ScriptInterface::Particles::ParticleModifier, ScriptInterface::Particles::ParticleList, ScriptInterface::Particles::ParticleSlice, ScriptInterface::ReactionMethods::ReactionAlgorithm, ScriptInterface::ReactionMethods::WidomInsertion, ScriptInterface::Shapes::Shape, ScriptInterface::Thermostat::Interface< CoreClass >, ScriptInterface::Thermostat::Interface<::BrownianThermostat >, ScriptInterface::Thermostat::Interface<::DPDThermostat >, ScriptInterface::Thermostat::Interface<::IsotropicNptThermostat >, ScriptInterface::Thermostat::Interface<::LangevinThermostat >, ScriptInterface::Thermostat::Interface<::LBThermostat >, ScriptInterface::Thermostat::Interface<::StokesianThermostat >, ScriptInterface::Thermostat::Interface<::ThermalizedBondThermostat >, ScriptInterface::Thermostat::Thermostat, ScriptInterface::walberla::EKPoissonSolverNode, ScriptInterface::walberla::EKPoissonSolverSlice, ScriptInterface::walberla::EKSpeciesNode, ScriptInterface::walberla::EKSpeciesSlice, ScriptInterface::walberla::LBFluid, ScriptInterface::walberla::LBFluidNode, and ScriptInterface::walberla::LBFluidSlice.
Definition at line 145 of file ObjectHandle.hpp.
References ScriptInterface::none.
Referenced by call_method().
do_construct()
virtual void ScriptInterface::ObjectHandle::do_construct (VariantMap const & params) inline virtual
Reimplemented in ScriptInterface::Analysis::Analysis, ScriptInterface::Galilei::Galilei, ScriptInterface::Interactions::NonBondedInteractions, ScriptInterface::Particles::ParticleList, ScriptInterface::Accumulators::Correlator, ScriptInterface::Constraints::ExternalField< Coupling, Field >, ScriptInterface::Constraints::ExternalPotential< Coupling, Field >, ScriptInterface::walberla::EKFFT, ScriptInterface::walberla::EKNone, ScriptInterface::walberla::EKReactant, ScriptInterface::walberla::EKBulkReaction, ScriptInterface::walberla::EKIndexedReaction, ScriptInterface::walberla::LatticeWalberla, ScriptInterface::MPIIO::MPIIOScript, ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >, ScriptInterface::Interactions::InteractionPotentialInterface<::BMHTF_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Buckingham_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::DPD_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Gaussian_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::GayBerne_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Hat_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Hertzian_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJ_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJcos2_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJcos_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::LJGen_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::Morse_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::SoftSphere_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >, ScriptInterface::Interactions::InteractionPotentialInterface<::Thole_Parameters >, ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >, ScriptInterface::Accumulators::ContactTimes, ScriptInterface::Accumulators::MeanVarianceCalculator, ScriptInterface::Accumulators::TimeSeries, ScriptInterface::CellSystem::CellSystem, ScriptInterface::CellSystem::CheckpointerContext, ScriptInterface::ClusterAnalysis::ClusterStructure, ScriptInterface::CollisionDetection::CollisionDetection, ScriptInterface::CollisionDetection::Protocol, ScriptInterface::Constraints::ShapeBasedConstraint, ScriptInterface::Coulomb::Container, ScriptInterface::Coulomb::CoulombMMM1D, ScriptInterface::Coulomb::CoulombP3M, ScriptInterface::Coulomb::CoulombScafacos, ScriptInterface::Coulomb::DebyeHueckel, ScriptInterface::Coulomb::ElectrostaticLayerCorrection, ScriptInterface::Coulomb::ICCStar, ScriptInterface::Coulomb::ReactionField, ScriptInterface::Galilei::ComFixed, ScriptInterface::Writer::H5md, ScriptInterface::Integrators::IntegratorHandle, ScriptInterface::Interactions::BondedInteraction, ScriptInterface::Interactions::NonBondedInteractionHandle, ScriptInterface::LB::Container, ScriptInterface::LeesEdwards::LeesEdwards, ScriptInterface::Dipoles::Container, ScriptInterface::Dipoles::DipolarDirectSum, ScriptInterface::Dipoles::DipolarLayerCorrection, ScriptInterface::Dipoles::DipolarP3M< Architecture >, ScriptInterface::Dipoles::DipolarScafacos, ScriptInterface::Math::CylindricalTransformationParameters, ScriptInterface::Particles::ParticleHandle, ScriptInterface::Particles::ParticleModifier, ScriptInterface::Particles::ParticleSlice, ScriptInterface::ReactionMethods::ConstantpHEnsemble, ScriptInterface::ReactionMethods::ReactionEnsemble, ScriptInterface::ReactionMethods::SingleReaction, ScriptInterface::ReactionMethods::WidomInsertion, ScriptInterface::Shapes::HollowConicalFrustum, ScriptInterface::System::System, ScriptInterface::Thermostat::Interface< CoreClass >, ScriptInterface::Thermostat::Interface<::BrownianThermostat >, ScriptInterface::Thermostat::Interface<::DPDThermostat >, ScriptInterface::Thermostat::Interface<::IsotropicNptThermostat >, ScriptInterface::Thermostat::Interface<::LangevinThermostat >, ScriptInterface::Thermostat::Interface<::LBThermostat >, ScriptInterface::Thermostat::Interface<::StokesianThermostat >, ScriptInterface::Thermostat::Interface<::ThermalizedBondThermostat >, ScriptInterface::Thermostat::Thermostat, ScriptInterface::walberla::EKPoissonSolverNode, ScriptInterface::walberla::EKPoissonSolverSlice, ScriptInterface::walberla::EKSpecies, ScriptInterface::walberla::EKSpeciesNode, ScriptInterface::walberla::EKSpeciesSlice, ScriptInterface::walberla::LBFluid, ScriptInterface::walberla::LBFluidNode, ScriptInterface::walberla::LBFluidSlice, ScriptInterface::walberla::VTKHandleBase< Field >, ScriptInterface::walberla::VTKHandleBase<::EKinWalberlaBase >, ScriptInterface::walberla::VTKHandleBase<::LBWalberlaBase >, and ScriptInterface::walberla::VTKHandleBase<::walberla::PoissonSolver >.
Definition at line 79 of file ObjectHandle.hpp.
References do_set_parameter(), and stream.
Referenced by ScriptInterface::CollisionDetection::CollisionDetection::attach(), construct(), and ScriptInterface::ClusterAnalysis::ClusterStructure::do_construct().
do_set_parameter()
virtual void ScriptInterface::ObjectHandle::do_set_parameter (const std::string & , const Variant &) inline virtual
Local implementation of set_parameter.
Reimplemented in ScriptInterface::AutoParameters< Derived, Base >, ScriptInterface::AutoParameters< AccumulatorBase >, ScriptInterface::AutoParameters< Actor< CoulombMMM1D, ::CoulombMMM1D >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombP3M, ::CoulombP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombScafacos, ::CoulombScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DebyeHueckel, ::DebyeHueckel >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarDirectSum, ::DipolarDirectSum >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarLayerCorrection, ::DipolarLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarP3M< Architecture >, ::DipolarP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarScafacos, ::DipolarScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ElectrostaticLayerCorrection, ::ElectrostaticLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ReactionField, ::ReactionField >, System::Leaf >, ScriptInterface::AutoParameters< Actor< SIClass, CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< BondedInteraction >, ScriptInterface::AutoParameters< BreakageSpec >, ScriptInterface::AutoParameters< CellSystem, System::Leaf >, ScriptInterface::AutoParameters< Cluster >, ScriptInterface::AutoParameters< ClusterStructure >, ScriptInterface::AutoParameters< CollisionDetection, System::Leaf >, ScriptInterface::AutoParameters< ComFixed, System::Leaf >, ScriptInterface::AutoParameters< Constraint >, ScriptInterface::AutoParameters< Container, System::Leaf >, ScriptInterface::AutoParameters< CudaInitHandle >, ScriptInterface::AutoParameters< CylindricalTransformationParameters >, ScriptInterface::AutoParameters< EKPoissonSolver >, ScriptInterface::AutoParameters< EKPoissonSolverNode, LatticeIndices >, ScriptInterface::AutoParameters< EKReaction, LatticeIndices >, ScriptInterface::AutoParameters< EKSpeciesNode, LatticeIndices >, ScriptInterface::AutoParameters< Galilei, System::Leaf >, ScriptInterface::AutoParameters< H5md >, ScriptInterface::AutoParameters< ICCStar, System::Leaf >, ScriptInterface::AutoParameters< IntegratorHandle, System::Leaf >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::BMHTF_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Buckingham_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::DPD_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Gaussian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::GayBerne_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hat_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hertzian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJ_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos2_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJGen_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Morse_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SmoothStep_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SoftSphere_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::TabulatedPotential > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Thole_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::WCA_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >, ScriptInterface::AutoParameters< Interface< ::BrownianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::DPDThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::IsotropicNptThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LangevinThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LBThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::StokesianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::ThermalizedBondThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::EKinWalberlaBase, EKVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::LBWalberlaBase, LBVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::walberla::PoissonSolver, EKPoissonVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeWalberla >, ScriptInterface::AutoParameters< LBFluidNode, LatticeIndices >, ScriptInterface::AutoParameters< LeesEdwards, System::Leaf >, ScriptInterface::AutoParameters< NonBondedInteractionHandle >, ScriptInterface::AutoParameters< PairCriterion >, ScriptInterface::AutoParameters< ParticleHandle >, ScriptInterface::AutoParameters< ParticleSlice >, ScriptInterface::AutoParameters< Polymer >, ScriptInterface::AutoParameters< Protocol >, ScriptInterface::AutoParameters< ReactionAlgorithm >, ScriptInterface::AutoParameters< Shape >, ScriptInterface::AutoParameters< SingleReaction >, ScriptInterface::AutoParameters< System >, ScriptInterface::AutoParameters< Thermostat, System::Leaf >, ScriptInterface::AutoParameters< VTKHandleBase< ::EKinWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::LBWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::walberla::PoissonSolver > >, ScriptInterface::AutoParameters< VTKHandleBase< Field > >, and ScriptInterface::AutoParameters<::walberla::EKReactant >.
Definition at line 131 of file ObjectHandle.hpp.
Referenced by do_construct(), and set_parameter().
get_internal_state()
virtual std::string ScriptInterface::ObjectHandle::get_internal_state () const inline private virtual
Reimplemented in ScriptInterface::Accumulators::AccumulatorBase, ScriptInterface::Interactions::NonBondedInteractions, ScriptInterface::ReactionMethods::ReactionAlgorithm, and ScriptInterface::System::System.
Definition at line 168 of file ObjectHandle.hpp.
get_parameter()
virtual Variant ScriptInterface::ObjectHandle::get_parameter (std::string const & name) const inline virtual
Get single parameter.
Parameters
name Name of the parameter
Returns
Value of parameter name
Reimplemented in ScriptInterface::AutoParameters< Derived, Base >, ScriptInterface::AutoParameters< AccumulatorBase >, ScriptInterface::AutoParameters< Actor< CoulombMMM1D, ::CoulombMMM1D >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombP3M, ::CoulombP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombScafacos, ::CoulombScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DebyeHueckel, ::DebyeHueckel >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarDirectSum, ::DipolarDirectSum >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarLayerCorrection, ::DipolarLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarP3M< Architecture >, ::DipolarP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarScafacos, ::DipolarScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ElectrostaticLayerCorrection, ::ElectrostaticLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ReactionField, ::ReactionField >, System::Leaf >, ScriptInterface::AutoParameters< Actor< SIClass, CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< BondedInteraction >, ScriptInterface::AutoParameters< BreakageSpec >, ScriptInterface::AutoParameters< CellSystem, System::Leaf >, ScriptInterface::AutoParameters< Cluster >, ScriptInterface::AutoParameters< ClusterStructure >, ScriptInterface::AutoParameters< CollisionDetection, System::Leaf >, ScriptInterface::AutoParameters< ComFixed, System::Leaf >, ScriptInterface::AutoParameters< Constraint >, ScriptInterface::AutoParameters< Container, System::Leaf >, ScriptInterface::AutoParameters< CudaInitHandle >, ScriptInterface::AutoParameters< CylindricalTransformationParameters >, ScriptInterface::AutoParameters< EKPoissonSolver >, ScriptInterface::AutoParameters< EKPoissonSolverNode, LatticeIndices >, ScriptInterface::AutoParameters< EKReaction, LatticeIndices >, ScriptInterface::AutoParameters< EKSpeciesNode, LatticeIndices >, ScriptInterface::AutoParameters< Galilei, System::Leaf >, ScriptInterface::AutoParameters< H5md >, ScriptInterface::AutoParameters< ICCStar, System::Leaf >, ScriptInterface::AutoParameters< IntegratorHandle, System::Leaf >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::BMHTF_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Buckingham_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::DPD_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Gaussian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::GayBerne_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hat_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hertzian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJ_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos2_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJGen_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Morse_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SmoothStep_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SoftSphere_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::TabulatedPotential > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Thole_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::WCA_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >, ScriptInterface::AutoParameters< Interface< ::BrownianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::DPDThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::IsotropicNptThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LangevinThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LBThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::StokesianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::ThermalizedBondThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::EKinWalberlaBase, EKVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::LBWalberlaBase, LBVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::walberla::PoissonSolver, EKPoissonVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeWalberla >, ScriptInterface::AutoParameters< LBFluidNode, LatticeIndices >, ScriptInterface::AutoParameters< LeesEdwards, System::Leaf >, ScriptInterface::AutoParameters< NonBondedInteractionHandle >, ScriptInterface::AutoParameters< PairCriterion >, ScriptInterface::AutoParameters< ParticleHandle >, ScriptInterface::AutoParameters< ParticleSlice >, ScriptInterface::AutoParameters< Polymer >, ScriptInterface::AutoParameters< Protocol >, ScriptInterface::AutoParameters< ReactionAlgorithm >, ScriptInterface::AutoParameters< Shape >, ScriptInterface::AutoParameters< SingleReaction >, ScriptInterface::AutoParameters< System >, ScriptInterface::AutoParameters< Thermostat, System::Leaf >, ScriptInterface::AutoParameters< VTKHandleBase< ::EKinWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::LBWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::walberla::PoissonSolver > >, ScriptInterface::AutoParameters< VTKHandleBase< Field > >, and ScriptInterface::AutoParameters<::walberla::EKReactant >.
Definition at line 117 of file ObjectHandle.hpp.
References name().
Referenced by get_parameters().
get_parameters()
VariantMap ScriptInterface::ObjectHandle::get_parameters () const inline
Get current parameters.
Returns
Parameters set in class.
Definition at line 90 of file ObjectHandle.hpp.
References get_parameter(), name(), stream, and valid_parameters().
Referenced by ScriptInterface::Dipoles::DipolarScafacos::DipolarScafacos(), ScriptInterface::CellSystem::CellSystem::do_call_method(), serialize_parameters(), and ScriptInterface::AutoParameters< Derived, Base >::serialize_parameters().
has_parameter()
virtual bool ScriptInterface::ObjectHandle::has_parameter (std::string const & needle) const inline virtual
Reimplemented in ScriptInterface::AutoParameters< Derived, Base >, ScriptInterface::AutoParameters< AccumulatorBase >, ScriptInterface::AutoParameters< Actor< CoulombMMM1D, ::CoulombMMM1D >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombP3M, ::CoulombP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombScafacos, ::CoulombScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DebyeHueckel, ::DebyeHueckel >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarDirectSum, ::DipolarDirectSum >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarLayerCorrection, ::DipolarLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarP3M< Architecture >, ::DipolarP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarScafacos, ::DipolarScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ElectrostaticLayerCorrection, ::ElectrostaticLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ReactionField, ::ReactionField >, System::Leaf >, ScriptInterface::AutoParameters< Actor< SIClass, CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< BondedInteraction >, ScriptInterface::AutoParameters< BreakageSpec >, ScriptInterface::AutoParameters< CellSystem, System::Leaf >, ScriptInterface::AutoParameters< Cluster >, ScriptInterface::AutoParameters< ClusterStructure >, ScriptInterface::AutoParameters< CollisionDetection, System::Leaf >, ScriptInterface::AutoParameters< ComFixed, System::Leaf >, ScriptInterface::AutoParameters< Constraint >, ScriptInterface::AutoParameters< Container, System::Leaf >, ScriptInterface::AutoParameters< CudaInitHandle >, ScriptInterface::AutoParameters< CylindricalTransformationParameters >, ScriptInterface::AutoParameters< EKPoissonSolver >, ScriptInterface::AutoParameters< EKPoissonSolverNode, LatticeIndices >, ScriptInterface::AutoParameters< EKReaction, LatticeIndices >, ScriptInterface::AutoParameters< EKSpeciesNode, LatticeIndices >, ScriptInterface::AutoParameters< Galilei, System::Leaf >, ScriptInterface::AutoParameters< H5md >, ScriptInterface::AutoParameters< ICCStar, System::Leaf >, ScriptInterface::AutoParameters< IntegratorHandle, System::Leaf >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::BMHTF_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Buckingham_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::DPD_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Gaussian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::GayBerne_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hat_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hertzian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJ_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos2_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJGen_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Morse_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SmoothStep_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SoftSphere_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::TabulatedPotential > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Thole_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::WCA_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >, ScriptInterface::AutoParameters< Interface< ::BrownianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::DPDThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::IsotropicNptThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LangevinThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LBThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::StokesianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::ThermalizedBondThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::EKinWalberlaBase, EKVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::LBWalberlaBase, LBVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::walberla::PoissonSolver, EKPoissonVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeWalberla >, ScriptInterface::AutoParameters< LBFluidNode, LatticeIndices >, ScriptInterface::AutoParameters< LeesEdwards, System::Leaf >, ScriptInterface::AutoParameters< NonBondedInteractionHandle >, ScriptInterface::AutoParameters< PairCriterion >, ScriptInterface::AutoParameters< ParticleHandle >, ScriptInterface::AutoParameters< ParticleSlice >, ScriptInterface::AutoParameters< Polymer >, ScriptInterface::AutoParameters< Protocol >, ScriptInterface::AutoParameters< ReactionAlgorithm >, ScriptInterface::AutoParameters< Shape >, ScriptInterface::AutoParameters< SingleReaction >, ScriptInterface::AutoParameters< System >, ScriptInterface::AutoParameters< Thermostat, System::Leaf >, ScriptInterface::AutoParameters< VTKHandleBase< ::EKinWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::LBWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::walberla::PoissonSolver > >, ScriptInterface::AutoParameters< VTKHandleBase< Field > >, and ScriptInterface::AutoParameters<::walberla::EKReactant >.
Definition at line 106 of file ObjectHandle.hpp.
References stream, and valid_parameters().
name()
std::string_view ScriptInterface::ObjectHandle::name () const
Definition at line 117 of file ObjectHandle.cpp.
Referenced by ScriptInterface::Constraints::ShapeBasedConstraint::bind_system(), call_method(), ScriptInterface::Writer::H5md::do_call_method(), ScriptInterface::Constraints::ExternalField< Coupling, Field >::do_call_method(), ScriptInterface::Constraints::ExternalPotential< Coupling, Field >::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), ScriptInterface::Coulomb::Container::do_call_method(), ScriptInterface::Coulomb::ICCStar::do_call_method(), ScriptInterface::LB::Container::do_call_method(), ScriptInterface::Dipoles::Container::do_call_method(), ScriptInterface::ReactionMethods::SingleReaction::do_call_method(), ScriptInterface::walberla::VTKHandleBase< Field >::do_call_method(), ScriptInterface::Analysis::Analysis::do_call_method(), ScriptInterface::Analysis::ObservableStat::do_call_method(), ScriptInterface::CodeInfo::CodeInfo::do_call_method(), ScriptInterface::CodeInfo::CodeVersion::do_call_method(), ScriptInterface::MPIIO::MPIIOScript::do_call_method(), ScriptInterface::Particles::Polymer::do_call_method(), ScriptInterface::System::CudaInitHandle::do_call_method(), ScriptInterface::CellSystem::CellSystem::do_call_method(), ScriptInterface::CellSystem::CheckpointerContext::do_call_method(), ScriptInterface::Coulomb::CoulombScafacos::do_call_method(), ScriptInterface::Galilei::Galilei::do_call_method(), ScriptInterface::Integrators::Integrator::do_call_method(), ScriptInterface::Interactions::BondedInteraction::do_call_method(), ScriptInterface::Interactions::IBMVolCons::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::InteractionWCA::do_call_method(), ScriptInterface::Interactions::InteractionLJcos2::do_call_method(), ScriptInterface::Interactions::InteractionTabulated::do_call_method(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_call_method(), ScriptInterface::LeesEdwards::LeesEdwards::do_call_method(), ScriptInterface::Dipoles::DipolarScafacos::do_call_method(), ScriptInterface::Particles::ParticleModifier::do_call_method(), ScriptInterface::Particles::ParticleList::do_call_method(), ScriptInterface::Particles::ParticleSlice::do_call_method(), ScriptInterface::ReactionMethods::ReactionAlgorithm::do_call_method(), ScriptInterface::ReactionMethods::WidomInsertion::do_call_method(), ScriptInterface::Shapes::Shape::do_call_method(), ScriptInterface::Thermostat::Interface< CoreClass >::do_call_method(), ScriptInterface::Thermostat::Thermostat::do_call_method(), ScriptInterface::walberla::EKPoissonSolverNode::do_call_method(), ScriptInterface::walberla::EKPoissonSolverSlice::do_call_method(), ScriptInterface::walberla::EKSpeciesNode::do_call_method(), ScriptInterface::walberla::EKSpeciesSlice::do_call_method(), ScriptInterface::walberla::LBFluid::do_call_method(), ScriptInterface::walberla::LBFluidNode::do_call_method(), ScriptInterface::walberla::LBFluidSlice::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_construct(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_construct(), ScriptInterface::AutoParameters< Derived, Base >::do_set_parameter(), ScriptInterface::AutoParameters< Derived, Base >::get_parameter(), get_parameter(), get_parameters(), ScriptInterface::Thermostat::Interface< CoreClass >::get_required_parameters(), ScriptInterface::AutoParameters< Derived, Base >::has_parameter(), ScriptInterface::Thermostat::Interface< CoreClass >::make_autogamma(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::make_autoparameter(), ScriptInterface::Thermostat::Interface< CoreClass >::make_autoparameter(), ScriptInterface::Thermostat::Thermostat::make_autoparameter(), ScriptInterface::Interactions::NonBondedInteractionHandle::NonBondedInteractionHandle(), ScriptInterface::Thermostat::Interface< CoreClass >::sanity_checks_positive(), ScriptInterface::Thermostat::Interface< CoreClass >::sanity_checks_positive(), and set_parameter().
operator=()
ObjectHandle & ScriptInterface::ObjectHandle::operator= (ObjectHandle const &) delete
serialize()
std::string ScriptInterface::ObjectHandle::serialize () const
Definition at line 66 of file ObjectHandle.cpp.
References serialize_parameters(), and stream.
Referenced by ScriptInterface::System::System::get_internal_state().
serialize_parameters()
virtual std::vector< std::pair< std::string, Variant > > ScriptInterface::ObjectHandle::serialize_parameters () const inline virtual
Serialize parameters.
Can be overridden to e.g. serialize parameters in a specific order.
Reimplemented in ScriptInterface::AutoParameters< Derived, Base >, ScriptInterface::AutoParameters< AccumulatorBase >, ScriptInterface::AutoParameters< Actor< CoulombMMM1D, ::CoulombMMM1D >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombP3M, ::CoulombP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombScafacos, ::CoulombScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DebyeHueckel, ::DebyeHueckel >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarDirectSum, ::DipolarDirectSum >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarLayerCorrection, ::DipolarLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarP3M< Architecture >, ::DipolarP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarScafacos, ::DipolarScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ElectrostaticLayerCorrection, ::ElectrostaticLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ReactionField, ::ReactionField >, System::Leaf >, ScriptInterface::AutoParameters< Actor< SIClass, CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< BondedInteraction >, ScriptInterface::AutoParameters< BreakageSpec >, ScriptInterface::AutoParameters< CellSystem, System::Leaf >, ScriptInterface::AutoParameters< Cluster >, ScriptInterface::AutoParameters< ClusterStructure >, ScriptInterface::AutoParameters< CollisionDetection, System::Leaf >, ScriptInterface::AutoParameters< ComFixed, System::Leaf >, ScriptInterface::AutoParameters< Constraint >, ScriptInterface::AutoParameters< Container, System::Leaf >, ScriptInterface::AutoParameters< CudaInitHandle >, ScriptInterface::AutoParameters< CylindricalTransformationParameters >, ScriptInterface::AutoParameters< EKPoissonSolver >, ScriptInterface::AutoParameters< EKPoissonSolverNode, LatticeIndices >, ScriptInterface::AutoParameters< EKReaction, LatticeIndices >, ScriptInterface::AutoParameters< EKSpeciesNode, LatticeIndices >, ScriptInterface::AutoParameters< Galilei, System::Leaf >, ScriptInterface::AutoParameters< H5md >, ScriptInterface::AutoParameters< ICCStar, System::Leaf >, ScriptInterface::AutoParameters< IntegratorHandle, System::Leaf >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::BMHTF_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Buckingham_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::DPD_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Gaussian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::GayBerne_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hat_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hertzian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJ_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos2_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJGen_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Morse_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SmoothStep_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SoftSphere_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::TabulatedPotential > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Thole_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::WCA_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >, ScriptInterface::AutoParameters< Interface< ::BrownianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::DPDThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::IsotropicNptThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LangevinThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LBThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::StokesianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::ThermalizedBondThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::EKinWalberlaBase, EKVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::LBWalberlaBase, LBVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::walberla::PoissonSolver, EKPoissonVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeWalberla >, ScriptInterface::AutoParameters< LBFluidNode, LatticeIndices >, ScriptInterface::AutoParameters< LeesEdwards, System::Leaf >, ScriptInterface::AutoParameters< NonBondedInteractionHandle >, ScriptInterface::AutoParameters< PairCriterion >, ScriptInterface::AutoParameters< ParticleHandle >, ScriptInterface::AutoParameters< ParticleSlice >, ScriptInterface::AutoParameters< Polymer >, ScriptInterface::AutoParameters< Protocol >, ScriptInterface::AutoParameters< ReactionAlgorithm >, ScriptInterface::AutoParameters< Shape >, ScriptInterface::AutoParameters< SingleReaction >, ScriptInterface::AutoParameters< System >, ScriptInterface::AutoParameters< Thermostat, System::Leaf >, ScriptInterface::AutoParameters< VTKHandleBase< ::EKinWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::LBWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::walberla::PoissonSolver > >, ScriptInterface::AutoParameters< VTKHandleBase< Field > >, and ScriptInterface::AutoParameters<::walberla::EKReactant >.
Definition at line 162 of file ObjectHandle.hpp.
References get_parameters().
Referenced by serialize().
set_internal_state()
virtual void ScriptInterface::ObjectHandle::set_internal_state (std::string const &) inline private virtual
Reimplemented in ScriptInterface::Accumulators::AccumulatorBase, ScriptInterface::Interactions::NonBondedInteractions, and ScriptInterface::System::System.
Definition at line 169 of file ObjectHandle.hpp.
set_parameter()
void ScriptInterface::ObjectHandle::set_parameter (const std::string & name, const Variant & value)
Set single parameter.
Can only be called on the head node.
Definition at line 44 of file ObjectHandle.cpp.
References do_set_parameter(), fe_trap::make_shared_scoped(), name(), and stream.
Referenced by ScriptInterface::Interactions::NonBondedInteractionHandle::do_construct(), and ScriptInterface::Integrators::IntegratorHandle::on_bind_system().
valid_parameters()
virtual std::vector< std::string_view > ScriptInterface::ObjectHandle::valid_parameters () const inline virtual
Get required and optional parameters for class.
Returns
Expected parameters.
Reimplemented in ScriptInterface::AutoParameters< Derived, Base >, ScriptInterface::AutoParameters< AccumulatorBase >, ScriptInterface::AutoParameters< Actor< CoulombMMM1D, ::CoulombMMM1D >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombP3M, ::CoulombP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< CoulombScafacos, ::CoulombScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DebyeHueckel, ::DebyeHueckel >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarDirectSum, ::DipolarDirectSum >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarLayerCorrection, ::DipolarLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarP3M< Architecture >, ::DipolarP3M >, System::Leaf >, ScriptInterface::AutoParameters< Actor< DipolarScafacos, ::DipolarScafacos >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ElectrostaticLayerCorrection, ::ElectrostaticLayerCorrection >, System::Leaf >, ScriptInterface::AutoParameters< Actor< ReactionField, ::ReactionField >, System::Leaf >, ScriptInterface::AutoParameters< Actor< SIClass, CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< BondedInteraction >, ScriptInterface::AutoParameters< BreakageSpec >, ScriptInterface::AutoParameters< CellSystem, System::Leaf >, ScriptInterface::AutoParameters< Cluster >, ScriptInterface::AutoParameters< ClusterStructure >, ScriptInterface::AutoParameters< CollisionDetection, System::Leaf >, ScriptInterface::AutoParameters< ComFixed, System::Leaf >, ScriptInterface::AutoParameters< Constraint >, ScriptInterface::AutoParameters< Container, System::Leaf >, ScriptInterface::AutoParameters< CudaInitHandle >, ScriptInterface::AutoParameters< CylindricalTransformationParameters >, ScriptInterface::AutoParameters< EKPoissonSolver >, ScriptInterface::AutoParameters< EKPoissonSolverNode, LatticeIndices >, ScriptInterface::AutoParameters< EKReaction, LatticeIndices >, ScriptInterface::AutoParameters< EKSpeciesNode, LatticeIndices >, ScriptInterface::AutoParameters< Galilei, System::Leaf >, ScriptInterface::AutoParameters< H5md >, ScriptInterface::AutoParameters< ICCStar, System::Leaf >, ScriptInterface::AutoParameters< IntegratorHandle, System::Leaf >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::BMHTF_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Buckingham_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::DPD_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Gaussian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::GayBerne_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hat_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Hertzian_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJ_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos2_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJcos_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::LJGen_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Morse_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SmoothStep_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::SoftSphere_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::TabulatedPotential > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::Thole_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< ::WCA_Parameters > >, ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >, ScriptInterface::AutoParameters< Interface< ::BrownianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::DPDThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::IsotropicNptThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LangevinThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::LBThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::StokesianThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< ::ThermalizedBondThermostat >, System::Leaf >, ScriptInterface::AutoParameters< Interface< CoreClass >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::EKinWalberlaBase, EKVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::LBWalberlaBase, LBVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< ::walberla::PoissonSolver, EKPoissonVTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle >, System::Leaf >, ScriptInterface::AutoParameters< LatticeWalberla >, ScriptInterface::AutoParameters< LBFluidNode, LatticeIndices >, ScriptInterface::AutoParameters< LeesEdwards, System::Leaf >, ScriptInterface::AutoParameters< NonBondedInteractionHandle >, ScriptInterface::AutoParameters< PairCriterion >, ScriptInterface::AutoParameters< ParticleHandle >, ScriptInterface::AutoParameters< ParticleSlice >, ScriptInterface::AutoParameters< Polymer >, ScriptInterface::AutoParameters< Protocol >, ScriptInterface::AutoParameters< ReactionAlgorithm >, ScriptInterface::AutoParameters< Shape >, ScriptInterface::AutoParameters< SingleReaction >, ScriptInterface::AutoParameters< System >, ScriptInterface::AutoParameters< Thermostat, System::Leaf >, ScriptInterface::AutoParameters< VTKHandleBase< ::EKinWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::LBWalberlaBase > >, ScriptInterface::AutoParameters< VTKHandleBase< ::walberla::PoissonSolver > >, ScriptInterface::AutoParameters< VTKHandleBase< Field > >, and ScriptInterface::AutoParameters<::walberla::EKReactant >.
Definition at line 104 of file ObjectHandle.hpp.
Referenced by get_parameters(), and has_parameter().
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 47 of file ObjectHandle.hpp.
The documentation for this class was generated from the following files:
ObjectHandle.hpp
ObjectHandle.cpp