ESPResSo: ScriptInterface::LB::Container Class Reference
ScriptInterface::LB::Container Class Reference
#include <Container.hpp>
Public Member Functions
Container ()
void do_construct (VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::AutoParameters< Container, System::Leaf >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::System::Leaf
~Leaf () override=default
void bind_system (std::shared_ptr<::System::System > const &system)
void detach_system ()
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
Variant do_call_method (std::string const &name, VariantMap const &) override
Protected Member Functions inherited from ScriptInterface::AutoParameters< Container, System::Leaf >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Member Functions inherited from ScriptInterface::System::Leaf
auto const & get_system () const
auto & get_system ()
Private Member Functions
void on_bind_system (::System::System &) override
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Attributes inherited from ScriptInterface::System::Leaf
std::weak_ptr<::System::System > m_system
Detailed Description
Definition at line 36 of file lb/Container.hpp.
Constructor & Destructor Documentation
Container()
ScriptInterface::LB::Container::Container () inline
Definition at line 65 of file lb/Container.hpp.
References ScriptInterface::AutoParameters< Container, System::Leaf >::add_parameters(), ScriptInterface::ObjectHandle::context(), ScriptInterface::is_none(), ScriptInterface::Context::parallel_try_catch(), and stream.
Member Function Documentation
do_call_method()
Variant ScriptInterface::LB::Container::do_call_method (std::string const & name, VariantMap const &) inline override protected virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 97 of file lb/Container.hpp.
References ScriptInterface::ObjectHandle::name().
do_construct()
void ScriptInterface::LB::Container::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 92 of file lb/Container.hpp.
on_bind_system()
void ScriptInterface::LB::Container::on_bind_system (::System::System &) inline override private virtual
Reimplemented from ScriptInterface::System::Leaf.
Definition at line 54 of file lb/Container.hpp.
References ScriptInterface::AutoParameters< Container, System::Leaf >::do_set_parameter(), ScriptInterface::AutoParameters< Container, System::Leaf >::get_parameter_insertion_order(), and stream.
The documentation for this class was generated from the following file:
lb/Container.hpp