ESPResSo: ScriptInterface::walberla::LatticeSlice< FieldSerializer > Class Template Reference
ScriptInterface::walberla::LatticeSlice< FieldSerializer > Class Template Reference abstract
#include <LatticeSlice.hpp>
Public Member Functions
virtual ::LatticeWalberla const & get_lattice () const =0
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
virtual void do_construct (VariantMap const &params)
VariantMap get_parameters () const
Get current parameters.
virtual std::vector< std::string_view > valid_parameters () const
Get required and optional parameters for class.
virtual bool has_parameter (std::string const &needle) const
virtual Variant get_parameter (std::string const &name) const
Get single parameter.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
virtual void do_set_parameter (const std::string &, const Variant &)
Local implementation of set_parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
virtual Variant do_call_method (const std::string &, const VariantMap &)
Local implementation of call_method.
std::string serialize () const
virtual std::vector< std::pair< std::string, Variant > > serialize_parameters () const
Serialize parameters.
Protected Member Functions
template<class LatticeModel , typename T >
Variant gather_3d (std::vector< int > const &data_dims, LatticeModel const &lattice_model, std::vector< T >(LatticeModel::*getter)(Utils::Vector3i const &, Utils::Vector3i const &) const, double units_conversion=1.) const
template<class LatticeModel , typename T >
void scatter_3d (Variant const &grid_values, std::vector< int > const &data_dims, LatticeModel &lattice_model, void(LatticeModel::*setter)(Utils::Vector3i const &, Utils::Vector3i const &, std::vector< T > const &), double units_conversion=1.)
Protected Member Functions inherited from ScriptInterface::LatticeIndices
bool is_index_valid (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
void throw_invalid_index (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
Utils::Vector3i get_mapped_index (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
Protected Attributes
Utils::Vector3i m_slice_lower_corner
Utils::Vector3i m_slice_upper_corner
std::vector< int > m_shape
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
template<class FieldSerializer>
class ScriptInterface::walberla::LatticeSlice< FieldSerializer >
Definition at line 40 of file LatticeSlice.hpp.
Member Function Documentation
gather_3d()
template<class FieldSerializer > template<class LatticeModel , typename T > Variant ScriptInterface::walberla::LatticeSlice< FieldSerializer >::gather_3d (std::vector< int > const & data_dims, LatticeModel const & lattice_model, std::vector< T >(LatticeModel::*)(Utils::Vector3i const &, Utils::Vector3i const &) const getter, double units_conversion = 1.) const protected
Definition at line 112 of file LatticeSlice.impl.hpp.
get_lattice()
template<class FieldSerializer > virtual ::LatticeWalberla const & ScriptInterface::walberla::LatticeSlice< FieldSerializer >::get_lattice () const pure virtual
Implemented in ScriptInterface::walberla::EKPoissonSolverSlice, ScriptInterface::walberla::EKSpeciesSlice, and ScriptInterface::walberla::LBFluidSlice.
References LatticeWalberla::get_ghost_layers().
scatter_3d()
template<class FieldSerializer > template<class LatticeModel , typename T > void ScriptInterface::walberla::LatticeSlice< FieldSerializer >::scatter_3d (Variant const & grid_values, std::vector< int > const & data_dims, LatticeModel & lattice_model, void(LatticeModel::*)(Utils::Vector3i const &, Utils::Vector3i const &, std::vector< T > const &) setter, double units_conversion = 1.) protected
Definition at line 165 of file LatticeSlice.impl.hpp.
References Utils::Vector< T, N >::broadcast(), ScriptInterface::ObjectHandle::context(), ScriptInterface::walberla::gather_slices_topology(), ScriptInterface::Context::get_comm(), and stream.
Member Data Documentation
m_shape
template<class FieldSerializer > std::vector<int> ScriptInterface::walberla::LatticeSlice< FieldSerializer >::m_shape protected
Definition at line 44 of file LatticeSlice.hpp.
m_slice_lower_corner
template<class FieldSerializer > Utils::Vector3i ScriptInterface::walberla::LatticeSlice< FieldSerializer >::m_slice_lower_corner protected
Definition at line 42 of file LatticeSlice.hpp.
m_slice_upper_corner
template<class FieldSerializer > Utils::Vector3i ScriptInterface::walberla::LatticeSlice< FieldSerializer >::m_slice_upper_corner protected
Definition at line 43 of file LatticeSlice.hpp.
The documentation for this class was generated from the following files:
LatticeSlice.hpp
LatticeSlice.impl.hpp