ESPResSo: walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector Class Reference
walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector Class Reference
#include <DynamicUBBDoublePrecisionCUDA.h>
Public Member Functions
ForceVector ()=default
bool operator== (ForceVector const &other) const
~ForceVector ()
auto & forceVector ()
auto const & forceVector () const
ForceStruct * pointerCpu ()
bool empty () const
ForceStruct * pointerGpu ()
Vector3< double > getForce ()
void syncGPU ()
void syncCPU ()
Detailed Description
Definition at line 162 of file DynamicUBBDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
ForceVector()
walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::ForceVector () default
~ForceVector()
walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::~ForceVector () inline
Definition at line 169 of file DynamicUBBDoublePrecisionCUDA.h.
References stream.
Member Function Documentation
empty()
bool walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::empty () const inline
Definition at line 179 of file DynamicUBBDoublePrecisionCUDA.h.
forceVector() [1/2]
auto & walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::forceVector () inline
Definition at line 174 of file DynamicUBBDoublePrecisionCUDA.h.
Referenced by walberla::lbm::DynamicUBBDoublePrecisionCUDA::getForceVector().
forceVector() [2/2]
auto const & walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::forceVector () const inline
Definition at line 175 of file DynamicUBBDoublePrecisionCUDA.h.
getForce()
Vector3< double > walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::getForce () inline
Definition at line 182 of file DynamicUBBDoublePrecisionCUDA.h.
References stream, and syncCPU().
Referenced by walberla::lbm::DynamicUBBDoublePrecisionCUDA::getForce().
operator==()
bool walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::operator== (ForceVector const & other) const inline
Definition at line 165 of file DynamicUBBDoublePrecisionCUDA.h.
References stream.
pointerCpu()
ForceStruct * walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::pointerCpu () inline
Definition at line 176 of file DynamicUBBDoublePrecisionCUDA.h.
References stream.
pointerGpu()
ForceStruct * walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::pointerGpu () inline
Definition at line 181 of file DynamicUBBDoublePrecisionCUDA.h.
syncCPU()
void walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::syncCPU () inline
Definition at line 208 of file DynamicUBBDoublePrecisionCUDA.h.
References stream.
Referenced by getForce().
syncGPU()
void walberla::lbm::DynamicUBBDoublePrecisionCUDA::ForceVector::syncGPU () inline
Definition at line 193 of file DynamicUBBDoublePrecisionCUDA.h.
References stream.
The documentation for this class was generated from the following file:
DynamicUBBDoublePrecisionCUDA.h