ESPResSo: walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA Class Reference
walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA Class Reference
#include <ReactionKernelBulk_5_single_precision_CUDA.h>
Public Member Functions
ReactionKernelBulk_5_single_precision_CUDA (BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, float order_0, float order_1, float order_2, float order_3, float order_4, float rate_coefficient, float stoech_0, float stoech_1, float stoech_2, float stoech_3, float stoech_4)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getOrder_0 () const
float getOrder_1 () const
float getOrder_2 () const
float getOrder_3 () const
float getOrder_4 () const
float getRate_coefficient () const
float getStoech_0 () const
float getStoech_1 () const
float getStoech_2 () const
float getStoech_3 () const
float getStoech_4 () const
void setOrder_0 (const float value)
void setOrder_1 (const float value)
void setOrder_2 (const float value)
void setOrder_3 (const float value)
void setOrder_4 (const float value)
void setRate_coefficient (const float value)
void setStoech_0 (const float value)
void setStoech_1 (const float value)
void setStoech_2 (const float value)
void setStoech_3 (const float value)
void setStoech_4 (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ReactionKernelBulk_5_single_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_5_single_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file ReactionKernelBulk_5_single_precision_CUDA.h.
Constructor & Destructor Documentation
ReactionKernelBulk_5_single_precision_CUDA()
walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::ReactionKernelBulk_5_single_precision_CUDA (BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, float order_0, float order_1, float order_2, float order_3, float order_4, float rate_coefficient, float stoech_0, float stoech_1, float stoech_2, float stoech_3, float stoech_4) inline
Definition at line 57 of file ReactionKernelBulk_5_single_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 112 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getOrder_0()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getOrder_0 () const inline
Definition at line 115 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getOrder_1()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getOrder_1 () const inline
Definition at line 116 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getOrder_2()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getOrder_2 () const inline
Definition at line 117 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getOrder_3()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getOrder_3 () const inline
Definition at line 118 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getOrder_4()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getOrder_4 () const inline
Definition at line 119 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getRate_coefficient()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getRate_coefficient () const inline
Definition at line 120 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getStoech_0()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getStoech_0 () const inline
Definition at line 121 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getStoech_1()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getStoech_1 () const inline
Definition at line 122 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getStoech_2()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getStoech_2 () const inline
Definition at line 123 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getStoech_3()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getStoech_3 () const inline
Definition at line 124 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getStoech_4()
float walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getStoech_4 () const inline
Definition at line 125 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getSweep (const shared_ptr< ReactionKernelBulk_5_single_precision_CUDA > & kernel) inline static
Definition at line 81 of file ReactionKernelBulk_5_single_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 97 of file ReactionKernelBulk_5_single_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_5_single_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 86 of file ReactionKernelBulk_5_single_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 102 of file ReactionKernelBulk_5_single_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 77 of file ReactionKernelBulk_5_single_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 69 of file ReactionKernelBulk_5_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 124 of file ReactionKernelBulk_5_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setOrder_0()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setOrder_0 (const float value) inline
Definition at line 126 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setOrder_1()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setOrder_1 (const float value) inline
Definition at line 127 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setOrder_2()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setOrder_2 (const float value) inline
Definition at line 128 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setOrder_3()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setOrder_3 (const float value) inline
Definition at line 129 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setOrder_4()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setOrder_4 (const float value) inline
Definition at line 130 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setRate_coefficient()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setRate_coefficient (const float value) inline
Definition at line 131 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setStoech_0()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setStoech_0 (const float value) inline
Definition at line 134 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setStoech_1()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setStoech_1 (const float value) inline
Definition at line 135 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setStoech_2()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setStoech_2 (const float value) inline
Definition at line 136 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setStoech_3()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setStoech_3 (const float value) inline
Definition at line 137 of file ReactionKernelBulk_5_single_precision_CUDA.h.
setStoech_4()
void walberla::pystencils::ReactionKernelBulk_5_single_precision_CUDA::setStoech_4 (const float value) inline
Definition at line 138 of file ReactionKernelBulk_5_single_precision_CUDA.h.
The documentation for this class was generated from the following files:
ReactionKernelBulk_5_single_precision_CUDA.h
ReactionKernelBulk_5_single_precision_CUDA.cu