ESPResSo: walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX Class Reference
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX Class Reference
#include <StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h>
Public Member Functions
StreamCollideSweepSinglePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s)
~StreamCollideSweepSinglePrecisionLeesEdwardsAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getGrid_size () const
float getOmega_shear () const
float getV_s () const
void setGrid_size (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepSinglePrecisionLeesEdwardsAVX()
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::StreamCollideSweepSinglePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s) inline
Definition at line 57 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
~StreamCollideSweepSinglePrecisionLeesEdwardsAVX()
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::~StreamCollideSweepSinglePrecisionLeesEdwardsAVX () inline
Definition at line 64 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 106 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
getGrid_size()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getGrid_size () const inline
Definition at line 109 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getOmega_shear () const inline
Definition at line 110 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getSweep () inline
Definition at line 93 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsAVX > & kernel) inline static
Definition at line 79 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
References runOnCellInterval(), and stream.
getV_s()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::getV_s () const inline
Definition at line 111 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::run (IBlock * block)
Definition at line 183 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_b58565c91bfe08c1a391f73d40cf95a1::streamcollidesweepsingleprecisionleesedwardsavx_streamcollidesweepsingleprecisionleesedwardsavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 237 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_b58565c91bfe08c1a391f73d40cf95a1::streamcollidesweepsingleprecisionleesedwardsavx_streamcollidesweepsingleprecisionleesedwardsavx().
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::setGrid_size (const float value) inline
Definition at line 112 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::setOmega_shear (const float value) inline
Definition at line 113 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
setV_s()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsAVX::setV_s (const float value) inline
Definition at line 114 of file StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepSinglePrecisionLeesEdwardsAVX.h
StreamCollideSweepSinglePrecisionLeesEdwardsAVX.cpp