ESPResSo: ScriptInterface::walberla::EKSpecies Class Reference
ScriptInterface::walberla::EKSpecies Class Reference
#include <EKSpecies.hpp>
Public Member Functions
EKSpecies ()
void do_construct (VariantMap const &params) override
auto get_ekinstance () const
auto get_lattice () const
auto get_mpi_cart_comm_observer () const
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
auto get_conversion_factor_density () const noexcept
auto get_conversion_factor_flux () const noexcept
::LatticeModel::units_map get_lattice_to_md_units_conversion () const override
void flux_boundary_ghost_layer_size_sanity_check () const
Public Member Functions inherited from ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >
Variant do_call_method (std::string const &method_name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Types
using Base = LatticeModel<::EKinWalberlaBase, EKVTKHandle >
Protected Member Functions
void make_instance (VariantMap const &params) override
Protected Member Functions inherited from ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >
auto find_vtk (std::shared_ptr< EKVTKHandle > const &vtk) const
auto has_vtk (std::shared_ptr< EKVTKHandle > const &vtk) const
auto serialize_vtk_writers () const
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes
std::optional< ResourceObserver > m_mpi_cart_comm_observer
double m_conv_diffusion
double m_conv_ext_efield
double m_conv_energy
double m_conv_density
double m_conv_flux
double m_tau
double m_density
Protected Attributes inherited from ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >
std::shared_ptr< LatticeWalberla > m_lattice
std::shared_ptr< ::EKinWalberlaBase > m_instance
std::vector< std::shared_ptr< EKVTKHandle > > m_vtk_writers
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
Definition at line 64 of file EKSpecies.hpp.
Member Typedef Documentation
Base
using ScriptInterface::walberla::EKSpecies::Base = LatticeModel<::EKinWalberlaBase, EKVTKHandle> protected
Definition at line 66 of file EKSpecies.hpp.
Constructor & Destructor Documentation
EKSpecies()
ScriptInterface::walberla::EKSpecies::EKSpecies () inline
Definition at line 77 of file EKSpecies.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), ScriptInterface::ObjectHandle::context(), m_conv_density, m_conv_diffusion, m_conv_energy, m_conv_ext_efield, m_density, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_instance, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_lattice, m_tau, ScriptInterface::Context::parallel_try_catch(), ScriptInterface::AutoParameter::read_only, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::serialize_vtk_writers(), and stream.
Member Function Documentation
do_call_method()
Variant ScriptInterface::walberla::EKSpecies::do_call_method (std::string const & method, VariantMap const & parameters) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 56 of file EKSpecies.cpp.
References ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::do_call_method(), flux_boundary_ghost_layer_size_sanity_check(), ScriptInterface::get_value(), m_conv_density, m_conv_flux, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_instance, and stream.
do_construct()
void ScriptInterface::walberla::EKSpecies::do_construct (VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 127 of file EKSpecies.cpp.
References ScriptInterface::ObjectHandle::context(), density, get_lattice_to_md_units_conversion(), walberla::get_mpi_cart_comm_observer(), m_conv_density, m_conv_diffusion, m_conv_energy, m_conv_ext_efield, m_conv_flux, m_density, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_instance, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_lattice, m_mpi_cart_comm_observer, m_tau, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_vtk_writers, make_instance(), ScriptInterface::Context::parallel_try_catch(), and stream.
flux_boundary_ghost_layer_size_sanity_check()
void ScriptInterface::walberla::EKSpecies::flux_boundary_ghost_layer_size_sanity_check () const inline
Definition at line 176 of file EKSpecies.hpp.
References ScriptInterface::ObjectHandle::context(), get_lattice(), ScriptInterface::Context::parallel_try_catch(), and stream.
Referenced by do_call_method().
get_conversion_factor_density()
auto ScriptInterface::walberla::EKSpecies::get_conversion_factor_density () const inline noexcept
Definition at line 161 of file EKSpecies.hpp.
References m_conv_density.
get_conversion_factor_flux()
auto ScriptInterface::walberla::EKSpecies::get_conversion_factor_flux () const inline noexcept
Definition at line 164 of file EKSpecies.hpp.
References m_conv_flux.
get_ekinstance()
auto ScriptInterface::walberla::EKSpecies::get_ekinstance () const inline
Definition at line 152 of file EKSpecies.hpp.
References ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_instance.
get_lattice()
auto ScriptInterface::walberla::EKSpecies::get_lattice () const inline
Definition at line 153 of file EKSpecies.hpp.
References ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_lattice.
Referenced by flux_boundary_ghost_layer_size_sanity_check().
get_lattice_to_md_units_conversion()
::LatticeModel::units_map ScriptInterface::walberla::EKSpecies::get_lattice_to_md_units_conversion () const inline override virtual
Implements ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >.
Definition at line 169 of file EKSpecies.hpp.
References m_conv_density, and m_conv_flux.
Referenced by do_construct().
get_mpi_cart_comm_observer()
auto ScriptInterface::walberla::EKSpecies::get_mpi_cart_comm_observer () const inline
Definition at line 154 of file EKSpecies.hpp.
References m_mpi_cart_comm_observer.
make_instance()
void ScriptInterface::walberla::EKSpecies::make_instance (VariantMap const & params) override protected virtual
Implements ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >.
Definition at line 97 of file EKSpecies.cpp.
References ScriptInterface::CodeInfo::check_features(), density, ScriptInterface::get_value_or(), m_conv_density, m_conv_diffusion, m_conv_energy, m_conv_ext_efield, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_instance, ScriptInterface::walberla::LatticeModel<::EKinWalberlaBase, EKVTKHandle >::m_lattice, walberla::new_ek_walberla_cpu(), walberla::new_ek_walberla_gpu(), and stream.
Referenced by do_construct().
Member Data Documentation
m_conv_density
double ScriptInterface::walberla::EKSpecies::m_conv_density protected
Definition at line 71 of file EKSpecies.hpp.
Referenced by do_call_method(), do_construct(), EKSpecies(), get_conversion_factor_density(), get_lattice_to_md_units_conversion(), and make_instance().
m_conv_diffusion
double ScriptInterface::walberla::EKSpecies::m_conv_diffusion protected
Definition at line 68 of file EKSpecies.hpp.
Referenced by do_construct(), EKSpecies(), and make_instance().
m_conv_energy
double ScriptInterface::walberla::EKSpecies::m_conv_energy protected
Definition at line 70 of file EKSpecies.hpp.
Referenced by do_construct(), EKSpecies(), and make_instance().
m_conv_ext_efield
double ScriptInterface::walberla::EKSpecies::m_conv_ext_efield protected
Definition at line 69 of file EKSpecies.hpp.
Referenced by do_construct(), EKSpecies(), and make_instance().
m_conv_flux
double ScriptInterface::walberla::EKSpecies::m_conv_flux protected
Definition at line 72 of file EKSpecies.hpp.
Referenced by do_call_method(), do_construct(), get_conversion_factor_flux(), and get_lattice_to_md_units_conversion().
m_density
double ScriptInterface::walberla::EKSpecies::m_density protected
Definition at line 74 of file EKSpecies.hpp.
Referenced by do_construct(), and EKSpecies().
m_mpi_cart_comm_observer
std::optional<ResourceObserver> ScriptInterface::walberla::EKSpecies::m_mpi_cart_comm_observer protected
Definition at line 67 of file EKSpecies.hpp.
Referenced by do_construct(), and get_mpi_cart_comm_observer().
m_tau
double ScriptInterface::walberla::EKSpecies::m_tau protected
Definition at line 73 of file EKSpecies.hpp.
Referenced by do_construct(), and EKSpecies().
The documentation for this class was generated from the following files:
EKSpecies.hpp
EKSpecies.cpp