ESPResSo: LeesEdwards::Push Class Reference
LeesEdwards::Push Class Reference
#include <lees_edwards.hpp>
Public Member Functions
Push (BoxGeometry const &box, double time_step)
void operator() (Particle &p) const
Public Member Functions inherited from LeesEdwards::UpdateOffset
UpdateOffset (BoxGeometry const &box, double time_step)
void operator() (Particle &p) const
Additional Inherited Members
Protected Attributes inherited from LeesEdwards::UpdateOffset
const LeesEdwardsBC & m_le
const double m_half_time_step
Detailed Description
Definition at line 46 of file lees_edwards.hpp.
Constructor & Destructor Documentation
Push()
LeesEdwards::Push::Push (BoxGeometry const & box, double time_step) inline
Definition at line 50 of file lees_edwards.hpp.
References time_step.
Member Function Documentation
operator()()
void LeesEdwards::Push::operator() (Particle & p) const inline
Definition at line 53 of file lees_edwards.hpp.
References Particle::lees_edwards_flag(), Particle::lees_edwards_offset(), LeesEdwards::UpdateOffset::m_le, LeesEdwards::UpdateOffset::operator()(), Particle::pos(), LeesEdwardsBC::pos_offset, LeesEdwardsBC::shear_direction, LeesEdwardsBC::shear_plane_normal, LeesEdwardsBC::shear_velocity, and Particle::v().
The documentation for this class was generated from the following file:
lees_edwards.hpp