ESPResSo: walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX Class Reference
walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX Class Reference
#include <CollideSweepDoublePrecisionThermalizedAVX.h>
Public Member Functions
CollideSweepDoublePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepDoublePrecisionThermalizedAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionThermalizedAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepDoublePrecisionThermalizedAVX.h.
Constructor & Destructor Documentation
CollideSweepDoublePrecisionThermalizedAVX()
walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::CollideSweepDoublePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file CollideSweepDoublePrecisionThermalizedAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 104 of file CollideSweepDoublePrecisionThermalizedAVX.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getBlock_offset_0 () const inline
Definition at line 113 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getBlock_offset_1()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getBlock_offset_1 () const inline
Definition at line 114 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getBlock_offset_2()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getBlock_offset_2 () const inline
Definition at line 115 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getKt()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getKt () const inline
Definition at line 116 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_bulk()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getOmega_bulk () const inline
Definition at line 117 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_even()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getOmega_even () const inline
Definition at line 118 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_odd()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getOmega_odd () const inline
Definition at line 119 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_shear()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getOmega_shear () const inline
Definition at line 120 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getSeed()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getSeed () const inline
Definition at line 121 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getSweep () inline
Definition at line 91 of file CollideSweepDoublePrecisionThermalizedAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getSweep (const shared_ptr< CollideSweepDoublePrecisionThermalizedAVX > & kernel) inline static
Definition at line 77 of file CollideSweepDoublePrecisionThermalizedAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionThermalizedAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 82 of file CollideSweepDoublePrecisionThermalizedAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 96 of file CollideSweepDoublePrecisionThermalizedAVX.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::getTime_step () const inline
Definition at line 122 of file CollideSweepDoublePrecisionThermalizedAVX.h.
operator()()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::operator() (IBlock * block) inline
Definition at line 75 of file CollideSweepDoublePrecisionThermalizedAVX.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::run (IBlock * block)
Definition at line 773 of file CollideSweepDoublePrecisionThermalizedAVX.cpp.
References block(), walberla::pystencils::internal_25bc51f30ec2c20f3ee9796f7dcb65c6::collidesweepdoubleprecisionthermalizedavx_collidesweepdoubleprecisionthermalizedavx(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 819 of file CollideSweepDoublePrecisionThermalizedAVX.cpp.
References block(), walberla::pystencils::internal_25bc51f30ec2c20f3ee9796f7dcb65c6::collidesweepdoubleprecisionthermalizedavx_collidesweepdoubleprecisionthermalizedavx(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setBlock_offset_0 (const uint32_t value) inline
Definition at line 123 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setBlock_offset_1()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setBlock_offset_1 (const uint32_t value) inline
Definition at line 126 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setBlock_offset_2()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setBlock_offset_2 (const uint32_t value) inline
Definition at line 129 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setKt()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setKt (const double value) inline
Definition at line 132 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_bulk()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setOmega_bulk (const double value) inline
Definition at line 133 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_even()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setOmega_even (const double value) inline
Definition at line 134 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_odd()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setOmega_odd (const double value) inline
Definition at line 135 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_shear()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setOmega_shear (const double value) inline
Definition at line 136 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setSeed()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setSeed (const uint32_t value) inline
Definition at line 137 of file CollideSweepDoublePrecisionThermalizedAVX.h.
setTime_step()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedAVX::setTime_step (const uint32_t value) inline
Definition at line 138 of file CollideSweepDoublePrecisionThermalizedAVX.h.
The documentation for this class was generated from the following files:
CollideSweepDoublePrecisionThermalizedAVX.h
CollideSweepDoublePrecisionThermalizedAVX.cpp