ESPResSo: Constraints::Constraints< ParticleRange, Constraint > Class Template Reference
Constraints::Constraints< ParticleRange, Constraint > Class Template Reference
#include <Constraints.hpp>
Public Types
using value_type = typename container_type::value_type
using iterator = typename container_type::iterator
using const_iterator = typename container_type::const_iterator
Public Member Functions
bool contains (std::shared_ptr< Constraint > const &constraint) const noexcept
void add (std::shared_ptr< Constraint > const &constraint)
void remove (std::shared_ptr< Constraint > const &constraint)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void add_forces (BoxGeometry const &box_geo, ParticleRange &particles, double time) const
void add_energy (BoxGeometry const &box_geo, ParticleRange const &particles, double time, Observable_stat &obs_energy) const
void veto_boxl_change () const
void on_boxl_change () const
Detailed Description
template<class ParticleRange, class Constraint>
class Constraints::Constraints< ParticleRange, Constraint >
Definition at line 33 of file core/constraints/Constraints.hpp.
Member Typedef Documentation
const_iterator
template<class ParticleRange , class Constraint > using Constraints::Constraints< ParticleRange, Constraint >::const_iterator = typename container_type::const_iterator
Definition at line 39 of file core/constraints/Constraints.hpp.
iterator
template<class ParticleRange , class Constraint > using Constraints::Constraints< ParticleRange, Constraint >::iterator = typename container_type::iterator
Definition at line 38 of file core/constraints/Constraints.hpp.
value_type
template<class ParticleRange , class Constraint > using Constraints::Constraints< ParticleRange, Constraint >::value_type = typename container_type::value_type
Definition at line 37 of file core/constraints/Constraints.hpp.
Member Function Documentation
add()
template<class ParticleRange , class Constraint > void Constraints::Constraints< ParticleRange, Constraint >::add (std::shared_ptr< Constraint > const & constraint) inline
Definition at line 54 of file core/constraints/Constraints.hpp.
References System::get_system().
add_energy()
template<class ParticleRange , class Constraint > void Constraints::Constraints< ParticleRange, Constraint >::add_energy (BoxGeometry const & box_geo, ParticleRange const & particles, double time, Observable_stat & obs_energy) const inline
Definition at line 94 of file core/constraints/Constraints.hpp.
References BoxGeometry::folded_position().
add_forces()
template<class ParticleRange , class Constraint > void Constraints::Constraints< ParticleRange, Constraint >::add_forces (BoxGeometry const & box_geo, ParticleRange & particles, double time) const inline
Definition at line 76 of file core/constraints/Constraints.hpp.
References BoxGeometry::folded_position().
begin() [1/2]
template<class ParticleRange , class Constraint > iterator Constraints::Constraints< ParticleRange, Constraint >::begin () inline
Definition at line 71 of file core/constraints/Constraints.hpp.
begin() [2/2]
template<class ParticleRange , class Constraint > const_iterator Constraints::Constraints< ParticleRange, Constraint >::begin () const inline
Definition at line 73 of file core/constraints/Constraints.hpp.
contains()
template<class ParticleRange , class Constraint > bool Constraints::Constraints< ParticleRange, Constraint >::contains (std::shared_ptr< Constraint > const & constraint) const inline noexcept
Definition at line 51 of file core/constraints/Constraints.hpp.
end() [1/2]
template<class ParticleRange , class Constraint > iterator Constraints::Constraints< ParticleRange, Constraint >::end () inline
Definition at line 72 of file core/constraints/Constraints.hpp.
end() [2/2]
template<class ParticleRange , class Constraint > const_iterator Constraints::Constraints< ParticleRange, Constraint >::end () const inline
Definition at line 74 of file core/constraints/Constraints.hpp.
on_boxl_change()
template<class ParticleRange , class Constraint > void Constraints::Constraints< ParticleRange, Constraint >::on_boxl_change () const inline
Definition at line 115 of file core/constraints/Constraints.hpp.
remove()
template<class ParticleRange , class Constraint > void Constraints::Constraints< ParticleRange, Constraint >::remove (std::shared_ptr< Constraint > const & constraint) inline
Definition at line 64 of file core/constraints/Constraints.hpp.
References System::get_system().
veto_boxl_change()
template<class ParticleRange , class Constraint > void Constraints::Constraints< ParticleRange, Constraint >::veto_boxl_change () const inline
Definition at line 108 of file core/constraints/Constraints.hpp.
The documentation for this class was generated from the following file:
core/constraints/Constraints.hpp