ESPResSo: ImmersedBoundaries Class Reference
ImmersedBoundaries Class Reference
#include <ImmersedBoundaries.hpp>
Public Member Functions
ImmersedBoundaries ()
void init_volume_conservation (CellStructure &cs)
Initialize volume conservation.
void volume_conservation (CellStructure &cs)
Calculate volumes, volume force and add it to each virtual particle.
void register_softID (int softID)
double get_current_volume (int softID) const
Detailed Description
Definition at line 30 of file ImmersedBoundaries.hpp.
Constructor & Destructor Documentation
ImmersedBoundaries()
ImmersedBoundaries::ImmersedBoundaries () inline
Definition at line 32 of file ImmersedBoundaries.hpp.
Member Function Documentation
get_current_volume()
double ImmersedBoundaries::get_current_volume (int softID) const inline
Definition at line 44 of file ImmersedBoundaries.hpp.
Referenced by ScriptInterface::Interactions::IBMVolCons::do_call_method().
init_volume_conservation()
void ImmersedBoundaries::init_volume_conservation (CellStructure & cs)
Initialize volume conservation.
Definition at line 52 of file ImmersedBoundaries.cpp.
References BondedInteractionsMap::begin(), bonded_ia_params, and BondedInteractionsMap::end().
Referenced by System::System::update_dependent_particles().
register_softID()
void ImmersedBoundaries::register_softID (int softID) inline
Definition at line 37 of file ImmersedBoundaries.hpp.
Referenced by IBMVolCons::IBMVolCons().
volume_conservation()
void ImmersedBoundaries::volume_conservation (CellStructure & cs)
Calculate volumes, volume force and add it to each virtual particle.
Definition at line 43 of file ImmersedBoundaries.cpp.
Referenced by System::System::calculate_forces().
The documentation for this class was generated from the following files:
ImmersedBoundaries.hpp
ImmersedBoundaries.cpp