ESPResSo: ScriptInterface::Observables::PidObservable< CorePidObs > Class Template Reference
ScriptInterface::Observables::PidObservable< CorePidObs > Class Template Reference
Base class for script interfaces to particle-based observables.
#include <PidObservable.hpp>
Public Member Functions
PidObservable ()
void do_construct (VariantMap const &params) override
std::shared_ptr<::Observables::Observable > observable () const override
Public Member Functions inherited from ScriptInterface::AutoParameters< PidObservable< CorePidObs >, Observable >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< PidObservable< CorePidObs >, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
template<typename CorePidObs>
class ScriptInterface::Observables::PidObservable< CorePidObs >
Base class for script interfaces to particle-based observables.
Template Parameters
CorePidObs Any core class derived from Observables::PidObservable
Definition at line 44 of file script_interface/observables/PidObservable.hpp.
Constructor & Destructor Documentation
PidObservable()
template<typename CorePidObs > ScriptInterface::Observables::PidObservable< CorePidObs >::PidObservable () inline
Definition at line 49 of file script_interface/observables/PidObservable.hpp.
References ScriptInterface::AutoParameters< PidObservable< CorePidObs >, Observable >::add_parameters(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_construct()
template<typename CorePidObs > void ScriptInterface::Observables::PidObservable< CorePidObs >::do_construct (VariantMap const & params) inline override
Definition at line 54 of file script_interface/observables/PidObservable.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Context::parallel_try_catch(), and stream.
observable()
template<typename CorePidObs > std::shared_ptr<::Observables::Observable > ScriptInterface::Observables::PidObservable< CorePidObs >::observable () const inline override
Definition at line 61 of file script_interface/observables/PidObservable.hpp.
The documentation for this class was generated from the following file:
script_interface/observables/PidObservable.hpp