ESPResSo: CoulombMMM1DGpu Class Reference
CoulombMMM1DGpu Class Reference
#include <mmm1d_gpu.hpp>
Public Member Functions
CoulombMMM1DGpu (double prefactor, double maxPWerror, double far_switch_radius, int bessel_cutoff)
~CoulombMMM1DGpu ()
void add_long_range_forces ()
void add_long_range_energy ()
void on_activation ()
void on_boxl_change ()
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
void init () const
void sanity_checks () const
void tune ()
bool is_tuned () const
Public Member Functions inherited from Coulomb::Actor< CoulombMMM1DGpu >
void set_prefactor (double new_prefactor)
void sanity_checks_charge_neutrality () const
Public Attributes
double maxPWerror
double far_switch_radius
double far_switch_radius_sq
int bessel_cutoff
Public Attributes inherited from Coulomb::Actor< CoulombMMM1DGpu >
double prefactor
Electrostatics prefactor.
double charge_neutrality_tolerance
Relative tolerance for the charge excess during neutrality checks.
Additional Inherited Members
Static Public Attributes inherited from Coulomb::Actor< CoulombMMM1DGpu >
static constexpr auto charge_neutrality_tolerance_default
Detailed Description
Definition at line 38 of file mmm1d_gpu.hpp.
Constructor & Destructor Documentation
CoulombMMM1DGpu()
CoulombMMM1DGpu::CoulombMMM1DGpu (double prefactor, double maxPWerror, double far_switch_radius, int bessel_cutoff)
Definition at line 34 of file mmm1d_gpu.cpp.
References maxPWerror.
~CoulombMMM1DGpu()
CoulombMMM1DGpu::~CoulombMMM1DGpu ()
Definition at line 189 of file mmm1d_gpu_cuda.cu.
Member Function Documentation
add_long_range_energy()
void CoulombMMM1DGpu::add_long_range_energy ()
Definition at line 542 of file mmm1d_gpu_cuda.cu.
References CUDA_energy::coulomb, EspressoSystemInterface::eGpu(), energiesKernel(), es_system, KERNELCALL, KERNELCALL_shared, EspressoSystemInterface::npart_gpu(), EspressoSystemInterface::qGpuBegin(), EspressoSystemInterface::rGpuBegin(), scaleAndAddKernel(), and sumKernel().
add_long_range_forces()
void CoulombMMM1DGpu::add_long_range_forces ()
Definition at line 510 of file mmm1d_gpu_cuda.cu.
References es_system, EspressoSystemInterface::fGpuBegin(), forcesKernel(), KERNELCALL, EspressoSystemInterface::npart_gpu(), EspressoSystemInterface::qGpuBegin(), EspressoSystemInterface::rGpuBegin(), and vectorReductionKernel().
init()
void CoulombMMM1DGpu::init () const inline
Definition at line 61 of file mmm1d_gpu.hpp.
is_tuned()
bool CoulombMMM1DGpu::is_tuned () const inline
Definition at line 70 of file mmm1d_gpu.hpp.
on_activation()
void CoulombMMM1DGpu::on_activation () inline
Definition at line 53 of file mmm1d_gpu.hpp.
References sanity_checks(), and tune().
on_boxl_change()
void CoulombMMM1DGpu::on_boxl_change () inline
Definition at line 57 of file mmm1d_gpu.hpp.
on_cell_structure_change()
void CoulombMMM1DGpu::on_cell_structure_change () inline
Definition at line 60 of file mmm1d_gpu.hpp.
on_node_grid_change()
void CoulombMMM1DGpu::on_node_grid_change () const inline
Definition at line 58 of file mmm1d_gpu.hpp.
on_periodicity_change()
void CoulombMMM1DGpu::on_periodicity_change () const inline
Definition at line 59 of file mmm1d_gpu.hpp.
sanity_checks()
void CoulombMMM1DGpu::sanity_checks () const inline
Definition at line 63 of file mmm1d_gpu.hpp.
References Coulomb::Actor< CoulombMMM1DGpu >::sanity_checks_charge_neutrality().
Referenced by on_activation().
tune()
void CoulombMMM1DGpu::tune ()
Definition at line 68 of file mmm1d_gpu.cpp.
References bessel_cutoff, far_switch_radius, EspressoSystemInterface::init(), EspressoSystemInterface::Instance(), maxPWerror, and this_node.
Referenced by on_activation().
Member Data Documentation
bessel_cutoff
int CoulombMMM1DGpu::bessel_cutoff
Definition at line 43 of file mmm1d_gpu.hpp.
Referenced by tune().
far_switch_radius
double CoulombMMM1DGpu::far_switch_radius
Definition at line 41 of file mmm1d_gpu.hpp.
Referenced by tune().
far_switch_radius_sq
double CoulombMMM1DGpu::far_switch_radius_sq
Definition at line 42 of file mmm1d_gpu.hpp.
maxPWerror
double CoulombMMM1DGpu::maxPWerror
Definition at line 40 of file mmm1d_gpu.hpp.
Referenced by CoulombMMM1DGpu(), and tune().
The documentation for this class was generated from the following files:
mmm1d_gpu.hpp
mmm1d_gpu.cpp
mmm1d_gpu_cuda.cu