ESPResSo: walberla::pystencils::ContinuityKernel_double_precision Class Reference
walberla::pystencils::ContinuityKernel_double_precision Class Reference
#include <ContinuityKernel_double_precision.h>
Public Member Functions
ContinuityKernel_double_precision (BlockDataID jID_, BlockDataID rhoID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ContinuityKernel_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< ContinuityKernel_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file ContinuityKernel_double_precision.h.
Constructor & Destructor Documentation
ContinuityKernel_double_precision()
walberla::pystencils::ContinuityKernel_double_precision::ContinuityKernel_double_precision (BlockDataID jID_, BlockDataID rhoID_) inline
Definition at line 55 of file ContinuityKernel_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::ContinuityKernel_double_precision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 93 of file ContinuityKernel_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_double_precision::getSweep () inline
Definition at line 80 of file ContinuityKernel_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_double_precision::getSweep (const shared_ptr< ContinuityKernel_double_precision > & kernel) inline static
Definition at line 67 of file ContinuityKernel_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_double_precision::getSweepOnCellInterval (const shared_ptr< ContinuityKernel_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 71 of file ContinuityKernel_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 85 of file ContinuityKernel_double_precision.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::ContinuityKernel_double_precision::operator() (IBlock * block) inline
Definition at line 64 of file ContinuityKernel_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::ContinuityKernel_double_precision::run (IBlock * block)
Definition at line 60 of file ContinuityKernel_double_precision.cpp.
References block(), walberla::pystencils::internal_5c5e903f8ea7925cf790d7c2318b2c56::continuitykernel_double_precision_continuitykernel_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ContinuityKernel_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 85 of file ContinuityKernel_double_precision.cpp.
References block(), walberla::pystencils::internal_5c5e903f8ea7925cf790d7c2318b2c56::continuitykernel_double_precision_continuitykernel_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
ContinuityKernel_double_precision.h
ContinuityKernel_double_precision.cpp