ESPResSo: AtomDecomposition Class Reference
AtomDecomposition Class Reference
Atom decomposition cell system.
#include <AtomDecomposition.hpp>
Public Member Functions
AtomDecomposition (BoxGeometry const &m_box)
AtomDecomposition (boost::mpi::communicator comm, BoxGeometry const &box_geo)
void resort (bool global_flag, std::vector< ParticleChange > &diff) override
GhostCommunicator const & exchange_ghosts_comm () const override
GhostCommunicator const & collect_ghost_force_comm () const override
std::span< Cell *const > local_cells () const override
std::span< Cell *const > ghost_cells () const override
auto const & get_local_cells () const
auto const & get_ghost_cells () const
Cell * particle_to_cell (Particle const &p) override
Determine which cell a particle id belongs to.
Cell const * particle_to_cell (Particle const &p) const override
Utils::Vector3d max_cutoff () const override
Utils::Vector3d max_range () const override
std::optional< BoxGeometry > minimum_image_distance () const override
BoxGeometry const & box () const override
Public Member Functions inherited from ParticleDecomposition
virtual ~ParticleDecomposition ()=default
Detailed Description
Atom decomposition cell system.
This implements a distributed particle storage by just evenly distributing the particles over all part-taking nodes. Pairs are found by just considering all pairs independent of logical or physical location, it has therefore quadratic time complexity in the number of particles.
For a more detailed discussion please see [36].
Definition at line 53 of file AtomDecomposition.hpp.
Constructor & Destructor Documentation
AtomDecomposition() [1/2]
AtomDecomposition::AtomDecomposition (BoxGeometry const & m_box)
Definition at line 147 of file AtomDecomposition.cpp.
AtomDecomposition() [2/2]
AtomDecomposition::AtomDecomposition (boost::mpi::communicator comm, BoxGeometry const & box_geo)
Definition at line 150 of file AtomDecomposition.cpp.
Member Function Documentation
box()
BoxGeometry const & AtomDecomposition::box () const inline override virtual
Implements ParticleDecomposition.
Definition at line 109 of file AtomDecomposition.hpp.
collect_ghost_force_comm()
GhostCommunicator const & AtomDecomposition::collect_ghost_force_comm () const inline override virtual
Implements ParticleDecomposition.
Definition at line 74 of file AtomDecomposition.hpp.
Referenced by HybridDecomposition::HybridDecomposition().
exchange_ghosts_comm()
GhostCommunicator const & AtomDecomposition::exchange_ghosts_comm () const inline override virtual
Implements ParticleDecomposition.
Definition at line 71 of file AtomDecomposition.hpp.
Referenced by HybridDecomposition::HybridDecomposition().
get_ghost_cells()
auto const & AtomDecomposition::get_ghost_cells () const inline
Definition at line 83 of file AtomDecomposition.hpp.
Referenced by HybridDecomposition::HybridDecomposition().
get_local_cells()
auto const & AtomDecomposition::get_local_cells () const inline
Definition at line 82 of file AtomDecomposition.hpp.
Referenced by HybridDecomposition::count_particles_in_n_square(), HybridDecomposition::HybridDecomposition(), and HybridDecomposition::resort().
ghost_cells()
std::span< Cell *const > AtomDecomposition::ghost_cells () const inline override virtual
Implements ParticleDecomposition.
Definition at line 79 of file AtomDecomposition.hpp.
local_cells()
std::span< Cell *const > AtomDecomposition::local_cells () const inline override virtual
Implements ParticleDecomposition.
Definition at line 78 of file AtomDecomposition.hpp.
Referenced by HybridDecomposition::resort().
max_cutoff()
Utils::Vector3d AtomDecomposition::max_cutoff () const override virtual
Implements ParticleDecomposition.
Definition at line 161 of file AtomDecomposition.cpp.
References Utils::Vector< T, N >::broadcast().
Referenced by HybridDecomposition::max_cutoff(), and max_range().
max_range()
Utils::Vector3d AtomDecomposition::max_range () const override virtual
Implements ParticleDecomposition.
Definition at line 165 of file AtomDecomposition.cpp.
References max_cutoff().
Referenced by HybridDecomposition::max_range().
minimum_image_distance()
std::optional< BoxGeometry > AtomDecomposition::minimum_image_distance () const inline override virtual
Implements ParticleDecomposition.
Definition at line 105 of file AtomDecomposition.hpp.
particle_to_cell() [1/2]
Cell const * AtomDecomposition::particle_to_cell (Particle const & p) const inline override virtual
Implements ParticleDecomposition.
Definition at line 96 of file AtomDecomposition.hpp.
References Particle::id().
particle_to_cell() [2/2]
Cell * AtomDecomposition::particle_to_cell (Particle const & p) inline override virtual
Determine which cell a particle id belongs to.
Since there is only one local cell this is trivial.
Parameters
p Particle to find cell for.
Returns
Pointer to cell or nullptr if not local.
Implements ParticleDecomposition.
Definition at line 93 of file AtomDecomposition.hpp.
References Particle::id().
Referenced by HybridDecomposition::particle_to_cell(), and HybridDecomposition::particle_to_cell().
resort()
void AtomDecomposition::resort (bool global_flag, std::vector< ParticleChange > & diff) override virtual
Implements ParticleDecomposition.
Definition at line 106 of file AtomDecomposition.cpp.
References BoxGeometry::fold_position(), RemovedParticle::id, Cell::particles(), and stream.
Referenced by HybridDecomposition::resort().
The documentation for this class was generated from the following files:
AtomDecomposition.hpp
AtomDecomposition.cpp