ESPResSo: ScriptInterface::walberla::LBFluid Class Reference
ScriptInterface::walberla::LBFluid Class Reference
#include <LBFluid.hpp>
Public Member Functions
LBFluid ()
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &name, VariantMap const &params) override
auto get_lb_fluid () const
auto get_lb_params () const
auto get_mpi_cart_comm_observer () const
::LatticeModel::units_map get_lattice_to_md_units_conversion () const override
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Types
using Base = LatticeModel<::LBWalberlaBase, LBVTKHandle >
Protected Member Functions
void make_instance (VariantMap const &params) override
Protected Member Functions inherited from ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >
auto find_vtk (std::shared_ptr< LBVTKHandle > const &vtk) const
auto has_vtk (std::shared_ptr< LBVTKHandle > const &vtk) const
auto serialize_vtk_writers () const
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes
std::shared_ptr<::LB::LBWalberlaParams > m_lb_params
std::optional< ResourceObserver > m_mpi_cart_comm_observer
bool m_is_active
double m_conv_dist
double m_conv_visc
double m_conv_dens
double m_conv_speed
double m_conv_press
double m_conv_force
double m_conv_force_dens
double m_conv_energy
Protected Attributes inherited from ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >
std::shared_ptr< LatticeWalberla > m_lattice
std::shared_ptr< ::LBWalberlaBase > m_instance
std::vector< std::shared_ptr< LBVTKHandle > > m_vtk_writers
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
Definition at line 70 of file LBFluid.hpp.
Member Typedef Documentation
Base
using ScriptInterface::walberla::LBFluid::Base = LatticeModel<::LBWalberlaBase, LBVTKHandle> protected
Definition at line 72 of file LBFluid.hpp.
Constructor & Destructor Documentation
LBFluid()
ScriptInterface::walberla::LBFluid::LBFluid () inline
Definition at line 86 of file LBFluid.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), ScriptInterface::ObjectHandle::context(), m_conv_dens, m_conv_energy, m_conv_force_dens, m_conv_visc, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_instance, m_is_active, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_lattice, m_lb_params, ScriptInterface::Context::parallel_try_catch(), ScriptInterface::AutoParameter::read_only, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::serialize_vtk_writers(), and stream.
Member Function Documentation
do_call_method()
Variant ScriptInterface::walberla::LBFluid::do_call_method (std::string const & name, VariantMap const & params) override virtual
Reimplemented from ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >.
Definition at line 71 of file LBFluid.cpp.
References System::System::box_geo, ScriptInterface::ObjectHandle::context(), ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::do_call_method(), ScriptInterface::get_value(), System::System::lb, ScriptInterface::walberla::lb_throw_if_expired(), m_conv_dist, m_conv_force, m_conv_speed, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_instance, m_is_active, m_lb_params, m_mpi_cart_comm_observer, ScriptInterface::ObjectHandle::name(), System::System::on_lb_boundary_conditions_change(), ScriptInterface::Context::parallel_try_catch(), LB::Solver::reset(), stream, and LB::LBWalberla::update_collision_model().
do_construct()
void ScriptInterface::walberla::LBFluid::do_construct (VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 169 of file LBFluid.cpp.
References ScriptInterface::ObjectHandle::context(), get_lattice_to_md_units_conversion(), walberla::get_mpi_cart_comm_observer(), m_conv_dens, m_conv_dist, m_conv_energy, m_conv_force, m_conv_force_dens, m_conv_press, m_conv_speed, m_conv_visc, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_instance, m_is_active, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_lattice, m_lb_params, m_mpi_cart_comm_observer, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_vtk_writers, make_instance(), ScriptInterface::Context::parallel_try_catch(), and stream.
get_lattice_to_md_units_conversion()
::LatticeModel::units_map ScriptInterface::walberla::LBFluid::get_lattice_to_md_units_conversion () const inline override virtual
Implements ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >.
Definition at line 152 of file LBFluid.hpp.
References m_conv_dens, m_conv_press, and m_conv_speed.
Referenced by do_construct().
get_lb_fluid()
auto ScriptInterface::walberla::LBFluid::get_lb_fluid () const inline
Definition at line 145 of file LBFluid.hpp.
References ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_instance.
get_lb_params()
auto ScriptInterface::walberla::LBFluid::get_lb_params () const inline
Definition at line 146 of file LBFluid.hpp.
References m_lb_params.
get_mpi_cart_comm_observer()
auto ScriptInterface::walberla::LBFluid::get_mpi_cart_comm_observer () const inline
Definition at line 147 of file LBFluid.hpp.
References m_mpi_cart_comm_observer.
make_instance()
void ScriptInterface::walberla::LBFluid::make_instance (VariantMap const & params) override protected virtual
Implements ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >.
Definition at line 143 of file LBFluid.cpp.
References ScriptInterface::CodeInfo::check_features(), ScriptInterface::get_value_or(), m_conv_dens, m_conv_visc, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_instance, ScriptInterface::walberla::LatticeModel<::LBWalberlaBase, LBVTKHandle >::m_lattice, new_lb_walberla_cpu(), new_lb_walberla_gpu(), and stream.
Referenced by do_construct().
Member Data Documentation
m_conv_dens
double ScriptInterface::walberla::LBFluid::m_conv_dens protected
Definition at line 78 of file LBFluid.hpp.
Referenced by do_construct(), get_lattice_to_md_units_conversion(), LBFluid(), and make_instance().
m_conv_dist
double ScriptInterface::walberla::LBFluid::m_conv_dist protected
Definition at line 76 of file LBFluid.hpp.
Referenced by do_call_method(), and do_construct().
m_conv_energy
double ScriptInterface::walberla::LBFluid::m_conv_energy protected
Definition at line 83 of file LBFluid.hpp.
Referenced by do_construct(), and LBFluid().
m_conv_force
double ScriptInterface::walberla::LBFluid::m_conv_force protected
Definition at line 81 of file LBFluid.hpp.
Referenced by do_call_method(), and do_construct().
m_conv_force_dens
double ScriptInterface::walberla::LBFluid::m_conv_force_dens protected
Definition at line 82 of file LBFluid.hpp.
Referenced by do_construct(), and LBFluid().
m_conv_press
double ScriptInterface::walberla::LBFluid::m_conv_press protected
Definition at line 80 of file LBFluid.hpp.
Referenced by do_construct(), and get_lattice_to_md_units_conversion().
m_conv_speed
double ScriptInterface::walberla::LBFluid::m_conv_speed protected
Definition at line 79 of file LBFluid.hpp.
Referenced by do_call_method(), do_construct(), and get_lattice_to_md_units_conversion().
m_conv_visc
double ScriptInterface::walberla::LBFluid::m_conv_visc protected
Definition at line 77 of file LBFluid.hpp.
Referenced by do_construct(), LBFluid(), and make_instance().
m_is_active
bool ScriptInterface::walberla::LBFluid::m_is_active protected
Definition at line 75 of file LBFluid.hpp.
Referenced by do_call_method(), do_construct(), and LBFluid().
m_lb_params
std::shared_ptr<::LB::LBWalberlaParams> ScriptInterface::walberla::LBFluid::m_lb_params protected
Definition at line 73 of file LBFluid.hpp.
Referenced by do_call_method(), do_construct(), get_lb_params(), and LBFluid().
m_mpi_cart_comm_observer
std::optional<ResourceObserver> ScriptInterface::walberla::LBFluid::m_mpi_cart_comm_observer protected
Definition at line 74 of file LBFluid.hpp.
Referenced by do_call_method(), do_construct(), and get_mpi_cart_comm_observer().
The documentation for this class was generated from the following files:
LBFluid.hpp
LBFluid.cpp