ESPResSo: HybridDecomposition Class Reference
HybridDecomposition Class Reference
Hybrid decomposition cell system.
#include <HybridDecomposition.hpp>
Public Member Functions
HybridDecomposition (boost::mpi::communicator comm, double cutoff_regular, double skin, std::function< bool()> get_ghost_flags, BoxGeometry const &box_geo, LocalBox const &local_box, std::set< int > n_square_types)
auto get_cell_grid () const
auto get_cell_size () const
auto get_n_square_types () const
void resort (bool global, std::vector< ParticleChange > &diff) override
auto get_cutoff_regular () const
GhostCommunicator const & exchange_ghosts_comm () const override
GhostCommunicator const & collect_ghost_force_comm () const override
Utils::Span< Cell *const > local_cells () const override
Utils::Span< Cell *const > ghost_cells () const override
Cell * particle_to_cell (Particle const &p) override
Cell const * particle_to_cell (Particle const &p) const override
Utils::Vector3d max_cutoff () const override
Utils::Vector3d max_range () const override
boost::optional< BoxGeometry > minimum_image_distance () const override
BoxGeometry const & box () const override
std::size_t count_particles_in_regular () const
Count particles in child regular decompositions.
std::size_t count_particles_in_n_square () const
Count particles in child N-square decompositions.
Public Member Functions inherited from ParticleDecomposition
virtual ~ParticleDecomposition ()=default
Detailed Description
Hybrid decomposition cell system.
Store particles with short-range interactions in a RegularDecomposition cell system and particles with long-range interactions in a AtomDecomposition (N-square) cell system. All regular cells are coupled to the N-square cells.
Definition at line 56 of file HybridDecomposition.hpp.
Constructor & Destructor Documentation
HybridDecomposition()
HybridDecomposition::HybridDecomposition (boost::mpi::communicator comm, double cutoff_regular, double skin, std::function< bool()> get_ghost_flags, BoxGeometry const & box_geo, LocalBox const & local_box, std::set< int > n_square_types)
Definition at line 43 of file HybridDecomposition.cpp.
References AtomDecomposition::collect_ghost_force_comm(), RegularDecomposition::collect_ghost_force_comm(), GhostCommunicator::communications, AtomDecomposition::exchange_ghosts_comm(), RegularDecomposition::exchange_ghosts_comm(), AtomDecomposition::get_ghost_cells(), RegularDecomposition::get_ghost_cells(), AtomDecomposition::get_local_cells(), RegularDecomposition::get_local_cells(), and RegularDecomposition::local_cells().
Member Function Documentation
box()
BoxGeometry const& HybridDecomposition::box () const inline override virtual
Implements ParticleDecomposition.
Definition at line 134 of file HybridDecomposition.hpp.
collect_ghost_force_comm()
GhostCommunicator const& HybridDecomposition::collect_ghost_force_comm () const inline override virtual
Implements ParticleDecomposition.
Definition at line 99 of file HybridDecomposition.hpp.
count_particles_in_n_square()
std::size_t HybridDecomposition::count_particles_in_n_square () const inline
Count particles in child N-square decompositions.
Definition at line 142 of file HybridDecomposition.hpp.
References AtomDecomposition::get_local_cells().
count_particles_in_regular()
std::size_t HybridDecomposition::count_particles_in_regular () const inline
Count particles in child regular decompositions.
Definition at line 137 of file HybridDecomposition.hpp.
References RegularDecomposition::get_local_cells().
exchange_ghosts_comm()
GhostCommunicator const& HybridDecomposition::exchange_ghosts_comm () const inline override virtual
Implements ParticleDecomposition.
Definition at line 95 of file HybridDecomposition.hpp.
Referenced by resort().
get_cell_grid()
auto HybridDecomposition::get_cell_grid () const inline
Definition at line 85 of file HybridDecomposition.hpp.
References RegularDecomposition::cell_grid.
get_cell_size()
auto HybridDecomposition::get_cell_size () const inline
Definition at line 87 of file HybridDecomposition.hpp.
References RegularDecomposition::cell_size.
get_cutoff_regular()
auto HybridDecomposition::get_cutoff_regular () const inline
Definition at line 93 of file HybridDecomposition.hpp.
get_n_square_types()
auto HybridDecomposition::get_n_square_types () const inline
Definition at line 89 of file HybridDecomposition.hpp.
ghost_cells()
Utils::Span<Cell *const> HybridDecomposition::ghost_cells () const inline override virtual
Implements ParticleDecomposition.
Definition at line 107 of file HybridDecomposition.hpp.
References Utils::make_span().
local_cells()
Utils::Span<Cell *const> HybridDecomposition::local_cells () const inline override virtual
Implements ParticleDecomposition.
Definition at line 103 of file HybridDecomposition.hpp.
References Utils::make_span().
max_cutoff()
Utils::Vector3d HybridDecomposition::max_cutoff () const inline override virtual
Implements ParticleDecomposition.
Definition at line 125 of file HybridDecomposition.hpp.
References AtomDecomposition::max_cutoff().
max_range()
Utils::Vector3d HybridDecomposition::max_range () const inline override virtual
Implements ParticleDecomposition.
Definition at line 128 of file HybridDecomposition.hpp.
References AtomDecomposition::max_range().
minimum_image_distance()
boost::optional<BoxGeometry> HybridDecomposition::minimum_image_distance () const inline override virtual
Implements ParticleDecomposition.
Definition at line 130 of file HybridDecomposition.hpp.
particle_to_cell() [1/2]
Cell const* HybridDecomposition::particle_to_cell (Particle const & p) const inline override virtual
Implements ParticleDecomposition.
Definition at line 118 of file HybridDecomposition.hpp.
References AtomDecomposition::particle_to_cell(), RegularDecomposition::particle_to_cell(), and Particle::type().
particle_to_cell() [2/2]
Cell* HybridDecomposition::particle_to_cell (Particle const & p) inline override virtual
Implements ParticleDecomposition.
Definition at line 111 of file HybridDecomposition.hpp.
References AtomDecomposition::particle_to_cell(), RegularDecomposition::particle_to_cell(), and Particle::type().
Referenced by resort().
resort()
void HybridDecomposition::resort (bool global, std::vector< ParticleChange > & diff) override virtual
Implements ParticleDecomposition.
Definition at line 98 of file HybridDecomposition.cpp.
References exchange_ghosts_comm(), AtomDecomposition::get_local_cells(), RegularDecomposition::get_local_cells(), ghost_communicator(), GHOSTTRANS_PARTNUM, RemovedParticle::id, AtomDecomposition::local_cells(), RegularDecomposition::local_cells(), map_data_parts(), particle_to_cell(), RegularDecomposition::resort(), and AtomDecomposition::resort().
The documentation for this class was generated from the following files:
HybridDecomposition.hpp
HybridDecomposition.cpp