ESPResSo: Observables::RDF Class Reference
Observables::RDF Class Reference
Radial distribution function.
#include <RDF.hpp>
Public Member Functions
std::vector< std::size_t > shape () const override
RDF (std::vector< int > ids1, std::vector< int > ids2, int n_r_bins, double min_r, double max_r)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > & ids1 ()
std::vector< int > & ids2 ()
std::vector< int > const & ids1 () const
std::vector< int > const & ids2 () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Public Attributes
double min_r
double max_r
std::size_t n_r_bins
Detailed Description
Radial distribution function.
Definition at line 35 of file core/observables/RDF.hpp.
Constructor & Destructor Documentation
RDF()
Observables::RDF::RDF (std::vector< int > ids1, std::vector< int > ids2, int n_r_bins, double min_r, double max_r) inline
Definition at line 55 of file core/observables/RDF.hpp.
References max_r, min_r, and n_r_bins.
Member Function Documentation
ids1() [1/2]
std::vector< int > & Observables::RDF::ids1 () inline
Definition at line 68 of file core/observables/RDF.hpp.
Referenced by operator()().
ids1() [2/2]
std::vector< int > const & Observables::RDF::ids1 () const inline
Definition at line 70 of file core/observables/RDF.hpp.
ids2() [1/2]
std::vector< int > & Observables::RDF::ids2 () inline
Definition at line 69 of file core/observables/RDF.hpp.
Referenced by operator()().
ids2() [2/2]
std::vector< int > const & Observables::RDF::ids2 () const inline
Definition at line 71 of file core/observables/RDF.hpp.
operator()()
std::vector< double > Observables::RDF::operator() (boost::mpi::communicator const & comm) const final virtual
Implements Observables::Observable.
Definition at line 40 of file RDF.cpp.
References fetch_particles(), ids1(), ids2(), and stream.
shape()
std::vector< std::size_t > Observables::RDF::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 53 of file core/observables/RDF.hpp.
References n_r_bins.
Member Data Documentation
max_r
double Observables::RDF::max_r
Definition at line 49 of file core/observables/RDF.hpp.
Referenced by RDF().
min_r
double Observables::RDF::min_r
Definition at line 49 of file core/observables/RDF.hpp.
Referenced by RDF().
n_r_bins
std::size_t Observables::RDF::n_r_bins
Definition at line 51 of file core/observables/RDF.hpp.
Referenced by RDF(), and shape().
The documentation for this class was generated from the following files:
core/observables/RDF.hpp
RDF.cpp