ESPResSo: walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX Class Reference
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX Class Reference
#include <StreamCollideSweepThermalizedSinglePrecisionAVX.h>
Public Member Functions
StreamCollideSweepThermalizedSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepThermalizedSinglePrecisionAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepThermalizedSinglePrecisionAVX()
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::StreamCollideSweepThermalizedSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 55 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
~StreamCollideSweepThermalizedSinglePrecisionAVX()
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::~StreamCollideSweepThermalizedSinglePrecisionAVX () inline
Definition at line 65 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 107 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getBlock_offset_0 () const inline
Definition at line 116 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getBlock_offset_1 () const inline
Definition at line 117 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getBlock_offset_2 () const inline
Definition at line 118 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getKt()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getKt () const inline
Definition at line 119 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getOmega_bulk () const inline
Definition at line 120 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getOmega_even () const inline
Definition at line 121 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getOmega_odd () const inline
Definition at line 122 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getOmega_shear () const inline
Definition at line 123 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getSeed () const inline
Definition at line 124 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getSweep () inline
Definition at line 94 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getSweep (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionAVX > & kernel) inline static
Definition at line 80 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 85 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 99 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::getTime_step () const inline
Definition at line 125 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::operator() (IBlock * block) inline
Definition at line 77 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::run (IBlock * block)
Definition at line 741 of file StreamCollideSweepThermalizedSinglePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_482af0085ade5d86c474548ac4b32084::streamcollidesweepthermalizedsingleprecisionavx_streamcollidesweepthermalizedsingleprecisionavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 804 of file StreamCollideSweepThermalizedSinglePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_482af0085ade5d86c474548ac4b32084::streamcollidesweepthermalizedsingleprecisionavx_streamcollidesweepthermalizedsingleprecisionavx().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setBlock_offset_0 (const uint32_t value) inline
Definition at line 126 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setBlock_offset_1 (const uint32_t value) inline
Definition at line 129 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setBlock_offset_2 (const uint32_t value) inline
Definition at line 132 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setKt()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setKt (const float value) inline
Definition at line 135 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setOmega_bulk (const float value) inline
Definition at line 136 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setOmega_even (const float value) inline
Definition at line 137 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setOmega_odd (const float value) inline
Definition at line 138 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setOmega_shear (const float value) inline
Definition at line 139 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setSeed()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setSeed (const uint32_t value) inline
Definition at line 140 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionAVX::setTime_step (const uint32_t value) inline
Definition at line 141 of file StreamCollideSweepThermalizedSinglePrecisionAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepThermalizedSinglePrecisionAVX.h
StreamCollideSweepThermalizedSinglePrecisionAVX.cpp