ESPResSo: walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA Class Reference
walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA Class Reference
#include <ReactionKernelIndexed_3_double_precision_CUDA.h>
Classes
struct IndexInfo
class IndexVectors
Public Member Functions
ReactionKernelIndexed_3_double_precision_CUDA (const std::shared_ptr< StructuredBlockForest > &blocks, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, double order_0, double order_1, double order_2, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2)
ReactionKernelIndexed_3_double_precision_CUDA (BlockDataID indexVectorID_, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, double order_0, double order_1, double order_2, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2)
void run (IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
void inner (IBlock *block, gpuStream_t stream=nullptr)
void outer (IBlock *block, gpuStream_t stream=nullptr)
Vector3< double > getForce (IBlock *)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getInnerSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getOuterSweep (gpuStream_t stream=nullptr)
template<typename FlagField_T >
void fillFromFlagField (const std::shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
Public Attributes
BlockDataID rho_0ID
BlockDataID rho_1ID
BlockDataID rho_2ID
double order_0_
double order_1_
double order_2_
double rate_coefficient_
double stoech_0_
double stoech_1_
double stoech_2_
Detailed Description
Definition at line 75 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
Constructor & Destructor Documentation
ReactionKernelIndexed_3_double_precision_CUDA() [1/2]
walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::ReactionKernelIndexed_3_double_precision_CUDA (const std::shared_ptr< StructuredBlockForest > & blocks, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, double order_0, double order_1, double order_2, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2) inline
Definition at line 143 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References stream.
ReactionKernelIndexed_3_double_precision_CUDA() [2/2]
walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::ReactionKernelIndexed_3_double_precision_CUDA (BlockDataID indexVectorID_, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, double order_0, double order_1, double order_2, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2) inline
Definition at line 160 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::fillFromFlagField (const std::shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 200 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References block(), and stream.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::fillFromFlagField (IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 209 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::ALL, block(), walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::indexVector(), walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::INNER, inner(), walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::OUTER, and stream.
getForce()
Vector3< double > walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::getForce (IBlock *) inline
Definition at line 180 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References stream.
getInnerSweep()
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::getInnerSweep (gpuStream_t stream = nullptr) inline
Definition at line 191 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References inner(), and stream.
getOuterSweep()
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::getOuterSweep (gpuStream_t stream = nullptr) inline
Definition at line 195 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References outer(), and stream.
getSweep()
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 187 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References run(), and stream.
inner()
void walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::inner (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 159 of file ReactionKernelIndexed_3_double_precision_CUDA.cu.
References block(), walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::INNER, and stream.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 172 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
References block(), run(), and stream.
outer()
void walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::outer (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 163 of file ReactionKernelIndexed_3_double_precision_CUDA.cu.
References block(), walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::OUTER, and stream.
Referenced by getOuterSweep().
run()
void walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 155 of file ReactionKernelIndexed_3_double_precision_CUDA.cu.
References walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::IndexVectors::ALL, block(), and stream.
Referenced by getSweep(), and operator()().
Member Data Documentation
order_0_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::order_0_
Definition at line 266 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
order_1_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::order_1_
Definition at line 267 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
order_2_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::order_2_
Definition at line 268 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
rate_coefficient_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::rate_coefficient_
Definition at line 269 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
rho_0ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::rho_0ID
Definition at line 263 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
rho_1ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::rho_1ID
Definition at line 264 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
rho_2ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::rho_2ID
Definition at line 265 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
stoech_0_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::stoech_0_
Definition at line 270 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
stoech_1_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::stoech_1_
Definition at line 271 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
stoech_2_
double walberla::pystencils::ReactionKernelIndexed_3_double_precision_CUDA::stoech_2_
Definition at line 272 of file ReactionKernelIndexed_3_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
ReactionKernelIndexed_3_double_precision_CUDA.h
ReactionKernelIndexed_3_double_precision_CUDA.cu