ESPResSo: walberla::pystencils::InitialPDFsSetterDoublePrecision Class Reference
walberla::pystencils::InitialPDFsSetterDoublePrecision Class Reference
#include <InitialPDFsSetterDoublePrecision.h>
Public Member Functions
InitialPDFsSetterDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, double rho_0)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< InitialPDFsSetterDoublePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterDoublePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID forceID
BlockDataID pdfsID
BlockDataID velocityID
double rho_0_
Detailed Description
Definition at line 53 of file InitialPDFsSetterDoublePrecision.h.
Constructor & Destructor Documentation
InitialPDFsSetterDoublePrecision()
walberla::pystencils::InitialPDFsSetterDoublePrecision::InitialPDFsSetterDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, double rho_0) inline
Definition at line 55 of file InitialPDFsSetterDoublePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::InitialPDFsSetterDoublePrecision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 95 of file InitialPDFsSetterDoublePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecision::getSweep () inline
Definition at line 82 of file InitialPDFsSetterDoublePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecision::getSweep (const shared_ptr< InitialPDFsSetterDoublePrecision > & kernel) inline static
Definition at line 69 of file InitialPDFsSetterDoublePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecision::getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterDoublePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 73 of file InitialPDFsSetterDoublePrecision.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 87 of file InitialPDFsSetterDoublePrecision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::InitialPDFsSetterDoublePrecision::operator() (IBlock * block) inline
Definition at line 66 of file InitialPDFsSetterDoublePrecision.h.
References block(), and run().
run()
void walberla::pystencils::InitialPDFsSetterDoublePrecision::run (IBlock * block)
Definition at line 82 of file InitialPDFsSetterDoublePrecision.cpp.
References block(), forceID, walberla::pystencils::internal_2df07fce91f5444fc18533f996cd1a79::initialpdfssetterdoubleprecision_initialpdfssetterdoubleprecision(), pdfsID, RESTRICT, rho_0_, velocity(), and velocityID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::InitialPDFsSetterDoublePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 122 of file InitialPDFsSetterDoublePrecision.cpp.
References block(), forceID, walberla::pystencils::internal_2df07fce91f5444fc18533f996cd1a79::initialpdfssetterdoubleprecision_initialpdfssetterdoubleprecision(), pdfsID, RESTRICT, rho_0_, velocity(), and velocityID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
forceID
BlockDataID walberla::pystencils::InitialPDFsSetterDoublePrecision::forceID
Definition at line 98 of file InitialPDFsSetterDoublePrecision.h.
Referenced by run(), and runOnCellInterval().
pdfsID
BlockDataID walberla::pystencils::InitialPDFsSetterDoublePrecision::pdfsID
Definition at line 99 of file InitialPDFsSetterDoublePrecision.h.
Referenced by run(), and runOnCellInterval().
rho_0_
double walberla::pystencils::InitialPDFsSetterDoublePrecision::rho_0_
Definition at line 101 of file InitialPDFsSetterDoublePrecision.h.
Referenced by run(), and runOnCellInterval().
velocityID
BlockDataID walberla::pystencils::InitialPDFsSetterDoublePrecision::velocityID
Definition at line 100 of file InitialPDFsSetterDoublePrecision.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
InitialPDFsSetterDoublePrecision.h
InitialPDFsSetterDoublePrecision.cpp