ESPResSo: DipolarTuningAlgorithm Class Reference
DipolarTuningAlgorithm Class Reference
Public Member Functions
DipolarTuningAlgorithm (System::System &system, dp3m_data_struct &input_dp3m, double prefactor, int timings)
P3MParameters & get_params () override
void on_solver_change () const override
std::optional< std::string > layer_correction_veto_r_cut (double) const override
void setup_logger (bool verbose) override
std::tuple< double, double, double, double > calculate_accuracy (Utils::Vector3i const &mesh, int cao, double r_cut_iL) const override
void determine_mesh_limits () override
TuningAlgorithm::Parameters get_time () override
Public Member Functions inherited from TuningAlgorithm
TuningAlgorithm (System::System &system, double prefactor, int timings)
virtual ~TuningAlgorithm ()=default
void determine_r_cut_limits ()
Determine a sensible range for the real-space cutoff.
void determine_cao_limits (int initial_cao)
Determine a sensible range for the charge assignment order.
void commit (Utils::Vector3i const &mesh, int cao, double r_cut_iL, double alpha_L)
Write tuned parameters to the P3M parameter struct.
void tune ()
Additional Inherited Members
Protected Member Functions inherited from TuningAlgorithm
auto get_n_trials ()
void increment_n_trials ()
void reset_n_trials ()
double get_m_time (Utils::Vector3i const &mesh, int &tuned_cao, double &tuned_r_cut_iL, double &tuned_alpha_L, double &tuned_accuracy)
Get the optimal alpha and the corresponding computation time for a fixed mesh.
double get_mc_time (Utils::Vector3i const &mesh, int cao, double &tuned_r_cut_iL, double &tuned_alpha_L, double &tuned_accuracy)
Get the optimal alpha and the corresponding computation time for a fixed mesh and cao.
Protected Attributes inherited from TuningAlgorithm
System::System & m_system
double m_prefactor
std::unique_ptr< TuningLogger > m_logger = nullptr
int cao_min = -1
int cao_max = -1
int cao_best = -1
double m_r_cut_iL_min = -1.
double m_r_cut_iL_max = -1.
Static Protected Attributes inherited from TuningAlgorithm
static constexpr auto time_granularity = 2.
Granularity of the time measurement (milliseconds).
static constexpr auto max_n_consecutive_trials = 20
Maximal number of consecutive trials that don't improve runtime.
static constexpr auto time_sentinel = std::numeric_limits<double>::max()
Value for invalid time measurements.
Detailed Description
Definition at line 605 of file dp3m.cpp.
Constructor & Destructor Documentation
DipolarTuningAlgorithm()
DipolarTuningAlgorithm::DipolarTuningAlgorithm (System::System & system, dp3m_data_struct & input_dp3m, double prefactor, int timings) inline
Definition at line 610 of file dp3m.cpp.
Member Function Documentation
calculate_accuracy()
std::tuple<double, double, double, double> DipolarTuningAlgorithm::calculate_accuracy (Utils::Vector3i const & mesh, int cao, double r_cut_iL) const inline override virtual
Implements TuningAlgorithm.
Definition at line 634 of file dp3m.cpp.
References P3MParameters::accuracy, System::System::box_geo, dp3m_k_space_error(), dp3m_real_space_error(), dp3m_rtbisection(), TuningAlgorithm::m_system, Utils::Vector< T, N >::norm(), p3m_data_struct_base::params, Utils::sqrt_2(), dp3m_data_struct::sum_dip_part, and dp3m_data_struct::sum_mu2.
determine_mesh_limits()
void DipolarTuningAlgorithm::determine_mesh_limits () inline override virtual
Implements TuningAlgorithm.
Definition at line 667 of file dp3m.cpp.
References TuningAlgorithm::m_logger, P3MParameters::mesh, p3m_data_struct_base::params, and dp3m_data_struct::sum_dip_part.
Referenced by DipolarP3M::tune().
get_params()
P3MParameters& DipolarTuningAlgorithm::get_params () inline override virtual
Implements TuningAlgorithm.
Definition at line 614 of file dp3m.cpp.
References p3m_data_struct_base::params.
get_time()
TuningAlgorithm::Parameters DipolarTuningAlgorithm::get_time () inline override virtual
Implements TuningAlgorithm.
Definition at line 683 of file dp3m.cpp.
References Utils::Vector< T, N >::broadcast(), TuningAlgorithm::cao_best, TuningAlgorithm::get_m_time(), TuningAlgorithm::get_n_trials(), TuningAlgorithm::m_r_cut_iL_max, TuningAlgorithm::max_n_consecutive_trials, TuningAlgorithm::Parameters::mesh, TuningAlgorithm::reset_n_trials(), TuningAlgorithm::time_granularity, and TuningAlgorithm::time_sentinel.
layer_correction_veto_r_cut()
std::optional<std::string> DipolarTuningAlgorithm::layer_correction_veto_r_cut (double) const inline override virtual
Implements TuningAlgorithm.
Definition at line 619 of file dp3m.cpp.
on_solver_change()
void DipolarTuningAlgorithm::on_solver_change () const inline override virtual
Implements TuningAlgorithm.
Definition at line 616 of file dp3m.cpp.
References TuningAlgorithm::m_system, and System::System::on_dipoles_change().
setup_logger()
void DipolarTuningAlgorithm::setup_logger (bool verbose) inline override virtual
Implements TuningAlgorithm.
Definition at line 623 of file dp3m.cpp.
References P3MParameters::accuracy, System::System::box_geo, TuningLogger::Dipolar, TuningAlgorithm::m_logger, TuningAlgorithm::m_prefactor, TuningAlgorithm::m_system, p3m_data_struct_base::params, dp3m_data_struct::sum_dip_part, dp3m_data_struct::sum_mu2, and this_node.
Referenced by DipolarP3M::tune().
The documentation for this class was generated from the following file:
dp3m.cpp