ESPResSo: walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized Class Reference
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized Class Reference
#include <StreamCollideSweepDoublePrecisionThermalized.h>
Public Member Functions
StreamCollideSweepDoublePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepDoublePrecisionThermalized ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionThermalized > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionThermalized > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepDoublePrecisionThermalized.h.
Constructor & Destructor Documentation
StreamCollideSweepDoublePrecisionThermalized()
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::StreamCollideSweepDoublePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file StreamCollideSweepDoublePrecisionThermalized.h.
~StreamCollideSweepDoublePrecisionThermalized()
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::~StreamCollideSweepDoublePrecisionThermalized () inline
Definition at line 67 of file StreamCollideSweepDoublePrecisionThermalized.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 108 of file StreamCollideSweepDoublePrecisionThermalized.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getBlock_offset_0 () const inline
Definition at line 117 of file StreamCollideSweepDoublePrecisionThermalized.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getBlock_offset_1 () const inline
Definition at line 118 of file StreamCollideSweepDoublePrecisionThermalized.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getBlock_offset_2 () const inline
Definition at line 119 of file StreamCollideSweepDoublePrecisionThermalized.h.
getKt()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getKt () const inline
Definition at line 120 of file StreamCollideSweepDoublePrecisionThermalized.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getOmega_bulk () const inline
Definition at line 121 of file StreamCollideSweepDoublePrecisionThermalized.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getOmega_even () const inline
Definition at line 122 of file StreamCollideSweepDoublePrecisionThermalized.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getOmega_odd () const inline
Definition at line 123 of file StreamCollideSweepDoublePrecisionThermalized.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getOmega_shear () const inline
Definition at line 124 of file StreamCollideSweepDoublePrecisionThermalized.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getSeed () const inline
Definition at line 125 of file StreamCollideSweepDoublePrecisionThermalized.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getSweep () inline
Definition at line 95 of file StreamCollideSweepDoublePrecisionThermalized.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionThermalized > & kernel) inline static
Definition at line 81 of file StreamCollideSweepDoublePrecisionThermalized.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionThermalized > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 86 of file StreamCollideSweepDoublePrecisionThermalized.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 100 of file StreamCollideSweepDoublePrecisionThermalized.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::getTime_step () const inline
Definition at line 126 of file StreamCollideSweepDoublePrecisionThermalized.h.
operator()()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::operator() (IBlock * block) inline
Definition at line 79 of file StreamCollideSweepDoublePrecisionThermalized.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::run (IBlock * block)
Definition at line 426 of file StreamCollideSweepDoublePrecisionThermalized.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_bdc99b91ffd091fa865a4ccd734ba062::streamcollidesweepdoubleprecisionthermalized_streamcollidesweepdoubleprecisionthermalized().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 486 of file StreamCollideSweepDoublePrecisionThermalized.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_bdc99b91ffd091fa865a4ccd734ba062::streamcollidesweepdoubleprecisionthermalized_streamcollidesweepdoubleprecisionthermalized().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setBlock_offset_0 (const uint32_t value) inline
Definition at line 127 of file StreamCollideSweepDoublePrecisionThermalized.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setBlock_offset_1 (const uint32_t value) inline
Definition at line 130 of file StreamCollideSweepDoublePrecisionThermalized.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setBlock_offset_2 (const uint32_t value) inline
Definition at line 133 of file StreamCollideSweepDoublePrecisionThermalized.h.
setKt()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setKt (const double value) inline
Definition at line 136 of file StreamCollideSweepDoublePrecisionThermalized.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setOmega_bulk (const double value) inline
Definition at line 137 of file StreamCollideSweepDoublePrecisionThermalized.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setOmega_even (const double value) inline
Definition at line 138 of file StreamCollideSweepDoublePrecisionThermalized.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setOmega_odd (const double value) inline
Definition at line 139 of file StreamCollideSweepDoublePrecisionThermalized.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setOmega_shear (const double value) inline
Definition at line 140 of file StreamCollideSweepDoublePrecisionThermalized.h.
setSeed()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setSeed (const uint32_t value) inline
Definition at line 141 of file StreamCollideSweepDoublePrecisionThermalized.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalized::setTime_step (const uint32_t value) inline
Definition at line 142 of file StreamCollideSweepDoublePrecisionThermalized.h.
The documentation for this class was generated from the following files:
StreamCollideSweepDoublePrecisionThermalized.h
StreamCollideSweepDoublePrecisionThermalized.cpp