ESPResSo: Observables::BondAngles Class Reference
Observables::BondAngles Class Reference
Calculate bond angles between particles in a polymer.
#include <BondAngles.hpp>
Public Member Functions
BondAngles (std::vector< int > ids)
std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, const ParticleObservables::traits< Particle > &traits) const override
std::vector< std::size_t > shape () const override
PidObservable (std::vector< int > ids)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > const & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Detailed Description
Calculate bond angles between particles in a polymer.
For \(n \) bonded particles, return the \(n-2 \) angles along the chain, in radians.
Definition at line 43 of file BondAngles.hpp.
Constructor & Destructor Documentation
BondAngles()
Observables::BondAngles::BondAngles (std::vector< int > ids) inline explicit
Definition at line 46 of file BondAngles.hpp.
References Observables::PidObservable::ids().
Member Function Documentation
evaluate()
std::vector< double > Observables::BondAngles::evaluate (boost::mpi::communicator const & comm, ParticleReferenceRange const & local_particles, const ParticleObservables::traits< Particle > & traits) const inline override virtual
Implements Observables::PidObservable.
Definition at line 52 of file BondAngles.hpp.
References System::System::box_geo, System::get_system(), Observables::PidObservable::ids(), Observables::Observable::n_values(), stream, and tiny_cos_angle_value.
PidObservable()
Observables::PidObservable::PidObservable (std::vector< int > ids) inline explicit
Definition at line 64 of file core/observables/PidObservable.hpp.
shape()
std::vector< std::size_t > Observables::BondAngles::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 83 of file BondAngles.hpp.
References Observables::PidObservable::ids(), and stream.
The documentation for this class was generated from the following file:
BondAngles.hpp