ESPResSo: walberla::pystencils::ReactionKernelIndexed_5_double_precision Class Reference
walberla::pystencils::ReactionKernelIndexed_5_double_precision Class Reference
#include <ReactionKernelIndexed_5_double_precision.h>
Classes
struct IndexInfo
class IndexVectors
Public Member Functions
ReactionKernelIndexed_5_double_precision (const std::shared_ptr< StructuredBlockForest > &blocks, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, double order_0, double order_1, double order_2, double order_3, double order_4, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3, double stoech_4)
ReactionKernelIndexed_5_double_precision (BlockDataID indexVectorID_, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, double order_0, double order_1, double order_2, double order_3, double order_4, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3, double stoech_4)
void run (IBlock *block)
void operator() (IBlock *block)
void inner (IBlock *block)
void outer (IBlock *block)
Vector3< double > getForce (IBlock *)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getInnerSweep ()
std::function< void(IBlock *)> getOuterSweep ()
template<typename FlagField_T >
void fillFromFlagField (const std::shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
Public Attributes
BlockDataID rho_0ID
BlockDataID rho_1ID
BlockDataID rho_2ID
BlockDataID rho_3ID
BlockDataID rho_4ID
double order_0_
double order_1_
double order_2_
double order_3_
double order_4_
double rate_coefficient_
double stoech_0_
double stoech_1_
double stoech_2_
double stoech_3_
double stoech_4_
Detailed Description
Definition at line 73 of file ReactionKernelIndexed_5_double_precision.h.
Constructor & Destructor Documentation
ReactionKernelIndexed_5_double_precision() [1/2]
walberla::pystencils::ReactionKernelIndexed_5_double_precision::ReactionKernelIndexed_5_double_precision (const std::shared_ptr< StructuredBlockForest > & blocks, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, double order_0, double order_1, double order_2, double order_3, double order_4, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3, double stoech_4) inline
Definition at line 108 of file ReactionKernelIndexed_5_double_precision.h.
References stream.
ReactionKernelIndexed_5_double_precision() [2/2]
walberla::pystencils::ReactionKernelIndexed_5_double_precision::ReactionKernelIndexed_5_double_precision (BlockDataID indexVectorID_, BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, double order_0, double order_1, double order_2, double order_3, double order_4, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3, double stoech_4) inline
Definition at line 128 of file ReactionKernelIndexed_5_double_precision.h.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::pystencils::ReactionKernelIndexed_5_double_precision::fillFromFlagField (const std::shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 170 of file ReactionKernelIndexed_5_double_precision.h.
References block(), and stream.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::pystencils::ReactionKernelIndexed_5_double_precision::fillFromFlagField (IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 179 of file ReactionKernelIndexed_5_double_precision.h.
References walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::ALL, block(), walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::indexVector(), walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::INNER, inner(), walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::OUTER, and stream.
getForce()
Vector3< double > walberla::pystencils::ReactionKernelIndexed_5_double_precision::getForce (IBlock *) inline
Definition at line 150 of file ReactionKernelIndexed_5_double_precision.h.
References stream.
getInnerSweep()
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelIndexed_5_double_precision::getInnerSweep () inline
Definition at line 161 of file ReactionKernelIndexed_5_double_precision.h.
References inner().
getOuterSweep()
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelIndexed_5_double_precision::getOuterSweep () inline
Definition at line 165 of file ReactionKernelIndexed_5_double_precision.h.
References outer().
getSweep()
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelIndexed_5_double_precision::getSweep () inline
Definition at line 157 of file ReactionKernelIndexed_5_double_precision.h.
References run().
inner()
void walberla::pystencils::ReactionKernelIndexed_5_double_precision::inner (IBlock * block)
Definition at line 139 of file ReactionKernelIndexed_5_double_precision.cpp.
References block(), and walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::INNER.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::pystencils::ReactionKernelIndexed_5_double_precision::operator() (IBlock * block) inline
Definition at line 144 of file ReactionKernelIndexed_5_double_precision.h.
References block(), and run().
outer()
void walberla::pystencils::ReactionKernelIndexed_5_double_precision::outer (IBlock * block)
Definition at line 143 of file ReactionKernelIndexed_5_double_precision.cpp.
References block(), and walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::OUTER.
Referenced by getOuterSweep().
run()
void walberla::pystencils::ReactionKernelIndexed_5_double_precision::run (IBlock * block)
Definition at line 135 of file ReactionKernelIndexed_5_double_precision.cpp.
References walberla::pystencils::ReactionKernelIndexed_5_double_precision::IndexVectors::ALL, and block().
Referenced by getSweep(), and operator()().
Member Data Documentation
order_0_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::order_0_
Definition at line 237 of file ReactionKernelIndexed_5_double_precision.h.
order_1_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::order_1_
Definition at line 238 of file ReactionKernelIndexed_5_double_precision.h.
order_2_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::order_2_
Definition at line 239 of file ReactionKernelIndexed_5_double_precision.h.
order_3_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::order_3_
Definition at line 240 of file ReactionKernelIndexed_5_double_precision.h.
order_4_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::order_4_
Definition at line 241 of file ReactionKernelIndexed_5_double_precision.h.
rate_coefficient_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::rate_coefficient_
Definition at line 242 of file ReactionKernelIndexed_5_double_precision.h.
rho_0ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_5_double_precision::rho_0ID
Definition at line 232 of file ReactionKernelIndexed_5_double_precision.h.
rho_1ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_5_double_precision::rho_1ID
Definition at line 233 of file ReactionKernelIndexed_5_double_precision.h.
rho_2ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_5_double_precision::rho_2ID
Definition at line 234 of file ReactionKernelIndexed_5_double_precision.h.
rho_3ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_5_double_precision::rho_3ID
Definition at line 235 of file ReactionKernelIndexed_5_double_precision.h.
rho_4ID
BlockDataID walberla::pystencils::ReactionKernelIndexed_5_double_precision::rho_4ID
Definition at line 236 of file ReactionKernelIndexed_5_double_precision.h.
stoech_0_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::stoech_0_
Definition at line 243 of file ReactionKernelIndexed_5_double_precision.h.
stoech_1_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::stoech_1_
Definition at line 244 of file ReactionKernelIndexed_5_double_precision.h.
stoech_2_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::stoech_2_
Definition at line 245 of file ReactionKernelIndexed_5_double_precision.h.
stoech_3_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::stoech_3_
Definition at line 246 of file ReactionKernelIndexed_5_double_precision.h.
stoech_4_
double walberla::pystencils::ReactionKernelIndexed_5_double_precision::stoech_4_
Definition at line 247 of file ReactionKernelIndexed_5_double_precision.h.
The documentation for this class was generated from the following files:
ReactionKernelIndexed_5_double_precision.h
ReactionKernelIndexed_5_double_precision.cpp