ESPResSo: CommBuf Class Reference
CommBuf Class Reference
Class that stores marshalled data for ghost communications.
Public Member Functions
char * data ()
Returns a pointer to the non-bond storage.
const char * data () const
std::size_t size () const
Returns the number of elements in the non-bond storage.
void resize (std::size_t new_size)
Resizes the underlying storage s.t.
auto & bonds ()
Returns a reference to the bond storage.
const auto & bonds () const
Detailed Description
Class that stores marshalled data for ghost communications.
To store and retrieve data, use the adapter classes below.
Definition at line 63 of file ghosts.cpp.
Member Function Documentation
bonds() [1/2]
auto& CommBuf::bonds () inline
Returns a reference to the bond storage.
Definition at line 82 of file ghosts.cpp.
Referenced by ghost_communicator(), prepare_recv_buffer(), prepare_send_buffer(), and put_recv_buffer().
bonds() [2/2]
const auto& CommBuf::bonds () const inline
Definition at line 83 of file ghosts.cpp.
data() [1/2]
char* CommBuf::data () inline
Returns a pointer to the non-bond storage.
Definition at line 67 of file ghosts.cpp.
Referenced by ghost_communicator().
data() [2/2]
const char* CommBuf::data () const inline
Definition at line 68 of file ghosts.cpp.
resize()
void CommBuf::resize (std::size_t new_size) inline
Resizes the underlying storage s.t.
the object is capable of holding "new_size" chars.
Parameters
new_size new size
Definition at line 78 of file ghosts.cpp.
Referenced by cell_cell_transfer(), prepare_recv_buffer(), and prepare_send_buffer().
size()
std::size_t CommBuf::size () const inline
Returns the number of elements in the non-bond storage.
Definition at line 72 of file ghosts.cpp.
Referenced by ghost_communicator(), prepare_send_buffer(), and put_recv_buffer().
The documentation for this class was generated from the following file:
ghosts.cpp