ESPResSo: walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA Class Reference
walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA Class Reference
#include <ReactionKernelBulk_2_double_precision_CUDA.h>
Public Member Functions
ReactionKernelBulk_2_double_precision_CUDA (BlockDataID rho_0ID_, BlockDataID rho_1ID_, double order_0, double order_1, double rate_coefficient, double stoech_0, double stoech_1)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getOrder_0 () const
double getOrder_1 () const
double getRate_coefficient () const
double getStoech_0 () const
double getStoech_1 () const
void setOrder_0 (const double value)
void setOrder_1 (const double value)
void setRate_coefficient (const double value)
void setStoech_0 (const double value)
void setStoech_1 (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ReactionKernelBulk_2_double_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_2_double_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file ReactionKernelBulk_2_double_precision_CUDA.h.
Constructor & Destructor Documentation
ReactionKernelBulk_2_double_precision_CUDA()
walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::ReactionKernelBulk_2_double_precision_CUDA (BlockDataID rho_0ID_, BlockDataID rho_1ID_, double order_0, double order_1, double rate_coefficient, double stoech_0, double stoech_1) inline
Definition at line 57 of file ReactionKernelBulk_2_double_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 108 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getOrder_0()
double walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getOrder_0 () const inline
Definition at line 111 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getOrder_1()
double walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getOrder_1 () const inline
Definition at line 112 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getRate_coefficient()
double walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getRate_coefficient () const inline
Definition at line 113 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getStoech_0()
double walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getStoech_0 () const inline
Definition at line 114 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getStoech_1()
double walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getStoech_1 () const inline
Definition at line 115 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getSweep (const shared_ptr< ReactionKernelBulk_2_double_precision_CUDA > & kernel) inline static
Definition at line 77 of file ReactionKernelBulk_2_double_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 93 of file ReactionKernelBulk_2_double_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_2_double_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 82 of file ReactionKernelBulk_2_double_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 98 of file ReactionKernelBulk_2_double_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 73 of file ReactionKernelBulk_2_double_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 63 of file ReactionKernelBulk_2_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 94 of file ReactionKernelBulk_2_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setOrder_0()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::setOrder_0 (const double value) inline
Definition at line 116 of file ReactionKernelBulk_2_double_precision_CUDA.h.
setOrder_1()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::setOrder_1 (const double value) inline
Definition at line 117 of file ReactionKernelBulk_2_double_precision_CUDA.h.
setRate_coefficient()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::setRate_coefficient (const double value) inline
Definition at line 118 of file ReactionKernelBulk_2_double_precision_CUDA.h.
setStoech_0()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::setStoech_0 (const double value) inline
Definition at line 121 of file ReactionKernelBulk_2_double_precision_CUDA.h.
setStoech_1()
void walberla::pystencils::ReactionKernelBulk_2_double_precision_CUDA::setStoech_1 (const double value) inline
Definition at line 122 of file ReactionKernelBulk_2_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
ReactionKernelBulk_2_double_precision_CUDA.h
ReactionKernelBulk_2_double_precision_CUDA.cu