ESPResSo: walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA Class Reference
walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA Class Reference
#include <DiffusiveFluxKernel_double_precision_CUDA.h>
Public Member Functions
DiffusiveFluxKernel_double_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_, double D)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getD () const
void setD (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernel_double_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernel_double_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file DiffusiveFluxKernel_double_precision_CUDA.h.
Constructor & Destructor Documentation
DiffusiveFluxKernel_double_precision_CUDA()
walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::DiffusiveFluxKernel_double_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_, double D) inline
Definition at line 57 of file DiffusiveFluxKernel_double_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 103 of file DiffusiveFluxKernel_double_precision_CUDA.h.
getD()
double walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::getD () const inline
Definition at line 106 of file DiffusiveFluxKernel_double_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::getSweep (const shared_ptr< DiffusiveFluxKernel_double_precision_CUDA > & kernel) inline static
Definition at line 72 of file DiffusiveFluxKernel_double_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 88 of file DiffusiveFluxKernel_double_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernel_double_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 77 of file DiffusiveFluxKernel_double_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 93 of file DiffusiveFluxKernel_double_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 68 of file DiffusiveFluxKernel_double_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 97 of file DiffusiveFluxKernel_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 129 of file DiffusiveFluxKernel_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setD()
void walberla::pystencils::DiffusiveFluxKernel_double_precision_CUDA::setD (const double value) inline
Definition at line 107 of file DiffusiveFluxKernel_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernel_double_precision_CUDA.h
DiffusiveFluxKernel_double_precision_CUDA.cu