ESPResSo: ScriptInterface::Integrators::VelocityVerletIsoNPT Class Reference
ScriptInterface::Integrators::VelocityVerletIsoNPT Class Reference
#include <VelocityVerletIsoNPT.hpp>
Public Member Functions
VelocityVerletIsoNPT ()
void do_construct (VariantMap const &params) override
void activate () override
::NptIsoParameters const & get_instance () const
Public Member Functions inherited from ScriptInterface::AutoParameters< VelocityVerletIsoNPT, Integrator >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< VelocityVerletIsoNPT, Integrator >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 39 of file VelocityVerletIsoNPT.hpp.
Constructor & Destructor Documentation
VelocityVerletIsoNPT()
ScriptInterface::Integrators::VelocityVerletIsoNPT::VelocityVerletIsoNPT ()
Definition at line 40 of file VelocityVerletIsoNPT.cpp.
References ScriptInterface::AutoParameters< VelocityVerletIsoNPT, Integrator >::add_parameters(), NptIsoParameters::cubic_box, NptIsoParameters::get_direction(), get_instance(), NptIsoParameters::p_ext, NptIsoParameters::piston, and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
activate()
void ScriptInterface::Integrators::VelocityVerletIsoNPT::activate () override
Definition at line 67 of file VelocityVerletIsoNPT.cpp.
References INTEG_METHOD_NPT_ISO_AND, INTEG_METHOD_NPT_ISO_MTK, System::System::nptiso, System::System::on_thermostat_param_change(), and System::System::propagation.
do_construct()
void ScriptInterface::Integrators::VelocityVerletIsoNPT::do_construct (VariantMap const & params) override
Definition at line 53 of file VelocityVerletIsoNPT.cpp.
References Utils::Vector< T, N >::broadcast(), and stream.
get_instance()
::NptIsoParameters const & ScriptInterface::Integrators::VelocityVerletIsoNPT::get_instance () const inline
Definition at line 50 of file VelocityVerletIsoNPT.hpp.
Referenced by VelocityVerletIsoNPT().
The documentation for this class was generated from the following files:
VelocityVerletIsoNPT.hpp
VelocityVerletIsoNPT.cpp