ESPResSo: walberla::pystencils::PackInfoVecDoublePrecision Class Reference
walberla::pystencils::PackInfoVecDoublePrecision Class Reference
#include <PackInfoVecDoublePrecision.h>
Public Member Functions
PackInfoVecDoublePrecision (BlockDataID fieldID_)
~PackInfoVecDoublePrecision () override=default
bool constantDataExchange () const override
bool threadsafeReceiving () const override
void unpackData (IBlock *receiver, stencil::Direction dir, mpi::RecvBuffer &buffer) override
void communicateLocal (const IBlock *sender, IBlock *receiver, stencil::Direction dir) override
void packDataImpl (const IBlock *sender, stencil::Direction dir, mpi::SendBuffer &outBuffer) const override
void pack (stencil::Direction dir, unsigned char *buffer, IBlock *block) const
void unpack (stencil::Direction dir, unsigned char *buffer, IBlock *block) const
uint_t size (stencil::Direction dir, const IBlock *block) const
Detailed Description
Definition at line 45 of file PackInfoVecDoublePrecision.h.
Constructor & Destructor Documentation
PackInfoVecDoublePrecision()
walberla::pystencils::PackInfoVecDoublePrecision::PackInfoVecDoublePrecision (BlockDataID fieldID_) inline
Definition at line 48 of file PackInfoVecDoublePrecision.h.
~PackInfoVecDoublePrecision()
walberla::pystencils::PackInfoVecDoublePrecision::~PackInfoVecDoublePrecision () override default
Member Function Documentation
communicateLocal()
void walberla::pystencils::PackInfoVecDoublePrecision::communicateLocal (const IBlock * sender, IBlock * receiver, stencil::Direction dir) inline override
Definition at line 63 of file PackInfoVecDoublePrecision.h.
References stream, and unpackData().
constantDataExchange()
bool walberla::pystencils::PackInfoVecDoublePrecision::constantDataExchange () const inline override
Definition at line 51 of file PackInfoVecDoublePrecision.h.
pack()
void walberla::pystencils::PackInfoVecDoublePrecision::pack (stencil::Direction dir, unsigned char * buffer, IBlock * block) const
Definition at line 69 of file PackInfoVecDoublePrecision.cpp.
References block(), walberla::pystencils::internal_05a1eb9a7382e5e7047cdb22e28b6556::pack_SW_BW_W_TW_NW_BS_S_TS_B_C_T_BN_N_TN_SE_BE_E_TE_NE(), RESTRICT, and stream.
Referenced by packDataImpl().
packDataImpl()
void walberla::pystencils::PackInfoVecDoublePrecision::packDataImpl (const IBlock * sender, stencil::Direction dir, mpi::SendBuffer & outBuffer) const inline override
Definition at line 71 of file PackInfoVecDoublePrecision.h.
References pack(), size(), and stream.
size()
uint_t walberla::pystencils::PackInfoVecDoublePrecision::size (stencil::Direction dir, const IBlock * block) const
Definition at line 174 of file PackInfoVecDoublePrecision.cpp.
References block(), and stream.
Referenced by packDataImpl(), and unpackData().
threadsafeReceiving()
bool walberla::pystencils::PackInfoVecDoublePrecision::threadsafeReceiving () const inline override
Definition at line 52 of file PackInfoVecDoublePrecision.h.
unpack()
void walberla::pystencils::PackInfoVecDoublePrecision::unpack (stencil::Direction dir, unsigned char * buffer, IBlock * block) const
Definition at line 121 of file PackInfoVecDoublePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_1ccccad4ca561e07a0934cadb07d0fc1::unpack_SW_BW_W_TW_NW_BS_S_TS_B_C_T_BN_N_TN_SE_BE_E_TE_NE().
Referenced by unpackData().
unpackData()
void walberla::pystencils::PackInfoVecDoublePrecision::unpackData (IBlock * receiver, stencil::Direction dir, mpi::RecvBuffer & buffer) inline override
Definition at line 54 of file PackInfoVecDoublePrecision.h.
References size(), stream, and unpack().
Referenced by communicateLocal().
The documentation for this class was generated from the following files:
PackInfoVecDoublePrecision.h
PackInfoVecDoublePrecision.cpp