ESPResSo: ScriptInterface::Thermostat::Thermostat Class Reference
ScriptInterface::Thermostat::Thermostat Class Reference
#include <thermostat.hpp>
Public Member Functions
Thermostat ()
Variant do_call_method (std::string const &name, VariantMap const &params) override
void do_construct (VariantMap const &params) override
void on_bind_system (::System::System &system) override
Public Member Functions inherited from ScriptInterface::AutoParameters< Thermostat, System::Leaf >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::System::Leaf
~Leaf () override=default
void bind_system (std::shared_ptr<::System::System > const &system)
void detach_system ()
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
template<typename T >
auto make_autoparameter (T Thermostat::*member, char const *name)
template<typename T >
void setup_thermostat (std::shared_ptr< T > &thermostat, VariantMap const &params)
template<typename T >
void turn_thermostat_off (T &thermostat)
void update_global_kT (double old_kT, double new_kT, int thermo_flag)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Thermostat, System::Leaf >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Member Functions inherited from ScriptInterface::System::Leaf
auto const & get_system () const
auto & get_system ()
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Attributes inherited from ScriptInterface::System::Leaf
std::weak_ptr<::System::System > m_system
Detailed Description
Definition at line 508 of file script_interface/thermostat/thermostat.hpp.
Constructor & Destructor Documentation
Thermostat()
ScriptInterface::Thermostat::Thermostat::Thermostat () inline
Definition at line 634 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::AutoParameters< Thermostat, System::Leaf >::add_parameters(), make_autoparameter(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_call_method()
Variant ScriptInterface::Thermostat::Thermostat::do_call_method (std::string const & name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 659 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::System::Leaf::get_system(), ScriptInterface::ObjectHandle::name(), ScriptInterface::Context::parallel_try_catch(), setup_thermostat(), stream, THERMO_OFF, and turn_thermostat_off().
do_construct()
void ScriptInterface::Thermostat::Thermostat::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 712 of file script_interface/thermostat/thermostat.hpp.
make_autoparameter()
template<typename T > auto ScriptInterface::Thermostat::Thermostat::make_autoparameter (T Thermostat::* member, char const * name) inline protected
Definition at line 547 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::ObjectHandle::name(), and stream.
Referenced by Thermostat().
on_bind_system()
void ScriptInterface::Thermostat::Thermostat::on_bind_system (::System::System & system) inline override virtual
Reimplemented from ScriptInterface::System::Leaf.
Definition at line 716 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::ObjectHandle::context(), and stream.
setup_thermostat()
template<typename T > void ScriptInterface::Thermostat::Thermostat::setup_thermostat (std::shared_ptr< T > & thermostat, VariantMap const & params) inline protected
Definition at line 561 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::System::Leaf::m_system, ScriptInterface::Context::parallel_try_catch(), stream, turn_thermostat_off(), and update_global_kT().
Referenced by do_call_method().
turn_thermostat_off()
template<typename T > void ScriptInterface::Thermostat::Thermostat::turn_thermostat_off (T & thermostat) inline protected
Definition at line 603 of file script_interface/thermostat/thermostat.hpp.
References stream.
Referenced by do_call_method(), and setup_thermostat().
update_global_kT()
void ScriptInterface::Thermostat::Thermostat::update_global_kT (double old_kT, double new_kT, int thermo_flag) inline protected
Definition at line 614 of file script_interface/thermostat/thermostat.hpp.
References Thermostat::are_kT_equal(), ScriptInterface::System::Leaf::get_system(), stream, THERMO_BOND, and THERMO_OFF.
Referenced by setup_thermostat().
The documentation for this class was generated from the following file:
script_interface/thermostat/thermostat.hpp