ESPResSo: ScriptInterface::AutoParameters< Derived, Base > Class Template Reference
ScriptInterface::AutoParameters< Derived, Base > Class Template Reference
Bind parameters in the script interface.
#include <AutoParameters.hpp>
Classes
struct UnknownParameter
Exception thrown when accessing an unknown parameter.
struct WriteError
Exception thrown when writing to a read-only parameter.
Public Member Functions
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
virtual void do_construct (VariantMap const &params)
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
virtual Variant do_call_method (const std::string &, const VariantMap &)
Local implementation of call_method.
std::string serialize () const
Protected Member Functions
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
template<typename Derived, typename Base = ObjectHandle>
class ScriptInterface::AutoParameters< Derived, Base >
Bind parameters in the script interface.
This class implements ScriptInterfaceBase, binding the parameters added by add_parameters or by the constructor. To use it, derive from this class and add parameters. For example, given a class A
class A {
public:
  int i() { return m_i; }
private:
  int m_i;
};
that should have i exposed, this can be achieved by extending it like this:
class A : public AutoParameters {
public:
  A() : AutoParameters({"name_for_i", i}) {}
  int i() { return m_i; }
private:
  int m_i;
};
If there is more complicated logic needed, specific setters and getters can be provided. E.g. given a class B like
class B {
public:
  void set_i(int);
  int get_i();
private:
  int m_i;
};
we can use a lambdas to set and get the parameter like this:
class B : public AutoParameters {
public:
  B() : AutoParameters({"name_for_i",
                        [this](Variant const& v) {set_i(get_value<int>(v));},
                        [this]() {return get_i();}
                       }) {}
  void set_i(int);
  int get_i();
private:
  int m_i;
};
(this has to be captured in the lambdas to have access to the member functions of the class).
Definition at line 94 of file AutoParameters.hpp.
Constructor & Destructor Documentation
AutoParameters() [1/2]
template<typename Derived , typename Base = ObjectHandle> ScriptInterface::AutoParameters< Derived, Base >::AutoParameters () protected default
AutoParameters() [2/2]
template<typename Derived , typename Base = ObjectHandle> ScriptInterface::AutoParameters< Derived, Base >::AutoParameters (std::vector< AutoParameter > && params) inline explicit protected
Definition at line 114 of file AutoParameters.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters().
~AutoParameters()
template<typename Derived , typename Base = ObjectHandle> ScriptInterface::AutoParameters< Derived, Base >::~AutoParameters () override protected default
Member Function Documentation
add_parameters()
template<typename Derived , typename Base = ObjectHandle> void ScriptInterface::AutoParameters< Derived, Base >::add_parameters (std::vector< AutoParameter > && params) inline protected
Definition at line 123 of file AutoParameters.hpp.
References stream.
Referenced by ScriptInterface::AutoParameters< Derived, Base >::AutoParameters(), ScriptInterface::Thermostat::Brownian::Brownian(), ScriptInterface::Coulomb::CoulombMMM1D::CoulombMMM1D(), ScriptInterface::Coulomb::CoulombP3M::CoulombP3M(), ScriptInterface::Coulomb::CoulombScafacos::CoulombScafacos(), ScriptInterface::Coulomb::DebyeHueckel::DebyeHueckel(), ScriptInterface::Dipoles::DipolarDirectSum::DipolarDirectSum(), ScriptInterface::Dipoles::DipolarLayerCorrection::DipolarLayerCorrection(), ScriptInterface::Dipoles::DipolarP3M< Architecture >::DipolarP3M(), ScriptInterface::Dipoles::DipolarScafacos::DipolarScafacos(), ScriptInterface::walberla::EKSpecies::EKSpecies(), ScriptInterface::Coulomb::ElectrostaticLayerCorrection::ElectrostaticLayerCorrection(), ScriptInterface::Interactions::InteractionBMHTF::InteractionBMHTF(), ScriptInterface::Interactions::InteractionBuckingham::InteractionBuckingham(), ScriptInterface::Interactions::InteractionDPD::InteractionDPD(), ScriptInterface::Interactions::InteractionGaussian::InteractionGaussian(), ScriptInterface::Interactions::InteractionGayBerne::InteractionGayBerne(), ScriptInterface::Interactions::InteractionHat::InteractionHat(), ScriptInterface::Interactions::InteractionHertzian::InteractionHertzian(), ScriptInterface::Interactions::InteractionLJ::InteractionLJ(), ScriptInterface::Interactions::InteractionLJcos::InteractionLJcos(), ScriptInterface::Interactions::InteractionLJcos2::InteractionLJcos2(), ScriptInterface::Interactions::InteractionLJGen::InteractionLJGen(), ScriptInterface::Interactions::InteractionMorse::InteractionMorse(), ScriptInterface::Interactions::InteractionSmoothStep::InteractionSmoothStep(), ScriptInterface::Interactions::InteractionSoftSphere::InteractionSoftSphere(), ScriptInterface::Interactions::InteractionTabulated::InteractionTabulated(), ScriptInterface::Interactions::InteractionThole::InteractionThole(), ScriptInterface::Interactions::InteractionWCA::InteractionWCA(), ScriptInterface::Thermostat::IsotropicNpt::IsotropicNpt(), ScriptInterface::Thermostat::Langevin::Langevin(), ScriptInterface::walberla::LBFluid::LBFluid(), ScriptInterface::Thermostat::LBThermostat::LBThermostat(), and ScriptInterface::Coulomb::ReactionField::ReactionField().
do_set_parameter()
template<typename Derived , typename Base = ObjectHandle> void ScriptInterface::AutoParameters< Derived, Base >::do_set_parameter (const std::string & name, const Variant & value) inline final virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 154 of file AutoParameters.hpp.
References ScriptInterface::ObjectHandle::name().
get_parameter()
template<typename Derived , typename Base = ObjectHandle> Variant ScriptInterface::AutoParameters< Derived, Base >::get_parameter (const std::string & name) const inline final virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 146 of file AutoParameters.hpp.
References ScriptInterface::ObjectHandle::name().
get_parameter_insertion_order()
template<typename Derived , typename Base = ObjectHandle> auto const & ScriptInterface::AutoParameters< Derived, Base >::get_parameter_insertion_order () const inline protected
Definition at line 137 of file AutoParameters.hpp.
has_parameter()
template<typename Derived , typename Base = ObjectHandle> bool ScriptInterface::AutoParameters< Derived, Base >::has_parameter (std::string const & name) const inline override protected virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 119 of file AutoParameters.hpp.
References ScriptInterface::ObjectHandle::name().
serialize_parameters()
template<typename Derived , typename Base = ObjectHandle> std::vector< std::pair< std::string, Variant > > ScriptInterface::AutoParameters< Derived, Base >::serialize_parameters () const inline final virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 165 of file AutoParameters.hpp.
References ScriptInterface::ObjectHandle::get_parameters(), and stream.
valid_parameters()
template<typename Derived , typename Base = ObjectHandle> std::vector< std::string_view > ScriptInterface::AutoParameters< Derived, Base >::valid_parameters () const inline final virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 141 of file AutoParameters.hpp.
References stream.
The documentation for this class was generated from the following file:
AutoParameters.hpp