ESPResSo: walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA Class Reference
walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA Class Reference
#include <FrictionCouplingKernel_single_precision_CUDA.h>
Public Member Functions
FrictionCouplingKernel_single_precision_CUDA (BlockDataID fID_, BlockDataID jID_, float D, float kT, float rho_lb)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getD () const
float getKt () const
float getRho_lb () const
void setD (const float value)
void setKt (const float value)
void setRho_lb (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< FrictionCouplingKernel_single_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< FrictionCouplingKernel_single_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file FrictionCouplingKernel_single_precision_CUDA.h.
Constructor & Destructor Documentation
FrictionCouplingKernel_single_precision_CUDA()
walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::FrictionCouplingKernel_single_precision_CUDA (BlockDataID fID_, BlockDataID jID_, float D, float kT, float rho_lb) inline
Definition at line 57 of file FrictionCouplingKernel_single_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 104 of file FrictionCouplingKernel_single_precision_CUDA.h.
getD()
float walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getD () const inline
Definition at line 107 of file FrictionCouplingKernel_single_precision_CUDA.h.
getKt()
float walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getKt () const inline
Definition at line 108 of file FrictionCouplingKernel_single_precision_CUDA.h.
getRho_lb()
float walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getRho_lb () const inline
Definition at line 109 of file FrictionCouplingKernel_single_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getSweep (const shared_ptr< FrictionCouplingKernel_single_precision_CUDA > & kernel) inline static
Definition at line 73 of file FrictionCouplingKernel_single_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 89 of file FrictionCouplingKernel_single_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< FrictionCouplingKernel_single_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 78 of file FrictionCouplingKernel_single_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 94 of file FrictionCouplingKernel_single_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 69 of file FrictionCouplingKernel_single_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 61 of file FrictionCouplingKernel_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 97 of file FrictionCouplingKernel_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setD()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::setD (const float value) inline
Definition at line 110 of file FrictionCouplingKernel_single_precision_CUDA.h.
setKt()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::setKt (const float value) inline
Definition at line 111 of file FrictionCouplingKernel_single_precision_CUDA.h.
setRho_lb()
void walberla::pystencils::FrictionCouplingKernel_single_precision_CUDA::setRho_lb (const float value) inline
Definition at line 112 of file FrictionCouplingKernel_single_precision_CUDA.h.
The documentation for this class was generated from the following files:
FrictionCouplingKernel_single_precision_CUDA.h
FrictionCouplingKernel_single_precision_CUDA.cu