ESPResSo: walberla::FFT< FloatType > Class Template Reference
walberla::FFT< FloatType > Class Template Reference
#include <FFT.hpp>
Public Member Functions
FFT (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
~FFT () override=default
void reset_charge_field () override
void add_charge_to_field (std::size_t id, double valency, bool is_double_precision) override
std::size_t get_potential_field_id () const noexcept override
void solve () override
Public Member Functions inherited from walberla::PoissonSolver
PoissonSolver (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
virtual ~PoissonSolver ()=default
void set_permittivity (double permittivity) noexcept
double get_permittivity () const noexcept
auto const & get_lattice () const noexcept
Detailed Description
template<typename FloatType>
class walberla::FFT< FloatType >
Definition at line 40 of file FFT.hpp.
Constructor & Destructor Documentation
FFT()
template<typename FloatType > walberla::FFT< FloatType >::FFT (std::shared_ptr< LatticeWalberla > lattice, double permittivity) inline
Definition at line 58 of file FFT.hpp.
References walberla::PoissonSolver::get_lattice().
~FFT()
template<typename FloatType > walberla::FFT< FloatType >::~FFT () override default
Member Function Documentation
add_charge_to_field()
template<typename FloatType > void walberla::FFT< FloatType >::add_charge_to_field (std::size_t id, double valency, bool is_double_precision) inline override virtual
Implements walberla::PoissonSolver.
Definition at line 101 of file FFT.hpp.
References block(), walberla::PoissonSolver::get_lattice(), walberla::PoissonSolver::get_permittivity(), and walberla::FFT< FloatType >::get_potential_field_id().
get_potential_field_id()
template<typename FloatType > std::size_t walberla::FFT< FloatType >::get_potential_field_id () const inline override virtual noexcept
Implements walberla::PoissonSolver.
Definition at line 127 of file FFT.hpp.
Referenced by walberla::FFT< FloatType >::add_charge_to_field(), and walberla::FFT< FloatType >::reset_charge_field().
reset_charge_field()
template<typename FloatType > void walberla::FFT< FloatType >::reset_charge_field () inline override virtual
Implements walberla::PoissonSolver.
Definition at line 91 of file FFT.hpp.
References block(), walberla::PoissonSolver::get_lattice(), and walberla::FFT< FloatType >::get_potential_field_id().
solve()
template<typename FloatType > void walberla::FFT< FloatType >::solve () inline override virtual
Implements walberla::PoissonSolver.
Definition at line 131 of file FFT.hpp.
The documentation for this class was generated from the following file:
FFT.hpp