ESPResSo: walberla::pystencils::PackInfoPdfDoublePrecision Class Reference
walberla::pystencils::PackInfoPdfDoublePrecision Class Reference
#include <PackInfoPdfDoublePrecision.h>
Public Member Functions
PackInfoPdfDoublePrecision (BlockDataID pdfsID_)
~PackInfoPdfDoublePrecision () override=default
bool constantDataExchange () const override
bool threadsafeReceiving () const override
void unpackData (IBlock *receiver, stencil::Direction dir, mpi::RecvBuffer &buffer) override
void communicateLocal (const IBlock *sender, IBlock *receiver, stencil::Direction dir) override
void packDataImpl (const IBlock *sender, stencil::Direction dir, mpi::SendBuffer &outBuffer) const override
void pack (stencil::Direction dir, unsigned char *buffer, IBlock *block) const
void unpack (stencil::Direction dir, unsigned char *buffer, IBlock *block) const
uint_t size (stencil::Direction dir, const IBlock *block) const
Detailed Description
Definition at line 45 of file PackInfoPdfDoublePrecision.h.
Constructor & Destructor Documentation
PackInfoPdfDoublePrecision()
walberla::pystencils::PackInfoPdfDoublePrecision::PackInfoPdfDoublePrecision (BlockDataID pdfsID_) inline
Definition at line 48 of file PackInfoPdfDoublePrecision.h.
~PackInfoPdfDoublePrecision()
walberla::pystencils::PackInfoPdfDoublePrecision::~PackInfoPdfDoublePrecision () override default
Member Function Documentation
communicateLocal()
void walberla::pystencils::PackInfoPdfDoublePrecision::communicateLocal (const IBlock * sender, IBlock * receiver, stencil::Direction dir) inline override
Definition at line 63 of file PackInfoPdfDoublePrecision.h.
References stream, and unpackData().
constantDataExchange()
bool walberla::pystencils::PackInfoPdfDoublePrecision::constantDataExchange () const inline override
Definition at line 51 of file PackInfoPdfDoublePrecision.h.
pack()
void walberla::pystencils::PackInfoPdfDoublePrecision::pack (stencil::Direction dir, unsigned char * buffer, IBlock * block) const
Definition at line 521 of file PackInfoPdfDoublePrecision.cpp.
References block(), walberla::pystencils::internal_pack_B::pack_B(), walberla::pystencils::internal_pack_BE::pack_BE(), walberla::pystencils::internal_pack_BN::pack_BN(), walberla::pystencils::internal_pack_BS::pack_BS(), walberla::pystencils::internal_pack_BW::pack_BW(), walberla::pystencils::internal_pack_E::pack_E(), walberla::pystencils::internal_pack_N::pack_N(), walberla::pystencils::internal_pack_NE::pack_NE(), walberla::pystencils::internal_pack_NW::pack_NW(), walberla::pystencils::internal_pack_S::pack_S(), walberla::pystencils::internal_pack_SE::pack_SE(), walberla::pystencils::internal_pack_SW::pack_SW(), walberla::pystencils::internal_pack_T::pack_T(), walberla::pystencils::internal_pack_TE::pack_TE(), walberla::pystencils::internal_pack_TN::pack_TN(), walberla::pystencils::internal_pack_TS::pack_TS(), walberla::pystencils::internal_pack_TW::pack_TW(), walberla::pystencils::internal_pack_W::pack_W(), RESTRICT, and stream.
Referenced by packDataImpl().
packDataImpl()
void walberla::pystencils::PackInfoPdfDoublePrecision::packDataImpl (const IBlock * sender, stencil::Direction dir, mpi::SendBuffer & outBuffer) const inline override
Definition at line 71 of file PackInfoPdfDoublePrecision.h.
References pack(), size(), and stream.
size()
uint_t walberla::pystencils::PackInfoPdfDoublePrecision::size (stencil::Direction dir, const IBlock * block) const
Definition at line 1270 of file PackInfoPdfDoublePrecision.cpp.
References block(), and stream.
Referenced by packDataImpl(), and unpackData().
threadsafeReceiving()
bool walberla::pystencils::PackInfoPdfDoublePrecision::threadsafeReceiving () const inline override
Definition at line 52 of file PackInfoPdfDoublePrecision.h.
unpack()
void walberla::pystencils::PackInfoPdfDoublePrecision::unpack (stencil::Direction dir, unsigned char * buffer, IBlock * block) const
Definition at line 895 of file PackInfoPdfDoublePrecision.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_unpack_B::unpack_B(), walberla::pystencils::internal_unpack_BE::unpack_BE(), walberla::pystencils::internal_unpack_BN::unpack_BN(), walberla::pystencils::internal_unpack_BS::unpack_BS(), walberla::pystencils::internal_unpack_BW::unpack_BW(), walberla::pystencils::internal_unpack_E::unpack_E(), walberla::pystencils::internal_unpack_N::unpack_N(), walberla::pystencils::internal_unpack_NE::unpack_NE(), walberla::pystencils::internal_unpack_NW::unpack_NW(), walberla::pystencils::internal_unpack_S::unpack_S(), walberla::pystencils::internal_unpack_SE::unpack_SE(), walberla::pystencils::internal_unpack_SW::unpack_SW(), walberla::pystencils::internal_unpack_T::unpack_T(), walberla::pystencils::internal_unpack_TE::unpack_TE(), walberla::pystencils::internal_unpack_TN::unpack_TN(), walberla::pystencils::internal_unpack_TS::unpack_TS(), walberla::pystencils::internal_unpack_TW::unpack_TW(), and walberla::pystencils::internal_unpack_W::unpack_W().
Referenced by unpackData().
unpackData()
void walberla::pystencils::PackInfoPdfDoublePrecision::unpackData (IBlock * receiver, stencil::Direction dir, mpi::RecvBuffer & buffer) inline override
Definition at line 54 of file PackInfoPdfDoublePrecision.h.
References size(), stream, and unpack().
Referenced by communicateLocal().
The documentation for this class was generated from the following files:
PackInfoPdfDoublePrecision.h
PackInfoPdfDoublePrecision.cpp