ESPResSo: ScriptInterface::Observables::ProfileObservable< CoreObs > Class Template Reference
ScriptInterface::Observables::ProfileObservable< CoreObs > Class Template Reference
#include <ProfileObservable.hpp>
Public Member Functions
ProfileObservable ()
void construct (VariantMap const &) override
Variant call_method (std::string const &method, VariantMap const &parameters) override
std::shared_ptr<::Observables::ProfileObservable > profile_observable () const
std::shared_ptr<::Observables::Observable > observable () const override
Public Member Functions inherited from ScriptInterface::AutoParameters< ProfileObservable< CoreObs >, Observable >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< ProfileObservable< CoreObs >, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
template<typename CoreObs>
class ScriptInterface::Observables::ProfileObservable< CoreObs >
Definition at line 41 of file script_interface/observables/ProfileObservable.hpp.
Constructor & Destructor Documentation
ProfileObservable()
template<typename CoreObs > ScriptInterface::Observables::ProfileObservable< CoreObs >::ProfileObservable () inline
Definition at line 47 of file script_interface/observables/ProfileObservable.hpp.
References ScriptInterface::AutoParameters< ProfileObservable< CoreObs >, Observable >::add_parameters(), ScriptInterface::Observables::ProfileObservable< CoreObs >::profile_observable(), and stream.
Member Function Documentation
call_method()
template<typename CoreObs > Variant ScriptInterface::Observables::ProfileObservable< CoreObs >::call_method (std::string const & method, VariantMap const & parameters) inline override
Definition at line 107 of file script_interface/observables/ProfileObservable.hpp.
References ScriptInterface::Observables::ProfileObservable< CoreObs >::profile_observable(), and stream.
construct()
template<typename CoreObs > void ScriptInterface::Observables::ProfileObservable< CoreObs >::construct (VariantMap const &) inline override
Definition at line 105 of file script_interface/observables/ProfileObservable.hpp.
observable()
template<typename CoreObs > std::shared_ptr<::Observables::Observable > ScriptInterface::Observables::ProfileObservable< CoreObs >::observable () const inline override
Definition at line 122 of file script_interface/observables/ProfileObservable.hpp.
profile_observable()
template<typename CoreObs > std::shared_ptr<::Observables::ProfileObservable > ScriptInterface::Observables::ProfileObservable< CoreObs >::profile_observable () const inline
Definition at line 118 of file script_interface/observables/ProfileObservable.hpp.
Referenced by ScriptInterface::Observables::ProfileObservable< CoreObs >::call_method(), and ScriptInterface::Observables::ProfileObservable< CoreObs >::ProfileObservable().
The documentation for this class was generated from the following file:
script_interface/observables/ProfileObservable.hpp