ESPResSo: walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision Class Reference
walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision Class Reference
#include <DiffusiveFluxKernelThermalized_double_precision.h>
Public Member Functions
DiffusiveFluxKernelThermalized_double_precision (BlockDataID jID_, BlockDataID rhoID_, double D, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, uint32_t seed, uint32_t time_step)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
double getD () const
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
uint32_t getField_size_0 () const
uint32_t getField_size_1 () const
uint32_t getField_size_2 () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setD (const double value)
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setField_size_0 (const uint32_t value)
void setField_size_1 (const uint32_t value)
void setField_size_2 (const uint32_t value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelThermalized_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelThermalized_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file DiffusiveFluxKernelThermalized_double_precision.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelThermalized_double_precision()
walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::DiffusiveFluxKernelThermalized_double_precision (BlockDataID jID_, BlockDataID rhoID_, double D, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, uint32_t seed, uint32_t time_step) inline
Definition at line 55 of file DiffusiveFluxKernelThermalized_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 101 of file DiffusiveFluxKernelThermalized_double_precision.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getBlock_offset_0 () const inline
Definition at line 111 of file DiffusiveFluxKernelThermalized_double_precision.h.
getBlock_offset_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getBlock_offset_1 () const inline
Definition at line 112 of file DiffusiveFluxKernelThermalized_double_precision.h.
getBlock_offset_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getBlock_offset_2 () const inline
Definition at line 113 of file DiffusiveFluxKernelThermalized_double_precision.h.
getD()
double walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getD () const inline
Definition at line 110 of file DiffusiveFluxKernelThermalized_double_precision.h.
getField_size_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getField_size_0 () const inline
Definition at line 114 of file DiffusiveFluxKernelThermalized_double_precision.h.
getField_size_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getField_size_1 () const inline
Definition at line 115 of file DiffusiveFluxKernelThermalized_double_precision.h.
getField_size_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getField_size_2 () const inline
Definition at line 116 of file DiffusiveFluxKernelThermalized_double_precision.h.
getSeed()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getSeed () const inline
Definition at line 117 of file DiffusiveFluxKernelThermalized_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getSweep () inline
Definition at line 88 of file DiffusiveFluxKernelThermalized_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getSweep (const shared_ptr< DiffusiveFluxKernelThermalized_double_precision > & kernel) inline static
Definition at line 74 of file DiffusiveFluxKernelThermalized_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelThermalized_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 79 of file DiffusiveFluxKernelThermalized_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 93 of file DiffusiveFluxKernelThermalized_double_precision.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::getTime_step () const inline
Definition at line 118 of file DiffusiveFluxKernelThermalized_double_precision.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::operator() (IBlock * block) inline
Definition at line 71 of file DiffusiveFluxKernelThermalized_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::run (IBlock * block)
Definition at line 477 of file DiffusiveFluxKernelThermalized_double_precision.cpp.
References block(), walberla::pystencils::internal_0f4fef9c62f0d4e3c1700727b32f958f::diffusivefluxkernelthermalized_double_precision_diffusivefluxkernelthermalized_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 513 of file DiffusiveFluxKernelThermalized_double_precision.cpp.
References block(), walberla::pystencils::internal_0f4fef9c62f0d4e3c1700727b32f958f::diffusivefluxkernelthermalized_double_precision_diffusivefluxkernelthermalized_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setBlock_offset_0 (const uint32_t value) inline
Definition at line 120 of file DiffusiveFluxKernelThermalized_double_precision.h.
setBlock_offset_1()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setBlock_offset_1 (const uint32_t value) inline
Definition at line 123 of file DiffusiveFluxKernelThermalized_double_precision.h.
setBlock_offset_2()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setBlock_offset_2 (const uint32_t value) inline
Definition at line 126 of file DiffusiveFluxKernelThermalized_double_precision.h.
setD()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setD (const double value) inline
Definition at line 119 of file DiffusiveFluxKernelThermalized_double_precision.h.
setField_size_0()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setField_size_0 (const uint32_t value) inline
Definition at line 129 of file DiffusiveFluxKernelThermalized_double_precision.h.
setField_size_1()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setField_size_1 (const uint32_t value) inline
Definition at line 130 of file DiffusiveFluxKernelThermalized_double_precision.h.
setField_size_2()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setField_size_2 (const uint32_t value) inline
Definition at line 131 of file DiffusiveFluxKernelThermalized_double_precision.h.
setSeed()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setSeed (const uint32_t value) inline
Definition at line 132 of file DiffusiveFluxKernelThermalized_double_precision.h.
setTime_step()
void walberla::pystencils::DiffusiveFluxKernelThermalized_double_precision::setTime_step (const uint32_t value) inline
Definition at line 133 of file DiffusiveFluxKernelThermalized_double_precision.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelThermalized_double_precision.h
DiffusiveFluxKernelThermalized_double_precision.cpp