ESPResSo: EKContainer< EKSpecies > Class Template Reference
EKContainer< EKSpecies > Class Template Reference
#include <EKContainer.hpp>
Public Types
using value_type = container_type::value_type
using iterator = container_type::iterator
using const_iterator = container_type::const_iterator
Public Member Functions
EKContainer (double tau, std::shared_ptr< walberla::PoissonSolver > solver)
bool contains (std::shared_ptr< EKSpecies > const &ek_species) const noexcept
void add (std::shared_ptr< EKSpecies > const &ek_species)
void remove (std::shared_ptr< EKSpecies > const &ek_species)
iterator begin () noexcept
iterator end () noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
bool empty () const noexcept
void set_poisson_solver (std::shared_ptr< walberla::PoissonSolver > const &solver)
bool is_gpu () const noexcept
double get_tau () const noexcept
void set_tau (double tau) noexcept
void reset_charge () const
void add_charge (std::size_t const id, double valency) const
void solve_poisson () const
std::size_t get_potential_field_id () const
LatticeWalberla const & get_lattice () const noexcept
Detailed Description
template<class EKSpecies>
class EKContainer< EKSpecies >
Definition at line 32 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
Member Typedef Documentation
const_iterator
template<class EKSpecies > using EKContainer< EKSpecies >::const_iterator = container_type::const_iterator
Definition at line 38 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
iterator
template<class EKSpecies > using EKContainer< EKSpecies >::iterator = container_type::iterator
Definition at line 37 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
value_type
template<class EKSpecies > using EKContainer< EKSpecies >::value_type = container_type::value_type
Definition at line 36 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
Constructor & Destructor Documentation
EKContainer()
template<class EKSpecies > EKContainer< EKSpecies >::EKContainer (double tau, std::shared_ptr< walberla::PoissonSolver > solver) inline
Definition at line 73 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
Member Function Documentation
add()
template<class EKSpecies > void EKContainer< EKSpecies >::add (std::shared_ptr< EKSpecies > const & ek_species) inline
Definition at line 80 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
References EKContainer< EKSpecies >::contains(), and stream.
add_charge()
template<class EKSpecies > void EKContainer< EKSpecies >::add_charge (std::size_t const id, double valency) const inline
Definition at line 119 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
References stream.
begin() [1/2]
template<class EKSpecies > const_iterator EKContainer< EKSpecies >::begin () const inline noexcept
Definition at line 100 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
begin() [2/2]
template<class EKSpecies > iterator EKContainer< EKSpecies >::begin () inline noexcept
Definition at line 98 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
contains()
template<class EKSpecies > bool EKContainer< EKSpecies >::contains (std::shared_ptr< EKSpecies > const & ek_species) const inline noexcept
Definition at line 76 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
References stream.
Referenced by EKContainer< EKSpecies >::add(), and EKContainer< EKSpecies >::remove().
empty()
template<class EKSpecies > bool EKContainer< EKSpecies >::empty () const inline noexcept
Definition at line 102 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
end() [1/2]
template<class EKSpecies > const_iterator EKContainer< EKSpecies >::end () const inline noexcept
Definition at line 101 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
end() [2/2]
template<class EKSpecies > iterator EKContainer< EKSpecies >::end () inline noexcept
Definition at line 99 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
get_lattice()
template<class EKSpecies > LatticeWalberla const & EKContainer< EKSpecies >::get_lattice () const inline noexcept
Definition at line 129 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
get_potential_field_id()
template<class EKSpecies > std::size_t EKContainer< EKSpecies >::get_potential_field_id () const inline
Definition at line 125 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
get_tau()
template<class EKSpecies > double EKContainer< EKSpecies >::get_tau () const inline noexcept
Definition at line 113 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
is_gpu()
template<class EKSpecies > bool EKContainer< EKSpecies >::is_gpu () const inline noexcept
Definition at line 111 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
remove()
template<class EKSpecies > void EKContainer< EKSpecies >::remove (std::shared_ptr< EKSpecies > const & ek_species) inline
Definition at line 93 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
References EKContainer< EKSpecies >::contains(), and stream.
reset_charge()
template<class EKSpecies > void EKContainer< EKSpecies >::reset_charge () const inline
Definition at line 117 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
set_poisson_solver()
template<class EKSpecies > void EKContainer< EKSpecies >::set_poisson_solver (std::shared_ptr< walberla::PoissonSolver > const & solver) inline
Definition at line 105 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
References stream.
set_tau()
template<class EKSpecies > void EKContainer< EKSpecies >::set_tau (double tau) inline noexcept
Definition at line 115 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
solve_poisson()
template<class EKSpecies > void EKContainer< EKSpecies >::solve_poisson () const inline
Definition at line 123 of file walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp.
The documentation for this class was generated from the following files:
EKWalberla.hpp
walberla_bridge/include/walberla_bridge/electrokinetics/EKContainer.hpp