ESPResSo: ScriptInterface::Observables::LBProfileObservable< CoreLBObs > Class Template Reference
ScriptInterface::Observables::LBProfileObservable< CoreLBObs > Class Template Reference
#include <LBProfileObservable.hpp>
Public Member Functions
LBProfileObservable ()
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
std::shared_ptr<::Observables::Observable > observable () const override
virtual std::shared_ptr<::Observables::LBProfileObservable > profile_observable () const
Public Member Functions inherited from ScriptInterface::AutoParameters< LBProfileObservable< CoreLBObs >, Observable >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< LBProfileObservable< CoreLBObs >, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
Detailed Description
template<typename CoreLBObs>
class ScriptInterface::Observables::LBProfileObservable< CoreLBObs >
Definition at line 43 of file script_interface/observables/LBProfileObservable.hpp.
Constructor & Destructor Documentation
LBProfileObservable()
template<typename CoreLBObs > ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::LBProfileObservable () inline
Definition at line 52 of file script_interface/observables/LBProfileObservable.hpp.
References ScriptInterface::AutoParameters< LBProfileObservable< CoreLBObs >, Observable >::add_parameters(), ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::profile_observable(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_call_method()
template<typename CoreLBObs > Variant ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_call_method (std::string const & method, VariantMap const & parameters) inline override
Definition at line 105 of file script_interface/observables/LBProfileObservable.hpp.
References ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::profile_observable().
do_construct()
template<typename CoreLBObs > void ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_construct (VariantMap const & params) inline override
Definition at line 94 of file script_interface/observables/LBProfileObservable.hpp.
References ScriptInterface::make_shared_from_args(), and params.
observable()
template<typename CoreLBObs > std::shared_ptr<::Observables::Observable> ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::observable () const inline override
Definition at line 116 of file script_interface/observables/LBProfileObservable.hpp.
profile_observable()
template<typename CoreLBObs > virtual std::shared_ptr<::Observables::LBProfileObservable> ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::profile_observable () const inline virtual
Definition at line 121 of file script_interface/observables/LBProfileObservable.hpp.
Referenced by ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_call_method(), and ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::LBProfileObservable().
The documentation for this class was generated from the following file:
script_interface/observables/LBProfileObservable.hpp