ESPResSo: walberla::pystencils::AdvectiveFluxKernel_double_precision Class Reference
walberla::pystencils::AdvectiveFluxKernel_double_precision Class Reference
#include <AdvectiveFluxKernel_double_precision.h>
Public Member Functions
AdvectiveFluxKernel_double_precision (BlockDataID jID_, BlockDataID rhoID_, BlockDataID uID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< AdvectiveFluxKernel_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< AdvectiveFluxKernel_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID jID
BlockDataID rhoID
BlockDataID uID
Detailed Description
Definition at line 52 of file AdvectiveFluxKernel_double_precision.h.
Constructor & Destructor Documentation
AdvectiveFluxKernel_double_precision()
walberla::pystencils::AdvectiveFluxKernel_double_precision::AdvectiveFluxKernel_double_precision (BlockDataID jID_, BlockDataID rhoID_, BlockDataID uID_) inline
Definition at line 54 of file AdvectiveFluxKernel_double_precision.h.
Member Function Documentation
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_double_precision::getSweep () inline
Definition at line 80 of file AdvectiveFluxKernel_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_double_precision::getSweep (const shared_ptr< AdvectiveFluxKernel_double_precision > & kernel) inline static
Definition at line 67 of file AdvectiveFluxKernel_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_double_precision::getSweepOnCellInterval (const shared_ptr< AdvectiveFluxKernel_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 71 of file AdvectiveFluxKernel_double_precision.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 85 of file AdvectiveFluxKernel_double_precision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::AdvectiveFluxKernel_double_precision::operator() (IBlock * block) inline
Definition at line 64 of file AdvectiveFluxKernel_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::AdvectiveFluxKernel_double_precision::run (IBlock * block)
Definition at line 1627 of file AdvectiveFluxKernel_double_precision.cpp.
References walberla::pystencils::internal_5255e1c780a944d646f270232511968b::advectivefluxkernel_double_precision_advectivefluxkernel_double_precision(), block(), jID, RESTRICT, rhoID, and uID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::AdvectiveFluxKernel_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 1658 of file AdvectiveFluxKernel_double_precision.cpp.
References walberla::pystencils::internal_5255e1c780a944d646f270232511968b::advectivefluxkernel_double_precision_advectivefluxkernel_double_precision(), block(), jID, RESTRICT, rhoID, and uID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
jID
BlockDataID walberla::pystencils::AdvectiveFluxKernel_double_precision::jID
Definition at line 93 of file AdvectiveFluxKernel_double_precision.h.
Referenced by run(), and runOnCellInterval().
rhoID
BlockDataID walberla::pystencils::AdvectiveFluxKernel_double_precision::rhoID
Definition at line 94 of file AdvectiveFluxKernel_double_precision.h.
Referenced by run(), and runOnCellInterval().
uID
BlockDataID walberla::pystencils::AdvectiveFluxKernel_double_precision::uID
Definition at line 95 of file AdvectiveFluxKernel_double_precision.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
AdvectiveFluxKernel_double_precision.h
AdvectiveFluxKernel_double_precision.cpp