ESPResSo: walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX Class Reference
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX Class Reference
#include <StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h>
Public Member Functions
StreamCollideSweepLeesEdwardsSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, float omega_bulk, float omega_even, float omega_odd, float omega_shear, float v_s)
~StreamCollideSweepLeesEdwardsSinglePrecisionAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
int64_t getLebc_bot_index () const
int64_t getLebc_top_index () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
float getV_s () const
void setLebc_bot_index (const int64_t value)
void setLebc_top_index (const int64_t value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepLeesEdwardsSinglePrecisionAVX()
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::StreamCollideSweepLeesEdwardsSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, float omega_bulk, float omega_even, float omega_odd, float omega_shear, float v_s) inline
Definition at line 55 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
~StreamCollideSweepLeesEdwardsSinglePrecisionAVX()
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::~StreamCollideSweepLeesEdwardsSinglePrecisionAVX () inline
Definition at line 64 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 106 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getLebc_bot_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getLebc_bot_index () const inline
Definition at line 109 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getLebc_top_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getLebc_top_index () const inline
Definition at line 110 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getOmega_bulk () const inline
Definition at line 111 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getOmega_even () const inline
Definition at line 112 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getOmega_odd () const inline
Definition at line 113 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getOmega_shear () const inline
Definition at line 114 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getSweep () inline
Definition at line 93 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionAVX > & kernel) inline static
Definition at line 79 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
References runOnCellInterval(), and stream.
getV_s()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::getV_s () const inline
Definition at line 115 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::run (IBlock * block)
Definition at line 542 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_c275fa5bef4a1b9f30058dc82d50d3cf::streamcollidesweepleesedwardssingleprecisionavx_streamcollidesweepleesedwardssingleprecisionavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 600 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_c275fa5bef4a1b9f30058dc82d50d3cf::streamcollidesweepleesedwardssingleprecisionavx_streamcollidesweepleesedwardssingleprecisionavx().
Referenced by getSweepOnCellInterval().
setLebc_bot_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setLebc_bot_index (const int64_t value) inline
Definition at line 116 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
setLebc_top_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setLebc_top_index (const int64_t value) inline
Definition at line 119 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setOmega_bulk (const float value) inline
Definition at line 122 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setOmega_even (const float value) inline
Definition at line 123 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setOmega_odd (const float value) inline
Definition at line 124 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setOmega_shear (const float value) inline
Definition at line 125 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
setV_s()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionAVX::setV_s (const float value) inline
Definition at line 126 of file StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepLeesEdwardsSinglePrecisionAVX.h
StreamCollideSweepLeesEdwardsSinglePrecisionAVX.cpp