ESPResSo: ScriptInterface::Interactions::InteractionTabulated Class Reference
ScriptInterface::Interactions::InteractionTabulated Class Reference
#include <NonBondedInteraction.hpp>
Public Member Functions
InteractionTabulated ()
Variant do_call_method (std::string const &name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >
void do_construct (VariantMap const &params) final
void copy_si_to_core ()
void copy_core_to_si ()
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
CoreInteraction IA_parameters::* get_ptr_offset () const override
Protected Member Functions inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >
virtual double inactive_cutoff () const
Which magic value indicates the potential is inactive.
auto make_autoparameter (T CoreInteraction::*ptr, char const *name)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Private Member Functions
std::string inactive_parameter () const override
void make_new_instance (VariantMap const &params) override
Additional Inherited Members
Public Types inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >
using CoreInteraction = ::TabulatedPotential
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >
using BaseClass = AutoParameters< InteractionPotentialInterface< ::TabulatedPotential > >
Protected Attributes inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >
std::shared_ptr< CoreInteraction > m_ia_si
Managed object.
Detailed Description
Definition at line 593 of file NonBondedInteraction.hpp.
Constructor & Destructor Documentation
InteractionTabulated()
ScriptInterface::Interactions::InteractionTabulated::InteractionTabulated () inline
Definition at line 601 of file NonBondedInteraction.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), TabulatedPotential::energy_tab, TabulatedPotential::force_tab, ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >::make_autoparameter(), TabulatedPotential::maxval, and TabulatedPotential::minval.
Member Function Documentation
do_call_method()
Variant ScriptInterface::Interactions::InteractionTabulated::do_call_method (std::string const & name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >.
Definition at line 620 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >::m_ia_si, ScriptInterface::ObjectHandle::name(), and params.
get_ptr_offset()
CoreInteraction IA_parameters::* ScriptInterface::Interactions::InteractionTabulated::get_ptr_offset () const inline override protected virtual
Implements ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >.
Definition at line 596 of file NonBondedInteraction.hpp.
References IA_parameters::tab.
inactive_parameter()
std::string ScriptInterface::Interactions::InteractionTabulated::inactive_parameter () const inline override private virtual
Reimplemented from ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >.
Definition at line 611 of file NonBondedInteraction.hpp.
make_new_instance()
void ScriptInterface::Interactions::InteractionTabulated::make_new_instance (VariantMap const & params) inline override private virtual
Implements ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >.
Definition at line 613 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface<::TabulatedPotential >::m_ia_si, ScriptInterface::make_shared_from_args(), and params.
The documentation for this class was generated from the following file:
NonBondedInteraction.hpp