ESPResSo: walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision Class Reference
walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision Class Reference
#include <DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h>
Public Member Functions
DiffusiveFluxKernelWithElectrostaticThermalized_single_precision (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, float D, float f_ext_0, float f_ext_1, float f_ext_2, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, float kT, uint32_t seed, uint32_t time_step, float z)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
float getD () const
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getF_ext_0 () const
float getF_ext_1 () const
float getF_ext_2 () const
uint32_t getField_size_0 () const
uint32_t getField_size_1 () const
uint32_t getField_size_2 () const
float getKt () const
uint32_t getSeed () const
uint32_t getTime_step () const
float getZ () const
void setD (const float value)
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setF_ext_0 (const float value)
void setF_ext_1 (const float value)
void setF_ext_2 (const float value)
void setField_size_0 (const uint32_t value)
void setField_size_1 (const uint32_t value)
void setField_size_2 (const uint32_t value)
void setKt (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
void setZ (const float value)
void setPhiID (BlockDataID phiID_)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_single_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_single_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelWithElectrostaticThermalized_single_precision()
walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, float D, float f_ext_0, float f_ext_1, float f_ext_2, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, float kT, uint32_t seed, uint32_t time_step, float z) inline
Definition at line 55 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 106 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getBlock_offset_0 () const inline
Definition at line 116 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getBlock_offset_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getBlock_offset_1 () const inline
Definition at line 117 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getBlock_offset_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getBlock_offset_2 () const inline
Definition at line 118 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getD()
float walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getD () const inline
Definition at line 115 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getF_ext_0()
float walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getF_ext_0 () const inline
Definition at line 119 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getF_ext_1()
float walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getF_ext_1 () const inline
Definition at line 120 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getF_ext_2()
float walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getF_ext_2 () const inline
Definition at line 121 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getField_size_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getField_size_0 () const inline
Definition at line 122 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getField_size_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getField_size_1 () const inline
Definition at line 123 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getField_size_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getField_size_2 () const inline
Definition at line 124 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getKt()
float walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getKt () const inline
Definition at line 125 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getSeed()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getSeed () const inline
Definition at line 126 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getSweep () inline
Definition at line 93 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_single_precision > & kernel) inline static
Definition at line 76 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostaticThermalized_single_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 82 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getTime_step () const inline
Definition at line 127 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
getZ()
float walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::getZ () const inline
Definition at line 128 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::operator() (IBlock * block) inline
Definition at line 73 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
References block(), and run().
run()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::run (IBlock * block)
Definition at line 425 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.cpp.
References block(), walberla::pystencils::internal_e04f3d5b3f93f09e4de6aba968e70d10::diffusivefluxkernelwithelectrostaticthermalized_single_precision_diffusivefluxkernelwithelectrostaticthermalized_single_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 472 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.cpp.
References block(), walberla::pystencils::internal_e04f3d5b3f93f09e4de6aba968e70d10::diffusivefluxkernelwithelectrostaticthermalized_single_precision_diffusivefluxkernelwithelectrostaticthermalized_single_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setBlock_offset_0 (const uint32_t value) inline
Definition at line 130 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setBlock_offset_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setBlock_offset_1 (const uint32_t value) inline
Definition at line 133 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setBlock_offset_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setBlock_offset_2 (const uint32_t value) inline
Definition at line 136 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setD()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setD (const float value) inline
Definition at line 129 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setF_ext_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setF_ext_0 (const float value) inline
Definition at line 139 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setF_ext_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setF_ext_1 (const float value) inline
Definition at line 140 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setF_ext_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setF_ext_2 (const float value) inline
Definition at line 141 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setField_size_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setField_size_0 (const uint32_t value) inline
Definition at line 142 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setField_size_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setField_size_1 (const uint32_t value) inline
Definition at line 143 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setField_size_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setField_size_2 (const uint32_t value) inline
Definition at line 144 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setKt()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setKt (const float value) inline
Definition at line 145 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setPhiID()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setPhiID (BlockDataID phiID_) inline
Definition at line 155 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
References stream.
setSeed()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setSeed (const uint32_t value) inline
Definition at line 146 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setTime_step()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setTime_step (const uint32_t value) inline
Definition at line 147 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
setZ()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_single_precision::setZ (const float value) inline
Definition at line 148 of file DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.h
DiffusiveFluxKernelWithElectrostaticThermalized_single_precision.cpp