ESPResSo: Observables::ForceDensityProfile Class Reference
Observables::ForceDensityProfile Class Reference
#include <ForceDensityProfile.hpp>
Public Member Functions
std::vector< std::size_t > shape () const override
std::vector< double > evaluate (ParticleReferenceRange particles, const ParticleObservables::traits< Particle > &) const override
PidProfileObservable (std::vector< int > const &ids, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
Public Member Functions inherited from Observables::PidProfileObservable
PidProfileObservable (std::vector< int > const &ids, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() () const final
const std::vector< int > & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Public Member Functions inherited from Observables::ProfileObservable
ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
std::vector< std::size_t > shape () const override
auto n_bins () const
auto limits () const
std::array< std::vector< double >, 3 > edges () const
Calculate the bin edges for each dimension.
Detailed Description
Definition at line 35 of file ForceDensityProfile.hpp.
Member Function Documentation
evaluate()
std::vector<double> Observables::ForceDensityProfile::evaluate (ParticleReferenceRange particles, const ParticleObservables::traits< Particle > &) const inline override virtual
Implements Observables::PidObservable.
Definition at line 44 of file ForceDensityProfile.hpp.
References box_geo, folded_position(), Utils::Histogram< T, N, M, U >::get_histogram(), Observables::ProfileObservable::limits(), Observables::ProfileObservable::n_bins(), Utils::Histogram< T, N, M, U >::normalize(), Cells::particles(), and Utils::Histogram< T, N, M, U >::update().
PidProfileObservable()
Observables::PidProfileObservable::PidProfileObservable inline
Definition at line 32 of file core/observables/PidProfileObservable.hpp.
shape()
std::vector<std::size_t> Observables::ForceDensityProfile::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 38 of file ForceDensityProfile.hpp.
References Observables::ProfileObservable::n_bins().
The documentation for this class was generated from the following file:
ForceDensityProfile.hpp