ESPResSo: walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX Class Reference
walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX Class Reference
#include <UpdateVelFromPDFDoublePrecisionAVX.h>
Public Member Functions
UpdateVelFromPDFDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< UpdateVelFromPDFDoublePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFDoublePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file UpdateVelFromPDFDoublePrecisionAVX.h.
Constructor & Destructor Documentation
UpdateVelFromPDFDoublePrecisionAVX()
walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::UpdateVelFromPDFDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 55 of file UpdateVelFromPDFDoublePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file UpdateVelFromPDFDoublePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::getSweep () inline
Definition at line 81 of file UpdateVelFromPDFDoublePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::getSweep (const shared_ptr< UpdateVelFromPDFDoublePrecisionAVX > & kernel) inline static
Definition at line 68 of file UpdateVelFromPDFDoublePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file UpdateVelFromPDFDoublePrecisionAVX.h.
References runOnCellInterval(), and stream.
getSweepOnCellInterval() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFDoublePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file UpdateVelFromPDFDoublePrecisionAVX.h.
References stream.
operator()()
void walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::operator() (IBlock * block) inline
Definition at line 65 of file UpdateVelFromPDFDoublePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::run (IBlock * block)
Definition at line 101 of file UpdateVelFromPDFDoublePrecisionAVX.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_fb7a198ee8d4b87d3091e088a14673a2::updatevelfrompdfdoubleprecisionavx_updatevelfrompdfdoubleprecisionavx(), and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 143 of file UpdateVelFromPDFDoublePrecisionAVX.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_fb7a198ee8d4b87d3091e088a14673a2::updatevelfrompdfdoubleprecisionavx_updatevelfrompdfdoubleprecisionavx(), and velocity().
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
UpdateVelFromPDFDoublePrecisionAVX.h
UpdateVelFromPDFDoublePrecisionAVX.cpp