ESPResSo: ScriptInterface::walberla::LatticeModel< Method, VTKHandle > Class Template Reference
ScriptInterface::walberla::LatticeModel< Method, VTKHandle > Class Template Reference abstract
#include <LatticeModel.hpp>
Public Member Functions
Variant do_call_method (std::string const &method_name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle > >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
virtual ::LatticeModel::units_map get_latice_to_md_units_conversion () const =0
auto find_vtk (std::shared_ptr< VTKHandle > const &vtk) const
auto serialize_vtk_writers () const
Protected Member Functions inherited from ScriptInterface::AutoParameters< LatticeModel< Method, VTKHandle > >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes
std::shared_ptr< LatticeWalberla > m_lattice
std::shared_ptr< Method > m_instance
std::vector< std::shared_ptr< VTKHandle > > m_vtk_writers
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
template<class Method, class VTKHandle>
class ScriptInterface::walberla::LatticeModel< Method, VTKHandle >
Definition at line 38 of file script_interface/walberla/LatticeModel.hpp.
Member Function Documentation
do_call_method()
template<class Method , class VTKHandle > Variant ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method (std::string const & method_name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 56 of file script_interface/walberla/LatticeModel.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::find_vtk(), ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::get_latice_to_md_units_conversion(), ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_instance, ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_vtk_writers, ScriptInterface::Context::parallel_try_catch(), and params.
find_vtk()
template<class Method , class VTKHandle > auto ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::find_vtk (std::shared_ptr< VTKHandle > const & vtk) const inline protected
Definition at line 47 of file script_interface/walberla/LatticeModel.hpp.
References ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_vtk_writers.
Referenced by ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method().
get_latice_to_md_units_conversion()
template<class Method , class VTKHandle > virtual ::LatticeModel::units_map ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::get_latice_to_md_units_conversion () const protected pure virtual
Implemented in ScriptInterface::walberla::LBFluid, and ScriptInterface::walberla::EKSpecies.
Referenced by ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method().
serialize_vtk_writers()
template<class Method , class VTKHandle > auto ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::serialize_vtk_writers () const inline protected
Definition at line 51 of file script_interface/walberla/LatticeModel.hpp.
References ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_vtk_writers, and ScriptInterface::make_vector_of_variants().
Member Data Documentation
m_instance
template<class Method , class VTKHandle > std::shared_ptr<Method> ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_instance protected
Definition at line 41 of file script_interface/walberla/LatticeModel.hpp.
Referenced by ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method().
m_lattice
template<class Method , class VTKHandle > std::shared_ptr<LatticeWalberla> ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_lattice protected
Definition at line 40 of file script_interface/walberla/LatticeModel.hpp.
m_vtk_writers
template<class Method , class VTKHandle > std::vector<std::shared_ptr<VTKHandle> > ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::m_vtk_writers protected
Definition at line 42 of file script_interface/walberla/LatticeModel.hpp.
Referenced by ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method(), ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::find_vtk(), and ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::serialize_vtk_writers().
The documentation for this class was generated from the following file:
script_interface/walberla/LatticeModel.hpp