ESPResSo: ScriptInterface::System::System Class Reference
ScriptInterface::System::System Class Reference
Script interface wrapper for the system class.
#include <System.hpp>
Classes
struct Leaves
Container for leaves of the system class.
Public Member Functions
System ()
~System () override=default
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &name, VariantMap const &parameters) override
auto const & get_system () const
Public Member Functions inherited from ScriptInterface::AutoParameters< System >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Private Member Functions
std::string get_internal_state () const override
Serialize particles.
void set_internal_state (std::string const &state) override
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::AutoParameters< System >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Script interface wrapper for the system class.
See System class design for more details.
Definition at line 38 of file script_interface/system/System.hpp.
Constructor & Destructor Documentation
System()
ScriptInterface::System::System::System ()
Definition at line 148 of file script_interface/system/System.cpp.
References ScriptInterface::AutoParameters< System >::add_parameters(), ScriptInterface::get_value(), and stream.
~System()
ScriptInterface::System::System::~System () override default
Member Function Documentation
do_call_method()
Variant ScriptInterface::System::System::do_call_method (std::string const & name, VariantMap const & parameters) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 446 of file script_interface/system/System.cpp.
References Utils::Vector< T, N >::broadcast(), coord(), System::get_system(), init_type_map(), ScriptInterface::make_unordered_map_of_variants(), propagation_flags_map(), ScriptInterface::System::rescale_particles(), System::reset_system(), ScriptInterface::System::rotate_system(), stream, and ScriptInterface::System::system_created.
do_construct()
void ScriptInterface::System::System::do_construct (VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 287 of file script_interface/system/System.cpp.
References System::System::create(), NSQUARE, REGULAR, System::set_system(), stream, and ScriptInterface::System::system_created.
get_internal_state()
std::string ScriptInterface::System::System::get_internal_state () const override private virtual
Serialize particles.
Particles need to be serialized here to reduce overhead, and also to guarantee particles get instantiated after the cell structure was instantiated (since they store a weak pointer to it).
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 550 of file script_interface/system/System.cpp.
References get_particle_ids(), ScriptInterface::pack(), Utils::pack(), ScriptInterface::ObjectHandle::serialize(), and stream.
get_system()
auto const & ScriptInterface::System::System::get_system () const inline
Definition at line 51 of file script_interface/system/System.hpp.
set_internal_state()
void ScriptInterface::System::System::set_internal_state (std::string const & state) override private virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 576 of file script_interface/system/System.cpp.
References get_particle_ids(), ScriptInterface::System::set_bonds(), ScriptInterface::System::set_exclusions(), stream, and ScriptInterface::unpack().
The documentation for this class was generated from the following files:
script_interface/system/System.hpp
script_interface/system/System.cpp