ESPResSo: walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA Class Reference
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA Class Reference
#include <StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h>
Public Member Functions
StreamCollideSweepLeesEdwardsSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, float omega_bulk, float omega_even, float omega_odd, float omega_shear, float v_s)
~StreamCollideSweepLeesEdwardsSinglePrecisionCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
int64_t getLebc_bot_index () const
int64_t getLebc_top_index () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
float getV_s () const
void setLebc_bot_index (const int64_t value)
void setLebc_top_index (const int64_t value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepLeesEdwardsSinglePrecisionCUDA()
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, int64_t lebc_bot_index, int64_t lebc_top_index, float omega_bulk, float omega_even, float omega_odd, float omega_shear, float v_s) inline
Definition at line 57 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
~StreamCollideSweepLeesEdwardsSinglePrecisionCUDA()
walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::~StreamCollideSweepLeesEdwardsSinglePrecisionCUDA () inline
Definition at line 66 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 116 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getLebc_bot_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getLebc_bot_index () const inline
Definition at line 119 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getLebc_top_index()
int64_t walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getLebc_top_index () const inline
Definition at line 120 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getOmega_bulk () const inline
Definition at line 121 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getOmega_even () const inline
Definition at line 122 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getOmega_odd () const inline
Definition at line 123 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getOmega_shear () const inline
Definition at line 124 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getSweep (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionCUDA > & kernel) inline static
Definition at line 84 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 101 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepLeesEdwardsSinglePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 89 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 106 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
References runOnCellInterval(), and stream.
getV_s()
float walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::getV_s () const inline
Definition at line 125 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 79 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 298 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 355 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setLebc_bot_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setLebc_bot_index (const int64_t value) inline
Definition at line 126 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
setLebc_top_index()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setLebc_top_index (const int64_t value) inline
Definition at line 129 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setOmega_bulk (const float value) inline
Definition at line 132 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setOmega_even (const float value) inline
Definition at line 133 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setOmega_odd (const float value) inline
Definition at line 134 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setOmega_shear (const float value) inline
Definition at line 135 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
setV_s()
void walberla::pystencils::StreamCollideSweepLeesEdwardsSinglePrecisionCUDA::setV_s (const float value) inline
Definition at line 136 of file StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.h
StreamCollideSweepLeesEdwardsSinglePrecisionCUDA.cu