ESPResSo: walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards Class Reference
walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards Class Reference
#include <CollideSweepSinglePrecisionLeesEdwards.h>
Public Member Functions
CollideSweepSinglePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getGrid_size () const
float getOmega_shear () const
float getV_s () const
void setGrid_size (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepSinglePrecisionLeesEdwards > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionLeesEdwards > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepSinglePrecisionLeesEdwards.h.
Constructor & Destructor Documentation
CollideSweepSinglePrecisionLeesEdwards()
walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::CollideSweepSinglePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s) inline
Definition at line 57 of file CollideSweepSinglePrecisionLeesEdwards.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 98 of file CollideSweepSinglePrecisionLeesEdwards.h.
getGrid_size()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getGrid_size () const inline
Definition at line 101 of file CollideSweepSinglePrecisionLeesEdwards.h.
getOmega_shear()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getOmega_shear () const inline
Definition at line 102 of file CollideSweepSinglePrecisionLeesEdwards.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getSweep () inline
Definition at line 85 of file CollideSweepSinglePrecisionLeesEdwards.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getSweep (const shared_ptr< CollideSweepSinglePrecisionLeesEdwards > & kernel) inline static
Definition at line 72 of file CollideSweepSinglePrecisionLeesEdwards.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionLeesEdwards > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 76 of file CollideSweepSinglePrecisionLeesEdwards.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 90 of file CollideSweepSinglePrecisionLeesEdwards.h.
References runOnCellInterval().
getV_s()
float walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::getV_s () const inline
Definition at line 103 of file CollideSweepSinglePrecisionLeesEdwards.h.
operator()()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::operator() (IBlock * block) inline
Definition at line 69 of file CollideSweepSinglePrecisionLeesEdwards.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::run (IBlock * block)
Definition at line 158 of file CollideSweepSinglePrecisionLeesEdwards.cpp.
References block(), walberla::pystencils::internal_ab1f3bc3368574afb482da84ccb58898::collidesweepsingleprecisionleesedwards_collidesweepsingleprecisionleesedwards(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 192 of file CollideSweepSinglePrecisionLeesEdwards.cpp.
References block(), walberla::pystencils::internal_ab1f3bc3368574afb482da84ccb58898::collidesweepsingleprecisionleesedwards_collidesweepsingleprecisionleesedwards(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::setGrid_size (const float value) inline
Definition at line 104 of file CollideSweepSinglePrecisionLeesEdwards.h.
setOmega_shear()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::setOmega_shear (const float value) inline
Definition at line 105 of file CollideSweepSinglePrecisionLeesEdwards.h.
setV_s()
void walberla::pystencils::CollideSweepSinglePrecisionLeesEdwards::setV_s (const float value) inline
Definition at line 106 of file CollideSweepSinglePrecisionLeesEdwards.h.
The documentation for this class was generated from the following files:
CollideSweepSinglePrecisionLeesEdwards.h
CollideSweepSinglePrecisionLeesEdwards.cpp