ESPResSo: System::Leaf< Class > Class Template Reference
System::Leaf< Class > Class Template Reference
Abstract class that represents a component of the system.
#include <Leaf.hpp>
Public Member Functions
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Protected Member Functions
auto & get_system ()
auto & get_system () const
Protected Attributes
std::weak_ptr< System > m_system
Detailed Description
template<typename Class>
class System::Leaf< Class >
Abstract class that represents a component of the system.
See System class design for more details.
Definition at line 34 of file core/system/Leaf.hpp.
Member Function Documentation
bind_system()
template<typename Class > void System::Leaf< Class >::bind_system (std::shared_ptr< System > const & system) inline
Definition at line 51 of file core/system/Leaf.hpp.
References System::Leaf< Class >::m_system.
detach_system()
template<typename Class > void System::Leaf< Class >::detach_system (std::shared_ptr< System > const & system) inline
Definition at line 57 of file core/system/Leaf.hpp.
References System::Leaf< Class >::m_system.
get_system() [1/2]
template<typename Class > auto& System::Leaf< Class >::get_system () inline protected
Definition at line 38 of file core/system/Leaf.hpp.
References System::Leaf< Class >::m_system.
Referenced by DipolarLayerCorrection::add_force_corrections(), CoulombMMM1DGpu::add_long_range_energy(), CoulombMMM1DGpu::add_long_range_forces(), DipolarBarnesHutGpu::add_long_range_forces(), DipolarDirectSumGpu::add_long_range_forces(), CoulombP3MGPU::add_long_range_forces(), ElectrostaticLayerCorrection::add_long_range_forces(), DipolarDirectSum::add_long_range_forces(), CoulombP3M::count_charged_particles(), DipolarP3M::count_magnetic_particles(), DipolarDirectSum::dipole_field_at_part(), DipolarLayerCorrection::energy_correction(), CoulombP3M::init(), CoulombP3MGPU::init(), DipolarP3M::init(), DipolarBarnesHutGpu::long_range_energy(), DipolarDirectSumGpu::long_range_energy(), ElectrostaticLayerCorrection::long_range_energy(), DipolarDirectSum::long_range_energy(), CoulombP3M::long_range_kernel(), DipolarP3M::long_range_kernel(), CoulombP3M::long_range_pressure(), DipolarBarnesHutGpu::on_activation(), DipolarDirectSumGpu::on_activation(), CoulombMMM1D::pair_energy(), CoulombMMM1D::pair_force(), DipolarLayerCorrection::recalc_box_h(), CoulombP3MGPU::request_gpu(), CoulombMMM1D::tune(), CoulombMMM1DGpu::tune(), CoulombP3M::tune(), DipolarP3M::tune(), CoulombScafacosImpl::update_particle_data(), DipolarScafacosImpl::update_particle_data(), CoulombScafacosImpl::update_particle_forces(), and DipolarScafacosImpl::update_particle_forces().
get_system() [2/2]
template<typename Class > auto& System::Leaf< Class >::get_system () const inline protected
Definition at line 44 of file core/system/Leaf.hpp.
References System::Leaf< Class >::m_system.
Member Data Documentation
m_system
template<typename Class > std::weak_ptr<System> System::Leaf< Class >::m_system protected
Definition at line 36 of file core/system/Leaf.hpp.
Referenced by System::Leaf< Class >::bind_system(), CoulombTuningAlgorithm::calculate_accuracy(), System::Leaf< Class >::detach_system(), CoulombTuningAlgorithm::determine_mesh_limits(), System::Leaf< Class >::get_system(), CoulombTuningAlgorithm::get_time(), CoulombTuningAlgorithm::layer_correction_veto_r_cut(), ElectrostaticLayerCorrection::on_activation(), DipolarLayerCorrection::on_activation(), CoulombTuningAlgorithm::on_solver_change(), and CoulombTuningAlgorithm::setup_logger().
The documentation for this class was generated from the following file:
core/system/Leaf.hpp