ESPResSo: walberla::lbm::DynamicUBBDoublePrecision::ForceVector Class Reference
walberla::lbm::DynamicUBBDoublePrecision::ForceVector Class Reference
#include <DynamicUBBDoublePrecision.h>
Public Member Functions
ForceVector ()=default
bool operator== (ForceVector const &other) const
auto & forceVector ()
auto const & forceVector () const
ForceStruct * pointerCpu ()
bool empty () const
Vector3< double > getForce ()
void syncGPU ()
void syncCPU ()
Detailed Description
Definition at line 127 of file DynamicUBBDoublePrecision.h.
Constructor & Destructor Documentation
ForceVector()
walberla::lbm::DynamicUBBDoublePrecision::ForceVector::ForceVector () default
Member Function Documentation
empty()
bool walberla::lbm::DynamicUBBDoublePrecision::ForceVector::empty () const inline
Definition at line 139 of file DynamicUBBDoublePrecision.h.
forceVector() [1/2]
auto & walberla::lbm::DynamicUBBDoublePrecision::ForceVector::forceVector () inline
Definition at line 134 of file DynamicUBBDoublePrecision.h.
Referenced by walberla::lbm::DynamicUBBDoublePrecision::getForceVector().
forceVector() [2/2]
auto const & walberla::lbm::DynamicUBBDoublePrecision::ForceVector::forceVector () const inline
Definition at line 135 of file DynamicUBBDoublePrecision.h.
getForce()
Vector3< double > walberla::lbm::DynamicUBBDoublePrecision::ForceVector::getForce () inline
Definition at line 141 of file DynamicUBBDoublePrecision.h.
References stream, and syncCPU().
Referenced by walberla::lbm::DynamicUBBDoublePrecision::getForce().
operator==()
bool walberla::lbm::DynamicUBBDoublePrecision::ForceVector::operator== (ForceVector const & other) const inline
Definition at line 130 of file DynamicUBBDoublePrecision.h.
References stream.
pointerCpu()
ForceStruct * walberla::lbm::DynamicUBBDoublePrecision::ForceVector::pointerCpu () inline
Definition at line 136 of file DynamicUBBDoublePrecision.h.
References stream.
syncCPU()
void walberla::lbm::DynamicUBBDoublePrecision::ForceVector::syncCPU () inline
Definition at line 154 of file DynamicUBBDoublePrecision.h.
Referenced by getForce().
syncGPU()
void walberla::lbm::DynamicUBBDoublePrecision::ForceVector::syncGPU () inline
Definition at line 152 of file DynamicUBBDoublePrecision.h.
The documentation for this class was generated from the following file:
DynamicUBBDoublePrecision.h