ESPResSo: walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX Class Reference
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX Class Reference
#include <StreamCollideSweepDoublePrecisionThermalizedAVX.h>
Public Member Functions
StreamCollideSweepDoublePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepDoublePrecisionThermalizedAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepDoublePrecisionThermalizedAVX()
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::StreamCollideSweepDoublePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
~StreamCollideSweepDoublePrecisionThermalizedAVX()
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::~StreamCollideSweepDoublePrecisionThermalizedAVX () inline
Definition at line 67 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 109 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getBlock_offset_0 () const inline
Definition at line 118 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getBlock_offset_1 () const inline
Definition at line 119 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getBlock_offset_2 () const inline
Definition at line 120 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getKt()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getKt () const inline
Definition at line 121 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getOmega_bulk () const inline
Definition at line 122 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getOmega_even () const inline
Definition at line 123 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getOmega_odd () const inline
Definition at line 124 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getOmega_shear () const inline
Definition at line 125 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getSeed () const inline
Definition at line 126 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getSweep () inline
Definition at line 96 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedAVX > & kernel) inline static
Definition at line 82 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 87 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 101 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
References runOnCellInterval().
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::getTime_step () const inline
Definition at line 127 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::operator() (IBlock * block) inline
Definition at line 79 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::run (IBlock * block)
Definition at line 773 of file StreamCollideSweepDoublePrecisionThermalizedAVX.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_a31ab38610ae1a06ea4ee5b937860957::streamcollidesweepdoubleprecisionthermalizedavx_streamcollidesweepdoubleprecisionthermalizedavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 836 of file StreamCollideSweepDoublePrecisionThermalizedAVX.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_a31ab38610ae1a06ea4ee5b937860957::streamcollidesweepdoubleprecisionthermalizedavx_streamcollidesweepdoubleprecisionthermalizedavx().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setBlock_offset_0 (const uint32_t value) inline
Definition at line 128 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setBlock_offset_1 (const uint32_t value) inline
Definition at line 131 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setBlock_offset_2 (const uint32_t value) inline
Definition at line 134 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setKt()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setKt (const double value) inline
Definition at line 137 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setOmega_bulk (const double value) inline
Definition at line 138 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setOmega_even (const double value) inline
Definition at line 139 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setOmega_odd (const double value) inline
Definition at line 140 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setOmega_shear (const double value) inline
Definition at line 141 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setSeed()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setSeed (const uint32_t value) inline
Definition at line 142 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedAVX::setTime_step (const uint32_t value) inline
Definition at line 143 of file StreamCollideSweepDoublePrecisionThermalizedAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepDoublePrecisionThermalizedAVX.h
StreamCollideSweepDoublePrecisionThermalizedAVX.cpp