ESPResSo: LatticeModel Class Reference
LatticeModel Class Reference abstract
Abstract representation of a lattice-based model.
#include <LatticeModel.hpp>
Public Types
using units_map = std::unordered_map< std::string, double >
Public Member Functions
virtual ~LatticeModel ()=default
virtual LatticeWalberla const & get_lattice () const noexcept=0
Get the underlying lattice.
std::shared_ptr< VTKHandle > create_vtk (int delta_N, int initial_count, int flag_observables, units_map const &units_conversion, std::string const &identifier, std::string const &base_folder, std::string const &prefix, bool force_pvtu)
Create a VTK observable.
void write_vtk (std::string const &vtk_uid)
Write a VTK observable to disk.
void switch_vtk (std::string const &vtk_uid, bool status)
Toggle a VTK observable on/off.
Protected Member Functions
virtual void register_vtk_field_writers (walberla::vtk::VTKOutput &vtk_obj, units_map const &units_conversion, int flag_observables)=0
Register VTK writers.
virtual void register_vtk_field_filters (walberla::vtk::VTKOutput &vtk_obj)=0
virtual void integrate_vtk_writers ()=0
Protected Attributes
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_auto
VTK writers that are executed automatically.
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_manual
VTK writers that are executed manually.
Detailed Description
Abstract representation of a lattice-based model.
Definition at line 31 of file walberla_bridge/include/walberla_bridge/LatticeModel.hpp.
Member Typedef Documentation
units_map
using LatticeModel::units_map = std::unordered_map<std::string, double>
Definition at line 33 of file walberla_bridge/include/walberla_bridge/LatticeModel.hpp.
Constructor & Destructor Documentation
~LatticeModel()
virtual LatticeModel::~LatticeModel () virtual default
Member Function Documentation
create_vtk()
std::shared_ptr< VTKHandle > LatticeModel::create_vtk (int delta_N, int initial_count, int flag_observables, units_map const & units_conversion, std::string const & identifier, std::string const & base_folder, std::string const & prefix, bool force_pvtu)
Create a VTK observable.
Parameters
delta_N Write frequency, if 0 write a single frame, otherwise add a callback to write every delta_N EK steps to a new file
initial_count Initial execution count
flag_observables Which observables to measure (OR'ing of OutputVTK or EKOutputVTK values)
units_conversion Lattice-to-MD units conversion
identifier Name of the VTK dataset
base_folder Path to the VTK folder
prefix Prefix of the VTK files
force_pvtu Force parallel unstructured grid format
Definition at line 31 of file LatticeModel.cpp.
References LatticeWalberla::get_blocks(), get_lattice(), m_vtk_auto, m_vtk_manual, register_vtk_field_filters(), register_vtk_field_writers(), and stream.
get_lattice()
virtual LatticeWalberla const & LatticeModel::get_lattice () const pure virtual noexcept
Get the underlying lattice.
Implemented in walberla::PoissonSolver, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >, and walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by create_vtk().
integrate_vtk_writers()
virtual void LatticeModel::integrate_vtk_writers () protected pure virtual
Implemented in walberla::PoissonSolver, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >, walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::LBWalberlaImpl< FloatType, Architecture >.
register_vtk_field_filters()
virtual void LatticeModel::register_vtk_field_filters (walberla::vtk::VTKOutput & vtk_obj) protected pure virtual
Implemented in walberla::PoissonSolver, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >, and walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by create_vtk().
register_vtk_field_writers()
virtual void LatticeModel::register_vtk_field_writers (walberla::vtk::VTKOutput & vtk_obj, units_map const & units_conversion, int flag_observables) protected pure virtual
Register VTK writers.
Use the multi-piece uniform grid format.
Implemented in walberla::PoissonSolver, walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >, walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by create_vtk().
switch_vtk()
void LatticeModel::switch_vtk (std::string const & vtk_uid, bool status)
Toggle a VTK observable on/off.
Parameters
vtk_uid Name of the VTK object
status true to switch on, false to switch off
Definition at line 79 of file LatticeModel.cpp.
References m_vtk_auto, m_vtk_manual, and stream.
write_vtk()
void LatticeModel::write_vtk (std::string const & vtk_uid)
Write a VTK observable to disk.
Parameters
vtk_uid Name of the VTK object
Definition at line 67 of file LatticeModel.cpp.
References m_vtk_auto, m_vtk_manual, and stream.
Member Data Documentation
m_vtk_auto
std::map<std::string, std::shared_ptr<VTKHandle> > LatticeModel::m_vtk_auto protected
VTK writers that are executed automatically.
Definition at line 37 of file walberla_bridge/include/walberla_bridge/LatticeModel.hpp.
Referenced by create_vtk(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::integrate_vtk_writers(), walberla::PoissonSolverFFT< FloatType, Architecture >::integrate_vtk_writers(), walberla::LBWalberlaImpl< FloatType, Architecture >::integrate_vtk_writers(), switch_vtk(), and write_vtk().
m_vtk_manual
std::map<std::string, std::shared_ptr<VTKHandle> > LatticeModel::m_vtk_manual protected
VTK writers that are executed manually.
Definition at line 39 of file walberla_bridge/include/walberla_bridge/LatticeModel.hpp.
Referenced by create_vtk(), switch_vtk(), and write_vtk().
The documentation for this class was generated from the following files:
walberla_bridge/include/walberla_bridge/LatticeModel.hpp
LatticeModel.cpp