ESPResSo: ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType > Class Template Reference
ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType > Class Template Reference abstract
Owning map of object handles.
#include <ObjectMap.hpp>
Public Types
using Base = ObjectContainer< ObjectMap, ManagedType, BaseType >
using key_type = KeyType
using mapped_type = std::shared_ptr< ManagedType >
using container_type = std::unordered_map< key_type, mapped_type >
Public Member Functions
ObjectMap ()
~ObjectMap () override
void do_construct (VariantMap const &params) override=0
void insert (key_type const &key, mapped_type const &element)
Add an element to the map.
key_type insert (mapped_type const &element)
Add an element to the map.
void erase (key_type const &key)
Removes all occurrences of an element from the map.
auto const & elements () const
Map elements.
void clear ()
Clear the map.
Protected Member Functions
void do_destruct ()
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
void restore_from_checkpoint (VariantMap const &params)
key_type get_key (Variant const &key) const
Private Member Functions
virtual key_type insert_in_core (mapped_type const &obj_ptr)=0
virtual void insert_in_core (key_type const &key, mapped_type const &obj_ptr)=0
virtual void erase_in_core (key_type const &key)=0
Detailed Description
template<typename ManagedType, class BaseType = ObjectHandle, class KeyType = int>
class ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >
Owning map of object handles.
Mapped elements are cleared from the core during destruction. Due to how dynamic dispatch works, derived types must mark erase_in_core as final` and call do_destruct in their virtual destructor. This is to ensure that pure virtual functions called by clear cannot be executed in a type derived from the type currently being destructed, since derived types no longer exist at this point of the destruction sequence.
Template Parameters
ManagedType Type of the managed objects, needs to be derived from ObjectHandle
Definition at line 53 of file ObjectMap.hpp.
Member Typedef Documentation
Base
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> using ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::Base = ObjectContainer<ObjectMap, ManagedType, BaseType>
Definition at line 55 of file ObjectMap.hpp.
container_type
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> using ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::container_type = std::unordered_map<key_type, mapped_type>
Definition at line 59 of file ObjectMap.hpp.
key_type
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> using ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::key_type = KeyType
Definition at line 57 of file ObjectMap.hpp.
mapped_type
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> using ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::mapped_type = std::shared_ptr<ManagedType>
Definition at line 58 of file ObjectMap.hpp.
Constructor & Destructor Documentation
ObjectMap()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::ObjectMap () inline
Definition at line 78 of file ObjectMap.hpp.
References ScriptInterface::make_unordered_map_of_variants(), and ScriptInterface::AutoParameter::read_only.
~ObjectMap()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::~ObjectMap () inline override
Definition at line 85 of file ObjectMap.hpp.
References stream.
Member Function Documentation
clear()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::clear () inline
Clear the map.
Definition at line 131 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase_in_core(), and stream.
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method(), and ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_destruct().
do_call_method()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> Variant ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method (std::string const & method, VariantMap const & parameters) inline override protected
Definition at line 140 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::clear(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::get_key(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert(), ScriptInterface::make_unordered_map_of_variants(), ScriptInterface::none, and stream.
Referenced by ScriptInterface::BondBreakage::BreakageSpecs::do_call_method(), and ScriptInterface::Interactions::BondedInteractions::do_call_method().
do_construct()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_construct (VariantMap const & params) override pure virtual
Implemented in ScriptInterface::BondBreakage::BreakageSpecs, and ScriptInterface::Interactions::BondedInteractions.
do_destruct()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_destruct () inline protected
Definition at line 71 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::clear(), and stream.
Referenced by ScriptInterface::Interactions::BondedInteractions::~BondedInteractions(), and ScriptInterface::BondBreakage::BreakageSpecs::~BreakageSpecs().
elements()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> auto const & ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::elements () const inline
Map elements.
Definition at line 126 of file ObjectMap.hpp.
Referenced by ScriptInterface::Interactions::BondedInteractions::do_call_method().
erase()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase (key_type const & key) inline
Removes all occurrences of an element from the map.
Parameters
key Identifier of the element to remove.
Definition at line 118 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase_in_core(), and stream.
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method().
erase_in_core()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> virtual void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase_in_core (key_type const & key) private pure virtual
Implemented in ScriptInterface::BondBreakage::BreakageSpecs, and ScriptInterface::Interactions::BondedInteractions.
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::clear(), and ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase().
get_key()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> key_type ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::get_key (Variant const & key) const inline protected
Definition at line 202 of file ObjectMap.hpp.
References stream.
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method(), and ScriptInterface::Interactions::BondedInteractions::do_call_method().
insert() [1/2]
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert (key_type const & key, mapped_type const & element) inline
Add an element to the map.
Parameters
key Identifier of the element to add.
element The element to add.
Definition at line 96 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert_in_core(), and stream.
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method().
insert() [2/2]
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> key_type ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert (mapped_type const & element) inline
Add an element to the map.
A free key is generated automatically.
Parameters
element The element to add.
Definition at line 107 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert_in_core(), and stream.
insert_in_core() [1/2]
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> virtual void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert_in_core (key_type const & key, mapped_type const & obj_ptr) private pure virtual
Implemented in ScriptInterface::BondBreakage::BreakageSpecs, and ScriptInterface::Interactions::BondedInteractions.
insert_in_core() [2/2]
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> virtual key_type ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert_in_core (mapped_type const & obj_ptr) private pure virtual
Implemented in ScriptInterface::BondBreakage::BreakageSpecs, and ScriptInterface::Interactions::BondedInteractions.
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert(), and ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::restore_from_checkpoint().
restore_from_checkpoint()
template<typename ManagedType , class BaseType = ObjectHandle, class KeyType = int> void ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::restore_from_checkpoint (VariantMap const & params) inline protected
Definition at line 195 of file ObjectMap.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert_in_core(), and stream.
Referenced by ScriptInterface::BondBreakage::BreakageSpecs::do_construct(), and ScriptInterface::Interactions::BondedInteractions::on_bind_system().
The documentation for this class was generated from the following file:
ObjectMap.hpp