ESPResSo: walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX Class Reference
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX Class Reference
#include <StreamCollideSweepSinglePrecisionThermalizedAVX.h>
Public Member Functions
StreamCollideSweepSinglePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepSinglePrecisionThermalizedAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
Constructor & Destructor Documentation
StreamCollideSweepSinglePrecisionThermalizedAVX()
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::StreamCollideSweepSinglePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
~StreamCollideSweepSinglePrecisionThermalizedAVX()
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::~StreamCollideSweepSinglePrecisionThermalizedAVX () inline
Definition at line 67 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 109 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getBlock_offset_0 () const inline
Definition at line 118 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getBlock_offset_1 () const inline
Definition at line 119 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getBlock_offset_2 () const inline
Definition at line 120 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getKt()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getKt () const inline
Definition at line 121 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getOmega_bulk () const inline
Definition at line 122 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getOmega_even () const inline
Definition at line 123 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getOmega_odd () const inline
Definition at line 124 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getOmega_shear () const inline
Definition at line 125 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getSeed () const inline
Definition at line 126 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getSweep () inline
Definition at line 96 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedAVX > & kernel) inline static
Definition at line 82 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 87 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 101 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::getTime_step () const inline
Definition at line 127 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
operator()()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::operator() (IBlock * block) inline
Definition at line 79 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::run (IBlock * block)
Definition at line 741 of file StreamCollideSweepSinglePrecisionThermalizedAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_0ae93c82e35401d8a507fa8135e45553::streamcollidesweepsingleprecisionthermalizedavx_streamcollidesweepsingleprecisionthermalizedavx().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 804 of file StreamCollideSweepSinglePrecisionThermalizedAVX.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_0ae93c82e35401d8a507fa8135e45553::streamcollidesweepsingleprecisionthermalizedavx_streamcollidesweepsingleprecisionthermalizedavx().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setBlock_offset_0 (const uint32_t value) inline
Definition at line 128 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setBlock_offset_1 (const uint32_t value) inline
Definition at line 131 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setBlock_offset_2 (const uint32_t value) inline
Definition at line 134 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setKt()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setKt (const float value) inline
Definition at line 137 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setOmega_bulk (const float value) inline
Definition at line 138 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setOmega_even (const float value) inline
Definition at line 139 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setOmega_odd (const float value) inline
Definition at line 140 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setOmega_shear (const float value) inline
Definition at line 141 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setSeed()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setSeed (const uint32_t value) inline
Definition at line 142 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedAVX::setTime_step (const uint32_t value) inline
Definition at line 143 of file StreamCollideSweepSinglePrecisionThermalizedAVX.h.
The documentation for this class was generated from the following files:
StreamCollideSweepSinglePrecisionThermalizedAVX.h
StreamCollideSweepSinglePrecisionThermalizedAVX.cpp