ESPResSo: walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards Class Reference
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards Class Reference
#include <StreamCollideSweepSinglePrecisionLeesEdwards.h>
Public Member Functions
StreamCollideSweepSinglePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s)
~StreamCollideSweepSinglePrecisionLeesEdwards ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getGrid_size () const
float getOmega_shear () const
float getV_s () const
void setGrid_size (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwards > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwards > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
Constructor & Destructor Documentation
StreamCollideSweepSinglePrecisionLeesEdwards()
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::StreamCollideSweepSinglePrecisionLeesEdwards (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s) inline
Definition at line 57 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
~StreamCollideSweepSinglePrecisionLeesEdwards()
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::~StreamCollideSweepSinglePrecisionLeesEdwards () inline
Definition at line 64 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 105 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
getGrid_size()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getGrid_size () const inline
Definition at line 108 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getOmega_shear () const inline
Definition at line 109 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getSweep () inline
Definition at line 92 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwards > & kernel) inline static
Definition at line 78 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwards > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 83 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 97 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
References runOnCellInterval().
getV_s()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::getV_s () const inline
Definition at line 110 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
operator()()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::operator() (IBlock * block) inline
Definition at line 76 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::run (IBlock * block)
Definition at line 123 of file StreamCollideSweepSinglePrecisionLeesEdwards.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_67387e935f542c9d7b79fabcbf6b2506::streamcollidesweepsingleprecisionleesedwards_streamcollidesweepsingleprecisionleesedwards().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 174 of file StreamCollideSweepSinglePrecisionLeesEdwards.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_67387e935f542c9d7b79fabcbf6b2506::streamcollidesweepsingleprecisionleesedwards_streamcollidesweepsingleprecisionleesedwards().
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::setGrid_size (const float value) inline
Definition at line 111 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::setOmega_shear (const float value) inline
Definition at line 112 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
setV_s()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwards::setV_s (const float value) inline
Definition at line 113 of file StreamCollideSweepSinglePrecisionLeesEdwards.h.
The documentation for this class was generated from the following files:
StreamCollideSweepSinglePrecisionLeesEdwards.h
StreamCollideSweepSinglePrecisionLeesEdwards.cpp