ESPResSo: walberla::pystencils::StreamSweepDoublePrecisionAVX Class Reference
walberla::pystencils::StreamSweepDoublePrecisionAVX Class Reference
#include <StreamSweepDoublePrecisionAVX.h>
Public Member Functions
StreamSweepDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
~StreamSweepDoublePrecisionAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamSweepDoublePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamSweepDoublePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID forceID
BlockDataID pdfsID
BlockDataID velocityID
Detailed Description
Definition at line 53 of file StreamSweepDoublePrecisionAVX.h.
Constructor & Destructor Documentation
StreamSweepDoublePrecisionAVX()
walberla::pystencils::StreamSweepDoublePrecisionAVX::StreamSweepDoublePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 55 of file StreamSweepDoublePrecisionAVX.h.
~StreamSweepDoublePrecisionAVX()
walberla::pystencils::StreamSweepDoublePrecisionAVX::~StreamSweepDoublePrecisionAVX () inline
Definition at line 59 of file StreamSweepDoublePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamSweepDoublePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 100 of file StreamSweepDoublePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionAVX::getSweep () inline
Definition at line 87 of file StreamSweepDoublePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionAVX::getSweep (const shared_ptr< StreamSweepDoublePrecisionAVX > & kernel) inline static
Definition at line 74 of file StreamSweepDoublePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StreamSweepDoublePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 78 of file StreamSweepDoublePrecisionAVX.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 92 of file StreamSweepDoublePrecisionAVX.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::StreamSweepDoublePrecisionAVX::operator() (IBlock * block) inline
Definition at line 71 of file StreamSweepDoublePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamSweepDoublePrecisionAVX::run (IBlock * block)
Definition at line 167 of file StreamSweepDoublePrecisionAVX.cpp.
References block(), forceID, pdfsID, RESTRICT, walberla::pystencils::internal_91e2c9bdb4c4fa8a405803890749bf98::streamsweepdoubleprecisionavx_streamsweepdoubleprecisionavx(), velocity(), and velocityID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamSweepDoublePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 228 of file StreamSweepDoublePrecisionAVX.cpp.
References block(), forceID, pdfsID, RESTRICT, walberla::pystencils::internal_91e2c9bdb4c4fa8a405803890749bf98::streamsweepdoubleprecisionavx_streamsweepdoubleprecisionavx(), velocity(), and velocityID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
forceID
BlockDataID walberla::pystencils::StreamSweepDoublePrecisionAVX::forceID
Definition at line 103 of file StreamSweepDoublePrecisionAVX.h.
Referenced by run(), and runOnCellInterval().
pdfsID
BlockDataID walberla::pystencils::StreamSweepDoublePrecisionAVX::pdfsID
Definition at line 104 of file StreamSweepDoublePrecisionAVX.h.
Referenced by run(), and runOnCellInterval().
velocityID
BlockDataID walberla::pystencils::StreamSweepDoublePrecisionAVX::velocityID
Definition at line 105 of file StreamSweepDoublePrecisionAVX.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
StreamSweepDoublePrecisionAVX.h
StreamSweepDoublePrecisionAVX.cpp