ESPResSo: walberla::pystencils::PackInfoVecSinglePrecisionCUDA Class Reference
walberla::pystencils::PackInfoVecSinglePrecisionCUDA Class Reference
#include <PackInfoVecSinglePrecisionCUDA.h>
Public Member Functions
PackInfoVecSinglePrecisionCUDA (BlockDataID fieldID_)
~PackInfoVecSinglePrecisionCUDA () override=default
void pack (stencil::Direction dir, unsigned char *buffer, IBlock *block, gpuStream_t stream) override
void communicateLocal (stencil::Direction, const IBlock *, IBlock *, gpuStream_t) override
void unpack (stencil::Direction dir, unsigned char *buffer, IBlock *block, gpuStream_t stream) override
uint_t size (stencil::Direction dir, IBlock *block) override
Detailed Description
Definition at line 39 of file PackInfoVecSinglePrecisionCUDA.h.
Constructor & Destructor Documentation
PackInfoVecSinglePrecisionCUDA()
walberla::pystencils::PackInfoVecSinglePrecisionCUDA::PackInfoVecSinglePrecisionCUDA (BlockDataID fieldID_) inline
Definition at line 42 of file PackInfoVecSinglePrecisionCUDA.h.
~PackInfoVecSinglePrecisionCUDA()
walberla::pystencils::PackInfoVecSinglePrecisionCUDA::~PackInfoVecSinglePrecisionCUDA () override default
Member Function Documentation
communicateLocal()
void walberla::pystencils::PackInfoVecSinglePrecisionCUDA::communicateLocal (stencil::Direction , const IBlock * , IBlock * , gpuStream_t) inline override
Definition at line 47 of file PackInfoVecSinglePrecisionCUDA.h.
References stream.
pack()
void walberla::pystencils::PackInfoVecSinglePrecisionCUDA::pack (stencil::Direction dir, unsigned char * buffer, IBlock * block, gpuStream_t stream) override
Definition at line 103 of file PackInfoVecSinglePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
size()
uint_t walberla::pystencils::PackInfoVecSinglePrecisionCUDA::size (stencil::Direction dir, IBlock * block) override
Definition at line 212 of file PackInfoVecSinglePrecisionCUDA.cu.
References block(), and stream.
unpack()
void walberla::pystencils::PackInfoVecSinglePrecisionCUDA::unpack (stencil::Direction dir, unsigned char * buffer, IBlock * block, gpuStream_t stream) override
Definition at line 157 of file PackInfoVecSinglePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
The documentation for this class was generated from the following files:
PackInfoVecSinglePrecisionCUDA.h
PackInfoVecSinglePrecisionCUDA.cu