ESPResSo: Observable_stat Class Reference
Observable_stat Class Reference
Observable for the pressure and energy.
#include <Observable_stat.hpp>
Public Member Functions
Observable_stat (std::size_t chunk_size, std::size_t n_bonded, int max_type)
auto get_chunk_size () const
double accumulate (double acc=0.0, std::size_t column=0) const
Accumulate values.
void rescale (double volume)
Rescale values.
Utils::Span< double > bonded_contribution (int bond_id) const
Get contribution from a bonded interaction.
void add_non_bonded_contribution (int type1, int type2, int molid1, int molid2, Utils::Span< const double > data)
void add_non_bonded_contribution (int type1, int type2, int molid1, int molid2, double data)
Utils::Span< double > non_bonded_intra_contribution (int type1, int type2) const
Get contribution from a non-bonded intramolecular interaction.
Utils::Span< double > non_bonded_inter_contribution (int type1, int type2) const
Get contribution from a non-bonded intermolecular interaction.
void mpi_reduce ()
MPI reduction.
Public Attributes
Utils::Span< double > kinetic
Contribution from linear and angular kinetic energy (accumulated).
Utils::Span< double > bonded
Contribution(s) from bonded interactions.
Utils::Span< double > coulomb
Contribution(s) from Coulomb interactions.
Utils::Span< double > dipolar
Contribution(s) from dipolar interactions.
Utils::Span< double > virtual_sites
Contribution from virtual sites (accumulated).
Utils::Span< double > external_fields
Contribution from external fields (accumulated).
Utils::Span< double > non_bonded_intra
Contribution(s) from non-bonded intramolecular interactions.
Utils::Span< double > non_bonded_inter
Contribution(s) from non-bonded intermolecular interactions.
Detailed Description
Observable for the pressure and energy.
Definition at line 34 of file Observable_stat.hpp.
Constructor & Destructor Documentation
Observable_stat()
Observable_stat::Observable_stat (std::size_t chunk_size, std::size_t n_bonded, int max_type)
Definition at line 38 of file Observable_stat.cpp.
References bonded, coulomb, dipolar, Utils::Span< T >::end(), external_fields, kinetic, Utils::lower_triangular(), non_bonded_inter, non_bonded_intra, and virtual_sites.
Member Function Documentation
accumulate()
double Observable_stat::accumulate (double acc = 0.0, std::size_t column = 0) const inline
Accumulate values.
Parameters
acc Initial value for the accumulator.
column Which column to sum up (only relevant for multi-dimensional observables).
Definition at line 55 of file Observable_stat.hpp.
Referenced by ScriptInterface::Analysis::get_summary().
add_non_bonded_contribution() [1/2]
void Observable_stat::add_non_bonded_contribution (int type1, int type2, int molid1, int molid2, double data) inline
Definition at line 104 of file Observable_stat.hpp.
References add_non_bonded_contribution().
add_non_bonded_contribution() [2/2]
void Observable_stat::add_non_bonded_contribution (int type1, int type2, int molid1, int molid2, Utils::Span< const double > data) inline
Definition at line 95 of file Observable_stat.hpp.
References Utils::Span< T >::begin(), non_bonded_inter, non_bonded_intra, and Utils::Span< T >::size().
Referenced by Constraints::ShapeBasedConstraint::add_energy(), add_non_bonded_contribution(), add_non_bonded_pair_energy(), and add_non_bonded_pair_virials().
bonded_contribution()
Utils::Span<double> Observable_stat::bonded_contribution (int bond_id) const inline
Get contribution from a bonded interaction.
Definition at line 90 of file Observable_stat.hpp.
References bonded, and Utils::Span< T >::data().
Referenced by ScriptInterface::Analysis::get_summary().
get_chunk_size()
auto Observable_stat::get_chunk_size () const inline
Definition at line 48 of file Observable_stat.hpp.
Referenced by ScriptInterface::Analysis::get_summary().
mpi_reduce()
void Observable_stat::mpi_reduce ()
MPI reduction.
Definition at line 82 of file Observable_stat.cpp.
References comm_cart, and walberla::lbm::accessor::MomentumDensity::reduce().
non_bonded_inter_contribution()
Utils::Span<double> Observable_stat::non_bonded_inter_contribution (int type1, int type2) const inline
Get contribution from a non-bonded intermolecular interaction.
Definition at line 116 of file Observable_stat.hpp.
References non_bonded_inter.
Referenced by ScriptInterface::Analysis::get_summary().
non_bonded_intra_contribution()
Utils::Span<double> Observable_stat::non_bonded_intra_contribution (int type1, int type2) const inline
Get contribution from a non-bonded intramolecular interaction.
Definition at line 110 of file Observable_stat.hpp.
References non_bonded_intra.
Referenced by ScriptInterface::Analysis::get_summary().
rescale()
void Observable_stat::rescale (double volume) inline
Rescale values.
Definition at line 67 of file Observable_stat.hpp.
Member Data Documentation
bonded
Utils::Span<double> Observable_stat::bonded
Contribution(s) from bonded interactions.
Definition at line 75 of file Observable_stat.hpp.
Referenced by bonded_contribution(), and Observable_stat().
coulomb
Utils::Span<double> Observable_stat::coulomb
Contribution(s) from Coulomb interactions.
Definition at line 77 of file Observable_stat.hpp.
Referenced by add_non_bonded_pair_energy(), add_non_bonded_pair_virials(), ScriptInterface::Analysis::get_summary(), and Observable_stat().
dipolar
Utils::Span<double> Observable_stat::dipolar
Contribution(s) from dipolar interactions.
Definition at line 79 of file Observable_stat.hpp.
Referenced by Constraints::HomogeneousMagneticField::add_energy(), add_non_bonded_pair_energy(), ScriptInterface::Analysis::get_summary(), and Observable_stat().
external_fields
Utils::Span<double> Observable_stat::external_fields
Contribution from external fields (accumulated).
Definition at line 83 of file Observable_stat.hpp.
Referenced by Constraints::ExternalPotential< Coupling, Field >::add_energy(), ScriptInterface::Analysis::get_summary(), and Observable_stat().
kinetic
Utils::Span<double> Observable_stat::kinetic
Contribution from linear and angular kinetic energy (accumulated).
Definition at line 73 of file Observable_stat.hpp.
Referenced by add_kinetic_virials(), ScriptInterface::Analysis::get_summary(), and Observable_stat().
non_bonded_inter
Utils::Span<double> Observable_stat::non_bonded_inter
Contribution(s) from non-bonded intermolecular interactions.
Definition at line 87 of file Observable_stat.hpp.
Referenced by add_non_bonded_contribution(), non_bonded_inter_contribution(), and Observable_stat().
non_bonded_intra
Utils::Span<double> Observable_stat::non_bonded_intra
Contribution(s) from non-bonded intramolecular interactions.
Definition at line 85 of file Observable_stat.hpp.
Referenced by add_non_bonded_contribution(), non_bonded_intra_contribution(), and Observable_stat().
virtual_sites
Utils::Span<double> Observable_stat::virtual_sites
Contribution from virtual sites (accumulated).
Definition at line 81 of file Observable_stat.hpp.
Referenced by ScriptInterface::Analysis::get_summary(), and Observable_stat().
The documentation for this class was generated from the following files:
Observable_stat.hpp
Observable_stat.cpp