ESPResSo: ScriptInterface::Thermostat::Brownian Class Reference
ScriptInterface::Thermostat::Brownian Class Reference
#include <thermostat.hpp>
Public Member Functions
Brownian ()
::ThermostatFlags get_thermo_flag () const final
Public Member Functions inherited from ScriptInterface::Thermostat::Interface<::BrownianThermostat >
Interface ()
virtual std::optional< double > extract_kT (VariantMap const &params) const
auto release_lock ()
auto is_activated () const
virtual bool is_seed_required () const
auto get_rng_seed () const
auto get_rng_counter () const
void set_rng_seed (Variant const &value)
void set_rng_counter (Variant const &value)
void do_construct (VariantMap const &params) override
void update_and_bind (VariantMap const &params, bool was_active, std::shared_ptr<::System::System > system)
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
VariantMap extend_parameters (VariantMap const &parameters) const override
Protected Member Functions inherited from ScriptInterface::Thermostat::Interface<::BrownianThermostat >
void check_lock ()
void on_bind_system (::System::System &system) override
void on_detach_system (::System::System &system) override
void sanity_checks_positive (double value, std::string const &name) const
void sanity_checks_positive (Utils::Vector3d const &value, std::string const &name) const
virtual bool invalid_rng_state (VariantMap const &params) const
auto make_autoparameter (T CoreThermostat::*member, char const *name)
auto make_autogamma (T CoreThermostat::*member, char const *name)
Variant do_call_method (std::string const &name, VariantMap const &params) override
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Private Member Functions
std::shared_ptr< CoreThermostat > & get_member_handle (::Thermostat::Thermostat &thermostat) override
std::span< std::string_view const > get_required_parameters () const override
Additional Inherited Members
Public Types inherited from ScriptInterface::Thermostat::Interface<::BrownianThermostat >
using CoreThermostat = ::BrownianThermostat
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Attributes inherited from ScriptInterface::Thermostat::Interface<::BrownianThermostat >
bool is_active
std::shared_ptr< CoreThermostat > m_handle
std::weak_ptr< bool > m_edit_lock
Basic lock mechanism that follows RAII.
Detailed Description
Definition at line 348 of file script_interface/thermostat/thermostat.hpp.
Constructor & Destructor Documentation
Brownian()
ScriptInterface::Thermostat::Brownian::Brownian () inline
Definition at line 360 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), BrownianThermostat::gamma, BrownianThermostat::gamma_rotation, and ScriptInterface::Thermostat::Interface<::BrownianThermostat >::make_autogamma().
Member Function Documentation
extend_parameters()
VariantMap ScriptInterface::Thermostat::Brownian::extend_parameters (VariantMap const & parameters) const inline override protected virtual
Reimplemented from ScriptInterface::Thermostat::Interface<::BrownianThermostat >.
Definition at line 372 of file script_interface/thermostat/thermostat.hpp.
References ScriptInterface::Thermostat::Interface< CoreClass >::extend_parameters(), and stream.
get_member_handle()
std::shared_ptr< CoreThermostat > & ScriptInterface::Thermostat::Brownian::get_member_handle (::Thermostat::Thermostat & thermostat) inline override private virtual
Implements ScriptInterface::Thermostat::Interface<::BrownianThermostat >.
Definition at line 350 of file script_interface/thermostat/thermostat.hpp.
References Thermostat::Thermostat::brownian.
get_required_parameters()
std::span< std::string_view const > ScriptInterface::Thermostat::Brownian::get_required_parameters () const inline override private virtual
Implements ScriptInterface::Thermostat::Interface<::BrownianThermostat >.
Definition at line 354 of file script_interface/thermostat/thermostat.hpp.
References stream.
get_thermo_flag()
::ThermostatFlags ScriptInterface::Thermostat::Brownian::get_thermo_flag () const inline final virtual
Implements ScriptInterface::Thermostat::Interface<::BrownianThermostat >.
Definition at line 369 of file script_interface/thermostat/thermostat.hpp.
References THERMO_BROWNIAN.
The documentation for this class was generated from the following file:
script_interface/thermostat/thermostat.hpp