ESPResSo: LBBoundaries::LBBoundary Class Reference
LBBoundaries::LBBoundary Class Reference
#include <LBBoundary.hpp>
Public Member Functions
LBBoundary ()
void calc_dist (const Utils::Vector3d &pos, double &dist, Utils::Vector3d &vec) const
void set_shape (std::shared_ptr< Shapes::Shape > const &shape)
void set_velocity (const Utils::Vector3d &velocity)
void reset_force ()
const Shapes::Shape & shape () const
Utils::Vector3d & velocity ()
Utils::Vector3d & force ()
Utils::Vector3d get_force () const
void set_charge_density (double charge_density)
void set_net_charge (double net_charge)
float & charge_density ()
float & net_charge ()
Detailed Description
Definition at line 37 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
Constructor & Destructor Documentation
LBBoundary()
LBBoundaries::LBBoundary::LBBoundary () inline
Definition at line 39 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
Member Function Documentation
calc_dist()
void LBBoundaries::LBBoundary::calc_dist (const Utils::Vector3d & pos, double & dist, Utils::Vector3d & vec) const inline
Definition at line 50 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
References pos.
charge_density()
float& LBBoundaries::LBBoundary::charge_density () inline
Definition at line 88 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
Referenced by set_charge_density().
force()
Utils::Vector3d& LBBoundaries::LBBoundary::force () inline
Definition at line 69 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
get_force()
Utils::Vector3d LBBoundaries::LBBoundary::get_force () const inline
Definition at line 70 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
References LBBoundaries::lbboundary_get_force().
net_charge()
float& LBBoundaries::LBBoundary::net_charge () inline
Definition at line 89 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
Referenced by set_net_charge().
reset_force()
void LBBoundaries::LBBoundary::reset_force () inline
Definition at line 65 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
set_charge_density()
void LBBoundaries::LBBoundary::set_charge_density (double charge_density) inline
Definition at line 81 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
References charge_density().
set_net_charge()
void LBBoundaries::LBBoundary::set_net_charge (double net_charge) inline
Definition at line 84 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
References net_charge().
set_shape()
void LBBoundaries::LBBoundary::set_shape (std::shared_ptr< Shapes::Shape > const & shape) inline
Definition at line 55 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
References shape().
set_velocity()
void LBBoundaries::LBBoundary::set_velocity (const Utils::Vector3d & velocity) inline
Definition at line 59 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
References LBBoundaries::lb_init_boundaries(), and velocity().
shape()
const Shapes::Shape& LBBoundaries::LBBoundary::shape () const inline
Definition at line 67 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
Referenced by set_shape().
velocity()
Utils::Vector3d& LBBoundaries::LBBoundary::velocity () inline
Definition at line 68 of file core/grid_based_algorithms/lbboundaries/LBBoundary.hpp.
Referenced by set_velocity().
The documentation for this class was generated from the following file:
core/grid_based_algorithms/lbboundaries/LBBoundary.hpp