ESPResSo: walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA Class Reference
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA Class Reference
#include <StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h>
Public Member Functions
StreamCollideSweepSinglePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s)
~StreamCollideSweepSinglePrecisionLeesEdwardsCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getGrid_size () const
float getOmega_shear () const
float getV_s () const
void setGrid_size (const float value)
void setOmega_shear (const float value)
void setV_s (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepSinglePrecisionLeesEdwardsCUDA()
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float grid_size, float omega_shear, float v_s) inline
Definition at line 59 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
~StreamCollideSweepSinglePrecisionLeesEdwardsCUDA()
walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::~StreamCollideSweepSinglePrecisionLeesEdwardsCUDA () inline
Definition at line 66 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 116 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getGrid_size()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getGrid_size () const inline
Definition at line 119 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getOmega_shear () const inline
Definition at line 120 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsCUDA > & kernel) inline static
Definition at line 84 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 101 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionLeesEdwardsCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 89 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 106 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References runOnCellInterval(), and stream.
getV_s()
float walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::getV_s () const inline
Definition at line 121 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 79 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 114 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 167 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::setGrid_size (const float value) inline
Definition at line 122 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::setOmega_shear (const float value) inline
Definition at line 123 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
setV_s()
void walberla::pystencils::StreamCollideSweepSinglePrecisionLeesEdwardsCUDA::setV_s (const float value) inline
Definition at line 124 of file StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.h
StreamCollideSweepSinglePrecisionLeesEdwardsCUDA.cu