ESPResSo: walberla::pystencils::StreamSweepSinglePrecisionAVX Class Reference
walberla::pystencils::StreamSweepSinglePrecisionAVX Class Reference
#include <StreamSweepSinglePrecisionAVX.h>
Public Member Functions
StreamSweepSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
~StreamSweepSinglePrecisionAVX ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamSweepSinglePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamSweepSinglePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID forceID
BlockDataID pdfsID
BlockDataID velocityID
Detailed Description
Definition at line 52 of file StreamSweepSinglePrecisionAVX.h.
Constructor & Destructor Documentation
StreamSweepSinglePrecisionAVX()
walberla::pystencils::StreamSweepSinglePrecisionAVX::StreamSweepSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 54 of file StreamSweepSinglePrecisionAVX.h.
~StreamSweepSinglePrecisionAVX()
walberla::pystencils::StreamSweepSinglePrecisionAVX::~StreamSweepSinglePrecisionAVX () inline
Definition at line 58 of file StreamSweepSinglePrecisionAVX.h.
Member Function Documentation
getSweep() [1/2]
std::function<void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionAVX::getSweep () inline
Definition at line 86 of file StreamSweepSinglePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function<void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionAVX::getSweep (const shared_ptr< StreamSweepSinglePrecisionAVX > & kernel) inline static
Definition at line 73 of file StreamSweepSinglePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
static std::function<void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StreamSweepSinglePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 77 of file StreamSweepSinglePrecisionAVX.h.
getSweepOnCellInterval() [2/2]
std::function<void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 91 of file StreamSweepSinglePrecisionAVX.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::StreamSweepSinglePrecisionAVX::operator() (IBlock * block) inline
Definition at line 70 of file StreamSweepSinglePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::StreamSweepSinglePrecisionAVX::run (IBlock * block)
Definition at line 256 of file StreamSweepSinglePrecisionAVX.cpp.
References block(), force, RESTRICT, walberla::pystencils::internal_5e7ed0276adbfbb1ac4789ac0a0f54c4::streamsweepsingleprecisionavx_streamsweepsingleprecisionavx(), and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamSweepSinglePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 316 of file StreamSweepSinglePrecisionAVX.cpp.
References block(), force, RESTRICT, walberla::pystencils::internal_5e7ed0276adbfbb1ac4789ac0a0f54c4::streamsweepsingleprecisionavx_streamsweepsingleprecisionavx(), and velocity().
Referenced by getSweepOnCellInterval().
Member Data Documentation
forceID
BlockDataID walberla::pystencils::StreamSweepSinglePrecisionAVX::forceID
Definition at line 99 of file StreamSweepSinglePrecisionAVX.h.
pdfsID
BlockDataID walberla::pystencils::StreamSweepSinglePrecisionAVX::pdfsID
Definition at line 100 of file StreamSweepSinglePrecisionAVX.h.
velocityID
BlockDataID walberla::pystencils::StreamSweepSinglePrecisionAVX::velocityID
Definition at line 101 of file StreamSweepSinglePrecisionAVX.h.
The documentation for this class was generated from the following files:
StreamSweepSinglePrecisionAVX.h
StreamSweepSinglePrecisionAVX.cpp