ESPResSo: walberla::pystencils::StreamSweepDoublePrecisionCUDA Class Reference
walberla::pystencils::StreamSweepDoublePrecisionCUDA Class Reference
#include <StreamSweepDoublePrecisionCUDA.h>
Public Member Functions
StreamSweepDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
~StreamSweepDoublePrecisionCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamSweepDoublePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamSweepDoublePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file StreamSweepDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
StreamSweepDoublePrecisionCUDA()
walberla::pystencils::StreamSweepDoublePrecisionCUDA::StreamSweepDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 59 of file StreamSweepDoublePrecisionCUDA.h.
~StreamSweepDoublePrecisionCUDA()
walberla::pystencils::StreamSweepDoublePrecisionCUDA::~StreamSweepDoublePrecisionCUDA () inline
Definition at line 63 of file StreamSweepDoublePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamSweepDoublePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 111 of file StreamSweepDoublePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionCUDA::getSweep (const shared_ptr< StreamSweepDoublePrecisionCUDA > & kernel) inline static
Definition at line 81 of file StreamSweepDoublePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 96 of file StreamSweepDoublePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamSweepDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StreamSweepDoublePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 85 of file StreamSweepDoublePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 101 of file StreamSweepDoublePrecisionCUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::StreamSweepDoublePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 76 of file StreamSweepDoublePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamSweepDoublePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 109 of file StreamSweepDoublePrecisionCUDA.cu.
References block(), RESTRICT, and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamSweepDoublePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 167 of file StreamSweepDoublePrecisionCUDA.cu.
References block(), RESTRICT, and velocity().
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
StreamSweepDoublePrecisionCUDA.h
StreamSweepDoublePrecisionCUDA.cu