ESPResSo: walberla::EKReactionBase Class Reference
walberla::EKReactionBase Class Reference abstract
#include <EKReactionBase.hpp>
Public Types
using reactants_type = std::vector< std::shared_ptr< EKReactant > >
Public Member Functions
EKReactionBase (std::shared_ptr< LatticeWalberla > lattice, reactants_type reactants, double coefficient)
virtual ~EKReactionBase ()=default
void set_coefficient (double coefficient) noexcept
double get_coefficient () const noexcept
auto get_lattice () const noexcept
auto const & get_reactants () const noexcept
virtual void perform_reaction ()=0
Detailed Description
Definition at line 31 of file EKReactionBase.hpp.
Member Typedef Documentation
reactants_type
using walberla::EKReactionBase::reactants_type = std::vector<std::shared_ptr<EKReactant> >
Definition at line 33 of file EKReactionBase.hpp.
Constructor & Destructor Documentation
EKReactionBase()
walberla::EKReactionBase::EKReactionBase (std::shared_ptr< LatticeWalberla > lattice, reactants_type reactants, double coefficient) inline
Definition at line 41 of file EKReactionBase.hpp.
~EKReactionBase()
virtual walberla::EKReactionBase::~EKReactionBase () virtual default
Member Function Documentation
get_coefficient()
double walberla::EKReactionBase::get_coefficient () const inline noexcept
Definition at line 51 of file EKReactionBase.hpp.
Referenced by walberla::EKReactionImplIndexed< Architecture >::perform_reaction().
get_lattice()
auto walberla::EKReactionBase::get_lattice () const inline noexcept
Definition at line 54 of file EKReactionBase.hpp.
Referenced by walberla::EKReactionImplIndexed< Architecture >::boundary_update(), walberla::EKReactionImplIndexed< Architecture >::EKReactionImplIndexed(), walberla::EKReactionImplIndexed< Architecture >::get_node_is_boundary(), walberla::EKReactionImplIndexed< Architecture >::perform_reaction(), and walberla::EKReactionImplIndexed< Architecture >::set_node_is_boundary().
get_reactants()
auto const & walberla::EKReactionBase::get_reactants () const inline noexcept
Definition at line 55 of file EKReactionBase.hpp.
Referenced by walberla::EKReactionImplIndexed< Architecture >::perform_reaction().
perform_reaction()
virtual void walberla::EKReactionBase::perform_reaction () pure virtual
Implemented in walberla::EKReactionImplBulk< Architecture >, and walberla::EKReactionImplIndexed< Architecture >.
set_coefficient()
void walberla::EKReactionBase::set_coefficient (double coefficient) inline noexcept
Definition at line 48 of file EKReactionBase.hpp.
References stream.
The documentation for this class was generated from the following file:
EKReactionBase.hpp