ESPResSo: ScriptInterface::LatticeIndices Class Reference
ScriptInterface::LatticeIndices Class Reference
Interface to carry out simple operations on lattice indices.
#include <LatticeIndices.hpp>
Protected Member Functions
bool is_index_valid (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
void throw_invalid_index (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
Utils::Vector3i get_mapped_index (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
Additional Inherited Members
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
virtual void do_construct (VariantMap const &params)
VariantMap get_parameters () const
Get current parameters.
virtual std::span< const boost::string_ref > valid_parameters () const
Get required and optional parameters for class.
auto get_valid_parameters () const
virtual Variant get_parameter (std::string const &name) const
Get single parameter.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
virtual Variant do_call_method (const std::string &, const VariantMap &)
Local implementation of call_method.
std::string serialize () const
virtual std::vector< std::pair< std::string, Variant > > serialize_parameters () const
Serialize parameters.
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
Interface to carry out simple operations on lattice indices.
Definition at line 33 of file LatticeIndices.hpp.
Member Function Documentation
get_mapped_index()
Utils::Vector3i ScriptInterface::LatticeIndices::get_mapped_index (Utils::Vector3i const & index, Utils::Vector3i const & shape) const inline protected
Definition at line 53 of file LatticeIndices.hpp.
References ScriptInterface::get_value(), is_index_valid(), and throw_invalid_index().
Referenced by ScriptInterface::walberla::EKIndexedReaction::do_call_method(), ScriptInterface::walberla::EKSpeciesNode::do_construct(), and ScriptInterface::walberla::LBFluidNode::do_construct().
is_index_valid()
bool ScriptInterface::LatticeIndices::is_index_valid (Utils::Vector3i const & index, Utils::Vector3i const & shape) const inline protected
Definition at line 35 of file LatticeIndices.hpp.
References ScriptInterface::get_value().
Referenced by ScriptInterface::walberla::EKSpeciesNode::do_call_method(), and get_mapped_index().
throw_invalid_index()
void ScriptInterface::LatticeIndices::throw_invalid_index (Utils::Vector3i const & index, Utils::Vector3i const & shape) const inline protected
Definition at line 40 of file LatticeIndices.hpp.
References ScriptInterface::ObjectHandle::context(), Utils::Array< T, N >::formatter(), and ScriptInterface::get_value().
Referenced by get_mapped_index().
The documentation for this class was generated from the following file:
LatticeIndices.hpp