ESPResSo: Utils::Vector< T, N > Class Template Reference
Utils::Vector< T, N > Class Template Reference
#include <Vector.hpp>
Classes
struct is_vector
struct is_vector< Vector< U, Np > >
Public Member Functions
Vector () noexcept=default
Vector (Vector const &)=default
Vector & operator= (Vector const &)=default
void swap (Vector &rhs)
template<class Range >
requires (not is_vector<std::remove_cvref_t<Range>>::value and not std::is_same_v<std::remove_cvref_t<Range>, T[N]>)
constexpr Vector (Range &&rng)
constexpr Vector (T const (&v)[N]) noexcept
constexpr Vector (std::initializer_list< T > v)
template<typename InputIterator >
Vector (InputIterator first, InputIterator last)
std::vector< T > as_vector () const
operator std::vector< T > () const
constexpr std::span< T, N > as_span () const
constexpr operator std::span< T, N > () const
template<class U >
operator Vector< U, N > () const
constexpr T norm2 () const
T norm () const
Vector & normalize ()
Vector normalized () const
DEVICE_QUALIFIER constexpr reference at (size_type i)
DEVICE_QUALIFIER constexpr const_reference at (size_type i) const
DEVICE_QUALIFIER constexpr reference back ()
DEVICE_QUALIFIER constexpr const_reference back () const
DEVICE_QUALIFIER constexpr iterator begin () noexcept
DEVICE_QUALIFIER constexpr const_iterator begin () const noexcept
DEVICE_QUALIFIER constexpr const_iterator cbegin () const noexcept
DEVICE_QUALIFIER constexpr const_iterator cend () const noexcept
DEVICE_QUALIFIER constexpr pointer data () noexcept
DEVICE_QUALIFIER constexpr const_pointer data () const noexcept
DEVICE_QUALIFIER constexpr bool empty () const noexcept
DEVICE_QUALIFIER constexpr iterator end () noexcept
DEVICE_QUALIFIER constexpr const_iterator end () const noexcept
DEVICE_QUALIFIER void fill (const value_type &value)
DEVICE_QUALIFIER constexpr reference front ()
DEVICE_QUALIFIER constexpr const_reference front () const
DEVICE_QUALIFIER constexpr size_type max_size () const noexcept
DEVICE_QUALIFIER constexpr size_type size () const noexcept
Public Member Functions inherited from Utils::Array< T, N >
DEVICE_QUALIFIER constexpr reference at (size_type i)
DEVICE_QUALIFIER constexpr const_reference at (size_type i) const
DEVICE_QUALIFIER constexpr reference operator[] (size_type i) noexcept
DEVICE_QUALIFIER constexpr const_reference operator[] (size_type i) const noexcept
DEVICE_QUALIFIER constexpr reference front ()
DEVICE_QUALIFIER constexpr const_reference front () const
DEVICE_QUALIFIER constexpr reference back ()
DEVICE_QUALIFIER constexpr const_reference back () const
DEVICE_QUALIFIER constexpr pointer data () noexcept
DEVICE_QUALIFIER constexpr const_pointer data () const noexcept
DEVICE_QUALIFIER constexpr iterator begin () noexcept
DEVICE_QUALIFIER constexpr const_iterator begin () const noexcept
DEVICE_QUALIFIER constexpr const_iterator cbegin () const noexcept
DEVICE_QUALIFIER constexpr iterator end () noexcept
DEVICE_QUALIFIER constexpr const_iterator end () const noexcept
DEVICE_QUALIFIER constexpr const_iterator cend () const noexcept
DEVICE_QUALIFIER constexpr bool empty () const noexcept
DEVICE_QUALIFIER constexpr size_type size () const noexcept
DEVICE_QUALIFIER constexpr size_type max_size () const noexcept
DEVICE_QUALIFIER void fill (const value_type &value)
Static Public Member Functions
static DEVICE_QUALIFIER constexpr Vector< T, N > broadcast (typename Base::value_type const &value) noexcept
Create a vector that has all entries set to the same value.
Static Public Member Functions inherited from Utils::Array< T, N >
static constexpr detail::ArrayFormatter formatter (char const *sep=" ")
Additional Inherited Members
Public Types inherited from Utils::Array< T, N >
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using iterator = value_type *
using const_iterator = const value_type *
using pointer = value_type *
using const_pointer = const value_type *
Public Attributes inherited from Utils::Array< T, N >
detail::Storage< T, N > m_storage
Detailed Description
template<typename T, std::size_t N>
class Utils::Vector< T, N >
Definition at line 50 of file Vector.hpp.
Constructor & Destructor Documentation
Vector() [1/6]
template<typename T , std::size_t N> Utils::Vector< T, N >::Vector () default noexcept
Vector() [2/6]
template<typename T , std::size_t N> Utils::Vector< T, N >::Vector (Vector< T, N > const &) default
Vector() [3/6]
template<typename T , std::size_t N> template<class Range > requires (not is_vector<std::remove_cvref_t<Range>>::value and not std::is_same_v<std::remove_cvref_t<Range>, T[N]>) constexpr Utils::Vector< T, N >::Vector (Range && rng) inline explicit constexpr
Definition at line 94 of file Vector.hpp.
Vector() [4/6]
template<typename T , std::size_t N> constexpr Utils::Vector< T, N >::Vector (T const (&) v[N]) inline explicit constexpr noexcept
Definition at line 103 of file Vector.hpp.
References stream.
Vector() [5/6]
template<typename T , std::size_t N> constexpr Utils::Vector< T, N >::Vector (std::initializer_list< T > v) inline constexpr
Definition at line 109 of file Vector.hpp.
References stream.
Vector() [6/6]
template<typename T , std::size_t N> template<typename InputIterator > Utils::Vector< T, N >::Vector (InputIterator first, InputIterator last) inline
Definition at line 120 of file Vector.hpp.
References Utils::Vector< T, N >::begin(), and stream.
Member Function Documentation
as_span()
template<typename T , std::size_t N> constexpr std::span< T, N > Utils::Vector< T, N >::as_span () const inline constexpr
Definition at line 143 of file Vector.hpp.
References Utils::Vector< T, N >::begin(), and Utils::Vector< T, N >::size().
Referenced by Utils::Vector< int, dim >::operator std::span< int, N >().
as_vector()
template<typename T , std::size_t N> std::vector< T > Utils::Vector< T, N >::as_vector () const inline
Definition at line 139 of file Vector.hpp.
References Utils::Vector< T, N >::begin(), and Utils::Vector< T, N >::end().
Referenced by ScriptInterface::Particles::ParticleHandle::do_call_method(), Utils::Vector< int, dim >::operator std::vector< int >(), and Writer::H5md::write_box().
at() [1/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr reference Utils::Array< T, N >::at (size_type i) inline constexpr
Definition at line 97 of file Array.hpp.
Referenced by calc_rg().
at() [2/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_reference Utils::Array< T, N >::at (size_type i) const inline constexpr
Definition at line 104 of file Array.hpp.
back() [1/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr reference Utils::Array< T, N >::back () inline constexpr
Definition at line 126 of file Array.hpp.
back() [2/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_reference Utils::Array< T, N >::back () const inline constexpr
Definition at line 128 of file Array.hpp.
begin() [1/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_iterator Utils::Array< T, N >::begin () const inline constexpr noexcept
Definition at line 144 of file Array.hpp.
begin() [2/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr iterator Utils::Array< T, N >::begin () inline constexpr noexcept
Definition at line 140 of file Array.hpp.
Referenced by Utils::Vector< T, N >::as_span(), Utils::Vector< T, N >::as_vector(), System::System::calculate_pressure(), DipolarDirectSum::dipole_field_at_part_cpu(), Utils::hadamard_product(), Utils::sqrt(), and Utils::Vector< T, N >::Vector().
broadcast()
template<typename T , std::size_t N> static DEVICE_QUALIFIER constexpr Vector< T, N > Utils::Vector< T, N >::broadcast (typename Base::value_type const & value) inline static constexpr noexcept
Create a vector that has all entries set to the same value.
Definition at line 131 of file Vector.hpp.
References stream.
Referenced by P3MLocalMesh::calc_local_ca_mesh(), Utils::calc_orthonormal_vector(), Observables::LBProfileObservable::calculate_sampling_positions(), CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::determine_mesh_limits(), DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::DipolarP3MHeffte(), ScriptInterface::System::System::do_call_method(), ScriptInterface::walberla::LatticeWalberla::do_construct(), ScriptInterface::Integrators::VelocityVerletIsoNPT::do_construct(), dp3m_k_space_error(), dp3m_tune_aliasing_sums(), FieldCoupling::Fields::Interpolated< T, codim >::fits_in_box(), G_opt(), G_opt_dipolar(), G_opt_dipolar_self_energy(), walberla::get_block_interval(), ScriptInterface::Particles::get_gamma_safe(), walberla::get_interval(), LatticeWalberla::get_local_grid_range(), CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::get_time(), DipolarTuningAlgorithm< FloatType, Architecture, FFTConfig >::get_time(), in_local_domain(), influence_function_r2c(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), walberla::interpolate_bspline_at_pos(), LB::ParticleCoupling::kernel(), P3MFFT< FloatType, FFTConfig >::ks_local_ur_index(), lb_handle_particle_anisotropy(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel(), DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_pressure(), AtomDecomposition::max_cutoff(), p3m_calculate_interpolation_weights(), p3m_gpu_init(), p3m_tune_aliasing_sums(), P3MFFT< FloatType, FFTConfig >::P3MFFT(), P3MParameters::P3MParameters(), positions_in_halo(), P3MParameters::recalc_a_ai_cao_cut(), P3MFFT< FloatType, FFTConfig >::rs_local_size(), ScriptInterface::Thermostat::Interface< CoreClass >::sanity_checks_positive(), ScriptInterface::walberla::LatticeSlice< FieldSerializer >::scatter_3d(), and BoxGeometry::set_length().
cbegin()
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_iterator Utils::Array< T, N >::cbegin () const inline constexpr noexcept
Definition at line 148 of file Array.hpp.
Referenced by Utils::product().
cend()
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_iterator Utils::Array< T, N >::cend () const inline constexpr noexcept
Definition at line 160 of file Array.hpp.
Referenced by Utils::product().
data() [1/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_pointer Utils::Array< T, N >::data () const inline constexpr noexcept
Definition at line 136 of file Array.hpp.
data() [2/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr pointer Utils::Array< T, N >::data () inline constexpr noexcept
Definition at line 132 of file Array.hpp.
Referenced by CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::calculate_accuracy(), Utils::Mpi::cart_coords(), Utils::Mpi::cart_create(), Utils::Mpi::cart_rank(), p3m_send_mesh< FloatType >::gather_grid(), Communicator::init_comm_cart(), Utils::raster(), and p3m_send_mesh< FloatType >::spread_grid().
empty()
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr bool Utils::Array< T, N >::empty () const inline constexpr noexcept
Definition at line 164 of file Array.hpp.
end() [1/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_iterator Utils::Array< T, N >::end () const inline constexpr noexcept
Definition at line 156 of file Array.hpp.
end() [2/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr iterator Utils::Array< T, N >::end () inline constexpr noexcept
Definition at line 152 of file Array.hpp.
Referenced by Utils::Vector< T, N >::as_vector().
fill()
template<typename T , std::size_t N> DEVICE_QUALIFIER void Utils::Array< T, N >::fill (const value_type & value) inline
Definition at line 170 of file Array.hpp.
front() [1/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr reference Utils::Array< T, N >::front () inline constexpr
Definition at line 122 of file Array.hpp.
Referenced by Utils::get_cylindrical_sampling_positions().
front() [2/2]
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr const_reference Utils::Array< T, N >::front () const inline constexpr
Definition at line 124 of file Array.hpp.
max_size()
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr size_type Utils::Array< T, N >::max_size () const inline constexpr noexcept
Definition at line 168 of file Array.hpp.
norm()
template<typename T , std::size_t N> T Utils::Vector< T, N >::norm () const inline
Definition at line 159 of file Vector.hpp.
References Utils::Vector< T, N >::norm2().
Referenced by ElectrostaticLayerCorrection::add_pair_force_corrections(), Utils::area_triangle(), OifLocalForcesBond::calc_forces(), CoulombTuningAlgorithm< FloatType, Architecture, FFTConfig >::calculate_accuracy(), DipolarTuningAlgorithm< FloatType, Architecture, FFTConfig >::calculate_accuracy(), Shapes::Cylinder::calculate_dist(), Shapes::Ellipsoid::calculate_dist(), Shapes::SimplePore::calculate_dist(), Shapes::Sphere::calculate_dist(), Shapes::SpheroCylinder::calculate_dist(), Shapes::Torus::calculate_dist(), convert_dip_to_quat(), Utils::convert_director_to_quaternion(), BondedCoulomb::energy(), Utils::Vector< T, N >::normalize(), Utils::Vector< T, N >::normalized(), ElectrostaticLayerCorrection::pair_energy_correction(), ElectrostaticLayerCorrection::pair_energy_correction(), Shapes::Cylinder::precalc(), Shapes::SpheroCylinder::precalc(), Shapes::Torus::precalc(), and random_unit_vector().
norm2()
template<typename T , std::size_t N> constexpr T Utils::Vector< T, N >::norm2 () const inline constexpr
Definition at line 158 of file Vector.hpp.
Referenced by Utils::calc_orthonormal_vector(), for_each_image(), G_opt(), G_opt_dipolar(), Utils::Vector< T, N >::norm(), and pair_force().
normalize()
template<typename T , std::size_t N> Vector & Utils::Vector< T, N >::normalize () inline
Definition at line 167 of file Vector.hpp.
References Utils::Vector< T, N >::norm(), and stream.
Referenced by add_oif_global_forces(), Shapes::Cylinder::precalc(), Shapes::SpheroCylinder::precalc(), and Shapes::Wall::set_normal().
normalized()
template<typename T , std::size_t N> Vector Utils::Vector< T, N >::normalized () const inline
Definition at line 177 of file Vector.hpp.
References Utils::Vector< T, N >::norm().
Referenced by Utils::basis_change().
operator std::span< T, N >()
template<typename T , std::size_t N> constexpr Utils::Vector< T, N >::operator std::span< T, N > () const inline constexpr
Definition at line 147 of file Vector.hpp.
operator std::vector< T >()
template<typename T , std::size_t N> Utils::Vector< T, N >::operator std::vector< T > () const inline
Definition at line 141 of file Vector.hpp.
operator Vector< U, N >()
template<typename T , std::size_t N> template<class U > Utils::Vector< T, N >::operator Vector< U, N > () const inline explicit
Definition at line 149 of file Vector.hpp.
References stream.
operator=()
template<typename T , std::size_t N> Vector & Utils::Vector< T, N >::operator= (Vector< T, N > const &) default
size()
template<typename T , std::size_t N> DEVICE_QUALIFIER constexpr size_type Utils::Array< T, N >::size () const inline constexpr noexcept
Definition at line 166 of file Array.hpp.
Referenced by Utils::Vector< T, N >::as_span(), System::System::npt_ensemble_init(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary().
swap()
template<typename T , std::size_t N> void Utils::Vector< T, N >::swap (Vector< T, N > & rhs) inline
Definition at line 77 of file Vector.hpp.
References stream.
The documentation for this class was generated from the following file:
Vector.hpp