ESPResSo: Observables::LBFluidPressureTensor Class Reference
Observables::LBFluidPressureTensor Class Reference
#include <LBFluidPressureTensor.hpp>
Public Member Functions
std::vector< std::size_t > shape () const override
std::vector< double > operator() () const override
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Detailed Description
Definition at line 31 of file LBFluidPressureTensor.hpp.
Member Function Documentation
operator()()
std::vector<double> Observables::LBFluidPressureTensor::operator() () const inline override virtual
Implements Observables::Observable.
Definition at line 34 of file LBFluidPressureTensor.hpp.
References lb_lbfluid_get_agrid(), lb_lbfluid_get_pressure_tensor(), lb_lbfluid_get_tau(), and Utils::sqr().
shape()
std::vector<std::size_t> Observables::LBFluidPressureTensor::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 33 of file LBFluidPressureTensor.hpp.
The documentation for this class was generated from the following file:
LBFluidPressureTensor.hpp