ESPResSo: Utils::Span< T > Class Template Reference
Utils::Span< T > Class Template Reference
A stripped-down version of std::span from C++17.
#include <Span.hpp>
Public Types
using value_type = typename std::remove_cv< T >::type
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using size_type = std::size_t
using difference_type = std::ptrdiff_t
Public Member Functions
Span ()=default
Span (const Span &)=default
Span & operator= (const Span &)=default
constexpr DEVICE_QUALIFIER Span (pointer array, size_type length)
template<std::size_t N>
constexpr DEVICE_QUALIFIER Span (T(&a)[N]) noexcept
template<typename C , typename = enable_if_mutable_t<C>, typename = enable_if_has_data_t<C>>
DEVICE_QUALIFIER Span (C &c) noexcept
template<typename C , typename = enable_if_const_t<C>, typename = enable_if_has_data_t<C>>
DEVICE_QUALIFIER Span (const C &c) noexcept
constexpr DEVICE_QUALIFIER size_type size () const
constexpr DEVICE_QUALIFIER bool empty () const
constexpr DEVICE_QUALIFIER iterator begin () const
constexpr DEVICE_QUALIFIER const_iterator cbegin () const
constexpr DEVICE_QUALIFIER iterator end () const
constexpr DEVICE_QUALIFIER const_iterator cend () const
constexpr reverse_iterator rbegin () const
constexpr reverse_iterator rend () const
constexpr DEVICE_QUALIFIER reference operator[] (size_type i) const
constexpr reference at (size_type i) const
constexpr DEVICE_QUALIFIER pointer data () const
Detailed Description
template<class T>
class Utils::Span< T >
A stripped-down version of std::span from C++17.
Behaves like a std::span where implemented.
Definition at line 38 of file Span.hpp.
Member Typedef Documentation
const_iterator
template<class T > using Utils::Span< T >::const_iterator = const_pointer
Definition at line 46 of file Span.hpp.
const_pointer
template<class T > using Utils::Span< T >::const_pointer = const T *
Definition at line 42 of file Span.hpp.
const_reference
template<class T > using Utils::Span< T >::const_reference = const T &
Definition at line 44 of file Span.hpp.
const_reverse_iterator
template<class T > using Utils::Span< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 48 of file Span.hpp.
difference_type
template<class T > using Utils::Span< T >::difference_type = std::ptrdiff_t
Definition at line 50 of file Span.hpp.
iterator
template<class T > using Utils::Span< T >::iterator = pointer
Definition at line 45 of file Span.hpp.
pointer
template<class T > using Utils::Span< T >::pointer = T *
Definition at line 41 of file Span.hpp.
reference
template<class T > using Utils::Span< T >::reference = T &
Definition at line 43 of file Span.hpp.
reverse_iterator
template<class T > using Utils::Span< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 47 of file Span.hpp.
size_type
template<class T > using Utils::Span< T >::size_type = std::size_t
Definition at line 49 of file Span.hpp.
value_type
template<class T > using Utils::Span< T >::value_type = typename std::remove_cv<T>::type
Definition at line 40 of file Span.hpp.
Constructor & Destructor Documentation
Span() [1/6]
template<class T > Utils::Span< T >::Span () default
Span() [2/6]
template<class T > Utils::Span< T >::Span (const Span< T > &) default
Span() [3/6]
template<class T > constexpr DEVICE_QUALIFIER Utils::Span< T >::Span (pointer array, size_type length) inline constexpr
Definition at line 74 of file Span.hpp.
Span() [4/6]
template<class T > template<std::size_t N> constexpr DEVICE_QUALIFIER Utils::Span< T >::Span (T(&) a[N]) inline constexpr noexcept
Definition at line 77 of file Span.hpp.
Span() [5/6]
template<class T > template<typename C , typename = enable_if_mutable_t<C>, typename = enable_if_has_data_t<C>> DEVICE_QUALIFIER Utils::Span< T >::Span (C & c) inline explicit noexcept
Definition at line 81 of file Span.hpp.
Span() [6/6]
template<class T > template<typename C , typename = enable_if_const_t<C>, typename = enable_if_has_data_t<C>> DEVICE_QUALIFIER Utils::Span< T >::Span (const C & c) inline noexcept
Definition at line 84 of file Span.hpp.
Member Function Documentation
at()
template<class T > constexpr reference Utils::Span< T >::at (size_type i) const inline constexpr
Definition at line 102 of file Span.hpp.
References Utils::Span< T >::size().
begin()
template<class T > constexpr DEVICE_QUALIFIER iterator Utils::Span< T >::begin () const inline constexpr
Definition at line 89 of file Span.hpp.
Referenced by Observable_stat::add_non_bonded_contribution(), Neighbors< CellRef >::Neighbors(), Cells::particles(), prefetch_particle_data(), and Utils::Span< T >::rend().
cbegin()
template<class T > constexpr DEVICE_QUALIFIER const_iterator Utils::Span< T >::cbegin () const inline constexpr
Definition at line 90 of file Span.hpp.
cend()
template<class T > constexpr DEVICE_QUALIFIER const_iterator Utils::Span< T >::cend () const inline constexpr
Definition at line 92 of file Span.hpp.
data()
template<class T > constexpr DEVICE_QUALIFIER pointer Utils::Span< T >::data () const inline constexpr
Definition at line 108 of file Span.hpp.
Referenced by Observable_stat::bonded_contribution(), evaluateAsChebychevSeriesAt(), evaluateAsTaylorSeriesAt(), and ScriptInterface::Analysis::get_summary().
empty()
template<class T > constexpr DEVICE_QUALIFIER bool Utils::Span< T >::empty () const inline constexpr
Definition at line 87 of file Span.hpp.
References Utils::Span< T >::size().
Referenced by add_non_bonded_pair_energy(), add_non_bonded_pair_virials(), and evaluateAsTaylorSeriesAt().
end()
template<class T > constexpr DEVICE_QUALIFIER iterator Utils::Span< T >::end () const inline constexpr
Definition at line 91 of file Span.hpp.
Referenced by Neighbors< CellRef >::Neighbors(), Observable_stat::Observable_stat(), Cells::particles(), prefetch_particle_data(), and Utils::Span< T >::rbegin().
operator=()
template<class T > Span& Utils::Span< T >::operator= (const Span< T > &) default
operator[]()
template<class T > constexpr DEVICE_QUALIFIER reference Utils::Span< T >::operator[] (size_type i) const inline constexpr
Definition at line 98 of file Span.hpp.
References DEVICE_ASSERT, and Utils::Span< T >::size().
rbegin()
template<class T > constexpr reverse_iterator Utils::Span< T >::rbegin () const inline constexpr
Definition at line 95 of file Span.hpp.
References Utils::Span< T >::end().
rend()
template<class T > constexpr reverse_iterator Utils::Span< T >::rend () const inline constexpr
Definition at line 96 of file Span.hpp.
References Utils::Span< T >::begin().
size()
template<class T > constexpr DEVICE_QUALIFIER size_type Utils::Span< T >::size () const inline constexpr
Definition at line 86 of file Span.hpp.
Referenced by add_bonded_force(), Observable_stat::add_non_bonded_contribution(), Utils::Span< T >::at(), calc_bonded_energy(), Utils::Span< T >::empty(), evaluateAsChebychevSeriesAt(), evaluateAsTaylorSeriesAt(), p3m_send_mesh::gather_grid(), Neighbors< CellRef >::Neighbors(), Utils::Span< T >::operator[](), p3m_send_mesh::spread_grid(), and Utils::Histogram< T, N, M, U >::update().
The documentation for this class was generated from the following file:
Span.hpp