ESPResSo: ScriptInterface::walberla::EKContainer Class Reference
ScriptInterface::walberla::EKContainer Class Reference
#include <EKContainer.hpp>
Public Member Functions
EKContainer ()
~EKContainer () override
void do_construct (VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::ObjectList< EKSpecies, EK::Container >
ObjectList ()
~ObjectList () override
void do_construct (VariantMap const &params) override
void add (value_type const &element)
Add an element to the list.
void remove (value_type const &element)
Removes all occurrences of an element from the list.
auto const & elements () const
List elements.
void clear ()
Clear the list.
Protected Member Functions
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
Protected Member Functions inherited from ScriptInterface::ObjectList< EKSpecies, EK::Container >
void do_destruct ()
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
Private Member Functions
bool has_in_core (value_type const &obj_ptr) const override
void add_in_core (value_type const &obj_ptr) override
void remove_in_core (value_type const &obj_ptr) final
Additional Inherited Members
Public Types inherited from ScriptInterface::ObjectList< EKSpecies, EK::Container >
using Base = ObjectContainer< ObjectList, EKSpecies, EK::Container >
using value_type = std::shared_ptr< EKSpecies >
Detailed Description
Definition at line 51 of file script_interface/walberla/EKContainer.hpp.
Constructor & Destructor Documentation
EKContainer()
ScriptInterface::walberla::EKContainer::EKContainer () inline
Definition at line 163 of file script_interface/walberla/EKContainer.hpp.
References ScriptInterface::AutoParameter::read_only.
~EKContainer()
ScriptInterface::walberla::EKContainer::~EKContainer () inline override
Definition at line 176 of file script_interface/walberla/EKContainer.hpp.
References ScriptInterface::ObjectList< EKSpecies, EK::Container >::do_destruct().
Member Function Documentation
add_in_core()
void ScriptInterface::walberla::EKContainer::add_in_core (value_type const & obj_ptr) inline override private virtual
Implements ScriptInterface::ObjectList< EKSpecies, EK::Container >.
Definition at line 95 of file script_interface/walberla/EKContainer.hpp.
References ScriptInterface::walberla::ek_throw_if_expired(), ScriptInterface::ObjectList< EKSpecies, EK::Container >::elements(), and stream.
do_call_method()
Variant ScriptInterface::walberla::EKContainer::do_call_method (std::string const & method, VariantMap const & parameters) inline override protected
Definition at line 198 of file script_interface/walberla/EKContainer.hpp.
References ScriptInterface::ObjectList< EKSpecies, EK::Container >::do_call_method(), System::System::ek, EK::Solver::reset(), EK::Solver::set(), and stream.
do_construct()
void ScriptInterface::walberla::EKContainer::do_construct (VariantMap const & params) inline override
Definition at line 178 of file script_interface/walberla/EKContainer.hpp.
References ScriptInterface::ObjectList< EKSpecies, EK::Container >::do_construct(), ScriptInterface::none, and stream.
has_in_core()
bool ScriptInterface::walberla::EKContainer::has_in_core (value_type const & obj_ptr) const inline override private virtual
Implements ScriptInterface::ObjectList< EKSpecies, EK::Container >.
Definition at line 92 of file script_interface/walberla/EKContainer.hpp.
References stream.
remove_in_core()
void ScriptInterface::walberla::EKContainer::remove_in_core (value_type const & obj_ptr) inline final private virtual
Implements ScriptInterface::ObjectList< EKSpecies, EK::Container >.
Definition at line 109 of file script_interface/walberla/EKContainer.hpp.
References stream.
The documentation for this class was generated from the following file:
script_interface/walberla/EKContainer.hpp