ESPResSo: walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision Class Reference
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision Class Reference
#include <StreamCollideSweepThermalizedDoublePrecision.h>
Public Member Functions
StreamCollideSweepThermalizedDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepThermalizedDoublePrecision ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepThermalizedDoublePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedDoublePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepThermalizedDoublePrecision.h.
Constructor & Destructor Documentation
StreamCollideSweepThermalizedDoublePrecision()
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::StreamCollideSweepThermalizedDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 55 of file StreamCollideSweepThermalizedDoublePrecision.h.
~StreamCollideSweepThermalizedDoublePrecision()
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::~StreamCollideSweepThermalizedDoublePrecision () inline
Definition at line 65 of file StreamCollideSweepThermalizedDoublePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 106 of file StreamCollideSweepThermalizedDoublePrecision.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getBlock_offset_0 () const inline
Definition at line 115 of file StreamCollideSweepThermalizedDoublePrecision.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getBlock_offset_1 () const inline
Definition at line 116 of file StreamCollideSweepThermalizedDoublePrecision.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getBlock_offset_2 () const inline
Definition at line 117 of file StreamCollideSweepThermalizedDoublePrecision.h.
getKt()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getKt () const inline
Definition at line 118 of file StreamCollideSweepThermalizedDoublePrecision.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getOmega_bulk () const inline
Definition at line 119 of file StreamCollideSweepThermalizedDoublePrecision.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getOmega_even () const inline
Definition at line 120 of file StreamCollideSweepThermalizedDoublePrecision.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getOmega_odd () const inline
Definition at line 121 of file StreamCollideSweepThermalizedDoublePrecision.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getOmega_shear () const inline
Definition at line 122 of file StreamCollideSweepThermalizedDoublePrecision.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getSeed () const inline
Definition at line 123 of file StreamCollideSweepThermalizedDoublePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getSweep () inline
Definition at line 93 of file StreamCollideSweepThermalizedDoublePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getSweep (const shared_ptr< StreamCollideSweepThermalizedDoublePrecision > & kernel) inline static
Definition at line 79 of file StreamCollideSweepThermalizedDoublePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedDoublePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file StreamCollideSweepThermalizedDoublePrecision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file StreamCollideSweepThermalizedDoublePrecision.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::getTime_step () const inline
Definition at line 124 of file StreamCollideSweepThermalizedDoublePrecision.h.
operator()()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::operator() (IBlock * block) inline
Definition at line 77 of file StreamCollideSweepThermalizedDoublePrecision.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::run (IBlock * block)
Definition at line 426 of file StreamCollideSweepThermalizedDoublePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_fa53b6994358d65dbc792fd71884c2e7::streamcollidesweepthermalizeddoubleprecision_streamcollidesweepthermalizeddoubleprecision().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 486 of file StreamCollideSweepThermalizedDoublePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_fa53b6994358d65dbc792fd71884c2e7::streamcollidesweepthermalizeddoubleprecision_streamcollidesweepthermalizeddoubleprecision().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setBlock_offset_0 (const uint32_t value) inline
Definition at line 125 of file StreamCollideSweepThermalizedDoublePrecision.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setBlock_offset_1 (const uint32_t value) inline
Definition at line 128 of file StreamCollideSweepThermalizedDoublePrecision.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setBlock_offset_2 (const uint32_t value) inline
Definition at line 131 of file StreamCollideSweepThermalizedDoublePrecision.h.
setKt()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setKt (const double value) inline
Definition at line 134 of file StreamCollideSweepThermalizedDoublePrecision.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setOmega_bulk (const double value) inline
Definition at line 135 of file StreamCollideSweepThermalizedDoublePrecision.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setOmega_even (const double value) inline
Definition at line 136 of file StreamCollideSweepThermalizedDoublePrecision.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setOmega_odd (const double value) inline
Definition at line 137 of file StreamCollideSweepThermalizedDoublePrecision.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setOmega_shear (const double value) inline
Definition at line 138 of file StreamCollideSweepThermalizedDoublePrecision.h.
setSeed()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setSeed (const uint32_t value) inline
Definition at line 139 of file StreamCollideSweepThermalizedDoublePrecision.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecision::setTime_step (const uint32_t value) inline
Definition at line 140 of file StreamCollideSweepThermalizedDoublePrecision.h.
The documentation for this class was generated from the following files:
StreamCollideSweepThermalizedDoublePrecision.h
StreamCollideSweepThermalizedDoublePrecision.cpp