ESPResSo: ScriptInterface::ReactionMethods::SingleReaction Class Reference
ScriptInterface::ReactionMethods::SingleReaction Class Reference
#include <SingleReaction.hpp>
Public Member Functions
SingleReaction ()
void do_construct (VariantMap const &params) override
std::shared_ptr<::ReactionMethods::SingleReaction > get_reaction ()
Variant do_call_method (std::string const &name, VariantMap const &) override
Public Member Functions inherited from ScriptInterface::AutoParameters< SingleReaction >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::AutoParameters< SingleReaction >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 34 of file script_interface/reaction_methods/SingleReaction.hpp.
Constructor & Destructor Documentation
SingleReaction()
ScriptInterface::ReactionMethods::SingleReaction::SingleReaction () inline
Definition at line 36 of file script_interface/reaction_methods/SingleReaction.hpp.
References ScriptInterface::AutoParameters< SingleReaction >::add_parameters(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_call_method()
Variant ScriptInterface::ReactionMethods::SingleReaction::do_call_method (std::string const & name, VariantMap const &) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 66 of file script_interface/reaction_methods/SingleReaction.hpp.
References ScriptInterface::ObjectHandle::name().
do_construct()
void ScriptInterface::ReactionMethods::SingleReaction::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 51 of file script_interface/reaction_methods/SingleReaction.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::get_value(), ScriptInterface::Context::parallel_try_catch(), and params.
get_reaction()
std::shared_ptr<::ReactionMethods::SingleReaction> ScriptInterface::ReactionMethods::SingleReaction::get_reaction () inline
Definition at line 62 of file script_interface/reaction_methods/SingleReaction.hpp.
The documentation for this class was generated from the following file:
script_interface/reaction_methods/SingleReaction.hpp