ESPResSo: walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA Class Reference
walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA Class Reference
#include <CollideSweepDoublePrecisionThermalizedCUDA.h>
Public Member Functions
CollideSweepDoublePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepDoublePrecisionThermalizedCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionThermalizedCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
Constructor & Destructor Documentation
CollideSweepDoublePrecisionThermalizedCUDA()
walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::CollideSweepDoublePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 59 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 111 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getBlock_offset_0()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getBlock_offset_0 () const inline
Definition at line 120 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getBlock_offset_1 () const inline
Definition at line 121 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getBlock_offset_2 () const inline
Definition at line 122 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getKt()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getKt () const inline
Definition at line 123 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_bulk()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getOmega_bulk () const inline
Definition at line 124 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_even()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getOmega_even () const inline
Definition at line 125 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_odd()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getOmega_odd () const inline
Definition at line 126 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_shear()
double walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getOmega_shear () const inline
Definition at line 127 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getSeed()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getSeed () const inline
Definition at line 128 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getSweep (const shared_ptr< CollideSweepDoublePrecisionThermalizedCUDA > & kernel) inline static
Definition at line 80 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 96 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionThermalizedCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 85 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 101 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::getTime_step () const inline
Definition at line 129 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
operator()()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 76 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 419 of file CollideSweepDoublePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 464 of file CollideSweepDoublePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 130 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setBlock_offset_1()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 133 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setBlock_offset_2()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 136 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setKt()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setKt (const double value) inline
Definition at line 139 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_bulk()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setOmega_bulk (const double value) inline
Definition at line 140 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_even()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setOmega_even (const double value) inline
Definition at line 141 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_odd()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setOmega_odd (const double value) inline
Definition at line 142 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_shear()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setOmega_shear (const double value) inline
Definition at line 143 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setSeed()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setSeed (const uint32_t value) inline
Definition at line 144 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
setTime_step()
void walberla::pystencils::CollideSweepDoublePrecisionThermalizedCUDA::setTime_step (const uint32_t value) inline
Definition at line 145 of file CollideSweepDoublePrecisionThermalizedCUDA.h.
The documentation for this class was generated from the following files:
CollideSweepDoublePrecisionThermalizedCUDA.h
CollideSweepDoublePrecisionThermalizedCUDA.cu