ESPResSo: Observables::CylindricalLBFluxDensityProfileAtParticlePositions Class Reference
Observables::CylindricalLBFluxDensityProfileAtParticlePositions Class Reference
#include <CylindricalLBFluxDensityProfileAtParticlePositions.hpp>
Public Member Functions
std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, const ParticleObservables::traits< Particle > &traits) const override
std::vector< std::size_t > shape () const override
CylindricalPidProfileObservable (std::vector< int > const &ids, std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z)
Public Member Functions inherited from Observables::CylindricalPidProfileObservable
CylindricalPidProfileObservable (std::vector< int > const &ids, std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > const & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Public Member Functions inherited from Observables::CylindricalProfileObservable
CylindricalProfileObservable (std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z)
Public Member Functions inherited from Observables::ProfileObservable
ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
std::vector< std::size_t > shape () const override
auto n_bins () const
auto limits () const
std::array< std::vector< double >, 3 > edges () const
Calculate the bin edges for each dimension.
Additional Inherited Members
Public Attributes inherited from Observables::CylindricalProfileObservable
std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params
Detailed Description
Definition at line 31 of file CylindricalLBFluxDensityProfileAtParticlePositions.hpp.
Member Function Documentation
CylindricalPidProfileObservable()
Observables::CylindricalPidProfileObservable::CylindricalPidProfileObservable (std::vector< int > const & ids, std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z) inline
Definition at line 34 of file core/observables/CylindricalPidProfileObservable.hpp.
evaluate()
std::vector< double > Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate (boost::mpi::communicator const & comm, ParticleReferenceRange const & local_particles, const ParticleObservables::traits< Particle > & traits) const override virtual
Implements Observables::PidObservable.
Definition at line 36 of file CylindricalLBFluxDensityProfileAtParticlePositions.cpp.
References System::get_system(), Observables::ProfileObservable::limits(), Observables::ProfileObservable::n_bins(), stream, Utils::transform_coordinate_cartesian_to_cylinder(), Observables::CylindricalProfileObservable::transform_params, and Utils::transform_vector_cartesian_to_cylinder().
shape()
std::vector< std::size_t > Observables::CylindricalLBFluxDensityProfileAtParticlePositions::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 41 of file CylindricalLBFluxDensityProfileAtParticlePositions.hpp.
References Observables::ProfileObservable::n_bins().
The documentation for this class was generated from the following files:
CylindricalLBFluxDensityProfileAtParticlePositions.hpp
CylindricalLBFluxDensityProfileAtParticlePositions.cpp