ESPResSo: walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision Class Reference
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision Class Reference
#include <StreamCollideSweepThermalizedSinglePrecision.h>
Public Member Functions
StreamCollideSweepThermalizedSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepThermalizedSinglePrecision ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepThermalizedSinglePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedSinglePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file StreamCollideSweepThermalizedSinglePrecision.h.
Constructor & Destructor Documentation
StreamCollideSweepThermalizedSinglePrecision()
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::StreamCollideSweepThermalizedSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 55 of file StreamCollideSweepThermalizedSinglePrecision.h.
~StreamCollideSweepThermalizedSinglePrecision()
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::~StreamCollideSweepThermalizedSinglePrecision () inline
Definition at line 65 of file StreamCollideSweepThermalizedSinglePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 106 of file StreamCollideSweepThermalizedSinglePrecision.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getBlock_offset_0 () const inline
Definition at line 115 of file StreamCollideSweepThermalizedSinglePrecision.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getBlock_offset_1 () const inline
Definition at line 116 of file StreamCollideSweepThermalizedSinglePrecision.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getBlock_offset_2 () const inline
Definition at line 117 of file StreamCollideSweepThermalizedSinglePrecision.h.
getKt()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getKt () const inline
Definition at line 118 of file StreamCollideSweepThermalizedSinglePrecision.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getOmega_bulk () const inline
Definition at line 119 of file StreamCollideSweepThermalizedSinglePrecision.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getOmega_even () const inline
Definition at line 120 of file StreamCollideSweepThermalizedSinglePrecision.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getOmega_odd () const inline
Definition at line 121 of file StreamCollideSweepThermalizedSinglePrecision.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getOmega_shear () const inline
Definition at line 122 of file StreamCollideSweepThermalizedSinglePrecision.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getSeed () const inline
Definition at line 123 of file StreamCollideSweepThermalizedSinglePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getSweep () inline
Definition at line 93 of file StreamCollideSweepThermalizedSinglePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getSweep (const shared_ptr< StreamCollideSweepThermalizedSinglePrecision > & kernel) inline static
Definition at line 79 of file StreamCollideSweepThermalizedSinglePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedSinglePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file StreamCollideSweepThermalizedSinglePrecision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 98 of file StreamCollideSweepThermalizedSinglePrecision.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::getTime_step () const inline
Definition at line 124 of file StreamCollideSweepThermalizedSinglePrecision.h.
operator()()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::operator() (IBlock * block) inline
Definition at line 77 of file StreamCollideSweepThermalizedSinglePrecision.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::run (IBlock * block)
Definition at line 410 of file StreamCollideSweepThermalizedSinglePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_117eb60e8d249794b47e39bf52c9e4fe::streamcollidesweepthermalizedsingleprecision_streamcollidesweepthermalizedsingleprecision().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 470 of file StreamCollideSweepThermalizedSinglePrecision.cpp.
References block(), RESTRICT, stream, and walberla::pystencils::internal_117eb60e8d249794b47e39bf52c9e4fe::streamcollidesweepthermalizedsingleprecision_streamcollidesweepthermalizedsingleprecision().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setBlock_offset_0 (const uint32_t value) inline
Definition at line 125 of file StreamCollideSweepThermalizedSinglePrecision.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setBlock_offset_1 (const uint32_t value) inline
Definition at line 128 of file StreamCollideSweepThermalizedSinglePrecision.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setBlock_offset_2 (const uint32_t value) inline
Definition at line 131 of file StreamCollideSweepThermalizedSinglePrecision.h.
setKt()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setKt (const float value) inline
Definition at line 134 of file StreamCollideSweepThermalizedSinglePrecision.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setOmega_bulk (const float value) inline
Definition at line 135 of file StreamCollideSweepThermalizedSinglePrecision.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setOmega_even (const float value) inline
Definition at line 136 of file StreamCollideSweepThermalizedSinglePrecision.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setOmega_odd (const float value) inline
Definition at line 137 of file StreamCollideSweepThermalizedSinglePrecision.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setOmega_shear (const float value) inline
Definition at line 138 of file StreamCollideSweepThermalizedSinglePrecision.h.
setSeed()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setSeed (const uint32_t value) inline
Definition at line 139 of file StreamCollideSweepThermalizedSinglePrecision.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecision::setTime_step (const uint32_t value) inline
Definition at line 140 of file StreamCollideSweepThermalizedSinglePrecision.h.
The documentation for this class was generated from the following files:
StreamCollideSweepThermalizedSinglePrecision.h
StreamCollideSweepThermalizedSinglePrecision.cpp