ESPResSo: walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA Class Reference
walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA Class Reference
#include <ReactionKernelBulk_4_double_precision_CUDA.h>
Public Member Functions
ReactionKernelBulk_4_double_precision_CUDA (BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, double order_0, double order_1, double order_2, double order_3, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getOrder_0 () const
double getOrder_1 () const
double getOrder_2 () const
double getOrder_3 () const
double getRate_coefficient () const
double getStoech_0 () const
double getStoech_1 () const
double getStoech_2 () const
double getStoech_3 () const
void setOrder_0 (const double value)
void setOrder_1 (const double value)
void setOrder_2 (const double value)
void setOrder_3 (const double value)
void setRate_coefficient (const double value)
void setStoech_0 (const double value)
void setStoech_1 (const double value)
void setStoech_2 (const double value)
void setStoech_3 (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ReactionKernelBulk_4_double_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_4_double_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file ReactionKernelBulk_4_double_precision_CUDA.h.
Constructor & Destructor Documentation
ReactionKernelBulk_4_double_precision_CUDA()
walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::ReactionKernelBulk_4_double_precision_CUDA (BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, double order_0, double order_1, double order_2, double order_3, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3) inline
Definition at line 57 of file ReactionKernelBulk_4_double_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 110 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getOrder_0()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getOrder_0 () const inline
Definition at line 113 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getOrder_1()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getOrder_1 () const inline
Definition at line 114 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getOrder_2()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getOrder_2 () const inline
Definition at line 115 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getOrder_3()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getOrder_3 () const inline
Definition at line 116 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getRate_coefficient()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getRate_coefficient () const inline
Definition at line 117 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getStoech_0()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getStoech_0 () const inline
Definition at line 118 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getStoech_1()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getStoech_1 () const inline
Definition at line 119 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getStoech_2()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getStoech_2 () const inline
Definition at line 120 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getStoech_3()
double walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getStoech_3 () const inline
Definition at line 121 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getSweep (const shared_ptr< ReactionKernelBulk_4_double_precision_CUDA > & kernel) inline static
Definition at line 79 of file ReactionKernelBulk_4_double_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 95 of file ReactionKernelBulk_4_double_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_4_double_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file ReactionKernelBulk_4_double_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 100 of file ReactionKernelBulk_4_double_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 75 of file ReactionKernelBulk_4_double_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 67 of file ReactionKernelBulk_4_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 114 of file ReactionKernelBulk_4_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setOrder_0()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setOrder_0 (const double value) inline
Definition at line 122 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setOrder_1()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setOrder_1 (const double value) inline
Definition at line 123 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setOrder_2()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setOrder_2 (const double value) inline
Definition at line 124 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setOrder_3()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setOrder_3 (const double value) inline
Definition at line 125 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setRate_coefficient()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setRate_coefficient (const double value) inline
Definition at line 126 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setStoech_0()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setStoech_0 (const double value) inline
Definition at line 129 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setStoech_1()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setStoech_1 (const double value) inline
Definition at line 130 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setStoech_2()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setStoech_2 (const double value) inline
Definition at line 131 of file ReactionKernelBulk_4_double_precision_CUDA.h.
setStoech_3()
void walberla::pystencils::ReactionKernelBulk_4_double_precision_CUDA::setStoech_3 (const double value) inline
Definition at line 132 of file ReactionKernelBulk_4_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
ReactionKernelBulk_4_double_precision_CUDA.h
ReactionKernelBulk_4_double_precision_CUDA.cu