ESPResSo: walberla::pystencils::DiffusiveFluxKernel_single_precision Class Reference
walberla::pystencils::DiffusiveFluxKernel_single_precision Class Reference
#include <DiffusiveFluxKernel_single_precision.h>
Public Member Functions
DiffusiveFluxKernel_single_precision (BlockDataID jID_, BlockDataID rhoID_, float D)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernel_single_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernel_single_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID jID
BlockDataID rhoID
float D_
Detailed Description
Definition at line 53 of file DiffusiveFluxKernel_single_precision.h.
Constructor & Destructor Documentation
DiffusiveFluxKernel_single_precision()
walberla::pystencils::DiffusiveFluxKernel_single_precision::DiffusiveFluxKernel_single_precision (BlockDataID jID_, BlockDataID rhoID_, float D) inline
Definition at line 55 of file DiffusiveFluxKernel_single_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernel_single_precision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 94 of file DiffusiveFluxKernel_single_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_single_precision::getSweep () inline
Definition at line 81 of file DiffusiveFluxKernel_single_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_single_precision::getSweep (const shared_ptr< DiffusiveFluxKernel_single_precision > & kernel) inline static
Definition at line 68 of file DiffusiveFluxKernel_single_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_single_precision::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernel_single_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file DiffusiveFluxKernel_single_precision.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_single_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file DiffusiveFluxKernel_single_precision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::DiffusiveFluxKernel_single_precision::operator() (IBlock * block) inline
Definition at line 65 of file DiffusiveFluxKernel_single_precision.h.
References block(), and run().
run()
void walberla::pystencils::DiffusiveFluxKernel_single_precision::run (IBlock * block)
Definition at line 362 of file DiffusiveFluxKernel_single_precision.cpp.
References block(), D_, walberla::pystencils::internal_2fab63cfdbacde4ac630f257442231a8::diffusivefluxkernel_single_precision_diffusivefluxkernel_single_precision(), jID, RESTRICT, and rhoID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernel_single_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 388 of file DiffusiveFluxKernel_single_precision.cpp.
References block(), D_, walberla::pystencils::internal_2fab63cfdbacde4ac630f257442231a8::diffusivefluxkernel_single_precision_diffusivefluxkernel_single_precision(), jID, RESTRICT, and rhoID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
D_
float walberla::pystencils::DiffusiveFluxKernel_single_precision::D_
Definition at line 99 of file DiffusiveFluxKernel_single_precision.h.
Referenced by run(), and runOnCellInterval().
jID
BlockDataID walberla::pystencils::DiffusiveFluxKernel_single_precision::jID
Definition at line 97 of file DiffusiveFluxKernel_single_precision.h.
Referenced by run(), and runOnCellInterval().
rhoID
BlockDataID walberla::pystencils::DiffusiveFluxKernel_single_precision::rhoID
Definition at line 98 of file DiffusiveFluxKernel_single_precision.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
DiffusiveFluxKernel_single_precision.h
DiffusiveFluxKernel_single_precision.cpp