ESPResSo: walberla::pystencils::Dirichlet_double_precision_CUDA Class Reference
walberla::pystencils::Dirichlet_double_precision_CUDA Class Reference
#include <Dirichlet_double_precision_CUDA.h>
Classes
struct IndexInfo
class IndexVectors
Public Member Functions
Dirichlet_double_precision_CUDA (const std::shared_ptr< StructuredBlockForest > &blocks, BlockDataID fieldID_, std::function< double(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> &dirichletCallback)
void run (IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
void inner (IBlock *block, gpuStream_t stream=nullptr)
void outer (IBlock *block, gpuStream_t stream=nullptr)
Vector3< double > getForce (IBlock *)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getInnerSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getOuterSweep (gpuStream_t stream=nullptr)
template<typename FlagField_T >
void fillFromFlagField (const std::shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (const shared_ptr< StructuredBlockForest > &blocks, IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
Public Attributes
BlockDataID fieldID
Detailed Description
Definition at line 54 of file Dirichlet_double_precision_CUDA.h.
Constructor & Destructor Documentation
Dirichlet_double_precision_CUDA()
walberla::pystencils::Dirichlet_double_precision_CUDA::Dirichlet_double_precision_CUDA (const std::shared_ptr< StructuredBlockForest > & blocks, BlockDataID fieldID_, std::function< double(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> & dirichletCallback) inline
Definition at line 126 of file Dirichlet_double_precision_CUDA.h.
References stream.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::pystencils::Dirichlet_double_precision_CUDA::fillFromFlagField (const shared_ptr< StructuredBlockForest > & blocks, IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 179 of file Dirichlet_double_precision_CUDA.h.
References walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::ALL, block(), walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::indexVector(), walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::INNER, inner(), walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::OUTER, and stream.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::pystencils::Dirichlet_double_precision_CUDA::fillFromFlagField (const std::shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 170 of file Dirichlet_double_precision_CUDA.h.
References block(), and stream.
getForce()
Vector3< double > walberla::pystencils::Dirichlet_double_precision_CUDA::getForce (IBlock *) inline
Definition at line 150 of file Dirichlet_double_precision_CUDA.h.
References stream.
getInnerSweep()
std::function< void(IBlock *)> walberla::pystencils::Dirichlet_double_precision_CUDA::getInnerSweep (gpuStream_t stream = nullptr) inline
Definition at line 161 of file Dirichlet_double_precision_CUDA.h.
References inner(), and stream.
getOuterSweep()
std::function< void(IBlock *)> walberla::pystencils::Dirichlet_double_precision_CUDA::getOuterSweep (gpuStream_t stream = nullptr) inline
Definition at line 165 of file Dirichlet_double_precision_CUDA.h.
References outer(), and stream.
getSweep()
std::function< void(IBlock *)> walberla::pystencils::Dirichlet_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 157 of file Dirichlet_double_precision_CUDA.h.
References run(), and stream.
inner()
void walberla::pystencils::Dirichlet_double_precision_CUDA::inner (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 141 of file Dirichlet_double_precision_CUDA.cu.
References block(), walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::INNER, and stream.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::pystencils::Dirichlet_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 142 of file Dirichlet_double_precision_CUDA.h.
References block(), run(), and stream.
outer()
void walberla::pystencils::Dirichlet_double_precision_CUDA::outer (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 145 of file Dirichlet_double_precision_CUDA.cu.
References block(), walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::OUTER, and stream.
Referenced by getOuterSweep().
run()
void walberla::pystencils::Dirichlet_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 137 of file Dirichlet_double_precision_CUDA.cu.
References walberla::pystencils::Dirichlet_double_precision_CUDA::IndexVectors::ALL, block(), and stream.
Referenced by getSweep(), and operator()().
Member Data Documentation
fieldID
BlockDataID walberla::pystencils::Dirichlet_double_precision_CUDA::fieldID
Definition at line 240 of file Dirichlet_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
Dirichlet_double_precision_CUDA.h
Dirichlet_double_precision_CUDA.cu