ESPResSo: walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX Class Reference
walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX Class Reference
#include <CollideSweepSinglePrecisionThermalizedAVX.h>
Public Member Functions
CollideSweepSinglePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepSinglePrecisionThermalizedAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionThermalizedAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepSinglePrecisionThermalizedAVX.h.
Constructor & Destructor Documentation
CollideSweepSinglePrecisionThermalizedAVX()
walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::CollideSweepSinglePrecisionThermalizedAVX (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file CollideSweepSinglePrecisionThermalizedAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 103 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getBlock_offset_0()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getBlock_offset_0 () const inline
Definition at line 112 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getBlock_offset_1()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getBlock_offset_1 () const inline
Definition at line 113 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getBlock_offset_2()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getBlock_offset_2 () const inline
Definition at line 114 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getKt()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getKt () const inline
Definition at line 115 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_bulk()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getOmega_bulk () const inline
Definition at line 116 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_even()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getOmega_even () const inline
Definition at line 117 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_odd()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getOmega_odd () const inline
Definition at line 118 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getOmega_shear()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getOmega_shear () const inline
Definition at line 119 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getSeed()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getSeed () const inline
Definition at line 120 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getSweep () inline
Definition at line 90 of file CollideSweepSinglePrecisionThermalizedAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getSweep (const shared_ptr< CollideSweepSinglePrecisionThermalizedAVX > & kernel) inline static
Definition at line 76 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionThermalizedAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 81 of file CollideSweepSinglePrecisionThermalizedAVX.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 95 of file CollideSweepSinglePrecisionThermalizedAVX.h.
References runOnCellInterval().
getTime_step()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::getTime_step () const inline
Definition at line 121 of file CollideSweepSinglePrecisionThermalizedAVX.h.
operator()()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::operator() (IBlock * block) inline
Definition at line 74 of file CollideSweepSinglePrecisionThermalizedAVX.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::run (IBlock * block)
Definition at line 741 of file CollideSweepSinglePrecisionThermalizedAVX.cpp.
References block(), walberla::pystencils::internal_48c9ee502281a70505dce0378c55abd5::collidesweepsingleprecisionthermalizedavx_collidesweepsingleprecisionthermalizedavx(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 787 of file CollideSweepSinglePrecisionThermalizedAVX.cpp.
References block(), walberla::pystencils::internal_48c9ee502281a70505dce0378c55abd5::collidesweepsingleprecisionthermalizedavx_collidesweepsingleprecisionthermalizedavx(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setBlock_offset_0 (const uint32_t value) inline
Definition at line 122 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setBlock_offset_1()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setBlock_offset_1 (const uint32_t value) inline
Definition at line 125 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setBlock_offset_2()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setBlock_offset_2 (const uint32_t value) inline
Definition at line 128 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setKt()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setKt (const float value) inline
Definition at line 131 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_bulk()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setOmega_bulk (const float value) inline
Definition at line 132 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_even()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setOmega_even (const float value) inline
Definition at line 133 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_odd()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setOmega_odd (const float value) inline
Definition at line 134 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setOmega_shear()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setOmega_shear (const float value) inline
Definition at line 135 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setSeed()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setSeed (const uint32_t value) inline
Definition at line 136 of file CollideSweepSinglePrecisionThermalizedAVX.h.
setTime_step()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedAVX::setTime_step (const uint32_t value) inline
Definition at line 137 of file CollideSweepSinglePrecisionThermalizedAVX.h.
The documentation for this class was generated from the following files:
CollideSweepSinglePrecisionThermalizedAVX.h
CollideSweepSinglePrecisionThermalizedAVX.cpp