ESPResSo: PartCfg Class Reference
PartCfg Class Reference
Particle cache on the head node.
#include <PartCfg.hpp>
Public Types
using value_type = Particle
Public Member Functions
PartCfg ()
auto begin ()
Iterator pointing to the particle with the lowest id.
auto end ()
Iterator pointing past the particle with the highest id.
bool valid () const
Returns true if the cache is up-to-date.
void invalidate ()
Invalidate the cache and free memory.
std::size_t size ()
Number of particles in the config.
bool empty ()
size() == 0 ?
Detailed Description
Particle cache on the head node.
This class implements cached access to all particles in a particle range on the head node. This implementation fetches all particles to the head node on first access, which invalidates all existing particle pointers. Updates of the particle data are triggered automatically on access. The data in the cache is invalidated automatically by on_particle_change, and then updated on the next access.
Definition at line 38 of file PartCfg.hpp.
Member Typedef Documentation
value_type
using PartCfg::value_type = Particle
Definition at line 45 of file PartCfg.hpp.
Constructor & Destructor Documentation
PartCfg()
PartCfg::PartCfg () inline
Definition at line 46 of file PartCfg.hpp.
Member Function Documentation
begin()
auto PartCfg::begin () inline
Iterator pointing to the particle with the lowest id.
Returns a random access iterator that traverses the particles in order of ascending id. If the cache is not up-to-date, an update is triggered. This iterator stays valid as long as the cache is valid. Since the cache could be invalidated and updated elsewhere, iterators into the cache should not be stored.
Definition at line 60 of file PartCfg.hpp.
Referenced by mindist().
empty()
bool PartCfg::empty () inline
size() == 0 ?
Definition at line 121 of file PartCfg.hpp.
end()
auto PartCfg::end () inline
Iterator pointing past the particle with the highest id.
If the cache is not up-to-date, an update is triggered.
Definition at line 74 of file PartCfg.hpp.
Referenced by mindist().
invalidate()
void PartCfg::invalidate () inline
Invalidate the cache and free memory.
Definition at line 91 of file PartCfg.hpp.
Referenced by on_integration_start(), on_particle_change(), and on_particle_charge_change().
size()
std::size_t PartCfg::size () inline
Number of particles in the config.
Definition at line 111 of file PartCfg.hpp.
valid()
bool PartCfg::valid () const inline
Returns true if the cache is up-to-date.
If false, particle access will trigger an update.
Definition at line 86 of file PartCfg.hpp.
The documentation for this class was generated from the following files:
PartCfg.hpp
PartCfg.cpp