ESPResSo: Shapes::Slitpore Class Reference
Shapes::Slitpore Class Reference
#include <Slitpore.hpp>
Public Member Functions
Slitpore ()
void calculate_dist (const Utils::Vector3d &pos, double &dist, Utils::Vector3d &vec) const override
double & pore_mouth ()
double & upper_smoothing_radius ()
double & lower_smoothing_radius ()
double & channel_width ()
double & pore_width ()
double & pore_length ()
double & dividing_plane ()
const double & dividing_plane () const
Public Member Functions inherited from Shapes::Shape
virtual bool is_inside (Utils::Vector3d const &pos) const
Check whether the given point is inside the shape or not.
std::vector< int > rasterize (Utils::Vector3i const &grid_size, double grid_spacing, double grid_offset) const
Rasterize a shape on a regular grid.
virtual ~Shape ()=default
Detailed Description
Definition at line 30 of file shapes/include/shapes/Slitpore.hpp.
Constructor & Destructor Documentation
Slitpore()
Shapes::Slitpore::Slitpore () inline
Definition at line 32 of file shapes/include/shapes/Slitpore.hpp.
Member Function Documentation
calculate_dist()
void Shapes::Slitpore::calculate_dist (const Utils::Vector3d & pos, double & dist, Utils::Vector3d & vec) const override virtual
Implements Shapes::Shape.
Definition at line 30 of file Slitpore.cpp.
References dividing_plane(), pos, Utils::sqr(), and Utils::sqrt().
channel_width()
double& Shapes::Slitpore::channel_width () inline
Definition at line 43 of file shapes/include/shapes/Slitpore.hpp.
dividing_plane() [1/2]
double& Shapes::Slitpore::dividing_plane () inline
Definition at line 46 of file shapes/include/shapes/Slitpore.hpp.
Referenced by calculate_dist().
dividing_plane() [2/2]
const double& Shapes::Slitpore::dividing_plane () const inline
Definition at line 47 of file shapes/include/shapes/Slitpore.hpp.
lower_smoothing_radius()
double& Shapes::Slitpore::lower_smoothing_radius () inline
Definition at line 42 of file shapes/include/shapes/Slitpore.hpp.
pore_length()
double& Shapes::Slitpore::pore_length () inline
Definition at line 45 of file shapes/include/shapes/Slitpore.hpp.
pore_mouth()
double& Shapes::Slitpore::pore_mouth () inline
Definition at line 40 of file shapes/include/shapes/Slitpore.hpp.
pore_width()
double& Shapes::Slitpore::pore_width () inline
Definition at line 44 of file shapes/include/shapes/Slitpore.hpp.
upper_smoothing_radius()
double& Shapes::Slitpore::upper_smoothing_radius () inline
Definition at line 41 of file shapes/include/shapes/Slitpore.hpp.
The documentation for this class was generated from the following files:
shapes/include/shapes/Slitpore.hpp
Slitpore.cpp