ESPResSo: walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA Class Reference
walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA Class Reference
#include <CollideSweepDoublePrecisionLeesEdwardsCUDA.h>
Public Member Functions
CollideSweepDoublePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getGrid_size () const
double getOmega_shear () const
double getV_s () const
void setGrid_size (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
Constructor & Destructor Documentation
CollideSweepDoublePrecisionLeesEdwardsCUDA()
walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::CollideSweepDoublePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s) inline
Definition at line 59 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 108 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getGrid_size()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getGrid_size () const inline
Definition at line 111 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getOmega_shear()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getOmega_shear () const inline
Definition at line 112 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getSweep (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsCUDA > & kernel) inline static
Definition at line 77 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 93 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 82 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 98 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References runOnCellInterval(), and stream.
getV_s()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::getV_s () const inline
Definition at line 113 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
operator()()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 73 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 157 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 193 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::setGrid_size (const double value) inline
Definition at line 114 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
setOmega_shear()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::setOmega_shear (const double value) inline
Definition at line 115 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
setV_s()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsCUDA::setV_s (const double value) inline
Definition at line 116 of file CollideSweepDoublePrecisionLeesEdwardsCUDA.h.
The documentation for this class was generated from the following files:
CollideSweepDoublePrecisionLeesEdwardsCUDA.h
CollideSweepDoublePrecisionLeesEdwardsCUDA.cu