ESPResSo: walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX Class Reference
walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX Class Reference
#include <CollideSweepDoublePrecisionLeesEdwardsAVX.h>
Public Member Functions
CollideSweepDoublePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getGrid_size () const
double getOmega_shear () const
double getV_s () const
void setGrid_size (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
Constructor & Destructor Documentation
CollideSweepDoublePrecisionLeesEdwardsAVX()
walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::CollideSweepDoublePrecisionLeesEdwardsAVX (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s) inline
Definition at line 57 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 99 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
getGrid_size()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getGrid_size () const inline
Definition at line 102 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
getOmega_shear()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getOmega_shear () const inline
Definition at line 103 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getSweep () inline
Definition at line 86 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getSweep (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsAVX > & kernel) inline static
Definition at line 72 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< CollideSweepDoublePrecisionLeesEdwardsAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 77 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 91 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
References runOnCellInterval().
getV_s()
double walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::getV_s () const inline
Definition at line 104 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
operator()()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::operator() (IBlock * block) inline
Definition at line 70 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::run (IBlock * block)
Definition at line 261 of file CollideSweepDoublePrecisionLeesEdwardsAVX.cpp.
References block(), walberla::pystencils::internal_f11a519921c681cbc9d0b2f51454c920::collidesweepdoubleprecisionleesedwardsavx_collidesweepdoubleprecisionleesedwardsavx(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 298 of file CollideSweepDoublePrecisionLeesEdwardsAVX.cpp.
References block(), walberla::pystencils::internal_f11a519921c681cbc9d0b2f51454c920::collidesweepdoubleprecisionleesedwardsavx_collidesweepdoubleprecisionleesedwardsavx(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::setGrid_size (const double value) inline
Definition at line 105 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
setOmega_shear()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::setOmega_shear (const double value) inline
Definition at line 106 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
setV_s()
void walberla::pystencils::CollideSweepDoublePrecisionLeesEdwardsAVX::setV_s (const double value) inline
Definition at line 107 of file CollideSweepDoublePrecisionLeesEdwardsAVX.h.
The documentation for this class was generated from the following files:
CollideSweepDoublePrecisionLeesEdwardsAVX.h
CollideSweepDoublePrecisionLeesEdwardsAVX.cpp