ESPResSo: p3m_send_mesh< FloatType > Class Template Reference
p3m_send_mesh< FloatType > Class Template Reference
P3M halo communicator.
#include <send_mesh.hpp>
Public Member Functions
void resize (boost::mpi::communicator const &comm, P3MLocalMesh const &local_mesh)
void gather_grid (boost::mpi::communicator const &comm, std::span< FloatType * > meshes, Utils::Vector3i const &dim)
void gather_grid (boost::mpi::communicator const &comm, FloatType *mesh, Utils::Vector3i const &dim)
void spread_grid (boost::mpi::communicator const &comm, std::span< FloatType * > meshes, Utils::Vector3i const &dim)
void spread_grid (boost::mpi::communicator const &comm, FloatType *mesh, Utils::Vector3i const &dim)
Detailed Description
template<typename FloatType>
class p3m_send_mesh< FloatType >
P3M halo communicator.
Definition at line 38 of file send_mesh.hpp.
Member Function Documentation
gather_grid() [1/2]
template<typename FloatType > void p3m_send_mesh< FloatType >::gather_grid (boost::mpi::communicator const & comm, FloatType * mesh, Utils::Vector3i const & dim) inline
Definition at line 73 of file send_mesh.hpp.
References p3m_send_mesh< FloatType >::gather_grid().
gather_grid() [2/2]
template<typename FloatType > void p3m_send_mesh< FloatType >::gather_grid (boost::mpi::communicator const & comm, std::span< FloatType * > meshes, Utils::Vector3i const & dim)
Definition at line 165 of file send_mesh.cpp.
References Utils::Vector< T, N >::data(), fft_pack_block(), mesh_sendrecv(), p3m_add_block(), and stream.
Referenced by p3m_send_mesh< FloatType >::gather_grid().
resize()
template<typename FloatType > void p3m_send_mesh< FloatType >::resize (boost::mpi::communicator const & comm, P3MLocalMesh const & local_mesh)
Definition at line 91 of file send_mesh.cpp.
References P3MLocalMesh::dim, P3MLocalMesh::in_ur, P3MLocalMesh::margin, mesh_sendrecv(), and stream.
spread_grid() [1/2]
template<typename FloatType > void p3m_send_mesh< FloatType >::spread_grid (boost::mpi::communicator const & comm, FloatType * mesh, Utils::Vector3i const & dim) inline
Definition at line 79 of file send_mesh.hpp.
References p3m_send_mesh< FloatType >::spread_grid().
spread_grid() [2/2]
template<typename FloatType > void p3m_send_mesh< FloatType >::spread_grid (boost::mpi::communicator const & comm, std::span< FloatType * > meshes, Utils::Vector3i const & dim)
Definition at line 205 of file send_mesh.cpp.
References Utils::Vector< T, N >::data(), fft_pack_block(), fft_unpack_block(), mesh_sendrecv(), and stream.
Referenced by p3m_send_mesh< FloatType >::spread_grid().
The documentation for this class was generated from the following files:
send_mesh.hpp
send_mesh.cpp