ESPResSo: walberla::pystencils::ContinuityKernel_single_precision_CUDA Class Reference
walberla::pystencils::ContinuityKernel_single_precision_CUDA Class Reference
#include <ContinuityKernel_single_precision_CUDA.h>
Public Member Functions
ContinuityKernel_single_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ContinuityKernel_single_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< ContinuityKernel_single_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file ContinuityKernel_single_precision_CUDA.h.
Constructor & Destructor Documentation
ContinuityKernel_single_precision_CUDA()
walberla::pystencils::ContinuityKernel_single_precision_CUDA::ContinuityKernel_single_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_) inline
Definition at line 57 of file ContinuityKernel_single_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::ContinuityKernel_single_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 102 of file ContinuityKernel_single_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision_CUDA::getSweep (const shared_ptr< ContinuityKernel_single_precision_CUDA > & kernel) inline static
Definition at line 72 of file ContinuityKernel_single_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 87 of file ContinuityKernel_single_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::ContinuityKernel_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< ContinuityKernel_single_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 76 of file ContinuityKernel_single_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 92 of file ContinuityKernel_single_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::ContinuityKernel_single_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 67 of file ContinuityKernel_single_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::ContinuityKernel_single_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 59 of file ContinuityKernel_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ContinuityKernel_single_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 90 of file ContinuityKernel_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
ContinuityKernel_single_precision_CUDA.h
ContinuityKernel_single_precision_CUDA.cu