ESPResSo: walberla::PoissonSolverCuFFT< FloatType > Class Template Reference
walberla::PoissonSolverCuFFT< FloatType > Class Template Reference
#include <PoissonSolverCuFFT.hpp>
Classes
class PotentialVTKWriter
class VTKWriter
Public Member Functions
PoissonSolverCuFFT ()=default
PoissonSolverCuFFT (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
~PoissonSolverCuFFT () override=default
void reset_charge_field () override
void add_charge_to_field (std::size_t id, double valency, bool is_double_precision) override
std::size_t get_potential_field_id () const noexcept override
void solve () override
void set_permittivity (double permittivity) noexcept override
double get_permittivity () const noexcept override
LatticeWalberla const & get_lattice () const noexcept override
std::optional< double > get_node_potential (Utils::Vector3i const &node, bool consider_ghosts=false) override
std::vector< double > get_slice_potential (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const override
Public Member Functions inherited from walberla::PoissonSolver
PoissonSolver (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
~PoissonSolver () override=default
Public Member Functions inherited from LatticeModel
virtual ~LatticeModel ()=default
std::shared_ptr< VTKHandle > create_vtk (int delta_N, int initial_count, int flag_observables, units_map const &units_conversion, std::string const &identifier, std::string const &base_folder, std::string const &prefix)
Create a VTK observable.
void write_vtk (std::string const &vtk_uid)
Write a VTK observable to disk.
void switch_vtk (std::string const &vtk_uid, bool status)
Toggle a VTK observable on/off.
Protected Member Functions
void register_vtk_field_writers (walberla::vtk::VTKOutput &vtk_obj, LatticeModel::units_map const &units, int flag_observables) override
void integrate_vtk_writers () override
Protected Member Functions inherited from walberla::PoissonSolver
void register_vtk_field_filters (walberla::vtk::VTKOutput &vtk_obj) override
Additional Inherited Members
Public Types inherited from LatticeModel
using units_map = std::unordered_map< std::string, double >
Protected Attributes inherited from LatticeModel
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_auto
VTK writers that are executed automatically.
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_manual
VTK writers that are executed manually.
Detailed Description
template<typename FloatType>
class walberla::PoissonSolverCuFFT< FloatType >
Definition at line 45 of file PoissonSolverCuFFT.hpp.
Constructor & Destructor Documentation
PoissonSolverCuFFT() [1/2]
template<typename FloatType > walberla::PoissonSolverCuFFT< FloatType >::PoissonSolverCuFFT () default
PoissonSolverCuFFT() [2/2]
template<typename FloatType > walberla::PoissonSolverCuFFT< FloatType >::PoissonSolverCuFFT (std::shared_ptr< LatticeWalberla > lattice, double permittivity) inline
Definition at line 60 of file PoissonSolverCuFFT.hpp.
References stream.
~PoissonSolverCuFFT()
template<typename FloatType > walberla::PoissonSolverCuFFT< FloatType >::~PoissonSolverCuFFT () override default
Member Function Documentation
add_charge_to_field()
template<typename FloatType > void walberla::PoissonSolverCuFFT< FloatType >::add_charge_to_field (std::size_t id, double valency, bool is_double_precision) inline override virtual
Implements walberla::PoissonSolver.
Definition at line 71 of file PoissonSolverCuFFT.hpp.
References stream.
get_lattice()
template<typename FloatType > LatticeWalberla const & walberla::PoissonSolverCuFFT< FloatType >::get_lattice () const inline override virtual noexcept
Reimplemented from walberla::PoissonSolver.
Definition at line 93 of file PoissonSolverCuFFT.hpp.
Referenced by walberla::PoissonSolverCuFFT< FloatType >::get_node_potential(), walberla::PoissonSolverCuFFT< FloatType >::get_slice_potential(), and walberla::PoissonSolverCuFFT< FloatType >::register_vtk_field_writers().
get_node_potential()
template<typename FloatType > std::optional< double > walberla::PoissonSolverCuFFT< FloatType >::get_node_potential (Utils::Vector3i const & node, bool consider_ghosts = false) inline override virtual
Implements walberla::PoissonSolver.
Definition at line 98 of file PoissonSolverCuFFT.hpp.
References walberla::ek::accessor::Scalar::get(), walberla::get_block_and_cell(), walberla::PoissonSolverCuFFT< FloatType >::get_lattice(), walberla::PoissonSolverCuFFT< FloatType >::get_potential_field_id(), and stream.
get_permittivity()
template<typename FloatType > double walberla::PoissonSolverCuFFT< FloatType >::get_permittivity () const inline override virtual noexcept
Reimplemented from walberla::PoissonSolver.
Definition at line 89 of file PoissonSolverCuFFT.hpp.
get_potential_field_id()
template<typename FloatType > std::size_t walberla::PoissonSolverCuFFT< FloatType >::get_potential_field_id () const inline override virtual noexcept
Implements walberla::PoissonSolver.
Definition at line 76 of file PoissonSolverCuFFT.hpp.
Referenced by walberla::PoissonSolverCuFFT< FloatType >::get_node_potential(), walberla::PoissonSolverCuFFT< FloatType >::get_slice_potential(), and walberla::PoissonSolverCuFFT< FloatType >::register_vtk_field_writers().
get_slice_potential()
template<typename FloatType > std::vector< double > walberla::PoissonSolverCuFFT< FloatType >::get_slice_potential (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline override virtual
Implements walberla::PoissonSolver.
Definition at line 112 of file PoissonSolverCuFFT.hpp.
References block(), walberla::copy_block_buffer(), walberla::ek::accessor::Scalar::get(), walberla::get_block_interval(), walberla::get_interval(), walberla::PoissonSolverCuFFT< FloatType >::get_lattice(), walberla::PoissonSolverCuFFT< FloatType >::get_potential_field_id(), and stream.
integrate_vtk_writers()
template<typename FloatType > void walberla::PoissonSolverCuFFT< FloatType >::integrate_vtk_writers () inline override protected virtual
Reimplemented from walberla::PoissonSolver.
Definition at line 207 of file PoissonSolverCuFFT.hpp.
References LatticeModel::m_vtk_auto, and stream.
Referenced by walberla::PoissonSolverCuFFT< FloatType >::solve().
register_vtk_field_writers()
template<typename FloatType > void walberla::PoissonSolverCuFFT< FloatType >::register_vtk_field_writers (walberla::vtk::VTKOutput & vtk_obj, LatticeModel::units_map const & units, int flag_observables) inline override protected virtual
Reimplemented from walberla::PoissonSolver.
Definition at line 181 of file PoissonSolverCuFFT.hpp.
References LatticeWalberla::get_blocks(), LatticeWalberla::get_ghost_layers(), walberla::PoissonSolverCuFFT< FloatType >::get_lattice(), walberla::PoissonSolverCuFFT< FloatType >::get_potential_field_id(), potential, and stream.
reset_charge_field()
template<typename FloatType > void walberla::PoissonSolverCuFFT< FloatType >::reset_charge_field () inline override virtual
Implements walberla::PoissonSolver.
Definition at line 69 of file PoissonSolverCuFFT.hpp.
set_permittivity()
template<typename FloatType > void walberla::PoissonSolverCuFFT< FloatType >::set_permittivity (double permittivity) inline override virtual noexcept
Reimplemented from walberla::PoissonSolver.
Definition at line 85 of file PoissonSolverCuFFT.hpp.
References stream.
solve()
template<typename FloatType > void walberla::PoissonSolverCuFFT< FloatType >::solve () inline override virtual
Implements walberla::PoissonSolver.
Definition at line 80 of file PoissonSolverCuFFT.hpp.
References walberla::PoissonSolverCuFFT< FloatType >::integrate_vtk_writers().
The documentation for this class was generated from the following file:
PoissonSolverCuFFT.hpp