ESPResSo: Observables::CylindricalLBProfileObservable Class Reference
Observables::CylindricalLBProfileObservable Class Reference
#include <CylindricalLBProfileObservable.hpp>
Public Member Functions
CylindricalLBProfileObservable (std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z, double sampling_density)
void calculate_sampling_positions (auto const &box_geo, auto const &lb) const
Public Member Functions inherited from Observables::CylindricalProfileObservable
CylindricalProfileObservable (std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z)
Public Member Functions inherited from Observables::ProfileObservable
ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
std::vector< std::size_t > shape () const override
auto n_bins () const
auto limits () const
std::array< std::vector< double >, 3 > edges () const
Calculate the bin edges for each dimension.
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
virtual std::vector< double > operator() (boost::mpi::communicator const &comm) const =0
Calculate the set of values measured by the observable.
std::size_t n_values () const
Size of the flat array returned by the observable.
Public Attributes
double sampling_density
Public Attributes inherited from Observables::CylindricalProfileObservable
std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params
Protected Attributes
SanityChecksLB lb_sanity_checks
std::vector< Utils::Vector3d > sampling_positions
std::vector< Utils::Vector3d > sampling_positions_cyl
std::vector< Utils::Vector3d > sampling_positions_cart
Detailed Description
Definition at line 38 of file core/observables/CylindricalLBProfileObservable.hpp.
Constructor & Destructor Documentation
CylindricalLBProfileObservable()
Observables::CylindricalLBProfileObservable::CylindricalLBProfileObservable (std::shared_ptr< Utils::CylindricalTransformationParameters > transform_params, int n_r_bins, int n_phi_bins, int n_z_bins, double min_r, double max_r, double min_phi, double max_phi, double min_z, double max_z, double sampling_density) inline
Definition at line 40 of file core/observables/CylindricalLBProfileObservable.hpp.
Member Function Documentation
calculate_sampling_positions()
void Observables::CylindricalLBProfileObservable::calculate_sampling_positions (auto const & box_geo, auto const & lb) const inline
Definition at line 60 of file core/observables/CylindricalLBProfileObservable.hpp.
References Utils::angle_between(), Utils::get_cylindrical_sampling_positions(), lb_sanity_checks, Observables::ProfileObservable::limits(), Observables::ProfileObservable::n_bins(), sampling_density, sampling_positions, sampling_positions_cart, sampling_positions_cyl, stream, Utils::transform_coordinate_cartesian_to_cylinder(), Utils::transform_coordinate_cylinder_to_cartesian(), Observables::CylindricalProfileObservable::transform_params, Utils::vec_rotate(), and Utils::vector_product().
Referenced by Observables::CylindricalLBVelocityProfile::operator()().
Member Data Documentation
lb_sanity_checks
SanityChecksLB Observables::CylindricalLBProfileObservable::lb_sanity_checks mutable protected
Definition at line 54 of file core/observables/CylindricalLBProfileObservable.hpp.
Referenced by calculate_sampling_positions(), and Observables::CylindricalLBVelocityProfile::operator()().
sampling_density
double Observables::CylindricalLBProfileObservable::sampling_density
Definition at line 51 of file core/observables/CylindricalLBProfileObservable.hpp.
Referenced by calculate_sampling_positions().
sampling_positions
std::vector<Utils::Vector3d> Observables::CylindricalLBProfileObservable::sampling_positions mutable protected
Definition at line 55 of file core/observables/CylindricalLBProfileObservable.hpp.
Referenced by calculate_sampling_positions(), and Observables::CylindricalLBVelocityProfile::operator()().
sampling_positions_cart
std::vector<Utils::Vector3d> Observables::CylindricalLBProfileObservable::sampling_positions_cart mutable protected
Definition at line 57 of file core/observables/CylindricalLBProfileObservable.hpp.
Referenced by calculate_sampling_positions(), and Observables::CylindricalLBVelocityProfile::operator()().
sampling_positions_cyl
std::vector<Utils::Vector3d> Observables::CylindricalLBProfileObservable::sampling_positions_cyl mutable protected
Definition at line 56 of file core/observables/CylindricalLBProfileObservable.hpp.
Referenced by calculate_sampling_positions(), and Observables::CylindricalLBVelocityProfile::operator()().
The documentation for this class was generated from the following file:
core/observables/CylindricalLBProfileObservable.hpp