ESPResSo: walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA Class Reference
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA Class Reference
#include <StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h>
Public Member Functions
StreamCollideSweepDoublePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s)
~StreamCollideSweepDoublePrecisionLeesEdwardsCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getGrid_size () const
double getOmega_shear () const
double getV_s () const
void setGrid_size (const double value)
void setOmega_shear (const double value)
void setV_s (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepDoublePrecisionLeesEdwardsCUDA()
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double grid_size, double omega_shear, double v_s) inline
Definition at line 59 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
~StreamCollideSweepDoublePrecisionLeesEdwardsCUDA()
walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::~StreamCollideSweepDoublePrecisionLeesEdwardsCUDA () inline
Definition at line 67 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 117 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getGrid_size()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getGrid_size () const inline
Definition at line 120 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getOmega_shear () const inline
Definition at line 121 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsCUDA > & kernel) inline static
Definition at line 85 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 102 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionLeesEdwardsCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 90 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 107 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References runOnCellInterval(), and stream.
getV_s()
double walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::getV_s () const inline
Definition at line 122 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 80 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 114 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 167 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setGrid_size()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::setGrid_size (const double value) inline
Definition at line 123 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::setOmega_shear (const double value) inline
Definition at line 124 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
setV_s()
void walberla::pystencils::StreamCollideSweepDoublePrecisionLeesEdwardsCUDA::setV_s (const double value) inline
Definition at line 125 of file StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.h
StreamCollideSweepDoublePrecisionLeesEdwardsCUDA.cu