ESPResSo: Shapes::Sphere Class Reference
Shapes::Sphere Class Reference
#include <Sphere.hpp>
Public Member Functions
Sphere ()
void calculate_dist (const Utils::Vector3d &pos, double &dist, Utils::Vector3d &vec) const override
Utils::Vector3d & pos ()
double & rad ()
double & direction ()
Public Member Functions inherited from Shapes::Shape
virtual bool is_inside (Utils::Vector3d const &pos) const
Check whether the given point is inside the shape or not.
virtual ~Shape ()=default
Detailed Description
Definition at line 29 of file shapes/include/shapes/Sphere.hpp.
Constructor & Destructor Documentation
Sphere()
Shapes::Sphere::Sphere () inline
Definition at line 31 of file shapes/include/shapes/Sphere.hpp.
Member Function Documentation
calculate_dist()
void Shapes::Sphere::calculate_dist (const Utils::Vector3d & pos, double & dist, Utils::Vector3d & vec) const override virtual
Implements Shapes::Shape.
Definition at line 27 of file Sphere.cpp.
References Utils::Vector< T, N >::norm(), and pos().
direction()
double& Shapes::Sphere::direction () inline
Definition at line 38 of file shapes/include/shapes/Sphere.hpp.
pos()
Utils::Vector3d& Shapes::Sphere::pos () inline
Definition at line 36 of file shapes/include/shapes/Sphere.hpp.
Referenced by calculate_dist().
rad()
double& Shapes::Sphere::rad () inline
Definition at line 37 of file shapes/include/shapes/Sphere.hpp.
The documentation for this class was generated from the following files:
shapes/include/shapes/Sphere.hpp
Sphere.cpp