ESPResSo: walberla::pystencils::UpdateVelFromPDFSinglePrecision Class Reference
walberla::pystencils::UpdateVelFromPDFSinglePrecision Class Reference
#include <UpdateVelFromPDFSinglePrecision.h>
Public Member Functions
UpdateVelFromPDFSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< UpdateVelFromPDFSinglePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFSinglePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file UpdateVelFromPDFSinglePrecision.h.
Constructor & Destructor Documentation
UpdateVelFromPDFSinglePrecision()
walberla::pystencils::UpdateVelFromPDFSinglePrecision::UpdateVelFromPDFSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 55 of file UpdateVelFromPDFSinglePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::UpdateVelFromPDFSinglePrecision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file UpdateVelFromPDFSinglePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecision::getSweep () inline
Definition at line 81 of file UpdateVelFromPDFSinglePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecision::getSweep (const shared_ptr< UpdateVelFromPDFSinglePrecision > & kernel) inline static
Definition at line 68 of file UpdateVelFromPDFSinglePrecision.h.
getSweepOnCellInterval() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file UpdateVelFromPDFSinglePrecision.h.
References runOnCellInterval(), and stream.
getSweepOnCellInterval() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecision::getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFSinglePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file UpdateVelFromPDFSinglePrecision.h.
References stream.
operator()()
void walberla::pystencils::UpdateVelFromPDFSinglePrecision::operator() (IBlock * block) inline
Definition at line 65 of file UpdateVelFromPDFSinglePrecision.h.
References block(), and run().
run()
void walberla::pystencils::UpdateVelFromPDFSinglePrecision::run (IBlock * block)
Definition at line 81 of file UpdateVelFromPDFSinglePrecision.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_01ae0f7ae02292b7985da3bf4f45d4c4::updatevelfrompdfsingleprecision_updatevelfrompdfsingleprecision(), and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::UpdateVelFromPDFSinglePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 120 of file UpdateVelFromPDFSinglePrecision.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_01ae0f7ae02292b7985da3bf4f45d4c4::updatevelfrompdfsingleprecision_updatevelfrompdfsingleprecision(), and velocity().
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
UpdateVelFromPDFSinglePrecision.h
UpdateVelFromPDFSinglePrecision.cpp