ESPResSo: Constraints::ShapeBasedConstraint Class Reference
Constraints::ShapeBasedConstraint Class Reference
#include <ShapeBasedConstraint.hpp>
Public Member Functions
ShapeBasedConstraint ()
void add_energy (const Particle &p, const Utils::Vector3d &folded_pos, double time, Observable_stat &energy) const override
ParticleForce force (const Particle &p, const Utils::Vector3d &folded_pos, double time) override
bool fits_in_box (Utils::Vector3d const &) const override
double min_dist (BoxGeometry const &box_geo, ParticleRange const &particles) const
Calculate the minimum distance between all particle pairs.
void calc_dist (Utils::Vector3d const &pos, double &dist, Utils::Vector3d &vec) const
Calculate distance from the constraint.
void set_shape (std::shared_ptr< Shapes::Shape > const &shape)
Shapes::Shape const & shape () const
void reset_force () override
bool & only_positive ()
bool & penetrable ()
int & type ()
Utils::Vector3d & velocity ()
void set_type (int type)
Utils::Vector3d total_force () const
double total_normal_force () const
void bind_system (std::shared_ptr< System::System const > const &system)
Public Member Functions inherited from Constraints::Constraint
virtual ~Constraint ()=default
Detailed Description
Definition at line 43 of file core/constraints/ShapeBasedConstraint.hpp.
Constructor & Destructor Documentation
ShapeBasedConstraint()
Constraints::ShapeBasedConstraint::ShapeBasedConstraint () inline
Definition at line 45 of file core/constraints/ShapeBasedConstraint.hpp.
Member Function Documentation
add_energy()
void Constraints::ShapeBasedConstraint::add_energy (const Particle & p, const Utils::Vector3d & folded_pos, double time, Observable_stat & energy) const override virtual
Implements Constraints::Constraint.
Definition at line 163 of file ShapeBasedConstraint.cpp.
References calc_non_bonded_pair_energy(), get_ptr(), Particle::id(), Constraints::is_active(), Particle::mol_id(), runtimeErrorMsg, stream, and Particle::type().
bind_system()
void Constraints::ShapeBasedConstraint::bind_system (std::shared_ptr< System::System const > const & system) inline
Definition at line 88 of file core/constraints/ShapeBasedConstraint.hpp.
References stream.
calc_dist()
void Constraints::ShapeBasedConstraint::calc_dist (Utils::Vector3d const & pos, double & dist, Utils::Vector3d & vec) const inline
Calculate distance from the constraint.
Definition at line 63 of file core/constraints/ShapeBasedConstraint.hpp.
References stream.
fits_in_box()
bool Constraints::ShapeBasedConstraint::fits_in_box (Utils::Vector3d const &) const inline override virtual
Implements Constraints::Constraint.
Definition at line 56 of file core/constraints/ShapeBasedConstraint.hpp.
force()
ParticleForce Constraints::ShapeBasedConstraint::force (const Particle & p, const Utils::Vector3d & folded_pos, double time) override virtual
Implements Constraints::Constraint.
Definition at line 89 of file ShapeBasedConstraint.cpp.
References calc_central_radial_force(), calc_non_central_force(), calc_opposing_force(), dpd_pair_force(), get_ptr(), Particle::id(), Constraints::is_active(), Particle::pos(), runtimeErrorMsg, stream, THERMO_DPD, thole_pair_force(), ParticleForce::torque, Particle::type(), and Particle::v().
min_dist()
double Constraints::ShapeBasedConstraint::min_dist (BoxGeometry const & box_geo, ParticleRange const & particles) const
Calculate the minimum distance between all particle pairs.
Definition at line 67 of file ShapeBasedConstraint.cpp.
References stream.
only_positive()
bool & Constraints::ShapeBasedConstraint::only_positive () inline
Definition at line 79 of file core/constraints/ShapeBasedConstraint.hpp.
penetrable()
bool & Constraints::ShapeBasedConstraint::penetrable () inline
Definition at line 80 of file core/constraints/ShapeBasedConstraint.hpp.
reset_force()
void Constraints::ShapeBasedConstraint::reset_force () inline override virtual
Reimplemented from Constraints::Constraint.
Definition at line 74 of file core/constraints/ShapeBasedConstraint.hpp.
set_shape()
void Constraints::ShapeBasedConstraint::set_shape (std::shared_ptr< Shapes::Shape > const & shape) inline
Definition at line 68 of file core/constraints/ShapeBasedConstraint.hpp.
References shape().
set_type()
void Constraints::ShapeBasedConstraint::set_type (int type)
Definition at line 50 of file ShapeBasedConstraint.cpp.
References type(), and Particle::type().
shape()
Shapes::Shape const & Constraints::ShapeBasedConstraint::shape () const inline
Definition at line 72 of file core/constraints/ShapeBasedConstraint.hpp.
Referenced by set_shape().
total_force()
Utils::Vector3d Constraints::ShapeBasedConstraint::total_force () const
Definition at line 59 of file ShapeBasedConstraint.cpp.
References comm_cart, and stream.
total_normal_force()
double Constraints::ShapeBasedConstraint::total_normal_force () const
Definition at line 63 of file ShapeBasedConstraint.cpp.
References comm_cart, and stream.
type()
int & Constraints::ShapeBasedConstraint::type () inline
Definition at line 81 of file core/constraints/ShapeBasedConstraint.hpp.
References Particle::type().
Referenced by set_type().
velocity()
Utils::Vector3d & Constraints::ShapeBasedConstraint::velocity () inline
Definition at line 82 of file core/constraints/ShapeBasedConstraint.hpp.
References Particle::v().
The documentation for this class was generated from the following files:
core/constraints/ShapeBasedConstraint.hpp
ShapeBasedConstraint.cpp