ESPResSo: walberla::lbm::DynamicUBBSinglePrecision Class Reference
walberla::lbm::DynamicUBBSinglePrecision Class Reference
#include <DynamicUBBSinglePrecision.h>
Classes
struct ForceStruct
class ForceVector
struct IndexInfo
class IndexVectors
Public Member Functions
DynamicUBBSinglePrecision (const std::shared_ptr< StructuredBlockForest > &blocks, BlockDataID pdfsID_, std::function< Vector3< float >(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> &velocityCallbackDynamicUBBSinglePrecision)
void run (IBlock *block)
void operator() (IBlock *block)
void inner (IBlock *block)
void outer (IBlock *block)
Vector3< double > getForce (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getInnerSweep ()
std::function< void(IBlock *)> getOuterSweep ()
template<typename FlagField_T >
void fillFromFlagField (const std::shared_ptr< StructuredBlockForest > &blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
template<typename FlagField_T >
void fillFromFlagField (const shared_ptr< StructuredBlockForest > &blocks, IBlock *block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID)
auto const & getForceVector (IBlock const *block) const
auto const & getIndexVector (IBlock const *block) const
BlockDataID getIndexVectorID () const
BlockDataID getForceVectorID () const
Public Attributes
BlockDataID pdfsID
Static Public Attributes
static constexpr std::array< std::array< int, 19u >, 3u > neighborOffset
Detailed Description
Definition at line 73 of file DynamicUBBSinglePrecision.h.
Constructor & Destructor Documentation
DynamicUBBSinglePrecision()
walberla::lbm::DynamicUBBSinglePrecision::DynamicUBBSinglePrecision (const std::shared_ptr< StructuredBlockForest > & blocks, BlockDataID pdfsID_, std::function< Vector3< float >(const Cell &, const shared_ptr< StructuredBlockForest > &, IBlock &)> & velocityCallbackDynamicUBBSinglePrecision) inline
Definition at line 160 of file DynamicUBBSinglePrecision.h.
References stream.
Member Function Documentation
fillFromFlagField() [1/2]
template<typename FlagField_T > void walberla::lbm::DynamicUBBSinglePrecision::fillFromFlagField (const shared_ptr< StructuredBlockForest > & blocks, IBlock * block, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 216 of file DynamicUBBSinglePrecision.h.
References walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::ALL, block(), walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::indexVector(), walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::INNER, inner(), walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::OUTER, and stream.
fillFromFlagField() [2/2]
template<typename FlagField_T > void walberla::lbm::DynamicUBBSinglePrecision::fillFromFlagField (const std::shared_ptr< StructuredBlockForest > & blocks, ConstBlockDataID flagFieldID, FlagUID boundaryFlagUID, FlagUID domainFlagUID) inline
Definition at line 207 of file DynamicUBBSinglePrecision.h.
References block(), and stream.
getForce()
Vector3< double > walberla::lbm::DynamicUBBSinglePrecision::getForce (IBlock * block) inline
Definition at line 187 of file DynamicUBBSinglePrecision.h.
References block(), walberla::lbm::DynamicUBBSinglePrecision::ForceVector::getForce(), and stream.
getForceVector()
auto const & walberla::lbm::DynamicUBBSinglePrecision::getForceVector (IBlock const * block) const inline
Definition at line 661 of file DynamicUBBSinglePrecision.h.
References block(), and walberla::lbm::DynamicUBBSinglePrecision::ForceVector::forceVector().
getForceVectorID()
BlockDataID walberla::lbm::DynamicUBBSinglePrecision::getForceVectorID () const inline
Definition at line 672 of file DynamicUBBSinglePrecision.h.
getIndexVector()
auto const & walberla::lbm::DynamicUBBSinglePrecision::getIndexVector (IBlock const * block) const inline
Definition at line 666 of file DynamicUBBSinglePrecision.h.
References walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::ALL, block(), walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::indexVector(), and stream.
getIndexVectorID()
BlockDataID walberla::lbm::DynamicUBBSinglePrecision::getIndexVectorID () const inline
Definition at line 671 of file DynamicUBBSinglePrecision.h.
getInnerSweep()
std::function< void(IBlock *)> walberla::lbm::DynamicUBBSinglePrecision::getInnerSweep () inline
Definition at line 198 of file DynamicUBBSinglePrecision.h.
References inner().
getOuterSweep()
std::function< void(IBlock *)> walberla::lbm::DynamicUBBSinglePrecision::getOuterSweep () inline
Definition at line 202 of file DynamicUBBSinglePrecision.h.
References outer().
getSweep()
std::function< void(IBlock *)> walberla::lbm::DynamicUBBSinglePrecision::getSweep () inline
Definition at line 194 of file DynamicUBBSinglePrecision.h.
References run().
inner()
void walberla::lbm::DynamicUBBSinglePrecision::inner (IBlock * block)
Definition at line 131 of file DynamicUBBSinglePrecision.cpp.
References block(), and walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::INNER.
Referenced by fillFromFlagField(), and getInnerSweep().
operator()()
void walberla::lbm::DynamicUBBSinglePrecision::operator() (IBlock * block) inline
Definition at line 181 of file DynamicUBBSinglePrecision.h.
References block(), and run().
outer()
void walberla::lbm::DynamicUBBSinglePrecision::outer (IBlock * block)
Definition at line 135 of file DynamicUBBSinglePrecision.cpp.
References block(), and walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::OUTER.
Referenced by getOuterSweep().
run()
void walberla::lbm::DynamicUBBSinglePrecision::run (IBlock * block)
Definition at line 127 of file DynamicUBBSinglePrecision.cpp.
References walberla::lbm::DynamicUBBSinglePrecision::IndexVectors::ALL, and block().
Referenced by getSweep(), and operator()().
Member Data Documentation
neighborOffset
constexpr std::array<std::array<int, 19u>, 3u> walberla::lbm::DynamicUBBSinglePrecision::neighborOffset static constexpr
Initial value:
= {{
      {0, 0, 0, -1, 1, 0, 0, -1, 1, -1, 1, 0, 0, -1, 1, 0, 0, -1, 1},
      {0, 1, -1, 0, 0, 0, 0, 1, 1, -1, -1, 1, -1, 0, 0, 1, -1, 0, 0},
      {0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 1, 1, 1, 1, -1, -1, -1, -1},
  }}
Definition at line 655 of file DynamicUBBSinglePrecision.h.
pdfsID
BlockDataID walberla::lbm::DynamicUBBSinglePrecision::pdfsID
Definition at line 675 of file DynamicUBBSinglePrecision.h.
The documentation for this class was generated from the following files:
DynamicUBBSinglePrecision.h
DynamicUBBSinglePrecision.cpp