ESPResSo: Communication::MpiCallbacks Class Reference
Communication::MpiCallbacks Class Reference
The interface of the MPI callback mechanism.
#include <MpiCallbacks.hpp>
Classes
class CallbackHandle
RAII handle for a callback.
Public Member Functions
MpiCallbacks (MpiCallbacks const &)=delete
MpiCallbacks & operator= (MpiCallbacks const &)=delete
MpiCallbacks (boost::mpi::communicator comm, bool abort_on_exit=true)
~MpiCallbacks ()
template<class... Args>
void add (void(*fp)(Args...))
Add a new callback.
template<class... Args, class... ArgRef>
auto call (void(*fp)(Args...), ArgRef &&... args) const -> std::enable_if_t< std::is_void< decltype(fp(args...))>::value >
Call a callback on worker nodes.
template<class... Args, class... ArgRef>
void call_all (void(*fp)(Args...), ArgRef &&... args) const
Call a callback on all nodes.
template<class Op , class R , class... Args>
auto call (Result::Reduction, Op op, R(*fp)(Args...), Args... args) const -> std::remove_reference_t< decltype(op(std::declval< R >(), std::declval< R >()))>
Call a callback and reduce the result over all nodes.
template<class R , class... Args, class... ArgRef>
auto call (Result::Ignore, R(*fp)(Args...), ArgRef... args) const -> std::remove_reference_t< R >
Call a callback and ignore the result over all nodes.
template<class R , class... Args, class... ArgRef>
auto call (Result::OneRank, boost::optional< R >(*fp)(Args...), ArgRef... args) const -> std::remove_reference_t< R >
Call a callback and reduce the result over all nodes.
template<class R , class... Args, class... ArgRef>
auto call (Result::MainRank, R(*fp)(Args...), ArgRef... args) const -> std::remove_reference_t< R >
Call a callback and return the result of the head node.
void loop () const
Start the MPI loop.
void abort_loop ()
Abort the MPI loop.
const boost::mpi::communicator & comm () const
The boost mpi communicator used by this instance.
Static Public Member Functions
template<class... Args>
static void add_static (void(*fp)(Args...))
Add a new callback.
template<class Tag , class R , class... Args, class... TagArgs>
static void add_static (Tag tag, R(*fp)(Args...), TagArgs &&... tag_args)
Add a new callback with a return value.
Detailed Description
The interface of the MPI callback mechanism.
Definition at line 349 of file MpiCallbacks.hpp.
Constructor & Destructor Documentation
MpiCallbacks() [1/2]
Communication::MpiCallbacks::MpiCallbacks (MpiCallbacks const &) delete
MpiCallbacks() [2/2]
Communication::MpiCallbacks::MpiCallbacks (boost::mpi::communicator comm, bool abort_on_exit = true) inline explicit
Definition at line 421 of file MpiCallbacks.hpp.
~MpiCallbacks()
Communication::MpiCallbacks::~MpiCallbacks () inline
Definition at line 432 of file MpiCallbacks.hpp.
References abort_loop().
Member Function Documentation
abort_loop()
void Communication::MpiCallbacks::abort_loop () inline
Abort the MPI loop.
Make the worker nodes exit the MPI loop.
Definition at line 719 of file MpiCallbacks.hpp.
Referenced by ~MpiCallbacks().
add()
template<class... Args> void Communication::MpiCallbacks::add (void(*)(Args...) fp) inline
Add a new callback.
Add a new callback to the system. This is a collective function that must be run on all nodes.
Parameters
fp Pointer to the static callback function to add.
Definition at line 468 of file MpiCallbacks.hpp.
add_static() [1/2]
template<class Tag , class R , class... Args, class... TagArgs> static void Communication::MpiCallbacks::add_static (Tag tag, R(*)(Args...) fp, TagArgs &&... tag_args) inline static
Add a new callback with a return value.
Add a new callback to the system. This is a collective function that must be run on all nodes. tag is one of the tag types from Communication::Result, which indicates what to do with the return values.
Parameters
tag Tag type indicating return operation
tag_args Argument for the return operation, if any.
fp Pointer to the static callback function to add.
Definition at line 500 of file MpiCallbacks.hpp.
add_static() [2/2]
template<class... Args> static void Communication::MpiCallbacks::add_static (void(*)(Args...) fp) inline static
Add a new callback.
Add a new callback to the system. This is a collective function that must be run on all nodes.
Parameters
fp Pointer to the static callback function to add.
Definition at line 482 of file MpiCallbacks.hpp.
Referenced by Communication::RegisterCallback::RegisterCallback().
call() [1/5]
template<class R , class... Args, class... ArgRef> auto Communication::MpiCallbacks::call (Result::Ignore , R(*)(Args...) fp, ArgRef... args) const -> std::remove_reference_t<R> inline
Call a callback and ignore the result over all nodes.
This calls a callback on all nodes, including the head node, and ignore all return values.
This method can only be called on the head node.
Definition at line 628 of file MpiCallbacks.hpp.
call() [2/5]
template<class R , class... Args, class... ArgRef> auto Communication::MpiCallbacks::call (Result::MainRank , R(*)(Args...) fp, ArgRef... args) const -> std::remove_reference_t<R> inline
Call a callback and return the result of the head node.
This calls a callback on all nodes, including the head node, and returns the value from the head node.
This method can only be called on the head node.
Definition at line 679 of file MpiCallbacks.hpp.
call() [3/5]
template<class R , class... Args, class... ArgRef> auto Communication::MpiCallbacks::call (Result::OneRank , boost::optional< R >(*)(Args...) fp, ArgRef... args) const -> std::remove_reference_t<R> inline
Call a callback and reduce the result over all nodes.
This calls a callback on all nodes, including the head node, and returns the value from the node which returned an engaged optional. Only one node is allowed to return a value.
This method can only be called on the head node.
Definition at line 649 of file MpiCallbacks.hpp.
call() [4/5]
template<class Op , class R , class... Args> auto Communication::MpiCallbacks::call (Result::Reduction , Op op, R(*)(Args...) fp, Args... args) const -> std::remove_reference_t<decltype(op(std::declval<R>(), std::declval<R>()))> inline
Call a callback and reduce the result over all nodes.
This calls a callback on all nodes, including the head node, and does a mpi reduction with the registered operation.
This method can only be called on the head node.
Definition at line 604 of file MpiCallbacks.hpp.
call() [5/5]
template<class... Args, class... ArgRef> auto Communication::MpiCallbacks::call (void(*)(Args...) fp, ArgRef &&... args) const -> std::enable_if_t<std::is_void<decltype(fp(args...))>::value> inline
Call a callback on worker nodes.
The callback is not called on the head node.
This method can only be called on the head node.
Parameters
fp Pointer to the function to call.
args Arguments for the callback.
Definition at line 570 of file MpiCallbacks.hpp.
call_all()
template<class... Args, class... ArgRef> void Communication::MpiCallbacks::call_all (void(*)(Args...) fp, ArgRef &&... args) const inline
Call a callback on all nodes.
This calls a callback on all nodes, including the head node.
This method can only be called on the head node.
Parameters
fp Pointer to the function to call.
args Arguments for the callback.
Definition at line 590 of file MpiCallbacks.hpp.
Referenced by mpi_call_all().
comm()
const boost::mpi::communicator& Communication::MpiCallbacks::comm () const inline
The boost mpi communicator used by this instance.
Definition at line 724 of file MpiCallbacks.hpp.
Referenced by ScriptInterface::ContextManager::ContextManager(), errexit(), and ErrorHandling::init_error_handling().
loop()
void Communication::MpiCallbacks::loop () const inline
Start the MPI loop.
This is the callback loop for the worker nodes. They block on the MPI call and wait for a new callback request coming from the head node. This should be run on the worker nodes and must be running so that the head node can issue call().
Definition at line 697 of file MpiCallbacks.hpp.
Referenced by mpi_loop().
operator=()
MpiCallbacks& Communication::MpiCallbacks::operator= (MpiCallbacks const &) delete
The documentation for this class was generated from the following file:
MpiCallbacks.hpp