ESPResSo: ScriptInterface::Interactions::InteractionSmoothStep Class Reference
ScriptInterface::Interactions::InteractionSmoothStep Class Reference
#include <NonBondedInteraction.hpp>
Public Member Functions
InteractionSmoothStep ()
Public Member Functions inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >
Variant do_call_method (std::string const &name, VariantMap const &params) override
void do_construct (VariantMap const &params) final
void attach (std::weak_ptr< NonBondedInteractionHandle * > si_struct, std::weak_ptr<::IA_parameters > core_struct)
void update_core (bool notify=true)
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
CoreInteraction IA_parameters::* get_ptr_offset () const override
Protected Member Functions inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >
virtual std::string inactive_parameter () const
Which parameter indicates whether the potential is inactive.
virtual double get_inactive_cutoff () const
Which magic value indicates the potential is inactive.
auto make_autoparameter (T CoreInteraction::*ptr, char const *name)
std::set< std::string > get_valid_parameters () const
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Private Member Functions
void make_new_instance (VariantMap const &params) override
Additional Inherited Members
Public Types inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >
using CoreInteraction = ::SmoothStep_Parameters
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >
using BaseClass = AutoParameters< InteractionPotentialInterface< ::SmoothStep_Parameters > >
Protected Attributes inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >
std::shared_ptr< CoreInteraction > m_handle
Managed object.
std::weak_ptr<::IA_parameters > m_core_struct
Handle to the container whose members have to be synchronized.
std::weak_ptr< NonBondedInteractionHandle * > m_si_struct
Handle to the interface used to synchronize data members.
std::weak_ptr< std::function< void()> > m_notify_non_bonded_ia_change
Callback to notify changes to the interaction range.
Detailed Description
Definition at line 685 of file NonBondedInteraction.hpp.
Constructor & Destructor Documentation
InteractionSmoothStep()
ScriptInterface::Interactions::InteractionSmoothStep::InteractionSmoothStep () inline
Definition at line 693 of file NonBondedInteraction.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), SmoothStep_Parameters::cut, SmoothStep_Parameters::d, SmoothStep_Parameters::eps, SmoothStep_Parameters::k0, ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >::make_autoparameter(), SmoothStep_Parameters::n, and SmoothStep_Parameters::sig.
Member Function Documentation
get_ptr_offset()
CoreInteraction IA_parameters::* ScriptInterface::Interactions::InteractionSmoothStep::get_ptr_offset () const inline override protected virtual
Implements ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >.
Definition at line 688 of file NonBondedInteraction.hpp.
References IA_parameters::smooth_step.
make_new_instance()
void ScriptInterface::Interactions::InteractionSmoothStep::make_new_instance (VariantMap const & params) inline override private virtual
Implements ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >.
Definition at line 705 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface<::SmoothStep_Parameters >::m_handle, ScriptInterface::make_shared_from_args(), and stream.
The documentation for this class was generated from the following file:
NonBondedInteraction.hpp