ESPResSo: walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized Class Reference
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized Class Reference
#include <StreamCollideSweepSinglePrecisionThermalized.h>
Public Member Functions
StreamCollideSweepSinglePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepSinglePrecisionThermalized ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionThermalized > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionThermalized > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepSinglePrecisionThermalized.h.
Constructor & Destructor Documentation
StreamCollideSweepSinglePrecisionThermalized()
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::StreamCollideSweepSinglePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file StreamCollideSweepSinglePrecisionThermalized.h.
~StreamCollideSweepSinglePrecisionThermalized()
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::~StreamCollideSweepSinglePrecisionThermalized () inline
Definition at line 67 of file StreamCollideSweepSinglePrecisionThermalized.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 108 of file StreamCollideSweepSinglePrecisionThermalized.h.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getBlock_offset_0 () const inline
Definition at line 117 of file StreamCollideSweepSinglePrecisionThermalized.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getBlock_offset_1 () const inline
Definition at line 118 of file StreamCollideSweepSinglePrecisionThermalized.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getBlock_offset_2 () const inline
Definition at line 119 of file StreamCollideSweepSinglePrecisionThermalized.h.
getKt()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getKt () const inline
Definition at line 120 of file StreamCollideSweepSinglePrecisionThermalized.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getOmega_bulk () const inline
Definition at line 121 of file StreamCollideSweepSinglePrecisionThermalized.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getOmega_even () const inline
Definition at line 122 of file StreamCollideSweepSinglePrecisionThermalized.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getOmega_odd () const inline
Definition at line 123 of file StreamCollideSweepSinglePrecisionThermalized.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getOmega_shear () const inline
Definition at line 124 of file StreamCollideSweepSinglePrecisionThermalized.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getSeed () const inline
Definition at line 125 of file StreamCollideSweepSinglePrecisionThermalized.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getSweep () inline
Definition at line 95 of file StreamCollideSweepSinglePrecisionThermalized.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionThermalized > & kernel) inline static
Definition at line 81 of file StreamCollideSweepSinglePrecisionThermalized.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionThermalized > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 86 of file StreamCollideSweepSinglePrecisionThermalized.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 100 of file StreamCollideSweepSinglePrecisionThermalized.h.
References runOnCellInterval().
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::getTime_step () const inline
Definition at line 126 of file StreamCollideSweepSinglePrecisionThermalized.h.
operator()()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::operator() (IBlock * block) inline
Definition at line 79 of file StreamCollideSweepSinglePrecisionThermalized.h.
References block(), and run().
run()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::run (IBlock * block)
Definition at line 410 of file StreamCollideSweepSinglePrecisionThermalized.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_c9502d2ba75af3ad6bde4be90db2a757::streamcollidesweepsingleprecisionthermalized_streamcollidesweepsingleprecisionthermalized().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 470 of file StreamCollideSweepSinglePrecisionThermalized.cpp.
References block(), RESTRICT, and walberla::pystencils::internal_c9502d2ba75af3ad6bde4be90db2a757::streamcollidesweepsingleprecisionthermalized_streamcollidesweepsingleprecisionthermalized().
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setBlock_offset_0 (const uint32_t value) inline
Definition at line 127 of file StreamCollideSweepSinglePrecisionThermalized.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setBlock_offset_1 (const uint32_t value) inline
Definition at line 130 of file StreamCollideSweepSinglePrecisionThermalized.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setBlock_offset_2 (const uint32_t value) inline
Definition at line 133 of file StreamCollideSweepSinglePrecisionThermalized.h.
setKt()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setKt (const float value) inline
Definition at line 136 of file StreamCollideSweepSinglePrecisionThermalized.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setOmega_bulk (const float value) inline
Definition at line 137 of file StreamCollideSweepSinglePrecisionThermalized.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setOmega_even (const float value) inline
Definition at line 138 of file StreamCollideSweepSinglePrecisionThermalized.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setOmega_odd (const float value) inline
Definition at line 139 of file StreamCollideSweepSinglePrecisionThermalized.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setOmega_shear (const float value) inline
Definition at line 140 of file StreamCollideSweepSinglePrecisionThermalized.h.
setSeed()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setSeed (const uint32_t value) inline
Definition at line 141 of file StreamCollideSweepSinglePrecisionThermalized.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalized::setTime_step (const uint32_t value) inline
Definition at line 142 of file StreamCollideSweepSinglePrecisionThermalized.h.
The documentation for this class was generated from the following files:
StreamCollideSweepSinglePrecisionThermalized.h
StreamCollideSweepSinglePrecisionThermalized.cpp