ESPResSo: ScriptInterface::walberla::LBFluidSlice Class Reference
ScriptInterface::walberla::LBFluidSlice Class Reference
#include <LBFluidSlice.hpp>
Public Member Functions
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &name, VariantMap const &params) override
::LatticeWalberla const & get_lattice () const override
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
virtual std::vector< std::string_view > valid_parameters () const
Get required and optional parameters for class.
virtual bool has_parameter (std::string const &needle) const
virtual Variant get_parameter (std::string const &name) const
Get single parameter.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
virtual void do_set_parameter (const std::string &, const Variant &)
Local implementation of set_parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
virtual std::vector< std::pair< std::string, Variant > > serialize_parameters () const
Serialize parameters.
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >
Variant gather_3d (std::vector< int > const &data_dims, LatticeModel const &lattice_model, std::vector< T >(LatticeModel::*getter)(Utils::Vector3i const &, Utils::Vector3i const &) const, double units_conversion=1.) const
void scatter_3d (Variant const &grid_values, std::vector< int > const &data_dims, LatticeModel &lattice_model, void(LatticeModel::*setter)(Utils::Vector3i const &, Utils::Vector3i const &, std::vector< T > const &), double units_conversion=1.)
Protected Member Functions inherited from ScriptInterface::LatticeIndices
bool is_index_valid (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
void throw_invalid_index (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
Utils::Vector3i get_mapped_index (Utils::Vector3i const &index, Utils::Vector3i const &shape) const
Protected Attributes inherited from ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >
Utils::Vector3i m_slice_lower_corner
Utils::Vector3i m_slice_upper_corner
std::vector< int > m_shape
Detailed Description
Definition at line 101 of file LBFluidSlice.hpp.
Member Function Documentation
do_call_method()
Variant ScriptInterface::walberla::LBFluidSlice::do_call_method (std::string const & name, VariantMap const & params) override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 38 of file LBFluidSlice.cpp.
References ScriptInterface::ObjectHandle::context(), density, do_call_method(), ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::gather_3d(), LBWalberlaBase::get_slice_density(), LBWalberlaBase::get_slice_is_boundary(), LBWalberlaBase::get_slice_last_applied_force(), LBWalberlaBase::get_slice_population(), LBWalberlaBase::get_slice_pressure_tensor(), LBWalberlaBase::get_slice_velocity(), LBWalberlaBase::get_slice_velocity_at_boundary(), ScriptInterface::walberla::lb_throw_if_expired(), ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::m_slice_lower_corner, ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::m_slice_upper_corner, ScriptInterface::ObjectHandle::name(), ScriptInterface::Context::parallel_try_catch(), ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::scatter_3d(), LBWalberlaBase::set_slice_density(), LBWalberlaBase::set_slice_last_applied_force(), LBWalberlaBase::set_slice_population(), LBWalberlaBase::set_slice_velocity(), LBWalberlaBase::set_slice_velocity_at_boundary(), and stream.
Referenced by do_call_method().
do_construct()
void ScriptInterface::walberla::LBFluidSlice::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 113 of file LBFluidSlice.hpp.
References ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::m_shape, ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::m_slice_lower_corner, ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >::m_slice_upper_corner, and stream.
get_lattice()
::LatticeWalberla const & ScriptInterface::walberla::LBFluidSlice::get_lattice () const inline override virtual
Implements ScriptInterface::walberla::LatticeSlice< LBFieldSerializer >.
Definition at line 142 of file LBFluidSlice.hpp.
The documentation for this class was generated from the following files:
LBFluidSlice.hpp
LBFluidSlice.cpp