ESPResSo: InteractionsNonBonded Class Reference
InteractionsNonBonded Class Reference
#include <nonbonded_interaction_data.hpp>
Public Member Functions
InteractionsNonBonded ()
void make_particle_type_exist (int type)
Make sure the interaction parameter list is large enough to cover interactions for this particle type.
auto get_ia_param_key (int i, int j) const
auto & get_ia_param (int i, int j)
Get interaction parameters between particle types i and j.
auto const & get_ia_param (int i, int j) const
auto get_ia_param_ref_counted (int i, int j) const
void set_ia_param (int i, int j, std::shared_ptr< IA_parameters > const &ia)
auto get_max_seen_particle_type () const
void recalc_maximal_cutoffs ()
Recalculate cutoff of each interaction struct.
double maximal_cutoff () const
Get maximal cutoff.
void on_non_bonded_ia_change () const
Notify system that non-bonded interactions changed.
void dpd_init (double kT, double time_step)
Public Member Functions inherited from System::Leaf< InteractionsNonBonded >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< InteractionsNonBonded >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< InteractionsNonBonded >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 352 of file nonbonded_interaction_data.hpp.
Constructor & Destructor Documentation
InteractionsNonBonded()
InteractionsNonBonded::InteractionsNonBonded () inline
Definition at line 373 of file nonbonded_interaction_data.hpp.
References make_particle_type_exist().
Member Function Documentation
dpd_init()
void InteractionsNonBonded::dpd_init (double kT, double time_step)
Definition at line 61 of file dpd.cpp.
References get_ia_param(), get_max_seen_particle_type(), and stream.
get_ia_param() [1/2]
auto & InteractionsNonBonded::get_ia_param (int i, int j) inline
Get interaction parameters between particle types i and j.
This is symmetric, e.g. it holds that get_ia_param(i, j) and get_ia_param(j, i) point to the same data.
Parameters
i First type, must exist
j Second type, must exist
Returns
Reference to interaction parameters for the type pair.
Definition at line 412 of file nonbonded_interaction_data.hpp.
References get_ia_param_key(), and stream.
Referenced by dpd_init(), and ForcesKernel::operator()().
get_ia_param() [2/2]
auto const & InteractionsNonBonded::get_ia_param (int i, int j) const inline
Definition at line 416 of file nonbonded_interaction_data.hpp.
References get_ia_param_key(), and stream.
get_ia_param_key()
auto InteractionsNonBonded::get_ia_param_key (int i, int j) const inline
Definition at line 392 of file nonbonded_interaction_data.hpp.
References Utils::lower_triangular(), and stream.
Referenced by get_ia_param(), get_ia_param(), get_ia_param_ref_counted(), and set_ia_param().
get_ia_param_ref_counted()
auto InteractionsNonBonded::get_ia_param_ref_counted (int i, int j) const inline
Definition at line 420 of file nonbonded_interaction_data.hpp.
References get_ia_param_key(), and stream.
get_max_seen_particle_type()
auto InteractionsNonBonded::get_max_seen_particle_type () const inline
Definition at line 428 of file nonbonded_interaction_data.hpp.
Referenced by dpd_init().
make_particle_type_exist()
void InteractionsNonBonded::make_particle_type_exist (int type) inline
Make sure the interaction parameter list is large enough to cover interactions for this particle type.
New interactions are initialized with values such that no physical interaction occurs.
Definition at line 384 of file nonbonded_interaction_data.hpp.
References stream.
Referenced by InteractionsNonBonded().
maximal_cutoff()
double InteractionsNonBonded::maximal_cutoff () const
Get maximal cutoff.
Definition at line 124 of file nonbonded_interaction_data.cpp.
References inactive_cutoff, and stream.
on_non_bonded_ia_change()
void InteractionsNonBonded::on_non_bonded_ia_change () const
Notify system that non-bonded interactions changed.
Definition at line 132 of file nonbonded_interaction_data.cpp.
References System::Leaf< InteractionsNonBonded >::get_system().
recalc_maximal_cutoffs()
void InteractionsNonBonded::recalc_maximal_cutoffs ()
Recalculate cutoff of each interaction struct.
Definition at line 117 of file nonbonded_interaction_data.cpp.
References System::Leaf< InteractionsNonBonded >::get_system(), recalc_maximal_cutoff(), and stream.
set_ia_param()
void InteractionsNonBonded::set_ia_param (int i, int j, std::shared_ptr< IA_parameters > const & ia) inline
Definition at line 424 of file nonbonded_interaction_data.hpp.
References get_ia_param_key(), and stream.
The documentation for this class was generated from the following files:
nonbonded_interaction_data.hpp
dpd.cpp
nonbonded_interaction_data.cpp