ESPResSo: walberla::PoissonSolver Class Reference
walberla::PoissonSolver Class Reference abstract
#include <PoissonSolver.hpp>
Public Member Functions
PoissonSolver (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
~PoissonSolver () override=default
virtual void reset_charge_field ()=0
virtual void add_charge_to_field (std::size_t id, double valency)=0
virtual std::size_t get_potential_field_id () const noexcept=0
virtual void set_permittivity (double permittivity) noexcept
virtual double get_permittivity () const noexcept
LatticeWalberla const & get_lattice () const noexcept override
virtual void solve ()=0
virtual std::optional< double > get_node_potential (Utils::Vector3i const &node, bool consider_ghosts=false)=0
virtual std::vector< double > get_slice_potential (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
void register_vtk_field_writers (walberla::vtk::VTKOutput &, LatticeModel::units_map const &, int) override
virtual void setup_fft (bool use_gpu_aware)=0
virtual bool is_gpu () const noexcept=0
virtual bool is_double_precision () const noexcept=0
Public Member Functions inherited from LatticeModel
virtual ~LatticeModel ()=default
std::shared_ptr< VTKHandle > create_vtk (int delta_N, int initial_count, int flag_observables, units_map const &units_conversion, std::string const &identifier, std::string const &base_folder, std::string const &prefix, bool force_pvtu)
Create a VTK observable.
void write_vtk (std::string const &vtk_uid)
Write a VTK observable to disk.
void switch_vtk (std::string const &vtk_uid, bool status)
Toggle a VTK observable on/off.
Protected Member Functions
void integrate_vtk_writers () override
void register_vtk_field_filters (walberla::vtk::VTKOutput &) override
Additional Inherited Members
Public Types inherited from LatticeModel
using units_map = std::unordered_map< std::string, double >
Protected Attributes inherited from LatticeModel
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_auto
VTK writers that are executed automatically.
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_manual
VTK writers that are executed manually.
Detailed Description
Definition at line 32 of file PoissonSolver.hpp.
Constructor & Destructor Documentation
PoissonSolver()
walberla::PoissonSolver::PoissonSolver (std::shared_ptr< LatticeWalberla > lattice, double permittivity) inline
Definition at line 38 of file PoissonSolver.hpp.
~PoissonSolver()
walberla::PoissonSolver::~PoissonSolver () override default
Member Function Documentation
add_charge_to_field()
virtual void walberla::PoissonSolver::add_charge_to_field (std::size_t id, double valency) pure virtual
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
get_lattice()
LatticeWalberla const & walberla::PoissonSolver::get_lattice () const inline override virtual noexcept
Implements LatticeModel.
Definition at line 56 of file PoissonSolver.hpp.
Referenced by walberla::PoissonSolverFFT< FloatType, Architecture >::add_charge_to_field(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_node_potential(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_slice_potential(), walberla::PoissonSolverFFT< FloatType, Architecture >::PoissonSolverFFT(), walberla::PoissonSolverNone< FloatType >::PoissonSolverNone(), walberla::PoissonSolverFFT< FloatType, Architecture >::register_vtk_field_writers(), walberla::PoissonSolverFFT< FloatType, Architecture >::reset_charge_field(), walberla::PoissonSolverFFT< FloatType, Architecture >::setup_fft(), and walberla::PoissonSolverFFT< FloatType, Architecture >::solve().
get_node_potential()
virtual std::optional< double > walberla::PoissonSolver::get_node_potential (Utils::Vector3i const & node, bool consider_ghosts = false) pure virtual
Implemented in walberla::PoissonSolverNone< FloatType >, and walberla::PoissonSolverFFT< FloatType, Architecture >.
get_permittivity()
virtual double walberla::PoissonSolver::get_permittivity () const inline virtual noexcept
Definition at line 52 of file PoissonSolver.hpp.
Referenced by walberla::PoissonSolverFFT< FloatType, Architecture >::add_charge_to_field().
get_potential_field_id()
virtual std::size_t walberla::PoissonSolver::get_potential_field_id () const pure virtual noexcept
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
get_slice_potential()
virtual std::vector< double > walberla::PoissonSolver::get_slice_potential (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Implemented in walberla::PoissonSolverNone< FloatType >, and walberla::PoissonSolverFFT< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::EKPoissonSolverSlice::do_call_method().
integrate_vtk_writers()
void walberla::PoissonSolver::integrate_vtk_writers () inline override protected virtual
Implements LatticeModel.
Reimplemented in walberla::PoissonSolverFFT< FloatType, Architecture >.
Definition at line 80 of file PoissonSolver.hpp.
is_double_precision()
virtual bool walberla::PoissonSolver::is_double_precision () const pure virtual noexcept
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
is_gpu()
virtual bool walberla::PoissonSolver::is_gpu () const pure virtual noexcept
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
register_vtk_field_filters()
void walberla::PoissonSolver::register_vtk_field_filters (walberla::vtk::VTKOutput &) inline override protected virtual
Implements LatticeModel.
Definition at line 81 of file PoissonSolver.hpp.
register_vtk_field_writers()
void walberla::PoissonSolver::register_vtk_field_writers (walberla::vtk::VTKOutput & , LatticeModel::units_map const & , int) inline override virtual
Implements LatticeModel.
Reimplemented in walberla::PoissonSolverFFT< FloatType, Architecture >.
Definition at line 70 of file PoissonSolver.hpp.
reset_charge_field()
virtual void walberla::PoissonSolver::reset_charge_field () pure virtual
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
set_permittivity()
virtual void walberla::PoissonSolver::set_permittivity (double permittivity) inline virtual noexcept
Definition at line 48 of file PoissonSolver.hpp.
References stream.
setup_fft()
virtual void walberla::PoissonSolver::setup_fft (bool use_gpu_aware) pure virtual
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
solve()
virtual void walberla::PoissonSolver::solve () pure virtual
Implemented in walberla::PoissonSolverFFT< FloatType, Architecture >, and walberla::PoissonSolverNone< FloatType >.
The documentation for this class was generated from the following file:
PoissonSolver.hpp