ESPResSo: Observables::ParticleDistances Class Reference
Observables::ParticleDistances Class Reference
Calculate distances between particles in a polymer.
#include <ParticleDistances.hpp>
Public Member Functions
ParticleDistances (std::vector< int > ids)
std::vector< double > evaluate (ParticleReferenceRange particles, const ParticleObservables::traits< Particle > &traits) const override
std::vector< std::size_t > shape () const override
PidObservable (std::vector< int > ids)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() () const final
const std::vector< int > & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Detailed Description
Calculate distances between particles in a polymer.
For \(n \) bonded particles, return the \(n-1 \) distances separating them.
Definition at line 38 of file ParticleDistances.hpp.
Constructor & Destructor Documentation
ParticleDistances()
Observables::ParticleDistances::ParticleDistances (std::vector< int > ids) inline explicit
Definition at line 41 of file ParticleDistances.hpp.
References Observables::PidObservable::ids().
Member Function Documentation
evaluate()
std::vector<double> Observables::ParticleDistances::evaluate (ParticleReferenceRange particles, const ParticleObservables::traits< Particle > & traits) const inline override virtual
Implements Observables::PidObservable.
Definition at line 48 of file ParticleDistances.hpp.
References box_geo, BoxGeometry::get_mi_vector(), Observables::Observable::n_values(), Cells::particles(), and res.
PidObservable()
Observables::PidObservable::PidObservable inline explicit
Definition at line 61 of file core/observables/PidObservable.hpp.
shape()
std::vector<std::size_t> Observables::ParticleDistances::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 59 of file ParticleDistances.hpp.
References Observables::PidObservable::ids().
The documentation for this class was generated from the following file:
ParticleDistances.hpp