ESPResSo: walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA Class Reference
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA Class Reference
#include <StreamCollideSweepThermalizedDoublePrecisionCUDA.h>
Public Member Functions
StreamCollideSweepThermalizedDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepThermalizedDoublePrecisionCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepThermalizedDoublePrecisionCUDA()
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::StreamCollideSweepThermalizedDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
~StreamCollideSweepThermalizedDoublePrecisionCUDA()
walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::~StreamCollideSweepThermalizedDoublePrecisionCUDA () inline
Definition at line 67 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 117 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getBlock_offset_0 () const inline
Definition at line 126 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getBlock_offset_1 () const inline
Definition at line 127 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getBlock_offset_2 () const inline
Definition at line 128 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getKt()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getKt () const inline
Definition at line 129 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getOmega_bulk () const inline
Definition at line 130 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getOmega_even () const inline
Definition at line 131 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getOmega_odd () const inline
Definition at line 132 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getOmega_shear () const inline
Definition at line 133 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getSeed () const inline
Definition at line 134 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getSweep (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionCUDA > & kernel) inline static
Definition at line 85 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 102 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedDoublePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 90 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 107 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::getTime_step () const inline
Definition at line 135 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 80 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 417 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 479 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 136 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 139 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 142 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setKt()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setKt (const double value) inline
Definition at line 145 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setOmega_bulk (const double value) inline
Definition at line 146 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setOmega_even (const double value) inline
Definition at line 147 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setOmega_odd (const double value) inline
Definition at line 148 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setOmega_shear (const double value) inline
Definition at line 149 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setSeed()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setSeed (const uint32_t value) inline
Definition at line 150 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepThermalizedDoublePrecisionCUDA::setTime_step (const uint32_t value) inline
Definition at line 151 of file StreamCollideSweepThermalizedDoublePrecisionCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepThermalizedDoublePrecisionCUDA.h
StreamCollideSweepThermalizedDoublePrecisionCUDA.cu