ESPResSo: walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA Class Reference
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA Class Reference
#include <StreamCollideSweepSinglePrecisionThermalizedCUDA.h>
Public Member Functions
StreamCollideSweepSinglePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepSinglePrecisionThermalizedCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepSinglePrecisionThermalizedCUDA()
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::StreamCollideSweepSinglePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 59 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
~StreamCollideSweepSinglePrecisionThermalizedCUDA()
walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::~StreamCollideSweepSinglePrecisionThermalizedCUDA () inline
Definition at line 69 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 119 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getBlock_offset_0 () const inline
Definition at line 128 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getBlock_offset_1 () const inline
Definition at line 129 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getBlock_offset_2 () const inline
Definition at line 130 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getKt()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getKt () const inline
Definition at line 131 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getOmega_bulk () const inline
Definition at line 132 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getOmega_even () const inline
Definition at line 133 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getOmega_odd () const inline
Definition at line 134 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getOmega_shear () const inline
Definition at line 135 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getSeed () const inline
Definition at line 136 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getSweep (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedCUDA > & kernel) inline static
Definition at line 87 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 104 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepSinglePrecisionThermalizedCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 92 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 109 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::getTime_step () const inline
Definition at line 137 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 82 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 401 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 463 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 138 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 141 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 144 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setKt()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setKt (const float value) inline
Definition at line 147 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setOmega_bulk (const float value) inline
Definition at line 148 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setOmega_even (const float value) inline
Definition at line 149 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setOmega_odd (const float value) inline
Definition at line 150 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setOmega_shear (const float value) inline
Definition at line 151 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setSeed()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setSeed (const uint32_t value) inline
Definition at line 152 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepSinglePrecisionThermalizedCUDA::setTime_step (const uint32_t value) inline
Definition at line 153 of file StreamCollideSweepSinglePrecisionThermalizedCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepSinglePrecisionThermalizedCUDA.h
StreamCollideSweepSinglePrecisionThermalizedCUDA.cu