ESPResSo: ScriptInterface::Observables::PairwiseDistances< CoreObs > Class Template Reference
ScriptInterface::Observables::PairwiseDistances< CoreObs > Class Template Reference
#include <PairwiseDistances.hpp>
Public Member Functions
PairwiseDistances ()
void do_construct (VariantMap const &params) override
std::shared_ptr<::Observables::Observable > observable () const override
Public Member Functions inherited from ScriptInterface::AutoParameters< PairwiseDistances< CoreObs >, Observable >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< PairwiseDistances< CoreObs >, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
template<typename CoreObs>
class ScriptInterface::Observables::PairwiseDistances< CoreObs >
Definition at line 34 of file script_interface/observables/PairwiseDistances.hpp.
Constructor & Destructor Documentation
PairwiseDistances()
template<typename CoreObs > ScriptInterface::Observables::PairwiseDistances< CoreObs >::PairwiseDistances () inline
Definition at line 41 of file script_interface/observables/PairwiseDistances.hpp.
References ScriptInterface::AutoParameters< PairwiseDistances< CoreObs >, Observable >::add_parameters(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_construct()
template<typename CoreObs > void ScriptInterface::Observables::PairwiseDistances< CoreObs >::do_construct (VariantMap const & params) inline override
Definition at line 48 of file script_interface/observables/PairwiseDistances.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Context::parallel_try_catch(), and stream.
observable()
template<typename CoreObs > std::shared_ptr<::Observables::Observable > ScriptInterface::Observables::PairwiseDistances< CoreObs >::observable () const inline override
Definition at line 56 of file script_interface/observables/PairwiseDistances.hpp.
The documentation for this class was generated from the following file:
script_interface/observables/PairwiseDistances.hpp