ESPResSo: walberla::pystencils::ReactionKernelBulk_5_double_precision Class Reference
walberla::pystencils::ReactionKernelBulk_5_double_precision Class Reference
#include <ReactionKernelBulk_5_double_precision.h>
Public Member Functions
ReactionKernelBulk_5_double_precision (BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, double order_0, double order_1, double order_2, double order_3, double order_4, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3, double stoech_4)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getOrder_0 () const
double getOrder_1 () const
double getOrder_2 () const
double getOrder_3 () const
double getOrder_4 () const
double getRate_coefficient () const
double getStoech_0 () const
double getStoech_1 () const
double getStoech_2 () const
double getStoech_3 () const
double getStoech_4 () const
void setOrder_0 (const double value)
void setOrder_1 (const double value)
void setOrder_2 (const double value)
void setOrder_3 (const double value)
void setOrder_4 (const double value)
void setRate_coefficient (const double value)
void setStoech_0 (const double value)
void setStoech_1 (const double value)
void setStoech_2 (const double value)
void setStoech_3 (const double value)
void setStoech_4 (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ReactionKernelBulk_5_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_5_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file ReactionKernelBulk_5_double_precision.h.
Constructor & Destructor Documentation
ReactionKernelBulk_5_double_precision()
walberla::pystencils::ReactionKernelBulk_5_double_precision::ReactionKernelBulk_5_double_precision (BlockDataID rho_0ID_, BlockDataID rho_1ID_, BlockDataID rho_2ID_, BlockDataID rho_3ID_, BlockDataID rho_4ID_, double order_0, double order_1, double order_2, double order_3, double order_4, double rate_coefficient, double stoech_0, double stoech_1, double stoech_2, double stoech_3, double stoech_4) inline
Definition at line 55 of file ReactionKernelBulk_5_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 103 of file ReactionKernelBulk_5_double_precision.h.
getOrder_0()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getOrder_0 () const inline
Definition at line 106 of file ReactionKernelBulk_5_double_precision.h.
getOrder_1()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getOrder_1 () const inline
Definition at line 107 of file ReactionKernelBulk_5_double_precision.h.
getOrder_2()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getOrder_2 () const inline
Definition at line 108 of file ReactionKernelBulk_5_double_precision.h.
getOrder_3()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getOrder_3 () const inline
Definition at line 109 of file ReactionKernelBulk_5_double_precision.h.
getOrder_4()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getOrder_4 () const inline
Definition at line 110 of file ReactionKernelBulk_5_double_precision.h.
getRate_coefficient()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getRate_coefficient () const inline
Definition at line 111 of file ReactionKernelBulk_5_double_precision.h.
getStoech_0()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getStoech_0 () const inline
Definition at line 112 of file ReactionKernelBulk_5_double_precision.h.
getStoech_1()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getStoech_1 () const inline
Definition at line 113 of file ReactionKernelBulk_5_double_precision.h.
getStoech_2()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getStoech_2 () const inline
Definition at line 114 of file ReactionKernelBulk_5_double_precision.h.
getStoech_3()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getStoech_3 () const inline
Definition at line 115 of file ReactionKernelBulk_5_double_precision.h.
getStoech_4()
double walberla::pystencils::ReactionKernelBulk_5_double_precision::getStoech_4 () const inline
Definition at line 116 of file ReactionKernelBulk_5_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_double_precision::getSweep () inline
Definition at line 90 of file ReactionKernelBulk_5_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_double_precision::getSweep (const shared_ptr< ReactionKernelBulk_5_double_precision > & kernel) inline static
Definition at line 77 of file ReactionKernelBulk_5_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_double_precision::getSweepOnCellInterval (const shared_ptr< ReactionKernelBulk_5_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 81 of file ReactionKernelBulk_5_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ReactionKernelBulk_5_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 95 of file ReactionKernelBulk_5_double_precision.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::operator() (IBlock * block) inline
Definition at line 74 of file ReactionKernelBulk_5_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::run (IBlock * block)
Definition at line 70 of file ReactionKernelBulk_5_double_precision.cpp.
References block(), walberla::pystencils::internal_5119d69793e3096feaaca816d627c080::reactionkernelbulk_5_double_precision_reactionkernelbulk_5_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 123 of file ReactionKernelBulk_5_double_precision.cpp.
References block(), walberla::pystencils::internal_5119d69793e3096feaaca816d627c080::reactionkernelbulk_5_double_precision_reactionkernelbulk_5_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setOrder_0()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setOrder_0 (const double value) inline
Definition at line 117 of file ReactionKernelBulk_5_double_precision.h.
setOrder_1()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setOrder_1 (const double value) inline
Definition at line 118 of file ReactionKernelBulk_5_double_precision.h.
setOrder_2()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setOrder_2 (const double value) inline
Definition at line 119 of file ReactionKernelBulk_5_double_precision.h.
setOrder_3()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setOrder_3 (const double value) inline
Definition at line 120 of file ReactionKernelBulk_5_double_precision.h.
setOrder_4()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setOrder_4 (const double value) inline
Definition at line 121 of file ReactionKernelBulk_5_double_precision.h.
setRate_coefficient()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setRate_coefficient (const double value) inline
Definition at line 122 of file ReactionKernelBulk_5_double_precision.h.
setStoech_0()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setStoech_0 (const double value) inline
Definition at line 125 of file ReactionKernelBulk_5_double_precision.h.
setStoech_1()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setStoech_1 (const double value) inline
Definition at line 126 of file ReactionKernelBulk_5_double_precision.h.
setStoech_2()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setStoech_2 (const double value) inline
Definition at line 127 of file ReactionKernelBulk_5_double_precision.h.
setStoech_3()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setStoech_3 (const double value) inline
Definition at line 128 of file ReactionKernelBulk_5_double_precision.h.
setStoech_4()
void walberla::pystencils::ReactionKernelBulk_5_double_precision::setStoech_4 (const double value) inline
Definition at line 129 of file ReactionKernelBulk_5_double_precision.h.
The documentation for this class was generated from the following files:
ReactionKernelBulk_5_double_precision.h
ReactionKernelBulk_5_double_precision.cpp