ESPResSo: walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA Class Reference
walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA Class Reference
#include <CollideSweepSinglePrecisionThermalizedCUDA.h>
Public Member Functions
CollideSweepSinglePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepSinglePrecisionThermalizedCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionThermalizedCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
Constructor & Destructor Documentation
CollideSweepSinglePrecisionThermalizedCUDA()
walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::CollideSweepSinglePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 59 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 112 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getBlock_offset_0()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getBlock_offset_0 () const inline
Definition at line 121 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getBlock_offset_1 () const inline
Definition at line 122 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getBlock_offset_2 () const inline
Definition at line 123 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getKt()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getKt () const inline
Definition at line 124 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_bulk()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getOmega_bulk () const inline
Definition at line 125 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_even()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getOmega_even () const inline
Definition at line 126 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_odd()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getOmega_odd () const inline
Definition at line 127 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getOmega_shear()
float walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getOmega_shear () const inline
Definition at line 128 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getSeed()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getSeed () const inline
Definition at line 129 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getSweep (const shared_ptr< CollideSweepSinglePrecisionThermalizedCUDA > & kernel) inline static
Definition at line 81 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 97 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionThermalizedCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 86 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 102 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::getTime_step () const inline
Definition at line 130 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
operator()()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 77 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 403 of file CollideSweepSinglePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 448 of file CollideSweepSinglePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 131 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setBlock_offset_1()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 134 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setBlock_offset_2()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 137 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setKt()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setKt (const float value) inline
Definition at line 140 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_bulk()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setOmega_bulk (const float value) inline
Definition at line 141 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_even()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setOmega_even (const float value) inline
Definition at line 142 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_odd()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setOmega_odd (const float value) inline
Definition at line 143 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setOmega_shear()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setOmega_shear (const float value) inline
Definition at line 144 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setSeed()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setSeed (const uint32_t value) inline
Definition at line 145 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
setTime_step()
void walberla::pystencils::CollideSweepSinglePrecisionThermalizedCUDA::setTime_step (const uint32_t value) inline
Definition at line 146 of file CollideSweepSinglePrecisionThermalizedCUDA.h.
The documentation for this class was generated from the following files:
CollideSweepSinglePrecisionThermalizedCUDA.h
CollideSweepSinglePrecisionThermalizedCUDA.cu