ESPResSo: ScriptInterface::walberla::EKFFT Class Reference
ScriptInterface::walberla::EKFFT Class Reference
#include <EKFFT.hpp>
Public Member Functions
void do_construct (VariantMap const &args) override
EKFFT ()
~EKFFT () override
std::shared_ptr<::walberla::PoissonSolver > get_instance () const noexcept override
Public Member Functions inherited from ScriptInterface::AutoParameters< EKPoissonSolver >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
virtual Variant do_call_method (const std::string &, const VariantMap &)
Local implementation of call_method.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Member Functions inherited from ScriptInterface::AutoParameters< EKPoissonSolver >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 45 of file EKFFT.hpp.
Constructor & Destructor Documentation
EKFFT()
ScriptInterface::walberla::EKFFT::EKFFT () inline
Definition at line 71 of file EKFFT.hpp.
References ScriptInterface::AutoParameters< EKPoissonSolver >::add_parameters(), and ScriptInterface::AutoParameter::read_only.
~EKFFT()
ScriptInterface::walberla::EKFFT::~EKFFT () inline override
Definition at line 87 of file EKFFT.hpp.
Member Function Documentation
do_construct()
void ScriptInterface::walberla::EKFFT::do_construct (VariantMap const & args) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 53 of file EKFFT.hpp.
References Communication::mpiCallbacksHandle(), and walberla::new_ek_poisson_fft().
get_instance()
std::shared_ptr<::walberla::PoissonSolver> ScriptInterface::walberla::EKFFT::get_instance () const inline override virtual noexcept
Implements ScriptInterface::walberla::EKPoissonSolver.
Definition at line 94 of file EKFFT.hpp.
The documentation for this class was generated from the following file:
EKFFT.hpp