ESPResSo: ScriptInterface::Interactions::BondedInteractions Class Reference
ScriptInterface::Interactions::BondedInteractions Class Reference
#include <BondedInteractions.hpp>
Public Types
using key_type = KeyType
using mapped_type = std::shared_ptr< ManagedType >
Public Types inherited from ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >
using Base = ObjectContainer< ObjectMap, ManagedType, BaseType >
using key_type = KeyType
using mapped_type = std::shared_ptr< ManagedType >
using container_type = std::unordered_map< key_type, mapped_type >
Public Member Functions
~BondedInteractions () override
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >
ObjectMap ()
~ObjectMap () override
void insert (key_type const &key, mapped_type const &element)
Add an element to the map.
key_type insert (mapped_type const &element)
Add an element to the map.
void erase (key_type const &key)
Removes all occurrences of an element from the map.
auto const & elements () const
Map elements.
void clear ()
Clear the map.
Private Member Functions
void on_bind_system (::System::System &system) override
key_type insert_in_core (mapped_type const &obj_ptr) override
void insert_in_core (key_type const &key, mapped_type const &obj_ptr) override
void erase_in_core (key_type const &key) final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >
void do_destruct ()
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
void restore_from_checkpoint (VariantMap const &params)
key_type get_key (Variant const &key) const
Detailed Description
Definition at line 47 of file BondedInteractions.hpp.
Member Typedef Documentation
key_type
using ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::key_type = KeyType
Definition at line 57 of file ObjectMap.hpp.
mapped_type
using ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::mapped_type = std::shared_ptr<ManagedType>
Definition at line 58 of file ObjectMap.hpp.
Constructor & Destructor Documentation
~BondedInteractions()
ScriptInterface::Interactions::BondedInteractions::~BondedInteractions () inline override
Definition at line 59 of file BondedInteractions.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_destruct().
Member Function Documentation
do_call_method()
Variant ScriptInterface::Interactions::BondedInteractions::do_call_method (std::string const & name, VariantMap const & params) inline override
Definition at line 93 of file BondedInteractions.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::elements(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::get_key(), and stream.
do_construct()
void ScriptInterface::Interactions::BondedInteractions::do_construct (VariantMap const & params) inline override virtual
Implements ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >.
Definition at line 61 of file BondedInteractions.hpp.
erase_in_core()
void ScriptInterface::Interactions::BondedInteractions::erase_in_core (key_type const & key) inline final private virtual
Implements ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >.
Definition at line 90 of file BondedInteractions.hpp.
References stream.
insert_in_core() [1/2]
void ScriptInterface::Interactions::BondedInteractions::insert_in_core (key_type const & key, mapped_type const & obj_ptr) inline override private virtual
Implements ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >.
Definition at line 84 of file BondedInteractions.hpp.
References stream.
insert_in_core() [2/2]
key_type ScriptInterface::Interactions::BondedInteractions::insert_in_core (mapped_type const & obj_ptr) inline override private virtual
Implements ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >.
Definition at line 77 of file BondedInteractions.hpp.
References stream.
on_bind_system()
void ScriptInterface::Interactions::BondedInteractions::on_bind_system (::System::System & system) inline override private
Definition at line 67 of file BondedInteractions.hpp.
References ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::restore_from_checkpoint(), and stream.
The documentation for this class was generated from the following file:
BondedInteractions.hpp