ESPResSo: walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX Class Reference
walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX Class Reference
#include <UpdateVelFromPDFSinglePrecisionAVX.h>
Public Member Functions
UpdateVelFromPDFSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< UpdateVelFromPDFSinglePrecisionAVX > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFSinglePrecisionAVX > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file UpdateVelFromPDFSinglePrecisionAVX.h.
Constructor & Destructor Documentation
UpdateVelFromPDFSinglePrecisionAVX()
walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::UpdateVelFromPDFSinglePrecisionAVX (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 55 of file UpdateVelFromPDFSinglePrecisionAVX.h.
Member Function Documentation
configure()
void walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file UpdateVelFromPDFSinglePrecisionAVX.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::getSweep () inline
Definition at line 81 of file UpdateVelFromPDFSinglePrecisionAVX.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::getSweep (const shared_ptr< UpdateVelFromPDFSinglePrecisionAVX > & kernel) inline static
Definition at line 68 of file UpdateVelFromPDFSinglePrecisionAVX.h.
getSweepOnCellInterval() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file UpdateVelFromPDFSinglePrecisionAVX.h.
References runOnCellInterval(), and stream.
getSweepOnCellInterval() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFSinglePrecisionAVX > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file UpdateVelFromPDFSinglePrecisionAVX.h.
References stream.
operator()()
void walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::operator() (IBlock * block) inline
Definition at line 65 of file UpdateVelFromPDFSinglePrecisionAVX.h.
References block(), and run().
run()
void walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::run (IBlock * block)
Definition at line 101 of file UpdateVelFromPDFSinglePrecisionAVX.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_9f3cf46adc24d4ebfb8e08168d5e7562::updatevelfrompdfsingleprecisionavx_updatevelfrompdfsingleprecisionavx(), and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 143 of file UpdateVelFromPDFSinglePrecisionAVX.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_9f3cf46adc24d4ebfb8e08168d5e7562::updatevelfrompdfsingleprecisionavx_updatevelfrompdfsingleprecisionavx(), and velocity().
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
UpdateVelFromPDFSinglePrecisionAVX.h
UpdateVelFromPDFSinglePrecisionAVX.cpp