ESPResSo: walberla::pystencils::AdvectiveFluxKernel_single_precision Class Reference
walberla::pystencils::AdvectiveFluxKernel_single_precision Class Reference
#include <AdvectiveFluxKernel_single_precision.h>
Public Member Functions
AdvectiveFluxKernel_single_precision (BlockDataID jID_, BlockDataID rhoID_, BlockDataID uID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< AdvectiveFluxKernel_single_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< AdvectiveFluxKernel_single_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file AdvectiveFluxKernel_single_precision.h.
Constructor & Destructor Documentation
AdvectiveFluxKernel_single_precision()
walberla::pystencils::AdvectiveFluxKernel_single_precision::AdvectiveFluxKernel_single_precision (BlockDataID jID_, BlockDataID rhoID_, BlockDataID uID_) inline
Definition at line 55 of file AdvectiveFluxKernel_single_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::AdvectiveFluxKernel_single_precision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file AdvectiveFluxKernel_single_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision::getSweep () inline
Definition at line 81 of file AdvectiveFluxKernel_single_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision::getSweep (const shared_ptr< AdvectiveFluxKernel_single_precision > & kernel) inline static
Definition at line 68 of file AdvectiveFluxKernel_single_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision::getSweepOnCellInterval (const shared_ptr< AdvectiveFluxKernel_single_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file AdvectiveFluxKernel_single_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file AdvectiveFluxKernel_single_precision.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::AdvectiveFluxKernel_single_precision::operator() (IBlock * block) inline
Definition at line 65 of file AdvectiveFluxKernel_single_precision.h.
References block(), and run().
run()
void walberla::pystencils::AdvectiveFluxKernel_single_precision::run (IBlock * block)
Definition at line 98 of file AdvectiveFluxKernel_single_precision.cpp.
References walberla::pystencils::internal_47df4b171f276b8c3a55fc08d45e245e::advectivefluxkernel_single_precision_advectivefluxkernel_single_precision(), block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::AdvectiveFluxKernel_single_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 130 of file AdvectiveFluxKernel_single_precision.cpp.
References walberla::pystencils::internal_47df4b171f276b8c3a55fc08d45e245e::advectivefluxkernel_single_precision_advectivefluxkernel_single_precision(), block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
AdvectiveFluxKernel_single_precision.h
AdvectiveFluxKernel_single_precision.cpp