ESPResSo: ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA > Class Template Reference
ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA > Class Template Reference abstract
#include <NonBondedInteraction.hpp>
Public Types
using CoreInteraction = CoreIA
Public Member Functions
Variant do_call_method (std::string const &name, VariantMap const &params) override
void do_construct (VariantMap const &params) final
void copy_si_to_core ()
void copy_core_to_si ()
Public Member Functions inherited from ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Types
using BaseClass = AutoParameters< InteractionPotentialInterface< CoreIA > >
Protected Member Functions
virtual CoreInteraction IA_parameters::* get_ptr_offset () const =0
Pointer to the corresponding member in a handle.
virtual void make_new_instance (VariantMap const &params)=0
Create a new instance using the constructor with range checks.
virtual std::string inactive_parameter () const
Which parameter indicates whether the potential is inactive.
virtual double inactive_cutoff () const
Which magic value indicates the potential is inactive.
template<typename T >
auto make_autoparameter (T CoreInteraction::*ptr, char const *name)
Protected Member Functions inherited from ScriptInterface::AutoParameters< InteractionPotentialInterface< CoreIA > >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes
std::shared_ptr< CoreInteraction > m_ia_si
Managed object.
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
template<class CoreIA>
class ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >
Definition at line 50 of file NonBondedInteraction.hpp.
Member Typedef Documentation
BaseClass
template<class CoreIA > using ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::BaseClass = AutoParameters<InteractionPotentialInterface<CoreIA> > protected
Definition at line 59 of file NonBondedInteraction.hpp.
CoreInteraction
template<class CoreIA > using ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::CoreInteraction = CoreIA
Definition at line 56 of file NonBondedInteraction.hpp.
Member Function Documentation
copy_core_to_si()
template<class CoreIA > void ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_core_to_si () inline
Definition at line 167 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::get_ptr_offset(), System::get_system(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::m_ia_si, and System::System::nonbonded_ias.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct().
copy_si_to_core()
template<class CoreIA > void ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_si_to_core () inline
Definition at line 161 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::get_ptr_offset(), System::get_system(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::m_ia_si, and System::System::nonbonded_ias.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method().
do_call_method()
template<class CoreIA > Variant ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method (std::string const & name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 97 of file NonBondedInteraction.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_si_to_core(), System::get_system(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::m_ia_si, ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::make_new_instance(), ScriptInterface::ObjectHandle::name(), System::System::on_non_bonded_ia_change(), ScriptInterface::Context::parallel_try_catch(), and params.
Referenced by ScriptInterface::Interactions::InteractionWCA::do_call_method(), ScriptInterface::Interactions::InteractionLJcos2::do_call_method(), ScriptInterface::Interactions::InteractionTabulated::do_call_method(), and ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct().
do_construct()
template<class CoreIA > void ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct (VariantMap const & params) inline final virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 143 of file NonBondedInteraction.hpp.
References Utils::abs(), ScriptInterface::ObjectHandle::context(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_core_to_si(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::inactive_cutoff(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::inactive_parameter(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::m_ia_si, ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::make_new_instance(), ScriptInterface::Context::parallel_try_catch(), and params.
get_ptr_offset()
template<class CoreIA > virtual CoreInteraction IA_parameters::* ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::get_ptr_offset () const protected pure virtual
Pointer to the corresponding member in a handle.
Implemented in ScriptInterface::Interactions::InteractionSmoothStep, ScriptInterface::Interactions::InteractionThole, ScriptInterface::Interactions::InteractionDPD, ScriptInterface::Interactions::InteractionTabulated, ScriptInterface::Interactions::InteractionGayBerne, ScriptInterface::Interactions::InteractionHat, ScriptInterface::Interactions::InteractionSoftSphere, ScriptInterface::Interactions::InteractionBuckingham, ScriptInterface::Interactions::InteractionMorse, ScriptInterface::Interactions::InteractionBMHTF, ScriptInterface::Interactions::InteractionGaussian, ScriptInterface::Interactions::InteractionHertzian, ScriptInterface::Interactions::InteractionLJcos2, ScriptInterface::Interactions::InteractionLJcos, ScriptInterface::Interactions::InteractionLJGen, ScriptInterface::Interactions::InteractionLJ, and ScriptInterface::Interactions::InteractionWCA.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_core_to_si(), and ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_si_to_core().
inactive_cutoff()
template<class CoreIA > virtual double ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::inactive_cutoff () const inline protected virtual
Which magic value indicates the potential is inactive.
Definition at line 72 of file NonBondedInteraction.hpp.
References INACTIVE_CUTOFF.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct().
inactive_parameter()
template<class CoreIA > virtual std::string ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::inactive_parameter () const inline protected virtual
Which parameter indicates whether the potential is inactive.
Definition at line 70 of file NonBondedInteraction.hpp.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct().
make_autoparameter()
template<class CoreIA > template<typename T > auto ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::make_autoparameter (T CoreInteraction::* ptr, char const * name) inline protected
Definition at line 75 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::m_ia_si, ScriptInterface::ObjectHandle::name(), and ScriptInterface::AutoParameter::read_only.
make_new_instance()
template<class CoreIA > virtual void ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::make_new_instance (VariantMap const & params) protected pure virtual
Create a new instance using the constructor with range checks.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), and ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct().
Member Data Documentation
m_ia_si
template<class CoreIA > std::shared_ptr<CoreInteraction> ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::m_ia_si protected
Managed object.
Definition at line 64 of file NonBondedInteraction.hpp.
Referenced by ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_core_to_si(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_si_to_core(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct(), and ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::make_autoparameter().
The documentation for this class was generated from the following file:
NonBondedInteraction.hpp