ESPResSo: Utils::Accumulator Class Reference
Utils::Accumulator Class Reference
#include <Accumulator.hpp>
Public Member Functions
Accumulator (std::size_t N)
void operator() (const std::vector< double > &)
std::vector< double > mean () const
Compute the sample mean.
std::vector< double > variance () const
Compute the Bessel-corrected sample variance, assuming uncorrelated data.
std::vector< double > std_error () const
Compute the standard error of the mean, assuming uncorrelated data.
Friends
class boost::serialization::access
Detailed Description
Definition at line 48 of file Accumulator.hpp.
Constructor & Destructor Documentation
Accumulator()
Utils::Accumulator::Accumulator (std::size_t N) inline explicit
Definition at line 50 of file Accumulator.hpp.
Member Function Documentation
mean()
std::vector< double > Utils::Accumulator::mean () const inline
Compute the sample mean.
Definition at line 94 of file Accumulator.hpp.
References stream.
Referenced by Accumulators::MeanVarianceCalculator::mean().
operator()()
void Utils::Accumulator::operator() (const std::vector< double > & data) inline
Definition at line 68 of file Accumulator.hpp.
std_error()
std::vector< double > Utils::Accumulator::std_error () const inline
Compute the standard error of the mean, assuming uncorrelated data.
Definition at line 123 of file Accumulator.hpp.
References stream.
Referenced by Accumulators::MeanVarianceCalculator::std_error().
variance()
std::vector< double > Utils::Accumulator::variance () const inline
Compute the Bessel-corrected sample variance, assuming uncorrelated data.
Definition at line 105 of file Accumulator.hpp.
References stream.
Referenced by Accumulators::MeanVarianceCalculator::variance().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Definition at line 60 of file Accumulator.hpp.
The documentation for this class was generated from the following file:
Accumulator.hpp