ESPResSo: ScriptInterface::Coulomb::CoulombMMM1DGpu Class Reference
ScriptInterface::Coulomb::CoulombMMM1DGpu Class Reference
#include <CoulombMMM1DGpu.hpp>
Public Member Functions
CoulombMMM1DGpu ()
void do_construct (VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >
Actor ()
Variant do_call_method (std::string const &name, VariantMap const &params) override
std::shared_ptr< CoreActorClass > actor ()
std::shared_ptr< CoreActorClass const > actor () const
Public Member Functions inherited from ScriptInterface::AutoParameters< Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu > >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
virtual Utils::Span< const boost::string_ref > valid_parameters () const
Get required and optional parameters for class.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >
using SIActorClass = CoulombMMM1DGpu
using CoreActorClass = ::CoulombMMM1DGpu
Protected Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >
void set_charge_neutrality_tolerance (VariantMap const &params)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu > >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
Protected Attributes inherited from ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >
std::shared_ptr< CoreActorClass > m_actor
Detailed Description
Definition at line 39 of file CoulombMMM1DGpu.hpp.
Constructor & Destructor Documentation
CoulombMMM1DGpu()
ScriptInterface::Coulomb::CoulombMMM1DGpu::CoulombMMM1DGpu () inline
Definition at line 42 of file CoulombMMM1DGpu.hpp.
References ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >::actor(), ScriptInterface::AutoParameters< Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu > >::add_parameters(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_construct()
void ScriptInterface::Coulomb::CoulombMMM1DGpu::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 55 of file CoulombMMM1DGpu.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >::m_actor, ScriptInterface::Context::parallel_try_catch(), params, and ScriptInterface::Coulomb::Actor< CoulombMMM1DGpu, ::CoulombMMM1DGpu >::set_charge_neutrality_tolerance().
The documentation for this class was generated from the following file:
CoulombMMM1DGpu.hpp