ESPResSo: Utils::Counter< T > Class Template Reference
Utils::Counter< T > Class Template Reference
#include <Counter.hpp>
Public Member Functions
Counter (T initial_value=T(0)) noexcept
Counter (T initial_value, T value) noexcept
void increment ()
T value () const
T initial_value () const
Friends
class boost::serialization::access
Detailed Description
template<typename T>
class Utils::Counter< T >
Definition at line 25 of file Counter.hpp.
Constructor & Destructor Documentation
Counter() [1/2]
template<typename T > Utils::Counter< T >::Counter (T initial_value = T(0)) inline explicit noexcept
Definition at line 36 of file Counter.hpp.
Counter() [2/2]
template<typename T > Utils::Counter< T >::Counter (T initial_value, T value) inline noexcept
Definition at line 38 of file Counter.hpp.
Member Function Documentation
increment()
template<typename T > void Utils::Counter< T >::increment () inline
Definition at line 41 of file Counter.hpp.
Referenced by ek_integrate(), lb_lbcoupling_propagate(), lb_lbfluid_propagate(), and BaseThermostat::rng_initialize().
initial_value()
template<typename T > T Utils::Counter< T >::initial_value () const inline
Definition at line 44 of file Counter.hpp.
value()
template<typename T > T Utils::Counter< T >::value () const inline
Definition at line 43 of file Counter.hpp.
Referenced by ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), lb_calc_particle_lattice_ia_gpu(), lb_coupling_get_rng_state_cpu(), lb_coupling_get_rng_state_gpu(), lb_fluid_get_rng_state_gpu(), lb_integrate_GPU(), lb_lbcoupling_calc_particle_lattice_ia(), and BaseThermostat::rng_increment().
Friends And Related Function Documentation
boost::serialization::access
template<typename T > friend class boost::serialization::access friend
Definition at line 29 of file Counter.hpp.
The documentation for this class was generated from the following file:
Counter.hpp