ESPResSo: EK::EKReactions< EKReaction > Class Template Reference
EK::EKReactions< EKReaction > Class Template Reference
#include <EKReactions.hpp>
Public Types
using value_type = container_type::value_type
using iterator = container_type::iterator
using const_iterator = container_type::const_iterator
Public Member Functions
bool contains (std::shared_ptr< EKReaction > const &ek_reaction) const noexcept
void add (std::shared_ptr< EKReaction > const &ek_reaction)
void remove (std::shared_ptr< EKReaction > const &ek_reaction)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
Detailed Description
template<class EKReaction>
class EK::EKReactions< EKReaction >
Definition at line 29 of file core/ek/EKReactions.hpp.
Member Typedef Documentation
const_iterator
template<class EKReaction > using EK::EKReactions< EKReaction >::const_iterator = container_type::const_iterator
Definition at line 35 of file core/ek/EKReactions.hpp.
iterator
template<class EKReaction > using EK::EKReactions< EKReaction >::iterator = container_type::iterator
Definition at line 34 of file core/ek/EKReactions.hpp.
value_type
template<class EKReaction > using EK::EKReactions< EKReaction >::value_type = container_type::value_type
Definition at line 33 of file core/ek/EKReactions.hpp.
Member Function Documentation
add()
template<class EKReaction > void EK::EKReactions< EKReaction >::add (std::shared_ptr< EKReaction > const & ek_reaction) inline
Definition at line 44 of file core/ek/EKReactions.hpp.
References EK::EKReactions< EKReaction >::contains(), and stream.
begin() [1/2]
template<class EKReaction > iterator EK::EKReactions< EKReaction >::begin () inline
Definition at line 53 of file core/ek/EKReactions.hpp.
begin() [2/2]
template<class EKReaction > const_iterator EK::EKReactions< EKReaction >::begin () const inline
Definition at line 55 of file core/ek/EKReactions.hpp.
contains()
template<class EKReaction > bool EK::EKReactions< EKReaction >::contains (std::shared_ptr< EKReaction > const & ek_reaction) const inline noexcept
Definition at line 41 of file core/ek/EKReactions.hpp.
References EK::EKReactions< EKReaction >::end(), and stream.
Referenced by EK::EKReactions< EKReaction >::add(), and EK::EKReactions< EKReaction >::remove().
empty()
template<class EKReaction > bool EK::EKReactions< EKReaction >::empty () const inline
Definition at line 57 of file core/ek/EKReactions.hpp.
end() [1/2]
template<class EKReaction > iterator EK::EKReactions< EKReaction >::end () inline
Definition at line 54 of file core/ek/EKReactions.hpp.
Referenced by EK::EKReactions< EKReaction >::contains().
end() [2/2]
template<class EKReaction > const_iterator EK::EKReactions< EKReaction >::end () const inline
Definition at line 56 of file core/ek/EKReactions.hpp.
remove()
template<class EKReaction > void EK::EKReactions< EKReaction >::remove (std::shared_ptr< EKReaction > const & ek_reaction) inline
Definition at line 48 of file core/ek/EKReactions.hpp.
References EK::EKReactions< EKReaction >::contains(), and stream.
The documentation for this class was generated from the following file:
core/ek/EKReactions.hpp