ESPResSo: ScriptInterface::LocalContext Class Reference
ScriptInterface::LocalContext Class Reference
Trivial context.
#include <LocalContext.hpp>
Public Member Functions
LocalContext (Utils::Factory< ObjectHandle > factory, boost::mpi::communicator const &comm)
const Utils::Factory< ObjectHandle > & factory () const
void notify_call_method (const ObjectHandle *, std::string const &, VariantMap const &) override
void notify_set_parameter (const ObjectHandle *, std::string const &, Variant const &) override
std::shared_ptr< ObjectHandle > make_shared (std::string const &name, const VariantMap &parameters) override
std::string_view name (const ObjectHandle *o) const override
bool is_head_node () const override
void parallel_try_catch (std::function< void()> const &cb) const override
boost::mpi::communicator const & get_comm () const override
Public Member Functions inherited from ScriptInterface::Context
virtual ~Context ()=default
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::Context
void set_context (ObjectHandle *o)
Set the context of an object to this.
Detailed Description
Trivial context.
This context just maintains a local copy of an object.
Definition at line 44 of file LocalContext.hpp.
Constructor & Destructor Documentation
LocalContext()
ScriptInterface::LocalContext::LocalContext (Utils::Factory< ObjectHandle > factory, boost::mpi::communicator const & comm) inline
Definition at line 51 of file LocalContext.hpp.
Member Function Documentation
factory()
const Utils::Factory< ObjectHandle > & ScriptInterface::LocalContext::factory () const inline
Definition at line 58 of file LocalContext.hpp.
Referenced by name().
get_comm()
boost::mpi::communicator const & ScriptInterface::LocalContext::get_comm () const inline override virtual
Implements ScriptInterface::Context.
Definition at line 85 of file LocalContext.hpp.
is_head_node()
bool ScriptInterface::LocalContext::is_head_node () const inline override virtual
Implements ScriptInterface::Context.
Definition at line 81 of file LocalContext.hpp.
make_shared()
std::shared_ptr< ObjectHandle > ScriptInterface::LocalContext::make_shared (std::string const & name, const VariantMap & parameters) inline override virtual
Implements ScriptInterface::Context.
Definition at line 66 of file LocalContext.hpp.
References Utils::Factory< Base >::make(), name(), ScriptInterface::Context::set_context(), and stream.
name()
std::string_view ScriptInterface::LocalContext::name (const ObjectHandle * o) const inline override virtual
Implements ScriptInterface::Context.
Definition at line 75 of file LocalContext.hpp.
References factory(), and stream.
Referenced by make_shared().
notify_call_method()
void ScriptInterface::LocalContext::notify_call_method (const ObjectHandle * , std::string const & , VariantMap const &) inline override virtual
Implements ScriptInterface::Context.
Definition at line 60 of file LocalContext.hpp.
notify_set_parameter()
void ScriptInterface::LocalContext::notify_set_parameter (const ObjectHandle * , std::string const & , Variant const &) inline override virtual
Implements ScriptInterface::Context.
Definition at line 62 of file LocalContext.hpp.
parallel_try_catch()
void ScriptInterface::LocalContext::parallel_try_catch (std::function< void()> const & cb) const inline override virtual
Implements ScriptInterface::Context.
Definition at line 82 of file LocalContext.hpp.
References ScriptInterface::ParallelExceptionHandler::parallel_try_catch(), and stream.
The documentation for this class was generated from the following file:
LocalContext.hpp