ESPResSo: walberla::pystencils::DiffusiveFluxKernel_double_precision Class Reference
walberla::pystencils::DiffusiveFluxKernel_double_precision Class Reference
#include <DiffusiveFluxKernel_double_precision.h>
Public Member Functions
DiffusiveFluxKernel_double_precision (BlockDataID jID_, BlockDataID rhoID_, double D)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getD () const
void setD (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernel_double_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernel_double_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file DiffusiveFluxKernel_double_precision.h.
Constructor & Destructor Documentation
DiffusiveFluxKernel_double_precision()
walberla::pystencils::DiffusiveFluxKernel_double_precision::DiffusiveFluxKernel_double_precision (BlockDataID jID_, BlockDataID rhoID_, double D) inline
Definition at line 55 of file DiffusiveFluxKernel_double_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernel_double_precision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file DiffusiveFluxKernel_double_precision.h.
getD()
double walberla::pystencils::DiffusiveFluxKernel_double_precision::getD () const inline
Definition at line 97 of file DiffusiveFluxKernel_double_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision::getSweep () inline
Definition at line 81 of file DiffusiveFluxKernel_double_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision::getSweep (const shared_ptr< DiffusiveFluxKernel_double_precision > & kernel) inline static
Definition at line 68 of file DiffusiveFluxKernel_double_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernel_double_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file DiffusiveFluxKernel_double_precision.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernel_double_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file DiffusiveFluxKernel_double_precision.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::DiffusiveFluxKernel_double_precision::operator() (IBlock * block) inline
Definition at line 65 of file DiffusiveFluxKernel_double_precision.h.
References block(), and run().
run()
void walberla::pystencils::DiffusiveFluxKernel_double_precision::run (IBlock * block)
Definition at line 98 of file DiffusiveFluxKernel_double_precision.cpp.
References block(), walberla::pystencils::internal_e5e04d1215f19faa51f3c55db6d456a2::diffusivefluxkernel_double_precision_diffusivefluxkernel_double_precision(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernel_double_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 124 of file DiffusiveFluxKernel_double_precision.cpp.
References block(), walberla::pystencils::internal_e5e04d1215f19faa51f3c55db6d456a2::diffusivefluxkernel_double_precision_diffusivefluxkernel_double_precision(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setD()
void walberla::pystencils::DiffusiveFluxKernel_double_precision::setD (const double value) inline
Definition at line 98 of file DiffusiveFluxKernel_double_precision.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernel_double_precision.h
DiffusiveFluxKernel_double_precision.cpp