ESPResSo: CollisionDetection Class Reference
CollisionDetection Class Reference
#include <collision.hpp>
Public Member Functions
CollisionDetection ()
void initialize ()
Validates parameters and creates particle types if needed.
auto cutoff () const
void handle_collisions (CellStructure &cell_structure)
Handle queued collisions.
void clear_queue ()
void detect_collision (Particle const &p1, Particle const &p2, double const dist_sq)
Detect (and queue) a collision between the given particles.
bool glue_to_surface_criterion (Particle const &p1, Particle const &p2) const
Check additional criteria for the glue_to_surface collision mode.
Public Member Functions inherited from System::Leaf< CollisionDetection >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
CollisionModeType mode
collision protocol
double distance
distance at which particles are bound
double distance_sq
int bond_centers
bond type used between centers of colliding particles
int bond_vs
bond type used between virtual sites
int vs_particle_type
particle type for virtual sites created on collision
double dist_glued_part_to_vs
For mode "glue to surface": The distance from the particle which is to be glued to the new virtual site.
int part_type_to_be_glued
For mode "glue to surface": The particle type being glued.
int part_type_to_attach_vs_to
For mode "glue to surface": The particle type to which the virtual site is attached.
int part_type_after_glueing
Particle type to which the newly glued particle is converted.
double vs_placement
Placement of virtual sites for MODE_VS.
std::vector< CollisionPair > local_collision_queue
During force calculation, colliding particles are recorded in the queue. The queue is processed after force calculation, when it is safe to add particles.
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< CollisionDetection >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< CollisionDetection >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 53 of file collision.hpp.
Constructor & Destructor Documentation
CollisionDetection()
CollisionDetection::CollisionDetection () inline
Definition at line 55 of file collision.hpp.
Member Function Documentation
clear_queue()
void CollisionDetection::clear_queue () inline
Definition at line 103 of file collision.hpp.
References local_collision_queue.
Referenced by handle_collisions().
cutoff()
auto CollisionDetection::cutoff () const inline
Definition at line 93 of file collision.hpp.
References distance, INACTIVE_CUTOFF, mode, and OFF.
detect_collision()
void CollisionDetection::detect_collision (Particle const & p1, Particle const & p2, double const dist_sq) inline
Detect (and queue) a collision between the given particles.
Definition at line 106 of file collision.hpp.
References bond_centers, Particle::bonds(), distance_sq, GLUE_TO_SURF, glue_to_surface_criterion(), Particle::id(), Particle::is_ghost(), Particle::is_virtual(), local_collision_queue, mode, and pair_bond_exists_on().
glue_to_surface_criterion()
bool CollisionDetection::glue_to_surface_criterion (Particle const & p1, Particle const & p2) const inline
Check additional criteria for the glue_to_surface collision mode.
Definition at line 145 of file collision.hpp.
References part_type_to_attach_vs_to, part_type_to_be_glued, and Particle::type().
Referenced by detect_collision().
handle_collisions()
void CollisionDetection::handle_collisions (CellStructure & cell_structure)
Handle queued collisions.
Definition at line 283 of file collision.cpp.
References Utils::Mpi::all_compare(), bind_at_poc_create_bond_between_vs(), bind_at_point_of_collision_calc_vs_pos(), BIND_VS, bond_centers, Particle::bonds(), clear_queue(), comm_cart, Cells::DATA_PART_BONDS, Cells::DATA_PART_PROPERTIES, gather_collision_queue(), CellStructure::get_local_particle(), CellStructure::get_max_local_particle_id(), System::Leaf< CollisionDetection >::get_system(), GLUE_TO_SURF, glue_to_surface_bind_part_to_vs(), glue_to_surface_calc_vs_pos(), Particle::id(), Particle::is_ghost(), local_collision_queue, mode, OFF, part_type_after_glueing, part_type_to_be_glued, place_vs_and_relate_to_particle(), Cells::RESORT_GLOBAL, Particle::set_can_rotate_all_axes(), CellStructure::set_resort_particles(), Particle::type(), and CellStructure::update_ghosts_and_resort_particle().
initialize()
void CollisionDetection::initialize ()
Validates parameters and creates particle types if needed.
Definition at line 78 of file collision.cpp.
References BIND_CENTERS, BIND_VS, bond_centers, bond_vs, distance, distance_sq, System::Leaf< CollisionDetection >::get_system(), GLUE_TO_SURF, mode, number_of_partners(), OFF, part_type_after_glueing, part_type_to_attach_vs_to, part_type_to_be_glued, Utils::sqr(), and vs_particle_type.
Referenced by ScriptInterface::initialize().
Member Data Documentation
bond_centers
int CollisionDetection::bond_centers
bond type used between centers of colliding particles
Definition at line 67 of file collision.hpp.
Referenced by detect_collision(), handle_collisions(), and initialize().
bond_vs
int CollisionDetection::bond_vs
bond type used between virtual sites
Definition at line 69 of file collision.hpp.
Referenced by bind_at_poc_create_bond_between_vs(), glue_to_surface_bind_part_to_vs(), and initialize().
dist_glued_part_to_vs
double CollisionDetection::dist_glued_part_to_vs
For mode "glue to surface": The distance from the particle which is to be glued to the new virtual site.
Definition at line 75 of file collision.hpp.
Referenced by glue_to_surface_calc_vs_pos().
distance
double CollisionDetection::distance
distance at which particles are bound
Definition at line 62 of file collision.hpp.
Referenced by cutoff(), and initialize().
distance_sq
double CollisionDetection::distance_sq
Definition at line 64 of file collision.hpp.
Referenced by detect_collision(), and initialize().
local_collision_queue
std::vector<CollisionPair> CollisionDetection::local_collision_queue
During force calculation, colliding particles are recorded in the queue. The queue is processed after force calculation, when it is safe to add particles.
Definition at line 142 of file collision.hpp.
Referenced by clear_queue(), detect_collision(), and handle_collisions().
mode
CollisionModeType CollisionDetection::mode
collision protocol
Definition at line 60 of file collision.hpp.
Referenced by cutoff(), detect_collision(), handle_collisions(), and initialize().
part_type_after_glueing
int CollisionDetection::part_type_after_glueing
Particle type to which the newly glued particle is converted.
Definition at line 82 of file collision.hpp.
Referenced by glue_to_surface_bind_part_to_vs(), handle_collisions(), and initialize().
part_type_to_attach_vs_to
int CollisionDetection::part_type_to_attach_vs_to
For mode "glue to surface": The particle type to which the virtual site is attached.
Definition at line 80 of file collision.hpp.
Referenced by glue_to_surface_calc_vs_pos(), glue_to_surface_criterion(), and initialize().
part_type_to_be_glued
int CollisionDetection::part_type_to_be_glued
For mode "glue to surface": The particle type being glued.
Definition at line 77 of file collision.hpp.
Referenced by glue_to_surface_calc_vs_pos(), glue_to_surface_criterion(), handle_collisions(), and initialize().
vs_particle_type
int CollisionDetection::vs_particle_type
particle type for virtual sites created on collision
Definition at line 71 of file collision.hpp.
Referenced by initialize(), and place_vs_and_relate_to_particle().
vs_placement
double CollisionDetection::vs_placement
Placement of virtual sites for MODE_VS.
0=on same particle as related to, 1=on collision partner, 0.5=in the middle between
Definition at line 88 of file collision.hpp.
Referenced by bind_at_point_of_collision_calc_vs_pos().
The documentation for this class was generated from the following files:
collision.hpp
collision.cpp