ESPResSo: ScriptInterface::Coulomb::CoulombP3M Class Reference
ScriptInterface::Coulomb::CoulombP3M Class Reference
#include <CoulombP3M.hpp>
Public Types
using Base = Actor< CoulombP3M, ::CoulombP3M >
Public Member Functions
CoulombP3M ()
void do_construct (VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >
Variant do_call_method (std::string const &name, VariantMap const &params) override
std::shared_ptr< CoreActorClass > actor ()
std::shared_ptr< CoreActorClass const > actor () const
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >
using SIActorClass = CoulombP3M
using CoreActorClass = ::CoulombP3M
using ObjectClass = Actor< CoulombP3M, ::CoulombP3M >
Protected Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >
void on_bind_system (::System::System &) override
void set_charge_neutrality_tolerance (VariantMap const &params)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes inherited from ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >
std::shared_ptr< CoreActorClass > m_actor
Detailed Description
Definition at line 43 of file CoulombP3M.hpp.
Member Typedef Documentation
Base
using ScriptInterface::Coulomb::CoulombP3M::Base = Actor<CoulombP3M, ::CoulombP3M>
Definition at line 48 of file CoulombP3M.hpp.
Constructor & Destructor Documentation
CoulombP3M()
ScriptInterface::Coulomb::CoulombP3M::CoulombP3M () inline
Definition at line 58 of file CoulombP3M.hpp.
References ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >::actor(), ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), TuningParameters::limits, ScriptInterface::AutoParameter::read_only, stream, TuningParameters::timings, and TuningParameters::verbose.
Member Function Documentation
do_construct()
void ScriptInterface::Coulomb::CoulombP3M::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 108 of file CoulombP3M.hpp.
References ScriptInterface::CodeInfo::check_features(), ScriptInterface::ObjectHandle::context(), CPU, CUDA, ScriptInterface::get_value_or(), ScriptInterface::is_none(), ScriptInterface::is_type(), TuningParameters::limits, ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >::m_actor, new_coulomb_p3m_heffte(), ScriptInterface::Context::parallel_try_catch(), ScriptInterface::Coulomb::Actor< CoulombP3M, ::CoulombP3M >::set_charge_neutrality_tolerance(), stream, TuningParameters::timings, and TuningParameters::verbose.
The documentation for this class was generated from the following file:
CoulombP3M.hpp