ESPResSo: Shapes::Rhomboid Class Reference
Shapes::Rhomboid Class Reference
#include <Rhomboid.hpp>
Public Member Functions
Rhomboid ()
void calculate_dist (const Utils::Vector3d &pos, double &dist, Utils::Vector3d &vec) const override
Utils::Vector3d & pos ()
Utils::Vector3d & a ()
Utils::Vector3d & b ()
Utils::Vector3d & c ()
double & direction ()
Public Member Functions inherited from Shapes::Shape
virtual bool is_inside (Utils::Vector3d const &pos) const
Check whether the given point is inside the shape or not.
std::vector< int > rasterize (Utils::Vector3i const &grid_size, double grid_spacing, double grid_offset) const
Rasterize a shape on a regular grid.
virtual ~Shape ()=default
Detailed Description
Definition at line 29 of file shapes/include/shapes/Rhomboid.hpp.
Constructor & Destructor Documentation
Rhomboid()
Shapes::Rhomboid::Rhomboid () inline
Definition at line 31 of file shapes/include/shapes/Rhomboid.hpp.
Member Function Documentation
a()
Utils::Vector3d& Shapes::Rhomboid::a () inline
Definition at line 39 of file shapes/include/shapes/Rhomboid.hpp.
Referenced by calculate_dist().
b()
Utils::Vector3d& Shapes::Rhomboid::b () inline
Definition at line 40 of file shapes/include/shapes/Rhomboid.hpp.
Referenced by calculate_dist().
c()
Utils::Vector3d& Shapes::Rhomboid::c () inline
Definition at line 41 of file shapes/include/shapes/Rhomboid.hpp.
Referenced by calculate_dist().
calculate_dist()
void Shapes::Rhomboid::calculate_dist (const Utils::Vector3d & pos, double & dist, Utils::Vector3d & vec) const override virtual
Implements Shapes::Shape.
Definition at line 29 of file Rhomboid.cpp.
References a(), Utils::abs(), b(), c(), Utils::Vector< T, N >::norm(), pos(), and vector_product().
direction()
double& Shapes::Rhomboid::direction () inline
Definition at line 42 of file shapes/include/shapes/Rhomboid.hpp.
pos()
Utils::Vector3d& Shapes::Rhomboid::pos () inline
Definition at line 38 of file shapes/include/shapes/Rhomboid.hpp.
Referenced by calculate_dist().
The documentation for this class was generated from the following files:
shapes/include/shapes/Rhomboid.hpp
Rhomboid.cpp