ESPResSo: walberla::pystencils::StreamSweepSinglePrecisionCUDA Class Reference
walberla::pystencils::StreamSweepSinglePrecisionCUDA Class Reference
#include <StreamSweepSinglePrecisionCUDA.h>
Public Member Functions
StreamSweepSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
~StreamSweepSinglePrecisionCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamSweepSinglePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamSweepSinglePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file StreamSweepSinglePrecisionCUDA.h.
Constructor & Destructor Documentation
StreamSweepSinglePrecisionCUDA()
walberla::pystencils::StreamSweepSinglePrecisionCUDA::StreamSweepSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 59 of file StreamSweepSinglePrecisionCUDA.h.
~StreamSweepSinglePrecisionCUDA()
walberla::pystencils::StreamSweepSinglePrecisionCUDA::~StreamSweepSinglePrecisionCUDA () inline
Definition at line 63 of file StreamSweepSinglePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamSweepSinglePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 111 of file StreamSweepSinglePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionCUDA::getSweep (const shared_ptr< StreamSweepSinglePrecisionCUDA > & kernel) inline static
Definition at line 81 of file StreamSweepSinglePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 96 of file StreamSweepSinglePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamSweepSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StreamSweepSinglePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 85 of file StreamSweepSinglePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 101 of file StreamSweepSinglePrecisionCUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::StreamSweepSinglePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 76 of file StreamSweepSinglePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamSweepSinglePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 109 of file StreamSweepSinglePrecisionCUDA.cu.
References block(), RESTRICT, stream, and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamSweepSinglePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 167 of file StreamSweepSinglePrecisionCUDA.cu.
References block(), RESTRICT, stream, and velocity().
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
StreamSweepSinglePrecisionCUDA.h
StreamSweepSinglePrecisionCUDA.cu