ESPResSo: walberla::pystencils::StreamSweepDoublePrecision Class Reference
walberla::pystencils::StreamSweepDoublePrecision Class Reference
#include <StreamSweepDoublePrecision.h>
Public Member Functions
StreamSweepDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
~StreamSweepDoublePrecision ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamSweepDoublePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamSweepDoublePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID forceID
BlockDataID pdfsID
BlockDataID velocityID
Detailed Description
Definition at line 52 of file StreamSweepDoublePrecision.h.
Constructor & Destructor Documentation
StreamSweepDoublePrecision()
walberla::pystencils::StreamSweepDoublePrecision::StreamSweepDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 54 of file StreamSweepDoublePrecision.h.
~StreamSweepDoublePrecision()
walberla::pystencils::StreamSweepDoublePrecision::~StreamSweepDoublePrecision () inline
Definition at line 58 of file StreamSweepDoublePrecision.h.
Member Function Documentation
getSweep() [1/2]
std::function<void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecision::getSweep () inline
Definition at line 87 of file StreamSweepDoublePrecision.h.
References run().
getSweep() [2/2]
static std::function<void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecision::getSweep (const shared_ptr< StreamSweepDoublePrecision > & kernel) inline static
Definition at line 73 of file StreamSweepDoublePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function<void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecision::getSweepOnCellInterval (const shared_ptr< StreamSweepDoublePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 78 of file StreamSweepDoublePrecision.h.
getSweepOnCellInterval() [2/2]
std::function<void(IBlock *)> walberla::pystencils::StreamSweepDoublePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 92 of file StreamSweepDoublePrecision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::StreamSweepDoublePrecision::operator() (IBlock * block) inline
Definition at line 70 of file StreamSweepDoublePrecision.h.
References block(), and run().
run()
void walberla::pystencils::StreamSweepDoublePrecision::run (IBlock * block)
Definition at line 199 of file StreamSweepDoublePrecision.cpp.
References block(), force, RESTRICT, walberla::pystencils::internal_streamsweepdoubleprecision_streamsweepdoubleprecision::streamsweepdoubleprecision_streamsweepdoubleprecision(), and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamSweepDoublePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 256 of file StreamSweepDoublePrecision.cpp.
References block(), force, RESTRICT, walberla::pystencils::internal_streamsweepdoubleprecision_streamsweepdoubleprecision::streamsweepdoubleprecision_streamsweepdoubleprecision(), and velocity().
Referenced by getSweepOnCellInterval().
Member Data Documentation
forceID
BlockDataID walberla::pystencils::StreamSweepDoublePrecision::forceID
Definition at line 100 of file StreamSweepDoublePrecision.h.
pdfsID
BlockDataID walberla::pystencils::StreamSweepDoublePrecision::pdfsID
Definition at line 101 of file StreamSweepDoublePrecision.h.
velocityID
BlockDataID walberla::pystencils::StreamSweepDoublePrecision::velocityID
Definition at line 102 of file StreamSweepDoublePrecision.h.
The documentation for this class was generated from the following files:
StreamSweepDoublePrecision.h
StreamSweepDoublePrecision.cpp