ESPResSo: walberla::FFT_CUDA< FloatType > Class Template Reference
walberla::FFT_CUDA< FloatType > Class Template Reference
Classes
struct heffte_container
Public Member Functions
FFT_CUDA (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
~FFT_CUDA ()=default
void reset_charge_field ()
void add_charge_to_field (std::size_t id, double valency, bool is_double_precision)
std::size_t get_potential_field_id () const noexcept
void solve ()
void set_permittivity (double permittivity) noexcept
double get_permittivity () const noexcept
auto const & get_lattice () const noexcept
Detailed Description
template<typename FloatType>
class walberla::FFT_CUDA< FloatType >
Definition at line 44 of file FFT_CUDA.cuh.
Constructor & Destructor Documentation
FFT_CUDA()
template<typename FloatType > walberla::FFT_CUDA< FloatType >::FFT_CUDA (std::shared_ptr< LatticeWalberla > lattice, double permittivity)
Definition at line 127 of file FFT_CUDA.cu.
References block(), walberla::FFT_CUDA< FloatType >::get_lattice(), potential, walberla::FFT_CUDA< FloatType >::reset_charge_field(), and walberla::to_array().
~FFT_CUDA()
template<typename FloatType > walberla::FFT_CUDA< FloatType >::~FFT_CUDA () default
Member Function Documentation
add_charge_to_field()
template<typename FloatType > void walberla::FFT_CUDA< FloatType >::add_charge_to_field (std::size_t id, double valency, bool is_double_precision)
Definition at line 226 of file FFT_CUDA.cu.
References block().
get_lattice()
template<typename FloatType > auto const & walberla::FFT_CUDA< FloatType >::get_lattice () const inline noexcept
Definition at line 101 of file FFT_CUDA.cuh.
Referenced by walberla::FFT_CUDA< FloatType >::FFT_CUDA().
get_permittivity()
template<typename FloatType > double walberla::FFT_CUDA< FloatType >::get_permittivity () const inline noexcept
Definition at line 97 of file FFT_CUDA.cuh.
get_potential_field_id()
template<typename FloatType > std::size_t walberla::FFT_CUDA< FloatType >::get_potential_field_id () const inline noexcept
Definition at line 87 of file FFT_CUDA.cuh.
reset_charge_field()
template<typename FloatType > void walberla::FFT_CUDA< FloatType >::reset_charge_field ()
Definition at line 204 of file FFT_CUDA.cu.
References block(), and walberla::ek::accessor::Scalar::initialize().
Referenced by walberla::FFT_CUDA< FloatType >::FFT_CUDA().
set_permittivity()
template<typename FloatType > void walberla::FFT_CUDA< FloatType >::set_permittivity (double permittivity) inline noexcept
Definition at line 93 of file FFT_CUDA.cuh.
solve()
template<typename FloatType > void walberla::FFT_CUDA< FloatType >::solve ()
Definition at line 240 of file FFT_CUDA.cu.
References block(), and potential.
The documentation for this class was generated from the following files:
PoissonSolverCuFFT.hpp
FFT_CUDA.cuh
FFT_CUDA.cu