ESPResSo: ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs > Class Template Reference
ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs > Class Template Reference
#include <CylindricalPidProfileObservable.hpp>
Public Member Functions
CylindricalPidProfileObservable ()
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
std::shared_ptr<::Observables::Observable > observable () const override
virtual std::shared_ptr<::Observables::CylindricalPidProfileObservable > cylindrical_pid_profile_observable () const
Public Member Functions inherited from ScriptInterface::AutoParameters< CylindricalPidProfileObservable< CoreObs >, Observable >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< CylindricalPidProfileObservable< CoreObs >, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
template<typename CoreObs>
class ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >
Definition at line 45 of file script_interface/observables/CylindricalPidProfileObservable.hpp.
Constructor & Destructor Documentation
CylindricalPidProfileObservable()
template<typename CoreObs > ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::CylindricalPidProfileObservable () inline
Definition at line 55 of file script_interface/observables/CylindricalPidProfileObservable.hpp.
References ScriptInterface::AutoParameters< CylindricalPidProfileObservable< CoreObs >, Observable >::add_parameters(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::cylindrical_pid_profile_observable(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
cylindrical_pid_profile_observable()
template<typename CoreObs > virtual std::shared_ptr<::Observables::CylindricalPidProfileObservable > ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::cylindrical_pid_profile_observable () const inline virtual
Definition at line 139 of file script_interface/observables/CylindricalPidProfileObservable.hpp.
Referenced by ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::CylindricalPidProfileObservable(), and ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_call_method().
do_call_method()
template<typename CoreObs > Variant ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_call_method (std::string const & method, VariantMap const & parameters) inline override
Definition at line 123 of file script_interface/observables/CylindricalPidProfileObservable.hpp.
References ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::cylindrical_pid_profile_observable(), and stream.
do_construct()
template<typename CoreObs > void ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct (VariantMap const & params) inline override
Definition at line 102 of file script_interface/observables/CylindricalPidProfileObservable.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::get_value(), ScriptInterface::Context::parallel_try_catch(), ScriptInterface::set_from_args(), and stream.
observable()
template<typename CoreObs > std::shared_ptr<::Observables::Observable > ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::observable () const inline override
Definition at line 134 of file script_interface/observables/CylindricalPidProfileObservable.hpp.
The documentation for this class was generated from the following file:
script_interface/observables/CylindricalPidProfileObservable.hpp