ESPResSo: LeesEdwards::UpdateOffset Class Reference
LeesEdwards::UpdateOffset Class Reference
#include <lees_edwards.hpp>
Public Member Functions
UpdateOffset (BoxGeometry const &box, double time_step)
void operator() (Particle &p) const
Protected Attributes
const LeesEdwardsBC & m_le
const double m_half_time_step
Detailed Description
Definition at line 30 of file lees_edwards.hpp.
Constructor & Destructor Documentation
UpdateOffset()
LeesEdwards::UpdateOffset::UpdateOffset (BoxGeometry const & box, double time_step) inline
Definition at line 36 of file lees_edwards.hpp.
References BoxGeometry::lees_edwards_bc().
Member Function Documentation
operator()()
void LeesEdwards::UpdateOffset::operator() (Particle & p) const inline
Definition at line 39 of file lees_edwards.hpp.
References Particle::image_box(), Particle::lees_edwards_offset(), m_half_time_step, m_le, LeesEdwardsBC::shear_plane_normal, and LeesEdwardsBC::shear_velocity.
Referenced by LeesEdwards::Push::operator()().
Member Data Documentation
m_half_time_step
const double LeesEdwards::UpdateOffset::m_half_time_step protected
Definition at line 33 of file lees_edwards.hpp.
Referenced by operator()().
m_le
const LeesEdwardsBC& LeesEdwards::UpdateOffset::m_le protected
Definition at line 32 of file lees_edwards.hpp.
Referenced by operator()(), and LeesEdwards::Push::operator()().
The documentation for this class was generated from the following file:
lees_edwards.hpp