ESPResSo: ScriptInterface::Interactions::InteractionWCA Class Reference
ScriptInterface::Interactions::InteractionWCA Class Reference
#include <NonBondedInteraction.hpp>
Public Member Functions
InteractionWCA ()
Variant do_call_method (std::string const &name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >
Variant do_call_method (std::string const &name, VariantMap const &params) override
void do_construct (VariantMap const &params) final
void copy_si_to_core ()
void copy_core_to_si ()
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
Utils::Span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Protected Member Functions
CoreInteraction IA_parameters::* get_ptr_offset () const override
Protected Member Functions inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >
auto make_autoparameter (T CoreInteraction::*ptr, char const *name)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Additional Inherited Members
Public Types inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >
using CoreInteraction = ::WCA_Parameters
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >
using BaseClass = AutoParameters< InteractionPotentialInterface< ::WCA_Parameters > >
Protected Attributes inherited from ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >
std::shared_ptr< CoreInteraction > m_ia_si
Managed object.
Detailed Description
Definition at line 175 of file NonBondedInteraction.hpp.
Constructor & Destructor Documentation
InteractionWCA()
ScriptInterface::Interactions::InteractionWCA::InteractionWCA () inline
Definition at line 182 of file NonBondedInteraction.hpp.
References ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), WCA_Parameters::eps, ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >::make_autoparameter(), and WCA_Parameters::sig.
Member Function Documentation
do_call_method()
Variant ScriptInterface::Interactions::InteractionWCA::do_call_method (std::string const & name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 199 of file NonBondedInteraction.hpp.
References ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >::m_ia_si, ScriptInterface::ObjectHandle::name(), and params.
get_ptr_offset()
CoreInteraction IA_parameters::* ScriptInterface::Interactions::InteractionWCA::get_ptr_offset () const inline override protected virtual
Implements ScriptInterface::Interactions::InteractionPotentialInterface<::WCA_Parameters >.
Definition at line 177 of file NonBondedInteraction.hpp.
References IA_parameters::wca.
The documentation for this class was generated from the following file:
NonBondedInteraction.hpp