ESPResSo: walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA Class Reference
walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA Class Reference
#include <DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h>
Public Member Functions
DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, double kT, double z)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getD () const
double getF_ext_0 () const
double getF_ext_1 () const
double getF_ext_2 () const
double getKt () const
double getZ () const
void setD (const double value)
void setF_ext_0 (const double value)
void setF_ext_1 (const double value)
void setF_ext_2 (const double value)
void setKt (const double value)
void setZ (const double value)
void setPhiID (BlockDataID phiID_)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA()
walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA (BlockDataID jID_, BlockDataID phiID_, BlockDataID rhoID_, double D, double f_ext_0, double f_ext_1, double f_ext_2, double kT, double z) inline
Definition at line 57 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 107 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getD()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getD () const inline
Definition at line 110 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getF_ext_0()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getF_ext_0 () const inline
Definition at line 111 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getF_ext_1()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getF_ext_1 () const inline
Definition at line 112 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getF_ext_2()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getF_ext_2 () const inline
Definition at line 113 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getKt()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getKt () const inline
Definition at line 114 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getSweep (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA > & kernel) inline static
Definition at line 74 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 92 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 80 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 97 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
References runOnCellInterval(), and stream.
getZ()
double walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::getZ () const inline
Definition at line 115 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 70 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 97 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 140 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setD()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setD (const double value) inline
Definition at line 116 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
setF_ext_0()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setF_ext_0 (const double value) inline
Definition at line 117 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
setF_ext_1()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setF_ext_1 (const double value) inline
Definition at line 118 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
setF_ext_2()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setF_ext_2 (const double value) inline
Definition at line 119 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
setKt()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setKt (const double value) inline
Definition at line 120 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
setPhiID()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setPhiID (BlockDataID phiID_) inline
Definition at line 128 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
References stream.
setZ()
void walberla::pystencils::DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA::setZ (const double value) inline
Definition at line 121 of file DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.h
DiffusiveFluxKernelWithElectrostatic_double_precision_CUDA.cu