ESPResSo: Shapes::SimplePore Class Reference
Shapes::SimplePore Class Reference
#include <SimplePore.hpp>
Public Member Functions
SimplePore ()
double radius () const
void set_radius (double const &radius)
double length () const
void set_length (double const &length)
double smoothing_radius () const
void set_smoothing_radius (double const &smoothing_radius)
Utils::Vector3d const & axis () const
void set_axis (Utils::Vector3d const &axis)
Utils::Vector3d & center ()
void calculate_dist (const Utils::Vector3d &pos, double &dist, Utils::Vector3d &vec) const override
Public Member Functions inherited from Shapes::Shape
virtual bool is_inside (Utils::Vector3d const &pos) const
Check whether the given point is inside the shape or not.
std::vector< int > rasterize (Utils::Vector3i const &grid_size, double grid_spacing, double grid_offset) const
Rasterize a shape on a regular grid.
virtual ~Shape ()=default
Detailed Description
Definition at line 29 of file shapes/include/shapes/SimplePore.hpp.
Constructor & Destructor Documentation
SimplePore()
Shapes::SimplePore::SimplePore () inline
Definition at line 71 of file shapes/include/shapes/SimplePore.hpp.
Member Function Documentation
axis()
Utils::Vector3d const & Shapes::SimplePore::axis () const inline
Definition at line 91 of file shapes/include/shapes/SimplePore.hpp.
Referenced by set_axis().
calculate_dist()
void Shapes::SimplePore::calculate_dist (const Utils::Vector3d & pos, double & dist, Utils::Vector3d & vec) const override virtual
Implements Shapes::Shape.
Definition at line 81 of file SimplePore.cpp.
References Utils::Vector< T, N >::norm(), Utils::sqr(), and stream.
center()
Utils::Vector3d & Shapes::SimplePore::center () inline
Definition at line 97 of file shapes/include/shapes/SimplePore.hpp.
length()
double Shapes::SimplePore::length () const inline
Definition at line 79 of file shapes/include/shapes/SimplePore.hpp.
Referenced by set_length().
radius()
double Shapes::SimplePore::radius () const inline
Definition at line 73 of file shapes/include/shapes/SimplePore.hpp.
Referenced by set_radius().
set_axis()
void Shapes::SimplePore::set_axis (Utils::Vector3d const & axis) inline
Definition at line 92 of file shapes/include/shapes/SimplePore.hpp.
References axis().
set_length()
void Shapes::SimplePore::set_length (double const & length) inline
Definition at line 80 of file shapes/include/shapes/SimplePore.hpp.
References length().
set_radius()
void Shapes::SimplePore::set_radius (double const & radius) inline
Definition at line 74 of file shapes/include/shapes/SimplePore.hpp.
References radius().
set_smoothing_radius()
void Shapes::SimplePore::set_smoothing_radius (double const & smoothing_radius) inline
Definition at line 86 of file shapes/include/shapes/SimplePore.hpp.
References smoothing_radius().
smoothing_radius()
double Shapes::SimplePore::smoothing_radius () const inline
Definition at line 85 of file shapes/include/shapes/SimplePore.hpp.
Referenced by set_smoothing_radius().
The documentation for this class was generated from the following files:
shapes/include/shapes/SimplePore.hpp
SimplePore.cpp