ESPResSo: cuda_fatal_error Class Reference
cuda_fatal_error Class Reference
Fatal CUDA exception.
#include <utils.hpp>
Public Member Functions
cuda_fatal_error (std::string msg)
~cuda_fatal_error ()
auto get_terminate () noexcept
auto set_terminate (std::terminate_handler callback) noexcept
void terminate () noexcept
char const * what () const noexcept
Detailed Description
Fatal CUDA exception.
Best course of action is to terminate the program immediately.
Definition at line 45 of file core/cuda/utils.hpp.
Constructor & Destructor Documentation
cuda_fatal_error()
cuda_fatal_error::cuda_fatal_error (std::string msg) explicit
Definition at line 82 of file common_cuda.cu.
~cuda_fatal_error()
cuda_fatal_error::~cuda_fatal_error () inline
Definition at line 52 of file core/cuda/utils.hpp.
References terminate().
Member Function Documentation
get_terminate()
auto cuda_fatal_error::get_terminate () inline noexcept
Definition at line 54 of file core/cuda/utils.hpp.
set_terminate()
auto cuda_fatal_error::set_terminate (std::terminate_handler callback) inline noexcept
Definition at line 56 of file core/cuda/utils.hpp.
References stream.
terminate()
void cuda_fatal_error::terminate () noexcept
Definition at line 85 of file common_cuda.cu.
References errexit(), stream, and what().
Referenced by ~cuda_fatal_error().
what()
char const * cuda_fatal_error::what () const inline noexcept
Definition at line 64 of file core/cuda/utils.hpp.
Referenced by terminate().
The documentation for this class was generated from the following files:
core/cuda/utils.hpp
common_cuda.cu