ESPResSo: walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA Class Reference
walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA Class Reference
#include <InitialPDFsSetterDoublePrecisionCUDA.h>
Public Member Functions
InitialPDFsSetterDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, double rho_0)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
double getRho_0 () const
void setRho_0 (const double value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< InitialPDFsSetterDoublePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterDoublePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file InitialPDFsSetterDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
InitialPDFsSetterDoublePrecisionCUDA()
walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::InitialPDFsSetterDoublePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, double rho_0) inline
Definition at line 57 of file InitialPDFsSetterDoublePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 105 of file InitialPDFsSetterDoublePrecisionCUDA.h.
getRho_0()
double walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::getRho_0 () const inline
Definition at line 108 of file InitialPDFsSetterDoublePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::getSweep (const shared_ptr< InitialPDFsSetterDoublePrecisionCUDA > & kernel) inline static
Definition at line 75 of file InitialPDFsSetterDoublePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 90 of file InitialPDFsSetterDoublePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterDoublePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 79 of file InitialPDFsSetterDoublePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 95 of file InitialPDFsSetterDoublePrecisionCUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 70 of file InitialPDFsSetterDoublePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 82 of file InitialPDFsSetterDoublePrecisionCUDA.cu.
References block(), RESTRICT, stream, and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 124 of file InitialPDFsSetterDoublePrecisionCUDA.cu.
References block(), RESTRICT, stream, and velocity().
Referenced by getSweepOnCellInterval().
setRho_0()
void walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::setRho_0 (const double value) inline
Definition at line 109 of file InitialPDFsSetterDoublePrecisionCUDA.h.
The documentation for this class was generated from the following files:
InitialPDFsSetterDoublePrecisionCUDA.h
InitialPDFsSetterDoublePrecisionCUDA.cu