ESPResSo: walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA Class Reference
walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA Class Reference
#include <AdvectiveFluxKernel_single_precision_CUDA.h>
Public Member Functions
AdvectiveFluxKernel_single_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_, BlockDataID uID_)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< AdvectiveFluxKernel_single_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< AdvectiveFluxKernel_single_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file AdvectiveFluxKernel_single_precision_CUDA.h.
Constructor & Destructor Documentation
AdvectiveFluxKernel_single_precision_CUDA()
walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::AdvectiveFluxKernel_single_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_, BlockDataID uID_) inline
Definition at line 57 of file AdvectiveFluxKernel_single_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 104 of file AdvectiveFluxKernel_single_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::getSweep (const shared_ptr< AdvectiveFluxKernel_single_precision_CUDA > & kernel) inline static
Definition at line 73 of file AdvectiveFluxKernel_single_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 89 of file AdvectiveFluxKernel_single_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< AdvectiveFluxKernel_single_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 78 of file AdvectiveFluxKernel_single_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 94 of file AdvectiveFluxKernel_single_precision_CUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 69 of file AdvectiveFluxKernel_single_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 130 of file AdvectiveFluxKernel_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::AdvectiveFluxKernel_single_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 169 of file AdvectiveFluxKernel_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
AdvectiveFluxKernel_single_precision_CUDA.h
AdvectiveFluxKernel_single_precision_CUDA.cu