ESPResSo: ScriptInterface::ObjectList< ManagedType, BaseType > Class Template Reference
ScriptInterface::ObjectList< ManagedType, BaseType > Class Template Reference abstract
Owning list of object handles.
#include <ObjectList.hpp>
Public Types
using Base = ObjectContainer< ObjectList, ManagedType, BaseType >
using value_type = std::shared_ptr< ManagedType >
Public Member Functions
ObjectList ()
~ObjectList () override
void do_construct (VariantMap const &params) override
void add (value_type const &element)
Add an element to the list.
void remove (value_type const &element)
Removes all occurrences of an element from the list.
auto const & elements () const
List elements.
void clear ()
Clear the list.
Protected Member Functions
void do_destruct ()
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
Private Member Functions
virtual void add_in_core (value_type const &obj_ptr)=0
virtual void remove_in_core (value_type const &obj_ptr)=0
virtual bool has_in_core (value_type const &obj_ptr) const =0
Detailed Description
template<typename ManagedType, class BaseType = ObjectHandle>
class ScriptInterface::ObjectList< ManagedType, BaseType >
Owning list of object handles.
Stored elements are cleared from the core during destruction. Due to how dynamic dispatch works, derived types must mark remove_in_core as final` and call do_destruct in their virtual destructor. This is to ensure that pure virtual functions called by clear cannot be executed in a type derived from the type currently being destructed, since derived types no longer exist at this point of the destruction sequence.
Template Parameters
ManagedType Type of the managed objects, needs to be derived from ObjectHandle
Definition at line 53 of file ObjectList.hpp.
Member Typedef Documentation
Base
template<typename ManagedType , class BaseType = ObjectHandle> using ScriptInterface::ObjectList< ManagedType, BaseType >::Base = ObjectContainer<ObjectList, ManagedType, BaseType>
Definition at line 55 of file ObjectList.hpp.
value_type
template<typename ManagedType , class BaseType = ObjectHandle> using ScriptInterface::ObjectList< ManagedType, BaseType >::value_type = std::shared_ptr<ManagedType>
Definition at line 58 of file ObjectList.hpp.
Constructor & Destructor Documentation
ObjectList()
template<typename ManagedType , class BaseType = ObjectHandle> ScriptInterface::ObjectList< ManagedType, BaseType >::ObjectList () inline
Definition at line 76 of file ObjectList.hpp.
References ScriptInterface::make_vector_of_variants(), and ScriptInterface::AutoParameter::read_only.
~ObjectList()
template<typename ManagedType , class BaseType = ObjectHandle> ScriptInterface::ObjectList< ManagedType, BaseType >::~ObjectList () inline override
Definition at line 83 of file ObjectList.hpp.
References stream.
Member Function Documentation
add()
template<typename ManagedType , class BaseType = ObjectHandle> void ScriptInterface::ObjectList< ManagedType, BaseType >::add (value_type const & element) inline
Add an element to the list.
Parameters
element The element to add.
Definition at line 97 of file ObjectList.hpp.
References ScriptInterface::ObjectList< ManagedType, BaseType >::add_in_core(), and ScriptInterface::ObjectList< ManagedType, BaseType >::has_in_core().
Referenced by ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method().
add_in_core()
template<typename ManagedType , class BaseType = ObjectHandle> virtual void ScriptInterface::ObjectList< ManagedType, BaseType >::add_in_core (value_type const & obj_ptr) private pure virtual
Implemented in ScriptInterface::Accumulators::AutoUpdateAccumulators, ScriptInterface::Constraints::Constraints, ScriptInterface::Shapes::Union, ScriptInterface::walberla::EKContainer, and ScriptInterface::walberla::EKReactions.
Referenced by ScriptInterface::ObjectList< ManagedType, BaseType >::add(), and ScriptInterface::ObjectList< ManagedType, BaseType >::do_construct().
clear()
template<typename ManagedType , class BaseType = ObjectHandle> void ScriptInterface::ObjectList< ManagedType, BaseType >::clear () inline
Clear the list.
Definition at line 132 of file ObjectList.hpp.
References ScriptInterface::ObjectList< ManagedType, BaseType >::remove_in_core(), and stream.
Referenced by ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method(), and ScriptInterface::ObjectList< ManagedType, BaseType >::do_destruct().
do_call_method()
template<typename ManagedType , class BaseType = ObjectHandle> Variant ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method (std::string const & method, VariantMap const & parameters) inline override protected
Definition at line 141 of file ObjectList.hpp.
References ScriptInterface::ObjectList< ManagedType, BaseType >::add(), ScriptInterface::ObjectList< ManagedType, BaseType >::clear(), ScriptInterface::make_vector_of_variants(), ScriptInterface::none, ScriptInterface::ObjectList< ManagedType, BaseType >::remove(), and stream.
do_construct()
template<typename ManagedType , class BaseType = ObjectHandle> void ScriptInterface::ObjectList< ManagedType, BaseType >::do_construct (VariantMap const & params) inline override
Definition at line 85 of file ObjectList.hpp.
References ScriptInterface::ObjectList< ManagedType, BaseType >::add_in_core(), and stream.
Referenced by ScriptInterface::Accumulators::AutoUpdateAccumulators::on_bind_system(), and ScriptInterface::Constraints::Constraints::on_bind_system().
do_destruct()
template<typename ManagedType , class BaseType = ObjectHandle> void ScriptInterface::ObjectList< ManagedType, BaseType >::do_destruct () inline protected
Definition at line 69 of file ObjectList.hpp.
References ScriptInterface::ObjectList< ManagedType, BaseType >::clear(), and stream.
Referenced by ScriptInterface::Accumulators::AutoUpdateAccumulators::~AutoUpdateAccumulators(), and ScriptInterface::Constraints::Constraints::~Constraints().
elements()
template<typename ManagedType , class BaseType = ObjectHandle> auto const & ScriptInterface::ObjectList< ManagedType, BaseType >::elements () const inline
List elements.
Definition at line 127 of file ObjectList.hpp.
has_in_core()
template<typename ManagedType , class BaseType = ObjectHandle> virtual bool ScriptInterface::ObjectList< ManagedType, BaseType >::has_in_core (value_type const & obj_ptr) const private pure virtual
Implemented in ScriptInterface::Accumulators::AutoUpdateAccumulators, ScriptInterface::Constraints::Constraints, ScriptInterface::Shapes::Union, ScriptInterface::walberla::EKContainer, and ScriptInterface::walberla::EKReactions.
Referenced by ScriptInterface::ObjectList< ManagedType, BaseType >::add(), and ScriptInterface::ObjectList< ManagedType, BaseType >::remove().
remove()
template<typename ManagedType , class BaseType = ObjectHandle> void ScriptInterface::ObjectList< ManagedType, BaseType >::remove (value_type const & element) inline
Removes all occurrences of an element from the list.
Parameters
element The element to remove.
Definition at line 113 of file ObjectList.hpp.
References ScriptInterface::ObjectList< ManagedType, BaseType >::has_in_core(), ScriptInterface::ObjectList< ManagedType, BaseType >::remove_in_core(), and stream.
Referenced by ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method().
remove_in_core()
template<typename ManagedType , class BaseType = ObjectHandle> virtual void ScriptInterface::ObjectList< ManagedType, BaseType >::remove_in_core (value_type const & obj_ptr) private pure virtual
Implemented in ScriptInterface::Accumulators::AutoUpdateAccumulators, ScriptInterface::Constraints::Constraints, ScriptInterface::Shapes::Union, ScriptInterface::walberla::EKContainer, and ScriptInterface::walberla::EKReactions.
Referenced by ScriptInterface::ObjectList< ManagedType, BaseType >::clear(), and ScriptInterface::ObjectList< ManagedType, BaseType >::remove().
The documentation for this class was generated from the following file:
ObjectList.hpp