ESPResSo: walberla::pystencils::CollideSweepSinglePrecisionThermalized Class Reference
walberla::pystencils::CollideSweepSinglePrecisionThermalized Class Reference
#include <CollideSweepSinglePrecisionThermalized.h>
Public Member Functions
CollideSweepSinglePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< CollideSweepSinglePrecisionThermalized > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionThermalized > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file CollideSweepSinglePrecisionThermalized.h.
Constructor & Destructor Documentation
CollideSweepSinglePrecisionThermalized()
walberla::pystencils::CollideSweepSinglePrecisionThermalized::CollideSweepSinglePrecisionThermalized (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file CollideSweepSinglePrecisionThermalized.h.
Member Function Documentation
configure()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 103 of file CollideSweepSinglePrecisionThermalized.h.
getBlock_offset_0()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalized::getBlock_offset_0 () const inline
Definition at line 112 of file CollideSweepSinglePrecisionThermalized.h.
getBlock_offset_1()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalized::getBlock_offset_1 () const inline
Definition at line 113 of file CollideSweepSinglePrecisionThermalized.h.
getBlock_offset_2()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalized::getBlock_offset_2 () const inline
Definition at line 114 of file CollideSweepSinglePrecisionThermalized.h.
getKt()
float walberla::pystencils::CollideSweepSinglePrecisionThermalized::getKt () const inline
Definition at line 115 of file CollideSweepSinglePrecisionThermalized.h.
getOmega_bulk()
float walberla::pystencils::CollideSweepSinglePrecisionThermalized::getOmega_bulk () const inline
Definition at line 116 of file CollideSweepSinglePrecisionThermalized.h.
getOmega_even()
float walberla::pystencils::CollideSweepSinglePrecisionThermalized::getOmega_even () const inline
Definition at line 117 of file CollideSweepSinglePrecisionThermalized.h.
getOmega_odd()
float walberla::pystencils::CollideSweepSinglePrecisionThermalized::getOmega_odd () const inline
Definition at line 118 of file CollideSweepSinglePrecisionThermalized.h.
getOmega_shear()
float walberla::pystencils::CollideSweepSinglePrecisionThermalized::getOmega_shear () const inline
Definition at line 119 of file CollideSweepSinglePrecisionThermalized.h.
getSeed()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalized::getSeed () const inline
Definition at line 120 of file CollideSweepSinglePrecisionThermalized.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalized::getSweep () inline
Definition at line 90 of file CollideSweepSinglePrecisionThermalized.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalized::getSweep (const shared_ptr< CollideSweepSinglePrecisionThermalized > & kernel) inline static
Definition at line 77 of file CollideSweepSinglePrecisionThermalized.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< CollideSweepSinglePrecisionThermalized > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 81 of file CollideSweepSinglePrecisionThermalized.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::CollideSweepSinglePrecisionThermalized::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 95 of file CollideSweepSinglePrecisionThermalized.h.
References runOnCellInterval().
getTime_step()
uint32_t walberla::pystencils::CollideSweepSinglePrecisionThermalized::getTime_step () const inline
Definition at line 121 of file CollideSweepSinglePrecisionThermalized.h.
operator()()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::operator() (IBlock * block) inline
Definition at line 74 of file CollideSweepSinglePrecisionThermalized.h.
References block(), and run().
run()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::run (IBlock * block)
Definition at line 412 of file CollideSweepSinglePrecisionThermalized.cpp.
References block(), walberla::pystencils::internal_69764eed2d0964e29e3b97d1054b4693::collidesweepsingleprecisionthermalized_collidesweepsingleprecisionthermalized(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 455 of file CollideSweepSinglePrecisionThermalized.cpp.
References block(), walberla::pystencils::internal_69764eed2d0964e29e3b97d1054b4693::collidesweepsingleprecisionthermalized_collidesweepsingleprecisionthermalized(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setBlock_offset_0 (const uint32_t value) inline
Definition at line 122 of file CollideSweepSinglePrecisionThermalized.h.
setBlock_offset_1()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setBlock_offset_1 (const uint32_t value) inline
Definition at line 125 of file CollideSweepSinglePrecisionThermalized.h.
setBlock_offset_2()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setBlock_offset_2 (const uint32_t value) inline
Definition at line 128 of file CollideSweepSinglePrecisionThermalized.h.
setKt()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setKt (const float value) inline
Definition at line 131 of file CollideSweepSinglePrecisionThermalized.h.
setOmega_bulk()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setOmega_bulk (const float value) inline
Definition at line 132 of file CollideSweepSinglePrecisionThermalized.h.
setOmega_even()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setOmega_even (const float value) inline
Definition at line 133 of file CollideSweepSinglePrecisionThermalized.h.
setOmega_odd()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setOmega_odd (const float value) inline
Definition at line 134 of file CollideSweepSinglePrecisionThermalized.h.
setOmega_shear()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setOmega_shear (const float value) inline
Definition at line 135 of file CollideSweepSinglePrecisionThermalized.h.
setSeed()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setSeed (const uint32_t value) inline
Definition at line 136 of file CollideSweepSinglePrecisionThermalized.h.
setTime_step()
void walberla::pystencils::CollideSweepSinglePrecisionThermalized::setTime_step (const uint32_t value) inline
Definition at line 137 of file CollideSweepSinglePrecisionThermalized.h.
The documentation for this class was generated from the following files:
CollideSweepSinglePrecisionThermalized.h
CollideSweepSinglePrecisionThermalized.cpp