ESPResSo: Observables::ParticleObservable< ObsType > Class Template Reference
Observables::ParticleObservable< ObsType > Class Template Reference
This class implements an interface to the particle_observables library that implements necessary algorithms needed for observables that are based on single particle properties.
#include <PidObservable.hpp>
Classes
struct is_map
struct is_map< ParticleObservables::Map< T > >
Public Member Functions
std::vector< std::size_t > shape () const override
std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, ParticleObservables::traits< Particle > const &) const override
PidObservable (std::vector< int > ids)
Public Member Functions inherited from Observables::PidObservable
PidObservable (std::vector< int > ids)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > const & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Detailed Description
template<class ObsType>
class Observables::ParticleObservable< ObsType >
This class implements an interface to the particle_observables library that implements necessary algorithms needed for observables that are based on single particle properties.
Template Parameters
ObsType An observables composed of an algorithm from src/particle_observables/include/particle_observables/algorithms.hpp and two particle properties.
Example usage:
using namespace ParticleObservables;
using CenterOfMass = ParticleObservable<WeightedAverage<Position, Mass>>;
Definition at line 195 of file core/observables/PidObservable.hpp.
Member Function Documentation
evaluate()
template<class ObsType > std::vector< double > Observables::ParticleObservable< ObsType >::evaluate (boost::mpi::communicator const & comm, ParticleReferenceRange const & local_particles, ParticleObservables::traits< Particle > const &) const inline override virtual
Implements Observables::PidObservable.
Definition at line 210 of file core/observables/PidObservable.hpp.
References Utils::flatten(), Observables::PidObservable::ids(), and stream.
PidObservable()
template<class ObsType > Observables::PidObservable::PidObservable (std::vector< int > ids) inline explicit
Definition at line 64 of file core/observables/PidObservable.hpp.
shape()
template<class ObsType > std::vector< std::size_t > Observables::ParticleObservable< ObsType >::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 198 of file core/observables/PidObservable.hpp.
References Observables::PidObservable::ids(), and stream.
The documentation for this class was generated from the following file:
core/observables/PidObservable.hpp