ESPResSo: CollisionDetection::BindCenters Class Reference
CollisionDetection::BindCenters Class Reference
#include <BindCenters.hpp>
Public Member Functions
BindCenters (double distance, int bond_centers)
void initialize (System::System &system)
auto cutoff () const
void handle_collisions (System::System &system, std::vector< CollisionPair > &local_collision_queue)
bool detect_collision (Particle const &p1, Particle const &p2, double const dist_sq) const
Public Attributes
double distance
Distance at which particle are bound.
double distance_sq
Square of distance at which particle are bound.
int bond_centers
bond type used between centers of colliding particles
Detailed Description
Definition at line 36 of file core/collision_detection/BindCenters.hpp.
Constructor & Destructor Documentation
BindCenters()
CollisionDetection::BindCenters::BindCenters (double distance, int bond_centers) inline
Definition at line 45 of file core/collision_detection/BindCenters.hpp.
Member Function Documentation
cutoff()
auto CollisionDetection::BindCenters::cutoff () const inline
Definition at line 51 of file core/collision_detection/BindCenters.hpp.
References distance.
detect_collision()
bool CollisionDetection::BindCenters::detect_collision (Particle const & p1, Particle const & p2, double const dist_sq) const inline
Definition at line 56 of file core/collision_detection/BindCenters.hpp.
References bond_centers, CollisionDetection::detect_collision_common(), distance_sq, and stream.
handle_collisions()
void CollisionDetection::BindCenters::handle_collisions (System::System & system, std::vector< CollisionPair > & local_collision_queue)
Definition at line 59 of file BindCenters.cpp.
References CollisionDetection::add_bind_centers(), bond_centers, and stream.
initialize()
void CollisionDetection::BindCenters::initialize (System::System & system)
Definition at line 42 of file BindCenters.cpp.
References bond_centers, distance, distance_sq, number_of_partners(), Utils::sqr(), and stream.
Member Data Documentation
bond_centers
int CollisionDetection::BindCenters::bond_centers
bond type used between centers of colliding particles
Definition at line 43 of file core/collision_detection/BindCenters.hpp.
Referenced by detect_collision(), handle_collisions(), and initialize().
distance
double CollisionDetection::BindCenters::distance
Distance at which particle are bound.
Definition at line 39 of file core/collision_detection/BindCenters.hpp.
Referenced by cutoff(), and initialize().
distance_sq
double CollisionDetection::BindCenters::distance_sq
Square of distance at which particle are bound.
Definition at line 41 of file core/collision_detection/BindCenters.hpp.
Referenced by detect_collision(), and initialize().
The documentation for this class was generated from the following files:
core/collision_detection/BindCenters.hpp
BindCenters.cpp