ESPResSo: walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T > Class Template Reference
walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T > Class Template Reference
#include <BoundaryPackInfo.hpp>
Public Member Functions
~BoundaryPackInfo () override=default
void setup_boundary_handle (std::shared_ptr< LatticeWalberla > lattice, std::shared_ptr< Boundary_T > boundary)
bool constantDataExchange () const override
bool threadsafeReceiving () const override
void communicateLocal (IBlock const *sender, IBlock *receiver, stencil::Direction dir) override
void unpackData (IBlock *receiver, stencil::Direction dir, mpi::RecvBuffer &buffer) override
Protected Member Functions
void packDataImpl (IBlock const *sender, stencil::Direction dir, mpi::SendBuffer &buffer) const override
Protected Attributes
FlagUID const Domain_flag {"domain"}
Flag for domain cells, i.e.
FlagUID const Boundary_flag {"boundary"}
Flag for boundary cells.
Detailed Description
template<typename GhostLayerField_T, typename Boundary_T>
class walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >
Definition at line 52 of file BoundaryPackInfo.hpp.
Constructor & Destructor Documentation
~BoundaryPackInfo()
template<typename GhostLayerField_T , typename Boundary_T > walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::~BoundaryPackInfo () override default
Member Function Documentation
communicateLocal()
template<typename GhostLayerField_T , typename Boundary_T > void walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::communicateLocal (IBlock const * sender, IBlock * receiver, stencil::Direction dir) inline override
Definition at line 75 of file BoundaryPackInfo.hpp.
References walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::packDataImpl(), stream, and walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::unpackData().
constantDataExchange()
template<typename GhostLayerField_T , typename Boundary_T > bool walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::constantDataExchange () const inline override
Definition at line 72 of file BoundaryPackInfo.hpp.
packDataImpl()
template<typename GhostLayerField_T , typename Boundary_T > void walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::packDataImpl (IBlock const * sender, stencil::Direction dir, mpi::SendBuffer & buffer) const inline override protected
Definition at line 129 of file BoundaryPackInfo.hpp.
References walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::Boundary_flag, and stream.
Referenced by walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::communicateLocal().
setup_boundary_handle()
template<typename GhostLayerField_T , typename Boundary_T > void walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::setup_boundary_handle (std::shared_ptr< LatticeWalberla > lattice, std::shared_ptr< Boundary_T > boundary) inline
Definition at line 66 of file BoundaryPackInfo.hpp.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::EKinWalberlaImpl(), and walberla::LBWalberlaImpl< FloatType, Architecture >::LBWalberlaImpl().
threadsafeReceiving()
template<typename GhostLayerField_T , typename Boundary_T > bool walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::threadsafeReceiving () const inline override
Definition at line 73 of file BoundaryPackInfo.hpp.
unpackData()
template<typename GhostLayerField_T , typename Boundary_T > void walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::unpackData (IBlock * receiver, stencil::Direction dir, mpi::RecvBuffer & buffer) inline override
Definition at line 88 of file BoundaryPackInfo.hpp.
References walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::Boundary_flag, and stream.
Referenced by walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::communicateLocal().
Member Data Documentation
Boundary_flag
template<typename GhostLayerField_T , typename Boundary_T > FlagUID const walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::Boundary_flag {"boundary"} protected
Flag for boundary cells.
Definition at line 58 of file BoundaryPackInfo.hpp.
Referenced by walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::packDataImpl(), and walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::unpackData().
Domain_flag
template<typename GhostLayerField_T , typename Boundary_T > FlagUID const walberla::field::communication::BoundaryPackInfo< GhostLayerField_T, Boundary_T >::Domain_flag {"domain"} protected
Flag for domain cells, i.e.
all cells.
Definition at line 56 of file BoundaryPackInfo.hpp.
The documentation for this class was generated from the following file:
BoundaryPackInfo.hpp