ESPResSo: walberla::EKReactionImplBulk< Architecture > Class Template Reference
walberla::EKReactionImplBulk< Architecture > Class Template Reference
#include <EKReactionImplBulk.hpp>
Public Member Functions
~EKReactionImplBulk () override=default
void perform_reaction () override
EKReactionBase (std::shared_ptr< LatticeWalberla > lattice, reactants_type reactants, double coefficient)
double get_coefficient () const noexcept
auto get_lattice () const noexcept
auto const & get_reactants () const noexcept
Public Member Functions inherited from walberla::EKReactionBase
EKReactionBase (std::shared_ptr< LatticeWalberla > lattice, reactants_type reactants, double coefficient)
virtual ~EKReactionBase ()=default
void set_coefficient (double coefficient) noexcept
double get_coefficient () const noexcept
auto get_lattice () const noexcept
auto const & get_reactants () const noexcept
Additional Inherited Members
Public Types inherited from walberla::EKReactionBase
using reactants_type = std::vector< std::shared_ptr< EKReactant > >
Detailed Description
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU>
class walberla::EKReactionImplBulk< Architecture >
Definition at line 34 of file EKReactionImplBulk.hpp.
Constructor & Destructor Documentation
~EKReactionImplBulk()
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU> walberla::EKReactionImplBulk< Architecture >::~EKReactionImplBulk () override default
Member Function Documentation
EKReactionBase()
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU> walberla::EKReactionBase::EKReactionBase (std::shared_ptr< LatticeWalberla > lattice, reactants_type reactants, double coefficient) inline
Definition at line 41 of file EKReactionBase.hpp.
get_coefficient()
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU> double walberla::EKReactionBase::get_coefficient () const inline noexcept
Definition at line 51 of file EKReactionBase.hpp.
Referenced by walberla::EKReactionImplBulk< Architecture >::perform_reaction().
get_lattice()
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU> auto walberla::EKReactionBase::get_lattice () const inline noexcept
Definition at line 54 of file EKReactionBase.hpp.
Referenced by walberla::EKReactionImplBulk< Architecture >::perform_reaction().
get_reactants()
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU> auto const & walberla::EKReactionBase::get_reactants () const inline noexcept
Definition at line 55 of file EKReactionBase.hpp.
Referenced by walberla::EKReactionImplBulk< Architecture >::perform_reaction().
perform_reaction()
template<lbmpy::Arch Architecture = lbmpy::Arch::CPU> void walberla::EKReactionImplBulk< Architecture >::perform_reaction () inline override virtual
Implements walberla::EKReactionBase.
Definition at line 43 of file EKReactionImplBulk.hpp.
References block(), walberla::EKReactionImplBulk< Architecture >::get_coefficient(), walberla::EKReactionImplBulk< Architecture >::get_lattice(), walberla::EKReactionImplBulk< Architecture >::get_reactants(), and stream.
The documentation for this class was generated from the following file:
EKReactionImplBulk.hpp