ESPResSo: Observables::PidObservable Class Reference
Observables::PidObservable Class Reference abstract
Particle-based observable.
#include <PidObservable.hpp>
Public Member Functions
PidObservable (std::vector< int > ids)
std::vector< double > operator() (boost::mpi::communicator const &comm) const final
std::vector< int > const & ids () const
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
virtual std::vector< std::size_t > shape () const =0
Dimensions needed to reshape the flat array returned by the observable.
Private Member Functions
virtual std::vector< double > evaluate (boost::mpi::communicator const &comm, ParticleReferenceRange const &local_particles, const ParticleObservables::traits< Particle > &traits) const =0
Detailed Description
Particle-based observable.
Base class for observables extracting raw data from particle subsets and returning either the data or a statistic derived from it.
Definition at line 55 of file core/observables/PidObservable.hpp.
Constructor & Destructor Documentation
PidObservable()
Observables::PidObservable::PidObservable (std::vector< int > ids) inline explicit
Definition at line 65 of file core/observables/PidObservable.hpp.
Member Function Documentation
evaluate()
virtual std::vector<double> Observables::PidObservable::evaluate (boost::mpi::communicator const & comm, ParticleReferenceRange const & local_particles, const ParticleObservables::traits< Particle > & traits) const private pure virtual
Implemented in Observables::CylindricalLBVelocityProfileAtParticlePositions, Observables::ParticleObservable< ObsType >, Observables::ParticleObservable< ParticleObservables::DipoleFields >, Observables::ParticleDistances, Observables::ParticleDipoleFields, Observables::ForceDensityProfile, Observables::FluxDensityProfile, Observables::DensityProfile, Observables::CylindricalVelocityProfile, Observables::CylindricalLBFluxDensityProfileAtParticlePositions, Observables::CylindricalFluxDensityProfile, Observables::CylindricalDensityProfile, Observables::CosPersistenceAngles, Observables::BondDihedrals, Observables::BondAngles, and Observables::TotalForce.
Referenced by operator()().
ids()
std::vector<int> const& Observables::PidObservable::ids () const inline
Definition at line 68 of file core/observables/PidObservable.hpp.
Referenced by Observables::BondAngles::BondAngles(), Observables::BondDihedrals::BondDihedrals(), Observables::CosPersistenceAngles::CosPersistenceAngles(), operator()(), Observables::ParticleDistances::ParticleDistances(), Observables::BondAngles::shape(), Observables::BondDihedrals::shape(), Observables::CosPersistenceAngles::shape(), Observables::ParticleDistances::shape(), and Observables::ParticleObservable< ObsType >::shape().
operator()()
std::vector< double > Observables::PidObservable::operator() (boost::mpi::communicator const & comm) const final virtual
Implements Observables::Observable.
Definition at line 30 of file PidObservable.cpp.
References evaluate(), fetch_particles(), and ids().
The documentation for this class was generated from the following files:
core/observables/PidObservable.hpp
PidObservable.cpp