ESPResSo: BondView Class Reference
BondView Class Reference
Immutable view on a bond.
#include <BondList.hpp>
Public Member Functions
BondView ()=default
BondView (int id, Utils::Span< const int > partners)
int bond_id () const
const Utils::Span< const int > & partner_ids () const
bool operator== (BondView const &rhs) const
bool operator!= (BondView const &rhs) const
Detailed Description
Immutable view on a bond.
The bond id and ids of the partner particles of a bond can be inspected (but not changed) via this view.
Definition at line 46 of file BondList.hpp.
Constructor & Destructor Documentation
BondView() [1/2]
BondView::BondView () default
BondView() [2/2]
BondView::BondView (int id, Utils::Span< const int > partners) inline
Definition at line 53 of file BondList.hpp.
Member Function Documentation
bond_id()
int BondView::bond_id () const inline
Definition at line 56 of file BondList.hpp.
Referenced by BondList::insert(), and pair_bond_exists_on().
operator!=()
bool BondView::operator!= (BondView const & rhs) const inline
Definition at line 63 of file BondList.hpp.
operator==()
bool BondView::operator== (BondView const & rhs) const inline
Definition at line 59 of file BondList.hpp.
partner_ids()
const Utils::Span<const int>& BondView::partner_ids () const inline
Definition at line 57 of file BondList.hpp.
Referenced by BondList::insert(), and pair_bond_exists_on().
The documentation for this class was generated from the following file:
BondList.hpp