ESPResSo: LocalBox Class Reference
LocalBox Class Reference
#include <LocalBox.hpp>
Public Member Functions
LocalBox ()=default
LocalBox (Utils::Vector3d const &lower_corner, Utils::Vector3d const &local_box_length, Utils::Array< int, 6 > const &boundaries, CellStructureType const cell_structure_type)
auto const & my_left () const
Left (bottom, front) corner of this nodes local box.
auto const & my_right () const
Right (top, back) corner of this nodes local box.
auto const & length () const
Dimensions of the box a single node is responsible for.
auto const & boundary () const
Boundary information for the local box.
auto const & cell_structure_type () const
Return cell structure type.
auto volume () const
Volume of the local box.
void set_cell_structure_type (CellStructureType cell_structure_type)
Set cell structure type.
Static Public Member Functions
static LocalBox make_regular_decomposition (Utils::Vector3d const &box_l, Utils::Vector3i const &node_index, Utils::Vector3i const &node_grid)
Detailed Description
Definition at line 27 of file LocalBox.hpp.
Constructor & Destructor Documentation
LocalBox() [1/2]
LocalBox::LocalBox () default
LocalBox() [2/2]
LocalBox::LocalBox (Utils::Vector3d const & lower_corner, Utils::Vector3d const & local_box_length, Utils::Array< int, 6 > const & boundaries, CellStructureType const cell_structure_type) inline
Definition at line 36 of file LocalBox.hpp.
Member Function Documentation
boundary()
auto const & LocalBox::boundary () const inline
Boundary information for the local box.
This returns for each of the faces of the local box if it is a boundary of the simulation box. The format is as follows: (x low, x high, y low, y high, z low, z high).
Returns
Array with boundary information.
Definition at line 59 of file LocalBox.hpp.
cell_structure_type()
auto const & LocalBox::cell_structure_type () const inline
Return cell structure type.
Definition at line 62 of file LocalBox.hpp.
Referenced by set_cell_structure_type().
length()
auto const & LocalBox::length () const inline
Dimensions of the box a single node is responsible for.
Definition at line 49 of file LocalBox.hpp.
Referenced by RegularDecomposition::max_cutoff().
make_regular_decomposition()
static LocalBox LocalBox::make_regular_decomposition (Utils::Vector3d const & box_l, Utils::Vector3i const & node_index, Utils::Vector3i const & node_grid) inline static
Definition at line 72 of file LocalBox.hpp.
References Utils::hadamard_division(), Utils::hadamard_product(), my_left(), REGULAR, and stream.
Referenced by System::System::update_local_geo().
my_left()
auto const & LocalBox::my_left () const inline
Left (bottom, front) corner of this nodes local box.
Definition at line 45 of file LocalBox.hpp.
Referenced by P3MLocalMesh::calc_local_ca_mesh(), LB::ParticleCoupling::kernel(), and make_regular_decomposition().
my_right()
auto const & LocalBox::my_right () const inline
Right (top, back) corner of this nodes local box.
Definition at line 47 of file LocalBox.hpp.
Referenced by P3MLocalMesh::calc_local_ca_mesh(), and LB::ParticleCoupling::kernel().
set_cell_structure_type()
void LocalBox::set_cell_structure_type (CellStructureType cell_structure_type) inline
Set cell structure type.
Definition at line 68 of file LocalBox.hpp.
References cell_structure_type().
volume()
auto LocalBox::volume () const inline
Volume of the local box.
Definition at line 65 of file LocalBox.hpp.
References Utils::product().
The documentation for this class was generated from the following file:
LocalBox.hpp