ESPResSo: ScriptInterface::Observables::PidProfileObservable< CoreObs > Class Template Reference
ScriptInterface::Observables::PidProfileObservable< CoreObs > Class Template Reference
#include <PidProfileObservable.hpp>
Public Member Functions
PidProfileObservable ()
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &method, VariantMap const &parameters) override
std::shared_ptr<::Observables::PidProfileObservable > pid_profile_observable () const
std::shared_ptr<::Observables::Observable > observable () const override
Public Member Functions inherited from ScriptInterface::AutoParameters< PidProfileObservable< CoreObs >, Observable >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< PidProfileObservable< CoreObs >, Observable >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
template<typename CoreObs>
class ScriptInterface::Observables::PidProfileObservable< CoreObs >
Definition at line 45 of file script_interface/observables/PidProfileObservable.hpp.
Constructor & Destructor Documentation
PidProfileObservable()
template<typename CoreObs > ScriptInterface::Observables::PidProfileObservable< CoreObs >::PidProfileObservable () inline
Definition at line 51 of file script_interface/observables/PidProfileObservable.hpp.
References ScriptInterface::AutoParameters< PidProfileObservable< CoreObs >, Observable >::add_parameters(), ScriptInterface::Observables::PidProfileObservable< CoreObs >::pid_profile_observable(), and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
do_call_method()
template<typename CoreObs > Variant ScriptInterface::Observables::PidProfileObservable< CoreObs >::do_call_method (std::string const & method, VariantMap const & parameters) inline override
Definition at line 91 of file script_interface/observables/PidProfileObservable.hpp.
References ScriptInterface::Observables::PidProfileObservable< CoreObs >::pid_profile_observable(), and stream.
do_construct()
template<typename CoreObs > void ScriptInterface::Observables::PidProfileObservable< CoreObs >::do_construct (VariantMap const & params) inline override
Definition at line 81 of file script_interface/observables/PidProfileObservable.hpp.
References ScriptInterface::ObjectHandle::context(), ScriptInterface::Context::parallel_try_catch(), and stream.
observable()
template<typename CoreObs > std::shared_ptr<::Observables::Observable > ScriptInterface::Observables::PidProfileObservable< CoreObs >::observable () const inline override
Definition at line 107 of file script_interface/observables/PidProfileObservable.hpp.
pid_profile_observable()
template<typename CoreObs > std::shared_ptr<::Observables::PidProfileObservable > ScriptInterface::Observables::PidProfileObservable< CoreObs >::pid_profile_observable () const inline
Definition at line 103 of file script_interface/observables/PidProfileObservable.hpp.
Referenced by ScriptInterface::Observables::PidProfileObservable< CoreObs >::do_call_method(), and ScriptInterface::Observables::PidProfileObservable< CoreObs >::PidProfileObservable().
The documentation for this class was generated from the following file:
script_interface/observables/PidProfileObservable.hpp