ESPResSo: walberla::pystencils::UpdateVelFromPDFDoublePrecision Class Reference
walberla::pystencils::UpdateVelFromPDFDoublePrecision Class Reference
#include <UpdateVelFromPDFDoublePrecision.h>
Public Member Functions
UpdateVelFromPDFDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< UpdateVelFromPDFDoublePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFDoublePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 53 of file UpdateVelFromPDFDoublePrecision.h.
Constructor & Destructor Documentation
UpdateVelFromPDFDoublePrecision()
walberla::pystencils::UpdateVelFromPDFDoublePrecision::UpdateVelFromPDFDoublePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 55 of file UpdateVelFromPDFDoublePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::UpdateVelFromPDFDoublePrecision::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 94 of file UpdateVelFromPDFDoublePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecision::getSweep () inline
Definition at line 81 of file UpdateVelFromPDFDoublePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecision::getSweep (const shared_ptr< UpdateVelFromPDFDoublePrecision > & kernel) inline static
Definition at line 68 of file UpdateVelFromPDFDoublePrecision.h.
getSweepOnCellInterval() [1/2]
std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 86 of file UpdateVelFromPDFDoublePrecision.h.
References runOnCellInterval(), and stream.
getSweepOnCellInterval() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::UpdateVelFromPDFDoublePrecision::getSweepOnCellInterval (const shared_ptr< UpdateVelFromPDFDoublePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 72 of file UpdateVelFromPDFDoublePrecision.h.
References stream.
operator()()
void walberla::pystencils::UpdateVelFromPDFDoublePrecision::operator() (IBlock * block) inline
Definition at line 65 of file UpdateVelFromPDFDoublePrecision.h.
References block(), and run().
run()
void walberla::pystencils::UpdateVelFromPDFDoublePrecision::run (IBlock * block)
Definition at line 81 of file UpdateVelFromPDFDoublePrecision.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_de8af14df5055eb4add5a44e06cbe9b5::updatevelfrompdfdoubleprecision_updatevelfrompdfdoubleprecision(), and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::UpdateVelFromPDFDoublePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 120 of file UpdateVelFromPDFDoublePrecision.cpp.
References block(), RESTRICT, stream, walberla::pystencils::internal_de8af14df5055eb4add5a44e06cbe9b5::updatevelfrompdfdoubleprecision_updatevelfrompdfdoubleprecision(), and velocity().
Referenced by getSweepOnCellInterval().
The documentation for this class was generated from the following files:
UpdateVelFromPDFDoublePrecision.h
UpdateVelFromPDFDoublePrecision.cpp