ESPResSo: walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector Class Reference
walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector Class Reference
#include <DynamicUBBSinglePrecisionCUDA.h>
Public Member Functions
ForceVector ()=default
bool operator== (ForceVector const &other) const
~ForceVector ()
auto & forceVector ()
auto const & forceVector () const
ForceStruct * pointerCpu ()
bool empty () const
ForceStruct * pointerGpu ()
Vector3< double > getForce ()
void syncGPU ()
void syncCPU ()
Detailed Description
Definition at line 162 of file DynamicUBBSinglePrecisionCUDA.h.
Constructor & Destructor Documentation
ForceVector()
walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::ForceVector () default
~ForceVector()
walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::~ForceVector () inline
Definition at line 169 of file DynamicUBBSinglePrecisionCUDA.h.
References stream.
Member Function Documentation
empty()
bool walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::empty () const inline
Definition at line 179 of file DynamicUBBSinglePrecisionCUDA.h.
forceVector() [1/2]
auto & walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::forceVector () inline
Definition at line 174 of file DynamicUBBSinglePrecisionCUDA.h.
Referenced by walberla::lbm::DynamicUBBSinglePrecisionCUDA::getForceVector().
forceVector() [2/2]
auto const & walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::forceVector () const inline
Definition at line 175 of file DynamicUBBSinglePrecisionCUDA.h.
getForce()
Vector3< double > walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::getForce () inline
Definition at line 182 of file DynamicUBBSinglePrecisionCUDA.h.
References stream, and syncCPU().
Referenced by walberla::lbm::DynamicUBBSinglePrecisionCUDA::getForce().
operator==()
bool walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::operator== (ForceVector const & other) const inline
Definition at line 165 of file DynamicUBBSinglePrecisionCUDA.h.
References stream.
pointerCpu()
ForceStruct * walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::pointerCpu () inline
Definition at line 176 of file DynamicUBBSinglePrecisionCUDA.h.
References stream.
pointerGpu()
ForceStruct * walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::pointerGpu () inline
Definition at line 181 of file DynamicUBBSinglePrecisionCUDA.h.
syncCPU()
void walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::syncCPU () inline
Definition at line 208 of file DynamicUBBSinglePrecisionCUDA.h.
References stream.
Referenced by getForce().
syncGPU()
void walberla::lbm::DynamicUBBSinglePrecisionCUDA::ForceVector::syncGPU () inline
Definition at line 193 of file DynamicUBBSinglePrecisionCUDA.h.
References stream.
The documentation for this class was generated from the following file:
DynamicUBBSinglePrecisionCUDA.h