ESPResSo: Observables::LBVelocityProfile Class Reference
Observables::LBVelocityProfile Class Reference
#include <LBVelocityProfile.hpp>
Public Member Functions
std::vector< std::size_t > shape () const override
std::vector< double > operator() (boost::mpi::communicator const &comm) const override
LBProfileObservable (double sampling_delta_x, double sampling_delta_y, double sampling_delta_z, double sampling_offset_x, double sampling_offset_y, double sampling_offset_z, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z, bool allow_empty_bins=false)
Public Member Functions inherited from Observables::LBProfileObservable
LBProfileObservable (double sampling_delta_x, double sampling_delta_y, double sampling_delta_z, double sampling_offset_x, double sampling_offset_y, double sampling_offset_z, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z, bool allow_empty_bins=false)
void calculate_sampling_positions (auto const &box_geo, auto const &lb) const
Public Member Functions inherited from Observables::ProfileObservable
ProfileObservable (int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z)
std::vector< std::size_t > shape () const override
auto n_bins () const
auto limits () const
std::array< std::vector< double >, 3 > edges () const
Calculate the bin edges for each dimension.
Public Member Functions inherited from Observables::Observable
Observable ()=default
virtual ~Observable ()=default
std::size_t n_values () const
Size of the flat array returned by the observable.
Additional Inherited Members
Public Attributes inherited from Observables::LBProfileObservable
std::array< double, 3 > sampling_delta
std::array< double, 3 > sampling_offset
bool allow_empty_bins
Protected Attributes inherited from Observables::LBProfileObservable
SanityChecksLB lb_sanity_checks
std::vector< Utils::Vector3d > sampling_positions
Detailed Description
Definition at line 29 of file LBVelocityProfile.hpp.
Member Function Documentation
LBProfileObservable()
Observables::LBProfileObservable::LBProfileObservable (double sampling_delta_x, double sampling_delta_y, double sampling_delta_z, double sampling_offset_x, double sampling_offset_y, double sampling_offset_z, int n_x_bins, int n_y_bins, int n_z_bins, double min_x, double max_x, double min_y, double max_y, double min_z, double max_z, bool allow_empty_bins = false) inline
Definition at line 39 of file core/observables/LBProfileObservable.hpp.
operator()()
std::vector< double > Observables::LBVelocityProfile::operator() (boost::mpi::communicator const & comm) const override virtual
Implements Observables::Observable.
Definition at line 33 of file LBVelocityProfile.cpp.
References Observables::LBProfileObservable::allow_empty_bins, Observables::LBProfileObservable::calculate_sampling_positions(), System::get_system(), Observables::LBProfileObservable::lb_sanity_checks, Observables::ProfileObservable::limits(), Observables::SanityChecksLB::mismatch(), Observables::ProfileObservable::n_bins(), Observables::LBProfileObservable::sampling_positions, and stream.
shape()
std::vector< std::size_t > Observables::LBVelocityProfile::shape () const inline override virtual
Implements Observables::Observable.
Definition at line 32 of file LBVelocityProfile.hpp.
References Observables::ProfileObservable::n_bins().
The documentation for this class was generated from the following files:
LBVelocityProfile.hpp
LBVelocityProfile.cpp