ESPResSo: ScriptInterface::Integrators::SteepestDescent Class Reference
ScriptInterface::Integrators::SteepestDescent Class Reference
#include <SteepestDescent.hpp>
Public Member Functions
SteepestDescent ()
void do_construct (VariantMap const &params) override
Variant integrate (VariantMap const &params) override
void activate () override
::SteepestDescentParameters const & get_instance () const
Public Member Functions inherited from ScriptInterface::AutoParameters< SteepestDescent, Integrator >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Additional Inherited Members
Protected Member Functions inherited from ScriptInterface::AutoParameters< SteepestDescent, Integrator >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Detailed Description
Definition at line 35 of file SteepestDescent.hpp.
Constructor & Destructor Documentation
SteepestDescent()
ScriptInterface::Integrators::SteepestDescent::SteepestDescent ()
Definition at line 50 of file SteepestDescent.cpp.
References ScriptInterface::AutoParameters< SteepestDescent, Integrator >::add_parameters(), SteepestDescentParameters::f_max, SteepestDescentParameters::gamma, get_instance(), SteepestDescentParameters::max_displacement, and ScriptInterface::AutoParameter::read_only.
Member Function Documentation
activate()
void ScriptInterface::Integrators::SteepestDescent::activate () override
Definition at line 72 of file SteepestDescent.cpp.
References get_instance(), INTEG_METHOD_STEEPEST_DESCENT, System::System::propagation, and register_integrator().
do_construct()
void ScriptInterface::Integrators::SteepestDescent::do_construct (VariantMap const & params) override
Definition at line 61 of file SteepestDescent.cpp.
References ScriptInterface::get_value(), and params.
get_instance()
::SteepestDescentParameters const & ScriptInterface::Integrators::SteepestDescent::get_instance () const inline
Definition at line 45 of file SteepestDescent.hpp.
Referenced by activate(), and SteepestDescent().
integrate()
Variant ScriptInterface::Integrators::SteepestDescent::integrate (VariantMap const & params) override
Definition at line 37 of file SteepestDescent.cpp.
References ScriptInterface::get_value(), INTEG_REUSE_FORCES_NEVER, System::System::integrate_with_signal_handler(), and params.
The documentation for this class was generated from the following files:
SteepestDescent.hpp
SteepestDescent.cpp