ESPResSo: ScriptInterface::Coulomb::CoulombScafacos Class Reference
ScriptInterface::Coulomb::CoulombScafacos Class Reference
#include <CoulombScafacos.hpp>
Public Member Functions
CoulombScafacos ()
~CoulombScafacos () override
void do_construct (VariantMap const &params) override
Variant do_call_method (std::string const &name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >
Actor ()
std::shared_ptr< CoreActorClass > actor ()
std::shared_ptr< CoreActorClass const > actor () const
Public Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
std::span< const boost::string_ref > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Protected Types inherited from ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >
using SIActorClass = CoulombScafacos
using CoreActorClass = ::CoulombScafacos
using ObjectClass = Actor< CoulombScafacos, ::CoulombScafacos >
Protected Member Functions inherited from ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >
void on_bind_system (::System::System &) override
void set_charge_neutrality_tolerance (VariantMap const &params)
Protected Member Functions inherited from ScriptInterface::AutoParameters< Derived, Base >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Protected Attributes inherited from ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >
std::shared_ptr< CoreActorClass > m_actor
Detailed Description
Definition at line 47 of file CoulombScafacos.hpp.
Constructor & Destructor Documentation
CoulombScafacos()
ScriptInterface::Coulomb::CoulombScafacos::CoulombScafacos () inline
Definition at line 51 of file CoulombScafacos.hpp.
References ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >::actor(), ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), ScriptInterface::Scafacos::deserialize_parameters(), and ScriptInterface::AutoParameter::read_only.
~CoulombScafacos()
ScriptInterface::Coulomb::CoulombScafacos::~CoulombScafacos () inline override
Definition at line 85 of file CoulombScafacos.hpp.
References ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >::m_actor.
Member Function Documentation
do_call_method()
Variant ScriptInterface::Coulomb::CoulombScafacos::do_call_method (std::string const & name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >.
Definition at line 106 of file CoulombScafacos.hpp.
References ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >::actor(), ScriptInterface::Scafacos::available_methods(), ScriptInterface::ObjectHandle::context(), ScriptInterface::Coulomb::Actor< SIClass, CoreClass >::do_call_method(), ScriptInterface::make_vector_of_variants(), ScriptInterface::ObjectHandle::name(), ScriptInterface::Context::parallel_try_catch(), and params.
do_construct()
void ScriptInterface::Coulomb::CoulombScafacos::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 90 of file CoulombScafacos.hpp.
References ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >::actor(), ScriptInterface::ObjectHandle::context(), ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >::m_actor, make_coulomb_scafacos(), Communication::mpiCallbacksHandle(), ScriptInterface::Context::parallel_try_catch(), params, ScafacosContextBase::sanity_check_method(), ScriptInterface::Scafacos::serialize_parameters(), and ScriptInterface::Coulomb::Actor< CoulombScafacos, ::CoulombScafacos >::set_charge_neutrality_tolerance().
The documentation for this class was generated from the following file:
CoulombScafacos.hpp