ESPResSo: walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA Class Reference
walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA Class Reference
#include <InitialPDFsSetterSinglePrecisionCUDA.h>
Public Member Functions
InitialPDFsSetterSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, float rho_0)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &, IBlock *)
float getRho_0 () const
void setRho_0 (const float value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< InitialPDFsSetterSinglePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterSinglePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file InitialPDFsSetterSinglePrecisionCUDA.h.
Constructor & Destructor Documentation
InitialPDFsSetterSinglePrecisionCUDA()
walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::InitialPDFsSetterSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_, float rho_0) inline
Definition at line 57 of file InitialPDFsSetterSinglePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & , IBlock *) inline
Definition at line 105 of file InitialPDFsSetterSinglePrecisionCUDA.h.
getRho_0()
float walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::getRho_0 () const inline
Definition at line 108 of file InitialPDFsSetterSinglePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::getSweep (const shared_ptr< InitialPDFsSetterSinglePrecisionCUDA > & kernel) inline static
Definition at line 75 of file InitialPDFsSetterSinglePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 90 of file InitialPDFsSetterSinglePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< InitialPDFsSetterSinglePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 79 of file InitialPDFsSetterSinglePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 95 of file InitialPDFsSetterSinglePrecisionCUDA.h.
References runOnCellInterval(), and stream.
operator()()
void walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 70 of file InitialPDFsSetterSinglePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 82 of file InitialPDFsSetterSinglePrecisionCUDA.cu.
References block(), RESTRICT, stream, and velocity().
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 124 of file InitialPDFsSetterSinglePrecisionCUDA.cu.
References block(), RESTRICT, stream, and velocity().
Referenced by getSweepOnCellInterval().
setRho_0()
void walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::setRho_0 (const float value) inline
Definition at line 109 of file InitialPDFsSetterSinglePrecisionCUDA.h.
The documentation for this class was generated from the following files:
InitialPDFsSetterSinglePrecisionCUDA.h
InitialPDFsSetterSinglePrecisionCUDA.cu