ESPResSo: walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA Class Reference
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA Class Reference
#include <StreamCollideSweepThermalizedSinglePrecisionCUDA.h>
Public Member Functions
StreamCollideSweepThermalizedSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepThermalizedSinglePrecisionCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
float getKt () const
float getOmega_bulk () const
float getOmega_even () const
float getOmega_odd () const
float getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const float value)
void setOmega_bulk (const float value)
void setOmega_even (const float value)
void setOmega_odd (const float value)
void setOmega_shear (const float value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepThermalizedSinglePrecisionCUDA()
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::StreamCollideSweepThermalizedSinglePrecisionCUDA (BlockDataID forceID_, BlockDataID pdfsID_, float kT, float omega_bulk, float omega_even, float omega_odd, float omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
~StreamCollideSweepThermalizedSinglePrecisionCUDA()
walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::~StreamCollideSweepThermalizedSinglePrecisionCUDA () inline
Definition at line 67 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 117 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getBlock_offset_0 () const inline
Definition at line 126 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getBlock_offset_1 () const inline
Definition at line 127 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getBlock_offset_2 () const inline
Definition at line 128 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getKt()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getKt () const inline
Definition at line 129 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getOmega_bulk()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getOmega_bulk () const inline
Definition at line 130 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getOmega_even()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getOmega_even () const inline
Definition at line 131 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getOmega_odd()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getOmega_odd () const inline
Definition at line 132 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getOmega_shear()
float walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getOmega_shear () const inline
Definition at line 133 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getSeed () const inline
Definition at line 134 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getSweep (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionCUDA > & kernel) inline static
Definition at line 85 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 102 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepThermalizedSinglePrecisionCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 90 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 107 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::getTime_step () const inline
Definition at line 135 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 80 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 401 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 463 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 136 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 139 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 142 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setKt()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setKt (const float value) inline
Definition at line 145 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setOmega_bulk (const float value) inline
Definition at line 146 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setOmega_even (const float value) inline
Definition at line 147 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setOmega_odd (const float value) inline
Definition at line 148 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setOmega_shear (const float value) inline
Definition at line 149 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setSeed()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setSeed (const uint32_t value) inline
Definition at line 150 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepThermalizedSinglePrecisionCUDA::setTime_step (const uint32_t value) inline
Definition at line 151 of file StreamCollideSweepThermalizedSinglePrecisionCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepThermalizedSinglePrecisionCUDA.h
StreamCollideSweepThermalizedSinglePrecisionCUDA.cu