ESPResSo: ScriptInterface::System::SystemFacade Class Reference
ScriptInterface::System::SystemFacade Class Reference
Facade for the real System class.
#include <SystemFacade.hpp>
Public Member Functions
SystemFacade ()
void do_construct (VariantMap const &) override
Variant get_parameter (const std::string &name) const override
void do_set_parameter (const std::string &name, const Variant &v) override
Utils::Span< const boost::string_ref > valid_parameters () const override
Variant do_call_method (std::string const &name, VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
boost::string_ref name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
auto get_valid_parameters () const
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
std::string serialize () const
virtual std::vector< std::pair< std::string, Variant > > serialize_parameters () const
Serialize parameters.
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
Facade for the real System class.
All calls are forwarded to the real class. This construct is needed to satisfy the requirements of the checkpointing mechanism, which instantiates the SystemFacade after all other script interface objects have been instantiated.
Definition at line 40 of file SystemFacade.hpp.
Constructor & Destructor Documentation
SystemFacade()
ScriptInterface::System::SystemFacade::SystemFacade () inline
Definition at line 44 of file SystemFacade.hpp.
Member Function Documentation
do_call_method()
Variant ScriptInterface::System::SystemFacade::do_call_method (std::string const & name, VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 58 of file SystemFacade.hpp.
References ScriptInterface::ObjectHandle::name(), and params.
do_construct()
void ScriptInterface::System::SystemFacade::do_construct (VariantMap const &) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 48 of file SystemFacade.hpp.
do_set_parameter()
void ScriptInterface::System::SystemFacade::do_set_parameter (const std::string & name, const Variant & v) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 52 of file SystemFacade.hpp.
References ScriptInterface::ObjectHandle::name().
get_parameter()
Variant ScriptInterface::System::SystemFacade::get_parameter (const std::string & name) const inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 49 of file SystemFacade.hpp.
References ScriptInterface::ObjectHandle::name().
valid_parameters()
Utils::Span<const boost::string_ref> ScriptInterface::System::SystemFacade::valid_parameters () const inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 55 of file SystemFacade.hpp.
The documentation for this class was generated from the following file:
SystemFacade.hpp