ESPResSo: walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA Class Reference
walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA Class Reference
#include <DiffusiveFluxKernelThermalized_single_precision_CUDA.h>
Public Member Functions
DiffusiveFluxKernelThermalized_single_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_, float D, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, uint32_t seed, uint32_t time_step)
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
float getD () const
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
uint32_t getField_size_0 () const
uint32_t getField_size_1 () const
uint32_t getField_size_2 () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setD (const float value)
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setField_size_0 (const uint32_t value)
void setField_size_1 (const uint32_t value)
void setField_size_2 (const uint32_t value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< DiffusiveFluxKernelThermalized_single_precision_CUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelThermalized_single_precision_CUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 55 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
Constructor & Destructor Documentation
DiffusiveFluxKernelThermalized_single_precision_CUDA()
walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::DiffusiveFluxKernelThermalized_single_precision_CUDA (BlockDataID jID_, BlockDataID rhoID_, float D, uint32_t field_size_0, uint32_t field_size_1, uint32_t field_size_2, uint32_t seed, uint32_t time_step) inline
Definition at line 57 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 111 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
References stream.
getBlock_offset_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getBlock_offset_0 () const inline
Definition at line 121 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getBlock_offset_1 () const inline
Definition at line 122 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getBlock_offset_2 () const inline
Definition at line 123 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getD()
float walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getD () const inline
Definition at line 120 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getField_size_0()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getField_size_0 () const inline
Definition at line 124 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getField_size_1()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getField_size_1 () const inline
Definition at line 125 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getField_size_2()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getField_size_2 () const inline
Definition at line 126 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getSeed()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getSeed () const inline
Definition at line 127 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getSweep (const shared_ptr< DiffusiveFluxKernelThermalized_single_precision_CUDA > & kernel) inline static
Definition at line 78 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 96 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< DiffusiveFluxKernelThermalized_single_precision_CUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 84 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 101 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::getTime_step () const inline
Definition at line 128 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
operator()()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 74 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 424 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 466 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.cu.
References block(), RESTRICT, and stream.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 130 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setBlock_offset_1()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 133 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setBlock_offset_2()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 136 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setD()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setD (const float value) inline
Definition at line 129 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setField_size_0()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setField_size_0 (const uint32_t value) inline
Definition at line 139 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setField_size_1()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setField_size_1 (const uint32_t value) inline
Definition at line 140 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setField_size_2()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setField_size_2 (const uint32_t value) inline
Definition at line 141 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setSeed()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setSeed (const uint32_t value) inline
Definition at line 142 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
setTime_step()
void walberla::pystencils::DiffusiveFluxKernelThermalized_single_precision_CUDA::setTime_step (const uint32_t value) inline
Definition at line 143 of file DiffusiveFluxKernelThermalized_single_precision_CUDA.h.
The documentation for this class was generated from the following files:
DiffusiveFluxKernelThermalized_single_precision_CUDA.h
DiffusiveFluxKernelThermalized_single_precision_CUDA.cu