ESPResSo: P3MFFT< FloatType > Class Template Reference
P3MFFT< FloatType > Class Template Reference
#include <P3MFFT.hpp>
Public Member Functions
P3MFFT (boost::mpi::communicator comm, Utils::Vector3i const &global_mesh, Utils::Vector3i const &rs_local_ld_index, Utils::Vector3i const &rs_local_ur_index, Utils::Vector3i const &memory_layout)
void set_preferred_kspace_decomposition (Utils::Vector3i const &node_grid)
void init_fft ()
Utils::Vector3i ks_local_ld_index () const
Utils::Vector3i ks_local_ur_index () const
Utils::Vector3i ks_local_size () const
template<typename In , typename Out >
void forward (In in, Out out)
template<typename T1 , typename T2 >
auto backward (T1 &in, T2 &out)
auto const & get_memory_layout () const
Detailed Description
template<typename FloatType>
class P3MFFT< FloatType >
Definition at line 41 of file P3MFFT.hpp.
Constructor & Destructor Documentation
P3MFFT()
template<typename FloatType > P3MFFT< FloatType >::P3MFFT (boost::mpi::communicator comm, Utils::Vector3i const & global_mesh, Utils::Vector3i const & rs_local_ld_index, Utils::Vector3i const & rs_local_ur_index, Utils::Vector3i const & memory_layout) inline
Definition at line 54 of file P3MFFT.hpp.
References P3MFFT< FloatType >::init_fft().
Member Function Documentation
backward()
template<typename FloatType > template<typename T1 , typename T2 > auto P3MFFT< FloatType >::backward (T1 & in, T2 & out) inline
Definition at line 126 of file P3MFFT.hpp.
References stream.
forward()
template<typename FloatType > template<typename In , typename Out > void P3MFFT< FloatType >::forward (In in, Out out) inline
Definition at line 123 of file P3MFFT.hpp.
References stream.
get_memory_layout()
template<typename FloatType > auto const & P3MFFT< FloatType >::get_memory_layout () const inline
Definition at line 129 of file P3MFFT.hpp.
init_fft()
template<typename FloatType > void P3MFFT< FloatType >::init_fft () inline
Definition at line 89 of file P3MFFT.hpp.
References stream.
Referenced by P3MFFT< FloatType >::P3MFFT(), and P3MFFT< FloatType >::set_preferred_kspace_decomposition().
ks_local_ld_index()
template<typename FloatType > Utils::Vector3i P3MFFT< FloatType >::ks_local_ld_index () const inline
Definition at line 114 of file P3MFFT.hpp.
Referenced by P3MFFT< FloatType >::ks_local_size().
ks_local_size()
template<typename FloatType > Utils::Vector3i P3MFFT< FloatType >::ks_local_size () const inline
Definition at line 120 of file P3MFFT.hpp.
References P3MFFT< FloatType >::ks_local_ld_index(), and P3MFFT< FloatType >::ks_local_ur_index().
ks_local_ur_index()
template<typename FloatType > Utils::Vector3i P3MFFT< FloatType >::ks_local_ur_index () const inline
Definition at line 117 of file P3MFFT.hpp.
References Utils::Vector< T, N >::broadcast().
Referenced by P3MFFT< FloatType >::ks_local_size().
set_preferred_kspace_decomposition()
template<typename FloatType > void P3MFFT< FloatType >::set_preferred_kspace_decomposition (Utils::Vector3i const & node_grid) inline
Definition at line 71 of file P3MFFT.hpp.
References Utils::Vector< T, N >::broadcast(), P3MFFT< FloatType >::init_fft(), Utils::product(), stream, and to_array().
The documentation for this class was generated from the following files:
p3m.impl.hpp
P3MFFT.hpp