ESPResSo: walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA Class Reference
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA Class Reference
#include <StreamCollideSweepDoublePrecisionThermalizedCUDA.h>
Public Member Functions
StreamCollideSweepDoublePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step)
~StreamCollideSweepDoublePrecisionThermalizedCUDA ()
void run (IBlock *block, gpuStream_t stream=nullptr)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block, gpuStream_t stream=nullptr)
void operator() (IBlock *block, gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweep (gpuStream_t stream=nullptr)
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1, gpuStream_t stream=nullptr)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
uint32_t getBlock_offset_0 () const
uint32_t getBlock_offset_1 () const
uint32_t getBlock_offset_2 () const
double getKt () const
double getOmega_bulk () const
double getOmega_even () const
double getOmega_odd () const
double getOmega_shear () const
uint32_t getSeed () const
uint32_t getTime_step () const
void setBlock_offset_0 (const uint32_t value)
void setBlock_offset_1 (const uint32_t value)
void setBlock_offset_2 (const uint32_t value)
void setKt (const double value)
void setOmega_bulk (const double value)
void setOmega_even (const double value)
void setOmega_odd (const double value)
void setOmega_shear (const double value)
void setSeed (const uint32_t value)
void setTime_step (const uint32_t value)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedCUDA > &kernel)
static std::function< void(IBlock *, gpuStream_t)> getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedCUDA > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Detailed Description
Definition at line 57 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
Constructor & Destructor Documentation
StreamCollideSweepDoublePrecisionThermalizedCUDA()
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::StreamCollideSweepDoublePrecisionThermalizedCUDA (BlockDataID forceID_, BlockDataID pdfsID_, double kT, double omega_bulk, double omega_even, double omega_odd, double omega_shear, uint32_t seed, uint32_t time_step) inline
Definition at line 59 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
~StreamCollideSweepDoublePrecisionThermalizedCUDA()
walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::~StreamCollideSweepDoublePrecisionThermalizedCUDA () inline
Definition at line 69 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 119 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getBlock_offset_0()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getBlock_offset_0 () const inline
Definition at line 128 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getBlock_offset_1()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getBlock_offset_1 () const inline
Definition at line 129 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getBlock_offset_2()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getBlock_offset_2 () const inline
Definition at line 130 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getKt()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getKt () const inline
Definition at line 131 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_bulk()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getOmega_bulk () const inline
Definition at line 132 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_even()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getOmega_even () const inline
Definition at line 133 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_odd()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getOmega_odd () const inline
Definition at line 134 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getOmega_shear()
double walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getOmega_shear () const inline
Definition at line 135 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getSeed()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getSeed () const inline
Definition at line 136 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getSweep() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getSweep (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedCUDA > & kernel) inline static
Definition at line 87 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
getSweep() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getSweep (gpuStream_t stream = nullptr) inline
Definition at line 104 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
References run(), and stream.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *, gpuStream_t)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< StreamCollideSweepDoublePrecisionThermalizedCUDA > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 92 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
References stream.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1, gpuStream_t stream = nullptr) inline
Definition at line 109 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
References runOnCellInterval(), and stream.
getTime_step()
uint32_t walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::getTime_step () const inline
Definition at line 137 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
operator()()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::operator() (IBlock * block, gpuStream_t stream = nullptr) inline
Definition at line 82 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
References block(), run(), and stream.
run()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::run (IBlock * block, gpuStream_t stream = nullptr)
Definition at line 417 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block, gpuStream_t stream = nullptr)
Definition at line 479 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.cu.
References block(), and RESTRICT.
Referenced by getSweepOnCellInterval().
setBlock_offset_0()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setBlock_offset_0 (const uint32_t value) inline
Definition at line 138 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setBlock_offset_1()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setBlock_offset_1 (const uint32_t value) inline
Definition at line 141 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setBlock_offset_2()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setBlock_offset_2 (const uint32_t value) inline
Definition at line 144 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setKt()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setKt (const double value) inline
Definition at line 147 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_bulk()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setOmega_bulk (const double value) inline
Definition at line 148 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_even()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setOmega_even (const double value) inline
Definition at line 149 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_odd()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setOmega_odd (const double value) inline
Definition at line 150 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setOmega_shear()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setOmega_shear (const double value) inline
Definition at line 151 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setSeed()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setSeed (const uint32_t value) inline
Definition at line 152 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
setTime_step()
void walberla::pystencils::StreamCollideSweepDoublePrecisionThermalizedCUDA::setTime_step (const uint32_t value) inline
Definition at line 153 of file StreamCollideSweepDoublePrecisionThermalizedCUDA.h.
The documentation for this class was generated from the following files:
StreamCollideSweepDoublePrecisionThermalizedCUDA.h
StreamCollideSweepDoublePrecisionThermalizedCUDA.cu