ESPResSo: walberla::pystencils::ContinuityKernel_single_precision Class Reference
walberla::pystencils::ContinuityKernel_single_precision Class Reference
#include <ContinuityKernel_single_precision.h>
Public Member Functions
ContinuityKernel_single_precision (BlockDataID jID_, BlockDataID rhoID_)
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< ContinuityKernel_single_precision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< ContinuityKernel_single_precision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID jID
BlockDataID rhoID
Detailed Description
Definition at line 53 of file ContinuityKernel_single_precision.h.
Constructor & Destructor Documentation
ContinuityKernel_single_precision()
walberla::pystencils::ContinuityKernel_single_precision::ContinuityKernel_single_precision (BlockDataID jID_, BlockDataID rhoID_) inline
Definition at line 55 of file ContinuityKernel_single_precision.h.
Member Function Documentation
configure()
void walberla::pystencils::ContinuityKernel_single_precision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 93 of file ContinuityKernel_single_precision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision::getSweep () inline
Definition at line 80 of file ContinuityKernel_single_precision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision::getSweep (const shared_ptr< ContinuityKernel_single_precision > & kernel) inline static
Definition at line 67 of file ContinuityKernel_single_precision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision::getSweepOnCellInterval (const shared_ptr< ContinuityKernel_single_precision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 71 of file ContinuityKernel_single_precision.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::ContinuityKernel_single_precision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 85 of file ContinuityKernel_single_precision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::ContinuityKernel_single_precision::operator() (IBlock * block) inline
Definition at line 64 of file ContinuityKernel_single_precision.h.
References block(), and run().
run()
void walberla::pystencils::ContinuityKernel_single_precision::run (IBlock * block)
Definition at line 60 of file ContinuityKernel_single_precision.cpp.
References block(), walberla::pystencils::internal_990034b4e4dd57d2802b4bcb5f716e46::continuitykernel_single_precision_continuitykernel_single_precision(), jID, RESTRICT, and rhoID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::ContinuityKernel_single_precision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 85 of file ContinuityKernel_single_precision.cpp.
References block(), walberla::pystencils::internal_990034b4e4dd57d2802b4bcb5f716e46::continuitykernel_single_precision_continuitykernel_single_precision(), jID, RESTRICT, and rhoID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
jID
BlockDataID walberla::pystencils::ContinuityKernel_single_precision::jID
Definition at line 96 of file ContinuityKernel_single_precision.h.
Referenced by run(), and runOnCellInterval().
rhoID
BlockDataID walberla::pystencils::ContinuityKernel_single_precision::rhoID
Definition at line 97 of file ContinuityKernel_single_precision.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
ContinuityKernel_single_precision.h
ContinuityKernel_single_precision.cpp