ESPResSo: ScriptInterface::CollisionDetection::Protocol Class Reference
ScriptInterface::CollisionDetection::Protocol Class Reference abstract
#include <Protocol.hpp>
Public Member Functions
virtual std::shared_ptr<::CollisionDetection::ActiveProtocol > protocol ()=0
void bind_bonded_ias (std::weak_ptr< BondedInteractionsMap > bonded_ias, std::weak_ptr< Interactions::BondedInteractions > so_bonded_ias)
void do_construct (VariantMap const &params) override
Public Member Functions inherited from ScriptInterface::AutoParameters< Protocol >
std::vector< std::string_view > valid_parameters () const final
Variant get_parameter (const std::string &name) const final
void do_set_parameter (const std::string &name, const Variant &value) final
std::vector< std::pair< std::string, Variant > > serialize_parameters () const final
Public Member Functions inherited from ScriptInterface::ObjectHandle
ObjectHandle ()=default
ObjectHandle (ObjectHandle const &)=delete
ObjectHandle & operator= (ObjectHandle const &)=delete
virtual ~ObjectHandle ()=default
std::string_view name () const
Context * context () const
Responsible context.
void construct (VariantMap const &params)
Construct the handled object.
VariantMap get_parameters () const
Get current parameters.
void set_parameter (const std::string &name, const Variant &value)
Set single parameter.
Variant call_method (const std::string &name, const VariantMap &params)
Call a method on the object.
virtual Variant do_call_method (const std::string &, const VariantMap &)
Local implementation of call_method.
std::string serialize () const
Protected Member Functions
auto find_bond_id (Variant const &v) const
auto get_bond_variant_by_id (int bond_id)
virtual void do_initialize (VariantMap const &params)=0
Protected Member Functions inherited from ScriptInterface::AutoParameters< Protocol >
AutoParameters ()=default
AutoParameters (std::vector< AutoParameter > &&params)
~AutoParameters () override=default
bool has_parameter (std::string const &name) const override
void add_parameters (std::vector< AutoParameter > &&params)
auto const & get_parameter_insertion_order () const
Additional Inherited Members
Static Public Member Functions inherited from ScriptInterface::ObjectHandle
static ObjectRef deserialize (const std::string &state, Context &ctx)
Make object from serialized state.
Detailed Description
Definition at line 42 of file collision_detection/Protocol.hpp.
Member Function Documentation
bind_bonded_ias()
void ScriptInterface::CollisionDetection::Protocol::bind_bonded_ias (std::weak_ptr< BondedInteractionsMap > bonded_ias, std::weak_ptr< Interactions::BondedInteractions > so_bonded_ias) inline
Definition at line 49 of file collision_detection/Protocol.hpp.
References do_initialize(), and stream.
do_construct()
void ScriptInterface::CollisionDetection::Protocol::do_construct (VariantMap const & params) inline override virtual
Reimplemented from ScriptInterface::ObjectHandle.
Definition at line 60 of file collision_detection/Protocol.hpp.
do_initialize()
virtual void ScriptInterface::CollisionDetection::Protocol::do_initialize (VariantMap const & params) protected pure virtual
Implemented in ScriptInterface::CollisionDetection::Off, ScriptInterface::CollisionDetection::BindAtPointOfCollision, ScriptInterface::CollisionDetection::BindCenters, and ScriptInterface::CollisionDetection::GlueToSurface.
Referenced by bind_bonded_ias().
find_bond_id()
auto ScriptInterface::CollisionDetection::Protocol::find_bond_id (Variant const & v) const inline protected
Definition at line 65 of file collision_detection/Protocol.hpp.
References stream.
Referenced by ScriptInterface::CollisionDetection::BindAtPointOfCollision::do_initialize(), ScriptInterface::CollisionDetection::BindCenters::do_initialize(), and ScriptInterface::CollisionDetection::GlueToSurface::do_initialize().
get_bond_variant_by_id()
auto ScriptInterface::CollisionDetection::Protocol::get_bond_variant_by_id (int bond_id) inline protected
Definition at line 84 of file collision_detection/Protocol.hpp.
References stream.
Referenced by ScriptInterface::CollisionDetection::BindAtPointOfCollision::BindAtPointOfCollision(), ScriptInterface::CollisionDetection::BindCenters::BindCenters(), and ScriptInterface::CollisionDetection::GlueToSurface::GlueToSurface().
protocol()
virtual std::shared_ptr<::CollisionDetection::ActiveProtocol > ScriptInterface::CollisionDetection::Protocol::protocol () pure virtual
Implemented in ScriptInterface::CollisionDetection::BindAtPointOfCollision, ScriptInterface::CollisionDetection::BindCenters, ScriptInterface::CollisionDetection::GlueToSurface, and ScriptInterface::CollisionDetection::Off.
The documentation for this class was generated from the following file:
collision_detection/Protocol.hpp