ESPResSo: walberla::pystencils::StreamSweepSinglePrecision Class Reference
walberla::pystencils::StreamSweepSinglePrecision Class Reference
#include <StreamSweepSinglePrecision.h>
Public Member Functions
StreamSweepSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_)
~StreamSweepSinglePrecision ()
void run (IBlock *block)
void runOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers, IBlock *block)
void operator() (IBlock *block)
std::function< void(IBlock *)> getSweep ()
std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
void configure (const shared_ptr< StructuredBlockStorage > &blocks, IBlock *block)
Static Public Member Functions
static std::function< void(IBlock *)> getSweep (const shared_ptr< StreamSweepSinglePrecision > &kernel)
static std::function< void(IBlock *)> getSweepOnCellInterval (const shared_ptr< StreamSweepSinglePrecision > &kernel, const shared_ptr< StructuredBlockStorage > &blocks, const CellInterval &globalCellInterval, cell_idx_t ghostLayers=1)
Public Attributes
BlockDataID forceID
BlockDataID pdfsID
BlockDataID velocityID
Detailed Description
Definition at line 53 of file StreamSweepSinglePrecision.h.
Constructor & Destructor Documentation
StreamSweepSinglePrecision()
walberla::pystencils::StreamSweepSinglePrecision::StreamSweepSinglePrecision (BlockDataID forceID_, BlockDataID pdfsID_, BlockDataID velocityID_) inline
Definition at line 55 of file StreamSweepSinglePrecision.h.
~StreamSweepSinglePrecision()
walberla::pystencils::StreamSweepSinglePrecision::~StreamSweepSinglePrecision () inline
Definition at line 59 of file StreamSweepSinglePrecision.h.
Member Function Documentation
configure()
void walberla::pystencils::StreamSweepSinglePrecision::configure (const shared_ptr< StructuredBlockStorage > & blocks, IBlock * block) inline
Definition at line 101 of file StreamSweepSinglePrecision.h.
getSweep() [1/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecision::getSweep () inline
Definition at line 88 of file StreamSweepSinglePrecision.h.
References run().
getSweep() [2/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecision::getSweep (const shared_ptr< StreamSweepSinglePrecision > & kernel) inline static
Definition at line 74 of file StreamSweepSinglePrecision.h.
getSweepOnCellInterval() [1/2]
static std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecision::getSweepOnCellInterval (const shared_ptr< StreamSweepSinglePrecision > & kernel, const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline static
Definition at line 79 of file StreamSweepSinglePrecision.h.
getSweepOnCellInterval() [2/2]
std::function< void(IBlock *)> walberla::pystencils::StreamSweepSinglePrecision::getSweepOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers = 1) inline
Definition at line 93 of file StreamSweepSinglePrecision.h.
References runOnCellInterval().
operator()()
void walberla::pystencils::StreamSweepSinglePrecision::operator() (IBlock * block) inline
Definition at line 71 of file StreamSweepSinglePrecision.h.
References block(), and run().
run()
void walberla::pystencils::StreamSweepSinglePrecision::run (IBlock * block)
Definition at line 110 of file StreamSweepSinglePrecision.cpp.
References block(), forceID, pdfsID, RESTRICT, walberla::pystencils::internal_streamsweepsingleprecision_streamsweepsingleprecision::streamsweepsingleprecision_streamsweepsingleprecision(), velocity(), and velocityID.
Referenced by getSweep(), and operator()().
runOnCellInterval()
void walberla::pystencils::StreamSweepSinglePrecision::runOnCellInterval (const shared_ptr< StructuredBlockStorage > & blocks, const CellInterval & globalCellInterval, cell_idx_t ghostLayers, IBlock * block)
Definition at line 168 of file StreamSweepSinglePrecision.cpp.
References block(), forceID, pdfsID, RESTRICT, walberla::pystencils::internal_streamsweepsingleprecision_streamsweepsingleprecision::streamsweepsingleprecision_streamsweepsingleprecision(), velocity(), and velocityID.
Referenced by getSweepOnCellInterval().
Member Data Documentation
forceID
BlockDataID walberla::pystencils::StreamSweepSinglePrecision::forceID
Definition at line 104 of file StreamSweepSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
pdfsID
BlockDataID walberla::pystencils::StreamSweepSinglePrecision::pdfsID
Definition at line 105 of file StreamSweepSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
velocityID
BlockDataID walberla::pystencils::StreamSweepSinglePrecision::velocityID
Definition at line 106 of file StreamSweepSinglePrecision.h.
Referenced by run(), and runOnCellInterval().
The documentation for this class was generated from the following files:
StreamSweepSinglePrecision.h
StreamSweepSinglePrecision.cpp