ESPResSo: ParticleRange Class Reference
ParticleRange Class Reference
A range of particles.
#include <ParticleRange.hpp>
Public Member Functions
base_type::size_type size () const
template<typename Predicate >
ParticleRangeFiltered< Predicate > filter (Predicate pred) const
Detailed Description
A range of particles.
This is a boost::iterator_range with the addition that the size of the range is cached.
Definition at line 38 of file ParticleRange.hpp.
Member Function Documentation
filter()
template<typename Predicate > ParticleRangeFiltered< Predicate > ParticleRange::filter (Predicate pred) const inline
Definition at line 53 of file ParticleRange.hpp.
References stream.
Referenced by integrator_step_1(), and integrator_step_2().
size()
base_type::size_type ParticleRange::size () const inline
Definition at line 44 of file ParticleRange.hpp.
References stream.
Referenced by DipolarLayerCorrection::add_force_corrections(), calc_sc_cache(), DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::calc_surface_term(), dipolar_force_corrections(), gather_particle_data(), Mpiio::mpi_mpiio_common_write(), StokesianDynamics::propagate_vel_pos(), reduce_over_local_particles(), setup_PoQ(), setup_PQ(), GpuParticleData::Storage::split_particle_struct(), Writer::H5md::File::write(), and Writer::H5md::write_td_particle_property().
The documentation for this class was generated from the following file:
ParticleRange.hpp