ESPResSo: walberla::pystencils::PackInfoPdfDoublePrecisionCUDA Class Reference
walberla::pystencils::PackInfoPdfDoublePrecisionCUDA Class Reference
#include <PackInfoPdfDoublePrecisionCUDA.h>
Public Member Functions
PackInfoPdfDoublePrecisionCUDA (BlockDataID pdfsID_)
~PackInfoPdfDoublePrecisionCUDA () override=default
void pack (stencil::Direction dir, unsigned char *buffer, IBlock *block, gpuStream_t stream) override
void communicateLocal (stencil::Direction, const IBlock *, IBlock *, gpuStream_t) override
void unpack (stencil::Direction dir, unsigned char *buffer, IBlock *block, gpuStream_t stream) override
uint_t size (stencil::Direction dir, IBlock *block) override
Detailed Description
Definition at line 39 of file PackInfoPdfDoublePrecisionCUDA.h.
Constructor & Destructor Documentation
PackInfoPdfDoublePrecisionCUDA()
walberla::pystencils::PackInfoPdfDoublePrecisionCUDA::PackInfoPdfDoublePrecisionCUDA (BlockDataID pdfsID_) inline
Definition at line 42 of file PackInfoPdfDoublePrecisionCUDA.h.
~PackInfoPdfDoublePrecisionCUDA()
walberla::pystencils::PackInfoPdfDoublePrecisionCUDA::~PackInfoPdfDoublePrecisionCUDA () override default
Member Function Documentation
communicateLocal()
void walberla::pystencils::PackInfoPdfDoublePrecisionCUDA::communicateLocal (stencil::Direction , const IBlock * , IBlock * , gpuStream_t) inline override
Definition at line 47 of file PackInfoPdfDoublePrecisionCUDA.h.
References stream.
pack()
void walberla::pystencils::PackInfoPdfDoublePrecisionCUDA::pack (stencil::Direction dir, unsigned char * buffer, IBlock * block, gpuStream_t stream) override
Definition at line 521 of file PackInfoPdfDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
size()
uint_t walberla::pystencils::PackInfoPdfDoublePrecisionCUDA::size (stencil::Direction dir, IBlock * block) override
Definition at line 1342 of file PackInfoPdfDoublePrecisionCUDA.cu.
References block(), and stream.
unpack()
void walberla::pystencils::PackInfoPdfDoublePrecisionCUDA::unpack (stencil::Direction dir, unsigned char * buffer, IBlock * block, gpuStream_t stream) override
Definition at line 931 of file PackInfoPdfDoublePrecisionCUDA.cu.
References block(), RESTRICT, and stream.
The documentation for this class was generated from the following files:
PackInfoPdfDoublePrecisionCUDA.h
PackInfoPdfDoublePrecisionCUDA.cu