ESPResSo: LBWalberlaBase Class Reference
LBWalberlaBase Class Reference abstract
Interface of a lattice-based fluid model.
#include <LBWalberlaBase.hpp>
Public Member Functions
~LBWalberlaBase () override=default
virtual void integrate ()=0
Integrate LB for one time step.
virtual void ghost_communication ()=0
Perform a full ghost communication.
virtual void ghost_communication_pdf ()=0
Perform a ghost communication of the PDF field.
virtual void ghost_communication_vel ()=0
Perform a ghost communication of the velocity field.
virtual void ghost_communication_laf ()=0
Perform a ghost communication of the last applied forces field.
virtual std::size_t stencil_size () const noexcept=0
Number of discretized velocities in the PDF.
virtual bool is_double_precision () const noexcept=0
Whether kernels use double-precision floating point numbers.
virtual std::function< bool(Utils::Vector3d const &)> make_lattice_position_checker (bool consider_points_in_halo) const =0
Make a functor to check if a position is in the local domain.
virtual std::optional< Utils::Vector3d > get_velocity_at_pos (Utils::Vector3d const &position, bool consider_points_in_halo=false) const =0
Get interpolated velocities at a position.
virtual std::vector< Utils::Vector3d > get_velocities_at_pos (std::vector< Utils::Vector3d > const &pos)=0
Get interpolated velocities at positions.
virtual std::optional< double > get_density_at_pos (Utils::Vector3d const &position, bool consider_points_in_halo=false) const =0
Get interpolated densities at a position.
virtual std::vector< double > get_densities_at_pos (std::vector< Utils::Vector3d > const &pos)=0
Get interpolated densities at positions.
virtual bool add_force_at_pos (Utils::Vector3d const &position, Utils::Vector3d const &force)=0
Interpolate a force to the stored forces to be applied on nodes in the next time step.
virtual void add_forces_at_pos (std::vector< Utils::Vector3d > const &positions, std::vector< Utils::Vector3d > const &forces)=0
Interpolate forces to the stored forces to be applied on nodes in the next time step.
virtual std::optional< Utils::Vector3d > get_node_force_to_be_applied (Utils::Vector3i const &node) const =0
Get stored force to be applied on node in the next time step.
virtual std::optional< Utils::Vector3d > get_node_last_applied_force (Utils::Vector3i const &node, bool consider_ghosts=false) const =0
Get stored force that was applied on node in the last time step.
virtual bool set_node_last_applied_force (Utils::Vector3i const &node, Utils::Vector3d const &force)=0
Set stored force that was applied on node in the last time step.
virtual std::vector< double > get_slice_last_applied_force (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Get stored force that was applied on slice in the last time step.
virtual void set_slice_last_applied_force (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &force)=0
Set stored force that was applied on slice in the last time step.
virtual std::optional< std::vector< double > > get_node_population (Utils::Vector3i const &node, bool consider_ghosts=false) const =0
Get node population.
virtual bool set_node_population (Utils::Vector3i const &node, std::vector< double > const &population)=0
Set node population.
virtual std::vector< double > get_slice_population (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Get slice population.
virtual void set_slice_population (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &population)=0
Set slice population.
virtual std::optional< Utils::Vector3d > get_node_velocity (Utils::Vector3i const &node, bool consider_ghosts=false) const =0
Get node velocity.
virtual bool set_node_velocity (Utils::Vector3i const &node, Utils::Vector3d const &v)=0
Set node velocity.
virtual std::vector< double > get_slice_velocity (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Get slice velocity.
virtual void set_slice_velocity (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &velocity)=0
Set slice velocity.
virtual std::optional< double > get_node_density (Utils::Vector3i const &node, bool consider_ghosts=false) const =0
Get node density.
virtual bool set_node_density (Utils::Vector3i const &node, double density)=0
Set node density.
virtual std::vector< double > get_slice_density (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Get slice density.
virtual void set_slice_density (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< double > const &density)=0
Set slice density.
virtual std::optional< Utils::Vector3d > get_node_velocity_at_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const =0
Get node velocity boundary conditions.
virtual bool set_node_velocity_at_boundary (Utils::Vector3i const &node, Utils::Vector3d const &velocity)=0
Set node velocity boundary conditions.
virtual std::vector< std::optional< Utils::Vector3d > > get_slice_velocity_at_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Get slice velocity boundary conditions.
virtual void set_slice_velocity_at_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< std::optional< Utils::Vector3d > > const &velocity)=0
Set slice velocity boundary conditions.
virtual std::optional< Utils::Vector3d > get_node_boundary_force (Utils::Vector3i const &node) const =0
Get (stored) force applied on node due to boundary condition.
virtual bool remove_node_from_boundary (Utils::Vector3i const &node)=0
Remove a node from the boundaries.
virtual std::optional< bool > get_node_is_boundary (Utils::Vector3i const &node, bool consider_ghosts=false) const =0
Check if node has velocity boundary conditions.
virtual std::vector< bool > get_slice_is_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Check if slice has velocity boundary conditions.
virtual void reallocate_ubb_field ()=0
Rebuild the UBB field.
virtual void clear_boundaries ()=0
Clear the boundary flag field and the UBB field.
virtual void update_boundary_from_shape (std::vector< int > const &, std::vector< double > const &)=0
Update boundary conditions from a rasterized shape.
virtual void set_collision_model (double kT, unsigned int seed)=0
Configure the default collision model.
virtual void set_collision_model (std::unique_ptr< LeesEdwardsPack > &&lees_edwards_pack)=0
Configure a thermalized collision model for Lees-Edwards.
virtual void check_lebc (unsigned int shear_direction, unsigned int shear_plane_normal) const =0
Check Lees-Edwards boundary conditions.
virtual std::optional< Utils::VectorXd< 9 > > get_node_pressure_tensor (Utils::Vector3i const &node) const =0
Get node pressure tensor.
virtual std::vector< double > get_slice_pressure_tensor (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const =0
Get slice pressure tensor.
virtual Utils::Vector3d get_boundary_force_from_shape (std::vector< int > const &raster_flat) const =0
Calculate boundary force from a rasterized shape.
virtual Utils::Vector3d get_boundary_force () const =0
Calculate boundary force of the local domain.
virtual Utils::VectorXd< 9 > get_pressure_tensor () const =0
Calculate average pressure tensor of the local domain.
virtual Utils::Vector3d get_momentum () const =0
Calculate momentum of the local domain.
virtual void set_external_force (Utils::Vector3d const &ext_force)=0
Set a global external force.
virtual Utils::Vector3d get_external_force () const noexcept=0
Get the global external force.
virtual void set_viscosity (double viscosity)=0
Set the fluid viscosity.
virtual double get_viscosity () const noexcept=0
Get the fluid viscosity.
virtual double get_density () const noexcept=0
Get the fluid density.
virtual double get_kT () const noexcept=0
Get the fluid temperature (if thermalized).
virtual unsigned int get_seed () const noexcept=0
Get the RNG seed (if thermalized).
virtual std::optional< uint64_t > get_rng_state () const =0
Set the RNG counter (if thermalized).
virtual void set_rng_state (uint64_t counter)=0
Set the RNG counter (if thermalized).
virtual std::size_t get_velocity_field_id () const noexcept=0
Get the velocity field id.
virtual std::size_t get_force_field_id () const noexcept=0
Get the force field id.
virtual bool is_gpu () const noexcept=0
Get whether the kernels run on GPUs.
Public Member Functions inherited from LatticeModel
virtual ~LatticeModel ()=default
virtual LatticeWalberla const & get_lattice () const noexcept=0
Get the underlying lattice.
std::shared_ptr< VTKHandle > create_vtk (int delta_N, int initial_count, int flag_observables, units_map const &units_conversion, std::string const &identifier, std::string const &base_folder, std::string const &prefix, bool force_pvtu)
Create a VTK observable.
void write_vtk (std::string const &vtk_uid)
Write a VTK observable to disk.
void switch_vtk (std::string const &vtk_uid, bool status)
Toggle a VTK observable on/off.
Additional Inherited Members
Public Types inherited from LatticeModel
using units_map = std::unordered_map< std::string, double >
Protected Member Functions inherited from LatticeModel
virtual void register_vtk_field_writers (walberla::vtk::VTKOutput &vtk_obj, units_map const &units_conversion, int flag_observables)=0
Register VTK writers.
virtual void register_vtk_field_filters (walberla::vtk::VTKOutput &vtk_obj)=0
virtual void integrate_vtk_writers ()=0
Protected Attributes inherited from LatticeModel
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_auto
VTK writers that are executed automatically.
std::map< std::string, std::shared_ptr< VTKHandle > > m_vtk_manual
VTK writers that are executed manually.
Detailed Description
Interface of a lattice-based fluid model.
Definition at line 42 of file LBWalberlaBase.hpp.
Constructor & Destructor Documentation
~LBWalberlaBase()
LBWalberlaBase::~LBWalberlaBase () override default
Member Function Documentation
add_force_at_pos()
virtual bool LBWalberlaBase::add_force_at_pos (Utils::Vector3d const & position, Utils::Vector3d const & force) pure virtual
Interpolate a force to the stored forces to be applied on nodes in the next time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
add_forces_at_pos()
virtual void LBWalberlaBase::add_forces_at_pos (std::vector< Utils::Vector3d > const & positions, std::vector< Utils::Vector3d > const & forces) pure virtual
Interpolate forces to the stored forces to be applied on nodes in the next time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
check_lebc()
virtual void LBWalberlaBase::check_lebc (unsigned int shear_direction, unsigned int shear_plane_normal) const pure virtual
Check Lees-Edwards boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
clear_boundaries()
virtual void LBWalberlaBase::clear_boundaries () pure virtual
Clear the boundary flag field and the UBB field.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_boundary_force()
virtual Utils::Vector3d LBWalberlaBase::get_boundary_force () const pure virtual
Calculate boundary force of the local domain.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_boundary_force_from_shape()
virtual Utils::Vector3d LBWalberlaBase::get_boundary_force_from_shape (std::vector< int > const & raster_flat) const pure virtual
Calculate boundary force from a rasterized shape.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_densities_at_pos()
virtual std::vector< double > LBWalberlaBase::get_densities_at_pos (std::vector< Utils::Vector3d > const & pos) pure virtual
Get interpolated densities at positions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_density()
virtual double LBWalberlaBase::get_density () const pure virtual noexcept
Get the fluid density.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_density_at_pos()
virtual std::optional< double > LBWalberlaBase::get_density_at_pos (Utils::Vector3d const & position, bool consider_points_in_halo = false) const pure virtual
Get interpolated densities at a position.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_external_force()
virtual Utils::Vector3d LBWalberlaBase::get_external_force () const pure virtual noexcept
Get the global external force.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_force_field_id()
virtual std::size_t LBWalberlaBase::get_force_field_id () const pure virtual noexcept
Get the force field id.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_kT()
virtual double LBWalberlaBase::get_kT () const pure virtual noexcept
Get the fluid temperature (if thermalized).
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_momentum()
virtual Utils::Vector3d LBWalberlaBase::get_momentum () const pure virtual
Calculate momentum of the local domain.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_boundary_force()
virtual std::optional< Utils::Vector3d > LBWalberlaBase::get_node_boundary_force (Utils::Vector3i const & node) const pure virtual
Get (stored) force applied on node due to boundary condition.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_density()
virtual std::optional< double > LBWalberlaBase::get_node_density (Utils::Vector3i const & node, bool consider_ghosts = false) const pure virtual
Get node density.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_force_to_be_applied()
virtual std::optional< Utils::Vector3d > LBWalberlaBase::get_node_force_to_be_applied (Utils::Vector3i const & node) const pure virtual
Get stored force to be applied on node in the next time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_is_boundary()
virtual std::optional< bool > LBWalberlaBase::get_node_is_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const pure virtual
Check if node has velocity boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_last_applied_force()
virtual std::optional< Utils::Vector3d > LBWalberlaBase::get_node_last_applied_force (Utils::Vector3i const & node, bool consider_ghosts = false) const pure virtual
Get stored force that was applied on node in the last time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_population()
virtual std::optional< std::vector< double > > LBWalberlaBase::get_node_population (Utils::Vector3i const & node, bool consider_ghosts = false) const pure virtual
Get node population.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_pressure_tensor()
virtual std::optional< Utils::VectorXd< 9 > > LBWalberlaBase::get_node_pressure_tensor (Utils::Vector3i const & node) const pure virtual
Get node pressure tensor.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_velocity()
virtual std::optional< Utils::Vector3d > LBWalberlaBase::get_node_velocity (Utils::Vector3i const & node, bool consider_ghosts = false) const pure virtual
Get node velocity.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_node_velocity_at_boundary()
virtual std::optional< Utils::Vector3d > LBWalberlaBase::get_node_velocity_at_boundary (Utils::Vector3i const & node, bool consider_ghosts = false) const pure virtual
Get node velocity boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_pressure_tensor()
virtual Utils::VectorXd< 9 > LBWalberlaBase::get_pressure_tensor () const pure virtual
Calculate average pressure tensor of the local domain.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_rng_state()
virtual std::optional< uint64_t > LBWalberlaBase::get_rng_state () const pure virtual
Set the RNG counter (if thermalized).
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_seed()
virtual unsigned int LBWalberlaBase::get_seed () const pure virtual noexcept
Get the RNG seed (if thermalized).
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_slice_density()
virtual std::vector< double > LBWalberlaBase::get_slice_density (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Get slice density.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_slice_is_boundary()
virtual std::vector< bool > LBWalberlaBase::get_slice_is_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Check if slice has velocity boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_slice_last_applied_force()
virtual std::vector< double > LBWalberlaBase::get_slice_last_applied_force (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Get stored force that was applied on slice in the last time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_slice_population()
virtual std::vector< double > LBWalberlaBase::get_slice_population (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Get slice population.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_slice_pressure_tensor()
virtual std::vector< double > LBWalberlaBase::get_slice_pressure_tensor (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Get slice pressure tensor.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_slice_velocity()
virtual std::vector< double > LBWalberlaBase::get_slice_velocity (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Get slice velocity.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_slice_velocity_at_boundary()
virtual std::vector< std::optional< Utils::Vector3d > > LBWalberlaBase::get_slice_velocity_at_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const pure virtual
Get slice velocity boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
get_velocities_at_pos()
virtual std::vector< Utils::Vector3d > LBWalberlaBase::get_velocities_at_pos (std::vector< Utils::Vector3d > const & pos) pure virtual
Get interpolated velocities at positions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_velocity_at_pos()
virtual std::optional< Utils::Vector3d > LBWalberlaBase::get_velocity_at_pos (Utils::Vector3d const & position, bool consider_points_in_halo = false) const pure virtual
Get interpolated velocities at a position.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_velocity_field_id()
virtual std::size_t LBWalberlaBase::get_velocity_field_id () const pure virtual noexcept
Get the velocity field id.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
get_viscosity()
virtual double LBWalberlaBase::get_viscosity () const pure virtual noexcept
Get the fluid viscosity.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
ghost_communication()
virtual void LBWalberlaBase::ghost_communication () pure virtual
Perform a full ghost communication.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by LB::LBWalberla::update_collision_model().
ghost_communication_laf()
virtual void LBWalberlaBase::ghost_communication_laf () pure virtual
Perform a ghost communication of the last applied forces field.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
ghost_communication_pdf()
virtual void LBWalberlaBase::ghost_communication_pdf () pure virtual
Perform a ghost communication of the PDF field.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
ghost_communication_vel()
virtual void LBWalberlaBase::ghost_communication_vel () pure virtual
Perform a ghost communication of the velocity field.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
integrate()
virtual void LBWalberlaBase::integrate () pure virtual
Integrate LB for one time step.
The ghost layer may be out-of-date after integration. Call ghost_communication() to refresh them before calling any getter function that reads from the halo region.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
is_double_precision()
virtual bool LBWalberlaBase::is_double_precision () const pure virtual noexcept
Whether kernels use double-precision floating point numbers.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
is_gpu()
virtual bool LBWalberlaBase::is_gpu () const pure virtual noexcept
Get whether the kernels run on GPUs.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
make_lattice_position_checker()
virtual std::function< bool(Utils::Vector3d const &)> LBWalberlaBase::make_lattice_position_checker (bool consider_points_in_halo) const pure virtual
Make a functor to check if a position is in the local domain.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
reallocate_ubb_field()
virtual void LBWalberlaBase::reallocate_ubb_field () pure virtual
Rebuild the UBB field.
This is an expensive operation.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
remove_node_from_boundary()
virtual bool LBWalberlaBase::remove_node_from_boundary (Utils::Vector3i const & node) pure virtual
Remove a node from the boundaries.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_collision_model() [1/2]
virtual void LBWalberlaBase::set_collision_model (double kT, unsigned int seed) pure virtual
Configure the default collision model.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by LB::LBWalberla::update_collision_model().
set_collision_model() [2/2]
virtual void LBWalberlaBase::set_collision_model (std::unique_ptr< LeesEdwardsPack > && lees_edwards_pack) pure virtual
Configure a thermalized collision model for Lees-Edwards.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_external_force()
virtual void LBWalberlaBase::set_external_force (Utils::Vector3d const & ext_force) pure virtual
Set a global external force.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_node_density()
virtual bool LBWalberlaBase::set_node_density (Utils::Vector3i const & node, double density) pure virtual
Set node density.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_node_last_applied_force()
virtual bool LBWalberlaBase::set_node_last_applied_force (Utils::Vector3i const & node, Utils::Vector3d const & force) pure virtual
Set stored force that was applied on node in the last time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_node_population()
virtual bool LBWalberlaBase::set_node_population (Utils::Vector3i const & node, std::vector< double > const & population) pure virtual
Set node population.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_node_velocity()
virtual bool LBWalberlaBase::set_node_velocity (Utils::Vector3i const & node, Utils::Vector3d const & v) pure virtual
Set node velocity.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_node_velocity_at_boundary()
virtual bool LBWalberlaBase::set_node_velocity_at_boundary (Utils::Vector3i const & node, Utils::Vector3d const & velocity) pure virtual
Set node velocity boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_rng_state()
virtual void LBWalberlaBase::set_rng_state (uint64_t counter) pure virtual
Set the RNG counter (if thermalized).
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
set_slice_density()
virtual void LBWalberlaBase::set_slice_density (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & density) pure virtual
Set slice density.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
set_slice_last_applied_force()
virtual void LBWalberlaBase::set_slice_last_applied_force (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & force) pure virtual
Set stored force that was applied on slice in the last time step.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
set_slice_population()
virtual void LBWalberlaBase::set_slice_population (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & population) pure virtual
Set slice population.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
set_slice_velocity()
virtual void LBWalberlaBase::set_slice_velocity (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< double > const & velocity) pure virtual
Set slice velocity.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
set_slice_velocity_at_boundary()
virtual void LBWalberlaBase::set_slice_velocity_at_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< std::optional< Utils::Vector3d > > const & velocity) pure virtual
Set slice velocity boundary conditions.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
Referenced by ScriptInterface::walberla::LBFluidSlice::do_call_method().
set_viscosity()
virtual void LBWalberlaBase::set_viscosity (double viscosity) pure virtual
Set the fluid viscosity.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
stencil_size()
virtual std::size_t LBWalberlaBase::stencil_size () const pure virtual noexcept
Number of discretized velocities in the PDF.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
update_boundary_from_shape()
virtual void LBWalberlaBase::update_boundary_from_shape (std::vector< int > const & , std::vector< double > const &) pure virtual
Update boundary conditions from a rasterized shape.
Implemented in walberla::LBWalberlaImpl< FloatType, Architecture >.
The documentation for this class was generated from the following file:
LBWalberlaBase.hpp