ESPResSo: com.hpp File Reference
com.hpp File Reference
#include <config/config.hpp>
#include "BoxGeometry.hpp"
#include "cell_system/CellStructure.hpp"
#include <optional>
Functions
void vs_com_update_particles (CellStructure &cell_structure, BoxGeometry const &box_geo)
void vs_com_back_transfer_forces_and_torques (CellStructure &cell_structure)
std::optional< int > get_pid_for_vs_com (CellStructure &cell_structure, int mol_id)
Function Documentation
get_pid_for_vs_com()
std::optional< int > get_pid_for_vs_com (CellStructure & cell_structure, int mol_id)
Definition at line 96 of file com.cpp.
References comm_cart, CellStructure::for_each_local_particle(), Utils::Mpi::gather_buffer(), is_vs_com(), Particle::mol_id(), and stream.
Referenced by ScriptInterface::Particles::ParticleHandle::do_call_method().
vs_com_back_transfer_forces_and_torques()
void vs_com_back_transfer_forces_and_torques (CellStructure & cell_structure)
Definition at line 231 of file com.cpp.
References CellStructure::for_each_local_particle(), Particle::force(), gather_buffer_map(), CellStructure::ghosts_reduce_forces(), CellStructure::ghosts_reset_forces(), Particle::id(), is_vs_com(), Particle::mass(), Particle::mol_id(), and stream.
Referenced by System::System::calculate_forces().
vs_com_update_particles()
void vs_com_update_particles (CellStructure & cell_structure, BoxGeometry const & box_geo)
Definition at line 130 of file com.cpp.
References comm_cart, Cells::DATA_PART_POSITION, BoxGeometry::fold_position(), CellStructure::for_each_local_particle(), gather_buffer_map(), CellStructure::get_local_particle(), CellStructure::ghosts_update(), Particle::id(), Particle::image_box(), Particle::is_virtual(), is_vs_com(), Particle::mass(), Particle::mol_id(), Particle::pos(), stream, and BoxGeometry::unfolded_position().
Referenced by System::System::integrate(), and System::System::update_dependent_particles().