ESPResSo: common.hpp File Reference
common.hpp File Reference
#include "config.hpp"
#include <utils/Vector.hpp>
#include "LocalBox.hpp"
#include <array>
#include <cstddef>
#include <stdexcept>
#include <vector>
Classes
struct P3MParameters
Structure to hold P3M parameters and some dependent variables.
struct P3MLocalMesh
Structure for local mesh parameters.
Functions
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used to compute k-space errors.
Variables
constexpr auto P3M_EPSILON_METALLIC = 0.0
This value indicates metallic boundary conditions.
Detailed Description
Common functions for dipolar and charge P3M.
We use here a P3M (Particle-Particle Particle-Mesh) method based on the Ewald summation. Details of the used method can be found in [27] and [11] [12]. The file p3m contains only the Particle-Mesh part.
Further reading: [22], [27], [11], [12], [13], [14], [10]
Definition in file common.hpp.
Function Documentation
p3m_analytic_cotangent_sum()
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used to compute k-space errors.
Fortunately the one which is most important (because it converges most slowly, since it is not damped exponentially) can be calculated analytically. The result (which depends on the order of the spline interpolation) can be written as an even trigonometric polynomial. The results are tabulated here (the employed formula is eq. (7.66) in [27]).
Definition at line 39 of file common.cpp.
References D3Q19::c, errexit(), Utils::pi(), res, Utils::sqr(), and this_node.
Variable Documentation
P3M_EPSILON_METALLIC
constexpr auto P3M_EPSILON_METALLIC = 0.0 constexpr
This value indicates metallic boundary conditions.
Definition at line 43 of file common.hpp.
Referenced by DipolarLayerCorrection::adapt_solver(), DipolarLayerCorrection::add_force_corrections(), DipolarLayerCorrection::energy_correction(), DipolarP3M::kernel(), and CoulombP3M::long_range_kernel().