ESPResSo: common.cpp File Reference
common.cpp File Reference
#include "config.hpp"
#include "common.hpp"
#include "LocalBox.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <cmath>
#include <cstdio>
Functions
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used to compute k-space errors.
Function Documentation
p3m_analytic_cotangent_sum()
double p3m_analytic_cotangent_sum (int n, double mesh_i, int cao)
One of the aliasing sums used to compute k-space errors.
Fortunately the one which is most important (because it converges most slowly, since it is not damped exponentially) can be calculated analytically. The result (which depends on the order of the spline interpolation) can be written as an even trigonometric polynomial. The results are tabulated here (the employed formula is eq. (7.66) in [27]).
Definition at line 39 of file common.cpp.
References D3Q19::c, errexit(), Utils::pi(), res, Utils::sqr(), and this_node.