ESPResSo: optional.hpp File Reference
optional.hpp File Reference
#include <memory>
#include <optional>
Functions
template<typename T >
const T * get_ptr (std::optional< T > const &opt)
Function Documentation
get_ptr()
template<typename T > const T * get_ptr (std::optional< T > const & opt)
Definition at line 25 of file core/actor/optional.hpp.
References stream.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), System::System::calculate_energy(), System::System::calculate_forces(), System::System::calculate_pressure(), create_cabana_neighbor_kernel(), PairCriteria::EnergyCriterion::decide(), Constraints::ShapeBasedConstraint::force(), force_calc_icc(), System::System::particle_bond_energy(), and System::System::update_icc_particles().