ESPResSo: cuda_interface.cpp File Reference
cuda_interface.cpp File Reference
#include "cuda_interface.hpp"
#include "EspressoSystemInterface.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "grid.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "serialization/CUDA_particle_data.hpp"
#include <utils/Vector.hpp>
#include <utils/mpi/gather_buffer.hpp>
#include <utils/mpi/scatter_buffer.hpp>
#include <vector>
Functions
static void pack_particles (ParticleRange particles, CUDA_particle_data *buffer)
void cuda_mpi_get_particles (const ParticleRange &particles, pinned_vector< CUDA_particle_data > &particle_data_host)
static void add_forces_and_torques (ParticleRange particles, Utils::Span< const float > forces, Utils::Span< const float > torques)
Add a flat force (and torque) array to a range of particles.
void cuda_mpi_send_forces (const ParticleRange &particles, Utils::Span< float > host_forces, Utils::Span< float > host_torques)
Distribute forces to the worker nodes, and add them to the particles.
static void cuda_bcast_global_part_params_local ()
void cuda_bcast_global_part_params ()
void cuda_bcast_global_part_params_parallel ()
Function Documentation
add_forces_and_torques()
static void add_forces_and_torques (ParticleRange particles, Utils::Span< const float > forces, Utils::Span< const float > torques) static
Add a flat force (and torque) array to a range of particles.
Parameters
particles The particles the forces (and torques should be added to)
forces The forces as flat array of size 3 * particles.size()
torques The torques as flat array of size 3 * particles.size(), this is only touched if ROTATION is active.
Definition at line 115 of file cuda_interface.cpp.
References Cells::particles().
Referenced by cuda_mpi_send_forces().
cuda_bcast_global_part_params()
void cuda_bcast_global_part_params ()
Definition at line 165 of file cuda_interface.cpp.
References cuda_bcast_global_part_params_local(), and mpi_call_all().
Referenced by EspressoSystemInterface::enableParticleCommunication(), and lb_init_gpu().
cuda_bcast_global_part_params_local()
static void cuda_bcast_global_part_params_local () static
Definition at line 157 of file cuda_interface.cpp.
References comm_cart, gpu_get_global_particle_vars_pointer_host(), EspressoSystemInterface::Instance(), and EspressoSystemInterface::requestParticleStructGpu().
Referenced by cuda_bcast_global_part_params().
cuda_bcast_global_part_params_parallel()
void cuda_bcast_global_part_params_parallel ()
Definition at line 169 of file cuda_interface.cpp.
References comm_cart, gpu_get_global_particle_vars_pointer_host(), EspressoSystemInterface::Instance(), and EspressoSystemInterface::requestParticleStructGpuParallel().
Referenced by EspressoSystemInterface::enableParticleCommunicationParallel().
cuda_mpi_get_particles()
void cuda_mpi_get_particles (const ParticleRange & particles, pinned_vector< CUDA_particle_data > & particle_data_host)
Definition at line 85 of file cuda_interface.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), pack_particles(), particle_data_host, Cells::particles(), ParticleRange::size(), and this_node.
Referenced by copy_part_data_to_gpu().
cuda_mpi_send_forces()
void cuda_mpi_send_forces (const ParticleRange & particles, Utils::Span< float > host_forces, Utils::Span< float > host_torques)
Distribute forces to the worker nodes, and add them to the particles.
Parameters
particles The particles for which the forces (and torques) should be added to.
host_forces The forces as flat array of size 3 * particles.size(), only relevant on the head node.
host_torques The torques as flat array of size 3 * particles.size(), this is only touched if ROTATION is active. Only relevant on the head node.
This is a collective call.
Definition at line 130 of file cuda_interface.cpp.
References add_forces_and_torques(), comm_cart, Utils::Span< T >::data(), Cells::particles(), Utils::Mpi::scatter_buffer(), ParticleRange::size(), and this_node.
Referenced by copy_forces_from_GPU().
pack_particles()
static void pack_particles (ParticleRange particles, CUDA_particle_data * buffer) static
Definition at line 37 of file cuda_interface.cpp.
References box_geo, CUDA_particle_data::dip, CUDA_ParticleParametersSwimming::dipole_length, CUDA_ParticleParametersSwimming::director, CUDA_particle_data::director, CUDA_ParticleParametersSwimming::f_swim, folded_position(), CUDA_particle_data::identity, CUDA_particle_data::is_virtual, CUDA_particle_data::mass, CUDA_particle_data::mu_E, CUDA_particle_data::p, Cells::particles(), CUDA_ParticleParametersSwimming::push_pull, CUDA_particle_data::q, CUDA_particle_data::swim, CUDA_ParticleParametersSwimming::swimming, CUDA_particle_data::v, and CUDA_ParticleParametersSwimming::v_swim.
Referenced by cuda_mpi_get_particles().