ESPResSo: init.hpp File Reference
init.hpp File Reference
#include "config/config.hpp"
#include "utils.hpp"
#include <boost/serialization/access.hpp>
#include <cstddef>
#include <string>
#include <utility>
#include <vector>
Classes
struct EspressoGpuDevice
Struct to hold information relevant to ESPResSo about GPUs.
Functions
void cuda_init ()
Initializes the CUDA stream.
int cuda_get_n_gpus ()
Get the number of CUDA devices on the local host.
bool cuda_check_gpu_compute_capability (int dev)
Check that a given GPU has compute capability.
std::string cuda_get_gpu_name (int dev)
Get the name of a CUDA device.
void cuda_set_device (int dev)
Choose a device for future CUDA computations.
int cuda_get_device ()
Get the current CUDA device.
bool cuda_test_device_access ()
Test if communication to the CUDA device works.
void cuda_check_device ()
Check that a device is available, that its compute capability is sufficient for ESPResSo, and that data can be written to and read from it.
std::vector< EspressoGpuDevice > cuda_gather_gpus ()
Gather unique list of CUDA devices on all nodes.
EspressoGpuDevice cuda_get_device_props (int dev)
Get properties of a CUDA device.
void cuda_on_program_start ()
Called on program start.
Function Documentation
cuda_check_device()
void cuda_check_device ()
Check that a device is available, that its compute capability is sufficient for ESPResSo, and that data can be written to and read from it.
Otherwise, throw an exception.
Definition at line 102 of file init_cuda.cu.
References cuda_check_gpu_compute_capability(), cuda_get_device(), cuda_get_n_gpus(), cuda_test_device_access(), and stream.
cuda_check_gpu_compute_capability()
bool cuda_check_gpu_compute_capability (int dev)
Check that a given GPU has compute capability.
The minimal compute capability required by ESPResSo is computeCapabilityMinMajor . computeCapabilityMinMinor .
Parameters
dev CUDA device number
Returns
false if the GPU meets the requirements, else true.
Definition at line 50 of file init_cuda.cu.
References computeCapabilityMinMajor, computeCapabilityMinMinor, CUDA_CHECK, and stream.
Referenced by cuda_check_device().
cuda_gather_gpus()
std::vector< EspressoGpuDevice > cuda_gather_gpus ()
Gather unique list of CUDA devices on all nodes.
Returns
vector of device properties.
Gather unique list of CUDA devices on all nodes.
It relies on MPI_Get_processor_name() to get a unique identifier of the physical node, as opposed to the logical rank of which there can be more than one per node.
Definition at line 56 of file cuda/init.cpp.
References comm_cart, cuda_get_device_props(), cuda_get_n_gpus(), Utils::Mpi::gather_buffer(), invoke_skip_cuda_exceptions(), stream, and this_node.
Referenced by ScriptInterface::System::CudaInitHandle::do_call_method().
cuda_get_device()
int cuda_get_device ()
Get the current CUDA device.
Returns
the current device's number.
Definition at line 84 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by cuda_check_device(), and ScriptInterface::System::CudaInitHandle::CudaInitHandle().
cuda_get_device_props()
EspressoGpuDevice cuda_get_device_props (int dev)
Get properties of a CUDA device.
Parameters
dev CUDA device number
Definition at line 64 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by cuda_gather_gpus().
cuda_get_gpu_name()
std::string cuda_get_gpu_name (int dev)
Get the name of a CUDA device.
Parameters
[in] dev the CUDA device number to ask the name for
Definition at line 58 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by ScriptInterface::System::CudaInitHandle::do_call_method().
cuda_get_n_gpus()
int cuda_get_n_gpus ()
Get the number of CUDA devices on the local host.
Returns
the number of GPUs.
Definition at line 44 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by cuda_check_device(), cuda_gather_gpus(), and ScriptInterface::System::CudaInitHandle::do_call_method().
cuda_init()
void cuda_init ()
Initializes the CUDA stream.
Definition at line 42 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by cuda_on_program_start().
cuda_on_program_start()
void cuda_on_program_start ()
Called on program start.
Definition at line 91 of file cuda/init.cpp.
References communicator, cuda_init(), invoke_skip_cuda_exceptions(), and this_node.
Referenced by CommunicationEnvironment::CommunicationEnvironment().
cuda_set_device()
void cuda_set_device (int dev)
Choose a device for future CUDA computations.
Parameters
dev the device to use
Definition at line 78 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by ScriptInterface::System::CudaInitHandle::CudaInitHandle().
cuda_test_device_access()
bool cuda_test_device_access ()
Test if communication to the CUDA device works.
Returns
false on success, else true.
Definition at line 90 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by cuda_check_device().