ESPResSo: cuda_utils.cuh File Reference
cuda_utils.cuh File Reference
#include "cuda_utils.hpp"
#include <cuda.h>
#include <cassert>
#include <string>
Classes
class cuda_runtime_error_cuda
Macros
#define CORE_CUDA_UTILS_CUH
#define CUDA_CHECK(statement)
Convert CUDA error codes into runtime errors.
#define cuda_safe_mem(a) cuda_safe_mem_exit((a), __FILE__, __LINE__)
#define KERNELCALL_shared(_function, _grid, _block, _stream, ...)
#define KERNELCALL_stream(_function, _grid, _block, _stream, ...)
#define KERNELCALL(_function, _grid, _block, ...) KERNELCALL_shared(_function, _grid, _block, 0, ##__VA_ARGS__)
Functions
void cuda_safe_mem_exit (cudaError_t CU_err, const char *file, unsigned int line)
In case of error during CUDA memory allocation and memory copy, print the error message and exit.
void cuda_check_errors_exit (const dim3 &block, const dim3 &grid, const char *function, const char *file, unsigned int line)
In case of error during a CUDA operation, print the error message and exit.
dim3 calculate_dim_grid (unsigned const threads_x, unsigned const blocks_per_grid_y, unsigned const threads_per_block)
Calculate dim_grid for CUDA kernel calls.
Variables
cudaStream_t stream [1]
CUDA streams for parallel computing on CPU and GPU.
Macro Definition Documentation
CORE_CUDA_UTILS_CUH
#define CORE_CUDA_UTILS_CUH
Definition at line 20 of file cuda_utils.cuh.
CUDA_CHECK
#define CUDA_CHECK (statement)
Value:
  {                                                                            \
    cudaError_t const error_code = (statement);                                \
    if (error_code != cudaSuccess) {                                           \
      throw cuda_runtime_error_cuda(error_code);                               \
    }                                                                          \
  }
Convert CUDA error codes into runtime errors.
Definition at line 46 of file cuda_utils.cuh.
cuda_safe_mem
#define cuda_safe_mem (a) cuda_safe_mem_exit((a), __FILE__, __LINE__)
Definition at line 72 of file cuda_utils.cuh.
KERNELCALL
#define KERNELCALL (_function, _grid, _block, ...) KERNELCALL_shared(_function, _grid, _block, 0, ##__VA_ARGS__)
Definition at line 94 of file cuda_utils.cuh.
KERNELCALL_shared
#define KERNELCALL_shared (_function, _grid, _block, _stream, ...)
Value:
  _function<<<_grid, _block, _stream, stream[0]>>>(__VA_ARGS__);               \
  cuda_check_errors_exit(_grid, _block, #_function, __FILE__, __LINE__);
Definition at line 86 of file cuda_utils.cuh.
KERNELCALL_stream
#define KERNELCALL_stream (_function, _grid, _block, _stream, ...)
Value:
  _function<<<_grid, _block, 0, _stream>>>(__VA_ARGS__);                       \
  cuda_check_errors_exit(_grid, _block, #_function, __FILE__, __LINE__);
Definition at line 90 of file cuda_utils.cuh.
Function Documentation
calculate_dim_grid()
dim3 calculate_dim_grid (unsigned const threads_x, unsigned const blocks_per_grid_y, unsigned const threads_per_block) inline
Calculate dim_grid for CUDA kernel calls.
Definition at line 75 of file cuda_utils.cuh.
References threads_per_block.
Referenced by FdElectrostatics::calculatePotential(), ek_calculate_electrostatic_coupling(), ek_calculate_net_charge(), ek_init(), ek_init_species_density_wallcharge(), ek_integrate(), ek_integrate_electrostatics(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), FdElectrostatics::FdElectrostatics(), IBM_ForcesIntoFluid_GPU(), lb_calc_fluid_mass_GPU(), lb_calc_fluid_momentum_GPU(), lb_calc_particle_lattice_ia_gpu(), lb_get_boundary_flags_GPU(), lb_get_values_GPU(), lb_init_boundaries_GPU(), lb_init_GPU(), lb_integrate_GPU(), lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), ParticleVelocitiesFromLB_GPU(), and reset_LB_force_densities_GPU().
cuda_check_errors_exit()
void cuda_check_errors_exit (const dim3 & block, const dim3 & grid, const char * function, const char * file, unsigned int line)
In case of error during a CUDA operation, print the error message and exit.
Definition at line 71 of file cuda_common_cuda.cu.
References block(), and errexit().
Referenced by assign_charges(), and assign_forces().
cuda_safe_mem_exit()
void cuda_safe_mem_exit (cudaError_t CU_err, const char * file, unsigned int line)
In case of error during CUDA memory allocation and memory copy, print the error message and exit.
Parameters
CU_err cuda error code
file .cu file were the error took place
line line of the file were the error took place
Definition at line 218 of file cuda_common_cuda.cu.
References errexit().
Variable Documentation
stream
cudaStream_t stream[1]
CUDA streams for parallel computing on CPU and GPU.
Definition at line 69 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), cuda_init(), cuda_set_device(), ek_init(), and FdElectrostatics::FdElectrostatics().