ESPResSo: cuda_interface.hpp File Reference
cuda_interface.hpp File Reference
#include "config.hpp"
#include "CudaHostAllocator.hpp"
#include "ParticleRange.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
Classes
struct CUDA_ParticleParametersSwimming
struct CUDA_particle_data
data structure which must be copied to the GPU at each step run on the GPU
struct CUDA_energy
data structure for the different kinds of energies
struct CUDA_global_part_vars
Global variables associated with all of the particles and not with one individual particle.
Functions
void copy_forces_from_GPU (ParticleRange &particles, int this_node)
setup and call kernel to copy particle forces to host
CUDA_energy copy_energy_from_GPU ()
void clear_energy_on_GPU ()
CUDA_global_part_vars * gpu_get_global_particle_vars_pointer_host ()
Utils::Span< CUDA_particle_data > gpu_get_particle_pointer ()
float * gpu_get_particle_force_pointer ()
float * gpu_get_particle_torque_pointer ()
CUDA_energy * gpu_get_energy_pointer ()
void gpu_init_particle_comm (int this_node)
Setup and call particle reallocation from the host.
void cuda_mpi_get_particles (const ParticleRange &particles, pinned_vector< CUDA_particle_data > &particle_data_host)
void copy_part_data_to_gpu (ParticleRange particles, int this_node)
void cuda_mpi_send_forces (const ParticleRange &particles, Utils::Span< float > host_forces, Utils::Span< float > host_torques)
Distribute forces to the worker nodes, and add them to the particles.
void cuda_bcast_global_part_params_parallel ()
void cuda_bcast_global_part_params ()
Function Documentation
clear_energy_on_GPU()
void clear_energy_on_GPU ()
Definition at line 202 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_safe_mem, energy_device, and global_part_vars_host.
Referenced by calculate_energy_local().
copy_energy_from_GPU()
CUDA_energy copy_energy_from_GPU ()
Definition at line 210 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_safe_mem, energy_device, energy_host, and global_part_vars_host.
copy_forces_from_GPU()
void copy_forces_from_GPU (ParticleRange & particles, int this_node)
setup and call kernel to copy particle forces to host
Definition at line 183 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_mpi_send_forces(), global_part_vars_host, particle_forces_device, particle_forces_host, particle_torques_device, particle_torques_host, Cells::particles(), and this_node.
Referenced by force_calc().
copy_part_data_to_gpu()
void copy_part_data_to_gpu (ParticleRange particles, int this_node)
Definition at line 160 of file cuda_common_cuda.cu.
References byte_size(), CUDA_global_part_vars::communication_enabled, cuda_mpi_get_particles(), global_part_vars_host, particle_data_device, particle_data_host, particle_forces_device, particle_torques_device, Cells::particles(), raw_data_pointer(), resize_buffers(), stream, and this_node.
Referenced by EspressoSystemInterface::gatherParticles().
cuda_bcast_global_part_params()
void cuda_bcast_global_part_params ()
Definition at line 165 of file cuda_interface.cpp.
References cuda_bcast_global_part_params_local(), and mpi_call_all().
Referenced by EspressoSystemInterface::enableParticleCommunication(), and lb_init_gpu().
cuda_bcast_global_part_params_parallel()
void cuda_bcast_global_part_params_parallel ()
Definition at line 169 of file cuda_interface.cpp.
References comm_cart, gpu_get_global_particle_vars_pointer_host(), EspressoSystemInterface::Instance(), and EspressoSystemInterface::requestParticleStructGpuParallel().
Referenced by EspressoSystemInterface::enableParticleCommunicationParallel().
cuda_mpi_get_particles()
void cuda_mpi_get_particles (const ParticleRange & particles, pinned_vector< CUDA_particle_data > & particle_data_host)
Definition at line 85 of file cuda_interface.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), pack_particles(), particle_data_host, Cells::particles(), ParticleRange::size(), and this_node.
Referenced by copy_part_data_to_gpu().
cuda_mpi_send_forces()
void cuda_mpi_send_forces (const ParticleRange & particles, Utils::Span< float > host_forces, Utils::Span< float > host_torques)
Distribute forces to the worker nodes, and add them to the particles.
Parameters
particles The particles for which the forces (and torques) should be added to.
host_forces The forces as flat array of size 3 * particles.size(), only relevant on the head node.
host_torques The torques as flat array of size 3 * particles.size(), this is only touched if ROTATION is active. Only relevant on the head node.
This is a collective call.
Definition at line 130 of file cuda_interface.cpp.
References add_forces_and_torques(), comm_cart, Utils::Span< T >::data(), Cells::particles(), Utils::Mpi::scatter_buffer(), ParticleRange::size(), and this_node.
Referenced by copy_forces_from_GPU().
gpu_get_energy_pointer()
CUDA_energy* gpu_get_energy_pointer ()
Definition at line 158 of file cuda_common_cuda.cu.
References energy_device.
Referenced by EspressoSystemInterface::eGpu().
gpu_get_global_particle_vars_pointer_host()
CUDA_global_part_vars* gpu_get_global_particle_vars_pointer_host ()
Definition at line 147 of file cuda_common_cuda.cu.
References global_part_vars_host.
Referenced by cuda_bcast_global_part_params_local(), cuda_bcast_global_part_params_parallel(), EspressoSystemInterface::enableParticleCommunication(), EspressoSystemInterface::enableParticleCommunicationParallel(), EspressoSystemInterface::gatherParticles(), and on_integration_start().
gpu_get_particle_force_pointer()
float* gpu_get_particle_force_pointer ()
Definition at line 150 of file cuda_common_cuda.cu.
References particle_forces_device, and raw_data_pointer().
Referenced by ek_calculate_electrostatic_coupling(), EspressoSystemInterface::fGpuBegin(), lb_calc_particle_lattice_ia_gpu(), and p3m_gpu_add_farfield_force().
gpu_get_particle_pointer()
Utils::Span<CUDA_particle_data> gpu_get_particle_pointer ()
Definition at line 144 of file cuda_common_cuda.cu.
References particle_data_device, and raw_data_pointer().
Referenced by ek_calculate_electrostatic_coupling(), ek_get_particle_charge(), ek_integrate_electrostatics(), EspressoSystemInterface::enableParticleCommunication(), EspressoSystemInterface::enableParticleCommunicationParallel(), EspressoSystemInterface::gatherParticles(), IBM_ForcesIntoFluid_GPU(), lb_calc_particle_lattice_ia_gpu(), EspressoSystemInterface::npart_gpu(), p3m_gpu_add_farfield_force(), p3m_gpu_init(), ParticleVelocitiesFromLB_GPU(), and EspressoSystemInterface::split_particle_struct().
gpu_get_particle_torque_pointer()
float* gpu_get_particle_torque_pointer ()
Definition at line 154 of file cuda_common_cuda.cu.
References particle_torques_device, and raw_data_pointer().
Referenced by EspressoSystemInterface::torqueGpuBegin().
gpu_init_particle_comm()
void gpu_init_particle_comm (int this_node)
Setup and call particle reallocation from the host.
Note that in addition to calling this function the parameters must be broadcast with either:
cuda_bcast_global_part_params() (when just being executed on the head node) or
MPI_Bcast(gpu_get_global_particle_vars_pointer_host(), sizeof(CUDA_global_part_vars), MPI_BYTE, 0, comm_cart) (when executed on all nodes)
Definition at line 132 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_check_device(), errexit(), global_part_vars_host, and this_node.
Referenced by EspressoSystemInterface::enableParticleCommunication(), EspressoSystemInterface::enableParticleCommunicationParallel(), and lb_init_gpu().