ESPResSo: cuda_common_cuda.cu File Reference
cuda_common_cuda.cu File Reference
#include "config.hpp"
#include "ParticleRange.hpp"
#include "cuda_init.hpp"
#include "cuda_interface.hpp"
#include "cuda_utils.cuh"
#include "errorhandling.hpp"
#include "CudaDeviceAllocator.hpp"
#include "CudaHostAllocator.hpp"
#include <utils/constants.hpp>
#include <thrust/device_vector.h>
#include <cuda.h>
#include <cstddef>
#include <cstdio>
Typedefs
template<class T >
using device_vector = thrust::device_vector< T, CudaDeviceAllocator< T > >
Functions
template<class T , class A >
T * raw_data_pointer (thrust::device_vector< T, A > &vec)
template<class SpanLike >
std::size_t byte_size (SpanLike const &v)
void cuda_check_errors_exit (const dim3 &block, const dim3 &grid, const char *function, const char *file, unsigned int line)
In case of error during a CUDA operation, print the error message and exit.
template<class T >
void resize_or_replace (device_vector< T > &vec, std::size_t n)
Resize a device_vector.
void resize_buffers (std::size_t number_of_particles)
void gpu_init_particle_comm (int this_node)
Setup and call particle reallocation from the host.
Utils::Span< CUDA_particle_data > gpu_get_particle_pointer ()
CUDA_global_part_vars * gpu_get_global_particle_vars_pointer_host ()
float * gpu_get_particle_force_pointer ()
float * gpu_get_particle_torque_pointer ()
CUDA_energy * gpu_get_energy_pointer ()
void copy_part_data_to_gpu (ParticleRange particles, int this_node)
void copy_forces_from_GPU (ParticleRange &particles, int this_node)
setup and call kernel to copy particle forces to host
void clear_energy_on_GPU ()
CUDA_energy copy_energy_from_GPU ()
void cuda_safe_mem_exit (cudaError_t CU_err, const char *file, unsigned int line)
In case of error during CUDA memory allocation and memory copy, print the error message and exit.
Variables
static CUDA_global_part_vars global_part_vars_host = {}
static device_vector< float > particle_forces_device
struct for particle force
static device_vector< float > particle_torques_device
static device_vector< CUDA_particle_data > particle_data_device
struct for particle position and velocity
static CUDA_energy * energy_device = nullptr
struct for energies
pinned_vector< CUDA_particle_data > particle_data_host
pinned_vector< float > particle_forces_host
pinned_vector< float > particle_torques_host
CUDA_energy energy_host
cudaStream_t stream [1]
CUDA streams for parallel computing on CPU and GPU.
Typedef Documentation
device_vector
template<class T > using device_vector = thrust::device_vector<T, CudaDeviceAllocator<T> >
Definition at line 40 of file cuda_common_cuda.cu.
Function Documentation
byte_size()
template<class SpanLike > std::size_t byte_size (SpanLike const & v)
Definition at line 49 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu().
clear_energy_on_GPU()
void clear_energy_on_GPU ()
Definition at line 202 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_safe_mem, energy_device, and global_part_vars_host.
Referenced by calculate_energy_local().
copy_energy_from_GPU()
CUDA_energy copy_energy_from_GPU ()
Definition at line 210 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_safe_mem, energy_device, energy_host, and global_part_vars_host.
copy_forces_from_GPU()
void copy_forces_from_GPU (ParticleRange & particles, int this_node)
setup and call kernel to copy particle forces to host
Definition at line 183 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_mpi_send_forces(), global_part_vars_host, particle_forces_device, particle_forces_host, particle_torques_device, particle_torques_host, Cells::particles(), and this_node.
Referenced by force_calc().
copy_part_data_to_gpu()
void copy_part_data_to_gpu (ParticleRange particles, int this_node)
Definition at line 160 of file cuda_common_cuda.cu.
References byte_size(), CUDA_global_part_vars::communication_enabled, cuda_mpi_get_particles(), global_part_vars_host, particle_data_device, particle_data_host, particle_forces_device, particle_torques_device, Cells::particles(), raw_data_pointer(), resize_buffers(), stream, and this_node.
Referenced by EspressoSystemInterface::gatherParticles().
cuda_check_errors_exit()
void cuda_check_errors_exit (const dim3 & block, const dim3 & grid, const char * function, const char * file, unsigned int line)
In case of error during a CUDA operation, print the error message and exit.
Definition at line 71 of file cuda_common_cuda.cu.
References block(), and errexit().
Referenced by assign_charges(), and assign_forces().
cuda_safe_mem_exit()
void cuda_safe_mem_exit (cudaError_t CU_err, const char * file, unsigned int line)
In case of error during CUDA memory allocation and memory copy, print the error message and exit.
Parameters
CU_err cuda error code
file .cu file were the error took place
line line of the file were the error took place
Definition at line 218 of file cuda_common_cuda.cu.
References errexit().
gpu_get_energy_pointer()
CUDA_energy* gpu_get_energy_pointer ()
Definition at line 158 of file cuda_common_cuda.cu.
References energy_device.
Referenced by EspressoSystemInterface::eGpu().
gpu_get_global_particle_vars_pointer_host()
CUDA_global_part_vars* gpu_get_global_particle_vars_pointer_host ()
Definition at line 147 of file cuda_common_cuda.cu.
References global_part_vars_host.
Referenced by cuda_bcast_global_part_params_local(), cuda_bcast_global_part_params_parallel(), EspressoSystemInterface::enableParticleCommunication(), EspressoSystemInterface::enableParticleCommunicationParallel(), EspressoSystemInterface::gatherParticles(), and on_integration_start().
gpu_get_particle_force_pointer()
float* gpu_get_particle_force_pointer ()
Definition at line 150 of file cuda_common_cuda.cu.
References particle_forces_device, and raw_data_pointer().
Referenced by ek_calculate_electrostatic_coupling(), EspressoSystemInterface::fGpuBegin(), lb_calc_particle_lattice_ia_gpu(), and p3m_gpu_add_farfield_force().
gpu_get_particle_pointer()
Utils::Span<CUDA_particle_data> gpu_get_particle_pointer ()
Definition at line 144 of file cuda_common_cuda.cu.
References particle_data_device, and raw_data_pointer().
Referenced by ek_calculate_electrostatic_coupling(), ek_get_particle_charge(), ek_integrate_electrostatics(), EspressoSystemInterface::enableParticleCommunication(), EspressoSystemInterface::enableParticleCommunicationParallel(), EspressoSystemInterface::gatherParticles(), IBM_ForcesIntoFluid_GPU(), lb_calc_particle_lattice_ia_gpu(), EspressoSystemInterface::npart_gpu(), p3m_gpu_add_farfield_force(), p3m_gpu_init(), ParticleVelocitiesFromLB_GPU(), and EspressoSystemInterface::split_particle_struct().
gpu_get_particle_torque_pointer()
float* gpu_get_particle_torque_pointer ()
Definition at line 154 of file cuda_common_cuda.cu.
References particle_torques_device, and raw_data_pointer().
Referenced by EspressoSystemInterface::torqueGpuBegin().
gpu_init_particle_comm()
void gpu_init_particle_comm (int this_node)
Setup and call particle reallocation from the host.
Note that in addition to calling this function the parameters must be broadcast with either:
cuda_bcast_global_part_params() (when just being executed on the head node) or
MPI_Bcast(gpu_get_global_particle_vars_pointer_host(), sizeof(CUDA_global_part_vars), MPI_BYTE, 0, comm_cart) (when executed on all nodes)
Definition at line 132 of file cuda_common_cuda.cu.
References CUDA_global_part_vars::communication_enabled, cuda_check_device(), errexit(), global_part_vars_host, and this_node.
Referenced by EspressoSystemInterface::enableParticleCommunication(), EspressoSystemInterface::enableParticleCommunicationParallel(), and lb_init_gpu().
raw_data_pointer()
template<class T , class A > T* raw_data_pointer (thrust::device_vector< T, A > & vec)
Definition at line 45 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), and gpu_get_particle_torque_pointer().
resize_buffers()
void resize_buffers (std::size_t number_of_particles)
Definition at line 109 of file cuda_common_cuda.cu.
References particle_data_device, particle_data_host, particle_forces_device, particle_forces_host, particle_torques_device, particle_torques_host, and resize_or_replace().
Referenced by copy_part_data_to_gpu().
resize_or_replace()
template<class T > void resize_or_replace (device_vector< T > & vec, std::size_t n)
Resize a device_vector.
Due to a bug in thrust (https://github.com/thrust/thrust/issues/939), resizing or appending to default constructed containers causes undefined behavior by dereferencing a null-pointer for certain types. This function is used instead of the resize member function to side-step the problem. This is done by replacing the existing vector by a new one constructed with the desired size if resizing from capacity zero. Behaves as-if vec.resize(n) was called.
Template Parameters
T Type contained in the vector.
Parameters
vec Vector To resize.
n Desired new size of the element.
Definition at line 101 of file cuda_common_cuda.cu.
Referenced by resize_buffers().
Variable Documentation
energy_device
CUDA_energy* energy_device = nullptr static
struct for energies
Definition at line 62 of file cuda_common_cuda.cu.
Referenced by clear_energy_on_GPU(), copy_energy_from_GPU(), and gpu_get_energy_pointer().
energy_host
CUDA_energy energy_host
Definition at line 67 of file cuda_common_cuda.cu.
Referenced by copy_energy_from_GPU().
global_part_vars_host
CUDA_global_part_vars global_part_vars_host = {} static
Definition at line 42 of file cuda_common_cuda.cu.
Referenced by clear_energy_on_GPU(), copy_energy_from_GPU(), copy_forces_from_GPU(), copy_part_data_to_gpu(), gpu_get_global_particle_vars_pointer_host(), and gpu_init_particle_comm().
particle_data_device
device_vector<CUDA_particle_data> particle_data_device static
struct for particle position and velocity
Definition at line 60 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), gpu_get_particle_pointer(), and resize_buffers().
particle_data_host
pinned_vector<CUDA_particle_data> particle_data_host
Definition at line 64 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), cuda_mpi_get_particles(), and resize_buffers().
particle_forces_device
device_vector<float> particle_forces_device static
struct for particle force
Definition at line 54 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), copy_part_data_to_gpu(), gpu_get_particle_force_pointer(), and resize_buffers().
particle_forces_host
pinned_vector<float> particle_forces_host
Definition at line 65 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), and resize_buffers().
particle_torques_device
device_vector<float> particle_torques_device static
Definition at line 56 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), copy_part_data_to_gpu(), gpu_get_particle_torque_pointer(), and resize_buffers().
particle_torques_host
pinned_vector<float> particle_torques_host
Definition at line 66 of file cuda_common_cuda.cu.
Referenced by copy_forces_from_GPU(), and resize_buffers().
stream
cudaStream_t stream[1]
CUDA streams for parallel computing on CPU and GPU.
Definition at line 69 of file cuda_common_cuda.cu.
Referenced by copy_part_data_to_gpu(), cuda_init(), cuda_set_device(), ek_init(), and FdElectrostatics::FdElectrostatics().