ESPResSo: dds_gpu_cuda.cuh File Reference
dds_gpu_cuda.cuh File Reference
#include "config.hpp"
Macros
#define ESPRESSO_SRC_CORE_MAGNETOSTATICS_DIPOLAR_DIRECT_SUM_GPU_CUH
Functions
void DipolarDirectSum_kernel_wrapper_energy (float k, unsigned int n, float *pos, float *dip, float box_l[3], int periodic[3], float *E)
void DipolarDirectSum_kernel_wrapper_force (float k, unsigned int n, float *pos, float *dip, float *f, float *torque, float box_l[3], int periodic[3])
Macro Definition Documentation
ESPRESSO_SRC_CORE_MAGNETOSTATICS_DIPOLAR_DIRECT_SUM_GPU_CUH
#define ESPRESSO_SRC_CORE_MAGNETOSTATICS_DIPOLAR_DIRECT_SUM_GPU_CUH
Definition at line 21 of file dds_gpu_cuda.cuh.
Function Documentation
DipolarDirectSum_kernel_wrapper_energy()
void DipolarDirectSum_kernel_wrapper_energy (float k, unsigned int n, float * pos, float * dip, float box_l[3], int periodic[3], float * E)
Definition at line 272 of file dds_gpu_cuda.cu.
References block(), copy_box_data(), cuda_safe_mem, DipolarDirectSum_kernel_energy(), energySum, KERNELCALL_shared, and pos.
Referenced by DipolarDirectSumGpu::long_range_energy().
DipolarDirectSum_kernel_wrapper_force()
void DipolarDirectSum_kernel_wrapper_force (float k, unsigned int n, float * pos, float * dip, float * f, float * torque, float box_l[3], int periodic[3])
Definition at line 243 of file dds_gpu_cuda.cu.
References block(), copy_box_data(), DipolarDirectSum_kernel_force(), f, KERNELCALL, pos, and torque.
Referenced by DipolarDirectSumGpu::add_long_range_forces().