var DiffusiveFluxKernelWithElectrostaticThermalized__double__precision__CUDA_8h =
[
    [ "walberla::pystencils::DiffusiveFluxKernelWithElectrostaticThermalized_double_precision_CUDA", "classwalberla_1_1pystencils_1_1DiffusiveFluxKernelWithElectrostaticThermalized__double__precision__CUDA.html", "classwalberla_1_1pystencils_1_1DiffusiveFluxKernelWithElectrostaticThermalized__double__precision__CUDA" ],
    [ "RESTRICT", "DiffusiveFluxKernelWithElectrostaticThermalized__double__precision__CUDA_8h.html#aae3356b63849abbe8789dd41648ee90a", null ]
];