ESPResSo: dipolar_direct_sum_gpu_cuda.cuh File Reference
dipolar_direct_sum_gpu_cuda.cuh File Reference
#include <config/config.hpp>
Functions
void DipolarDirectSum_kernel_wrapper_energy (float k, unsigned int n, float const *pos, float const *dip, float box_l[3], int periodic[3], float *E)
void DipolarDirectSum_kernel_wrapper_force (float k, unsigned int n, float const *pos, float const *dip, float *dip_fld, float *f, float *torque, float box_l[3], int periodic[3], int n_replicas)
Function Documentation
DipolarDirectSum_kernel_wrapper_energy()
void DipolarDirectSum_kernel_wrapper_energy (float k, unsigned int n, float const * pos, float const * dip, float box_l[3], int periodic[3], float * E)
Definition at line 379 of file dipolar_direct_sum_gpu_cuda.cu.
References block(), copy_box_data(), cuda_safe_mem, DipolarDirectSum_kernel_energy(), KERNELCALL_shared, and stream.
Referenced by DipolarDirectSum::long_range_energy_gpu().
DipolarDirectSum_kernel_wrapper_force()
void DipolarDirectSum_kernel_wrapper_force (float k, unsigned int n, float const * pos, float const * dip, float * dip_fld, float * f, float * torque, float box_l[3], int periodic[3], int n_replicas)
Definition at line 347 of file dipolar_direct_sum_gpu_cuda.cu.
References block(), copy_box_data(), DipolarDirectSum_kernel_force(), KERNELCALL, and stream.
Referenced by DipolarDirectSum::add_long_range_forces_gpu().