ESPResSo: dipolar_direct_sum.cpp File Reference
dipolar_direct_sum.cpp File Reference
#include <config/config.hpp>
#include "magnetostatics/dipolar_direct_sum.hpp"
#include "BoxGeometry.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "system/System.hpp"
#include <utils/Vector.hpp>
#include <utils/cartesian_product.hpp>
#include <utils/mpi/iall_gatherv.hpp>
#include <boost/mpi/collectives.hpp>
#include <boost/mpi/communicator.hpp>
#include <mpi.h>
#include <algorithm>
#include <cassert>
#include <cmath>
#include <iterator>
#include <ranges>
#include <stdexcept>
#include <tuple>
#include <utility>
#include <vector>
Classes
struct PosMom
Position and dipole moment of one particle.
Functions
static auto pair_force (Utils::Vector3d const &d, Utils::Vector3d const &m1, Utils::Vector3d const &m2)
Pair force of two interacting dipoles.
static auto pair_potential (Utils::Vector3d const &d, Utils::Vector3d const &m1, Utils::Vector3d const &m2)
Pair potential for two interacting dipoles.
static auto dipole_field (Utils::Vector3d const &d, Utils::Vector3d const &m1)
Dipole field contribution from a particle with dipole moment m1 at a distance d.
template<typename F >
void for_each_image (Utils::Vector3i const &ncut, F f)
Call kernel for every 3d index in a sphere around the origin.
template<class InputIterator , class T , class F >
T image_sum (InputIterator begin, InputIterator end, InputIterator it, bool with_replicas, Utils::Vector3i const &ncut, BoxGeometry const &box_geo, T init, F f)
Sum over all pairs with periodic images.
static auto gather_particle_data (BoxGeometry const &box_geo, ParticleRange const &particles)
static auto get_n_cut (BoxGeometry const &box_geo, int n_replicas)
Function Documentation
dipole_field()
static auto dipole_field (Utils::Vector3d const & d, Utils::Vector3d const & m1) static
Dipole field contribution from a particle with dipole moment m1 at a distance d.
Parameters
d Distance vector.
m1 Dipole moment of one particle.
Returns
Utils::Vector3d containing dipole field components.
Definition at line 116 of file dipolar_direct_sum.cpp.
References stream.
for_each_image()
template<typename F > void for_each_image (Utils::Vector3i const & ncut, F f)
Call kernel for every 3d index in a sphere around the origin.
This calls a callable for all index-triples that are within ball around the origin with radius |ncut|.
Template Parameters
F Callable
Parameters
ncut Limits in the three directions, all non-zero elements have to be the same number.
f will be called for each index triple within the limits of ncut.
Definition at line 141 of file dipolar_direct_sum.cpp.
References Utils::cartesian_product(), Utils::Vector< T, N >::norm2(), and stream.
Referenced by DipolarDirectSum::add_long_range_forces_cpu(), and image_sum().
gather_particle_data()
static auto gather_particle_data (BoxGeometry const & box_geo, ParticleRange const & particles) static
Definition at line 223 of file dipolar_direct_sum.cpp.
References comm_cart, BoxGeometry::folded_position(), Utils::Mpi::iall_gatherv(), ParticleRange::size(), and stream.
Referenced by DipolarDirectSum::add_long_range_forces_cpu(), DipolarDirectSum::dipole_field_at_part_cpu(), and DipolarDirectSum::long_range_energy_cpu().
get_n_cut()
static auto get_n_cut (BoxGeometry const & box_geo, int n_replicas) static
Definition at line 263 of file dipolar_direct_sum.cpp.
References BoxGeometry::periodic().
Referenced by DipolarDirectSum::add_long_range_forces_cpu(), DipolarDirectSum::dipole_field_at_part_cpu(), and DipolarDirectSum::long_range_energy_cpu().
image_sum()
template<class InputIterator , class T , class F > T image_sum (InputIterator begin, InputIterator end, InputIterator it, bool with_replicas, Utils::Vector3i const & ncut, BoxGeometry const & box_geo, T init, F f)
Sum over all pairs with periodic images.
This implements the "primed" pair sum, the sum over all pairs between one particles and all other particles, including ncut periodic replicas in each direction. Primed means that in the primary replica the self-interaction is excluded, but not with the other periodic replicas. E.g. a particle does not interact with its self, but does with its periodically shifted versions.
Parameters
begin Iterator pointing to begin of particle range
end Iterator pointing past the end of particle range
it Pointer to particle that is considered
with_replicas If periodic replicas are to be considered at all. If false, distances are calculated as Euclidean distances, and not using minimum image convention.
ncut Number of replicas in each direction.
box_geo Box geometry.
init Initial value of the sum.
f Binary operation mapping distance and moment of the interaction partner to the value to be summed up for this pair.
Returns
The total sum.
Definition at line 199 of file dipolar_direct_sum.cpp.
References for_each_image(), BoxGeometry::get_mi_vector(), BoxGeometry::length(), and stream.
Referenced by DipolarDirectSum::add_long_range_forces_cpu(), DipolarDirectSum::dipole_field_at_part_cpu(), and DipolarDirectSum::long_range_energy_cpu().
pair_force()
static auto pair_force (Utils::Vector3d const & d, Utils::Vector3d const & m1, Utils::Vector3d const & m2) static
Pair force of two interacting dipoles.
Parameters
d Distance vector.
m1 Dipole moment of one particle.
m2 Dipole moment of the other particle.
Returns
Resulting force.
Definition at line 62 of file dipolar_direct_sum.cpp.
References Utils::Vector< T, N >::norm2(), stream, and vector_product().
Referenced by DipolarDirectSum::add_long_range_forces_cpu(), and calc_bonded_virial_pressure_tensor().
pair_potential()
static auto pair_potential (Utils::Vector3d const & d, Utils::Vector3d const & m1, Utils::Vector3d const & m2) static
Pair potential for two interacting dipoles.
Parameters
d Distance vector.
m1 Dipole moment of one particle.
m2 Dipole moment of the other particle.
Returns
Interaction energy.
Definition at line 92 of file dipolar_direct_sum.cpp.
References stream.