ESPResSo: electrokinetics_cuda.cu File Reference
electrokinetics_cuda.cu File Reference
#include "config.hpp"
#include "grid_based_algorithms/electrokinetics.hpp"
#include "cuda_interface.hpp"
#include "cuda_utils.cuh"
#include "errorhandling.hpp"
#include "fd-electrostatics.cuh"
#include "grid_based_algorithms/lb_boundaries.hpp"
#include "grid_based_algorithms/lb_interface.hpp"
#include "grid_based_algorithms/lb_particle_coupling.hpp"
#include "grid_based_algorithms/lbgpu.cuh"
#include "grid_based_algorithms/lbgpu.hpp"
#include "integrate.hpp"
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
#include <thrust/device_ptr.h>
#include <thrust/functional.h>
#include <thrust/transform_reduce.h>
#include <cuda.h>
#include <cufft.h>
#include <cstddef>
#include <cstdio>
#include <fstream>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
Classes
struct ek_charge_of_particle
Macros
#define EK_LINK_U00_pressure 0
#define EK_LINK_0U0_pressure 1
#define EK_LINK_00U_pressure 2
#define EK_LINK_D00_pressure 3
#define EK_LINK_0D0_pressure 4
#define EK_LINK_00D_pressure 5
Functions
__device__ cufftReal ek_getNode (unsigned x, unsigned y, unsigned z)
__device__ void ek_setNode (unsigned x, unsigned y, unsigned z, cufftReal value)
__device__ cufftReal ek_getNode (unsigned i)
__device__ void ek_setNode (unsigned i, cufftReal value)
__device__ unsigned int ek_getThreadIndex ()
__device__ void rhoindex_linear2cartesian (unsigned int index, unsigned int *coord)
__device__ unsigned int rhoindex_cartesian2linear (unsigned int x, unsigned int y, unsigned int z)
__device__ unsigned int rhoindex_cartesian2linear_padded (unsigned int x, unsigned int y, unsigned int z)
__device__ unsigned int jindex_getByRhoLinear (unsigned int rho_index, unsigned int c)
__device__ void ek_displacement (float *dx, LB_nodes_gpu n, unsigned int node_index, LB_parameters_gpu *ek_lbparameters_gpu)
__device__ void ek_diffusion_migration_lbforce_linkcentered_stencil (unsigned int index, unsigned int index_padded, unsigned int const *neighborindex, unsigned int const *neighborindex_padded, unsigned int species_index, LB_node_force_density_gpu node_f, LB_nodes_gpu lb_node)
__device__ void ek_diffusion_migration_lbforce_nodecentered_stencil (unsigned int index, unsigned int index_padded, unsigned int const *neighborindex, unsigned int const *neighborindex_padded, unsigned int species_index, LB_node_force_density_gpu node_f, LB_nodes_gpu lb_node)
__device__ void ek_add_advection_to_flux (unsigned int index, unsigned int *coord, unsigned int species_index, LB_nodes_gpu lb_node, LB_parameters_gpu *ek_lbparameters_gpu)
__device__ float4 ek_random_wrapper_philox (unsigned int index, unsigned int mode, uint64_t philox_counter)
__device__ void ek_add_fluctuations_to_flux (unsigned int index, unsigned int species_index, unsigned int const *neighborindex, LB_nodes_gpu lb_node, uint64_t philox_counter)
__global__ void ek_calculate_quantities (unsigned int species_index, LB_nodes_gpu lb_node, LB_node_force_density_gpu node_f, LB_parameters_gpu *ek_lbparameters_gpu, uint64_t philox_counter)
__global__ void ek_propagate_densities (unsigned int species_index)
__global__ void ek_apply_boundaries (LB_nodes_gpu lbnode)
__global__ void ek_clear_fluxes ()
__global__ void ek_init_species_density_homogeneous ()
__global__ void ek_gather_species_charge_density ()
__global__ void ek_gather_particle_charge_density (CUDA_particle_data *particle_data, std::size_t number_of_particles, LB_parameters_gpu *ek_lbparameters_gpu)
__global__ void ek_spread_particle_force (CUDA_particle_data *particle_data, std::size_t number_of_particles, float *particle_forces, LB_parameters_gpu *ek_lbparameters_gpu)
__global__ void ek_calc_electric_field (const float *potential)
__global__ void ek_clear_boundary_densities (LB_nodes_gpu lbnode)
__global__ void ek_calculate_system_charge (float *charge_gpu)
__global__ void ek_clear_node_force (LB_node_force_density_gpu node_f)
void ek_calculate_electrostatic_coupling ()
void ek_integrate_electrostatics ()
void ek_integrate ()
void ek_gather_wallcharge_species_density (float *wallcharge_species_density, int wallcharge_species)
void ek_init_species_density_wallcharge (float *wallcharge_species_density, int wallcharge_species)
void ek_init_species (int species)
int ek_init ()
unsigned int ek_calculate_boundary_mass ()
void rhoindex_linear2cartesian_host (unsigned int index, unsigned int *coord)
unsigned int jindex_cartesian2linear_host (unsigned int x, unsigned int y, unsigned int z, unsigned int c)
unsigned int jindex_getByRhoLinear_host (unsigned int rho_index, unsigned int c)
unsigned int rhoindex_cartesian2linear_host (unsigned int x, unsigned int y, unsigned int z)
int ek_lb_print_vtk_velocity (char *filename)
int ek_lb_print_vtk_density (char *filename)
int ek_print_vtk_density (int species, char *filename)
int ek_node_get_density (int species, int x, int y, int z, double *density)
int ek_node_get_flux (int species, int x, int y, int z, double *flux)
int ek_node_set_density (int species, int x, int y, int z, double density)
int ek_print_vtk_flux (int species, char *filename)
int ek_print_vtk_flux_fluc (int species, char *filename)
int ek_print_vtk_flux_link (int species, char *filename)
int ek_node_get_potential (int x, int y, int z, double *potential)
int ek_print_vtk_potential (char *filename)
int ek_print_vtk_particle_potential (char *filename)
int ek_print_vtk_lbforce_density (char *filename)
void ek_print_parameters ()
void ek_print_lbpar ()
void ek_setter_throw_if_initialized ()
void ek_set_agrid (float agrid)
void ek_set_lb_density (float lb_density)
void ek_set_prefactor (float prefactor)
void ek_set_electrostatics_coupling (bool electrostatics_coupling)
void ek_set_viscosity (float viscosity)
void ek_set_lb_ext_force_density (float lb_ext_force_dens_x, float lb_ext_force_dens_y, float lb_ext_force_dens_z)
void ek_set_friction (float friction)
void ek_set_bulk_viscosity (float bulk_viscosity)
void ek_set_gamma_odd (float gamma_odd)
void ek_set_gamma_even (float gamma_even)
void ek_set_stencil (int stencil)
void ek_set_advection (bool advection)
void ek_set_fluctuations (bool fluctuations)
void ek_set_fluctuation_amplitude (float fluctuation_amplitude)
void ek_set_fluidcoupling (bool ideal_contribution)
void ek_set_T (float T)
void ek_set_density (int species, float density)
void ek_set_D (int species, float D)
void ek_set_valency (int species, float valency)
void ek_set_ext_force_density (int species, float ext_force_density_x, float ext_force_density_y, float ext_force_density_z)
float ek_get_particle_charge ()
float ek_calculate_net_charge ()
int ek_neutralize_system (int species)
void ek_set_rng_state (uint64_t counter)
Variables
ActiveLB lattice_switch
bool ek_initialized
static constexpr unsigned int threads_per_block = 64
EKParameters ek_parameters
__device__ __constant__ EKParameters ek_parameters_gpu [1]
float * charge_gpu
LB_parameters_gpu * ek_lbparameters_gpu
CUDA_particle_data * particle_data_gpu
float * ek_lb_boundary_force
char * ek_node_is_catalyst
unsigned int old_number_of_species = 0
unsigned int old_number_of_boundaries = 0
Utils::Counter< uint64_t > philox_counter = Utils::Counter<uint64_t>(0)
FdElectrostatics * electrostatics = nullptr
LB_parameters_gpu lbpar_gpu
LB_node_force_density_gpu node_f
struct for node force density
LB_node_force_density_gpu node_f_buf
LB_nodes_gpu * current_nodes
EKParameters * lb_ek_parameters
Macro Definition Documentation
EK_LINK_00D_pressure
#define EK_LINK_00D_pressure 5
Definition at line 71 of file electrokinetics_cuda.cu.
EK_LINK_00U_pressure
#define EK_LINK_00U_pressure 2
Definition at line 68 of file electrokinetics_cuda.cu.
EK_LINK_0D0_pressure
#define EK_LINK_0D0_pressure 4
Definition at line 70 of file electrokinetics_cuda.cu.
EK_LINK_0U0_pressure
#define EK_LINK_0U0_pressure 1
Definition at line 67 of file electrokinetics_cuda.cu.
EK_LINK_D00_pressure
#define EK_LINK_D00_pressure 3
Definition at line 69 of file electrokinetics_cuda.cu.
EK_LINK_U00_pressure
#define EK_LINK_U00_pressure 0
Definition at line 66 of file electrokinetics_cuda.cu.
Function Documentation
ek_add_advection_to_flux()
__device__ void ek_add_advection_to_flux (unsigned int index, unsigned int * coord, unsigned int species_index, LB_nodes_gpu lb_node, LB_parameters_gpu * ek_lbparameters_gpu)
Definition at line 1094 of file electrokinetics_cuda.cu.
References LB_nodes_gpu::boundary, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_displacement(), ek_lbparameters_gpu, EK_LINK_00U, EK_LINK_0U0, EK_LINK_0UU, EK_LINK_U00, EK_LINK_U0U, EK_LINK_UDD, EK_LINK_UU0, EK_LINK_UUU, ek_parameters_gpu, EKParameters::j, jindex_getByRhoLinear(), node, EKParameters::rho, and rhoindex_cartesian2linear().
Referenced by ek_calculate_quantities().
ek_add_fluctuations_to_flux()
__device__ void ek_add_fluctuations_to_flux (unsigned int index, unsigned int species_index, unsigned int const * neighborindex, LB_nodes_gpu lb_node, uint64_t philox_counter)
Definition at line 1301 of file electrokinetics_cuda.cu.
References EKParameters::agrid, LB_nodes_gpu::boundary, EKParameters::D, ek_parameters_gpu, ek_random_wrapper_philox(), f, EKParameters::fluctuation_amplitude, EKParameters::j, EKParameters::j_fluc, jindex_getByRhoLinear(), anonymous_namespace{Correlator.cpp}::min(), philox_counter, EKParameters::rho, EKParameters::time_step, and time_step.
Referenced by ek_calculate_quantities().
ek_apply_boundaries()
__global__ void ek_apply_boundaries (LB_nodes_gpu lbnode)
Definition at line 1642 of file electrokinetics_cuda.cu.
References LB_nodes_gpu::boundary, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_getThreadIndex(), EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters_gpu, EKParameters::j, jindex_getByRhoLinear(), rhoindex_cartesian2linear(), and rhoindex_linear2cartesian().
Referenced by ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
ek_calc_electric_field()
__global__ void ek_calc_electric_field (const float * potential)
Definition at line 1992 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_getThreadIndex(), ek_parameters_gpu, EKParameters::electric_field, rhoindex_cartesian2linear_padded(), and rhoindex_linear2cartesian().
Referenced by ek_integrate_electrostatics().
ek_calculate_boundary_mass()
unsigned int ek_calculate_boundary_mass ()
Definition at line 2384 of file electrokinetics_cuda.cu.
References ek_parameters, lb_get_boundary_flags_GPU(), lbpar_gpu, EKParameters::number_of_nodes, and LB_parameters_gpu::number_of_nodes.
ek_calculate_electrostatic_coupling()
void ek_calculate_electrostatic_coupling ()
Definition at line 2073 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), ek_initialized, ek_lbparameters_gpu, ek_parameters, ek_spread_particle_force(), EKParameters::es_coupling, gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, and threads_per_block.
Referenced by Coulomb::calc_long_range_force().
ek_calculate_net_charge()
float ek_calculate_net_charge ()
Definition at line 3769 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), charge_gpu, cuda_safe_mem, ek_calculate_system_charge(), ek_get_particle_charge(), ek_parameters, EKParameters::es_coupling, KERNELCALL, EKParameters::number_of_nodes, and threads_per_block.
Referenced by ek_neutralize_system().
ek_calculate_quantities()
__global__ void ek_calculate_quantities (unsigned int species_index, LB_nodes_gpu lb_node, LB_node_force_density_gpu node_f, LB_parameters_gpu * ek_lbparameters_gpu, uint64_t philox_counter)
Definition at line 1372 of file electrokinetics_cuda.cu.
References EKParameters::advection, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_add_advection_to_flux(), ek_add_fluctuations_to_flux(), ek_diffusion_migration_lbforce_linkcentered_stencil(), ek_diffusion_migration_lbforce_nodecentered_stencil(), ek_getThreadIndex(), ek_lbparameters_gpu, EK_LINK_00U, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UU0, ek_parameters_gpu, EKParameters::fluctuations, node_f, philox_counter, rhoindex_cartesian2linear(), rhoindex_cartesian2linear_padded(), rhoindex_linear2cartesian(), and EKParameters::stencil.
Referenced by ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
ek_calculate_system_charge()
__global__ void ek_calculate_system_charge (float * charge_gpu)
Definition at line 2041 of file electrokinetics_cuda.cu.
References charge_gpu, ek_getThreadIndex(), ek_parameters_gpu, EKParameters::number_of_species, EKParameters::rho, and EKParameters::valency.
Referenced by ek_calculate_net_charge().
ek_clear_boundary_densities()
__global__ void ek_clear_boundary_densities (LB_nodes_gpu lbnode)
Definition at line 2028 of file electrokinetics_cuda.cu.
References LB_nodes_gpu::boundary, ek_getThreadIndex(), ek_parameters_gpu, EKParameters::number_of_species, and EKParameters::rho.
Referenced by ek_init_species_density_wallcharge().
ek_clear_fluxes()
__global__ void ek_clear_fluxes ()
Definition at line 1749 of file electrokinetics_cuda.cu.
References ek_getThreadIndex(), ek_parameters_gpu, EKParameters::j, EKParameters::j_fluc, and jindex_getByRhoLinear().
Referenced by ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
ek_clear_node_force()
__global__ void ek_clear_node_force (LB_node_force_density_gpu node_f)
Definition at line 2055 of file electrokinetics_cuda.cu.
References ek_getThreadIndex(), ek_parameters_gpu, LB_node_force_density_gpu::force_density, EKParameters::lb_force_density_previous, node_f, and EKParameters::number_of_nodes.
Referenced by ek_init().
ek_diffusion_migration_lbforce_linkcentered_stencil()
__device__ void ek_diffusion_migration_lbforce_linkcentered_stencil (unsigned int index, unsigned int index_padded, unsigned int const * neighborindex, unsigned int const * neighborindex_padded, unsigned int species_index, LB_node_force_density_gpu node_f, LB_nodes_gpu lb_node)
Definition at line 309 of file electrokinetics_cuda.cu.
References EKParameters::agrid, LB_nodes_gpu::boundary, EKParameters::charge_potential, EKParameters::D, EKParameters::d, EK_LINK_00U, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UU0, ek_parameters_gpu, EKParameters::ext_force_density, f, EKParameters::fluidcoupling_ideal_contribution, force, LB_node_force_density_gpu::force_density, EKParameters::j, jindex_getByRhoLinear(), node_f, EKParameters::rho, EKParameters::T, EKParameters::time_step, and EKParameters::valency.
Referenced by ek_calculate_quantities().
ek_diffusion_migration_lbforce_nodecentered_stencil()
__device__ void ek_diffusion_migration_lbforce_nodecentered_stencil (unsigned int index, unsigned int index_padded, unsigned int const * neighborindex, unsigned int const * neighborindex_padded, unsigned int species_index, LB_node_force_density_gpu node_f, LB_nodes_gpu lb_node)
Definition at line 719 of file electrokinetics_cuda.cu.
References EKParameters::agrid, LB_nodes_gpu::boundary, EKParameters::charge_potential, EKParameters::D, EKParameters::d, EK_LINK_00U, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UU0, ek_parameters_gpu, EKParameters::ext_force_density, f, force, LB_node_force_density_gpu::force_density, EKParameters::j, jindex_getByRhoLinear(), node_f, EKParameters::rho, EKParameters::T, EKParameters::time_step, and EKParameters::valency.
Referenced by ek_calculate_quantities().
ek_displacement()
__device__ void ek_displacement (float * dx, LB_nodes_gpu n, unsigned int node_index, LB_parameters_gpu * ek_lbparameters_gpu)
Definition at line 265 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, ek_lbparameters_gpu, ek_parameters_gpu, EKParameters::lb_force_density_previous, EKParameters::number_of_nodes, LB_nodes_gpu::populations, and LB_parameters_gpu::rho.
Referenced by ek_add_advection_to_flux().
ek_gather_particle_charge_density()
__global__ void ek_gather_particle_charge_density (CUDA_particle_data * particle_data, std::size_t number_of_particles, LB_parameters_gpu * ek_lbparameters_gpu)
Definition at line 1791 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::charge_potential, LB_parameters_gpu::dim, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_getThreadIndex(), ek_lbparameters_gpu, ek_parameters_gpu, CUDA_particle_data::p, CUDA_particle_data::q, and rhoindex_cartesian2linear_padded().
Referenced by ek_integrate_electrostatics().
ek_gather_species_charge_density()
__global__ void ek_gather_species_charge_density ()
Definition at line 1777 of file electrokinetics_cuda.cu.
References EKParameters::agrid, ek_getThreadIndex(), ek_parameters_gpu, ek_setNode(), f, EKParameters::number_of_species, EKParameters::rho, and EKParameters::valency.
Referenced by ek_integrate_electrostatics().
ek_gather_wallcharge_species_density()
void ek_gather_wallcharge_species_density (float * wallcharge_species_density, int wallcharge_species)
Definition at line 2153 of file electrokinetics_cuda.cu.
References cuda_safe_mem, ek_parameters, EKParameters::number_of_nodes, and EKParameters::rho.
Referenced by LBBoundaries::ek_init_boundaries().
ek_get_particle_charge()
float ek_get_particle_charge ()
Definition at line 3760 of file electrokinetics_cuda.cu.
References f, and gpu_get_particle_pointer().
Referenced by ek_calculate_net_charge(), and ek_neutralize_system().
ek_getNode() [1/2]
__device__ cufftReal ek_getNode (unsigned i)
Definition at line 212 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, ek_getNode(), and ek_parameters_gpu.
ek_getNode() [2/2]
__device__ cufftReal ek_getNode (unsigned x, unsigned y, unsigned z)
Definition at line 197 of file electrokinetics_cuda.cu.
References EKParameters::charge_potential, EKParameters::dim_x_padded, EKParameters::dim_y, and ek_parameters_gpu.
Referenced by ek_getNode().
ek_getThreadIndex()
__device__ unsigned int ek_getThreadIndex ()
Definition at line 228 of file electrokinetics_cuda.cu.
Referenced by ek_apply_boundaries(), ek_calc_electric_field(), ek_calculate_quantities(), ek_calculate_system_charge(), ek_clear_boundary_densities(), ek_clear_fluxes(), ek_clear_node_force(), ek_gather_particle_charge_density(), ek_gather_species_charge_density(), ek_init_species_density_homogeneous(), ek_propagate_densities(), and ek_spread_particle_force().
ek_init()
int ek_init ()
Definition at line 2206 of file electrokinetics_cuda.cu.
References Utils::abs(), EKParameters::agrid, LB_parameters_gpu::agrid, EKParameters::bulk_viscosity, LB_parameters_gpu::bulk_viscosity, calculate_dim_grid(), charge_gpu, EKParameters::charge_potential, EKParameters::charge_potential_buffer, cuda_safe_mem, LB_parameters_gpu::dim, EKParameters::dim_x, EKParameters::dim_x_padded, EKParameters::dim_y, EKParameters::dim_z, ek_clear_node_force(), ek_init_species_density_homogeneous(), ek_initialized, ek_integrate_electrostatics(), ek_lb_boundary_force, ek_lbparameters_gpu, ek_parameters, ek_parameters_gpu, EKParameters::electric_field, electrostatics, EKParameters::es_coupling, LB_parameters_gpu::ext_force_density, LB_parameters_gpu::external_force_density, EKParameters::friction, get_time_step(), FdElectrostatics::getGrid(), GPU, FdElectrostatics::Grid::grid, LB_parameters_gpu::is_TRT, EKParameters::j, EKParameters::j_fluc, KERNELCALL, lattice_switch, EKParameters::lb_density, EKParameters::lb_ext_force_density, EKParameters::lb_force_density_previous, lb_get_boundary_force_pointer(), lb_get_para_pointer(), LBBoundaries::lb_init_boundaries(), lb_init_gpu(), lb_lbcoupling_get_gamma(), lb_lbcoupling_set_gamma(), lb_reinit_parameters_gpu(), lbpar_gpu, node_f, EKParameters::node_is_catalyst, NONE, EKParameters::number_of_nodes, EKParameters::prefactor, LB_parameters_gpu::rho, EKParameters::species_index, Utils::sqr(), stream, EKParameters::T, threads_per_block, EKParameters::time_step, time_step, EKParameters::viscosity, and LB_parameters_gpu::viscosity.
Referenced by ek_init_species().
ek_init_species()
void ek_init_species (int species)
Definition at line 2177 of file electrokinetics_cuda.cu.
References cuda_safe_mem, EKParameters::D, EKParameters::d, EKParameters::density, ek_init(), ek_initialized, ek_parameters, EKParameters::ext_force_density, f, EKParameters::number_of_nodes, EKParameters::number_of_species, EKParameters::rho, EKParameters::species_index, Utils::sqrt(), and EKParameters::valency.
Referenced by ek_set_D(), ek_set_density(), ek_set_ext_force_density(), and ek_set_valency().
ek_init_species_density_homogeneous()
__global__ void ek_init_species_density_homogeneous ()
Definition at line 1762 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::density, ek_getThreadIndex(), ek_parameters_gpu, EKParameters::number_of_species, EKParameters::rho, and rhoindex_linear2cartesian().
Referenced by ek_init().
ek_init_species_density_wallcharge()
void ek_init_species_density_wallcharge (float * wallcharge_species_density, int wallcharge_species)
Definition at line 2161 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, ek_clear_boundary_densities(), ek_parameters, KERNELCALL, EKParameters::number_of_nodes, EKParameters::rho, and threads_per_block.
Referenced by LBBoundaries::ek_init_boundaries().
ek_integrate()
void ek_integrate ()
Definition at line 2121 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), current_nodes, ek_calculate_quantities(), ek_clear_fluxes(), ek_integrate_electrostatics(), ek_lbparameters_gpu, ek_parameters, ek_propagate_densities(), Utils::Counter< T >::increment(), KERNELCALL, lb_integrate_GPU(), node_f, EKParameters::number_of_nodes, EKParameters::number_of_species, philox_counter, threads_per_block, and Utils::Counter< T >::value().
Referenced by lb_lbfluid_integrate().
ek_integrate_electrostatics()
void ek_integrate_electrostatics ()
Definition at line 2087 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), FdElectrostatics::calculatePotential(), EKParameters::charge_potential, EKParameters::charge_potential_buffer, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_calc_electric_field(), ek_gather_particle_charge_density(), ek_gather_species_charge_density(), ek_lbparameters_gpu, ek_parameters, electrostatics, EKParameters::es_coupling, gpu_get_particle_pointer(), KERNELCALL, EKParameters::number_of_nodes, particle_data_gpu, and threads_per_block.
Referenced by ek_init(), ek_integrate(), and on_observable_calc().
ek_lb_print_vtk_density()
int ek_lb_print_vtk_density (char * filename)
Definition at line 2469 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim, host_values, lb_get_values_GPU(), lb_lbfluid_get_agrid(), lbpar_gpu, and LB_parameters_gpu::number_of_nodes.
ek_lb_print_vtk_velocity()
int ek_lb_print_vtk_velocity (char * filename)
Definition at line 2430 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim, host_values, lb_get_values_GPU(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, and LB_parameters_gpu::tau.
ek_neutralize_system()
int ek_neutralize_system (int species)
Definition at line 3788 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::density, ek_calculate_net_charge(), ek_get_particle_charge(), ek_parameters, EKParameters::es_coupling, f, if(), EKParameters::number_of_boundary_nodes, EKParameters::number_of_nodes, EKParameters::number_of_species, EKParameters::species_index, and EKParameters::valency.
ek_node_get_density()
int ek_node_get_density (int species, int x, int y, int z, double * density)
Definition at line 2553 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, ek_parameters, EKParameters::number_of_nodes, EKParameters::rho, and EKParameters::species_index.
ek_node_get_flux()
int ek_node_get_flux (int species, int x, int y, int z, double * flux)
Definition at line 2573 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters, EKParameters::j, jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_cartesian2linear_host(), EKParameters::species_index, Utils::sqr(), threads_per_block, EKParameters::time_step, and Utils::Counter< T >::value().
ek_node_get_potential()
int ek_node_get_potential (int x, int y, int z, double * potential)
Definition at line 3327 of file electrokinetics_cuda.cu.
References EKParameters::charge_potential, cuda_safe_mem, EKParameters::dim_x_padded, EKParameters::dim_y, and ek_parameters.
ek_node_set_density()
int ek_node_set_density (int species, int x, int y, int z, double density)
Definition at line 2772 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, ek_parameters, EKParameters::rho, and EKParameters::species_index.
ek_print_lbpar()
void ek_print_lbpar ()
Definition at line 3601 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::bulk_viscosity, LB_parameters_gpu::dim, LB_parameters_gpu::ext_force_density, LB_parameters_gpu::external_force_density, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_even, LB_parameters_gpu::gamma_odd, LB_parameters_gpu::gamma_shear, lbpar_gpu, LB_parameters_gpu::mu, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::rho, LB_parameters_gpu::tau, and LB_parameters_gpu::viscosity.
ek_print_parameters()
void ek_print_parameters ()
Definition at line 3478 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::bulk_viscosity, EKParameters::D, EKParameters::d, EKParameters::density, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, EKParameters::ext_force_density, EKParameters::friction, EKParameters::gamma_even, EKParameters::gamma_odd, EKParameters::j, EKParameters::lb_density, EKParameters::lb_ext_force_density, EKParameters::number_of_nodes, EKParameters::number_of_species, EKParameters::prefactor, EKParameters::reaction_ct_rate, EKParameters::reaction_fraction_0, EKParameters::reaction_species, EKParameters::rho, EKParameters::rho_product0_reservoir, EKParameters::rho_product1_reservoir, EKParameters::rho_reactant_reservoir, EKParameters::species_index, EKParameters::T, EKParameters::time_step, EKParameters::valency, and EKParameters::viscosity.
ek_print_vtk_density()
int ek_print_vtk_density (int species, char * filename)
Definition at line 2507 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, EKParameters::number_of_nodes, EKParameters::rho, and EKParameters::species_index.
ek_print_vtk_flux()
int ek_print_vtk_flux (int species, char * filename)
Definition at line 2791 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters, EKParameters::j, jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_linear2cartesian_host(), EKParameters::species_index, Utils::sqr(), threads_per_block, EKParameters::time_step, and Utils::Counter< T >::value().
ek_print_vtk_flux_fluc()
int ek_print_vtk_flux_fluc (int species, char * filename)
Definition at line 3017 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters, EKParameters::j_fluc, jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_linear2cartesian_host(), EKParameters::species_index, threads_per_block, and Utils::Counter< T >::value().
ek_print_vtk_flux_link()
int ek_print_vtk_flux_link (int species, char * filename)
Definition at line 3250 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, ek_parameters, EKParameters::j, jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_linear2cartesian_host(), EKParameters::species_index, threads_per_block, and Utils::Counter< T >::value().
ek_print_vtk_lbforce_density()
int ek_print_vtk_lbforce_density (char * filename)
Definition at line 3429 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, LB_node_force_density_gpu::force_density_buf, node_f, EKParameters::number_of_nodes, and EKParameters::time_step.
ek_print_vtk_particle_potential()
int ek_print_vtk_particle_potential (char * filename)
Definition at line 3385 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::charge_potential_buffer, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_x_padded, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, and EKParameters::number_of_nodes.
ek_print_vtk_potential()
int ek_print_vtk_potential (char * filename)
Definition at line 3341 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::charge_potential, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_x_padded, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, and EKParameters::number_of_nodes.
ek_propagate_densities()
__global__ void ek_propagate_densities (unsigned int species_index)
Definition at line 1488 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_getThreadIndex(), EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters_gpu, EKParameters::j, jindex_getByRhoLinear(), EKParameters::rho, rhoindex_cartesian2linear(), and rhoindex_linear2cartesian().
Referenced by ek_integrate().
ek_random_wrapper_philox()
__device__ float4 ek_random_wrapper_philox (unsigned int index, unsigned int mode, uint64_t philox_counter)
Definition at line 1280 of file electrokinetics_cuda.cu.
References f, and philox_counter.
Referenced by ek_add_fluctuations_to_flux().
ek_set_advection()
void ek_set_advection (bool advection)
Definition at line 3697 of file electrokinetics_cuda.cu.
References EKParameters::advection, ek_parameters, and ek_setter_throw_if_initialized().
ek_set_agrid()
void ek_set_agrid (float agrid)
Definition at line 3634 of file electrokinetics_cuda.cu.
References EKParameters::agrid, ek_parameters, and ek_setter_throw_if_initialized().
ek_set_bulk_viscosity()
void ek_set_bulk_viscosity (float bulk_viscosity)
Definition at line 3673 of file electrokinetics_cuda.cu.
References EKParameters::bulk_viscosity, ek_parameters, and ek_setter_throw_if_initialized().
ek_set_D()
void ek_set_D (int species, float D)
Definition at line 3730 of file electrokinetics_cuda.cu.
References EKParameters::D, EKParameters::d, ek_init_species(), ek_parameters, f, EKParameters::species_index, and Utils::sqrt().
ek_set_density()
void ek_set_density (int species, float density)
Definition at line 3725 of file electrokinetics_cuda.cu.
References EKParameters::density, ek_init_species(), ek_parameters, and EKParameters::species_index.
ek_set_electrostatics_coupling()
void ek_set_electrostatics_coupling (bool electrostatics_coupling)
Definition at line 3649 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::es_coupling.
ek_set_ext_force_density()
void ek_set_ext_force_density (int species, float ext_force_density_x, float ext_force_density_y, float ext_force_density_z)
Definition at line 3742 of file electrokinetics_cuda.cu.
References ek_init_species(), ek_parameters, EKParameters::ext_force_density, and EKParameters::species_index.
ek_set_fluctuation_amplitude()
void ek_set_fluctuation_amplitude (float fluctuation_amplitude)
Definition at line 3707 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::fluctuation_amplitude.
ek_set_fluctuations()
void ek_set_fluctuations (bool fluctuations)
Definition at line 3702 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::fluctuations.
ek_set_fluidcoupling()
void ek_set_fluidcoupling (bool ideal_contribution)
Definition at line 3712 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), EKParameters::fluidcoupling_ideal_contribution, and EKParameters::stencil.
ek_set_friction()
void ek_set_friction (float friction)
Definition at line 3668 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::friction.
ek_set_gamma_even()
void ek_set_gamma_even (float gamma_even)
Definition at line 3683 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::gamma_even.
ek_set_gamma_odd()
void ek_set_gamma_odd (float gamma_odd)
Definition at line 3678 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::gamma_odd.
ek_set_lb_density()
void ek_set_lb_density (float lb_density)
Definition at line 3639 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::lb_density.
ek_set_lb_ext_force_density()
void ek_set_lb_ext_force_density (float lb_ext_force_dens_x, float lb_ext_force_dens_y, float lb_ext_force_dens_z)
Definition at line 3659 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::lb_ext_force_density.
ek_set_prefactor()
void ek_set_prefactor (float prefactor)
Definition at line 3644 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::prefactor.
ek_set_rng_state()
void ek_set_rng_state (uint64_t counter)
Definition at line 3835 of file electrokinetics_cuda.cu.
References ek_initialized, and philox_counter.
ek_set_stencil()
void ek_set_stencil (int stencil)
Definition at line 3689 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), EKParameters::fluidcoupling_ideal_contribution, and EKParameters::stencil.
ek_set_T()
void ek_set_T (float T)
Definition at line 3720 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::T.
ek_set_valency()
void ek_set_valency (int species, float valency)
Definition at line 3737 of file electrokinetics_cuda.cu.
References ek_init_species(), ek_parameters, EKParameters::species_index, and EKParameters::valency.
ek_set_viscosity()
void ek_set_viscosity (float viscosity)
Definition at line 3654 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::viscosity.
ek_setNode() [1/2]
__device__ void ek_setNode (unsigned i, cufftReal value)
Definition at line 220 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, ek_parameters_gpu, and ek_setNode().
ek_setNode() [2/2]
__device__ void ek_setNode (unsigned x, unsigned y, unsigned z, cufftReal value)
Definition at line 204 of file electrokinetics_cuda.cu.
References EKParameters::charge_potential, EKParameters::dim_x_padded, EKParameters::dim_y, and ek_parameters_gpu.
Referenced by ek_gather_species_charge_density(), and ek_setNode().
ek_setter_throw_if_initialized()
void ek_setter_throw_if_initialized () inline
Definition at line 3628 of file electrokinetics_cuda.cu.
References ek_initialized.
Referenced by ek_set_advection(), ek_set_agrid(), ek_set_bulk_viscosity(), ek_set_electrostatics_coupling(), ek_set_fluctuation_amplitude(), ek_set_fluctuations(), ek_set_fluidcoupling(), ek_set_friction(), ek_set_gamma_even(), ek_set_gamma_odd(), ek_set_lb_density(), ek_set_lb_ext_force_density(), ek_set_prefactor(), ek_set_stencil(), ek_set_T(), and ek_set_viscosity().
ek_spread_particle_force()
__global__ void ek_spread_particle_force (CUDA_particle_data * particle_data, std::size_t number_of_particles, float * particle_forces, LB_parameters_gpu * ek_lbparameters_gpu)
Definition at line 1876 of file electrokinetics_cuda.cu.
References EKParameters::agrid, LB_parameters_gpu::dim, ek_getThreadIndex(), ek_lbparameters_gpu, ek_parameters_gpu, EKParameters::electric_field, CUDA_particle_data::p, CUDA_particle_data::q, and rhoindex_cartesian2linear().
Referenced by ek_calculate_electrostatic_coupling().
jindex_cartesian2linear_host()
unsigned int jindex_cartesian2linear_host (unsigned int x, unsigned int y, unsigned int z, unsigned int c)
Definition at line 2406 of file electrokinetics_cuda.cu.
References D3Q19::c, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, and EKParameters::number_of_nodes.
Referenced by ek_node_get_flux(), ek_print_vtk_flux(), and ek_print_vtk_flux_fluc().
jindex_getByRhoLinear()
__device__ unsigned int jindex_getByRhoLinear (unsigned int rho_index, unsigned int c)
Definition at line 259 of file electrokinetics_cuda.cu.
References D3Q19::c, ek_parameters_gpu, and EKParameters::number_of_nodes.
Referenced by ek_add_advection_to_flux(), ek_add_fluctuations_to_flux(), ek_apply_boundaries(), ek_clear_fluxes(), ek_diffusion_migration_lbforce_linkcentered_stencil(), ek_diffusion_migration_lbforce_nodecentered_stencil(), and ek_propagate_densities().
jindex_getByRhoLinear_host()
unsigned int jindex_getByRhoLinear_host (unsigned int rho_index, unsigned int c)
Definition at line 2417 of file electrokinetics_cuda.cu.
References D3Q19::c, ek_parameters, and EKParameters::number_of_nodes.
Referenced by ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
rhoindex_cartesian2linear()
__device__ unsigned int rhoindex_cartesian2linear (unsigned int x, unsigned int y, unsigned int z)
Definition at line 244 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, and ek_parameters_gpu.
Referenced by ek_add_advection_to_flux(), ek_apply_boundaries(), ek_calculate_quantities(), ek_propagate_densities(), and ek_spread_particle_force().
rhoindex_cartesian2linear_host()
unsigned int rhoindex_cartesian2linear_host (unsigned int x, unsigned int y, unsigned int z)
Definition at line 2423 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, and ek_parameters.
Referenced by ek_node_get_flux().
rhoindex_cartesian2linear_padded()
__device__ unsigned int rhoindex_cartesian2linear_padded (unsigned int x, unsigned int y, unsigned int z)
Definition at line 250 of file electrokinetics_cuda.cu.
References EKParameters::dim_x_padded, EKParameters::dim_y, and ek_parameters_gpu.
Referenced by ek_calc_electric_field(), ek_calculate_quantities(), and ek_gather_particle_charge_density().
rhoindex_linear2cartesian()
__device__ void rhoindex_linear2cartesian (unsigned int index, unsigned int * coord)
Definition at line 234 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, and ek_parameters_gpu.
Referenced by ek_apply_boundaries(), ek_calc_electric_field(), ek_calculate_quantities(), ek_init_species_density_homogeneous(), and ek_propagate_densities().
rhoindex_linear2cartesian_host()
void rhoindex_linear2cartesian_host (unsigned int index, unsigned int * coord)
Definition at line 2398 of file electrokinetics_cuda.cu.
References EKParameters::dim_x, EKParameters::dim_y, and ek_parameters.
Referenced by ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
Variable Documentation
charge_gpu
float* charge_gpu
Definition at line 181 of file electrokinetics_cuda.cu.
Referenced by ek_calculate_net_charge(), ek_calculate_system_charge(), and ek_init().
current_nodes
LB_nodes_gpu* current_nodes
Definition at line 108 of file lbgpu_cuda.cu.
Referenced by ek_init_species_density_wallcharge(), ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
ek_initialized
bool ek_initialized
Definition at line 85 of file lbgpu.cpp.
Referenced by ek_calculate_electrostatic_coupling(), ek_init(), ek_init_species(), ek_set_rng_state(), and ek_setter_throw_if_initialized().
ek_lb_boundary_force
float* ek_lb_boundary_force
Definition at line 184 of file electrokinetics_cuda.cu.
Referenced by ek_init().
ek_lbparameters_gpu
LB_parameters_gpu* ek_lbparameters_gpu
Definition at line 182 of file electrokinetics_cuda.cu.
Referenced by ek_add_advection_to_flux(), ek_calculate_electrostatic_coupling(), ek_calculate_quantities(), ek_displacement(), ek_gather_particle_charge_density(), ek_init(), ek_integrate(), ek_integrate_electrostatics(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), and ek_spread_particle_force().
ek_node_is_catalyst
char* ek_node_is_catalyst
Definition at line 185 of file electrokinetics_cuda.cu.
ek_parameters
EKParameters ek_parameters
Definition at line 79 of file electrokinetics_cuda.cu.
Referenced by ek_calculate_boundary_mass(), ek_calculate_electrostatic_coupling(), ek_calculate_net_charge(), ek_gather_wallcharge_species_density(), ek_init(), LBBoundaries::ek_init_boundaries(), ek_init_species(), ek_init_species_density_wallcharge(), ek_integrate(), ek_integrate_electrostatics(), ek_neutralize_system(), ek_node_get_density(), ek_node_get_flux(), ek_node_get_potential(), ek_node_set_density(), ek_print_parameters(), ek_print_vtk_density(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), ek_print_vtk_lbforce_density(), ek_print_vtk_particle_potential(), ek_print_vtk_potential(), ek_set_advection(), ek_set_agrid(), ek_set_bulk_viscosity(), ek_set_D(), ek_set_density(), ek_set_electrostatics_coupling(), ek_set_ext_force_density(), ek_set_fluctuation_amplitude(), ek_set_fluctuations(), ek_set_fluidcoupling(), ek_set_friction(), ek_set_gamma_even(), ek_set_gamma_odd(), ek_set_lb_density(), ek_set_lb_ext_force_density(), ek_set_prefactor(), ek_set_stencil(), ek_set_T(), ek_set_valency(), ek_set_viscosity(), jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), rhoindex_cartesian2linear_host(), and rhoindex_linear2cartesian_host().
ek_parameters_gpu
__device__ __constant__ EKParameters ek_parameters_gpu[1]
Definition at line 180 of file electrokinetics_cuda.cu.
Referenced by ek_add_advection_to_flux(), ek_add_fluctuations_to_flux(), ek_apply_boundaries(), ek_calc_electric_field(), ek_calculate_quantities(), ek_calculate_system_charge(), ek_clear_boundary_densities(), ek_clear_fluxes(), ek_clear_node_force(), ek_diffusion_migration_lbforce_linkcentered_stencil(), ek_diffusion_migration_lbforce_nodecentered_stencil(), ek_displacement(), ek_gather_particle_charge_density(), ek_gather_species_charge_density(), ek_getNode(), ek_init(), ek_init_species_density_homogeneous(), ek_propagate_densities(), ek_setNode(), ek_spread_particle_force(), jindex_getByRhoLinear(), rhoindex_cartesian2linear(), rhoindex_cartesian2linear_padded(), and rhoindex_linear2cartesian().
electrostatics
FdElectrostatics* electrostatics = nullptr
Definition at line 190 of file electrokinetics_cuda.cu.
Referenced by ek_init(), and ek_integrate_electrostatics().
lattice_switch
ActiveLB lattice_switch
Definition at line 46 of file lb_interface.cpp.
Referenced by ek_init(), global_ghost_flags(), IBM_UpdateParticlePositions(), LBBoundaries::lb_init_boundaries(), lb_lbcoupling_calc_particle_lattice_ia(), lb_lbcoupling_deactivate(), lb_lbcoupling_get_rng_state(), lb_lbcoupling_is_seed_required(), lb_lbcoupling_propagate(), lb_lbcoupling_set_rng_state(), and LBBoundaries::lbboundary_get_force().
lb_ek_parameters
EKParameters* lb_ek_parameters
lbpar_gpu
LB_parameters_gpu lbpar_gpu
Definition at line 44 of file lbgpu.cpp.
Referenced by ek_calculate_boundary_mass(), ek_init(), LBBoundaries::ek_init_boundaries(), ek_lb_print_vtk_density(), ek_lb_print_vtk_velocity(), ek_print_lbpar(), lb_calc_fluid_mass_GPU(), lb_calc_fluid_momentum_GPU(), lb_calc_particle_lattice_ia_gpu(), lb_get_boundary_flags_GPU(), lb_get_values_GPU(), LBBoundaries::lb_init_boundaries(), lb_init_boundaries_GPU(), lb_init_GPU(), lb_integrate_GPU(), lb_lbfluid_get_agrid(), lb_lbfluid_get_bulk_viscosity(), lb_lbfluid_get_density(), lb_lbfluid_get_ext_force_density(), lb_lbfluid_get_gamma_even(), lb_lbfluid_get_gamma_odd(), lb_lbfluid_get_kT(), lb_lbfluid_get_pressure_tensor(), lb_lbfluid_get_shape(), lb_lbfluid_get_tau(), lb_lbfluid_get_viscosity(), lb_lbfluid_load_checkpoint(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_velocity(), lb_lbfluid_save_checkpoint(), lb_lbfluid_set_bulk_viscosity(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force_density(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_kT(), lb_lbfluid_set_tau(), lb_lbfluid_set_viscosity(), lb_lbnode_get_boundary(), lb_lbnode_get_density(), lb_lbnode_get_pressure_tensor_neq(), lb_lbnode_get_velocity(), lb_lbnode_set_density(), lb_lbnode_set_velocity(), lb_load_checkpoint_GPU(), lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), lb_save_checkpoint_GPU(), reinit_parameters_GPU(), reset_LB_force_densities_GPU(), and stress_tensor_GPU().
node_f
LB_node_force_density_gpu node_f
struct for node force density
Definition at line 87 of file lbgpu_cuda.cu.
Referenced by ek_calculate_quantities(), ek_clear_node_force(), ek_diffusion_migration_lbforce_linkcentered_stencil(), ek_diffusion_migration_lbforce_nodecentered_stencil(), ek_init(), ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), and ek_print_vtk_lbforce_density().
node_f_buf
LB_node_force_density_gpu node_f_buf
Definition at line 193 of file electrokinetics_cuda.cu.
old_number_of_boundaries
unsigned int old_number_of_boundaries = 0
Definition at line 187 of file electrokinetics_cuda.cu.
old_number_of_species
unsigned int old_number_of_species = 0
Definition at line 186 of file electrokinetics_cuda.cu.
particle_data_gpu
CUDA_particle_data* particle_data_gpu
Definition at line 183 of file electrokinetics_cuda.cu.
Referenced by ek_integrate_electrostatics().
philox_counter
Utils::Counter<uint64_t> philox_counter = Utils::Counter<uint64_t>(0)
Definition at line 188 of file electrokinetics_cuda.cu.
Referenced by calc_fluid_particle_ia(), calc_viscous_force(), ek_add_fluctuations_to_flux(), ek_calculate_quantities(), ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), ek_random_wrapper_philox(), ek_set_rng_state(), integrate(), random_wrapper_philox(), and thermalize_modes().
threads_per_block
constexpr unsigned int threads_per_block = 64 static constexpr
Definition at line 77 of file electrokinetics_cuda.cu.
Referenced by calculate_dim_grid(), ek_calculate_electrostatic_coupling(), ek_calculate_net_charge(), ek_init(), ek_init_species_density_wallcharge(), ek_integrate(), ek_integrate_electrostatics(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().