ESPResSo: electrokinetics.hpp File Reference
electrokinetics.hpp File Reference
#include "config.hpp"
#include "grid_based_algorithms/lb_boundaries.hpp"
Classes
struct EKParameters
Macros
#define MAX_NUMBER_OF_SPECIES 10
#define EK_LINK_U00 0
#define EK_LINK_0U0 1
#define EK_LINK_00U 2
#define EK_LINK_UU0 3
#define EK_LINK_UD0 4
#define EK_LINK_U0U 5
#define EK_LINK_U0D 6
#define EK_LINK_0UU 7
#define EK_LINK_0UD 8
#define EK_LINK_UUU 9
#define EK_LINK_UUD 10
#define EK_LINK_UDU 11
#define EK_LINK_UDD 12
#define EK_LINK_D00 13
#define EK_LINK_0D0 14
#define EK_LINK_00D 15
#define EK_LINK_DD0 16
#define EK_LINK_DU0 17
#define EK_LINK_D0D 18
#define EK_LINK_D0U 19
#define EK_LINK_0DD 20
#define EK_LINK_0DU 21
#define EK_LINK_DDD 22
#define EK_LINK_DDU 23
#define EK_LINK_DUD 24
#define EK_LINK_DUU 25
Functions
void ek_integrate ()
void ek_integrate_electrostatics ()
void ek_print_parameters ()
void ek_print_lbpar ()
unsigned int ek_calculate_boundary_mass ()
int ek_print_vtk_density (int species, char *filename)
int ek_print_vtk_flux (int species, char *filename)
int ek_print_vtk_flux_fluc (int species, char *filename)
int ek_print_vtk_flux_link (int species, char *filename)
int ek_print_vtk_potential (char *filename)
int ek_print_vtk_particle_potential (char *filename)
int ek_print_vtk_lbforce_density (char *filename)
int ek_lb_print_vtk_density (char *filename)
int ek_lb_print_vtk_velocity (char *filename)
int ek_init ()
void ek_set_agrid (float agrid)
void ek_set_lb_density (float lb_density)
void ek_set_viscosity (float viscosity)
void ek_set_lb_ext_force_density (float lb_ext_force_dens_x, float lb_ext_force_dens_y, float lb_ext_force_dens_z)
void ek_set_friction (float friction)
void ek_set_T (float T)
void ek_set_prefactor (float prefactor)
void ek_set_electrostatics_coupling (bool electrostatics_coupling)
void ek_calculate_electrostatic_coupling ()
void ek_set_bulk_viscosity (float bulk_viscosity)
void ek_set_gamma_odd (float gamma_odd)
void ek_set_gamma_even (float gamma_even)
void ek_set_density (int species, float density)
void ek_set_D (int species, float D)
void ek_set_valency (int species, float valency)
void ek_set_ext_force_density (int species, float ext_force_density_x, float ext_force_density_y, float ext_force_density_z)
void ek_set_stencil (int stencil)
void ek_set_advection (bool advection)
void ek_set_fluidcoupling (bool ideal_contribution)
void ek_set_fluctuations (bool fluctuations)
void ek_set_fluctuation_amplitude (float fluctuation_amplitude)
void ek_set_rng_state (uint64_t counter)
int ek_node_get_density (int species, int x, int y, int z, double *density)
int ek_node_get_flux (int species, int x, int y, int z, double *flux)
int ek_node_get_potential (int x, int y, int z, double *potential)
int ek_node_set_density (int species, int x, int y, int z, double density)
float ek_calculate_net_charge ()
int ek_neutralize_system (int species)
void ek_gather_wallcharge_species_density (float *wallcharge_species_density, int wallcharge_species)
void ek_init_species_density_wallcharge (float *wallcharge_species_density, int wallcharge_species)
Variables
EKParameters ek_parameters
bool ek_initialized
Macro Definition Documentation
EK_LINK_00D
#define EK_LINK_00D 15
Definition at line 119 of file electrokinetics.hpp.
EK_LINK_00U
#define EK_LINK_00U 2
Definition at line 104 of file electrokinetics.hpp.
EK_LINK_0D0
#define EK_LINK_0D0 14
Definition at line 118 of file electrokinetics.hpp.
EK_LINK_0DD
#define EK_LINK_0DD 20
Definition at line 124 of file electrokinetics.hpp.
EK_LINK_0DU
#define EK_LINK_0DU 21
Definition at line 125 of file electrokinetics.hpp.
EK_LINK_0U0
#define EK_LINK_0U0 1
Definition at line 103 of file electrokinetics.hpp.
EK_LINK_0UD
#define EK_LINK_0UD 8
Definition at line 110 of file electrokinetics.hpp.
EK_LINK_0UU
#define EK_LINK_0UU 7
Definition at line 109 of file electrokinetics.hpp.
EK_LINK_D00
#define EK_LINK_D00 13
Definition at line 117 of file electrokinetics.hpp.
EK_LINK_D0D
#define EK_LINK_D0D 18
Definition at line 122 of file electrokinetics.hpp.
EK_LINK_D0U
#define EK_LINK_D0U 19
Definition at line 123 of file electrokinetics.hpp.
EK_LINK_DD0
#define EK_LINK_DD0 16
Definition at line 120 of file electrokinetics.hpp.
EK_LINK_DDD
#define EK_LINK_DDD 22
Definition at line 127 of file electrokinetics.hpp.
EK_LINK_DDU
#define EK_LINK_DDU 23
Definition at line 128 of file electrokinetics.hpp.
EK_LINK_DU0
#define EK_LINK_DU0 17
Definition at line 121 of file electrokinetics.hpp.
EK_LINK_DUD
#define EK_LINK_DUD 24
Definition at line 129 of file electrokinetics.hpp.
EK_LINK_DUU
#define EK_LINK_DUU 25
Definition at line 130 of file electrokinetics.hpp.
EK_LINK_U00
#define EK_LINK_U00 0
Definition at line 102 of file electrokinetics.hpp.
EK_LINK_U0D
#define EK_LINK_U0D 6
Definition at line 108 of file electrokinetics.hpp.
EK_LINK_U0U
#define EK_LINK_U0U 5
Definition at line 107 of file electrokinetics.hpp.
EK_LINK_UD0
#define EK_LINK_UD0 4
Definition at line 106 of file electrokinetics.hpp.
EK_LINK_UDD
#define EK_LINK_UDD 12
Definition at line 115 of file electrokinetics.hpp.
EK_LINK_UDU
#define EK_LINK_UDU 11
Definition at line 114 of file electrokinetics.hpp.
EK_LINK_UU0
#define EK_LINK_UU0 3
Definition at line 105 of file electrokinetics.hpp.
EK_LINK_UUD
#define EK_LINK_UUD 10
Definition at line 113 of file electrokinetics.hpp.
EK_LINK_UUU
#define EK_LINK_UUU 9
Definition at line 112 of file electrokinetics.hpp.
MAX_NUMBER_OF_SPECIES
#define MAX_NUMBER_OF_SPECIES 10
Definition at line 31 of file electrokinetics.hpp.
Function Documentation
ek_calculate_boundary_mass()
unsigned int ek_calculate_boundary_mass ()
Definition at line 2384 of file electrokinetics_cuda.cu.
References ek_parameters, lb_get_boundary_flags_GPU(), lbpar_gpu, EKParameters::number_of_nodes, and LB_parameters_gpu::number_of_nodes.
ek_calculate_electrostatic_coupling()
void ek_calculate_electrostatic_coupling ()
Definition at line 2073 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), ek_initialized, ek_lbparameters_gpu, ek_parameters, ek_spread_particle_force(), EKParameters::es_coupling, gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, and threads_per_block.
Referenced by Coulomb::calc_long_range_force().
ek_calculate_net_charge()
float ek_calculate_net_charge ()
Definition at line 3769 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), charge_gpu, cuda_safe_mem, ek_calculate_system_charge(), ek_get_particle_charge(), ek_parameters, EKParameters::es_coupling, KERNELCALL, EKParameters::number_of_nodes, and threads_per_block.
Referenced by ek_neutralize_system().
ek_gather_wallcharge_species_density()
void ek_gather_wallcharge_species_density (float * wallcharge_species_density, int wallcharge_species)
Definition at line 2153 of file electrokinetics_cuda.cu.
References cuda_safe_mem, ek_parameters, EKParameters::number_of_nodes, and EKParameters::rho.
Referenced by LBBoundaries::ek_init_boundaries().
ek_init()
int ek_init ()
Definition at line 2206 of file electrokinetics_cuda.cu.
References Utils::abs(), EKParameters::agrid, LB_parameters_gpu::agrid, EKParameters::bulk_viscosity, LB_parameters_gpu::bulk_viscosity, calculate_dim_grid(), charge_gpu, EKParameters::charge_potential, EKParameters::charge_potential_buffer, cuda_safe_mem, LB_parameters_gpu::dim, EKParameters::dim_x, EKParameters::dim_x_padded, EKParameters::dim_y, EKParameters::dim_z, ek_clear_node_force(), ek_init_species_density_homogeneous(), ek_initialized, ek_integrate_electrostatics(), ek_lb_boundary_force, ek_lbparameters_gpu, ek_parameters, ek_parameters_gpu, EKParameters::electric_field, electrostatics, EKParameters::es_coupling, LB_parameters_gpu::ext_force_density, LB_parameters_gpu::external_force_density, EKParameters::friction, get_time_step(), FdElectrostatics::getGrid(), GPU, FdElectrostatics::Grid::grid, LB_parameters_gpu::is_TRT, EKParameters::j, EKParameters::j_fluc, KERNELCALL, lattice_switch, EKParameters::lb_density, EKParameters::lb_ext_force_density, EKParameters::lb_force_density_previous, lb_get_boundary_force_pointer(), lb_get_para_pointer(), LBBoundaries::lb_init_boundaries(), lb_init_gpu(), lb_lbcoupling_get_gamma(), lb_lbcoupling_set_gamma(), lb_reinit_parameters_gpu(), lbpar_gpu, node_f, EKParameters::node_is_catalyst, NONE, EKParameters::number_of_nodes, EKParameters::prefactor, LB_parameters_gpu::rho, EKParameters::species_index, Utils::sqr(), stream, EKParameters::T, threads_per_block, EKParameters::time_step, time_step, EKParameters::viscosity, and LB_parameters_gpu::viscosity.
Referenced by ek_init_species().
ek_init_species_density_wallcharge()
void ek_init_species_density_wallcharge (float * wallcharge_species_density, int wallcharge_species)
Definition at line 2161 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, ek_clear_boundary_densities(), ek_parameters, KERNELCALL, EKParameters::number_of_nodes, EKParameters::rho, and threads_per_block.
Referenced by LBBoundaries::ek_init_boundaries().
ek_integrate()
void ek_integrate ()
Definition at line 2121 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), current_nodes, ek_calculate_quantities(), ek_clear_fluxes(), ek_integrate_electrostatics(), ek_lbparameters_gpu, ek_parameters, ek_propagate_densities(), Utils::Counter< T >::increment(), KERNELCALL, lb_integrate_GPU(), node_f, EKParameters::number_of_nodes, EKParameters::number_of_species, philox_counter, threads_per_block, and Utils::Counter< T >::value().
Referenced by lb_lbfluid_integrate().
ek_integrate_electrostatics()
void ek_integrate_electrostatics ()
Definition at line 2087 of file electrokinetics_cuda.cu.
References calculate_dim_grid(), FdElectrostatics::calculatePotential(), EKParameters::charge_potential, EKParameters::charge_potential_buffer, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_calc_electric_field(), ek_gather_particle_charge_density(), ek_gather_species_charge_density(), ek_lbparameters_gpu, ek_parameters, electrostatics, EKParameters::es_coupling, gpu_get_particle_pointer(), KERNELCALL, EKParameters::number_of_nodes, particle_data_gpu, and threads_per_block.
Referenced by ek_init(), ek_integrate(), and on_observable_calc().
ek_lb_print_vtk_density()
int ek_lb_print_vtk_density (char * filename)
Definition at line 2469 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim, host_values, lb_get_values_GPU(), lb_lbfluid_get_agrid(), lbpar_gpu, and LB_parameters_gpu::number_of_nodes.
ek_lb_print_vtk_velocity()
int ek_lb_print_vtk_velocity (char * filename)
Definition at line 2430 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim, host_values, lb_get_values_GPU(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, and LB_parameters_gpu::tau.
ek_neutralize_system()
int ek_neutralize_system (int species)
Definition at line 3788 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::density, ek_calculate_net_charge(), ek_get_particle_charge(), ek_parameters, EKParameters::es_coupling, f, if(), EKParameters::number_of_boundary_nodes, EKParameters::number_of_nodes, EKParameters::number_of_species, EKParameters::species_index, and EKParameters::valency.
ek_node_get_density()
int ek_node_get_density (int species, int x, int y, int z, double * density)
Definition at line 2553 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, ek_parameters, EKParameters::number_of_nodes, EKParameters::rho, and EKParameters::species_index.
ek_node_get_flux()
int ek_node_get_flux (int species, int x, int y, int z, double * flux)
Definition at line 2573 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters, EKParameters::j, jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_cartesian2linear_host(), EKParameters::species_index, Utils::sqr(), threads_per_block, EKParameters::time_step, and Utils::Counter< T >::value().
ek_node_get_potential()
int ek_node_get_potential (int x, int y, int z, double * potential)
Definition at line 3327 of file electrokinetics_cuda.cu.
References EKParameters::charge_potential, cuda_safe_mem, EKParameters::dim_x_padded, EKParameters::dim_y, and ek_parameters.
ek_node_set_density()
int ek_node_set_density (int species, int x, int y, int z, double density)
Definition at line 2772 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, ek_parameters, EKParameters::rho, and EKParameters::species_index.
ek_print_lbpar()
void ek_print_lbpar ()
Definition at line 3601 of file electrokinetics_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::bulk_viscosity, LB_parameters_gpu::dim, LB_parameters_gpu::ext_force_density, LB_parameters_gpu::external_force_density, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_even, LB_parameters_gpu::gamma_odd, LB_parameters_gpu::gamma_shear, lbpar_gpu, LB_parameters_gpu::mu, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::rho, LB_parameters_gpu::tau, and LB_parameters_gpu::viscosity.
ek_print_parameters()
void ek_print_parameters ()
Definition at line 3478 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::bulk_viscosity, EKParameters::D, EKParameters::d, EKParameters::density, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, EKParameters::ext_force_density, EKParameters::friction, EKParameters::gamma_even, EKParameters::gamma_odd, EKParameters::j, EKParameters::lb_density, EKParameters::lb_ext_force_density, EKParameters::number_of_nodes, EKParameters::number_of_species, EKParameters::prefactor, EKParameters::reaction_ct_rate, EKParameters::reaction_fraction_0, EKParameters::reaction_species, EKParameters::rho, EKParameters::rho_product0_reservoir, EKParameters::rho_product1_reservoir, EKParameters::rho_reactant_reservoir, EKParameters::species_index, EKParameters::T, EKParameters::time_step, EKParameters::valency, and EKParameters::viscosity.
ek_print_vtk_density()
int ek_print_vtk_density (int species, char * filename)
Definition at line 2507 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, EKParameters::number_of_nodes, EKParameters::rho, and EKParameters::species_index.
ek_print_vtk_flux()
int ek_print_vtk_flux (int species, char * filename)
Definition at line 2791 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters, EKParameters::j, jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_linear2cartesian_host(), EKParameters::species_index, Utils::sqr(), threads_per_block, EKParameters::time_step, and Utils::Counter< T >::value().
ek_print_vtk_flux_fluc()
int ek_print_vtk_flux_fluc (int species, char * filename)
Definition at line 3017 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, EK_LINK_00D, EK_LINK_00U, EK_LINK_0D0, EK_LINK_0DD, EK_LINK_0DU, EK_LINK_0U0, EK_LINK_0UD, EK_LINK_0UU, EK_LINK_D00, EK_LINK_D0D, EK_LINK_D0U, EK_LINK_DD0, EK_LINK_DDD, EK_LINK_DDU, EK_LINK_DU0, EK_LINK_DUD, EK_LINK_DUU, EK_LINK_U00, EK_LINK_U0D, EK_LINK_U0U, EK_LINK_UD0, EK_LINK_UDD, EK_LINK_UDU, EK_LINK_UU0, EK_LINK_UUD, EK_LINK_UUU, ek_parameters, EKParameters::j_fluc, jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_linear2cartesian_host(), EKParameters::species_index, threads_per_block, and Utils::Counter< T >::value().
ek_print_vtk_flux_link()
int ek_print_vtk_flux_link (int species, char * filename)
Definition at line 3250 of file electrokinetics_cuda.cu.
References EKParameters::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_apply_boundaries(), ek_calculate_quantities(), ek_clear_fluxes(), ek_lbparameters_gpu, ek_parameters, EKParameters::j, jindex_getByRhoLinear_host(), KERNELCALL, node_f, EKParameters::number_of_nodes, philox_counter, reset_LB_force_densities_GPU(), rhoindex_linear2cartesian_host(), EKParameters::species_index, threads_per_block, and Utils::Counter< T >::value().
ek_print_vtk_lbforce_density()
int ek_print_vtk_lbforce_density (char * filename)
Definition at line 3429 of file electrokinetics_cuda.cu.
References EKParameters::agrid, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, LB_node_force_density_gpu::force_density_buf, node_f, EKParameters::number_of_nodes, and EKParameters::time_step.
ek_print_vtk_particle_potential()
int ek_print_vtk_particle_potential (char * filename)
Definition at line 3385 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::charge_potential_buffer, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_x_padded, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, and EKParameters::number_of_nodes.
ek_print_vtk_potential()
int ek_print_vtk_potential (char * filename)
Definition at line 3341 of file electrokinetics_cuda.cu.
References EKParameters::agrid, EKParameters::charge_potential, cuda_safe_mem, EKParameters::dim_x, EKParameters::dim_x_padded, EKParameters::dim_y, EKParameters::dim_z, ek_parameters, and EKParameters::number_of_nodes.
ek_set_advection()
void ek_set_advection (bool advection)
Definition at line 3697 of file electrokinetics_cuda.cu.
References EKParameters::advection, ek_parameters, and ek_setter_throw_if_initialized().
ek_set_agrid()
void ek_set_agrid (float agrid)
Definition at line 3634 of file electrokinetics_cuda.cu.
References EKParameters::agrid, ek_parameters, and ek_setter_throw_if_initialized().
ek_set_bulk_viscosity()
void ek_set_bulk_viscosity (float bulk_viscosity)
Definition at line 3673 of file electrokinetics_cuda.cu.
References EKParameters::bulk_viscosity, ek_parameters, and ek_setter_throw_if_initialized().
ek_set_D()
void ek_set_D (int species, float D)
Definition at line 3730 of file electrokinetics_cuda.cu.
References EKParameters::D, EKParameters::d, ek_init_species(), ek_parameters, f, EKParameters::species_index, and Utils::sqrt().
ek_set_density()
void ek_set_density (int species, float density)
Definition at line 3725 of file electrokinetics_cuda.cu.
References EKParameters::density, ek_init_species(), ek_parameters, and EKParameters::species_index.
ek_set_electrostatics_coupling()
void ek_set_electrostatics_coupling (bool electrostatics_coupling)
Definition at line 3649 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::es_coupling.
ek_set_ext_force_density()
void ek_set_ext_force_density (int species, float ext_force_density_x, float ext_force_density_y, float ext_force_density_z)
Definition at line 3742 of file electrokinetics_cuda.cu.
References ek_init_species(), ek_parameters, EKParameters::ext_force_density, and EKParameters::species_index.
ek_set_fluctuation_amplitude()
void ek_set_fluctuation_amplitude (float fluctuation_amplitude)
Definition at line 3707 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::fluctuation_amplitude.
ek_set_fluctuations()
void ek_set_fluctuations (bool fluctuations)
Definition at line 3702 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::fluctuations.
ek_set_fluidcoupling()
void ek_set_fluidcoupling (bool ideal_contribution)
Definition at line 3712 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), EKParameters::fluidcoupling_ideal_contribution, and EKParameters::stencil.
ek_set_friction()
void ek_set_friction (float friction)
Definition at line 3668 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::friction.
ek_set_gamma_even()
void ek_set_gamma_even (float gamma_even)
Definition at line 3683 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::gamma_even.
ek_set_gamma_odd()
void ek_set_gamma_odd (float gamma_odd)
Definition at line 3678 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::gamma_odd.
ek_set_lb_density()
void ek_set_lb_density (float lb_density)
Definition at line 3639 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::lb_density.
ek_set_lb_ext_force_density()
void ek_set_lb_ext_force_density (float lb_ext_force_dens_x, float lb_ext_force_dens_y, float lb_ext_force_dens_z)
Definition at line 3659 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::lb_ext_force_density.
ek_set_prefactor()
void ek_set_prefactor (float prefactor)
Definition at line 3644 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::prefactor.
ek_set_rng_state()
void ek_set_rng_state (uint64_t counter)
Definition at line 3835 of file electrokinetics_cuda.cu.
References ek_initialized, and philox_counter.
ek_set_stencil()
void ek_set_stencil (int stencil)
Definition at line 3689 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), EKParameters::fluidcoupling_ideal_contribution, and EKParameters::stencil.
ek_set_T()
void ek_set_T (float T)
Definition at line 3720 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::T.
ek_set_valency()
void ek_set_valency (int species, float valency)
Definition at line 3737 of file electrokinetics_cuda.cu.
References ek_init_species(), ek_parameters, EKParameters::species_index, and EKParameters::valency.
ek_set_viscosity()
void ek_set_viscosity (float viscosity)
Definition at line 3654 of file electrokinetics_cuda.cu.
References ek_parameters, ek_setter_throw_if_initialized(), and EKParameters::viscosity.
Variable Documentation
ek_initialized
bool ek_initialized
Definition at line 85 of file lbgpu.cpp.
Referenced by LBBoundaries::ek_init_boundaries(), lb_lbfluid_integrate(), and on_observable_calc().
ek_parameters
EKParameters ek_parameters
Definition at line 79 of file electrokinetics_cuda.cu.
Referenced by ek_calculate_boundary_mass(), ek_calculate_electrostatic_coupling(), ek_calculate_net_charge(), ek_gather_wallcharge_species_density(), ek_init(), LBBoundaries::ek_init_boundaries(), ek_init_species(), ek_init_species_density_wallcharge(), ek_integrate(), ek_integrate_electrostatics(), ek_neutralize_system(), ek_node_get_density(), ek_node_get_flux(), ek_node_get_potential(), ek_node_set_density(), ek_print_parameters(), ek_print_vtk_density(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), ek_print_vtk_lbforce_density(), ek_print_vtk_particle_potential(), ek_print_vtk_potential(), ek_set_advection(), ek_set_agrid(), ek_set_bulk_viscosity(), ek_set_D(), ek_set_density(), ek_set_electrostatics_coupling(), ek_set_ext_force_density(), ek_set_fluctuation_amplitude(), ek_set_fluctuations(), ek_set_fluidcoupling(), ek_set_friction(), ek_set_gamma_even(), ek_set_gamma_odd(), ek_set_lb_density(), ek_set_lb_ext_force_density(), ek_set_prefactor(), ek_set_stencil(), ek_set_T(), ek_set_valency(), ek_set_viscosity(), jindex_cartesian2linear_host(), jindex_getByRhoLinear_host(), rhoindex_cartesian2linear_host(), and rhoindex_linear2cartesian_host().