ESPResSo: energy_cabana.hpp File Reference
energy_cabana.hpp File Reference
#include <config/config.hpp>
#include "aosoa_pack.hpp"
#include "energy_inline.hpp"
#include "short_range_cabana_helpers.hpp"
#include <utils/Vector.hpp>
#include <Cabana_Core.hpp>
#include <omp.h>
#include <cstddef>
#include <memory>
#include <optional>
#include <variant>
#include <vector>
Classes
struct EnergyBinLayout
struct EnergyKernel
Functions
static void reduce_cabana_energy (Kokkos::View< double **, Kokkos::LayoutRight > const &local_energy, EnergyBinLayout const &layout, Observable_stat &obs, BondedInteractionsMap const &bonded_ias, int n_types)
Function Documentation
reduce_cabana_energy()
static void reduce_cabana_energy (Kokkos::View< double **, Kokkos::LayoutRight > const & local_energy, EnergyBinLayout const & layout, Observable_stat & obs, BondedInteractionsMap const & bonded_ias, int n_types) static
Definition at line 207 of file energy_cabana.hpp.
References EnergyBinLayout::bonded_idx(), EnergyBinLayout::coulomb_idx(), EnergyBinLayout::dipolar_idx(), EnergyBinLayout::n_bonded, EnergyBinLayout::nb_inter_idx(), EnergyBinLayout::nb_intra_idx(), and stream.
Referenced by System::System::calculate_energy().