ESPResSo: energy.cpp File Reference
energy.cpp File Reference
#include "EspressoSystemInterface.hpp"
#include "Observable_stat.hpp"
#include "communication.hpp"
#include "constraints.hpp"
#include "cuda_interface.hpp"
#include "energy_inline.hpp"
#include "event.hpp"
#include "forces.hpp"
#include "integrate.hpp"
#include "interactions.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "short_range_loop.hpp"
#include "electrostatics/coulomb.hpp"
#include "magnetostatics/dipoles.hpp"
#include <utils/Span.hpp>
#include <memory>
Functions
static std::shared_ptr< Observable_stat > calculate_energy_local ()
std::shared_ptr< Observable_stat > calculate_energy ()
Parallel energy calculation.
double calculate_current_potential_energy_of_system ()
Calculate the total energy of the system.
double observable_compute_energy ()
Helper function for Observables::Energy.
double particle_short_range_energy_contribution_local (int pid)
REGISTER_CALLBACK_REDUCTION (particle_short_range_energy_contribution_local, std::plus< double >()) double particle_short_range_energy_contribution(int pid)
Detailed Description
Energy calculation.
Definition in file energy.cpp.
Function Documentation
calculate_current_potential_energy_of_system()
double calculate_current_potential_energy_of_system ()
Calculate the total energy of the system.
Definition at line 126 of file energy.cpp.
References calculate_energy().
Referenced by ReactionMethods::WidomInsertion::calculate_particle_insertion_potential_energy(), ReactionMethods::ReactionAlgorithm::do_global_mc_move_for_particles_of_type(), ReactionMethods::ReactionAlgorithm::do_reaction(), and ReactionMethods::ReactionAlgorithm::generic_oneway_reaction().
calculate_energy()
std::shared_ptr<Observable_stat> calculate_energy ()
Parallel energy calculation.
Definition at line 122 of file energy.cpp.
References calculate_energy_local(), Communication::Result::main_rank, and mpi_call().
Referenced by calculate_current_potential_energy_of_system(), and observable_compute_energy().
calculate_energy_local()
static std::shared_ptr<Observable_stat> calculate_energy_local () static
Definition at line 46 of file energy.cpp.
References calc_kinetic_energy(), cell_structure, clear_energy_on_GPU(), EspressoSystemInterface::Instance(), CellStructure::local_particles(), long_range_interactions_sanity_checks(), Coulomb::on_observable_calc(), Dipoles::pair_energy_kernel(), Coulomb::pair_energy_kernel(), and short_range_loop().
Referenced by calculate_energy().
observable_compute_energy()
double observable_compute_energy ()
Helper function for Observables::Energy.
Definition at line 131 of file energy.cpp.
References calculate_energy().
Referenced by Observables::Energy::operator()().
particle_short_range_energy_contribution_local()
double particle_short_range_energy_contribution_local (int pid)
Definition at line 136 of file energy.cpp.
References calc_non_bonded_pair_energy(), cell_structure, cells_update_ghosts(), do_nonbonded(), get_ia_param(), CellStructure::get_local_particle(), CellStructure::get_resort_particles(), global_ghost_flags(), Coulomb::pair_energy_kernel(), and CellStructure::run_on_particle_short_range_neighbors().
Referenced by REGISTER_CALLBACK_REDUCTION().
REGISTER_CALLBACK_REDUCTION()
REGISTER_CALLBACK_REDUCTION (particle_short_range_energy_contribution_local , std::plus< double > ())
Definition at line 162 of file energy.cpp.
References mpi_call(), particle_short_range_energy_contribution_local(), and Communication::Result::reduction.