ESPResSo: EspressoSystemInterface_cuda.cu File Reference
EspressoSystemInterface_cuda.cu File Reference
#include "EspressoSystemInterface.hpp"
#include "cuda_interface.hpp"
#include "cuda_utils.cuh"
#include "errorhandling.hpp"
#include <cstddef>
#include <cuda.h>
Functions
__global__ void split_kernel_rq (CUDA_particle_data *particles, float *r, float *q, unsigned int n)
__global__ void split_kernel_q (CUDA_particle_data *particles, float *q, unsigned int n)
__global__ void split_kernel_r (CUDA_particle_data *particles, float *r, unsigned int n)
__global__ void split_kernel_dip (CUDA_particle_data *particles, float *dip, unsigned int n)
Detailed Description
CUDA kernels to convert the particles AoS to a SoA on the device.
Definition in file EspressoSystemInterface_cuda.cu.
Function Documentation
split_kernel_dip()
__global__ void split_kernel_dip (CUDA_particle_data * particles, float * dip, unsigned int n)
Definition at line 86 of file EspressoSystemInterface_cuda.cu.
References CUDA_particle_data::dip, and Cells::particles().
Referenced by EspressoSystemInterface::split_particle_struct().
split_kernel_q()
__global__ void split_kernel_q (CUDA_particle_data * particles, float * q, unsigned int n)
Definition at line 55 of file EspressoSystemInterface_cuda.cu.
References Cells::particles(), and CUDA_particle_data::q.
Referenced by EspressoSystemInterface::split_particle_struct().
split_kernel_r()
__global__ void split_kernel_r (CUDA_particle_data * particles, float * r, unsigned int n)
Definition at line 69 of file EspressoSystemInterface_cuda.cu.
References CUDA_particle_data::p, and Cells::particles().
Referenced by EspressoSystemInterface::split_particle_struct().
split_kernel_rq()
__global__ void split_kernel_rq (CUDA_particle_data * particles, float * r, float * q, unsigned int n)
Definition at line 38 of file EspressoSystemInterface_cuda.cu.
References CUDA_particle_data::p, Cells::particles(), and CUDA_particle_data::q.
Referenced by EspressoSystemInterface::split_particle_struct().