ESPResSo: event.cpp File Reference
event.cpp File Reference
#include "event.hpp"
#include "bonded_interactions/thermalized_bond.hpp"
#include "cell_system/CellStructureType.hpp"
#include "cells.hpp"
#include "collision.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "cuda_init.hpp"
#include "cuda_interface.hpp"
#include "cuda_utils.hpp"
#include "electrostatics/coulomb.hpp"
#include "electrostatics/icc.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "grid_based_algorithms/electrokinetics.hpp"
#include "grid_based_algorithms/lb_boundaries.hpp"
#include "grid_based_algorithms/lb_interface.hpp"
#include "immersed_boundaries.hpp"
#include "integrate.hpp"
#include "interactions.hpp"
#include "magnetostatics/dipoles.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "npt.hpp"
#include "partCfg_global.hpp"
#include "particle_node.hpp"
#include "thermostat.hpp"
#include "virtual_sites.hpp"
#include <utils/mpi/all_compare.hpp>
#include <mpi.h>
Functions
void on_program_start ()
called once at the very beginning of the program start.
void on_integration_start (double time_step)
called every time the simulation is continued/started, i.e.
void on_observable_calc ()
called before calculating observables, i.e.
void on_particle_charge_change ()
called every time the charge of a particle has changed.
void on_particle_change ()
called every time a particle property is changed via the script interface.
void on_coulomb_and_dipoles_change ()
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
void on_dipoles_change ()
called every time the dipolar parameters are changed.
void on_short_range_ia_change ()
called every time short ranged interaction parameters are changed.
void on_constraint_change ()
called every time a constraint is changed.
void on_lbboundary_change ()
called every time the walls for the lb fluid are changed
void on_boxl_change (bool skip_method_adaption)
Called when the box length has changed.
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
void on_temperature_change ()
called every time the temperature changes.
void on_periodicity_change ()
Called when the periodicity changes.
void on_skin_change ()
Called when the skin is changed.
void on_thermostat_param_change ()
Called when parameters of thermostats are changed.
void on_timestep_change ()
Called when the timestep changed.
void on_forcecap_change ()
Called when the force cap changed.
void on_node_grid_change ()
Called when the node_grid changed.
unsigned global_ghost_flags ()
Returns the ghost flags required for running pair kernels for the global state, e.g.
void update_dependent_particles ()
Update particles with properties depending on other particles, namely virtual sites and ICC charges.
Variables
static bool reinit_thermo = true
whether the thermostat has to be reinitialized before integration
static bool reinit_electrostatics = false
whether electrostatics actor has to be reinitialized on observable calc
static bool reinit_magnetostatics = false
whether magnetostatics actor has to be reinitialized on observable calc
Detailed Description
Hook procedures.
Implementation of event.hpp.
Definition in file event.cpp.
Function Documentation
global_ghost_flags()
unsigned global_ghost_flags ()
Returns the ghost flags required for running pair kernels for the global state, e.g.
the force calculation.
Returns
Required data parts;
Definition at line 362 of file event.cpp.
References collision_params, CPU, Cells::DATA_PART_BONDS, Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, Cells::DATA_PART_PROPERTIES, lattice_switch, Collision_parameters::mode, n_thermalized_bonds, OFF, THERMO_DPD, and thermo_switch.
Referenced by integrate(), on_observable_calc(), particle_short_range_energy_contribution_local(), HybridDecomposition::resort(), and update_dependent_particles().
on_boxl_change()
void on_boxl_change (bool skip_method_adaption = false)
Called when the box length has changed.
This routine is relatively fast, and changing the box length every time step as for example necessary for NpT is more or less ok.
Parameters
skip_method_adaption skip the long-range methods adaptions
Definition at line 271 of file event.cpp.
References box_geo, cell_structure, cells_re_init(), CellStructure::decomposition_type(), grid_changed_box_l(), LBBoundaries::lb_init_boundaries(), lb_lbfluid_init(), Dipoles::on_boxl_change(), and Coulomb::on_boxl_change().
on_cell_structure_change()
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
This one is potentially slow.
Definition at line 294 of file event.cpp.
References clear_particle_node(), Dipoles::on_cell_structure_change(), and Coulomb::on_cell_structure_change().
on_constraint_change()
void on_constraint_change ()
called every time a constraint is changed.
Definition at line 261 of file event.cpp.
References recalc_forces.
Referenced by Constraints::Constraints< ParticleRange, Constraint >::add(), and Constraints::Constraints< ParticleRange, Constraint >::remove().
on_coulomb_and_dipoles_change()
void on_coulomb_and_dipoles_change ()
Definition at line 228 of file event.cpp.
References Coulomb::on_coulomb_change(), Dipoles::on_dipoles_change(), on_short_range_ia_change(), reinit_electrostatics, and reinit_magnetostatics.
Referenced by on_skin_change().
on_coulomb_change()
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
all Coulomb methods have a short range part, aka near field correction. Even in case of switching off, we should call this, since the required cutoff might have reduced.
Definition at line 240 of file event.cpp.
References electrostatics_actor, Coulomb::on_coulomb_change(), on_short_range_ia_change(), reinit_electrostatics, and visit_active_actor_try_catch().
on_dipoles_change()
void on_dipoles_change ()
called every time the dipolar parameters are changed.
Definition at line 248 of file event.cpp.
Referenced by DipolarP3M::tune().
on_forcecap_change()
void on_forcecap_change ()
Called when the force cap changed.
Definition at line 344 of file event.cpp.
References recalc_forces.
Referenced by mpi_set_forcecap_local().
on_integration_start()
void on_integration_start (double time_step)
called every time the simulation is continued/started, i.e.
when switching from the script interface to the simulation core.
Definition at line 105 of file event.cpp.
References Utils::Mpi::all_compare(), box_geo, cell_structure, comm_cart, electrostatics_actor, gpu_get_global_particle_vars_pointer_host(), integrator_npt_sanity_checks(), integrator_sanity_checks(), PartCfg::invalidate(), invalidate_fetch_cache(), lb_lbfluid_on_integration_start(), lb_lbfluid_sanity_checks(), long_range_interactions_sanity_checks(), magnetostatics_actor, npt_ensemble_init(), on_observable_calc(), partCfg(), recalc_forces, reinit_thermo, runtimeErrorMsg, thermo_init(), time_step, and CellStructure::use_verlet_list.
Referenced by integrate().
on_lbboundary_change()
void on_lbboundary_change ()
called every time the walls for the lb fluid are changed
Definition at line 263 of file event.cpp.
References LBBoundaries::lb_init_boundaries(), and recalc_forces.
Referenced by LBBoundaries::add(), and LBBoundaries::remove().
on_node_grid_change()
void on_node_grid_change ()
Called when the node_grid changed.
Definition at line 346 of file event.cpp.
References cell_structure, cells_re_init(), CellStructure::decomposition_type(), grid_changed_n_nodes(), Dipoles::on_node_grid_change(), and Coulomb::on_node_grid_change().
on_observable_calc()
void on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M etc.).
Definition at line 169 of file event.cpp.
References cells_update_ghosts(), clear_particle_node(), ek_initialized, ek_integrate_electrostatics(), global_ghost_flags(), Dipoles::on_observable_calc(), Coulomb::on_observable_calc(), reinit_electrostatics, reinit_magnetostatics, and update_dependent_particles().
Referenced by on_integration_start().
on_particle_change()
void on_particle_change ()
called every time a particle property is changed via the script interface.
Definition at line 206 of file event.cpp.
References cell_structure, CELL_STRUCTURE_HYBRID, CellStructure::decomposition_type(), PartCfg::invalidate(), invalidate_fetch_cache(), partCfg(), recalc_forces, reinit_electrostatics, reinit_magnetostatics, Cells::RESORT_GLOBAL, Cells::RESORT_LOCAL, and CellStructure::set_resort_particles().
Referenced by mpi_add_exclusion_local(), mpi_galilei_transform_local(), mpi_kill_particle_forces_local(), mpi_kill_particle_motion_local(), mpi_place_new_particle_local(), mpi_place_particle(), mpi_place_particle_local(), mpi_remove_all_particles_local(), mpi_remove_exclusion_local(), mpi_remove_particle_local(), mpi_rescale_particles(), mpi_rescale_particles_local(), mpi_rotate_system_local(), mpi_send_update_message(), and mpi_send_update_message_local().
on_particle_charge_change()
void on_particle_charge_change ()
called every time the charge of a particle has changed.
Definition at line 197 of file event.cpp.
References PartCfg::invalidate(), partCfg(), and reinit_electrostatics.
Referenced by ICCStar::iteration(), and ICCStar::on_activation().
on_periodicity_change()
void on_periodicity_change ()
Called when the periodicity changes.
Internally calls on_skin_change.
Definition at line 311 of file event.cpp.
References box_geo, INTEG_METHOD_SD, integ_switch, Dipoles::on_periodicity_change(), Coulomb::on_periodicity_change(), on_skin_change(), BoxGeometry::periodic(), and runtimeErrorMsg.
on_program_start()
void on_program_start ()
called once at the very beginning of the program start.
Definition at line 83 of file event.cpp.
References CELL_STRUCTURE_REGULAR, cells_re_init(), cuda_init(), init_node_grid(), make_particle_type_exist(), and this_node.
Referenced by Communication::init().
on_short_range_ia_change()
void on_short_range_ia_change ()
called every time short ranged interaction parameters are changed.
Definition at line 256 of file event.cpp.
References cell_structure, cells_re_init(), CellStructure::decomposition_type(), and recalc_forces.
Referenced by Collision_parameters::initialize(), mpi_bcast_ia_params_local(), mpi_update_cell_system_ia_range_local(), on_coulomb_and_dipoles_change(), on_coulomb_change(), and on_dipoles_change().
on_skin_change()
void on_skin_change ()
Called when the skin is changed.
Definition at line 332 of file event.cpp.
References cell_structure, cells_re_init(), CellStructure::decomposition_type(), and on_coulomb_and_dipoles_change().
Referenced by mpi_set_min_global_cut_local(), mpi_set_skin_local(), and on_periodicity_change().
on_temperature_change()
void on_temperature_change ()
called every time the temperature changes.
This one is potentially slow.
Definition at line 309 of file event.cpp.
References lb_lbfluid_reinit_parameters().
Referenced by mpi_set_temperature_local().
on_thermostat_param_change()
void on_thermostat_param_change ()
Called when parameters of thermostats are changed.
Definition at line 337 of file event.cpp.
References reinit_thermo.
Referenced by mpi_bcast_nptiso_geom_barostat_local(), mpi_set_langevin_gamma_local(), mpi_set_langevin_gamma_rot_local(), mpi_set_nptiso_gammas_local(), mpi_set_temperature_local(), on_timestep_change(), and ThermalizedBond::ThermalizedBond().
on_timestep_change()
void on_timestep_change ()
Called when the timestep changed.
Internally calls on_thermostat_param_change.
Definition at line 339 of file event.cpp.
References lb_lbfluid_reinit_parameters(), and on_thermostat_param_change().
Referenced by mpi_set_time_step_local().
update_dependent_particles()
void update_dependent_particles ()
Update particles with properties depending on other particles, namely virtual sites and ICC charges.
Definition at line 386 of file event.cpp.
References cell_structure, cells_update_ghosts(), global_ghost_flags(), immersed_boundaries, ImmersedBoundaries::init_volume_conservation(), update_icc_particles(), and virtual_sites().
Referenced by mpi_rotate_system_local(), and on_observable_calc().
Variable Documentation
reinit_electrostatics
bool reinit_electrostatics = false static
whether electrostatics actor has to be reinitialized on observable calc
Definition at line 63 of file event.cpp.
Referenced by on_coulomb_and_dipoles_change(), on_coulomb_change(), on_observable_calc(), on_particle_change(), and on_particle_charge_change().
reinit_magnetostatics
bool reinit_magnetostatics = false static
whether magnetostatics actor has to be reinitialized on observable calc
Definition at line 67 of file event.cpp.
Referenced by on_coulomb_and_dipoles_change(), on_dipoles_change(), on_observable_calc(), and on_particle_change().
reinit_thermo
bool reinit_thermo = true static
whether the thermostat has to be reinitialized before integration
Definition at line 60 of file event.cpp.
Referenced by on_integration_start(), and on_thermostat_param_change().