ESPResSo: fd-electrostatics_cuda.cu File Reference
fd-electrostatics_cuda.cu File Reference
#include "grid_based_algorithms/fd-electrostatics.cuh"
#include "cuda_utils.cuh"
#include <utils/constants.hpp>
#include <cuda.h>
#include <cufft.h>
#include <cstdio>
#include <stdexcept>
#include <string>
Functions
__device__ cufftReal fde_getNode (int x, int y, int z)
__device__ cufftReal fde_getNode (int i)
__device__ void fde_setNode (int x, int y, int z, cufftReal value)
__device__ void fde_setNode (int i, cufftReal value)
__global__ void createGreensfcn ()
__global__ void multiplyGreensfcn (cufftComplex *charge_potential)
__device__ unsigned int fde_getThreadIndex ()
Variables
static constexpr unsigned int threads_per_block = 64
__device__ __constant__ FdElectrostatics::Parameters fde_parameters_gpu [1]
Function Documentation
createGreensfcn()
__global__ void createGreensfcn ()
Definition at line 143 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::InputParameters::agrid, FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, FdElectrostatics::InputParameters::dim_z, fde_getThreadIndex(), fde_parameters_gpu, FdElectrostatics::Parameters::greensfcn, and FdElectrostatics::InputParameters::prefactor.
Referenced by FdElectrostatics::FdElectrostatics().
fde_getNode() [1/2]
__device__ cufftReal fde_getNode (int i)
Definition at line 72 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::Parameters::dim_x_padded, FdElectrostatics::InputParameters::dim_y, fde_getNode(), and fde_parameters_gpu.
fde_getNode() [2/2]
__device__ cufftReal fde_getNode (int x, int y, int z)
Definition at line 57 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::Parameters::charge_potential, FdElectrostatics::Parameters::dim_x_padded, FdElectrostatics::InputParameters::dim_y, and fde_parameters_gpu.
Referenced by fde_getNode().
fde_getThreadIndex()
__device__ unsigned int fde_getThreadIndex ()
Definition at line 51 of file fd-electrostatics_cuda.cu.
Referenced by createGreensfcn(), and multiplyGreensfcn().
fde_setNode() [1/2]
__device__ void fde_setNode (int i, cufftReal value)
Definition at line 80 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::Parameters::dim_x_padded, FdElectrostatics::InputParameters::dim_y, fde_parameters_gpu, and fde_setNode().
fde_setNode() [2/2]
__device__ void fde_setNode (int x, int y, int z, cufftReal value)
Definition at line 65 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::Parameters::charge_potential, FdElectrostatics::Parameters::dim_x_padded, FdElectrostatics::InputParameters::dim_y, and fde_parameters_gpu.
Referenced by fde_setNode().
multiplyGreensfcn()
__global__ void multiplyGreensfcn (cufftComplex * charge_potential)
Definition at line 180 of file fd-electrostatics_cuda.cu.
References FdElectrostatics::InputParameters::dim_x, FdElectrostatics::InputParameters::dim_y, fde_getThreadIndex(), fde_parameters_gpu, and FdElectrostatics::Parameters::greensfcn.
Referenced by FdElectrostatics::calculatePotential().
Variable Documentation
fde_parameters_gpu
__device__ __constant__ FdElectrostatics::Parameters fde_parameters_gpu[1]
Definition at line 49 of file fd-electrostatics_cuda.cu.
Referenced by createGreensfcn(), fde_getNode(), fde_setNode(), FdElectrostatics::FdElectrostatics(), and multiplyGreensfcn().
threads_per_block
constexpr unsigned int threads_per_block = 64 static constexpr
Definition at line 39 of file fd-electrostatics_cuda.cu.
Referenced by FdElectrostatics::calculatePotential(), and FdElectrostatics::FdElectrostatics().