ESPResSo: fetch_particles.hpp File Reference
fetch_particles.hpp File Reference
#include "PidObservable.hpp"
#include "cell_system/CellStructure.hpp"
#include "system/System.hpp"
#include <algorithm>
#include <iterator>
#include <set>
#include <vector>
Functions
auto fetch_particles (std::vector< int > const &ids)
Fetch a group of particles.
Function Documentation
fetch_particles()
auto fetch_particles (std::vector< int > const & ids) inline
Fetch a group of particles.
Parameters
ids particle identifiers
Returns
array of particle copies, with positions in the current box.
Definition at line 37 of file fetch_particles.hpp.
References System::get_system(), and stream.
Referenced by Observables::PidObservable::operator()(), and Observables::RDF::operator()().