ESPResSo: fft.cpp File Reference
fft.cpp File Reference
Routines, row decomposition, data structures and communication for the 3D-FFT.
#include "config/config.hpp"
#include "p3m/fft.hpp"
#include <utils/Vector.hpp>
#include <utils/index.hpp>
#include <utils/math/permute_ifield.hpp>
#include <fftw3.h>
#include <mpi.h>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <optional>
#include <span>
#include <stdexcept>
#include <utility>
#include <vector>
Namespaces
namespace anonymous_namespace{fft.cpp}
Macros
MPI tags for FFT communication
#define REQ_FFT_FORW 301
Tag for communication in forw_grid_comm()
#define REQ_FFT_BACK 302
Tag for communication in back_grid_comm()
Functions
std::optional< std::vector< int > > find_comm_groups (Utils::Vector3i const &grid1, Utils::Vector3i const &grid2, std::span< int const > node_list1, std::span< int > node_list2, std::span< int > pos, std::span< int > my_pos, int rank)
This ugly function does the bookkeeping: which nodes have to communicate to each other, when you change the node grid.
int anonymous_namespace{fft.cpp}::calc_local_mesh (const int *n_pos, const int *n_grid, const int *mesh, const double *mesh_off, int *loc_mesh, int *start)
Calculate the local fft mesh.
int anonymous_namespace{fft.cpp}::calc_send_block (const int *pos1, const int *grid1, const int *pos2, const int *grid2, const int *mesh, const double *mesh_off, int *block)
Calculate a send (or recv.) block for grid communication during a decomposition change.
void anonymous_namespace{fft.cpp}::pack_block_permute1 (double const *const in, double *const out, const int *start, const int *size, const int *dim, int element)
Pack a block with dimensions size[0] * size[1] * size[2] starting at start of an input 3D-grid with dimension dim into an output 3D-grid with dimensions size[2] * size[0] * size[1] with a simultaneous one-fold permutation of the indices.
void anonymous_namespace{fft.cpp}::pack_block_permute2 (double const *const in, double *const out, const int *start, const int *size, const int *dim, int element)
Pack a block with dimensions size[0] * size[1] * size[2] starting at start of an input 3D-grid with dimension dim into an output 3D-grid with dimensions size[2] * size[0] * size[1] with a simultaneous two-fold permutation of the indices.
void anonymous_namespace{fft.cpp}::forw_grid_comm (fft_forw_plan plan, const double *in, double *out, fft_data_struct &fft, const boost::mpi::communicator &comm)
Communicate the grid data according to the given forward FFT plan.
void anonymous_namespace{fft.cpp}::back_grid_comm (fft_forw_plan plan_f, fft_back_plan plan_b, const double *in, double *out, fft_data_struct &fft, const boost::mpi::communicator &comm)
Communicate the grid data according to the given backward FFT plan.
int map_3don2d_grid (int const g3d[3], int g2d[3])
Calculate 'best' mapping between a 2D and 3D grid.
static void calc_2d_grid (int n, int grid[3])
Calculate most square 2D grid.
int fft_init (Utils::Vector3i const &ca_mesh_dim, int const *ca_mesh_margin, Utils::Vector3i const &global_mesh_dim, Utils::Vector3d const &global_mesh_off, int &ks_pnum, fft_data_struct &fft, Utils::Vector3i const &grid, boost::mpi::communicator const &comm)
Initialize everything connected to the 3D-FFT.
void fft_perform_forw (double *data, fft_data_struct &fft, const boost::mpi::communicator &comm)
Perform an in-place forward 3D FFT.
void fft_perform_back (double *data, bool check_complex, fft_data_struct &fft, const boost::mpi::communicator &comm)
Perform an in-place backward 3D FFT.
void fft_pack_block (double const *const in, double *const out, int const start[3], int const size[3], int const dim[3], int element)
Pack a block (size[3] starting at start[3]) of an input 3d-grid with dimension dim[3] into an output 3d-block with dimension size[3].
void fft_unpack_block (double const *const in, double *const out, int const start[3], int const size[3], int const dim[3], int element)
Unpack a 3d-grid input block (size[3]) into an output 3d-grid with dimension dim[3] at start position start[3].
Detailed Description
Routines, row decomposition, data structures and communication for the 3D-FFT.
Definition in file fft.cpp.
Macro Definition Documentation
REQ_FFT_BACK
#define REQ_FFT_BACK 302
Tag for communication in back_grid_comm()
Definition at line 59 of file fft.cpp.
REQ_FFT_FORW
#define REQ_FFT_FORW 301
Tag for communication in forw_grid_comm()
Definition at line 57 of file fft.cpp.
Function Documentation
calc_2d_grid()
static void calc_2d_grid (int n, int grid[3]) static
Calculate most square 2D grid.
Definition at line 467 of file fft.cpp.
Referenced by fft_init().
fft_init()
int fft_init (Utils::Vector3i const & ca_mesh_dim, int const * ca_mesh_margin, Utils::Vector3i const & global_mesh_dim, Utils::Vector3d const & global_mesh_off, int & ks_pnum, fft_data_struct & fft, Utils::Vector3i const & grid, boost::mpi::communicator const & comm)
Initialize everything connected to the 3D-FFT.
Parameters
[in] ca_mesh_dim Local CA mesh dimensions.
[in] ca_mesh_margin Local CA mesh margins.
[in] global_mesh_dim Global CA mesh dimensions.
[in] global_mesh_off Global CA mesh offset.
[out] ks_pnum Number of permutations in k-space.
[out] fft FFT plan.
[in] grid Number of nodes in each spatial dimension.
[in] comm MPI communicator.
Returns
Maximal size of local fft mesh (needed for allocation of ca_mesh).
Definition at line 481 of file fft.cpp.
References fft_data_struct::back, calc_2d_grid(), anonymous_namespace{fft.cpp}::calc_local_mesh(), anonymous_namespace{fft.cpp}::calc_send_block(), Utils::Array< T, N >::data(), fft_data_struct::data_buf, fft_plan::dir, fft_forw_plan::element, fft_pack_block(), find_comm_groups(), fft_forw_plan::group, fft_data_struct::init_tag, map_3don2d_grid(), fft_data_struct::max_comm_size, fft_data_struct::max_mesh_size, fft_forw_plan::n_ffts, fft_forw_plan::n_permute, fft_forw_plan::new_mesh, fft_forw_plan::new_size, fft_forw_plan::old_mesh, fft_plan::our_fftw_plan, anonymous_namespace{fft.cpp}::pack_block_permute1(), anonymous_namespace{fft.cpp}::pack_block_permute2(), fft_plan::pack_function, fft_data_struct::plan, Utils::product(), fft_forw_plan::recv_block, fft_data_struct::recv_buf, fft_forw_plan::recv_size, fft_forw_plan::row_dir, fft_forw_plan::send_block, fft_data_struct::send_buf, fft_forw_plan::send_size, and fft_forw_plan::start.
Referenced by CoulombP3M::init(), and DipolarP3M::init().
fft_pack_block()
void fft_pack_block (double const * in, double * out, int const start[3], int const size[3], int const dim[3], int element)
Pack a block (size[3] starting at start[3]) of an input 3d-grid with dimension dim[3] into an output 3d-block with dimension size[3].
The block with dimensions (size[0], size[1], size[2]) is stored in 'row-major-order' or 'C-order', that means the first index is changing slowest when running through the linear array. The element (i0 (slow), i1 (mid), i2 (fast)) has the linear index li = i2 + size[2] * (i1 + (size[1] * i0)).
Parameters
[in] in pointer to input 3d-grid.
[out] out pointer to output 3d-grid (block).
[in] start start index of the block in the in-grid.
[in] size size of the block (=dimension of the out-grid).
[in] dim size of the in-grid.
[in] element size of a grid element (e.g. 1 for Real, 2 for Complex).
Definition at line 753 of file fft.cpp.
Referenced by fft_init(), p3m_send_mesh::gather_grid(), and p3m_send_mesh::spread_grid().
fft_perform_back()
void fft_perform_back (double * data, bool check_complex, fft_data_struct & fft, const boost::mpi::communicator & comm)
Perform an in-place backward 3D FFT.
Warning
The content of data is overwritten.
Parameters
[in,out] data Mesh.
[in] check_complex Throw an error if the complex component is non-zero.
[in,out] fft FFT plan.
[in] comm MPI communicator.
Definition at line 711 of file fft.cpp.
References fft_data_struct::back, anonymous_namespace{fft.cpp}::back_grid_comm(), fft_data_struct::data_buf, fft_forw_plan::new_size, fft_plan::our_fftw_plan, and fft_data_struct::plan.
Referenced by CoulombP3M::long_range_kernel(), and DipolarP3M::long_range_kernel().
fft_perform_forw()
void fft_perform_forw (double * data, fft_data_struct & fft, const boost::mpi::communicator & comm)
Perform an in-place forward 3D FFT.
Warning
The content of data is overwritten.
Parameters
[in,out] data Mesh.
[in,out] fft FFT plan.
[in] comm MPI communicator
Definition at line 680 of file fft.cpp.
References fft_data_struct::data_buf, anonymous_namespace{fft.cpp}::forw_grid_comm(), fft_forw_plan::new_size, fft_plan::our_fftw_plan, and fft_data_struct::plan.
Referenced by CoulombP3M::long_range_kernel(), DipolarP3M::long_range_kernel(), and CoulombP3M::long_range_pressure().
fft_unpack_block()
void fft_unpack_block (double const * in, double * out, int const start[3], int const size[3], int const dim[3], int element)
Unpack a 3d-grid input block (size[3]) into an output 3d-grid with dimension dim[3] at start position start[3].
see also fft_pack_block.
Parameters
[in] in pointer to input 3d-grid.
[out] out pointer to output 3d-grid (block).
[in] start start index of the block in the in-grid.
[in] size size of the block (=dimension of the out-grid).
[in] dim size of the in-grid.
[in] element size of a grid element (e.g. 1 for Real, 2 for Complex).
Definition at line 777 of file fft.cpp.
Referenced by anonymous_namespace{fft.cpp}::back_grid_comm(), anonymous_namespace{fft.cpp}::forw_grid_comm(), and p3m_send_mesh::spread_grid().
find_comm_groups()
std::optional< std::vector< int > > find_comm_groups (Utils::Vector3i const & grid1, Utils::Vector3i const & grid2, std::span< int const > node_list1, std::span< int > node_list2, std::span< int > pos, std::span< int > my_pos, int rank)
This ugly function does the bookkeeping: which nodes have to communicate to each other, when you change the node grid.
Changing the regular decomposition requires communication. This function finds (hopefully) the best way to do this. As input it needs the two grids (grid1, grid2) and a linear list (node_list1) with the node identities for grid1. The linear list (node_list2) for the second grid is calculated. For the communication group of the calling node it calculates a list (group) with the node identities and the positions (my_pos, pos) of that nodes in grid1 and grid2. The return value is the size of the communication group. It gives -1 if the two grids do not fit to each other (grid1 and grid2 have to be component-wise multiples of each other, see e.g. calc_2d_grid for how to do this).
Parameters
[in] grid1 The node grid you start with.
[in] grid2 The node grid you want to have.
[in] node_list1 Linear node index list for grid1.
[out] node_list2 Linear node index list for grid2.
[out] pos Positions of the nodes in grid2
[out] my_pos Position of comm.rank() in grid2.
[in] rank MPI rank.
Returns
Size of the communication group.
Definition at line 86 of file fft.cpp.
References Utils::product().
Referenced by fft_init().
map_3don2d_grid()
int map_3don2d_grid (int const g3d[3], int g2d[3])
Calculate 'best' mapping between a 2D and 3D grid.
Required for the communication from 3D regular domain decomposition to 2D regular row decomposition. The dimensions of the 2D grid are resorted, if necessary, in a way that they are multiples of the 3D grid dimensions.
Parameters
g3d 3D grid.
g2d 2D grid.
Returns
index of the row direction [0,1,2].
Definition at line 425 of file fft.cpp.
Referenced by fft_init().