ESPResSo: forcecap.cpp File Reference
forcecap.cpp File Reference
#include "forcecap.hpp"
#include "Particle.hpp"
#include "communication.hpp"
#include "event.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sqr.hpp>
#include <cmath>
Functions
double forcecap_get ()
void forcecap_cap (ParticleRange const &particles)
void mpi_set_forcecap_local (double force_cap)
void mpi_set_forcecap (double force_cap)
Variables
static double force_cap = 0.0
Detailed Description
Force capping calculation.
Definition in file forcecap.cpp.
Function Documentation
forcecap_cap()
void forcecap_cap (ParticleRange const & particles)
Definition at line 40 of file forcecap.cpp.
References force_cap, Cells::particles(), Utils::sqr(), and Utils::sqrt().
Referenced by force_calc().
forcecap_get()
double forcecap_get ()
Definition at line 38 of file forcecap.cpp.
References force_cap.
mpi_set_forcecap()
void mpi_set_forcecap (double force_cap)
Definition at line 62 of file forcecap.cpp.
References force_cap, mpi_call_all(), and mpi_set_forcecap_local().
mpi_set_forcecap_local()
void mpi_set_forcecap_local (double force_cap)
Definition at line 55 of file forcecap.cpp.
References force_cap, and on_forcecap_change().
Referenced by mpi_set_forcecap().
Variable Documentation
force_cap
double force_cap = 0.0 static
Definition at line 36 of file forcecap.cpp.
Referenced by forcecap_cap(), forcecap_get(), mpi_set_forcecap(), and mpi_set_forcecap_local().