ESPResSo: forces.hpp File Reference
forces.hpp File Reference
#include "ParticleRange.hpp"
#include "cell_system/CellStructure.hpp"
#include <utils/Vector.hpp>
Functions
void init_forces (const ParticleRange &particles, double time_step)
initialize real particle forces with thermostat forces and ghost particle forces with zero.
void init_forces_ghosts (const ParticleRange &particles)
Set forces of all ghosts to zero.
void force_calc (CellStructure &cell_structure, double time_step, double kT)
Calculate forces.
void calc_long_range_forces (const ParticleRange &particles)
Calculate long range forces (P3M, ...).
void npt_add_virial_force_contribution (const Utils::Vector3d &force, const Utils::Vector3d &d)
Update the NpT virial.
Detailed Description
Force calculation.
Todo:
Preprocessor switches for all forces (Default: everything is turned on).
Implement more flexible thermostat, e.g. which thermostat to use.
Implementation in forces.cpp.
Definition in file forces.hpp.
Function Documentation
calc_long_range_forces()
void calc_long_range_forces (const ParticleRange & particles)
Calculate long range forces (P3M, ...).
Definition at line 246 of file forces.cpp.
References Dipoles::calc_long_range_force(), Coulomb::calc_long_range_force(), ESPRESSO_PROFILER_CXX_MARK_FUNCTION, and Cells::particles().
Referenced by force_calc().
force_calc()
void force_calc (CellStructure & cell_structure, double time_step, double kT)
Calculate forces.
A short list, what the function is doing:
Initialize forces
Calculate bonded interaction forces
Calculate non-bonded short range interaction forces
Calculate long range interaction forces
Definition at line 144 of file forces.cpp.
References add_oif_global_forces(), calc_long_range_forces(), calc_oif_global(), cell_structure, BondBreakage::clear_queue(), collision_detection_cutoff(), comfixed, comm_cart, Constraints::constraints, copy_forces_from_GPU(), Dipoles::cutoff(), Coulomb::cutoff(), electrostatics_extension, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, forcecap_cap(), Utils::get(), get_sim_time(), CellStructure::ghost_particles(), CellStructure::ghosts_reduce_forces(), immersed_boundaries, INACTIVE_CUTOFF, init_forces(), EspressoSystemInterface::Instance(), interaction_range(), lb_lbcoupling_calc_particle_lattice_ia(), CellStructure::local_particles(), max_oif_objects, maximal_cutoff(), maximal_cutoff_bonded(), n_nodes, Coulomb::pair_force_elc_kernel(), Coulomb::pair_force_kernel(), Dipoles::pair_force_kernel(), Cells::particles(), prepare_local_collision_queue(), recalc_forces, short_range_loop(), skin, thermo_virtual, this_node, time_step, virtual_sites(), and ImmersedBoundaries::volume_conservation().
Referenced by integrate().
init_forces()
void init_forces (const ParticleRange & particles, double time_step)
initialize real particle forces with thermostat forces and ghost particle forces with zero.
init_forces_ghosts()
void init_forces_ghosts (const ParticleRange & particles)
Set forces of all ghosts to zero.
Definition at line 138 of file forces.cpp.
References init_ghost_force(), and Cells::particles().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques().
npt_add_virial_force_contribution()
void npt_add_virial_force_contribution (const Utils::Vector3d & force, const Utils::Vector3d & d)
Update the NpT virial.
Definition at line 261 of file forces.cpp.
References force, and npt_add_virial_contribution().
Referenced by add_bonded_two_body_force(), and add_non_bonded_pair_force().