ESPResSo: forces.cpp File Reference
forces.cpp File Reference
Force calculation.
#include <config/config.hpp>
#include "BoxGeometry.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "PropagationMode.hpp"
#include "bond_breakage/bond_breakage.hpp"
#include "cell_system/CellStructure.hpp"
#include "cells.hpp"
#include "collision_detection/CollisionDetection.hpp"
#include "communication.hpp"
#include "constraints/Constraints.hpp"
#include "electrostatics/icc.hpp"
#include "forces_inline.hpp"
#include "galilei/ComFixed.hpp"
#include "immersed_boundary/ImmersedBoundaries.hpp"
#include "integrators/Propagation.hpp"
#include "lb/particle_coupling.hpp"
#include "magnetostatics/dipoles.hpp"
#include "nonbonded_interactions/VerletCriterion.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "npt.hpp"
#include "rotation.hpp"
#include "short_range_cabana.hpp"
#include "short_range_loop.hpp"
#include "system/System.hpp"
#include "thermostat.hpp"
#include "thermostats/langevin_inline.hpp"
#include "virtual_sites/relative.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sqr.hpp>
#include <caliper/cali.h>
#include <Cabana_Core.hpp>
#include <cassert>
#include <cmath>
#include <memory>
#include <span>
#include <variant>
Functions
static ParticleForce external_force (Particle const &p)
External particle forces.
void init_forces_and_thermostat (System::System const &system)
Combined force initialization and Langevin noise application.
void init_forces_ghosts (const CellStructure &cell_structure)
Set forces of all ghosts to zero.
static void force_capping (CellStructure &cell_structure, double force_cap)
static void reinit_dip_fld (CellStructure const &cell_structure)
void calc_long_range_forces (const ParticleRange &particles)
Calculate long range forces (P3M, ...).
Detailed Description
Force calculation.
The corresponding header file is forces.hpp.
Definition in file forces.cpp.
Function Documentation
calc_long_range_forces()
void calc_long_range_forces (const ParticleRange & particles)
Calculate long range forces (P3M, ...).
Definition at line 403 of file forces.cpp.
References Coulomb::Solver::calc_long_range_force(), Dipoles::Solver::calc_long_range_force(), Coulomb::get_coulomb(), Dipoles::get_dipoles(), and stream.
Referenced by System::System::calculate_forces().
external_force()
static ParticleForce external_force (Particle const & p) static
External particle forces.
Definition at line 75 of file forces.cpp.
References Particle::calc_director(), Particle::ext_force(), Particle::ext_torque(), ParticleForce::f, stream, Particle::swimming(), and ParticleForce::torque.
Referenced by init_forces_and_thermostat().
force_capping()
static void force_capping (CellStructure & cell_structure, double force_cap) static
Definition at line 144 of file forces.cpp.
References CellStructure::for_each_local_particle(), Particle::force(), Utils::sqr(), and stream.
Referenced by System::System::calculate_forces().
init_forces_and_thermostat()
void init_forces_and_thermostat (System::System const & system)
Combined force initialization and Langevin noise application.
Definition at line 97 of file forces.cpp.
References convert_vector_body_to_space(), external_force(), Particle::force(), Particle::force_and_torque(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), init_forces_ghosts(), PropagationMode::ROT_LANGEVIN, stream, Particle::torque(), and PropagationMode::TRANS_LANGEVIN.
Referenced by System::System::calculate_forces().
init_forces_ghosts()
void init_forces_ghosts (const CellStructure & cell_structure)
Set forces of all ghosts to zero.
Definition at line 139 of file forces.cpp.
References CellStructure::for_each_ghost_particle(), and Particle::force_and_torque().
Referenced by init_forces_and_thermostat(), lb_tracers_add_particle_force_to_fluid(), and vs_relative_back_transfer_forces_and_torques().
reinit_dip_fld()
static void reinit_dip_fld (CellStructure const & cell_structure) static
Definition at line 158 of file forces.cpp.
References Particle::dip_fld(), and CellStructure::for_each_local_particle().
Referenced by System::System::calculate_forces().