ESPResSo: galilei.cpp File Reference
galilei.cpp File Reference
#include "galilei.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "event.hpp"
#include "grid.hpp"
#include <boost/range/numeric.hpp>
#include <boost/serialization/utility.hpp>
#include <utils/Vector.hpp>
#include <algorithm>
#include <utility>
Functions
void local_kill_particle_motion (int omega, const ParticleRange &particles)
Stop particle motion by setting the velocity of each particle to zero.
void local_kill_particle_forces (int torque, const ParticleRange &particles)
Set all the forces acting on the particles to zero.
std::pair< Utils::Vector3d, double > local_system_CMS ()
Calculate the CMS of the system.
std::pair< Utils::Vector3d, double > local_system_CMS_velocity ()
Calculate the CMS velocity of the system.
void local_galilei_transform (const Utils::Vector3d &cmsvel)
Remove the CMS velocity.
void mpi_kill_particle_motion_local (int rotation)
void mpi_kill_particle_motion (int rotation)
Stop particle motion by setting the velocity of each particle to zero.
void mpi_kill_particle_forces_local (int torque)
void mpi_kill_particle_forces (int torque)
Set all the forces acting on the particles to zero.
Utils::Vector3d mpi_system_CMS ()
Calculate the CMS of the system.
Utils::Vector3d mpi_system_CMS_velocity ()
Calculate the CMS velocity of the system.
void mpi_galilei_transform_local (Utils::Vector3d const &cmsvel)
void mpi_galilei_transform ()
Remove the CMS velocity.
Function Documentation
local_galilei_transform()
void local_galilei_transform (const Utils::Vector3d & cmsvel)
Remove the CMS velocity.
Definition at line 89 of file galilei.cpp.
References cell_structure, and CellStructure::local_particles().
Referenced by mpi_galilei_transform_local().
local_kill_particle_forces()
void local_kill_particle_forces (int torque, const ParticleRange & particles)
Set all the forces acting on the particles to zero.
Definition at line 50 of file galilei.cpp.
References Cells::particles(), and torque.
Referenced by mpi_kill_particle_forces_local().
local_kill_particle_motion()
void local_kill_particle_motion (int omega, const ParticleRange & particles)
Stop particle motion by setting the velocity of each particle to zero.
Definition at line 39 of file galilei.cpp.
References Cells::particles().
Referenced by mpi_kill_particle_motion_local().
local_system_CMS()
std::pair<Utils::Vector3d, double> local_system_CMS ()
Calculate the CMS of the system.
Definition at line 61 of file galilei.cpp.
References cell_structure, CellStructure::local_particles(), and sum.
Referenced by mpi_system_CMS().
local_system_CMS_velocity()
std::pair<Utils::Vector3d, double> local_system_CMS_velocity ()
Calculate the CMS velocity of the system.
Definition at line 76 of file galilei.cpp.
References cell_structure, CellStructure::local_particles(), and sum.
Referenced by mpi_system_CMS_velocity().
mpi_galilei_transform()
void mpi_galilei_transform ()
Remove the CMS velocity.
Definition at line 147 of file galilei.cpp.
References mpi_call_all(), mpi_galilei_transform_local(), and mpi_system_CMS_velocity().
mpi_galilei_transform_local()
void mpi_galilei_transform_local (Utils::Vector3d const & cmsvel)
Definition at line 140 of file galilei.cpp.
References local_galilei_transform(), and on_particle_change().
Referenced by mpi_galilei_transform().
mpi_kill_particle_forces()
void mpi_kill_particle_forces (int torque)
Set all the forces acting on the particles to zero.
Parameters
torque if true, also set particle torques to zero
Definition at line 113 of file galilei.cpp.
References mpi_call_all(), mpi_kill_particle_forces_local(), and torque.
mpi_kill_particle_forces_local()
void mpi_kill_particle_forces_local (int torque)
Definition at line 106 of file galilei.cpp.
References cell_structure, local_kill_particle_forces(), CellStructure::local_particles(), on_particle_change(), and torque.
Referenced by mpi_kill_particle_forces().
mpi_kill_particle_motion()
void mpi_kill_particle_motion (int rotation)
Stop particle motion by setting the velocity of each particle to zero.
Parameters
rotation if true, also set particle angular velocities to zero
Definition at line 102 of file galilei.cpp.
References mpi_call_all(), and mpi_kill_particle_motion_local().
mpi_kill_particle_motion_local()
void mpi_kill_particle_motion_local (int rotation)
Definition at line 95 of file galilei.cpp.
References cell_structure, local_kill_particle_motion(), CellStructure::local_particles(), and on_particle_change().
Referenced by mpi_kill_particle_motion().
mpi_system_CMS()
Utils::Vector3d mpi_system_CMS ()
Calculate the CMS of the system.
Definition at line 124 of file galilei.cpp.
References local_system_CMS(), mpi_call(), and Communication::Result::reduction.
mpi_system_CMS_velocity()
Utils::Vector3d mpi_system_CMS_velocity ()
Calculate the CMS velocity of the system.
Definition at line 132 of file galilei.cpp.
References local_system_CMS_velocity(), mpi_call(), and Communication::Result::reduction.
Referenced by mpi_galilei_transform().