ESPResSo: galilei.hpp File Reference
galilei.hpp File Reference
#include <utils/Vector.hpp>
Functions
void mpi_kill_particle_motion (int rotation)
Stop particle motion by setting the velocity of each particle to zero.
void mpi_kill_particle_forces (int torque)
Set all the forces acting on the particles to zero.
Utils::Vector3d mpi_system_CMS ()
Calculate the CMS of the system.
Utils::Vector3d mpi_system_CMS_velocity ()
Calculate the CMS velocity of the system.
void mpi_galilei_transform ()
Remove the CMS velocity.
Function Documentation
mpi_galilei_transform()
void mpi_galilei_transform ()
Remove the CMS velocity.
Definition at line 147 of file galilei.cpp.
References mpi_call_all(), mpi_galilei_transform_local(), and mpi_system_CMS_velocity().
mpi_kill_particle_forces()
void mpi_kill_particle_forces (int torque)
Set all the forces acting on the particles to zero.
Parameters
torque if true, also set particle torques to zero
Definition at line 113 of file galilei.cpp.
References mpi_call_all(), mpi_kill_particle_forces_local(), and torque.
mpi_kill_particle_motion()
void mpi_kill_particle_motion (int rotation)
Stop particle motion by setting the velocity of each particle to zero.
Parameters
rotation if true, also set particle angular velocities to zero
Definition at line 102 of file galilei.cpp.
References mpi_call_all(), and mpi_kill_particle_motion_local().
mpi_system_CMS()
Utils::Vector3d mpi_system_CMS ()
Calculate the CMS of the system.
Definition at line 124 of file galilei.cpp.
References local_system_CMS(), mpi_call(), and Communication::Result::reduction.
mpi_system_CMS_velocity()
Utils::Vector3d mpi_system_CMS_velocity ()
Calculate the CMS velocity of the system.
Definition at line 132 of file galilei.cpp.
References local_system_CMS_velocity(), mpi_call(), and Communication::Result::reduction.
Referenced by mpi_galilei_transform().