ESPResSo: gay_berne.hpp File Reference
gay_berne.hpp File Reference
Routines to calculate the Gay-Berne potential between particle pairs.
#include "config/config.hpp"
#include "Particle.hpp"
#include "nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
#include <utils/quaternion.hpp>
#include <cmath>
Functions
ParticleForce gb_pair_force (Utils::Vector3d const &ui, Utils::Vector3d const &uj, IA_parameters const &ia_params, Utils::Vector3d const &d, double dist)
Calculate Gay-Berne force and torques.
double gb_pair_energy (Utils::Quaternion< double > const &qi, Utils::Quaternion< double > const &qj, IA_parameters const &ia_params, Utils::Vector3d const &d, double dist)
Calculate Gay-Berne energy.
ParticleForce gb_pair_force (Utils::Quaternion< double > const &qi, Utils::Quaternion< double > const &qj, IA_parameters const &ia_params, Utils::Vector3d const &d, double dist)
Detailed Description
Routines to calculate the Gay-Berne potential between particle pairs.
Please note that contrary to the original paper [21], here the GB prefactor \(\varepsilon_0 \) is not raised to the power of \(\nu \), in agreement with the convention used in the GB literature.
Implementation in gay_berne.cpp.
Definition in file gay_berne.hpp.
Function Documentation
gb_pair_energy()
double gb_pair_energy (Utils::Quaternion< double > const & qi, Utils::Quaternion< double > const & qj, IA_parameters const & ia_params, Utils::Vector3d const & d, double dist) inline
Calculate Gay-Berne energy.
Definition at line 132 of file gay_berne.hpp.
References Utils::convert_quaternion_to_director(), Utils::int_pow(), Utils::sqr(), and stream.
Referenced by calc_non_bonded_pair_energy().
gb_pair_force() [1/2]
ParticleForce gb_pair_force (Utils::Quaternion< double > const & qi, Utils::Quaternion< double > const & qj, IA_parameters const & ia_params, Utils::Vector3d const & d, double dist) inline
Definition at line 177 of file gay_berne.hpp.
References Utils::convert_quaternion_to_director(), gb_pair_force(), and stream.
gb_pair_force() [2/2]
ParticleForce gb_pair_force (Utils::Vector3d const & ui, Utils::Vector3d const & uj, IA_parameters const & ia_params, Utils::Vector3d const & d, double dist) inline
Calculate Gay-Berne force and torques.
Definition at line 49 of file gay_berne.hpp.
References Utils::int_pow(), Utils::sqr(), stream, and vector_product().
Referenced by calc_non_central_force(), gb_pair_force(), and ForcesKernel::operator()().