ESPResSo: GpuParticleData.cpp File Reference
GpuParticleData.cpp File Reference
#include "config/config.hpp"
#include "GpuParticleData.hpp"
#include "cell_system/CellStructure.hpp"
#include "communication.hpp"
#include "cuda/CudaHostAllocator.hpp"
#include "system/System.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/mpi/gather_buffer.hpp>
#include <utils/mpi/scatter_buffer.hpp>
#include <boost/serialization/array.hpp>
#include <boost/serialization/is_bitwise_serializable.hpp>
#include <boost/serialization/split_free.hpp>
#include <vector>
Namespaces
boost
boost::serialization
Functions
template<typename Archive >
void boost::serialization::load (Archive &ar, GpuParticleData::GpuParticle &p, unsigned const)
template<typename Archive >
void boost::serialization::save (Archive &ar, GpuParticleData::GpuParticle const &p, unsigned const)
static void pack_particles (ParticleRange const &particles, GpuParticleData::GpuParticle *buffer)
static void add_forces_and_torques (ParticleRange const &particles, Utils::Span< const float > forces, Utils::Span< const float > torques)
Add a flat force (and torque) array to a range of particles.
Function Documentation
add_forces_and_torques()
static void add_forces_and_torques (ParticleRange const & particles, Utils::Span< const float > forces, Utils::Span< const float > torques) static
Add a flat force (and torque) array to a range of particles.
Parameters
particles The particles the forces (and torques) should be added to
forces The forces as flat array of size 3 * particles.size()
torques The torques as flat array of size 3 * particles.size(), this is only touched if ROTATION is active.
Definition at line 131 of file GpuParticleData.cpp.
References Cells::particles(), and u.
pack_particles()
static void pack_particles (ParticleRange const & particles, GpuParticleData::GpuParticle * buffer) static
Definition at line 84 of file GpuParticleData.cpp.
References System::System::box_geo, System::get_system(), Cells::particles(), and u.