ESPResSo: GpuParticleData_cuda.cu File Reference
GpuParticleData_cuda.cu File Reference
CUDA kernels to convert the particles AoS to a SoA on the device.
#include <config/config.hpp>
#include "GpuParticleData.hpp"
#include "System.hpp"
#include "ParticleRange.hpp"
#include "errorhandling.hpp"
#include "cuda/init.hpp"
#include "cuda/utils.cuh"
#include <thrust/copy.h>
#include <thrust/device_vector.h>
#include <cuda.h>
#include <cstddef>
#include <cstdio>
#include <memory>
#include <span>
Classes
class GpuParticleData::Storage
Host and device containers for particle data.
Functions
template<class T >
T * raw_data_pointer (thrust::device_vector< T > &vec)
template<class SpanLike >
std::size_t byte_size (SpanLike const &v)
template<class T >
void resize_or_replace (thrust::device_vector< T > &vec, std::size_t n)
Resize a thrust::device_vector.
template<typename T >
void free_device_vector (thrust::device_vector< T > &vec)
__global__ void split_kernel_r (GpuParticleData::GpuParticle *particles, float *r, std::size_t n)
__global__ void split_kernel_rq (GpuParticleData::GpuParticle *particles, float *r, float *q, std::size_t n)
__global__ void split_kernel_q (GpuParticleData::GpuParticle *particles, float *q, std::size_t n)
__global__ void split_kernel_dip (GpuParticleData::GpuParticle *particles, float *dip, std::size_t n)
Detailed Description
CUDA kernels to convert the particles AoS to a SoA on the device.
Definition in file GpuParticleData_cuda.cu.
Function Documentation
byte_size()
template<class SpanLike > std::size_t byte_size (SpanLike const & v)
Definition at line 53 of file GpuParticleData_cuda.cu.
Referenced by GpuParticleData::Storage::copy_particles_to_device().
free_device_vector()
template<typename T > void free_device_vector (thrust::device_vector< T > & vec)
Definition at line 84 of file GpuParticleData_cuda.cu.
References stream.
raw_data_pointer()
template<class T > T * raw_data_pointer (thrust::device_vector< T > & vec)
Definition at line 49 of file GpuParticleData_cuda.cu.
References stream.
Referenced by GpuParticleData::Storage::copy_particles_to_device(), GpuParticleData::get_particle_dip_fld_device(), GpuParticleData::get_particle_forces_device(), GpuParticleData::get_particle_torques_device(), and GpuParticleData::Storage::split_particle_struct().
resize_or_replace()
template<class T > void resize_or_replace (thrust::device_vector< T > & vec, std::size_t n)
Resize a thrust::device_vector.
Due to a bug in thrust (https://github.com/thrust/thrust/issues/939), resizing or appending to default constructed containers causes undefined behavior by dereferencing a null-pointer for certain types. This function is used instead of the resize member function to side-step the problem. This is done by replacing the existing vector by a new one constructed with the desired size if resizing from capacity zero. Behaves as-if vec.resize(n) was called. This is fixed in Thrust 1.11, shipped in CUDA 11.3 (https://github.com/NVIDIA/thrust/commit/1c4f25d9). But Clang 20's UBSAN still triggers a runtime error as of CUDA 12.0
Template Parameters
T Type contained in the vector.
Parameters
vec Vector to resize.
n Desired new size of the vector.
Definition at line 76 of file GpuParticleData_cuda.cu.
References stream.
Referenced by GpuParticleData::Storage::copy_particles_to_device().
split_kernel_dip()
__global__ void split_kernel_dip (GpuParticleData::GpuParticle * particles, float * dip, std::size_t n)
Definition at line 402 of file GpuParticleData_cuda.cu.
References stream.
split_kernel_q()
__global__ void split_kernel_q (GpuParticleData::GpuParticle * particles, float * q, std::size_t n)
Definition at line 389 of file GpuParticleData_cuda.cu.
References stream.
split_kernel_r()
__global__ void split_kernel_r (GpuParticleData::GpuParticle * particles, float * r, std::size_t n)
Definition at line 360 of file GpuParticleData_cuda.cu.
References stream.
split_kernel_rq()
__global__ void split_kernel_rq (GpuParticleData::GpuParticle * particles, float * r, float * q, std::size_t n)
Definition at line 375 of file GpuParticleData_cuda.cu.
References stream.