ESPResSo: halo.hpp File Reference
halo.hpp File Reference
#include "grid_based_algorithms/lattice.hpp"
#include <utils/Vector.hpp>
#include <mpi.h>
#include <memory>
#include <vector>
Classes
struct FieldType
Layout of the lattice data.
struct HaloInfo
Structure describing a Halo region.
class HaloCommunicator
Structure holding a set of HaloInfo which comprise a certain parallelization scheme.
Macros
Types of halo communications
#define HALO_LOCL 0
Tag for local exchange of halo regions on the same processor.
#define HALO_SENDRECV 1
Tag for halo exchange between different processors.
#define HALO_SEND 2
Tag for halo send only.
#define HALO_RECV 3
Tag for halo receive only.
#define HALO_OPEN 4
Tag for halo open boundary.
Tags for halo communications
#define REQ_HALO_SPREAD 501
Tag for halo update.
#define REQ_HALO_CHECK 599
Tag for consistency check of halo regions.
Functions
void prepare_halo_communication (HaloCommunicator &hc, const Lattice &lattice, MPI_Datatype datatype, const Utils::Vector3i &local_node_grid)
Preparation of the halo parallelization scheme.
void release_halo_communication (HaloCommunicator &hc)
Frees data structures associated with a halo communicator.
void halo_communication (const HaloCommunicator &hc, char *base)
Perform communication according to the parallelization scheme described by the halo communicator.
Detailed Description
Halo scheme for parallelization of lattice algorithms. Header file for halo.cpp.
Definition in file halo.hpp.
Macro Definition Documentation
HALO_LOCL
#define HALO_LOCL 0
Tag for local exchange of halo regions on the same processor.
Definition at line 41 of file halo.hpp.
HALO_OPEN
#define HALO_OPEN 4
Tag for halo open boundary.
Definition at line 47 of file halo.hpp.
HALO_RECV
#define HALO_RECV 3
Tag for halo receive only.
Definition at line 46 of file halo.hpp.
HALO_SEND
#define HALO_SEND 2
Tag for halo send only.
Definition at line 45 of file halo.hpp.
HALO_SENDRECV
#define HALO_SENDRECV 1
Tag for halo exchange between different processors.
Definition at line 43 of file halo.hpp.
REQ_HALO_CHECK
#define REQ_HALO_CHECK 599
Tag for consistency check of halo regions.
Definition at line 53 of file halo.hpp.
REQ_HALO_SPREAD
#define REQ_HALO_SPREAD 501
Tag for halo update.
Definition at line 52 of file halo.hpp.
Function Documentation
halo_communication()
void halo_communication (const HaloCommunicator & hc, char * base)
Perform communication according to the parallelization scheme described by the halo communicator.
Parameters
[in] hc halo communicator describing the parallelization scheme
[in] base base plane of local node
Todo:
this does not work for the n_i - <n_i>
Definition at line 211 of file halo.cpp.
References comm_cart, halo_dtcopy(), halo_dtset(), HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, HaloCommunicator::num, and REQ_HALO_SPREAD.
Referenced by lb_integrate(), and lb_lbfluid_on_integration_start().
prepare_halo_communication()
void prepare_halo_communication (HaloCommunicator & hc, const Lattice & lattice, MPI_Datatype datatype, const Utils::Vector3i & local_node_grid)
Preparation of the halo parallelization scheme.
Sets up the necessary data structures for halo_communication
Parameters
[in,out] hc halo communicator being created
[in] lattice lattice the communication is created for
datatype MPI datatype for the lattice data
local_node_grid Number of nodes in each spatial dimension
Definition at line 118 of file halo.cpp.
References LocalBox< T >::boundary(), box_geo, calc_node_neighbors(), comm_cart, HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, fieldtype_double, Lattice::grid, Lattice::halo_grid, HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, local_geo, HaloCommunicator::num, BoxGeometry::periodic(), HaloInfo::r_offset, HaloInfo::s_offset, HaloInfo::source_node, and HaloInfo::type.
Referenced by lb_prepare_communication().
release_halo_communication()
void release_halo_communication (HaloCommunicator & hc)
Frees data structures associated with a halo communicator.
Parameters
[in,out] hc halo communicator to be released
Definition at line 205 of file halo.cpp.
References HaloCommunicator::halo_info, and HaloCommunicator::num.
Referenced by lb_prepare_communication().