ESPResSo: halo.cpp File Reference
halo.cpp File Reference
#include "config.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "grid_based_algorithms/lattice.hpp"
#include "halo.hpp"
#include <utils/Vector.hpp>
#include <cstdlib>
#include <cstring>
#include <memory>
Functions
void halo_dtset (char *dest, int value, std::shared_ptr< FieldType > type)
Set halo region to a given value.
void halo_dtcopy (char *r_buffer, char *s_buffer, int count, std::shared_ptr< FieldType > type)
Copy lattice data with layout described by type.
void halo_copy_vector (char *r_buffer, char *s_buffer, int count, std::shared_ptr< FieldType > type, bool vflag)
void prepare_halo_communication (HaloCommunicator &hc, const Lattice &lattice, MPI_Datatype datatype, const Utils::Vector3i &local_node_grid)
Preparation of the halo parallelization scheme.
void release_halo_communication (HaloCommunicator &hc)
Frees data structures associated with a halo communicator.
void halo_communication (const HaloCommunicator &hc, char *const base)
Perform communication according to the parallelization scheme described by the halo communicator.
Variables
static std::shared_ptr< FieldType > fieldtype_double
Predefined fieldtype for double-precision LB.
Detailed Description
Halo scheme for parallelization of lattice algorithms. Implementation of file halo.hpp.
Definition in file halo.cpp.
Function Documentation
halo_communication()
void halo_communication (const HaloCommunicator & hc, char * base)
Perform communication according to the parallelization scheme described by the halo communicator.
Parameters
[in] hc halo communicator describing the parallelization scheme
[in] base base plane of local node
Todo:
this does not work for the n_i - <n_i>
Definition at line 211 of file halo.cpp.
References comm_cart, halo_dtcopy(), halo_dtset(), HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, HaloCommunicator::num, and REQ_HALO_SPREAD.
Referenced by lb_integrate(), and lb_lbfluid_on_integration_start().
halo_copy_vector()
void halo_copy_vector (char * r_buffer, char * s_buffer, int count, std::shared_ptr< FieldType > type, bool vflag)
Definition at line 71 of file halo.cpp.
References FieldType::extent, halo_dtcopy(), FieldType::subtype, FieldType::vblocks, FieldType::vskip, and FieldType::vstride.
Referenced by halo_dtcopy().
halo_dtcopy()
void halo_dtcopy (char * r_buffer, char * s_buffer, int count, std::shared_ptr< FieldType > type)
Copy lattice data with layout described by type.
Parameters
r_buffer data destination
s_buffer data source
count amount of data to copy
type field layout type
Definition at line 97 of file halo.cpp.
References FieldType::count, FieldType::disps, FieldType::extent, halo_copy_vector(), FieldType::lengths, FieldType::subtype, and FieldType::vflag.
Referenced by halo_communication(), and halo_copy_vector().
halo_dtset()
void halo_dtset (char * dest, int value, std::shared_ptr< FieldType > type)
Set halo region to a given value.
Parameters
[out] dest pointer to the halo buffer
value integer value to write into the halo buffer
type halo field layout description
Definition at line 50 of file halo.cpp.
References FieldType::disps, FieldType::extent, FieldType::lengths, FieldType::vblocks, FieldType::vskip, and FieldType::vstride.
Referenced by halo_communication().
prepare_halo_communication()
void prepare_halo_communication (HaloCommunicator & hc, const Lattice & lattice, MPI_Datatype datatype, const Utils::Vector3i & local_node_grid)
Preparation of the halo parallelization scheme.
Sets up the necessary data structures for halo_communication
Parameters
[in,out] hc halo communicator being created
[in] lattice lattice the communication is created for
datatype MPI datatype for the lattice data
local_node_grid Number of nodes in each spatial dimension
Definition at line 118 of file halo.cpp.
References LocalBox< T >::boundary(), box_geo, calc_node_neighbors(), comm_cart, HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, fieldtype_double, Lattice::grid, Lattice::halo_grid, HaloCommunicator::halo_info, HALO_LOCL, HALO_OPEN, HALO_RECV, HALO_SEND, HALO_SENDRECV, local_geo, HaloCommunicator::num, BoxGeometry::periodic(), HaloInfo::r_offset, HaloInfo::s_offset, HaloInfo::source_node, and HaloInfo::type.
Referenced by lb_prepare_communication().
release_halo_communication()
void release_halo_communication (HaloCommunicator & hc)
Frees data structures associated with a halo communicator.
Parameters
[in,out] hc halo communicator to be released
Definition at line 205 of file halo.cpp.
References HaloCommunicator::halo_info, and HaloCommunicator::num.
Referenced by lb_prepare_communication().
Variable Documentation
fieldtype_double
std::shared_ptr<FieldType> fieldtype_double static
Initial value:
=
    std::make_shared<FieldType>(static_cast<int>(sizeof(double)))
Predefined fieldtype for double-precision LB.
Definition at line 42 of file halo.cpp.
Referenced by prepare_halo_communication().