ESPResSo: hat.hpp File Reference
hat.hpp File Reference
#include "config.hpp"
#include "nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
Functions
int hat_set_params (int part_type_a, int part_type_b, double Fmax, double r)
double hat_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate hat force factor.
double hat_pair_energy (IA_parameters const &ia_params, double dist)
Calculate hat energy.
Detailed Description
Routines to calculate the hat potential between particle pairs.
Implementation in hat.cpp.
Definition in file hat.hpp.
Function Documentation
hat_pair_energy()
double hat_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate hat energy.
Definition at line 50 of file hat.hpp.
References Hat_Parameters::Fmax, IA_parameters::hat, and Hat_Parameters::r.
Referenced by calc_non_bonded_pair_energy().
hat_pair_force_factor()
double hat_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate hat force factor.
Definition at line 41 of file hat.hpp.
References Hat_Parameters::Fmax, IA_parameters::hat, and Hat_Parameters::r.
Referenced by calc_non_bonded_pair_force().
hat_set_params()
int hat_set_params (int part_type_a, int part_type_b, double Fmax, double r)
Definition at line 33 of file hat.cpp.
References ES_ERROR, ES_OK, Hat_Parameters::Fmax, get_ia_param_safe(), IA_parameters::hat, mpi_bcast_ia_params(), and Hat_Parameters::r.