ESPResSo: ibm_common.cpp File Reference
ibm_common.cpp File Reference
#include "ibm_common.hpp"
#include "Particle.hpp"
#include "cell_system/CellStructure.hpp"
#include "communication.hpp"
#include "system/System.hpp"
#include <utils/Vector.hpp>
#include <utils/serialization/optional.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <optional>
#include <stdexcept>
Functions
Utils::Vector3d get_ibm_particle_position (CellStructure const &cell_structure, int pid)
Returns the position of a given particle.
Function Documentation
get_ibm_particle_position()
Utils::Vector3d get_ibm_particle_position (CellStructure const & cell_structure, int pid)
Returns the position of a given particle.
Parameters
cell_structure Cell structure to search.
pid Particle id.
Returns
position of the particle.
Definition at line 35 of file ibm_common.cpp.
References comm_cart, CellStructure::get_local_particle(), Particle::pos(), and stream.
Referenced by IBMTribend::initialize(), and IBMTriel::initialize().