ESPResSo: icc.cpp File Reference
icc.cpp File Reference
#include "config.hpp"
#include "icc.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "actor/visitors.hpp"
#include "cell_system/CellStructure.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "electrostatics/coulomb.hpp"
#include "electrostatics/coulomb_inline.hpp"
#include "errorhandling.hpp"
#include "event.hpp"
#include "integrate.hpp"
#include <utils/constants.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <boost/mpi/operations.hpp>
#include <algorithm>
#include <cassert>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <vector>
Functions
static void force_calc_icc (CellStructure &cell_structure, ParticleRange const &particles, ParticleRange const &ghost_particles, Coulomb::ShortRangeForceKernel::result_type const &coulomb_kernel, Coulomb::ShortRangeForceCorrectionsKernel::result_type const &elc_kernel)
Calculate the electrostatic forces between source charges (= real charges) and wall charges.
void update_icc_particles ()
Detailed Description
Functions to compute the electric field acting on the induced charges, excluding forces other than the electrostatic ones. Detailed information about the ICC* method is included in the corresponding header file icc.hpp.
Definition in file icc.cpp.
Function Documentation
force_calc_icc()
static void force_calc_icc (CellStructure & cell_structure, ParticleRange const & particles, ParticleRange const & ghost_particles, Coulomb::ShortRangeForceKernel::result_type const & coulomb_kernel, Coulomb::ShortRangeForceCorrectionsKernel::result_type const & elc_kernel) static
Calculate the electrostatic forces between source charges (= real charges) and wall charges.
For each electrostatic method, the proper functions for short- and long-range parts are called. Long-range parts are calculated directly, short-range parts need helper functions according to the particle data organisation. This is a modified version of force_calc.
Definition at line 65 of file icc.cpp.
References cell_structure, CellStructure::non_bonded_loop(), and Cells::particles().
Referenced by ICCStar::iteration().
update_icc_particles()
void update_icc_particles ()
Definition at line 276 of file icc.cpp.
References cell_structure, electrostatics_extension, Utils::get(), CellStructure::ghost_particles(), and CellStructure::local_particles().
Referenced by update_dependent_particles().