ESPResSo: init_cuda.cu File Reference
init_cuda.cu File Reference
#include <cuda.h>
#include "init.hpp"
#include "utils.cuh"
#include <utils/constants.hpp>
#include <cstring>
#include <string>
Functions
void cuda_init ()
Initializes the CUDA stream.
int cuda_get_n_gpus ()
Get the number of CUDA devices.
int cuda_check_gpu_compute_capability (int dev)
Check that a given GPU has compute capability.
void cuda_get_gpu_name (int dev, char name[64])
Get the name of a CUDA device.
EspressoGpuDevice cuda_get_device_props (const int dev)
Get properties of a CUDA device.
void cuda_set_device (int dev)
Choose a device for future CUDA computations.
int cuda_get_device ()
Get the current CUDA device.
int cuda_test_device_access ()
Test if actual CUDA device works.
void cuda_check_device ()
Check that a device is available, that its compute capability is sufficient for ESPResSo, and that data can be written to and read from it.
Variables
minimally required compute capability.
static const int computeCapabilityMinMajor = 3
static const int computeCapabilityMinMinor = 0
Function Documentation
cuda_check_device()
void cuda_check_device ()
Check that a device is available, that its compute capability is sufficient for ESPResSo, and that data can be written to and read from it.
Otherwise, throw an exception.
Definition at line 122 of file init_cuda.cu.
References cuda_check_gpu_compute_capability(), cuda_get_device(), cuda_get_n_gpus(), cuda_test_device_access(), and ES_OK.
cuda_check_gpu_compute_capability()
int cuda_check_gpu_compute_capability (int dev)
Check that a given GPU has compute capability.
The minimal compute capability required by ESPResSo is computeCapabilityMinMajor . computeCapabilityMinMinor .
Parameters
dev CUDA device number
Returns
ES_OK if the GPU meets the requirements, else ES_ERROR.
Definition at line 50 of file init_cuda.cu.
References computeCapabilityMinMajor, computeCapabilityMinMinor, CUDA_CHECK, ES_ERROR, and ES_OK.
Referenced by cuda_check_device().
cuda_get_device()
int cuda_get_device ()
Get the current CUDA device.
Returns
the current device's number.
Definition at line 90 of file init_cuda.cu.
References CUDA_CHECK.
Referenced by allocBHmemCopy(), cuda_check_device(), and ScriptInterface::System::CudaInitHandle::CudaInitHandle().
cuda_get_device_props()
EspressoGpuDevice cuda_get_device_props (int dev)
Get properties of a CUDA device.
Parameters
dev CUDA device number
Definition at line 68 of file init_cuda.cu.
References CUDA_CHECK.
Referenced by allocBHmemCopy(), and cuda_gather_gpus().
cuda_get_gpu_name()
void cuda_get_gpu_name (int dev, char name[64])
Get the name of a CUDA device.
Parameters
[in] dev the CUDA device number to ask the name for
[out] name a buffer to write the name to, at least 64 characters
Definition at line 61 of file init_cuda.cu.
References CUDA_CHECK.
Referenced by ScriptInterface::System::CudaInitHandle::do_call_method().
cuda_get_n_gpus()
int cuda_get_n_gpus ()
Get the number of CUDA devices.
Returns
the number of GPUs.
Definition at line 44 of file init_cuda.cu.
References CUDA_CHECK, and deviceCount.
Referenced by cuda_check_device(), cuda_gather_gpus(), and ScriptInterface::System::CudaInitHandle::do_call_method().
cuda_init()
void cuda_init ()
Initializes the CUDA stream.
Definition at line 42 of file init_cuda.cu.
References CUDA_CHECK, and stream.
Referenced by cuda_on_program_start().
cuda_set_device()
void cuda_set_device (int dev)
Choose a device for future CUDA computations.
Parameters
dev the device to use
Definition at line 84 of file init_cuda.cu.
References CUDA_CHECK, cudaSetDevice, and stream.
Referenced by ScriptInterface::System::CudaInitHandle::CudaInitHandle().
cuda_test_device_access()
int cuda_test_device_access ()
Test if actual CUDA device works.
Returns
ES_OK on success, ES_ERROR else.
Definition at line 96 of file init_cuda.cu.
References ES_ERROR, ES_OK, and h.
Referenced by cuda_check_device().
Variable Documentation
computeCapabilityMinMajor
const int computeCapabilityMinMajor = 3 static
Definition at line 38 of file init_cuda.cu.
Referenced by cuda_check_gpu_compute_capability().
computeCapabilityMinMinor
const int computeCapabilityMinMinor = 0 static
Definition at line 39 of file init_cuda.cu.
Referenced by cuda_check_gpu_compute_capability().