ESPResSo: integrate.cpp File Reference
integrate.cpp File Reference
#include "integrate.hpp"
#include "integrators/brownian_inline.hpp"
#include "integrators/steepest_descent.hpp"
#include "integrators/stokesian_dynamics_inline.hpp"
#include "integrators/velocity_verlet_inline.hpp"
#include "integrators/velocity_verlet_npt.hpp"
#include "ParticleRange.hpp"
#include "accumulators.hpp"
#include "bond_breakage/bond_breakage.hpp"
#include "bonded_interactions/rigid_bond.hpp"
#include "cells.hpp"
#include "collision.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "event.hpp"
#include "forces.hpp"
#include "grid.hpp"
#include "grid_based_algorithms/lb_interface.hpp"
#include "grid_based_algorithms/lb_particle_coupling.hpp"
#include "interactions.hpp"
#include "lees_edwards/lees_edwards.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "npt.hpp"
#include "rattle.hpp"
#include "rotation.hpp"
#include "signalhandling.hpp"
#include "thermostat.hpp"
#include "virtual_sites.hpp"
#include <profiler/profiler.hpp>
#include <boost/range/algorithm/min_element.hpp>
#include <algorithm>
#include <cassert>
#include <cmath>
#include <csignal>
#include <functional>
#include <stdexcept>
#include <utility>
Namespaces
anonymous_namespace{integrate.cpp}
LeesEdwards
Functions
void anonymous_namespace{integrate.cpp}::notify_sig_int ()
static void LeesEdwards::update_box_params ()
Update the Lees-Edwards parameters of the box geometry for the current simulation time.
void LeesEdwards::set_protocol (std::shared_ptr< ActiveProtocol > new_protocol)
Set a new Lees-Edwards protocol.
void LeesEdwards::unset_protocol ()
Delete the currently active Lees-Edwards protocol.
template<class Kernel >
void LeesEdwards::run_kernel ()
void integrator_sanity_checks ()
Check integrator parameters and incompatibilities between the integrator and the currently active thermostat(s).
static void resort_particles_if_needed (ParticleRange const &particles)
static bool integrator_step_1 (ParticleRange const &particles)
Calls the hook for propagation kernels before the force calculation.
static void integrator_step_2 (ParticleRange const &particles, double kT)
Calls the hook of the propagation kernels after force calculation.
int integrate (int n_steps, int reuse_forces)
Integrate equations of motion.
int python_integrate (int n_steps, bool recalc_forces_par, bool reuse_forces_par)
Run the integration loop.
static int mpi_steepest_descent_local (int steps)
int mpi_steepest_descent (int steps)
Steepest descent main integration loop.
static int mpi_integrate_local (int n_steps, int reuse_forces)
int mpi_integrate (int n_steps, int reuse_forces)
Start integrator.
void integrate_set_steepest_descent (const double f_max, const double gamma, const double max_displacement)
Set the steepest descent integrator for energy minimization.
void integrate_set_nvt ()
Set the velocity Verlet integrator for the NVT ensemble.
void integrate_set_bd ()
Set the Brownian Dynamics integrator.
void integrate_set_sd ()
Set the Stokesian Dynamics integrator.
void integrate_set_npt_isotropic (double ext_pressure, double piston, bool xdir_rescale, bool ydir_rescale, bool zdir_rescale, bool cubic_box)
Set the velocity Verlet integrator modified for the NpT ensemble with isotropic rescaling.
double interaction_range ()
double get_verlet_reuse ()
Get verlet_reuse.
double get_time_step ()
Get time step.
double get_sim_time ()
Get simulation time.
void increment_sim_time (double amount)
Increase simulation time (only on head node)
void mpi_set_time_step_local (double dt)
void mpi_set_time_step (double time_s)
Send new time_step and rescale the velocities accordingly.
void mpi_set_skin_local (double skin)
void mpi_set_skin (double skin)
Set and broadcast the skin.
void mpi_set_time_local (double time)
void mpi_set_time (double time)
Set and broadcast the time.
void mpi_set_integ_switch_local (int integ_switch)
void mpi_set_integ_switch (int integ_switch)
Variables
int integ_switch = INTEG_METHOD_NVT
Switch determining which integrator to use.
static double time_step = -1.0
Time step for the integration.
static double sim_time = 0.0
Actual simulation time.
double skin = 0.0
Verlet list skin.
static bool skin_set = false
True iff the user has changed the skin setting.
bool recalc_forces = true
If true, the forces will be recalculated before the next integration.
static double verlet_reuse = 0.0
Average number of integration steps the Verlet list has been re-using.
static int fluid_step = 0
bool set_py_interrupt = false
Communicate signal handling to the Python interpreter.
volatile std::sig_atomic_t anonymous_namespace{integrate.cpp}::ctrl_C = 0
static std::shared_ptr< ActiveProtocol > LeesEdwards::protocol = nullptr
Currently active Lees-Edwards protocol.
Detailed Description
Molecular dynamics integrator.
For more information about the integrator see integrate.hpp.
Definition in file integrate.cpp.
Function Documentation
get_sim_time()
double get_sim_time ()
Get simulation time.
Definition at line 540 of file integrate.cpp.
References sim_time.
Referenced by force_calc().
get_time_step()
double get_time_step ()
Get time step.
Definition at line 538 of file integrate.cpp.
References time_step.
Referenced by ek_init(), and lb_reinit_parameters_gpu().
get_verlet_reuse()
double get_verlet_reuse ()
Get verlet_reuse.
Definition at line 536 of file integrate.cpp.
References verlet_reuse.
Referenced by ScriptInterface::CellSystem::CellSystem::do_call_method().
increment_sim_time()
void increment_sim_time (double amount)
Increase simulation time (only on head node)
Definition at line 542 of file integrate.cpp.
References sim_time.
Referenced by brownian_dynamics_propagator(), stokesian_dynamics_step_1(), velocity_verlet_npt_step_1(), and velocity_verlet_step_1().
integrate()
int integrate (int n_steps, int reuse_forces)
Integrate equations of motion.
Parameters
n_steps Number of integration steps, can be zero
reuse_forces Decide when to re-calculate forces:
-1: recalculate forces unconditionally (mostly used for timing)
0: recalculate forces if recalc_forces is set, meaning it is probably necessary
1: do not recalculate forces (mostly when reading checkpoints with forces)
This function calls two hooks for propagation kernels such as velocity verlet, velocity verlet + npt box changes, and steepest_descent. One hook is called before and one after the force calculation. It is up to the propagation kernels to increment the simulation time.
This function propagates the system according to the choice of integrator stored in integ_switch. The general structure is:
if reuse_forces is zero, recalculate the forces based on the current state of the system
Loop over the number of simulation steps:
initialization (e.g., RATTLE)
First hook for propagation kernels
Update dependent particles and properties (RATTLE, virtual sites)
Calculate forces for the current state of the system. This includes forces added by the Langevin thermostat and the Lattice-Boltzmann-particle coupling
Second hook for propagation kernels
Update dependent properties (Virtual sites, RATTLE)
Run single step algorithms (Lattice-Boltzmann propagation, collision detection, NpT update)
Final update of dependent properties and statistics/counters
High-level documentation of the integration and thermostatting schemes can be found in doc/sphinx/system_setup.rst and /doc/sphinx/running.rst
Returns
number of steps that have been integrated
Definition at line 253 of file integrate.cpp.
References cell_structure, cells_update_ghosts(), check_runtime_errors(), comm_cart, convert_initial_torques(), correct_position_shake(), correct_velocity_shake(), anonymous_namespace{integrate.cpp}::ctrl_C, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, ESPRESSO_PROFILER_CXX_MARK_LOOP_BEGIN, ESPRESSO_PROFILER_CXX_MARK_LOOP_END, ESPRESSO_PROFILER_CXX_MARK_LOOP_ITERATION, ESPRESSO_PROFILER_MARK_BEGIN, ESPRESSO_PROFILER_MARK_END, fluid_step, force_calc(), CellStructure::get_resort_particles(), CellStructure::ghost_particles(), global_ghost_flags(), handle_collisions(), INTEG_METHOD_NPT_ISO, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, integrator_step_1(), integrator_step_2(), lb_lbcoupling_activate(), lb_lbcoupling_deactivate(), lb_lbcoupling_propagate(), lb_lbfluid_get_lattice_switch(), lb_lbfluid_get_tau(), lb_lbfluid_propagate(), CellStructure::local_particles(), n_rigidbonds, NONE, anonymous_namespace{integrate.cpp}::notify_sig_int(), on_integration_start(), Cells::particles(), philox_counter_increment(), BondBreakage::process_queue(), recalc_forces, Cells::RESORT_LOCAL, resort_particles_if_needed(), save_old_position(), synchronize_npt_state(), temperature, time_step, LeesEdwards::update_box_params(), verlet_reuse, and virtual_sites().
Referenced by mpi_integrate_local(), and mpi_steepest_descent_local().
integrate_set_bd()
void integrate_set_bd ()
Set the Brownian Dynamics integrator.
Definition at line 511 of file integrate.cpp.
References INTEG_METHOD_BD, and mpi_set_integ_switch().
integrate_set_npt_isotropic()
void integrate_set_npt_isotropic (double ext_pressure, double piston, bool xdir_rescale, bool ydir_rescale, bool zdir_rescale, bool cubic_box)
Set the velocity Verlet integrator modified for the NpT ensemble with isotropic rescaling.
Parameters
ext_pressure Reference pressure
piston Piston mass
xdir_rescale Enable box rescaling in the x-direction
ydir_rescale Enable box rescaling in the y-direction
zdir_rescale Enable box rescaling in the z-direction
cubic_box Determines if the volume fluctuations should also apply to dimensions which are switched off by the above flags and which do not contribute to the pressure (3D) or tension (2D, 1D)
Definition at line 521 of file integrate.cpp.
References INTEG_METHOD_NPT_ISO, mpi_set_integ_switch(), and nptiso_init().
integrate_set_nvt()
void integrate_set_nvt ()
Set the velocity Verlet integrator for the NVT ensemble.
Definition at line 509 of file integrate.cpp.
References INTEG_METHOD_NVT, and mpi_set_integ_switch().
integrate_set_sd()
void integrate_set_sd ()
Set the Stokesian Dynamics integrator.
Definition at line 513 of file integrate.cpp.
References box_geo, INTEG_METHOD_SD, mpi_set_integ_switch(), and BoxGeometry::periodic().
integrate_set_steepest_descent()
void integrate_set_steepest_descent (const double f_max, const double gamma, const double max_displacement)
Set the steepest descent integrator for energy minimization.
Definition at line 503 of file integrate.cpp.
References Utils::gamma(), INTEG_METHOD_STEEPEST_DESCENT, mpi_set_integ_switch(), and steepest_descent_init().
integrator_sanity_checks()
void integrator_sanity_checks ()
Check integrator parameters and incompatibilities between the integrator and the currently active thermostat(s).
Definition at line 146 of file integrate.cpp.
References box_geo, INTEG_METHOD_BD, INTEG_METHOD_NPT_ISO, INTEG_METHOD_NVT, INTEG_METHOD_SD, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, LEES_EDWARDS, runtimeErrorMsg, THERMO_BROWNIAN, THERMO_NPT_ISO, THERMO_OFF, THERMO_SD, thermo_switch, time_step, and BoxGeometry::type().
Referenced by on_integration_start().
integrator_step_1()
static bool integrator_step_1 (ParticleRange const & particles) static
Calls the hook for propagation kernels before the force calculation.
Returns
whether or not to stop the integration loop early.
Definition at line 195 of file integrate.cpp.
References INTEG_METHOD_BD, INTEG_METHOD_NPT_ISO, INTEG_METHOD_NVT, INTEG_METHOD_SD, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, Cells::particles(), steepest_descent_step(), stokesian_dynamics_step_1(), time_step, velocity_verlet_npt_step_1(), and velocity_verlet_step_1().
Referenced by integrate().
integrator_step_2()
static void integrator_step_2 (ParticleRange const & particles, double kT) static
Calls the hook of the propagation kernels after force calculation.
Definition at line 225 of file integrate.cpp.
References brownian, brownian_dynamics_propagator(), INTEG_METHOD_BD, INTEG_METHOD_NPT_ISO, INTEG_METHOD_NVT, INTEG_METHOD_SD, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, Cells::particles(), resort_particles_if_needed(), time_step, velocity_verlet_npt_step_2(), and velocity_verlet_step_2().
Referenced by integrate().
interaction_range()
double interaction_range ()
Definition at line 530 of file integrate.cpp.
References INACTIVE_CUTOFF, maximal_cutoff(), n_nodes, and skin.
Referenced by cells_re_init(), ScriptInterface::CellSystem::CellSystem::CellSystem(), and force_calc().
mpi_integrate()
int mpi_integrate (int n_steps, int reuse_forces)
Start integrator.
Parameters
n_steps how many steps to do.
reuse_forces whether to trust the old forces for the first half step
Returns
nonzero on error
Definition at line 498 of file integrate.cpp.
References mpi_call(), mpi_integrate_local(), and Communication::Result::reduction.
Referenced by python_integrate(), and time_calc().
mpi_integrate_local()
static int mpi_integrate_local (int n_steps, int reuse_forces) static
Definition at line 490 of file integrate.cpp.
References check_runtime_errors_local(), and integrate().
Referenced by mpi_integrate().
mpi_set_integ_switch()
void mpi_set_integ_switch (int integ_switch)
Definition at line 585 of file integrate.cpp.
References integ_switch, mpi_call_all(), and mpi_set_integ_switch_local().
Referenced by integrate_set_bd(), integrate_set_npt_isotropic(), integrate_set_nvt(), integrate_set_sd(), and integrate_set_steepest_descent().
mpi_set_integ_switch_local()
void mpi_set_integ_switch_local (int integ_switch)
Definition at line 579 of file integrate.cpp.
References integ_switch.
Referenced by mpi_set_integ_switch().
mpi_set_skin()
void mpi_set_skin (double skin)
Set and broadcast the skin.
Parameters
skin skin value
Definition at line 567 of file integrate.cpp.
References mpi_call_all(), mpi_set_skin_local(), and skin.
Referenced by python_integrate(), EspressoSystemStandAlone::set_skin(), and tune_skin().
mpi_set_skin_local()
void mpi_set_skin_local (double skin)
Definition at line 559 of file integrate.cpp.
References on_skin_change(), skin, and skin_set.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and mpi_set_skin().
mpi_set_time()
void mpi_set_time (double time)
Set and broadcast the time.
Parameters
time time
Definition at line 577 of file integrate.cpp.
References mpi_call_all(), and mpi_set_time_local().
mpi_set_time_local()
void mpi_set_time_local (double time)
Definition at line 569 of file integrate.cpp.
References recalc_forces, sim_time, and LeesEdwards::update_box_params().
Referenced by mpi_set_time().
mpi_set_time_step()
void mpi_set_time_step (double time_s)
Send new time_step and rescale the velocities accordingly.
Definition at line 551 of file integrate.cpp.
References check_tau_time_step_consistency(), lb_lbfluid_get_lattice_switch(), lb_lbfluid_get_tau(), mpi_call_all(), mpi_set_time_step_local(), and NONE.
Referenced by EspressoSystemStandAlone::set_time_step().
mpi_set_time_step_local()
void mpi_set_time_step_local (double dt)
Definition at line 544 of file integrate.cpp.
References on_timestep_change(), and time_step.
Referenced by mpi_set_time_step().
mpi_steepest_descent()
int mpi_steepest_descent (int steps)
Steepest descent main integration loop.
Integration stops when the maximal force is lower than the user limit f_max or when the maximal number of steps steps is reached.
Parameters
steps Maximal number of integration steps
Returns
number of integrated steps
Definition at line 485 of file integrate.cpp.
References Communication::Result::main_rank, mpi_call(), and mpi_steepest_descent_local().
mpi_steepest_descent_local()
static int mpi_steepest_descent_local (int steps) static
Definition at line 479 of file integrate.cpp.
References integrate().
Referenced by mpi_steepest_descent().
python_integrate()
int python_integrate (int n_steps, bool recalc_forces, bool reuse_forces)
Run the integration loop.
Can be interrupted with Ctrl+C.
Parameters
n_steps Number of integration steps, can be zero
recalc_forces Whether to recalculate forces
reuse_forces Whether to re-use forces
Return values
ES_OK on success
ES_ERROR on error
Definition at line 421 of file integrate.cpp.
References Accumulators::auto_update(), Accumulators::auto_update_next_update(), cell_structure, anonymous_namespace{integrate.cpp}::ctrl_C, ES_ERROR, ES_OK, CellStructure::max_cutoff(), maximal_cutoff(), anonymous_namespace{Correlator.cpp}::min(), mpi_integrate(), mpi_set_skin(), n_nodes, runtimeErrorMsg, and skin_set.
resort_particles_if_needed()
static void resort_particles_if_needed (ParticleRange const & particles) static
Definition at line 184 of file integrate.cpp.
References box_geo, cell_structure, CellStructure::check_resort_required(), CellStructure::get_le_pos_offset_at_last_resort(), Cells::particles(), Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), skin, and LeesEdwards::verlet_list_offset().
Referenced by integrate(), and integrator_step_2().
Variable Documentation
fluid_step
int fluid_step = 0 static
Definition at line 93 of file integrate.cpp.
Referenced by integrate().
integ_switch
int integ_switch = INTEG_METHOD_NVT
Switch determining which integrator to use.
Definition at line 75 of file integrate.cpp.
Referenced by integrate(), integrator_npt_sanity_checks(), integrator_sanity_checks(), integrator_step_1(), integrator_step_2(), mpi_set_integ_switch(), mpi_set_integ_switch_local(), npt_add_virial_contribution(), npt_ensemble_init(), npt_reset_instantaneous_virials(), on_periodicity_change(), ICCStar::sanity_check(), and velocity_verlet_npt_propagate_vel().
recalc_forces
bool recalc_forces = true
If true, the forces will be recalculated before the next integration.
Definition at line 88 of file integrate.cpp.
Referenced by force_calc(), integrate(), mpi_set_time_local(), npt_ensemble_init(), on_constraint_change(), on_forcecap_change(), on_integration_start(), on_lbboundary_change(), on_particle_change(), on_short_range_ia_change(), LeesEdwards::set_protocol(), set_virtual_sites(), and LeesEdwards::unset_protocol().
set_py_interrupt
bool set_py_interrupt = false
Communicate signal handling to the Python interpreter.
Definition at line 95 of file integrate.cpp.
Referenced by anonymous_namespace{integrate.cpp}::notify_sig_int().
sim_time
double sim_time = 0.0 static
Actual simulation time.
Definition at line 81 of file integrate.cpp.
Referenced by get_sim_time(), increment_sim_time(), mpi_set_time_local(), and LeesEdwards::update_box_params().
skin
double skin = 0.0
Verlet list skin.
Definition at line 83 of file integrate.cpp.
Referenced by P3MLocalMesh::calc_local_ca_mesh(), ScriptInterface::CellSystem::CellSystem::CellSystem(), check_resort_particles(), TuningAlgorithm::determine_r_cut_limits(), force_calc(), TuningAlgorithm::get_mc_time(), IBM_UpdateParticlePositions(), CoulombP3M::init(), DipolarP3M::init(), interaction_range(), mpi_set_skin(), mpi_set_skin_local(), resort_particles_if_needed(), and VirtualSitesRelative::update().
skin_set
bool skin_set = false static
True iff the user has changed the skin setting.
Definition at line 86 of file integrate.cpp.
Referenced by mpi_set_skin_local(), and python_integrate().
time_step
double time_step = -1.0 static
Time step for the integration.
Definition at line 78 of file integrate.cpp.
Referenced by anonymous_namespace{lb_particle_coupling.cpp}::add_md_force(), add_swimmer_force(), brownian_dynamics_propagator(), calc_fluid_particle_ia(), calc_viscous_force(), check_tau_time_step_consistency(), convert_torques_propagate_omega(), dpd_init(), ek_add_fluctuations_to_flux(), ek_init(), force_calc(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), get_time_step(), IBM_UpdateParticlePositions(), init_forces(), init_real_particle_force(), integrate(), integrator_sanity_checks(), integrator_step_1(), integrator_step_2(), lb_calc_particle_lattice_ia_gpu(), lb_lbcoupling_calc_particle_lattice_ia(), lb_lbfluid_sanity_checks(), mpi_set_time_step_local(), on_integration_start(), propagate_omega_quat_particle(), propagate_vel_pos_sd(), LeesEdwards::Push::Push(), LangevinThermostat::recalc_prefactors(), IsotropicNptThermostat::recalc_prefactors(), LeesEdwards::run_kernel(), EspressoSystemStandAlone::set_time_step(), LangevinThermostat::sigma(), IsotropicNptThermostat::sigma(), stokesian_dynamics_propagate_vel_pos(), stokesian_dynamics_step_1(), thermalized_bond_init(), thermo_init(), thermostat_force(), velocity_verlet_npt_finalize_p_inst(), velocity_verlet_npt_propagate_pos(), velocity_verlet_npt_propagate_vel(), velocity_verlet_npt_propagate_vel_final(), velocity_verlet_npt_step_1(), velocity_verlet_npt_step_2(), velocity_verlet_propagate_vel_final(), velocity_verlet_propagate_vel_pos(), velocity_verlet_step_1(), and velocity_verlet_step_2().
verlet_reuse
double verlet_reuse = 0.0 static
Average number of integration steps the Verlet list has been re-using.
Definition at line 91 of file integrate.cpp.
Referenced by get_verlet_reuse(), and integrate().