ESPResSo: brownian_inline.hpp File Reference
brownian_inline.hpp File Reference
#include "config/config.hpp"
#include "rotation.hpp"
#include "thermostat.hpp"
#include "thermostats/brownian_inline.hpp"
Functions
void brownian_dynamics_propagator (BrownianThermostat const &brownian, Particle &p, double time_step, double kT)
void brownian_dynamics_rotator (BrownianThermostat const &brownian, Particle &p, double time_step, double kT)
Function Documentation
brownian_dynamics_propagator()
void brownian_dynamics_propagator (BrownianThermostat const & brownian, Particle & p, double time_step, double kT) inline
Definition at line 30 of file integrators/brownian_inline.hpp.
References bd_drag(), bd_drag_vel(), bd_random_walk(), bd_random_walk_vel(), BrownianThermostat::gamma, Particle::pos(), and Particle::v().
Referenced by integrator_step_1().
brownian_dynamics_rotator()
void brownian_dynamics_rotator (BrownianThermostat const & brownian, Particle & p, double time_step, double kT) inline
Definition at line 40 of file integrators/brownian_inline.hpp.
References bd_drag_rot(), bd_drag_vel_rot(), bd_random_walk_rot(), bd_random_walk_vel_rot(), Particle::can_rotate(), convert_torque_to_body_frame_apply_fix(), BrownianThermostat::gamma_rotation, Particle::omega(), and Particle::quat().
Referenced by integrator_step_1().