ESPResSo: interactions.cpp File Reference
interactions.cpp File Reference
#include "communication.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "collision.hpp"
#include "electrostatics/coulomb.hpp"
#include "errorhandling.hpp"
#include "event.hpp"
#include "magnetostatics/dipoles.hpp"
#include "serialization/IA_parameters.hpp"
#include <boost/mpi/collectives/broadcast.hpp>
#include <algorithm>
Functions
static double recalc_long_range_cutoff ()
double maximal_cutoff (bool single_node)
Calculate the maximal cutoff of all interactions.
bool long_range_interactions_sanity_checks ()
Check electrostatic and magnetostatic methods are properly initialized.
void mpi_bcast_ia_params_local (int i, int j)
void mpi_bcast_ia_params (int i, int j)
Send new IA params.
Function Documentation
long_range_interactions_sanity_checks()
bool long_range_interactions_sanity_checks ()
Check electrostatic and magnetostatic methods are properly initialized.
Returns
true if sanity checks failed.
Definition at line 66 of file interactions.cpp.
References runtimeErrorMsg, Dipoles::sanity_checks(), and Coulomb::sanity_checks().
Referenced by calculate_energy_local(), calculate_pressure_local(), and on_integration_start().
maximal_cutoff()
double maximal_cutoff (bool single_node)
Calculate the maximal cutoff of all interactions.
Definition at line 49 of file interactions.cpp.
References collision_detection_cutoff(), get_min_global_cut(), maximal_cutoff_bonded(), maximal_cutoff_nonbonded(), and recalc_long_range_cutoff().
Referenced by force_calc(), interaction_range(), python_integrate(), and tune_skin().
mpi_bcast_ia_params()
void mpi_bcast_ia_params (int i, int j)
Send new IA params.
Also calls on_short_range_ia_change.
Used for both bonded and non-bonded interaction parameters. Therefore i and j are used depending on their value:
Parameters
i particle type for non-bonded interaction parameters / bonded interaction type number.
j if not negative: particle type for non-bonded interaction parameters / if negative: flag for bonded interaction
Definition at line 88 of file interactions.cpp.
References mpi_bcast_ia_params_local(), and mpi_call_all().
Referenced by BMHTF_set_params(), buckingham_set_params(), dpd_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), lennard_jones_set_params(), ljcos2_set_params(), ljcos_set_params(), ljgen_set_params(), morse_set_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), thole_set_params(), and wca_set_params().
mpi_bcast_ia_params_local()
void mpi_bcast_ia_params_local (int i, int j)
Definition at line 81 of file interactions.cpp.
References comm_cart, get_ia_param(), and on_short_range_ia_change().
Referenced by mpi_bcast_ia_params().
recalc_long_range_cutoff()
static double recalc_long_range_cutoff () static
Definition at line 36 of file interactions.cpp.
References Dipoles::cutoff(), Coulomb::cutoff(), and INACTIVE_CUTOFF.
Referenced by maximal_cutoff().