ESPResSo: integrate.hpp File Reference
integrate.hpp File Reference
Macros
Integrator switches
#define INTEG_METHOD_NPT_ISO 0
#define INTEG_METHOD_NVT 1
#define INTEG_METHOD_STEEPEST_DESCENT 2
#define INTEG_METHOD_BD 3
#define INTEG_METHOD_SD 7
Functions
double interaction_range ()
void integrator_sanity_checks ()
Check integrator parameters and incompatibilities between the integrator and the currently active thermostat(s).
int integrate (int n_steps, int reuse_forces)
Integrate equations of motion.
int python_integrate (int n_steps, bool recalc_forces, bool reuse_forces)
Run the integration loop.
int mpi_integrate (int n_steps, int reuse_forces)
Start integrator.
int mpi_steepest_descent (int steps)
Steepest descent main integration loop.
void integrate_set_steepest_descent (double f_max, double gamma, double max_displacement)
Set the steepest descent integrator for energy minimization.
void integrate_set_nvt ()
Set the velocity Verlet integrator for the NVT ensemble.
void integrate_set_bd ()
Set the Brownian Dynamics integrator.
void integrate_set_sd ()
Set the Stokesian Dynamics integrator.
void integrate_set_npt_isotropic (double ext_pressure, double piston, bool xdir_rescale, bool ydir_rescale, bool zdir_rescale, bool cubic_box)
Set the velocity Verlet integrator modified for the NpT ensemble with isotropic rescaling.
double get_verlet_reuse ()
Get verlet_reuse.
double get_time_step ()
Get time step.
double get_sim_time ()
Get simulation time.
void increment_sim_time (double amount)
Increase simulation time (only on head node)
void mpi_set_time_step (double time_step)
Send new time_step and rescale the velocities accordingly.
void mpi_set_skin (double skin)
Set and broadcast the skin.
void mpi_set_skin_local (double skin)
void mpi_set_time (double time)
Set and broadcast the time.
void mpi_set_integ_switch (int integ_switch)
Variables
int integ_switch
Switch determining which integrator to use.
double skin
Verlet list skin.
bool recalc_forces
If true, the forces will be recalculated before the next integration.
bool set_py_interrupt
Communicate signal handling to the Python interpreter.
Detailed Description
Molecular dynamics integrator.
Implementation in integrate.cpp.
Definition in file integrate.hpp.
Macro Definition Documentation
INTEG_METHOD_BD
#define INTEG_METHOD_BD 3
Definition at line 35 of file integrate.hpp.
INTEG_METHOD_NPT_ISO
#define INTEG_METHOD_NPT_ISO 0
Definition at line 32 of file integrate.hpp.
INTEG_METHOD_NVT
#define INTEG_METHOD_NVT 1
Definition at line 33 of file integrate.hpp.
INTEG_METHOD_SD
#define INTEG_METHOD_SD 7
Definition at line 36 of file integrate.hpp.
INTEG_METHOD_STEEPEST_DESCENT
#define INTEG_METHOD_STEEPEST_DESCENT 2
Definition at line 34 of file integrate.hpp.
Function Documentation
get_sim_time()
double get_sim_time ()
Get simulation time.
Definition at line 540 of file integrate.cpp.
References sim_time.
Referenced by force_calc().
get_time_step()
double get_time_step ()
Get time step.
Definition at line 538 of file integrate.cpp.
References time_step.
Referenced by ek_init(), and lb_reinit_parameters_gpu().
get_verlet_reuse()
double get_verlet_reuse ()
Get verlet_reuse.
Definition at line 536 of file integrate.cpp.
References verlet_reuse.
Referenced by ScriptInterface::CellSystem::CellSystem::do_call_method().
increment_sim_time()
void increment_sim_time (double amount)
Increase simulation time (only on head node)
Definition at line 542 of file integrate.cpp.
References sim_time.
Referenced by brownian_dynamics_propagator(), stokesian_dynamics_step_1(), velocity_verlet_npt_step_1(), and velocity_verlet_step_1().
integrate()
int integrate (int n_steps, int reuse_forces)
Integrate equations of motion.
Parameters
n_steps Number of integration steps, can be zero
reuse_forces Decide when to re-calculate forces:
-1: recalculate forces unconditionally (mostly used for timing)
0: recalculate forces if recalc_forces is set, meaning it is probably necessary
1: do not recalculate forces (mostly when reading checkpoints with forces)
This function calls two hooks for propagation kernels such as velocity verlet, velocity verlet + npt box changes, and steepest_descent. One hook is called before and one after the force calculation. It is up to the propagation kernels to increment the simulation time.
This function propagates the system according to the choice of integrator stored in integ_switch. The general structure is:
if reuse_forces is zero, recalculate the forces based on the current state of the system
Loop over the number of simulation steps:
initialization (e.g., RATTLE)
First hook for propagation kernels
Update dependent particles and properties (RATTLE, virtual sites)
Calculate forces for the current state of the system. This includes forces added by the Langevin thermostat and the Lattice-Boltzmann-particle coupling
Second hook for propagation kernels
Update dependent properties (Virtual sites, RATTLE)
Run single step algorithms (Lattice-Boltzmann propagation, collision detection, NpT update)
Final update of dependent properties and statistics/counters
High-level documentation of the integration and thermostatting schemes can be found in doc/sphinx/system_setup.rst and /doc/sphinx/running.rst
Returns
number of steps that have been integrated
Definition at line 253 of file integrate.cpp.
References cell_structure, cells_update_ghosts(), check_runtime_errors(), comm_cart, convert_initial_torques(), correct_position_shake(), correct_velocity_shake(), anonymous_namespace{integrate.cpp}::ctrl_C, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, ESPRESSO_PROFILER_CXX_MARK_LOOP_BEGIN, ESPRESSO_PROFILER_CXX_MARK_LOOP_END, ESPRESSO_PROFILER_CXX_MARK_LOOP_ITERATION, ESPRESSO_PROFILER_MARK_BEGIN, ESPRESSO_PROFILER_MARK_END, fluid_step, force_calc(), CellStructure::get_resort_particles(), CellStructure::ghost_particles(), global_ghost_flags(), handle_collisions(), INTEG_METHOD_NPT_ISO, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, integrator_step_1(), integrator_step_2(), lb_lbcoupling_activate(), lb_lbcoupling_deactivate(), lb_lbcoupling_propagate(), lb_lbfluid_get_lattice_switch(), lb_lbfluid_get_tau(), lb_lbfluid_propagate(), CellStructure::local_particles(), n_rigidbonds, NONE, anonymous_namespace{integrate.cpp}::notify_sig_int(), on_integration_start(), Cells::particles(), philox_counter_increment(), BondBreakage::process_queue(), recalc_forces, Cells::RESORT_LOCAL, resort_particles_if_needed(), save_old_position(), synchronize_npt_state(), temperature, time_step, LeesEdwards::update_box_params(), verlet_reuse, and virtual_sites().
Referenced by mpi_integrate_local(), and mpi_steepest_descent_local().
integrate_set_bd()
void integrate_set_bd ()
Set the Brownian Dynamics integrator.
Definition at line 511 of file integrate.cpp.
References INTEG_METHOD_BD, and mpi_set_integ_switch().
integrate_set_npt_isotropic()
void integrate_set_npt_isotropic (double ext_pressure, double piston, bool xdir_rescale, bool ydir_rescale, bool zdir_rescale, bool cubic_box)
Set the velocity Verlet integrator modified for the NpT ensemble with isotropic rescaling.
Parameters
ext_pressure Reference pressure
piston Piston mass
xdir_rescale Enable box rescaling in the x-direction
ydir_rescale Enable box rescaling in the y-direction
zdir_rescale Enable box rescaling in the z-direction
cubic_box Determines if the volume fluctuations should also apply to dimensions which are switched off by the above flags and which do not contribute to the pressure (3D) or tension (2D, 1D)
Definition at line 521 of file integrate.cpp.
References INTEG_METHOD_NPT_ISO, mpi_set_integ_switch(), and nptiso_init().
integrate_set_nvt()
void integrate_set_nvt ()
Set the velocity Verlet integrator for the NVT ensemble.
Definition at line 509 of file integrate.cpp.
References INTEG_METHOD_NVT, and mpi_set_integ_switch().
integrate_set_sd()
void integrate_set_sd ()
Set the Stokesian Dynamics integrator.
Definition at line 513 of file integrate.cpp.
References box_geo, INTEG_METHOD_SD, mpi_set_integ_switch(), and BoxGeometry::periodic().
integrate_set_steepest_descent()
void integrate_set_steepest_descent (double f_max, double gamma, double max_displacement)
Set the steepest descent integrator for energy minimization.
Definition at line 503 of file integrate.cpp.
References Utils::gamma(), INTEG_METHOD_STEEPEST_DESCENT, mpi_set_integ_switch(), and steepest_descent_init().
integrator_sanity_checks()
void integrator_sanity_checks ()
Check integrator parameters and incompatibilities between the integrator and the currently active thermostat(s).
Definition at line 146 of file integrate.cpp.
References box_geo, INTEG_METHOD_BD, INTEG_METHOD_NPT_ISO, INTEG_METHOD_NVT, INTEG_METHOD_SD, INTEG_METHOD_STEEPEST_DESCENT, integ_switch, LEES_EDWARDS, runtimeErrorMsg, THERMO_BROWNIAN, THERMO_NPT_ISO, THERMO_OFF, THERMO_SD, thermo_switch, time_step, and BoxGeometry::type().
Referenced by on_integration_start().
interaction_range()
double interaction_range ()
Definition at line 530 of file integrate.cpp.
References INACTIVE_CUTOFF, maximal_cutoff(), n_nodes, and skin.
Referenced by cells_re_init(), ScriptInterface::CellSystem::CellSystem::CellSystem(), and force_calc().
mpi_integrate()
int mpi_integrate (int n_steps, int reuse_forces)
Start integrator.
Parameters
n_steps how many steps to do.
reuse_forces whether to trust the old forces for the first half step
Returns
nonzero on error
Definition at line 498 of file integrate.cpp.
References mpi_call(), mpi_integrate_local(), and Communication::Result::reduction.
Referenced by python_integrate(), and time_calc().
mpi_set_integ_switch()
void mpi_set_integ_switch (int integ_switch)
Definition at line 585 of file integrate.cpp.
References integ_switch, mpi_call_all(), and mpi_set_integ_switch_local().
Referenced by integrate_set_bd(), integrate_set_npt_isotropic(), integrate_set_nvt(), integrate_set_sd(), and integrate_set_steepest_descent().
mpi_set_skin()
void mpi_set_skin (double skin)
Set and broadcast the skin.
Parameters
skin skin value
Definition at line 567 of file integrate.cpp.
References mpi_call_all(), mpi_set_skin_local(), and skin.
Referenced by python_integrate(), EspressoSystemStandAlone::set_skin(), and tune_skin().
mpi_set_skin_local()
void mpi_set_skin_local (double skin)
Definition at line 559 of file integrate.cpp.
References on_skin_change(), skin, and skin_set.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and mpi_set_skin().
mpi_set_time()
void mpi_set_time (double time)
Set and broadcast the time.
Parameters
time time
Definition at line 577 of file integrate.cpp.
References mpi_call_all(), and mpi_set_time_local().
mpi_set_time_step()
void mpi_set_time_step (double time_step)
Send new time_step and rescale the velocities accordingly.
Definition at line 551 of file integrate.cpp.
References check_tau_time_step_consistency(), lb_lbfluid_get_lattice_switch(), lb_lbfluid_get_tau(), mpi_call_all(), mpi_set_time_step_local(), and NONE.
Referenced by EspressoSystemStandAlone::set_time_step().
mpi_steepest_descent()
int mpi_steepest_descent (int steps)
Steepest descent main integration loop.
Integration stops when the maximal force is lower than the user limit f_max or when the maximal number of steps steps is reached.
Parameters
steps Maximal number of integration steps
Returns
number of integrated steps
Definition at line 485 of file integrate.cpp.
References Communication::Result::main_rank, mpi_call(), and mpi_steepest_descent_local().
python_integrate()
int python_integrate (int n_steps, bool recalc_forces, bool reuse_forces)
Run the integration loop.
Can be interrupted with Ctrl+C.
Parameters
n_steps Number of integration steps, can be zero
recalc_forces Whether to recalculate forces
reuse_forces Whether to re-use forces
Return values
ES_OK on success
ES_ERROR on error
Definition at line 421 of file integrate.cpp.
References Accumulators::auto_update(), Accumulators::auto_update_next_update(), cell_structure, anonymous_namespace{integrate.cpp}::ctrl_C, ES_ERROR, ES_OK, CellStructure::max_cutoff(), maximal_cutoff(), anonymous_namespace{Correlator.cpp}::min(), mpi_integrate(), mpi_set_skin(), n_nodes, runtimeErrorMsg, and skin_set.
Variable Documentation
integ_switch
int integ_switch
Switch determining which integrator to use.
Definition at line 75 of file integrate.cpp.
Referenced by integrate(), integrator_npt_sanity_checks(), integrator_sanity_checks(), integrator_step_1(), integrator_step_2(), mpi_set_integ_switch(), mpi_set_integ_switch_local(), npt_add_virial_contribution(), npt_ensemble_init(), npt_reset_instantaneous_virials(), on_periodicity_change(), ICCStar::sanity_check(), and velocity_verlet_npt_propagate_vel().
recalc_forces
bool recalc_forces
If true, the forces will be recalculated before the next integration.
Definition at line 88 of file integrate.cpp.
Referenced by force_calc(), integrate(), mpi_set_time_local(), npt_ensemble_init(), on_constraint_change(), on_forcecap_change(), on_integration_start(), on_lbboundary_change(), on_particle_change(), on_short_range_ia_change(), LeesEdwards::set_protocol(), set_virtual_sites(), and LeesEdwards::unset_protocol().
set_py_interrupt
bool set_py_interrupt
Communicate signal handling to the Python interpreter.
Definition at line 95 of file integrate.cpp.
Referenced by anonymous_namespace{integrate.cpp}::notify_sig_int().
skin
double skin
Verlet list skin.
Definition at line 83 of file integrate.cpp.
Referenced by P3MLocalMesh::calc_local_ca_mesh(), ScriptInterface::CellSystem::CellSystem::CellSystem(), check_resort_particles(), TuningAlgorithm::determine_r_cut_limits(), force_calc(), TuningAlgorithm::get_mc_time(), IBM_UpdateParticlePositions(), CoulombP3M::init(), DipolarP3M::init(), interaction_range(), mpi_set_skin(), mpi_set_skin_local(), resort_particles_if_needed(), and VirtualSitesRelative::update().