ESPResSo: philox_rand.h File Reference
philox_rand.h File Reference
Philox counter-based RNG from [39].
#include "myintrin.h"
#include <cstdint>
Macros
#define SVE_QUALIFIERS
#define QUALIFIERS inline
#define PHILOX_W32_0 (0x9E3779B9)
#define PHILOX_W32_1 (0xBB67AE85)
#define PHILOX_M4x32_0 (0xD2511F53)
#define PHILOX_M4x32_1 (0xCD9E8D57)
#define TWOPOW53_INV_DOUBLE (1.1102230246251565e-16)
#define TWOPOW32_INV_FLOAT (2.3283064e-10f)
Typedefs
typedef std::uint32_t uint32
typedef std::uint64_t uint64
Functions
QUALIFIERS uint32 mulhilo32 (uint32 a, uint32 b, uint32 *hip)
QUALIFIERS void _philox4x32round (uint32 *ctr, uint32 *key)
QUALIFIERS void _philox4x32bumpkey (uint32 *key)
QUALIFIERS double _uniform_double_hq (uint32 x, uint32 y)
QUALIFIERS void philox_double2 (uint32 ctr0, uint32 ctr1, uint32 ctr2, uint32 ctr3, uint32 key0, uint32 key1, double &rnd1, double &rnd2)
QUALIFIERS void philox_float4 (uint32 ctr0, uint32 ctr1, uint32 ctr2, uint32 ctr3, uint32 key0, uint32 key1, float &rnd1, float &rnd2, float &rnd3, float &rnd4)
Detailed Description
Philox counter-based RNG from [39].
Adapted from the pystencils source file https://i10git.cs.fau.de/pycodegen/pystencils/-/blob/b4d7ef7cb5b499f3fa55ebfcd598ac7d6e11a3db/src/pystencils/include/philox_rand.h
Definition in file lattice_boltzmann/generated_kernels/philox_rand.h.
Macro Definition Documentation
PHILOX_M4x32_0
#define PHILOX_M4x32_0 (0xD2511F53)
Definition at line 107 of file lattice_boltzmann/generated_kernels/philox_rand.h.
PHILOX_M4x32_1
#define PHILOX_M4x32_1 (0xCD9E8D57)
Definition at line 108 of file lattice_boltzmann/generated_kernels/philox_rand.h.
PHILOX_W32_0
#define PHILOX_W32_0 (0x9E3779B9)
Definition at line 105 of file lattice_boltzmann/generated_kernels/philox_rand.h.
PHILOX_W32_1
#define PHILOX_W32_1 (0xBB67AE85)
Definition at line 106 of file lattice_boltzmann/generated_kernels/philox_rand.h.
QUALIFIERS
#define QUALIFIERS inline
Definition at line 101 of file lattice_boltzmann/generated_kernels/philox_rand.h.
SVE_QUALIFIERS
#define SVE_QUALIFIERS
Definition at line 92 of file lattice_boltzmann/generated_kernels/philox_rand.h.
TWOPOW32_INV_FLOAT
#define TWOPOW32_INV_FLOAT (2.3283064e-10f)
Definition at line 110 of file lattice_boltzmann/generated_kernels/philox_rand.h.
TWOPOW53_INV_DOUBLE
#define TWOPOW53_INV_DOUBLE (1.1102230246251565e-16)
Definition at line 109 of file lattice_boltzmann/generated_kernels/philox_rand.h.
Typedef Documentation
uint32
typedef std::uint32_t uint32
Definition at line 120 of file lattice_boltzmann/generated_kernels/philox_rand.h.
uint64
typedef std::uint64_t uint64
Definition at line 121 of file lattice_boltzmann/generated_kernels/philox_rand.h.
Function Documentation
_philox4x32bumpkey()
QUALIFIERS void _philox4x32bumpkey (uint32 * key)
Definition at line 169 of file lattice_boltzmann/generated_kernels/philox_rand.h.
References PHILOX_W32_0, PHILOX_W32_1, and stream.
Referenced by philox_double2(), and philox_float4().
_philox4x32round()
QUALIFIERS void _philox4x32round (uint32 * ctr, uint32 * key)
Definition at line 157 of file lattice_boltzmann/generated_kernels/philox_rand.h.
References mulhilo32(), PHILOX_M4x32_0, PHILOX_M4x32_1, and stream.
Referenced by philox_double2(), and philox_float4().
_uniform_double_hq()
QUALIFIERS double _uniform_double_hq (uint32 x, uint32 y)
Definition at line 174 of file lattice_boltzmann/generated_kernels/philox_rand.h.
References TWOPOW53_INV_DOUBLE.
Referenced by philox_double2().
mulhilo32()
QUALIFIERS uint32 mulhilo32 (uint32 a, uint32 b, uint32 * hip)
Definition at line 135 of file lattice_boltzmann/generated_kernels/philox_rand.h.
References stream.
Referenced by _philox4x32round().
philox_double2()
QUALIFIERS void philox_double2 (uint32 ctr0, uint32 ctr1, uint32 ctr2, uint32 ctr3, uint32 key0, uint32 key1, double & rnd1, double & rnd2)
Definition at line 179 of file lattice_boltzmann/generated_kernels/philox_rand.h.
References _philox4x32bumpkey(), _philox4x32round(), _uniform_double_hq(), and stream.
philox_float4()
QUALIFIERS void philox_float4 (uint32 ctr0, uint32 ctr1, uint32 ctr2, uint32 ctr3, uint32 key0, uint32 key1, float & rnd1, float & rnd2, float & rnd3, float & rnd4)
Definition at line 218 of file lattice_boltzmann/generated_kernels/philox_rand.h.
References _philox4x32bumpkey(), _philox4x32round(), stream, and TWOPOW32_INV_FLOAT.