ESPResSo: lb.cpp File Reference
lb.cpp File Reference
#include "grid_based_algorithms/lb.hpp"
#include "cell_system/CellStructureType.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "grid_based_algorithms/lb_boundaries.hpp"
#include "halo.hpp"
#include "lb-d3q19.hpp"
#include "random.hpp"
#include <utils/Counter.hpp>
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/index.hpp>
#include <utils/math/matrix_vector_product.hpp>
#include <utils/math/sqr.hpp>
#include <utils/uniform.hpp>
#include <Random123/philox.h>
#include <boost/mpi/collectives/reduce.hpp>
#include <boost/multi_array.hpp>
#include <boost/optional.hpp>
#include <boost/range/algorithm.hpp>
#include <boost/range/numeric.hpp>
#include <profiler/profiler.hpp>
#include <mpi.h>
#include <algorithm>
#include <array>
#include <cassert>
#include <cinttypes>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <vector>
Namespaces
anonymous_namespace{lb.cpp}
Typedefs
using LB_FluidData = boost::multi_array< double, 2 >
Functions
void lb_on_param_change (LBParam param)
static void lb_check_halo_regions (const LB_Fluid &lb_fluid, const Lattice &lb_lattice)
Check consistency of the halo regions.
void lb_initialize_fields (std::vector< LB_FluidNode > &lb_fields, LB_Parameters const &lb_parameters, Lattice const &lb_lattice)
Initialize fluid nodes.
void lb_realloc_fluid (LB_FluidData &lb_fluid_a, LB_FluidData &lb_fluid_b, const Lattice::index_t halo_grid_volume, LB_Fluid &lb_fluid, LB_Fluid &lb_fluid_post)
(Re-)allocate memory for the fluid and initialize pointers.
void lb_set_equilibrium_populations (const Lattice &lb_lattice, const LB_Parameters &lb_parameters)
void lb_init (const LB_Parameters &lb_parameters)
void lb_reinit_fluid (std::vector< LB_FluidNode > &lb_fields, Lattice const &lb_lattice, LB_Parameters const &lb_parameters)
void lb_reinit_parameters (LB_Parameters &lb_parameters)
static void halo_push_communication (LB_Fluid &lb_fluid, const Lattice &lb_lattice)
Halo communication for push scheme.
void lb_sanity_checks (const LB_Parameters &lb_parameters)
Performs basic sanity checks.
uint64_t lb_fluid_get_rng_state ()
void mpi_set_lb_fluid_counter (uint64_t counter)
void lb_fluid_set_rng_state (uint64_t counter)
void lb_prepare_communication (HaloCommunicator &halo_comm, const Lattice &lb_lattice)
Set up the structures for exchange of the halo regions.
std::array< double, 19 > lb_calc_modes (Lattice::index_t index, const LB_Fluid &lb_fluid)
Calculation of hydrodynamic modes.
template<typename T >
std::array< T, 19 > lb_relax_modes (const std::array< T, 19 > &modes, const Utils::Vector< T, 3 > &force_density, const LB_Parameters &parameters)
template<typename T >
std::array< T, 19 > lb_thermalize_modes (Lattice::index_t index, const std::array< T, 19 > &modes, const LB_Parameters &lb_parameters, boost::optional< Utils::Counter< uint64_t >> const &rng_counter)
template<typename T >
std::array< T, 19 > lb_apply_forces (const std::array< T, 19 > &modes, const LB_Parameters &lb_parameters, Utils::Vector< T, 3 > const &f)
auto lb_next_offsets (const Lattice &lb_lattice, std::array< Utils::Vector3i, 19 > const &c)
Relative index for the next node for each lattice velocity.
template<typename T >
void lb_stream (LB_Fluid &lb_fluid, const std::array< T, 19 > &populations, std::size_t index, std::array< std::ptrdiff_t, 19 > const &offsets)
void lb_integrate ()
Integrate the lattice-Boltzmann system for one time step.
int compare_buffers (std::array< double, D3Q19::n_vel > const &buff_a, std::array< double, D3Q19::n_vel > const &buff_b)
void log_buffer_diff (std::ostream &out, int dir, Lattice::index_t index, int x, int y, int z)
double lb_calc_density (std::array< double, 19 > const &modes, const LB_Parameters &lb_parameters)
Utils::Vector3d lb_calc_momentum_density (std::array< double, 19 > const &modes, Utils::Vector3d const &force_density)
Utils::Vector6d lb_calc_pressure_tensor (std::array< double, 19 > const &modes, Utils::Vector3d const &force_density, const LB_Parameters &lb_parameters)
void lb_bounce_back (LB_Fluid &lb_fluid, const LB_Parameters &lb_parameters, const std::vector< LB_FluidNode > &lb_fields)
Bounce back boundary conditions.
Utils::Vector3d lb_calc_local_momentum_density (Lattice::index_t index, const LB_Fluid &lb_fluid)
Calculate the local fluid momentum.
void lb_calc_fluid_momentum (double *result, const LB_Parameters &lb_parameters, const std::vector< LB_FluidNode > &lb_fields, const Lattice &lb_lattice)
Calculate momentum of the LB fluid.
void lb_collect_boundary_forces (double *result)
Mapping between hydrodynamic fields and particle populations
template<typename T >
std::array< T, 19 > normalize_modes (const std::array< T, 19 > &modes)
template<typename T >
std::array< T, 19 > lb_calc_n_from_m (const std::array< T, 19 > &modes)
Transform modes to populations.
Utils::Vector19d lb_get_population_from_density_momentum_density_stress (double density, Utils::Vector3d const &momentum_density, Utils::Vector6d const &stress)
Get the populations as a function of density, flux density and stress.
void lb_set_population_from_density_momentum_density_stress (Lattice::index_t const index, double density, Utils::Vector3d const &momentum_density, Utils::Vector6d const &stress)
Sets the equilibrium distributions.
Variables
constexpr const std::array< std::array< int, 19 >, 19 > anonymous_namespace{lb.cpp}::e_ki
Basis of the mode space as described in [17].
constexpr const std::array< std::array< int, 19 >, 19 > anonymous_namespace{lb.cpp}::e_ki_transposed
Transposed version of e_ki.
boost::optional< Utils::Counter< uint64_t > > rng_counter_fluid
Counter for the RNG.
LB_Parameters lbpar
Lattice Boltzmann parameters.
Lattice lblattice
The underlying lattice.
static LB_FluidData lbfluid_a
static LB_FluidData lbfluid_b
LB_Fluid lbfluid
Span of the velocity populations of the fluid (pre-collision populations).
LB_Fluid lbfluid_post
Span of the velocity populations of the fluid (post-collision populations).
std::vector< LB_FluidNode > lbfields
Hydrodynamic fields of the fluid.
HaloCommunicator update_halo_comm = HaloCommunicator(0)
Communicator for halo exchange between processors.
Detailed Description
Lattice Boltzmann algorithm for hydrodynamic degrees of freedom.
Includes fluctuating LB and coupling to MD particles via frictional momentum transfer.
The corresponding header file is lb.hpp.
Definition in file lb.cpp.
Typedef Documentation
LB_FluidData
using LB_FluidData = boost::multi_array<double, 2>
Definition at line 179 of file lb.cpp.
Function Documentation
compare_buffers()
int compare_buffers (std::array< double, D3Q19::n_vel > const & buff_a, std::array< double, D3Q19::n_vel > const & buff_b)
Definition at line 978 of file lb.cpp.
References ES_ERROR, ES_OK, and runtimeErrorMsg.
Referenced by lb_check_halo_regions().
halo_push_communication()
static void halo_push_communication (LB_Fluid & lb_fluid, const Lattice & lb_lattice) static
Halo communication for push scheme.
Definition at line 334 of file lb.cpp.
References calc_node_neighbors(), comm_cart, Utils::get_linear_index(), Lattice::grid, Lattice::halo_grid, and REQ_HALO_SPREAD.
Referenced by lb_integrate().
lb_apply_forces()
template<typename T > std::array<T, 19> lb_apply_forces (const std::array< T, 19 > & modes, const LB_Parameters & lb_parameters, Utils::Vector< T, 3 > const & f)
Definition at line 838 of file lb.cpp.
References LB_Parameters::density, f, LB_Parameters::gamma_bulk, LB_Parameters::gamma_shear, and u.
Referenced by lb_integrate().
lb_bounce_back()
void lb_bounce_back (LB_Fluid & lbfluid, const LB_Parameters & lb_parameters, const std::vector< LB_FluidNode > & lb_fields)
Bounce back boundary conditions.
The populations that have propagated into a boundary node are bounced back to the node they came from. This results in no slip boundary conditions, cf. [31].
Definition at line 1253 of file lb.cpp.
References D3Q19::c, LB_Parameters::density, Utils::get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_next_offsets(), LBBoundaries::lbboundaries, lblattice, and D3Q19::w.
Referenced by lb_integrate().
lb_calc_density()
double lb_calc_density (std::array< double, 19 > const & modes, const LB_Parameters & lb_parameters)
Definition at line 1177 of file lb.cpp.
References LB_Parameters::density.
Referenced by lb_calc_pressure_tensor().
lb_calc_fluid_momentum()
void lb_calc_fluid_momentum (double * result, const LB_Parameters & lb_parameters, const std::vector< LB_FluidNode > & lb_fields, const Lattice & lb_lattice)
Calculate momentum of the LB fluid.
Parameters
[out] result Fluid momentum in MD units
[in] lb_parameters LB parameters
[in] lb_fields Hydrodynamic fields of the fluid
[in] lb_lattice The underlying lattice
Definition at line 1324 of file lb.cpp.
References LB_Parameters::agrid, comm_cart, Utils::get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_momentum_density(), lbfluid, momentum(), and LB_Parameters::tau.
Referenced by lb_lbfluid_calc_fluid_momentum(), and mpi_lb_lbfluid_calc_fluid_momentum_local().
lb_calc_local_momentum_density()
Utils::Vector3d lb_calc_local_momentum_density (Lattice::index_t index, const LB_Fluid & lb_fluid)
Calculate the local fluid momentum.
The calculation is implemented explicitly for the special case of D3Q19.
Parameters
[in] index Local lattice site
[in] lb_fluid Populations of the fluid
Return values
The local fluid momentum.
Definition at line 1302 of file lb.cpp.
Referenced by lb_calc_fluid_momentum().
lb_calc_modes()
std::array<double, 19> lb_calc_modes (Lattice::index_t index, const LB_Fluid & lb_fluid)
Calculation of hydrodynamic modes.
Parameters
[in] index Number of the node to calculate the modes for
[in] lb_fluid Populations of the fluid
Return values
Array containing the modes.
Definition at line 741 of file lb.cpp.
Referenced by GetIBMInterpolatedVelocity(), lb_integrate(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
lb_calc_momentum_density()
Utils::Vector3d lb_calc_momentum_density (std::array< double, 19 > const & modes, Utils::Vector3d const & force_density)
Definition at line 1182 of file lb.cpp.
Referenced by lb_calc_pressure_tensor().
lb_calc_n_from_m()
template<typename T > std::array<T, 19> lb_calc_n_from_m (const std::array< T, 19 > & modes)
Transform modes to populations.
Definition at line 713 of file lb.cpp.
References normalize_modes(), and D3Q19::w.
Referenced by lb_get_population_from_density_momentum_density_stress(), and lb_integrate().
lb_calc_pressure_tensor()
Utils::Vector6d lb_calc_pressure_tensor (std::array< double, 19 > const & modes, Utils::Vector3d const & force_density, const LB_Parameters & lb_parameters)
Definition at line 1189 of file lb.cpp.
References LB_Parameters::gamma_bulk, LB_Parameters::gamma_shear, lb_calc_density(), lb_calc_momentum_density(), and Utils::sqr().
lb_check_halo_regions()
void lb_check_halo_regions (const LB_Fluid & lb_fluid, const Lattice & lb_lattice) static
Check consistency of the halo regions.
Test whether the halo regions have been exchanged correctly.
Definition at line 1002 of file lb.cpp.
References box_geo, calc_node_neighbors(), comm_cart, compare_buffers(), Utils::get_linear_index(), Lattice::grid, Lattice::halo_grid, log_buffer_diff(), n_nodes, D3Q19::n_vel, BoxGeometry::periodic(), and REQ_HALO_CHECK.
Referenced by lb_integrate().
lb_collect_boundary_forces()
void lb_collect_boundary_forces (double * result)
Definition at line 1344 of file lb.cpp.
References comm_cart, and LBBoundaries::lbboundaries.
Referenced by LBBoundaries::lb_collect_boundary_forces_local(), and LBBoundaries::lbboundary_get_force().
lb_fluid_get_rng_state()
uint64_t lb_fluid_get_rng_state ()
Definition at line 626 of file lb.cpp.
References rng_counter_fluid.
Referenced by lb_lbfluid_get_rng_state().
lb_fluid_set_rng_state()
void lb_fluid_set_rng_state (uint64_t counter)
Definition at line 637 of file lb.cpp.
References mpi_call(), and mpi_set_lb_fluid_counter().
Referenced by lb_lbfluid_set_rng_state().
lb_get_population_from_density_momentum_density_stress()
Utils::Vector19d lb_get_population_from_density_momentum_density_stress (double density, Utils::Vector3d const & momentum_density, Utils::Vector6d const & stress)
Get the populations as a function of density, flux density and stress.
Parameters
density fluid density
momentum_density fluid flux density
stress fluid stress
Returns
19 populations (including equilibrium density contribution).
Definition at line 721 of file lb.cpp.
References lb_calc_n_from_m().
Referenced by lb_lbnode_set_density(), lb_lbnode_set_velocity(), and lb_set_population_from_density_momentum_density_stress().
lb_init()
void lb_init (const LB_Parameters & lb_parameters)
Definition at line 238 of file lb.cpp.
References LB_Parameters::agrid, box_geo, calc_node_pos(), check_runtime_errors(), comm_cart, Lattice::halo_grid_volume, LBBoundaries::lb_init_boundaries(), lb_initialize_fields(), lb_prepare_communication(), lb_realloc_fluid(), lb_reinit_parameters(), lb_set_equilibrium_populations(), lbfields, lbfluid, lbfluid_a, lbfluid_b, lbfluid_post, lblattice, lbpar, LocalBox< T >::length(), BoxGeometry::length(), local_geo, LocalBox< T >::my_right(), node_grid, runtimeErrorMsg, and update_halo_comm.
Referenced by lb_lbfluid_init(), and lb_on_param_change().
lb_initialize_fields()
void lb_initialize_fields (std::vector< LB_FluidNode > & lb_fields, LB_Parameters const & lb_parameters, Lattice const & lb_lattice)
Initialize fluid nodes.
Parameters
[out] lb_fields Vector containing the fluid nodes
[in] lb_parameters Parameters for the LB
[in] lb_lattice Lattice instance
Definition at line 200 of file lb.cpp.
References LB_Parameters::ext_force_density, and Lattice::halo_grid_volume.
Referenced by lb_init(), lb_on_param_change(), and lb_reinit_fluid().
lb_integrate()
void lb_integrate ()
Integrate the lattice-Boltzmann system for one time step.
This function performs the collision step and the streaming step. If external force densities are present, they are applied prior to the collisions. If boundaries are present, it also applies the boundary conditions.
Definition at line 901 of file lb.cpp.
References D3Q19::c, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, LB_Parameters::ext_force_density, Lattice::grid, halo_communication(), Lattice::halo_grid, Lattice::halo_offset, halo_push_communication(), lb_apply_forces(), lb_bounce_back(), lb_calc_modes(), lb_calc_n_from_m(), lb_check_halo_regions(), lb_next_offsets(), lb_relax_modes(), lb_stream(), lb_thermalize_modes(), LBBoundaries::lbboundaries, lbfields, lbfluid, lbfluid_post, lblattice, lbpar, rng_counter_fluid, and update_halo_comm.
Referenced by lb_lbfluid_integrate().
lb_next_offsets()
auto lb_next_offsets (const Lattice & lb_lattice, std::array< Utils::Vector3i, 19 > const & c)
Relative index for the next node for each lattice velocity.
Parameters
lb_lattice The lattice parameters.
c Lattice velocities.
Definition at line 877 of file lb.cpp.
References D3Q19::c, and Lattice::halo_grid.
Referenced by lb_bounce_back(), and lb_integrate().
lb_on_param_change()
void lb_on_param_change (LBParam param)
Definition at line 121 of file lb.cpp.
References AGRID, BULKVISC, DENSITY, EXT_FORCE_DENSITY, GAMMA_EVEN, GAMMA_ODD, KT, lb_init(), lb_initialize_fields(), lb_reinit_fluid(), lb_reinit_parameters(), lbfields, lblattice, lbpar, TAU, and VISCOSITY.
Referenced by mpi_bcast_lb_params(), and mpi_bcast_lb_params_local().
lb_prepare_communication()
void lb_prepare_communication (HaloCommunicator & halo_comm, const Lattice & lb_lattice)
Set up the structures for exchange of the halo regions.
See also halo.cpp
Definition at line 647 of file lb.cpp.
References HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, Lattice::halo_grid_volume, HaloCommunicator::halo_info, D3Q19::n_vel, node_grid, HaloCommunicator::num, prepare_halo_communication(), HaloInfo::r_offset, release_halo_communication(), HaloInfo::s_offset, HaloInfo::source_node, and HaloInfo::type.
Referenced by lb_init().
lb_realloc_fluid()
void lb_realloc_fluid (LB_FluidData & lb_fluid_a, LB_FluidData & lb_fluid_b, const Lattice::index_t halo_grid_volume, LB_Fluid & lb_fluid, LB_Fluid & lb_fluid_post)
(Re-)allocate memory for the fluid and initialize pointers.
Definition at line 213 of file lb.cpp.
References D3Q19::n_vel.
Referenced by lb_init().
lb_reinit_fluid()
void lb_reinit_fluid (std::vector< LB_FluidNode > & lb_fields, Lattice const & lb_lattice, LB_Parameters const & lb_parameters)
Definition at line 275 of file lb.cpp.
References lb_initialize_fields(), and lb_set_equilibrium_populations().
Referenced by lb_on_param_change().
lb_reinit_parameters()
void lb_reinit_parameters (LB_Parameters & lb_parameters)
Definition at line 282 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::bulk_viscosity, LB_Parameters::gamma_bulk, LB_Parameters::gamma_even, LB_Parameters::gamma_odd, LB_Parameters::gamma_shear, LB_Parameters::is_TRT, LB_Parameters::kT, D3Q19::n_vel, LB_Parameters::phi, Utils::sqr(), Utils::sqrt(), LB_Parameters::tau, LB_Parameters::viscosity, and D3Q19::w_k.
Referenced by lb_init(), lb_lbfluid_reinit_parameters(), and lb_on_param_change().
lb_relax_modes()
template<typename T > std::array<T, 19> lb_relax_modes (const std::array< T, 19 > & modes, const Utils::Vector< T, 3 > & force_density, const LB_Parameters & parameters)
Definition at line 748 of file lb.cpp.
References LB_Parameters::density, LB_Parameters::gamma_bulk, LB_Parameters::gamma_even, LB_Parameters::gamma_odd, LB_Parameters::gamma_shear, Utils::Vector< T, N >::norm2(), and Utils::sqr().
Referenced by lb_integrate().
lb_sanity_checks()
void lb_sanity_checks (const LB_Parameters & lb_parameters)
Performs basic sanity checks.
Definition at line 604 of file lb.cpp.
References LB_Parameters::agrid, CELL_STRUCTURE_REGULAR, LocalBox< T >::cell_structure_type(), LB_Parameters::density, local_geo, n_nodes, runtimeErrorMsg, LB_Parameters::tau, and LB_Parameters::viscosity.
Referenced by lb_lbfluid_sanity_checks().
lb_set_equilibrium_populations()
void lb_set_equilibrium_populations (const Lattice & lb_lattice, const LB_Parameters & lb_parameters)
Definition at line 228 of file lb.cpp.
References LB_Parameters::density, Lattice::halo_grid_volume, and lb_set_population_from_density_momentum_density_stress().
Referenced by lb_init(), and lb_reinit_fluid().
lb_set_population_from_density_momentum_density_stress()
void lb_set_population_from_density_momentum_density_stress (Lattice::index_t index, double density, Utils::Vector3d const & momentum_density, Utils::Vector6d const & stress)
Sets the equilibrium distributions.
Parameters
index Index of the local site
density local fluid density
momentum_density local fluid flux density
stress local fluid stress
Definition at line 731 of file lb.cpp.
References lb_get_population_from_density_momentum_density_stress(), and lb_set_population().
Referenced by lb_set_equilibrium_populations().
lb_stream()
template<typename T > void lb_stream (LB_Fluid & lb_fluid, const std::array< T, 19 > & populations, std::size_t index, std::array< std::ptrdiff_t, 19 > const & offsets)
Definition at line 892 of file lb.cpp.
Referenced by lb_integrate().
lb_thermalize_modes()
template<typename T > std::array<T, 19> lb_thermalize_modes (Lattice::index_t index, const std::array< T, 19 > & modes, const LB_Parameters & lb_parameters, boost::optional< Utils::Counter< uint64_t >> const & rng_counter)
Definition at line 790 of file lb.cpp.
References D3Q19::c, LB_Parameters::density, FLUID, LB_Parameters::kT, LB_Parameters::phi, Utils::sqrt(), and Utils::uniform().
Referenced by lb_integrate().
log_buffer_diff()
void log_buffer_diff (std::ostream & out, int dir, Lattice::index_t index, int x, int y, int z)
Definition at line 987 of file lb.cpp.
Referenced by lb_check_halo_regions().
mpi_set_lb_fluid_counter()
void mpi_set_lb_fluid_counter (uint64_t counter)
Definition at line 631 of file lb.cpp.
References rng_counter_fluid.
Referenced by lb_fluid_set_rng_state().
normalize_modes()
template<typename T > std::array<T, 19> normalize_modes (const std::array< T, 19 > & modes)
Definition at line 701 of file lb.cpp.
References D3Q19::w_k.
Referenced by lb_calc_n_from_m().
Variable Documentation
lbfields
std::vector<LB_FluidNode> lbfields
Hydrodynamic fields of the fluid.
Definition at line 190 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), lb_init(), LBBoundaries::lb_init_boundaries(), lb_integrate(), lb_lbfluid_calc_fluid_momentum(), lb_lbinterpolation_add_force_density(), lb_on_param_change(), mpi_lb_lbfluid_calc_fluid_momentum_local(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
lbfluid
LB_Fluid lbfluid
Span of the velocity populations of the fluid (pre-collision populations).
Definition at line 185 of file lb.cpp.
Referenced by GetIBMInterpolatedVelocity(), lb_calc_fluid_momentum(), lb_get_population(), lb_init(), lb_integrate(), lb_lbfluid_on_integration_start(), lb_set_population(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
lbfluid_a
LB_FluidData lbfluid_a static
Definition at line 180 of file lb.cpp.
Referenced by lb_init().
lbfluid_b
LB_FluidData lbfluid_b static
Definition at line 181 of file lb.cpp.
Referenced by lb_init().
lbfluid_post
LB_Fluid lbfluid_post
Span of the velocity populations of the fluid (post-collision populations).
Definition at line 188 of file lb.cpp.
Referenced by lb_init(), and lb_integrate().
lblattice
Lattice lblattice
The underlying lattice.
Definition at line 177 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IsHalo(), lb_bounce_back(), lb_init(), LBBoundaries::lb_init_boundaries(), lb_integrate(), lb_lbfluid_calc_fluid_momentum(), lb_lbfluid_get_shape(), lb_lbinterpolation_add_force_density(), lb_lbinterpolation_get_interpolated_density(), lb_lbinterpolation_get_interpolated_velocity(), lb_on_param_change(), and mpi_lb_lbfluid_calc_fluid_momentum_local().
lbpar
LB_Parameters lbpar
Initial value:
= {
    0.0,
    0.0,
    -1.0,
    -1.0,
    -1.0,
    {0.0, 0.0, 0.0},
    0.,
    0.,
    0.,
    0.,
    false,
    {},
    0.0}
Lattice Boltzmann parameters.
Definition at line 149 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), lb_get_population(), lb_init(), lb_integrate(), lb_lbfluid_calc_fluid_momentum(), lb_lbfluid_get_agrid(), lb_lbfluid_get_bulk_viscosity(), lb_lbfluid_get_density(), lb_lbfluid_get_ext_force_density(), lb_lbfluid_get_gamma_even(), lb_lbfluid_get_gamma_odd(), lb_lbfluid_get_kT(), lb_lbfluid_get_tau(), lb_lbfluid_get_viscosity(), lb_lbfluid_init(), lb_lbfluid_reinit_parameters(), lb_lbfluid_sanity_checks(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_viscosity(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force_density(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_kT(), lb_lbfluid_set_tau(), lb_lbfluid_set_viscosity(), lb_on_param_change(), lb_set_population(), mpi_bcast_lb_params(), mpi_bcast_lb_params_local(), mpi_lb_lbfluid_calc_fluid_momentum_local(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
rng_counter_fluid
boost::optional<Utils::Counter<uint64_t> > rng_counter_fluid
Counter for the RNG.
Definition at line 147 of file lb.cpp.
Referenced by lb_fluid_get_rng_state(), lb_integrate(), lb_lbfluid_propagate(), and mpi_set_lb_fluid_counter().
update_halo_comm
HaloCommunicator update_halo_comm = HaloCommunicator(0)
Communicator for halo exchange between processors.
Definition at line 192 of file lb.cpp.
Referenced by lb_init(), lb_integrate(), and lb_lbfluid_on_integration_start().