ESPResSo: lb.hpp File Reference
lb.hpp File Reference
#include "config.hpp"
#include "grid_based_algorithms/lattice.hpp"
#include "grid_based_algorithms/lb-d3q19.hpp"
#include "grid_based_algorithms/lb_constants.hpp"
#include "halo.hpp"
#include <utils/Counter.hpp>
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <boost/optional.hpp>
#include <array>
#include <cstddef>
#include <cstdint>
#include <ostream>
#include <vector>
Classes
struct LB_FluidNode
Data structure for fluid on a local lattice site.
struct LB_Parameters
Data structure holding the parameters for the Lattice Boltzmann system.
class LB_Fluid_Ref
Namespaces
Utils
Typedefs
using LB_Fluid = std::array< Utils::Span< double >, 19 >
Functions
void lb_init (const LB_Parameters &lb_parameters)
void lb_reinit_fluid (std::vector< LB_FluidNode > &lb_fields, const Lattice &lb_lattice, const LB_Parameters &lb_parameters)
void lb_reinit_parameters (LB_Parameters &lb_parameters)
template<std::size_t I>
auto Utils::get (const LB_Fluid_Ref &lb_fluid)
void lb_integrate ()
Integrate the lattice-Boltzmann system for one time step.
void lb_sanity_checks (const LB_Parameters &lb_parameters)
Performs basic sanity checks.
void lb_set_population_from_density_momentum_density_stress (Lattice::index_t index, double density, Utils::Vector3d const &momentum_density, Utils::Vector6d const &stress)
Sets the equilibrium distributions.
double lb_calc_density (std::array< double, 19 > const &modes, const LB_Parameters &lb_parameters)
Utils::Vector3d lb_calc_momentum_density (std::array< double, 19 > const &modes, Utils::Vector3d const &force_density)
Utils::Vector6d lb_calc_pressure_tensor (std::array< double, 19 > const &modes, Utils::Vector3d const &force_density, const LB_Parameters &lb_parameters)
std::array< double, 19 > lb_calc_modes (Lattice::index_t index, const LB_Fluid &lb_fluid)
Calculation of hydrodynamic modes.
Utils::Vector19d lb_get_population_from_density_momentum_density_stress (double density, Utils::Vector3d const &momentum_density, Utils::Vector6d const &stress)
Get the populations as a function of density, flux density and stress.
Utils::Vector19d lb_get_population (Lattice::index_t index)
void lb_set_population (Lattice::index_t index, const Utils::Vector19d &pop)
uint64_t lb_fluid_get_rng_state ()
void lb_fluid_set_rng_state (uint64_t counter)
void lb_prepare_communication (HaloCommunicator &halo_comm, const Lattice &lb_lattice)
Set up the structures for exchange of the halo regions.
void lb_bounce_back (LB_Fluid &lbfluid, const LB_Parameters &lb_parameters, const std::vector< LB_FluidNode > &lb_fields)
Bounce back boundary conditions.
void lb_calc_fluid_momentum (double *result, const LB_Parameters &lb_parameters, const std::vector< LB_FluidNode > &lb_fields, const Lattice &lb_lattice)
Calculate momentum of the LB fluid.
void lb_collect_boundary_forces (double *result)
void lb_initialize_fields (std::vector< LB_FluidNode > &fields, LB_Parameters const &lb_parameters, Lattice const &lb_lattice)
Initialize fluid nodes.
void lb_on_param_change (LBParam param)
void log_buffer_diff (std::ostream &out, int dir, Lattice::index_t index, int x, int y, int z)
Variables
boost::optional< Utils::Counter< uint64_t > > rng_counter_fluid
Counter for the RNG.
LB_Parameters lbpar
Lattice Boltzmann parameters.
Lattice lblattice
The underlying lattice.
HaloCommunicator update_halo_comm
Communicator for halo exchange between processors.
LB_Fluid lbfluid
Span of the velocity populations of the fluid (pre-collision populations).
std::vector< LB_FluidNode > lbfields
Hydrodynamic fields of the fluid.
Detailed Description
Lattice Boltzmann algorithm for hydrodynamic degrees of freedom.
For performance reasons it is clever to do streaming and collision at the same time because every fluid node has to be read and written only once. This increases mainly cache efficiency.
The hydrodynamic fields, corresponding to density, velocity and pressure, are stored in LB_FluidNode in the array lbfields, the populations in LB_Fluid in the array lbfluid which is constructed as 2 x (Nx x Ny x Nz) x 19 array.
Implementation in lb.cpp.
Definition in file lb.hpp.
Typedef Documentation
LB_Fluid
using LB_Fluid = std::array<Utils::Span<double>, 19>
Definition at line 147 of file lb.hpp.
Function Documentation
lb_bounce_back()
void lb_bounce_back (LB_Fluid & lbfluid, const LB_Parameters & lb_parameters, const std::vector< LB_FluidNode > & lb_fields)
Bounce back boundary conditions.
The populations that have propagated into a boundary node are bounced back to the node they came from. This results in no slip boundary conditions, cf. [31].
Definition at line 1253 of file lb.cpp.
References D3Q19::c, LB_Parameters::density, Utils::get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_next_offsets(), LBBoundaries::lbboundaries, lblattice, and D3Q19::w.
Referenced by lb_integrate().
lb_calc_density()
double lb_calc_density (std::array< double, 19 > const & modes, const LB_Parameters & lb_parameters)
Definition at line 1177 of file lb.cpp.
References LB_Parameters::density.
Referenced by lb_calc_pressure_tensor().
lb_calc_fluid_momentum()
void lb_calc_fluid_momentum (double * result, const LB_Parameters & lb_parameters, const std::vector< LB_FluidNode > & lb_fields, const Lattice & lb_lattice)
Calculate momentum of the LB fluid.
Parameters
[out] result Fluid momentum in MD units
[in] lb_parameters LB parameters
[in] lb_fields Hydrodynamic fields of the fluid
[in] lb_lattice The underlying lattice
Definition at line 1324 of file lb.cpp.
References LB_Parameters::agrid, comm_cart, Utils::get_linear_index(), Lattice::grid, Lattice::halo_grid, lb_calc_local_momentum_density(), lbfluid, momentum(), and LB_Parameters::tau.
Referenced by lb_lbfluid_calc_fluid_momentum(), and mpi_lb_lbfluid_calc_fluid_momentum_local().
lb_calc_modes()
std::array<double, 19> lb_calc_modes (Lattice::index_t index, const LB_Fluid & lb_fluid)
Calculation of hydrodynamic modes.
Parameters
[in] index Number of the node to calculate the modes for
[in] lb_fluid Populations of the fluid
Return values
Array containing the modes.
Definition at line 741 of file lb.cpp.
Referenced by GetIBMInterpolatedVelocity(), lb_integrate(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
lb_calc_momentum_density()
Utils::Vector3d lb_calc_momentum_density (std::array< double, 19 > const & modes, Utils::Vector3d const & force_density)
Definition at line 1182 of file lb.cpp.
Referenced by lb_calc_pressure_tensor().
lb_calc_pressure_tensor()
Utils::Vector6d lb_calc_pressure_tensor (std::array< double, 19 > const & modes, Utils::Vector3d const & force_density, const LB_Parameters & lb_parameters)
Definition at line 1189 of file lb.cpp.
References LB_Parameters::gamma_bulk, LB_Parameters::gamma_shear, lb_calc_density(), lb_calc_momentum_density(), and Utils::sqr().
lb_collect_boundary_forces()
void lb_collect_boundary_forces (double * result)
Definition at line 1344 of file lb.cpp.
References comm_cart, and LBBoundaries::lbboundaries.
Referenced by LBBoundaries::lb_collect_boundary_forces_local(), and LBBoundaries::lbboundary_get_force().
lb_fluid_get_rng_state()
uint64_t lb_fluid_get_rng_state ()
Definition at line 626 of file lb.cpp.
References rng_counter_fluid.
Referenced by lb_lbfluid_get_rng_state().
lb_fluid_set_rng_state()
void lb_fluid_set_rng_state (uint64_t counter)
Definition at line 637 of file lb.cpp.
References mpi_call(), and mpi_set_lb_fluid_counter().
Referenced by lb_lbfluid_set_rng_state().
lb_get_population()
Utils::Vector19d lb_get_population (Lattice::index_t index) inline
Definition at line 222 of file lb.hpp.
References D3Q19::coefficients, LB_Parameters::density, lbfluid, lbpar, and D3Q19::n_vel.
lb_get_population_from_density_momentum_density_stress()
Utils::Vector19d lb_get_population_from_density_momentum_density_stress (double density, Utils::Vector3d const & momentum_density, Utils::Vector6d const & stress)
Get the populations as a function of density, flux density and stress.
Parameters
density fluid density
momentum_density fluid flux density
stress fluid stress
Returns
19 populations (including equilibrium density contribution).
Definition at line 721 of file lb.cpp.
References lb_calc_n_from_m().
Referenced by lb_lbnode_set_density(), lb_lbnode_set_velocity(), and lb_set_population_from_density_momentum_density_stress().
lb_init()
void lb_init (const LB_Parameters & lb_parameters)
Definition at line 238 of file lb.cpp.
References LB_Parameters::agrid, box_geo, calc_node_pos(), check_runtime_errors(), comm_cart, Lattice::halo_grid_volume, LBBoundaries::lb_init_boundaries(), lb_initialize_fields(), lb_prepare_communication(), lb_realloc_fluid(), lb_reinit_parameters(), lb_set_equilibrium_populations(), lbfields, lbfluid, lbfluid_a, lbfluid_b, lbfluid_post, lblattice, lbpar, LocalBox< T >::length(), BoxGeometry::length(), local_geo, LocalBox< T >::my_right(), node_grid, runtimeErrorMsg, and update_halo_comm.
Referenced by lb_lbfluid_init(), and lb_on_param_change().
lb_initialize_fields()
void lb_initialize_fields (std::vector< LB_FluidNode > & lb_fields, LB_Parameters const & lb_parameters, Lattice const & lb_lattice)
Initialize fluid nodes.
Parameters
[out] lb_fields Vector containing the fluid nodes
[in] lb_parameters Parameters for the LB
[in] lb_lattice Lattice instance
Definition at line 200 of file lb.cpp.
References LB_Parameters::ext_force_density, and Lattice::halo_grid_volume.
Referenced by lb_init(), lb_on_param_change(), and lb_reinit_fluid().
lb_integrate()
void lb_integrate ()
Integrate the lattice-Boltzmann system for one time step.
This function performs the collision step and the streaming step. If external force densities are present, they are applied prior to the collisions. If boundaries are present, it also applies the boundary conditions.
Definition at line 901 of file lb.cpp.
References D3Q19::c, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, LB_Parameters::ext_force_density, Lattice::grid, halo_communication(), Lattice::halo_grid, Lattice::halo_offset, halo_push_communication(), lb_apply_forces(), lb_bounce_back(), lb_calc_modes(), lb_calc_n_from_m(), lb_check_halo_regions(), lb_next_offsets(), lb_relax_modes(), lb_stream(), lb_thermalize_modes(), LBBoundaries::lbboundaries, lbfields, lbfluid, lbfluid_post, lblattice, lbpar, rng_counter_fluid, and update_halo_comm.
Referenced by lb_lbfluid_integrate().
lb_on_param_change()
void lb_on_param_change (LBParam param)
Definition at line 121 of file lb.cpp.
References AGRID, BULKVISC, DENSITY, EXT_FORCE_DENSITY, GAMMA_EVEN, GAMMA_ODD, KT, lb_init(), lb_initialize_fields(), lb_reinit_fluid(), lb_reinit_parameters(), lbfields, lblattice, lbpar, TAU, and VISCOSITY.
Referenced by mpi_bcast_lb_params(), and mpi_bcast_lb_params_local().
lb_prepare_communication()
void lb_prepare_communication (HaloCommunicator & halo_comm, const Lattice & lb_lattice)
Set up the structures for exchange of the halo regions.
See also halo.cpp
Definition at line 647 of file lb.cpp.
References HaloInfo::datatype, HaloInfo::dest_node, HaloInfo::fieldtype, Lattice::halo_grid_volume, HaloCommunicator::halo_info, D3Q19::n_vel, node_grid, HaloCommunicator::num, prepare_halo_communication(), HaloInfo::r_offset, release_halo_communication(), HaloInfo::s_offset, HaloInfo::source_node, and HaloInfo::type.
Referenced by lb_init().
lb_reinit_fluid()
void lb_reinit_fluid (std::vector< LB_FluidNode > & lb_fields, const Lattice & lb_lattice, const LB_Parameters & lb_parameters)
Definition at line 275 of file lb.cpp.
References lb_initialize_fields(), and lb_set_equilibrium_populations().
Referenced by lb_on_param_change().
lb_reinit_parameters()
void lb_reinit_parameters (LB_Parameters & lb_parameters)
Definition at line 282 of file lb.cpp.
References LB_Parameters::agrid, LB_Parameters::bulk_viscosity, LB_Parameters::gamma_bulk, LB_Parameters::gamma_even, LB_Parameters::gamma_odd, LB_Parameters::gamma_shear, LB_Parameters::is_TRT, LB_Parameters::kT, D3Q19::n_vel, LB_Parameters::phi, Utils::sqr(), Utils::sqrt(), LB_Parameters::tau, LB_Parameters::viscosity, and D3Q19::w_k.
Referenced by lb_init(), lb_lbfluid_reinit_parameters(), and lb_on_param_change().
lb_sanity_checks()
void lb_sanity_checks (const LB_Parameters & lb_parameters)
Performs basic sanity checks.
Definition at line 604 of file lb.cpp.
References LB_Parameters::agrid, CELL_STRUCTURE_REGULAR, LocalBox< T >::cell_structure_type(), LB_Parameters::density, local_geo, n_nodes, runtimeErrorMsg, LB_Parameters::tau, and LB_Parameters::viscosity.
Referenced by lb_lbfluid_sanity_checks().
lb_set_population()
void lb_set_population (Lattice::index_t index, const Utils::Vector19d & pop) inline
Definition at line 230 of file lb.hpp.
References D3Q19::coefficients, LB_Parameters::density, lbfluid, lbpar, and D3Q19::n_vel.
Referenced by lb_set_population_from_density_momentum_density_stress().
lb_set_population_from_density_momentum_density_stress()
void lb_set_population_from_density_momentum_density_stress (Lattice::index_t index, double density, Utils::Vector3d const & momentum_density, Utils::Vector6d const & stress)
Sets the equilibrium distributions.
Parameters
index Index of the local site
density local fluid density
momentum_density local fluid flux density
stress local fluid stress
Definition at line 731 of file lb.cpp.
References lb_get_population_from_density_momentum_density_stress(), and lb_set_population().
Referenced by lb_set_equilibrium_populations().
log_buffer_diff()
void log_buffer_diff (std::ostream & out, int dir, Lattice::index_t index, int x, int y, int z)
Definition at line 987 of file lb.cpp.
Referenced by lb_check_halo_regions().
Variable Documentation
lbfields
std::vector<LB_FluidNode> lbfields
Hydrodynamic fields of the fluid.
Definition at line 190 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), lb_init(), LBBoundaries::lb_init_boundaries(), lb_integrate(), lb_lbfluid_calc_fluid_momentum(), lb_lbinterpolation_add_force_density(), lb_on_param_change(), mpi_lb_lbfluid_calc_fluid_momentum_local(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
lbfluid
LB_Fluid lbfluid
Span of the velocity populations of the fluid (pre-collision populations).
Definition at line 185 of file lb.cpp.
Referenced by GetIBMInterpolatedVelocity(), lb_calc_fluid_momentum(), lb_get_population(), lb_init(), lb_integrate(), lb_lbfluid_on_integration_start(), lb_set_population(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
lblattice
Lattice lblattice
The underlying lattice.
Definition at line 177 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), IsHalo(), lb_bounce_back(), lb_init(), LBBoundaries::lb_init_boundaries(), lb_integrate(), lb_lbfluid_calc_fluid_momentum(), lb_lbfluid_get_shape(), lb_lbinterpolation_add_force_density(), lb_lbinterpolation_get_interpolated_density(), lb_lbinterpolation_get_interpolated_velocity(), lb_on_param_change(), and mpi_lb_lbfluid_calc_fluid_momentum_local().
lbpar
LB_Parameters lbpar
Lattice Boltzmann parameters.
Definition at line 149 of file lb.cpp.
Referenced by CoupleIBMParticleToFluid(), GetIBMInterpolatedVelocity(), lb_get_population(), lb_init(), lb_integrate(), lb_lbfluid_calc_fluid_momentum(), lb_lbfluid_get_agrid(), lb_lbfluid_get_bulk_viscosity(), lb_lbfluid_get_density(), lb_lbfluid_get_ext_force_density(), lb_lbfluid_get_gamma_even(), lb_lbfluid_get_gamma_odd(), lb_lbfluid_get_kT(), lb_lbfluid_get_tau(), lb_lbfluid_get_viscosity(), lb_lbfluid_init(), lb_lbfluid_reinit_parameters(), lb_lbfluid_sanity_checks(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_viscosity(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force_density(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_kT(), lb_lbfluid_set_tau(), lb_lbfluid_set_viscosity(), lb_on_param_change(), lb_set_population(), mpi_bcast_lb_params(), mpi_bcast_lb_params_local(), mpi_lb_lbfluid_calc_fluid_momentum_local(), anonymous_namespace{lb_interpolation.cpp}::node_dens(), and anonymous_namespace{lb_interpolation.cpp}::node_u().
rng_counter_fluid
boost::optional<Utils::Counter<uint64_t> > rng_counter_fluid
Counter for the RNG.
Definition at line 147 of file lb.cpp.
Referenced by lb_fluid_get_rng_state(), lb_integrate(), lb_lbfluid_propagate(), and mpi_set_lb_fluid_counter().
update_halo_comm
HaloCommunicator update_halo_comm
Communicator for halo exchange between processors.
Definition at line 192 of file lb.cpp.
Referenced by lb_init(), lb_integrate(), and lb_lbfluid_on_integration_start().