ESPResSo: lb_particle_coupling.hpp File Reference
lb_particle_coupling.hpp File Reference
#include "BoxGeometry.hpp"
#include "OptionalCounter.hpp"
#include "ParticleRange.hpp"
#include <boost/serialization/access.hpp>
#include <cstdint>
#include <unordered_set>
Classes
struct LB_Particle_Coupling
Typedefs
template<class T , std::size_t N>
using Box = std::pair< Utils::Vector< T, N >, Utils::Vector< T, N > >
Functions
void lb_lbcoupling_calc_particle_lattice_ia (bool couple_virtual, const ParticleRange &particles, const ParticleRange &more_particles, double time_step)
Calculate particle lattice interactions.
void lb_lbcoupling_propagate ()
uint64_t lb_lbcoupling_get_rng_state ()
void lb_lbcoupling_set_rng_state (uint64_t counter)
void lb_lbcoupling_set_gamma (double friction)
double lb_lbcoupling_get_gamma ()
bool lb_lbcoupling_is_seed_required ()
void lb_lbcoupling_activate ()
Activate the coupling between LB and MD particles.
void lb_lbcoupling_deactivate ()
Deactivate the coupling between LB and MD particles.
template<class T , std::size_t N>
bool in_box (Utils::Vector< T, N > const &pos, Box< T, N > const &box)
Check if a position is in a box.
bool in_local_halo (Utils::Vector3d const &pos)
Check if a position is within the local LB domain plus halo.
std::vector< Utils::Vector3d > positions_in_halo (Utils::Vector3d pos, const BoxGeometry &box)
Return a vector of positions shifted by +,- box length in each coordinate.
bool is_ghost_for_local_particle (const Particle &p)
Return if locally there exists a physical particle for a given (ghost) particle.
bool should_be_coupled (const Particle &p, std::unordered_set< int > &coupled_ghost_particles)
Determine if a given particle should be coupled.
Typedef Documentation
Box
template<class T , std::size_t N> using Box = std::pair<Utils::Vector<T, N>, Utils::Vector<T, N> >
Definition at line 79 of file lb_particle_coupling.hpp.
Function Documentation
in_box()
template<class T , std::size_t N> bool in_box (Utils::Vector< T, N > const & pos, Box< T, N > const & box)
Check if a position is in a box.
The left boundary belong to the box, the right one does not. Periodic boundaries are not considered.
Parameters
pos Position to check
box Box to check
Returns
True iff the point is inside of the box.
Definition at line 94 of file lb_particle_coupling.hpp.
References pos.
Referenced by in_local_domain().
in_local_halo()
bool in_local_halo (Utils::Vector3d const & pos)
Check if a position is within the local LB domain plus halo.
Parameters
pos Position to check
Returns
True iff the point is inside of the domain.
Definition at line 194 of file lb_particle_coupling.cpp.
References in_local_domain(), lb_lbfluid_get_agrid(), and pos.
Referenced by IBM_ForcesIntoFluid_CPU(), lb_lbcoupling_calc_particle_lattice_ia(), and positions_in_halo().
is_ghost_for_local_particle()
bool is_ghost_for_local_particle (const Particle & p)
Return if locally there exists a physical particle for a given (ghost) particle.
Definition at line 222 of file lb_particle_coupling.cpp.
References cell_structure, CellStructure::get_local_particle(), Particle::id(), and Particle::is_ghost().
Referenced by should_be_coupled().
lb_lbcoupling_activate()
void lb_lbcoupling_activate ()
Activate the coupling between LB and MD particles.
Note
This is a collective function and needs to be called from all processes.
Definition at line 58 of file lb_particle_coupling.cpp.
References LB_Particle_Coupling::couple_to_md, and lb_particle_coupling.
Referenced by integrate().
lb_lbcoupling_calc_particle_lattice_ia()
void lb_lbcoupling_calc_particle_lattice_ia (bool couple_virtual, const ParticleRange & particles, const ParticleRange & more_particles, double time_step)
Calculate particle lattice interactions.
So far, only viscous coupling with Stokesian friction is implemented. Include all particle-lattice forces in this function. The function is called from force_calc.
Definition at line 265 of file lb_particle_coupling.cpp.
References anonymous_namespace{lb_particle_coupling.cpp}::add_md_force(), add_swimmer_force(), box_geo, CELL_STRUCTURE_REGULAR, LocalBox< T >::cell_structure_type(), LB_Particle_Coupling::couple_to_md, CPU, ESPRESSO_PROFILER_CXX_MARK_FUNCTION, force, GPU, in_local_domain(), in_local_halo(), lattice_switch, lb_calc_particle_lattice_ia_gpu< 27 >(), lb_calc_particle_lattice_ia_gpu< 8 >(), lb_lbcoupling_get_gamma(), lb_lbfluid_get_kT(), lb_lbinterpolation_get_interpolation_order(), lb_particle_coupling, lb_viscous_coupling(), linear, local_geo, n_nodes, Cells::particles(), pos, positions_in_halo(), quadratic, LB_Particle_Coupling::rng_counter_coupling, should_be_coupled(), Utils::sqrt(), this_node, time_step, and Utils::Counter< T >::value().
Referenced by force_calc().
lb_lbcoupling_deactivate()
void lb_lbcoupling_deactivate ()
Deactivate the coupling between LB and MD particles.
Note
This is a collective function and needs to be called from all processes.
Definition at line 60 of file lb_particle_coupling.cpp.
References LB_Particle_Coupling::couple_to_md, LB_Particle_Coupling::gamma, lattice_switch, lb_particle_coupling, NONE, runtimeWarningMsg, and this_node.
Referenced by integrate().
lb_lbcoupling_get_gamma()
double lb_lbcoupling_get_gamma ()
Definition at line 77 of file lb_particle_coupling.cpp.
References LB_Particle_Coupling::gamma, and lb_particle_coupling.
Referenced by ek_init(), lb_lbcoupling_calc_particle_lattice_ia(), and lb_viscous_coupling().
lb_lbcoupling_get_rng_state()
uint64_t lb_lbcoupling_get_rng_state ()
Definition at line 95 of file lb_particle_coupling.cpp.
References CPU, GPU, lattice_switch, lb_coupling_get_rng_state_cpu(), and lb_coupling_get_rng_state_gpu().
lb_lbcoupling_is_seed_required()
bool lb_lbcoupling_is_seed_required ()
Definition at line 79 of file lb_particle_coupling.cpp.
References CPU, GPU, OptionalCounter::is_initialized(), lattice_switch, lb_particle_coupling, LB_Particle_Coupling::rng_counter_coupling, and rng_counter_coupling_gpu.
lb_lbcoupling_propagate()
void lb_lbcoupling_propagate ()
Definition at line 372 of file lb_particle_coupling.cpp.
References CPU, GPU, Utils::Counter< T >::increment(), lattice_switch, lb_lbfluid_get_kT(), lb_particle_coupling, NONE, LB_Particle_Coupling::rng_counter_coupling, and rng_counter_coupling_gpu.
Referenced by integrate().
lb_lbcoupling_set_gamma()
void lb_lbcoupling_set_gamma (double friction)
Definition at line 72 of file lb_particle_coupling.cpp.
References Utils::gamma(), LB_Particle_Coupling::gamma, lb_particle_coupling, and mpi_bcast_lb_particle_coupling().
Referenced by ek_init().
lb_lbcoupling_set_rng_state()
void lb_lbcoupling_set_rng_state (uint64_t counter)
Definition at line 107 of file lb_particle_coupling.cpp.
References CPU, GPU, lattice_switch, lb_coupling_set_rng_state_gpu(), lb_particle_coupling, mpi_bcast_lb_particle_coupling(), and LB_Particle_Coupling::rng_counter_coupling.
positions_in_halo()
std::vector<Utils::Vector3d> positions_in_halo (Utils::Vector3d pos, const BoxGeometry & box)
Return a vector of positions shifted by +,- box length in each coordinate.
Definition at line 202 of file lb_particle_coupling.cpp.
References Utils::hadamard_product(), in_local_halo(), BoxGeometry::length(), pos, and res.
Referenced by add_swimmer_force(), lb_lbcoupling_calc_particle_lattice_ia(), and ParticleVelocitiesFromLB_CPU().
should_be_coupled()
bool should_be_coupled (const Particle & p, std::unordered_set< int > & coupled_ghost_particles)
Determine if a given particle should be coupled.
In certain cases, there may be more than one ghost for the same particle. To make sure, that these are only coupled once, ghosts' ids are stored in an unordered_set.
Definition at line 230 of file lb_particle_coupling.cpp.
References Particle::id(), Particle::is_ghost(), and is_ghost_for_local_particle().
Referenced by lb_lbcoupling_calc_particle_lattice_ia(), and ParticleVelocitiesFromLB_CPU().