ESPResSo: lb_collective_interface.cpp File Reference
lb_collective_interface.cpp File Reference
#include "MpiCallbacks.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "grid.hpp"
#include "lb.hpp"
#include "lb_constants.hpp"
#include "lb_interpolation.hpp"
#include <utils/Vector.hpp>
#include <utils/index.hpp>
#include <boost/optional.hpp>
Functions
boost::optional< Utils::Vector3d > mpi_lb_get_interpolated_velocity (Utils::Vector3d const &pos)
boost::optional< double > mpi_lb_get_interpolated_density (Utils::Vector3d const &pos)
auto mpi_lb_get_density (Utils::Vector3i const &index)
auto mpi_lb_get_populations (Utils::Vector3i const &index)
boost::optional< int > mpi_lb_get_boundary_flag (Utils::Vector3i const &index)
void mpi_lb_set_population (Utils::Vector3i const &index, Utils::Vector19d const &population)
void mpi_lb_set_force_density (Utils::Vector3i const &index, Utils::Vector3d const &force_density)
auto mpi_lb_get_momentum_density (Utils::Vector3i const &index)
auto mpi_lb_get_pressure_tensor (Utils::Vector3i const &index)
void mpi_bcast_lb_params_local (LBParam field, LB_Parameters const &params)
void mpi_bcast_lb_params (LBParam field)
Broadcast a parameter for lattice Boltzmann.
Function Documentation
mpi_bcast_lb_params()
void mpi_bcast_lb_params (LBParam field)
Broadcast a parameter for lattice Boltzmann.
Parameters
[in] field References the parameter field to be broadcasted. The references are defined in lb.hpp
Definition at line 177 of file lb_collective_interface.cpp.
References lb_on_param_change(), lbpar, mpi_bcast_lb_params_local(), and mpi_call().
Referenced by lb_lbfluid_load_checkpoint(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_viscosity(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force_density(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_kT(), lb_lbfluid_set_tau(), and lb_lbfluid_set_viscosity().
mpi_bcast_lb_params_local()
void mpi_bcast_lb_params_local (LBParam field, LB_Parameters const & params)
Definition at line 166 of file lb_collective_interface.cpp.
References lb_on_param_change(), lbpar, and params.
Referenced by mpi_bcast_lb_params().
mpi_lb_get_boundary_flag()
boost::optional<int> mpi_lb_get_boundary_flag (Utils::Vector3i const & index)
Definition at line 112 of file lb_collective_interface.cpp.
Referenced by lb_lbnode_get_boundary().
mpi_lb_get_density()
auto mpi_lb_get_density (Utils::Vector3i const & index)
Definition at line 93 of file lb_collective_interface.cpp.
Referenced by lb_lbnode_get_density(), and lb_lbnode_get_velocity().
mpi_lb_get_interpolated_density()
boost::optional<double> mpi_lb_get_interpolated_density (Utils::Vector3d const & pos)
Definition at line 85 of file lb_collective_interface.cpp.
Referenced by lb_lbfluid_get_interpolated_density().
mpi_lb_get_interpolated_velocity()
boost::optional<Utils::Vector3d> mpi_lb_get_interpolated_velocity (Utils::Vector3d const & pos)
Definition at line 76 of file lb_collective_interface.cpp.
Referenced by lb_lbfluid_get_interpolated_velocity().
mpi_lb_get_momentum_density()
auto mpi_lb_get_momentum_density (Utils::Vector3i const & index)
Definition at line 148 of file lb_collective_interface.cpp.
Referenced by lb_lbnode_get_velocity().
mpi_lb_get_populations()
auto mpi_lb_get_populations (Utils::Vector3i const & index)
Definition at line 102 of file lb_collective_interface.cpp.
Referenced by lb_lbfluid_save_checkpoint(), and lb_lbnode_get_pop().
mpi_lb_get_pressure_tensor()
auto mpi_lb_get_pressure_tensor (Utils::Vector3i const & index)
Definition at line 157 of file lb_collective_interface.cpp.
Referenced by lb_lbnode_get_pressure_tensor_neq().
mpi_lb_set_force_density()
void mpi_lb_set_force_density (Utils::Vector3i const & index, Utils::Vector3d const & force_density)
Definition at line 137 of file lb_collective_interface.cpp.
Referenced by lb_lbnode_set_velocity().
mpi_lb_set_population()
void mpi_lb_set_population (Utils::Vector3i const & index, Utils::Vector19d const & population)
Definition at line 126 of file lb_collective_interface.cpp.
Referenced by lb_lbnode_set_density(), lb_lbnode_set_pop(), and lb_lbnode_set_velocity().