ESPResSo: lb_inertialess_tracers_cuda_interface.hpp File Reference
lb_inertialess_tracers_cuda_interface.hpp File Reference
#include "config.hpp"
#include "ParticleRange.hpp"
#include <vector>
Classes
struct IBM_CUDA_ParticleDataInput
struct IBM_CUDA_ParticleDataOutput
Functions
void IBM_cuda_mpi_send_velocities (ParticleRange const &particles)
Particle velocities have been communicated from GPU, now transmit to all nodes.
void IBM_cuda_mpi_get_particles (ParticleRange const &particles)
Gather particle positions on the head node in order to communicate them to GPU.
void ParticleVelocitiesFromLB_GPU (ParticleRange const &particles, int this_node)
Call a kernel function to interpolate the velocity at each IBM particle's position.
Variables
std::vector< IBM_CUDA_ParticleDataInput > IBM_ParticleDataInput_host
std::vector< IBM_CUDA_ParticleDataOutput > IBM_ParticleDataOutput_host
Function Documentation
IBM_cuda_mpi_get_particles()
void IBM_cuda_mpi_get_particles (ParticleRange const & particles)
Gather particle positions on the head node in order to communicate them to GPU.
We transfer all particles (real and virtual), but actually we would only need the virtual ones. Room for improvement... Analogous to cuda_mpi_get_particles.
Definition at line 70 of file lb_inertialess_tracers_cuda_interface.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), IBM_ParticleDataInput_host, pack_particles(), Cells::particles(), ParticleRange::size(), and this_node.
Referenced by IBM_ForcesIntoFluid_GPU().
IBM_cuda_mpi_send_velocities()
void IBM_cuda_mpi_send_velocities (ParticleRange const & particles)
Particle velocities have been communicated from GPU, now transmit to all nodes.
Analogous to cuda_mpi_send_forces.
Definition at line 103 of file lb_inertialess_tracers_cuda_interface.cpp.
References comm_cart, IBM_ParticleDataOutput_host, Cells::particles(), Utils::Mpi::scatter_buffer(), set_velocities(), ParticleRange::size(), and this_node.
Referenced by ParticleVelocitiesFromLB_GPU().
ParticleVelocitiesFromLB_GPU()
void ParticleVelocitiesFromLB_GPU (ParticleRange const & particles, int this_node)
Call a kernel function to interpolate the velocity at each IBM particle's position.
Store velocity in the particle data structure.
Definition at line 378 of file lb_inertialess_tracers_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, gpu_get_particle_pointer(), IBM_cuda_mpi_send_velocities(), IBM_ParticleDataInput_device, IBM_ParticleDataOutput_device, IBM_ParticleDataOutput_host, KERNELCALL, lb_boundary_velocity_IBM, node_f, para_gpu, Cells::particles(), ParticleVelocitiesFromLB_Kernel(), this_node, and threads_per_block.
Referenced by IBM_UpdateParticlePositions().
Variable Documentation
IBM_ParticleDataInput_host
std::vector<IBM_CUDA_ParticleDataInput> IBM_ParticleDataInput_host
Definition at line 41 of file lb_inertialess_tracers_cuda_interface.cpp.
Referenced by IBM_cuda_mpi_get_particles(), IBM_ForcesIntoFluid_GPU(), and InitCUDA_IBM().
IBM_ParticleDataOutput_host
std::vector<IBM_CUDA_ParticleDataOutput> IBM_ParticleDataOutput_host
Definition at line 42 of file lb_inertialess_tracers_cuda_interface.cpp.
Referenced by IBM_cuda_mpi_send_velocities(), InitCUDA_IBM(), and ParticleVelocitiesFromLB_GPU().