ESPResSo: lb_interpolation.cpp File Reference
lb_interpolation.cpp File Reference
#include "lb_interpolation.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "grid_based_algorithms/lattice.hpp"
#include "lb.hpp"
#include <utils/Vector.hpp>
#include <algorithm>
#include <cstddef>
#include <stdexcept>
Namespaces
anonymous_namespace{lb_interpolation.cpp}
Functions
void mpi_set_interpolation_order_local (InterpolationOrder const &order)
void lb_lbinterpolation_set_interpolation_order (InterpolationOrder const &order)
Set the interpolation order for the LB.
InterpolationOrder lb_lbinterpolation_get_interpolation_order ()
Get the interpolation order for the LB.
template<typename Op >
void anonymous_namespace{lb_interpolation.cpp}::lattice_interpolation (Lattice const &lattice, Utils::Vector3d const &pos, Op &&op)
Utils::Vector3d anonymous_namespace{lb_interpolation.cpp}::node_u (Lattice::index_t index)
double anonymous_namespace{lb_interpolation.cpp}::node_dens (Lattice::index_t index)
const Utils::Vector3d lb_lbinterpolation_get_interpolated_velocity (const Utils::Vector3d &pos)
Calculates the fluid velocity at a given position of the lattice.
double lb_lbinterpolation_get_interpolated_density (const Utils::Vector3d &pos)
Calculates the fluid density at a given position of the lattice.
void lb_lbinterpolation_add_force_density (const Utils::Vector3d &pos, const Utils::Vector3d &force_density)
Add a force density to the fluid at the given position.
Variables
InterpolationOrder anonymous_namespace{lb_interpolation.cpp}::interpolation_order = InterpolationOrder::linear
Function Documentation
lb_lbinterpolation_add_force_density()
void lb_lbinterpolation_add_force_density (const Utils::Vector3d & pos, const Utils::Vector3d & force_density)
Add a force density to the fluid at the given position.
Definition at line 124 of file lb_interpolation.cpp.
References anonymous_namespace{lb_interpolation.cpp}::interpolation_order, anonymous_namespace{lb_interpolation.cpp}::lattice_interpolation(), lbfields, lblattice, linear, pos, quadratic, and D3Q19::w.
Referenced by anonymous_namespace{lb_particle_coupling.cpp}::add_md_force().
lb_lbinterpolation_get_interpolated_density()
double lb_lbinterpolation_get_interpolated_density (const Utils::Vector3d & p)
Calculates the fluid density at a given position of the lattice.
Note
It can lead to undefined behaviour if the position is not within the local lattice.
Definition at line 111 of file lb_interpolation.cpp.
References anonymous_namespace{lb_interpolation.cpp}::lattice_interpolation(), lblattice, anonymous_namespace{lb_interpolation.cpp}::node_dens(), pos, and D3Q19::w.
lb_lbinterpolation_get_interpolated_velocity()
const Utils::Vector3d lb_lbinterpolation_get_interpolated_velocity (const Utils::Vector3d & p)
Calculates the fluid velocity at a given position of the lattice.
Note
It can lead to undefined behaviour if the position is not within the local lattice.
Definition at line 98 of file lb_interpolation.cpp.
References anonymous_namespace{lb_interpolation.cpp}::lattice_interpolation(), lblattice, anonymous_namespace{lb_interpolation.cpp}::node_u(), pos, and D3Q19::w.
Referenced by lb_viscous_coupling().
lb_lbinterpolation_get_interpolation_order()
InterpolationOrder lb_lbinterpolation_get_interpolation_order ()
Get the interpolation order for the LB.
Definition at line 48 of file lb_interpolation.cpp.
References anonymous_namespace{lb_interpolation.cpp}::interpolation_order.
Referenced by lb_lbcoupling_calc_particle_lattice_ia(), lb_lbfluid_get_interpolated_density(), and lb_lbfluid_get_interpolated_velocity().
lb_lbinterpolation_set_interpolation_order()
void lb_lbinterpolation_set_interpolation_order (InterpolationOrder const & order)
Set the interpolation order for the LB.
Definition at line 43 of file lb_interpolation.cpp.
References mpi_call_all(), and mpi_set_interpolation_order_local().
mpi_set_interpolation_order_local()
void mpi_set_interpolation_order_local (InterpolationOrder const & order)
Definition at line 37 of file lb_interpolation.cpp.
References anonymous_namespace{lb_interpolation.cpp}::interpolation_order.
Referenced by lb_lbinterpolation_set_interpolation_order().