ESPResSo: lb_interface.cpp File Reference
lb_interface.cpp File Reference
#include "lb_interface.hpp"
#include "BoxGeometry.hpp"
#include "MpiCallbacks.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "electrokinetics.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "halo.hpp"
#include "lb-d3q19.hpp"
#include "lb.hpp"
#include "lb_boundaries.hpp"
#include "lb_collective_interface.hpp"
#include "lb_constants.hpp"
#include "lb_interpolation.hpp"
#include "lbgpu.hpp"
#include <utils/Vector.hpp>
#include <cmath>
#include <fstream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
Functions
ActiveLB lb_lbfluid_get_lattice_switch ()
Get the global variable lattice_switch.
void lb_lbfluid_integrate ()
void lb_lbfluid_propagate ()
Propagate the LB fluid.
void lb_boundary_mach_check ()
Check the boundary velocities.
void lb_lbfluid_sanity_checks (double time_step)
Perform LB parameter and boundary velocity checks.
void lb_lbfluid_on_integration_start ()
Event handler for integration start.
void lb_lbfluid_reinit_parameters ()
(Re-)initialize the fluid.
void lb_lbfluid_init ()
Perform a full initialization of the lattice Boltzmann system.
uint64_t lb_lbfluid_get_rng_state ()
Get the current counter of the Philox RNG.
void lb_lbfluid_set_rng_state (uint64_t counter)
Set the current counter of the Philox RNG.
void lb_lbfluid_set_density (double density)
Set the global LB density.
double lb_lbfluid_get_density ()
Get the global LB density.
void lb_lbfluid_set_viscosity (double viscosity)
Set the global LB viscosity.
double lb_lbfluid_get_viscosity ()
Get the global LB viscosity.
void lb_lbfluid_set_bulk_viscosity (double bulk_viscosity)
Set the global LB bulk viscosity.
double lb_lbfluid_get_bulk_viscosity ()
Get the global LB bulk viscosity.
void lb_lbfluid_set_gamma_odd (double gamma_odd)
Set the global LB relaxation parameter for odd modes.
double lb_lbfluid_get_gamma_odd ()
Get the global LB relaxation parameter for odd modes.
void lb_lbfluid_set_gamma_even (double gamma_even)
Set the global LB relaxation parameter for even modes.
double lb_lbfluid_get_gamma_even ()
Get the global LB relaxation parameter for even modes.
void lb_lbfluid_set_agrid (double agrid)
Set the global LB lattice spacing.
double lb_lbfluid_get_agrid ()
Get the LB grid spacing.
void lb_lbfluid_set_ext_force_density (const Utils::Vector3d &force_density)
Set the external force density acting on the LB fluid.
const Utils::Vector3d lb_lbfluid_get_ext_force_density ()
Get the external force density acting on the LB fluid.
void lb_lbfluid_set_tau (double tau)
Set the LB time step.
void check_tau_time_step_consistency (double tau, double time_step)
Check if tau is an integer multiple of time_step, throws if not.
double lb_lbfluid_get_tau ()
Get the LB time step.
void lb_lbfluid_set_lattice_switch (ActiveLB local_lattice_switch)
Set the global variable lattice_switch.
void lb_lbfluid_set_kT (double kT)
Set the LB fluid thermal energy.
double lb_lbfluid_get_kT ()
Get the thermal energy parameter of the LB fluid.
double lb_lbfluid_get_lattice_speed ()
Get the lattice speed (agrid/tau).
void lb_lbfluid_print_vtk_boundary (const std::string &filename)
void lb_lbfluid_print_vtk_velocity (const std::string &filename, std::vector< int > bb1, std::vector< int > bb2)
void lb_lbfluid_print_boundary (const std::string &filename)
void lb_lbfluid_print_velocity (const std::string &filename)
void lb_lbfluid_save_checkpoint (const std::string &filename, bool binary)
void lb_lbfluid_load_checkpoint (const std::string &filename, bool binary)
Utils::Vector3i lb_lbfluid_get_shape ()
returns the shape of the LB fluid lattice
bool lb_lbnode_is_index_valid (Utils::Vector3i const &ind)
Checks whether the given node index is within the LB lattice.
double lb_lbnode_get_density (const Utils::Vector3i &ind)
Get the LB fluid density for a single node.
const Utils::Vector3d lb_lbnode_get_velocity (const Utils::Vector3i &ind)
Get the LB fluid velocity for a single node.
const Utils::Vector6d lb_lbnode_get_pressure_tensor (const Utils::Vector3i &ind)
const Utils::Vector6d lb_lbnode_get_pressure_tensor_neq (const Utils::Vector3i &ind)
const Utils::Vector6d lb_lbfluid_get_pressure_tensor ()
Calculate the average pressure tensor of all nodes by accumulating over all nodes and dividing by the number of nodes.
int lb_lbnode_get_boundary (const Utils::Vector3i &ind)
Get the LB fluid boundary bool for a single node.
const Utils::Vector19d lb_lbnode_get_pop (const Utils::Vector3i &ind)
Get the LB fluid populations for a single node.
void lb_lbnode_set_density (const Utils::Vector3i &ind, double p_density)
Set the LB density for a single node.
void lb_lbnode_set_velocity (const Utils::Vector3i &ind, const Utils::Vector3d &u)
Set the LB fluid velocity for a single node.
void lb_lbnode_set_pop (const Utils::Vector3i &ind, const Utils::Vector19d &p_pop)
Set the LB fluid populations for a single node.
static void mpi_lb_lbfluid_calc_fluid_momentum_local ()
Utils::Vector3d lb_lbfluid_calc_fluid_momentum ()
const Utils::Vector3d lb_lbfluid_get_interpolated_velocity (const Utils::Vector3d &pos)
Calculates the interpolated fluid velocity on the head node process.
double lb_lbfluid_get_interpolated_density (const Utils::Vector3d &pos)
Calculates the interpolated fluid density on the head node process.
void mpi_set_lattice_switch_local (ActiveLB lattice_switch)
void mpi_set_lattice_switch (ActiveLB lattice_switch)
Variables
ActiveLB lattice_switch = ActiveLB::NONE
Switch determining the type of lattice dynamics.
Function Documentation
check_tau_time_step_consistency()
void check_tau_time_step_consistency (double tau, double time_step)
Check if tau is an integer multiple of time_step, throws if not.
Definition at line 401 of file lb_interface.cpp.
References time_step.
Referenced by lb_lbfluid_sanity_checks(), and mpi_set_time_step().
lb_boundary_mach_check()
void lb_boundary_mach_check () inline
Check the boundary velocities.
Definition at line 90 of file lb_interface.cpp.
References runtimeErrorMsg, and LBBoundaries::sanity_check_mach_limit().
Referenced by lb_lbfluid_sanity_checks().
lb_lbfluid_calc_fluid_momentum()
Utils::Vector3d lb_lbfluid_calc_fluid_momentum ()
Definition at line 1108 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_calc_fluid_momentum(), lb_calc_fluid_momentum_GPU(), lbfields, lblattice, lbpar, mpi_call(), and mpi_lb_lbfluid_calc_fluid_momentum_local().
Referenced by REGISTER_CALLBACK_REDUCTION().
lb_lbfluid_get_agrid()
double lb_lbfluid_get_agrid ()
Get the LB grid spacing.
Definition at line 339 of file lb_interface.cpp.
References LB_parameters_gpu::agrid, LB_Parameters::agrid, CPU, GPU, lattice_switch, lbpar, and lbpar_gpu.
Referenced by ScriptInterface::LBBoundaries::LBBoundary::do_call_method(), ek_lb_print_vtk_density(), in_local_halo(), lb_lbfluid_get_lattice_speed(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_velocity(), and Observables::LBFluidPressureTensor::operator()().
lb_lbfluid_get_bulk_viscosity()
double lb_lbfluid_get_bulk_viscosity ()
Get the global LB bulk viscosity.
Definition at line 248 of file lb_interface.cpp.
References LB_parameters_gpu::bulk_viscosity, LB_Parameters::bulk_viscosity, CPU, GPU, lattice_switch, lbpar, and lbpar_gpu.
lb_lbfluid_get_density()
double lb_lbfluid_get_density ()
Get the global LB density.
Definition at line 189 of file lb_interface.cpp.
References CPU, LB_Parameters::density, GPU, lattice_switch, lbpar, lbpar_gpu, and LB_parameters_gpu::rho.
Referenced by lb_lbfluid_get_pressure_tensor(), and lb_lbnode_get_pressure_tensor().
lb_lbfluid_get_ext_force_density()
const Utils::Vector3d lb_lbfluid_get_ext_force_density ()
Get the external force density acting on the LB fluid.
Definition at line 371 of file lb_interface.cpp.
References CPU, LB_parameters_gpu::ext_force_density, LB_Parameters::ext_force_density, GPU, lattice_switch, lbpar, and lbpar_gpu.
lb_lbfluid_get_gamma_even()
double lb_lbfluid_get_gamma_even ()
Get the global LB relaxation parameter for even modes.
Definition at line 308 of file lb_interface.cpp.
References CPU, LB_parameters_gpu::gamma_even, LB_Parameters::gamma_even, GPU, lattice_switch, lbpar, and lbpar_gpu.
lb_lbfluid_get_gamma_odd()
double lb_lbfluid_get_gamma_odd ()
Get the global LB relaxation parameter for odd modes.
Definition at line 278 of file lb_interface.cpp.
References CPU, LB_parameters_gpu::gamma_odd, LB_Parameters::gamma_odd, GPU, lattice_switch, lbpar, and lbpar_gpu.
lb_lbfluid_get_interpolated_density()
double lb_lbfluid_get_interpolated_density (const Utils::Vector3d & pos)
Calculates the interpolated fluid density on the head node process.
Parameters
pos Position at which the density is to be calculated.
Return values
interpolated fluid density.
Definition at line 1154 of file lb_interface.cpp.
References box_geo, CPU, folded_position(), GPU, anonymous_namespace{lb_interpolation.cpp}::interpolation_order, lattice_switch, lb_lbinterpolation_get_interpolation_order(), linear, mpi_call(), mpi_lb_get_interpolated_density(), Communication::Result::one_rank, pos, and quadratic.
Referenced by Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate().
lb_lbfluid_get_interpolated_velocity()
const Utils::Vector3d lb_lbfluid_get_interpolated_velocity (const Utils::Vector3d & pos)
Calculates the interpolated fluid velocity on the head node process.
Parameters
pos Position at which the velocity is to be calculated.
Return values
interpolated fluid velocity.
Definition at line 1122 of file lb_interface.cpp.
References box_geo, CPU, folded_position(), GPU, anonymous_namespace{lb_interpolation.cpp}::interpolation_order, lattice_switch, lb_get_interpolated_velocity_gpu< 27 >(), lb_get_interpolated_velocity_gpu< 8 >(), lb_lbinterpolation_get_interpolation_order(), linear, mpi_call(), mpi_lb_get_interpolated_velocity(), Communication::Result::one_rank, pos, and quadratic.
Referenced by Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfile::operator()(), and Observables::LBVelocityProfile::operator()().
lb_lbfluid_get_kT()
double lb_lbfluid_get_kT ()
Get the thermal energy parameter of the LB fluid.
Definition at line 453 of file lb_interface.cpp.
References CPU, GPU, LB_parameters_gpu::kT, LB_Parameters::kT, lattice_switch, lbpar, and lbpar_gpu.
Referenced by lb_lbcoupling_calc_particle_lattice_ia(), lb_lbcoupling_propagate(), and lb_lbfluid_propagate().
lb_lbfluid_get_lattice_speed()
double lb_lbfluid_get_lattice_speed ()
Get the lattice speed (agrid/tau).
Definition at line 465 of file lb_interface.cpp.
References lb_lbfluid_get_agrid(), and lb_lbfluid_get_tau().
Referenced by anonymous_namespace{lb_particle_coupling.cpp}::add_md_force(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), LBBoundaries::lb_init_boundaries(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_velocity(), lb_viscous_coupling(), Observables::CylindricalLBVelocityProfile::operator()(), Observables::LBVelocityProfile::operator()(), and LBBoundaries::sanity_check_mach_limit().
lb_lbfluid_get_lattice_switch()
ActiveLB lb_lbfluid_get_lattice_switch ()
Get the global variable lattice_switch.
Definition at line 48 of file lb_interface.cpp.
References lattice_switch.
Referenced by integrate(), and mpi_set_time_step().
lb_lbfluid_get_pressure_tensor()
const Utils::Vector6d lb_lbfluid_get_pressure_tensor ()
Calculate the average pressure tensor of all nodes by accumulating over all nodes and dividing by the number of nodes.
Returns the lower triangle of the LB pressure tensor.
Definition at line 968 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_lbfluid_get_density(), lb_lbfluid_get_shape(), lb_lbnode_get_pressure_tensor(), lbpar_gpu, node, LB_parameters_gpu::number_of_nodes, Utils::product(), and stress_tensor_GPU().
Referenced by Observables::LBFluidPressureTensor::operator()().
lb_lbfluid_get_rng_state()
uint64_t lb_lbfluid_get_rng_state ()
Get the current counter of the Philox RNG.
Definition at line 147 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_fluid_get_rng_state(), and lb_fluid_get_rng_state_gpu().
lb_lbfluid_get_shape()
Utils::Vector3i lb_lbfluid_get_shape ()
returns the shape of the LB fluid lattice
Definition at line 878 of file lb_interface.cpp.
References CPU, LB_parameters_gpu::dim, Lattice::global_grid, GPU, lattice_switch, lblattice, and lbpar_gpu.
Referenced by lb_lbfluid_get_pressure_tensor(), lb_lbfluid_load_checkpoint(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_velocity(), lb_lbfluid_save_checkpoint(), and lb_lbnode_is_index_valid().
lb_lbfluid_get_tau()
double lb_lbfluid_get_tau ()
Get the LB time step.
Definition at line 416 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lbpar, lbpar_gpu, LB_parameters_gpu::tau, and LB_Parameters::tau.
Referenced by ScriptInterface::LBBoundaries::LBBoundary::do_call_method(), integrate(), lb_lbfluid_get_lattice_speed(), lb_lbfluid_sanity_checks(), mpi_set_time_step(), and Observables::LBFluidPressureTensor::operator()().
lb_lbfluid_get_viscosity()
double lb_lbfluid_get_viscosity ()
Get the global LB viscosity.
Definition at line 217 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lbpar, lbpar_gpu, LB_parameters_gpu::viscosity, and LB_Parameters::viscosity.
lb_lbfluid_init()
void lb_lbfluid_init ()
Perform a full initialization of the lattice Boltzmann system.
Perform a full initialization of the lattice-Boltzmann system.
All derived parameters and the fluid are reset to their default values.
Definition at line 137 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_init(), lb_init_gpu(), lbpar, and this_node.
Referenced by on_boxl_change().
lb_lbfluid_integrate()
void lb_lbfluid_integrate ()
Definition at line 54 of file lb_interface.cpp.
References CPU, ek_initialized, ek_integrate(), GPU, lattice_switch, lb_integrate(), lb_integrate_GPU(), and this_node.
Referenced by lb_lbfluid_propagate().
lb_lbfluid_load_checkpoint()
void lb_lbfluid_load_checkpoint (const std::string & filename, bool binary)
Definition at line 802 of file lb_interface.cpp.
References CPU, DENSITY, GPU, lattice_switch, lb_lbfluid_get_shape(), lb_lbnode_set_pop(), lb_load_checkpoint_GPU(), lbpar_gpu, mpi_bcast_lb_params(), D3Q19::n_vel, and LB_parameters_gpu::number_of_nodes.
lb_lbfluid_on_integration_start()
void lb_lbfluid_on_integration_start ()
Event handler for integration start.
Definition at line 115 of file lb_interface.cpp.
References CPU, halo_communication(), lattice_switch, lbfluid, and update_halo_comm.
Referenced by on_integration_start().
lb_lbfluid_print_boundary()
void lb_lbfluid_print_boundary (const std::string & filename)
Definition at line 596 of file lb_interface.cpp.
References LB_parameters_gpu::dim, GPU, lattice_switch, lb_get_boundary_flags_GPU(), lb_lbfluid_get_agrid(), lb_lbfluid_get_shape(), lb_lbnode_get_boundary(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, and pos.
lb_lbfluid_print_velocity()
void lb_lbfluid_print_velocity (const std::string & filename)
Definition at line 639 of file lb_interface.cpp.
References LB_parameters_gpu::dim, GPU, host_values, lattice_switch, lb_get_values_GPU(), lb_lbfluid_get_agrid(), lb_lbfluid_get_lattice_speed(), lb_lbfluid_get_shape(), lb_lbnode_get_velocity(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, pos, and velocity().
lb_lbfluid_print_vtk_boundary()
void lb_lbfluid_print_vtk_boundary (const std::string & filename)
Definition at line 469 of file lb_interface.cpp.
References GPU, lattice_switch, lb_get_boundary_flags_GPU(), lb_lbfluid_get_agrid(), lb_lbfluid_get_shape(), lb_lbnode_get_boundary(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, pos, and Utils::product().
lb_lbfluid_print_vtk_velocity()
void lb_lbfluid_print_vtk_velocity (const std::string & filename, std::vector< int > bb1, std::vector< int > bb2)
Definition at line 522 of file lb_interface.cpp.
References GPU, host_values, lattice_switch, lb_get_values_GPU(), lb_lbfluid_get_agrid(), lb_lbfluid_get_lattice_speed(), lb_lbfluid_get_shape(), lb_lbnode_get_velocity(), lbpar_gpu, anonymous_namespace{Correlator.cpp}::min(), LB_parameters_gpu::number_of_nodes, pos, and Utils::product().
lb_lbfluid_propagate()
void lb_lbfluid_propagate ()
Propagate the LB fluid.
Definition at line 72 of file lb_interface.cpp.
References CPU, GPU, Utils::Counter< T >::increment(), lattice_switch, lb_lbfluid_get_kT(), lb_lbfluid_integrate(), NONE, rng_counter_fluid, and rng_counter_fluid_gpu.
Referenced by integrate().
lb_lbfluid_reinit_parameters()
void lb_lbfluid_reinit_parameters ()
(Re-)initialize the fluid.
Reinitialize the derived parameters for the lattice-Boltzmann system.
Definition at line 123 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_reinit_parameters(), lb_reinit_parameters_gpu(), lbpar, and this_node.
Referenced by lb_lbfluid_set_bulk_viscosity(), lb_lbfluid_set_density(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_tau(), lb_lbfluid_set_viscosity(), on_temperature_change(), and on_timestep_change().
lb_lbfluid_sanity_checks()
void lb_lbfluid_sanity_checks (double time_step)
Perform LB parameter and boundary velocity checks.
Definition at line 98 of file lb_interface.cpp.
References check_tau_time_step_consistency(), CPU, GPU, lattice_switch, lb_boundary_mach_check(), lb_GPU_sanity_checks(), lb_lbfluid_get_tau(), lb_sanity_checks(), lbpar, this_node, and time_step.
Referenced by on_integration_start().
lb_lbfluid_save_checkpoint()
void lb_lbfluid_save_checkpoint (const std::string & filename, bool binary)
Definition at line 747 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_lbfluid_get_shape(), lb_save_checkpoint_GPU(), lbpar_gpu, mpi_call(), mpi_lb_get_populations(), D3Q19::n_vel, LB_parameters_gpu::number_of_nodes, and Communication::Result::one_rank.
lb_lbfluid_set_agrid()
void lb_lbfluid_set_agrid (double agrid)
Set the global LB lattice spacing.
Definition at line 320 of file lb_interface.cpp.
References AGRID, LB_Parameters::agrid, CPU, GPU, lattice_switch, LBBoundaries::lb_init_boundaries(), lb_init_gpu(), lb_set_agrid_gpu(), lbpar, and mpi_bcast_lb_params().
lb_lbfluid_set_bulk_viscosity()
void lb_lbfluid_set_bulk_viscosity (double bulk_viscosity)
Set the global LB bulk viscosity.
Definition at line 229 of file lb_interface.cpp.
References LB_parameters_gpu::bulk_viscosity, LB_Parameters::bulk_viscosity, BULKVISC, CPU, GPU, LB_parameters_gpu::is_TRT, LB_Parameters::is_TRT, lattice_switch, lb_lbfluid_reinit_parameters(), lbpar, lbpar_gpu, and mpi_bcast_lb_params().
lb_lbfluid_set_density()
void lb_lbfluid_set_density (double density)
Set the global LB density.
Definition at line 171 of file lb_interface.cpp.
References CPU, DENSITY, LB_Parameters::density, GPU, lattice_switch, lb_lbfluid_reinit_parameters(), lb_reinit_fluid_gpu(), lbpar, lbpar_gpu, mpi_bcast_lb_params(), and LB_parameters_gpu::rho.
lb_lbfluid_set_ext_force_density()
void lb_lbfluid_set_ext_force_density (const Utils::Vector3d & force_density)
Set the external force density acting on the LB fluid.
Definition at line 351 of file lb_interface.cpp.
References CPU, EXT_FORCE_DENSITY, LB_parameters_gpu::ext_force_density, LB_Parameters::ext_force_density, LB_parameters_gpu::external_force_density, GPU, lattice_switch, lb_reinit_extern_nodeforce_GPU(), lbpar, lbpar_gpu, and mpi_bcast_lb_params().
lb_lbfluid_set_gamma_even()
void lb_lbfluid_set_gamma_even (double gamma_even)
Set the global LB relaxation parameter for even modes.
Definition at line 290 of file lb_interface.cpp.
References CPU, DENSITY, LB_parameters_gpu::gamma_even, LB_Parameters::gamma_even, GPU, LB_parameters_gpu::is_TRT, LB_Parameters::is_TRT, lattice_switch, lb_lbfluid_reinit_parameters(), lbpar, lbpar_gpu, and mpi_bcast_lb_params().
lb_lbfluid_set_gamma_odd()
void lb_lbfluid_set_gamma_odd (double gamma_odd)
Set the global LB relaxation parameter for odd modes.
Definition at line 260 of file lb_interface.cpp.
References CPU, GAMMA_ODD, LB_parameters_gpu::gamma_odd, LB_Parameters::gamma_odd, GPU, LB_parameters_gpu::is_TRT, LB_Parameters::is_TRT, lattice_switch, lb_lbfluid_reinit_parameters(), lbpar, lbpar_gpu, and mpi_bcast_lb_params().
lb_lbfluid_set_kT()
void lb_lbfluid_set_kT (double kT)
Set the LB fluid thermal energy.
Definition at line 440 of file lb_interface.cpp.
References CPU, GPU, KT, LB_parameters_gpu::kT, LB_Parameters::kT, lattice_switch, lbpar, lbpar_gpu, and mpi_bcast_lb_params().
lb_lbfluid_set_lattice_switch()
void lb_lbfluid_set_lattice_switch (ActiveLB local_lattice_switch)
Set the global variable lattice_switch.
Definition at line 428 of file lb_interface.cpp.
References CPU, GPU, mpi_set_lattice_switch(), and NONE.
lb_lbfluid_set_rng_state()
void lb_lbfluid_set_rng_state (uint64_t counter)
Set the current counter of the Philox RNG.
Definition at line 159 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_fluid_set_rng_state(), and lb_fluid_set_rng_state_gpu().
lb_lbfluid_set_tau()
void lb_lbfluid_set_tau (double tau)
Set the LB time step.
Definition at line 385 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_lbfluid_reinit_parameters(), lbpar, lbpar_gpu, mpi_bcast_lb_params(), TAU, LB_parameters_gpu::tau, and LB_Parameters::tau.
lb_lbfluid_set_viscosity()
void lb_lbfluid_set_viscosity (double viscosity)
Set the global LB viscosity.
Definition at line 201 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_lbfluid_reinit_parameters(), lbpar, lbpar_gpu, mpi_bcast_lb_params(), VISCOSITY, LB_parameters_gpu::viscosity, and LB_Parameters::viscosity.
lb_lbnode_get_boundary()
int lb_lbnode_get_boundary (const Utils::Vector3i & ind)
Get the LB fluid boundary bool for a single node.
Definition at line 1004 of file lb_interface.cpp.
References calculate_node_index(), CPU, GPU, lattice_switch, lb_get_boundary_flag_GPU(), lbpar_gpu, mpi_call(), mpi_lb_get_boundary_flag(), and Communication::Result::one_rank.
Referenced by lb_lbfluid_print_boundary(), and lb_lbfluid_print_vtk_boundary().
lb_lbnode_get_density()
double lb_lbnode_get_density (const Utils::Vector3i & ind)
Get the LB fluid density for a single node.
Definition at line 897 of file lb_interface.cpp.
References calculate_node_index(), CPU, GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, mpi_lb_get_density(), Communication::mpiCallbacks(), Communication::Result::one_rank, and LB_rho_v_pi_gpu::rho.
Referenced by lb_lbnode_set_density(), and lb_lbnode_set_velocity().
lb_lbnode_get_pop()
const Utils::Vector19d lb_lbnode_get_pop (const Utils::Vector3i & ind)
Get the LB fluid populations for a single node.
Definition at line 1020 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_lbfluid_get_population(), mpi_call(), mpi_lb_get_populations(), D3Q19::n_vel, and Communication::Result::one_rank.
lb_lbnode_get_pressure_tensor()
const Utils::Vector6d lb_lbnode_get_pressure_tensor (const Utils::Vector3i & ind)
Definition at line 935 of file lb_interface.cpp.
References lb_lbfluid_get_density(), and lb_lbnode_get_pressure_tensor_neq().
Referenced by lb_lbfluid_get_pressure_tensor(), lb_lbnode_set_density(), and lb_lbnode_set_velocity().
lb_lbnode_get_pressure_tensor_neq()
const Utils::Vector6d lb_lbnode_get_pressure_tensor_neq (const Utils::Vector3i & ind)
Definition at line 948 of file lb_interface.cpp.
References calculate_node_index(), CPU, GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, mpi_call(), mpi_lb_get_pressure_tensor(), Communication::Result::one_rank, and LB_rho_v_pi_gpu::pi.
Referenced by lb_lbnode_get_pressure_tensor().
lb_lbnode_get_velocity()
const Utils::Vector3d lb_lbnode_get_velocity (const Utils::Vector3i & ind)
Get the LB fluid velocity for a single node.
Definition at line 913 of file lb_interface.cpp.
References calculate_node_index(), CPU, GPU, lattice_switch, lb_print_node_GPU(), lbpar_gpu, mpi_lb_get_density(), mpi_lb_get_momentum_density(), Communication::mpiCallbacks(), Communication::Result::one_rank, and LB_rho_v_pi_gpu::v.
Referenced by lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_velocity(), and lb_lbnode_set_density().
lb_lbnode_is_index_valid()
bool lb_lbnode_is_index_valid (Utils::Vector3i const & ind)
Checks whether the given node index is within the LB lattice.
Definition at line 892 of file lb_interface.cpp.
References lb_lbfluid_get_shape().
lb_lbnode_set_density()
void lb_lbnode_set_density (const Utils::Vector3i & ind, double p_density)
Set the LB density for a single node.
Definition at line 1039 of file lb_interface.cpp.
References calculate_node_index(), CPU, GPU, lattice_switch, lb_get_population_from_density_momentum_density_stress(), lb_lbnode_get_density(), lb_lbnode_get_pressure_tensor(), lb_lbnode_get_velocity(), lb_set_node_rho_GPU(), lbpar_gpu, mpi_call_all(), and mpi_lb_set_population().
lb_lbnode_set_pop()
void lb_lbnode_set_pop (const Utils::Vector3i & ind, const Utils::Vector19d & p_pop)
Set the LB fluid populations for a single node.
Definition at line 1084 of file lb_interface.cpp.
References CPU, GPU, lattice_switch, lb_lbfluid_set_population(), mpi_call_all(), mpi_lb_set_population(), and D3Q19::n_vel.
Referenced by lb_lbfluid_load_checkpoint().
lb_lbnode_set_velocity()
void lb_lbnode_set_velocity (const Utils::Vector3i & ind, const Utils::Vector3d & u)
Set the LB fluid velocity for a single node.
Definition at line 1059 of file lb_interface.cpp.
References calculate_node_index(), CPU, GPU, lattice_switch, lb_get_population_from_density_momentum_density_stress(), lb_lbnode_get_density(), lb_lbnode_get_pressure_tensor(), lb_set_node_velocity_GPU(), lbpar_gpu, mpi_call_all(), mpi_lb_set_force_density(), mpi_lb_set_population(), and u.
mpi_lb_lbfluid_calc_fluid_momentum_local()
static void mpi_lb_lbfluid_calc_fluid_momentum_local () static
Definition at line 1102 of file lb_interface.cpp.
References lb_calc_fluid_momentum(), lbfields, lblattice, and lbpar.
Referenced by lb_lbfluid_calc_fluid_momentum().
mpi_set_lattice_switch()
void mpi_set_lattice_switch (ActiveLB lattice_switch)
Definition at line 1180 of file lb_interface.cpp.
References lattice_switch, mpi_call_all(), and mpi_set_lattice_switch_local().
Referenced by lb_lbfluid_set_lattice_switch().
mpi_set_lattice_switch_local()
void mpi_set_lattice_switch_local (ActiveLB lattice_switch)
Definition at line 1174 of file lb_interface.cpp.
References lattice_switch.
Referenced by mpi_set_lattice_switch().
Variable Documentation
lattice_switch
ActiveLB lattice_switch = ActiveLB::NONE
Switch determining the type of lattice dynamics.
Definition at line 46 of file lb_interface.cpp.
Referenced by ek_init(), global_ghost_flags(), IBM_UpdateParticlePositions(), LBBoundaries::lb_init_boundaries(), lb_lbcoupling_calc_particle_lattice_ia(), lb_lbcoupling_deactivate(), lb_lbcoupling_get_rng_state(), lb_lbcoupling_is_seed_required(), lb_lbcoupling_propagate(), lb_lbcoupling_set_rng_state(), lb_lbfluid_calc_fluid_momentum(), lb_lbfluid_get_agrid(), lb_lbfluid_get_bulk_viscosity(), lb_lbfluid_get_density(), lb_lbfluid_get_ext_force_density(), lb_lbfluid_get_gamma_even(), lb_lbfluid_get_gamma_odd(), lb_lbfluid_get_interpolated_density(), lb_lbfluid_get_interpolated_velocity(), lb_lbfluid_get_kT(), lb_lbfluid_get_lattice_switch(), lb_lbfluid_get_pressure_tensor(), lb_lbfluid_get_rng_state(), lb_lbfluid_get_shape(), lb_lbfluid_get_tau(), lb_lbfluid_get_viscosity(), lb_lbfluid_init(), lb_lbfluid_integrate(), lb_lbfluid_load_checkpoint(), lb_lbfluid_on_integration_start(), lb_lbfluid_print_boundary(), lb_lbfluid_print_velocity(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_velocity(), lb_lbfluid_propagate(), lb_lbfluid_reinit_parameters(), lb_lbfluid_sanity_checks(), lb_lbfluid_save_checkpoint(), lb_lbfluid_set_agrid(), lb_lbfluid_set_bulk_viscosity(), lb_lbfluid_set_density(), lb_lbfluid_set_ext_force_density(), lb_lbfluid_set_gamma_even(), lb_lbfluid_set_gamma_odd(), lb_lbfluid_set_kT(), lb_lbfluid_set_rng_state(), lb_lbfluid_set_tau(), lb_lbfluid_set_viscosity(), lb_lbnode_get_boundary(), lb_lbnode_get_density(), lb_lbnode_get_pop(), lb_lbnode_get_pressure_tensor_neq(), lb_lbnode_get_velocity(), lb_lbnode_set_density(), lb_lbnode_set_pop(), lb_lbnode_set_velocity(), LBBoundaries::lbboundary_get_force(), mpi_set_lattice_switch(), and mpi_set_lattice_switch_local().