ESPResSo: lb_inertialess_tracers.cpp File Reference
lb_inertialess_tracers.cpp File Reference
Main of the Bayreuth Immersed-Boundary implementation.
#include "config.hpp"
#include "virtual_sites/lb_inertialess_tracers.hpp"
#include "Particle.hpp"
#include "cells.hpp"
#include "grid.hpp"
#include "grid_based_algorithms/lb.hpp"
#include "grid_based_algorithms/lb_boundaries.hpp"
#include "grid_based_algorithms/lb_interface.hpp"
#include "grid_based_algorithms/lb_particle_coupling.hpp"
#include "integrate.hpp"
#include "lb_inertialess_tracers_cuda_interface.hpp"
#include <utils/Vector.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
#include <cstddef>
#include <unordered_set>
Functions
void CoupleIBMParticleToFluid (Particle const &p, Utils::Vector3d const &pos)
Put the momentum of a given particle into the LB fluid.
void ParticleVelocitiesFromLB_CPU ()
Get particle velocities from LB and set the velocity field in the particles data structure.
bool IsHalo (std::size_t indexCheck)
Build a cache structure which contains a flag for each LB node whether that node is a halo node or not.
void IBM_ForcesIntoFluid_CPU ()
Put the calculated force stored on the ibm particles into the fluid by updating the lbfields structure.
void IBM_UpdateParticlePositions (ParticleRange const &particles, double time_step, int this_node)
Interpolate LB velocity at the particle positions and propagate the particles.
template<bool ReturnVelocity>
Utils::Vector3d GetIBMInterpolatedVelocity (Utils::Vector3d const &pos)
Calculate the LB fluid velocity at a particle position.
bool in_local_domain (Utils::Vector3d const &pos, double halo=0.)
Check if a position is within the local box + halo.
Variables
static bool * isHaloCache = nullptr
Detailed Description
Main of the Bayreuth Immersed-Boundary implementation.
Definition in file lb_inertialess_tracers.cpp.
Function Documentation
CoupleIBMParticleToFluid()
void CoupleIBMParticleToFluid (Particle const & p, Utils::Vector3d const & pos)
Put the momentum of a given particle into the LB fluid.
Definition at line 110 of file lb_inertialess_tracers.cpp.
References LB_Parameters::agrid, Particle::force(), IsHalo(), lbfields, lblattice, lbpar, Lattice::map_position_to_lattice(), pos, and LB_Parameters::tau.
Referenced by IBM_ForcesIntoFluid_CPU().
GetIBMInterpolatedVelocity()
template<bool ReturnVelocity> Utils::Vector3d GetIBMInterpolatedVelocity (Utils::Vector3d const & pos)
Calculate the LB fluid velocity at a particle position.
Very similar to the velocity interpolation done in standard ESPResSo, except that we add the f/2 contribution, cf. [26]. The fluid velocity is obtained by linear interpolation, cf. eq. (11) in [2].
Definition at line 144 of file lb_inertialess_tracers.cpp.
References LB_Parameters::agrid, LB_Parameters::density, LB_Parameters::ext_force_density, f, lb_calc_modes(), LBBoundaries::lbboundaries, lbfields, lbfluid, lblattice, lbpar, Lattice::map_position_to_lattice(), pos, Utils::sqr(), and LB_Parameters::tau.
IBM_ForcesIntoFluid_CPU()
void IBM_ForcesIntoFluid_CPU ()
Put the calculated force stored on the ibm particles into the fluid by updating the lbfields structure.
Called from the integration loop right after the forces have been calculated.
Definition at line 56 of file lb_inertialess_tracers.cpp.
References cell_structure, CoupleIBMParticleToFluid(), Cells::DATA_PART_FORCE, CellStructure::ghost_particles(), CellStructure::ghosts_update(), in_local_halo(), and CellStructure::local_particles().
IBM_UpdateParticlePositions()
void IBM_UpdateParticlePositions (ParticleRange const & particles, double time_step, int this_node)
Interpolate LB velocity at the particle positions and propagate the particles.
Called from the integration loop right after the LB update.
Definition at line 82 of file lb_inertialess_tracers.cpp.
References cell_structure, CellStructure::check_resort_required(), CPU, GPU, lattice_switch, Cells::particles(), ParticleVelocitiesFromLB_CPU(), ParticleVelocitiesFromLB_GPU(), Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), skin, this_node, and time_step.
in_local_domain()
bool in_local_domain (Utils::Vector3d const & pos, double halo = 0.) inline
Check if a position is within the local box + halo.
Parameters
pos Position to check
halo Halo
Returns
True iff the point is inside of the box up to halo.
Definition at line 249 of file lb_inertialess_tracers.cpp.
References Utils::Vector< T, N >::broadcast(), in_box(), local_geo, LocalBox< T >::my_left(), LocalBox< T >::my_right(), and pos.
Referenced by ParticleVelocitiesFromLB_CPU().
IsHalo()
bool IsHalo (std::size_t indexCheck)
Build a cache structure which contains a flag for each LB node whether that node is a halo node or not.
Definition at line 216 of file lb_inertialess_tracers.cpp.
References Lattice::grid, Lattice::halo_grid, Lattice::halo_grid_volume, Lattice::halo_offset, isHaloCache, and lblattice.
Referenced by CoupleIBMParticleToFluid().
ParticleVelocitiesFromLB_CPU()
void ParticleVelocitiesFromLB_CPU ()
Get particle velocities from LB and set the velocity field in the particles data structure.
Definition at line 259 of file lb_inertialess_tracers.cpp.
References box_geo, cell_structure, CellStructure::ghost_particles(), CellStructure::ghosts_reduce_forces(), in_local_domain(), CellStructure::local_particles(), pos, positions_in_halo(), and should_be_coupled().
Referenced by IBM_UpdateParticlePositions().
Variable Documentation
isHaloCache
bool* isHaloCache = nullptr static
Definition at line 49 of file lb_inertialess_tracers.cpp.
Referenced by IsHalo().