ESPResSo: lb_walberla_init.hpp File Reference
lb_walberla_init.hpp File Reference
#include <walberla_bridge/LatticeWalberla.hpp>
#include <walberla_bridge/lattice_boltzmann/LBWalberlaBase.hpp>
#include <memory>
Functions
std::shared_ptr< LBWalberlaBase > new_lb_walberla_cpu (std::shared_ptr< LatticeWalberla > const &lattice, double viscosity, double density, bool single_precision)
std::shared_ptr< LBWalberlaBase > new_lb_walberla_gpu (std::shared_ptr< LatticeWalberla > const &lattice, double viscosity, double density, bool single_precision)
void set_device_id_per_rank ()
Function Documentation
new_lb_walberla_cpu()
std::shared_ptr< LBWalberlaBase > new_lb_walberla_cpu (std::shared_ptr< LatticeWalberla > const & lattice, double viscosity, double density, bool single_precision)
Definition at line 30 of file lb_walberla_init.cpp.
References density, and stream.
Referenced by ScriptInterface::walberla::LBFluid::make_instance().
new_lb_walberla_gpu()
std::shared_ptr< LBWalberlaBase > new_lb_walberla_gpu (std::shared_ptr< LatticeWalberla > const & lattice, double viscosity, double density, bool single_precision)
Definition at line 52 of file lb_walberla_init.cu.
References density, and stream.
Referenced by ScriptInterface::walberla::LBFluid::make_instance().
set_device_id_per_rank()
void set_device_id_per_rank ()
Definition at line 62 of file lb_walberla_init.cu.
Referenced by ScriptInterface::System::CudaInitHandle::do_call_method().