ESPResSo: lbgpu.hpp File Reference
lbgpu.hpp File Reference
#include "config.hpp"
#include "OptionalCounter.hpp"
#include <utils/Vector.hpp>
#include <utils/index.hpp>
#include <cstddef>
#include <cstdint>
#include <vector>
Classes
struct LB_parameters_gpu
Parameters for the lattice Boltzmann system for GPU.
struct LB_rho_v_pi_gpu
struct LB_node_force_density_gpu
struct LB_rho_v_gpu
Conserved quantities for the lattice Boltzmann system.
Macros
#define LBQ 19
Functions
Exported Functions
void lb_GPU_sanity_checks ()
void lb_get_boundary_force_pointer (float **pointer_address)
void lb_get_para_pointer (LB_parameters_gpu **pointer_address)
void lb_init_gpu ()
Perform a full initialization of the lattice Boltzmann system.
void lb_reinit_parameters_gpu ()
(Re-)initialize the derived parameters for the lattice Boltzmann system.
void lb_reinit_fluid_gpu ()
(Re-)initialize the fluid.
void reset_LB_force_densities_GPU (bool buffer=true)
Reset the forces on the fluid nodes.
void lb_init_GPU (const LB_parameters_gpu &lbpar_gpu)
Initialization for the lb gpu fluid called from host.
void lb_integrate_GPU ()
Integrate the lattice-Boltzmann system for one time step.
void lb_get_values_GPU (LB_rho_v_pi_gpu *host_values)
Setup and call kernel for getting macroscopic fluid values of all nodes.
void lb_print_node_GPU (unsigned single_nodeindex, LB_rho_v_pi_gpu *host_print_values)
Setup and call kernel for getting macroscopic fluid values of a single node.
void lb_init_boundaries_GPU (std::size_t n_lb_boundaries, unsigned number_of_boundnodes, int *host_boundary_node_list, int *host_boundary_index_list, float *lb_bounday_velocity)
Setup and call boundaries from the host.
void lb_set_agrid_gpu (double agrid)
template<std::size_t no_of_neighbours>
void lb_calc_particle_lattice_ia_gpu (bool couple_virtual, double friction, double time_step)
Setup and call particle kernel from the host.
void lb_calc_fluid_mass_GPU (double *mass)
Setup and call kernel to calculate the total momentum of the hole fluid.
void lb_calc_fluid_momentum_GPU (double *host_mom)
Setup and call kernel to calculate the total momentum of the whole fluid.
void lb_get_boundary_flag_GPU (unsigned int single_nodeindex, unsigned int *host_flag)
Setup and call kernel to get the boundary flag of a single node.
void lb_get_boundary_flags_GPU (unsigned int *host_bound_array)
Get all the boundary flags for all nodes.
void lb_set_node_velocity_GPU (unsigned single_nodeindex, float *host_velocity)
Set the net velocity at a single node.
void lb_set_node_rho_GPU (unsigned single_nodeindex, float host_rho)
Set the density at a single node.
void reinit_parameters_GPU (LB_parameters_gpu *lbpar_gpu)
Reinitialize parameters.
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu *lbpar_gpu)
Setup and call extern single node force initialization from the host.
void lb_reinit_GPU (LB_parameters_gpu *lbpar_gpu)
Reinitialization for the lb gpu fluid called from host.
void lb_gpu_get_boundary_forces (std::vector< double > &forces)
void lb_save_checkpoint_GPU (float *host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
void lb_load_checkpoint_GPU (float const *host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
void lb_lbfluid_set_population (const Utils::Vector3i &, float[LBQ])
Interface to set the populations of a specific node for the GPU.
void lb_lbfluid_get_population (const Utils::Vector3i &, float[LBQ])
Interface to get the populations of a specific node for the GPU.
template<std::size_t no_of_neighbours>
void lb_get_interpolated_velocity_gpu (double const *positions, double *velocities, int length)
void linear_velocity_interpolation (double const *positions, double *velocities, int length)
void quadratic_velocity_interpolation (double const *positions, double *velocities, int length)
Utils::Array< float, 6 > stress_tensor_GPU ()
uint64_t lb_fluid_get_rng_state_gpu ()
void lb_fluid_set_rng_state_gpu (uint64_t counter)
uint64_t lb_coupling_get_rng_state_gpu ()
void lb_coupling_set_rng_state_gpu (uint64_t counter)
unsigned int calculate_node_index (LB_parameters_gpu const &lbpar_gpu, Utils::Vector3i const &coord)
Calculate the node index from its coordinates.
Variables
Exported Variables
LB_parameters_gpu lbpar_gpu
Switch indicating momentum exchange between particles and fluid.
std::vector< LB_rho_v_pi_gpu > host_values
LB_node_force_density_gpu node_f
struct for node force density
bool ek_initialized
OptionalCounter rng_counter_fluid_gpu
OptionalCounter rng_counter_coupling_gpu
Detailed Description
Lattice Boltzmann implementation on GPUs.
Implementation in lbgpu.cpp.
Definition in file lbgpu.hpp.
Macro Definition Documentation
LBQ
#define LBQ 19
Definition at line 44 of file lbgpu.hpp.
Function Documentation
calculate_node_index()
unsigned int calculate_node_index (LB_parameters_gpu const & lbpar_gpu, Utils::Vector3i const & coord) inline
Calculate the node index from its coordinates.
Definition at line 222 of file lbgpu.hpp.
References LB_parameters_gpu::dim, Utils::get_linear_index(), and lbpar_gpu.
Referenced by lb_lbnode_get_boundary(), lb_lbnode_get_density(), lb_lbnode_get_pressure_tensor_neq(), lb_lbnode_get_velocity(), lb_lbnode_set_density(), and lb_lbnode_set_velocity().
lb_calc_fluid_mass_GPU()
void lb_calc_fluid_mass_GPU (double * mass)
Setup and call kernel to calculate the total momentum of the hole fluid.
Parameters
mass value of the mass calculated on the GPU
Definition at line 2307 of file lbgpu_cuda.cu.
References calc_mass(), calculate_dim_grid(), cuda_safe_mem, current_nodes, KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and threads_per_block.
lb_calc_fluid_momentum_GPU()
void lb_calc_fluid_momentum_GPU (double * host_mom)
Setup and call kernel to calculate the total momentum of the whole fluid.
Parameters
host_mom value of the momentum calculated on the GPU
Definition at line 2329 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, KERNELCALL, lbpar_gpu, momentum(), node_f, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::tau, and threads_per_block.
Referenced by lb_lbfluid_calc_fluid_momentum().
lb_calc_particle_lattice_ia_gpu()
template<std::size_t no_of_neighbours> void lb_calc_particle_lattice_ia_gpu (bool couple_virtual, double friction, double time_step)
Setup and call particle kernel from the host.
Template Parameters
no_of_neighbours The number of neighbours to consider for interpolation
Definition at line 2214 of file lbgpu_cuda.cu.
References calculate_dim_grid(), current_nodes, gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, LB_parameters_gpu::kT, lbpar_gpu, node_f, rng_counter_coupling_gpu, threads_per_block, time_step, and Utils::Counter< T >::value().
lb_coupling_get_rng_state_gpu()
uint64_t lb_coupling_get_rng_state_gpu ()
Definition at line 2694 of file lbgpu_cuda.cu.
References rng_counter_coupling_gpu, and Utils::Counter< T >::value().
Referenced by lb_lbcoupling_get_rng_state().
lb_coupling_set_rng_state_gpu()
void lb_coupling_set_rng_state_gpu (uint64_t counter)
Definition at line 2686 of file lbgpu_cuda.cu.
References rng_counter_coupling_gpu.
Referenced by lb_lbcoupling_set_rng_state().
lb_fluid_get_rng_state_gpu()
uint64_t lb_fluid_get_rng_state_gpu ()
Definition at line 2698 of file lbgpu_cuda.cu.
References rng_counter_fluid_gpu, and Utils::Counter< T >::value().
Referenced by lb_lbfluid_get_rng_state().
lb_fluid_set_rng_state_gpu()
void lb_fluid_set_rng_state_gpu (uint64_t counter)
Definition at line 2690 of file lbgpu_cuda.cu.
References rng_counter_fluid_gpu.
Referenced by lb_lbfluid_set_rng_state().
lb_get_boundary_flag_GPU()
void lb_get_boundary_flag_GPU (unsigned int single_nodeindex, unsigned int * host_flag)
Setup and call kernel to get the boundary flag of a single node.
Parameters
single_nodeindex number of the node to get the flag for
host_flag here goes the value of the boundary flag
Definition at line 2378 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, KERNELCALL, and lb_get_boundary_flag().
Referenced by lb_lbnode_get_boundary().
lb_get_boundary_flags_GPU()
void lb_get_boundary_flags_GPU (unsigned int * host_bound_array)
Get all the boundary flags for all nodes.
Parameters
host_bound_array here go the values of the boundary flag
Definition at line 2263 of file lbgpu_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, KERNELCALL, lb_get_boundaries(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, and threads_per_block.
Referenced by ek_calculate_boundary_mass(), lb_lbfluid_print_boundary(), and lb_lbfluid_print_vtk_boundary().
lb_get_boundary_force_pointer()
void lb_get_boundary_force_pointer (float ** pointer_address)
Definition at line 2036 of file lbgpu_cuda.cu.
References lb_boundary_force.
Referenced by ek_init().
lb_get_interpolated_velocity_gpu()
template<std::size_t no_of_neighbours> void lb_get_interpolated_velocity_gpu (double const * positions, double * velocities, int length)
Definition at line 2644 of file lbgpu_cuda.cu.
References current_nodes, and device_rho_v.
lb_get_para_pointer()
void lb_get_para_pointer (LB_parameters_gpu ** pointer_address)
Definition at line 2028 of file lbgpu_cuda.cu.
References errexit(), and para.
Referenced by ek_init(), and InitCUDA_IBM().
lb_get_values_GPU()
void lb_get_values_GPU (LB_rho_v_pi_gpu * host_values)
Setup and call kernel for getting macroscopic fluid values of all nodes.
Parameters
host_values struct to save the gpu values
Definition at line 2249 of file lbgpu_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, device_rho_v, get_mesoscopic_values_in_LB_units(), host_values, KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, print_rho_v_pi, and threads_per_block.
Referenced by ek_lb_print_vtk_density(), ek_lb_print_vtk_velocity(), lb_lbfluid_print_velocity(), and lb_lbfluid_print_vtk_velocity().
lb_gpu_get_boundary_forces()
void lb_gpu_get_boundary_forces (std::vector< double > & forces)
Definition at line 2493 of file lbgpu_cuda.cu.
References cuda_safe_mem, lb_boundary_force, and LBBoundaries::lbboundaries.
Referenced by LBBoundaries::lbboundary_get_force().
lb_GPU_sanity_checks()
void lb_GPU_sanity_checks ()
Definition at line 161 of file lbgpu.cpp.
References LB_parameters_gpu::agrid, lbpar_gpu, LB_parameters_gpu::rho, runtimeErrorMsg, LB_parameters_gpu::tau, this_node, and LB_parameters_gpu::viscosity.
Referenced by lb_lbfluid_sanity_checks().
lb_init_boundaries_GPU()
void lb_init_boundaries_GPU (std::size_t host_n_lb_boundaries, unsigned number_of_boundnodes, int * host_boundary_node_list, int * host_boundary_index_list, float * host_lb_boundary_velocity)
Setup and call boundaries from the host.
Parameters
host_n_lb_boundaries Number of LB boundaries
number_of_boundnodes Number of boundnodes
host_boundary_node_list The indices of the boundary nodes
host_boundary_index_list The flag representing the corresponding boundary
host_lb_boundary_velocity The constant velocity at the boundary, set by the user
Definition at line 2141 of file lbgpu_cuda.cu.
References boundaries, calculate_dim_grid(), cuda_safe_mem, init_boundaries(), KERNELCALL, lb_boundary_force, LBBoundaries::lbboundaries, lbpar_gpu, LB_parameters_gpu::number_of_nodes, reset_boundaries(), and threads_per_block.
Referenced by LBBoundaries::lb_init_boundaries().
lb_init_gpu()
void lb_init_gpu ()
Perform a full initialization of the lattice Boltzmann system.
All derived parameters and the fluid are reset to their default values.
Perform a full initialization of the lattice Boltzmann system.
All derived parameters and the fluid are reset to their default values.
Definition at line 151 of file lbgpu.cpp.
References cuda_bcast_global_part_params(), gpu_init_particle_comm(), lb_init_GPU(), lb_reinit_parameters_gpu(), lbpar_gpu, and this_node.
Referenced by ek_init(), lb_lbfluid_init(), and lb_lbfluid_set_agrid().
lb_init_GPU()
void lb_init_GPU (const LB_parameters_gpu & lbpar_gpu)
Initialization for the lb gpu fluid called from host.
Parameters
lbpar_gpu Pointer to parameters to setup the lb field
Definition at line 2045 of file lbgpu_cuda.cu.
References boundaries, LB_nodes_gpu::boundary, LB_nodes_gpu::boundary_velocity, calc_n_from_rho_j_pi(), calculate_dim_grid(), cuda_safe_mem, current_nodes, device_gpu_lb_initialized, device_rho_v, errexit(), LB_node_force_density_gpu::force_density, LB_node_force_density_gpu::force_density_buf, free_realloc_and_clear, LB_boundaries_gpu::index, intflag, KERNELCALL, lbpar_gpu, node_f, nodes_a, nodes_b, LB_parameters_gpu::number_of_nodes, para, LB_nodes_gpu::populations, print_rho_v_pi, reinit_node_force(), reset_boundaries(), threads_per_block, and LB_boundaries_gpu::velocity.
Referenced by lb_init_gpu().
lb_integrate_GPU()
void lb_integrate_GPU ()
Integrate the lattice-Boltzmann system for one time step.
Integrate the lattice-Boltzmann system for one time step.
Definition at line 2449 of file lbgpu_cuda.cu.
References apply_boundaries(), boundaries, calculate_dim_grid(), cuda_safe_mem, current_nodes, device_rho_v, integrate(), intflag, KERNELCALL, LB_parameters_gpu::kT, lb_boundary_force, LBBoundaries::lbboundaries, lbpar_gpu, node_f, nodes_a, nodes_b, LB_parameters_gpu::number_of_nodes, rng_counter_fluid_gpu, threads_per_block, and Utils::Counter< T >::value().
Referenced by ek_integrate(), and lb_lbfluid_integrate().
lb_lbfluid_get_population()
void lb_lbfluid_get_population (const Utils::Vector3i & xyz, float population_host[LBQ])
Interface to get the populations of a specific node for the GPU.
Parameters
[in] xyz Node coordinates
[out] population_host Population
Definition at line 2570 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, KERNELCALL, lb_lbfluid_get_population_kernel(), and LBQ.
Referenced by lb_lbnode_get_pop().
lb_lbfluid_set_population()
void lb_lbfluid_set_population (const Utils::Vector3i & xyz, float population_host[LBQ])
Interface to set the populations of a specific node for the GPU.
Parameters
[in] xyz Node coordinates
[in] population_host Population
Definition at line 2535 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, KERNELCALL, lb_lbfluid_set_population_kernel(), and LBQ.
Referenced by lb_lbnode_set_pop().
lb_load_checkpoint_GPU()
void lb_load_checkpoint_GPU (float const *const host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
Parameters
[in] host_checkpoint_vd LB populations
Definition at line 2364 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, intflag, lbpar_gpu, nodes_a, LB_parameters_gpu::number_of_nodes, and LB_nodes_gpu::populations.
Referenced by lb_lbfluid_load_checkpoint().
lb_print_node_GPU()
void lb_print_node_GPU (unsigned single_nodeindex, LB_rho_v_pi_gpu * host_print_values)
Setup and call kernel for getting macroscopic fluid values of a single node.
Definition at line 2284 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, device_rho_v, KERNELCALL, lb_print_node(), and node_f.
Referenced by lb_lbnode_get_density(), lb_lbnode_get_pressure_tensor_neq(), and lb_lbnode_get_velocity().
lb_reinit_extern_nodeforce_GPU()
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu * lbpar_gpu)
Setup and call extern single node force initialization from the host.
Parameters
lbpar_gpu Host parameter struct
Definition at line 2200 of file lbgpu_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, para, reinit_node_force(), and threads_per_block.
Referenced by lb_lbfluid_set_ext_force_density(), and lb_reinit_fluid_gpu().
lb_reinit_fluid_gpu()
void lb_reinit_fluid_gpu ()
(Re-)initialize the fluid.
(Re-)initialize the fluid.
Definition at line 88 of file lbgpu.cpp.
References lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), lb_reinit_parameters_gpu(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, and u.
Referenced by lb_lbfluid_set_density().
lb_reinit_GPU()
void lb_reinit_GPU (LB_parameters_gpu * lbpar_gpu)
Reinitialization for the lb gpu fluid called from host.
Parameters
lbpar_gpu Pointer to parameters to setup the lb field
Definition at line 2118 of file lbgpu_cuda.cu.
References calc_n_from_rho_j_pi(), calculate_dim_grid(), cuda_safe_mem, device_gpu_lb_initialized, device_rho_v, KERNELCALL, lbpar_gpu, node_f, nodes_a, LB_parameters_gpu::number_of_nodes, para, and threads_per_block.
Referenced by lb_reinit_fluid_gpu().
lb_reinit_parameters_gpu()
void lb_reinit_parameters_gpu ()
(Re-)initialize the derived parameters for the lattice Boltzmann system.
The current state of the fluid is unchanged.
(Re-)initialize the derived parameters for the lattice Boltzmann system.
See [17] and [15].
Definition at line 99 of file lbgpu.cpp.
References LB_parameters_gpu::agrid, LB_parameters_gpu::bulk_viscosity, ek_initialized, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_even, LB_parameters_gpu::gamma_odd, LB_parameters_gpu::gamma_shear, get_time_step(), LB_parameters_gpu::is_TRT, LB_parameters_gpu::kT, lb_set_agrid_gpu(), lbpar_gpu, LB_parameters_gpu::mu, reinit_parameters_GPU(), Utils::sqr(), LB_parameters_gpu::tau, and LB_parameters_gpu::viscosity.
Referenced by ek_init(), lb_init_gpu(), lb_lbfluid_reinit_parameters(), and lb_reinit_fluid_gpu().
lb_save_checkpoint_GPU()
void lb_save_checkpoint_GPU (float *const host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
Parameters
[out] host_checkpoint_vd LB populations
Definition at line 2355 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and LB_nodes_gpu::populations.
Referenced by lb_lbfluid_save_checkpoint().
lb_set_agrid_gpu()
void lb_set_agrid_gpu (double agrid)
Definition at line 178 of file lbgpu.cpp.
References LB_parameters_gpu::agrid, box_geo, LB_parameters_gpu::dim, Utils::hadamard_division(), lbpar_gpu, and BoxGeometry::length().
Referenced by lb_lbfluid_set_agrid(), and lb_reinit_parameters_gpu().
lb_set_node_rho_GPU()
void lb_set_node_rho_GPU (unsigned single_nodeindex, float host_rho)
Set the density at a single node.
Parameters
single_nodeindex the node to set the velocity for
host_rho the density to set
Definition at line 2401 of file lbgpu_cuda.cu.
References current_nodes, device_rho_v, KERNELCALL, and set_rho().
Referenced by lb_lbnode_set_density().
lb_set_node_velocity_GPU()
void lb_set_node_velocity_GPU (unsigned single_nodeindex, float * host_velocity)
Set the net velocity at a single node.
Parameters
single_nodeindex the node to set the velocity for
host_velocity the velocity to set
Definition at line 2415 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, device_rho_v, KERNELCALL, node_f, set_force_density(), and set_u_from_rho_v_pi().
Referenced by lb_lbnode_set_velocity().
linear_velocity_interpolation()
void linear_velocity_interpolation (double const * positions, double * velocities, int length)
Definition at line 2676 of file lbgpu_cuda.cu.
References lb_get_interpolated_velocity_gpu< 8 >().
quadratic_velocity_interpolation()
void quadratic_velocity_interpolation (double const * positions, double * velocities, int length)
Definition at line 2681 of file lbgpu_cuda.cu.
References lb_get_interpolated_velocity_gpu< 27 >().
reinit_parameters_GPU()
void reinit_parameters_GPU (LB_parameters_gpu * lbpar_gpu)
Reinitialize parameters.
Parameters
lbpar_gpu struct containing the parameters of the fluid
Definition at line 2443 of file lbgpu_cuda.cu.
References cuda_safe_mem, lbpar_gpu, and para.
Referenced by lb_reinit_parameters_gpu().
reset_LB_force_densities_GPU()
void reset_LB_force_densities_GPU (bool buffer = true)
Reset the forces on the fluid nodes.
Definition at line 271 of file lbgpu_cuda.cu.
References calculate_dim_grid(), KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, reset_LB_force_densities_kernel(), and threads_per_block.
Referenced by ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
stress_tensor_GPU()
Utils::Array<float, 6> stress_tensor_GPU ()
Definition at line 2624 of file lbgpu_cuda.cu.
References current_nodes, device_rho_v, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and LB_nodes_gpu::populations.
Referenced by lb_lbfluid_get_pressure_tensor().
Variable Documentation
ek_initialized
bool ek_initialized
Definition at line 85 of file lbgpu.cpp.
Referenced by lb_reinit_parameters_gpu().
host_values
std::vector<LB_rho_v_pi_gpu> host_values
Referenced by ek_lb_print_vtk_density(), ek_lb_print_vtk_velocity(), lb_get_values_GPU(), lb_lbfluid_print_velocity(), and lb_lbfluid_print_vtk_velocity().
lbpar_gpu
LB_parameters_gpu lbpar_gpu
Switch indicating momentum exchange between particles and fluid.
Definition at line 44 of file lbgpu.cpp.
Referenced by calculate_node_index(), lb_GPU_sanity_checks(), lb_init_gpu(), lb_reinit_fluid_gpu(), lb_reinit_parameters_gpu(), and lb_set_agrid_gpu().
node_f
LB_node_force_density_gpu node_f
struct for node force density
Definition at line 87 of file lbgpu_cuda.cu.
rng_counter_coupling_gpu
OptionalCounter rng_counter_coupling_gpu
Definition at line 115 of file lbgpu_cuda.cu.
Referenced by lb_calc_particle_lattice_ia_gpu(), lb_coupling_get_rng_state_gpu(), lb_coupling_set_rng_state_gpu(), lb_lbcoupling_is_seed_required(), and lb_lbcoupling_propagate().
rng_counter_fluid_gpu
OptionalCounter rng_counter_fluid_gpu
Definition at line 116 of file lbgpu_cuda.cu.
Referenced by lb_fluid_get_rng_state_gpu(), lb_fluid_set_rng_state_gpu(), lb_integrate_GPU(), and lb_lbfluid_propagate().