ESPResSo: lbgpu_cuda.cu File Reference
lbgpu_cuda.cu File Reference
#include "config.hpp"
#include "grid_based_algorithms/OptionalCounter.hpp"
#include "grid_based_algorithms/lb-d3q19.hpp"
#include "grid_based_algorithms/lb_boundaries.hpp"
#include "grid_based_algorithms/lbgpu.cuh"
#include "grid_based_algorithms/lbgpu.hpp"
#include "cuda_interface.hpp"
#include "cuda_utils.cuh"
#include "errorhandling.hpp"
#include <utils/Array.hpp>
#include <utils/Counter.hpp>
#include <thrust/device_ptr.h>
#include <thrust/device_vector.h>
#include <thrust/functional.h>
#include <thrust/host_vector.h>
#include <thrust/iterator/zip_iterator.h>
#include <thrust/transform_reduce.h>
#include <thrust/tuple.h>
#include <cuda.h>
#include <curand_kernel.h>
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>
Classes
struct lb_lbfluid_mass_of_particle
struct interpolation< no_of_neighbours >
Velocity interpolation functor.
struct Plus
struct Stress
Macros
#define BOUNCEBACK()
#define free_realloc_and_clear(var, size)
Functions
template<typename T >
__device__ uint3 index_to_xyz (T index)
Transformation from 1d array-index to xyz.
template<typename T >
__device__ T xyz_to_index (T x, T y, T z)
Transformation from xyz to 1d array-index.
__device__ void calc_m_from_n (Utils::Array< float, 19 > const &populations, Utils::Array< float, 19 > &mode)
Calculate modes from the populations (space-transform).
__device__ void reset_LB_force_densities (unsigned int index, LB_node_force_density_gpu node_f, bool buffer=true)
__global__ void reset_LB_force_densities_kernel (LB_node_force_density_gpu node_f, bool buffer=true)
void reset_LB_force_densities_GPU (bool buffer)
Reset the forces on the fluid nodes.
__device__ void update_rho_v (Utils::Array< float, 19 > const &modes, unsigned int index, LB_node_force_density_gpu const &node_f, LB_rho_v_gpu *d_v)
__device__ void relax_modes (Utils::Array< float, 19 > &mode, unsigned int index, LB_node_force_density_gpu node_f, LB_rho_v_gpu *d_v)
lb_relax_modes, means collision update of the modes
__device__ void thermalize_modes (Utils::Array< float, 19 > &mode, unsigned int index, uint64_t philox_counter)
Thermalization of the modes with Gaussian random numbers.
__device__ void normalize_modes (Utils::Array< float, 19 > &mode)
Normalization of the modes need before back-transformation into velocity space.
__device__ void calc_n_from_modes_push (LB_nodes_gpu n_b, Utils::Array< float, 19 > const &mode, unsigned int index)
Back-transformation from modespace to densityspace and streaming with the push method using pbc.
__device__ void bounce_back_boundaries (LB_nodes_gpu n_curr, LB_boundaries_gpu boundaries, unsigned int index, float *lb_boundary_force)
Bounce back boundary conditions.
__device__ void apply_forces (unsigned int index, Utils::Array< float, 19 > &mode, LB_node_force_density_gpu node_f, LB_rho_v_gpu *d_v)
Add external forces within the modespace, needed for particle-interaction.
__device__ Utils::Array< float, 19 > stress_modes (LB_rho_v_gpu const &rho_v, const Utils::Array< float, 19 > &modes)
__device__ Utils::Array< float, 6 > stress_from_stress_modes (Utils::Array< float, 19 > const &modes)
Calculate the stress tensor.
__device__ void calc_values_in_LB_units (LB_nodes_gpu n_a, Utils::Array< float, 19 > const &modes, LB_rho_v_pi_gpu *d_p_v, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f, unsigned int index, unsigned int print_index)
Calculate hydrodynamic fields in LB units.
__device__ void calc_values_from_m (Utils::Array< float, 19 > const &mode_single, LB_rho_v_gpu const &d_v_single, float *rho_out, float *j_out, Utils::Array< float, 6 > &pi_out)
Calculate hydrodynamic fields in MD units.
__device__ __inline__ float three_point_polynomial_smallerequal_than_half (float u)
Interpolation kernel.
__device__ __inline__ float three_point_polynomial_larger_than_half (float u)
Interpolation kernel.
__device__ __inline__ float3 node_velocity (float rho_eq, LB_nodes_gpu n_a, unsigned index)
Get velocity of at index.
__device__ __inline__ float3 velocity_interpolation (LB_nodes_gpu n_a, float const *particle_position, Utils::Array< unsigned int, 27 > &node_indices, Utils::Array< float, 27 > &delta)
__device__ __inline__ float3 velocity_interpolation (LB_nodes_gpu n_a, float const *particle_position, Utils::Array< unsigned int, 8 > &node_index, Utils::Array< float, 8 > &delta)
Velocity interpolation.
template<std::size_t no_of_neighbours>
__device__ void calc_viscous_force (LB_nodes_gpu n_a, Utils::Array< float, no_of_neighbours > &delta, CUDA_particle_data *particle_data, float *particle_force, unsigned int part_index, float *delta_j, Utils::Array< unsigned int, no_of_neighbours > &node_index, bool flag_cs, uint64_t philox_counter, float friction, float time_step)
Calculate viscous force.
template<std::size_t no_of_neighbours>
__device__ void calc_node_force (Utils::Array< float, no_of_neighbours > const &delta, float const *delta_j, Utils::Array< unsigned int, no_of_neighbours > const &node_index, LB_node_force_density_gpu node_f)
Calculate the node force caused by the particles, with atomicAdd due to avoiding race conditions.
System setup and Kernel functions
__global__ void calc_n_from_rho_j_pi (LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f, bool *gpu_check)
Kernel to calculate local populations from hydrodynamic fields.
__global__ void set_force_density (unsigned single_nodeindex, float const *force_density, LB_node_force_density_gpu node_f)
__global__ void set_u_from_rho_v_pi (LB_nodes_gpu n_a, unsigned single_nodeindex, float const *velocity, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f)
Kernel to calculate local populations from hydrodynamic fields from given flow field velocities.
__global__ void calc_mass (LB_nodes_gpu n_a, float *sum)
Calculate the mass of the whole fluid kernel.
__global__ void reinit_node_force (LB_node_force_density_gpu node_f)
(Re-)initialize the node force density / set the external force density in lb units
__global__ void set_rho (LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, unsigned single_nodeindex, float rho)
Kernel to set the local density.
__global__ void init_boundaries (int const *boundary_node_list, int const *boundary_index_list, float const *boundary_velocities, unsigned number_of_boundnodes, LB_boundaries_gpu boundaries)
Set the boundary flag for all boundary nodes.
__global__ void reset_boundaries (LB_boundaries_gpu boundaries)
Reset the boundary flag of every node.
__global__ void integrate (LB_nodes_gpu n_a, LB_nodes_gpu n_b, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f, uint64_t philox_counter)
Integration step of the LB-fluid-solver.
__global__ void integrate (LB_nodes_gpu n_a, LB_nodes_gpu n_b, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f)
Integration step of the LB-fluid-solver.
template<std::size_t no_of_neighbours>
__global__ void calc_fluid_particle_ia (LB_nodes_gpu n_a, Utils::Span< CUDA_particle_data > particle_data, float *particle_force, LB_node_force_density_gpu node_f, bool couple_virtual, uint64_t philox_counter, float friction, float time_step)
Particle interaction kernel.
__global__ void apply_boundaries (LB_nodes_gpu n_curr, LB_boundaries_gpu boundaries, float *lb_boundary_force)
Bounce back boundary kernel.
__global__ void get_mesoscopic_values_in_LB_units (LB_nodes_gpu n_a, LB_rho_v_pi_gpu *p_v, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f)
Get physical values of the nodes (density, velocity, ...)
__global__ void lb_get_boundaries (LB_nodes_gpu n_a, unsigned int *device_bound_array)
Get boundary flags.
__global__ void lb_print_node (unsigned int single_nodeindex, LB_rho_v_pi_gpu *d_p_v, LB_nodes_gpu n_a, LB_rho_v_gpu *d_v, LB_node_force_density_gpu node_f)
Print single node values kernel.
__global__ void momentum (LB_nodes_gpu n_a, LB_node_force_density_gpu node_f, float *sum)
__global__ void lb_get_boundary_flag (unsigned int single_nodeindex, unsigned int *device_flag, LB_nodes_gpu n_a)
Print single node boundary flag.
void lb_get_para_pointer (LB_parameters_gpu **pointer_address)
void lb_get_boundary_force_pointer (float **pointer_address)
void lb_init_GPU (const LB_parameters_gpu &lbpar_gpu)
Initialization for the lb gpu fluid called from host.
void lb_reinit_GPU (LB_parameters_gpu *lbpar_gpu)
Reinitialization for the lb gpu fluid called from host.
void lb_init_boundaries_GPU (std::size_t host_n_lb_boundaries, unsigned number_of_boundnodes, int *host_boundary_node_list, int *host_boundary_index_list, float *host_lb_boundary_velocity)
Setup and call boundaries from the host.
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu *lbpar_gpu)
Setup and call extern single node force initialization from the host.
template<std::size_t no_of_neighbours>
void lb_calc_particle_lattice_ia_gpu (bool couple_virtual, double friction, double time_step)
Setup and call particle kernel from the host.
template void lb_calc_particle_lattice_ia_gpu< 8 > (bool couple_virtual, double friction, double time_step)
template void lb_calc_particle_lattice_ia_gpu< 27 > (bool couple_virtual, double friction, double time_step)
void lb_get_values_GPU (LB_rho_v_pi_gpu *host_values)
Setup and call kernel for getting macroscopic fluid values of all nodes.
void lb_get_boundary_flags_GPU (unsigned int *host_bound_array)
Get all the boundary flags for all nodes.
void lb_print_node_GPU (unsigned single_nodeindex, LB_rho_v_pi_gpu *host_print_values)
Setup and call kernel for getting macroscopic fluid values of a single node.
void lb_calc_fluid_mass_GPU (double *mass)
Setup and call kernel to calculate the total momentum of the hole fluid.
void lb_calc_fluid_momentum_GPU (double *host_mom)
Setup and call kernel to calculate the total momentum of the whole fluid.
void lb_save_checkpoint_GPU (float *const host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
void lb_load_checkpoint_GPU (float const *const host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
void lb_get_boundary_flag_GPU (unsigned int single_nodeindex, unsigned int *host_flag)
Setup and call kernel to get the boundary flag of a single node.
void lb_set_node_rho_GPU (unsigned single_nodeindex, float host_rho)
Set the density at a single node.
void lb_set_node_velocity_GPU (unsigned single_nodeindex, float *host_velocity)
Set the net velocity at a single node.
void reinit_parameters_GPU (LB_parameters_gpu *lbpar_gpu)
Reinitialize parameters.
void lb_integrate_GPU ()
Integration kernel for the lb gpu fluid update called from host.
void lb_gpu_get_boundary_forces (std::vector< double > &forces)
__global__ void lb_lbfluid_set_population_kernel (LB_nodes_gpu n_a, float const population[LBQ], int x, int y, int z)
Set the populations of a specific node on the GPU.
void lb_lbfluid_set_population (const Utils::Vector3i &xyz, float population_host[LBQ])
Interface to set the populations of a specific node for the GPU.
__global__ void lb_lbfluid_get_population_kernel (LB_nodes_gpu n_a, float population[LBQ], int x, int y, int z)
Get the populations of a specific node on the GPU.
void lb_lbfluid_get_population (const Utils::Vector3i &xyz, float population_host[LBQ])
Interface to get the populations of a specific node for the GPU.
Utils::Array< float, 6 > stress_tensor_GPU ()
template<std::size_t no_of_neighbours>
void lb_get_interpolated_velocity_gpu (double const *positions, double *velocities, int length)
template void lb_get_interpolated_velocity_gpu< 8 > (double const *positions, double *velocities, int length)
template void lb_get_interpolated_velocity_gpu< 27 > (double const *positions, double *velocities, int length)
void linear_velocity_interpolation (double const *positions, double *velocities, int length)
void quadratic_velocity_interpolation (double const *positions, double *velocities, int length)
void lb_coupling_set_rng_state_gpu (uint64_t counter)
void lb_fluid_set_rng_state_gpu (uint64_t counter)
uint64_t lb_coupling_get_rng_state_gpu ()
uint64_t lb_fluid_get_rng_state_gpu ()
Variables
static LB_rho_v_gpu * device_rho_v = nullptr
struct for hydrodynamic fields: this is for internal use (i.e.
static LB_rho_v_pi_gpu * print_rho_v_pi = nullptr
struct for hydrodynamic fields: this is the interface and stores values in MD units.
static LB_boundaries_gpu boundaries
boundary information
LB_node_force_density_gpu node_f
struct for node force density
static float * lb_boundary_force = nullptr
Force on the boundary nodes.
static bool * device_gpu_lb_initialized = nullptr
Whether LB GPU was initialized.
static bool intflag = true
Direction of data transfer between nodes_a and nodes_b during integration in lb_integrate_GPU.
LB_nodes_gpu * current_nodes = nullptr
__device__ __constant__ LB_parameters_gpu para [1]
Parameters residing in constant memory.
static constexpr float sqrt12 = 3.4641016151377544f
static constexpr unsigned int threads_per_block = 64
OptionalCounter rng_counter_coupling_gpu
OptionalCounter rng_counter_fluid_gpu
structs for velocity densities
static LB_nodes_gpu nodes_a
static LB_nodes_gpu nodes_b
Detailed Description
Lattice Boltzmann on GPUs.
The corresponding header file is lbgpu.cuh.
Definition in file lbgpu_cuda.cu.
Macro Definition Documentation
BOUNCEBACK
#define BOUNCEBACK ()
Value:
  shift = 2.0f / para->agrid * para->rho * 3.0f * weight * para->tau *         \
          (v[0] * static_cast<float>(c[0]) + v[1] * static_cast<float>(c[1]) + \
           v[2] * static_cast<float>(c[2]));                                   \
  pop_to_bounce_back = n_curr.populations[index][population];                  \
  to_index_x =                                                                 \
      (x + static_cast<unsigned>(c[0]) + para->dim[0]) % para->dim[0];         \
  to_index_y =                                                                 \
      (y + static_cast<unsigned>(c[1]) + para->dim[1]) % para->dim[1];         \
  to_index_z =                                                                 \
      (z + static_cast<unsigned>(c[2]) + para->dim[2]) % para->dim[2];         \
  to_index = to_index_x + para->dim[0] * to_index_y +                          \
             para->dim[0] * para->dim[1] * to_index_z;                         \
  if (n_curr.boundary[to_index] == 0) {                                        \
    boundary_force[0] +=                                                       \
        (2.0f * pop_to_bounce_back + shift) * static_cast<float>(c[0]);        \
    boundary_force[1] +=                                                       \
        (2.0f * pop_to_bounce_back + shift) * static_cast<float>(c[1]);        \
    boundary_force[2] +=                                                       \
        (2.0f * pop_to_bounce_back + shift) * static_cast<float>(c[2]);        \
    n_curr.populations[to_index][inverse] = pop_to_bounce_back + shift;        \
  }
free_realloc_and_clear
#define free_realloc_and_clear (var, size)
Value:
  {                                                                            \
    if ((var) != nullptr)                                                      \
      cuda_safe_mem(cudaFree((var)));                                          \
    cuda_safe_mem(cudaMalloc((void **)&(var), size));                          \
    cudaMemset(var, 0, size);                                                  \
  }
Function Documentation
apply_boundaries()
__global__ void apply_boundaries (LB_nodes_gpu n_curr, LB_boundaries_gpu boundaries, float * lb_boundary_force)
Bounce back boundary kernel.
Parameters
[in] n_curr Pointer to local node receiving the current node field
[in] boundaries Constant velocity at the boundary, set by the user
[out] lb_boundary_force Force on the boundary nodes
Definition at line 1915 of file lbgpu_cuda.cu.
References bounce_back_boundaries(), boundaries, and lb_boundary_force.
Referenced by lb_integrate_GPU().
apply_forces()
__device__ void apply_forces (unsigned int index, Utils::Array< float, 19 > & mode, LB_node_force_density_gpu node_f, LB_rho_v_gpu * d_v)
Add external forces within the modespace, needed for particle-interaction.
Parameters
[in] index Node index / thread index
[in,out] mode Local register values mode
[in,out] node_f Local node force
[in] d_v Local device values
Definition at line 847 of file lbgpu_cuda.cu.
References LB_node_force_density_gpu::force_density, LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_shear, node_f, para, reset_LB_force_densities(), u, and LB_rho_v_gpu::v.
Referenced by integrate().
bounce_back_boundaries()
__device__ void bounce_back_boundaries (LB_nodes_gpu n_curr, LB_boundaries_gpu boundaries, unsigned int index, float * lb_boundary_force)
Bounce back boundary conditions.
The populations that have propagated into a boundary node are bounced back to the node they came from. This results in no slip boundary conditions, cf. [31].
Parameters
[in] index Node index / thread index
[in] n_curr Local node receiving the current node field
[in] boundaries Constant velocity at the boundary, set by the user
[out] lb_boundary_force Force on the boundary nodes
Definition at line 637 of file lbgpu_cuda.cu.
References BOUNCEBACK, boundaries, LB_nodes_gpu::boundary, D3Q19::c, LB_boundaries_gpu::index, index_to_xyz(), lb_boundary_force, LB_boundaries_gpu::velocity, and weight().
Referenced by apply_boundaries().
calc_fluid_particle_ia()
template<std::size_t no_of_neighbours> __global__ void calc_fluid_particle_ia (LB_nodes_gpu n_a, Utils::Span< CUDA_particle_data > particle_data, float * particle_force, LB_node_force_density_gpu node_f, bool couple_virtual, uint64_t philox_counter, float friction, float time_step)
Particle interaction kernel.
Parameters
[in] n_a Local node residing in array a
[in,out] particle_data Particle position and velocity
[in,out] particle_force Particle force
[out] node_f Local node force
[in] couple_virtual If true, virtual particles are also coupled
[in] philox_counter Philox counter
[in] friction Friction constant for the particle coupling
[in] time_step MD time step
Template Parameters
no_of_neighbours The number of neighbours to consider for interpolation
Definition at line 1874 of file lbgpu_cuda.cu.
References Utils::Span< T >::data(), node_f, philox_counter, Utils::Span< T >::size(), and time_step.
calc_m_from_n()
__device__ void calc_m_from_n (Utils::Array< float, 19 > const & populations, Utils::Array< float, 19 > & mode)
Calculate modes from the populations (space-transform).
Parameters
[in] populations Populations of one node.
[out] mode Modes corresponding to given populations.
The following convention and equations from [16] are used: The \(\hat{c}_i\) are given by:
\begin{align*} c_{ 0} &= (0, 0, 0) \\ c_{ 1} &= (1, 0, 0) \\ c_{ 2} &= (-1, 0, 0) \\ c_{ 3} &= (0, 1, 0) \\ c_{ 4} &= (0,-1, 0) \\ c_{ 5} &= (0, 0, 1) \\ c_{ 6} &= (0, 0,-1) \\ c_{ 7} &= (1, 1, 0) \\ c_{ 8} &= (-1,-1, 0) \\ c_{ 9} &= (1,-1, 0) \\ c_{10} &= (-1, 1, 0) \\ c_{11} &= (1, 0, 1) \\ c_{12} &= (-1, 0,-1) \\ c_{13} &= (1, 0,-1) \\ c_{14} &= (-1, 0, 1) \\ c_{15} &= (0, 1, 1) \\ c_{16} &= (0,-1,-1) \\ c_{17} &= (0, 1,-1) \\ c_{18} &= (0,-1, 1) \end{align*}
The basis vectors (modes) are constructed as follows (eq. (111)):
\[m_k = \sum_{i} e_{ki} n_{i}\]
where the \(e_{ki}\) form a linear transformation (matrix) that is given by (modified from table 1):
\begin{align*} e_{ 0,i} &= 1 \\ e_{ 1,i} &= \hat{c}_{i,x} \\ e_{ 2,i} &= \hat{c}_{i,y} \\ e_{ 3,i} &= \hat{c}_{i,z} \\ e_{ 4,i} &= \hat{c}_{i}^2 - 1 \\ e_{ 5,i} &= \hat{c}_{i,x}^2 - \hat{c}_{i,y}^2 \\ e_{ 6,i} &= \hat{c}_{i}^2 - 3 \hat{c}_{i,z}^2 \\ e_{ 7,i} &= \hat{c}_{i,x} \hat{c}_{i,y} \\ e_{ 8,i} &= \hat{c}_{i,x} \hat{c}_{i,z} \\ e_{ 9,i} &= \hat{c}_{i,y} \hat{c}_{i,z} \\ e_{10,i} &= (3 \hat{c}_{i}^2 - 5) \hat{c}_{i,x} \\ e_{11,i} &= (3 \hat{c}_{i}^2 - 5) \hat{c}_{i,y} \\ e_{12,i} &= (3 \hat{c}_{i}^2 - 5) \hat{c}_{i,z} \\ e_{13,i} &= (\hat{c}_{i,y}^2 - \hat{c}_{i,z}^2) \hat{c}_{i,x} \\ e_{14,i} &= (\hat{c}_{i,x}^2 - \hat{c}_{i,z}^2) \hat{c}_{i,y} \\ e_{15,i} &= (\hat{c}_{i,x}^2 - \hat{c}_{i,y}^2) \hat{c}_{i,z} \\ e_{16,i} &= 3 \hat{c}_{i}^4 - 6 \hat{c}_{i}^2 + 1 \\ e_{17,i} &= (2 \hat{c}_{i}^2 - 3) (\hat{c}_{i,x}^2 - \hat{c}_{i,y}^2) \\ e_{18,i} &= (2 \hat{c}_{i}^2 - 3) (\hat{c}_{i}^2 - 3 \hat{c}_{i,z}^2) \end{align*}
Such that the transformation matrix is given by:
{{ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
 { 0, 1,-1, 0, 0, 0, 0, 1,-1, 1,-1, 1,-1, 1,-1, 0, 0, 0, 0},
 { 0, 0, 0, 1,-1, 0, 0, 1,-1,-1, 1, 0, 0, 0, 0, 1,-1, 1,-1},
 { 0, 0, 0, 0, 0, 1,-1, 0, 0, 0, 0, 1,-1,-1, 1, 1,-1,-1, 1},
 {-1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
 { 0, 1, 1,-1,-1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,-1,-1,-1,-1},
 { 0, 1, 1, 1, 1,-2,-2, 2, 2, 2, 2,-1,-1,-1,-1,-1,-1,-1,-1},
 { 0, 0, 0, 0, 0, 0, 0, 1, 1,-1,-1, 0, 0, 0, 0, 0, 0, 0, 0},
 { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,-1,-1, 0, 0, 0, 0},
 { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,-1,-1},
 { 0,-2, 2, 0, 0, 0, 0, 1,-1, 1,-1, 1,-1, 1,-1, 0, 0, 0, 0},
 { 0, 0, 0,-2, 2, 0, 0, 1,-1,-1, 1, 0, 0, 0, 0, 1,-1, 1,-1},
 { 0, 0, 0, 0, 0,-2, 2, 0, 0, 0, 0, 1,-1,-1, 1, 1,-1,-1, 1},
 { 0, 0, 0, 0, 0, 0, 0, 1,-1, 1,-1,-1, 1,-1, 1, 0, 0, 0, 0},
 { 0, 0, 0, 0, 0, 0, 0, 1,-1,-1, 1, 0, 0, 0, 0,-1, 1,-1, 1},
 { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,-1,-1, 1,-1, 1, 1,-1},
 { 1,-2,-2,-2,-2,-2,-2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
 { 0,-1,-1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,-1,-1,-1,-1},
 { 0,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2,-1,-1,-1,-1,-1,-1,-1,-1}}
with weights
\[q^{c_{i}} = (1/3, 1/18, 1/18, 1/18, 1/18, 1/18, 1/18, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36, 1/36)\]
which makes the transformation satisfy the following orthogonality condition (eq. (109)):
\[\sum_{i} q^{c_{i}} e_{ki} e_{li} = w_{k} \delta_{kl}\]
where the weights are:
\[w_{i} = (1, 1/3, 1/3, 1/3, 2/3, 4/9, 4/3, 1/9, 1/9, 1/9, 2/3, 2/3, 2/3, 2/9, 2/9, 2/9, 2, 4/9, 4/3)\]
Definition at line 142 of file lbgpu_cuda.cu.
References calc_mode_x_from_n().
Referenced by calc_n_from_rho_j_pi(), get_mesoscopic_values_in_LB_units(), integrate(), lb_print_node(), Stress::operator()(), and set_u_from_rho_v_pi().
calc_mass()
__global__ void calc_mass (LB_nodes_gpu n_a, float * sum)
Calculate the mass of the whole fluid kernel.
Parameters
[out] sum Resulting mass
[in] n_a Local node residing in array a
Definition at line 1704 of file lbgpu_cuda.cu.
References calc_mass_and_momentum_mode(), para, LB_parameters_gpu::rho, and sum.
Referenced by lb_calc_fluid_mass_GPU().
calc_n_from_modes_push()
__device__ void calc_n_from_modes_push (LB_nodes_gpu n_b, Utils::Array< float, 19 > const & mode, unsigned int index)
Back-transformation from modespace to densityspace and streaming with the push method using pbc.
Parameters
[in] index Node index / thread index
[in] mode Local register values mode
[out] n_b Local node residing in array b
Definition at line 491 of file lbgpu_cuda.cu.
References LB_parameters_gpu::dim, f, index_to_xyz(), para, and LB_nodes_gpu::populations.
Referenced by integrate().
calc_n_from_rho_j_pi()
__global__ void calc_n_from_rho_j_pi (LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f, bool * gpu_check)
Kernel to calculate local populations from hydrodynamic fields.
The mapping is given in terms of the equilibrium distribution.
Eq. (2.15) [32]. Eq. (4) in [51].
Parameters
[out] n_a Lattice site
[out] gpu_check Additional check if GPU kernel are executed
[out] d_v Local device values
[in] node_f Node forces
Definition at line 1407 of file lbgpu_cuda.cu.
References calc_m_from_n(), f, node_f, para, Utils::pi(), LB_nodes_gpu::populations, LB_parameters_gpu::rho, and update_rho_v().
Referenced by lb_init_GPU(), and lb_reinit_GPU().
calc_node_force()
template<std::size_t no_of_neighbours> __device__ void calc_node_force (Utils::Array< float, no_of_neighbours > const & delta, float const * delta_j, Utils::Array< unsigned int, no_of_neighbours > const & node_index, LB_node_force_density_gpu node_f)
Calculate the node force caused by the particles, with atomicAdd due to avoiding race conditions.
Eq. (14) [2].
Parameters
[in] delta Weighting of particle position
[in] delta_j Weighting of particle momentum
[in] node_index Node index around (8) particle
[out] node_f Node force
Template Parameters
no_of_neighbours The number of neighbours to consider for interpolation
Definition at line 1380 of file lbgpu_cuda.cu.
References LB_node_force_density_gpu::force_density, node, and node_f.
calc_values_from_m()
__device__ void calc_values_from_m (Utils::Array< float, 19 > const & mode_single, LB_rho_v_gpu const & d_v_single, float * rho_out, float * j_out, Utils::Array< float, 6 > & pi_out)
Calculate hydrodynamic fields in MD units.
Parameters
[out] mode_single Local register values mode
[in] d_v_single Local device values
[out] rho_out Density
[out] j_out Momentum
[out] pi_out Pressure tensor
Definition at line 1020 of file lbgpu_cuda.cu.
References LB_rho_v_gpu::rho, stress_from_stress_modes(), stress_modes(), and LB_rho_v_gpu::v.
Referenced by set_u_from_rho_v_pi().
calc_values_in_LB_units()
__device__ void calc_values_in_LB_units (LB_nodes_gpu n_a, Utils::Array< float, 19 > const & modes, LB_rho_v_pi_gpu * d_p_v, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f, unsigned int index, unsigned int print_index)
Calculate hydrodynamic fields in LB units.
Parameters
[in] n_a Local node residing in array a for boundary flag
[in] modes Local register values modes
[out] d_p_v Local print values
[out] d_v Local device values
[in] node_f Local node force
[in] index Node index / thread index
[in] print_index Node index / thread index TODO: code duplication with calc_values_from_m
Definition at line 990 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, node_f, LB_rho_v_pi_gpu::pi, LB_rho_v_pi_gpu::rho, LB_rho_v_gpu::rho, stress_from_stress_modes(), stress_modes(), update_rho_v(), LB_rho_v_pi_gpu::v, and LB_rho_v_gpu::v.
Referenced by get_mesoscopic_values_in_LB_units(), and lb_print_node().
calc_viscous_force()
template<std::size_t no_of_neighbours> __device__ void calc_viscous_force (LB_nodes_gpu n_a, Utils::Array< float, no_of_neighbours > & delta, CUDA_particle_data * particle_data, float * particle_force, unsigned int part_index, float * delta_j, Utils::Array< unsigned int, no_of_neighbours > & node_index, bool flag_cs, uint64_t philox_counter, float friction, float time_step)
Calculate viscous force.
Eq. (12) [2].
Parameters
[in] n_a Local node residing in array a
[out] delta Weighting of particle position
[out] delta_j Weighting of particle momentum
[in,out] particle_data Particle position and velocity
[in,out] particle_force Particle force
[in] part_index Particle id / thread id
[out] node_index Node index around (8) particle
[in] flag_cs Determine if we are at the centre (0, typical) or at the source (1, swimmer only)
[in] philox_counter Philox counter
[in] friction Friction constant for the particle coupling
[in] time_step MD time step
Template Parameters
no_of_neighbours The number of neighbours to consider for interpolation
Definition at line 1233 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, CUDA_ParticleParametersSwimming::dipole_length, CUDA_ParticleParametersSwimming::director, f, CUDA_ParticleParametersSwimming::f_swim, LB_parameters_gpu::kT, LBQ, CUDA_particle_data::mu_E, CUDA_particle_data::p, para, philox_counter, random_wrapper_philox(), CUDA_particle_data::swim, LB_parameters_gpu::tau, time_step, CUDA_particle_data::v, CUDA_ParticleParametersSwimming::v_cs, CUDA_ParticleParametersSwimming::v_swim, velocity(), and velocity_interpolation().
get_mesoscopic_values_in_LB_units()
__global__ void get_mesoscopic_values_in_LB_units (LB_nodes_gpu n_a, LB_rho_v_pi_gpu * p_v, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f)
Get physical values of the nodes (density, velocity, ...)
Parameters
[in] n_a Local node residing in array a
[out] p_v Local print values
[out] d_v Local device values
[in] node_f Local node force
Definition at line 1934 of file lbgpu_cuda.cu.
References calc_m_from_n(), calc_values_in_LB_units(), node_f, and LB_nodes_gpu::populations.
Referenced by lb_get_values_GPU().
index_to_xyz()
template<typename T > __device__ uint3 index_to_xyz (T index)
Transformation from 1d array-index to xyz.
Parameters
[in] index Node index / thread index
Definition at line 121 of file lbgpu_cuda.cu.
References LB_parameters_gpu::dim, and para.
Referenced by bounce_back_boundaries(), and calc_n_from_modes_push().
init_boundaries()
__global__ void init_boundaries (int const * boundary_node_list, int const * boundary_index_list, float const * boundary_velocities, unsigned number_of_boundnodes, LB_boundaries_gpu boundaries)
Set the boundary flag for all boundary nodes.
Parameters
[in] boundary_node_list Indices of the boundary nodes
[in] boundary_index_list Flag for the corresponding boundary
[in] boundary_velocities Boundary velocities
[in] number_of_boundnodes Number of boundary nodes
[in] boundaries Boundary information
Definition at line 1780 of file lbgpu_cuda.cu.
References boundaries, LB_boundaries_gpu::index, and LB_boundaries_gpu::velocity.
Referenced by lb_init_boundaries_GPU().
integrate() [1/2]
__global__ void integrate (LB_nodes_gpu n_a, LB_nodes_gpu n_b, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f)
Integration step of the LB-fluid-solver.
Parameters
[in] n_a Local node residing in array a
[out] n_b Local node residing in array b
[in,out] d_v Local device values
[in,out] node_f Local node force density
Definition at line 1843 of file lbgpu_cuda.cu.
References apply_forces(), calc_m_from_n(), calc_n_from_modes_push(), node_f, normalize_modes(), LB_nodes_gpu::populations, and relax_modes().
integrate() [2/2]
__global__ void integrate (LB_nodes_gpu n_a, LB_nodes_gpu n_b, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f, uint64_t philox_counter)
Integration step of the LB-fluid-solver.
Parameters
[in] n_a Local node residing in array a
[out] n_b Local node residing in array b
[in,out] d_v Local device values
[in,out] node_f Local node force density
[in] philox_counter Philox counter
Definition at line 1818 of file lbgpu_cuda.cu.
References apply_forces(), calc_m_from_n(), calc_n_from_modes_push(), node_f, normalize_modes(), philox_counter, LB_nodes_gpu::populations, relax_modes(), and thermalize_modes().
Referenced by benchmark_integration_step(), and lb_integrate_GPU().
lb_calc_fluid_mass_GPU()
void lb_calc_fluid_mass_GPU (double * mass)
Setup and call kernel to calculate the total momentum of the hole fluid.
Parameters
mass value of the mass calculated on the GPU
Definition at line 2307 of file lbgpu_cuda.cu.
References calc_mass(), calculate_dim_grid(), cuda_safe_mem, current_nodes, KERNELCALL, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and threads_per_block.
lb_calc_fluid_momentum_GPU()
void lb_calc_fluid_momentum_GPU (double * host_mom)
Setup and call kernel to calculate the total momentum of the whole fluid.
Parameters
host_mom value of the momentum calculated on the GPU
Definition at line 2329 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, calculate_dim_grid(), cuda_safe_mem, current_nodes, KERNELCALL, lbpar_gpu, momentum(), node_f, LB_parameters_gpu::number_of_nodes, LB_parameters_gpu::tau, and threads_per_block.
Referenced by lb_lbfluid_calc_fluid_momentum().
lb_calc_particle_lattice_ia_gpu()
template<std::size_t no_of_neighbours> void lb_calc_particle_lattice_ia_gpu (bool couple_virtual, double friction, double time_step)
Setup and call particle kernel from the host.
Template Parameters
no_of_neighbours The number of neighbours to consider for interpolation
Definition at line 2214 of file lbgpu_cuda.cu.
References calculate_dim_grid(), current_nodes, gpu_get_particle_force_pointer(), gpu_get_particle_pointer(), KERNELCALL, LB_parameters_gpu::kT, lbpar_gpu, node_f, rng_counter_coupling_gpu, threads_per_block, time_step, and Utils::Counter< T >::value().
lb_calc_particle_lattice_ia_gpu< 27 >()
template void lb_calc_particle_lattice_ia_gpu< 27 > (bool couple_virtual, double friction, double time_step)
Referenced by lb_lbcoupling_calc_particle_lattice_ia().
lb_calc_particle_lattice_ia_gpu< 8 >()
template void lb_calc_particle_lattice_ia_gpu< 8 > (bool couple_virtual, double friction, double time_step)
Referenced by lb_lbcoupling_calc_particle_lattice_ia().
lb_coupling_get_rng_state_gpu()
uint64_t lb_coupling_get_rng_state_gpu ()
Definition at line 2694 of file lbgpu_cuda.cu.
References rng_counter_coupling_gpu, and Utils::Counter< T >::value().
Referenced by lb_lbcoupling_get_rng_state().
lb_coupling_set_rng_state_gpu()
void lb_coupling_set_rng_state_gpu (uint64_t counter)
Definition at line 2686 of file lbgpu_cuda.cu.
References rng_counter_coupling_gpu.
Referenced by lb_lbcoupling_set_rng_state().
lb_fluid_get_rng_state_gpu()
uint64_t lb_fluid_get_rng_state_gpu ()
Definition at line 2698 of file lbgpu_cuda.cu.
References rng_counter_fluid_gpu, and Utils::Counter< T >::value().
Referenced by lb_lbfluid_get_rng_state().
lb_fluid_set_rng_state_gpu()
void lb_fluid_set_rng_state_gpu (uint64_t counter)
Definition at line 2690 of file lbgpu_cuda.cu.
References rng_counter_fluid_gpu.
Referenced by lb_lbfluid_set_rng_state().
lb_get_boundaries()
__global__ void lb_get_boundaries (LB_nodes_gpu n_a, unsigned int * device_bound_array)
Get boundary flags.
Parameters
[in] n_a Local node residing in array a
[out] device_bound_array Local device values
Definition at line 1951 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary.
Referenced by lb_get_boundary_flags_GPU().
lb_get_boundary_flag()
__global__ void lb_get_boundary_flag (unsigned int single_nodeindex, unsigned int * device_flag, LB_nodes_gpu n_a)
Print single node boundary flag.
Parameters
[in] single_nodeindex Node index
[out] device_flag Result
[in] n_a Local node residing in array a
Definition at line 2014 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary.
Referenced by lb_get_boundary_flag_GPU().
lb_get_boundary_flag_GPU()
void lb_get_boundary_flag_GPU (unsigned int single_nodeindex, unsigned int * host_flag)
Setup and call kernel to get the boundary flag of a single node.
Parameters
single_nodeindex number of the node to get the flag for
host_flag here goes the value of the boundary flag
Definition at line 2378 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, KERNELCALL, and lb_get_boundary_flag().
Referenced by lb_lbnode_get_boundary().
lb_get_boundary_flags_GPU()
void lb_get_boundary_flags_GPU (unsigned int * host_bound_array)
Get all the boundary flags for all nodes.
Parameters
host_bound_array here go the values of the boundary flag
Definition at line 2263 of file lbgpu_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, KERNELCALL, lb_get_boundaries(), lbpar_gpu, LB_parameters_gpu::number_of_nodes, and threads_per_block.
Referenced by ek_calculate_boundary_mass(), lb_lbfluid_print_boundary(), and lb_lbfluid_print_vtk_boundary().
lb_get_boundary_force_pointer()
void lb_get_boundary_force_pointer (float ** pointer_address)
Definition at line 2036 of file lbgpu_cuda.cu.
References lb_boundary_force.
Referenced by ek_init().
lb_get_interpolated_velocity_gpu()
template<std::size_t no_of_neighbours> void lb_get_interpolated_velocity_gpu (double const * positions, double * velocities, int length)
Definition at line 2644 of file lbgpu_cuda.cu.
References current_nodes, and device_rho_v.
lb_get_interpolated_velocity_gpu< 27 >()
template void lb_get_interpolated_velocity_gpu< 27 > (double const * positions, double * velocities, int length)
Referenced by lb_lbfluid_get_interpolated_velocity(), and quadratic_velocity_interpolation().
lb_get_interpolated_velocity_gpu< 8 >()
template void lb_get_interpolated_velocity_gpu< 8 > (double const * positions, double * velocities, int length)
Referenced by lb_lbfluid_get_interpolated_velocity(), and linear_velocity_interpolation().
lb_get_para_pointer()
void lb_get_para_pointer (LB_parameters_gpu ** pointer_address)
Definition at line 2028 of file lbgpu_cuda.cu.
References errexit(), and para.
Referenced by ek_init(), and InitCUDA_IBM().
lb_get_values_GPU()
void lb_get_values_GPU (LB_rho_v_pi_gpu * host_values)
Setup and call kernel for getting macroscopic fluid values of all nodes.
Parameters
host_values struct to save the gpu values
Definition at line 2249 of file lbgpu_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, current_nodes, device_rho_v, get_mesoscopic_values_in_LB_units(), host_values, KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, print_rho_v_pi, and threads_per_block.
Referenced by ek_lb_print_vtk_density(), ek_lb_print_vtk_velocity(), lb_lbfluid_print_velocity(), and lb_lbfluid_print_vtk_velocity().
lb_gpu_get_boundary_forces()
void lb_gpu_get_boundary_forces (std::vector< double > & forces)
Definition at line 2493 of file lbgpu_cuda.cu.
References cuda_safe_mem, lb_boundary_force, and LBBoundaries::lbboundaries.
Referenced by LBBoundaries::lbboundary_get_force().
lb_init_boundaries_GPU()
void lb_init_boundaries_GPU (std::size_t host_n_lb_boundaries, unsigned number_of_boundnodes, int * host_boundary_node_list, int * host_boundary_index_list, float * host_lb_boundary_velocity)
Setup and call boundaries from the host.
Parameters
host_n_lb_boundaries Number of LB boundaries
number_of_boundnodes Number of boundnodes
host_boundary_node_list The indices of the boundary nodes
host_boundary_index_list The flag representing the corresponding boundary
host_lb_boundary_velocity The constant velocity at the boundary, set by the user
Definition at line 2141 of file lbgpu_cuda.cu.
References boundaries, calculate_dim_grid(), cuda_safe_mem, init_boundaries(), KERNELCALL, lb_boundary_force, LBBoundaries::lbboundaries, lbpar_gpu, LB_parameters_gpu::number_of_nodes, reset_boundaries(), and threads_per_block.
Referenced by LBBoundaries::lb_init_boundaries().
lb_init_GPU()
void lb_init_GPU (const LB_parameters_gpu & lbpar_gpu)
Initialization for the lb gpu fluid called from host.
Parameters
lbpar_gpu Pointer to parameters to setup the lb field
Definition at line 2045 of file lbgpu_cuda.cu.
References boundaries, LB_nodes_gpu::boundary, LB_nodes_gpu::boundary_velocity, calc_n_from_rho_j_pi(), calculate_dim_grid(), cuda_safe_mem, current_nodes, device_gpu_lb_initialized, device_rho_v, errexit(), LB_node_force_density_gpu::force_density, LB_node_force_density_gpu::force_density_buf, free_realloc_and_clear, LB_boundaries_gpu::index, intflag, KERNELCALL, lbpar_gpu, node_f, nodes_a, nodes_b, LB_parameters_gpu::number_of_nodes, para, LB_nodes_gpu::populations, print_rho_v_pi, reinit_node_force(), reset_boundaries(), threads_per_block, and LB_boundaries_gpu::velocity.
Referenced by lb_init_gpu().
lb_integrate_GPU()
void lb_integrate_GPU ()
Integration kernel for the lb gpu fluid update called from host.
Integrate the lattice-Boltzmann system for one time step.
Definition at line 2449 of file lbgpu_cuda.cu.
References apply_boundaries(), boundaries, calculate_dim_grid(), cuda_safe_mem, current_nodes, device_rho_v, integrate(), intflag, KERNELCALL, LB_parameters_gpu::kT, lb_boundary_force, LBBoundaries::lbboundaries, lbpar_gpu, node_f, nodes_a, nodes_b, LB_parameters_gpu::number_of_nodes, rng_counter_fluid_gpu, threads_per_block, and Utils::Counter< T >::value().
Referenced by ek_integrate(), and lb_lbfluid_integrate().
lb_lbfluid_get_population()
void lb_lbfluid_get_population (const Utils::Vector3i & xyz, float population_host[LBQ])
Interface to get the populations of a specific node for the GPU.
Parameters
[in] xyz Node coordinates
[out] population_host Population
Definition at line 2570 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, KERNELCALL, lb_lbfluid_get_population_kernel(), and LBQ.
Referenced by lb_lbnode_get_pop().
lb_lbfluid_get_population_kernel()
__global__ void lb_lbfluid_get_population_kernel (LB_nodes_gpu n_a, float population[LBQ], int x, int y, int z)
Get the populations of a specific node on the GPU.
Parameters
[in] n_a Local node residing in array a
[out] population Population
[in] x x-coordinate of node
[in] y y-coordinate of node
[in] z z-coordinate of node
Definition at line 2556 of file lbgpu_cuda.cu.
References LBQ, LB_nodes_gpu::populations, and xyz_to_index().
Referenced by lb_lbfluid_get_population().
lb_lbfluid_set_population()
void lb_lbfluid_set_population (const Utils::Vector3i & xyz, float population_host[LBQ])
Interface to set the populations of a specific node for the GPU.
Parameters
[in] xyz Node coordinates
[in] population_host Population
Definition at line 2535 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, KERNELCALL, lb_lbfluid_set_population_kernel(), and LBQ.
Referenced by lb_lbnode_set_pop().
lb_lbfluid_set_population_kernel()
__global__ void lb_lbfluid_set_population_kernel (LB_nodes_gpu n_a, float const population[LBQ], int x, int y, int z)
Set the populations of a specific node on the GPU.
Parameters
[out] n_a Local node residing in array a
[in] population New population
[in] x x-coordinate of node
[in] y y-coordinate of node
[in] z z-coordinate of node
Definition at line 2521 of file lbgpu_cuda.cu.
References LBQ, LB_nodes_gpu::populations, and xyz_to_index().
Referenced by lb_lbfluid_set_population().
lb_load_checkpoint_GPU()
void lb_load_checkpoint_GPU (float const *const host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
Parameters
[in] host_checkpoint_vd LB populations
Definition at line 2364 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, intflag, lbpar_gpu, nodes_a, LB_parameters_gpu::number_of_nodes, and LB_nodes_gpu::populations.
Referenced by lb_lbfluid_load_checkpoint().
lb_print_node()
__global__ void lb_print_node (unsigned int single_nodeindex, LB_rho_v_pi_gpu * d_p_v, LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f)
Print single node values kernel.
Parameters
[in] single_nodeindex Node index
[out] d_p_v Result
[in] n_a Local node residing in array a
[out] d_v Local device values
[in] node_f Local node force
Definition at line 1967 of file lbgpu_cuda.cu.
References calc_m_from_n(), calc_values_in_LB_units(), node_f, and LB_nodes_gpu::populations.
Referenced by lb_print_node_GPU().
lb_print_node_GPU()
void lb_print_node_GPU (unsigned single_nodeindex, LB_rho_v_pi_gpu * host_print_values)
Setup and call kernel for getting macroscopic fluid values of a single node.
Definition at line 2284 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, device_rho_v, KERNELCALL, lb_print_node(), and node_f.
Referenced by lb_lbnode_get_density(), lb_lbnode_get_pressure_tensor_neq(), and lb_lbnode_get_velocity().
lb_reinit_extern_nodeforce_GPU()
void lb_reinit_extern_nodeforce_GPU (LB_parameters_gpu * lbpar_gpu)
Setup and call extern single node force initialization from the host.
Parameters
lbpar_gpu Host parameter struct
Definition at line 2200 of file lbgpu_cuda.cu.
References calculate_dim_grid(), cuda_safe_mem, KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, para, reinit_node_force(), and threads_per_block.
Referenced by lb_lbfluid_set_ext_force_density(), and lb_reinit_fluid_gpu().
lb_reinit_GPU()
void lb_reinit_GPU (LB_parameters_gpu * lbpar_gpu)
Reinitialization for the lb gpu fluid called from host.
Parameters
lbpar_gpu Pointer to parameters to setup the lb field
Definition at line 2118 of file lbgpu_cuda.cu.
References calc_n_from_rho_j_pi(), calculate_dim_grid(), cuda_safe_mem, device_gpu_lb_initialized, device_rho_v, KERNELCALL, lbpar_gpu, node_f, nodes_a, LB_parameters_gpu::number_of_nodes, para, and threads_per_block.
Referenced by lb_reinit_fluid_gpu().
lb_save_checkpoint_GPU()
void lb_save_checkpoint_GPU (float *const host_checkpoint_vd)
Setup and call kernel for getting macroscopic fluid values of all nodes.
Parameters
[out] host_checkpoint_vd LB populations
Definition at line 2355 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and LB_nodes_gpu::populations.
Referenced by lb_lbfluid_save_checkpoint().
lb_set_node_rho_GPU()
void lb_set_node_rho_GPU (unsigned single_nodeindex, float host_rho)
Set the density at a single node.
Parameters
single_nodeindex the node to set the velocity for
host_rho the density to set
Definition at line 2401 of file lbgpu_cuda.cu.
References current_nodes, device_rho_v, KERNELCALL, and set_rho().
Referenced by lb_lbnode_set_density().
lb_set_node_velocity_GPU()
void lb_set_node_velocity_GPU (unsigned single_nodeindex, float * host_velocity)
Set the net velocity at a single node.
Parameters
single_nodeindex the node to set the velocity for
host_velocity the velocity to set
Definition at line 2415 of file lbgpu_cuda.cu.
References cuda_safe_mem, current_nodes, device_rho_v, KERNELCALL, node_f, set_force_density(), and set_u_from_rho_v_pi().
Referenced by lb_lbnode_set_velocity().
linear_velocity_interpolation()
void linear_velocity_interpolation (double const * positions, double * velocities, int length)
Definition at line 2676 of file lbgpu_cuda.cu.
References lb_get_interpolated_velocity_gpu< 8 >().
momentum()
__global__ void momentum (LB_nodes_gpu n_a, LB_node_force_density_gpu node_f, float * sum)
Definition at line 1983 of file lbgpu_cuda.cu.
References LB_nodes_gpu::boundary, calc_mass_and_momentum_mode(), LB_node_force_density_gpu::force_density, node_f, and sum.
Referenced by lb_calc_fluid_momentum(), lb_calc_fluid_momentum_GPU(), and mpi_particle_momentum_local().
node_velocity()
__device__ __inline__ float3 node_velocity (float rho_eq, LB_nodes_gpu n_a, unsigned index)
Get velocity of at index.
Definition at line 1059 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_nodes_gpu::boundary, LB_nodes_gpu::boundary_velocity, calc_mode_x_from_n(), para, LB_nodes_gpu::populations, LB_parameters_gpu::tau, and u.
Referenced by velocity_interpolation().
normalize_modes()
__device__ void normalize_modes (Utils::Array< float, 19 > & mode)
Normalization of the modes need before back-transformation into velocity space.
Parameters
[in,out] mode Local register values mode
Definition at line 462 of file lbgpu_cuda.cu.
Referenced by integrate().
quadratic_velocity_interpolation()
void quadratic_velocity_interpolation (double const * positions, double * velocities, int length)
Definition at line 2681 of file lbgpu_cuda.cu.
References lb_get_interpolated_velocity_gpu< 27 >().
reinit_node_force()
__global__ void reinit_node_force (LB_node_force_density_gpu node_f)
(Re-)initialize the node force density / set the external force density in lb units
Parameters
[out] node_f Local node force density
Definition at line 1721 of file lbgpu_cuda.cu.
References LB_parameters_gpu::ext_force_density, LB_node_force_density_gpu::force_density, node_f, and para.
Referenced by lb_init_GPU(), and lb_reinit_extern_nodeforce_GPU().
reinit_parameters_GPU()
void reinit_parameters_GPU (LB_parameters_gpu * lbpar_gpu)
Reinitialize parameters.
Parameters
lbpar_gpu struct containing the parameters of the fluid
Definition at line 2443 of file lbgpu_cuda.cu.
References cuda_safe_mem, lbpar_gpu, and para.
Referenced by lb_reinit_parameters_gpu().
relax_modes()
__device__ void relax_modes (Utils::Array< float, 19 > & mode, unsigned int index, LB_node_force_density_gpu node_f, LB_rho_v_gpu * d_v)
lb_relax_modes, means collision update of the modes
Parameters
[in] index Node index / thread index
[in,out] mode Local register values mode
[in] node_f Local node force
[in,out] d_v Local device values
Definition at line 326 of file lbgpu_cuda.cu.
References LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_even, LB_parameters_gpu::gamma_odd, LB_parameters_gpu::gamma_shear, node_f, para, LB_parameters_gpu::rho, update_rho_v(), and LB_rho_v_gpu::v.
Referenced by integrate().
reset_boundaries()
__global__ void reset_boundaries (LB_boundaries_gpu boundaries)
Reset the boundary flag of every node.
Definition at line 1803 of file lbgpu_cuda.cu.
References boundaries, and LB_boundaries_gpu::index.
Referenced by lb_init_boundaries_GPU(), and lb_init_GPU().
reset_LB_force_densities()
__device__ void reset_LB_force_densities (unsigned int index, LB_node_force_density_gpu node_f, bool buffer = true)
Definition at line 244 of file lbgpu_cuda.cu.
References LB_parameters_gpu::ext_force_density, LB_parameters_gpu::external_force_density, LB_node_force_density_gpu::force_density, LB_node_force_density_gpu::force_density_buf, node_f, and para.
Referenced by apply_forces(), and reset_LB_force_densities_kernel().
reset_LB_force_densities_GPU()
void reset_LB_force_densities_GPU (bool buffer)
Reset the forces on the fluid nodes.
Definition at line 271 of file lbgpu_cuda.cu.
References calculate_dim_grid(), KERNELCALL, lbpar_gpu, node_f, LB_parameters_gpu::number_of_nodes, reset_LB_force_densities_kernel(), and threads_per_block.
Referenced by ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), and ek_print_vtk_flux_link().
reset_LB_force_densities_kernel()
__global__ void reset_LB_force_densities_kernel (LB_node_force_density_gpu node_f, bool buffer = true)
Definition at line 262 of file lbgpu_cuda.cu.
References node_f, and reset_LB_force_densities().
Referenced by reset_LB_force_densities_GPU().
set_force_density()
__global__ void set_force_density (unsigned single_nodeindex, float const * force_density, LB_node_force_density_gpu node_f)
Definition at line 1531 of file lbgpu_cuda.cu.
References LB_node_force_density_gpu::force_density, and node_f.
Referenced by lb_set_node_velocity_GPU().
set_rho()
__global__ void set_rho (LB_nodes_gpu n_a, LB_rho_v_gpu * d_v, unsigned single_nodeindex, float rho)
Kernel to set the local density.
Parameters
[out] n_a Current nodes array (double buffering!)
[in] single_nodeindex Node to set the velocity for
[in] rho Density to set
[in] d_v Local modes
Definition at line 1739 of file lbgpu_cuda.cu.
References para, LB_nodes_gpu::populations, LB_parameters_gpu::rho, and LB_rho_v_gpu::rho.
Referenced by lb_set_node_rho_GPU().
set_u_from_rho_v_pi()
__global__ void set_u_from_rho_v_pi (LB_nodes_gpu n_a, unsigned single_nodeindex, float const * velocity, LB_rho_v_gpu * d_v, LB_node_force_density_gpu node_f)
Kernel to calculate local populations from hydrodynamic fields from given flow field velocities.
The mapping is given in terms of the equilibrium distribution.
Eq. (2.15) [32]. Eq. (4) in [51].
Parameters
[out] n_a Current nodes array (double buffering!)
[in] single_nodeindex Single node index
[in] velocity Velocity
[out] d_v Local device values
[in] node_f Node forces
Definition at line 1557 of file lbgpu_cuda.cu.
References calc_m_from_n(), calc_values_from_m(), f, node_f, para, LB_nodes_gpu::populations, LB_parameters_gpu::rho, update_rho_v(), and velocity().
Referenced by lb_set_node_velocity_GPU().
stress_from_stress_modes()
__device__ Utils::Array<float, 6> stress_from_stress_modes (Utils::Array< float, 19 > const & modes)
Calculate the stress tensor.
Transform the stress tensor components according to the modes that correspond to those used by U. Schiller. In terms of populations this expression then corresponds exactly to those in eq. (116)-(121) in [17], when these are written out in populations. But to ensure this, the expression in Schiller's modes has to be different!
Parameters
[in] modes Local register values modes
Definition at line 970 of file lbgpu_cuda.cu.
References f.
Referenced by calc_values_from_m(), calc_values_in_LB_units(), and Stress::operator()().
stress_modes()
__device__ Utils::Array<float, 19> stress_modes (LB_rho_v_gpu const & rho_v, const Utils::Array< float, 19 > & modes)
Definition at line 904 of file lbgpu_cuda.cu.
References LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_shear, para, res, LB_rho_v_gpu::rho, and LB_rho_v_gpu::v.
Referenced by calc_values_from_m(), calc_values_in_LB_units(), and Stress::operator()().
stress_tensor_GPU()
Utils::Array<float, 6> stress_tensor_GPU ()
Definition at line 2624 of file lbgpu_cuda.cu.
References current_nodes, device_rho_v, lbpar_gpu, LB_parameters_gpu::number_of_nodes, and LB_nodes_gpu::populations.
Referenced by lb_lbfluid_get_pressure_tensor().
thermalize_modes()
__device__ void thermalize_modes (Utils::Array< float, 19 > & mode, unsigned int index, uint64_t philox_counter)
Thermalization of the modes with Gaussian random numbers.
Parameters
[in] index Node index / thread index
[in,out] mode Local register values mode
[in] philox_counter Philox counter
Definition at line 391 of file lbgpu_cuda.cu.
References LB_parameters_gpu::gamma_bulk, LB_parameters_gpu::gamma_even, LB_parameters_gpu::gamma_odd, LB_parameters_gpu::gamma_shear, LB_parameters_gpu::mu, para, philox_counter, random_wrapper_philox(), LB_parameters_gpu::rho, and sqrt12.
Referenced by integrate().
three_point_polynomial_larger_than_half()
__device__ __inline__ float three_point_polynomial_larger_than_half (float u)
Interpolation kernel.
See [16]
Parameters
u Distance to grid point in units of agrid
Return values
Value for the interpolation function.
Definition at line 1051 of file lbgpu_cuda.cu.
References f, and u.
Referenced by velocity_interpolation().
three_point_polynomial_smallerequal_than_half()
__device__ __inline__ float three_point_polynomial_smallerequal_than_half (float u)
Interpolation kernel.
See [16]
Parameters
u Distance to grid point in units of agrid
Return values
Value for the interpolation function.
Definition at line 1042 of file lbgpu_cuda.cu.
References f, and u.
Referenced by velocity_interpolation().
update_rho_v()
__device__ void update_rho_v (Utils::Array< float, 19 > const & modes, unsigned int index, LB_node_force_density_gpu const & node_f, LB_rho_v_gpu * d_v)
Parameters
[in] modes Local register values modes
[in] index Node index / thread index
[in] node_f Local node force
[out] d_v Local device values
If forces are present, the momentum density is redefined to include one half-step of the force action. See the Chapman-Enskog expansion in [31].
Definition at line 285 of file lbgpu_cuda.cu.
References LB_node_force_density_gpu::force_density, node_f, para, LB_parameters_gpu::rho, LB_rho_v_gpu::rho, and LB_rho_v_gpu::v.
Referenced by calc_n_from_rho_j_pi(), calc_values_in_LB_units(), relax_modes(), and set_u_from_rho_v_pi().
velocity_interpolation() [1/2]
__device__ __inline__ float3 velocity_interpolation (LB_nodes_gpu n_a, float const * particle_position, Utils::Array< unsigned int, 27 > & node_indices, Utils::Array< float, 27 > & delta)
Definition at line 1077 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim, anonymous_namespace{lb_interpolation.cpp}::node_u(), node_velocity(), para, LB_parameters_gpu::rho, three_point_polynomial_larger_than_half(), three_point_polynomial_smallerequal_than_half(), and xyz_to_index().
Referenced by calc_viscous_force(), and interpolation< no_of_neighbours >::operator()().
velocity_interpolation() [2/2]
__device__ __inline__ float3 velocity_interpolation (LB_nodes_gpu n_a, float const * particle_position, Utils::Array< unsigned int, 8 > & node_index, Utils::Array< float, 8 > & delta)
Velocity interpolation.
Eq. (12) [2].
Parameters
[in] n_a Local node residing in array a
[in] particle_position Particle position
[out] node_index Node index around (8) particle
[out] delta Weighting of particle position
Return values
Interpolated velocity
Definition at line 1159 of file lbgpu_cuda.cu.
References LB_parameters_gpu::agrid, LB_parameters_gpu::dim, anonymous_namespace{lb_interpolation.cpp}::node_u(), node_velocity(), para, LB_parameters_gpu::rho, and xyz_to_index().
xyz_to_index()
template<typename T > __device__ T xyz_to_index (T x, T y, T z)
Transformation from xyz to 1d array-index.
Parameters
[in] x,y,z The xyz array
Definition at line 133 of file lbgpu_cuda.cu.
References LB_parameters_gpu::dim, and para.
Referenced by lb_lbfluid_get_population_kernel(), lb_lbfluid_set_population_kernel(), and velocity_interpolation().
Variable Documentation
boundaries
LB_boundaries_gpu boundaries static
boundary information
Definition at line 84 of file lbgpu_cuda.cu.
Referenced by apply_boundaries(), bounce_back_boundaries(), LBBoundaries::ek_init_boundaries(), init_boundaries(), lb_init_boundaries_GPU(), lb_init_GPU(), lb_integrate_GPU(), regular_decomposition(), and reset_boundaries().
current_nodes
LB_nodes_gpu* current_nodes = nullptr
Definition at line 108 of file lbgpu_cuda.cu.
Referenced by ek_init_species_density_wallcharge(), ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), lb_calc_fluid_mass_GPU(), lb_calc_fluid_momentum_GPU(), lb_calc_particle_lattice_ia_gpu(), lb_get_boundary_flag_GPU(), lb_get_boundary_flags_GPU(), lb_get_interpolated_velocity_gpu(), lb_get_values_GPU(), lb_init_GPU(), lb_integrate_GPU(), lb_lbfluid_get_population(), lb_lbfluid_set_population(), lb_load_checkpoint_GPU(), lb_print_node_GPU(), lb_save_checkpoint_GPU(), lb_set_node_rho_GPU(), lb_set_node_velocity_GPU(), ParticleVelocitiesFromLB_GPU(), and stress_tensor_GPU().
device_gpu_lb_initialized
bool* device_gpu_lb_initialized = nullptr static
Whether LB GPU was initialized.
Definition at line 102 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), and lb_reinit_GPU().
device_rho_v
LB_rho_v_gpu* device_rho_v = nullptr static
struct for hydrodynamic fields: this is for internal use (i.e.
stores values in LB units) and should not be used for printing values
Definition at line 66 of file lbgpu_cuda.cu.
Referenced by lb_get_interpolated_velocity_gpu(), lb_get_values_GPU(), lb_init_GPU(), lb_integrate_GPU(), lb_print_node_GPU(), lb_reinit_GPU(), lb_set_node_rho_GPU(), lb_set_node_velocity_GPU(), and stress_tensor_GPU().
intflag
bool intflag = true static
Direction of data transfer between nodes_a and nodes_b during integration in lb_integrate_GPU.
Definition at line 107 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), lb_integrate_GPU(), and lb_load_checkpoint_GPU().
lb_boundary_force
float* lb_boundary_force = nullptr static
Force on the boundary nodes.
Definition at line 98 of file lbgpu_cuda.cu.
Referenced by apply_boundaries(), bounce_back_boundaries(), lb_get_boundary_force_pointer(), lb_gpu_get_boundary_forces(), lb_init_boundaries_GPU(), and lb_integrate_GPU().
node_f
LB_node_force_density_gpu node_f
Initial value:
= {
    nullptr,
    nullptr
}
struct for node force density
Definition at line 87 of file lbgpu_cuda.cu.
Referenced by apply_forces(), calc_fluid_particle_ia(), calc_n_from_rho_j_pi(), calc_node_force(), calc_values_in_LB_units(), ek_calculate_quantities(), ek_clear_node_force(), ek_diffusion_migration_lbforce_linkcentered_stencil(), ek_diffusion_migration_lbforce_nodecentered_stencil(), ek_init(), ek_integrate(), ek_node_get_flux(), ek_print_vtk_flux(), ek_print_vtk_flux_fluc(), ek_print_vtk_flux_link(), ek_print_vtk_lbforce_density(), ForcesIntoFluid_Kernel(), get_mesoscopic_values_in_LB_units(), IBM_ForcesIntoFluid_GPU(), integrate(), lb_calc_fluid_momentum_GPU(), lb_calc_particle_lattice_ia_gpu(), lb_get_values_GPU(), lb_init_GPU(), lb_integrate_GPU(), lb_print_node(), lb_print_node_GPU(), lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), lb_set_node_velocity_GPU(), momentum(), ParticleVelocitiesFromLB_GPU(), ParticleVelocitiesFromLB_Kernel(), reinit_node_force(), relax_modes(), reset_LB_force_densities(), reset_LB_force_densities_GPU(), reset_LB_force_densities_kernel(), ResetLBForces_Kernel(), set_force_density(), set_u_from_rho_v_pi(), and update_rho_v().
nodes_a
LB_nodes_gpu nodes_a static
Definition at line 79 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), lb_integrate_GPU(), lb_load_checkpoint_GPU(), and lb_reinit_GPU().
nodes_b
LB_nodes_gpu nodes_b static
Definition at line 80 of file lbgpu_cuda.cu.
Referenced by lb_init_GPU(), and lb_integrate_GPU().
para
__device__ __constant__ LB_parameters_gpu para[1]
Parameters residing in constant memory.
Definition at line 111 of file lbgpu_cuda.cu.
Referenced by apply_forces(), calc_mass(), calc_n_from_modes_push(), calc_n_from_rho_j_pi(), calc_viscous_force(), ForcesIntoFluid_Kernel(), index_to_xyz(), lb_get_para_pointer(), lb_init_GPU(), lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), node_velocity(), ParticleVelocitiesFromLB_Kernel(), reinit_node_force(), reinit_parameters_GPU(), relax_modes(), reset_LB_force_densities(), ResetLBForces_Kernel(), set_rho(), set_u_from_rho_v_pi(), stress_modes(), thermalize_modes(), update_rho_v(), velocity_interpolation(), and xyz_to_index().
print_rho_v_pi
LB_rho_v_pi_gpu* print_rho_v_pi = nullptr static
struct for hydrodynamic fields: this is the interface and stores values in MD units.
It should not be used as an input for any LB calculations. TODO: in the future, one might want to have several structures for printing separately rho, v, pi without having to compute/store the complete set.
Definition at line 75 of file lbgpu_cuda.cu.
Referenced by lb_get_values_GPU(), and lb_init_GPU().
rng_counter_coupling_gpu
OptionalCounter rng_counter_coupling_gpu
Definition at line 115 of file lbgpu_cuda.cu.
Referenced by lb_calc_particle_lattice_ia_gpu(), lb_coupling_get_rng_state_gpu(), lb_coupling_set_rng_state_gpu(), lb_lbcoupling_is_seed_required(), and lb_lbcoupling_propagate().
rng_counter_fluid_gpu
OptionalCounter rng_counter_fluid_gpu
Definition at line 116 of file lbgpu_cuda.cu.
Referenced by lb_fluid_get_rng_state_gpu(), lb_fluid_set_rng_state_gpu(), lb_integrate_GPU(), and lb_lbfluid_propagate().
sqrt12
constexpr float sqrt12 = 3.4641016151377544f static constexpr
Definition at line 113 of file lbgpu_cuda.cu.
Referenced by thermalize_modes().
threads_per_block
constexpr unsigned int threads_per_block = 64 static constexpr
Definition at line 114 of file lbgpu_cuda.cu.
Referenced by lb_calc_fluid_mass_GPU(), lb_calc_fluid_momentum_GPU(), lb_calc_particle_lattice_ia_gpu(), lb_get_boundary_flags_GPU(), lb_get_values_GPU(), lb_init_boundaries_GPU(), lb_init_GPU(), lb_integrate_GPU(), lb_reinit_extern_nodeforce_GPU(), lb_reinit_GPU(), and reset_LB_force_densities_GPU().