ESPResSo: lbgpu.cuh File Reference
lbgpu.cuh File Reference
#include "config.hpp"
#include <curand_kernel.h>
#include <utils/Array.hpp>
Classes
struct LB_nodes_gpu
Velocity densities for the lattice Boltzmann system.
struct LB_boundaries_gpu
Macros
#define LBGPU_CUH
Functions
__device__ __inline__ float calc_mode_x_from_n (Utils::Array< float, 19 > const &populations, int x)
__device__ __inline__ void calc_mass_and_momentum_mode (Utils::Array< float, 4 > &mode, LB_nodes_gpu n_a, unsigned int node_index)
__device__ float4 random_wrapper_philox (unsigned int index, unsigned int mode, uint64_t philox_counter)
Detailed Description
Lattice Boltzmann on GPUs.
Implementation in lbgpu_cuda.cu.
Definition in file lbgpu.cuh.
Macro Definition Documentation
LBGPU_CUH
#define LBGPU_CUH
Definition at line 26 of file lbgpu.cuh.
Function Documentation
calc_mass_and_momentum_mode()
__device__ __inline__ void calc_mass_and_momentum_mode (Utils::Array< float, 4 > & mode, LB_nodes_gpu n_a, unsigned int node_index)
Parameters
[in] node_index Node index around (8) particle
[out] mode Local register values mode
[in] n_a Local node residing in array a
Definition at line 170 of file lbgpu.cuh.
References calc_mode_x_from_n(), and LB_nodes_gpu::populations.
Referenced by calc_mass(), momentum(), and ParticleVelocitiesFromLB_Kernel().
calc_mode_x_from_n()
__device__ __inline__ float calc_mode_x_from_n (Utils::Array< float, 19 > const & populations, int x)
Definition at line 44 of file lbgpu.cuh.
References f.
Referenced by calc_m_from_n(), calc_mass_and_momentum_mode(), and node_velocity().
random_wrapper_philox()
__device__ float4 random_wrapper_philox (unsigned int index, unsigned int mode, uint64_t philox_counter) inline
Definition at line 195 of file lbgpu.cuh.
References f, and philox_counter.
Referenced by calc_viscous_force(), and thermalize_modes().