ESPResSo: lj.hpp File Reference
lj.hpp File Reference
#include "config.hpp"
#include "nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
Functions
int lennard_jones_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, double min)
double lj_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate Lennard-Jones force factor.
double lj_pair_energy (IA_parameters const &ia_params, double dist)
Calculate Lennard-Jones energy.
Detailed Description
Routines to calculate the Lennard-Jones potential between particle pairs.
Implementation in lj.cpp.
Definition in file lj.hpp.
Function Documentation
lennard_jones_set_params()
int lennard_jones_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, double min)
Definition at line 33 of file lj.cpp.
References LJ_Parameters::cut, LJ_Parameters::eps, ES_ERROR, ES_OK, get_ia_param_safe(), IA_parameters::lj, anonymous_namespace{Correlator.cpp}::min(), LJ_Parameters::min, mpi_bcast_ia_params(), LJ_Parameters::offset, LJ_Parameters::shift, and LJ_Parameters::sig.
lj_pair_energy()
double lj_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate Lennard-Jones energy.
Definition at line 57 of file lj.hpp.
References LJ_Parameters::cut, LJ_Parameters::eps, IA_parameters::lj, LJ_Parameters::min, LJ_Parameters::offset, LJ_Parameters::shift, LJ_Parameters::sig, and Utils::sqr().
Referenced by calc_non_bonded_pair_energy().
lj_pair_force_factor()
double lj_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate Lennard-Jones force factor.
Definition at line 45 of file lj.hpp.
References LJ_Parameters::cut, LJ_Parameters::eps, IA_parameters::lj, LJ_Parameters::min, LJ_Parameters::offset, and LJ_Parameters::sig.
Referenced by calc_non_bonded_pair_force().