ESPResSo: ljcos.hpp File Reference
ljcos.hpp File Reference
#include "config.hpp"
#include "nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
#include <cmath>
Functions
int ljcos_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double offset)
double ljcos_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate Lennard-Jones cosine force factor.
double ljcos_pair_energy (IA_parameters const &ia_params, double dist)
Calculate Lennard-Jones cosine energy.
Detailed Description
Routines to calculate the Lennard-Jones+cosine potential between particle pairs.
Implementation in ljcos.cpp.
Definition in file ljcos.hpp.
Function Documentation
ljcos_pair_energy()
double ljcos_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate Lennard-Jones cosine energy.
Definition at line 67 of file ljcos.hpp.
References LJcos_Parameters::alfa, LJcos_Parameters::beta, LJcos_Parameters::cut, LJcos_Parameters::eps, IA_parameters::ljcos, LJcos_Parameters::offset, LJcos_Parameters::rmin, LJcos_Parameters::sig, and Utils::sqr().
Referenced by calc_non_bonded_pair_energy().
ljcos_pair_force_factor()
double ljcos_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate Lennard-Jones cosine force factor.
Definition at line 46 of file ljcos.hpp.
References LJcos_Parameters::alfa, LJcos_Parameters::beta, LJcos_Parameters::cut, LJcos_Parameters::eps, IA_parameters::ljcos, LJcos_Parameters::offset, LJcos_Parameters::rmin, LJcos_Parameters::sig, and Utils::sqr().
Referenced by calc_non_bonded_pair_force().
ljcos_set_params()
int ljcos_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double offset)
Definition at line 34 of file ljcos.cpp.
References LJcos_Parameters::alfa, LJcos_Parameters::beta, Utils::cbrt_2(), LJcos_Parameters::cut, LJcos_Parameters::eps, ES_ERROR, ES_OK, get_ia_param_safe(), IA_parameters::ljcos, mpi_bcast_ia_params(), LJcos_Parameters::offset, Utils::pi(), LJcos_Parameters::rmin, LJcos_Parameters::sig, Utils::sqr(), and Utils::sqrt().