ESPResSo: ljgen.hpp File Reference
ljgen.hpp File Reference
#include "config.hpp"
#include "nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sqr.hpp>
#include <cmath>
Functions
int ljgen_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, double a1, double a2, double b1, double b2, double lambda, double softrad)
double ljgen_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate Lennard-Jones force factor.
double ljgen_pair_energy (IA_parameters const &ia_params, double dist)
Calculate Lennard-Jones energy.
Detailed Description
Routines to calculate the generalized Lennard-Jones potential between particle pairs. "Generalized" here means that the LJ energy is of the form
\[ \varepsilon \cdot \left[ b_1 \left(\frac{\sigma}{r-r_{\text{offset}}}\right)^{a_1} - b_2 \left(\frac{\sigma}{r-r_{\text{offset}}}\right)^{a_2} + \text{shift} \right] \]
Implementation in ljgen.cpp.
Definition in file ljgen.hpp.
Function Documentation
ljgen_pair_energy()
double ljgen_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate Lennard-Jones energy.
Definition at line 90 of file ljgen.hpp.
References LJGen_Parameters::a1, LJGen_Parameters::a2, Utils::abs(), LJGen_Parameters::b1, LJGen_Parameters::b2, LJGen_Parameters::cut, LJGen_Parameters::eps, LJGen_Parameters::lambda1, IA_parameters::ljgen, LJGen_Parameters::offset, LJGen_Parameters::shift, LJGen_Parameters::sig, LJGen_Parameters::softrad, and Utils::sqrt().
Referenced by calc_non_bonded_pair_energy().
ljgen_pair_force_factor()
double ljgen_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate Lennard-Jones force factor.
Definition at line 60 of file ljgen.hpp.
References LJGen_Parameters::a1, LJGen_Parameters::a2, Utils::abs(), LJGen_Parameters::b1, LJGen_Parameters::b2, LJGen_Parameters::cut, LJGen_Parameters::eps, LJGen_Parameters::lambda1, IA_parameters::ljgen, LJGen_Parameters::offset, LJGen_Parameters::sig, LJGen_Parameters::softrad, Utils::sqr(), and Utils::sqrt().
Referenced by calc_non_bonded_pair_force().
ljgen_set_params()
int ljgen_set_params (int part_type_a, int part_type_b, double eps, double sig, double cut, double shift, double offset, double a1, double a2, double b1, double b2, double lambda, double softrad)
Definition at line 33 of file ljgen.cpp.
References LJGen_Parameters::a1, LJGen_Parameters::a2, LJGen_Parameters::b1, LJGen_Parameters::b2, LJGen_Parameters::cut, LJGen_Parameters::eps, ES_ERROR, ES_OK, get_ia_param_safe(), LJGen_Parameters::lambda1, IA_parameters::ljgen, mpi_bcast_ia_params(), LJGen_Parameters::offset, LJGen_Parameters::shift, LJGen_Parameters::sig, and LJGen_Parameters::softrad.