ESPResSo: mmm-common.hpp File Reference
mmm-common.hpp File Reference
Common parts of the MMM family of methods for the electrostatic interaction: MMM1D and ELC.
#include "mmm-modpsi.hpp"
#include "specfunc.hpp"
#include <vector>
Functions
double mod_psi_even (int n, double x)
Modified polygamma for even order 2*n, n >= 0
double mod_psi_odd (int n, double x)
Modified polygamma for odd order 2*n+1, n>= 0
Detailed Description
Common parts of the MMM family of methods for the electrostatic interaction: MMM1D and ELC.
This file contains the code for the polygamma expansions used for the near formulas of MMM1D.
The expansion of the polygamma functions is fairly easy and follows directly from [1]. For details, see [5].
Definition in file mmm-common.hpp.
Function Documentation
mod_psi_even()
double mod_psi_even (int n, double x) inline
Modified polygamma for even order 2*n, n >= 0
Definition at line 40 of file mmm-common.hpp.
References evaluateAsTaylorSeriesAt(), and modPsi.
Referenced by CoulombMMM1D::pair_energy(), and CoulombMMM1D::pair_force().
mod_psi_odd()
double mod_psi_odd (int n, double x) inline
Modified polygamma for odd order 2*n+1, n>= 0
Definition at line 45 of file mmm-common.hpp.
References evaluateAsTaylorSeriesAt(), and modPsi.
Referenced by CoulombMMM1D::pair_force().