ESPResSo: mmm1d.cpp File Reference
mmm1d.cpp File Reference
#include <config/config.hpp>
#include "electrostatics/mmm1d.hpp"
#include "electrostatics/coulomb.hpp"
#include "BoxGeometry.hpp"
#include "LocalBox.hpp"
#include "Particle.hpp"
#include "cell_system/CellStructureType.hpp"
#include "errorhandling.hpp"
#include "tuning.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sqr.hpp>
#include <gsl/gsl_sf_bessel.h>
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <limits>
#include <numbers>
#include <vector>
Functions
static auto far_error (int P, double minrad, Utils::Vector3d const &box_l_inv)
static auto determine_minrad (double maxPWerror, int P, Utils::Vector3d const &box_l, Utils::Vector3d const &box_l_inv)
static double evaluateAsTaylorSeriesAt (std::span< const double > series, double x)
static double mod_psi_even (auto const &modPsi, int n, double x)
Modified polygamma for even order 2*n, n >= 0
static double mod_psi_odd (auto const &modPsi, int n, double x)
Modified polygamma for odd order 2*n+1, n>= 0
Function Documentation
determine_minrad()
static auto determine_minrad (double maxPWerror, int P, Utils::Vector3d const & box_l, Utils::Vector3d const & box_l_inv) static
Definition at line 59 of file mmm1d.cpp.
References far_error(), P, and stream.
evaluateAsTaylorSeriesAt()
static double evaluateAsTaylorSeriesAt (std::span< const double > series, double x) static
Definition at line 90 of file mmm1d.cpp.
References stream.
Referenced by mod_psi_even(), and mod_psi_odd().
far_error()
static auto far_error (int P, double minrad, Utils::Vector3d const & box_l_inv) static
Definition at line 49 of file mmm1d.cpp.
References P, and stream.
Referenced by determine_minrad().
mod_psi_even()
static double mod_psi_even (auto const & modPsi, int n, double x) static
Modified polygamma for even order 2*n, n >= 0
Definition at line 100 of file mmm1d.cpp.
References evaluateAsTaylorSeriesAt().
Referenced by CoulombMMM1D::pair_energy(), and CoulombMMM1D::pair_force().
mod_psi_odd()
static double mod_psi_odd (auto const & modPsi, int n, double x) static
Modified polygamma for odd order 2*n+1, n>= 0
Definition at line 105 of file mmm1d.cpp.
References evaluateAsTaylorSeriesAt().
Referenced by CoulombMMM1D::pair_force().