ESPResSo: mmm1d_gpu_cuda.cu File Reference
mmm1d_gpu_cuda.cu File Reference
This file contains the code for the polygamma expansions used for the near formulas of MMM1D on GPU, as well as the force kernels.
#include "config/config.hpp"
#include "electrostatics/mmm-modpsi.hpp"
#include "electrostatics/mmm1d_gpu.hpp"
#include "electrostatics/specfunc.cuh"
#include "BoxGeometry.hpp"
#include "cuda/utils.cuh"
#include "system/System.hpp"
#include <utils/constants.hpp>
#include <utils/math/sqr.hpp>
#include <cuda.h>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <stdexcept>
#include <vector>
Macros
#define cudaSetDevice(d)
Functions
__device__ float dev_mod_psi_even (int n, float x)
__device__ float dev_mod_psi_odd (int n, float x)
static auto numBlocksOps (std::size_t n_ops)
Get number of blocks for a given number of operations.
static auto numBlocks (std::size_t n_part)
Get number of blocks for a given number of particles.
__forceinline__ __device__ float sqpow (float x)
__forceinline__ __device__ float cbpow (float x)
__device__ void sumReduction (float *input, float *sum)
__global__ void sumKernel (float *data, std::size_t N)
__global__ void besselTuneKernel (int *result, float far_switch_radius, int maxCut)
__global__ void forcesKernel (float const *const __restrict__ r, float const *const __restrict__ q, float *const __restrict__ force, std::size_t N, int pairs)
__global__ void energiesKernel (float const *const __restrict__ r, float const *const __restrict__ q, float *const __restrict__ energy, std::size_t N, int pairs)
__global__ void vectorReductionKernel (float const *src, float *dst, std::size_t N)
__global__ void scaleAndAddKernel (float *const dst, float const *const src, std::size_t N, float factor)
Variables
static constexpr int deviceCount = 1
static constexpr unsigned int numThreads = 64u
__constant__ float far_switch_radius_sq [1] = {0.05f * 0.05f}
__constant__ float boxz [1]
__constant__ float uz [1]
__constant__ float coulomb_prefactor [1] = {1.0f}
__constant__ int bessel_cutoff [1] = {5}
__constant__ float maxPWerror [1] = {1e-5f}
constexpr int modpsi_order = 30
constexpr int modpsi_constant_size = modpsi_order * modpsi_order * 2
__constant__ int device_n_modPsi [1] = {0}
__constant__ unsigned int device_linModPsi_offsets [2 *modpsi_order]
__constant__ unsigned int device_linModPsi_lengths [2 *modpsi_order]
__constant__ float device_linModPsi [modpsi_constant_size]
Detailed Description
This file contains the code for the polygamma expansions used for the near formulas of MMM1D on GPU, as well as the force kernels.
Definition in file mmm1d_gpu_cuda.cu.
Macro Definition Documentation
cudaSetDevice
#define cudaSetDevice (d)
Definition at line 57 of file mmm1d_gpu_cuda.cu.
Function Documentation
besselTuneKernel()
__global__ void besselTuneKernel (int * result, float far_switch_radius, int maxCut)
Definition at line 243 of file mmm1d_gpu_cuda.cu.
References dev_K1(), maxPWerror, P, and uz.
cbpow()
__forceinline__ __device__ float cbpow (float x)
Definition at line 207 of file mmm1d_gpu_cuda.cu.
Referenced by forcesKernel().
dev_mod_psi_even()
__device__ float dev_mod_psi_even (int n, float x)
Definition at line 78 of file mmm1d_gpu_cuda.cu.
References device_linModPsi, device_linModPsi_lengths, device_linModPsi_offsets, and evaluateAsTaylorSeriesAt().
Referenced by energiesKernel(), and forcesKernel().
dev_mod_psi_odd()
__device__ float dev_mod_psi_odd (int n, float x)
Definition at line 84 of file mmm1d_gpu_cuda.cu.
References device_linModPsi, device_linModPsi_lengths, device_linModPsi_offsets, and evaluateAsTaylorSeriesAt().
Referenced by forcesKernel().
energiesKernel()
__global__ void energiesKernel (float const *const __restrict__ r, float const *const __restrict__ q, float *const __restrict__ energy, std::size_t N, int pairs)
Definition at line 437 of file mmm1d_gpu_cuda.cu.
References __syncthreads(), bessel_cutoff, boxz, coulomb_prefactor, dev_K0(), dev_mod_psi_even(), device_n_modPsi, far_switch_radius_sq, maxPWerror, N, sqpow(), Utils::sqr(), Utils::sqrt(), sumReduction(), and uz.
Referenced by CoulombMMM1DGpu::add_long_range_energy().
forcesKernel()
__global__ void forcesKernel (float const *const __restrict__ r, float const *const __restrict__ q, float *const __restrict__ force, std::size_t N, int pairs)
Definition at line 349 of file mmm1d_gpu_cuda.cu.
References bessel_cutoff, boxz, cbpow(), coulomb_prefactor, dev_K0(), dev_K1(), dev_mod_psi_even(), dev_mod_psi_odd(), device_n_modPsi, far_switch_radius_sq, force, maxPWerror, N, sqpow(), Utils::sqr(), Utils::sqrt(), and uz.
Referenced by CoulombMMM1DGpu::add_long_range_forces().
numBlocks()
static auto numBlocks (std::size_t n_part) static
Get number of blocks for a given number of particles.
Definition at line 142 of file mmm1d_gpu_cuda.cu.
References numBlocksOps(), and Utils::sqr().
Referenced by CoulombMMM1DGpu::add_long_range_energy(), CoulombMMM1DGpu::add_long_range_forces(), and GpuParticleData::Storage::split_particle_struct().
numBlocksOps()
static auto numBlocksOps (std::size_t n_ops) static
Get number of blocks for a given number of operations.
Definition at line 136 of file mmm1d_gpu_cuda.cu.
References numThreads.
Referenced by CoulombMMM1DGpu::add_long_range_forces(), and numBlocks().
scaleAndAddKernel()
__global__ void scaleAndAddKernel (float *const dst, float const *const src, std::size_t N, float factor)
Definition at line 549 of file mmm1d_gpu_cuda.cu.
References N.
Referenced by CoulombMMM1DGpu::add_long_range_energy().
sqpow()
__forceinline__ __device__ float sqpow (float x)
Definition at line 206 of file mmm1d_gpu_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
sumKernel()
__global__ void sumKernel (float * data, std::size_t N)
Definition at line 221 of file mmm1d_gpu_cuda.cu.
References N, and sumReduction().
Referenced by CoulombMMM1DGpu::add_long_range_energy().
sumReduction()
__device__ void sumReduction (float * input, float * sum)
Definition at line 209 of file mmm1d_gpu_cuda.cu.
References __syncthreads(), and sum.
Referenced by energiesKernel(), and sumKernel().
vectorReductionKernel()
__global__ void vectorReductionKernel (float const * src, float * dst, std::size_t N)
Definition at line 507 of file mmm1d_gpu_cuda.cu.
References N, and Utils::sqr().
Referenced by CoulombMMM1DGpu::add_long_range_forces().
Variable Documentation
bessel_cutoff
__constant__ int bessel_cutoff[1] = {5}
Definition at line 63 of file mmm1d_gpu_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
boxz
__constant__ float boxz[1]
Definition at line 60 of file mmm1d_gpu_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
coulomb_prefactor
__constant__ float coulomb_prefactor[1] = {1.0f}
Definition at line 62 of file mmm1d_gpu_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
device_linModPsi
__constant__ float device_linModPsi[modpsi_constant_size]
Definition at line 76 of file mmm1d_gpu_cuda.cu.
Referenced by dev_mod_psi_even(), and dev_mod_psi_odd().
device_linModPsi_lengths
__constant__ unsigned int device_linModPsi_lengths[2 *modpsi_order]
Definition at line 75 of file mmm1d_gpu_cuda.cu.
Referenced by dev_mod_psi_even(), and dev_mod_psi_odd().
device_linModPsi_offsets
__constant__ unsigned int device_linModPsi_offsets[2 *modpsi_order]
Definition at line 74 of file mmm1d_gpu_cuda.cu.
Referenced by dev_mod_psi_even(), and dev_mod_psi_odd().
device_n_modPsi
__constant__ int device_n_modPsi[1] = {0}
Definition at line 73 of file mmm1d_gpu_cuda.cu.
Referenced by energiesKernel(), and forcesKernel().
deviceCount
constexpr int deviceCount = 1 static constexpr
Definition at line 53 of file mmm1d_gpu_cuda.cu.
Referenced by cuda_get_n_gpus().
far_switch_radius_sq
__constant__ float far_switch_radius_sq[1] = {0.05f * 0.05f}
Definition at line 59 of file mmm1d_gpu_cuda.cu.
Referenced by CoulombMMM1D::CoulombMMM1D(), energiesKernel(), forcesKernel(), CoulombMMM1D::pair_energy(), CoulombMMM1D::pair_force(), and CoulombMMM1D::tune().
maxPWerror
__constant__ float maxPWerror[1] = {1e-5f}
Definition at line 64 of file mmm1d_gpu_cuda.cu.
Referenced by besselTuneKernel(), determine_minrad(), energiesKernel(), and forcesKernel().
modpsi_constant_size
constexpr int modpsi_constant_size = modpsi_order * modpsi_order * 2 constexpr
Definition at line 70 of file mmm1d_gpu_cuda.cu.
modpsi_order
constexpr int modpsi_order = 30 constexpr
Definition at line 69 of file mmm1d_gpu_cuda.cu.
numThreads
constexpr unsigned int numThreads = 64u static constexpr
Definition at line 54 of file mmm1d_gpu_cuda.cu.
Referenced by CoulombMMM1DGpu::add_long_range_energy(), CoulombMMM1DGpu::add_long_range_forces(), and numBlocksOps().
uz
__constant__ float uz[1]
Definition at line 61 of file mmm1d_gpu_cuda.cu.
Referenced by besselTuneKernel(), energiesKernel(), and forcesKernel().