ESPResSo: anonymous_namespace{lb_interpolation.cpp} Namespace Reference
anonymous_namespace{lb_interpolation.cpp} Namespace Reference
Functions
template<typename Op >
void lattice_interpolation (Lattice const &lattice, Utils::Vector3d const &pos, Op &&op)
Utils::Vector3d node_u (Lattice::index_t index)
double node_dens (Lattice::index_t index)
Variables
InterpolationOrder interpolation_order = InterpolationOrder::linear
Function Documentation
lattice_interpolation()
template<typename Op > void anonymous_namespace{lb_interpolation.cpp}::lattice_interpolation (Lattice const & lattice, Utils::Vector3d const & pos, Op && op)
Definition at line 54 of file lb_interpolation.cpp.
References Lattice::map_position_to_lattice(), pos, and D3Q19::w.
Referenced by lb_lbinterpolation_add_force_density(), lb_lbinterpolation_get_interpolated_density(), and lb_lbinterpolation_get_interpolated_velocity().
node_dens()
double anonymous_namespace{lb_interpolation.cpp}::node_dens (Lattice::index_t index)
Definition at line 85 of file lb_interpolation.cpp.
References LB_Parameters::density, lb_calc_modes(), lbfields, lbfluid, and lbpar.
Referenced by lb_lbinterpolation_get_interpolated_density().
node_u()
Utils::Vector3d anonymous_namespace{lb_interpolation.cpp}::node_u (Lattice::index_t index)
Definition at line 74 of file lb_interpolation.cpp.
References LB_Parameters::density, lb_calc_modes(), lbfields, lbfluid, and lbpar.
Referenced by lb_lbinterpolation_get_interpolated_velocity(), and velocity_interpolation().
Variable Documentation
interpolation_order
InterpolationOrder anonymous_namespace{lb_interpolation.cpp}::interpolation_order = InterpolationOrder::linear
Definition at line 34 of file lb_interpolation.cpp.
Referenced by lb_lbfluid_get_interpolated_density(), lb_lbfluid_get_interpolated_velocity(), lb_lbinterpolation_add_force_density(), lb_lbinterpolation_get_interpolation_order(), and mpi_set_interpolation_order_local().