ESPResSo: walberla::ek::accessor::Flux Namespace Reference
walberla::ek::accessor::Flux Namespace Reference
Functions
auto get (GhostLayerField< double, uint_t{13u}> const *flux_field, Cell const &cell)
void initialize (GhostLayerField< double, uint_t{13u}> *flux_field, std::array< double, 13 > const &values)
auto get (GhostLayerField< double, uint_t{13u}> const *flux_field, CellInterval const &ci)
auto get_vector (GhostLayerField< double, uint_t{13u}> const *flux_field, Cell const &cell)
auto get_vector (GhostLayerField< double, uint_t{13u}> const *flux_field, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< double > flux_field, double *j_out)
__global__ void kernel_broadcast (gpu::FieldAccessor< double > flux_field, double const *RESTRICT j_in)
__global__ void kernel_get_vector (gpu::FieldAccessor< double > flux_field, double *j_out)
std::array< double, 13 > get (gpu::GPUField< double > const *flux_field, Cell const &cell)
Get value from a single cell.
void initialize (gpu::GPUField< double > *flux_field, std::array< double, 13 > const &flux)
Initialize all cells with the same value.
std::vector< double > get (gpu::GPUField< double > const *flux_field, CellInterval const &ci)
Get values from a cell interval.
Vector3< double > get_vector (gpu::GPUField< double > const *flux_field, Cell const &cell)
Get flux vector from a single cell.
std::vector< double > get_vector (gpu::GPUField< double > const *flux_field, CellInterval const &ci)
Get flux vector from a cell interval.
auto get (GhostLayerField< float, uint_t{13u}> const *flux_field, Cell const &cell)
void initialize (GhostLayerField< float, uint_t{13u}> *flux_field, std::array< float, 13 > const &values)
auto get (GhostLayerField< float, uint_t{13u}> const *flux_field, CellInterval const &ci)
auto get_vector (GhostLayerField< float, uint_t{13u}> const *flux_field, Cell const &cell)
auto get_vector (GhostLayerField< float, uint_t{13u}> const *flux_field, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< float > flux_field, float *j_out)
__global__ void kernel_broadcast (gpu::FieldAccessor< float > flux_field, float const *RESTRICT j_in)
__global__ void kernel_get_vector (gpu::FieldAccessor< float > flux_field, float *j_out)
std::array< float, 13 > get (gpu::GPUField< float > const *flux_field, Cell const &cell)
Get value from a single cell.
void initialize (gpu::GPUField< float > *flux_field, std::array< float, 13 > const &flux)
Initialize all cells with the same value.
std::vector< float > get (gpu::GPUField< float > const *flux_field, CellInterval const &ci)
Get values from a cell interval.
Vector3< float > get_vector (gpu::GPUField< float > const *flux_field, Cell const &cell)
Get flux vector from a single cell.
std::vector< float > get_vector (gpu::GPUField< float > const *flux_field, CellInterval const &ci)
Get flux vector from a cell interval.
Function Documentation
get() [1/8]
auto walberla::ek::accessor::Flux::get (GhostLayerField< double, uint_t{13u}> const * flux_field, Cell const & cell) inline
Definition at line 190 of file EK_FieldAccessors_double_precision.h.
get() [2/8]
auto walberla::ek::accessor::Flux::get (GhostLayerField< double, uint_t{13u}> const * flux_field, CellInterval const & ci) inline
Definition at line 230 of file EK_FieldAccessors_double_precision.h.
get() [3/8]
auto walberla::ek::accessor::Flux::get (GhostLayerField< float, uint_t{13u}> const * flux_field, Cell const & cell) inline
Definition at line 190 of file EK_FieldAccessors_single_precision.h.
get() [4/8]
auto walberla::ek::accessor::Flux::get (GhostLayerField< float, uint_t{13u}> const * flux_field, CellInterval const & ci) inline
Definition at line 230 of file EK_FieldAccessors_single_precision.h.
get() [5/8]
std::array< double, 13 > walberla::ek::accessor::Flux::get (gpu::GPUField< double > const * flux_field, Cell const & cell)
Get value from a single cell.
Definition at line 565 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_get(), and stream.
get() [6/8]
std::vector< double > walberla::ek::accessor::Flux::get (gpu::GPUField< double > const * flux_field, CellInterval const & ci)
Get values from a cell interval.
Definition at line 592 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_get(), and stream.
get() [7/8]
std::array< float, 13 > walberla::ek::accessor::Flux::get (gpu::GPUField< float > const * flux_field, Cell const & cell)
Get value from a single cell.
Definition at line 565 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_get(), and stream.
get() [8/8]
std::vector< float > walberla::ek::accessor::Flux::get (gpu::GPUField< float > const * flux_field, CellInterval const & ci)
Get values from a cell interval.
Definition at line 592 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_get(), and stream.
get_vector() [1/8]
auto walberla::ek::accessor::Flux::get_vector (GhostLayerField< double, uint_t{13u}> const * flux_field, Cell const & cell) inline
Definition at line 247 of file EK_FieldAccessors_double_precision.h.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::FluxVTKWriter< OutputType >::evaluate(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_vector(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector().
get_vector() [2/8]
auto walberla::ek::accessor::Flux::get_vector (GhostLayerField< double, uint_t{13u}> const * flux_field, CellInterval const & ci) inline
Definition at line 393 of file EK_FieldAccessors_double_precision.h.
get_vector() [3/8]
auto walberla::ek::accessor::Flux::get_vector (GhostLayerField< float, uint_t{13u}> const * flux_field, Cell const & cell) inline
Definition at line 247 of file EK_FieldAccessors_single_precision.h.
get_vector() [4/8]
auto walberla::ek::accessor::Flux::get_vector (GhostLayerField< float, uint_t{13u}> const * flux_field, CellInterval const & ci) inline
Definition at line 390 of file EK_FieldAccessors_single_precision.h.
get_vector() [5/8]
Vector3< double > walberla::ek::accessor::Flux::get_vector (gpu::GPUField< double > const * flux_field, Cell const & cell)
Get flux vector from a single cell.
Definition at line 606 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_get_vector(), and stream.
get_vector() [6/8]
std::vector< double > walberla::ek::accessor::Flux::get_vector (gpu::GPUField< double > const * flux_field, CellInterval const & ci)
Get flux vector from a cell interval.
Definition at line 621 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_get_vector(), and stream.
get_vector() [7/8]
Vector3< float > walberla::ek::accessor::Flux::get_vector (gpu::GPUField< float > const * flux_field, Cell const & cell)
Get flux vector from a single cell.
Definition at line 606 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_get_vector(), and stream.
get_vector() [8/8]
std::vector< float > walberla::ek::accessor::Flux::get_vector (gpu::GPUField< float > const * flux_field, CellInterval const & ci)
Get flux vector from a cell interval.
Definition at line 621 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_get_vector(), and stream.
initialize() [1/4]
void walberla::ek::accessor::Flux::initialize (GhostLayerField< double, uint_t{13u}> * flux_field, std::array< double, 13 > const & values) inline
Definition at line 210 of file EK_FieldAccessors_double_precision.h.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::add_to_storage().
initialize() [2/4]
void walberla::ek::accessor::Flux::initialize (GhostLayerField< float, uint_t{13u}> * flux_field, std::array< float, 13 > const & values) inline
Definition at line 210 of file EK_FieldAccessors_single_precision.h.
initialize() [3/4]
void walberla::ek::accessor::Flux::initialize (gpu::GPUField< double > * flux_field, std::array< double, 13 > const & flux)
Initialize all cells with the same value.
Definition at line 580 of file EK_FieldAccessors_double_precision_CUDA.cu.
References flux, kernel_broadcast(), and stream.
initialize() [4/4]
void walberla::ek::accessor::Flux::initialize (gpu::GPUField< float > * flux_field, std::array< float, 13 > const & flux)
Initialize all cells with the same value.
Definition at line 580 of file EK_FieldAccessors_single_precision_CUDA.cu.
References flux, kernel_broadcast(), and stream.
kernel_broadcast() [1/2]
__global__ void walberla::ek::accessor::Flux::kernel_broadcast (gpu::FieldAccessor< double > flux_field, double const *RESTRICT j_in)
Definition at line 405 of file EK_FieldAccessors_double_precision_CUDA.cu.
References stream.
Referenced by initialize(), and initialize().
kernel_broadcast() [2/2]
__global__ void walberla::ek::accessor::Flux::kernel_broadcast (gpu::FieldAccessor< float > flux_field, float const *RESTRICT j_in)
Definition at line 405 of file EK_FieldAccessors_single_precision_CUDA.cu.
References stream.
kernel_get() [1/2]
__global__ void walberla::ek::accessor::Flux::kernel_get (gpu::FieldAccessor< double > flux_field, double * j_out)
Definition at line 382 of file EK_FieldAccessors_double_precision_CUDA.cu.
References getLinearIndex(), and stream.
Referenced by get(), get(), get(), and get().
kernel_get() [2/2]
__global__ void walberla::ek::accessor::Flux::kernel_get (gpu::FieldAccessor< float > flux_field, float * j_out)
Definition at line 382 of file EK_FieldAccessors_single_precision_CUDA.cu.
References getLinearIndex(), and stream.
kernel_get_vector() [1/2]
__global__ void walberla::ek::accessor::Flux::kernel_get_vector (gpu::FieldAccessor< double > flux_field, double * j_out)
Definition at line 426 of file EK_FieldAccessors_double_precision_CUDA.cu.
References getLinearIndex(), and stream.
Referenced by get_vector(), get_vector(), get_vector(), and get_vector().
kernel_get_vector() [2/2]
__global__ void walberla::ek::accessor::Flux::kernel_get_vector (gpu::FieldAccessor< float > flux_field, float * j_out)
Definition at line 426 of file EK_FieldAccessors_single_precision_CUDA.cu.
References getLinearIndex(), and stream.