ESPResSo: Communication Namespace Reference
Communication Namespace Reference
Namespaces
Result
This namespace contains tag types to indicate what to do with the return values of callbacks.
Classes
class MpiCallbacks
The interface of the MPI callback mechanism.
class RegisterCallback
Helper class to add callbacks before main.
Typedefs
template<class... Args>
using CallbackHandle = MpiCallbacks::CallbackHandle< Args... >
Functions
MpiCallbacks & mpiCallbacks ()
Returns a reference to the global callback class instance.
void init (std::shared_ptr< boost::mpi::environment > mpi_env)
Init globals for communication.
Variables
const auto & mpi_datatype_cache = boost::mpi::detail::mpi_datatype_cache()
std::shared_ptr< boost::mpi::environment > mpi_env
std::unique_ptr< MpiCallbacks > m_callbacks
Typedef Documentation
CallbackHandle
template<class... Args> using Communication::CallbackHandle = typedef MpiCallbacks::CallbackHandle<Args...>
Definition at line 761 of file MpiCallbacks.hpp.
Function Documentation
init()
void Communication::init (std::shared_ptr< boost::mpi::environment > mpi_env)
Init globals for communication.
and calls on_program_start. Keeps a copy of the pointer to the mpi environment to keep it alive while the program is loaded.
Parameters
mpi_env MPI environment that should be used
Definition at line 122 of file communication.cpp.
References Utils::Mpi::cart_create(), comm_cart, ErrorHandling::init_error_handling(), m_callbacks, mpi_env, mpiCallbacks(), n_nodes, node_grid, on_program_start(), and this_node.
Referenced by Utils::Interpolation::bspline_3d_accumulate(), Utils::Interpolation::bspline_3d_gradient_accumulate(), and EspressoSystemStandAlone::EspressoSystemStandAlone().
mpiCallbacks()
MpiCallbacks & Communication::mpiCallbacks ()
Returns a reference to the global callback class instance.
Definition at line 53 of file communication.cpp.
References m_callbacks.
Referenced by get_particle_data(), init(), lb_lbnode_get_density(), lb_lbnode_get_velocity(), mpi_call(), mpi_call_all(), and mpi_loop().
Variable Documentation
m_callbacks
std::unique_ptr<MpiCallbacks> Communication::m_callbacks
Definition at line 50 of file communication.cpp.
Referenced by init(), and mpiCallbacks().
mpi_datatype_cache
const auto& Communication::mpi_datatype_cache = boost::mpi::detail::mpi_datatype_cache()
Definition at line 43 of file communication.cpp.
mpi_env
std::shared_ptr<boost::mpi::environment> Communication::mpi_env
Definition at line 44 of file communication.cpp.
Referenced by EspressoSystemStandAlone::EspressoSystemStandAlone(), and init().