ESPResSo: LeesEdwards Namespace Reference
LeesEdwards Namespace Reference
Classes
class LeesEdwards
struct LinearShear
Lees-Edwards protocol for linear shearing.
struct Off
Lees-Edwards protocol for un-altered periodic boundary conditions.
struct OscillatoryShear
Lees-Edwards protocol for oscillatory shearing.
class PosOffsetGetter
class Push
class ShearVelocityGetter
Visitor to get shear velocity from the Lees-Edwards protocol.
class UpdateOffset
Typedefs
using ActiveProtocol = std::variant< Off, LinearShear, OscillatoryShear >
Type which holds the currently active protocol.
Functions
double velocity_shift (short int le_flag, BoxGeometry const &box)
Utils::Vector3d shear_direction (BoxGeometry const &box)
Utils::Vector3d verlet_list_offset (BoxGeometry const &box, double pos_offset_at_last_resort)
double get_pos_offset (double time, ActiveProtocol const &protocol)
double get_shear_velocity (double time, ActiveProtocol const &protocol)
Calculation of current velocity.
Typedef Documentation
ActiveProtocol
using LeesEdwards::ActiveProtocol = typedef std::variant<Off, LinearShear, OscillatoryShear>
Type which holds the currently active protocol.
Definition at line 75 of file protocols.hpp.
Function Documentation
get_pos_offset()
double LeesEdwards::get_pos_offset (double time, ActiveProtocol const & protocol) inline
Definition at line 88 of file protocols.hpp.
Referenced by LeesEdwards::LeesEdwards::update_box_params().
get_shear_velocity()
double LeesEdwards::get_shear_velocity (double time, ActiveProtocol const & protocol) inline
Calculation of current velocity.
Definition at line 105 of file protocols.hpp.
Referenced by LeesEdwards::LeesEdwards::update_box_params().
shear_direction()
Utils::Vector3d LeesEdwards::shear_direction (BoxGeometry const & box) inline
Definition at line 81 of file lees_edwards.hpp.
References BoxGeometry::lees_edwards_bc(), and LeesEdwardsBC::shear_direction.
Referenced by verlet_list_offset().
velocity_shift()
double LeesEdwards::velocity_shift (short int le_flag, BoxGeometry const & box) inline
Definition at line 74 of file lees_edwards.hpp.
References LEES_EDWARDS, BoxGeometry::lees_edwards_bc(), LeesEdwardsBC::shear_velocity, stream, and BoxGeometry::type().
verlet_list_offset()
Utils::Vector3d LeesEdwards::verlet_list_offset (BoxGeometry const & box, double pos_offset_at_last_resort) inline
Definition at line 85 of file lees_edwards.hpp.
References LEES_EDWARDS, BoxGeometry::lees_edwards_bc(), LeesEdwardsBC::pos_offset, shear_direction(), stream, and BoxGeometry::type().
Referenced by resort_particles_if_needed().