ESPResSo: CollisionDetection Namespace Reference
CollisionDetection Namespace Reference
Classes
class BindAtPointOfCollision
class BindCenters
class CollisionDetection
class GlueToSurface
class Off
Typedefs
using ActiveProtocol = std::variant< Off, BindAtPointOfCollision, GlueToSurface, BindCenters >
using CollisionPair = std::pair< int, int >
Functions
auto detect_collision_common (Particle const &p1, Particle const &p2, int const bond_centers)
auto & get_part (CellStructure &cell_structure, int id)
void place_vs_and_relate_to_particle (CellStructure &cell_structure, BoxGeometry const &box_geo, int const part_type_vs, double const min_global_cut, int const current_vs_pid, Utils::Vector3d const &pos, int const relate_to)
auto gather_collision_queue (std::vector< CollisionPair > const &local)
void add_bind_centers (std::vector< CollisionPair > &collision_queue, System::System &system, int bond_id)
Typedef Documentation
ActiveProtocol
using CollisionDetection::ActiveProtocol = typedef std::variant<Off, BindAtPointOfCollision, GlueToSurface, BindCenters>
Definition at line 34 of file ActiveProtocol.hpp.
CollisionPair
using CollisionDetection::CollisionPair = typedef std::pair<int, int>
Definition at line 29 of file CollisionPair.hpp.
Function Documentation
add_bind_centers()
void CollisionDetection::add_bind_centers (std::vector< CollisionPair > & collision_queue, System::System & system, int bond_id) inline
Definition at line 83 of file core/collision_detection/utils.hpp.
References add_bond(), stream, and use_one_sided_bond_storage.
Referenced by CollisionDetection::BindAtPointOfCollision::handle_collisions(), and CollisionDetection::BindCenters::handle_collisions().
detect_collision_common()
auto CollisionDetection::detect_collision_common (Particle const & p1, Particle const & p2, int const bond_centers) inline
Definition at line 31 of file collision_detection/common.hpp.
References pair_bond_exists_on(), and stream.
Referenced by CollisionDetection::BindAtPointOfCollision::detect_collision(), CollisionDetection::BindCenters::detect_collision(), and CollisionDetection::GlueToSurface::detect_collision().
gather_collision_queue()
auto CollisionDetection::gather_collision_queue (std::vector< CollisionPair > const & local) inline
Definition at line 74 of file core/collision_detection/utils.hpp.
References comm_cart, Utils::Mpi::gather_buffer(), and stream.
Referenced by CollisionDetection::BindAtPointOfCollision::handle_collisions(), and CollisionDetection::GlueToSurface::handle_collisions().
get_part()
auto & CollisionDetection::get_part (CellStructure & cell_structure, int id) inline
Definition at line 48 of file core/collision_detection/utils.hpp.
References CellStructure::get_local_particle(), and stream.
Referenced by CollisionDetection::GlueToSurface::handle_collisions(), and place_vs_and_relate_to_particle().
place_vs_and_relate_to_particle()
void CollisionDetection::place_vs_and_relate_to_particle (CellStructure & cell_structure, BoxGeometry const & box_geo, int const part_type_vs, double const min_global_cut, int const current_vs_pid, Utils::Vector3d const & pos, int const relate_to) inline
Definition at line 60 of file core/collision_detection/utils.hpp.
References CellStructure::add_particle(), get_part(), stream, and vs_relate_to().
Referenced by CollisionDetection::BindAtPointOfCollision::handle_collisions(), and CollisionDetection::GlueToSurface::handle_collisions().