ESPResSo: walberla::lbm::accessor::Equilibrium Namespace Reference
walberla::lbm::accessor::Equilibrium Namespace Reference
Functions
void set (GhostLayerField< double, uint_t{19u}> *pdf_field, Vector3< double > const &u, double const rho, Cell const &cell)
__device__ void kernel_set_device (gpu::FieldAccessor< double > pdf, double const *RESTRICT const u, double rho)
void set (GhostLayerField< float, uint_t{19u}> *pdf_field, Vector3< float > const &u, float const rho, Cell const &cell)
__device__ void kernel_set_device (gpu::FieldAccessor< float > pdf, float const *RESTRICT const u, float rho)
Function Documentation
kernel_set_device() [1/2]
__device__ void walberla::lbm::accessor::Equilibrium::kernel_set_device (gpu::FieldAccessor< double > pdf, double const *RESTRICT const u, double rho)
Definition at line 767 of file FieldAccessorsDoublePrecisionCUDA.cu.
References stream.
Referenced by walberla::lbm::accessor::Density::kernel_set(), walberla::lbm::accessor::Velocity::kernel_set(), walberla::lbm::accessor::Density::kernel_set(), and walberla::lbm::accessor::Velocity::kernel_set().
kernel_set_device() [2/2]
__device__ void walberla::lbm::accessor::Equilibrium::kernel_set_device (gpu::FieldAccessor< float > pdf, float const *RESTRICT const u, float rho)
Definition at line 767 of file FieldAccessorsSinglePrecisionCUDA.cu.
References stream.
set() [1/2]
void walberla::lbm::accessor::Equilibrium::set (GhostLayerField< double, uint_t{19u}> * pdf_field, Vector3< double > const & u, double const rho, Cell const & cell) inline
Definition at line 501 of file FieldAccessorsDoublePrecision.h.
set() [2/2]
void walberla::lbm::accessor::Equilibrium::set (GhostLayerField< float, uint_t{19u}> * pdf_field, Vector3< float > const & u, float const rho, Cell const & cell) inline
Definition at line 501 of file FieldAccessorsSinglePrecision.h.