ESPResSo: ErrorHandling Namespace Reference
ErrorHandling Namespace Reference
Classes
struct RuntimeError
A runtime error.
class RuntimeErrorCollector
class RuntimeErrorStream
Create a runtime error message via the streaming operator.
Functions
void init_error_handling (boost::mpi::communicator const &comm)
Initialize the error collection system.
void deinit_error_handling ()
RuntimeErrorStream _runtimeMessageStream (RuntimeError::ErrorLevel level, const std::string &file, const int line, const std::string &function)
static void mpi_gather_runtime_errors_local ()
std::vector< RuntimeError > mpi_gather_runtime_errors ()
Gather messages on main rank.
std::vector< RuntimeError > mpi_gather_runtime_errors_all (bool is_head_node)
Gather messages on main rank.
Variables
static std::unique_ptr< RuntimeErrorCollector > runtimeErrorCollector
RuntimeErrorCollector instance.
Function Documentation
_runtimeMessageStream()
RuntimeErrorStream ErrorHandling::_runtimeMessageStream (RuntimeError::ErrorLevel level, const std::string & file, const int line, const std::string & function)
Definition at line 55 of file errorhandling.cpp.
References runtimeErrorCollector.
deinit_error_handling()
void ErrorHandling::deinit_error_handling ()
Definition at line 53 of file errorhandling.cpp.
References runtimeErrorCollector.
Referenced by CommunicationEnvironment::~CommunicationEnvironment().
init_error_handling()
void ErrorHandling::init_error_handling (boost::mpi::communicator const & comm)
Initialize the error collection system.
Definition at line 48 of file errorhandling.cpp.
References runtimeErrorCollector.
Referenced by CommunicationEnvironment::CommunicationEnvironment().
mpi_gather_runtime_errors()
std::vector< RuntimeError > ErrorHandling::mpi_gather_runtime_errors ()
Gather messages on main rank.
Only call from main rank.
Definition at line 68 of file errorhandling.cpp.
References mpi_gather_runtime_errors_local(), Communication::mpiCallbacks(), and runtimeErrorCollector.
mpi_gather_runtime_errors_all()
std::vector< RuntimeError > ErrorHandling::mpi_gather_runtime_errors_all (bool is_head_node)
Gather messages on main rank.
Call on all ranks.
Definition at line 73 of file errorhandling.cpp.
References runtimeErrorCollector.
mpi_gather_runtime_errors_local()
static void ErrorHandling::mpi_gather_runtime_errors_local () static
Definition at line 62 of file errorhandling.cpp.
References runtimeErrorCollector.
Referenced by mpi_gather_runtime_errors().
Variable Documentation
runtimeErrorCollector
std::unique_ptr<RuntimeErrorCollector> ErrorHandling::runtimeErrorCollector static
RuntimeErrorCollector instance.
This is a unique pointer so we don't leak on repeated calls of init_error_handling.
Definition at line 46 of file errorhandling.cpp.
Referenced by _runtimeMessageStream(), deinit_error_handling(), errexit(), flush_runtime_errors_local(), init_error_handling(), mpi_gather_runtime_errors(), mpi_gather_runtime_errors_all(), and mpi_gather_runtime_errors_local().