ESPResSo: Thermostat Namespace Reference
Thermostat Namespace Reference
Classes
class Thermostat
Typedefs
using GammaType = Utils::Vector3d
Functions
auto const & handle_particle_gamma (GammaType const &particle_gamma, GammaType const &default_gamma)
auto handle_particle_anisotropy (Particle const &p, GammaType const &gamma_body)
bool are_kT_equal (double old_kT, double new_kT)
Check that two kT values are close up to a small tolerance.
Variables
constexpr GammaType gamma_sentinel {{-1.0, -1.0, -1.0}}
Value for unset friction coefficient.
constexpr GammaType gamma_null {{0.0, 0.0, 0.0}}
Value for a null friction coefficient.
Typedef Documentation
GammaType
using Thermostat::GammaType = typedef Utils::Vector3d
Definition at line 48 of file core/thermostat.hpp.
Function Documentation
are_kT_equal()
bool Thermostat::are_kT_equal (double old_kT, double new_kT) inline
Check that two kT values are close up to a small tolerance.
Definition at line 94 of file core/thermostat.hpp.
References stream.
Referenced by ScriptInterface::Thermostat::Thermostat::update_global_kT(), and LB::LBWalberla::veto_kT().
handle_particle_anisotropy()
auto Thermostat::handle_particle_anisotropy (Particle const & p, GammaType const & gamma_body) inline
Definition at line 78 of file core/thermostat.hpp.
References convert_body_to_space(), and stream.
handle_particle_gamma()
auto const & Thermostat::handle_particle_gamma (GammaType const & particle_gamma, GammaType const & default_gamma) inline
Definition at line 72 of file core/thermostat.hpp.
References gamma_null, and stream.
Referenced by lb_handle_particle_anisotropy().
Variable Documentation
gamma_null
constexpr GammaType Thermostat::gamma_null {{0.0, 0.0, 0.0}} constexpr
Value for a null friction coefficient.
Definition at line 66 of file core/thermostat.hpp.
Referenced by handle_particle_gamma(), and ScriptInterface::Thermostat::Interface< CoreClass >::make_autogamma().
gamma_sentinel
constexpr GammaType Thermostat::gamma_sentinel {{-1.0, -1.0, -1.0}} constexpr
Value for unset friction coefficient.
Sentinel value for the Langevin/Brownian parameters, indicating that they have not been set yet.
Definition at line 58 of file core/thermostat.hpp.