ESPResSo: ScriptInterface::Analysis Namespace Reference
ScriptInterface::Analysis Namespace Reference
Classes
class Analysis
class ObservableStat
Functions
static void check_topology (CellStructure const &cell_structure, int chain_start, int chain_length, int n_chains)
Check if a contiguous range of particle ids exists.
void initialize (Utils::Factory< ObjectHandle > *om)
static auto get_summary (::System::System const &system, Observable_stat const &obs, bool const calc_sp)
Generate an observable summary.
Function Documentation
check_topology()
static void ScriptInterface::Analysis::check_topology (CellStructure const & cell_structure, int chain_start, int chain_length, int n_chains) static
Check if a contiguous range of particle ids exists.
Definition at line 53 of file Analysis.cpp.
References comm_cart, ScriptInterface::Particles::error_msg(), and CellStructure::get_local_particle().
Referenced by ScriptInterface::Analysis::Analysis::do_call_method().
get_summary()
static auto ScriptInterface::Analysis::get_summary (::System::System const & system, Observable_stat const & obs, bool const calc_sp) static
Generate an observable summary.
Parameters
[in] system The system to analyze.
[in] obs The observable handle.
[in] calc_sp Whether to compute a scalar pressure.
Definition at line 44 of file ObservableStat.cpp.
References Observable_stat::accumulate(), Observable_stat::bonded_contribution(), bonded_ia_params, Observable_stat::coulomb, Utils::Span< T >::data(), Observable_stat::dipolar, Observable_stat::external_fields, Observable_stat::get_chunk_size(), BondedInteractionsMap::get_next_key(), BondedInteractionsMap::get_zero_based_type(), Observable_stat::kinetic, Observable_stat::non_bonded_inter_contribution(), Observable_stat::non_bonded_intra_contribution(), and Observable_stat::virtual_sites.
Referenced by ScriptInterface::Analysis::ObservableStat::do_call_method().
initialize()
void ScriptInterface::Analysis::initialize (Utils::Factory< ObjectHandle > * om)
Definition at line 27 of file analysis/initialize.cpp.
References Utils::Factory< T >::register_new().
Referenced by ScriptInterface::initialize().