ESPResSo: LBBoundaries Namespace Reference
LBBoundaries Namespace Reference
Classes
class LBBoundary
Typedefs
using LB_Fluid = std::array< Utils::Span< double >, 19 >
Functions
void add (const std::shared_ptr< LBBoundary > &b)
void remove (const std::shared_ptr< LBBoundary > &b)
bool sanity_check_mach_limit ()
Check the boundary velocities.
void ek_init_boundaries ()
void lb_init_boundaries ()
Initialize boundary conditions for all constraints in the system.
static void lb_collect_boundary_forces_local ()
Utils::Vector3d lbboundary_get_force (LBBoundary const *lbb)
Variables
std::vector< std::shared_ptr< LBBoundary > > lbboundaries
Typedef Documentation
LB_Fluid
using LBBoundaries::LB_Fluid = typedef std::array<Utils::Span<double>, 19>
Definition at line 46 of file lb_boundaries.hpp.
Function Documentation
add()
void LBBoundaries::add (const std::shared_ptr< LBBoundary > & b)
Definition at line 62 of file lb_boundaries.cpp.
References lbboundaries, and on_lbboundary_change().
Referenced by morse_pair_energy(), morse_pair_force_factor(), and CoulombMMM1D::pair_energy().
ek_init_boundaries()
void LBBoundaries::ek_init_boundaries ()
Definition at line 90 of file lb_boundaries.cpp.
References EKParameters::agrid, LB_parameters_gpu::agrid, boundaries, Utils::Vector< T, N >::broadcast(), LB_parameters_gpu::dim, EKParameters::dim_x, EKParameters::dim_y, ek_gather_wallcharge_species_density(), ek_init_species_density_wallcharge(), ek_initialized, ek_parameters, lbboundaries, lbpar_gpu, EKParameters::number_of_boundary_nodes, EKParameters::number_of_nodes, EKParameters::number_of_species, pos, runtimeErrorMsg, and EKParameters::valency.
Referenced by lb_init_boundaries().
lb_collect_boundary_forces_local()
static void LBBoundaries::lb_collect_boundary_forces_local () static
Definition at line 279 of file lb_boundaries.cpp.
References lb_collect_boundary_forces().
Referenced by lbboundary_get_force().
lb_init_boundaries()
void LBBoundaries::lb_init_boundaries ()
Initialize boundary conditions for all constraints in the system.
Initializes the constraints in the system.
This function determines the lattice sites which belong to boundaries and marks them with a corresponding flag.
Definition at line 171 of file lb_boundaries.cpp.
References Lattice::agrid, LB_parameters_gpu::agrid, Utils::Vector< T, N >::broadcast(), calc_node_pos(), comm_cart, CPU, LB_parameters_gpu::dim, ek_init_boundaries(), f, Utils::find_if(), Utils::for_each(), Utils::get_linear_index(), GPU, Lattice::grid, Utils::hadamard_product(), Lattice::halo_grid, lattice_switch, lb_init_boundaries_GPU(), lb_lbfluid_get_lattice_speed(), lbboundaries, lbfields, lblattice, lbpar_gpu, node, LB_parameters_gpu::number_of_boundnodes, pos, runtimeErrorMsg, and this_node.
Referenced by ek_init(), lb_init(), lb_lbfluid_set_agrid(), on_boxl_change(), on_lbboundary_change(), and LBBoundaries::LBBoundary::set_velocity().
lbboundary_get_force()
Utils::Vector3d LBBoundaries::lbboundary_get_force (LBBoundary const * lbb)
Definition at line 286 of file lb_boundaries.cpp.
References CPU, Utils::find_if(), force, GPU, lattice_switch, lb_collect_boundary_forces(), lb_collect_boundary_forces_local(), lb_gpu_get_boundary_forces(), lbboundaries, and mpi_call().
Referenced by LBBoundaries::LBBoundary::get_force().
remove()
void LBBoundaries::remove (const std::shared_ptr< LBBoundary > & b)
Definition at line 70 of file lb_boundaries.cpp.
References lbboundaries, and on_lbboundary_change().
Referenced by Writer::H5md::File::close(), delete_exclusion(), Shapes::Union::remove(), Constraints::Constraints< ParticleRange, Constraint >::remove(), and ScriptInterface::ObjectList< Constraint >::remove().
sanity_check_mach_limit()
bool LBBoundaries::sanity_check_mach_limit ()
Check the boundary velocities.
Sanity check if the velocity defined at LB boundaries is within the Mach number limit of the scheme, i.e. u < 0.2.
Definition at line 79 of file lb_boundaries.cpp.
References lb_lbfluid_get_lattice_speed(), and lbboundaries.
Referenced by lb_boundary_mach_check().
Variable Documentation
lbboundaries
std::vector< std::shared_ptr< LBBoundary > > LBBoundaries::lbboundaries
Definition at line 59 of file lb_boundaries.cpp.
Referenced by add(), ek_init_boundaries(), GetIBMInterpolatedVelocity(), InitCUDA_IBM(), lb_bounce_back(), lb_collect_boundary_forces(), lb_gpu_get_boundary_forces(), lb_init_boundaries(), lb_init_boundaries_GPU(), lb_integrate(), lb_integrate_GPU(), lbboundary_get_force(), remove(), and sanity_check_mach_limit().