ESPResSo: Coulomb Namespace Reference
Coulomb Namespace Reference
Namespaces
traits
Classes
class Actor
struct ShortRangeEnergyKernel
struct ShortRangeForceCorrectionsKernel
struct ShortRangeForceKernel
struct ShortRangePressureKernel
Functions
void check_charge_neutrality (double relative_tolerance)
Check if the system is charge-neutral.
void sanity_checks ()
void on_coulomb_change ()
called every time the Coulomb parameters are changed.
void on_boxl_change ()
void on_node_grid_change ()
Called when the node_grid changed.
void on_periodicity_change ()
Called when the periodicity changes.
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
Utils::Vector9d calc_pressure_long_range (ParticleRange const &particles)
double cutoff ()
void on_observable_calc ()
called before calculating observables, i.e.
void calc_long_range_force (ParticleRange const &particles)
double calc_energy_long_range (ParticleRange const &particles)
static auto calc_charge_excess_ratio (std::vector< double > const &charges)
Compute the net charge rescaled by the smallest non-zero charge.
ShortRangeForceKernel::result_type pair_force_kernel ()
ShortRangeForceCorrectionsKernel::result_type pair_force_elc_kernel ()
ShortRangePressureKernel::result_type pair_pressure_kernel ()
ShortRangeEnergyKernel::result_type pair_energy_kernel ()
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr>
void add_actor (std::shared_ptr< T > const &actor)
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr>
void remove_actor (std::shared_ptr< T > const &actor)
Function Documentation
add_actor()
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr> void Coulomb::add_actor (std::shared_ptr< T > const & actor)
Definition at line 43 of file electrostatics/registration.hpp.
References electrostatics_actor, get_actor_name(), and on_coulomb_change().
calc_charge_excess_ratio()
static auto Coulomb::calc_charge_excess_ratio (std::vector< double > const & charges) static
Compute the net charge rescaled by the smallest non-zero charge.
Definition at line 304 of file coulomb.cpp.
References Utils::abs(), and anonymous_namespace{Correlator.cpp}::min().
Referenced by check_charge_neutrality().
calc_energy_long_range()
double Coulomb::calc_energy_long_range (ParticleRange const & particles)
Definition at line 295 of file coulomb.cpp.
References electrostatics_actor, and Cells::particles().
calc_long_range_force()
void Coulomb::calc_long_range_force (ParticleRange const & particles)
Definition at line 283 of file coulomb.cpp.
References ek_calculate_electrostatic_coupling(), electrostatics_actor, Cells::particles(), and this_node.
Referenced by calc_long_range_forces().
calc_pressure_long_range()
Utils::Vector9d Coulomb::calc_pressure_long_range (ParticleRange const & particles)
Definition at line 131 of file coulomb.cpp.
References electrostatics_actor, and Cells::particles().
check_charge_neutrality()
void Coulomb::check_charge_neutrality (double excess_ratio)
Check if the system is charge-neutral.
Definition at line 321 of file coulomb.cpp.
References calc_charge_excess_ratio(), cell_structure, comm_cart, CellStructure::local_particles(), and this_node.
Referenced by Coulomb::Actor< ReactionField >::sanity_checks_charge_neutrality().
cutoff()
double Coulomb::cutoff ()
Definition at line 171 of file coulomb.cpp.
References electrostatics_actor.
Referenced by force_calc(), recalc_long_range_cutoff(), recalc_maximal_cutoff(), and thole_pair_energy().
on_boxl_change()
void Coulomb::on_boxl_change ()
Definition at line 76 of file coulomb.cpp.
References electrostatics_actor, and visit_active_actor_try_catch().
Referenced by mpi_set_box_length_local(), on_boxl_change(), and velocity_verlet_npt_propagate_pos().
on_cell_structure_change()
void Coulomb::on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
This one is potentially slow.
Definition at line 94 of file coulomb.cpp.
Referenced by cells_re_init(), on_cell_structure_change(), and set_hybrid_decomposition().
on_coulomb_change()
void Coulomb::on_coulomb_change ()
called every time the Coulomb parameters are changed.
all Coulomb methods have a short range part, aka near field correction. Even in case of switching off, we should call this, since the required cutoff might have reduced.
Definition at line 71 of file coulomb.cpp.
Referenced by add_actor(), on_coulomb_and_dipoles_change(), on_coulomb_change(), remove_actor(), CoulombMMM1D::tune(), and CoulombP3M::tune().
on_node_grid_change()
void Coulomb::on_node_grid_change ()
Called when the node_grid changed.
Definition at line 81 of file coulomb.cpp.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), mpi_set_node_grid_local(), and on_node_grid_change().
on_observable_calc()
void Coulomb::on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M etc.).
Definition at line 192 of file coulomb.cpp.
Referenced by calculate_energy_local(), calculate_pressure_local(), dpd_viscous_stress_local(), get_pairs_filtered(), and on_observable_calc().
on_periodicity_change()
void Coulomb::on_periodicity_change ()
Called when the periodicity changes.
Internally calls on_skin_change.
Definition at line 88 of file coulomb.cpp.
Referenced by mpi_set_periodicity_local(), and on_periodicity_change().
pair_energy_kernel()
ShortRangeEnergyKernel::result_type Coulomb::pair_energy_kernel () inline
Definition at line 200 of file coulomb_inline.hpp.
References electrostatics_actor.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), calculate_energy_local(), PairCriteria::EnergyCriterion::decide(), and particle_short_range_energy_contribution_local().
pair_force_elc_kernel()
ShortRangeForceCorrectionsKernel::result_type Coulomb::pair_force_elc_kernel () inline
Definition at line 180 of file coulomb_inline.hpp.
References electrostatics_actor.
Referenced by force_calc(), and ICCStar::iteration().
pair_force_kernel()
ShortRangeForceKernel::result_type Coulomb::pair_force_kernel () inline
Definition at line 94 of file coulomb_inline.hpp.
References electrostatics_actor.
Referenced by calculate_pressure_local(), Constraints::ShapeBasedConstraint::force(), force_calc(), ICCStar::iteration(), and Coulomb::ShortRangePressureKernel::operator()().
pair_pressure_kernel()
ShortRangePressureKernel::result_type Coulomb::pair_pressure_kernel () inline
Definition at line 190 of file coulomb_inline.hpp.
References electrostatics_actor.
Referenced by calculate_pressure_local().
remove_actor()
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr> void Coulomb::remove_actor (std::shared_ptr< T > const & actor)
Definition at line 54 of file electrostatics/registration.hpp.
References electrostatics_actor, is_already_stored(), and on_coulomb_change().
sanity_checks()
void Coulomb::sanity_checks ()
Definition at line 64 of file coulomb.cpp.
References electrostatics_actor.
Referenced by long_range_interactions_sanity_checks().