ESPResSo: LB Namespace Reference
LB Namespace Reference
Classes
class CouplingBookkeeping
Keep track of ghost particles that have already been coupled once.
struct LBNone
struct LBWalberla
struct LBWalberlaParams
struct NoLBActive
class ParticleCoupling
struct Solver
Typedefs
using HydrodynamicsActor = std::variant< std::shared_ptr< LBWalberla >, std::shared_ptr< LBNone > >
Functions
static void lb_coupling_sanity_checks (Particle const &p)
bool is_tracer (Particle const &p)
static auto is_solver_set (std::unique_ptr< Solver::Implementation > const &ptr)
static void check_solver (std::unique_ptr< Solver::Implementation > const &ptr)
Typedef Documentation
HydrodynamicsActor
using LB::HydrodynamicsActor = typedef std::variant< std::shared_ptr<LBWalberla>, std::shared_ptr<LBNone> >
Definition at line 35 of file lb/Implementation.hpp.
Function Documentation
check_solver()
static void LB::check_solver (std::unique_ptr< Solver::Implementation > const & ptr) static
Definition at line 59 of file lb/Solver.cpp.
References is_solver_set(), and stream.
Referenced by LB::Solver::get_agrid(), LB::Solver::get_kT(), LB::Solver::get_momentum(), LB::Solver::get_pressure_tensor(), LB::Solver::get_tau(), LB::Solver::ghost_communication(), LB::Solver::ghost_communication_pdf(), LB::Solver::ghost_communication_vel(), LB::Solver::is_gpu(), and LB::Solver::propagate().
is_solver_set()
static auto LB::is_solver_set (std::unique_ptr< Solver::Implementation > const & ptr) static
Definition at line 55 of file lb/Solver.cpp.
References stream.
Referenced by check_solver(), and LB::Solver::is_solver_set().
is_tracer()
bool LB::is_tracer (Particle const & p) inline
Definition at line 146 of file particle_coupling.hpp.
References Particle::propagation(), and PropagationMode::TRANS_LB_TRACER.
Referenced by System::System::lb_couple_particles(), lb_tracers_add_particle_force_to_fluid(), and lb_tracers_propagate().
lb_coupling_sanity_checks()
static void LB::lb_coupling_sanity_checks (Particle const & p) static
Definition at line 335 of file particle_coupling.cpp.
References Particle::gamma(), Particle::id(), runtimeErrorMsg, and stream.
Referenced by System::System::lb_couple_particles().