ESPResSo: Accumulators Namespace Reference
Accumulators Namespace Reference
Namespaces
anonymous_namespace{accumulators.cpp}
Classes
class AccumulatorBase
class Correlator
The main correlator class.
class MeanVarianceCalculator
class TimeSeries
Record values of an observable.
Functions
std::vector< double > compress_linear (std::vector< double > const &A1, std::vector< double > const &A2)
Compress computing arithmetic mean: A_compressed=(A1+A2)/2.
std::vector< double > compress_discard1 (std::vector< double > const &A1, std::vector< double > const &A2)
Compress discarding the 1st argument and return the 2nd.
std::vector< double > compress_discard2 (std::vector< double > const &A1, std::vector< double > const &A2)
Compress discarding the 2nd argument and return the 1st.
std::vector< double > scalar_product (std::vector< double > const &A, std::vector< double > const &B, Utils::Vector3d const &)
std::vector< double > componentwise_product (std::vector< double > const &A, std::vector< double > const &B, Utils::Vector3d const &)
std::vector< double > tensor_product (std::vector< double > const &A, std::vector< double > const &B, Utils::Vector3d const &)
std::vector< double > square_distance_componentwise (std::vector< double > const &A, std::vector< double > const &B, Utils::Vector3d const &)
std::vector< double > fcs_acf (std::vector< double > const &A, std::vector< double > const &B, Utils::Vector3d const &wsquare)
void auto_update (boost::mpi::communicator const &comm, int steps)
Update accumulators.
int auto_update_next_update ()
void auto_update_add (AccumulatorBase *acc)
void auto_update_remove (AccumulatorBase *acc)
bool auto_update_contains (AccumulatorBase const *acc) noexcept
Function Documentation
auto_update()
void Accumulators::auto_update (boost::mpi::communicator const & comm, int steps)
Update accumulators.
Checks for all auto update accumulators if they need to be updated and if so does.
Definition at line 42 of file accumulators.cpp.
References Accumulators::anonymous_namespace{accumulators.cpp}::auto_update_accumulators.
Referenced by System::System::integrate_with_signal_handler().
auto_update_add()
void Accumulators::auto_update_add (AccumulatorBase * acc)
Definition at line 72 of file accumulators.cpp.
References Accumulators::anonymous_namespace{accumulators.cpp}::auto_update_accumulators, and auto_update_contains().
auto_update_contains()
bool Accumulators::auto_update_contains (AccumulatorBase const * acc) noexcept
Definition at line 85 of file accumulators.cpp.
References Accumulators::anonymous_namespace{accumulators.cpp}::auto_update_accumulators.
Referenced by auto_update_add(), and auto_update_remove().
auto_update_next_update()
int Accumulators::auto_update_next_update ()
Definition at line 55 of file accumulators.cpp.
Referenced by System::System::integrate_with_signal_handler().
auto_update_remove()
void Accumulators::auto_update_remove (AccumulatorBase * acc)
Definition at line 77 of file accumulators.cpp.
References Accumulators::anonymous_namespace{accumulators.cpp}::auto_update_accumulators, and auto_update_contains().
componentwise_product()
std::vector<double> Accumulators::componentwise_product (std::vector< double > const & A, std::vector< double > const & B, Utils::Vector3d const &)
Definition at line 90 of file Correlator.cpp.
compress_discard1()
std::vector<double> Accumulators::compress_discard1 (std::vector< double > const & A1, std::vector< double > const & A2)
Compress discarding the 1st argument and return the 2nd.
Definition at line 63 of file Correlator.cpp.
compress_discard2()
std::vector<double> Accumulators::compress_discard2 (std::vector< double > const & A1, std::vector< double > const & A2)
Compress discarding the 2nd argument and return the 1st.
Definition at line 71 of file Correlator.cpp.
compress_linear()
std::vector<double> Accumulators::compress_linear (std::vector< double > const & A1, std::vector< double > const & A2)
Compress computing arithmetic mean: A_compressed=(A1+A2)/2.
Definition at line 51 of file Correlator.cpp.
fcs_acf()
std::vector<double> Accumulators::fcs_acf (std::vector< double > const & A, std::vector< double > const & B, Utils::Vector3d const & wsquare)
Definition at line 139 of file Correlator.cpp.
References Utils::sqr().
scalar_product()
std::vector<double> Accumulators::scalar_product (std::vector< double > const & A, std::vector< double > const & B, Utils::Vector3d const &)
Definition at line 78 of file Correlator.cpp.
square_distance_componentwise()
std::vector<double> Accumulators::square_distance_componentwise (std::vector< double > const & A, std::vector< double > const & B, Utils::Vector3d const &)
Definition at line 119 of file Correlator.cpp.
tensor_product()
std::vector<double> Accumulators::tensor_product (std::vector< double > const & A, std::vector< double > const & B, Utils::Vector3d const &)
Definition at line 104 of file Correlator.cpp.
Referenced by constraint_stress(), dpd_pair_force(), dpd_viscous_stress_local(), and FieldCoupling::Fields::PlaneWave< T, codim >::jacobian().