ESPResSo: Utils Namespace Reference
Utils Namespace Reference
Namespaces
Interpolation
Mpi
Statistics
Classes
class Accumulator
struct AccumulatorData
struct Array
class Bag
Bag of elements.
class Cache
class compact_vector
Custom vector container optimized for size.
struct conjunction
struct conjunction< B1 >
struct conjunction< B1, Bn... >
class Counter
class CylindricalHistogram
Histogram in cylindrical coordinates.
class CylindricalTransformationParameters
A class to hold and validate parameters for a cylindrical coordinate transformations.
struct decay_to_scalar
Meta function to turns a Vector<1, T> into T.
struct decay_to_scalar< Vector< T, 1 > >
struct decay_to_scalar< Vector< T, N > >
class Factory
Factory template.
struct function_remove_const
Remove const from a function signature.
struct function_remove_const< R(Args...) const >
struct function_remove_const< R(Args...)>
class Histogram
Histogram in Cartesian coordinates.
struct is_statically_serializable
Type trait to indicate that a type is serializable with a static size, e.g.
struct Matrix
Matrix representation with static size.
class MemcpyIArchive
Archive that deserializes from a buffer via memcpy.
class MemcpyOArchive
Archive that serializes to a buffer via memcpy.
class NumeratedContainer
Container for objects that are identified by a numeric id.
struct Quaternion
Quaternion representation.
struct size_in_bits
Size of a type in bits.
class Span
A stripped-down version of std::span from C++17.
struct tuple_element
struct tuple_element< I, Array< T, N > >
struct tuple_element< I, Vector< T, N > >
struct tuple_size
struct tuple_size< Array< T, N > >
struct tuple_size< Vector< T, N > >
class Vector
Typedefs
template<std::size_t I, class Tuple >
using tuple_element_t = typename tuple_element< I, Tuple >::type
template<class T >
using Vector3 = Vector< T, 3 >
template<std::size_t N>
using VectorXd = Vector< double, N >
using Vector2d = VectorXd< 2 >
using Vector3d = VectorXd< 3 >
using Vector4d = VectorXd< 4 >
using Vector6d = VectorXd< 6 >
using Vector9d = VectorXd< 9 >
using Vector19d = VectorXd< 19 >
template<std::size_t N>
using VectorXf = Vector< float, N >
using Vector3f = VectorXf< 3 >
template<std::size_t N>
using VectorXi = Vector< int, N >
using Vector3i = VectorXi< 3 >
Enumerations
enum MemoryOrder { MemoryOrder::COLUMN_MAJOR, MemoryOrder::ROW_MAJOR }
Functions
template<std::size_t I>
auto get (const LB_Fluid_Ref &lb_fluid)
template<std::size_t I, class T , std::size_t N>
auto get (Array< T, N > const &a) -> std::enable_if_t<(I< N), const T & >
template<class T >
constexpr std::add_const< T >::type & as_const (T &t) noexcept
template<typename ParticleRange >
bool check_charge_neutrality (ParticleRange &prange)
template<class InputIt , class T >
bool contains (InputIt first, InputIt last, T const &value)
Check whether an iterator range contains a value.
template<class Range , class T >
bool contains (const Range &rng, T const &value)
Check whether a range contains a value.
template<class T >
std::string demangle ()
Get a human-readable name for a type.
template<class Range , class OutputIterator >
void flatten (Range const &v, OutputIterator out)
Flatten a range of ranges.
template<typename ForwardIterator , typename BinaryOp >
void for_each_pair (ForwardIterator first, ForwardIterator last, BinaryOp op)
Execute op for each pair of elements in [first, last) once.
template<typename ForwardRange , typename BinaryOp >
void for_each_pair (ForwardRange &&rng, BinaryOp &&op)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<typename ForwardIterator , typename BinaryOp >
void for_each_cartesian_pair (ForwardIterator first1, ForwardIterator last1, ForwardIterator first2, ForwardIterator last2, BinaryOp op)
Execute op for each pair of elements between [first1, last1) and [first2, last2).
template<typename ForwardRange , typename BinaryOp >
void for_each_cartesian_pair (ForwardRange &&rng1, ForwardRange &&rng2, BinaryOp &&op)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<typename ForwardIterator , typename BinaryOp , typename BinaryCmp >
void for_each_cartesian_pair_if (ForwardIterator first1, ForwardIterator last1, ForwardIterator first2, ForwardIterator last2, BinaryOp op, BinaryCmp cmp)
Execute op for each pair of elements between [first1, last1) and [first2, last2) if a condition is satisfied.
template<typename ForwardRange , typename BinaryOp , typename BinaryCmp >
void for_each_cartesian_pair_if (ForwardRange &&rng1, ForwardRange &&rng2, BinaryOp &&op, BinaryCmp cmp)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<std::size_t I, typename T >
const std::tuple_element_t< I, T > & get (const T &v)
int get_linear_index (int a, int b, int c, const Vector3i &adim, MemoryOrder memory_order=MemoryOrder::COLUMN_MAJOR)
get the linear index from the position (a,b,c) in a 3D grid of dimensions adim.
int get_linear_index (const Vector3i &ind, const Vector3i &adim, MemoryOrder memory_order=MemoryOrder::COLUMN_MAJOR)
template<class T >
T upper_triangular (T i, T j, T n)
Linear index into an upper triangular matrix.
template<template< std::size_t > class F, std::size_t min, std::size_t max, class... Args>
decltype(auto) integral_parameter (std::size_t i, Args &&... args)
Generate a call table for a integral non-type template parameter.
template<typename Map >
auto keys (Map const &m) -> std::vector< typename Map::key_type >
Return the keys of a map type.
template<typename T , typename Container >
T linear_interpolation (Container const &table, T hi, T offset, T x)
Linear interpolation between two data points.
template<class T , class Integral >
auto mask (Integral mask, T t) -> std::enable_if_t< std::is_unsigned< Integral >::value &&(size_in_bits< Integral >::value >=tuple_size< T >::value), T >
Pick elements of a tuple-like by a bit mask.
DEVICE_QUALIFIER double abs (double x)
Return the absolute value of x.
DEVICE_QUALIFIER float abs (float x)
Return the absolute value of x.
template<typename T >
constexpr T AS_erfc_part (T d)
Approximate \(\exp(d^2) \mathrm{erfc}(d)\) by applying a formula from [1] chapter 7.
template<int order, typename T >
DEVICE_QUALIFIER auto bspline (int i, T x) -> std::enable_if_t<(order > 0) &&(order<=7), T >
Formula of the B-spline.
template<class T >
auto bspline (int i, T x, int k)
Calculate B-splines.
template<int order, typename T = double>
DEVICE_QUALIFIER auto bspline_d (int i, T x) -> std::enable_if_t<(order > 0) &&(order<=7), T >
Derivative of the B-spline.
Vector3d basis_change (Vector3d const &b1, Vector3d const &b2, Vector3d const &b3, Vector3d const &v, bool reverse=false)
Basis change.
Vector3d transform_coordinate_cartesian_to_cylinder (Vector3d const &pos)
Coordinate transformation from Cartesian to cylindrical coordinates.
Vector3d transform_coordinate_cartesian_to_cylinder (Vector3d const &pos, Vector3d const &axis, Vector3d const &orientation)
Coordinate transformation from Cartesian to cylindrical coordinates with change of basis.
Vector3d transform_coordinate_cylinder_to_cartesian (Vector3d const &pos)
Coordinate transformation from cylindrical to Cartesian coordinates.
Vector3d transform_coordinate_cylinder_to_cartesian (Vector3d const &pos, Vector3d const &axis, Vector3d const &orientation)
Coordinate transformation from cylindrical to Cartesian coordinates with change of basis.
Vector3d transform_vector_cartesian_to_cylinder (Vector3d const &vec, Vector3d const &axis, Vector3d const &pos)
Vector transformation from Cartesian to cylindrical coordinates.
double gaussian (Vector3d x, Vector3d x0, double sigma)
Utils::Vector3d del_gaussian (Vector3d x, Vector3d x0, double sigma)
template<unsigned n, typename T >
constexpr DEVICE_QUALIFIER T int_pow (T x)
Calculate integer powers.
template<class T >
auto make_lin_space (T start, T stop, std::size_t number, bool endpoint=true)
Equally spaced values in interval.
template<typename T , std::size_t N, const std::array< std::array< int, N >, N > & matrix, typename Container >
constexpr std::array< T, N > matrix_vector_product (const Container &vec)
Calculate the matrix-vector product for a statically given (square) matrix.
template<typename T , std::size_t N>
Vector< T, N > calc_orthonormal_vector (Vector< T, N > const &vec)
Return a vector that is orthonormal to vec.
void permute_ifield (int *field, int size, int permute)
permute an integer array field of size size about permute positions.
template<class T >
Vector< T, 3 > convert_quaternion_to_director (Quaternion< T > const &quat)
Convert quaternion to director.
template<class T >
Quaternion< T > convert_director_to_quaternion (Vector< T, 3 > const &d)
Convert director to quaternion.
template<typename T >
constexpr int sgn (T val)
Calculate signum of val.
template<typename T >
DEVICE_QUALIFIER T sinc (T d)
Calculates the sinc-function as sin(PI*x)/(PI*x).
template<typename T >
constexpr DEVICE_QUALIFIER T sqr (T x)
Calculates the SQuaRe of x.
template<typename T , std::size_t N, std::size_t M>
Matrix< T, N, M > tensor_product (const Vector< T, N > &x, const Vector< T, M > &y)
template<typename T , std::size_t N>
Vector< T, N > tensor_product (const T &x, const Vector< T, N > &y)
Vector3d get_n_triangle (const Vector3d &P1, const Vector3d &P2, const Vector3d &P3)
Computes the normal vector of a triangle.
double area_triangle (const Vector3d &P1, const Vector3d &P2, const Vector3d &P3)
Computes the area of triangle between vectors P1,P2,P3, by computing the cross product P1P2 x P1P3 and taking the half of its norm.
double angle_btw_triangles (const Vector3d &P1, const Vector3d &P2, const Vector3d &P3, const Vector3d &P4)
Computes the angle between two triangles in 3D space.
Vector3d vec_rotate (const Vector3d &axis, double angle, const Vector3d &vector)
Rotate a vector around an axis.
double angle_between (Vector3d const &v1, Vector3d const &v2)
Determine the angle between two vectors.
template<typename T , std::size_t M, std::size_t N>
Utils::Vector< T, M *N > flatten (Matrix< T, M, N > const &m)
template<typename T , std::size_t Rows, std::size_t Cols>
Matrix< T, Rows, Cols > diagonal_mat (Utils::Vector< T, Rows > const &v)
template<typename T , std::size_t Rows, std::size_t Cols>
Matrix< T, Rows, Cols > identity_mat ()
template<typename T , typename U , std::enable_if_t< std::is_arithmetic< U >::value, bool > = true>
Quaternion< T > operator* (const U &b, const Quaternion< T > &a)
Product quaternion and arithmetic type.
template<typename T >
Matrix< T, 3, 3 > rotation_matrix (Quaternion< T > const &q)
Convert quaternion to rotation matrix.
template<class T , class F >
auto raster (Vector< T, 3 > const &offset, Vector< T, 3 > const &grid_spacing, Vector3i size, F f)
Raster a function over a regular 3d grid.
std::vector< Vector3d > get_cylindrical_sampling_positions (std::pair< double, double > const &r_limits, std::pair< double, double > const &phi_limits, std::pair< double, double > const &z_limits, std::size_t n_r_bins, std::size_t n_phi_bins, std::size_t n_z_bins, double sampling_density)
Generate sampling positions for a cylindrical histogram.
template<class T >
std::string pack (T const &v)
Pack a serialize type into a string.
template<class T >
T unpack (std::string const &state)
Unpack a serialize type into a string.
template<typename T >
constexpr DEVICE_QUALIFIER Span< T > make_span (T *p, std::size_t N)
template<class C >
constexpr DEVICE_QUALIFIER auto make_span (C &c)
template<typename T >
constexpr DEVICE_QUALIFIER Span< std::add_const_t< T > > make_const_span (T *p, std::size_t N)
template<class C >
constexpr DEVICE_QUALIFIER auto make_const_span (C &c)
template<class F , class Tuple >
constexpr decltype(auto) apply (F &&f, Tuple &&t)
Call function with expanded tuple as parameters.
template<class F , class Tuple >
void for_each (F &&f, Tuple &t)
template<class F , class Tuple >
void for_each (F &&f, Tuple &&t)
template<class Pred , class Tuple , class F >
constexpr auto find_if (Pred &&pred, Tuple const &t, F &&f)
Find first element in tuple for which a predicate holds, and call a Callable with the element.
template<template< class > class Predicate, class Tuple >
constexpr auto filter (Tuple const &in)
Filter a tuple by a static predicate.
constexpr uint64_t u32_to_u64 (uint32_t high, uint32_t low)
constexpr std::pair< uint32_t, uint32_t > u64_to_u32 (uint64_t in)
constexpr double uniform (uint64_t in)
Uniformly map unsigned integer to double.
template<std::size_t N, typename T >
constexpr bool operator< (Vector< T, N > const &a, Vector< T, N > const &b)
template<std::size_t N, typename T >
constexpr bool operator> (Vector< T, N > const &a, Vector< T, N > const &b)
template<std::size_t N, typename T >
constexpr bool operator<= (Vector< T, N > const &a, Vector< T, N > const &b)
template<std::size_t N, typename T >
constexpr bool operator>= (Vector< T, N > const &a, Vector< T, N > const &b)
template<std::size_t N, typename T >
constexpr bool operator== (Vector< T, N > const &a, Vector< T, N > const &b)
template<std::size_t N, typename T >
constexpr bool operator!= (Vector< T, N > const &a, Vector< T, N > const &b)
template<std::size_t N, typename T , typename U >
auto operator+ (Vector< T, N > const &a, Vector< U, N > const &b)
template<std::size_t N, typename T >
Vector< T, N > & operator+= (Vector< T, N > &a, Vector< T, N > const &b)
template<std::size_t N, typename T , typename U >
auto operator- (Vector< T, N > const &a, Vector< U, N > const &b)
template<std::size_t N, typename T >
Vector< T, N > operator- (Vector< T, N > const &a)
template<std::size_t N, typename T >
Vector< T, N > & operator-= (Vector< T, N > &a, Vector< T, N > const &b)
template<std::size_t N, typename T , class U , std::enable_if_t< std::is_arithmetic< U >::value, bool > = true>
auto operator* (U const &a, Vector< T, N > const &b)
template<std::size_t N, typename T , class U , std::enable_if_t< std::is_arithmetic< U >::value, bool > = true>
auto operator* (Vector< T, N > const &b, U const &a)
template<std::size_t N, typename T >
Vector< T, N > & operator*= (Vector< T, N > &b, T const &a)
template<std::size_t N, typename T >
Vector< T, N > operator/ (Vector< T, N > const &a, T const &b)
template<std::size_t N, typename T >
Vector< T, N > & operator/= (Vector< T, N > &a, T const &b)
template<std::size_t N, typename T , class U , class = std::enable_if_t<not(detail::is_vector<T>::value or detail::is_vector<U>::value)>>
auto operator* (Vector< T, N > const &a, Vector< U, N > const &b)
template<std::size_t N, typename T , class U , class = std::enable_if_t<std::is_integral<T>::value && std::is_integral<U>::value>>
auto operator% (Vector< T, N > const &a, Vector< U, N > const &b)
template<std::size_t N, typename T >
Vector< T, N > sqrt (Vector< T, N > const &a)
template<class T >
Vector< T, 3 > vector_product (Vector< T, 3 > const &a, Vector< T, 3 > const &b)
template<class T , std::size_t N>
T product (Vector< T, N > const &v)
template<class T , class U , std::size_t N>
auto hadamard_product (Vector< T, N > const &a, Vector< U, N > const &b)
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<T>::value)>>
auto hadamard_product (T const &a, Vector< U, N > const &b)
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<U>::value)>>
auto hadamard_product (Vector< T, N > const &a, U const &b)
template<typename T , typename U , class = std::enable_if_t<not(detail::is_vector<T>::value or detail::is_vector<U>::value)>>
auto hadamard_product (T const &a, U const &b)
template<class T , class U , std::size_t N>
auto hadamard_division (Vector< T, N > const &a, Vector< U, N > const &b)
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<U>::value)>>
auto hadamard_division (Vector< T, N > const &a, U const &b)
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<T>::value)>>
auto hadamard_division (T const &a, Vector< U, N > const &b)
template<typename T , typename U , class = std::enable_if_t<not(detail::is_vector<T>::value or detail::is_vector<U>::value)>>
auto hadamard_division (T const &a, U const &b)
template<typename T >
Vector< T, 3 > unit_vector (int i)
template<std::size_t I, class T , std::size_t N>
auto get (Vector< T, N > const &a) -> std::enable_if_t<(I< N), const T & >
Typedef Documentation
tuple_element_t
template<std::size_t I, class Tuple > using Utils::tuple_element_t = typedef typename tuple_element<I, Tuple>::type
Definition at line 37 of file get.hpp.
Vector19d
using Utils::Vector19d = typedef VectorXd<19>
Definition at line 161 of file Vector.hpp.
Vector2d
using Utils::Vector2d = typedef VectorXd<2>
Definition at line 156 of file Vector.hpp.
Vector3
template<class T > using Utils::Vector3 = typedef Vector<T, 3>
Definition at line 153 of file Vector.hpp.
Vector3d
using Utils::Vector3d = typedef VectorXd<3>
Definition at line 157 of file Vector.hpp.
Vector3f
using Utils::Vector3f = typedef VectorXf<3>
Definition at line 164 of file Vector.hpp.
Vector3i
using Utils::Vector3i = typedef VectorXi<3>
Definition at line 167 of file Vector.hpp.
Vector4d
using Utils::Vector4d = typedef VectorXd<4>
Definition at line 158 of file Vector.hpp.
Vector6d
using Utils::Vector6d = typedef VectorXd<6>
Definition at line 159 of file Vector.hpp.
Vector9d
using Utils::Vector9d = typedef VectorXd<9>
Definition at line 160 of file Vector.hpp.
VectorXd
template<std::size_t N> using Utils::VectorXd = typedef Vector<double, N>
Definition at line 155 of file Vector.hpp.
VectorXf
template<std::size_t N> using Utils::VectorXf = typedef Vector<float, N>
Definition at line 163 of file Vector.hpp.
VectorXi
template<std::size_t N> using Utils::VectorXi = typedef Vector<int, N>
Definition at line 166 of file Vector.hpp.
Enumeration Type Documentation
MemoryOrder
enum Utils::MemoryOrder strong
Enumerator
COLUMN_MAJOR
ROW_MAJOR
Definition at line 32 of file index.hpp.
Function Documentation
abs() [1/2]
DEVICE_QUALIFIER double Utils::abs (double x) inline
Return the absolute value of x.
Definition at line 32 of file abs.hpp.
Referenced by Coulomb::calc_charge_excess_ratio(), Shapes::Rhomboid::calculate_dist(), Shapes::Ellipsoid::calculate_dist(), Shapes::Torus::calculate_dist(), Shapes::HollowConicalFrustum::calculate_dist(), Shapes::SpheroCylinder::calculate_dist(), Shapes::SimplePore::calculate_dist(), Shapes::Cylinder::calculate_dist(), calculate_positional_correction(), calculate_velocity_correction(), check_charge_neutrality(), ek_init(), ReactionMethods::factorial_Ni0_divided_by_factorial_Ni0_plus_nu_i(), ICCStar::iteration(), ljgen_pair_energy(), ljgen_pair_force_factor(), local_rotate_particle(), local_rotate_particle_body(), sinc(), transform_coordinate_cartesian_to_cylinder(), transform_coordinate_cylinder_to_cartesian(), and vec_rotate().
abs() [2/2]
DEVICE_QUALIFIER float Utils::abs (float x) inline
Return the absolute value of x.
Definition at line 37 of file abs.hpp.
angle_between()
double Utils::angle_between (Vector3d const & v1, Vector3d const & v2) inline
Determine the angle between two vectors.
Definition at line 52 of file vec_rotate.hpp.
References Utils::Vector< T, N >::norm2(), and sqrt().
Referenced by Observables::CylindricalLBProfileObservable::calculate_sampling_positions(), and transform_vector_cartesian_to_cylinder().
angle_btw_triangles()
double Utils::angle_btw_triangles (const Vector3d & P1, const Vector3d & P2, const Vector3d & P3, const Vector3d & P4) inline
Computes the angle between two triangles in 3D space.
Returns the angle between two triangles in 3D space given by points P1P2P3 and P2P3P4. Note, that the common edge is given as the second and the third argument. Here, the angle can have values from 0 to 2 * PI, depending on the orientation of the two triangles. So the angle can be convex or concave. For each triangle, an inward direction has been defined as the direction of one of the two normal vectors. Particularly, for triangle P1P2P3 it is the vector N1 = P2P1 x P2P3 and for triangle P2P3P4 it is N2 = P2P3 x P2P4. The method first computes the angle between N1 and N2, which gives always value between 0 and PI and then it checks whether this value must be corrected to a value between PI and 2 * PI.
As an example, consider 4 points A,B,C,D in space given by coordinates A = [1,1,1], B = [2,1,1], C = [1,2,1], D = [1,1,2]. We want to determine the angle between triangles ABC and ACD. In case the orientation of the triangle ABC is [0,0,1] and orientation of ACD is [1,0,0], the resulting angle must be PI/2.0. To get correct results, note that the common edge is AC, and one must call the method as angle_btw_triangles(B,A,C,D). With this call we have ensured that N1 = AB x AC (which coincides with [0,0,1]) and N2 = AC x AD (which coincides with [1,0,0]). Alternatively, if the orientations of the two triangles were the opposite, the correct call would be angle_btw_triangles(B,C,A,D) so that N1 = CB x CA and N2 = CA x CD.
Definition at line 80 of file triangle_functions.hpp.
References get_n_triangle(), pi(), and sqrt().
Referenced by OifLocalForcesBond::calc_forces().
apply()
template<class F , class Tuple > constexpr decltype(auto) Utils::apply (F && f, Tuple && t) constexpr
Call function with expanded tuple as parameters.
Like std::apply.
Template Parameters
F Callable with tuple elements as arguments
Tuple Has to conform to the tuple interface
Returns
Whatever f returns.
Definition at line 53 of file tuple.hpp.
Referenced by flatten().
area_triangle()
double Utils::area_triangle (const Vector3d & P1, const Vector3d & P2, const Vector3d & P3) inline
Computes the area of triangle between vectors P1,P2,P3, by computing the cross product P1P2 x P1P3 and taking the half of its norm.
Definition at line 49 of file triangle_functions.hpp.
References get_n_triangle(), and Utils::Vector< T, N >::norm().
Referenced by OifLocalForcesBond::calc_forces().
as_const()
template<class T > constexpr std::add_const<T>::type& Utils::as_const (T & t) constexpr noexcept
Definition at line 26 of file as_const.hpp.
Referenced by cells_re_init(), ScriptInterface::Accumulators::Correlator::Correlator(), ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::get_hybrid_decomposition(), ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::get_regular_decomposition(), ScriptInterface::Accumulators::MeanVarianceCalculator::MeanVarianceCalculator(), and ScriptInterface::Accumulators::TimeSeries::TimeSeries().
AS_erfc_part()
template<typename T > constexpr T Utils::AS_erfc_part (T d) constexpr
Approximate \(\exp(d^2) \mathrm{erfc}(d)\) by applying a formula from [1] chapter 7.
Definition at line 29 of file AS_erfc_part.hpp.
Referenced by CoulombP3M::pair_energy(), DipolarP3M::pair_energy(), DipolarP3M::pair_force(), and CoulombP3M::pair_force().
basis_change()
Vector3d Utils::basis_change (Vector3d const & b1, Vector3d const & b2, Vector3d const & b3, Vector3d const & v, bool reverse = false) inline
Basis change.
Definition at line 47 of file coordinate_transformation.hpp.
References Utils::Vector< T, N >::normalized(), and Utils::Matrix< T, Rows, Cols >::transposed().
Referenced by Shapes::HollowConicalFrustum::calculate_dist(), transform_coordinate_cartesian_to_cylinder(), and transform_coordinate_cylinder_to_cartesian().
bspline() [1/2]
template<int order, typename T > DEVICE_QUALIFIER auto Utils::bspline (int i, T x) -> std::enable_if_t<(order > 0) && (order <= 7), T>
Formula of the B-spline.
Definition at line 31 of file bspline.hpp.
References DEVICE_ASSERT, DEVICE_THROW, and sqr().
Referenced by Utils::Interpolation::bspline_3d(), Utils::Interpolation::bspline_3d_gradient(), and p3m_calculate_interpolation_weights().
bspline() [2/2]
template<class T > auto Utils::bspline (int i, T x, int k)
Calculate B-splines.
Parameters
i knot number, using 0-based indexing
x position in the range (-0.5, 0.5)
k order of the B-spline, using 1-based indexing, i.e. a B-spline of order k is a polynomial of degree k-1
Definition at line 186 of file bspline.hpp.
bspline_d()
template<int order, typename T = double> DEVICE_QUALIFIER auto Utils::bspline_d (int i, T x) -> std::enable_if_t<(order > 0) && (order <= 7), T>
Derivative of the B-spline.
Definition at line 209 of file bspline.hpp.
References DEVICE_ASSERT, and DEVICE_THROW.
calc_orthonormal_vector()
template<typename T , std::size_t N> Vector<T, N> Utils::calc_orthonormal_vector (Vector< T, N > const & vec)
Return a vector that is orthonormal to vec.
Definition at line 32 of file orthonormal_vec.hpp.
References Utils::Vector< T, N >::broadcast(), Utils::Vector< T, N >::norm(), Utils::Vector< T, N >::norm2(), and sqrt_2().
cbrt_2()
template<class T = double> constexpr DEVICE_QUALIFIER T Utils::cbrt_2 () constexpr
Cube root of 2.
Definition at line 71 of file constants.hpp.
Referenced by ljcos_set_params().
check_charge_neutrality()
template<typename ParticleRange > bool Utils::check_charge_neutrality (ParticleRange & prange)
Definition at line 31 of file charge_neutrality.hpp.
References abs(), and anonymous_namespace{Correlator.cpp}::min().
contains() [1/2]
template<class Range , class T > bool Utils::contains (const Range & rng, T const & value)
Check whether a range contains a value.
Parameters
rng The range to search in.
value The value to search for.
Returns
True iff range contains the value.
Definition at line 49 of file contains.hpp.
References contains().
contains() [2/2]
template<class InputIt , class T > bool Utils::contains (InputIt first, InputIt last, T const & value)
Check whether an iterator range contains a value.
Parameters
first Beginning of the range
last End of the range.
value The value to search for.
Returns
True iff range contains the value.
Definition at line 36 of file contains.hpp.
Referenced by add_exclusion(), calc_part_distribution(), calc_structurefactor(), contains(), ReactionMethods::ReactionAlgorithm::generate_new_particle_positions(), mindist(), and CellStructure::remove_particle().
convert_director_to_quaternion()
template<class T > Quaternion<T> Utils::convert_director_to_quaternion (Vector< T, 3 > const & d)
Convert director to quaternion.
Parameters
d Director
Returns
A (non-normalized) quaternion from the director, or {1, 0, 0, 0} if the director is the null vector.
Definition at line 54 of file math/quaternion.hpp.
References Utils::Vector< T, N >::norm(), and sqrt().
Referenced by calculate_vs_relate_to_params(), convert_dip_to_quat(), and set_particle_director().
convert_quaternion_to_director()
template<class T > Vector<T, 3> Utils::convert_quaternion_to_director (Quaternion< T > const & quat)
Convert quaternion to director.
Returns
A (non-normalized) director.
Definition at line 41 of file math/quaternion.hpp.
Referenced by ParticlePosition::calc_director(), and connection_vector().
del_gaussian()
Utils::Vector3d Utils::del_gaussian (Vector3d x, Vector3d x0, double sigma) inline
Definition at line 31 of file utils/include/utils/math/gaussian.hpp.
References gaussian().
demangle()
template<class T > std::string Utils::demangle ()
Get a human-readable name for a type.
Uses boost to demangle the name, for details see documentation for boost::core::demangle.
Template Parameters
T type
Returns
name
Definition at line 36 of file demangle.hpp.
diagonal_mat()
template<typename T , std::size_t Rows, std::size_t Cols> Matrix<T, Rows, Cols> Utils::diagonal_mat (Utils::Vector< T, Rows > const & v)
Definition at line 225 of file matrix.hpp.
filter()
template<template< class > class Predicate, class Tuple > constexpr auto Utils::filter (Tuple const & in) constexpr
Filter a tuple by a static predicate.
E.g. filter(std::is_integral, std::make_tuple(1, 1.5, 2u)) -> std::tuple<int, unsigned>(1, 2u).
Template Parameters
Predicate Metafunction that returns a bool for each type.
Tuple tuple-like type that implements the tuple interface.
Parameters
in The input tuple-like
Returns
std::tuple with the elements selected by the predicate.
Definition at line 179 of file tuple.hpp.
Referenced by get_pairs_filtered().
find_if()
template<class Pred , class Tuple , class F > constexpr auto Utils::find_if (Pred && pred, Tuple const & t, F && f) constexpr
Find first element in tuple for which a predicate holds, and call a Callable with the element.
Any return value of the Callable is ignored.
Template Parameters
Pred Must be callable with all types occurring as elements in Tuple, returning a value convertible to bool.
Tuple a tuple-like type supporting Utils::get
F Must be callable with all types occurring as elements in Tuple.
Parameters
pred The predicate.
t Tuple for search in.
f Is called for first found element.
Returns
true iff the predicate was true for at least one element.
Definition at line 126 of file tuple.hpp.
References f.
Referenced by Accumulators::auto_update_add(), Accumulators::auto_update_remove(), CellStructure::get_max_local_particle_id(), ghost_communicator(), LBBoundaries::lb_init_boundaries(), LBBoundaries::lbboundary_get_force(), Cells::particles(), and vol_cons_parameters().
flatten() [1/2]
template<typename T , std::size_t M, std::size_t N> Utils::Vector<T, M * N> Utils::flatten (Matrix< T, M, N > const & m)
Definition at line 220 of file matrix.hpp.
References Utils::Matrix< T, Rows, Cols >::begin(), and Utils::Matrix< T, Rows, Cols >::end().
flatten() [2/2]
template<class Range , class OutputIterator > void Utils::flatten (Range const & v, OutputIterator out)
Flatten a range of ranges.
Copy a range of ranges to an output range by subsequently copying the nested ranges to the output. Arbitrary deep nesting is supported, the elements are copied into the output in a depth-first fashion.
Template Parameters
Range A Forward Range
OutputIterator An OutputIterator
Parameters
v Input Range
out Output iterator
Definition at line 63 of file flatten.hpp.
References apply().
Referenced by add_non_bonded_pair_virials(), dpd_stress(), Observables::ParticleObservable< ObsType >::evaluate(), and Utils::Matrix< T, Rows, Cols >::Matrix().
for_each() [1/2]
template<class F , class Tuple > void Utils::for_each (F && f, Tuple && t)
Definition at line 77 of file tuple.hpp.
for_each() [2/2]
template<class F , class Tuple > void Utils::for_each (F && f, Tuple & t)
Definition at line 71 of file tuple.hpp.
References f.
Referenced by apply_positional_correction(), apply_velocity_correction(), init_correction_vector(), LBBoundaries::lb_init_boundaries(), LeesEdwards::run_kernel(), and save_old_position().
for_each_cartesian_pair() [1/2]
template<typename ForwardIterator , typename BinaryOp > void Utils::for_each_cartesian_pair (ForwardIterator first1, ForwardIterator last1, ForwardIterator first2, ForwardIterator last2, BinaryOp op)
Execute op for each pair of elements between [first1, last1) and [first2, last2).
Diagonal elements are not excluded. Pairs are traversed ordered, so that for op(*it, *jt), it holds that distance(it - first) < distance(jt - first), and distance(it_n - first) < distance(it_n+1 - first) for consecutive calls.
Definition at line 62 of file for_each_pair.hpp.
Referenced by for_each_cartesian_pair().
for_each_cartesian_pair() [2/2]
template<typename ForwardRange , typename BinaryOp > void Utils::for_each_cartesian_pair (ForwardRange && rng1, ForwardRange && rng2, BinaryOp && op)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 76 of file for_each_pair.hpp.
References for_each_cartesian_pair().
for_each_cartesian_pair_if() [1/2]
template<typename ForwardIterator , typename BinaryOp , typename BinaryCmp > void Utils::for_each_cartesian_pair_if (ForwardIterator first1, ForwardIterator last1, ForwardIterator first2, ForwardIterator last2, BinaryOp op, BinaryCmp cmp)
Execute op for each pair of elements between [first1, last1) and [first2, last2) if a condition is satisfied.
Diagonal elements are not excluded. Pairs are traversed ordered, so that for op(*it, *jt), it holds that distance(it - first) < distance(jt - first), and distance(it_n - first) < distance(it_n+1 - first) for consecutive calls.
Definition at line 93 of file for_each_pair.hpp.
Referenced by for_each_cartesian_pair_if().
for_each_cartesian_pair_if() [2/2]
template<typename ForwardRange , typename BinaryOp , typename BinaryCmp > void Utils::for_each_cartesian_pair_if (ForwardRange && rng1, ForwardRange && rng2, BinaryOp && op, BinaryCmp cmp)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 109 of file for_each_pair.hpp.
References for_each_cartesian_pair_if().
for_each_pair() [1/2]
template<typename ForwardIterator , typename BinaryOp > void Utils::for_each_pair (ForwardIterator first, ForwardIterator last, BinaryOp op)
Execute op for each pair of elements in [first, last) once.
Diagonal elements are excluded. Pairs are traversed ordered, so that for op(*it, *jt), it holds that distance(it - first) < distance(jt - first), and distance(it_n - first) < distance(it_n+1 - first) for consecutive calls.
Definition at line 35 of file for_each_pair.hpp.
Referenced by for_each_pair(), and ClusterAnalysis::ClusterStructure::run_for_all_pairs().
for_each_pair() [2/2]
template<typename ForwardRange , typename BinaryOp > void Utils::for_each_pair (ForwardRange && rng, BinaryOp && op)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 47 of file for_each_pair.hpp.
References for_each_pair().
gamma()
template<class T = double> constexpr DEVICE_QUALIFIER T Utils::gamma () constexpr
Euler-Mascheroni constant.
Definition at line 50 of file constants.hpp.
Referenced by bd_drag(), bd_drag_rot(), bd_drag_vel(), bd_drag_vel_rot(), ScriptInterface::ReactionMethods::ReactionAlgorithm::do_call_method(), dpd_set_params(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), integrate_set_steepest_descent(), lb_lbcoupling_set_gamma(), mpi_set_brownian_gamma(), mpi_set_brownian_gamma_local(), mpi_set_brownian_gamma_rot(), mpi_set_brownian_gamma_rot_local(), mpi_set_langevin_gamma(), mpi_set_langevin_gamma_local(), mpi_set_langevin_gamma_rot(), mpi_set_langevin_gamma_rot_local(), CoulombMMM1D::pair_energy(), preparePolygammaEven(), set_particle_gamma(), IsotropicNptThermostat::sigma(), and steepest_descent_init().
gaussian()
double Utils::gaussian (Vector3d x, Vector3d x0, double sigma) inline
Definition at line 27 of file utils/include/utils/math/gaussian.hpp.
Referenced by del_gaussian().
get() [1/4]
template<std::size_t I, class T , std::size_t N> auto Utils::get (Array< T, N > const & a) -> std::enable_if_t<(I < N), const T &>
Definition at line 214 of file Array.hpp.
get() [2/4]
template<std::size_t I> auto Utils::get (const LB_Fluid_Ref & lb_fluid)
Definition at line 165 of file lb.hpp.
References LB_Fluid_Ref::get().
Referenced by add_bonded_four_body_force(), add_bonded_three_body_force(), add_bonded_two_body_force(), force_calc(), and update_icc_particles().
get() [3/4]
template<std::size_t I, typename T > const std::tuple_element_t<I, T>& Utils::get (const T & v)
Definition at line 27 of file get.hpp.
get() [4/4]
template<std::size_t I, class T , std::size_t N> auto Utils::get (Vector< T, N > const & a) -> std::enable_if_t<(I < N), const T &>
Definition at line 480 of file Vector.hpp.
get_cylindrical_sampling_positions()
std::vector<Vector3d> Utils::get_cylindrical_sampling_positions (std::pair< double, double > const & r_limits, std::pair< double, double > const & phi_limits, std::pair< double, double > const & z_limits, std::size_t n_r_bins, std::size_t n_phi_bins, std::size_t n_z_bins, double sampling_density)
Generate sampling positions for a cylindrical histogram.
Parameters
r_limits Range for radial coordinate as std::pair.
phi_limits Range for azimuthal angle as std::pair.
z_limits Range for z coordinate as std::pair.
n_r_bins Number of bins in radial direction.
n_phi_bins Number of bins in azimuthal direction.
n_z_bins Number of bins in z direction.
sampling_density The number of samples per unit volume.
Return values
Cartesian sampling coordinates.
Definition at line 47 of file sampling.hpp.
References Utils::Array< T, N >::begin(), make_lin_space(), and sqr().
Referenced by Observables::CylindricalLBProfileObservable::calculate_sampling_positions().
get_linear_index() [1/2]
int Utils::get_linear_index (const Vector3i & ind, const Vector3i & adim, MemoryOrder memory_order = MemoryOrder::COLUMN_MAJOR) inline
Definition at line 60 of file index.hpp.
References get_linear_index().
get_linear_index() [2/2]
int Utils::get_linear_index (int a, int b, int c, const Vector3i & adim, MemoryOrder memory_order = MemoryOrder::COLUMN_MAJOR) inline
get the linear index from the position (a,b,c) in a 3D grid of dimensions adim.
Returns
The linear index
Parameters
a,b,c Position in 3D space
adim Dimensions of the underlying grid
memory_order Row- or column-major
Definition at line 43 of file index.hpp.
References D3Q19::c, COLUMN_MAJOR, and ROW_MAJOR.
Referenced by calculate_node_index(), fft_init(), anonymous_namespace{fft.cpp}::find_comm_groups(), get_linear_index(), halo_push_communication(), Lattice::Lattice(), lb_bounce_back(), lb_calc_fluid_momentum(), lb_check_halo_regions(), LBBoundaries::lb_init_boundaries(), Lattice::map_position_to_lattice(), and p3m_calculate_interpolation_weights().
get_n_triangle()
Vector3d Utils::get_n_triangle (const Vector3d & P1, const Vector3d & P2, const Vector3d & P3) inline
Computes the normal vector of a triangle.
The sign convention is such that P1P2, P1P3 and the normal form a right-handed system. The normal vector is not normalized, i.e. its length is arbitrary.
Definition at line 38 of file triangle_functions.hpp.
References u, and vector_product().
Referenced by angle_btw_triangles(), area_triangle(), and OifLocalForcesBond::calc_forces().
hadamard_division() [1/4]
template<typename T , typename U , class = std::enable_if_t<not(detail::is_vector<T>::value or detail::is_vector<U>::value)>> auto Utils::hadamard_division (T const & a, U const & b)
Definition at line 447 of file Vector.hpp.
hadamard_division() [2/4]
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<T>::value)>> auto Utils::hadamard_division (T const & a, Vector< U, N > const & b)
Definition at line 434 of file Vector.hpp.
References Utils::Array< T, N >::begin().
hadamard_division() [3/4]
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<U>::value)>> auto Utils::hadamard_division (Vector< T, N > const & a, U const & b)
Definition at line 423 of file Vector.hpp.
hadamard_division() [4/4]
template<class T , class U , std::size_t N> auto Utils::hadamard_division (Vector< T, N > const & a, Vector< U, N > const & b)
Definition at line 408 of file Vector.hpp.
References Utils::Array< T, N >::begin(), Utils::Array< T, N >::cbegin(), and Utils::Array< T, N >::cend().
Referenced by bd_drag(), bd_drag_vel(), convert_torques_propagate_omega(), TuningAlgorithm::get_mc_time(), lb_set_agrid_gpu(), p3m_k_space_error(), P3MParameters::recalc_a_ai_cao_cut(), and BrownianThermostat::sigma().
hadamard_product() [1/4]
template<typename T , typename U , class = std::enable_if_t<not(detail::is_vector<T>::value or detail::is_vector<U>::value)>> auto Utils::hadamard_product (T const & a, U const & b)
Definition at line 403 of file Vector.hpp.
hadamard_product() [2/4]
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<T>::value)>> auto Utils::hadamard_product (T const & a, Vector< U, N > const & b)
Definition at line 380 of file Vector.hpp.
hadamard_product() [3/4]
template<class T , class U , std::size_t N, class = std::enable_if_t<not(detail::is_vector<U>::value)>> auto Utils::hadamard_product (Vector< T, N > const & a, U const & b)
Definition at line 391 of file Vector.hpp.
hadamard_product() [4/4]
template<class T , class U , std::size_t N> auto Utils::hadamard_product (Vector< T, N > const & a, Vector< U, N > const & b)
Definition at line 365 of file Vector.hpp.
References Utils::Array< T, N >::begin(), Utils::Array< T, N >::cbegin(), and Utils::Array< T, N >::cend().
Referenced by FieldCoupling::Fields::Interpolated< T, codim >::fits_in_box(), friction_thermo_langevin_rotation(), image_shift(), LBBoundaries::lb_init_boundaries(), npt_add_virial_contribution(), positions_in_halo(), and rotational_kinetic_energy().
identity_mat()
template<typename T , std::size_t Rows, std::size_t Cols> Matrix<T, Rows, Cols> Utils::identity_mat ()
Definition at line 231 of file matrix.hpp.
int_pow()
template<unsigned n, typename T > constexpr DEVICE_QUALIFIER T Utils::int_pow (T x) constexpr
Calculate integer powers.
This functions calculates x^n, where n is a positive integer that is known at compile time. It uses exponentiation by squaring to construct an efficient function.
Definition at line 61 of file int_pow.hpp.
Referenced by G_opt(), G_opt_dipolar(), gb_pair_energy(), and gb_pair_force().
integral_parameter()
template<template< std::size_t > class F, std::size_t min, std::size_t max, class... Args> decltype(auto) Utils::integral_parameter (std::size_t i, Args &&... args)
Generate a call table for a integral non-type template parameter.
Definition at line 59 of file integral_parameter.hpp.
keys()
template<typename Map > auto Utils::keys (Map const & m) -> std::vector<typename Map::key_type>
Return the keys of a map type.
Returns a vector of copies of the keys of a map, unordered_map, ...
Definition at line 34 of file keys.hpp.
Referenced by ComFixed< ParticleRange >::get_fixed_types(), and get_particle_ids().
linear_interpolation()
template<typename T , typename Container > T Utils::linear_interpolation (Container const & table, T hi, T offset, T x)
Linear interpolation between two data points.
Parameters
[in] table Tabulated values, equally-spaced along the x-axis
[in] hi Distance on the x-axis between tabulated values
[in] offset Position on the x-axis of the first tabulated value
[in] x Position on the x-axis at which to interpolate the value
Returns
Interpolated value on the y-axis at x.
Definition at line 33 of file linear_interpolation.hpp.
Referenced by TabulatedPotential::energy(), and TabulatedPotential::force().
ln_2()
template<class T = double> constexpr DEVICE_QUALIFIER T Utils::ln_2 () constexpr
Natural logarithm of 2.
Definition at line 57 of file constants.hpp.
Referenced by K0(), K1(), LPK0(), LPK01(), LPK1(), and CoulombMMM1D::pair_energy().
make_const_span() [1/2]
template<class C > constexpr DEVICE_QUALIFIER auto Utils::make_const_span (C & c) constexpr
Definition at line 130 of file Span.hpp.
References D3Q19::c, and make_const_span().
make_const_span() [2/2]
template<typename T > constexpr DEVICE_QUALIFIER Span<std::add_const_t<T> > Utils::make_const_span (T * p, std::size_t N) constexpr
Definition at line 126 of file Span.hpp.
References N.
Referenced by fetch_particles(), p3m_interpolation_cache::load(), and make_const_span().
make_lin_space()
template<class T > auto Utils::make_lin_space (T start, T stop, std::size_t number, bool endpoint = true)
Equally spaced values in interval.
Returns a range of equally spaced values in the range of start and stop, like numpy.linspace.
Template Parameters
T floating point type
Parameters
start Start value of the interval
stop End value of the interval
number Number of partition points
endpoint If true, the last point is stop, otherwise one less.
Returns
Range of equally spaced values
Definition at line 45 of file make_lin_space.hpp.
Referenced by Observables::ProfileObservable::edges(), get_cylindrical_sampling_positions(), and raster().
make_span() [1/2]
template<class C > constexpr DEVICE_QUALIFIER auto Utils::make_span (C & c) constexpr
Definition at line 120 of file Span.hpp.
References D3Q19::c, and make_span().
make_span() [2/2]
template<typename T > constexpr DEVICE_QUALIFIER Span<T> Utils::make_span (T * p, std::size_t N) constexpr
Definition at line 116 of file Span.hpp.
References N.
Referenced by add_forces_from_recv_buffer(), add_rattle_correction_from_recv_buffer(), cell_cell_transfer(), fft_init(), p3m_send_mesh::gather_grid(), AtomDecomposition::ghost_cells(), RegularDecomposition::ghost_cells(), HybridDecomposition::ghost_cells(), DipolarP3M::kernel(), AtomDecomposition::local_cells(), RegularDecomposition::local_cells(), HybridDecomposition::local_cells(), CoulombP3M::long_range_kernel(), make_span(), prepare_send_buffer(), put_recv_buffer(), and p3m_send_mesh::spread_grid().
mask()
template<class T , class Integral > auto Utils::mask (Integral mask, T t) -> std::enable_if_t<std::is_unsigned<Integral>::value && (size_in_bits<Integral>::value >= tuple_size<T>::value), T>
Pick elements of a tuple-like by a bit mask.
E.g. every element of the input for which the corresponding bit is set in the mask is set is copied to the output unmodified, the elements that are not set are set to zero (default constructed instance of the type).
Example: mask(0b1011, {1, 2, 3, 4}) => {1, 0, 3, 4}
Template Parameters
T implements the tuple interface(get, tuple_size, ...)
Integral An unsigned integral type
Parameters
mask bit mask, if the i-th bit is set, the i-th element in t is copied to the output, otherwise it is set to zero.
t input elements
Returns
t partially zeroed out according to mask
Definition at line 57 of file mask.hpp.
Referenced by bd_drag_rot(), bd_drag_vel_rot(), bd_random_walk_rot(), bd_random_walk_vel_rot(), convert_torque_to_body_frame_apply_fix(), local_rotate_particle_body(), and propagate_omega_quat_particle().
matrix_vector_product()
template<typename T , std::size_t N, const std::array< std::array< int, N >, N > & matrix, typename Container > constexpr std::array<T, N> Utils::matrix_vector_product (const Container & vec) constexpr
Calculate the matrix-vector product for a statically given (square) matrix.
Template Parameters
T data type for the vector.
N size of the vector.
matrix const reference to a static integer array (size N) of arrays (each of size N).
Container container type for the vector.
Parameters
vec Container with data of type T and length N with the vector data.
Return values
An array with the result of the matrix-vector product.
Definition at line 104 of file matrix_vector_product.hpp.
operator!=()
template<std::size_t N, typename T > constexpr bool Utils::operator!= (Vector< T, N > const & a, Vector< T, N > const & b) constexpr
Definition at line 228 of file Vector.hpp.
operator%()
template<std::size_t N, typename T , class U , class = std::enable_if_t<std::is_integral<T>::value && std::is_integral<U>::value>> auto Utils::operator% (Vector< T, N > const & a, Vector< U, N > const & b)
Definition at line 331 of file Vector.hpp.
operator*() [1/4]
template<typename T , typename U , std::enable_if_t< std::is_arithmetic< U >::value, bool > = true> Quaternion<T> Utils::operator* (const U & b, const Quaternion< T > & a)
Product quaternion and arithmetic type.
Template Parameters
T Data type of quaternion a.
U Type of multiplier b.
Parameters
b Quaternion.
a Multiplier.
Returns
Multiplied quaternion.
Definition at line 141 of file quaternion.hpp.
operator*() [2/4]
template<std::size_t N, typename T , class U , std::enable_if_t< std::is_arithmetic< U >::value, bool > = true> auto Utils::operator* (U const & a, Vector< T, N > const & b)
Definition at line 265 of file Vector.hpp.
operator*() [3/4]
template<std::size_t N, typename T , class U , class = std::enable_if_t<not(detail::is_vector<T>::value or detail::is_vector<U>::value)>> auto Utils::operator* (Vector< T, N > const & a, Vector< U, N > const & b)
Definition at line 321 of file Vector.hpp.
operator*() [4/4]
template<std::size_t N, typename T , class U , std::enable_if_t< std::is_arithmetic< U >::value, bool > = true> auto Utils::operator* (Vector< T, N > const & b, U const & a)
Definition at line 277 of file Vector.hpp.
operator*=()
template<std::size_t N, typename T > Vector<T, N>& Utils::operator*= (Vector< T, N > & b, T const & a)
Definition at line 288 of file Vector.hpp.
operator+()
template<std::size_t N, typename T , typename U > auto Utils::operator+ (Vector< T, N > const & a, Vector< U, N > const & b)
Definition at line 233 of file Vector.hpp.
operator+=()
template<std::size_t N, typename T > Vector<T, N>& Utils::operator+= (Vector< T, N > & a, Vector< T, N > const & b)
Definition at line 238 of file Vector.hpp.
operator-() [1/2]
template<std::size_t N, typename T > Vector<T, N> Utils::operator- (Vector< T, N > const & a)
Definition at line 248 of file Vector.hpp.
operator-() [2/2]
template<std::size_t N, typename T , typename U > auto Utils::operator- (Vector< T, N > const & a, Vector< U, N > const & b)
Definition at line 243 of file Vector.hpp.
operator-=()
template<std::size_t N, typename T > Vector<T, N>& Utils::operator-= (Vector< T, N > & a, Vector< T, N > const & b)
Definition at line 258 of file Vector.hpp.
operator/()
template<std::size_t N, typename T > Vector<T, N> Utils::operator/ (Vector< T, N > const & a, T const & b)
Definition at line 296 of file Vector.hpp.
References Utils::Array< T, N >::begin().
operator/=()
template<std::size_t N, typename T > Vector<T, N>& Utils::operator/= (Vector< T, N > & a, T const & b)
Definition at line 305 of file Vector.hpp.
operator<()
template<std::size_t N, typename T > constexpr bool Utils::operator< (Vector< T, N > const & a, Vector< T, N > const & b) constexpr
Definition at line 203 of file Vector.hpp.
operator<=()
template<std::size_t N, typename T > constexpr bool Utils::operator<= (Vector< T, N > const & a, Vector< T, N > const & b) constexpr
Definition at line 213 of file Vector.hpp.
operator==()
template<std::size_t N, typename T > constexpr bool Utils::operator== (Vector< T, N > const & a, Vector< T, N > const & b) constexpr
Definition at line 223 of file Vector.hpp.
operator>()
template<std::size_t N, typename T > constexpr bool Utils::operator> (Vector< T, N > const & a, Vector< T, N > const & b) constexpr
Definition at line 208 of file Vector.hpp.
operator>=()
template<std::size_t N, typename T > constexpr bool Utils::operator>= (Vector< T, N > const & a, Vector< T, N > const & b) constexpr
Definition at line 218 of file Vector.hpp.
pack()
template<class T > std::string Utils::pack (T const & v)
Pack a serialize type into a string.
Template Parameters
T Serializable type
Parameters
v Value to serialize
Returns
String representation
Definition at line 38 of file pack.hpp.
Referenced by ScriptInterface::ContextManager::serialize().
permute_ifield()
void Utils::permute_ifield (int * field, int size, int permute) inline
permute an integer array field of size size about permute positions.
Definition at line 24 of file permute_ifield.hpp.
Referenced by fft_init().
pi()
template<class T = double> constexpr DEVICE_QUALIFIER T Utils::pi () constexpr
Ratio of diameter and circumference of a circle.
Definition at line 36 of file constants.hpp.
Referenced by DipolarLayerCorrection::add_force_corrections(), add_PQ_force(), angle_btw_triangles(), calc_dihedral_angle(), calc_n_from_rho_j_pi(), calc_sc_cache(), calc_structurefactor(), coldet_do_three_particle_bond(), dipolar_energy_correction(), dipolar_force_corrections(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct(), ScriptInterface::Observables::CylindricalLBProfileObservable< CoreCylLBObs >::do_construct(), dp3m_k_space_error(), dp3m_tune_aliasing_sums(), DipolarLayerCorrection::energy_correction(), far_error(), G_opt(), G_opt_dipolar(), ReactionMethods::ReactionAlgorithm::get_random_position_in_box(), IBMTribend::IBMTribend(), ICCStar::iteration(), DipolarP3M::kernel(), ljcos2_pair_energy(), ljcos2_pair_force_factor(), ljcos_set_params(), CoulombP3M::long_range_kernel(), Random::noise_gaussian(), p3m_analytic_cotangent_sum(), p3m_k_space_error_gpu_kernel_ad(), p3m_k_space_error_gpu_kernel_ad_i(), p3m_k_space_error_gpu_kernel_ik(), p3m_k_space_error_gpu_kernel_ik_i(), p3m_tune_aliasing_sums(), CoulombMMM1D::pair_energy(), CoulombMMM1D::pair_force(), random_unit_vector(), setup_PoQ(), setup_PQ(), TabulatedAngleBond::TabulatedAngleBond(), and TabulatedDihedralBond::TabulatedDihedralBond().
product()
template<class T , std::size_t N> T Utils::product (Vector< T, N > const & v)
Definition at line 360 of file Vector.hpp.
References Utils::Array< T, N >::cbegin(), and Utils::Array< T, N >::cend().
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), fft_init(), Lattice::Lattice(), lb_lbfluid_get_pressure_tensor(), lb_lbfluid_print_vtk_boundary(), lb_lbfluid_print_vtk_velocity(), p3m_gpu_add_farfield_force(), and BoxGeometry::volume().
raster()
template<class T , class F > auto Utils::raster (Vector< T, 3 > const & offset, Vector< T, 3 > const & grid_spacing, Vector3i size, F f)
Raster a function over a regular 3d grid.
This evaluates a function over a regular grid and returns the function values at the grid points.
Parameters
offset Position of the lowest grid point
grid_spacing Grid constant
size Grid size
f Function to evaluate
Returns
Function values at the grid points.
Definition at line 42 of file raster.hpp.
References f, make_lin_space(), and res.
rotation_matrix()
template<typename T > Matrix<T, 3, 3> Utils::rotation_matrix (Quaternion< T > const & q)
Convert quaternion to rotation matrix.
Template Parameters
T Data type of quaternion.
Parameters
q Quaternion.
Returns
Rotation matrix.
Definition at line 151 of file quaternion.hpp.
References Utils::Quaternion< T >::normalized().
Referenced by convert_body_to_space(), and convert_vector_space_to_body().
sgn()
template<typename T > constexpr int Utils::sgn (T val) constexpr
Calculate signum of val.
Definition at line 27 of file sgn.hpp.
Referenced by BoxGeometry::velocity_difference().
sinc()
template<typename T > DEVICE_QUALIFIER T Utils::sinc (T d)
Calculates the sinc-function as sin(PI*x)/(PI*x).
(same convention as in [27]). In order to avoid divisions by 0, arguments, whose modulus is smaller than epsi, will be evaluated by an 8th order Taylor expansion of the sinc function. Note that the difference between sinc(x) and this expansion is smaller than 0.235e-12, if x is smaller than 0.1. (The next term in the expansion is the 10th order contribution PI^10/39916800 * x^10 = 0.2346...*x^12). This expansion should also save time, since it reduces the number of function calls to sin().
Definition at line 45 of file sinc.hpp.
References abs().
Referenced by Aliasing_sums_ik(), dp3m_tune_aliasing_sums(), G_opt(), G_opt_dipolar(), G_opt_dipolar_self_energy(), p3m_k_space_error_gpu_kernel_ad(), p3m_k_space_error_gpu_kernel_ad_i(), p3m_k_space_error_gpu_kernel_ik(), p3m_k_space_error_gpu_kernel_ik_i(), and p3m_tune_aliasing_sums().
sqr()
template<typename T > constexpr DEVICE_QUALIFIER T Utils::sqr (T x) constexpr
Calculates the SQuaRe of x.
Definition at line 26 of file sqr.hpp.
Referenced by Aliasing_sums_ik(), bspline(), IBMTriel::calc_forces(), calc_part_distribution(), calc_rg(), calc_rh(), calc_structurefactor(), Shapes::Ellipsoid::calculate_dist(), Shapes::Slitpore::calculate_dist(), Shapes::Torus::calculate_dist(), calculate_influence_function_device(), CoulombP3M::count_charged_particles(), elc_data::dielectric_layers_self_energy(), elc_data::dielectric_layers_self_forces(), dp3m_k_space_error(), dp3m_real_space_error(), dp3m_tune_aliasing_sums(), dpd_pair_force(), ek_init(), ek_node_get_flux(), ek_print_vtk_flux(), energiesKernel(), QuarticBond::energy(), AngleCossquareBond::energy(), HarmonicBond::energy(), AngleHarmonicBond::energy(), AngleCosineBond::energy(), DipolarLayerCorrection::energy_correction(), Accumulators::fcs_acf(), FeneBond::FeneBond(), forcecap_cap(), AngleHarmonicBond::forces(), AngleCosineBond::forces(), TabulatedAngleBond::forces(), forcesKernel(), G_opt_dipolar(), gaussian_pair_energy(), gaussian_pair_force_factor(), gb_pair_energy(), gb_pair_force(), get_cylindrical_sampling_positions(), GetIBMInterpolatedVelocity(), grid_influence_function(), hzeta(), Collision_parameters::initialize(), DipolarDirectSumWithReplica::kernel(), DipolarP3M::kernel(), lb_calc_pressure_tensor(), lb_reinit_parameters(), lb_reinit_parameters_gpu(), lb_relax_modes(), lj_pair_energy(), ljcos2_pair_energy(), ljcos_pair_energy(), ljcos_pair_force_factor(), ljcos_set_params(), ljgen_pair_force_factor(), CoulombP3M::long_range_kernel(), modify_p3m_sums(), morse_pair_energy(), morse_pair_force_factor(), Observables::LBFluidPressureTensor::operator()(), VerletCriterion< CutoffGetter >::operator()(), p3m_analytic_cotangent_sum(), CoulombP3M::p3m_calc_kspace_pressure_tensor(), p3m_k_space_error(), p3m_k_space_error_gpu_kernel_ad(), p3m_k_space_error_gpu_kernel_ad_i(), p3m_k_space_error_gpu_kernel_ik(), p3m_k_space_error_gpu_kernel_ik_i(), p3m_real_space_error(), p3m_tune_aliasing_sums(), DipolarP3M::pair_energy(), DipolarP3M::pair_force(), SmSt_pair_force_factor(), steepest_descent_step(), CoulombMMM1D::tune(), vectorReductionKernel(), velocity_verlet_npt_finalize_p_inst(), velocity_verlet_npt_propagate_pos(), velocity_verlet_npt_propagate_vel(), velocity_verlet_npt_propagate_vel_final(), and wca_pair_energy().
sqrt()
template<std::size_t N, typename T > Vector<T, N> Utils::sqrt (Vector< T, N > const & a)
Definition at line 343 of file Vector.hpp.
References Utils::Array< T, N >::begin().
Referenced by angle_between(), angle_btw_triangles(), bd_random_walk(), bd_random_walk_rot(), bd_random_walk_vel(), bd_random_walk_vel_rot(), anonymous_namespace{fft.cpp}::calc_2d_grid(), OifLocalForcesBond::calc_forces(), calc_part_distribution(), calc_re(), calc_rg(), calc_rh(), calc_structurefactor(), Shapes::Slitpore::calculate_dist(), Shapes::Torus::calculate_dist(), Shapes::SpheroCylinder::calculate_dist(), Shapes::SimplePore::calculate_dist(), Shapes::Cylinder::calculate_dist(), convert_director_to_quaternion(), RigidBond::cutoff(), dipolar_energy_correction(), dipolar_force_corrections(), distto(), dp3m_k_space_error(), dp3m_real_space_error(), dpd_init(), dpd_viscous_stress_local(), ek_init_species(), ek_set_D(), energiesKernel(), AngleCosineBond::energy(), BondedCoulomb::force(), forcecap_cap(), AngleHarmonicBond::forces(), AngleCosineBond::forces(), ThermalizedBond::forces(), TabulatedAngleBond::forces(), forcesKernel(), gb_pair_energy(), gb_pair_force(), ReactionMethods::ReactionAlgorithm::generate_new_particle_positions(), ReactionMethods::ReactionAlgorithm::get_random_position_in_box(), K0(), K1(), DipolarDirectSumWithReplica::kernel(), lb_lbcoupling_calc_particle_lattice_ia(), lb_reinit_parameters(), lb_thermalize_modes(), ljcos_set_params(), ljgen_pair_energy(), ljgen_pair_force_factor(), LPK0(), LPK01(), LPK1(), mindist(), Random::noise_gaussian(), Utils::Vector< double, 3 >::norm(), p3m_k_space_error(), p3m_k_space_error_gpu(), p3m_real_space_error(), CoulombMMM1D::pair_energy(), CoulombMMM1D::pair_force(), propagate_omega_quat_particle(), propagate_vel_pos_sd(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), ScriptInterface::Interactions::RigidBond::RigidBond(), Utils::Statistics::RunningAverage< Scalar >::sig(), LangevinThermostat::sigma(), BrownianThermostat::sigma(), IsotropicNptThermostat::sigma(), steepest_descent_step(), thermalized_bond_init(), transform_coordinate_cartesian_to_cylinder(), and transform_vector_cartesian_to_cylinder().
sqrt_2()
template<class T = double> constexpr DEVICE_QUALIFIER T Utils::sqrt_2 () constexpr
Square root of 2.
Definition at line 64 of file constants.hpp.
Referenced by calc_orthonormal_vector(), and dp3m_rtbisection().
sqrt_pi_i()
template<class T = double> constexpr DEVICE_QUALIFIER T Utils::sqrt_pi_i () constexpr
One over square root of pi.
Definition at line 43 of file constants.hpp.
Referenced by DipolarP3M::kernel(), CoulombP3M::long_range_kernel(), DipolarP3M::pair_energy(), DipolarP3M::pair_force(), and CoulombP3M::pair_force().
tensor_product() [1/2]
template<typename T , std::size_t N> Vector<T, N> Utils::tensor_product (const T & x, const Vector< T, N > & y)
Definition at line 38 of file tensor_product.hpp.
tensor_product() [2/2]
template<typename T , std::size_t N, std::size_t M> Matrix<T, N, M> Utils::tensor_product (const Vector< T, N > & x, const Vector< T, M > & y)
Definition at line 30 of file tensor_product.hpp.
Referenced by add_non_bonded_pair_virials(), Utils::Interpolation::bspline_3d_gradient_accumulate(), calc_bonded_three_body_pressure_tensor(), calc_bonded_virial_pressure_tensor(), FieldCoupling::Fields::PlaneWave< T, codim >::jacobian(), and Coulomb::ShortRangePressureKernel::operator()().
transform_coordinate_cartesian_to_cylinder() [1/2]
Vector3d Utils::transform_coordinate_cartesian_to_cylinder (Vector3d const & pos) inline
Coordinate transformation from Cartesian to cylindrical coordinates.
The origins and z-axis of the coordinate systems co-incide. The \(\phi = 0 \) direction corresponds to the x-axis in the original coordinate system.
Parameters
pos Vector to transform
Definition at line 72 of file coordinate_transformation.hpp.
References pos, and sqrt().
Referenced by Shapes::HollowConicalFrustum::calculate_dist(), Observables::CylindricalDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::CylindricalLBVelocityProfile::operator()(), and transform_coordinate_cartesian_to_cylinder().
transform_coordinate_cartesian_to_cylinder() [2/2]
Vector3d Utils::transform_coordinate_cartesian_to_cylinder (Vector3d const & pos, Vector3d const & axis, Vector3d const & orientation) inline
Coordinate transformation from Cartesian to cylindrical coordinates with change of basis.
The origins of the coordinate systems co-incide.
If the parameter axis is not equal to [0, 0, 1], the value of the angle \(\phi \) in cylindrical coordinates is under-defined. To fully define it, it is necessary to provide an orientation vector in Cartesian coordinates that will be used as the reference point (i.e. such that \(\phi = 0 \)), by default it is the x-axis.
Parameters
pos Vector to transform
axis Longitudinal axis of the cylindrical coordinates
orientation Reference point (in untransformed coordinates) for which \(\phi = 0 \)
Definition at line 93 of file coordinate_transformation.hpp.
References abs(), basis_change(), pos, transform_coordinate_cartesian_to_cylinder(), and vector_product().
transform_coordinate_cylinder_to_cartesian() [1/2]
Vector3d Utils::transform_coordinate_cylinder_to_cartesian (Vector3d const & pos) inline
Coordinate transformation from cylindrical to Cartesian coordinates.
The origins and z-axis of the coordinate systems co-incide. The \(\phi = 0 \) direction corresponds to the x-axis in the transformed coordinate system.
Parameters
pos Vector to transform
Definition at line 111 of file coordinate_transformation.hpp.
References pos.
Referenced by Shapes::HollowConicalFrustum::calculate_dist(), Observables::CylindricalLBProfileObservable::calculate_sampling_positions(), and transform_coordinate_cylinder_to_cartesian().
transform_coordinate_cylinder_to_cartesian() [2/2]
Vector3d Utils::transform_coordinate_cylinder_to_cartesian (Vector3d const & pos, Vector3d const & axis, Vector3d const & orientation) inline
Coordinate transformation from cylindrical to Cartesian coordinates with change of basis.
The origins of the coordinate systems co-incide.
If the parameter axis is not equal to [0, 0, 1], the value of the angle \(\phi \) in cylindrical coordinates is under-defined. To fully define it, it is necessary to provide an orientation vector in Cartesian coordinates that will be used as the reference point (i.e. such that \(\phi = 0 \)).
Parameters
pos Vector to transform
axis Longitudinal axis of the cylindrical coordinates
orientation Reference point (in Cartesian coordinates) for which \(\phi = 0 \)
Definition at line 133 of file coordinate_transformation.hpp.
References abs(), basis_change(), pos, transform_coordinate_cylinder_to_cartesian(), and vector_product().
transform_vector_cartesian_to_cylinder()
Vector3d Utils::transform_vector_cartesian_to_cylinder (Vector3d const & vec, Vector3d const & axis, Vector3d const & pos) inline
Vector transformation from Cartesian to cylindrical coordinates.
Parameters
vec Vector to transform
axis Longitudinal axis of the cylindrical coordinates
pos Origin of the vector
Definition at line 149 of file coordinate_transformation.hpp.
References angle_between(), Utils::Vector< T, N >::normalize(), pos, sqrt(), vec_rotate(), and vector_product().
Referenced by Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), and Observables::CylindricalLBVelocityProfile::operator()().
u32_to_u64()
constexpr uint64_t Utils::u32_to_u64 (uint32_t high, uint32_t low) inline constexpr
Definition at line 26 of file u32_to_u64.hpp.
Referenced by Random::philox_4_uint64s().
u64_to_u32()
constexpr std::pair<uint32_t, uint32_t> Utils::u64_to_u32 (uint64_t in) inline constexpr
Definition at line 30 of file u32_to_u64.hpp.
uniform()
constexpr double Utils::uniform (uint64_t in) inline constexpr
Uniformly map unsigned integer to double.
This maps a unsigned integer to the double interval (0., 1.], where 0 is mapped to the smallest representable value larger than 0., and the maximal integer value is mapped to 1.
Parameters
in Unsigned integer value
Returns
Mapped floating point value.
Definition at line 36 of file uniform.hpp.
Referenced by lb_thermalize_modes().
unit_vector()
template<typename T > Vector<T, 3> Utils::unit_vector (int i)
Definition at line 451 of file Vector.hpp.
unpack()
template<class T > T Utils::unpack (std::string const & state)
Unpack a serialize type into a string.
Template Parameters
T Serializable type
Parameters
state String to construct the value from, as returned by Utils::pack.
Returns
Unpacked value
Definition at line 53 of file pack.hpp.
upper_triangular()
template<class T > T Utils::upper_triangular (T i, T j, T n)
Linear index into an upper triangular matrix.
This is row-major.
Template Parameters
T Integral
Parameters
i row index
j column index
n matrix size
Returns
linear index
Definition at line 76 of file index.hpp.
Referenced by get_ia_param(), and mpi_realloc_ia_params_local().
vec_rotate()
Vector3d Utils::vec_rotate (const Vector3d & axis, double angle, const Vector3d & vector) inline
Rotate a vector around an axis.
Parameters
axis The axis to rotate about
angle Angle to rotate
vector Vector to act on
Returns
Rotated vector
Definition at line 40 of file vec_rotate.hpp.
References abs().
Referenced by Observables::CylindricalLBProfileObservable::calculate_sampling_positions(), draw_polymer_positions(), mpi_rotate_system_local(), and transform_vector_cartesian_to_cylinder().
vector_product()
template<class T > Vector<T, 3> Utils::vector_product (Vector< T, 3 > const & a, Vector< T, 3 > const & b)
Definition at line 354 of file Vector.hpp.
Referenced by Shapes::HollowConicalFrustum::calculate_dist(), Observables::CylindricalLBProfileObservable::calculate_sampling_positions(), Observables::BondDihedrals::evaluate(), get_n_triangle(), transform_coordinate_cartesian_to_cylinder(), transform_coordinate_cylinder_to_cartesian(), and transform_vector_cartesian_to_cylinder().