ESPResSo: Utils::Interpolation Namespace Reference
Utils::Interpolation Namespace Reference
Functions
template<int order, typename Kernel >
void bspline_3d (const Vector3d &pos, const Kernel &kernel, const Vector3d &grid_spacing, const Vector3d &offset)
cardinal B-spline interpolation with internal iteration.
template<int order, typename T , typename Kernel >
T bspline_3d_accumulate (const Vector3d &pos, const Kernel &kernel, const Vector3d &grid_spacing, const Vector3d &offset, T const &init)
cardinal B-spline weighted sum.
template<std::size_t order, typename Kernel >
void bspline_3d_gradient (const Vector3d &pos, const Kernel &kernel, const Vector3d &grid_spacing, const Vector3d &offset)
cardinal B-spline gradient interpolation with internal iteration.
template<std::size_t order, typename T , typename Kernel >
T bspline_3d_gradient_accumulate (const Vector3d &pos, const Kernel &kernel, const Vector3d &grid_spacing, const Vector3d &offset, T const &init)
cardinal B-spline weighted sum.
Function Documentation
bspline_3d()
template<int order, typename Kernel > void Utils::Interpolation::bspline_3d (const Vector3d & pos, const Kernel & kernel, const Vector3d & grid_spacing, const Vector3d & offset)
cardinal B-spline interpolation with internal iteration.
Template Parameters
order The number of interpolation points in each direction.
Kernel Callable that can be called at every point with the index of the point and its weight as arguments.
Parameters
pos The point at which the interpolation should be run.
kernel Function to run for every point.
grid_spacing The distance between the grid points.
offset Shift of the grid relative to the origin.
Definition at line 45 of file bspline_3d.hpp.
References block(), Utils::bspline(), and pos.
bspline_3d_accumulate()
template<int order, typename T , typename Kernel > T Utils::Interpolation::bspline_3d_accumulate (const Vector3d & pos, const Kernel & kernel, const Vector3d & grid_spacing, const Vector3d & offset, T const & init)
cardinal B-spline weighted sum.
Definition at line 79 of file bspline_3d.hpp.
References Communication::init(), and pos.
bspline_3d_gradient()
template<std::size_t order, typename Kernel > void Utils::Interpolation::bspline_3d_gradient (const Vector3d & pos, const Kernel & kernel, const Vector3d & grid_spacing, const Vector3d & offset)
cardinal B-spline gradient interpolation with internal iteration.
Template Parameters
order The number of interpolation points in each direction.
Kernel Callable that can be called at every point with the index of the point and its weights as arguments.
Parameters
pos The point at which the interpolation should be run.
kernel Function to run for every point.
grid_spacing The distance between the grid points.
offset Shift of the grid relative to the origin.
Definition at line 46 of file bspline_3d_gradient.hpp.
References block(), Utils::bspline(), and pos.
bspline_3d_gradient_accumulate()
template<std::size_t order, typename T , typename Kernel > T Utils::Interpolation::bspline_3d_gradient_accumulate (const Vector3d & pos, const Kernel & kernel, const Vector3d & grid_spacing, const Vector3d & offset, T const & init)
cardinal B-spline weighted sum.
Definition at line 85 of file bspline_3d_gradient.hpp.
References Communication::init(), pos, and Utils::tensor_product().