ESPResSo: walberla::ek::accessor::Scalar Namespace Reference
walberla::ek::accessor::Scalar Namespace Reference
Functions
auto get (GhostLayerField< double, 1u > const *scalar_field, Cell const &cell)
void set (GhostLayerField< double, 1u > *scalar_field, double const &value, Cell const &cell)
void add (GhostLayerField< double, 1u > *scalar_field, double const &value, Cell const &cell)
void initialize (GhostLayerField< double, 1u > *scalar_field, double const &value)
void add_to_all (GhostLayerField< double, 1u > *scalar_field, double const &value)
auto get (GhostLayerField< double, 1u > const *scalar_field, CellInterval const &ci)
void set (GhostLayerField< double, 1u > *scalar_field, std::vector< double > const &values, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< double > scalar_field, double *out)
__global__ void kernel_set (gpu::FieldAccessor< double > scalar_field, double const *RESTRICT in)
__global__ void kernel_broadcast (gpu::FieldAccessor< double > scalar_field, double const in)
__global__ void kernel_add (gpu::FieldAccessor< double > scalar_field, double const *RESTRICT in)
__global__ void kernel_broadcast_add (gpu::FieldAccessor< double > scalar_field, double const in)
double get (gpu::GPUField< double > const *field, Cell const &cell)
Get value from a single cell.
void set (gpu::GPUField< double > *field, double value, Cell const &cell)
Set value on a single cell.
void add (gpu::GPUField< double > *field, double value, Cell const &cell)
Add value to a single cell.
void initialize (gpu::GPUField< double > *field, double value)
Initialize all cells with the same value.
void add_to_all (gpu::GPUField< double > *scalar_field, Vector3< double > const value)
std::vector< double > get (gpu::GPUField< double > const *ield, CellInterval const &ci)
Get values from a cell interval.
void set (gpu::GPUField< double > *field, std::vector< double > const &values, CellInterval const &ci)
Set values on a cell interval.
void add_to_all (gpu::GPUField< double > *field, double value)
Add value to all cells.
auto get (GhostLayerField< float, 1u > const *scalar_field, Cell const &cell)
void set (GhostLayerField< float, 1u > *scalar_field, float const &value, Cell const &cell)
void add (GhostLayerField< float, 1u > *scalar_field, float const &value, Cell const &cell)
void initialize (GhostLayerField< float, 1u > *scalar_field, float const &value)
void add_to_all (GhostLayerField< float, 1u > *scalar_field, float const &value)
auto get (GhostLayerField< float, 1u > const *scalar_field, CellInterval const &ci)
void set (GhostLayerField< float, 1u > *scalar_field, std::vector< float > const &values, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< float > scalar_field, float *out)
__global__ void kernel_set (gpu::FieldAccessor< float > scalar_field, float const *RESTRICT in)
__global__ void kernel_broadcast (gpu::FieldAccessor< float > scalar_field, float const in)
__global__ void kernel_add (gpu::FieldAccessor< float > scalar_field, float const *RESTRICT in)
__global__ void kernel_broadcast_add (gpu::FieldAccessor< float > scalar_field, float const in)
float get (gpu::GPUField< float > const *field, Cell const &cell)
Get value from a single cell.
void set (gpu::GPUField< float > *field, float value, Cell const &cell)
Set value on a single cell.
void add (gpu::GPUField< float > *field, float value, Cell const &cell)
Add value to a single cell.
void initialize (gpu::GPUField< float > *field, float value)
Initialize all cells with the same value.
void add_to_all (gpu::GPUField< float > *scalar_field, Vector3< float > const value)
std::vector< float > get (gpu::GPUField< float > const *ield, CellInterval const &ci)
Get values from a cell interval.
void set (gpu::GPUField< float > *field, std::vector< float > const &values, CellInterval const &ci)
Set values on a cell interval.
void add_to_all (gpu::GPUField< float > *field, float value)
Add value to all cells.
Function Documentation
add() [1/4]
void walberla::ek::accessor::Scalar::add (GhostLayerField< double, 1u > * scalar_field, double const & value, Cell const & cell) inline
Definition at line 61 of file EK_FieldAccessors_double_precision.h.
References stream.
add() [2/4]
void walberla::ek::accessor::Scalar::add (GhostLayerField< float, 1u > * scalar_field, float const & value, Cell const & cell) inline
Definition at line 61 of file EK_FieldAccessors_single_precision.h.
References stream.
add() [3/4]
void walberla::ek::accessor::Scalar::add (gpu::GPUField< double > * scalar_field, double const value, Cell const & cell)
Add value to a single cell.
Definition at line 166 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_add(), and stream.
add() [4/4]
void walberla::ek::accessor::Scalar::add (gpu::GPUField< float > * scalar_field, float const value, Cell const & cell)
Add value to a single cell.
Definition at line 166 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_add(), and stream.
add_to_all() [1/6]
void walberla::ek::accessor::Scalar::add_to_all (GhostLayerField< double, 1u > * scalar_field, double const & value) inline
Definition at line 72 of file EK_FieldAccessors_double_precision.h.
References stream.
add_to_all() [2/6]
void walberla::ek::accessor::Scalar::add_to_all (GhostLayerField< float, 1u > * scalar_field, float const & value) inline
Definition at line 72 of file EK_FieldAccessors_single_precision.h.
References stream.
add_to_all() [3/6]
void walberla::ek::accessor::Scalar::add_to_all (gpu::GPUField< double > * field, double value)
Add value to all cells.
add_to_all() [4/6]
void walberla::ek::accessor::Scalar::add_to_all (gpu::GPUField< double > * scalar_field, Vector3< double > const value)
Definition at line 187 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_broadcast_add(), and stream.
add_to_all() [5/6]
void walberla::ek::accessor::Scalar::add_to_all (gpu::GPUField< float > * field, float value)
Add value to all cells.
add_to_all() [6/6]
void walberla::ek::accessor::Scalar::add_to_all (gpu::GPUField< float > * scalar_field, Vector3< float > const value)
Definition at line 187 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_broadcast_add(), and stream.
get() [1/8]
auto walberla::ek::accessor::Scalar::get (GhostLayerField< double, 1u > const * scalar_field, Cell const & cell) inline
Definition at line 51 of file EK_FieldAccessors_double_precision.h.
References stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::DensityVTKWriter< OutputType >::evaluate(), walberla::PoissonSolverFFT< FloatType, Architecture >::PotentialVTKWriter< OutputType >::evaluate(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_node_potential(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density(), and walberla::PoissonSolverFFT< FloatType, Architecture >::get_slice_potential().
get() [2/8]
auto walberla::ek::accessor::Scalar::get (GhostLayerField< double, 1u > const * scalar_field, CellInterval const & ci) inline
Definition at line 78 of file EK_FieldAccessors_double_precision.h.
References stream.
get() [3/8]
auto walberla::ek::accessor::Scalar::get (GhostLayerField< float, 1u > const * scalar_field, Cell const & cell) inline
Definition at line 51 of file EK_FieldAccessors_single_precision.h.
References stream.
get() [4/8]
auto walberla::ek::accessor::Scalar::get (GhostLayerField< float, 1u > const * scalar_field, CellInterval const & ci) inline
Definition at line 78 of file EK_FieldAccessors_single_precision.h.
References stream.
get() [5/8]
double walberla::ek::accessor::Scalar::get (gpu::GPUField< double > const * scalar_field, Cell const & cell)
Get value from a single cell.
Definition at line 140 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_get(), and stream.
get() [6/8]
std::vector< double > walberla::ek::accessor::Scalar::get (gpu::GPUField< double > const * scalar_field, CellInterval const & ci)
Get values from a cell interval.
Definition at line 197 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_get(), and stream.
get() [7/8]
float walberla::ek::accessor::Scalar::get (gpu::GPUField< float > const * scalar_field, Cell const & cell)
Get value from a single cell.
Definition at line 140 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_get(), and stream.
get() [8/8]
std::vector< float > walberla::ek::accessor::Scalar::get (gpu::GPUField< float > const * scalar_field, CellInterval const & ci)
Get values from a cell interval.
Definition at line 197 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_get(), and stream.
initialize() [1/4]
void walberla::ek::accessor::Scalar::initialize (GhostLayerField< double, 1u > * scalar_field, double const & value) inline
Definition at line 66 of file EK_FieldAccessors_double_precision.h.
References stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::add_to_storage(), and walberla::PoissonSolverFFT< FloatType, Architecture >::reset_charge_field().
initialize() [2/4]
void walberla::ek::accessor::Scalar::initialize (GhostLayerField< float, 1u > * scalar_field, float const & value) inline
Definition at line 66 of file EK_FieldAccessors_single_precision.h.
References stream.
initialize() [3/4]
void walberla::ek::accessor::Scalar::initialize (gpu::GPUField< double > * scalar_field, double const value)
Initialize all cells with the same value.
Definition at line 177 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_broadcast(), and stream.
initialize() [4/4]
void walberla::ek::accessor::Scalar::initialize (gpu::GPUField< float > * scalar_field, float const value)
Initialize all cells with the same value.
Definition at line 177 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_broadcast(), and stream.
kernel_add() [1/2]
__global__ void walberla::ek::accessor::Scalar::kernel_add (gpu::FieldAccessor< double > scalar_field, double const *RESTRICT in)
Definition at line 119 of file EK_FieldAccessors_double_precision_CUDA.cu.
References getLinearIndex(), and stream.
Referenced by add(), and add().
kernel_add() [2/2]
__global__ void walberla::ek::accessor::Scalar::kernel_add (gpu::FieldAccessor< float > scalar_field, float const *RESTRICT in)
Definition at line 119 of file EK_FieldAccessors_single_precision_CUDA.cu.
References getLinearIndex(), and stream.
kernel_broadcast() [1/2]
__global__ void walberla::ek::accessor::Scalar::kernel_broadcast (gpu::FieldAccessor< double > scalar_field, double const in)
Definition at line 110 of file EK_FieldAccessors_double_precision_CUDA.cu.
References stream.
Referenced by initialize(), initialize(), set(), and set().
kernel_broadcast() [2/2]
__global__ void walberla::ek::accessor::Scalar::kernel_broadcast (gpu::FieldAccessor< float > scalar_field, float const in)
Definition at line 110 of file EK_FieldAccessors_single_precision_CUDA.cu.
References stream.
kernel_broadcast_add() [1/2]
__global__ void walberla::ek::accessor::Scalar::kernel_broadcast_add (gpu::FieldAccessor< double > scalar_field, double const in)
Definition at line 130 of file EK_FieldAccessors_double_precision_CUDA.cu.
References stream.
Referenced by add_to_all(), and add_to_all().
kernel_broadcast_add() [2/2]
__global__ void walberla::ek::accessor::Scalar::kernel_broadcast_add (gpu::FieldAccessor< float > scalar_field, float const in)
Definition at line 130 of file EK_FieldAccessors_single_precision_CUDA.cu.
References stream.
kernel_get() [1/2]
__global__ void walberla::ek::accessor::Scalar::kernel_get (gpu::FieldAccessor< double > scalar_field, double * out)
Definition at line 88 of file EK_FieldAccessors_double_precision_CUDA.cu.
References getLinearIndex(), and stream.
Referenced by get(), get(), get(), and get().
kernel_get() [2/2]
__global__ void walberla::ek::accessor::Scalar::kernel_get (gpu::FieldAccessor< float > scalar_field, float * out)
Definition at line 88 of file EK_FieldAccessors_single_precision_CUDA.cu.
References getLinearIndex(), and stream.
kernel_set() [1/2]
__global__ void walberla::ek::accessor::Scalar::kernel_set (gpu::FieldAccessor< double > scalar_field, double const *RESTRICT in)
Definition at line 99 of file EK_FieldAccessors_double_precision_CUDA.cu.
References getLinearIndex(), and stream.
Referenced by set(), and set().
kernel_set() [2/2]
__global__ void walberla::ek::accessor::Scalar::kernel_set (gpu::FieldAccessor< float > scalar_field, float const *RESTRICT in)
Definition at line 99 of file EK_FieldAccessors_single_precision_CUDA.cu.
References getLinearIndex(), and stream.
set() [1/8]
void walberla::ek::accessor::Scalar::set (GhostLayerField< double, 1u > * scalar_field, double const & value, Cell const & cell) inline
Definition at line 56 of file EK_FieldAccessors_double_precision.h.
References stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density().
set() [2/8]
void walberla::ek::accessor::Scalar::set (GhostLayerField< double, 1u > * scalar_field, std::vector< double > const & values, CellInterval const & ci) inline
Definition at line 92 of file EK_FieldAccessors_double_precision.h.
References stream.
set() [3/8]
void walberla::ek::accessor::Scalar::set (GhostLayerField< float, 1u > * scalar_field, float const & value, Cell const & cell) inline
Definition at line 56 of file EK_FieldAccessors_single_precision.h.
References stream.
set() [4/8]
void walberla::ek::accessor::Scalar::set (GhostLayerField< float, 1u > * scalar_field, std::vector< float > const & values, CellInterval const & ci) inline
Definition at line 92 of file EK_FieldAccessors_single_precision.h.
References stream.
set() [5/8]
void walberla::ek::accessor::Scalar::set (gpu::GPUField< double > * scalar_field, double const value, Cell const & cell)
Set value on a single cell.
Definition at line 155 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_broadcast(), and stream.
set() [6/8]
void walberla::ek::accessor::Scalar::set (gpu::GPUField< double > * scalar_field, std::vector< double > const & values, CellInterval const & ci)
Set values on a cell interval.
Definition at line 211 of file EK_FieldAccessors_double_precision_CUDA.cu.
References kernel_set(), and stream.
set() [7/8]
void walberla::ek::accessor::Scalar::set (gpu::GPUField< float > * scalar_field, float const value, Cell const & cell)
Set value on a single cell.
Definition at line 155 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_broadcast(), and stream.
set() [8/8]
void walberla::ek::accessor::Scalar::set (gpu::GPUField< float > * scalar_field, std::vector< float > const & values, CellInterval const & ci)
Set values on a cell interval.
Definition at line 211 of file EK_FieldAccessors_single_precision_CUDA.cu.
References kernel_set(), and stream.