ESPResSo: ScriptInterface::System Namespace Reference
ScriptInterface::System Namespace Reference
Classes
class CudaInitHandle
class Leaf
Script interface wrapper for a component of the system class.
class System
Script interface wrapper for the system class.
Functions
void initialize (Utils::Factory< ObjectHandle > *om)
static void set_exclusions (Particles::ParticleHandle &p, Variant const &exclusions)
static void set_bonds (Particles::ParticleHandle &p, Variant const &bonds)
static void rotate_system (CellStructure &cell_structure, double phi, double theta, double alpha)
static void rescale_particles (CellStructure &cell_structure, int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
Variables
static bool system_created = false
Function Documentation
initialize()
void ScriptInterface::System::initialize (Utils::Factory< ObjectHandle > * om)
Definition at line 28 of file system/initialize.cpp.
References stream.
Referenced by ScriptInterface::initialize().
rescale_particles()
static void ScriptInterface::System::rescale_particles (CellStructure & cell_structure, int dir, double scale) static
Rescale all particle positions in direction dir by a factor scale.
Parameters
cell_structure cell structure
dir direction to scale (0/1/2 = x/y/z, 3 = x+y+z isotropically)
scale factor by which to rescale (>1: stretch, <1: contract)
Definition at line 435 of file script_interface/system/System.cpp.
References CellStructure::local_particles(), and rescale_particles().
Referenced by ScriptInterface::System::System::do_call_method(), and rescale_particles().
rotate_system()
static void ScriptInterface::System::rotate_system (CellStructure & cell_structure, double phi, double theta, double alpha) static
Definition at line 390 of file script_interface/system/System.cpp.
References comm_cart, Cells::DATA_PART_POSITION, Cells::DATA_PART_PROPERTIES, CellStructure::local_particles(), local_rotate_particle(), Cells::RESORT_GLOBAL, rotate_system(), CellStructure::set_resort_particles(), stream, CellStructure::update_ghosts_and_resort_particle(), and Utils::vec_rotate().
Referenced by ScriptInterface::System::System::do_call_method(), and rotate_system().
set_bonds()
static void ScriptInterface::System::set_bonds (Particles::ParticleHandle & p, Variant const & bonds) static
Definition at line 94 of file script_interface/system/System.cpp.
References ScriptInterface::ObjectHandle::call_method(), and stream.
Referenced by ScriptInterface::System::System::set_internal_state().
set_exclusions()
static void ScriptInterface::System::set_exclusions (Particles::ParticleHandle & p, Variant const & exclusions) static
Definition at line 88 of file script_interface/system/System.cpp.
References ScriptInterface::ObjectHandle::call_method().
Referenced by ScriptInterface::System::System::set_internal_state().
Variable Documentation
system_created
bool ScriptInterface::System::system_created = false static
Definition at line 85 of file script_interface/system/System.cpp.
Referenced by ScriptInterface::System::System::do_call_method(), and ScriptInterface::System::System::do_construct().