ESPResSo: ScriptInterface::ReactionMethods Namespace Reference
ScriptInterface::ReactionMethods Namespace Reference
Classes
class ConstantpHEnsemble
class ReactionAlgorithm
class ReactionEnsemble
class SingleReaction
class WidomInsertion
Functions
void initialize (Utils::Factory< ObjectHandle > *om)
static auto get_real_particle (boost::mpi::communicator const &comm, int p_id)
Function Documentation
get_real_particle()
static auto ScriptInterface::ReactionMethods::get_real_particle (boost::mpi::communicator const & comm, int p_id) static
Definition at line 105 of file script_interface/reaction_methods/ReactionAlgorithm.cpp.
References System::get_system().
initialize()
void ScriptInterface::ReactionMethods::initialize (Utils::Factory< ObjectHandle > * om)
Definition at line 32 of file reaction_methods/initialize.cpp.
References Utils::Factory< T >::register_new().
Referenced by ScriptInterface::initialize().