ESPResSo: anonymous_namespace{RegularDecomposition.cpp} Namespace Reference
anonymous_namespace{RegularDecomposition.cpp} Namespace Reference
Functions
void fold_and_reset (Particle &p, BoxGeometry const &box_geo)
Fold coordinates to box and reset the old position.
void revert_comm_order (GhostCommunicator &comm)
Revert the order of a communicator: After calling this the communicator is working in reverted order with exchanged communication types GHOST_SEND <-> GHOST_RECV.
void assign_prefetches (GhostCommunicator &comm)
Of every two communication rounds, set the first receivers to prefetch and poststore.
Function Documentation
assign_prefetches()
void anonymous_namespace{RegularDecomposition.cpp}::assign_prefetches (GhostCommunicator & comm)
Of every two communication rounds, set the first receivers to prefetch and poststore.
Definition at line 521 of file RegularDecomposition.cpp.
References GhostCommunicator::communications, GHOST_PREFETCH, GHOST_PSTSTORE, GHOST_RECV, and GHOST_SEND.
Referenced by RegularDecomposition::RegularDecomposition().
fold_and_reset()
void anonymous_namespace{RegularDecomposition.cpp}::fold_and_reset (Particle & p, BoxGeometry const & box_geo)
Fold coordinates to box and reset the old position.
Definition at line 169 of file RegularDecomposition.cpp.
References box_geo, fold_position(), Particle::image_box(), Particle::pos(), and Particle::pos_at_last_verlet_update().
Referenced by RegularDecomposition::resort().
revert_comm_order()
void anonymous_namespace{RegularDecomposition.cpp}::revert_comm_order (GhostCommunicator & comm)
Revert the order of a communicator: After calling this the communicator is working in reverted order with exchanged communication types GHOST_SEND <-> GHOST_RECV.
Definition at line 502 of file RegularDecomposition.cpp.
References D3Q19::c, GhostCommunicator::communications, GHOST_LOCL, GHOST_RECV, and GHOST_SEND.
Referenced by RegularDecomposition::RegularDecomposition().