ESPResSo: walberla::lbm::accessor::Velocity Namespace Reference
walberla::lbm::accessor::Velocity Namespace Reference
Functions
auto get (GhostLayerField< double, uint_t{19u}> const *pdf_field, GhostLayerField< double, uint_t{3u}> const *force_field, Cell const &cell)
auto get (GhostLayerField< double, uint_t{19u}> const *pdf_field, GhostLayerField< double, uint_t{3u}> const *force_field, CellInterval const &ci)
void set (GhostLayerField< double, uint_t{19u}> *pdf_field, GhostLayerField< double, uint_t{3u}> *velocity_field, GhostLayerField< double, uint_t{3u}> const *force_field, Vector3< double > const &u, Cell const &cell)
void set (GhostLayerField< double, uint_t{19u}> *pdf_field, GhostLayerField< double, uint_t{3u}> *velocity_field, GhostLayerField< double, uint_t{3u}> const *force_field, std::vector< double > const &values, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > force, double *RESTRICT u_out)
__global__ void kernel_set (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > velocity, gpu::FieldAccessor< double > force, double const *RESTRICT u_in)
Vector3< double > get (gpu::GPUField< double > const *pdf_field, gpu::GPUField< double > const *force_field, Cell const &cell)
std::vector< double > get (gpu::GPUField< double > const *pdf_field, gpu::GPUField< double > const *force_field, CellInterval const &ci)
void set (gpu::GPUField< double > *pdf_field, gpu::GPUField< double > *velocity_field, gpu::GPUField< double > const *force_field, Vector3< double > const &u, Cell const &cell)
void set (gpu::GPUField< double > *pdf_field, gpu::GPUField< double > *velocity_field, gpu::GPUField< double > const *force_field, std::vector< double > const &values, CellInterval const &ci)
auto get (GhostLayerField< float, uint_t{19u}> const *pdf_field, GhostLayerField< float, uint_t{3u}> const *force_field, Cell const &cell)
auto get (GhostLayerField< float, uint_t{19u}> const *pdf_field, GhostLayerField< float, uint_t{3u}> const *force_field, CellInterval const &ci)
void set (GhostLayerField< float, uint_t{19u}> *pdf_field, GhostLayerField< float, uint_t{3u}> *velocity_field, GhostLayerField< float, uint_t{3u}> const *force_field, Vector3< float > const &u, Cell const &cell)
void set (GhostLayerField< float, uint_t{19u}> *pdf_field, GhostLayerField< float, uint_t{3u}> *velocity_field, GhostLayerField< float, uint_t{3u}> const *force_field, std::vector< float > const &values, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > force, float *RESTRICT u_out)
__global__ void kernel_set (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > velocity, gpu::FieldAccessor< float > force, float const *RESTRICT u_in)
Vector3< float > get (gpu::GPUField< float > const *pdf_field, gpu::GPUField< float > const *force_field, Cell const &cell)
std::vector< float > get (gpu::GPUField< float > const *pdf_field, gpu::GPUField< float > const *force_field, CellInterval const &ci)
void set (gpu::GPUField< float > *pdf_field, gpu::GPUField< float > *velocity_field, gpu::GPUField< float > const *force_field, Vector3< float > const &u, Cell const &cell)
void set (gpu::GPUField< float > *pdf_field, gpu::GPUField< float > *velocity_field, gpu::GPUField< float > const *force_field, std::vector< float > const &values, CellInterval const &ci)
Function Documentation
get() [1/8]
auto walberla::lbm::accessor::Velocity::get (GhostLayerField< double, uint_t{19u}> const * pdf_field, GhostLayerField< double, uint_t{3u}> const * force_field, Cell const & cell) inline
Definition at line 782 of file FieldAccessorsDoublePrecision.h.
get() [2/8]
auto walberla::lbm::accessor::Velocity::get (GhostLayerField< double, uint_t{19u}> const * pdf_field, GhostLayerField< double, uint_t{3u}> const * force_field, CellInterval const & ci) inline
Definition at line 829 of file FieldAccessorsDoublePrecision.h.
get() [3/8]
auto walberla::lbm::accessor::Velocity::get (GhostLayerField< float, uint_t{19u}> const * pdf_field, GhostLayerField< float, uint_t{3u}> const * force_field, Cell const & cell) inline
Definition at line 782 of file FieldAccessorsSinglePrecision.h.
get() [4/8]
auto walberla::lbm::accessor::Velocity::get (GhostLayerField< float, uint_t{19u}> const * pdf_field, GhostLayerField< float, uint_t{3u}> const * force_field, CellInterval const & ci) inline
Definition at line 829 of file FieldAccessorsSinglePrecision.h.
get() [5/8]
Vector3< double > walberla::lbm::accessor::Velocity::get (gpu::GPUField< double > const * pdf_field, gpu::GPUField< double > const * force_field, Cell const & cell)
Definition at line 1041 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_get(), and stream.
get() [6/8]
std::vector< double > walberla::lbm::accessor::Velocity::get (gpu::GPUField< double > const * pdf_field, gpu::GPUField< double > const * force_field, CellInterval const & ci)
Definition at line 1058 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_get(), and stream.
get() [7/8]
Vector3< float > walberla::lbm::accessor::Velocity::get (gpu::GPUField< float > const * pdf_field, gpu::GPUField< float > const * force_field, Cell const & cell)
Definition at line 1041 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_get(), and stream.
get() [8/8]
std::vector< float > walberla::lbm::accessor::Velocity::get (gpu::GPUField< float > const * pdf_field, gpu::GPUField< float > const * force_field, CellInterval const & ci)
Definition at line 1058 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_get(), and stream.
kernel_get() [1/2]
__global__ void walberla::lbm::accessor::Velocity::kernel_get (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > force, double *RESTRICT u_out)
Definition at line 945 of file FieldAccessorsDoublePrecisionCUDA.cu.
References getLinearIndex(), and stream.
Referenced by get(), get(), get(), and get().
kernel_get() [2/2]
__global__ void walberla::lbm::accessor::Velocity::kernel_get (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > force, float *RESTRICT u_out)
Definition at line 945 of file FieldAccessorsSinglePrecisionCUDA.cu.
References getLinearIndex(), and stream.
kernel_set() [1/2]
__global__ void walberla::lbm::accessor::Velocity::kernel_set (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > velocity, gpu::FieldAccessor< double > force, double const *RESTRICT u_in)
Definition at line 991 of file FieldAccessorsDoublePrecisionCUDA.cu.
References getLinearIndex(), walberla::lbm::accessor::Equilibrium::kernel_set_device(), RESTRICT, stream, and velocity().
Referenced by set(), set(), set(), and set().
kernel_set() [2/2]
__global__ void walberla::lbm::accessor::Velocity::kernel_set (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > velocity, gpu::FieldAccessor< float > force, float const *RESTRICT u_in)
Definition at line 991 of file FieldAccessorsSinglePrecisionCUDA.cu.
References getLinearIndex(), walberla::lbm::accessor::Equilibrium::kernel_set_device(), RESTRICT, stream, and velocity().
set() [1/8]
void walberla::lbm::accessor::Velocity::set (GhostLayerField< double, uint_t{19u}> * pdf_field, GhostLayerField< double, uint_t{3u}> * velocity_field, GhostLayerField< double, uint_t{3u}> const * force_field, std::vector< double > const & values, CellInterval const & ci) inline
Definition at line 931 of file FieldAccessorsDoublePrecision.h.
set() [2/8]
void walberla::lbm::accessor::Velocity::set (GhostLayerField< double, uint_t{19u}> * pdf_field, GhostLayerField< double, uint_t{3u}> * velocity_field, GhostLayerField< double, uint_t{3u}> const * force_field, Vector3< double > const & u, Cell const & cell) inline
Definition at line 884 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity().
set() [3/8]
void walberla::lbm::accessor::Velocity::set (GhostLayerField< float, uint_t{19u}> * pdf_field, GhostLayerField< float, uint_t{3u}> * velocity_field, GhostLayerField< float, uint_t{3u}> const * force_field, std::vector< float > const & values, CellInterval const & ci) inline
Definition at line 931 of file FieldAccessorsSinglePrecision.h.
set() [4/8]
void walberla::lbm::accessor::Velocity::set (GhostLayerField< float, uint_t{19u}> * pdf_field, GhostLayerField< float, uint_t{3u}> * velocity_field, GhostLayerField< float, uint_t{3u}> const * force_field, Vector3< float > const & u, Cell const & cell) inline
Definition at line 884 of file FieldAccessorsSinglePrecision.h.
set() [5/8]
void walberla::lbm::accessor::Velocity::set (gpu::GPUField< double > * pdf_field, gpu::GPUField< double > * velocity_field, gpu::GPUField< double > const * force_field, std::vector< double > const & values, CellInterval const & ci)
Definition at line 1091 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_set(), and stream.
set() [6/8]
void walberla::lbm::accessor::Velocity::set (gpu::GPUField< double > * pdf_field, gpu::GPUField< double > * velocity_field, gpu::GPUField< double > const * force_field, Vector3< double > const & u, Cell const & cell)
Definition at line 1074 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_set(), and stream.
set() [7/8]
void walberla::lbm::accessor::Velocity::set (gpu::GPUField< float > * pdf_field, gpu::GPUField< float > * velocity_field, gpu::GPUField< float > const * force_field, std::vector< float > const & values, CellInterval const & ci)
Definition at line 1091 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_set(), and stream.
set() [8/8]
void walberla::lbm::accessor::Velocity::set (gpu::GPUField< float > * pdf_field, gpu::GPUField< float > * velocity_field, gpu::GPUField< float > const * force_field, Vector3< float > const & u, Cell const & cell)
Definition at line 1074 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_set(), and stream.