ESPResSo: System Namespace Reference
System Namespace Reference
Classes
class Leaf
Abstract class that represents a component of the system.
class System
Main system class.
Functions
bool is_system_set ()
void reset_system ()
void set_system (std::shared_ptr< System > new_instance)
System & get_system ()
Variables
static std::shared_ptr< System > instance = System::create()
Function Documentation
get_system()
System & System::get_system ()
Definition at line 98 of file core/system/System.cpp.
References instance.
Referenced by ScriptInterface::Integrators::SteepestDescent::activate(), ScriptInterface::Integrators::StokesianDynamics::activate(), ScriptInterface::Integrators::VelocityVerletIsoNPT::activate(), Constraints::Constraints< ParticleRange, Constraint >::add(), ScriptInterface::Particles::auto_exclusions(), ReactionMethods::ReactionAlgorithm::calculate_potential_energy(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_core_to_si(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::copy_si_to_core(), NptIsoParameters::coulomb_dipole_sanity_checks(), PairCriteria::DistanceCriterion::decide(), ScriptInterface::MPIIO::MPIIOScript::do_call_method(), ScriptInterface::walberla::EKContainer::do_call_method(), ScriptInterface::Interactions::NonBondedInteractions::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), ScriptInterface::Particles::Polymer::do_call_method(), ScriptInterface::System::System::do_call_method(), ScriptInterface::Coulomb::Actor< SIClass, CoreClass >::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Dipoles::Actor< SIClass, CoreClass >::do_call_method(), ScriptInterface::Particles::ParticleHandle::do_call_method(), ScriptInterface::walberla::LBFluid::do_call_method(), ScriptInterface::walberla::LatticeWalberla::do_construct(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_construct(), ScriptInterface::Particles::ParticleHandle::do_construct(), ScriptInterface::walberla::LBFluid::do_construct(), dpd_init(), dpd_stress(), dpd_viscous_stress_local(), Observables::CylindricalDensityProfile::evaluate(), Observables::CylindricalFluxDensityProfile::evaluate(), Observables::CylindricalLBFluxDensityProfileAtParticlePositions::evaluate(), Observables::CylindricalVelocityProfile::evaluate(), Observables::DensityProfile::evaluate(), Observables::FluxDensityProfile::evaluate(), Observables::ForceDensityProfile::evaluate(), Observables::ParticleDipoleFields::evaluate(), Observables::CylindricalLBVelocityProfileAtParticlePositions::evaluate(), fetch_particles(), ThermalizedBond::forces(), ClusterAnalysis::Cluster::fractal_dimension(), get_cell_structure(), Coulomb::get_coulomb(), Dipoles::get_dipoles(), get_ibm_particle_position(), LB::Solver::get_interpolated_density(), LB::Solver::get_interpolated_velocity(), ReactionMethods::ReactionAlgorithm::get_random_position_in_box(), ScriptInterface::Particles::get_real_particle(), ScriptInterface::ReactionMethods::get_real_particle(), handle_collisions(), IBMTribend::IBMTribend(), IBMTriel::IBMTriel(), init_type_map(), Collision_parameters::initialize(), ScriptInterface::Integrators::SteepestDescent::integrate(), integrator_npt_sanity_checks(), Thermostat::Thermostat::lb_coupling_deactivate(), ScriptInterface::Particles::local_add_exclusion(), ScriptInterface::Particles::local_remove_exclusion(), ClusterAnalysis::Cluster::longest_distance(), make_new_particle(), ReactionMethods::ReactionAlgorithm::make_reaction_attempt(), maybe_insert_particle(), maybe_move_particle(), Mpiio::mpi_mpiio_common_read(), npt_add_virial_contribution(), npt_reset_instantaneous_virials(), Observables::CylindricalLBVelocityProfile::operator()(), Observables::Energy::operator()(), Observables::LBFluidPressureTensor::operator()(), Observables::LBVelocityProfile::operator()(), Observables::Pressure::operator()(), Observables::PressureTensor::operator()(), pack_particles(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), ParticleObservables::traits< Particle >::position(), EK::EKWalberla::propagate(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), register_integrator(), Constraints::Constraints< ParticleRange, Constraint >::remove(), remove_all_particles(), remove_particle(), EK::Solver::reset(), LB::Solver::reset(), ReactionMethods::ReactionAlgorithm::restore_old_system_state(), ClusterAnalysis::ClusterStructure::run_for_all_pairs(), ClusterAnalysis::ClusterStructure::run_for_bonded_particles(), ReactionMethods::ReactionAlgorithm::set_cyl_constraint(), set_particle_pos(), LeesEdwards::LeesEdwards::set_protocol(), ReactionMethods::ReactionAlgorithm::set_slab_constraint(), steepest_descent_step(), LeesEdwards::LeesEdwards::unset_protocol(), and ReactionMethods::ReactionAlgorithm::update_volume().
is_system_set()
bool System::is_system_set ()
Definition at line 90 of file core/system/System.cpp.
References instance.
reset_system()
void System::reset_system ()
Definition at line 92 of file core/system/System.cpp.
References instance.
Referenced by ScriptInterface::System::System::do_call_method().
set_system()
void System::set_system (std::shared_ptr< System > new_instance)
Definition at line 94 of file core/system/System.cpp.
References instance.
Referenced by ScriptInterface::System::System::do_construct().
Variable Documentation
instance
std::shared_ptr<System> System::instance = System::create() static
Definition at line 51 of file core/system/System.cpp.
Referenced by ScriptInterface::walberla::VTKHandleBase< Field >::attach_to_lattice(), get_system(), is_system_set(), walberla::mpi_init(), EK::FieldsConnector::operator()(), reset_system(), and set_system().