ESPResSo: Dipoles Namespace Reference
Dipoles Namespace Reference
Namespaces
traits
Classes
struct ShortRangeEnergyKernel
struct ShortRangeForceKernel
Functions
void sanity_checks ()
void on_dipoles_change ()
called every time the dipolar parameters are changed.
void on_boxl_change ()
void on_node_grid_change ()
Called when the node_grid changed.
void on_periodicity_change ()
Called when the periodicity changes.
void on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
void calc_pressure_long_range ()
double cutoff ()
void on_observable_calc ()
called before calculating observables, i.e.
void calc_long_range_force (ParticleRange const &particles)
double calc_energy_long_range (ParticleRange const &particles)
ShortRangeForceKernel::result_type pair_force_kernel ()
ShortRangeEnergyKernel::result_type pair_energy_kernel ()
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr>
void add_actor (std::shared_ptr< T > const &actor)
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr>
void remove_actor (std::shared_ptr< T > const &actor)
Function Documentation
add_actor()
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr> void Dipoles::add_actor (std::shared_ptr< T > const & actor)
Definition at line 43 of file magnetostatics/registration.hpp.
References get_actor_name(), magnetostatics_actor, and on_dipoles_change().
calc_energy_long_range()
double Dipoles::calc_energy_long_range (ParticleRange const & particles)
Definition at line 203 of file dipoles.cpp.
References magnetostatics_actor, and Cells::particles().
calc_long_range_force()
void Dipoles::calc_long_range_force (ParticleRange const & particles)
Definition at line 197 of file dipoles.cpp.
References magnetostatics_actor, and Cells::particles().
Referenced by calc_long_range_forces().
calc_pressure_long_range()
void Dipoles::calc_pressure_long_range ()
Definition at line 86 of file dipoles.cpp.
References magnetostatics_actor, and runtimeWarningMsg.
cutoff()
double Dipoles::cutoff ()
Definition at line 92 of file dipoles.cpp.
References magnetostatics_actor.
Referenced by force_calc(), and recalc_long_range_cutoff().
on_boxl_change()
void Dipoles::on_boxl_change ()
Definition at line 62 of file dipoles.cpp.
References magnetostatics_actor, and visit_active_actor_try_catch().
Referenced by on_boxl_change().
on_cell_structure_change()
void Dipoles::on_cell_structure_change ()
called every time a major change to the cell structure has happened, like the skin or grid have changed.
This one is potentially slow.
Definition at line 80 of file dipoles.cpp.
References electrostatics_actor, magnetostatics_actor, and visit_active_actor_try_catch().
Referenced by on_cell_structure_change().
on_dipoles_change()
void Dipoles::on_dipoles_change ()
called every time the dipolar parameters are changed.
Definition at line 57 of file dipoles.cpp.
References magnetostatics_actor, on_dipoles_change(), on_short_range_ia_change(), reinit_magnetostatics, and visit_active_actor_try_catch().
Referenced by add_actor(), on_coulomb_and_dipoles_change(), on_dipoles_change(), and remove_actor().
on_node_grid_change()
void Dipoles::on_node_grid_change ()
Called when the node_grid changed.
Definition at line 67 of file dipoles.cpp.
References electrostatics_actor, and magnetostatics_actor.
Referenced by on_node_grid_change().
on_observable_calc()
void Dipoles::on_observable_calc ()
called before calculating observables, i.e.
energy, pressure or the integrator (forces). Initialize any methods here which are not initialized immediately (P3M etc.).
Definition at line 101 of file dipoles.cpp.
References electrostatics_actor, and magnetostatics_actor.
Referenced by on_observable_calc().
on_periodicity_change()
void Dipoles::on_periodicity_change ()
Called when the periodicity changes.
Internally calls on_skin_change.
Definition at line 74 of file dipoles.cpp.
References electrostatics_actor, magnetostatics_actor, and visit_active_actor_try_catch().
Referenced by on_periodicity_change().
pair_energy_kernel()
ShortRangeEnergyKernel::result_type Dipoles::pair_energy_kernel () inline
Definition at line 113 of file dipoles_inline.hpp.
References magnetostatics_actor.
Referenced by calculate_energy_local().
pair_force_kernel()
ShortRangeForceKernel::result_type Dipoles::pair_force_kernel () inline
Definition at line 103 of file dipoles_inline.hpp.
References magnetostatics_actor.
Referenced by force_calc().
remove_actor()
template<typename T , std::enable_if_t< traits::is_solver< T >::value > * = nullptr> void Dipoles::remove_actor (std::shared_ptr< T > const & actor)
Definition at line 54 of file magnetostatics/registration.hpp.
References is_already_stored(), magnetostatics_actor, and on_dipoles_change().
sanity_checks()
void Dipoles::sanity_checks ()
Definition at line 50 of file dipoles.cpp.
References magnetostatics_actor.
Referenced by long_range_interactions_sanity_checks().