ESPResSo: anonymous_namespace{particle_node.cpp} Namespace Reference
anonymous_namespace{particle_node.cpp} Namespace Reference
Variables
std::size_t const max_cache_size = (100ul * 1048576ul) / sizeof(Particle)
Utils::Cache< int, Particle > particle_fetch_cache (max_cache_size)
Variable Documentation
max_cache_size
std::size_t const anonymous_namespace{particle_node.cpp}::max_cache_size = (100ul * 1048576ul) / sizeof(Particle)
Definition at line 152 of file particle_node.cpp.
particle_fetch_cache
Utils::Cache< int, Particle > anonymous_namespace{particle_node.cpp}::particle_fetch_cache(max_cache_size) (max_cache_size)
Referenced by fetch_cache_max_size(), get_particle_data(), invalidate_fetch_cache(), and prefetch_particle_data().