ESPResSo: anonymous_namespace{fft.cpp} Namespace Reference
anonymous_namespace{fft.cpp} Namespace Reference
Functions
boost::optional< std::vector< int > > find_comm_groups (Utils::Vector3i const &grid1, Utils::Vector3i const &grid2, Utils::Span< const int > node_list1, Utils::Span< int > node_list2, Utils::Span< int > pos, Utils::Span< int > my_pos, boost::mpi::communicator const &comm)
This ugly function does the bookkeeping: which nodes have to communicate to each other, when you change the node grid.
int calc_local_mesh (const int *n_pos, const int *n_grid, const int *mesh, const double *mesh_off, int *loc_mesh, int *start)
Calculate the local fft mesh.
int calc_send_block (const int *pos1, const int *grid1, const int *pos2, const int *grid2, const int *mesh, const double *mesh_off, int *block)
Calculate a send (or recv.) block for grid communication during a decomposition change.
void pack_block_permute1 (double const *const in, double *const out, const int *start, const int *size, const int *dim, int element)
Pack a block with dimensions size[0] * size[1] * size[2] starting at start of an input 3D-grid with dimension dim into an output 3D-grid with dimensions size[2] * size[0] * size[1] with a simultaneous one-fold permutation of the indices.
void pack_block_permute2 (double const *const in, double *const out, const int *start, const int *size, const int *dim, int element)
Pack a block with dimensions size[0] * size[1] * size[2] starting at start of an input 3D-grid with dimension dim into an output 3D-grid with dimensions size[2] * size[0] * size[1] with a simultaneous two-fold permutation of the indices.
void forw_grid_comm (fft_forw_plan plan, const double *in, double *out, fft_data_struct &fft, const boost::mpi::communicator &comm)
Communicate the grid data according to the given forward FFT plan.
void back_grid_comm (fft_forw_plan plan_f, fft_back_plan plan_b, const double *in, double *out, fft_data_struct &fft, const boost::mpi::communicator &comm)
Communicate the grid data according to the given backward FFT plan.
int map_3don2d_grid (int const g3d[3], int g2d[3])
Calculate 'best' mapping between a 2D and 3D grid.
void calc_2d_grid (int n, int grid[3])
Calculate most square 2D grid.
Function Documentation
back_grid_comm()
void anonymous_namespace{fft.cpp}::back_grid_comm (fft_forw_plan plan_f, fft_back_plan plan_b, const double * in, double * out, fft_data_struct & fft, const boost::mpi::communicator & comm)
Communicate the grid data according to the given backward FFT plan.
Parameters
plan_f Forward FFT plan.
plan_b Backward FFT plan.
in input mesh.
out output mesh.
fft FFT communication plan.
comm MPI communicator.
Definition at line 391 of file fft.cpp.
References fft_forw_plan::element, fft_unpack_block(), fft_forw_plan::group, fft_forw_plan::new_mesh, fft_forw_plan::old_mesh, fft_back_plan::pack_function, fft_forw_plan::recv_block, fft_data_struct::recv_buf, fft_forw_plan::recv_size, REQ_FFT_BACK, fft_forw_plan::send_block, fft_data_struct::send_buf, and fft_forw_plan::send_size.
Referenced by fft_perform_back().
calc_2d_grid()
void anonymous_namespace{fft.cpp}::calc_2d_grid (int n, int grid[3])
Calculate most square 2D grid.
Definition at line 468 of file fft.cpp.
References Utils::sqrt().
Referenced by fft_init().
calc_local_mesh()
int anonymous_namespace{fft.cpp}::calc_local_mesh (const int * n_pos, const int * n_grid, const int * mesh, const double * mesh_off, int * loc_mesh, int * start)
Calculate the local fft mesh.
Calculate the local mesh (loc_mesh) of a node at position (n_pos) in a node grid (n_grid) for a global mesh of size (mesh) and a mesh offset (mesh_off (in mesh units)) and store also the first point (start) of the local mesh.
Parameters
[in] n_pos Position of the node in n_grid.
[in] n_grid node grid.
[in] mesh global mesh dimensions.
[in] mesh_off global mesh offset (see p3m_data_struct).
[out] loc_mesh local mesh dimension.
[out] start first point of local mesh in global mesh.
Returns
Number of mesh points in local mesh.
Definition at line 193 of file fft.cpp.
Referenced by calc_send_block(), and fft_init().
calc_send_block()
int anonymous_namespace{fft.cpp}::calc_send_block (const int * pos1, const int * grid1, const int * pos2, const int * grid2, const int * mesh, const double * mesh_off, int * block)
Calculate a send (or recv.) block for grid communication during a decomposition change.
Calculate the send block specification (block = lower left corner and upper right corner) which a node at position (pos1) in the actual node grid (grid1) has to send to another node at position (pos2) in the desired node grid (grid2). The global mesh, subject to communication, is specified via its size (mesh) and its mesh offset (mesh_off (in mesh units)).
For the calculation of a receive block you have to change the arguments in the following way:
pos1: position of receiving node in the desired node grid.
grid1: desired node grid.
pos2: position of the node you intend to receive the data from in the actual node grid.
grid2: actual node grid.
Parameters
[in] pos1 Position of send node in grid1.
[in] grid1 node grid 1.
[in] pos2 Position of recv node in grid2.
[in] grid2 node grid 2.
[in] mesh global mesh dimensions.
[in] mesh_off global mesh offset (see p3m_data_struct).
[out] block send block specification.
Returns
Size of the send block.
Definition at line 237 of file fft.cpp.
References block(), calc_local_mesh(), and anonymous_namespace{Correlator.cpp}::min().
Referenced by fft_init().
find_comm_groups()
boost::optional<std::vector<int> > anonymous_namespace{fft.cpp}::find_comm_groups (Utils::Vector3i const & grid1, Utils::Vector3i const & grid2, Utils::Span< const int > node_list1, Utils::Span< int > node_list2, Utils::Span< int > pos, Utils::Span< int > my_pos, boost::mpi::communicator const & comm)
This ugly function does the bookkeeping: which nodes have to communicate to each other, when you change the node grid.
Changing the regular decomposition requires communication. This function finds (hopefully) the best way to do this. As input it needs the two grids (grid1, grid2) and a linear list (node_list1) with the node identities for grid1. The linear list (node_list2) for the second grid is calculated. For the communication group of the calling node it calculates a list (group) with the node identities and the positions (my_pos, pos) of that nodes in grid1 and grid2. The return value is the size of the communication group. It gives -1 if the two grids do not fit to each other (grid1 and grid2 have to be component-wise multiples of each other, see e.g. calc_2d_grid for how to do this).
Parameters
[in] grid1 The node grid you start with.
[in] grid2 The node grid you want to have.
[in] node_list1 Linear node index list for grid1.
[out] node_list2 Linear node index list for grid2.
[out] pos Positions of the nodes in grid2
[out] my_pos Position of comm.rank() in grid2.
[in] comm MPI communicator.
Returns
Size of the communication group.
Definition at line 88 of file fft.cpp.
References Utils::get_linear_index(), ScriptInterface::none, and pos.
Referenced by fft_init().
forw_grid_comm()
void anonymous_namespace{fft.cpp}::forw_grid_comm (fft_forw_plan plan, const double * in, double * out, fft_data_struct & fft, const boost::mpi::communicator & comm)
Communicate the grid data according to the given forward FFT plan.
Parameters
plan FFT communication plan.
in input mesh.
out output mesh.
fft FFT communication plan.
comm MPI communicator.
Definition at line 361 of file fft.cpp.
References fft_forw_plan::element, fft_unpack_block(), fft_forw_plan::group, fft_forw_plan::new_mesh, fft_forw_plan::old_mesh, fft_forw_plan::pack_function, fft_forw_plan::recv_block, fft_data_struct::recv_buf, fft_forw_plan::recv_size, REQ_FFT_FORW, fft_forw_plan::send_block, fft_data_struct::send_buf, and fft_forw_plan::send_size.
Referenced by fft_perform_forw().
map_3don2d_grid()
int anonymous_namespace{fft.cpp}::map_3don2d_grid (int const g3d[3], int g2d[3])
Calculate 'best' mapping between a 2D and 3D grid.
Required for the communication from 3D regular domain decomposition to 2D regular row decomposition. The dimensions of the 2D grid are resorted, if necessary, in a way that they are multiples of the 3D grid dimensions.
Parameters
g3d 3D grid.
g2d 2D grid.
Returns
index of the row direction [0,1,2].
Definition at line 426 of file fft.cpp.
Referenced by fft_init().
pack_block_permute1()
void anonymous_namespace{fft.cpp}::pack_block_permute1 (double const *const in, double *const out, const int * start, const int * size, const int * dim, int element)
Pack a block with dimensions size[0] * size[1] * size[2] starting at start of an input 3D-grid with dimension dim into an output 3D-grid with dimensions size[2] * size[0] * size[1] with a simultaneous one-fold permutation of the indices.
The permutation is defined as: slow_in -> fast_out, mid_in ->slow_out, fast_in -> mid_out.
An element (i0_in, i1_in, i2_in) is then (i0_out = i1_in-start[1], i1_out = i2_in-start[2], i2_out = i0_in-start[0]) and for the linear indices we have:
li_in = i2_in + size[2] * (i1_in + (size[1]*i0_in))
li_out = i2_out + size[0] * (i1_out + (size[2]*i0_out))
For index definition see fft_pack_block.
Parameters
[in] in input 3D-grid.
[out] out output 3D-grid (block).
[in] start start index of the block in the in-grid.
[in] size size of the block (=dimension of the out-grid).
[in] dim size of the in-grid.
[in] element size of a grid element (e.g. 1 for Real, 2 for Complex).
Definition at line 278 of file fft.cpp.
References f.
Referenced by fft_init().
pack_block_permute2()
void anonymous_namespace{fft.cpp}::pack_block_permute2 (double const *const in, double *const out, const int * start, const int * size, const int * dim, int element)
Pack a block with dimensions size[0] * size[1] * size[2] starting at start of an input 3D-grid with dimension dim into an output 3D-grid with dimensions size[2] * size[0] * size[1] with a simultaneous two-fold permutation of the indices.
The permutation is defined as: slow_in -> mid_out, mid_in ->fast_out, fast_in -> slow_out.
An element (i0_in, i1_in, i2_in) is then (i0_out = i2_in-start[2], i1_out = i0_in-start[0], i2_out = i1_in-start[1]) and for the linear indices we have:
li_in = i2_in + size[2] * (i1_in + (size[1]*i0_in))
li_out = i2_out + size[0] * (i1_out + (size[2]*i0_out))
For index definition see fft_pack_block.
Parameters
[in] in input 3D-grid.
[out] out output 3D-grid (block).
[in] start start index of the block in the in-grid.
[in] size size of the block (=dimension of the out-grid).
[in] dim size of the in-grid.
[in] element size of a grid element (e.g. 1 for Real, 2 for Complex).
Definition at line 326 of file fft.cpp.
References f.
Referenced by fft_init().