ESPResSo: ParticlePropertyRange Namespace Reference
ParticlePropertyRange Namespace Reference
Functions
auto unfolded_pos_range (ParticleRange const &particles, BoxGeometry const &box)
auto pos_range (ParticleRange const &particles)
auto charge_range (ParticleRange const &particles)
auto force_range (ParticleRange const &particles)
Function Documentation
charge_range()
auto ParticlePropertyRange::charge_range (ParticleRange const & particles) inline
Definition at line 58 of file ParticlePropertyIterator.hpp.
References stream.
Referenced by ElectrostaticLayerCorrection::add_long_range_forces(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::charge_assign(), ElectrostaticLayerCorrection::long_range_energy(), and CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel().
force_range()
auto ParticlePropertyRange::force_range (ParticleRange const & particles) inline
Definition at line 63 of file ParticlePropertyIterator.hpp.
References stream.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel().
pos_range()
auto ParticlePropertyRange::pos_range (ParticleRange const & particles) inline
Definition at line 53 of file ParticlePropertyIterator.hpp.
References stream.
Referenced by ElectrostaticLayerCorrection::add_long_range_forces(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::charge_assign(), and ElectrostaticLayerCorrection::long_range_energy().
unfolded_pos_range()
auto ParticlePropertyRange::unfolded_pos_range (ParticleRange const & particles, BoxGeometry const & box) inline
Definition at line 45 of file ParticlePropertyIterator.hpp.
References BoxGeometry::length(), and stream.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel().