ESPResSo: walberla::lbm::accessor::MomentumDensity Namespace Reference
walberla::lbm::accessor::MomentumDensity Namespace Reference
Functions
auto reduce (GhostLayerField< double, uint_t{19u}> const *pdf_field, GhostLayerField< double, uint_t{3u}> const *force_field, double const density)
__global__ void kernel_get (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > force, double *RESTRICT out, double const density)
Vector3< double > reduce (gpu::GPUField< double > const *pdf_field, gpu::GPUField< double > const *force_field, double const density)
auto reduce (GhostLayerField< float, uint_t{19u}> const *pdf_field, GhostLayerField< float, uint_t{3u}> const *force_field, float const density)
__global__ void kernel_get (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > force, float *RESTRICT out, float const density)
Vector3< float > reduce (gpu::GPUField< float > const *pdf_field, gpu::GPUField< float > const *force_field, float const density)
Function Documentation
kernel_get() [1/2]
__global__ void walberla::lbm::accessor::MomentumDensity::kernel_get (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > force, double *RESTRICT out, double const density)
Definition at line 1204 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, getLinearIndex(), and stream.
Referenced by reduce(), and reduce().
kernel_get() [2/2]
__global__ void walberla::lbm::accessor::MomentumDensity::kernel_get (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > force, float *RESTRICT out, float const density)
Definition at line 1204 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, getLinearIndex(), and stream.
reduce() [1/4]
auto walberla::lbm::accessor::MomentumDensity::reduce (GhostLayerField< double, uint_t{19u}> const * pdf_field, GhostLayerField< double, uint_t{3u}> const * force_field, double const density) inline
Definition at line 1108 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum().
reduce() [2/4]
auto walberla::lbm::accessor::MomentumDensity::reduce (GhostLayerField< float, uint_t{19u}> const * pdf_field, GhostLayerField< float, uint_t{3u}> const * force_field, float const density) inline
Definition at line 1108 of file FieldAccessorsSinglePrecision.h.
reduce() [3/4]
Vector3< double > walberla::lbm::accessor::MomentumDensity::reduce (gpu::GPUField< double > const * pdf_field, gpu::GPUField< double > const * force_field, double const density)
Definition at line 1248 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_get(), and stream.
reduce() [4/4]
Vector3< float > walberla::lbm::accessor::MomentumDensity::reduce (gpu::GPUField< float > const * pdf_field, gpu::GPUField< float > const * force_field, float const density)
Definition at line 1248 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_get(), and stream.