ESPResSo: walberla::lbm::accessor::Force Namespace Reference
walberla::lbm::accessor::Force Namespace Reference
Functions
void set (GhostLayerField< double, uint_t{19u}> const *pdf_field, GhostLayerField< double, uint_t{3u}> *velocity_field, GhostLayerField< double, uint_t{3u}> *force_field, Vector3< double > const &force, double const density, Cell const &cell)
void set (GhostLayerField< double, uint_t{19u}> const *pdf_field, GhostLayerField< double, uint_t{3u}> *velocity_field, GhostLayerField< double, uint_t{3u}> *force_field, std::vector< double > const &values, double const density, CellInterval const &ci)
__global__ void kernel_set (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > velocity, gpu::FieldAccessor< double > force, double const *RESTRICT f_in, double const density)
void set (gpu::GPUField< double > const *pdf_field, gpu::GPUField< double > *velocity_field, gpu::GPUField< double > *force_field, Vector3< double > const &u, double const density, Cell const &cell)
void set (gpu::GPUField< double > const *pdf_field, gpu::GPUField< double > *velocity_field, gpu::GPUField< double > *force_field, std::vector< double > const &values, double const density, CellInterval const &ci)
void set (GhostLayerField< float, uint_t{19u}> const *pdf_field, GhostLayerField< float, uint_t{3u}> *velocity_field, GhostLayerField< float, uint_t{3u}> *force_field, Vector3< float > const &force, float const density, Cell const &cell)
void set (GhostLayerField< float, uint_t{19u}> const *pdf_field, GhostLayerField< float, uint_t{3u}> *velocity_field, GhostLayerField< float, uint_t{3u}> *force_field, std::vector< float > const &values, float const density, CellInterval const &ci)
__global__ void kernel_set (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > velocity, gpu::FieldAccessor< float > force, float const *RESTRICT f_in, float const density)
void set (gpu::GPUField< float > const *pdf_field, gpu::GPUField< float > *velocity_field, gpu::GPUField< float > *force_field, Vector3< float > const &u, float const density, Cell const &cell)
void set (gpu::GPUField< float > const *pdf_field, gpu::GPUField< float > *velocity_field, gpu::GPUField< float > *force_field, std::vector< float > const &values, float const density, CellInterval const &ci)
Function Documentation
kernel_set() [1/2]
__global__ void walberla::lbm::accessor::Force::kernel_set (gpu::FieldAccessor< double > pdf, gpu::FieldAccessor< double > velocity, gpu::FieldAccessor< double > force, double const *RESTRICT f_in, double const density)
Definition at line 1110 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, getLinearIndex(), stream, and velocity().
Referenced by set(), set(), set(), and set().
kernel_set() [2/2]
__global__ void walberla::lbm::accessor::Force::kernel_set (gpu::FieldAccessor< float > pdf, gpu::FieldAccessor< float > velocity, gpu::FieldAccessor< float > force, float const *RESTRICT f_in, float const density)
Definition at line 1110 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, getLinearIndex(), stream, and velocity().
set() [1/8]
void walberla::lbm::accessor::Force::set (GhostLayerField< double, uint_t{19u}> const * pdf_field, GhostLayerField< double, uint_t{3u}> * velocity_field, GhostLayerField< double, uint_t{3u}> * force_field, std::vector< double > const & values, double const density, CellInterval const & ci) inline
Definition at line 1040 of file FieldAccessorsDoublePrecision.h.
set() [2/8]
void walberla::lbm::accessor::Force::set (GhostLayerField< double, uint_t{19u}> const * pdf_field, GhostLayerField< double, uint_t{3u}> * velocity_field, GhostLayerField< double, uint_t{3u}> * force_field, Vector3< double > const & force, double const density, Cell const & cell) inline
Definition at line 989 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force().
set() [3/8]
void walberla::lbm::accessor::Force::set (GhostLayerField< float, uint_t{19u}> const * pdf_field, GhostLayerField< float, uint_t{3u}> * velocity_field, GhostLayerField< float, uint_t{3u}> * force_field, std::vector< float > const & values, float const density, CellInterval const & ci) inline
Definition at line 1040 of file FieldAccessorsSinglePrecision.h.
set() [4/8]
void walberla::lbm::accessor::Force::set (GhostLayerField< float, uint_t{19u}> const * pdf_field, GhostLayerField< float, uint_t{3u}> * velocity_field, GhostLayerField< float, uint_t{3u}> * force_field, Vector3< float > const & force, float const density, Cell const & cell) inline
Definition at line 989 of file FieldAccessorsSinglePrecision.h.
set() [5/8]
void walberla::lbm::accessor::Force::set (gpu::GPUField< double > const * pdf_field, gpu::GPUField< double > * velocity_field, gpu::GPUField< double > * force_field, std::vector< double > const & values, double const density, CellInterval const & ci)
Definition at line 1184 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_set(), and stream.
set() [6/8]
void walberla::lbm::accessor::Force::set (gpu::GPUField< double > const * pdf_field, gpu::GPUField< double > * velocity_field, gpu::GPUField< double > * force_field, Vector3< double > const & u, double const density, Cell const & cell)
Definition at line 1166 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_set(), and stream.
set() [7/8]
void walberla::lbm::accessor::Force::set (gpu::GPUField< float > const * pdf_field, gpu::GPUField< float > * velocity_field, gpu::GPUField< float > * force_field, std::vector< float > const & values, float const density, CellInterval const & ci)
Definition at line 1184 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_set(), and stream.
set() [8/8]
void walberla::lbm::accessor::Force::set (gpu::GPUField< float > const * pdf_field, gpu::GPUField< float > * velocity_field, gpu::GPUField< float > * force_field, Vector3< float > const & u, float const density, Cell const & cell)
Definition at line 1166 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_set(), and stream.