ESPResSo: BondBreakage Namespace Reference
BondBreakage Namespace Reference
Classes
struct BreakageSpec
struct DeleteAllBonds
struct DeleteBond
Typedefs
using Action = boost::variant< DeleteBond, DeleteAllBonds >
using ActionSet = std::unordered_set< Action >
using Queue = std::vector< QueueEntry >
Queue to record bonds broken during a time step.
Enumerations
enum ActionType { ActionType::NONE = 0, ActionType::DELETE_BOND = 1, ActionType::REVERT_BIND_AT_POINT_OF_COLLISION = 2 }
Functions
void insert_spec (int key, std::shared_ptr< BreakageSpec > obj)
void erase_spec (int key)
boost::optional< BreakageSpec > get_breakage_spec (int bond_type)
Retrieve breakage specification for the bond type.
void queue_breakage (int particle_id, int bond_partner_id, int bond_type)
Add a particle+bond combination to the breakage queue.
bool check_and_handle_breakage (int particle_id, int bond_partner_id, int bond_type, double distance)
Check if the bond between the particles should break, if yes, queue it.
void clear_queue ()
Queue gather_global_queue (Queue const &local_queue)
Gathers combined queue from all mpi ranks.
ActionSet actions_for_breakage (QueueEntry const &e)
Constructs the actions to take for a breakage queue entry.
void process_queue ()
Variables
static std::unordered_map< int, std::shared_ptr< BreakageSpec > > breakage_specs
Queue queue
Typedef Documentation
Action
using BondBreakage::Action = typedef boost::variant<DeleteBond, DeleteAllBonds>
Definition at line 52 of file bond_breakage.cpp.
ActionSet
using BondBreakage::ActionSet = typedef std::unordered_set<Action>
Definition at line 55 of file bond_breakage.cpp.
Queue
using BondBreakage::Queue = typedef std::vector<QueueEntry>
Queue to record bonds broken during a time step.
Definition at line 74 of file bond_breakage.cpp.
Enumeration Type Documentation
ActionType
enum BondBreakage::ActionType strong
Enumerator
NONE
DELETE_BOND
REVERT_BIND_AT_POINT_OF_COLLISION
Definition at line 28 of file bond_breakage.hpp.
Function Documentation
actions_for_breakage()
ActionSet BondBreakage::actions_for_breakage (QueueEntry const & e)
Constructs the actions to take for a breakage queue entry.
Definition at line 116 of file bond_breakage.cpp.
References cell_structure, DELETE_BOND, get_breakage_spec(), CellStructure::get_local_particle(), REVERT_BIND_AT_POINT_OF_COLLISION, and runtimeErrorMsg.
Referenced by process_queue().
check_and_handle_breakage()
bool BondBreakage::check_and_handle_breakage (int particle_id, int bond_partner_id, int bond_type, double distance)
Check if the bond between the particles should break, if yes, queue it.
Definition at line 90 of file bond_breakage.cpp.
References get_breakage_spec(), and queue_breakage().
Referenced by add_bonded_force().
clear_queue()
void BondBreakage::clear_queue ()
Definition at line 105 of file bond_breakage.cpp.
References queue.
Referenced by force_calc().
erase_spec()
void BondBreakage::erase_spec (int key)
Definition at line 49 of file bond_breakage.cpp.
References breakage_specs.
Referenced by ScriptInterface::BondBreakage::BreakageSpecs::erase_in_core().
gather_global_queue()
Queue BondBreakage::gather_global_queue (Queue const & local_queue)
Gathers combined queue from all mpi ranks.
Definition at line 108 of file bond_breakage.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), and res.
Referenced by process_queue().
get_breakage_spec()
boost::optional<BreakageSpec> BondBreakage::get_breakage_spec (int bond_type)
Retrieve breakage specification for the bond type.
Definition at line 78 of file bond_breakage.cpp.
References breakage_specs.
Referenced by actions_for_breakage(), and check_and_handle_breakage().
insert_spec()
void BondBreakage::insert_spec (int key, std::shared_ptr< BreakageSpec > obj)
Definition at line 45 of file bond_breakage.cpp.
References breakage_specs.
Referenced by ScriptInterface::BondBreakage::BreakageSpecs::insert_in_core().
process_queue()
void BondBreakage::process_queue ()
Definition at line 173 of file bond_breakage.cpp.
References actions_for_breakage(), breakage_specs, gather_global_queue(), and queue.
Referenced by integrate().
queue_breakage()
void BondBreakage::queue_breakage (int particle_id, int bond_partner_id, int bond_type)
Add a particle+bond combination to the breakage queue.
Definition at line 86 of file bond_breakage.cpp.
References queue.
Referenced by check_and_handle_breakage().
Variable Documentation
breakage_specs
std::unordered_map<int, std::shared_ptr<BreakageSpec> > BondBreakage::breakage_specs static
Definition at line 43 of file bond_breakage.cpp.
Referenced by erase_spec(), get_breakage_spec(), insert_spec(), and process_queue().
queue
Queue BondBreakage::queue
Definition at line 75 of file bond_breakage.cpp.
Referenced by clear_queue(), process_queue(), and queue_breakage().