ESPResSo: walberla::lbm::accessor::PressureTensor Namespace Reference
walberla::lbm::accessor::PressureTensor Namespace Reference
Functions
auto get (GhostLayerField< double, uint_t{19u}> const *pdf_field, double const density, Cell const &cell)
auto get (GhostLayerField< double, uint_t{19u}> const *pdf_field, double const density, CellInterval const &ci)
auto reduce (GhostLayerField< double, uint_t{19u}> const *pdf_field, double const density)
__global__ void kernel_get (gpu::FieldAccessor< double > pdf, double *RESTRICT p_out)
Matrix3< double > get (gpu::GPUField< double > const *pdf_field, double const density, Cell const &cell)
std::vector< double > get (gpu::GPUField< double > const *pdf_field, double const density, CellInterval const &ci)
Matrix3< double > reduce (gpu::GPUField< double > const *pdf_field, double const density)
auto get (GhostLayerField< float, uint_t{19u}> const *pdf_field, float const density, Cell const &cell)
auto get (GhostLayerField< float, uint_t{19u}> const *pdf_field, float const density, CellInterval const &ci)
auto reduce (GhostLayerField< float, uint_t{19u}> const *pdf_field, float const density)
__global__ void kernel_get (gpu::FieldAccessor< float > pdf, float *RESTRICT p_out)
Matrix3< float > get (gpu::GPUField< float > const *pdf_field, float const density, Cell const &cell)
std::vector< float > get (gpu::GPUField< float > const *pdf_field, float const density, CellInterval const &ci)
Matrix3< float > reduce (gpu::GPUField< float > const *pdf_field, float const density)
Function Documentation
get() [1/8]
auto walberla::lbm::accessor::PressureTensor::get (GhostLayerField< double, uint_t{19u}> const * pdf_field, double const density, Cell const & cell) inline
Definition at line 1160 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::PressureTensorVTKWriter< OutputType >::evaluate(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor(), and walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor().
get() [2/8]
auto walberla::lbm::accessor::PressureTensor::get (GhostLayerField< double, uint_t{19u}> const * pdf_field, double const density, CellInterval const & ci) inline
Definition at line 1212 of file FieldAccessorsDoublePrecision.h.
get() [3/8]
auto walberla::lbm::accessor::PressureTensor::get (GhostLayerField< float, uint_t{19u}> const * pdf_field, float const density, Cell const & cell) inline
Definition at line 1160 of file FieldAccessorsSinglePrecision.h.
get() [4/8]
auto walberla::lbm::accessor::PressureTensor::get (GhostLayerField< float, uint_t{19u}> const * pdf_field, float const density, CellInterval const & ci) inline
Definition at line 1212 of file FieldAccessorsSinglePrecision.h.
get() [5/8]
Matrix3< double > walberla::lbm::accessor::PressureTensor::get (gpu::GPUField< double > const * pdf_field, double const density, Cell const & cell)
Definition at line 1322 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_get(), and stream.
get() [6/8]
std::vector< double > walberla::lbm::accessor::PressureTensor::get (gpu::GPUField< double > const * pdf_field, double const density, CellInterval const & ci)
Definition at line 1338 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_get(), and stream.
get() [7/8]
Matrix3< float > walberla::lbm::accessor::PressureTensor::get (gpu::GPUField< float > const * pdf_field, float const density, Cell const & cell)
Definition at line 1322 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_get(), and stream.
get() [8/8]
std::vector< float > walberla::lbm::accessor::PressureTensor::get (gpu::GPUField< float > const * pdf_field, float const density, CellInterval const & ci)
Definition at line 1338 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_get(), and stream.
kernel_get() [1/2]
__global__ void walberla::lbm::accessor::PressureTensor::kernel_get (gpu::FieldAccessor< double > pdf, double *RESTRICT p_out)
Definition at line 1275 of file FieldAccessorsDoublePrecisionCUDA.cu.
References getLinearIndex(), and stream.
Referenced by get(), get(), get(), get(), reduce(), and reduce().
kernel_get() [2/2]
__global__ void walberla::lbm::accessor::PressureTensor::kernel_get (gpu::FieldAccessor< float > pdf, float *RESTRICT p_out)
Definition at line 1275 of file FieldAccessorsSinglePrecisionCUDA.cu.
References getLinearIndex(), and stream.
reduce() [1/4]
auto walberla::lbm::accessor::PressureTensor::reduce (GhostLayerField< double, uint_t{19u}> const * pdf_field, double const density) inline
Definition at line 1267 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_pressure_tensor().
reduce() [2/4]
auto walberla::lbm::accessor::PressureTensor::reduce (GhostLayerField< float, uint_t{19u}> const * pdf_field, float const density) inline
Definition at line 1267 of file FieldAccessorsSinglePrecision.h.
reduce() [3/4]
Matrix3< double > walberla::lbm::accessor::PressureTensor::reduce (gpu::GPUField< double > const * pdf_field, double const density)
Definition at line 1355 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_get(), and stream.
reduce() [4/4]
Matrix3< float > walberla::lbm::accessor::PressureTensor::reduce (gpu::GPUField< float > const * pdf_field, float const density)
Definition at line 1355 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_get(), and stream.