ESPResSo: ScriptInterface::CodeInfo Namespace Reference
ScriptInterface::CodeInfo Namespace Reference
Classes
class CodeInfo
class CodeVersion
Functions
static auto get_feature_vector (char const *const ptr[], unsigned int len)
static auto get_feature_set (char const *const ptr[], unsigned int len)
void check_features (std::vector< std::string > const &features)
static auto get_version_tuple_as_string ()
void initialize (Utils::Factory< ObjectHandle > *om)
Function Documentation
check_features()
void ScriptInterface::CodeInfo::check_features (std::vector< std::string > const & features)
Definition at line 66 of file CodeInfo.cpp.
References get_feature_set(), and ScriptInterface::get_value().
get_feature_set()
static auto ScriptInterface::CodeInfo::get_feature_set (char const *const ptr[], unsigned int len) static
Definition at line 40 of file CodeInfo.cpp.
References ScriptInterface::get_value().
Referenced by check_features().
get_feature_vector()
static auto ScriptInterface::CodeInfo::get_feature_vector (char const *const ptr[], unsigned int len) static
Definition at line 36 of file CodeInfo.cpp.
References ScriptInterface::get_value().
Referenced by ScriptInterface::CodeInfo::CodeInfo::do_call_method().
get_version_tuple_as_string()
static auto ScriptInterface::CodeInfo::get_version_tuple_as_string () static
Definition at line 32 of file CodeVersion.cpp.
References ScriptInterface::get_value().
Referenced by ScriptInterface::CodeInfo::CodeVersion::do_call_method().
initialize()
void ScriptInterface::CodeInfo::initialize (Utils::Factory< ObjectHandle > * om)
Definition at line 28 of file code_info/initialize.cpp.
References ScriptInterface::get_value().
Referenced by ScriptInterface::initialize().