ESPResSo: ScriptInterface::Scafacos Namespace Reference
ScriptInterface::Scafacos Namespace Reference
Classes
struct ConvertToStringVector
struct GetParameterList
Functions
std::vector< std::string > available_methods ()
Fetch list of methods compiled in ScaFaCoS.
std::string serialize_parameters (Variant const &pack)
Flatten a parameter map.
template<typename T >
std::optional< Variant > string_to_number (std::string const &s)
std::unordered_map< std::string, Variant > deserialize_parameters (std::string const &parameters)
Convert flattened parameters to a map.
Function Documentation
available_methods()
std::vector< std::string > ScriptInterface::Scafacos::available_methods ()
Fetch list of methods compiled in ScaFaCoS.
Definition at line 50 of file scafacos.cpp.
References ScafacosContextBase::available_methods().
Referenced by ScriptInterface::CodeInfo::CodeInfo::do_call_method(), ScriptInterface::Coulomb::CoulombScafacos::do_call_method(), and ScriptInterface::Dipoles::DipolarScafacos::do_call_method().
deserialize_parameters()
std::unordered_map< std::string, Variant > ScriptInterface::Scafacos::deserialize_parameters (std::string const & parameters)
Convert flattened parameters to a map.
Definition at line 153 of file scafacos.cpp.
References stream.
Referenced by ScriptInterface::Coulomb::CoulombScafacos::CoulombScafacos(), and ScriptInterface::Dipoles::DipolarScafacos::DipolarScafacos().
serialize_parameters()
std::string ScriptInterface::Scafacos::serialize_parameters (Variant const & pack)
Flatten a parameter map.
Definition at line 124 of file scafacos.cpp.
References ScriptInterface::pack(), and stream.
Referenced by ScriptInterface::Coulomb::CoulombScafacos::do_construct(), and ScriptInterface::Dipoles::DipolarScafacos::do_construct().
string_to_number()
template<typename T > std::optional< Variant > ScriptInterface::Scafacos::string_to_number (std::string const & s)
Definition at line 142 of file scafacos.cpp.
References stream.