ESPResSo: ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp} Namespace Reference
ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp} Namespace Reference
Functions
Variant pack_vector (Utils::Vector3i const &vec)
const auto & get_regular_decomposition ()
const auto & get_hybrid_decomposition ()
Function Documentation
get_hybrid_decomposition()
const auto& ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::get_hybrid_decomposition ()
Definition at line 65 of file CellSystem.hpp.
References Utils::as_const(), and cell_structure.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and ScriptInterface::CellSystem::CellSystem::do_call_method().
get_regular_decomposition()
const auto& ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::get_regular_decomposition ()
Definition at line 60 of file CellSystem.hpp.
References Utils::as_const(), and cell_structure.
Referenced by ScriptInterface::CellSystem::CellSystem::do_call_method().
pack_vector()
Variant ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::pack_vector (Utils::Vector3i const & vec)
Definition at line 57 of file CellSystem.hpp.
References Utils::Array< T, N >::begin(), and Utils::Array< T, N >::end().
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and ScriptInterface::CellSystem::CellSystem::do_call_method().