ESPResSo: walberla::lbm::accessor::Vector Namespace Reference
walberla::lbm::accessor::Vector Namespace Reference
Functions
auto get (GhostLayerField< double, uint_t{3u}> const *vec_field, Cell const &cell)
void set (GhostLayerField< double, uint_t{3u}> *vec_field, Vector3< double > const &vec, Cell const &cell)
void add (GhostLayerField< double, uint_t{3u}> *vec_field, Vector3< double > const &vec, Cell const &cell)
void initialize (GhostLayerField< double, uint_t{3u}> *vec_field, Vector3< double > const &vec)
void add_to_all (GhostLayerField< double, uint_t{3u}> *vec_field, Vector3< double > const &vec)
auto get (GhostLayerField< double, uint_t{3u}> const *vec_field, CellInterval const &ci)
void set (GhostLayerField< double, uint_t{3u}> *vec_field, std::vector< double > const &values, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< double > vec, double *u_out)
__global__ void kernel_set (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
__global__ void kernel_broadcast (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
__global__ void kernel_add (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
__global__ void kernel_broadcast_add (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
__global__ void kernel_set_from_list (gpu::FieldAccessor< double > vec, int const *RESTRICT const indices, double const *RESTRICT const values, uint length)
Vector3< double > get (gpu::GPUField< double > const *field, Cell const &cell)
Get value from a single cell.
void set (gpu::GPUField< double > *field, Vector3< double > const &vec, Cell const &cell)
Set value on a single cell.
void add (gpu::GPUField< double > *field, Vector3< double > const &vec, Cell const &cell)
Add value to a single cell.
void initialize (gpu::GPUField< double > *field, Vector3< double > const &vec)
Initialize all cells with the same value.
void add_to_all (gpu::GPUField< double > *field, Vector3< double > const &vec)
Add value to all cells.
std::vector< double > get (gpu::GPUField< double > const *vec_field, CellInterval const &ci)
Get values from a cell interval.
void set (gpu::GPUField< double > *vec_field, std::vector< double > const &values, CellInterval const &ci)
Set values on a cell interval.
void set_from_list (gpu::GPUField< double > const *field, thrust::device_vector< int > const &indices, thrust::device_vector< double > const &values, uint gl)
auto get (GhostLayerField< float, uint_t{3u}> const *vec_field, Cell const &cell)
void set (GhostLayerField< float, uint_t{3u}> *vec_field, Vector3< float > const &vec, Cell const &cell)
void add (GhostLayerField< float, uint_t{3u}> *vec_field, Vector3< float > const &vec, Cell const &cell)
void initialize (GhostLayerField< float, uint_t{3u}> *vec_field, Vector3< float > const &vec)
void add_to_all (GhostLayerField< float, uint_t{3u}> *vec_field, Vector3< float > const &vec)
auto get (GhostLayerField< float, uint_t{3u}> const *vec_field, CellInterval const &ci)
void set (GhostLayerField< float, uint_t{3u}> *vec_field, std::vector< float > const &values, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< float > vec, float *u_out)
__global__ void kernel_set (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
__global__ void kernel_broadcast (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
__global__ void kernel_add (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
__global__ void kernel_broadcast_add (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
__global__ void kernel_set_from_list (gpu::FieldAccessor< float > vec, int const *RESTRICT const indices, float const *RESTRICT const values, uint length)
Vector3< float > get (gpu::GPUField< float > const *field, Cell const &cell)
Get value from a single cell.
void set (gpu::GPUField< float > *field, Vector3< float > const &vec, Cell const &cell)
Set value on a single cell.
void add (gpu::GPUField< float > *field, Vector3< float > const &vec, Cell const &cell)
Add value to a single cell.
void initialize (gpu::GPUField< float > *field, Vector3< float > const &vec)
Initialize all cells with the same value.
void add_to_all (gpu::GPUField< float > *field, Vector3< float > const &vec)
Add value to all cells.
std::vector< float > get (gpu::GPUField< float > const *vec_field, CellInterval const &ci)
Get values from a cell interval.
void set (gpu::GPUField< float > *vec_field, std::vector< float > const &values, CellInterval const &ci)
Set values on a cell interval.
void set_from_list (gpu::GPUField< float > const *field, thrust::device_vector< int > const &indices, thrust::device_vector< float > const &values, uint gl)
Function Documentation
add() [1/4]
void walberla::lbm::accessor::Vector::add (GhostLayerField< double, uint_t{3u}> * vec_field, Vector3< double > const & vec, Cell const & cell) inline
Definition at line 320 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel().
add() [2/4]
void walberla::lbm::accessor::Vector::add (GhostLayerField< float, uint_t{3u}> * vec_field, Vector3< float > const & vec, Cell const & cell) inline
Definition at line 320 of file FieldAccessorsSinglePrecision.h.
add() [3/4]
void walberla::lbm::accessor::Vector::add (gpu::GPUField< double > * vec_field, Vector3< double > const & vec, Cell const & cell)
Add value to a single cell.
Definition at line 464 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_add(), and stream.
add() [4/4]
void walberla::lbm::accessor::Vector::add (gpu::GPUField< float > * vec_field, Vector3< float > const & vec, Cell const & cell)
Add value to a single cell.
Definition at line 464 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_add(), and stream.
add_to_all() [1/4]
void walberla::lbm::accessor::Vector::add_to_all (GhostLayerField< double, uint_t{3u}> * vec_field, Vector3< double > const & vec) inline
Definition at line 338 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::ResetForce< PdfField, ForceField >::operator()().
add_to_all() [2/4]
void walberla::lbm::accessor::Vector::add_to_all (GhostLayerField< float, uint_t{3u}> * vec_field, Vector3< float > const & vec) inline
Definition at line 338 of file FieldAccessorsSinglePrecision.h.
add_to_all() [3/4]
void walberla::lbm::accessor::Vector::add_to_all (gpu::GPUField< double > * vec_field, Vector3< double > const & vec)
Add value to all cells.
Definition at line 489 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_broadcast_add(), and stream.
add_to_all() [4/4]
void walberla::lbm::accessor::Vector::add_to_all (gpu::GPUField< float > * vec_field, Vector3< float > const & vec)
Add value to all cells.
Definition at line 489 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_broadcast_add(), and stream.
get() [1/8]
auto walberla::lbm::accessor::Vector::get (GhostLayerField< double, uint_t{3u}> const * vec_field, Cell const & cell) inline
Definition at line 302 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::VelocityVTKWriter< OutputType >::evaluate(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel().
get() [2/8]
auto walberla::lbm::accessor::Vector::get (GhostLayerField< double, uint_t{3u}> const * vec_field, CellInterval const & ci) inline
Definition at line 348 of file FieldAccessorsDoublePrecision.h.
get() [3/8]
auto walberla::lbm::accessor::Vector::get (GhostLayerField< float, uint_t{3u}> const * vec_field, Cell const & cell) inline
Definition at line 302 of file FieldAccessorsSinglePrecision.h.
get() [4/8]
auto walberla::lbm::accessor::Vector::get (GhostLayerField< float, uint_t{3u}> const * vec_field, CellInterval const & ci) inline
Definition at line 348 of file FieldAccessorsSinglePrecision.h.
get() [5/8]
Vector3< double > walberla::lbm::accessor::Vector::get (gpu::GPUField< double > const * vec_field, Cell const & cell)
Get value from a single cell.
Definition at line 436 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_get(), and stream.
get() [6/8]
std::vector< double > walberla::lbm::accessor::Vector::get (gpu::GPUField< double > const * vec_field, CellInterval const & ci)
Get values from a cell interval.
Definition at line 501 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_get(), and stream.
get() [7/8]
Vector3< float > walberla::lbm::accessor::Vector::get (gpu::GPUField< float > const * vec_field, Cell const & cell)
Get value from a single cell.
Definition at line 436 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_get(), and stream.
get() [8/8]
std::vector< float > walberla::lbm::accessor::Vector::get (gpu::GPUField< float > const * vec_field, CellInterval const & ci)
Get values from a cell interval.
Definition at line 501 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_get(), and stream.
initialize() [1/4]
void walberla::lbm::accessor::Vector::initialize (GhostLayerField< double, uint_t{3u}> * vec_field, Vector3< double > const & vec) inline
Definition at line 328 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::add_to_storage(), and walberla::ResetForce< PdfField, ForceField >::operator()().
initialize() [2/4]
void walberla::lbm::accessor::Vector::initialize (GhostLayerField< float, uint_t{3u}> * vec_field, Vector3< float > const & vec) inline
Definition at line 328 of file FieldAccessorsSinglePrecision.h.
initialize() [3/4]
void walberla::lbm::accessor::Vector::initialize (gpu::GPUField< double > * vec_field, Vector3< double > const & vec)
Initialize all cells with the same value.
Definition at line 477 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_broadcast(), and stream.
initialize() [4/4]
void walberla::lbm::accessor::Vector::initialize (gpu::GPUField< float > * vec_field, Vector3< float > const & vec)
Initialize all cells with the same value.
Definition at line 477 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_broadcast(), and stream.
kernel_add() [1/2]
__global__ void walberla::lbm::accessor::Vector::kernel_add (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
Definition at line 389 of file FieldAccessorsDoublePrecisionCUDA.cu.
References getLinearIndex(), and stream.
Referenced by add(), and add().
kernel_add() [2/2]
__global__ void walberla::lbm::accessor::Vector::kernel_add (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
Definition at line 389 of file FieldAccessorsSinglePrecisionCUDA.cu.
References getLinearIndex(), and stream.
kernel_broadcast() [1/2]
__global__ void walberla::lbm::accessor::Vector::kernel_broadcast (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
Definition at line 378 of file FieldAccessorsDoublePrecisionCUDA.cu.
References stream.
Referenced by initialize(), and initialize().
kernel_broadcast() [2/2]
__global__ void walberla::lbm::accessor::Vector::kernel_broadcast (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
Definition at line 378 of file FieldAccessorsSinglePrecisionCUDA.cu.
References stream.
kernel_broadcast_add() [1/2]
__global__ void walberla::lbm::accessor::Vector::kernel_broadcast_add (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
Definition at line 402 of file FieldAccessorsDoublePrecisionCUDA.cu.
References stream.
Referenced by add_to_all(), and add_to_all().
kernel_broadcast_add() [2/2]
__global__ void walberla::lbm::accessor::Vector::kernel_broadcast_add (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
Definition at line 402 of file FieldAccessorsSinglePrecisionCUDA.cu.
References stream.
kernel_get() [1/2]
__global__ void walberla::lbm::accessor::Vector::kernel_get (gpu::FieldAccessor< double > vec, double * u_out)
Definition at line 352 of file FieldAccessorsDoublePrecisionCUDA.cu.
References getLinearIndex(), and stream.
Referenced by get(), get(), get(), and get().
kernel_get() [2/2]
__global__ void walberla::lbm::accessor::Vector::kernel_get (gpu::FieldAccessor< float > vec, float * u_out)
Definition at line 352 of file FieldAccessorsSinglePrecisionCUDA.cu.
References getLinearIndex(), and stream.
kernel_set() [1/2]
__global__ void walberla::lbm::accessor::Vector::kernel_set (gpu::FieldAccessor< double > vec, double const *RESTRICT u_in)
Definition at line 365 of file FieldAccessorsDoublePrecisionCUDA.cu.
References getLinearIndex(), and stream.
Referenced by set(), set(), set(), and set().
kernel_set() [2/2]
__global__ void walberla::lbm::accessor::Vector::kernel_set (gpu::FieldAccessor< float > vec, float const *RESTRICT u_in)
Definition at line 365 of file FieldAccessorsSinglePrecisionCUDA.cu.
References getLinearIndex(), and stream.
kernel_set_from_list() [1/2]
__global__ void walberla::lbm::accessor::Vector::kernel_set_from_list (gpu::FieldAccessor< double > vec, int const *RESTRICT const indices, double const *RESTRICT const values, uint length)
Definition at line 413 of file FieldAccessorsDoublePrecisionCUDA.cu.
References stream.
kernel_set_from_list() [2/2]
__global__ void walberla::lbm::accessor::Vector::kernel_set_from_list (gpu::FieldAccessor< float > vec, int const *RESTRICT const indices, float const *RESTRICT const values, uint length)
Definition at line 413 of file FieldAccessorsSinglePrecisionCUDA.cu.
References stream.
set() [1/8]
void walberla::lbm::accessor::Vector::set (GhostLayerField< double, uint_t{3u}> * vec_field, std::vector< double > const & values, CellInterval const & ci) inline
Definition at line 365 of file FieldAccessorsDoublePrecision.h.
set() [2/8]
void walberla::lbm::accessor::Vector::set (GhostLayerField< double, uint_t{3u}> * vec_field, Vector3< double > const & vec, Cell const & cell) inline
Definition at line 312 of file FieldAccessorsDoublePrecision.h.
set() [3/8]
void walberla::lbm::accessor::Vector::set (GhostLayerField< float, uint_t{3u}> * vec_field, std::vector< float > const & values, CellInterval const & ci) inline
Definition at line 365 of file FieldAccessorsSinglePrecision.h.
set() [4/8]
void walberla::lbm::accessor::Vector::set (GhostLayerField< float, uint_t{3u}> * vec_field, Vector3< float > const & vec, Cell const & cell) inline
Definition at line 312 of file FieldAccessorsSinglePrecision.h.
set() [5/8]
void walberla::lbm::accessor::Vector::set (gpu::GPUField< double > * vec_field, Vector3< double > const & vec, Cell const & cell)
Set value on a single cell.
Definition at line 451 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_set(), and stream.
set() [6/8]
void walberla::lbm::accessor::Vector::set (gpu::GPUField< double > * vec_field, std::vector< double > const & values, CellInterval const & ci)
Set values on a cell interval.
Definition at line 515 of file FieldAccessorsDoublePrecisionCUDA.cu.
References kernel_set(), and stream.
set() [7/8]
void walberla::lbm::accessor::Vector::set (gpu::GPUField< float > * vec_field, Vector3< float > const & vec, Cell const & cell)
Set value on a single cell.
Definition at line 451 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_set(), and stream.
set() [8/8]
void walberla::lbm::accessor::Vector::set (gpu::GPUField< float > * vec_field, std::vector< float > const & values, CellInterval const & ci)
Set values on a cell interval.
Definition at line 515 of file FieldAccessorsSinglePrecisionCUDA.cu.
References kernel_set(), and stream.
set_from_list() [1/2]
void walberla::lbm::accessor::Vector::set_from_list (gpu::GPUField< double > const * field, thrust::device_vector< int > const & indices, thrust::device_vector< double > const & values, uint gl)
Definition at line 527 of file FieldAccessorsDoublePrecisionCUDA.cu.
References calculate_dim_grid(), and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_velocities_at_pos().
set_from_list() [2/2]
void walberla::lbm::accessor::Vector::set_from_list (gpu::GPUField< float > const * field, thrust::device_vector< int > const & indices, thrust::device_vector< float > const & values, uint gl)
Definition at line 527 of file FieldAccessorsSinglePrecisionCUDA.cu.
References calculate_dim_grid(), and stream.