ESPResSo: walberla::lbm::accessor::Density Namespace Reference
walberla::lbm::accessor::Density Namespace Reference
Functions
double get (GhostLayerField< double, uint_t{19u}> const *pdf_field, double const density, Cell const &cell)
void set (GhostLayerField< double, uint_t{19u}> *pdf_field, double const rho_in, double const density, Cell const &cell)
std::vector< double > get (GhostLayerField< double, uint_t{19u}> const *pdf_field, double const density, CellInterval const &ci)
void set (GhostLayerField< double, uint_t{19u}> *pdf_field, std::vector< double > const &values, double const density, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< double > pdf, double *RESTRICT rho_out, double const density)
__global__ void kernel_set (gpu::FieldAccessor< double > pdf, double const *RESTRICT rho_in, double const density)
double get (gpu::GPUField< double > const *pdf_field, double const density, Cell const &cell)
std::vector< double > get (gpu::GPUField< double > const *pdf_field, double const density, CellInterval const &ci)
void set (gpu::GPUField< double > *pdf_field, double const rho, double const density, Cell const &cell)
void set (gpu::GPUField< double > *pdf_field, std::vector< double > const &values, double const density, CellInterval const &ci)
float get (GhostLayerField< float, uint_t{19u}> const *pdf_field, float const density, Cell const &cell)
void set (GhostLayerField< float, uint_t{19u}> *pdf_field, float const rho_in, float const density, Cell const &cell)
std::vector< float > get (GhostLayerField< float, uint_t{19u}> const *pdf_field, float const density, CellInterval const &ci)
void set (GhostLayerField< float, uint_t{19u}> *pdf_field, std::vector< float > const &values, float const density, CellInterval const &ci)
__global__ void kernel_get (gpu::FieldAccessor< float > pdf, float *RESTRICT rho_out, float const density)
__global__ void kernel_set (gpu::FieldAccessor< float > pdf, float const *RESTRICT rho_in, float const density)
float get (gpu::GPUField< float > const *pdf_field, float const density, Cell const &cell)
std::vector< float > get (gpu::GPUField< float > const *pdf_field, float const density, CellInterval const &ci)
void set (gpu::GPUField< float > *pdf_field, float const rho, float const density, Cell const &cell)
void set (gpu::GPUField< float > *pdf_field, std::vector< float > const &values, float const density, CellInterval const &ci)
Function Documentation
get() [1/8]
double walberla::lbm::accessor::Density::get (GhostLayerField< double, uint_t{19u}> const * pdf_field, double const density, Cell const & cell) inline
Definition at line 609 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::DensityVTKWriter< OutputType >::evaluate(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), and walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel().
get() [2/8]
std::vector< double > walberla::lbm::accessor::Density::get (GhostLayerField< double, uint_t{19u}> const * pdf_field, double const density, CellInterval const & ci) inline
Definition at line 684 of file FieldAccessorsDoublePrecision.h.
get() [3/8]
float walberla::lbm::accessor::Density::get (GhostLayerField< float, uint_t{19u}> const * pdf_field, float const density, Cell const & cell) inline
Definition at line 609 of file FieldAccessorsSinglePrecision.h.
get() [4/8]
std::vector< float > walberla::lbm::accessor::Density::get (GhostLayerField< float, uint_t{19u}> const * pdf_field, float const density, CellInterval const & ci) inline
Definition at line 684 of file FieldAccessorsSinglePrecision.h.
get() [5/8]
double walberla::lbm::accessor::Density::get (gpu::GPUField< double > const * pdf_field, double const density, Cell const & cell)
Definition at line 880 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_get(), and stream.
get() [6/8]
std::vector< double > walberla::lbm::accessor::Density::get (gpu::GPUField< double > const * pdf_field, double const density, CellInterval const & ci)
Definition at line 897 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_get(), and stream.
get() [7/8]
float walberla::lbm::accessor::Density::get (gpu::GPUField< float > const * pdf_field, float const density, Cell const & cell)
Definition at line 880 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_get(), and stream.
get() [8/8]
std::vector< float > walberla::lbm::accessor::Density::get (gpu::GPUField< float > const * pdf_field, float const density, CellInterval const & ci)
Definition at line 897 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_get(), and stream.
kernel_get() [1/2]
__global__ void walberla::lbm::accessor::Density::kernel_get (gpu::FieldAccessor< double > pdf, double *RESTRICT rho_out, double const density)
Definition at line 799 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, getLinearIndex(), and stream.
Referenced by get(), get(), get(), and get().
kernel_get() [2/2]
__global__ void walberla::lbm::accessor::Density::kernel_get (gpu::FieldAccessor< float > pdf, float *RESTRICT rho_out, float const density)
Definition at line 799 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, getLinearIndex(), and stream.
kernel_set() [1/2]
__global__ void walberla::lbm::accessor::Density::kernel_set (gpu::FieldAccessor< double > pdf, double const *RESTRICT rho_in, double const density)
Definition at line 835 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, getLinearIndex(), walberla::lbm::accessor::Equilibrium::kernel_set_device(), and stream.
Referenced by set(), set(), set(), and set().
kernel_set() [2/2]
__global__ void walberla::lbm::accessor::Density::kernel_set (gpu::FieldAccessor< float > pdf, float const *RESTRICT rho_in, float const density)
Definition at line 835 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, getLinearIndex(), walberla::lbm::accessor::Equilibrium::kernel_set_device(), and stream.
set() [1/8]
void walberla::lbm::accessor::Density::set (GhostLayerField< double, uint_t{19u}> * pdf_field, double const rho_in, double const density, Cell const & cell) inline
Definition at line 640 of file FieldAccessorsDoublePrecision.h.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density().
set() [2/8]
void walberla::lbm::accessor::Density::set (GhostLayerField< double, uint_t{19u}> * pdf_field, std::vector< double > const & values, double const density, CellInterval const & ci) inline
Definition at line 724 of file FieldAccessorsDoublePrecision.h.
set() [3/8]
void walberla::lbm::accessor::Density::set (GhostLayerField< float, uint_t{19u}> * pdf_field, float const rho_in, float const density, Cell const & cell) inline
Definition at line 640 of file FieldAccessorsSinglePrecision.h.
set() [4/8]
void walberla::lbm::accessor::Density::set (GhostLayerField< float, uint_t{19u}> * pdf_field, std::vector< float > const & values, float const density, CellInterval const & ci) inline
Definition at line 724 of file FieldAccessorsSinglePrecision.h.
set() [5/8]
void walberla::lbm::accessor::Density::set (gpu::GPUField< double > * pdf_field, double const rho, double const density, Cell const & cell)
Definition at line 913 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_set(), and stream.
set() [6/8]
void walberla::lbm::accessor::Density::set (gpu::GPUField< double > * pdf_field, std::vector< double > const & values, double const density, CellInterval const & ci)
Definition at line 928 of file FieldAccessorsDoublePrecisionCUDA.cu.
References density, kernel_set(), and stream.
set() [7/8]
void walberla::lbm::accessor::Density::set (gpu::GPUField< float > * pdf_field, float const rho, float const density, Cell const & cell)
Definition at line 913 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_set(), and stream.
set() [8/8]
void walberla::lbm::accessor::Density::set (gpu::GPUField< float > * pdf_field, std::vector< float > const & values, float const density, CellInterval const & ci)
Definition at line 928 of file FieldAccessorsSinglePrecisionCUDA.cu.
References density, kernel_set(), and stream.