ESPResSo: ScriptInterface::walberla Namespace Reference
ScriptInterface::walberla Namespace Reference
Classes
class CheckpointFile
Handle for a checkpoint file.
class EKBulkReaction
class EKContainer
class EKFFT
struct EKFieldSerializer
class EKIndexedReaction
class EKNone
class EKPoissonSolver
class EKPoissonSolverNode
class EKPoissonSolverSlice
class EKPoissonVTKHandle
class EKReactant
class EKReaction
class EKReactions
class EKSpecies
class EKSpeciesNode
class EKSpeciesSlice
class EKVTKHandle
class LatticeModel
class LatticeSlice
class LatticeWalberla
struct LBFieldSerializer
class LBFluid
class LBFluidNode
class LBFluidSlice
class LBVTKHandle
class VTKHandleBase
Typedefs
using DensityBoundaryType = std::optional< double >
using FluxBoundaryType = std::optional< Utils::Vector3d >
using VelocityBounceBackType = std::optional< Utils::Vector3d >
Enumerations
enum class CptMode : int { ascii = 0 , binary = 1 , unit_test_runtime_error = -1 , unit_test_ios_failure = -2 }
Functions
void ek_throw_if_expired (std::optional< ResourceObserver > const &mpi_obs)
static bool is_boundary_all_reduce (boost::mpi::communicator const &comm, std::optional< bool > const &is_boundary)
void initialize (Utils::Factory< ObjectHandle > *om)
auto gather_slices_topology (boost::mpi::communicator const &comm, Utils::Vector3i const &local_lower_corner, Utils::Vector3i const &local_upper_corner)
void lb_throw_if_expired (std::optional< ResourceObserver > const &mpi_obs)
static bool is_boundary_all_reduce (boost::mpi::communicator const &comm, std::optional< bool > const &is_boundary)
void unit_test_handle (int mode)
Inject code for unit tests.
template<typename F1 , typename F2 , typename F3 >
void load_checkpoint_common (Context const &context, std::string const classname, std::filesystem::path const &path, int mode, F1 const read_metadata, F2 const read_data, F3 const on_success)
template<typename F1 , typename F2 , typename F3 >
void save_checkpoint_common (Context const &context, std::string const classname, std::filesystem::path const &path, int mode, F1 const write_metadata, F2 const write_data, F3 const on_failure)
Typedef Documentation
DensityBoundaryType
using ScriptInterface::walberla::DensityBoundaryType = typedef std::optional<double>
Definition at line 50 of file EKSpeciesSlice.hpp.
FluxBoundaryType
using ScriptInterface::walberla::FluxBoundaryType = typedef std::optional<Utils::Vector3d>
Definition at line 51 of file EKSpeciesSlice.hpp.
VelocityBounceBackType
using ScriptInterface::walberla::VelocityBounceBackType = typedef std::optional<Utils::Vector3d>
Definition at line 50 of file LBFluidSlice.hpp.
Enumeration Type Documentation
CptMode
enum class ScriptInterface::walberla::CptMode : int strong
Enumerator
ascii
binary
unit_test_runtime_error
unit_test_ios_failure
Definition at line 43 of file WalberlaCheckpoint.hpp.
Function Documentation
ek_throw_if_expired()
void ScriptInterface::walberla::ek_throw_if_expired (std::optional< ResourceObserver > const & mpi_obs) inline
Definition at line 57 of file EKSpecies.hpp.
References stream.
Referenced by ScriptInterface::walberla::EKContainer::add_in_core(), ScriptInterface::walberla::EKSpeciesNode::do_call_method(), and ScriptInterface::walberla::EKSpeciesSlice::do_call_method().
gather_slices_topology()
auto ScriptInterface::walberla::gather_slices_topology (boost::mpi::communicator const & comm, Utils::Vector3i const & local_lower_corner, Utils::Vector3i const & local_upper_corner) inline
Definition at line 100 of file LatticeSlice.impl.hpp.
References stream.
Referenced by ScriptInterface::walberla::LatticeSlice< FieldSerializer >::scatter_3d().
initialize()
void ScriptInterface::walberla::initialize (Utils::Factory< ObjectHandle > * om)
Definition at line 56 of file walberla/initialize.cpp.
References stream.
Referenced by ScriptInterface::initialize().
is_boundary_all_reduce() [1/2]
static bool ScriptInterface::walberla::is_boundary_all_reduce (boost::mpi::communicator const & comm, std::optional< bool > const & is_boundary) static
Definition at line 46 of file EKSpeciesNode.cpp.
Referenced by ScriptInterface::walberla::EKSpeciesNode::do_call_method(), and ScriptInterface::walberla::LBFluidNode::do_call_method().
is_boundary_all_reduce() [2/2]
static bool ScriptInterface::walberla::is_boundary_all_reduce (boost::mpi::communicator const & comm, std::optional< bool > const & is_boundary) static
Definition at line 41 of file LBFluidNode.cpp.
lb_throw_if_expired()
void ScriptInterface::walberla::lb_throw_if_expired (std::optional< ResourceObserver > const & mpi_obs) inline
Definition at line 63 of file LBFluid.hpp.
References stream.
Referenced by ScriptInterface::walberla::LBFluid::do_call_method(), ScriptInterface::walberla::LBFluidNode::do_call_method(), and ScriptInterface::walberla::LBFluidSlice::do_call_method().
load_checkpoint_common()
template<typename F1 , typename F2 , typename F3 > void ScriptInterface::walberla::load_checkpoint_common (Context const & context, std::string const classname, std::filesystem::path const & path, int mode, F1 const read_metadata, F2 const read_data, F3 const on_success)
Definition at line 144 of file WalberlaCheckpoint.hpp.
References binary, ScriptInterface::Context::get_comm(), ScriptInterface::Context::is_head_node(), and stream.
save_checkpoint_common()
template<typename F1 , typename F2 , typename F3 > void ScriptInterface::walberla::save_checkpoint_common (Context const & context, std::string const classname, std::filesystem::path const & path, int mode, F1 const write_metadata, F2 const write_data, F3 const on_failure)
Definition at line 202 of file WalberlaCheckpoint.hpp.
References binary, ScriptInterface::Context::get_comm(), ScriptInterface::Context::is_head_node(), and stream.
unit_test_handle()
void ScriptInterface::walberla::unit_test_handle (int mode) inline
Inject code for unit tests.
Definition at line 51 of file WalberlaCheckpoint.hpp.
References ascii, binary, stream, unit_test_ios_failure, and unit_test_runtime_error.