ESPResSo: ScriptInterface Namespace Reference
ScriptInterface Namespace Reference
Namespaces
namespace Accumulators
namespace Analysis
namespace BondBreakage
namespace CellSystem
namespace ClusterAnalysis
namespace CodeInfo
namespace CollisionDetection
namespace Constraints
namespace Coulomb
namespace Dipoles
namespace Galilei
namespace Integrators
namespace Interactions
namespace LeesEdwards
namespace Math
namespace MPIIO
namespace Observables
namespace PairCriteria
namespace Particles
namespace Profiler
namespace ReactionMethods
namespace Scafacos
namespace Shapes
namespace System
namespace Thermostat
namespace walberla
namespace Writer
Classes
struct AutoParameter
Description and getter/setter for a parameter.
class AutoParameters
Bind parameters in the script interface.
class Context
Context of an object handle.
class ContextManager
Manage object contexts.
struct Exception
class GlobalContext
Global synchronizing context.
class LatticeIndices
Interface to carry out simple operations on lattice indices.
class LocalContext
Trivial context.
class None
Type to indicate no value in Variant.
class ObjectHandle
Base class for interface handles.
class ObjectList
Owning list of object handles.
class ObjectMap
Owning map of object handles.
struct ObjectState
State of an object ready for serialization.
struct PackVisitor
Visitor that converts a Variant to a PackedVariant.
class ParallelExceptionHandler
Handle exceptions thrown in MPI parallel code.
struct UnpackVisitor
Visitor that converts a PackedVariant to a Variant.
Typedefs
template<template< typename... > class Container, typename ManagedType , class BaseType , class = std::enable_if_t<std::is_base_of_v<ObjectHandle, ManagedType>>>
using ObjectContainer = std::conditional_t< std::is_same_v< BaseType, ObjectHandle >, AutoParameters< Container< ManagedType, BaseType >, BaseType >, BaseType >
Base class for containers whose BaseType might be a full specialization of AutoParameters.
using ObjectId = std::size_t
using PackedVariant = boost::make_recursive_variant< None, bool, int, std::size_t, double, std::string, ObjectId, Utils::Vector3b, Utils::Vector3i, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::vector< int >, std::vector< double >, std::vector< boost::recursive_variant_ >, std::unordered_map< int, boost::recursive_variant_ >, std::unordered_map< std::string, boost::recursive_variant_ > >::type
Packed version of Variant.
using PackedMap = std::vector< std::pair< std::string, PackedVariant > >
using ObjectRef = std::shared_ptr< ObjectHandle >
using Variant = boost::make_recursive_variant< None, bool, int, std::size_t, double, std::string, ObjectRef, Utils::Vector3b, Utils::Vector3i, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::vector< int >, std::vector< double >, std::vector< boost::recursive_variant_ >, std::unordered_map< int, boost::recursive_variant_ >, std::unordered_map< std::string, boost::recursive_variant_ > >::type
Possible types for parameters.
using VariantMap = std::unordered_map< std::string, Variant >
Functions
template<typename T >
T mpi_reduce_sum (boost::mpi::communicator const &comm, T const &result)
Reduce object by sum on the head node.
template<typename T >
T get_value (Variant const &v)
Extract value of specific type T from a Variant.
template<typename T >
T get_value (VariantMap const &vals, std::string const &name)
Get a value from a VariantMap by name, or throw if it does not exist or is not convertible to the target type.
template<typename T >
T get_value_or (VariantMap const &vals, std::string const &name, T const &default_)
Get a value from a VariantMap by name, or return a default value if it does not exist.
template<typename T , typename... Types, typename... ArgNames>
std::shared_ptr< T > make_shared_from_args (VariantMap const &vals, ArgNames &&...args)
Make a new std::shared_ptr<T> with arguments extracted from a VariantMap.
template<typename T >
void set_from_args (T &dst, VariantMap const &vals, const char *name)
void initialize (Utils::Factory< ObjectHandle > *f)
ObjectId object_id (const ObjectHandle *p)
Id for object.
PackedVariant pack (const Variant &v)
Transform a Variant to a PackedVariant.
Variant unpack (const PackedVariant &v, std::unordered_map< ObjectId, ObjectRef > const &objects)
Unpack a PackedVariant.
PackedMap pack (const VariantMap &v)
Pack a VariantMap.
VariantMap unpack (const PackedMap &v, std::unordered_map< ObjectId, ObjectRef > const &objects)
Unpack a PackedMap.
template<typename T >
Variant make_variant (const T &x)
Make a Variant from argument.
template<typename K , typename V >
auto make_unordered_map_of_variants (std::unordered_map< K, V > const &v)
template<typename T >
auto make_vector_of_variants (std::vector< T > const &v)
template<class T >
bool is_type (Variant const &v)
Check is a Variant holds a specific type.
bool is_none (Variant const &v)
Variables
constexpr const None none {}
None-"literal".
Typedef Documentation
ObjectContainer
template<template< typename... > class Container, typename ManagedType , class BaseType , class = std::enable_if_t<std::is_base_of_v<ObjectHandle, ManagedType>>> using ScriptInterface::ObjectContainer = typedef std::conditional_t< std::is_same_v<BaseType, ObjectHandle>, AutoParameters<Container<ManagedType, BaseType>, BaseType>, BaseType>
Base class for containers whose BaseType might be a full specialization of AutoParameters.
Definition at line 36 of file ObjectContainer.hpp.
ObjectId
using ScriptInterface::ObjectId = typedef std::size_t
Definition at line 33 of file packed_variant.hpp.
ObjectRef
using ScriptInterface::ObjectRef = typedef std::shared_ptr<ObjectHandle>
Definition at line 46 of file Variant.hpp.
PackedMap
using ScriptInterface::PackedMap = typedef std::vector<std::pair<std::string, PackedVariant> >
Definition at line 63 of file packed_variant.hpp.
PackedVariant
using ScriptInterface::PackedVariant = typedef boost::make_recursive_variant< None, bool, int, std::size_t, double, std::string, ObjectId, Utils::Vector3b, Utils::Vector3i, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::vector<int>, std::vector<double>, std::vector<boost::recursive_variant_>, std::unordered_map<int, boost::recursive_variant_>, std::unordered_map<std::string, boost::recursive_variant_> >::type
Packed version of Variant.
When packing variants by PackVisitor, objects of type ObjectRef are packed as ObjectId. Other than that, all other types allowed in Variant must appear here.
Definition at line 55 of file packed_variant.hpp.
Variant
using ScriptInterface::Variant = typedef boost::make_recursive_variant< None, bool, int, std::size_t, double, std::string, ObjectRef, Utils::Vector3b, Utils::Vector3i, Utils::Vector2d, Utils::Vector3d, Utils::Vector4d, std::vector<int>, std::vector<double>, std::vector<boost::recursive_variant_>, std::unordered_map<int, boost::recursive_variant_>, std::unordered_map<std::string, boost::recursive_variant_> >::type
Possible types for parameters.
The visitors and packing functions need to be adapted accordingly when extending this variant with new types. For the exact details, see commit b48ab62. The number of types is limited by macro BOOST_MPL_LIMIT_LIST_SIZE (defaults to 20).
Definition at line 61 of file Variant.hpp.
VariantMap
using ScriptInterface::VariantMap = typedef std::unordered_map<std::string, Variant>
Definition at line 69 of file Variant.hpp.
Function Documentation
get_value() [1/2]
template<typename T > T ScriptInterface::get_value (Variant const & v)
Extract value of specific type T from a Variant.
This is a wrapper around boost::get that allows us to customize the behavior for different types. This is needed e.g. to deal with containers whose elements have mixed types that are implicitly convertible to a requested type.
Definition at line 400 of file get_value.hpp.
Referenced by ScriptInterface::Accumulators::AccumulatorBase::AccumulatorBase(), ScriptInterface::Accumulators::AutoUpdateAccumulators::add_in_core(), ScriptInterface::Constraints::Constraints::add_in_core(), ScriptInterface::Shapes::Union::add_in_core(), ScriptInterface::walberla::EKContainer::add_in_core(), ScriptInterface::walberla::EKReactions::add_in_core(), ScriptInterface::AutoParameters< Derived, Base >::add_parameters(), ScriptInterface::Interactions::NonBondedInteractionHandle::attach(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::attach(), ScriptInterface::Particles::ParticleHandle::attach(), ScriptInterface::Particles::ParticleSlice::attach(), ScriptInterface::walberla::VTKHandleBase< Field >::attach_to_lattice(), ScriptInterface::Particles::auto_exclusions(), ScriptInterface::AutoParameter::AutoParameter(), ScriptInterface::AutoParameter::AutoParameter(), ScriptInterface::AutoParameter::AutoParameter(), ScriptInterface::AutoParameter::AutoParameter(), ScriptInterface::CollisionDetection::Protocol::bind_bonded_ias(), ScriptInterface::System::Leaf::bind_system(), ScriptInterface::Constraints::ShapeBasedConstraint::bind_system(), ScriptInterface::Particles::bitfield_from_flag(), ScriptInterface::PairCriteria::BondCriterion::BondCriterion(), ScriptInterface::walberla::EKReaction::calculate_bulk_conversion_factor(), ScriptInterface::ReactionMethods::ReactionAlgorithm::calculate_factorial_expression(), ScriptInterface::ReactionMethods::ConstantpHEnsemble::calculate_factorial_expression(), ScriptInterface::ObjectHandle::call_method(), ScriptInterface::Observables::ProfileObservable< CoreObs >::call_method(), ScriptInterface::CellSystem::CellSystem::CellSystem(), ScriptInterface::CodeInfo::check_features(), ScriptInterface::Analysis::check_topology(), ScriptInterface::walberla::CheckpointFile::CheckpointFile(), ScriptInterface::ObjectList< ManagedType, BaseType >::clear(), ScriptInterface::ClusterAnalysis::ClusterStructure::ClusterStructure(), ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), ScriptInterface::Galilei::ComFixed::ComFixed(), ScriptInterface::CellSystem::CellSystem::configure(), ScriptInterface::CellSystem::CellSystem::configure(), ScriptInterface::ReactionMethods::ConstantpHEnsemble::ConstantpHEnsemble(), ScriptInterface::Coulomb::Container::Container(), ScriptInterface::Dipoles::Container::Container(), ScriptInterface::ContextManager::ContextManager(), ScriptInterface::Coulomb::CoulombP3M< Architecture >::CoulombP3M(), ScriptInterface::Coulomb::CoulombScafacos::CoulombScafacos(), ScriptInterface::System::CudaInitHandle::CudaInitHandle(), ScriptInterface::ContextManager::deserialize(), ScriptInterface::walberla::EKFieldSerializer::deserialize(), ScriptInterface::walberla::LBFieldSerializer::deserialize(), ScriptInterface::Scafacos::deserialize_parameters(), ScriptInterface::System::Leaf::detach_system(), ScriptInterface::Dipoles::DipolarP3M< Architecture >::DipolarP3M(), ScriptInterface::PairCriteria::DistanceCriterion::DistanceCriterion(), ScriptInterface::Writer::H5md::do_call_method(), ScriptInterface::Constraints::ExternalField< Coupling, Field >::do_call_method(), ScriptInterface::Constraints::ExternalPotential< Coupling, Field >::do_call_method(), ScriptInterface::Accumulators::AccumulatorBase::do_call_method(), ScriptInterface::Accumulators::ContactTimes::do_call_method(), ScriptInterface::Accumulators::Correlator::do_call_method(), ScriptInterface::Accumulators::MeanVarianceCalculator::do_call_method(), ScriptInterface::Accumulators::TimeSeries::do_call_method(), ScriptInterface::ClusterAnalysis::Cluster::do_call_method(), ScriptInterface::ClusterAnalysis::ClusterStructure::do_call_method(), ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method(), ScriptInterface::Observables::CylindricalLBProfileObservable< CoreCylLBObs >::do_call_method(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_call_method(), ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_call_method(), ScriptInterface::Observables::Observable::do_call_method(), ScriptInterface::Observables::PidProfileObservable< CoreObs >::do_call_method(), ScriptInterface::PairCriteria::PairCriterion::do_call_method(), ScriptInterface::Profiler::Caliper::do_call_method(), ScriptInterface::walberla::EKContainer::do_call_method(), ScriptInterface::walberla::EKIndexedReaction::do_call_method(), ScriptInterface::walberla::EKSpecies::do_call_method(), ScriptInterface::Interactions::NonBondedInteractions::do_call_method(), ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), ScriptInterface::Analysis::Analysis::do_call_method(), ScriptInterface::Analysis::ObservableStat::do_call_method(), ScriptInterface::BondBreakage::BreakageSpecs::do_call_method(), ScriptInterface::CodeInfo::CodeInfo::do_call_method(), ScriptInterface::CodeInfo::CodeVersion::do_call_method(), ScriptInterface::MPIIO::MPIIOScript::do_call_method(), ScriptInterface::Particles::Polymer::do_call_method(), ScriptInterface::System::CudaInitHandle::do_call_method(), ScriptInterface::System::System::do_call_method(), ScriptInterface::CellSystem::CellSystem::do_call_method(), ScriptInterface::Coulomb::Actor< SIClass, CoreClass >::do_call_method(), ScriptInterface::Coulomb::CoulombScafacos::do_call_method(), ScriptInterface::Coulomb::ICCStar::do_call_method(), ScriptInterface::Galilei::Galilei::do_call_method(), ScriptInterface::Interactions::BondedInteraction::do_call_method(), ScriptInterface::Interactions::BondedInteractions::do_call_method(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_call_method(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_call_method(), ScriptInterface::LeesEdwards::LeesEdwards::do_call_method(), ScriptInterface::Dipoles::Actor< SIClass, CoreClass >::do_call_method(), ScriptInterface::Particles::ParticleList::do_call_method(), ScriptInterface::Particles::ParticleSlice::do_call_method(), ScriptInterface::ReactionMethods::ReactionAlgorithm::do_call_method(), ScriptInterface::ReactionMethods::WidomInsertion::do_call_method(), ScriptInterface::Shapes::Shape::do_call_method(), ScriptInterface::Thermostat::Thermostat::do_call_method(), ScriptInterface::walberla::EKSpeciesNode::do_call_method(), ScriptInterface::walberla::EKSpeciesSlice::do_call_method(), ScriptInterface::walberla::LBFluid::do_call_method(), ScriptInterface::walberla::LBFluidNode::do_call_method(), ScriptInterface::walberla::LBFluidSlice::do_call_method(), ScriptInterface::Accumulators::Correlator::do_construct(), ScriptInterface::Constraints::ExternalField< Coupling, Field >::do_construct(), ScriptInterface::Constraints::ExternalPotential< Coupling, Field >::do_construct(), ScriptInterface::walberla::EKFFT::do_construct(), ScriptInterface::walberla::EKNone::do_construct(), ScriptInterface::walberla::EKReactant::do_construct(), ScriptInterface::walberla::EKBulkReaction::do_construct(), ScriptInterface::walberla::EKIndexedReaction::do_construct(), ScriptInterface::walberla::LatticeWalberla::do_construct(), ScriptInterface::MPIIO::MPIIOScript::do_construct(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::do_construct(), ScriptInterface::Accumulators::ContactTimes::do_construct(), ScriptInterface::Accumulators::MeanVarianceCalculator::do_construct(), ScriptInterface::Accumulators::TimeSeries::do_construct(), ScriptInterface::ClusterAnalysis::ClusterStructure::do_construct(), ScriptInterface::Constraints::Constraints::do_construct(), ScriptInterface::Coulomb::CoulombMMM1D::do_construct(), ScriptInterface::Coulomb::CoulombP3M< Architecture >::do_construct(), ScriptInterface::Coulomb::CoulombScafacos::do_construct(), ScriptInterface::Coulomb::DebyeHueckel::do_construct(), ScriptInterface::Coulomb::ElectrostaticLayerCorrection::do_construct(), ScriptInterface::Coulomb::ICCStar::do_construct(), ScriptInterface::Coulomb::ReactionField::do_construct(), ScriptInterface::Writer::H5md::do_construct(), ScriptInterface::Integrators::SteepestDescent::do_construct(), ScriptInterface::Integrators::StokesianDynamics::do_construct(), ScriptInterface::Integrators::VelocityVerletIsoNPT::do_construct(), ScriptInterface::Interactions::NonBondedInteractionHandle::do_construct(), ScriptInterface::Interactions::NonBondedInteractions::do_construct(), ScriptInterface::Dipoles::DipolarDirectSum::do_construct(), ScriptInterface::Dipoles::DipolarDirectSumGpu::do_construct(), ScriptInterface::Dipoles::DipolarLayerCorrection::do_construct(), ScriptInterface::Dipoles::DipolarP3M< Architecture >::do_construct(), ScriptInterface::Dipoles::DipolarScafacos::do_construct(), ScriptInterface::Math::CylindricalTransformationParameters::do_construct(), ScriptInterface::ObjectList< ManagedType, BaseType >::do_construct(), ScriptInterface::Observables::CylindricalLBProfileObservable< CoreCylLBObs >::do_construct(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct(), ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_construct(), ScriptInterface::Observables::PairwiseDistances< CoreObs >::do_construct(), ScriptInterface::Observables::PidObservable< CorePidObs >::do_construct(), ScriptInterface::Observables::PidProfileObservable< CoreObs >::do_construct(), ScriptInterface::Observables::RDF::do_construct(), ScriptInterface::Particles::ParticleSlice::do_construct(), ScriptInterface::ReactionMethods::ConstantpHEnsemble::do_construct(), ScriptInterface::ReactionMethods::ReactionEnsemble::do_construct(), ScriptInterface::ReactionMethods::SingleReaction::do_construct(), ScriptInterface::ReactionMethods::WidomInsertion::do_construct(), ScriptInterface::Shapes::HollowConicalFrustum::do_construct(), ScriptInterface::System::System::do_construct(), ScriptInterface::Thermostat::Interface< CoreClass >::do_construct(), ScriptInterface::walberla::EKContainer::do_construct(), ScriptInterface::walberla::EKSpecies::do_construct(), ScriptInterface::walberla::EKSpeciesNode::do_construct(), ScriptInterface::walberla::EKSpeciesSlice::do_construct(), ScriptInterface::walberla::LBFluid::do_construct(), ScriptInterface::walberla::LBFluidNode::do_construct(), ScriptInterface::walberla::LBFluidSlice::do_construct(), ScriptInterface::walberla::VTKHandleBase< Field >::do_construct(), ScriptInterface::ObjectList< ManagedType, BaseType >::do_destruct(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_destruct(), ScriptInterface::CollisionDetection::BindAtPointOfCollision::do_initialize(), ScriptInterface::CollisionDetection::BindCenters::do_initialize(), ScriptInterface::CollisionDetection::GlueToSurface::do_initialize(), ScriptInterface::walberla::EKBulkReaction::EKBulkReaction(), ScriptInterface::walberla::EKFFT::EKFFT(), ScriptInterface::walberla::EKIndexedReaction::EKIndexedReaction(), ScriptInterface::walberla::EKSpecies::EKSpecies(), ScriptInterface::Shapes::Ellipsoid::Ellipsoid(), ScriptInterface::PairCriteria::EnergyCriterion::EnergyCriterion(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::erase(), ScriptInterface::BondBreakage::BreakageSpecs::erase_in_core(), ScriptInterface::Interactions::BondedInteractions::erase_in_core(), ScriptInterface::Particles::error_msg(), ScriptInterface::Thermostat::Interface< CoreClass >::extend_parameters(), ScriptInterface::Thermostat::Langevin::extend_parameters(), ScriptInterface::Thermostat::Brownian::extend_parameters(), ScriptInterface::Thermostat::Interface< CoreClass >::extract_kT(), ScriptInterface::Thermostat::LBThermostat::extract_kT(), ScriptInterface::CollisionDetection::Protocol::find_bond_id(), ScriptInterface::walberla::gather_slices_topology(), ScriptInterface::walberla::EKReaction::get_agrid(), ScriptInterface::CollisionDetection::Protocol::get_bond_variant_by_id(), ScriptInterface::Accumulators::AccumulatorBase::get_core_system_pointer(), ScriptInterface::CodeInfo::get_feature_set(), ScriptInterface::CodeInfo::get_feature_vector(), ScriptInterface::Particles::get_gamma_safe(), ScriptInterface::Interactions::NonBondedInteractions::get_internal_state(), ScriptInterface::ReactionMethods::ReactionAlgorithm::get_internal_state(), ScriptInterface::System::System::get_internal_state(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::get_key(), ScriptInterface::LatticeIndices::get_mapped_index(), ScriptInterface::Thermostat::Interface< CoreClass >::get_member_handle(), ScriptInterface::walberla::VTKHandleBase< Field >::get_obs_map(), ScriptInterface::ObjectHandle::get_parameters(), ScriptInterface::Particles::get_quaternion_safe(), ScriptInterface::ReactionMethods::ReactionAlgorithm::get_reaction_index(), ScriptInterface::Particles::get_real_particle(), ScriptInterface::Thermostat::Interface< CoreClass >::get_required_parameters(), ScriptInterface::Thermostat::Langevin::get_required_parameters(), ScriptInterface::Thermostat::Brownian::get_required_parameters(), ScriptInterface::Thermostat::IsotropicNpt::get_required_parameters(), ScriptInterface::Thermostat::LBThermostat::get_required_parameters(), ScriptInterface::Thermostat::Interface< CoreClass >::get_rng_counter(), ScriptInterface::Thermostat::Interface< CoreClass >::get_rng_seed(), ScriptInterface::Analysis::get_summary(), ScriptInterface::System::Leaf::get_system(), ScriptInterface::System::Leaf::get_system(), ScriptInterface::Interactions::BondedInteraction::get_valid_parameters(), ScriptInterface::ObjectHandle::get_valid_parameters(), get_value(), get_value_or(), ScriptInterface::CodeInfo::get_version_tuple_as_string(), ScriptInterface::GlobalContext::GlobalContext(), ScriptInterface::Accumulators::AutoUpdateAccumulators::has_in_core(), ScriptInterface::Constraints::Constraints::has_in_core(), ScriptInterface::Shapes::Union::has_in_core(), ScriptInterface::walberla::EKContainer::has_in_core(), ScriptInterface::walberla::EKReactions::has_in_core(), ScriptInterface::Shapes::HollowConicalFrustum::HollowConicalFrustum(), ScriptInterface::Constraints::HomogeneousMagneticField::HomogeneousMagneticField(), ScriptInterface::Accumulators::initialize(), ScriptInterface::Analysis::initialize(), ScriptInterface::CellSystem::initialize(), ScriptInterface::ClusterAnalysis::initialize(), ScriptInterface::CodeInfo::initialize(), ScriptInterface::CollisionDetection::initialize(), ScriptInterface::Constraints::initialize(), ScriptInterface::Coulomb::initialize(), ScriptInterface::Galilei::initialize(), ScriptInterface::Writer::initialize(), ScriptInterface::Integrators::initialize(), ScriptInterface::Interactions::initialize(), ScriptInterface::LeesEdwards::initialize(), ScriptInterface::Dipoles::initialize(), ScriptInterface::Math::initialize(), ScriptInterface::MPIIO::initialize(), ScriptInterface::PairCriteria::initialize(), ScriptInterface::Particles::initialize(), ScriptInterface::Profiler::initialize(), ScriptInterface::ReactionMethods::initialize(), ScriptInterface::System::initialize(), ScriptInterface::Thermostat::initialize(), ScriptInterface::walberla::initialize(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::insert(), ScriptInterface::BondBreakage::BreakageSpecs::insert_in_core(), ScriptInterface::Interactions::BondedInteractions::insert_in_core(), ScriptInterface::Interactions::BondedInteractions::insert_in_core(), ScriptInterface::Integrators::Integrator::integrate(), ScriptInterface::Integrators::SteepestDescent::integrate(), ScriptInterface::Integrators::IntegratorHandle::IntegratorHandle(), ScriptInterface::Thermostat::Interface< CoreClass >::Interface(), ScriptInterface::Thermostat::Interface< CoreClass >::invalid_rng_state(), ScriptInterface::Thermostat::LBThermostat::invalid_rng_state(), ScriptInterface::LatticeIndices::is_index_valid(), is_none(), ScriptInterface::walberla::LBFluid::LBFluid(), ScriptInterface::Thermostat::LBThermostat::LBThermostat(), ScriptInterface::LeesEdwards::LeesEdwards::LeesEdwards(), ScriptInterface::walberla::load_checkpoint_common(), ScriptInterface::Thermostat::Interface< CoreClass >::make_autogamma(), ScriptInterface::Thermostat::Interface< CoreClass >::make_autoparameter(), ScriptInterface::Thermostat::Thermostat::make_autoparameter(), ScriptInterface::walberla::EKReaction::make_instance(), ScriptInterface::walberla::EKSpecies::make_instance(), ScriptInterface::walberla::LBFluidCPU::make_instance(), ScriptInterface::walberla::LBFluidGPU::make_instance(), ScriptInterface::Interactions::InteractionWCA::make_new_instance(), ScriptInterface::Interactions::InteractionLJ::make_new_instance(), ScriptInterface::Interactions::InteractionLJGen::make_new_instance(), ScriptInterface::Interactions::InteractionLJcos::make_new_instance(), ScriptInterface::Interactions::InteractionLJcos2::make_new_instance(), ScriptInterface::Interactions::InteractionHertzian::make_new_instance(), ScriptInterface::Interactions::InteractionGaussian::make_new_instance(), ScriptInterface::Interactions::InteractionBMHTF::make_new_instance(), ScriptInterface::Interactions::InteractionMorse::make_new_instance(), ScriptInterface::Interactions::InteractionBuckingham::make_new_instance(), ScriptInterface::Interactions::InteractionSoftSphere::make_new_instance(), ScriptInterface::Interactions::InteractionHat::make_new_instance(), ScriptInterface::Interactions::InteractionGayBerne::make_new_instance(), ScriptInterface::Interactions::InteractionTabulated::make_new_instance(), ScriptInterface::Interactions::InteractionDPD::make_new_instance(), ScriptInterface::Interactions::InteractionThole::make_new_instance(), ScriptInterface::Interactions::InteractionSmoothStep::make_new_instance(), ScriptInterface::ContextManager::make_shared(), ScriptInterface::GlobalContext::make_shared(), ScriptInterface::LocalContext::make_shared(), make_shared_from_args(), make_unordered_map_of_variants(), make_vector_of_variants(), mpi_reduce_sum(), ScriptInterface::GlobalContext::name(), ScriptInterface::LocalContext::name(), ScriptInterface::Interactions::NonBondedInteractionHandle::NonBondedInteractionHandle(), ScriptInterface::GlobalContext::notify_call_method(), ScriptInterface::GlobalContext::notify_set_parameter(), ScriptInterface::Coulomb::Container::on_bind_system(), ScriptInterface::Dipoles::Container::on_bind_system(), ScriptInterface::Accumulators::AutoUpdateAccumulators::on_bind_system(), ScriptInterface::BondBreakage::BreakageSpecs::on_bind_system(), ScriptInterface::CellSystem::CellSystem::on_bind_system(), ScriptInterface::CollisionDetection::CollisionDetection::on_bind_system(), ScriptInterface::Constraints::Constraints::on_bind_system(), ScriptInterface::Galilei::ComFixed::on_bind_system(), ScriptInterface::Galilei::Galilei::on_bind_system(), ScriptInterface::Integrators::IntegratorHandle::on_bind_system(), ScriptInterface::Interactions::BondedInteractions::on_bind_system(), ScriptInterface::Interactions::NonBondedInteractions::on_bind_system(), ScriptInterface::LeesEdwards::LeesEdwards::on_bind_system(), ScriptInterface::Thermostat::Interface< CoreClass >::on_bind_system(), ScriptInterface::Thermostat::Thermostat::on_bind_system(), ScriptInterface::Thermostat::Interface< CoreClass >::on_detach_system(), ScriptInterface::Interactions::NonBondedInteractionHandle::on_non_bonded_ia_change(), ScriptInterface::PackVisitor::operator()(), ScriptInterface::UnpackVisitor::operator()(), ScriptInterface::PackVisitor::operator()(), ScriptInterface::UnpackVisitor::operator()(), ScriptInterface::PackVisitor::operator()(), ScriptInterface::Scafacos::GetParameterList::operator()(), ScriptInterface::Scafacos::ConvertToStringVector::operator()(), ScriptInterface::Scafacos::GetParameterList::operator()(), ScriptInterface::Scafacos::ConvertToStringVector::operator()(), ScriptInterface::Scafacos::ConvertToStringVector::operator()(), ScriptInterface::PackVisitor::operator()(), ScriptInterface::UnpackVisitor::operator()(), ScriptInterface::Scafacos::GetParameterList::operator()(), ScriptInterface::Interactions::BondedInteraction::operator==(), pack(), ScriptInterface::ParallelExceptionHandler::parallel_try_catch(), ScriptInterface::GlobalContext::parallel_try_catch(), ScriptInterface::LocalContext::parallel_try_catch(), ScriptInterface::Particles::particle_checks(), ScriptInterface::Observables::ProfileObservable< CoreObs >::ProfileObservable(), ScriptInterface::ReactionMethods::ReactionAlgorithm::ReactionAlgorithm(), ScriptInterface::walberla::CheckpointFile::read(), ScriptInterface::Thermostat::Interface< CoreClass >::release_lock(), ScriptInterface::ObjectList< ManagedType, BaseType >::remove(), ScriptInterface::Accumulators::AutoUpdateAccumulators::remove_in_core(), ScriptInterface::Constraints::Constraints::remove_in_core(), ScriptInterface::Shapes::Union::remove_in_core(), ScriptInterface::walberla::EKContainer::remove_in_core(), ScriptInterface::walberla::EKReactions::remove_in_core(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::restore_from_checkpoint(), ScriptInterface::System::rotate_system(), ScriptInterface::Thermostat::Interface< CoreClass >::sanity_checks_positive(), ScriptInterface::walberla::save_checkpoint_common(), ScriptInterface::walberla::LatticeSlice< FieldSerializer >::scatter_3d(), ScriptInterface::ObjectHandle::serialize(), ScriptInterface::ObjectState::serialize(), ScriptInterface::ContextManager::serialize(), ScriptInterface::walberla::EKFieldSerializer::serialize(), ScriptInterface::walberla::LBFieldSerializer::serialize(), ScriptInterface::AutoParameters< Derived, Base >::serialize_parameters(), ScriptInterface::Scafacos::serialize_parameters(), ScriptInterface::System::set_bonds(), ScriptInterface::Coulomb::Actor< SIClass, CoreClass >::set_charge_neutrality_tolerance(), ScriptInterface::Context::set_context(), set_from_args(), ScriptInterface::Accumulators::AccumulatorBase::set_internal_state(), ScriptInterface::Interactions::NonBondedInteractions::set_internal_state(), ScriptInterface::ObjectHandle::set_parameter(), ScriptInterface::ClusterAnalysis::Cluster::set_particle_list(), ScriptInterface::Thermostat::Interface< CoreClass >::set_rng_counter(), ScriptInterface::Thermostat::Interface< CoreClass >::set_rng_seed(), ScriptInterface::Thermostat::Thermostat::setup_thermostat(), ScriptInterface::Constraints::ShapeBasedConstraint::ShapeBasedConstraint(), ScriptInterface::Scafacos::string_to_number(), ScriptInterface::System::System::System(), ScriptInterface::LatticeIndices::throw_invalid_index(), ScriptInterface::Thermostat::Thermostat::turn_thermostat_off(), ScriptInterface::walberla::unit_test_handle(), ScriptInterface::Thermostat::Interface< CoreClass >::update_and_bind(), ScriptInterface::Interactions::InteractionPotentialInterface< CoreIA >::update_core(), ScriptInterface::Thermostat::Thermostat::update_global_kT(), ScriptInterface::AutoParameters< Derived, Base >::valid_parameters(), ScriptInterface::Shapes::Wall::Wall(), ScriptInterface::walberla::CheckpointFile::write(), ScriptInterface::Writer::H5md::~H5md(), ScriptInterface::ObjectList< ManagedType, BaseType >::~ObjectList(), and ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::~ObjectMap().
get_value() [2/2]
template<typename T > T ScriptInterface::get_value (VariantMap const & vals, std::string const & name)
Get a value from a VariantMap by name, or throw if it does not exist or is not convertible to the target type.
Definition at line 410 of file get_value.hpp.
References get_value().
get_value_or()
template<typename T > T ScriptInterface::get_value_or (VariantMap const & vals, std::string const & name, T const & default_)
Get a value from a VariantMap by name, or return a default value if it does not exist.
Definition at line 422 of file get_value.hpp.
References get_value().
Referenced by ScriptInterface::ReactionMethods::ConstantpHEnsemble::do_construct(), and ScriptInterface::ReactionMethods::ReactionEnsemble::do_construct().
initialize()
void ScriptInterface::initialize (Utils::Factory< ObjectHandle > * f)
Definition at line 52 of file initialize.cpp.
References ScriptInterface::BondBreakage::initialize(), ScriptInterface::Shapes::initialize(), ScriptInterface::Accumulators::initialize(), ScriptInterface::Analysis::initialize(), ScriptInterface::CellSystem::initialize(), ScriptInterface::ClusterAnalysis::initialize(), ScriptInterface::CodeInfo::initialize(), ScriptInterface::CollisionDetection::initialize(), ScriptInterface::Constraints::initialize(), ScriptInterface::Coulomb::initialize(), ScriptInterface::Galilei::initialize(), ScriptInterface::Writer::initialize(), ScriptInterface::Integrators::initialize(), ScriptInterface::Interactions::initialize(), ScriptInterface::LeesEdwards::initialize(), ScriptInterface::Dipoles::initialize(), ScriptInterface::Math::initialize(), ScriptInterface::MPIIO::initialize(), ScriptInterface::Observables::initialize(), ScriptInterface::PairCriteria::initialize(), ScriptInterface::Particles::initialize(), ScriptInterface::Profiler::initialize(), ScriptInterface::ReactionMethods::initialize(), ScriptInterface::System::initialize(), ScriptInterface::Thermostat::initialize(), and ScriptInterface::walberla::initialize().
is_none()
bool ScriptInterface::is_none (Variant const & v) inline
Definition at line 115 of file Variant.hpp.
References get_value().
Referenced by ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), ScriptInterface::Coulomb::Container::Container(), ScriptInterface::Dipoles::Container::Container(), ScriptInterface::walberla::EKFieldSerializer::deserialize(), ScriptInterface::walberla::LBFieldSerializer::deserialize(), ScriptInterface::LeesEdwards::LeesEdwards::do_call_method(), ScriptInterface::walberla::EKSpeciesNode::do_call_method(), ScriptInterface::walberla::LBFluidNode::do_call_method(), ScriptInterface::Coulomb::CoulombP3M< Architecture >::do_construct(), ScriptInterface::Dipoles::DipolarP3M< Architecture >::do_construct(), ScriptInterface::Thermostat::Interface< CoreClass >::Interface(), ScriptInterface::Thermostat::Interface< CoreClass >::invalid_rng_state(), ScriptInterface::Thermostat::LBThermostat::invalid_rng_state(), ScriptInterface::Thermostat::LBThermostat::LBThermostat(), ScriptInterface::LeesEdwards::LeesEdwards::LeesEdwards(), and ScriptInterface::Thermostat::Interface< CoreClass >::make_autogamma().
is_type()
template<class T > bool ScriptInterface::is_type (Variant const & v)
Check is a Variant holds a specific type.
Template Parameters
T type to check for
Parameters
v Variant to check in
Returns
true, if v holds a T.
Definition at line 111 of file Variant.hpp.
Referenced by ScriptInterface::walberla::EKFieldSerializer::deserialize(), ScriptInterface::walberla::LBFieldSerializer::deserialize(), ScriptInterface::Coulomb::CoulombP3M< Architecture >::do_construct(), and ScriptInterface::Dipoles::DipolarP3M< Architecture >::do_construct().
make_shared_from_args()
template<typename T , typename... Types, typename... ArgNames> std::shared_ptr< T > ScriptInterface::make_shared_from_args (VariantMap const & vals, ArgNames &&... args)
Make a new std::shared_ptr<T> with arguments extracted from a VariantMap.
Definition at line 435 of file get_value.hpp.
References get_value().
Referenced by ScriptInterface::Writer::H5md::do_construct(), ScriptInterface::Observables::LBProfileObservable< CoreLBObs >::do_construct(), ScriptInterface::Interactions::InteractionLJ::make_new_instance(), ScriptInterface::Interactions::InteractionLJGen::make_new_instance(), ScriptInterface::Interactions::InteractionBMHTF::make_new_instance(), ScriptInterface::Interactions::InteractionBuckingham::make_new_instance(), ScriptInterface::Interactions::InteractionGayBerne::make_new_instance(), ScriptInterface::Interactions::InteractionTabulated::make_new_instance(), ScriptInterface::Interactions::InteractionDPD::make_new_instance(), and ScriptInterface::Interactions::InteractionSmoothStep::make_new_instance().
make_unordered_map_of_variants()
template<typename K , typename V > auto ScriptInterface::make_unordered_map_of_variants (std::unordered_map< K, V > const & v)
Definition at line 80 of file Variant.hpp.
References get_value().
Referenced by ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method(), ScriptInterface::Analysis::Analysis::do_call_method(), ScriptInterface::System::CudaInitHandle::do_call_method(), ScriptInterface::System::System::do_call_method(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::ObjectMap(), ScriptInterface::ReactionMethods::ReactionAlgorithm::ReactionAlgorithm(), ScriptInterface::Integrators::StokesianDynamics::StokesianDynamics(), and ScriptInterface::walberla::VTKHandleBase< Field >::VTKHandleBase().
make_variant()
template<typename T > Variant ScriptInterface::make_variant (const T & x)
Make a Variant from argument.
This is a convenience function, so that rather involved constructors from boost::variant are not needed in the script interfaces.
Definition at line 77 of file Variant.hpp.
Referenced by ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), and ScriptInterface::LeesEdwards::LeesEdwards::LeesEdwards().
make_vector_of_variants()
template<typename T > auto ScriptInterface::make_vector_of_variants (std::vector< T > const & v)
Definition at line 88 of file Variant.hpp.
References get_value().
Referenced by ScriptInterface::Writer::H5md::do_call_method(), ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method(), ScriptInterface::Analysis::Analysis::do_call_method(), ScriptInterface::CodeInfo::CodeInfo::do_call_method(), ScriptInterface::Particles::Polymer::do_call_method(), ScriptInterface::Coulomb::CoulombScafacos::do_call_method(), ScriptInterface::Dipoles::DipolarScafacos::do_call_method(), ScriptInterface::Particles::ParticleHandle::do_call_method(), ScriptInterface::walberla::VTKHandleBase< Field >::do_call_method(), ScriptInterface::Writer::H5md::H5md(), ScriptInterface::Coulomb::ICCStar::ICCStar(), ScriptInterface::ObjectList< ManagedType, BaseType >::ObjectList(), ScriptInterface::walberla::EKFieldSerializer::serialize(), ScriptInterface::walberla::LBFieldSerializer::serialize(), and ScriptInterface::walberla::LatticeModel< Method, VTKHandle >::serialize_vtk_writers().
mpi_reduce_sum()
template<typename T > T ScriptInterface::mpi_reduce_sum (boost::mpi::communicator const & comm, T const & result)
Reduce object by sum on the head node.
Worker nodes get a default-constructed object.
Definition at line 35 of file script_interface/communication.hpp.
References get_value().
Referenced by ScriptInterface::Analysis::Analysis::do_call_method().
object_id()
ObjectId ScriptInterface::object_id (const ObjectHandle * p) inline
Id for object.
This assigns every ObjectHandle a unique id.
Definition at line 40 of file packed_variant.hpp.
Referenced by ScriptInterface::GlobalContext::make_shared(), ScriptInterface::GlobalContext::notify_call_method(), ScriptInterface::GlobalContext::notify_set_parameter(), and ScriptInterface::PackVisitor::operator()().
pack() [1/2]
PackedVariant ScriptInterface::pack (const Variant & v) inline
Transform a Variant to a PackedVariant.
Applies PackVisitor to a Variant.
Parameters
v Input Variant
Returns
Packed variant.
Definition at line 169 of file packed_variant.hpp.
Referenced by ScriptInterface::Particles::Polymer::do_call_method(), ScriptInterface::System::System::get_internal_state(), ScriptInterface::GlobalContext::notify_call_method(), ScriptInterface::GlobalContext::notify_set_parameter(), and ScriptInterface::Scafacos::serialize_parameters().
pack() [2/2]
PackedMap ScriptInterface::pack (const VariantMap & v) inline
Pack a VariantMap.
Applies pack to every value in the input map.
Definition at line 193 of file packed_variant.hpp.
References get_value().
set_from_args()
template<typename T > void ScriptInterface::set_from_args (T & dst, VariantMap const & vals, const char * name)
Definition at line 442 of file get_value.hpp.
References get_value().
Referenced by ScriptInterface::Accumulators::Correlator::do_construct(), ScriptInterface::Accumulators::ContactTimes::do_construct(), ScriptInterface::Accumulators::MeanVarianceCalculator::do_construct(), ScriptInterface::Accumulators::TimeSeries::do_construct(), ScriptInterface::Observables::CylindricalLBProfileObservable< CoreCylLBObs >::do_construct(), ScriptInterface::Observables::CylindricalPidProfileObservable< CoreObs >::do_construct(), and ScriptInterface::Shapes::HollowConicalFrustum::do_construct().
unpack() [1/2]
VariantMap ScriptInterface::unpack (const PackedMap & v, std::unordered_map< ObjectId, ObjectRef > const & objects) inline
Unpack a PackedMap.
Applies unpack to every value in the input map.
Definition at line 210 of file packed_variant.hpp.
References unpack().
unpack() [2/2]
Variant ScriptInterface::unpack (const PackedVariant & v, std::unordered_map< ObjectId, ObjectRef > const & objects) inline
Unpack a PackedVariant.
Applies UnpackVisitor to a Variant.
Parameters
v Packed Variant.
objects Map of ids to reference.
Returns
Transformed variant.
Definition at line 182 of file packed_variant.hpp.
Referenced by ScriptInterface::System::System::set_internal_state(), and unpack().
Variable Documentation
none
constexpr const None ScriptInterface::none {} constexpr
None-"literal".
Definition at line 50 of file Variant.hpp.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), ScriptInterface::CollisionDetection::CollisionDetection::CollisionDetection(), ScriptInterface::ObjectHandle::do_call_method(), ScriptInterface::Constraints::ExternalField< Coupling, Field >::do_call_method(), ScriptInterface::Constraints::ExternalPotential< Coupling, Field >::do_call_method(), ScriptInterface::ObjectList< ManagedType, BaseType >::do_call_method(), ScriptInterface::ObjectMap< ManagedType, BaseType, KeyType >::do_call_method(), ScriptInterface::walberla::EKIndexedReaction::do_call_method(), ScriptInterface::Constraints::ShapeBasedConstraint::do_call_method(), ScriptInterface::Integrators::Integrator::do_call_method(), ScriptInterface::walberla::EKContainer::do_construct(), ScriptInterface::LeesEdwards::LeesEdwards::LeesEdwards(), and ScriptInterface::ReactionMethods::WidomInsertion::WidomInsertion().