ESPResSo: Algorithm Namespace Reference
Algorithm Namespace Reference
Functions
template<typename CellIterator , typename PairKernel >
void link_cell (CellIterator first, CellIterator last, PairKernel &&pair_kernel)
Iterates over all particles in the cell range, and over all pairs within the cells and with their neighbors.
template<FloatingPointOrRef T, IntegralOrRef I>
std::pair< T, I > periodic_fold (T x, I i, T const l)
Fold value into primary interval.
template<FloatingPointOrRef T>
T periodic_fold (T x, T const l)
Fold value into primary interval.
Function Documentation
link_cell()
template<typename CellIterator , typename PairKernel > void Algorithm::link_cell (CellIterator first, CellIterator last, PairKernel && pair_kernel)
Iterates over all particles in the cell range, and over all pairs within the cells and with their neighbors.
Definition at line 32 of file link_cell.hpp.
periodic_fold() [1/2]
template<FloatingPointOrRef T, IntegralOrRef I> std::pair< T, I > Algorithm::periodic_fold (T x, I i, T const l)
Fold value into primary interval.
Parameters
x Value to fold
i Image count before folding
l Length of primary interval
Returns
x folded into [0, l) and number of folds.
Definition at line 45 of file periodic_fold.hpp.
Referenced by BoxGeometry::fold_position(), BoxGeometry::folded_image_box(), BoxGeometry::folded_position(), BoxGeometry::get_mi_vector(), BoxGeometry::get_mi_vector(), and positions_in_halo_impl().
periodic_fold() [2/2]
template<FloatingPointOrRef T> T Algorithm::periodic_fold (T x, T const l)
Fold value into primary interval.
Parameters
x Value to fold
l Length of primary interval
Returns
x folded into [0, l).
Definition at line 68 of file periodic_fold.hpp.