ESPResSo: ReactionMethods Namespace Reference
ReactionMethods Namespace Reference
Classes
class ConstantpHEnsemble
Constant-pH Ensemble, for derivation see [38].
class ReactionAlgorithm
Base class for reaction ensemble methods.
class ReactionEnsemble
Reaction ensemble method.
struct SingleReaction
class WidomInsertion
Widom insertion method.
Functions
double ln_factorial_Ni0_divided_by_factorial_Ni0_plus_nu_i (int Ni0, int nu_i)
Calculates the logarithm of factorial expression which occurs in the reaction ensemble acceptance probability.
double calculate_factorial_expression (SingleReaction const &reaction, std::unordered_map< int, int > const &particle_numbers)
Calculates the logarithm of whole product of factorial expressions which occur in the reaction ensemble acceptance probability.
double calculate_factorial_expression_cpH (SingleReaction const &reaction, std::unordered_map< int, int > const &particle_numbers)
Calculates the logarithm of factorial expression which occurs in the constant pH method with symmetric proposal probability.
Function Documentation
calculate_factorial_expression()
double ReactionMethods::calculate_factorial_expression (SingleReaction const & reaction, std::unordered_map< int, int > const & particle_numbers)
Calculates the logarithm of whole product of factorial expressions which occur in the reaction ensemble acceptance probability.
See [41].
Definition at line 49 of file utils.cpp.
References ln_factorial_Ni0_divided_by_factorial_Ni0_plus_nu_i(), and stream.
calculate_factorial_expression_cpH()
double ReactionMethods::calculate_factorial_expression_cpH (SingleReaction const & reaction, std::unordered_map< int, int > const & particle_numbers)
Calculates the logarithm of factorial expression which occurs in the constant pH method with symmetric proposal probability.
See [29] for details. zeta = 1 (see [41]) since we only perform one reaction at one call of the function.
Definition at line 68 of file utils.cpp.
References ln_factorial_Ni0_divided_by_factorial_Ni0_plus_nu_i(), and stream.
ln_factorial_Ni0_divided_by_factorial_Ni0_plus_nu_i()
double ReactionMethods::ln_factorial_Ni0_divided_by_factorial_Ni0_plus_nu_i (int Ni0, int nu_i)
Calculates the logarithm of factorial expression which occurs in the reaction ensemble acceptance probability.
Definition at line 29 of file utils.cpp.
References stream.
Referenced by calculate_factorial_expression(), and calculate_factorial_expression_cpH().