ESPResSo: walberla Namespace Reference
walberla Namespace Reference
\file PackInfoPdfDoublePrecision.cpp \author pystencils
Namespaces
namespace blockforest
namespace domain_decomposition
namespace ek
namespace field
namespace lbm
namespace pystencils
namespace vtk
Classes
struct BlockAndCell
class BoundaryHandling
Boundary class optimized for sparse data.
class EKinWalberlaImpl
Class that runs and controls the EK on waLBerla.
class EKReactant
class EKReactionBase
class EKReactionBaseIndexed
class EKReactionImplBulk
class EKReactionImplIndexed
class InterpolateAndShiftAtBoundary
Lees-Edwards sweep.
class LBWalberlaImpl
Class that runs and controls the LB on waLBerla.
class PoissonSolver
class PoissonSolverFFT
class PoissonSolverNone
class ResetForce
Sweep that swaps force_to_be_applied and last_applied_force and resets force_to_be_applied to the global external force.
Functions
Cell to_cell (signed_integral_vector auto const &xyz)
IBlock * get_block_extended (LatticeWalberla const &lattice, auto const &pos, unsigned int n_ghost_layers)
std::optional< BlockAndCell > get_block_and_cell (::LatticeWalberla const &lattice, signed_integral_vector auto const &node, bool consider_ghost_layers)
IBlock * get_block (::LatticeWalberla const &lattice, real_vector auto const &pos, bool consider_ghost_layers)
auto convert_cell_corner_to_coord (real_vector auto const &corner)
Get the block-local coordinates of a block corner.
auto get_min_corner (IBlock const &block)
Get the block-local coordinates of the lower corner of a block.
auto get_max_corner (IBlock const &block)
Get the block-local coordinates of the upper corner of a block.
std::optional< walberla::cell::CellInterval > get_interval (::LatticeWalberla const &lattice, Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner)
std::optional< walberla::cell::CellInterval > get_block_interval (::LatticeWalberla const &lattice, Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, Utils::Vector3i const &block_offset, IBlock const &block)
template<typename Kernel >
void copy_block_buffer (CellInterval const &bci, CellInterval const &ci, Utils::Vector3i const &block_offset, Utils::Vector3i const &lower_corner, Kernel &&kernel)
Synchronize data between a sliced block and a container.
std::shared_ptr< EKinWalberlaBase > new_ek_walberla_cpu (std::shared_ptr< LatticeWalberla > const &lattice, double diffusion, double kT, double valency, Utils::Vector3d ext_efield, double density, bool advection, bool friction_coupling, bool single_precision, bool thermalized, unsigned int seed)
std::shared_ptr< EKinWalberlaBase > new_ek_walberla_gpu (std::shared_ptr< LatticeWalberla > const &lattice, double diffusion, double kT, double valency, Utils::Vector3d ext_efield, double density, bool advection, bool friction_coupling, bool single_precision, bool thermalized, unsigned int seed)
std::shared_ptr< EKReactionBase > new_ek_reaction_bulk_cpu (std::shared_ptr< LatticeWalberla > const &lattice, typename EKReactionBase::reactants_type const &reactants, double coefficient)
std::shared_ptr< EKReactionBase > new_ek_reaction_bulk_gpu (std::shared_ptr< LatticeWalberla > const &lattice, typename EKReactionBase::reactants_type const &reactants, double coefficient)
std::shared_ptr< EKReactionBaseIndexed > new_ek_reaction_indexed_cpu (std::shared_ptr< LatticeWalberla > const &lattice, typename EKReactionBase::reactants_type const &reactants, double coefficient)
std::shared_ptr< EKReactionBaseIndexed > new_ek_reaction_indexed_gpu (std::shared_ptr< LatticeWalberla > const &lattice, typename EKReactionBase::reactants_type const &reactants, double coefficient)
std::shared_ptr< walberla::PoissonSolver > new_ek_poisson_none (std::shared_ptr< LatticeWalberla > const &lattice, bool single_precision)
std::shared_ptr< walberla::PoissonSolver > new_ek_poisson_fft (std::shared_ptr< LatticeWalberla > const &lattice, double permittivity, bool single_precision)
std::shared_ptr< walberla::PoissonSolver > new_ek_poisson_fft_cuda (std::shared_ptr< LatticeWalberla > const &lattice, double permittivity, bool single_precision)
void mpi_init ()
Initialize waLBerla's MPI manager and environment.
void mpi_deinit ()
Release waLBerla's MPI manager and environment.
void mpi_reinit (int const *cart_topol)
Re-initialize waLBerla's MPI Cartesian communicator.
std::unique_ptr< ResourceManager > get_vtk_dependent_resources ()
Get a lock on waLBerla's global resources for VTK.
ResourceObserver get_mpi_cart_comm_observer ()
Get an observer on waLBerla's MPI Cartesian communicator status.
template<typename FloatType >
FloatType greens_function (int x, int y, int z, auto const &dim)
template<typename T , std::size_t N>
auto to_array (Utils::Vector< T, N > const &vec)
int pos_to_linear_index (int x, int y, int z, auto const &dim)
std::vector< Utils::Vector3d > fill_3D_vector_array (std::vector< double > const &vec_flat, Utils::Vector3i const &grid_size)
std::vector< double > fill_3D_scalar_array (std::vector< double > const &vec_flat, Utils::Vector3i const &grid_size)
template<class BoundaryModel , class DataType >
void set_boundary_from_grid (BoundaryModel &boundary, LatticeWalberla const &lattice, std::vector< int > const &raster_flat, std::vector< DataType > const &data_flat)
template<typename T , typename U = T>
U es2walberla (T const &v)
template<>
Vector3< float > es2walberla (Utils::Vector3d const &v)
template<>
Vector3< double > es2walberla (Utils::Vector3d const &v)
template<typename T >
auto to_vector3d (Vector3< T > const &v) noexcept
Utils::Vector3i to_vector3i (Vector3< int > const &v) noexcept
Utils::Vector3i to_vector3i (Cell const &v) noexcept
template<typename T >
auto to_vector3 (Utils::Vector3d const &v) noexcept
template<typename T >
auto to_vector9d (Matrix3< T > const &m) noexcept
template<typename Function >
void interpolate_bspline_at_pos (Utils::Vector3d const &pos, Function const &f)
Detailed Description
\file PackInfoPdfDoublePrecision.cpp \author pystencils
\file PackInfoVecSinglePrecisionCUDA.h \author pystencils
\file PackInfoVecSinglePrecision.cpp \author pystencils
\file PackInfoVecDoublePrecisionCUDA.h \author pystencils
\file PackInfoVecDoublePrecision.cpp \author pystencils
\file PackInfoPdfSinglePrecisionCUDA.h \author pystencils
\file PackInfoPdfSinglePrecision.cpp \author pystencils
\file PackInfoPdfDoublePrecisionCUDA.h \author pystencils
Function Documentation
convert_cell_corner_to_coord()
auto walberla::convert_cell_corner_to_coord (real_vector auto const & corner) inline
Get the block-local coordinates of a block corner.
This method leverages the fact that the grid spacing is unity in LB units, i.e. floating-point coordinates can be cast to integers indices.
Definition at line 141 of file BlockAndCell.hpp.
Referenced by LatticeWalberla::get_local_grid_range(), get_max_corner(), and get_min_corner().
copy_block_buffer()
template<typename Kernel > void walberla::copy_block_buffer (CellInterval const & bci, CellInterval const & ci, Utils::Vector3i const & block_offset, Utils::Vector3i const & lower_corner, Kernel && kernel)
Synchronize data between a sliced block and a container.
Synchronize data between two data buffers representing sliced matrices with different memory layouts. The kernel takes as argument an index for the flattened data buffer containing the serialized block slice, an index for the flattened I/O buffer, and a block-local node position.
Parameters
bci Cell interval of the local block within a 3D slice
ci Cell interval of the entire lattice within a 3D slice
block_offset Origin of the local block
lower_corner Lower corner of the 3D slice
kernel Function to execute on the two data buffers
Definition at line 217 of file BlockAndCell.hpp.
References Utils::get_linear_index(), Utils::ROW_MAJOR, stream, and to_vector3i().
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_slice_potential(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary().
es2walberla() [1/3]
template<typename T , typename U = T> U walberla::es2walberla (T const & v) inline
Definition at line 34 of file types_conversion.hpp.
References stream.
es2walberla() [2/3]
template<> Vector3< float > walberla::es2walberla (Utils::Vector3d const & v) inline
Definition at line 40 of file types_conversion.hpp.
References stream.
es2walberla() [3/3]
template<> Vector3< double > walberla::es2walberla (Utils::Vector3d const & v) inline
Definition at line 44 of file types_conversion.hpp.
References stream.
fill_3D_scalar_array()
std::vector< double > walberla::fill_3D_scalar_array (std::vector< double > const & vec_flat, Utils::Vector3i const & grid_size) inline
Definition at line 60 of file boundary.hpp.
References Utils::product(), and stream.
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_density_boundary_from_shape().
fill_3D_vector_array()
std::vector< Utils::Vector3d > walberla::fill_3D_vector_array (std::vector< double > const & vec_flat, Utils::Vector3i const & grid_size) inline
Definition at line 36 of file boundary.hpp.
References Utils::product(), and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape().
get_block()
IBlock * walberla::get_block (::LatticeWalberla const & lattice, real_vector auto const & pos, bool consider_ghost_layers) inline
Definition at line 123 of file BlockAndCell.hpp.
References block(), get_block_extended(), LatticeWalberla::get_blocks(), LatticeWalberla::get_ghost_layers(), and stream.
get_block_and_cell()
std::optional< BlockAndCell > walberla::get_block_and_cell (::LatticeWalberla const & lattice, signed_integral_vector auto const & node, bool consider_ghost_layers) inline
Definition at line 102 of file BlockAndCell.hpp.
References block(), get_block_extended(), LatticeWalberla::get_blocks(), LatticeWalberla::get_ghost_layers(), stream, and to_cell().
Referenced by get_interval(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_boundary_force(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_density_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_vector(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied(), walberla::EKReactionImplIndexed< Architecture >::get_node_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_is_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_is_flux_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_population(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_node_potential(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::remove_node_from_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::remove_node_from_flux_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_node_flux_boundary(), walberla::EKReactionImplIndexed< Architecture >::set_node_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_flux_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary().
get_block_extended()
IBlock * walberla::get_block_extended (LatticeWalberla const & lattice, auto const & pos, unsigned int n_ghost_layers)
Definition at line 87 of file BlockAndCell.hpp.
References block(), LatticeWalberla::get_cached_blocks(), and stream.
Referenced by get_block(), get_block_and_cell(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel(), and walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel().
get_block_interval()
std::optional< walberla::cell::CellInterval > walberla::get_block_interval (::LatticeWalberla const & lattice, Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, Utils::Vector3i const & block_offset, IBlock const & block) inline
Definition at line 178 of file BlockAndCell.hpp.
References block(), Utils::Vector< T, N >::broadcast(), LatticeWalberla::get_block_corner(), stream, and to_cell().
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_slice_potential(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary().
get_interval()
std::optional< walberla::cell::CellInterval > walberla::get_interval (::LatticeWalberla const & lattice, Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) inline
Definition at line 158 of file BlockAndCell.hpp.
References Utils::Vector< T, N >::broadcast(), get_block_and_cell(), get_min_corner(), stream, and to_cell().
Referenced by walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_density_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_vector(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_is_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_population(), walberla::PoissonSolverFFT< FloatType, Architecture >::get_slice_potential(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_pressure_tensor(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_density(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_density_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::set_slice_flux_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_population(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), and walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary().
get_max_corner()
auto walberla::get_max_corner (IBlock const & block) inline
Get the block-local coordinates of the upper corner of a block.
Definition at line 153 of file BlockAndCell.hpp.
References block(), and convert_cell_corner_to_coord().
Referenced by LatticeWalberla::get_block_corner().
get_min_corner()
auto walberla::get_min_corner (IBlock const & block) inline
Get the block-local coordinates of the lower corner of a block.
Definition at line 148 of file BlockAndCell.hpp.
References block(), and convert_cell_corner_to_coord().
Referenced by LatticeWalberla::get_block_corner(), and get_interval().
get_mpi_cart_comm_observer()
ResourceObserver walberla::get_mpi_cart_comm_observer ()
Get an observer on waLBerla's MPI Cartesian communicator status.
Definition at line 82 of file walberla_init.cpp.
References stream, and walberla_mpi_cart_comm_observer.
Referenced by ScriptInterface::walberla::EKSpecies::do_construct(), and ScriptInterface::walberla::LBFluid::do_construct().
get_vtk_dependent_resources()
std::unique_ptr< ResourceManager > walberla::get_vtk_dependent_resources ()
Get a lock on waLBerla's global resources for VTK.
Definition at line 73 of file walberla_init.cpp.
References stream, walberla_mpi_comm, and walberla_mpi_env.
Referenced by VTKHandle::VTKHandle().
greens_function()
template<typename FloatType > FloatType walberla::greens_function (int x, int y, int z, auto const & dim)
Definition at line 35 of file greens_function.hpp.
References stream.
interpolate_bspline_at_pos()
template<typename Function > void walberla::interpolate_bspline_at_pos (Utils::Vector3d const & pos, Function const & f)
Definition at line 76 of file types_conversion.hpp.
References Utils::Vector< T, N >::broadcast().
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel(), and walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel().
mpi_deinit()
void walberla::mpi_deinit ()
Release waLBerla's MPI manager and environment.
Definition at line 64 of file walberla_init.cpp.
References stream, walberla_mpi_cart_comm_observer, walberla_mpi_comm, and walberla_mpi_env.
Referenced by CommunicationEnvironment::~CommunicationEnvironment().
mpi_init()
void walberla::mpi_init ()
Initialize waLBerla's MPI manager and environment.
Definition at line 43 of file walberla_init.cpp.
References stream, walberla_mpi_cart_comm_observer, walberla_mpi_comm, and walberla_mpi_env.
Referenced by CommunicationEnvironment::CommunicationEnvironment().
mpi_reinit()
void walberla::mpi_reinit (int const * cart_topol)
Re-initialize waLBerla's MPI Cartesian communicator.
Definition at line 54 of file walberla_init.cpp.
References stream, walberla_mpi_cart_comm_observer, walberla_mpi_comm, and walberla_mpi_env.
Referenced by Communicator::init_comm_cart().
new_ek_poisson_fft()
std::shared_ptr< walberla::PoissonSolver > walberla::new_ek_poisson_fft (std::shared_ptr< LatticeWalberla > const & lattice, double permittivity, bool single_precision)
Definition at line 31 of file ek_poisson_fft_init.cpp.
References stream.
Referenced by ScriptInterface::walberla::EKFFT::make_instance().
new_ek_poisson_fft_cuda()
std::shared_ptr< walberla::PoissonSolver > walberla::new_ek_poisson_fft_cuda (std::shared_ptr< LatticeWalberla > const & lattice, double permittivity, bool single_precision)
Definition at line 42 of file ek_poisson_fft_init_cuda.cu.
References stream.
Referenced by ScriptInterface::walberla::EKFFT::make_instance().
new_ek_poisson_none()
std::shared_ptr< walberla::PoissonSolver > walberla::new_ek_poisson_none (std::shared_ptr< LatticeWalberla > const & lattice, bool single_precision)
Definition at line 30 of file ek_poisson_none_init.cpp.
References stream.
Referenced by ScriptInterface::walberla::EKNone::do_construct().
new_ek_reaction_bulk_cpu()
std::shared_ptr< EKReactionBase > walberla::new_ek_reaction_bulk_cpu (std::shared_ptr< LatticeWalberla > const & lattice, typename EKReactionBase::reactants_type const & reactants, double coefficient)
Definition at line 52 of file ek_walberla_init.cpp.
References stream.
Referenced by ScriptInterface::walberla::EKBulkReaction::do_construct().
new_ek_reaction_bulk_gpu()
std::shared_ptr< EKReactionBase > walberla::new_ek_reaction_bulk_gpu (std::shared_ptr< LatticeWalberla > const & lattice, typename EKReactionBase::reactants_type const & reactants, double coefficient)
Definition at line 76 of file ek_walberla_init.cu.
References stream.
Referenced by ScriptInterface::walberla::EKBulkReaction::do_construct().
new_ek_reaction_indexed_cpu()
std::shared_ptr< EKReactionBaseIndexed > walberla::new_ek_reaction_indexed_cpu (std::shared_ptr< LatticeWalberla > const & lattice, typename EKReactionBase::reactants_type const & reactants, double coefficient)
Definition at line 60 of file ek_walberla_init.cpp.
References stream.
Referenced by ScriptInterface::walberla::EKIndexedReaction::do_construct().
new_ek_reaction_indexed_gpu()
std::shared_ptr< EKReactionBaseIndexed > walberla::new_ek_reaction_indexed_gpu (std::shared_ptr< LatticeWalberla > const & lattice, typename EKReactionBase::reactants_type const & reactants, double coefficient)
Definition at line 84 of file ek_walberla_init.cu.
References stream.
Referenced by ScriptInterface::walberla::EKIndexedReaction::do_construct().
new_ek_walberla_cpu()
std::shared_ptr< EKinWalberlaBase > walberla::new_ek_walberla_cpu (std::shared_ptr< LatticeWalberla > const & lattice, double diffusion, double kT, double valency, Utils::Vector3d ext_efield, double density, bool advection, bool friction_coupling, bool single_precision, bool thermalized, unsigned int seed)
Definition at line 36 of file ek_walberla_init.cpp.
References density, and stream.
Referenced by ScriptInterface::walberla::EKSpecies::make_instance().
new_ek_walberla_gpu()
std::shared_ptr< EKinWalberlaBase > walberla::new_ek_walberla_gpu (std::shared_ptr< LatticeWalberla > const & lattice, double diffusion, double kT, double valency, Utils::Vector3d ext_efield, double density, bool advection, bool friction_coupling, bool single_precision, bool thermalized, unsigned int seed)
Definition at line 60 of file ek_walberla_init.cu.
References density, and stream.
Referenced by ScriptInterface::walberla::EKSpecies::make_instance().
pos_to_linear_index()
int walberla::pos_to_linear_index (int x, int y, int z, auto const & dim) inline
Definition at line 96 of file PoissonSolverFFT.hpp.
Referenced by walberla::PoissonSolverFFT< FloatType, Architecture >::add_charge_to_field(), walberla::PoissonSolverFFT< FloatType, Architecture >::reset_charge_field(), walberla::PoissonSolverFFT< FloatType, Architecture >::setup_fft(), and walberla::PoissonSolverFFT< FloatType, Architecture >::solve().
set_boundary_from_grid()
template<class BoundaryModel , class DataType > void walberla::set_boundary_from_grid (BoundaryModel & boundary, LatticeWalberla const & lattice, std::vector< int > const & raster_flat, std::vector< DataType > const & data_flat)
Definition at line 81 of file boundary.hpp.
References block(), LatticeWalberla::get_block_corner(), LatticeWalberla::get_blocks(), LatticeWalberla::get_ghost_layers(), LatticeWalberla::get_grid_dimensions(), Utils::product(), and stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::update_boundary_from_shape(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_density_boundary_from_shape(), and walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::update_flux_boundary_from_shape().
to_array()
template<typename T , std::size_t N> auto walberla::to_array (Utils::Vector< T, N > const & vec)
Definition at line 90 of file PoissonSolverFFT.hpp.
References stream.
Referenced by walberla::PoissonSolverFFT< FloatType, Architecture >::heffte_container< ComplexType >::heffte_container().
to_cell()
Cell walberla::to_cell (signed_integral_vector auto const & xyz) inline
Definition at line 78 of file BlockAndCell.hpp.
References stream.
Referenced by get_block_and_cell(), get_block_interval(), get_interval(), walberla::BoundaryHandling< FloatType, ValueType, BoundaryClass >::get_node_value_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_density_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_force_interpolation_kernel(), walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel(), walberla::BoundaryHandling< FloatType, ValueType, BoundaryClass >::node_is_boundary(), walberla::BoundaryHandling< FloatType, ValueType, BoundaryClass >::remove_node_from_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_density_boundary_handling(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::reset_flux_boundary_handling(), walberla::BoundaryHandling< FloatType, ValueType, BoundaryClass >::set_node_value_at_boundary(), and walberla::BoundaryHandling< FloatType, ValueType, BoundaryClass >::unpack_node().
to_vector3()
template<typename T > auto walberla::to_vector3 (Utils::Vector3d const & v) noexcept
Definition at line 63 of file types_conversion.hpp.
References stream.
to_vector3d()
template<typename T > auto walberla::to_vector3d (Vector3< T > const & v) noexcept
Definition at line 48 of file types_conversion.hpp.
References stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_boundary_force(), walberla::ResetForce< PdfField, ForceField >::get_ext_force(), LatticeWalberla::get_local_domain(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_momentum(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_node_flux_vector(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_force_to_be_applied(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_last_applied_force(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_velocity_at_boundary(), walberla::EKinWalberlaImpl< FluxCount, FloatType, Architecture >::get_slice_flux_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::get_slice_velocity_at_boundary(), and walberla::LBWalberlaImpl< FloatType, Architecture >::make_velocity_interpolation_kernel().
to_vector3i() [1/2]
Utils::Vector3i walberla::to_vector3i (Cell const & v) inline noexcept
Definition at line 58 of file types_conversion.hpp.
to_vector3i() [2/2]
Utils::Vector3i walberla::to_vector3i (Vector3< int > const & v) inline noexcept
Definition at line 53 of file types_conversion.hpp.
Referenced by copy_block_buffer().
to_vector9d()
template<typename T > auto walberla::to_vector9d (Matrix3< T > const & m) noexcept
Definition at line 68 of file types_conversion.hpp.
References stream.
Referenced by walberla::LBWalberlaImpl< FloatType, Architecture >::get_node_pressure_tensor(), and walberla::LBWalberlaImpl< FloatType, Architecture >::get_pressure_tensor().