ESPResSo: nonbonded_interaction_data.hpp File Reference
nonbonded_interaction_data.hpp File Reference
#include "TabulatedPotential.hpp"
#include "config.hpp"
#include <utils/index.hpp>
#include <algorithm>
#include <cassert>
#include <string>
#include <vector>
Classes
struct LJ_Parameters
Lennard-Jones with shift.
struct WCA_Parameters
WCA potential.
struct LJGen_Parameters
Generic Lennard-Jones with shift.
struct SmoothStep_Parameters
smooth step potential
struct Hertzian_Parameters
Hertzian potential.
struct Gaussian_Parameters
Gaussian potential.
struct BMHTF_Parameters
BMHTF NaCl potential.
struct Morse_Parameters
Morse potential.
struct Buckingham_Parameters
Buckingham potential.
struct SoftSphere_Parameters
soft-sphere potential
struct Hat_Parameters
hat potential
struct LJcos_Parameters
Lennard-Jones+Cos potential.
struct LJcos2_Parameters
Lennard-Jones with a different Cos potential.
struct GayBerne_Parameters
Gay-Berne potential.
struct Thole_Parameters
Thole potential.
struct DPDParameters
DPD potential.
struct IA_parameters
Data structure containing the interaction parameters for non-bonded interactions.
Functions
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
IA_parameters * get_ia_param (int i, int j)
Get interaction parameters between particle types i and j.
IA_parameters * get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
void ia_params_set_state (std::string const &)
Set the state of all non-bonded interactions.
bool is_new_particle_type (int type)
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
void make_particle_type_exist_local (int type)
void reset_ia_params ()
Reset all interaction parameters to their defaults.
bool checkIfInteraction (IA_parameters const &data)
Check if a non-bonded interaction is defined.
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
double get_min_global_cut ()
Variables
constexpr double INACTIVE_CUTOFF = -1.
Cutoff for deactivated interactions.
std::vector< IA_parameters > nonbonded_ia_params
int max_seen_particle_type
Maximal particle type seen so far.
Detailed Description
Various procedures concerning interactions between particles.
Definition in file nonbonded_interaction_data.hpp.
Function Documentation
checkIfInteraction()
bool checkIfInteraction (IA_parameters const & data) inline
Check if a non-bonded interaction is defined.
Definition at line 336 of file nonbonded_interaction_data.hpp.
References INACTIVE_CUTOFF, and IA_parameters::max_cut.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), and Constraints::ShapeBasedConstraint::force().
get_ia_param()
IA_parameters* get_ia_param (int i, int j) inline
Get interaction parameters between particle types i and j.
This is symmetric, e.g. it holds that get_ia_param(i, j) and get_ia_param(j, i) point to the same data.
Parameters
i First type, has to be smaller than max_seen_particle_type.
j Second type, has to be smaller than max_seen_particle_type.
Returns
Pointer to interaction parameters for the type pair.
Definition at line 299 of file nonbonded_interaction_data.hpp.
References max_seen_particle_type, anonymous_namespace{Correlator.cpp}::min(), nonbonded_ia_params, and Utils::upper_triangular().
Referenced by Constraints::ShapeBasedConstraint::add_energy(), add_non_bonded_pair_energy(), add_non_bonded_pair_force(), add_non_bonded_pair_virials(), PairCriteria::EnergyCriterion::decide(), dpd_init(), dpd_viscous_stress_local(), Constraints::ShapeBasedConstraint::force(), get_ia_param_safe(), mpi_bcast_ia_params_local(), mpi_realloc_ia_params_local(), GetNonbondedCutoff::operator()(), and particle_short_range_energy_contribution_local().
get_ia_param_safe()
IA_parameters* get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
Slower than get_ia_param, but can also be used on not yet present particle types
Definition at line 98 of file nonbonded_interaction_data.cpp.
References get_ia_param(), and make_particle_type_exist().
Referenced by BMHTF_set_params(), buckingham_set_params(), dpd_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), lennard_jones_set_params(), ljcos2_set_params(), ljcos_set_params(), ljgen_set_params(), morse_set_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), thole_set_params(), and wca_set_params().
get_min_global_cut()
double get_min_global_cut ()
Definition at line 245 of file nonbonded_interaction_data.cpp.
References min_global_cut.
Referenced by calculate_vs_relate_to_params(), and maximal_cutoff().
ia_params_get_state()
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
Definition at line 103 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type, and nonbonded_ia_params.
ia_params_set_state()
void ia_params_set_state (std::string const &)
Set the state of all non-bonded interactions.
Definition at line 111 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type, mpi_bcast_all_ia_params(), mpi_realloc_ia_params(), and nonbonded_ia_params.
is_new_particle_type()
bool is_new_particle_type (int type)
Definition at line 220 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type.
Referenced by make_particle_type_exist(), and make_particle_type_exist_local().
make_particle_type_exist()
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
The interactions are initialized with values such that no physical interaction occurs.
Definition at line 224 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and mpi_realloc_ia_params().
Referenced by get_ia_param_safe(), Collision_parameters::initialize(), on_program_start(), and set_particle_type().
make_particle_type_exist_local()
void make_particle_type_exist_local (int type)
Definition at line 229 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and mpi_realloc_ia_params_local().
Referenced by Constraints::ShapeBasedConstraint::set_type().
maximal_cutoff_nonbonded()
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
Definition at line 204 of file nonbonded_interaction_data.cpp.
References INACTIVE_CUTOFF, nonbonded_ia_params, and recalc_maximal_cutoff().
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and maximal_cutoff().
mpi_set_min_global_cut()
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
Parameters
min_global_cut minimum global cutoff
Definition at line 241 of file nonbonded_interaction_data.cpp.
References min_global_cut, mpi_call_all(), and mpi_set_min_global_cut_local().
reset_ia_params()
void reset_ia_params ()
Reset all interaction parameters to their defaults.
Definition at line 215 of file nonbonded_interaction_data.cpp.
References mpi_bcast_all_ia_params(), and nonbonded_ia_params.
Variable Documentation
INACTIVE_CUTOFF
constexpr double INACTIVE_CUTOFF = -1. constexpr
Cutoff for deactivated interactions.
Must be negative, so that even particles on top of each other don't interact by chance.
Definition at line 40 of file nonbonded_interaction_data.hpp.
Referenced by checkIfInteraction(), force_calc(), interaction_range(), maximal_cutoff_nonbonded(), VerletCriterion< CutoffGetter >::operator()(), recalc_long_range_cutoff(), and recalc_maximal_cutoff().
max_seen_particle_type
int max_seen_particle_type
Maximal particle type seen so far.
Definition at line 50 of file nonbonded_interaction_data.cpp.
Referenced by dpd_init(), get_ia_param(), ia_params_get_state(), ia_params_set_state(), is_new_particle_type(), max_non_bonded_pairs(), and mpi_realloc_ia_params_local().
nonbonded_ia_params
std::vector<IA_parameters> nonbonded_ia_params
Definition at line 51 of file nonbonded_interaction_data.cpp.
Referenced by get_ia_param(), ia_params_get_state(), ia_params_set_state(), maximal_cutoff_nonbonded(), mpi_bcast_all_ia_params_local(), mpi_realloc_ia_params_local(), and reset_ia_params().