ESPResSo: nonbonded_interaction_data.cpp File Reference
nonbonded_interaction_data.cpp File Reference
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "communication.hpp"
#include "electrostatics/coulomb.hpp"
#include "event.hpp"
#include "serialization/IA_parameters.hpp"
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/iostreams/device/array.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/range/algorithm/fill.hpp>
#include <boost/serialization/string.hpp>
#include <boost/serialization/vector.hpp>
#include <utils/index.hpp>
#include <algorithm>
#include <sstream>
#include <string>
#include <utility>
#include <vector>
Functions
static void mpi_realloc_ia_params_local (int new_size)
void mpi_realloc_ia_params (int new_size)
Increase the size of the nonbonded_ia_params vector.
static void mpi_bcast_all_ia_params_local ()
void mpi_bcast_all_ia_params ()
Broadcast nonbonded_ia_params to all nodes.
IA_parameters * get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
void ia_params_set_state (std::string const &state)
Set the state of all non-bonded interactions.
static double recalc_maximal_cutoff (const IA_parameters &data)
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
void reset_ia_params ()
Reset all interaction parameters to their defaults.
bool is_new_particle_type (int type)
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
void make_particle_type_exist_local (int type)
void mpi_set_min_global_cut_local (double min_global_cut)
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
double get_min_global_cut ()
Variables
int max_seen_particle_type = 0
Maximal particle type seen so far.
std::vector< IA_parameters > nonbonded_ia_params
static double min_global_cut = INACTIVE_CUTOFF
Minimal global interaction cutoff.
Detailed Description
Implementation of nonbonded_interaction_data.hpp
Definition in file nonbonded_interaction_data.cpp.
Function Documentation
get_ia_param_safe()
IA_parameters* get_ia_param_safe (int i, int j)
Get interaction parameters between particle types i and j.
Slower than get_ia_param, but can also be used on not yet present particle types
Definition at line 98 of file nonbonded_interaction_data.cpp.
References get_ia_param(), and make_particle_type_exist().
Referenced by BMHTF_set_params(), buckingham_set_params(), dpd_set_params(), gaussian_set_params(), gay_berne_set_params(), hat_set_params(), hertzian_set_params(), lennard_jones_set_params(), ljcos2_set_params(), ljcos_set_params(), ljgen_set_params(), morse_set_params(), smooth_step_set_params(), soft_sphere_set_params(), tabulated_set_params(), thole_set_params(), and wca_set_params().
get_min_global_cut()
double get_min_global_cut ()
Definition at line 245 of file nonbonded_interaction_data.cpp.
References min_global_cut.
Referenced by calculate_vs_relate_to_params(), and maximal_cutoff().
ia_params_get_state()
std::string ia_params_get_state ()
Get the state of all non-bonded interactions.
Definition at line 103 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type, and nonbonded_ia_params.
ia_params_set_state()
void ia_params_set_state (std::string const & state)
Set the state of all non-bonded interactions.
Definition at line 111 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type, mpi_bcast_all_ia_params(), mpi_realloc_ia_params(), and nonbonded_ia_params.
is_new_particle_type()
bool is_new_particle_type (int type)
Definition at line 220 of file nonbonded_interaction_data.cpp.
References max_seen_particle_type.
Referenced by make_particle_type_exist(), and make_particle_type_exist_local().
make_particle_type_exist()
void make_particle_type_exist (int type)
Make sure that ia_params is large enough to cover interactions for this particle type.
The interactions are initialized with values such that no physical interaction occurs.
Definition at line 224 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and mpi_realloc_ia_params().
Referenced by get_ia_param_safe(), Collision_parameters::initialize(), on_program_start(), and set_particle_type().
make_particle_type_exist_local()
void make_particle_type_exist_local (int type)
Definition at line 229 of file nonbonded_interaction_data.cpp.
References is_new_particle_type(), and mpi_realloc_ia_params_local().
Referenced by Constraints::ShapeBasedConstraint::set_type().
maximal_cutoff_nonbonded()
double maximal_cutoff_nonbonded ()
Maximal interaction cutoff (real space/short range non-bonded interactions).
Definition at line 204 of file nonbonded_interaction_data.cpp.
References INACTIVE_CUTOFF, nonbonded_ia_params, and recalc_maximal_cutoff().
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and maximal_cutoff().
mpi_bcast_all_ia_params()
void mpi_bcast_all_ia_params () inline
Broadcast nonbonded_ia_params to all nodes.
Definition at line 94 of file nonbonded_interaction_data.cpp.
References mpi_bcast_all_ia_params_local(), and mpi_call_all().
Referenced by ia_params_set_state(), and reset_ia_params().
mpi_bcast_all_ia_params_local()
static void mpi_bcast_all_ia_params_local () static
Definition at line 87 of file nonbonded_interaction_data.cpp.
References comm_cart, and nonbonded_ia_params.
Referenced by mpi_bcast_all_ia_params().
mpi_realloc_ia_params()
void mpi_realloc_ia_params (int new_size) inline
Increase the size of the nonbonded_ia_params vector.
Definition at line 83 of file nonbonded_interaction_data.cpp.
References mpi_call_all(), and mpi_realloc_ia_params_local().
Referenced by ia_params_set_state(), and make_particle_type_exist().
mpi_realloc_ia_params_local()
static void mpi_realloc_ia_params_local (int new_size) static
Definition at line 63 of file nonbonded_interaction_data.cpp.
References get_ia_param(), max_seen_particle_type, nonbonded_ia_params, and Utils::upper_triangular().
Referenced by make_particle_type_exist_local(), and mpi_realloc_ia_params().
mpi_set_min_global_cut()
void mpi_set_min_global_cut (double min_global_cut)
Set and broadcast the min_global_cut.
Parameters
min_global_cut minimum global cutoff
Definition at line 241 of file nonbonded_interaction_data.cpp.
References min_global_cut, mpi_call_all(), and mpi_set_min_global_cut_local().
mpi_set_min_global_cut_local()
void mpi_set_min_global_cut_local (double min_global_cut)
Definition at line 234 of file nonbonded_interaction_data.cpp.
References min_global_cut, and on_skin_change().
Referenced by mpi_set_min_global_cut().
recalc_maximal_cutoff()
static double recalc_maximal_cutoff (const IA_parameters & data) static
Definition at line 123 of file nonbonded_interaction_data.cpp.
References IA_parameters::bmhtf, IA_parameters::buckingham, LJ_Parameters::cut, WCA_Parameters::cut, LJGen_Parameters::cut, SmoothStep_Parameters::cut, Gaussian_Parameters::cut, BMHTF_Parameters::cut, Morse_Parameters::cut, Buckingham_Parameters::cut, SoftSphere_Parameters::cut, LJcos_Parameters::cut, LJcos2_Parameters::cut, GayBerne_Parameters::cut, TabulatedPotential::cutoff(), Coulomb::cutoff(), DPDParameters::cutoff, IA_parameters::dpd_radial, IA_parameters::dpd_trans, IA_parameters::gaussian, IA_parameters::gay_berne, IA_parameters::hat, IA_parameters::hertzian, INACTIVE_CUTOFF, IA_parameters::lj, IA_parameters::ljcos, IA_parameters::ljcos2, IA_parameters::ljgen, IA_parameters::morse, LJ_Parameters::offset, LJGen_Parameters::offset, SoftSphere_Parameters::offset, LJcos_Parameters::offset, LJcos2_Parameters::offset, Hat_Parameters::r, Thole_Parameters::scaling_coeff, Hertzian_Parameters::sig, IA_parameters::smooth_step, IA_parameters::soft_sphere, IA_parameters::tab, IA_parameters::thole, and IA_parameters::wca.
Referenced by maximal_cutoff_nonbonded().
reset_ia_params()
void reset_ia_params ()
Reset all interaction parameters to their defaults.
Definition at line 215 of file nonbonded_interaction_data.cpp.
References mpi_bcast_all_ia_params(), and nonbonded_ia_params.
Variable Documentation
max_seen_particle_type
int max_seen_particle_type = 0
Maximal particle type seen so far.
Definition at line 50 of file nonbonded_interaction_data.cpp.
Referenced by dpd_init(), get_ia_param(), ia_params_get_state(), ia_params_set_state(), is_new_particle_type(), max_non_bonded_pairs(), and mpi_realloc_ia_params_local().
min_global_cut
double min_global_cut = INACTIVE_CUTOFF static
Minimal global interaction cutoff.
Particles with a distance smaller than this are guaranteed to be available on the same node (through ghosts).
Definition at line 57 of file nonbonded_interaction_data.cpp.
Referenced by calculate_vs_relate_to_params(), get_min_global_cut(), mpi_set_min_global_cut(), and mpi_set_min_global_cut_local().
nonbonded_ia_params
std::vector<IA_parameters> nonbonded_ia_params
Definition at line 51 of file nonbonded_interaction_data.cpp.
Referenced by get_ia_param(), ia_params_get_state(), ia_params_set_state(), maximal_cutoff_nonbonded(), mpi_bcast_all_ia_params_local(), mpi_realloc_ia_params_local(), and reset_ia_params().