ESPResSo: nonbonded_tab.hpp File Reference
nonbonded_tab.hpp File Reference
#include "config.hpp"
#include "TabulatedPotential.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <vector>
Functions
int tabulated_set_params (int part_type_a, int part_type_b, double min, double max, std::vector< double > const &energy, std::vector< double > const &force)
Set the parameters of a non-bonded tabulated potential.
double tabulated_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate a non-bonded pair force factor by linear interpolation from a table.
double tabulated_pair_energy (IA_parameters const &ia_params, double dist)
Calculate a non-bonded pair energy by linear interpolation from a table.
Detailed Description
Routines to calculate the energy and/or force for particle pairs via interpolation of lookup tables.
Implementation in nonbonded_tab.cpp. Needs feature TABULATED compiled in (see config.hpp).
Definition in file nonbonded_tab.hpp.
Function Documentation
tabulated_pair_energy()
double tabulated_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate a non-bonded pair energy by linear interpolation from a table.
Definition at line 70 of file nonbonded_tab.hpp.
References TabulatedPotential::cutoff(), TabulatedPotential::energy(), and IA_parameters::tab.
Referenced by calc_non_bonded_pair_energy().
tabulated_pair_force_factor()
double tabulated_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate a non-bonded pair force factor by linear interpolation from a table.
Definition at line 61 of file nonbonded_tab.hpp.
References TabulatedPotential::cutoff(), TabulatedPotential::force(), and IA_parameters::tab.
Referenced by calc_non_bonded_pair_force().
tabulated_set_params()
int tabulated_set_params (int part_type_a, int part_type_b, double min, double max, std::vector< double > const & energy, std::vector< double > const & force)
Set the parameters of a non-bonded tabulated potential.
ia_params and force/energy tables are communicated to each node
Parameters
part_type_a particle type for which the interaction is defined
part_type_b particle type for which the interaction is defined
min Position on the x-axis of the first tabulated value.
max Position on the x-axis of the last tabulated value.
energy Tabulated energies.
force Tabulated forces.
Return values
ES_OK
Definition at line 35 of file nonbonded_tab.cpp.
References ES_OK, force, get_ia_param_safe(), anonymous_namespace{Correlator.cpp}::min(), and mpi_bcast_ia_params().