ESPResSo: npt.cpp File Reference
npt.cpp File Reference
#include "npt.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "electrostatics/coulomb.hpp"
#include "errorhandling.hpp"
#include "event.hpp"
#include "integrate.hpp"
#include "magnetostatics/dipoles.hpp"
#include <utils/Vector.hpp>
#include <boost/mpi/collectives/broadcast.hpp>
#include <algorithm>
#include <cmath>
#include <stdexcept>
Functions
void synchronize_npt_state ()
Synchronizes NpT state such as instantaneous and average pressure.
void mpi_bcast_nptiso_geom_barostat_local ()
void mpi_bcast_nptiso_geom_barostat ()
Broadcast nptiso geometry and barostat parameters to all nodes.
void integrator_npt_coulomb_dipole_sanity_checks (NptIsoParameters const &params)
void nptiso_init (double ext_pressure, double piston, bool xdir_rescale, bool ydir_rescale, bool zdir_rescale, bool cubic_box)
NpT initializer.
void npt_ensemble_init (const BoxGeometry &box)
void integrator_npt_sanity_checks ()
void npt_reset_instantaneous_virials ()
reset virial part of instantaneous pressure
void npt_add_virial_contribution (double energy)
void npt_add_virial_contribution (const Utils::Vector3d &force, const Utils::Vector3d &d)
Variables
NptIsoParameters nptiso
Function Documentation
integrator_npt_coulomb_dipole_sanity_checks()
void integrator_npt_coulomb_dipole_sanity_checks (NptIsoParameters const & params)
Definition at line 76 of file npt.cpp.
References electrostatics_actor, magnetostatics_actor, and params.
Referenced by integrator_npt_sanity_checks(), and nptiso_init().
integrator_npt_sanity_checks()
void integrator_npt_sanity_checks ()
Definition at line 160 of file npt.cpp.
References INTEG_METHOD_NPT_ISO, integ_switch, integrator_npt_coulomb_dipole_sanity_checks(), nptiso, and runtimeErrorMsg.
Referenced by on_integration_start().
mpi_bcast_nptiso_geom_barostat()
void mpi_bcast_nptiso_geom_barostat ()
Broadcast nptiso geometry and barostat parameters to all nodes.
Definition at line 72 of file npt.cpp.
References mpi_bcast_nptiso_geom_barostat_local(), and mpi_call_all().
Referenced by nptiso_init().
mpi_bcast_nptiso_geom_barostat_local()
void mpi_bcast_nptiso_geom_barostat_local ()
Definition at line 59 of file npt.cpp.
References comm_cart, NptIsoParameters::cubic_box, NptIsoParameters::dimension, NptIsoParameters::geometry, NptIsoParameters::non_const_dim, nptiso, on_thermostat_param_change(), NptIsoParameters::p_ext, and NptIsoParameters::piston.
Referenced by mpi_bcast_nptiso_geom_barostat().
npt_add_virial_contribution() [1/2]
void npt_add_virial_contribution (const Utils::Vector3d & force, const Utils::Vector3d & d)
Definition at line 182 of file npt.cpp.
References force, Utils::hadamard_product(), INTEG_METHOD_NPT_ISO, integ_switch, nptiso, and NptIsoParameters::p_vir.
npt_add_virial_contribution() [2/2]
void npt_add_virial_contribution (double energy)
Definition at line 176 of file npt.cpp.
References INTEG_METHOD_NPT_ISO, integ_switch, nptiso, and NptIsoParameters::p_vir.
Referenced by npt_add_virial_force_contribution(), and npt_add_virial_magnetic_contribution().
npt_ensemble_init()
void npt_ensemble_init (const BoxGeometry & box)
Definition at line 147 of file npt.cpp.
References NptIsoParameters::dimension, INTEG_METHOD_NPT_ISO, integ_switch, NptIsoParameters::inv_piston, BoxGeometry::length(), NptIsoParameters::non_const_dim, nptiso, NptIsoParameters::p_inst, NptIsoParameters::p_vel, NptIsoParameters::p_vir, NptIsoParameters::piston, recalc_forces, and NptIsoParameters::volume.
Referenced by on_integration_start().
npt_reset_instantaneous_virials()
void npt_reset_instantaneous_virials ()
reset virial part of instantaneous pressure
Definition at line 171 of file npt.cpp.
References INTEG_METHOD_NPT_ISO, integ_switch, nptiso, and NptIsoParameters::p_vir.
Referenced by init_forces().
nptiso_init()
void nptiso_init (double ext_pressure, double piston, bool xdir_rescale, bool ydir_rescale, bool zdir_rescale, bool cubic_box)
NpT initializer.
Parameters
ext_pressure Reference pressure
piston Piston mass
xdir_rescale Enable box rescaling in the x-direction
ydir_rescale Enable box rescaling in the y-direction
zdir_rescale Enable box rescaling in the z-direction
cubic_box Determines if the volume fluctuations should also apply to dimensions which are switched off by the above flags and which do not contribute to the pressure (3D) or tension (2D, 1D)
Definition at line 93 of file npt.cpp.
References NptIsoParameters::dimension, NptIsoParameters::geometry, integrator_npt_coulomb_dipole_sanity_checks(), NptIsoParameters::inv_piston, mpi_bcast_nptiso_geom_barostat(), NptIsoParameters::non_const_dim, NptIsoParameters::nptgeom_dir, NPTGEOM_XDIR, NPTGEOM_YDIR, NPTGEOM_ZDIR, nptiso, NptIsoParameters::p_diff, NptIsoParameters::p_inst, NptIsoParameters::p_vel, NptIsoParameters::p_vir, and NptIsoParameters::volume.
Referenced by integrate_set_npt_isotropic().
synchronize_npt_state()
void synchronize_npt_state ()
Synchronizes NpT state such as instantaneous and average pressure.
Definition at line 53 of file npt.cpp.
References comm_cart, nptiso, NptIsoParameters::p_diff, NptIsoParameters::p_inst, and NptIsoParameters::volume.
Referenced by integrate().
Variable Documentation
nptiso
NptIsoParameters nptiso
Initial value:
= {0.0,
                           0.0,
                           0.0,
                           0.0,
                           0.0,
                           0.0,
                           {0.0, 0.0, 0.0},
                           {0.0, 0.0, 0.0},
                           0,
                           {NPTGEOM_XDIR, NPTGEOM_YDIR, NPTGEOM_ZDIR},
                           0,
                           false,
                           0}
Definition at line 39 of file npt.cpp.
Referenced by integrator_npt_sanity_checks(), mpi_bcast_nptiso_geom_barostat_local(), npt_add_virial_contribution(), npt_ensemble_init(), npt_reset_instantaneous_virials(), nptiso_init(), synchronize_npt_state(), thermo_init(), velocity_verlet_npt_finalize_p_inst(), velocity_verlet_npt_propagate_pos(), velocity_verlet_npt_propagate_vel(), and velocity_verlet_npt_propagate_vel_final().