ESPResSo: oif_global_forces.cpp File Reference
oif_global_forces.cpp File Reference
#include "oif_global_forces.hpp"
#include "BoxGeometry.hpp"
#include "Particle.hpp"
#include "cell_system/CellStructure.hpp"
#include "communication.hpp"
#include "grid.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/triangle_functions.hpp>
#include <boost/mpi/collectives.hpp>
#include <functional>
Functions
Utils::Vector2d calc_oif_global (int molType, CellStructure &cs)
Calculate the OIF global force.
void add_oif_global_forces (Utils::Vector2d const &area_volume, int molType, CellStructure &cs)
Distribute the OIF global forces to all particles in the mesh.
void mpi_set_max_oif_objects_local (int max_oif_objects)
void mpi_set_max_oif_objects (int max_oif_objects)
Variables
int max_oif_objects = 0
Function Documentation
add_oif_global_forces()
void add_oif_global_forces (Utils::Vector2d const & area_volume, int molType, CellStructure & cs)
Distribute the OIF global forces to all particles in the mesh.
Definition at line 79 of file oif_global_forces.cpp.
References BondedInteractionsMap::at(), CellStructure::bond_loop(), bonded_ia_params, if(), and Particle::mol_id().
Referenced by force_calc().
calc_oif_global()
Utils::Vector2d calc_oif_global (int molType, CellStructure & cs)
Calculate the OIF global force.
Called in force_calc() from within forces.cpp
calculates the global area and global volume for a cell before the forces are handled
MPI synchronization with all reduce
!!! loop over particles from regular_decomposition !!!
Definition at line 42 of file oif_global_forces.cpp.
References BondedInteractionsMap::at(), CellStructure::bond_loop(), bonded_ia_params, comm_cart, if(), and Particle::mol_id().
Referenced by force_calc().
mpi_set_max_oif_objects()
void mpi_set_max_oif_objects (int max_oif_objects)
Definition at line 139 of file oif_global_forces.cpp.
References max_oif_objects, mpi_call_all(), and mpi_set_max_oif_objects_local().
mpi_set_max_oif_objects_local()
void mpi_set_max_oif_objects_local (int max_oif_objects)
Definition at line 133 of file oif_global_forces.cpp.
References max_oif_objects.
Referenced by mpi_set_max_oif_objects().
Variable Documentation
max_oif_objects
int max_oif_objects = 0
Definition at line 131 of file oif_global_forces.cpp.
Referenced by force_calc(), mpi_set_max_oif_objects(), and mpi_set_max_oif_objects_local().