ESPResSo: oif_global_forces.hpp File Reference
oif_global_forces.hpp File Reference
Routines to calculate the OIF global forces energy or/and and force for a particle triple (triangle from mesh).
#include "BoxGeometry.hpp"
#include "cell_system/CellStructure.hpp"
#include "oif_global_forces_params.hpp"
#include <utils/Vector.hpp>
Functions
Utils::Vector2d calc_oif_global (int molType, BoxGeometry const &box_geo, CellStructure &cs)
Calculate the OIF global force.
void add_oif_global_forces (Utils::Vector2d const &area_volume, int molType, BoxGeometry const &box_geo, CellStructure &cs)
Distribute the OIF global forces to all particles in the mesh.
Variables
int max_oif_objects
Detailed Description
Routines to calculate the OIF global forces energy or/and and force for a particle triple (triangle from mesh).
See [14].
Definition in file oif_global_forces.hpp.
Function Documentation
add_oif_global_forces()
void add_oif_global_forces (Utils::Vector2d const & area_volume, int molType, BoxGeometry const & box_geo, CellStructure & cs)
Distribute the OIF global forces to all particles in the mesh.
Definition at line 70 of file oif_global_forces.cpp.
References Utils::area_triangle(), BondedInteractionsMap::at(), CellStructure::bond_loop(), bonded_ia_params, Particle::force(), BoxGeometry::get_mi_vector(), Utils::get_n_triangle(), Particle::image_box(), Particle::mol_id(), Utils::Vector< T, N >::normalize(), Particle::pos(), and BoxGeometry::unfolded_position().
Referenced by System::System::calculate_forces().
calc_oif_global()
Utils::Vector2d calc_oif_global (int molType, BoxGeometry const & box_geo, CellStructure & cs)
Calculate the OIF global force.
Called in force_calc() from within forces.cpp
calculates the global area and global volume for a cell before the forces are handled
MPI synchronization with all reduce
!!! loop over particles from regular_decomposition !!!
Definition at line 35 of file oif_global_forces.cpp.
References Utils::area_triangle(), BondedInteractionsMap::at(), CellStructure::bond_loop(), bonded_ia_params, BoxGeometry::get_mi_vector(), Utils::get_n_triangle(), Particle::image_box(), Particle::mol_id(), Particle::pos(), and BoxGeometry::unfolded_position().
Referenced by System::System::calculate_forces().
Variable Documentation
max_oif_objects
int max_oif_objects extern
Definition at line 33 of file oif_global_forces.cpp.
Referenced by System::System::calculate_forces().