ESPResSo: particle_data.hpp File Reference
particle_data.hpp File Reference
#include "config.hpp"
#include "Particle.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/quaternion.hpp>
#include <vector>
Functions
void set_particle_v (int part, Utils::Vector3d const &v)
Call only on the head node: set particle velocity.
void set_particle_lees_edwards_offset (int part, double v)
Call only on the head node: set particle Lees-Edwards offset.
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the head node: set particle velocity.
void set_particle_f (int part, const Utils::Vector3d &F)
Call only on the head node: set particle force.
void set_particle_mass (int part, double mass)
Call only on the head node: set particle mass.
void set_particle_rotational_inertia (int part, Utils::Vector3d const &rinertia)
Call only on the head node: set particle rotational inertia.
void set_particle_rotation (int part, Utils::Vector3i const &flag)
Call only on the head node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
void rotate_particle (int part, const Utils::Vector3d &axis, double angle)
rotate a particle around an axis
void set_particle_q (int part, double q)
Call only on the head node: set particle charge.
void set_particle_mu_E (int part, Utils::Vector3d const &mu_E)
Call only on the head node: set particle electrophoretic mobility.
void set_particle_type (int p_id, int type)
Call only on the head node: set particle type.
void set_particle_mol_id (int part, int mid)
Call only on the head node: set particle's molecule id.
void set_particle_quat (int part, Utils::Quaternion< double > const &quat)
Call only on the head node: set particle orientation using quaternions.
void set_particle_director (int part, const Utils::Vector3d &director)
Call only on the head node: set particle orientation using director.
void set_particle_omega_lab (int part, const Utils::Vector3d &omega_lab)
Call only on the head node: set particle angular velocity from lab frame.
void set_particle_omega_body (int part, const Utils::Vector3d &omega)
Call only on the head node: set particle angular velocity in body frame.
void set_particle_torque_lab (int part, const Utils::Vector3d &torque_lab)
Call only on the head node: set particle torque from lab frame.
void set_particle_dip (int part, Utils::Vector3d const &dip)
Call only on the head node: set particle dipole orientation.
void set_particle_dipm (int part, double dipm)
Call only on the head node: set particle dipole moment (absolute value).
void set_particle_virtual (int part, bool is_virtual)
Call only on the head node: set particle virtual flag.
void set_particle_vs_quat (int part, Utils::Quaternion< double > const &vs_relative_quat)
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const &rel_ori)
void set_particle_gamma (int part, Utils::Vector3d const &gamma)
Call only on the head node: set particle frictional coefficient.
void set_particle_gamma_rot (int part, Utils::Vector3d const &gamma_rot)
void set_particle_ext_torque (int part, const Utils::Vector3d &torque)
Call only on the head node: set particle external torque.
void set_particle_ext_force (int part, const Utils::Vector3d &force)
Call only on the head node: set particle external force.
void set_particle_fix (int part, Utils::Vector3i const &flag)
Call only on the head node: set coordinate axes for which the particles motion is fixed.
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: remove bond from particle.
void delete_particle_bonds (int part)
Call only on the head node: remove all bonds from particle.
void local_remove_bond (Particle &p, std::vector< int > const &bond)
Remove the specified bond from the particle.
void local_remove_pair_bonds_to (Particle &p, int other_pid)
Remove all pair bonds on the particle which have the specified particle id as partner.
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: Add bond to particle.
const std::vector< BondView > & get_particle_bonds (int part)
void remove_particle_exclusion (int part1, int part2)
Remove particle exclusion.
void add_particle_exclusion (int part1, int part2)
Add particle exclusion.
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
Utils::Quaternion< double > get_particle_vs_quat (Particle const *p)
Utils::Quaternion< double > get_particle_vs_relative (Particle const *p, int &vs_relative_to, double &vs_distance)
Utils::Vector3i get_particle_fix (Particle const *p)
Utils::Vector3d get_particle_gamma (Particle const *p)
Utils::Vector3d get_particle_gamma_rot (Particle const *p)
Utils::Vector3i get_particle_rotation (Particle const *p)
Detailed Description
Particles property access.
This file contains everything related to particle properties. If you want to add a new property to the particles, it is probably a good idea to modify Particle to give scripts access to that property. You always have to modify two positions: first the print section, where you should add your new data at the end, and second the read section where you have to find a nice and short name for your property to appear in the Python code.
Definition in file particle_data.hpp.
Function Documentation
add_particle_bond()
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: Add bond to particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 632 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
add_particle_exclusion()
void add_particle_exclusion (int part1, int part2)
Add particle exclusion.
Call only on the head node.
Parameters
part1 identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set.
Definition at line 762 of file particle_data.cpp.
References mpi_add_exclusion_local(), mpi_call_all(), and particle_exclusion_sanity_checks().
Referenced by auto_exclusions().
auto_exclusions()
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
This uses the bond topology obtained directly from the particles. To easily setup the bonds, all data should be on a single node, therefore the partCfg array is used. With large amounts of particles, you should avoid this function and setup exclusions manually.
Definition at line 767 of file particle_data.cpp.
References add_particle_exclusion(), add_partner(), Particle::id(), and partCfg().
delete_particle_bond()
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: remove bond from particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 623 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
delete_particle_bonds()
void delete_particle_bonds (int part)
Call only on the head node: remove all bonds from particle.
Parameters
part identity of principal atom of the bond.
Definition at line 628 of file particle_data.cpp.
References mpi_send_update_message().
get_particle_bonds()
const std::vector<BondView>& get_particle_bonds (int part)
Definition at line 637 of file particle_data.cpp.
References get_particle_data().
get_particle_fix()
Utils::Vector3i get_particle_fix (Particle const * p) inline
Definition at line 309 of file particle_data.hpp.
References Particle::is_fixed_along().
get_particle_gamma()
Utils::Vector3d get_particle_gamma (Particle const * p) inline
Definition at line 317 of file particle_data.hpp.
References Particle::gamma().
get_particle_gamma_rot()
Utils::Vector3d get_particle_gamma_rot (Particle const * p) inline
Definition at line 325 of file particle_data.hpp.
References Particle::gamma_rot().
get_particle_rotation()
Utils::Vector3i get_particle_rotation (Particle const * p) inline
Definition at line 337 of file particle_data.hpp.
References Particle::can_rotate_around().
get_particle_vs_quat()
Utils::Quaternion<double> get_particle_vs_quat (Particle const * p) inline
Definition at line 296 of file particle_data.hpp.
References Particle::vs_relative().
get_particle_vs_relative()
Utils::Quaternion<double> get_particle_vs_relative (Particle const * p, int & vs_relative_to, double & vs_distance) inline
Definition at line 299 of file particle_data.hpp.
References Particle::vs_relative().
local_remove_bond()
void local_remove_bond (Particle & p, std::vector< int > const & bond)
Remove the specified bond from the particle.
Parameters
p The particle to update
bond The bond in the form {bond_id, partner_1, partner_2, ...}
Definition at line 338 of file particle_data.cpp.
local_remove_pair_bonds_to()
void local_remove_pair_bonds_to (Particle & p, int other_pid)
Remove all pair bonds on the particle which have the specified particle id as partner.
Parameters
p The particle to update
other_pid The particle id to filter for
Definition at line 342 of file particle_data.cpp.
mpi_rescale_particles()
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
Definition at line 669 of file particle_data.cpp.
References comm_cart, local_rescale_particles(), mpi_call(), mpi_rescale_particles_local(), n_nodes, on_particle_change(), some_tag, and this_node.
Referenced by rescale_boxl().
remove_particle_exclusion()
void remove_particle_exclusion (int part1, int part2)
Remove particle exclusion.
Call only on the head node.
Parameters
part1 identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set.
Definition at line 757 of file particle_data.cpp.
References mpi_call_all(), mpi_remove_exclusion_local(), and particle_exclusion_sanity_checks().
rotate_particle()
void rotate_particle (int part, const Utils::Vector3d & axis, double angle)
rotate a particle around an axis
Parameters
part particle id
axis rotation axis
angle rotation angle
Definition at line 458 of file particle_data.cpp.
References mpi_send_update_message().
set_particle_dip()
void set_particle_dip (int part, Utils::Vector3d const & dip)
Call only on the head node: set particle dipole orientation.
Parameters
part the particle.
dip its new dipole orientation.
Definition at line 468 of file particle_data.cpp.
References convert_dip_to_quat(), set_particle_dipm(), and set_particle_quat().
set_particle_dipm()
void set_particle_dipm (int part, double dipm)
Call only on the head node: set particle dipole moment (absolute value).
Parameters
part the particle.
dipm its new dipole moment.
Definition at line 464 of file particle_data.cpp.
Referenced by set_particle_dip().
set_particle_director()
void set_particle_director (int part, const Utils::Vector3d & director)
Call only on the head node: set particle orientation using director.
The particle director defines the z-axis in the body-fixed frame.
Parameters
part the particle.
director its new director vector (will be normalized if necessary)
Definition at line 542 of file particle_data.cpp.
References Utils::convert_director_to_quaternion(), Utils::Vector< T, N >::normalized(), and set_particle_quat().
set_particle_ext_force()
void set_particle_ext_force (int part, const Utils::Vector3d & force)
Call only on the head node: set particle external force.
Parameters
part the particle.
force new value for ext_force.
Definition at line 605 of file particle_data.cpp.
References force.
set_particle_ext_torque()
void set_particle_ext_torque (int part, const Utils::Vector3d & torque)
Call only on the head node: set particle external torque.
Parameters
part the particle.
torque new value for ext_torque.
Definition at line 599 of file particle_data.cpp.
References ParticleProperties::ext_torque, mpi_update_particle_property(), and torque.
set_particle_f()
void set_particle_f (int part, const Utils::Vector3d & F)
Call only on the head node: set particle force.
Parameters
part the particle.
F its new force.
Definition at line 422 of file particle_data.cpp.
References ParticleForce::f, Particle::f, f, and mpi_update_particle().
set_particle_fix()
void set_particle_fix (int part, Utils::Vector3i const & flag)
Call only on the head node: set coordinate axes for which the particles motion is fixed.
Parameters
part the particle.
flag coordinates to be fixed.
Definition at line 610 of file particle_data.cpp.
References u.
set_particle_gamma()
void set_particle_gamma (int part, Utils::Vector3d const & gamma)
Call only on the head node: set particle frictional coefficient.
Parameters
part the particle.
gamma its new frictional coefficient.
Definition at line 576 of file particle_data.cpp.
References Utils::gamma().
set_particle_gamma_rot()
void set_particle_gamma_rot (int part, Utils::Vector3d const & gamma_rot)
Definition at line 589 of file particle_data.cpp.
set_particle_lees_edwards_offset()
void set_particle_lees_edwards_offset (int part, double v)
Call only on the head node: set particle Lees-Edwards offset.
Parameters
part the particle.
v new value for Lees-Edwards offset
Definition at line 410 of file particle_data.cpp.
References Particle::l, ParticleLocal::lees_edwards_offset, and mpi_update_particle().
set_particle_mass()
void set_particle_mass (int part, double mass)
Call only on the head node: set particle mass.
Parameters
part the particle.
mass its new mass.
Definition at line 428 of file particle_data.cpp.
set_particle_mol_id()
void set_particle_mol_id (int part, int mid)
Call only on the head node: set particle's molecule id.
Parameters
part the particle.
mid its new mol id.
Definition at line 532 of file particle_data.cpp.
set_particle_mu_E()
void set_particle_mu_E (int part, Utils::Vector3d const & mu_E)
Call only on the head node: set particle electrophoretic mobility.
Parameters
part the particle.
mu_E its new mobility.
Definition at line 520 of file particle_data.cpp.
set_particle_omega_body()
void set_particle_omega_body (int part, const Utils::Vector3d & omega)
Call only on the head node: set particle angular velocity in body frame.
Parameters
part the particle.
omega its new angular velocity.
Definition at line 556 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_omega_lab()
void set_particle_omega_lab (int part, const Utils::Vector3d & omega_lab)
Call only on the head node: set particle angular velocity from lab frame.
Parameters
part the particle.
omega_lab its new angular velocity.
Definition at line 548 of file particle_data.cpp.
References convert_vector_space_to_body(), get_particle_data(), Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_q()
void set_particle_q (int part, double q)
Call only on the head node: set particle charge.
Parameters
part the particle.
q its new charge.
Definition at line 509 of file particle_data.cpp.
Referenced by ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_quat()
void set_particle_quat (int part, Utils::Quaternion< double > const & quat)
Call only on the head node: set particle orientation using quaternions.
Parameters
part the particle.
quat its new value for quaternions.
Definition at line 537 of file particle_data.cpp.
References ParticlePosition::quat.
Referenced by set_particle_dip(), and set_particle_director().
set_particle_rotation()
void set_particle_rotation (int part, Utils::Vector3i const & flag)
Call only on the head node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
If set to zero, the content of the torque and omega variables are meaningless
Parameters
part the particle.
flag the degrees of freedom flag.
Definition at line 446 of file particle_data.cpp.
References u.
set_particle_rotational_inertia()
void set_particle_rotational_inertia (int part, Utils::Vector3d const & rinertia)
Call only on the head node: set particle rotational inertia.
Parameters
part the particle.
rinertia its new inertia.
Definition at line 436 of file particle_data.cpp.
set_particle_swimming()
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the head node: set particle velocity.
Parameters
part the particle.
swim struct containing swimming parameters
Definition at line 416 of file particle_data.cpp.
References mpi_update_particle_property(), and ParticleProperties::swim.
set_particle_torque_lab()
void set_particle_torque_lab (int part, const Utils::Vector3d & torque_lab)
Call only on the head node: set particle torque from lab frame.
Parameters
part the particle.
torque_lab its new torque.
Definition at line 561 of file particle_data.cpp.
References convert_vector_space_to_body(), Particle::f, get_particle_data(), mpi_update_particle(), and ParticleForce::torque.
set_particle_type()
void set_particle_type (int p_id, int type)
Call only on the head node: set particle type.
Parameters
p_id the particle.
type its new type.
Definition at line 526 of file particle_data.cpp.
References make_particle_type_exist(), and on_particle_type_change().
Referenced by ReactionMethods::ReactionAlgorithm::generic_oneway_reaction(), and ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_v()
void set_particle_v (int part, Utils::Vector3d const & v)
Call only on the head node: set particle velocity.
Parameters
part the particle.
v its new velocity.
Definition at line 405 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::v.
set_particle_virtual()
void set_particle_virtual (int part, bool is_virtual)
Call only on the head node: set particle virtual flag.
Parameters
part the particle.
is_virtual new is_virtual flag.
Definition at line 479 of file particle_data.cpp.
Referenced by vs_relate_to().
set_particle_vs_quat()
void set_particle_vs_quat (int part, Utils::Quaternion< double > const & vs_relative_quat)
Definition at line 486 of file particle_data.cpp.
References get_particle_data(), mpi_update_particle_property(), ParticleProperties::vs_relative, and Particle::vs_relative().
set_particle_vs_relative()
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const & rel_ori)
Definition at line 496 of file particle_data.cpp.
References ParticleProperties::VirtualSitesRelativeParameters::distance, mpi_update_particle_property(), ParticleProperties::VirtualSitesRelativeParameters::rel_orientation, ParticleProperties::VirtualSitesRelativeParameters::to_particle_id, and ParticleProperties::vs_relative.
Referenced by vs_relate_to().