ESPResSo: particle_data.cpp File Reference
particle_data.cpp File Reference
#include "particle_data.hpp"
#include "Particle.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "event.hpp"
#include "exclusions.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "partCfg_global.hpp"
#include "particle_node.hpp"
#include "rotation.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <utils/quaternion.hpp>
#include <boost/range/algorithm/copy.hpp>
#include <boost/range/algorithm/find.hpp>
#include <boost/serialization/variant.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/variant.hpp>
#include <iterator>
#include <stdexcept>
#include <tuple>
#include <unordered_map>
#include <vector>
Namespaces
anonymous_namespace{particle_data.cpp}
Typedefs
template<typename T , T ParticleProperties::* m>
using anonymous_namespace{particle_data.cpp}::UpdateProperty = UpdateParticle< ParticleProperties, &Particle::p, T, m >
template<typename T , T ParticleLocal::* m>
using anonymous_namespace{particle_data.cpp}::UpdateLocalProperty = UpdateParticle< ParticleLocal, &Particle::l, T, m >
template<typename T , T ParticlePosition ::* m>
using anonymous_namespace{particle_data.cpp}::UpdatePosition = UpdateParticle< ParticlePosition, &Particle::r, T, m >
template<typename T , T ParticleMomentum ::* m>
using anonymous_namespace{particle_data.cpp}::UpdateMomentum = UpdateParticle< ParticleMomentum, &Particle::m, T, m >
template<typename T , T ParticleForce ::* m>
using anonymous_namespace{particle_data.cpp}::UpdateForce = UpdateParticle< ParticleForce, &Particle::f, T, m >
using anonymous_namespace{particle_data.cpp}::Prop = ParticleProperties
using anonymous_namespace{particle_data.cpp}::UpdatePropertyMessage = boost::variant< UpdateProperty< int, &Prop::type >, UpdateProperty< int, &Prop::mol_id >, UpdateProperty< double, &Prop::mass >, UpdateProperty< Utils::Vector3d, &Prop::rinertia >, UpdateProperty< uint8_t, &Prop::rotation >, UpdateProperty< double, &Prop::q >, UpdateProperty< Utils::Vector3d, &Prop::mu_E >, UpdateProperty< ParticleParametersSwimming, &Prop::swim >, UpdateProperty< double, &Prop::dipm >, UpdateProperty< bool, &Prop::is_virtual >, UpdateProperty< ParticleProperties::VirtualSitesRelativeParameters, &Prop::vs_relative >, UpdateProperty< Utils::Vector3d, &Prop::gamma >, UpdateProperty< Utils::Vector3d, &Prop::gamma_rot >, UpdateProperty< uint8_t, &Prop::ext_flag >, UpdateProperty< Utils::Vector3d, &Prop::ext_force >, UpdateProperty< Utils::Vector3d, &Prop::ext_torque > >
using anonymous_namespace{particle_data.cpp}::UpdateLocalPropertyMessage = boost::variant< UpdateLocalProperty< double, &ParticleLocal::lees_edwards_offset > >
using anonymous_namespace{particle_data.cpp}::UpdatePositionMessage = boost::variant< UpdatePosition< Utils::Vector3d, &ParticlePosition::p >, UpdatePosition< Utils::Quaternion< double >, &ParticlePosition::quat > >
using anonymous_namespace{particle_data.cpp}::UpdateMomentumMessage = boost::variant< UpdateMomentum< Utils::Vector3d, &ParticleMomentum::v >, UpdateMomentum< Utils::Vector3d, &ParticleMomentum::omega > >
using anonymous_namespace{particle_data.cpp}::UpdateForceMessage = boost::variant< UpdateForce< Utils::Vector3d, &ParticleForce::f >, UpdateForce< Utils::Vector3d, &ParticleForce::torque > >
using anonymous_namespace{particle_data.cpp}::UpdateBondMessage = boost::variant< RemoveBond, RemoveBonds, AddBond >
using anonymous_namespace{particle_data.cpp}::UpdateMessage = boost::variant< UpdateLocalPropertyMessage, UpdatePropertyMessage, UpdatePositionMessage, UpdateMomentumMessage, UpdateForceMessage, UpdateBondMessage, UpdateOrientation >
Top-level message.
template<typename S , S Particle::* s>
using anonymous_namespace{particle_data.cpp}::message_type_t = typename message_type< S, s >::type
Functions
void local_remove_bond (Particle &p, std::vector< int > const &bond)
Remove the specified bond from the particle.
void local_remove_pair_bonds_to (Particle &p, int other_pid)
Remove all pair bonds on the particle which have the specified particle id as partner.
static void mpi_send_update_message_local (int node, int id)
static void mpi_send_update_message (int id, const UpdateMessage &msg)
Send a particle update message.
template<typename S , S Particle::* s, typename T , T S::* m>
void mpi_update_particle (int id, const T &value)
template<typename T , T ParticleProperties::* m>
void mpi_update_particle_property (int id, const T &value)
void set_particle_v (int part, Utils::Vector3d const &v)
Call only on the head node: set particle velocity.
void set_particle_lees_edwards_offset (int part, const double v)
Call only on the head node: set particle Lees-Edwards offset.
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the head node: set particle velocity.
void set_particle_f (int part, const Utils::Vector3d &f)
Call only on the head node: set particle force.
void set_particle_mass (int part, double mass)
Call only on the head node: set particle mass.
void set_particle_rotational_inertia (int part, Utils::Vector3d const &rinertia)
Call only on the head node: set particle rotational inertia.
void set_particle_rotation (int part, Utils::Vector3i const &flag)
Call only on the head node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
void rotate_particle (int part, const Utils::Vector3d &axis, double angle)
rotate a particle around an axis
void set_particle_dipm (int part, double dipm)
Call only on the head node: set particle dipole moment (absolute value).
void set_particle_dip (int part, Utils::Vector3d const &dip)
Call only on the head node: set particle dipole orientation.
void set_particle_virtual (int part, bool is_virtual)
Call only on the head node: set particle virtual flag.
void set_particle_vs_quat (int part, Utils::Quaternion< double > const &vs_relative_quat)
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const &rel_ori)
void set_particle_q (int part, double q)
Call only on the head node: set particle charge.
void set_particle_mu_E (int part, Utils::Vector3d const &mu_E)
Call only on the head node: set particle electrophoretic mobility.
void set_particle_type (int p_id, int type)
Call only on the head node: set particle type.
void set_particle_mol_id (int part, int mid)
Call only on the head node: set particle's molecule id.
void set_particle_quat (int part, Utils::Quaternion< double > const &quat)
Call only on the head node: set particle orientation using quaternions.
void set_particle_director (int part, const Utils::Vector3d &director)
Call only on the head node: set particle orientation using director.
void set_particle_omega_lab (int part, const Utils::Vector3d &omega_lab)
Call only on the head node: set particle angular velocity from lab frame.
void set_particle_omega_body (int part, const Utils::Vector3d &omega)
Call only on the head node: set particle angular velocity in body frame.
void set_particle_torque_lab (int part, const Utils::Vector3d &torque_lab)
Call only on the head node: set particle torque from lab frame.
void set_particle_gamma (int part, Utils::Vector3d const &gamma)
Call only on the head node: set particle frictional coefficient.
void set_particle_gamma_rot (int part, Utils::Vector3d const &gamma_rot)
void set_particle_ext_torque (int part, const Utils::Vector3d &torque)
Call only on the head node: set particle external torque.
void set_particle_ext_force (int part, const Utils::Vector3d &force)
Call only on the head node: set particle external force.
void set_particle_fix (int part, Utils::Vector3i const &flag)
Call only on the head node: set coordinate axes for which the particles motion is fixed.
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: remove bond from particle.
void delete_particle_bonds (int part)
Call only on the head node: remove all bonds from particle.
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: Add bond to particle.
const std::vector< BondView > & get_particle_bonds (int part)
void local_rescale_particles (int dir, double scale)
Locally rescale all particles on current node.
static void mpi_rescale_particles_local (int dir)
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
static void local_remove_exclusion (int part1, int part2)
Locally remove an exclusion to a particle.
static void local_add_exclusion (int part1, int part2)
Locally add an exclusion to a particle.
static void add_partner (std::vector< int > &il, int i, int j, int distance)
static void mpi_remove_exclusion_local (int part1, int part2)
static void mpi_add_exclusion_local (int part1, int part2)
static void check_particle_exists (int p_id)
static void particle_exclusion_sanity_checks (int part1, int part2)
void remove_particle_exclusion (int part1, int part2)
Remove particle exclusion.
void add_particle_exclusion (int part1, int part2)
Add particle exclusion.
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
Variables
constexpr auto some_tag = 42
Function Documentation
add_particle_bond()
void add_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: Add bond to particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 632 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
add_particle_exclusion()
void add_particle_exclusion (int part1, int part2)
Add particle exclusion.
Call only on the head node.
Parameters
part1 identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set.
Definition at line 762 of file particle_data.cpp.
References mpi_add_exclusion_local(), mpi_call_all(), and particle_exclusion_sanity_checks().
Referenced by auto_exclusions().
add_partner()
static void add_partner (std::vector< int > & il, int i, int j, int distance) static
Definition at line 716 of file particle_data.cpp.
Referenced by auto_exclusions().
auto_exclusions()
void auto_exclusions (int distance)
Automatically add the next <distance> neighbors in each molecule to the exclusion list.
This uses the bond topology obtained directly from the particles. To easily setup the bonds, all data should be on a single node, therefore the partCfg array is used. With large amounts of particles, you should avoid this function and setup exclusions manually.
Definition at line 767 of file particle_data.cpp.
References add_particle_exclusion(), add_partner(), Particle::id(), and partCfg().
check_particle_exists()
static void check_particle_exists (int p_id) static
Definition at line 741 of file particle_data.cpp.
References particle_exists().
Referenced by particle_exclusion_sanity_checks().
delete_particle_bond()
void delete_particle_bond (int part, Utils::Span< const int > bond)
Call only on the head node: remove bond from particle.
Parameters
part identity of principal atom of the bond.
bond field containing the bond type number and the identity of all bond partners (secondary atoms of the bond).
Definition at line 623 of file particle_data.cpp.
References Utils::Span< T >::begin(), Utils::Span< T >::end(), and mpi_send_update_message().
delete_particle_bonds()
void delete_particle_bonds (int part)
Call only on the head node: remove all bonds from particle.
Parameters
part identity of principal atom of the bond.
Definition at line 628 of file particle_data.cpp.
References mpi_send_update_message().
get_particle_bonds()
const std::vector<BondView>& get_particle_bonds (int part)
Definition at line 637 of file particle_data.cpp.
References get_particle_data().
local_add_exclusion()
static void local_add_exclusion (int part1, int part2) static
Locally add an exclusion to a particle.
Parameters
part1 the identity of the first exclusion partner
part2 the identity of the second exclusion partner
Definition at line 703 of file particle_data.cpp.
References add_exclusion(), cell_structure, and CellStructure::get_local_particle().
Referenced by mpi_add_exclusion_local().
local_remove_bond()
void local_remove_bond (Particle & p, std::vector< int > const & bond)
Remove the specified bond from the particle.
Parameters
p The particle to update
bond The bond in the form {bond_id, partner_1, partner_2, ...}
Definition at line 338 of file particle_data.cpp.
local_remove_exclusion()
static void local_remove_exclusion (int part1, int part2) static
Locally remove an exclusion to a particle.
Parameters
part1 the identity of the first exclusion partner
part2 the identity of the second exclusion partner
Definition at line 687 of file particle_data.cpp.
References cell_structure, delete_exclusion(), and CellStructure::get_local_particle().
Referenced by mpi_remove_exclusion_local().
local_remove_pair_bonds_to()
void local_remove_pair_bonds_to (Particle & p, int other_pid)
Remove all pair bonds on the particle which have the specified particle id as partner.
Parameters
p The particle to update
other_pid The particle id to filter for
Definition at line 342 of file particle_data.cpp.
local_rescale_particles()
void local_rescale_particles (int dir, double scale)
Locally rescale all particles on current node.
Parameters
dir direction to scale (0/1/2 = x/y/z, 3 = x+y+z isotropically)
scale factor by which to rescale (>1: stretch, <1: contract)
Definition at line 650 of file particle_data.cpp.
References cell_structure, CellStructure::local_particles(), and Particle::pos().
Referenced by mpi_rescale_particles(), and mpi_rescale_particles_local().
mpi_add_exclusion_local()
static void mpi_add_exclusion_local (int part1, int part2) static
Definition at line 734 of file particle_data.cpp.
References local_add_exclusion(), and on_particle_change().
Referenced by add_particle_exclusion().
mpi_remove_exclusion_local()
static void mpi_remove_exclusion_local (int part1, int part2) static
Definition at line 727 of file particle_data.cpp.
References local_remove_exclusion(), and on_particle_change().
Referenced by remove_particle_exclusion().
mpi_rescale_particles()
void mpi_rescale_particles (int dir, double scale)
Rescale all particle positions in direction dir by a factor scale.
Definition at line 669 of file particle_data.cpp.
References comm_cart, local_rescale_particles(), mpi_call(), mpi_rescale_particles_local(), n_nodes, on_particle_change(), some_tag, and this_node.
Referenced by rescale_boxl().
mpi_rescale_particles_local()
static void mpi_rescale_particles_local (int dir) static
Definition at line 660 of file particle_data.cpp.
References comm_cart, local_rescale_particles(), on_particle_change(), and some_tag.
Referenced by mpi_rescale_particles().
mpi_send_update_message()
static void mpi_send_update_message (int id, const UpdateMessage & msg) static
Send a particle update message.
This sends the message to the node that is responsible for the particle, where msg is called with the particle as argument. The message then performs the change to the particle that is encoded in it. The mechanism to call a functor based on the active type of a variant is called visitation. Here we can use UpdateVisitor with a single templated call operator on the visitor because all message (eventually) provide the same interface. Overall this is logically equivalent to nested switch statements over the message types, where the case statements play the role of the call of the messages in our case. A general introduction can be found in the documentation of boost::variant.
Parameters
id Id of the particle to update
msg The message
Definition at line 376 of file particle_data.cpp.
References comm_cart, get_particle_node(), mpi_call(), mpi_send_update_message_local(), on_particle_change(), and some_tag.
Referenced by add_particle_bond(), delete_particle_bond(), delete_particle_bonds(), mpi_update_particle(), and rotate_particle().
mpi_send_update_message_local()
static void mpi_send_update_message_local (int node, int id) static
Definition at line 346 of file particle_data.cpp.
References comm_cart, node, on_particle_change(), and some_tag.
Referenced by mpi_send_update_message().
mpi_update_particle()
template<typename S , S Particle::* s, typename T , T S::* m> void mpi_update_particle (int id, const T & value)
Definition at line 394 of file particle_data.cpp.
References mpi_send_update_message().
Referenced by set_particle_f(), set_particle_lees_edwards_offset(), set_particle_omega_body(), set_particle_omega_lab(), set_particle_torque_lab(), and set_particle_v().
mpi_update_particle_property()
template<typename T , T ParticleProperties::* m> void mpi_update_particle_property (int id, const T & value)
Definition at line 401 of file particle_data.cpp.
Referenced by set_particle_ext_torque(), set_particle_swimming(), set_particle_vs_quat(), and set_particle_vs_relative().
particle_exclusion_sanity_checks()
static void particle_exclusion_sanity_checks (int part1, int part2) static
Definition at line 748 of file particle_data.cpp.
References check_particle_exists().
Referenced by add_particle_exclusion(), and remove_particle_exclusion().
remove_particle_exclusion()
void remove_particle_exclusion (int part1, int part2)
Remove particle exclusion.
Call only on the head node.
Parameters
part1 identity of particle for which the exclusion is set.
part2 identity of particle for which the exclusion is set.
Definition at line 757 of file particle_data.cpp.
References mpi_call_all(), mpi_remove_exclusion_local(), and particle_exclusion_sanity_checks().
rotate_particle()
void rotate_particle (int part, const Utils::Vector3d & axis, double angle)
rotate a particle around an axis
Parameters
part particle id
axis rotation axis
angle rotation angle
Definition at line 458 of file particle_data.cpp.
References mpi_send_update_message().
set_particle_dip()
void set_particle_dip (int part, Utils::Vector3d const & dip)
Call only on the head node: set particle dipole orientation.
Parameters
part the particle.
dip its new dipole orientation.
Definition at line 468 of file particle_data.cpp.
References convert_dip_to_quat(), set_particle_dipm(), and set_particle_quat().
set_particle_dipm()
void set_particle_dipm (int part, double dipm)
Call only on the head node: set particle dipole moment (absolute value).
Parameters
part the particle.
dipm its new dipole moment.
Definition at line 464 of file particle_data.cpp.
Referenced by set_particle_dip().
set_particle_director()
void set_particle_director (int part, const Utils::Vector3d & director)
Call only on the head node: set particle orientation using director.
The particle director defines the z-axis in the body-fixed frame.
Parameters
part the particle.
director its new director vector (will be normalized if necessary)
Definition at line 542 of file particle_data.cpp.
References Utils::convert_director_to_quaternion(), Utils::Vector< T, N >::normalized(), and set_particle_quat().
set_particle_ext_force()
void set_particle_ext_force (int part, const Utils::Vector3d & force)
Call only on the head node: set particle external force.
Parameters
part the particle.
force new value for ext_force.
Definition at line 605 of file particle_data.cpp.
References force.
set_particle_ext_torque()
void set_particle_ext_torque (int part, const Utils::Vector3d & torque)
Call only on the head node: set particle external torque.
Parameters
part the particle.
torque new value for ext_torque.
Definition at line 599 of file particle_data.cpp.
References ParticleProperties::ext_torque, mpi_update_particle_property(), and torque.
set_particle_f()
void set_particle_f (int part, const Utils::Vector3d & F)
Call only on the head node: set particle force.
Parameters
part the particle.
F its new force.
Definition at line 422 of file particle_data.cpp.
References ParticleForce::f, Particle::f, f, and mpi_update_particle().
set_particle_fix()
void set_particle_fix (int part, Utils::Vector3i const & flag)
Call only on the head node: set coordinate axes for which the particles motion is fixed.
Parameters
part the particle.
flag coordinates to be fixed.
Definition at line 610 of file particle_data.cpp.
References u.
set_particle_gamma()
void set_particle_gamma (int part, Utils::Vector3d const & gamma)
Call only on the head node: set particle frictional coefficient.
Parameters
part the particle.
gamma its new frictional coefficient.
Definition at line 576 of file particle_data.cpp.
References Utils::gamma().
set_particle_gamma_rot()
void set_particle_gamma_rot (int part, Utils::Vector3d const & gamma_rot)
Definition at line 589 of file particle_data.cpp.
set_particle_lees_edwards_offset()
void set_particle_lees_edwards_offset (int part, double v)
Call only on the head node: set particle Lees-Edwards offset.
Parameters
part the particle.
v new value for Lees-Edwards offset
Definition at line 410 of file particle_data.cpp.
References Particle::l, ParticleLocal::lees_edwards_offset, and mpi_update_particle().
set_particle_mass()
void set_particle_mass (int part, double mass)
Call only on the head node: set particle mass.
Parameters
part the particle.
mass its new mass.
Definition at line 428 of file particle_data.cpp.
set_particle_mol_id()
void set_particle_mol_id (int part, int mid)
Call only on the head node: set particle's molecule id.
Parameters
part the particle.
mid its new mol id.
Definition at line 532 of file particle_data.cpp.
set_particle_mu_E()
void set_particle_mu_E (int part, Utils::Vector3d const & mu_E)
Call only on the head node: set particle electrophoretic mobility.
Parameters
part the particle.
mu_E its new mobility.
Definition at line 520 of file particle_data.cpp.
set_particle_omega_body()
void set_particle_omega_body (int part, const Utils::Vector3d & omega)
Call only on the head node: set particle angular velocity in body frame.
Parameters
part the particle.
omega its new angular velocity.
Definition at line 556 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_omega_lab()
void set_particle_omega_lab (int part, const Utils::Vector3d & omega_lab)
Call only on the head node: set particle angular velocity from lab frame.
Parameters
part the particle.
omega_lab its new angular velocity.
Definition at line 548 of file particle_data.cpp.
References convert_vector_space_to_body(), get_particle_data(), Particle::m, mpi_update_particle(), and ParticleMomentum::omega.
set_particle_q()
void set_particle_q (int part, double q)
Call only on the head node: set particle charge.
Parameters
part the particle.
q its new charge.
Definition at line 509 of file particle_data.cpp.
Referenced by ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_quat()
void set_particle_quat (int part, Utils::Quaternion< double > const & quat)
Call only on the head node: set particle orientation using quaternions.
Parameters
part the particle.
quat its new value for quaternions.
Definition at line 537 of file particle_data.cpp.
References ParticlePosition::quat.
Referenced by set_particle_dip(), and set_particle_director().
set_particle_rotation()
void set_particle_rotation (int part, Utils::Vector3i const & flag)
Call only on the head node: Specifies whether a particle's rotational degrees of freedom are integrated or not.
If set to zero, the content of the torque and omega variables are meaningless
Parameters
part the particle.
flag the degrees of freedom flag.
Definition at line 446 of file particle_data.cpp.
References u.
set_particle_rotational_inertia()
void set_particle_rotational_inertia (int part, Utils::Vector3d const & rinertia)
Call only on the head node: set particle rotational inertia.
Parameters
part the particle.
rinertia its new inertia.
Definition at line 436 of file particle_data.cpp.
set_particle_swimming()
void set_particle_swimming (int part, ParticleParametersSwimming swim)
Call only on the head node: set particle velocity.
Parameters
part the particle.
swim struct containing swimming parameters
Definition at line 416 of file particle_data.cpp.
References mpi_update_particle_property(), and ParticleProperties::swim.
set_particle_torque_lab()
void set_particle_torque_lab (int part, const Utils::Vector3d & torque_lab)
Call only on the head node: set particle torque from lab frame.
Parameters
part the particle.
torque_lab its new torque.
Definition at line 561 of file particle_data.cpp.
References convert_vector_space_to_body(), Particle::f, get_particle_data(), mpi_update_particle(), and ParticleForce::torque.
set_particle_type()
void set_particle_type (int p_id, int type)
Call only on the head node: set particle type.
Parameters
p_id the particle.
type its new type.
Definition at line 526 of file particle_data.cpp.
References make_particle_type_exist(), and on_particle_type_change().
Referenced by ReactionMethods::ReactionAlgorithm::generic_oneway_reaction(), and ReactionMethods::ReactionAlgorithm::restore_properties().
set_particle_v()
void set_particle_v (int part, Utils::Vector3d const & v)
Call only on the head node: set particle velocity.
Parameters
part the particle.
v its new velocity.
Definition at line 405 of file particle_data.cpp.
References Particle::m, mpi_update_particle(), and ParticleMomentum::v.
set_particle_virtual()
void set_particle_virtual (int part, bool is_virtual)
Call only on the head node: set particle virtual flag.
Parameters
part the particle.
is_virtual new is_virtual flag.
Definition at line 479 of file particle_data.cpp.
Referenced by vs_relate_to().
set_particle_vs_quat()
void set_particle_vs_quat (int part, Utils::Quaternion< double > const & vs_relative_quat)
Definition at line 486 of file particle_data.cpp.
References get_particle_data(), mpi_update_particle_property(), ParticleProperties::vs_relative, and Particle::vs_relative().
set_particle_vs_relative()
void set_particle_vs_relative (int part, int vs_relative_to, double vs_distance, Utils::Quaternion< double > const & rel_ori)
Definition at line 496 of file particle_data.cpp.
References ParticleProperties::VirtualSitesRelativeParameters::distance, mpi_update_particle_property(), ParticleProperties::VirtualSitesRelativeParameters::rel_orientation, ParticleProperties::VirtualSitesRelativeParameters::to_particle_id, and ParticleProperties::vs_relative.
Referenced by vs_relate_to().
Variable Documentation
some_tag
constexpr auto some_tag = 42 constexpr
Definition at line 51 of file particle_data.cpp.
Referenced by mpi_rescale_particles(), mpi_rescale_particles_local(), mpi_send_update_message(), and mpi_send_update_message_local().