ESPResSo: particle_node.cpp File Reference
particle_node.cpp File Reference
#include "particle_node.hpp"
#include "BoxGeometry.hpp"
#include "Particle.hpp"
#include "cell_system/CellStructure.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "system/System.hpp"
#include <utils/Cache.hpp>
#include <utils/Vector.hpp>
#include <utils/mpi/gatherv.hpp>
#include <boost/mpi/collectives/all_gather.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <boost/mpi/collectives/gather.hpp>
#include <boost/mpi/collectives/reduce.hpp>
#include <boost/mpi/collectives/scatter.hpp>
#include <algorithm>
#include <cmath>
#include <functional>
#include <iterator>
#include <ranges>
#include <span>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
Namespaces
namespace anonymous_namespace{particle_node.cpp}
Functions
static auto & get_cell_structure ()
static auto rebuild_needed ()
static void mpi_synchronize_max_seen_pid_local ()
void init_type_map (int type)
static void remove_id_from_map (int p_id, int type)
static void add_id_to_type_map (int p_id, int type)
void on_particle_type_change (int p_id, int old_type, int new_type)
void invalidate_fetch_cache ()
Invalidate the fetch cache for get_particle_data.
std::size_t fetch_cache_max_size ()
Return the maximal number of particles that are kept in the fetch cache.
static void mpi_send_particle_data_local (int p_id)
const Particle & get_particle_data (int p_id)
Get particle data.
static void mpi_get_particles_local ()
static std::vector< Particle > mpi_get_particles (std::span< const int > ids)
Get multiple particles at once.
void prefetch_particle_data (std::span< const int > in_ids)
Fetch a range of particle into the fetch cache.
static void mpi_who_has_local ()
static void mpi_who_has_head ()
static void build_particle_node ()
Rebuild the particle index.
static void build_particle_node_parallel ()
Rebuild the particle index.
int get_particle_node (int p_id)
Get the MPI rank which owns the a specific particle.
int get_particle_node_parallel (int p_id)
void clear_particle_node ()
Invalidate particle_node.
static void clear_particle_type_map ()
static int calculate_max_seen_id ()
Calculate the largest particle id.
static bool maybe_insert_particle (int p_id, Utils::Vector3d const &pos)
Create a new particle and attach it to a cell.
static bool maybe_move_particle (int p_id, Utils::Vector3d const &pos)
Move particle to a new position.
void remove_all_particles ()
Remove all particles.
void remove_particle (int p_id)
Remove particle with a given identity.
void make_new_particle (int p_id, Utils::Vector3d const &pos)
Create a new particle and attach it to a cell.
void set_particle_pos (int p_id, Utils::Vector3d const &pos)
Move particle to a new position.
int get_random_p_id (int type, int random_index_in_type_map)
Find a particle of given type and return its id.
int number_of_particles_with_type (int type)
bool particle_exists (int p_id)
Check if particle exists.
std::vector< int > get_particle_ids ()
Get all particle ids.
std::vector< int > get_particle_ids_parallel ()
int get_maximal_particle_id ()
Get maximal particle id.
int get_n_part ()
Get number of particles.
Variables
constexpr auto some_tag = 42
static bool type_list_enable
Enable particle type tracking in particle_type_map.
static std::unordered_map< int, std::unordered_set< int > > particle_type_map
Mapping particle types to lists of particle ids.
static std::unordered_map< int, int > particle_node
Mapping particle ids to MPI ranks.
static int max_seen_pid = -1
Keep track of the largest particle id.
std::size_t const anonymous_namespace{particle_node.cpp}::max_cache_size = (100ul * 1048576ul) / sizeof(Particle)
Utils::Cache< int, Particle > anonymous_namespace{particle_node.cpp}::particle_fetch_cache (max_cache_size)
Function Documentation
add_id_to_type_map()
static void add_id_to_type_map (int p_id, int type) static
Definition at line 120 of file particle_node.cpp.
References particle_type_map, and stream.
Referenced by on_particle_type_change().
build_particle_node()
static void build_particle_node () static
Rebuild the particle index.
Definition at line 338 of file particle_node.cpp.
References mpi_who_has_head(), mpi_who_has_local(), and Communication::mpiCallbacks().
Referenced by get_n_part(), get_particle_ids(), get_particle_node(), and particle_exists().
build_particle_node_parallel()
static void build_particle_node_parallel () static
Rebuild the particle index.
Definition at line 346 of file particle_node.cpp.
References mpi_who_has_head(), mpi_who_has_local(), and this_node.
Referenced by get_maximal_particle_id(), get_particle_ids_parallel(), get_particle_node_parallel(), and make_new_particle().
calculate_max_seen_id()
static int calculate_max_seen_id () static
Calculate the largest particle id.
Traversing the particle_node to find the largest particle id scales with O(N). Consider using the cached value in max_seen_pid if possible. This function is only necessary when the cached value is invalidated, for example when removing the particle which has the largest id.
Definition at line 414 of file particle_node.cpp.
References particle_node.
Referenced by remove_particle().
clear_particle_node()
void clear_particle_node ()
Invalidate particle_node.
This has to be done at the beginning of the integration.
Definition at line 395 of file particle_node.cpp.
References max_seen_pid, and particle_node.
Referenced by System::System::on_cell_structure_change(), System::System::on_observable_calc(), and remove_all_particles().
clear_particle_type_map()
static void clear_particle_type_map () static
Definition at line 400 of file particle_node.cpp.
References particle_type_map.
Referenced by remove_all_particles().
fetch_cache_max_size()
std::size_t fetch_cache_max_size ()
Return the maximal number of particles that are kept in the fetch cache.
Definition at line 157 of file particle_node.cpp.
References anonymous_namespace{particle_node.cpp}::particle_fetch_cache.
get_cell_structure()
static auto & get_cell_structure () static
Definition at line 66 of file particle_node.cpp.
References System::System::cell_structure, and System::get_system().
Referenced by ScriptInterface::Particles::ParticleHandle::do_call_method(), ScriptInterface::Particles::ParticleHandle::do_construct(), get_particle_data(), init_type_map(), maybe_insert_particle(), mpi_send_particle_data_local(), mpi_who_has_head(), mpi_who_has_local(), on_particle_type_change(), remove_all_particles(), remove_particle(), and set_particle_pos().
get_maximal_particle_id()
int get_maximal_particle_id ()
Get maximal particle id.
Definition at line 594 of file particle_node.cpp.
References build_particle_node_parallel(), max_seen_pid, and rebuild_needed().
Referenced by ReactionMethods::ReactionAlgorithm::delete_particle(), ScriptInterface::Particles::ParticleList::do_call_method(), and ScriptInterface::Particles::ParticleHandle::do_construct().
get_n_part()
int get_n_part ()
Get number of particles.
Definition at line 602 of file particle_node.cpp.
References build_particle_node(), and particle_node.
Referenced by ScriptInterface::Particles::ParticleList::do_call_method().
get_particle_data()
const Particle & get_particle_data (int p_id)
Get particle data.
Parameters
p_id the identity of the particle to fetch
Definition at line 172 of file particle_node.cpp.
References Communication::MpiCallbacks::call_all(), comm_cart, get_cell_structure(), get_particle_node(), mpi_send_particle_data_local(), Communication::mpiCallbacks(), anonymous_namespace{particle_node.cpp}::particle_fetch_cache, stream, and this_node.
Referenced by ClusterAnalysis::Cluster::center_of_mass_subcluster(), PairCriteria::PairCriterion::decide(), ScriptInterface::Particles::ParticleHandle::do_call_method(), ClusterAnalysis::Cluster::fractal_dimension(), ClusterAnalysis::Cluster::longest_distance(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), and ClusterAnalysis::ClusterStructure::run_for_bonded_particles().
get_particle_ids()
std::vector< int > get_particle_ids ()
Get all particle ids.
Returns
Sorted ids of all existing particles.
Definition at line 573 of file particle_node.cpp.
References build_particle_node(), particle_node, and stream.
Referenced by ScriptInterface::Particles::ParticleList::do_call_method(), ScriptInterface::System::System::get_internal_state(), and ScriptInterface::System::System::set_internal_state().
get_particle_ids_parallel()
std::vector< int > get_particle_ids_parallel ()
Definition at line 584 of file particle_node.cpp.
References build_particle_node_parallel(), comm_cart, particle_node, rebuild_needed(), and stream.
Referenced by ReactionMethods::ReactionAlgorithm::setup_bookkeeping_of_empty_pids().
get_particle_node()
int get_particle_node (int p_id)
Get the MPI rank which owns the a specific particle.
Parameters
p_id identity of the particle
Returns
The MPI rank the particle is on.
Definition at line 354 of file particle_node.cpp.
References build_particle_node(), particle_node, and stream.
Referenced by get_particle_data(), mpi_get_particles(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and prefetch_particle_data().
get_particle_node_parallel()
int get_particle_node_parallel (int p_id)
Definition at line 372 of file particle_node.cpp.
References build_particle_node_parallel(), particle_node, rebuild_needed(), stream, and this_node.
get_random_p_id()
int get_random_p_id (int type, int random_index_in_type_map)
Find a particle of given type and return its id.
Definition at line 539 of file particle_node.cpp.
References comm_cart, particle_type_map, and stream.
Referenced by ReactionMethods::ReactionAlgorithm::displacement_mc_move(), and ReactionMethods::ReactionAlgorithm::make_reaction_attempt().
init_type_map()
void init_type_map (int type)
Definition at line 89 of file particle_node.cpp.
References comm_cart, get_cell_structure(), System::get_system(), System::System::nonbonded_ias, particle_type_map, stream, and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::add_reaction(), ScriptInterface::System::System::do_call_method(), and ScriptInterface::ReactionMethods::ReactionAlgorithm::do_call_method().
invalidate_fetch_cache()
void invalidate_fetch_cache ()
Invalidate the fetch cache for get_particle_data.
Definition at line 156 of file particle_node.cpp.
References anonymous_namespace{particle_node.cpp}::particle_fetch_cache.
Referenced by System::System::on_integration_start(), and System::System::on_particle_change().
make_new_particle()
void make_new_particle (int p_id, Utils::Vector3d const & pos)
Create a new particle and attach it to a cell.
Parameters
p_id The identity of the particle to create.
pos The particle position.
Definition at line 508 of file particle_node.cpp.
References build_particle_node_parallel(), comm_cart, System::get_system(), max_seen_pid, maybe_insert_particle(), mpi_synchronize_max_seen_pid_local(), System::System::on_particle_change(), particle_node, rebuild_needed(), stream, and this_node.
Referenced by ScriptInterface::Particles::ParticleHandle::do_construct().
maybe_insert_particle()
static bool maybe_insert_particle (int p_id, Utils::Vector3d const & pos) static
Create a new particle and attach it to a cell.
Parameters
p_id The identity of the particle to create.
pos The particle position.
Returns
Whether the particle was created on that node.
Definition at line 426 of file particle_node.cpp.
References System::System::box_geo, get_cell_structure(), System::get_system(), and stream.
Referenced by make_new_particle().
maybe_move_particle()
static bool maybe_move_particle (int p_id, Utils::Vector3d const & pos) static
Move particle to a new position.
Parameters
p_id The identity of the particle to move.
pos The new particle position.
Returns
Whether the particle was moved from that node.
Definition at line 447 of file particle_node.cpp.
References System::get_system(), and stream.
Referenced by set_particle_pos().
mpi_get_particles()
static std::vector< Particle > mpi_get_particles (std::span< const int > ids) static
Get multiple particles at once.
WARNING Particles are returned in an arbitrary order.
Parameters
ids The ids of the particles that should be returned.
Returns
The particle list.
Definition at line 221 of file particle_node.cpp.
References comm_cart, Utils::Mpi::gatherv(), get_particle_node(), mpi_get_particles_local(), Communication::mpiCallbacks(), stream, and this_node.
Referenced by prefetch_particle_data().
mpi_get_particles_local()
static void mpi_get_particles_local () static
Definition at line 195 of file particle_node.cpp.
References comm_cart, Utils::Mpi::gatherv(), and stream.
Referenced by mpi_get_particles().
mpi_send_particle_data_local()
static void mpi_send_particle_data_local (int p_id) static
Definition at line 159 of file particle_node.cpp.
References comm_cart, get_cell_structure(), and stream.
Referenced by get_particle_data().
mpi_synchronize_max_seen_pid_local()
static void mpi_synchronize_max_seen_pid_local () static
Definition at line 85 of file particle_node.cpp.
References comm_cart, and max_seen_pid.
Referenced by make_new_particle(), mpi_who_has_head(), mpi_who_has_local(), and remove_particle().
mpi_who_has_head()
static void mpi_who_has_head () static
Definition at line 305 of file particle_node.cpp.
References comm_cart, get_cell_structure(), max_seen_pid, mpi_synchronize_max_seen_pid_local(), particle_node, some_tag, stream, and this_node.
Referenced by build_particle_node(), and build_particle_node_parallel().
mpi_who_has_local()
static void mpi_who_has_local () static
Definition at line 282 of file particle_node.cpp.
References comm_cart, get_cell_structure(), mpi_synchronize_max_seen_pid_local(), some_tag, and stream.
Referenced by build_particle_node(), and build_particle_node_parallel().
number_of_particles_with_type()
int number_of_particles_with_type (int type)
Definition at line 556 of file particle_node.cpp.
References particle_type_map, and stream.
Referenced by ReactionMethods::ReactionAlgorithm::all_reactant_particles_exist(), ReactionMethods::ReactionAlgorithm::displacement_mc_move(), ReactionMethods::ReactionAlgorithm::make_displacement_mc_move_attempt(), and ReactionMethods::ReactionAlgorithm::make_reaction_attempt().
on_particle_type_change()
void on_particle_type_change (int p_id, int old_type, int new_type)
Definition at line 126 of file particle_node.cpp.
References add_id_to_type_map(), type_tracking::any_type, get_cell_structure(), type_tracking::new_part, particle_type_map, remove_id_from_map(), stream, and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::make_reaction_attempt(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), ReactionMethods::ReactionAlgorithm::restore_old_system_state(), and ScriptInterface::Particles::set_particles_types().
particle_exists()
bool particle_exists (int p_id)
Check if particle exists.
Parameters
p_id identity of the particle
Returns
True iff the particle exists.
Definition at line 567 of file particle_node.cpp.
References build_particle_node(), particle_node, and stream.
Referenced by ScriptInterface::Particles::ParticleList::do_call_method(), and ScriptInterface::Particles::ParticleSlice::do_construct().
prefetch_particle_data()
void prefetch_particle_data (std::span< const int > ids)
Fetch a range of particle into the fetch cache.
If the range is larger than the cache size, only the particle that fit into the cache are fetched.
The particles have to exist, an exception it throw if one of the the particles can not be found.
Parameters
ids Ids of the particles that should be fetched.
Definition at line 256 of file particle_node.cpp.
References comm_cart, get_particle_node(), mpi_get_particles(), anonymous_namespace{particle_node.cpp}::particle_fetch_cache, stream, and this_node.
Referenced by ScriptInterface::Particles::ParticleSlice::do_call_method().
rebuild_needed()
static auto rebuild_needed () static
Definition at line 79 of file particle_node.cpp.
References comm_cart, particle_node, and stream.
Referenced by get_maximal_particle_id(), get_particle_ids_parallel(), get_particle_node_parallel(), and make_new_particle().
remove_all_particles()
void remove_all_particles ()
Remove all particles.
Definition at line 462 of file particle_node.cpp.
References clear_particle_node(), clear_particle_type_map(), get_cell_structure(), System::get_system(), and System::System::on_particle_change().
Referenced by ScriptInterface::Particles::ParticleList::do_call_method().
remove_id_from_map()
static void remove_id_from_map (int p_id, int type) static
Definition at line 114 of file particle_node.cpp.
References particle_type_map, and stream.
Referenced by on_particle_type_change(), and remove_particle().
remove_particle()
void remove_particle (int p_id)
Remove particle with a given identity.
Also removes all bonds to the particle.
Parameters
p_id identity of the particle to remove
Definition at line 469 of file particle_node.cpp.
References calculate_max_seen_id(), comm_cart, get_cell_structure(), System::get_system(), max_seen_pid, mpi_synchronize_max_seen_pid_local(), System::System::on_particle_change(), particle_node, remove_id_from_map(), stream, this_node, and type_list_enable.
Referenced by ReactionMethods::ReactionAlgorithm::delete_particle(), ScriptInterface::Particles::ParticleHandle::do_call_method(), and ScriptInterface::Particles::ParticleHandle::do_construct().
set_particle_pos()
void set_particle_pos (int p_id, Utils::Vector3d const & pos)
Move particle to a new position.
Parameters
p_id The identity of the particle to move.
pos The new particle position.
Definition at line 526 of file particle_node.cpp.
References comm_cart, get_cell_structure(), System::get_system(), maybe_move_particle(), System::System::on_particle_change(), Cells::RESORT_GLOBAL, stream, and this_node.
Referenced by ReactionMethods::ReactionAlgorithm::displacement_mc_move(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and ScriptInterface::Particles::set_particles_positions().
Variable Documentation
max_seen_pid
int max_seen_pid = -1 static
Keep track of the largest particle id.
This book-keeping variable is necessary to make particle insertion run in constant time. Traversing the particle_node to find the largest particle id scales with O(N) and traversing the local cells in parallel followed by a reduction scales with O(N^2).
Definition at line 77 of file particle_node.cpp.
Referenced by clear_particle_node(), get_maximal_particle_id(), make_new_particle(), mpi_synchronize_max_seen_pid_local(), mpi_who_has_head(), and remove_particle().
particle_node
std::unordered_map<int, int> particle_node static
Mapping particle ids to MPI ranks.
Definition at line 64 of file particle_node.cpp.
Referenced by calculate_max_seen_id(), clear_particle_node(), get_n_part(), get_particle_ids(), get_particle_ids_parallel(), get_particle_node(), get_particle_node_parallel(), make_new_particle(), mpi_who_has_head(), particle_exists(), rebuild_needed(), and remove_particle().
particle_type_map
std::unordered_map<int, std::unordered_set<int> > particle_type_map static
Mapping particle types to lists of particle ids.
Definition at line 61 of file particle_node.cpp.
Referenced by add_id_to_type_map(), clear_particle_type_map(), get_random_p_id(), init_type_map(), number_of_particles_with_type(), on_particle_type_change(), and remove_id_from_map().
some_tag
constexpr auto some_tag = 42 constexpr
Definition at line 55 of file particle_node.cpp.
Referenced by mpi_who_has_head(), and mpi_who_has_local().
type_list_enable
bool type_list_enable static
Enable particle type tracking in particle_type_map.
Definition at line 58 of file particle_node.cpp.
Referenced by init_type_map(), on_particle_type_change(), and remove_particle().