ESPResSo: particle_coupling.cpp File Reference
particle_coupling.cpp File Reference
#include <config/config.hpp>
#include "BoxGeometry.hpp"
#include "LocalBox.hpp"
#include "Particle.hpp"
#include "cell_system/CellStructure.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "lb/particle_coupling.hpp"
#include "random.hpp"
#include "system/System.hpp"
#include "thermostat.hpp"
#include <utils/Counter.hpp>
#include <utils/Vector.hpp>
#include <boost/mpi.hpp>
#include <caliper/cali.h>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <initializer_list>
#include <limits>
#include <ranges>
#include <vector>
Namespaces
namespace LB
Functions
static Thermostat::GammaType lb_handle_particle_anisotropy (Particle const &p, double lb_gamma)
static Utils::Vector3d lb_drag_force (Particle const &p, double lb_gamma, Utils::Vector3d const &v_fluid)
Utils::Vector3d lb_drag_force (LB::Solver const &lb, double lb_gamma, Particle const &p, Utils::Vector3d const &shifted_pos)
Calculate drag force on a single particle.
static bool in_local_domain (LocalBox const &local_box, Utils::Vector3d const &pos, double halo=0.)
Check if a position is within the local box + halo.
static bool in_box (Utils::Vector3d const &pos, Utils::Vector3d const &lower_corner, Utils::Vector3d const &upper_corner)
bool in_local_halo (LocalBox const &local_box, Utils::Vector3d const &pos, double agrid)
Check if a position is within the local LB domain plus halo.
static void positions_in_halo_impl (Utils::Vector3d const &pos_folded, Utils::Vector3d const &halo_lower_corner, Utils::Vector3d const &halo_upper_corner, BoxGeometry const &box_geo, std::vector< Utils::Vector3d > &res)
std::vector< Utils::Vector3d > positions_in_halo (Utils::Vector3d const &pos, BoxGeometry const &box_geo, LocalBox const &local_box, double agrid)
Return a vector of positions shifted by +,- box length in each coordinate.
static auto lees_edwards_vel_shift (Utils::Vector3d const &pos_shifted_by_box_l, Utils::Vector3d const &orig_pos, BoxGeometry const &box_geo)
static void LB::lb_coupling_sanity_checks (Particle const &p)
Function Documentation
in_box()
static bool in_box (Utils::Vector3d const & pos, Utils::Vector3d const & lower_corner, Utils::Vector3d const & upper_corner) static
Definition at line 104 of file particle_coupling.cpp.
References stream.
Referenced by LB::ParticleCoupling::kernel(), positions_in_halo(), and positions_in_halo_impl().
in_local_domain()
static bool in_local_domain (LocalBox const & local_box, Utils::Vector3d const & pos, double halo = 0.) static
Check if a position is within the local box + halo.
Parameters
local_box Local geometry
pos Position to check
halo Halo
Returns
True iff the point is inside of the box up to halo.
Definition at line 95 of file particle_coupling.cpp.
References Utils::Vector< T, N >::broadcast(), and stream.
Referenced by in_local_halo().
in_local_halo()
bool in_local_halo (LocalBox const & local_box, Utils::Vector3d const & pos, double agrid)
Check if a position is within the local LB domain plus halo.
Returns
True iff the point is inside of the domain.
Definition at line 110 of file particle_coupling.cpp.
References in_local_domain(), and stream.
lb_drag_force() [1/2]
Utils::Vector3d lb_drag_force (LB::Solver const & lb, double lb_gamma, Particle const & p, Utils::Vector3d const & shifted_pos)
Calculate drag force on a single particle.
See section II.C. and eq. 9 in [2].
Parameters
[in] lb The coupled fluid
[in] lb_gamma The friction coefficient
[in] p The coupled particle
[in] shifted_pos The particle position in MD units with optional shift
Returns
The viscous coupling force
Definition at line 79 of file particle_coupling.cpp.
References LB::Solver::get_coupling_interpolated_velocity(), lb_drag_force(), and stream.
lb_drag_force() [2/2]
static Utils::Vector3d lb_drag_force (Particle const & p, double lb_gamma, Utils::Vector3d const & v_fluid) static
Definition at line 66 of file particle_coupling.cpp.
References Utils::hadamard_product(), lb_handle_particle_anisotropy(), Particle::mu_E(), stream, and Particle::v().
Referenced by LB::ParticleCoupling::kernel(), and lb_drag_force().
lb_handle_particle_anisotropy()
static Thermostat::GammaType lb_handle_particle_anisotropy (Particle const & p, double lb_gamma) static
Definition at line 51 of file particle_coupling.cpp.
References Utils::Vector< T, N >::broadcast(), Particle::gamma(), Thermostat::handle_particle_gamma(), and stream.
Referenced by LB::ParticleCoupling::get_noise_term(), and lb_drag_force().
lees_edwards_vel_shift()
static auto lees_edwards_vel_shift (Utils::Vector3d const & pos_shifted_by_box_l, Utils::Vector3d const & orig_pos, BoxGeometry const & box_geo) static
Definition at line 179 of file particle_coupling.cpp.
References LEES_EDWARDS, BoxGeometry::lees_edwards_bc(), stream, and BoxGeometry::type().
Referenced by LB::ParticleCoupling::kernel().
positions_in_halo()
std::vector< Utils::Vector3d > positions_in_halo (Utils::Vector3d const & pos, BoxGeometry const & box_geo, LocalBox const & local_box, double agrid)
Return a vector of positions shifted by +,- box length in each coordinate.
Definition at line 159 of file particle_coupling.cpp.
References Utils::Vector< T, N >::broadcast(), BoxGeometry::folded_position(), in_box(), positions_in_halo_impl(), and stream.
Referenced by lb_tracers_add_particle_force_to_fluid().
positions_in_halo_impl()
static void positions_in_halo_impl (Utils::Vector3d const & pos_folded, Utils::Vector3d const & halo_lower_corner, Utils::Vector3d const & halo_upper_corner, BoxGeometry const & box_geo, std::vector< Utils::Vector3d > & res) static
Definition at line 116 of file particle_coupling.cpp.
References Utils::hadamard_product(), in_box(), LEES_EDWARDS, BoxGeometry::lees_edwards_bc(), BoxGeometry::length(), Algorithm::periodic_fold(), stream, and BoxGeometry::type().
Referenced by LB::ParticleCoupling::kernel(), and positions_in_halo().