ESPResSo: particle_coupling.hpp File Reference
particle_coupling.hpp File Reference
#include "BoxGeometry.hpp"
#include "LocalBox.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "PropagationMode.hpp"
#include "cell_system/CellStructure.hpp"
#include "lb/Solver.hpp"
#include "system/System.hpp"
#include "thermostat.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sqr.hpp>
#include <cmath>
#include <unordered_set>
#include <vector>
Classes
class LB::ParticleCoupling
class LB::CouplingBookkeeping
Keep track of ghost particles that have already been coupled once.
Namespaces
LB
Functions
bool in_local_halo (LocalBox const &local_box, Utils::Vector3d const &pos, double agrid)
Check if a position is within the local LB domain plus halo.
void add_md_force (LB::Solver &lb, Utils::Vector3d const &pos, Utils::Vector3d const &force, double time_step)
Add a force to the lattice force density.
std::vector< Utils::Vector3d > positions_in_halo (Utils::Vector3d const &pos, BoxGeometry const &box, LocalBox const &local_geo, double agrid)
Return a vector of positions shifted by +,- box length in each coordinate.
Utils::Vector3d lb_drag_force (LB::Solver const &lb, double lb_gamma, Particle const &p, Utils::Vector3d const &shifted_pos, Utils::Vector3d const &vel_offset)
Calculate drag force on a single particle.
bool LB::is_tracer (Particle const &p)
Function Documentation
add_md_force()
void add_md_force (LB::Solver & lb, Utils::Vector3d const & pos, Utils::Vector3d const & force, double time_step)
Add a force to the lattice force density.
Parameters
lb Hydrodynamics solver
pos Position of the force in LB units.
force Force in MD units.
time_step MD time step.
Definition at line 49 of file particle_coupling.cpp.
References LB::Solver::add_force_density(), force, LB::Solver::get_lattice_speed(), and pos.
Referenced by LB::ParticleCoupling::kernel(), and lb_tracers_add_particle_force_to_fluid().
in_local_halo()
bool in_local_halo (LocalBox const & local_box, Utils::Vector3d const & pos, double agrid)
Check if a position is within the local LB domain plus halo.
Returns
True iff the point is inside of the domain.
Definition at line 110 of file particle_coupling.cpp.
References in_local_domain(), and pos.
Referenced by LB::ParticleCoupling::kernel().
lb_drag_force()
Utils::Vector3d lb_drag_force (LB::Solver const & lb, double lb_gamma, Particle const & p, Utils::Vector3d const & shifted_pos, Utils::Vector3d const & vel_offset)
Calculate drag force on a single particle.
See section II.C. [2]
Parameters
[in] lb The coupled fluid
[in] lb_gamma The friction coefficient
[in] p The coupled particle
[in] shifted_pos The particle position in LB units with optional shift
[in] vel_offset Velocity offset in MD units to be added to interpolated LB velocity before calculating the force
Returns
The viscous coupling force
Definition at line 72 of file particle_coupling.cpp.
References Utils::gamma(), LB::Solver::get_coupling_interpolated_velocity(), Utils::hadamard_product(), lb_handle_particle_anisotropy(), and Particle::v().
Referenced by LB::ParticleCoupling::kernel().
positions_in_halo()
std::vector<Utils::Vector3d> positions_in_halo (Utils::Vector3d const & pos, BoxGeometry const & box, LocalBox const & local_geo, double agrid)
Return a vector of positions shifted by +,- box length in each coordinate.
Definition at line 120 of file particle_coupling.cpp.
References Utils::Vector< T, N >::broadcast(), Utils::hadamard_product(), if(), in_box(), LEES_EDWARDS, BoxGeometry::lees_edwards_bc(), BoxGeometry::length(), LocalBox::my_left(), LocalBox::my_right(), pos, res, and BoxGeometry::type().
Referenced by LB::ParticleCoupling::kernel(), and lb_tracers_add_particle_force_to_fluid().