ESPResSo: polymer.cpp File Reference
polymer.cpp File Reference
#include "polymer.hpp"
#include "BoxGeometry.hpp"
#include "constraints.hpp"
#include "constraints/Constraints.hpp"
#include "constraints/ShapeBasedConstraint.hpp"
#include "grid.hpp"
#include "random.hpp"
#include <utils/Vector.hpp>
#include <utils/constants.hpp>
#include <utils/math/vec_rotate.hpp>
#include <boost/optional.hpp>
#include <cmath>
#include <cstddef>
#include <memory>
#include <stdexcept>
#include <vector>
Functions
template<class RNG >
static Utils::Vector3d random_position (RNG &rng)
template<class RNG >
static Utils::Vector3d random_unit_vector (RNG &rng)
static double distto (PartCfg &partCfg, Utils::Vector3d const &pos)
Calculate minimal distance to point.
static bool is_valid_position (Utils::Vector3d const &pos, std::vector< std::vector< Utils::Vector3d >> const &positions, PartCfg &partCfg, double const min_distance, int const respect_constraints)
Determines whether a given position pos is valid, i.e., it doesn't collide with existing or buffered particles, nor with existing constraints (if respect_constraints).
std::vector< std::vector< Utils::Vector3d > > draw_polymer_positions (PartCfg &partCfg, int const n_polymers, int const beads_per_chain, double const bond_length, std::vector< Utils::Vector3d > const &start_positions, double const min_distance, int const max_tries, int const use_bond_angle, double const bond_angle, int const respect_constraints, int const seed)
Determines valid polymer positions and returns them.
Detailed Description
This file contains everything needed to create a start-up configuration of (partially charged) polymer chains with counterions and salt molecules, assigning velocities to the particles and cross-linking the polymers if necessary.
The corresponding header file is polymer.hpp.
Definition in file polymer.cpp.
Function Documentation
distto()
static double distto (PartCfg & partCfg, Utils::Vector3d const & pos) static
Calculate minimal distance to point.
Note: Particle handles may be invalidated!
Parameters
partCfg particle selection
pos point from which to check for close neighbors
Returns
the minimal distance of a particle to coordinates pos
Definition at line 75 of file polymer.cpp.
References box_geo, BoxGeometry::get_mi_vector(), anonymous_namespace{Correlator.cpp}::min(), partCfg(), pos, and Utils::sqrt().
Referenced by is_valid_position().
draw_polymer_positions()
std::vector<std::vector<Utils::Vector3d> > draw_polymer_positions (PartCfg & partCfg, int n_polymers, int beads_per_chain, double bond_length, std::vector< Utils::Vector3d > const & start_positions, double min_distance, int max_tries, int use_bond_angle, double bond_angle, int respect_constraints, int seed)
Determines valid polymer positions and returns them.
Parameters
partCfg particle collection
n_polymers how many polymers to create
beads_per_chain monomers per chain
bond_length length of the bonds between two monomers
start_positions starting positions of each polymers
min_distance minimum distance between all particles
max_tries how often a monomer/polymer should be reset if current position collides with a previous particle
use_bond_angle whether to use the bond_angle argument
bond_angle desired bond-angle to be fixed
respect_constraints whether to respect constraints
seed seed for RNG
Definition at line 141 of file polymer.cpp.
References is_valid_position(), Random::mt19937(), partCfg(), pos, random_position(), random_unit_vector(), Utils::vec_rotate(), and vector_product().
is_valid_position()
static bool is_valid_position (Utils::Vector3d const & pos, std::vector< std::vector< Utils::Vector3d >> const & positions, PartCfg & partCfg, double const min_distance, int const respect_constraints) static
Determines whether a given position pos is valid, i.e., it doesn't collide with existing or buffered particles, nor with existing constraints (if respect_constraints).
Parameters
pos the trial position in question
positions buffered positions to respect
partCfg existing particles to respect
min_distance threshold for the minimum distance between trial position and buffered/existing particles
respect_constraints whether to respect constraints
Returns
true if valid position, false if not.
Definition at line 98 of file polymer.cpp.
References box_geo, D3Q19::c, Constraints::constraints, distto(), folded_position(), BoxGeometry::get_mi_vector(), Utils::Vector< T, N >::norm2(), partCfg(), and pos.
Referenced by draw_polymer_positions().
random_position()
template<class RNG > static Utils::Vector3d random_position (RNG & rng) static
Definition at line 51 of file polymer.cpp.
References box_geo, and BoxGeometry::length().
Referenced by draw_polymer_positions().
random_unit_vector()
template<class RNG > static Utils::Vector3d random_unit_vector (RNG & rng) static
Definition at line 58 of file polymer.cpp.
References Utils::Vector< T, N >::norm(), and Utils::pi().
Referenced by draw_polymer_positions().