ESPResSo: pressure.cpp File Reference
pressure.cpp File Reference
#include "pressure.hpp"
#include "Observable_stat.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "event.hpp"
#include "grid.hpp"
#include "interactions.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "pressure_inline.hpp"
#include "virtual_sites.hpp"
#include "short_range_loop.hpp"
#include "electrostatics/coulomb.hpp"
#include "magnetostatics/dipoles.hpp"
#include <utils/Span.hpp>
#include <utils/Vector.hpp>
#include <boost/range/algorithm/copy.hpp>
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <memory>
#include <utility>
Functions
static std::shared_ptr< Observable_stat > calculate_pressure_local ()
std::shared_ptr< Observable_stat > calculate_pressure ()
Parallel pressure calculation from a virial expansion.
Utils::Vector9d observable_compute_pressure_tensor ()
Helper function for Observables::PressureTensor.
Detailed Description
Implementation of pressure.hpp.
Definition in file pressure.cpp.
Function Documentation
calculate_pressure()
std::shared_ptr<Observable_stat> calculate_pressure ()
Parallel pressure calculation from a virial expansion.
Definition at line 131 of file pressure.cpp.
References calculate_pressure_local(), Communication::Result::main_rank, and mpi_call().
Referenced by observable_compute_pressure_tensor().
calculate_pressure_local()
static std::shared_ptr<Observable_stat> calculate_pressure_local () static
Definition at line 56 of file pressure.cpp.
References add_kinetic_virials(), box_geo, cell_structure, CellStructure::local_particles(), long_range_interactions_sanity_checks(), Coulomb::on_observable_calc(), Coulomb::pair_force_kernel(), Coulomb::pair_pressure_kernel(), short_range_loop(), and BoxGeometry::volume().
Referenced by calculate_pressure().
observable_compute_pressure_tensor()
Utils::Vector9d observable_compute_pressure_tensor ()
Helper function for Observables::PressureTensor.
Definition at line 135 of file pressure.cpp.
References calculate_pressure().
Referenced by Observables::Pressure::operator()(), and Observables::PressureTensor::operator()().