ESPResSo: pressure.hpp File Reference
pressure.hpp File Reference
#include "Observable_stat.hpp"
#include <utils/Vector.hpp>
#include <memory>
Functions
std::shared_ptr< Observable_stat > calculate_pressure ()
Parallel pressure calculation from a virial expansion.
Utils::Vector9d observable_compute_pressure_tensor ()
Helper function for Observables::PressureTensor.
Detailed Description
Pressure calculation. Really similar to energy.hpp.
Definition in file pressure.hpp.
Function Documentation
calculate_pressure()
std::shared_ptr<Observable_stat> calculate_pressure ()
Parallel pressure calculation from a virial expansion.
Definition at line 131 of file pressure.cpp.
References calculate_pressure_local(), Communication::Result::main_rank, and mpi_call().
Referenced by observable_compute_pressure_tensor().
observable_compute_pressure_tensor()
Utils::Vector9d observable_compute_pressure_tensor ()
Helper function for Observables::PressureTensor.
Definition at line 135 of file pressure.cpp.
References calculate_pressure().
Referenced by Observables::Pressure::operator()(), and Observables::PressureTensor::operator()().