ESPResSo: propagation.cpp File Reference
propagation.cpp File Reference
#include "propagation.hpp"
#include "config/config.hpp"
#include "PropagationMode.hpp"
#include <cassert>
#include <string>
#include <unordered_map>
Functions
static bool force_code_coverage (bool value)
bool is_valid_propagation_combination (int propagation)
Note for developers: when enabling new propagation mode combinations, make sure every single line of this function has code coverage.
std::unordered_map< std::string, int > propagation_flags_map ()
Convert PropagationMode::PropagationMode to name/value pairs.
std::string propagation_bitmask_to_string (int propagation)
Convert a propagation modes bitmask to a string.
Function Documentation
force_code_coverage()
static bool force_code_coverage (bool value) static
Definition at line 31 of file propagation.cpp.
Referenced by is_valid_propagation_combination().
is_valid_propagation_combination()
bool is_valid_propagation_combination (int propagation)
Note for developers: when enabling new propagation mode combinations, make sure every single line of this function has code coverage.
Check allowlist of valid propagation modes combinations.
Definition at line 37 of file propagation.cpp.
References force_code_coverage(), PropagationMode::NONE, PropagationMode::ROT_BROWNIAN, PropagationMode::ROT_EULER, PropagationMode::ROT_LANGEVIN, PropagationMode::ROT_STOKESIAN, PropagationMode::ROT_VS_RELATIVE, PropagationMode::SYSTEM_DEFAULT, PropagationMode::TRANS_BROWNIAN, PropagationMode::TRANS_LANGEVIN, PropagationMode::TRANS_LANGEVIN_NPT, PropagationMode::TRANS_LB_MOMENTUM_EXCHANGE, PropagationMode::TRANS_LB_TRACER, PropagationMode::TRANS_NEWTON, PropagationMode::TRANS_STOKESIAN, and PropagationMode::TRANS_VS_RELATIVE.
propagation_bitmask_to_string()
std::string propagation_bitmask_to_string (int propagation)
Convert a propagation modes bitmask to a string.
Definition at line 125 of file propagation.cpp.
References propagation_flags_map().
propagation_flags_map()
std::unordered_map<std::string, int> propagation_flags_map ()
Convert PropagationMode::PropagationMode to name/value pairs.
Definition at line 104 of file propagation.cpp.
References PropagationMode::NONE, PropagationMode::ROT_BROWNIAN, PropagationMode::ROT_EULER, PropagationMode::ROT_LANGEVIN, PropagationMode::ROT_STOKESIAN, PropagationMode::ROT_VS_RELATIVE, PropagationMode::SYSTEM_DEFAULT, PropagationMode::TRANS_BROWNIAN, PropagationMode::TRANS_LANGEVIN, PropagationMode::TRANS_LANGEVIN_NPT, PropagationMode::TRANS_LB_MOMENTUM_EXCHANGE, PropagationMode::TRANS_LB_TRACER, PropagationMode::TRANS_NEWTON, PropagationMode::TRANS_STOKESIAN, and PropagationMode::TRANS_VS_RELATIVE.
Referenced by ScriptInterface::System::System::do_call_method(), and propagation_bitmask_to_string().