ESPResSo: rattle.hpp File Reference
rattle.hpp File Reference
RATTLE algorithm ([4]).
#include <config/config.hpp>
#include "BoxGeometry.hpp"
#include "ParticleRange.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "cell_system/CellStructure.hpp"
Functions
void save_old_position (ParticleRange const &particles, ParticleRange const &ghost_particles)
Transfer the current particle positions from Particle::pos to Particle::pos_last_time_step.
void correct_position_shake (CellStructure &cs, BoxGeometry const &box_geo, BondedInteractionsMap const &bonded_ias)
Propagate velocity and position while using SHAKE algorithm for bond constraint.
void correct_velocity_shake (CellStructure &cs, BoxGeometry const &box_geo, BondedInteractionsMap const &bonded_ias)
Correction of current velocities using RATTLE algorithm.
Detailed Description
RATTLE algorithm ([4]).
For more information see rattle.cpp.
Definition in file rattle.hpp.
Function Documentation
correct_position_shake()
void correct_position_shake (CellStructure & cs, BoxGeometry const & box_geo, BondedInteractionsMap const & bonded_ias)
Propagate velocity and position while using SHAKE algorithm for bond constraint.
Definition at line 157 of file rattle.cpp.
References apply_positional_correction(), calculate_positional_correction(), check_convergence(), CellStructure::check_resort_required(), comm_cart, compute_correction_vector(), Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, Cells::DATA_PART_PROPERTIES, CellStructure::ghost_particles(), CellStructure::ghosts_reduce_rattle_correction(), CellStructure::ghosts_update(), init_correction_vector(), CellStructure::local_particles(), Cells::RESORT_LOCAL, Cells::RESORT_NONE, CellStructure::set_resort_particles(), shake_max_iterations, stream, and CellStructure::update_ghosts_and_resort_particle().
Referenced by System::System::integrate().
correct_velocity_shake()
void correct_velocity_shake (CellStructure & cs, BoxGeometry const & box_geo, BondedInteractionsMap const & bonded_ias)
Correction of current velocities using RATTLE algorithm.
Definition at line 229 of file rattle.cpp.
References apply_velocity_correction(), calculate_velocity_correction(), check_convergence(), comm_cart, compute_correction_vector(), Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, CellStructure::ghost_particles(), CellStructure::ghosts_reduce_rattle_correction(), CellStructure::ghosts_update(), init_correction_vector(), CellStructure::local_particles(), shake_max_iterations, and stream.
Referenced by System::System::integrate().
save_old_position()
void save_old_position (const ParticleRange & particles, const ParticleRange & ghost_particles)
Transfer the current particle positions from Particle::pos to Particle::pos_last_time_step.
Transfer the current particle positions from Particle::pos to Particle::pos_last_time_step.
Parameters
particles particle range
ghost_particles ghost particle range
Definition at line 59 of file rattle.cpp.
References stream.
Referenced by System::System::integrate().