ESPResSo: relative.cpp File Reference
relative.cpp File Reference
#include <config/config.hpp>
#include "BoxGeometry.hpp"
#include "Particle.hpp"
#include "PropagationMode.hpp"
#include "cell_system/CellStructure.hpp"
#include "cells.hpp"
#include "errorhandling.hpp"
#include "forces.hpp"
#include "lees_edwards/lees_edwards.hpp"
#include "rotation.hpp"
#include <utils/Vector.hpp>
#include <utils/math/quaternion.hpp>
#include <utils/math/tensor_product.hpp>
#include <utils/quaternion.hpp>
#include <cassert>
Functions
static auto connection_vector (Particle const &p_ref, Particle const &p_vs)
Vector pointing from the real particle to the virtual site.
static Utils::Vector3d velocity (Particle const &p_ref, Particle const &p_vs)
Velocity of the virtual site.
Particle * get_reference_particle (CellStructure &cell_structure, Particle const &p)
Get real particle tracked by a virtual site.
static auto constraint_stress (Particle const &p_ref, Particle const &p_vs)
Constraint force to hold the particle at its prescribed position.
static bool is_vs_relative_trans (Particle const &p)
static bool is_vs_relative_rot (Particle const &p)
static bool is_vs_independent_rot (Particle const &p)
static bool is_vs_rot (Particle const &p)
static bool is_vs (Particle const &p)
void vs_relative_update_particles (CellStructure &cell_structure, BoxGeometry const &box_geo)
void vs_relative_back_transfer_forces_and_torques (CellStructure &cell_structure)
Utils::Matrix< double, 3, 3 > vs_relative_pressure_tensor (CellStructure const &cell_structure)
Function Documentation
connection_vector()
static auto connection_vector (Particle const & p_ref, Particle const & p_vs) static
Vector pointing from the real particle to the virtual site.
Returns
Relative distance.
Definition at line 46 of file relative.cpp.
References Utils::convert_quaternion_to_director(), Particle::quat(), and Particle::vs_relative().
Referenced by constraint_stress(), velocity(), vs_relative_back_transfer_forces_and_torques(), and vs_relative_update_particles().
constraint_stress()
static auto constraint_stress (Particle const & p_ref, Particle const & p_vs) static
Constraint force to hold the particle at its prescribed position.
Parameters
p_ref Reference particle.
p_vs Virtual site.
Returns
Constraint force.
Definition at line 98 of file relative.cpp.
References connection_vector(), and Particle::force().
Referenced by vs_relative_pressure_tensor().
get_reference_particle()
Particle * get_reference_particle (CellStructure & cell_structure, Particle const & p)
Get real particle tracked by a virtual site.
Parameters
cell_structure Cell structure.
p Virtual site.
Returns
Pointer to real particle, or nullptr if lookup fails.
Definition at line 75 of file relative.cpp.
References CellStructure::get_local_particle(), Particle::id(), runtimeErrorMsg, and Particle::vs_relative().
Referenced by run_magnetodynamics(), vs_relative_back_transfer_forces_and_torques(), and vs_relative_update_particles().
is_vs()
static bool is_vs (Particle const & p) static
Definition at line 117 of file relative.cpp.
References is_vs_relative_trans(), and is_vs_rot().
Referenced by vs_relative_back_transfer_forces_and_torques(), and vs_relative_update_particles().
is_vs_independent_rot()
static bool is_vs_independent_rot (Particle const & p) static
Definition at line 111 of file relative.cpp.
References Particle::propagation(), and PropagationMode::ROT_VS_INDEPENDENT.
Referenced by is_vs_rot().
is_vs_relative_rot()
static bool is_vs_relative_rot (Particle const & p) static
Definition at line 108 of file relative.cpp.
References Particle::propagation(), and PropagationMode::ROT_VS_RELATIVE.
Referenced by is_vs_rot(), and vs_relative_update_particles().
is_vs_relative_trans()
static bool is_vs_relative_trans (Particle const & p) static
Definition at line 105 of file relative.cpp.
References Particle::propagation(), and PropagationMode::TRANS_VS_RELATIVE.
Referenced by is_vs(), vs_relative_back_transfer_forces_and_torques(), vs_relative_pressure_tensor(), and vs_relative_update_particles().
is_vs_rot()
static bool is_vs_rot (Particle const & p) static
Definition at line 114 of file relative.cpp.
References is_vs_independent_rot(), and is_vs_relative_rot().
Referenced by is_vs(), and vs_relative_back_transfer_forces_and_torques().
velocity()
static Utils::Vector3d velocity (Particle const & p_ref, Particle const & p_vs) static
Velocity of the virtual site.
Parameters
p_ref Reference particle for the virtual site.
p_vs Virtual site.
Returns
Velocity of the virtual site.
Definition at line 65 of file relative.cpp.
References connection_vector(), convert_vector_body_to_space(), Particle::omega(), Particle::v(), and vector_product().
Referenced by bd_drag_vel(), bd_random_walk_vel(), walberla::LBWalberlaImpl< FloatType, Architecture >::VelocityVTKWriter< OutputType >::evaluate(), walberla::lbm::accessor::Force::kernel_set(), walberla::lbm::accessor::Velocity::kernel_set(), walberla::lbm::accessor::Force::kernel_set(), walberla::lbm::accessor::Velocity::kernel_set(), walberla::lbm::accessor::Population::kernel_set_vel(), walberla::lbm::accessor::Population::kernel_set_vel(), walberla::pystencils::InitialPDFsSetterDoublePrecision::run(), walberla::pystencils::InitialPDFsSetterSinglePrecision::run(), walberla::pystencils::UpdateVelFromPDFDoublePrecision::run(), walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::run(), walberla::pystencils::UpdateVelFromPDFSinglePrecision::run(), walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::run(), walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::run(), walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::run(), walberla::pystencils::UpdateVelFromPDFDoublePrecisionCUDA::run(), walberla::pystencils::UpdateVelFromPDFSinglePrecisionCUDA::run(), walberla::pystencils::InitialPDFsSetterDoublePrecision::runOnCellInterval(), walberla::pystencils::InitialPDFsSetterSinglePrecision::runOnCellInterval(), walberla::pystencils::UpdateVelFromPDFDoublePrecision::runOnCellInterval(), walberla::pystencils::UpdateVelFromPDFDoublePrecisionAVX::runOnCellInterval(), walberla::pystencils::UpdateVelFromPDFSinglePrecision::runOnCellInterval(), walberla::pystencils::UpdateVelFromPDFSinglePrecisionAVX::runOnCellInterval(), walberla::pystencils::InitialPDFsSetterDoublePrecisionCUDA::runOnCellInterval(), walberla::pystencils::InitialPDFsSetterSinglePrecisionCUDA::runOnCellInterval(), walberla::pystencils::UpdateVelFromPDFDoublePrecisionCUDA::runOnCellInterval(), walberla::pystencils::UpdateVelFromPDFSinglePrecisionCUDA::runOnCellInterval(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_node_velocity_at_boundary(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity(), walberla::LBWalberlaImpl< FloatType, Architecture >::set_slice_velocity_at_boundary(), and vs_relative_update_particles().
vs_relative_back_transfer_forces_and_torques()
void vs_relative_back_transfer_forces_and_torques (CellStructure & cell_structure)
Definition at line 164 of file relative.cpp.
References connection_vector(), CellStructure::for_each_local_particle(), Particle::force(), get_reference_particle(), CellStructure::ghosts_reduce_forces(), init_forces_ghosts(), is_vs(), is_vs_relative_trans(), is_vs_rot(), Particle::torque(), and vector_product().
Referenced by System::System::calculate_forces().
vs_relative_pressure_tensor()
Utils::Matrix< double, 3, 3 > vs_relative_pressure_tensor (CellStructure const & cell_structure)
Definition at line 195 of file relative.cpp.
References constraint_stress(), CellStructure::get_local_particle(), is_vs_relative_trans(), CellStructure::local_particles(), and pressure_tensor.
Referenced by System::System::calculate_pressure().
vs_relative_update_particles()
void vs_relative_update_particles (CellStructure & cell_structure, BoxGeometry const & box_geo)
Definition at line 121 of file relative.cpp.
References CellStructure::check_resort_required(), connection_vector(), Cells::DATA_PART_MOMENTUM, Cells::DATA_PART_POSITION, BoxGeometry::fold_position(), CellStructure::for_each_local_particle(), get_reference_particle(), CellStructure::ghosts_update(), Particle::image_box(), is_vs(), is_vs_relative_rot(), is_vs_relative_trans(), LEES_EDWARDS, Particle::pos(), Particle::quat(), Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), BoxGeometry::type(), Particle::v(), velocity(), and Particle::vs_relative().
Referenced by System::System::integrate(), and System::System::update_dependent_particles().