ESPResSo: rotate_system.cpp File Reference
rotate_system.cpp File Reference
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "cells.hpp"
#include "communication.hpp"
#include "config.hpp"
#include "event.hpp"
#include "rotation.hpp"
#include <utils/Vector.hpp>
#include <utils/math/vec_rotate.hpp>
#include <boost/mpi/collectives.hpp>
#include <algorithm>
#include <array>
#include <cmath>
#include <functional>
Functions
static void mpi_rotate_system_local (double phi, double theta, double alpha)
void mpi_rotate_system (double phi, double theta, double alpha)
Rotate all particle coordinates around an axis given by phi,theta through the center of mass by an angle alpha.
Function Documentation
mpi_rotate_system()
void mpi_rotate_system (double phi, double theta, double alpha)
Rotate all particle coordinates around an axis given by phi,theta through the center of mass by an angle alpha.
Definition at line 78 of file rotate_system.cpp.
References mpi_call_all(), and mpi_rotate_system_local().
mpi_rotate_system_local()
static void mpi_rotate_system_local (double phi, double theta, double alpha) static
Definition at line 37 of file rotate_system.cpp.
References cell_structure, comm_cart, CellStructure::local_particles(), local_rotate_particle(), on_particle_change(), Cells::particles(), Cells::RESORT_GLOBAL, CellStructure::set_resort_particles(), update_dependent_particles(), and Utils::vec_rotate().
Referenced by mpi_rotate_system().