ESPResSo: sd_interface.hpp File Reference
sd_interface.hpp File Reference
#include "config.hpp"
#include "ParticleRange.hpp"
#include <boost/mpi/communicator.hpp>
#include <unordered_map>
Functions
void set_sd_viscosity (double eta)
void set_sd_radius_dict (std::unordered_map< int, double > const &x)
void set_sd_kT (double kT)
double get_sd_kT ()
void set_sd_flags (int flg)
void propagate_vel_pos_sd (const ParticleRange &particles, const boost::mpi::communicator &comm, double time_step)
Takes the forces and torques on all particles and computes their velocities.
Detailed Description
See [20] for the Stokesian dynamics method used here. See [6] and [7] for the thermalization method.
Definition in file sd_interface.hpp.
Function Documentation
get_sd_kT()
double get_sd_kT ()
Definition at line 143 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_kT.
propagate_vel_pos_sd()
void propagate_vel_pos_sd (const ParticleRange & particles, const boost::mpi::communicator & comm, double time_step)
Takes the forces and torques on all particles and computes their velocities.
Acts globally on particles on all nodes; i.e. particle data is gathered from all nodes and their velocities and angular velocities are set according to the Stokesian Dynamics method.
Definition at line 147 of file sd_interface.cpp.
References Utils::Mpi::gather_buffer(), Cells::particles(), anonymous_namespace{sd_interface.cpp}::radius_dict, BaseThermostat::rng_counter(), BaseThermostat::rng_seed(), Utils::Mpi::scatter_buffer(), anonymous_namespace{sd_interface.cpp}::sd_flags, anonymous_namespace{sd_interface.cpp}::sd_kT, sd_update_locally(), anonymous_namespace{sd_interface.cpp}::sd_viscosity, ParticleRange::size(), Utils::sqrt(), stokesian, time_step, and anonymous_namespace{sd_interface.cpp}::v_sd.
Referenced by stokesian_dynamics_propagate_vel_pos().
set_sd_flags()
void set_sd_flags (int flg)
Definition at line 145 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_flags.
set_sd_kT()
void set_sd_kT (double kT)
Definition at line 135 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_kT.
set_sd_radius_dict()
void set_sd_radius_dict (std::unordered_map< int, double > const & x)
Definition at line 122 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::radius_dict.
set_sd_viscosity()
void set_sd_viscosity (double eta)
Definition at line 113 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_viscosity.