ESPResSo: sd_interface.cpp File Reference
sd_interface.cpp File Reference
#include "config.hpp"
#include "sd_interface.hpp"
#include "stokesian_dynamics/sd_cpu.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "thermostat.hpp"
#include <utils/Vector.hpp>
#include <utils/mpi/gather_buffer.hpp>
#include <utils/mpi/scatter_buffer.hpp>
#include <boost/range/algorithm.hpp>
#include <boost/serialization/is_bitwise_serializable.hpp>
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <iterator>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
Namespaces
anonymous_namespace{sd_interface.cpp}
Functions
void sd_update_locally (ParticleRange const &parts)
Update translational and rotational velocities of all particles.
void set_sd_viscosity (double eta)
void set_sd_radius_dict (std::unordered_map< int, double > const &x)
void set_sd_kT (double kT)
double get_sd_kT ()
void set_sd_flags (int flg)
void propagate_vel_pos_sd (const ParticleRange &particles, const boost::mpi::communicator &comm, const double time_step)
Takes the forces and torques on all particles and computes their velocities.
Variables
double anonymous_namespace{sd_interface.cpp}::sd_viscosity = -1.0
std::unordered_map< int, double > anonymous_namespace{sd_interface.cpp}::radius_dict
double anonymous_namespace{sd_interface.cpp}::sd_kT = 0.0
int anonymous_namespace{sd_interface.cpp}::sd_flags = 0
std::vector< double > anonymous_namespace{sd_interface.cpp}::v_sd {}
Buffer that holds the (translational and angular) velocities of the local particles on each node, used for returning results.
Function Documentation
get_sd_kT()
double get_sd_kT ()
Definition at line 143 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_kT.
propagate_vel_pos_sd()
void propagate_vel_pos_sd (const ParticleRange & particles, const boost::mpi::communicator & comm, double time_step)
Takes the forces and torques on all particles and computes their velocities.
Acts globally on particles on all nodes; i.e. particle data is gathered from all nodes and their velocities and angular velocities are set according to the Stokesian Dynamics method.
Definition at line 147 of file sd_interface.cpp.
References Utils::Mpi::gather_buffer(), Cells::particles(), anonymous_namespace{sd_interface.cpp}::radius_dict, BaseThermostat::rng_counter(), BaseThermostat::rng_seed(), Utils::Mpi::scatter_buffer(), anonymous_namespace{sd_interface.cpp}::sd_flags, anonymous_namespace{sd_interface.cpp}::sd_kT, sd_update_locally(), anonymous_namespace{sd_interface.cpp}::sd_viscosity, ParticleRange::size(), Utils::sqrt(), stokesian, time_step, and anonymous_namespace{sd_interface.cpp}::v_sd.
Referenced by stokesian_dynamics_propagate_vel_pos().
sd_update_locally()
void sd_update_locally (ParticleRange const & parts)
Update translational and rotational velocities of all particles.
Definition at line 86 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::v_sd.
Referenced by propagate_vel_pos_sd().
set_sd_flags()
void set_sd_flags (int flg)
Definition at line 145 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_flags.
set_sd_kT()
void set_sd_kT (double kT)
Definition at line 135 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_kT.
set_sd_radius_dict()
void set_sd_radius_dict (std::unordered_map< int, double > const & x)
Definition at line 122 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::radius_dict.
set_sd_viscosity()
void set_sd_viscosity (double eta)
Definition at line 113 of file sd_interface.cpp.
References anonymous_namespace{sd_interface.cpp}::sd_viscosity.