ESPResSo: send_mesh.cpp File Reference
send_mesh.cpp File Reference
#include <config/config.hpp>
#include "fft/fft.hpp"
#include "p3m/common.hpp"
#include "p3m/packing.hpp"
#include "p3m/send_mesh.hpp"
#include <utils/Vector.hpp>
#include <utils/mpi/cart_comm.hpp>
#include <boost/mpi/communicator.hpp>
#include <boost/mpi/datatype.hpp>
#include <mpi.h>
#include <algorithm>
#include <complex>
#include <cstddef>
#include <span>
#include <utility>
Functions
template<typename T >
static void mesh_sendrecv (T const *const sendbuf, int scount, int dest, T *const recvbuf, int rcount, int source, boost::mpi::communicator const &comm, int tag)
template<typename FloatType >
static void p3m_add_block (FloatType const *in, FloatType *out, int const start[3], int const size[3], int const dim[3])
Add values of a 3d-grid input block (size[3]) to values of 3d-grid output array with dimension dim[3] at start position start[3].
Function Documentation
mesh_sendrecv()
template<typename T > static void mesh_sendrecv (T const *const sendbuf, int scount, int dest, T *const recvbuf, int rcount, int source, boost::mpi::communicator const & comm, int tag) static
Definition at line 46 of file send_mesh.cpp.
References stream.
Referenced by p3m_send_mesh< FloatType >::gather_grid(), p3m_send_mesh< FloatType >::resize(), and p3m_send_mesh< FloatType >::spread_grid().
p3m_add_block()
template<typename FloatType > static void p3m_add_block (FloatType const * in, FloatType * out, int const start[3], int const size[3], int const dim[3]) static
Add values of a 3d-grid input block (size[3]) to values of 3d-grid output array with dimension dim[3] at start position start[3].
Parameters
in Pointer to first element of input block data.
out Pointer to first element of output grid.
start Start position of block in output grid.
size Dimensions of the block
dim Dimensions of the output grid.
Definition at line 65 of file send_mesh.cpp.
References stream.
Referenced by p3m_send_mesh< FloatType >::gather_grid().