ESPResSo: short_range_loop.hpp File Reference
short_range_loop.hpp File Reference
#include "config/config.hpp"
#include "cell_system/CellStructure.hpp"
#include <caliper/cali.h>
#include <cassert>
Functions
template<class BondKernel , class PairKernel , class VerletCriterion = detail::True>
void short_range_loop (BondKernel bond_kernel, PairKernel pair_kernel, CellStructure &cell_structure, double pair_cutoff, double bond_cutoff, VerletCriterion const &verlet_criterion={})
Function Documentation
short_range_loop()
template<class BondKernel , class PairKernel , class VerletCriterion = detail::True> void short_range_loop (BondKernel bond_kernel, PairKernel pair_kernel, CellStructure & cell_structure, double pair_cutoff, double bond_cutoff, VerletCriterion const & verlet_criterion = {})
Definition at line 44 of file short_range_loop.hpp.
Referenced by System::System::calculate_energy(), System::System::calculate_forces(), and System::System::calculate_pressure().