ESPResSo: short_range_cabana.hpp File Reference
short_range_cabana.hpp File Reference
#include <config/config.hpp>
#include "cell_system/CellStructure.hpp"
#include "aosoa_pack.hpp"
#include "custom_verlet_list.hpp"
#include "forces_cabana.hpp"
#include <Cabana_Core.hpp>
#include <Cabana_NeighborList.hpp>
#include <caliper/cali.h>
#include <iterator>
#include <span>
#include <utility>
Functions
template<class KokkosRangePolicy = Kokkos::RangePolicy<>>
ESPRESSO_ATTR_ALWAYS_INLINE void kokkos_parallel_range_for (auto const &name, auto start, auto end, auto const &kernel)
ESPRESSO_ATTR_ALWAYS_INLINE void commit_particle (Particle const &p, auto const index, CellStructure::AoSoA_pack &aosoa, bool const rebuild)
ESPRESSO_ATTR_ALWAYS_INLINE void link_cell_kokkos (std::span< Cell *const > cells, BoxGeometry const &box_geo, auto const &verlet_criterion, Kokkos::View< int * > const &id_to_index, int const max_id, auto const &intra_operator, auto const &inter_operator)
ESPRESSO_ATTR_ALWAYS_INLINE void update_cabana_state (CellStructure &cell_structure, auto const &verlet_criterion, double const pair_cutoff, auto const integ_switch)
ESPRESSO_ATTR_ALWAYS_INLINE void update_aosoa_charges (CellStructure &cell_structure)
void cabana_short_range (auto const &bond_kernel, auto const &forces_kernel, CellStructure &cell_structure, double pair_cutoff, double bond_cutoff, auto const &verlet_criterion, auto const integ_switch)
Function Documentation
cabana_short_range()
void cabana_short_range (auto const & bond_kernel, auto const & forces_kernel, CellStructure & cell_structure, double pair_cutoff, double bond_cutoff, auto const & verlet_criterion, auto const integ_switch)
Definition at line 262 of file short_range_cabana.hpp.
References CellStructure::bond_loop(), CellStructure::cell_list_loop(), CellStructure::get_cached_max_local_particle_id(), CellStructure::get_id_to_index(), CellStructure::get_resort_particles(), CellStructure::get_unique_particles(), CellStructure::get_verlet_list_cabana(), INTEG_METHOD_STEEPEST_DESCENT, link_cell_kokkos(), Cells::RESORT_NONE, and CellStructure::use_verlet_list.
Referenced by System::System::calculate_forces().
commit_particle()
ESPRESSO_ATTR_ALWAYS_INLINE void commit_particle (Particle const & p, auto const index, CellStructure::AoSoA_pack & aosoa, bool const rebuild) inline
Definition at line 58 of file short_range_cabana.hpp.
References CellStructure::AoSoA_pack::charge, Utils::convert_quaternion_to_director(), CellStructure::AoSoA_pack::dipm, Particle::dipm(), CellStructure::AoSoA_pack::director, Particle::exclusions(), CellStructure::AoSoA_pack::flags, CellStructure::AoSoA_pack::id, Particle::id(), Particle::pos(), CellStructure::AoSoA_pack::position, Particle::q(), Particle::quat(), CellStructure::AoSoA_pack::set_has_exclusion(), CellStructure::AoSoA_pack::set_vector_at(), CellStructure::AoSoA_pack::type, Particle::type(), Particle::v(), and CellStructure::AoSoA_pack::velocity.
Referenced by update_cabana_state().
kokkos_parallel_range_for()
template<class KokkosRangePolicy = Kokkos::RangePolicy<>> ESPRESSO_ATTR_ALWAYS_INLINE void kokkos_parallel_range_for (auto const & name, auto start, auto end, auto const & kernel) inline
Definition at line 45 of file short_range_cabana.hpp.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel(), anonymous_namespace{dp3m_heffte.impl.hpp}::AssignDipole< cao >::operator()(), anonymous_namespace{dp3m_heffte.impl.hpp}::AssignTorques< cao >::operator()(), anonymous_namespace{dp3m_heffte.impl.hpp}::AssignForcesDip< cao >::operator()(), anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao >::operator()(), and anonymous_namespace{p3m_heffte.impl.hpp}::AssignForces< cao >::operator()().
link_cell_kokkos()
ESPRESSO_ATTR_ALWAYS_INLINE void link_cell_kokkos (std::span< Cell *const > cells, BoxGeometry const & box_geo, auto const & verlet_criterion, Kokkos::View< int * > const & id_to_index, int const max_id, auto const & intra_operator, auto const & inter_operator) inline
Definition at line 91 of file short_range_cabana.hpp.
Referenced by cabana_short_range(), and update_cabana_state().
update_aosoa_charges()
ESPRESSO_ATTR_ALWAYS_INLINE void update_aosoa_charges (CellStructure & cell_structure) inline
Definition at line 247 of file short_range_cabana.hpp.
References CellStructure::get_aosoa(), and CellStructure::get_unique_particles().
Referenced by ICCStar::iteration().
update_cabana_state()
ESPRESSO_ATTR_ALWAYS_INLINE void update_cabana_state (CellStructure & cell_structure, auto const & verlet_criterion, double const pair_cutoff, auto const integ_switch) inline
Definition at line 159 of file short_range_cabana.hpp.
References CustomVerletList< MemorySpace, AlgorithmTag, LayoutTag, BuildTag >::addNeighbor(), CustomVerletList< MemorySpace, AlgorithmTag, LayoutTag, BuildTag >::addNeighborLB(), commit_particle(), CellStructure::get_aosoa(), CellStructure::get_cached_max_local_particle_id(), CellStructure::get_id_to_index(), CellStructure::get_unique_particles(), CustomVerletList< MemorySpace, AlgorithmTag, LayoutTag, BuildTag >::hasOverflow(), INTEG_METHOD_STEEPEST_DESCENT, link_cell_kokkos(), CellStructure::prepare_verlet_list_cabana(), CellStructure::rebuild_verlet_list_cabana(), runtimeWarningMsg, and CellStructure::use_verlet_list.
Referenced by System::System::calculate_forces(), and System::System::rebuild_aosoa().