ESPResSo: specfunc.cuh File Reference
specfunc.cuh File Reference
This file contains implementations for the modified Bessel functions of first and second kind.
#include "config/config.hpp"
#include <utils/constants.hpp>
Functions
__device__ float evaluateAsChebychevSeriesAt (float const *c, int n, float x)
__device__ float evaluateAsTaylorSeriesAt (float const *c, int n, float x)
__device__ float dev_K0 (float x)
__device__ float dev_K1 (float x)
Variables
Chebyshev expansions based on SLATEC bk0(), bk0e()
static __constant__ float bk0_data [11]
static __constant__ int bk0_size = 11
static __constant__ float ak0_data [17]
static __constant__ int ak0_size = 16
static __constant__ float ak02_data [14]
static __constant__ int ak02_size = 13
Chebyshev expansions based on SLATEC besi0()
static __constant__ float bi0_data [12]
static __constant__ int bi0_size = 12
Chebyshev expansions based on SLATEC besk1(), besk1e()
static __constant__ float bk1_data [11]
static __constant__ int bk1_size = 11
static __constant__ float ak1_data [17]
static __constant__ int ak1_size = 17
static __constant__ float ak12_data [14]
static __constant__ int ak12_size = 14
Chebyshev expansions based on SLATEC besi1(), besi1e()
static __constant__ float bi1_data [11]
static __constant__ int bi1_size = 11
Detailed Description
This file contains implementations for the modified Bessel functions of first and second kind.
The implementations are based on the GSL code (see the original GSL header above) and are duplicated from specfunc.cpp.
Definition in file specfunc.cuh.
Function Documentation
dev_K0()
__device__ float dev_K0 (float x)
Definition at line 154 of file specfunc.cuh.
References ak02_data, ak02_size, ak0_data, ak0_size, bi0_data, bi0_size, bk0_data, bk0_size, and evaluateAsChebychevSeriesAt().
Referenced by energiesKernel(), and forcesKernel().
dev_K1()
__device__ float dev_K1 (float x)
Definition at line 173 of file specfunc.cuh.
References ak12_data, ak12_size, ak1_data, ak1_size, bi1_data, bi1_size, bk1_data, bk1_size, and evaluateAsChebychevSeriesAt().
Referenced by besselTuneKernel(), and forcesKernel().
evaluateAsChebychevSeriesAt()
__device__ float evaluateAsChebychevSeriesAt (float const * c, int n, float x)
Definition at line 134 of file specfunc.cuh.
Referenced by dev_K0(), dev_K1(), K0(), and K1().
evaluateAsTaylorSeriesAt()
__device__ float evaluateAsTaylorSeriesAt (float const * c, int n, float x)
Definition at line 146 of file specfunc.cuh.
Referenced by dev_mod_psi_even(), dev_mod_psi_odd(), mod_psi_even(), and mod_psi_odd().
Variable Documentation
ak02_data
__constant__ float ak02_data[14] static
Initial value:
= {
    2.5f - 0.01201869826307592f, -0.00917485269102569f, 0.00014445509317750f,
    -0.00000401361417543f,       0.00000015678318108f,  -0.00000000777011043f,
    0.00000000046111825f,        -0.00000000003158592f, 0.00000000000243501f,
    -0.00000000000020743f,       0.00000000000001925f,  -0.00000000000000192f,
    0.00000000000000020f,        -0.00000000000000002f}
Definition at line 74 of file specfunc.cuh.
Referenced by dev_K0().
ak02_size
__constant__ int ak02_size = 13 static
Definition at line 80 of file specfunc.cuh.
Referenced by dev_K0().
ak0_data
__constant__ float ak0_data[17] static
Initial value:
= {
    2.5f - 0.07643947903327941f, -0.02235652605699819f, 0.00077341811546938f,
    -0.00004281006688886f,       0.00000308170017386f,  -0.00000026393672220f,
    0.00000002563713036f,        -0.00000000274270554f, 0.00000000031694296f,
    -0.00000000003902353f,       0.00000000000506804f,  -0.00000000000068895f,
    0.00000000000009744f,        -0.00000000000001427f, 0.00000000000000215f,
    -0.00000000000000033f,       0.00000000000000005f}
Definition at line 65 of file specfunc.cuh.
Referenced by dev_K0().
ak0_size
__constant__ int ak0_size = 16 static
Definition at line 72 of file specfunc.cuh.
Referenced by dev_K0().
ak12_data
__constant__ float ak12_data[14] static
Initial value:
= {
    2.5f + 0.06379308343739001f, 0.02832887813049721f,  -0.00024753706739052f,
    0.00000577197245160f,        -0.00000020689392195f, 0.00000000973998344f,
    -0.00000000055853361f,       0.00000000003732996f,  -0.00000000000282505f,
    0.00000000000023720f,        -0.00000000000002176f, 0.00000000000000215f,
    -0.00000000000000022f,       0.00000000000000002f}
Definition at line 115 of file specfunc.cuh.
Referenced by dev_K1().
ak12_size
__constant__ int ak12_size = 14 static
Definition at line 121 of file specfunc.cuh.
Referenced by dev_K1().
ak1_data
__constant__ float ak1_data[17] static
Initial value:
= {
    2.5f + 0.27443134069738830f, 0.07571989953199368f,  -0.00144105155647540f,
    0.00006650116955125f,        -0.00000436998470952f, 0.00000035402774997f,
    -0.00000003311163779f,       0.00000000344597758f,  -0.00000000038989323f,
    0.00000000004720819f,        -0.00000000000604783f, 0.00000000000081284f,
    -0.00000000000011386f,       0.00000000000001654f,  -0.00000000000000248f,
    0.00000000000000038f,        -0.00000000000000006f}
Definition at line 106 of file specfunc.cuh.
Referenced by dev_K1().
ak1_size
__constant__ int ak1_size = 17 static
Definition at line 113 of file specfunc.cuh.
Referenced by dev_K1().
bi0_data
__constant__ float bi0_data[12] static
Initial value:
= {
    5.5f - .07660547252839144951f, 1.92733795399380827000f,
    .22826445869203013390f,        .01304891466707290428f,
    .00043442709008164874f,        .00000942265768600193f,
    .00000014340062895106f,        .00000000161384906966f,
    .00000000001396650044f,        .00000000000009579451f,
    .00000000000000053339f,        .00000000000000000245f}
Definition at line 85 of file specfunc.cuh.
Referenced by dev_K0().
bi0_size
__constant__ int bi0_size = 12 static
Definition at line 92 of file specfunc.cuh.
Referenced by dev_K0().
bi1_data
__constant__ float bi1_data[11] static
Initial value:
= {
    1.75f - 0.001971713261099859f, 0.407348876675464810f, 0.034838994299959456f,
    0.001545394556300123f,         0.000041888521098377f, 0.000000764902676483f,
    0.000000010042493924f,         0.000000000099322077f, 0.000000000000766380f,
    0.000000000000004741f,         0.000000000000000024f}
Definition at line 126 of file specfunc.cuh.
Referenced by dev_K1().
bi1_size
__constant__ int bi1_size = 11 static
Definition at line 131 of file specfunc.cuh.
Referenced by dev_K1().
bk0_data
__constant__ float bk0_data[11] static
Initial value:
= {
    -.5f - 0.03532739323390276872f, 0.3442898999246284869f,
    0.03597993651536150163f,        0.00126461541144692592f,
    0.00002286212103119451f,        0.00000025347910790261f,
    0.00000000190451637722f,        0.00000000001034969525f,
    0.00000000000004259816f,        0.00000000000000013744f,
    0.00000000000000000035f}
Definition at line 56 of file specfunc.cuh.
Referenced by dev_K0().
bk0_size
__constant__ int bk0_size = 11 static
Definition at line 63 of file specfunc.cuh.
Referenced by dev_K0().
bk1_data
__constant__ float bk1_data[11] static
Initial value:
= {
    1.5f + 0.0253002273389477705f, -0.3531559607765448760f,
    -0.1226111808226571480f,       -0.0069757238596398643f,
    -0.0001730288957513052f,       -0.0000024334061415659f,
    -0.0000000221338763073f,       -0.0000000001411488392f,
    -0.0000000000006666901f,       -0.0000000000000024274f,
    -0.0000000000000000070f}
Definition at line 97 of file specfunc.cuh.
Referenced by dev_K1().
bk1_size
__constant__ int bk1_size = 11 static
Definition at line 104 of file specfunc.cuh.
Referenced by dev_K1().