ESPResSo: statistics_chain.cpp File Reference
statistics_chain.cpp File Reference
Implementation of statistics_chain.hpp.
#include "analysis/statistics_chain.hpp"
#include "BoxGeometry.hpp"
#include "Particle.hpp"
#include "cell_system/CellStructure.hpp"
#include "communication.hpp"
#include "system/System.hpp"
#include <utils/Vector.hpp>
#include <utils/math/sqr.hpp>
#include <utils/mpi/gather_buffer.hpp>
#include <boost/mpi/collectives/all_reduce.hpp>
#include <array>
#include <cmath>
#include <functional>
#include <stdexcept>
#include <unordered_map>
#include <vector>
Classes
struct GatherParticleTraits< T >
Gather particle properties (or any derived quantities) on MPI rank 0.
struct GatherPos
struct GatherCom
struct GatherMass
Functions
std::array< double, 4 > calc_re (System::System const &system, int chain_start, int chain_length, int n_chains)
Calculate the end-to-end-distance.
std::array< double, 4 > calc_rg (System::System const &system, int chain_start, int chain_length, int n_chains)
Calculate the radius of gyration.
std::array< double, 2 > calc_rh (System::System const &system, int chain_start, int chain_length, int n_chains)
Calculate the hydrodynamic radius (ref.
Detailed Description
Implementation of statistics_chain.hpp.
Definition in file statistics_chain.cpp.
Function Documentation
calc_re()
std::array< double, 4 > calc_re (System::System const & system, int chain_start, int chain_length, int n_chains)
Calculate the end-to-end-distance.
Calculates the average end-to-end-distance of a range of monodisperse polymers with continuous ids.
Parameters
system The system to analyze.
chain_start The id of the first monomer of the first chain.
n_chains Number of chains contained in the range.
chain_length The length of every chain.
Definition at line 105 of file statistics_chain.cpp.
References comm_cart, GatherParticleTraits< T >::fetch(), Utils::sqr(), and stream.
Referenced by ScriptInterface::Analysis::Analysis::do_call_method().
calc_rg()
std::array< double, 4 > calc_rg (System::System const & system, int chain_start, int chain_length, int n_chains)
Calculate the radius of gyration.
Calculates the average radius of gyration of a range of monodisperse polymers with continuous ids.
Parameters
system The system to analyze.
chain_start The id of the first monomer of the first chain.
n_chains Number of chains contained in the range.
chain_length The length of every chain.
Definition at line 137 of file statistics_chain.cpp.
References Utils::Vector< T, N >::at(), comm_cart, Utils::sqr(), and stream.
Referenced by ScriptInterface::Analysis::Analysis::do_call_method().
calc_rh()
std::array< double, 2 > calc_rh (System::System const & system, int chain_start, int chain_length, int n_chains)
Calculate the hydrodynamic radius (ref.
Kirkwood-Zimm theory).
Calculates the average hydrodynamic radius of a range of monodisperse polymers with continuous ids.
Parameters
system The system to analyze.
chain_start The id of the first monomer of the first chain.
n_chains Number of chains contained in the range.
chain_length The length of every chain.
Definition at line 201 of file statistics_chain.cpp.
References comm_cart, GatherParticleTraits< T >::fetch(), Utils::sqr(), and stream.
Referenced by ScriptInterface::Analysis::Analysis::do_call_method().