ESPResSo: steepest_descent.hpp File Reference
steepest_descent.hpp File Reference
#include "ParticleRange.hpp"
#include <boost/serialization/access.hpp>
Classes
struct SteepestDescentParameters
Parameters for the steepest descent algorithm.
Functions
void steepest_descent_init (double f_max, double gamma, double max_displacement)
Steepest descent initializer.
bool steepest_descent_step (const ParticleRange &particles)
Steepest descent integrator.
Function Documentation
steepest_descent_init()
void steepest_descent_init (double f_max, double gamma, double max_displacement)
Steepest descent initializer.
Sets the parameters in SteepestDescentParameters
Definition at line 118 of file steepest_descent.cpp.
References Utils::gamma(), mpi_bcast_steepest_descent(), and params.
Referenced by integrate_set_steepest_descent().
steepest_descent_step()
bool steepest_descent_step (const ParticleRange & particles)
Steepest descent integrator.
Returns
whether the maximum force/torque encountered is below the user limit f_max.
Definition at line 46 of file steepest_descent.cpp.
References cell_structure, comm_cart, dq, f, SteepestDescentParameters::f_max, SteepestDescentParameters::gamma, local_rotate_particle(), SteepestDescentParameters::max_displacement, params, Cells::particles(), Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), Utils::sqr(), and Utils::sqrt().
Referenced by integrator_step_1().