ESPResSo: stoner_wohlfarth_thermal.hpp File Reference
stoner_wohlfarth_thermal.hpp File Reference
#include <config/config.hpp>
#include "cell_system/CellStructure.hpp"
#include "thermostat.hpp"
Functions
void run_magnetodynamics (CellStructure &cell_structure, Thermostat::Thermostat const &thermostat)
Run magnetodynamics update for local virtual particles.
Function Documentation
run_magnetodynamics()
void run_magnetodynamics (CellStructure & cell_structure, Thermostat::Thermostat const & thermostat)
Run magnetodynamics update for local virtual particles.
Iterate over local particles and update the dipole moment of virtual particles according to the thermal Stoner-Wohlfarth model. Collect active homogeneous external magnetic fields from constraints and add the per-particle dipolar contribution before performing either the simplified no-field update or the full thermal Stoner-Wohlfarth update.
Parameters
cell_structure CellStructure providing access to local particles.
thermostat thermostat used to access Philox RNG state and seeds.
Definition at line 258 of file stoner_wohlfarth_thermal.cpp.
References Particle::dip_fld(), CellStructure::for_each_local_particle(), get_external_field(), get_reference_particle(), Particle::id(), Particle::is_virtual(), Thermostat::Thermostat::kT, Thermostat::Thermostat::langevin, Particle::stoner_wohlfarth_is_enabled(), stoner_wohlfarth_main(), stoner_wohlfarth_no_field(), THERMO_LANGEVIN, Thermostat::Thermostat::thermo_switch, and Utils::uniform().
Referenced by System::System::integrate().