ESPResSo: stoner_wohlfarth_thermal.cpp File Reference
stoner_wohlfarth_thermal.cpp File Reference
#include <config/config.hpp>
#include "Particle.hpp"
#include "cell_system/CellStructure.hpp"
#include "cells.hpp"
#include "constraints/Constraints.hpp"
#include "constraints/HomogeneousMagneticField.hpp"
#include "errorhandling.hpp"
#include "random.hpp"
#include "rotation.hpp"
#include "system/System.hpp"
#include "thermostat.hpp"
#include "virtual_sites/relative.hpp"
#include <utils/Vector.hpp>
#include <utils/uniform.hpp>
#include <nlopt.hpp>
#include <cassert>
#include <cmath>
#include <memory>
#include <numbers>
#include <utility>
#include <vector>
Functions
static double phi_objective (unsigned n, const double *x, double *grad, void *my_func_data)
Objective (energy) function for the Stoner-Wohlfarth phi minimisation.
static double get_phi_at_energy_min (double theta, double h, double phi0, double ani_param, double tau0_inv, double dt, double const &noise)
Find the in-plane angle phi corresponding to the correct energy minimum for the thermal Stoner-Wohlfarth particles.
static auto get_external_field (Constraints::Constraints const &constraints)
Collect external homogeneous magnetic field from active constraints.
void stoner_wohlfarth_no_field (Particle &p, Utils::Vector3d const &e_k, double const kT, double const noise)
Simplified Stoner-Wohlfarth update in field-free case.
static void stoner_wohlfarth_main (Particle &p, Utils::Vector3d const &e_k, Utils::Vector3d const &ext_fld_dpl, double const kT, double const noise)
Update virtual site dipole moment according to the full in-field (incl.
Variables
static constexpr double eps_phi = 1e-3
static constexpr double eps_abs = 1e-15
static constexpr double eps_rel = 1e-15
Function Documentation
get_external_field()
static auto get_external_field (Constraints::Constraints const & constraints) static
Collect external homogeneous magnetic field from active constraints.
Iterate over constraints and sum the homogeneous magnetic field vectors provided by Constraints::HomogeneousMagneticField objects.
Returns
The total external homogeneous magnetic field.
Definition at line 159 of file stoner_wohlfarth_thermal.cpp.
References stream.
Referenced by System::System::integrate_magnetodynamics().
get_phi_at_energy_min()
static double get_phi_at_energy_min (double theta, double h, double phi0, double ani_param, double tau0_inv, double dt, double const & noise) static
Find the in-plane angle phi corresponding to the correct energy minimum for the thermal Stoner-Wohlfarth particles.
Parameters
theta Angle between anisotropy director and external field (rad).
h Reduced field (external + dipolar) normalised by H_k.
phi0 Initial in-plane angle guess (rad).
ani_param Inverse thermal energy factor (\(1/(k_B T V)\) scaled).
tau0_inv Attempt frequency inverse (1/tau0).
dt Time increment for switching probability.
noise Uniform random number in (0,1) used for the kinetic MC step.
Returns
In-plane angle phi in range \([0,2\pi) \).
Definition at line 94 of file stoner_wohlfarth_thermal.cpp.
References eps_abs, eps_phi, eps_rel, phi_objective(), and stream.
Referenced by stoner_wohlfarth_main().
phi_objective()
static double phi_objective (unsigned n, const double * x, double * grad, void * my_func_data) static
Objective (energy) function for the Stoner-Wohlfarth phi minimisation.
Evaluate the magnetic energy (normalized by the anisotropy field) for a given in-plane angle phi according to Eq. 5 in [32]. Assumes minima lie in the plane phi = zeta and uses trig identities to reduce the expression.
Parameters
n Number of optimization variables (should be 1: phi).
x Pointer to variables; x[0] is the angle phi.
grad If non-null, gradient is written to grad[0].
my_func_data Pointer to a double[2] array with {theta, h}.
Returns
Energy value for the given phi.
Definition at line 69 of file stoner_wohlfarth_thermal.cpp.
References stream.
Referenced by get_phi_at_energy_min().
stoner_wohlfarth_main()
static void stoner_wohlfarth_main (Particle & p, Utils::Vector3d const & e_k, Utils::Vector3d const & ext_fld_dpl, double const kT, double const noise) static
Update virtual site dipole moment according to the full in-field (incl.
dipole field) thermal Stoner-Wohlfarth model (incl. the kinetic MC step)
Parameters
[in,out] p Virtual particle to update (modified).
e_k Anisotropy director of the reference particle.
ext_fld_dpl External homogeneous magnetic field + total dipolar field acting on the particle.
kT Thermal energy from thermostat.
noise Uniform random number in (0,1) used for the kinetic MC step.
Definition at line 218 of file stoner_wohlfarth_thermal.cpp.
References convert_dip_to_quat(), Particle::dipm(), get_phi_at_energy_min(), Particle::magnetic_anisotropy_energy(), Particle::magnetic_anisotropy_field_inv(), Particle::quat(), Particle::saturation_magnetization(), Particle::stoner_wohlfarth_dt_incr(), Particle::stoner_wohlfarth_phi_0(), Particle::stoner_wohlfarth_tau0_inv(), stream, and vector_product().
Referenced by System::System::integrate_magnetodynamics().
stoner_wohlfarth_no_field()
void stoner_wohlfarth_no_field (Particle & p, Utils::Vector3d const & e_k, double const kT, double const noise)
Simplified Stoner-Wohlfarth update in field-free case.
Parameters
[in,out] p Virtual particle to update.
e_k Anisotropy director of the reference particle.
kT Thermal energy from thermostat.
noise Uniform random number in (0,1) used for the kinetic MC step.
Definition at line 179 of file stoner_wohlfarth_thermal.cpp.
References convert_dip_to_quat(), Particle::dipm(), Particle::magnetic_anisotropy_energy(), Particle::quat(), Particle::saturation_magnetization(), Particle::stoner_wohlfarth_dt_incr(), Particle::stoner_wohlfarth_phi_0(), Particle::stoner_wohlfarth_tau0_inv(), and stream.
Referenced by System::System::integrate_magnetodynamics().
Variable Documentation
eps_abs
constexpr double eps_abs = 1e-15 static constexpr
Definition at line 51 of file stoner_wohlfarth_thermal.cpp.
Referenced by get_phi_at_energy_min().
eps_phi
constexpr double eps_phi = 1e-3 static constexpr
Definition at line 49 of file stoner_wohlfarth_thermal.cpp.
Referenced by get_phi_at_energy_min().
eps_rel
constexpr double eps_rel = 1e-15 static constexpr
Definition at line 53 of file stoner_wohlfarth_thermal.cpp.
Referenced by get_phi_at_energy_min().