ESPResSo: Particle Struct Reference
Particle Struct Reference
Struct holding all information for one particle.
#include <Particle.hpp>
Public Member Functions
auto const & id () const
auto & id ()
auto const & mol_id () const
auto & mol_id ()
auto const & type () const
auto & type ()
auto const & propagation () const
auto & propagation ()
bool operator== (Particle const &rhs) const
bool operator!= (Particle const &rhs) const
auto const & bonds () const
auto & bonds ()
auto const & pos () const
auto & pos ()
auto const & v () const
auto & v ()
auto const & force () const
auto & force ()
auto const & force_and_torque () const
auto & force_and_torque ()
bool is_ghost () const
void set_ghost (bool const ghost_flag)
auto & pos_at_last_verlet_update ()
auto const & pos_at_last_verlet_update () const
auto const & image_box () const
auto & image_box ()
auto const & lees_edwards_offset () const
auto & lees_edwards_offset ()
auto const & lees_edwards_flag () const
auto & lees_edwards_flag ()
auto const & mass () const
auto & mass ()
auto const & rotation () const
auto & rotation ()
bool can_rotate () const
bool can_rotate_around (unsigned int const axis) const
void set_can_rotate_around (unsigned int const axis, bool const rot_flag)
void set_can_rotate_all_axes ()
void set_cannot_rotate_all_axes ()
auto const & quat () const
auto & quat ()
auto const & torque () const
auto & torque ()
auto const & omega () const
auto & omega ()
auto const & ext_torque () const
auto & ext_torque ()
auto calc_director () const
auto const & dipm () const
auto & dipm ()
auto calc_dip () const
auto const & stoner_wohlfarth_is_enabled () const
auto & stoner_wohlfarth_is_enabled ()
auto const & stoner_wohlfarth_phi_0 () const
auto & stoner_wohlfarth_phi_0 ()
auto const & saturation_magnetization () const
auto & saturation_magnetization ()
auto const & magnetic_anisotropy_field_inv () const
auto & magnetic_anisotropy_field_inv ()
auto const & magnetic_anisotropy_energy () const
auto & magnetic_anisotropy_energy ()
auto const & stoner_wohlfarth_tau0_inv () const
auto & stoner_wohlfarth_tau0_inv ()
auto const & stoner_wohlfarth_dt_incr () const
auto & stoner_wohlfarth_dt_incr ()
auto const & dip_fld () const
auto & dip_fld ()
auto const & rinertia () const
auto & rinertia ()
auto const & q () const
auto & q ()
auto const & mu_E () const
auto & mu_E ()
auto is_virtual () const
auto const & vs_relative () const
auto & vs_relative ()
auto const & gamma () const
auto & gamma ()
auto const & gamma_rot () const
auto & gamma_rot ()
auto const & fixed () const
auto & fixed ()
bool has_fixed_coordinates () const
bool is_fixed_along (unsigned int const axis) const
void set_fixed_along (int const axis, bool const fixed_flag)
auto const & ext_force () const
auto & ext_force ()
auto const & swimming () const
auto & swimming ()
auto const & pos_last_time_step () const
auto & pos_last_time_step ()
auto const & rattle_params () const
auto & rattle_params ()
auto const & rattle_correction () const
auto & rattle_correction ()
Utils::compact_vector< int > & exclusions ()
Utils::compact_vector< int > const & exclusions () const
bool has_exclusion (int pid) const
Detailed Description
Struct holding all information for one particle.
Definition at line 435 of file Particle.hpp.
Member Function Documentation
bonds() [1/2]
auto & Particle::bonds () inline
Definition at line 469 of file Particle.hpp.
bonds() [2/2]
auto const & Particle::bonds () const inline
Definition at line 468 of file Particle.hpp.
Referenced by add_bond(), ScriptInterface::Particles::ParticleHandle::do_call_method(), BondedInteractionsMap::pair_bond_exists_on(), BondBreakage::remove_bond(), BondBreakage::remove_pair_bonds_to(), and ScriptInterface::Particles::set_particles_bonds().
calc_dip()
auto Particle::calc_dip () const inline
Definition at line 535 of file Particle.hpp.
References calc_director(), and dipm().
Referenced by Constraints::HomogeneousMagneticField::add_energy(), DipolarLayerCorrection::add_force_corrections(), calc_slab_dipole(), dipolar_energy_correction(), dipolar_force_corrections(), ParticleObservables::traits< Particle >::dipole_moment(), Constraints::HomogeneousMagneticField::force(), and ScriptInterface::Particles::ParticleHandle::ParticleHandle().
calc_director()
auto Particle::calc_director () const inline
Definition at line 527 of file Particle.hpp.
References ParticlePosition::calc_director().
Referenced by calc_dip(), ParticleObservables::traits< Particle >::director(), and external_force().
can_rotate()
bool Particle::can_rotate () const inline
Definition at line 500 of file Particle.hpp.
References ParticleProperties::rotation.
Referenced by brownian_dynamics_rotator(), convert_torque_propagate_omega(), local_rotate_particle_body(), propagate_omega_quat_particle(), symplectic_euler_rotator_1(), velocity_verlet_rotator_1(), and velocity_verlet_rotator_2().
can_rotate_around()
bool Particle::can_rotate_around (unsigned int const axis) const inline
Definition at line 501 of file Particle.hpp.
References ParticleProperties::rotation, and stream.
Referenced by bd_drag_rot(), bd_drag_vel_rot(), bd_random_walk_rot(), bd_random_walk_vel_rot(), and define_Qdd().
dip_fld() [1/2]
auto & Particle::dip_fld () inline
Definition at line 569 of file Particle.hpp.
References ParticleProperties::dip_fld.
dip_fld() [2/2]
auto const & Particle::dip_fld () const inline
Definition at line 568 of file Particle.hpp.
References ParticleProperties::dip_fld.
Referenced by ParticleObservables::traits< Particle >::dipole_field(), System::System::integrate_magnetodynamics(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and reinit_dip_fld().
dipm() [1/2]
auto & Particle::dipm () inline
Definition at line 534 of file Particle.hpp.
References ParticleProperties::dipm.
dipm() [2/2]
auto const & Particle::dipm () const inline
Definition at line 533 of file Particle.hpp.
References ParticleProperties::dipm.
Referenced by DipolarLayerCorrection::add_force_corrections(), calc_dip(), calc_slab_dipole(), commit_particle(), count_magnetic_particles(), dipolar_energy_correction(), dipolar_force_corrections(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), stoner_wohlfarth_main(), and stoner_wohlfarth_no_field().
exclusions() [1/2]
Utils::compact_vector< int > & Particle::exclusions () inline
Definition at line 646 of file Particle.hpp.
Referenced by add_exclusion(), commit_particle(), delete_exclusion(), and ScriptInterface::Particles::ParticleHandle::do_call_method().
exclusions() [2/2]
Utils::compact_vector< int > const & Particle::exclusions () const inline
Definition at line 647 of file Particle.hpp.
ext_force() [1/2]
auto & Particle::ext_force () inline
Definition at line 627 of file Particle.hpp.
References ParticleProperties::ext_force.
ext_force() [2/2]
auto const & Particle::ext_force () const inline
Definition at line 626 of file Particle.hpp.
References ParticleProperties::ext_force.
Referenced by external_force(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
ext_torque() [1/2]
auto & Particle::ext_torque () inline
Definition at line 525 of file Particle.hpp.
References ParticleProperties::ext_torque.
ext_torque() [2/2]
auto const & Particle::ext_torque () const inline
Definition at line 524 of file Particle.hpp.
References ParticleProperties::ext_torque.
Referenced by external_force(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
fixed() [1/2]
auto & Particle::fixed () inline
Definition at line 612 of file Particle.hpp.
References ParticleProperties::ext_flag.
fixed() [2/2]
auto const & Particle::fixed () const inline
Definition at line 611 of file Particle.hpp.
References ParticleProperties::ext_flag.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
force() [1/2]
auto & Particle::force () inline
Definition at line 476 of file Particle.hpp.
References ParticleForce::f.
force() [2/2]
auto const & Particle::force () const inline
Definition at line 475 of file Particle.hpp.
References ParticleForce::f.
Referenced by DipolarLayerCorrection::add_force_corrections(), add_PoQ_force(), add_PQ_force(), bd_drag(), bd_drag_vel(), ParticleObservables::traits< Particle >::force(), force_capping(), init_forces_and_thermostat(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), symplectic_euler_propagator_1(), velocity_verlet_propagator_1(), velocity_verlet_propagator_2(), vs_com_back_transfer_forces_and_torques(), vs_relative_back_transfer_forces_and_torques(), and Writer::H5md::File::write().
force_and_torque() [1/2]
auto & Particle::force_and_torque () inline
Definition at line 478 of file Particle.hpp.
force_and_torque() [2/2]
auto const & Particle::force_and_torque () const inline
Definition at line 477 of file Particle.hpp.
Referenced by CellStructure::ghosts_reset_forces(), and init_forces_and_thermostat().
gamma() [1/2]
auto & Particle::gamma () inline
Definition at line 604 of file Particle.hpp.
References ParticleProperties::gamma.
gamma() [2/2]
auto const & Particle::gamma () const inline
Definition at line 603 of file Particle.hpp.
References ParticleProperties::gamma.
Referenced by bd_drag(), bd_drag_vel(), bd_random_walk(), friction_thermo_langevin(), LB::lb_coupling_sanity_checks(), lb_handle_particle_anisotropy(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
gamma_rot() [1/2]
auto & Particle::gamma_rot () inline
Definition at line 607 of file Particle.hpp.
References ParticleProperties::gamma_rot.
gamma_rot() [2/2]
auto const & Particle::gamma_rot () const inline
Definition at line 606 of file Particle.hpp.
References ParticleProperties::gamma_rot.
Referenced by bd_drag_rot(), bd_drag_vel_rot(), bd_random_walk_rot(), friction_thermo_langevin_rotation(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
has_exclusion()
bool Particle::has_exclusion (int pid) const inline
Definition at line 648 of file Particle.hpp.
Referenced by ScriptInterface::Particles::ParticleHandle::do_call_method().
has_fixed_coordinates()
bool Particle::has_fixed_coordinates () const inline
Definition at line 613 of file Particle.hpp.
References ParticleProperties::ext_flag.
id() [1/2]
auto & Particle::id () inline
Definition at line 455 of file Particle.hpp.
References ParticleProperties::identity.
id() [2/2]
auto const & Particle::id () const inline
Definition at line 454 of file Particle.hpp.
References ParticleProperties::identity.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), ClusterAnalysis::Cluster::add_particle(), bd_random_walk(), bd_random_walk_rot(), bd_random_walk_vel(), bd_random_walk_vel_rot(), BondBreakage::bond_handler(), CellStructure::check_particle_index(), commit_particle(), Constraints::ShapeBasedConstraint::force(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), get_neighbor_pids(), LB::ParticleCoupling::get_noise_term(), get_reference_particle(), ParticleObservables::traits< Particle >::id(), System::System::integrate_magnetodynamics(), LB::lb_coupling_sanity_checks(), operator!=(), operator==(), ClusterAnalysis::ClusterStructure::part_of_cluster(), System::System::particle_bond_energy(), AtomDecomposition::particle_to_cell(), AtomDecomposition::particle_to_cell(), serialize_and_reduce(), CellStructure::set_index_map(), LB::CouplingBookkeeping::should_be_coupled(), CellStructure::update_particle_index(), CellStructure::update_particle_index(), vs_com_back_transfer_forces_and_torques(), vs_com_update_particles(), and Writer::H5md::File::write().
image_box() [1/2]
auto & Particle::image_box () inline
Definition at line 485 of file Particle.hpp.
References ParticlePosition::i.
image_box() [2/2]
auto const & Particle::image_box () const inline
Definition at line 484 of file Particle.hpp.
References ParticlePosition::i.
Referenced by calc_dipole_moment(), fold_and_reset(), GatherPos::kernel(), GatherCom::kernel(), LeesEdwards::Push::operator()(), ParticleObservables::traits< Particle >::position(), serialize_and_reduce(), vs_com_update_particles(), and vs_relative_update_particles().
is_fixed_along()
bool Particle::is_fixed_along (unsigned int const axis) const inline
Definition at line 614 of file Particle.hpp.
References ParticleProperties::ext_flag, and stream.
Referenced by bd_drag(), bd_drag_vel(), bd_random_walk(), bd_random_walk_vel(), symplectic_euler_propagator_1(), velocity_verlet_propagator_1(), and velocity_verlet_propagator_2().
is_ghost()
bool Particle::is_ghost () const inline
Definition at line 480 of file Particle.hpp.
References ParticleLocal::ghost.
Referenced by CellStructure::find_current_cell(), System::System::particle_bond_energy(), and LB::CouplingBookkeeping::should_be_coupled().
is_virtual()
auto Particle::is_virtual () const inline
Definition at line 588 of file Particle.hpp.
References ParticleProperties::propagation, PropagationMode::ROT_VS_INDEPENDENT, PropagationMode::ROT_VS_RELATIVE, PropagationMode::TRANS_LB_TRACER, PropagationMode::TRANS_VS_CENTER_OF_MASS, and PropagationMode::TRANS_VS_RELATIVE.
Referenced by ScriptInterface::Particles::ParticleHandle::do_call_method(), System::System::integrate_magnetodynamics(), integrator_step_1(), integrator_step_2(), ParticleObservables::traits< Particle >::mass(), FieldCoupling::Coupling::Mass::operator()(), translational_kinetic_energy(), and vs_com_update_particles().
lees_edwards_flag() [1/2]
auto & Particle::lees_edwards_flag () inline
Definition at line 489 of file Particle.hpp.
References ParticleLocal::lees_edwards_flag.
lees_edwards_flag() [2/2]
auto const & Particle::lees_edwards_flag () const inline
Definition at line 488 of file Particle.hpp.
References ParticleLocal::lees_edwards_flag.
Referenced by LeesEdwards::Push::operator()(), and ScriptInterface::Particles::ParticleHandle::ParticleHandle().
lees_edwards_offset() [1/2]
auto & Particle::lees_edwards_offset () inline
Definition at line 487 of file Particle.hpp.
References ParticleLocal::lees_edwards_offset.
lees_edwards_offset() [2/2]
auto const & Particle::lees_edwards_offset () const inline
Definition at line 486 of file Particle.hpp.
References ParticleLocal::lees_edwards_offset.
Referenced by LeesEdwards::Push::operator()(), and ScriptInterface::Particles::ParticleHandle::ParticleHandle().
magnetic_anisotropy_energy() [1/2]
auto & Particle::magnetic_anisotropy_energy () inline
Definition at line 557 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::ani_energy, and ParticleProperties::magnetodynamics.
magnetic_anisotropy_energy() [2/2]
auto const & Particle::magnetic_anisotropy_energy () const inline
Definition at line 554 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::ani_energy, and ParticleProperties::magnetodynamics.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), stoner_wohlfarth_main(), and stoner_wohlfarth_no_field().
magnetic_anisotropy_field_inv() [1/2]
auto & Particle::magnetic_anisotropy_field_inv () inline
Definition at line 551 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::ani_fld_inv, and ParticleProperties::magnetodynamics.
magnetic_anisotropy_field_inv() [2/2]
auto const & Particle::magnetic_anisotropy_field_inv () const inline
Definition at line 548 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::ani_fld_inv, and ParticleProperties::magnetodynamics.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and stoner_wohlfarth_main().
mass() [1/2]
auto & Particle::mass () inline
Definition at line 493 of file Particle.hpp.
References ParticleProperties::mass.
mass() [2/2]
auto const & Particle::mass () const inline
Definition at line 492 of file Particle.hpp.
References ParticleProperties::mass.
Referenced by bd_random_walk_vel(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), GatherCom::kernel(), GatherMass::kernel(), ParticleObservables::traits< Particle >::mass(), FieldCoupling::Coupling::Mass::operator()(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), symplectic_euler_propagator_1(), translational_kinetic_energy(), velocity_verlet_propagator_1(), velocity_verlet_propagator_2(), vs_com_back_transfer_forces_and_torques(), vs_com_update_particles(), and Writer::H5md::File::write().
mol_id() [1/2]
auto & Particle::mol_id () inline
Definition at line 457 of file Particle.hpp.
References ParticleProperties::mol_id.
mol_id() [2/2]
auto const & Particle::mol_id () const inline
Definition at line 456 of file Particle.hpp.
References ParticleProperties::mol_id.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), get_pid_for_vs_com(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), vs_com_back_transfer_forces_and_torques(), and vs_com_update_particles().
mu_E() [1/2]
auto & Particle::mu_E () inline
Definition at line 585 of file Particle.hpp.
References ParticleProperties::mu_E.
mu_E() [2/2]
auto const & Particle::mu_E () const inline
Definition at line 584 of file Particle.hpp.
References ParticleProperties::mu_E.
Referenced by lb_drag_force(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
omega() [1/2]
auto & Particle::omega () inline
Definition at line 522 of file Particle.hpp.
References ParticleMomentum::omega.
omega() [2/2]
auto const & Particle::omega () const inline
Definition at line 521 of file Particle.hpp.
References ParticleMomentum::omega.
Referenced by ParticleObservables::traits< Particle >::angular_velocity(), ParticleObservables::traits< Particle >::angular_velocity_body(), brownian_dynamics_rotator(), convert_torque_propagate_omega(), define_Qdd(), friction_thermo_langevin_rotation(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), propagate_omega_quat_particle(), and serialize_and_reduce().
operator!=()
bool Particle::operator!= (Particle const & rhs) const inline
Definition at line 466 of file Particle.hpp.
References id(), and stream.
operator==()
bool Particle::operator== (Particle const & rhs) const inline
Definition at line 464 of file Particle.hpp.
References id(), and stream.
pos() [1/2]
auto & Particle::pos () inline
Definition at line 472 of file Particle.hpp.
References ParticlePosition::p.
pos() [2/2]
auto const & Particle::pos () const inline
Definition at line 471 of file Particle.hpp.
References ParticlePosition::p.
Referenced by apply_positional_correction(), BondBreakage::bond_handler(), brownian_dynamics_propagator(), calc_dipole_moment(), ClusterAnalysis::Cluster::center_of_mass_subcluster(), commit_particle(), dipolar_energy_correction(), dipolar_force_corrections(), fold_and_reset(), Constraints::ShapeBasedConstraint::force(), get_ibm_particle_position(), GatherPos::kernel(), GatherCom::kernel(), ClusterAnalysis::Cluster::longest_distance(), LeesEdwards::Push::operator()(), RegularDecomposition::particle_to_cell(), RegularDecomposition::particle_to_cell(), ParticleObservables::traits< Particle >::position(), ParticleObservables::traits< Particle >::position_folded(), ClusterAnalysis::Cluster::radius_of_gyration_subcluster(), serialize_and_reduce(), setup_PoQ(), setup_PQ(), symplectic_euler_propagator_1(), velocity_verlet_propagator_1(), vs_com_update_particles(), and vs_relative_update_particles().
pos_at_last_verlet_update() [1/2]
auto & Particle::pos_at_last_verlet_update () inline
Definition at line 482 of file Particle.hpp.
References ParticleLocal::p_old.
Referenced by fold_and_reset().
pos_at_last_verlet_update() [2/2]
auto const & Particle::pos_at_last_verlet_update () const inline
Definition at line 483 of file Particle.hpp.
References ParticleLocal::p_old.
pos_last_time_step() [1/2]
auto & Particle::pos_last_time_step () inline
Definition at line 638 of file Particle.hpp.
References ParticlePosition::p_last_timestep.
pos_last_time_step() [2/2]
auto const & Particle::pos_last_time_step () const inline
Definition at line 637 of file Particle.hpp.
References ParticlePosition::p_last_timestep.
Referenced by serialize_and_reduce().
propagation() [1/2]
auto & Particle::propagation () inline
Definition at line 462 of file Particle.hpp.
References ParticleProperties::propagation.
propagation() [2/2]
auto const & Particle::propagation () const inline
Definition at line 461 of file Particle.hpp.
References ParticleProperties::propagation.
Referenced by LB::is_tracer(), is_vs_com(), is_vs_independent_rot(), is_vs_relative_rot(), is_vs_relative_trans(), PropagationPredicate< Predicate >::operator()(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), LB::CouplingBookkeeping::should_be_coupled(), and Propagation::should_propagate_with().
q() [1/2]
auto & Particle::q () inline
Definition at line 579 of file Particle.hpp.
References ParticleProperties::q.
q() [2/2]
auto const & Particle::q () const inline
Definition at line 578 of file Particle.hpp.
References ParticleProperties::q.
Referenced by calc_dipole_moment(), calc_total_charge(), ParticleObservables::traits< Particle >::charge(), commit_particle(), FieldCoupling::Coupling::Charge::operator()(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), ScriptInterface::Particles::set_particles_charges(), setup_PoQ(), setup_PQ(), and Writer::H5md::File::write().
quat() [1/2]
auto & Particle::quat () inline
Definition at line 518 of file Particle.hpp.
References ParticlePosition::quat.
quat() [2/2]
auto const & Particle::quat () const inline
Definition at line 517 of file Particle.hpp.
References ParticlePosition::quat.
Referenced by bd_drag_rot(), bd_random_walk_rot(), brownian_dynamics_rotator(), commit_particle(), convert_body_to_space(), convert_vector_body_to_space(), convert_vector_space_to_body(), define_Qdd(), local_rotate_particle(), local_rotate_particle_body(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), propagate_omega_quat_particle(), serialize_and_reduce(), stoner_wohlfarth_main(), stoner_wohlfarth_no_field(), and vs_relative_update_particles().
rattle_correction() [1/2]
auto & Particle::rattle_correction () inline
Definition at line 642 of file Particle.hpp.
References ParticleRattle::correction.
rattle_correction() [2/2]
auto const & Particle::rattle_correction () const inline
Definition at line 641 of file Particle.hpp.
References ParticleRattle::correction.
Referenced by serialize_and_reduce().
rattle_params() [1/2]
auto & Particle::rattle_params () inline
Definition at line 640 of file Particle.hpp.
rattle_params() [2/2]
auto const & Particle::rattle_params () const inline
Definition at line 639 of file Particle.hpp.
Referenced by apply_positional_correction(), and apply_velocity_correction().
rinertia() [1/2]
auto & Particle::rinertia () inline
Definition at line 573 of file Particle.hpp.
References ParticleProperties::rinertia.
rinertia() [2/2]
auto const & Particle::rinertia () const inline
Definition at line 572 of file Particle.hpp.
References ParticleProperties::rinertia.
Referenced by bd_random_walk_vel_rot(), convert_torque_propagate_omega(), define_Qdd(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
rotation() [1/2]
auto & Particle::rotation () inline
Definition at line 499 of file Particle.hpp.
References ParticleProperties::rotation.
rotation() [2/2]
auto const & Particle::rotation () const inline
Definition at line 498 of file Particle.hpp.
References ParticleProperties::rotation.
Referenced by bd_drag_rot(), bd_drag_vel_rot(), bd_random_walk_rot(), bd_random_walk_vel_rot(), convert_torque_to_body_frame_apply_fix(), local_rotate_particle_body(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), propagate_omega_quat_particle(), and serialize_and_reduce().
saturation_magnetization() [1/2]
auto & Particle::saturation_magnetization () inline
Definition at line 547 of file Particle.hpp.
References ParticleProperties::magnetodynamics, and ThermalStonerWohlfarthParameters::sat_mag.
saturation_magnetization() [2/2]
auto const & Particle::saturation_magnetization () const inline
Definition at line 544 of file Particle.hpp.
References ParticleProperties::magnetodynamics, and ThermalStonerWohlfarthParameters::sat_mag.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), stoner_wohlfarth_main(), and stoner_wohlfarth_no_field().
set_can_rotate_all_axes()
void Particle::set_can_rotate_all_axes () inline
Definition at line 513 of file Particle.hpp.
References ParticleProperties::rotation, and stream.
Referenced by CollisionDetection::BindAtPointOfCollision::handle_collisions().
set_can_rotate_around()
void Particle::set_can_rotate_around (unsigned int const axis, bool const rot_flag) inline
Definition at line 505 of file Particle.hpp.
References ParticleProperties::rotation, and stream.
set_cannot_rotate_all_axes()
void Particle::set_cannot_rotate_all_axes () inline
Definition at line 514 of file Particle.hpp.
References ParticleProperties::rotation, and stream.
set_fixed_along()
void Particle::set_fixed_along (int const axis, bool const fixed_flag) inline
Definition at line 618 of file Particle.hpp.
References ParticleProperties::ext_flag, and stream.
set_ghost()
void Particle::set_ghost (bool const ghost_flag) inline
Definition at line 481 of file Particle.hpp.
References ParticleLocal::ghost, and stream.
stoner_wohlfarth_dt_incr() [1/2]
auto & Particle::stoner_wohlfarth_dt_incr () inline
Definition at line 565 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::dt_incr, and ParticleProperties::magnetodynamics.
stoner_wohlfarth_dt_incr() [2/2]
auto const & Particle::stoner_wohlfarth_dt_incr () const inline
Definition at line 562 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::dt_incr, and ParticleProperties::magnetodynamics.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), stoner_wohlfarth_main(), and stoner_wohlfarth_no_field().
stoner_wohlfarth_is_enabled() [1/2]
auto & Particle::stoner_wohlfarth_is_enabled () inline
Definition at line 541 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::is_enabled, and ParticleProperties::magnetodynamics.
stoner_wohlfarth_is_enabled() [2/2]
auto const & Particle::stoner_wohlfarth_is_enabled () const inline
Definition at line 538 of file Particle.hpp.
References ThermalStonerWohlfarthParameters::is_enabled, and ParticleProperties::magnetodynamics.
Referenced by System::System::integrate_magnetodynamics(), and ScriptInterface::Particles::ParticleHandle::ParticleHandle().
stoner_wohlfarth_phi_0() [1/2]
auto & Particle::stoner_wohlfarth_phi_0 () inline
Definition at line 543 of file Particle.hpp.
References ParticleProperties::magnetodynamics, and ThermalStonerWohlfarthParameters::phi0.
stoner_wohlfarth_phi_0() [2/2]
auto const & Particle::stoner_wohlfarth_phi_0 () const inline
Definition at line 542 of file Particle.hpp.
References ParticleProperties::magnetodynamics, and ThermalStonerWohlfarthParameters::phi0.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), stoner_wohlfarth_main(), and stoner_wohlfarth_no_field().
stoner_wohlfarth_tau0_inv() [1/2]
auto & Particle::stoner_wohlfarth_tau0_inv () inline
Definition at line 561 of file Particle.hpp.
References ParticleProperties::magnetodynamics, and ThermalStonerWohlfarthParameters::tau0_inv.
stoner_wohlfarth_tau0_inv() [2/2]
auto const & Particle::stoner_wohlfarth_tau0_inv () const inline
Definition at line 558 of file Particle.hpp.
References ParticleProperties::magnetodynamics, and ThermalStonerWohlfarthParameters::tau0_inv.
Referenced by ScriptInterface::Particles::ParticleHandle::ParticleHandle(), stoner_wohlfarth_main(), and stoner_wohlfarth_no_field().
swimming() [1/2]
auto & Particle::swimming () inline
Definition at line 634 of file Particle.hpp.
References ParticleProperties::swim.
swimming() [2/2]
auto const & Particle::swimming () const inline
Definition at line 633 of file Particle.hpp.
References ParticleProperties::swim.
Referenced by external_force(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), and serialize_and_reduce().
torque() [1/2]
auto & Particle::torque () inline
Definition at line 520 of file Particle.hpp.
References ParticleForce::torque.
torque() [2/2]
auto const & Particle::torque () const inline
Definition at line 519 of file Particle.hpp.
References ParticleForce::torque.
Referenced by DipolarLayerCorrection::add_force_corrections(), bd_drag_rot(), bd_drag_vel_rot(), convert_torque_propagate_omega(), convert_torque_to_body_frame_apply_fix(), define_Qdd(), init_forces_and_thermostat(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), and vs_relative_back_transfer_forces_and_torques().
type() [1/2]
auto & Particle::type () inline
Definition at line 459 of file Particle.hpp.
References ParticleProperties::type.
type() [2/2]
auto const & Particle::type () const inline
Definition at line 458 of file Particle.hpp.
References ParticleProperties::type.
Referenced by Constraints::ShapeBasedConstraint::add_energy(), commit_particle(), Constraints::ShapeBasedConstraint::force(), get_pairs_of_types(), CollisionDetection::GlueToSurface::handle_collisions(), HybridDecomposition::particle_to_cell(), HybridDecomposition::particle_to_cell(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), ScriptInterface::Particles::set_particles_types(), Constraints::ShapeBasedConstraint::set_type(), Constraints::ShapeBasedConstraint::type(), and Writer::H5md::File::write().
v() [1/2]
auto & Particle::v () inline
Definition at line 474 of file Particle.hpp.
References ParticleMomentum::v.
v() [2/2]
auto const & Particle::v () const inline
Definition at line 473 of file Particle.hpp.
References ParticleMomentum::v.
Referenced by apply_positional_correction(), apply_velocity_correction(), brownian_dynamics_propagator(), commit_particle(), Constraints::ShapeBasedConstraint::force(), friction_thermo_langevin(), lb_drag_force(), LeesEdwards::Push::operator()(), FieldCoupling::Coupling::Viscous::operator()(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), symplectic_euler_propagator_1(), translational_kinetic_energy(), Constraints::ShapeBasedConstraint::velocity(), ParticleObservables::traits< Particle >::velocity(), ParticleObservables::traits< Particle >::velocity_body(), velocity_verlet_propagator_1(), velocity_verlet_propagator_2(), vs_relative_update_particles(), and Writer::H5md::File::write().
vs_relative() [1/2]
auto & Particle::vs_relative () inline
Definition at line 600 of file Particle.hpp.
References ParticleProperties::vs_relative.
vs_relative() [2/2]
auto const & Particle::vs_relative () const inline
Definition at line 599 of file Particle.hpp.
References ParticleProperties::vs_relative.
Referenced by get_reference_particle(), ScriptInterface::Particles::ParticleHandle::ParticleHandle(), serialize_and_reduce(), and vs_relative_update_particles().
The documentation for this struct was generated from the following file:
Particle.hpp