ESPResSo: anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao > Struct Template Reference
anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao > Struct Template Reference
#include <p3m_heffte.impl.hpp>
Public Member Functions
void operator() (auto &p3m, double q, InterpolationWeights< cao > const &weights)
void operator() (auto &p3m, double q, Utils::Vector3d const &real_pos, p3m_interpolation_cache &inter_weights)
void operator() (auto &p3m, double q, Utils::Vector3d const &real_pos)
void operator() (auto &p3m, auto &cell_structure)
Detailed Description
template<int cao>
struct anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao >
Definition at line 345 of file p3m_heffte.impl.hpp.
Member Function Documentation
operator()() [1/4]
template<int cao> void anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao >::operator() (auto & p3m, auto & cell_structure) inline
Definition at line 372 of file p3m_heffte.impl.hpp.
References CoulombP3MState< FloatType, FFTConfig >::inter_weights, kokkos_parallel_range_for(), p3m_interpolate(), Utils::ROW_MAJOR, stream, and p3m_interpolation_cache::zfill().
operator()() [2/4]
template<int cao> void anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao >::operator() (auto & p3m, double q, InterpolationWeights< cao > const & weights) inline
Definition at line 346 of file p3m_heffte.impl.hpp.
References p3m_interpolate().
operator()() [3/4]
template<int cao> void anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao >::operator() (auto & p3m, double q, Utils::Vector3d const & real_pos) inline
Definition at line 364 of file p3m_heffte.impl.hpp.
References Utils::ROW_MAJOR, and stream.
operator()() [4/4]
template<int cao> void anonymous_namespace{p3m_heffte.impl.hpp}::AssignCharge< cao >::operator() (auto & p3m, double q, Utils::Vector3d const & real_pos, p3m_interpolation_cache & inter_weights) inline
Definition at line 355 of file p3m_heffte.impl.hpp.
References Utils::ROW_MAJOR, p3m_interpolation_cache::store(), and stream.
The documentation for this struct was generated from the following file:
p3m_heffte.impl.hpp