ESPResSo: SteepestDescent Struct Reference
SteepestDescent Struct Reference
Steepest descent algorithm.
#include <steepest_descent.hpp>
Public Member Functions
SteepestDescent ()=default
SteepestDescent (double f_max, double gamma, double max_displacement)
bool propagate (CellStructure &cell_structure) const
Run steepest descent algorithm.
Public Attributes
double f_max = 0.
Maximal particle force or torque.
double gamma = 0.
Dampening constant.
double max_displacement = 0.
Maximal particle displacement or rotation.
Detailed Description
Steepest descent algorithm.
Definition at line 27 of file steepest_descent.hpp.
Constructor & Destructor Documentation
SteepestDescent() [1/2]
SteepestDescent::SteepestDescent () default
SteepestDescent() [2/2]
SteepestDescent::SteepestDescent (double f_max, double gamma, double max_displacement)
Definition at line 97 of file steepest_descent.cpp.
References f_max, gamma, and max_displacement.
Member Function Documentation
propagate()
bool SteepestDescent::propagate (CellStructure & cell_structure) const
Run steepest descent algorithm.
Returns
whether the maximum force/torque encountered is below the user limit f_max.
Definition at line 42 of file steepest_descent.cpp.
References comm_cart, f_max, gamma, CellStructure::local_particles(), local_rotate_particle(), max_displacement, Cells::RESORT_LOCAL, CellStructure::set_resort_particles(), Utils::sqr(), and stream.
Member Data Documentation
f_max
double SteepestDescent::f_max = 0.
Maximal particle force or torque.
If the maximal force experienced by particles in the system (in any direction) is inferior to this threshold, minimization stops.
Definition at line 34 of file steepest_descent.hpp.
Referenced by propagate(), and SteepestDescent().
gamma
double SteepestDescent::gamma = 0.
Dampening constant.
Definition at line 36 of file steepest_descent.hpp.
Referenced by propagate(), and SteepestDescent().
max_displacement
double SteepestDescent::max_displacement = 0.
Maximal particle displacement or rotation.
Maximal distance in MD units of length or rotation in radians that a particle can experience during one integration step, in one direction.
Definition at line 43 of file steepest_descent.hpp.
Referenced by propagate(), and SteepestDescent().
The documentation for this struct was generated from the following files:
steepest_descent.hpp
steepest_descent.cpp