ESPResSo: EnergyKernel Struct Reference
EnergyKernel Struct Reference
#include <energy_cabana.hpp>
Public Member Functions
EnergyKernel (BondedInteractionsMap const &bonded_ias_, InteractionsNonBonded const &nonbonded_ias_, Coulomb::Solver const &coulomb_, Coulomb::ShortRangeEnergyKernel::kernel_type const *coulomb_u_kernel_, Dipoles::ShortRangeEnergyKernel::kernel_type const *dipoles_u_kernel_, BoxGeometry const &box_geo_, std::vector< Particle * > const &unique_particles_, Kokkos::View< double **, Kokkos::LayoutRight > const &local_energy_, EnergyBinLayout layout_, CellStructure::AoSoA_pack const &aosoa_, Kokkos::View< int * > mol_id_view_, double system_max_cutoff_)
KOKKOS_INLINE_FUNCTION void operator() (std::size_t i, std::size_t j) const
Public Attributes
BondedInteractionsMap const & bonded_ias
InteractionsNonBonded const & nonbonded_ias
Coulomb::Solver const & coulomb
Coulomb::ShortRangeEnergyKernel::kernel_type const * coulomb_u_kernel
Dipoles::ShortRangeEnergyKernel::kernel_type const * dipoles_u_kernel
BoxGeometry const & box_geo
std::vector< Particle * > const & unique_particles
Kokkos::View< double **, Kokkos::LayoutRight > local_energy
EnergyBinLayout layout
CellStructure::AoSoA_pack const & aosoa
Kokkos::View< int * > mol_id_view
double system_max_cutoff_sq
Detailed Description
Definition at line 79 of file energy_cabana.hpp.
Constructor & Destructor Documentation
EnergyKernel()
EnergyKernel::EnergyKernel (BondedInteractionsMap const & bonded_ias_, InteractionsNonBonded const & nonbonded_ias_, Coulomb::Solver const & coulomb_, Coulomb::ShortRangeEnergyKernel::kernel_type const * coulomb_u_kernel_, Dipoles::ShortRangeEnergyKernel::kernel_type const * dipoles_u_kernel_, BoxGeometry const & box_geo_, std::vector< Particle * > const & unique_particles_, Kokkos::View< double **, Kokkos::LayoutRight > const & local_energy_, EnergyBinLayout layout_, CellStructure::AoSoA_pack const & aosoa_, Kokkos::View< int * > mol_id_view_, double system_max_cutoff_) inline
Definition at line 93 of file energy_cabana.hpp.
Member Function Documentation
operator()()
KOKKOS_INLINE_FUNCTION void EnergyKernel::operator() (std::size_t i, std::size_t j) const inline
Definition at line 112 of file energy_cabana.hpp.
References aosoa, bonded_ias, box_geo, calc_central_radial_energy(), CellStructure::AoSoA_pack::charge, coulomb, EnergyBinLayout::coulomb_idx(), coulomb_u_kernel, CellStructure::AoSoA_pack::dipm, EnergyBinLayout::dipolar_idx(), dipoles_u_kernel, CellStructure::AoSoA_pack::director, do_nonbonded(), gay_berne_active(), gb_pair_energy(), InteractionsNonBonded::get_ia_param(), BoxGeometry::get_mi_vector(), CellStructure::AoSoA_pack::get_vector_at(), CellStructure::AoSoA_pack::has_exclusion(), layout, local_energy, mol_id_view, EnergyBinLayout::nb_inter_idx(), EnergyBinLayout::nb_intra_idx(), nonbonded_ias, CellStructure::AoSoA_pack::position, stream, system_max_cutoff_sq, thole_active(), thole_pair_energy(), CellStructure::AoSoA_pack::type, and unique_particles.
Member Data Documentation
aosoa
CellStructure::AoSoA_pack const& EnergyKernel::aosoa
Definition at line 89 of file energy_cabana.hpp.
Referenced by operator()().
bonded_ias
BondedInteractionsMap const& EnergyKernel::bonded_ias
Definition at line 80 of file energy_cabana.hpp.
Referenced by operator()().
box_geo
BoxGeometry const& EnergyKernel::box_geo
Definition at line 85 of file energy_cabana.hpp.
Referenced by operator()().
coulomb
Coulomb::Solver const& EnergyKernel::coulomb
Definition at line 82 of file energy_cabana.hpp.
Referenced by operator()().
coulomb_u_kernel
Coulomb::ShortRangeEnergyKernel::kernel_type const* EnergyKernel::coulomb_u_kernel
Definition at line 83 of file energy_cabana.hpp.
Referenced by operator()().
dipoles_u_kernel
Dipoles::ShortRangeEnergyKernel::kernel_type const* EnergyKernel::dipoles_u_kernel
Definition at line 84 of file energy_cabana.hpp.
Referenced by operator()().
layout
EnergyBinLayout EnergyKernel::layout
Definition at line 88 of file energy_cabana.hpp.
Referenced by operator()().
local_energy
Kokkos::View<double **, Kokkos::LayoutRight> EnergyKernel::local_energy
Definition at line 87 of file energy_cabana.hpp.
Referenced by operator()().
mol_id_view
Kokkos::View<int *> EnergyKernel::mol_id_view
Definition at line 90 of file energy_cabana.hpp.
Referenced by operator()().
nonbonded_ias
InteractionsNonBonded const& EnergyKernel::nonbonded_ias
Definition at line 81 of file energy_cabana.hpp.
Referenced by operator()().
system_max_cutoff_sq
double EnergyKernel::system_max_cutoff_sq
Definition at line 91 of file energy_cabana.hpp.
Referenced by operator()().
unique_particles
std::vector<Particle *> const& EnergyKernel::unique_particles
Definition at line 86 of file energy_cabana.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
energy_cabana.hpp