ESPResSo: ScriptInterface::walberla::EKFieldSerializer Struct Reference
ScriptInterface::walberla::EKFieldSerializer Struct Reference
#include <EKSpeciesSlice.hpp>
Static Public Member Functions
template<typename T >
static Variant serialize (std::vector< T > const &values)
template<typename T >
static std::vector< T > deserialize (Variant const &variant)
Detailed Description
Definition at line 53 of file EKSpeciesSlice.hpp.
Member Function Documentation
deserialize()
template<typename T > static std::vector< T > ScriptInterface::walberla::EKFieldSerializer::deserialize (Variant const & variant) inline static
Definition at line 76 of file EKSpeciesSlice.hpp.
References ScriptInterface::is_none(), ScriptInterface::is_type(), and stream.
serialize()
template<typename T > static Variant ScriptInterface::walberla::EKFieldSerializer::serialize (std::vector< T > const & values) inline static
Definition at line 55 of file EKSpeciesSlice.hpp.
References ScriptInterface::make_vector_of_variants(), and stream.
The documentation for this struct was generated from the following file:
EKSpeciesSlice.hpp