ESPResSo: AngleCossquareBond Struct Reference
AngleCossquareBond Struct Reference
Parameters for three-body angular potential (cossquare).
#include <angle_cossquare.hpp>
Public Member Functions
double cutoff () const
AngleCossquareBond (double bend, double phi0)
std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > forces (Utils::Vector3d const &vec1, Utils::Vector3d const &vec2) const
Compute the three-body angle interaction force.
double energy (Utils::Vector3d const &vec1, Utils::Vector3d const &vec2) const
Computes the three-body angle interaction energy.
Public Attributes
double bend
bending constant
double phi0
equilibrium angle (default is 180 degrees)
double cos_phi0
cosine of phi0 (internal parameter)
Static Public Attributes
static constexpr int num = 2
Detailed Description
Parameters for three-body angular potential (cossquare).
Definition at line 39 of file angle_cossquare.hpp.
Constructor & Destructor Documentation
AngleCossquareBond()
AngleCossquareBond::AngleCossquareBond (double bend, double phi0) inline
Definition at line 51 of file angle_cossquare.hpp.
References bend, phi0, and stream.
Member Function Documentation
cutoff()
double AngleCossquareBond::cutoff () const inline
Definition at line 47 of file angle_cossquare.hpp.
energy()
double AngleCossquareBond::energy (Utils::Vector3d const & vec1, Utils::Vector3d const & vec2) const inline
Computes the three-body angle interaction energy.
Parameters
[in] vec1 Vector from central particle to left particle.
[in] vec2 Vector from central particle to right particle.
Definition at line 82 of file angle_cossquare.hpp.
References bend, calc_cosine(), cos_phi0, Utils::sqr(), and stream.
forces()
std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > AngleCossquareBond::forces (Utils::Vector3d const & vec1, Utils::Vector3d const & vec2) const inline
Compute the three-body angle interaction force.
Parameters
[in] vec1 Vector from central particle to left particle.
[in] vec2 Vector from central particle to right particle.
Returns
Forces on the second, first and third particles, in that order.
Definition at line 68 of file angle_cossquare.hpp.
References angle_generic_force(), bend, cos_phi0, and stream.
Member Data Documentation
bend
double AngleCossquareBond::bend
bending constant
Definition at line 41 of file angle_cossquare.hpp.
Referenced by AngleCossquareBond(), energy(), and forces().
cos_phi0
double AngleCossquareBond::cos_phi0
cosine of phi0 (internal parameter)
Definition at line 45 of file angle_cossquare.hpp.
Referenced by energy(), and forces().
num
constexpr int AngleCossquareBond::num = 2 static constexpr
Definition at line 49 of file angle_cossquare.hpp.
phi0
double AngleCossquareBond::phi0
equilibrium angle (default is 180 degrees)
Definition at line 43 of file angle_cossquare.hpp.
Referenced by AngleCossquareBond().
The documentation for this struct was generated from the following file:
angle_cossquare.hpp