ESPResSo: Utils::Array< T, N > Struct Template Reference
Utils::Array< T, N > Struct Template Reference
#include <Array.hpp>
Public Types
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using iterator = value_type *
using const_iterator = const value_type *
using pointer = value_type *
using const_pointer = const value_type *
Public Member Functions
constexpr DEVICE_QUALIFIER reference at (size_type i)
constexpr DEVICE_QUALIFIER const_reference at (size_type i) const
constexpr DEVICE_QUALIFIER reference operator[] (size_type i)
constexpr DEVICE_QUALIFIER const_reference operator[] (size_type i) const
constexpr DEVICE_QUALIFIER reference front ()
constexpr DEVICE_QUALIFIER const_reference front () const
constexpr DEVICE_QUALIFIER reference back ()
constexpr DEVICE_QUALIFIER const_reference back () const
constexpr DEVICE_QUALIFIER pointer data () noexcept
constexpr DEVICE_QUALIFIER const_pointer data () const noexcept
constexpr DEVICE_QUALIFIER iterator begin () noexcept
constexpr DEVICE_QUALIFIER const_iterator begin () const noexcept
constexpr DEVICE_QUALIFIER const_iterator cbegin () const noexcept
constexpr DEVICE_QUALIFIER iterator end () noexcept
constexpr DEVICE_QUALIFIER const_iterator end () const noexcept
constexpr DEVICE_QUALIFIER const_iterator cend () const noexcept
constexpr DEVICE_QUALIFIER bool empty () const noexcept
constexpr DEVICE_QUALIFIER size_type size () const noexcept
constexpr DEVICE_QUALIFIER size_type max_size () const noexcept
DEVICE_QUALIFIER void fill (const value_type &value)
Static Public Member Functions
static constexpr DEVICE_QUALIFIER Array< T, N > broadcast (const value_type &value)
static constexpr detail::ArrayFormatter formatter (char const *sep=" ")
Public Attributes
detail::Storage< T, N > m_storage
Friends
std::ostream & operator<< (std::ostream &out, Array const &a)
std::ostream & operator<< (detail::ArrayFormatterStream const &fmt, Array const &a)
Detailed Description
template<typename T, std::size_t N>
struct Utils::Array< T, N >
Definition at line 73 of file Array.hpp.
Member Typedef Documentation
const_iterator
template<typename T , std::size_t N> using Utils::Array< T, N >::const_iterator = const value_type *
Definition at line 80 of file Array.hpp.
const_pointer
template<typename T , std::size_t N> using Utils::Array< T, N >::const_pointer = const value_type *
Definition at line 82 of file Array.hpp.
const_reference
template<typename T , std::size_t N> using Utils::Array< T, N >::const_reference = const value_type &
Definition at line 78 of file Array.hpp.
difference_type
template<typename T , std::size_t N> using Utils::Array< T, N >::difference_type = std::ptrdiff_t
Definition at line 76 of file Array.hpp.
iterator
template<typename T , std::size_t N> using Utils::Array< T, N >::iterator = value_type *
Definition at line 79 of file Array.hpp.
pointer
template<typename T , std::size_t N> using Utils::Array< T, N >::pointer = value_type *
Definition at line 81 of file Array.hpp.
reference
template<typename T , std::size_t N> using Utils::Array< T, N >::reference = value_type &
Definition at line 77 of file Array.hpp.
size_type
template<typename T , std::size_t N> using Utils::Array< T, N >::size_type = std::size_t
Definition at line 75 of file Array.hpp.
value_type
template<typename T , std::size_t N> using Utils::Array< T, N >::value_type = T
Definition at line 74 of file Array.hpp.
Member Function Documentation
at() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER reference Utils::Array< T, N >::at (size_type i) inline constexpr
Definition at line 86 of file Array.hpp.
at() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_reference Utils::Array< T, N >::at (size_type i) const inline constexpr
Definition at line 93 of file Array.hpp.
back() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER reference Utils::Array< T, N >::back () inline constexpr
Definition at line 114 of file Array.hpp.
back() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_reference Utils::Array< T, N >::back () const inline constexpr
Definition at line 116 of file Array.hpp.
begin() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_iterator Utils::Array< T, N >::begin () const inline constexpr noexcept
Definition at line 132 of file Array.hpp.
begin() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER iterator Utils::Array< T, N >::begin () inline constexpr noexcept
Definition at line 128 of file Array.hpp.
Referenced by Utils::Vector< double, 3 >::as_vector(), Utils::Matrix< T, Rows, Cols >::begin(), Utils::Vector< double, 3 >::broadcast(), Shapes::Ellipsoid::calculate_dist(), ScriptInterface::CellSystem::CellSystem::CellSystem(), Utils::Array< T, 4 >::front(), Utils::get_cylindrical_sampling_positions(), Utils::hadamard_division(), Utils::hadamard_product(), p3m_interpolation_cache::load(), Utils::Vector< double, 3 >::operator Vector< U, N >(), Utils::operator/(), ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::pack_vector(), Utils::sqrt(), Utils::Vector< double, 3 >::swap(), and Utils::Vector< double, 3 >::Vector().
broadcast()
template<typename T , std::size_t N> static constexpr DEVICE_QUALIFIER Array<T, N> Utils::Array< T, N >::broadcast (const value_type & value) inline static constexpr
Definition at line 165 of file Array.hpp.
cbegin()
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_iterator Utils::Array< T, N >::cbegin () const inline constexpr noexcept
Definition at line 136 of file Array.hpp.
Referenced by Utils::Array< T, 4 >::front(), Utils::hadamard_division(), Utils::hadamard_product(), and Utils::product().
cend()
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_iterator Utils::Array< T, N >::cend () const inline constexpr noexcept
Definition at line 148 of file Array.hpp.
Referenced by Utils::Array< T, 4 >::back(), Utils::hadamard_division(), Utils::hadamard_product(), and Utils::product().
data() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_pointer Utils::Array< T, N >::data () const inline constexpr noexcept
Definition at line 124 of file Array.hpp.
data() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER pointer Utils::Array< T, N >::data () inline constexpr noexcept
Definition at line 120 of file Array.hpp.
Referenced by Utils::Mpi::cart_create(), Utils::Matrix< T, Rows, Cols >::data(), fft_init(), p3m_send_mesh::gather_grid(), CoulombP3MGPU::init(), p3mgpu_k_space_error(), and p3m_send_mesh::spread_grid().
empty()
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER bool Utils::Array< T, N >::empty () const inline constexpr noexcept
Definition at line 152 of file Array.hpp.
end() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_iterator Utils::Array< T, N >::end () const inline constexpr noexcept
Definition at line 144 of file Array.hpp.
end() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER iterator Utils::Array< T, N >::end () inline constexpr noexcept
Definition at line 140 of file Array.hpp.
Referenced by Utils::Vector< double, 3 >::as_vector(), Utils::Array< T, 4 >::back(), Utils::Vector< double, 3 >::broadcast(), Shapes::Ellipsoid::calculate_dist(), Utils::Matrix< T, Rows, Cols >::end(), Utils::Vector< double, 3 >::operator Vector< U, N >(), ScriptInterface::CellSystem::anonymous_namespace{CellSystem.hpp}::pack_vector(), and Utils::Vector< double, 3 >::swap().
fill()
template<typename T , std::size_t N> DEVICE_QUALIFIER void Utils::Array< T, N >::fill (const value_type & value) inline
Definition at line 158 of file Array.hpp.
formatter()
template<typename T , std::size_t N> static constexpr detail::ArrayFormatter Utils::Array< T, N >::formatter (char const * sep = " ") inline static constexpr
Definition at line 173 of file Array.hpp.
front() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER reference Utils::Array< T, N >::front () inline constexpr
Definition at line 110 of file Array.hpp.
front() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_reference Utils::Array< T, N >::front () const inline constexpr
Definition at line 112 of file Array.hpp.
max_size()
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER size_type Utils::Array< T, N >::max_size () const inline constexpr noexcept
Definition at line 156 of file Array.hpp.
operator[]() [1/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER reference Utils::Array< T, N >::operator[] (size_type i) inline constexpr
Definition at line 100 of file Array.hpp.
operator[]() [2/2]
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER const_reference Utils::Array< T, N >::operator[] (size_type i) const inline constexpr
Definition at line 105 of file Array.hpp.
size()
template<typename T , std::size_t N> constexpr DEVICE_QUALIFIER size_type Utils::Array< T, N >::size () const inline constexpr noexcept
Definition at line 154 of file Array.hpp.
Referenced by Utils::Array< T, 4 >::empty(), and Utils::Array< T, 4 >::fill().
Friends And Related Function Documentation
operator<< [1/2]
template<typename T , std::size_t N> std::ostream& operator<< (detail::ArrayFormatterStream const & fmt, Array< T, N > const & a) friend
Definition at line 199 of file Array.hpp.
operator<< [2/2]
template<typename T , std::size_t N> std::ostream& operator<< (std::ostream & out, Array< T, N > const & a) friend
Definition at line 195 of file Array.hpp.
Member Data Documentation
m_storage
template<typename T , std::size_t N> detail::Storage<T, N> Utils::Array< T, N >::m_storage
Definition at line 84 of file Array.hpp.
Referenced by Utils::Array< T, 4 >::at(), Utils::Array< T, 4 >::begin(), Utils::Array< T, 4 >::cbegin(), Utils::Array< T, 4 >::cend(), Utils::Array< T, 4 >::data(), Utils::Array< T, 4 >::end(), Utils::Array< T, 4 >::fill(), and Utils::Array< T, 4 >::operator[]().
The documentation for this struct was generated from the following file:
Array.hpp