ESPResSo: PressureBinLayout Struct Reference
PressureBinLayout Struct Reference
#include <pressure_cabana.hpp>
Public Member Functions
PressureBinLayout (std::size_t n_bonded_, std::size_t n_types_)
KOKKOS_INLINE_FUNCTION std::size_t tensor_offset (std::size_t bin, std::size_t k) const
KOKKOS_INLINE_FUNCTION std::size_t nb_inter_idx (int t1, int t2) const
KOKKOS_INLINE_FUNCTION std::size_t nb_intra_idx (int t1, int t2) const
KOKKOS_INLINE_FUNCTION std::size_t coulomb_idx () const
KOKKOS_INLINE_FUNCTION std::size_t dipolar_idx () const
KOKKOS_INLINE_FUNCTION std::size_t dpd_idx () const
KOKKOS_INLINE_FUNCTION std::size_t bonded_idx (int b) const
Public Attributes
std::size_t n_bonded
std::size_t n_types
std::size_t off_bonded = 0
std::size_t off_nb_inter
std::size_t off_nb_intra
std::size_t off_coulomb
std::size_t off_dipolar
std::size_t off_dpd
std::size_t total
Detailed Description
Definition at line 51 of file pressure_cabana.hpp.
Constructor & Destructor Documentation
PressureBinLayout()
PressureBinLayout::PressureBinLayout (std::size_t n_bonded_, std::size_t n_types_) inline
Definition at line 62 of file pressure_cabana.hpp.
References n_bonded, n_types, off_bonded, off_coulomb, off_dipolar, off_dpd, off_nb_inter, off_nb_intra, stream, and total.
Member Function Documentation
bonded_idx()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::bonded_idx (int b) const inline
Definition at line 93 of file pressure_cabana.hpp.
References off_bonded.
Referenced by reduce_cabana_pressure().
coulomb_idx()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::coulomb_idx () const inline
Definition at line 90 of file pressure_cabana.hpp.
References off_coulomb.
Referenced by PressureKernel::operator()(), and reduce_cabana_pressure().
dipolar_idx()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::dipolar_idx () const inline
Definition at line 91 of file pressure_cabana.hpp.
References off_dipolar.
Referenced by reduce_cabana_pressure().
dpd_idx()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::dpd_idx () const inline
Definition at line 92 of file pressure_cabana.hpp.
References off_dpd.
Referenced by PressureKernel::operator()(), and reduce_cabana_pressure().
nb_inter_idx()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::nb_inter_idx (int t1, int t2) const inline
Definition at line 79 of file pressure_cabana.hpp.
References Utils::lower_triangular(), off_nb_inter, and stream.
Referenced by PressureKernel::operator()(), and reduce_cabana_pressure().
nb_intra_idx()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::nb_intra_idx (int t1, int t2) const inline
Definition at line 85 of file pressure_cabana.hpp.
References Utils::lower_triangular(), off_nb_intra, and stream.
Referenced by PressureKernel::operator()(), and reduce_cabana_pressure().
tensor_offset()
KOKKOS_INLINE_FUNCTION std::size_t PressureBinLayout::tensor_offset (std::size_t bin, std::size_t k) const inline
Definition at line 74 of file pressure_cabana.hpp.
References stream.
Referenced by PressureKernel::operator()(), and reduce_cabana_pressure().
Member Data Documentation
n_bonded
std::size_t PressureBinLayout::n_bonded
Definition at line 52 of file pressure_cabana.hpp.
Referenced by PressureBinLayout(), and reduce_cabana_pressure().
n_types
std::size_t PressureBinLayout::n_types
Definition at line 53 of file pressure_cabana.hpp.
Referenced by PressureBinLayout().
off_bonded
std::size_t PressureBinLayout::off_bonded = 0
Definition at line 54 of file pressure_cabana.hpp.
Referenced by bonded_idx(), and PressureBinLayout().
off_coulomb
std::size_t PressureBinLayout::off_coulomb
Definition at line 57 of file pressure_cabana.hpp.
Referenced by coulomb_idx(), and PressureBinLayout().
off_dipolar
std::size_t PressureBinLayout::off_dipolar
Definition at line 58 of file pressure_cabana.hpp.
Referenced by dipolar_idx(), and PressureBinLayout().
off_dpd
std::size_t PressureBinLayout::off_dpd
Definition at line 59 of file pressure_cabana.hpp.
Referenced by dpd_idx(), and PressureBinLayout().
off_nb_inter
std::size_t PressureBinLayout::off_nb_inter
Definition at line 55 of file pressure_cabana.hpp.
Referenced by nb_inter_idx(), and PressureBinLayout().
off_nb_intra
std::size_t PressureBinLayout::off_nb_intra
Definition at line 56 of file pressure_cabana.hpp.
Referenced by nb_intra_idx(), and PressureBinLayout().
total
std::size_t PressureBinLayout::total
Definition at line 60 of file pressure_cabana.hpp.
Referenced by PressureBinLayout().
The documentation for this struct was generated from the following file:
pressure_cabana.hpp