ESPResSo: TabulatedPotential Struct Reference
TabulatedPotential Struct Reference
Evaluate forces and energies using a custom potential profile.
#include <TabulatedPotential.hpp>
Public Member Functions
double force (double x) const
Evaluate the force at position x.
double energy (double x) const
Evaluate the energy at position x.
double cutoff () const
Public Attributes
double minval = -1.0
Position on the x-axis of the first tabulated value.
double maxval = -1.0
Position on the x-axis of the last tabulated value.
double invstepsize = 0.0
Distance on the x-axis between tabulated values.
std::vector< double > force_tab
Tabulated forces.
std::vector< double > energy_tab
Tabulated energies.
Detailed Description
Evaluate forces and energies using a custom potential profile.
Forces and energies are evaluated by linear interpolation. The curves force_tab and energy_tab must be sampled uniformly between minval and maxval.
Definition at line 37 of file TabulatedPotential.hpp.
Member Function Documentation
cutoff()
double TabulatedPotential::cutoff () const inline
Definition at line 69 of file TabulatedPotential.hpp.
References maxval.
Referenced by recalc_maximal_cutoff(), tabulated_pair_energy(), and tabulated_pair_force_factor().
energy()
double TabulatedPotential::energy (double x) const inline
Evaluate the energy at position x.
Parameters
x Bond length/angle
Returns
Interpolated energy.
Definition at line 63 of file TabulatedPotential.hpp.
References energy_tab, invstepsize, Utils::linear_interpolation(), maxval, and minval.
Referenced by tabulated_pair_energy().
force()
double TabulatedPotential::force (double x) const inline
Evaluate the force at position x.
Parameters
x Bond length/angle
Returns
Interpolated force.
Definition at line 53 of file TabulatedPotential.hpp.
References force_tab, invstepsize, Utils::linear_interpolation(), maxval, and minval.
Referenced by tabulated_pair_force_factor().
Member Data Documentation
energy_tab
std::vector<double> TabulatedPotential::energy_tab
Tabulated energies.
Definition at line 47 of file TabulatedPotential.hpp.
Referenced by energy().
force_tab
std::vector<double> TabulatedPotential::force_tab
Tabulated forces.
Definition at line 45 of file TabulatedPotential.hpp.
Referenced by force().
invstepsize
double TabulatedPotential::invstepsize = 0.0
Distance on the x-axis between tabulated values.
Definition at line 43 of file TabulatedPotential.hpp.
Referenced by energy(), and force().
maxval
double TabulatedPotential::maxval = -1.0
Position on the x-axis of the last tabulated value.
Definition at line 41 of file TabulatedPotential.hpp.
Referenced by cutoff(), energy(), and force().
minval
double TabulatedPotential::minval = -1.0
Position on the x-axis of the first tabulated value.
Definition at line 39 of file TabulatedPotential.hpp.
Referenced by energy(), and force().
The documentation for this struct was generated from the following file:
TabulatedPotential.hpp