ESPResSo: ScriptInterface::walberla::EKReactionSliceAdapter Struct Reference
ScriptInterface::walberla::EKReactionSliceAdapter Struct Reference
Adapter that exposes EKReactionBaseIndexed with the interface expected by LatticeSlice::gather_3d / scatter_3d.
#include <EKIndexedReactionSlice.hpp>
Public Member Functions
::LatticeWalberla const & get_lattice () const noexcept
std::vector< int > get_slice_is_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner) const
void set_slice_is_boundary (Utils::Vector3i const &lower_corner, Utils::Vector3i const &upper_corner, std::vector< int > const &values)
void ghost_communication ()
Public Attributes
::walberla::EKReactionBaseIndexed * m_impl
Detailed Description
Adapter that exposes EKReactionBaseIndexed with the interface expected by LatticeSlice::gather_3d / scatter_3d.
LatticeSlice requires the lattice model to provide get_lattice() returning a LatticeWalberla const &, but EKReactionBase::get_lattice() returns a shared_ptr. This adapter bridges that mismatch.
Definition at line 54 of file EKIndexedReactionSlice.hpp.
Member Function Documentation
get_lattice()
::LatticeWalberla const & ScriptInterface::walberla::EKReactionSliceAdapter::get_lattice () const inline noexcept
Definition at line 57 of file EKIndexedReactionSlice.hpp.
References walberla::EKReactionBase::get_lattice(), and m_impl.
get_slice_is_boundary()
std::vector< int > ScriptInterface::walberla::EKReactionSliceAdapter::get_slice_is_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner) const inline
Definition at line 62 of file EKIndexedReactionSlice.hpp.
References walberla::EKReactionBaseIndexed::get_slice_is_boundary(), m_impl, and stream.
Referenced by ScriptInterface::walberla::EKIndexedReactionSlice::do_call_method().
ghost_communication()
void ScriptInterface::walberla::EKReactionSliceAdapter::ghost_communication () inline
Definition at line 73 of file EKIndexedReactionSlice.hpp.
References walberla::EKReactionBaseIndexed::ghost_communication(), and m_impl.
set_slice_is_boundary()
void ScriptInterface::walberla::EKReactionSliceAdapter::set_slice_is_boundary (Utils::Vector3i const & lower_corner, Utils::Vector3i const & upper_corner, std::vector< int > const & values) inline
Definition at line 67 of file EKIndexedReactionSlice.hpp.
References m_impl, walberla::EKReactionBaseIndexed::set_slice_is_boundary(), and stream.
Referenced by ScriptInterface::walberla::EKIndexedReactionSlice::do_call_method().
Member Data Documentation
m_impl
::walberla::EKReactionBaseIndexed* ScriptInterface::walberla::EKReactionSliceAdapter::m_impl
Definition at line 55 of file EKIndexedReactionSlice.hpp.
Referenced by get_lattice(), get_slice_is_boundary(), ghost_communication(), and set_slice_is_boundary().
The documentation for this struct was generated from the following file:
EKIndexedReactionSlice.hpp