ESPResSo: DipolarP3MHeffte< FloatType, Architecture, FFTConfig > Struct Template Reference
DipolarP3MHeffte< FloatType, Architecture, FFTConfig > Struct Template Reference
#include <dp3m_heffte.hpp>
Public Types
using DipolarP3MStateClass = DipolarP3MState< FloatType, FFTConfig >
Public Member Functions
~DipolarP3MHeffte () override=default
DipolarP3MHeffte (std::unique_ptr< DipolarP3MStateClass > &&dp3m_state, TuningParameters tuning_params, double prefactor)
void init () override
void tune () override
void count_magnetic_particles () override
bool is_tuned () const noexcept override
bool is_gpu () const noexcept override
bool is_double_precision () const noexcept override
void on_activation () override
double long_range_energy () override
void add_long_range_forces () override
void dipole_assign () override
Public Member Functions inherited from DipolarP3M
DipolarP3M (P3MParameters const &dp3m_params)
virtual ~DipolarP3M ()=default
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
void sanity_checks () const
ParticleForce pair_force (double d1d2, Utils::Vector3d const &dip1, Utils::Vector3d const &dip2, Utils::Vector3d const &d, double dist, double dist2) const
Calculate real-space contribution of p3m dipolar pair forces and torques.
double pair_energy (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist, double dist2) const
Calculate real-space contribution of dipolar pair energy.
Public Member Functions inherited from Dipoles::Actor< DipolarP3M >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
DipolarP3MStateClass & dp3m
Dipolar P3M parameters.
Public Attributes inherited from DipolarP3M
P3MParameters const & dp3m_params
Public Attributes inherited from Dipoles::Actor< DipolarP3M >
double prefactor
Magnetostatics prefactor.
Protected Member Functions
double long_range_kernel (bool force_flag, bool energy_flag)
Compute the k-space part of forces and energies.
double calc_average_self_energy_k_space () const override
void calc_energy_correction () override
void calc_influence_function_force () override
void calc_influence_function_energy () override
double calc_surface_term (bool force_flag, bool energy_flag) override
void init_cpu_kernels ()
void scaleby_box_l () override
void npt_add_virial_contribution (double energy) const override
Protected Member Functions inherited from DipolarP3M
void sanity_checks_boxl () const
Checks for correctness of the k-space cutoff.
void sanity_checks_node_grid () const
void sanity_checks_periodicity () const
void sanity_checks_cell_structure () const
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Additional Inherited Members
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
template<typename FloatType, Arch Architecture, class FFTConfig>
struct DipolarP3MHeffte< FloatType, Architecture, FFTConfig >
Definition at line 158 of file dp3m_heffte.hpp.
Member Typedef Documentation
DipolarP3MStateClass
template<typename FloatType , Arch Architecture, class FFTConfig > using DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::DipolarP3MStateClass = DipolarP3MState<FloatType, FFTConfig>
Definition at line 165 of file dp3m_heffte.hpp.
Constructor & Destructor Documentation
~DipolarP3MHeffte()
template<typename FloatType , Arch Architecture, class FFTConfig > DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::~DipolarP3MHeffte () override default
DipolarP3MHeffte()
template<typename FloatType , Arch Architecture, class FFTConfig > DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::DipolarP3MHeffte (std::unique_ptr< DipolarP3MStateClass > && dp3m_state, TuningParameters tuning_params, double prefactor) inline
Definition at line 180 of file dp3m_heffte.hpp.
References Utils::Vector< T, N >::broadcast(), DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::dp3m, DipolarP3MState< FloatType, FFTConfig >::init_labels(), P3MParameters::mesh, P3MStateCommon< FloatType >::params, Dipoles::Actor< DipolarP3M >::prefactor, Dipoles::Actor< DipolarP3M >::set_prefactor(), stream, TuningParameters::timings, and P3MParameters::tuning.
Member Function Documentation
add_long_range_forces()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces () inline override virtual
Implements DipolarP3M.
Definition at line 225 of file dp3m_heffte.hpp.
References CPU, DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel(), and stream.
calc_average_self_energy_k_space()
template<typename FloatType , Arch Architecture, class FFTConfig > double DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::calc_average_self_energy_k_space () const override protected virtual
Implements DipolarP3M.
Definition at line 134 of file dp3m_heffte.impl.hpp.
References System::System::box_geo, comm_cart, and stream.
calc_energy_correction()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::calc_energy_correction () override protected virtual
Implements DipolarP3M.
Definition at line 1403 of file dp3m_heffte.impl.hpp.
References P3MParameters::alpha_L, System::System::box_geo, DipolarP3MState< FloatType, FFTConfig >::energy_correction, P3MStateCommon< FloatType >::params, stream, and DipolarP3MState< FloatType, FFTConfig >::sum_mu2.
calc_influence_function_energy()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::calc_influence_function_energy () override protected virtual
Implements DipolarP3M.
Definition at line 1001 of file dp3m_heffte.impl.hpp.
References System::System::box_geo, grid_influence_function_dipolar(), P3M_BRILLOUIN, and stream.
calc_influence_function_force()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::calc_influence_function_force () override protected virtual
Implements DipolarP3M.
Definition at line 976 of file dp3m_heffte.impl.hpp.
References System::System::box_geo, grid_influence_function_dipolar(), P3M_BRILLOUIN, and stream.
calc_surface_term()
template<typename FloatType , Arch Architecture, class FFTConfig > double DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::calc_surface_term (bool force_flag, bool energy_flag) override protected virtual
Implements DipolarP3M.
Definition at line 905 of file dp3m_heffte.impl.hpp.
References comm_cart, ParticleRange::size(), and stream.
count_magnetic_particles()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::count_magnetic_particles () override virtual
Implements DipolarP3M.
Definition at line 102 of file dp3m_heffte.impl.hpp.
References System::System::cell_structure, comm_cart, and stream.
dipole_assign()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::dipole_assign () override virtual
Implements DipolarP3M.
Definition at line 256 of file dp3m_heffte.impl.hpp.
References System::System::cell_structure.
init()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::init () inline override virtual
Implements DipolarP3M.
Definition at line 202 of file dp3m_heffte.hpp.
References CPU, DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), and stream.
init_cpu_kernels()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels () protected
Definition at line 147 of file dp3m_heffte.impl.hpp.
References Utils::Vector< T, N >::broadcast(), comm_cart, communicator, count_magnetic_particles(), Communicator::node_grid, p3m_max_cao, p3m_min_cao, and stream.
Referenced by DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::init().
is_double_precision()
template<typename FloatType , Arch Architecture, class FFTConfig > bool DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::is_double_precision () const inline override virtual noexcept
Implements DipolarP3M.
Definition at line 214 of file dp3m_heffte.hpp.
is_gpu()
template<typename FloatType , Arch Architecture, class FFTConfig > bool DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::is_gpu () const inline override virtual noexcept
Implements DipolarP3M.
Definition at line 211 of file dp3m_heffte.hpp.
References CPU, and stream.
is_tuned()
template<typename FloatType , Arch Architecture, class FFTConfig > bool DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::is_tuned () const inline override virtual noexcept
Implements DipolarP3M.
Definition at line 210 of file dp3m_heffte.hpp.
long_range_energy()
template<typename FloatType , Arch Architecture, class FFTConfig > double DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_energy () inline override virtual
Implements DipolarP3M.
Definition at line 223 of file dp3m_heffte.hpp.
References DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel().
long_range_kernel()
template<typename FloatType , Arch Architecture, class FFTConfig > double DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel (bool force_flag, bool energy_flag) protected
Compute the k-space part of forces and energies.
Definition at line 398 of file dp3m_heffte.impl.hpp.
References Utils::Vector< T, N >::broadcast(), comm_cart, extract_block(), for_each_3d(), Utils::integral_parameter(), p3m_max_cao, p3m_min_cao, pad_with_zeros_discard_imag(), Utils::product(), Utils::ROW_MAJOR, Utils::sqr(), stream, and this_node.
Referenced by DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces(), and DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_energy().
npt_add_virial_contribution()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::npt_add_virial_contribution (double energy) const override protected virtual
Implements DipolarP3M.
Definition at line 1415 of file dp3m_heffte.impl.hpp.
References System::System::npt_add_virial_contribution().
on_activation()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation () inline override virtual
Implements DipolarP3M.
Definition at line 218 of file dp3m_heffte.hpp.
References DipolarP3M::sanity_checks(), and DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::tune().
scaleby_box_l()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::scaleby_box_l () override protected virtual
Implements DipolarP3M.
Definition at line 1384 of file dp3m_heffte.impl.hpp.
References P3MParameters::alpha, P3MParameters::alpha_L, System::System::box_geo, comm_cart, DipolarP3MState< FloatType, FFTConfig >::energy_correction, DipolarP3MState< FloatType, FFTConfig >::halo_comm, DipolarP3MState< FloatType, FFTConfig >::heffte, P3MStateCommon< FloatType >::local_mesh, P3MStateCommon< FloatType >::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, P3MParameters::recalc_a_ai_cao_cut(), P3MLocalMesh::recalc_ld_pos(), and DipolarP3MState< FloatType, FFTConfig >::world_size.
tune()
template<typename FloatType , Arch Architecture, class FFTConfig > void DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::tune () override virtual
Implements DipolarP3M.
Definition at line 1148 of file dp3m_heffte.impl.hpp.
References P3MParameters::alpha, P3MParameters::alpha_L, count_magnetic_particles(), P3MStateCommon< FloatType >::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, stream, DipolarP3MState< FloatType, FFTConfig >::sum_dip_part, and P3MParameters::tuning.
Referenced by DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation().
Member Data Documentation
dp3m
template<typename FloatType , Arch Architecture, class FFTConfig > DipolarP3MStateClass& DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::dp3m
Dipolar P3M parameters.
Definition at line 167 of file dp3m_heffte.hpp.
Referenced by DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::DipolarP3MHeffte().
The documentation for this struct was generated from the following files:
dp3m_heffte.hpp
dp3m_heffte.impl.hpp