ESPResSo: CoulombP3MHeffte< FloatType, Architecture, FFTConfig > Struct Template Reference
CoulombP3MHeffte< FloatType, Architecture, FFTConfig > Struct Template Reference
#include <p3m_heffte.hpp>
Public Types
using CoulombP3MStateClass = CoulombP3MState< FloatType, FFTConfig >
Public Member Functions
~CoulombP3MHeffte () override=default
CoulombP3MHeffte (std::unique_ptr< CoulombP3MStateClass > &&p3m_state, TuningParameters tuning_params, double prefactor)
void init () override
void tune () override
void count_charged_particles () override
void count_charged_particles_elc (std::size_t n, double sum_q2, double square_sum_q) override
void adapt_epsilon_elc () override
bool is_tuned () const noexcept override
bool is_gpu () const noexcept override
bool is_double_precision () const noexcept override
void on_activation () override
double long_range_energy () override
void add_long_range_forces () override
Utils::Vector9d long_range_pressure () override
void charge_assign () override
void assign_charge (double q, Utils::Vector3d const &real_pos, bool skip_cache) override
void prepare_fft_mesh (bool reset_weights) override
Public Member Functions inherited from CoulombP3M
CoulombP3M (P3MParameters const &p3m_params)
virtual ~CoulombP3M ()=default
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
void sanity_checks () const
Utils::Vector3d pair_force (double q1q2, Utils::Vector3d const &d, double dist) const
Calculate real-space contribution of p3m Coulomb pair forces.
double pair_energy (double q1q2, double dist) const
Calculate real-space contribution of Coulomb pair energy.
Public Member Functions inherited from Coulomb::Actor< CoulombP3M >
void set_prefactor (double new_prefactor)
void sanity_checks_charge_neutrality () const
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
CoulombP3MStateClass & p3m
Coulomb P3M parameters.
Public Attributes inherited from CoulombP3M
P3MParameters const & p3m_params
Public Attributes inherited from Coulomb::Actor< CoulombP3M >
double prefactor
Electrostatics prefactor.
double charge_neutrality_tolerance
Relative tolerance for the charge excess during neutrality checks.
Protected Member Functions
double long_range_kernel (bool force_flag, bool energy_flag)
Compute the k-space part of forces and energies.
void calc_influence_function_force () override
Calculate the optimal influence function of [23].
void calc_influence_function_energy () override
Calculate the influence function optimized for the energy and the self energy correction.
void scaleby_box_l () override
void init_cpu_kernels ()
void init_gpu_kernels ()
void add_long_range_forces_gpu ()
void request_gpu () const
Protected Member Functions inherited from CoulombP3M
void sanity_checks_boxl () const
Checks for correctness of the k-space cutoff.
void sanity_checks_periodicity () const
void sanity_checks_cell_structure () const
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes
std::shared_ptr< P3MGpuParams > m_gpu_data = nullptr
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Additional Inherited Members
Static Public Attributes inherited from Coulomb::Actor< CoulombP3M >
static auto constexpr charge_neutrality_tolerance_default
Detailed Description
template<typename FloatType, Arch Architecture, class FFTConfig>
struct CoulombP3MHeffte< FloatType, Architecture, FFTConfig >
Definition at line 106 of file p3m_heffte.hpp.
Member Typedef Documentation
CoulombP3MStateClass
template<typename FloatType , Arch Architecture, class FFTConfig > using CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::CoulombP3MStateClass = CoulombP3MState<FloatType, FFTConfig>
Definition at line 109 of file p3m_heffte.hpp.
Constructor & Destructor Documentation
~CoulombP3MHeffte()
template<typename FloatType , Arch Architecture, class FFTConfig > CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::~CoulombP3MHeffte () override default
CoulombP3MHeffte()
template<typename FloatType , Arch Architecture, class FFTConfig > CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::CoulombP3MHeffte (std::unique_ptr< CoulombP3MStateClass > && p3m_state, TuningParameters tuning_params, double prefactor) inline
Definition at line 131 of file p3m_heffte.hpp.
References CoulombP3MState< FloatType, FFTConfig >::init_labels(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::p3m, P3MStateCommon< FloatType >::params, Coulomb::Actor< CoulombP3M >::prefactor, Coulomb::Actor< CoulombP3M >::set_prefactor(), stream, TuningParameters::timings, and P3MParameters::tuning.
Member Function Documentation
adapt_epsilon_elc()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::adapt_epsilon_elc () inline override virtual
Implements CoulombP3M.
Definition at line 168 of file p3m_heffte.hpp.
References P3MParameters::epsilon, CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::p3m, P3M_EPSILON_METALLIC, and P3MStateCommon< FloatType >::params.
add_long_range_forces()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces () inline override virtual
Implements CoulombP3M.
Definition at line 199 of file p3m_heffte.hpp.
References CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces_gpu(), CPU, CUDA, CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel(), and stream.
add_long_range_forces_gpu()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces_gpu () protected
Definition at line 1177 of file p3m_heffte.impl.hpp.
References CUDA, System::System::gpu, System::System::has_npt_enabled(), System::System::npt_add_virial_contribution(), p3m_gpu_add_farfield_force(), stream, and this_node.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces().
assign_charge()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::assign_charge (double q, Utils::Vector3d const & real_pos, bool skip_cache) override virtual
Implements CoulombP3M.
Definition at line 441 of file p3m_heffte.impl.hpp.
References stream.
calc_influence_function_energy()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::calc_influence_function_energy () override protected virtual
Calculate the influence function optimized for the energy and the self energy correction.
Implements CoulombP3M.
Definition at line 181 of file p3m_heffte.impl.hpp.
References System::System::box_geo, grid_influence_function(), P3M_BRILLOUIN, and stream.
calc_influence_function_force()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::calc_influence_function_force () override protected virtual
Calculate the optimal influence function of [23].
(optimised for force calculations)
Each node calculates only the values for its domain in k-space.
See also: [23] eq. 8-22 (p. 275). Note the somewhat different convention for the prefactors, which is described in [11] [12].
Implements CoulombP3M.
Definition at line 164 of file p3m_heffte.impl.hpp.
References System::System::box_geo, grid_influence_function(), P3M_BRILLOUIN, and stream.
charge_assign()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::charge_assign () override virtual
Implements CoulombP3M.
Definition at line 423 of file p3m_heffte.impl.hpp.
References ParticlePropertyRange::charge_range(), ParticlePropertyRange::pos_range(), and stream.
count_charged_particles()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::count_charged_particles () override virtual
Implements CoulombP3M.
Definition at line 124 of file p3m_heffte.impl.hpp.
References comm_cart, reduce_over_local_particles(), Utils::sqr(), and stream.
count_charged_particles_elc()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::count_charged_particles_elc (std::size_t n, double sum_q2, double square_sum_q) inline override virtual
Implements CoulombP3M.
Definition at line 162 of file p3m_heffte.hpp.
References CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::p3m, CoulombP3MState< FloatType, FFTConfig >::square_sum_q, CoulombP3MState< FloatType, FFTConfig >::sum_q2, and CoulombP3MState< FloatType, FFTConfig >::sum_qpart.
init()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init () inline override virtual
Implements CoulombP3M.
Definition at line 150 of file p3m_heffte.hpp.
References CPU, CUDA, CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_gpu_kernels(), and stream.
init_cpu_kernels()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels () protected
Definition at line 298 of file p3m_heffte.impl.hpp.
References Utils::Vector< T, N >::broadcast(), comm_cart, communicator, Communicator::node_grid, p3m_max_cao, p3m_min_cao, Utils::product(), and stream.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init(), and CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation().
init_gpu_kernels()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_gpu_kernels () protected
Definition at line 1198 of file p3m_heffte.impl.hpp.
References P3MParameters::alpha, P3MParameters::cao, CUDA, P3MParameters::mesh, p3m_gpu_init(), P3MStateCommon< FloatType >::params, and stream.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init().
is_double_precision()
template<typename FloatType , Arch Architecture, class FFTConfig > bool CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::is_double_precision () const inline override virtual noexcept
Implements CoulombP3M.
Definition at line 176 of file p3m_heffte.hpp.
is_gpu()
template<typename FloatType , Arch Architecture, class FFTConfig > bool CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::is_gpu () const inline override virtual noexcept
Implements CoulombP3M.
Definition at line 173 of file p3m_heffte.hpp.
References CPU, and stream.
is_tuned()
template<typename FloatType , Arch Architecture, class FFTConfig > bool CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::is_tuned () const inline override virtual noexcept
Implements CoulombP3M.
Definition at line 172 of file p3m_heffte.hpp.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation().
long_range_energy()
template<typename FloatType , Arch Architecture, class FFTConfig > double CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_energy () inline override virtual
Implements CoulombP3M.
Definition at line 197 of file p3m_heffte.hpp.
References CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel().
long_range_kernel()
template<typename FloatType , Arch Architecture, class FFTConfig > double CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_kernel (bool force_flag, bool energy_flag) protected
Compute the k-space part of forces and energies.
Definition at line 690 of file p3m_heffte.impl.hpp.
References Utils::Vector< T, N >::broadcast(), calc_dipole_moment(), charge_assign(), ParticlePropertyRange::charge_range(), comm_cart, ParticlePropertyRange::force_range(), kokkos_parallel_range_for(), System::System::npt_add_virial_contribution(), P3M_EPSILON_METALLIC, Utils::sqr(), stream, this_node, and ParticlePropertyRange::unfolded_pos_range().
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::add_long_range_forces(), and CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_energy().
long_range_pressure()
template<typename FloatType , Arch Architecture, class FFTConfig > Utils::Vector9d CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::long_range_pressure () override virtual
Calculate the long range electrostatics part of the pressure tensor. This is part \(\Pi_{\textrm{dir}, \alpha, \beta}\) eq. (2.6) in [18]. The part \(\Pi_{\textrm{corr}, \alpha, \beta}\) eq. (2.8) is not present here since M is the empty set in our simulations.
Implements CoulombP3M.
Definition at line 621 of file p3m_heffte.impl.hpp.
References System::System::box_geo, Utils::Vector< T, N >::broadcast(), charge_assign(), Utils::sqr(), and stream.
on_activation()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation () inline override virtual
Implements CoulombP3M.
Definition at line 180 of file p3m_heffte.hpp.
References CUDA, CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::is_tuned(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::request_gpu(), CoulombP3M::sanity_checks(), stream, and CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::tune().
prepare_fft_mesh()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::prepare_fft_mesh (bool reset_weights) inline override virtual
Implements CoulombP3M.
Definition at line 215 of file p3m_heffte.hpp.
References P3MParameters::cao, CoulombP3MState< FloatType, FFTConfig >::inter_weights, P3MStateCommon< FloatType >::local_mesh, CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::p3m, P3MStateCommon< FloatType >::params, p3m_interpolation_cache::reset(), CoulombP3MState< FloatType, FFTConfig >::rs_charge_density, CoulombP3MState< FloatType, FFTConfig >::rs_charge_density_kokkos, P3MLocalMesh::size, and stream.
request_gpu()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::request_gpu () const protected
Definition at line 1211 of file p3m_heffte.impl.hpp.
References CUDA, GpuParticleData::prop::force, System::System::gpu, GpuParticleData::prop::pos, GpuParticleData::prop::q, and stream.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation().
scaleby_box_l()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::scaleby_box_l () override protected virtual
Implements CoulombP3M.
Definition at line 1162 of file p3m_heffte.impl.hpp.
References P3MParameters::alpha, P3MParameters::alpha_L, System::System::box_geo, comm_cart, CoulombP3MState< FloatType, FFTConfig >::halo_comm, P3MStateCommon< FloatType >::local_mesh, P3MStateCommon< FloatType >::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, P3MParameters::recalc_a_ai_cao_cut(), and P3MLocalMesh::recalc_ld_pos().
tune()
template<typename FloatType , Arch Architecture, class FFTConfig > void CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::tune () override virtual
Implements CoulombP3M.
Definition at line 1072 of file p3m_heffte.impl.hpp.
References P3MParameters::alpha, P3MParameters::alpha_L, P3MStateCommon< FloatType >::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, stream, CoulombP3MState< FloatType, FFTConfig >::sum_qpart, and P3MParameters::tuning.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::on_activation().
Member Data Documentation
m_gpu_data
template<typename FloatType , Arch Architecture, class FFTConfig > std::shared_ptr<P3MGpuParams> CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::m_gpu_data = nullptr protected
Definition at line 240 of file p3m_heffte.hpp.
p3m
template<typename FloatType , Arch Architecture, class FFTConfig > CoulombP3MStateClass& CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::p3m
Coulomb P3M parameters.
Definition at line 111 of file p3m_heffte.hpp.
Referenced by CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::adapt_epsilon_elc(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::CoulombP3MHeffte(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::count_charged_particles_elc(), and CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::prepare_fft_mesh().
The documentation for this struct was generated from the following files:
p3m_heffte.hpp
p3m_heffte.impl.hpp