ESPResSo: DipolarScafacosImpl Struct Reference
DipolarScafacosImpl Struct Reference
#include <scafacos_impl.hpp>
Public Types
using ScafacosContext = ScafacosContext<::Scafacos::Dipoles >
Public Member Functions
void update_particle_data () override
void update_particle_forces () const override
double long_range_energy () override
void add_long_range_forces () override
Public Member Functions inherited from DipolarScafacos
~DipolarScafacos () override=default
void on_activation ()
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change ()
void on_cell_structure_change () const
void init () const
void sanity_checks () const override
Public Member Functions inherited from ScafacosContextBase
ScafacosContextBase ()=default
virtual ~ScafacosContextBase ()=default
Public Member Functions inherited from Dipoles::Actor< DipolarScafacos >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Member Functions inherited from ScafacosContext< ScafacosInterface >
void update_system_params () override
std::string get_method () const override
std::string get_parameters () const override
ScafacosContextBase ()=default
Additional Inherited Members
Static Public Member Functions inherited from ScafacosContextBase
static std::vector< std::string > available_methods ()
static void sanity_check_method (std::string const &method_name)
Public Attributes inherited from Dipoles::Actor< DipolarScafacos >
double prefactor
Magnetostatics prefactor.
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 43 of file magnetostatics/scafacos_impl.hpp.
Member Typedef Documentation
ScafacosContext
using DipolarScafacosImpl::ScafacosContext = ScafacosContext<::Scafacos::Dipoles>
Definition at line 45 of file magnetostatics/scafacos_impl.hpp.
Member Function Documentation
add_long_range_forces()
void DipolarScafacosImpl::add_long_range_forces () inline override virtual
Implements ScafacosContextBase.
Definition at line 58 of file magnetostatics/scafacos_impl.hpp.
References update_particle_data(), and update_particle_forces().
long_range_energy()
double DipolarScafacosImpl::long_range_energy () inline override virtual
Implements ScafacosContextBase.
Definition at line 52 of file magnetostatics/scafacos_impl.hpp.
References Dipoles::Actor< DipolarScafacos >::prefactor, and update_particle_data().
update_particle_data()
void DipolarScafacosImpl::update_particle_data () override virtual
Implements ScafacosContextBase.
Definition at line 49 of file magnetostatics/scafacos_impl.cpp.
References System::Leaf< Class >::get_system(), and stream.
Referenced by add_long_range_forces(), and long_range_energy().
update_particle_forces()
void DipolarScafacosImpl::update_particle_forces () const override virtual
Implements ScafacosContextBase.
Definition at line 69 of file magnetostatics/scafacos_impl.cpp.
References System::Leaf< Class >::get_system(), Dipoles::Actor< DipolarScafacos >::prefactor, stream, and vector_product().
Referenced by add_long_range_forces().
The documentation for this struct was generated from the following files:
magnetostatics/scafacos_impl.hpp
magnetostatics/scafacos_impl.cpp