ESPResSo: AngleCosineBond Struct Reference
AngleCosineBond Struct Reference
Parameters for three-body angular potential (cosine).
#include <angle_cosine.hpp>
Public Member Functions
double cutoff () const
AngleCosineBond (double bend, double phi0)
std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > forces (Utils::Vector3d const &r_mid, Utils::Vector3d const &r_left, Utils::Vector3d const &r_right) const
Compute the three-body angle interaction force.
double energy (Utils::Vector3d const &r_mid, Utils::Vector3d const &r_left, Utils::Vector3d const &r_right) const
Computes the three-body angle interaction energy.
Public Attributes
double bend
bending constant
double phi0
equilibrium angle (default is 180 degrees)
double cos_phi0
cosine of phi0 (internal parameter)
double sin_phi0
sine of phi0 (internal parameter)
Static Public Attributes
static constexpr int num = 2
Detailed Description
Parameters for three-body angular potential (cosine).
Definition at line 38 of file angle_cosine.hpp.
Constructor & Destructor Documentation
AngleCosineBond()
AngleCosineBond::AngleCosineBond (double bend, double phi0)
Definition at line 29 of file angle_cosine.cpp.
References bend, cos_phi0, phi0, and sin_phi0.
Member Function Documentation
cutoff()
double AngleCosineBond::cutoff () const inline
Definition at line 48 of file angle_cosine.hpp.
energy()
double AngleCosineBond::energy (Utils::Vector3d const & r_mid, Utils::Vector3d const & r_left, Utils::Vector3d const & r_right) const inline
Computes the three-body angle interaction energy.
Parameters
[in] r_mid Position of second/middle particle.
[in] r_left Position of first/left particle.
[in] r_right Position of third/right particle.
Definition at line 97 of file angle_cosine.hpp.
References bend, calc_vectors_and_cosine(), cos_phi0, sin_phi0, Utils::sqr(), and Utils::sqrt().
forces()
std::tuple< Utils::Vector3d, Utils::Vector3d, Utils::Vector3d > AngleCosineBond::forces (Utils::Vector3d const & r_mid, Utils::Vector3d const & r_left, Utils::Vector3d const & r_right) const inline
Compute the three-body angle interaction force.
Parameters
[in] r_mid Position of second/middle particle.
[in] r_left Position of first/left particle.
[in] r_right Position of third/right particle.
Returns
Forces on the second, first and third particles, in that order.
Definition at line 78 of file angle_cosine.hpp.
References angle_generic_force(), bend, cos_phi0, sin_phi0, Utils::sqr(), and Utils::sqrt().
Member Data Documentation
bend
double AngleCosineBond::bend
bending constant
Definition at line 40 of file angle_cosine.hpp.
Referenced by AngleCosineBond(), energy(), and forces().
cos_phi0
double AngleCosineBond::cos_phi0
cosine of phi0 (internal parameter)
Definition at line 44 of file angle_cosine.hpp.
Referenced by AngleCosineBond(), energy(), and forces().
num
constexpr int AngleCosineBond::num = 2 static constexpr
Definition at line 50 of file angle_cosine.hpp.
phi0
double AngleCosineBond::phi0
equilibrium angle (default is 180 degrees)
Definition at line 42 of file angle_cosine.hpp.
Referenced by AngleCosineBond().
sin_phi0
double AngleCosineBond::sin_phi0
sine of phi0 (internal parameter)
Definition at line 46 of file angle_cosine.hpp.
Referenced by AngleCosineBond(), energy(), and forces().
The documentation for this struct was generated from the following files:
angle_cosine.hpp
angle_cosine.cpp