ESPResSo: CoulombScafacosImpl Struct Reference
CoulombScafacosImpl Struct Reference
#include <scafacos_impl.hpp>
Public Types
using ScafacosContext = ScafacosContext<::Scafacos::Coulomb >
Public Member Functions
void update_particle_data () override
void update_particle_forces () const override
double long_range_energy () override
void add_long_range_forces () override
double get_pair_force (double dist) const override
double get_pair_energy (double dist) const override
void set_near_field_delegation (bool delegate) override
bool get_near_field_delegation () const override
double get_r_cut () const override
Public Member Functions inherited from CoulombScafacos
~CoulombScafacos () override=default
void on_activation ()
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change ()
void on_cell_structure_change () const
void init () const
void sanity_checks () const override
bool is_tuned () const
void tune ()
Utils::Vector3d pair_force (double q1q2, Utils::Vector3d const &d, double dist) const
Calculate near-field pair force.
double pair_energy (double q1q2, double dist) const
Calculate near-field pair energy.
Public Member Functions inherited from ScafacosContextBase
ScafacosContextBase ()=default
virtual ~ScafacosContextBase ()=default
Public Member Functions inherited from Coulomb::Actor< CoulombScafacos >
void set_prefactor (double new_prefactor)
void sanity_checks_charge_neutrality () const
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Member Functions inherited from ScafacosContext< ScafacosInterface >
void update_system_params () override
std::string get_method () const override
std::string get_parameters () const override
ScafacosContextBase ()=default
Private Member Functions
void tune_impl () override
Additional Inherited Members
Static Public Member Functions inherited from ScafacosContextBase
static std::vector< std::string > available_methods ()
static void sanity_check_method (std::string const &method_name)
Public Attributes inherited from Coulomb::Actor< CoulombScafacos >
double prefactor
Electrostatics prefactor.
double charge_neutrality_tolerance
Relative tolerance for the charge excess during neutrality checks.
Static Public Attributes inherited from Coulomb::Actor< CoulombScafacos >
static auto constexpr charge_neutrality_tolerance_default
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 38 of file electrostatics/scafacos_impl.hpp.
Member Typedef Documentation
ScafacosContext
using CoulombScafacosImpl::ScafacosContext = ScafacosContext<::Scafacos::Coulomb>
Definition at line 40 of file electrostatics/scafacos_impl.hpp.
Member Function Documentation
add_long_range_forces()
void CoulombScafacosImpl::add_long_range_forces () inline override virtual
Implements ScafacosContextBase.
Definition at line 53 of file electrostatics/scafacos_impl.hpp.
References update_particle_data(), and update_particle_forces().
get_near_field_delegation()
bool CoulombScafacosImpl::get_near_field_delegation () const inline override virtual
Implements CoulombScafacos.
Definition at line 71 of file electrostatics/scafacos_impl.hpp.
get_pair_energy()
double CoulombScafacosImpl::get_pair_energy (double dist) const inline override virtual
Implements CoulombScafacos.
Definition at line 63 of file electrostatics/scafacos_impl.hpp.
References stream.
get_pair_force()
double CoulombScafacosImpl::get_pair_force (double dist) const inline override virtual
Implements CoulombScafacos.
Definition at line 59 of file electrostatics/scafacos_impl.hpp.
References stream.
get_r_cut()
double CoulombScafacosImpl::get_r_cut () const inline override virtual
Implements CoulombScafacos.
Definition at line 75 of file electrostatics/scafacos_impl.hpp.
long_range_energy()
double CoulombScafacosImpl::long_range_energy () inline override virtual
Implements ScafacosContextBase.
Definition at line 47 of file electrostatics/scafacos_impl.hpp.
References Coulomb::Actor< CoulombScafacos >::prefactor, and update_particle_data().
set_near_field_delegation()
void CoulombScafacosImpl::set_near_field_delegation (bool delegate) inline override virtual
Implements CoulombScafacos.
Definition at line 67 of file electrostatics/scafacos_impl.hpp.
References stream.
tune_impl()
void CoulombScafacosImpl::tune_impl () override private virtual
Implements CoulombScafacos.
Definition at line 133 of file electrostatics/scafacos_impl.cpp.
References System::Leaf< Class >::get_system(), stream, and update_particle_data().
update_particle_data()
void CoulombScafacosImpl::update_particle_data () override virtual
Implements ScafacosContextBase.
Definition at line 52 of file electrostatics/scafacos_impl.cpp.
References System::Leaf< Class >::get_system(), and stream.
Referenced by add_long_range_forces(), long_range_energy(), and tune_impl().
update_particle_forces()
void CoulombScafacosImpl::update_particle_forces () const override virtual
Implements ScafacosContextBase.
Definition at line 69 of file electrostatics/scafacos_impl.cpp.
References System::Leaf< Class >::get_system(), Coulomb::Actor< CoulombScafacos >::prefactor, and stream.
Referenced by add_long_range_forces().
The documentation for this struct was generated from the following files:
electrostatics/scafacos_impl.hpp
electrostatics/scafacos_impl.cpp