ESPResSo: Communicator Struct Reference
Communicator Struct Reference
#include <communication.hpp>
Public Member Functions
Communicator ()
void init_comm_cart ()
void full_initialization ()
Utils::Vector3i calc_node_index () const
Calculate the node index in the Cartesian topology.
void set_node_grid (Utils::Vector3i const &value)
Set new Cartesian topology.
Public Attributes
boost::mpi::communicator & comm
Utils::Vector3i node_grid
int & this_node
The MPI rank.
int size
The MPI world size.
bool locked_for_checkpointing
Detailed Description
Definition at line 84 of file core/communication.hpp.
Constructor & Destructor Documentation
Communicator()
Communicator::Communicator ()
Definition at line 162 of file communication.cpp.
Member Function Documentation
calc_node_index()
Utils::Vector3i Communicator::calc_node_index () const
Calculate the node index in the Cartesian topology.
Definition at line 191 of file communication.cpp.
References comm, and this_node.
Referenced by System::System::update_local_geo().
full_initialization()
void Communicator::full_initialization ()
Definition at line 177 of file communication.cpp.
References init_comm_cart(), node_grid, size, stream, and this_node.
Referenced by CommunicationEnvironment::CommunicationEnvironment().
init_comm_cart()
void Communicator::init_comm_cart ()
Definition at line 166 of file communication.cpp.
References Utils::Mpi::cart_create(), comm, Utils::Vector< T, N >::data(), walberla::mpi_reinit(), node_grid, stream, and this_node.
Referenced by full_initialization(), and set_node_grid().
set_node_grid()
void Communicator::set_node_grid (Utils::Vector3i const & value)
Set new Cartesian topology.
Definition at line 185 of file communication.cpp.
References init_comm_cart(), locked_for_checkpointing, node_grid, and stream.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), and ScriptInterface::CellSystem::CheckpointerContext::do_call_method().
Member Data Documentation
comm
boost::mpi::communicator& Communicator::comm
Definition at line 85 of file core/communication.hpp.
Referenced by calc_node_index(), and init_comm_cart().
locked_for_checkpointing
bool Communicator::locked_for_checkpointing
Definition at line 91 of file core/communication.hpp.
Referenced by ScriptInterface::CellSystem::CheckpointerContext::do_call_method(), and set_node_grid().
node_grid
Utils::Vector3i Communicator::node_grid
Definition at line 86 of file core/communication.hpp.
Referenced by ScriptInterface::CellSystem::CellSystem::CellSystem(), full_initialization(), FFTBackendLegacy< FloatType >::init(), init_comm_cart(), CoulombP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), DipolarP3MHeffte< FloatType, Architecture, FFTConfig >::init_cpu_kernels(), DipolarP3M::sanity_checks_node_grid(), set_node_grid(), and System::System::update_local_geo().
size
int Communicator::size
The MPI world size.
Definition at line 90 of file core/communication.hpp.
Referenced by full_initialization().
this_node
int& Communicator::this_node
The MPI rank.
Definition at line 88 of file core/communication.hpp.
Referenced by calc_node_index(), full_initialization(), and init_comm_cart().
The documentation for this struct was generated from the following files:
core/communication.hpp
communication.cpp