ESPResSo: DipolarDirectSumWithReplica Struct Reference
DipolarDirectSumWithReplica Struct Reference
Dipolar direct sum with replica.
#include <dds_replica.hpp>
Public Member Functions
DipolarDirectSumWithReplica (double prefactor, int n_replica)
void on_activation () const
void on_boxl_change () const
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change () const
void init () const
void sanity_checks () const
double kernel (bool force_flag, bool energy_flag, ParticleRange const &particles) const
Public Attributes
double prefactor
int n_replica
Detailed Description
Dipolar direct sum with replica.
Calculate dipole-dipole interaction of a periodic system by explicitly summing the dipole-dipole interaction over several copies of the system. Uses spherical summation order.
Definition at line 37 of file dds_replica.hpp.
Constructor & Destructor Documentation
DipolarDirectSumWithReplica()
DipolarDirectSumWithReplica::DipolarDirectSumWithReplica (double prefactor, int n_replica)
Definition at line 205 of file dds_replica.cpp.
References prefactor.
Member Function Documentation
init()
void DipolarDirectSumWithReplica::init () const inline
Definition at line 47 of file dds_replica.hpp.
kernel()
double DipolarDirectSumWithReplica::kernel (bool force_flag, bool energy_flag, ParticleRange const & particles) const
Definition at line 51 of file dds_replica.cpp.
References box_geo, D3Q19::c, folded_position(), force, BoxGeometry::length(), n_nodes, n_replica, Cells::particles(), BoxGeometry::periodic(), prefactor, ParticleRange::size(), Utils::sqr(), Utils::sqrt(), and torque.
on_activation()
void DipolarDirectSumWithReplica::on_activation () const inline
Definition at line 42 of file dds_replica.hpp.
References sanity_checks().
on_boxl_change()
void DipolarDirectSumWithReplica::on_boxl_change () const inline
Definition at line 43 of file dds_replica.hpp.
on_cell_structure_change()
void DipolarDirectSumWithReplica::on_cell_structure_change () const inline
Definition at line 46 of file dds_replica.hpp.
on_node_grid_change()
void DipolarDirectSumWithReplica::on_node_grid_change () const inline
Definition at line 44 of file dds_replica.hpp.
on_periodicity_change()
void DipolarDirectSumWithReplica::on_periodicity_change () const inline
Definition at line 45 of file dds_replica.hpp.
sanity_checks()
void DipolarDirectSumWithReplica::sanity_checks () const inline
Definition at line 49 of file dds_replica.hpp.
Referenced by on_activation().
Member Data Documentation
n_replica
int DipolarDirectSumWithReplica::n_replica
Definition at line 39 of file dds_replica.hpp.
Referenced by kernel().
prefactor
double DipolarDirectSumWithReplica::prefactor
Definition at line 38 of file dds_replica.hpp.
Referenced by DipolarDirectSumWithReplica(), and kernel().
The documentation for this struct was generated from the following files:
dds_replica.hpp
dds_replica.cpp