ESPResSo: DipolarDirectSumGpu Struct Reference
DipolarDirectSumGpu Struct Reference
#include <dipolar_direct_sum_gpu.hpp>
Public Member Functions
DipolarDirectSumGpu (double prefactor, int n_replicas)
void on_activation () const
void on_boxl_change () const
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change () const
void init () const
void sanity_checks () const
void add_long_range_forces () const
double long_range_energy () const
Calculate long-range dipolar energy.
Public Member Functions inherited from Dipoles::Actor< DipolarDirectSumGpu >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
int n_replicas
Public Attributes inherited from Dipoles::Actor< DipolarDirectSumGpu >
double prefactor
Magnetostatics prefactor.
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 28 of file dipolar_direct_sum_gpu.hpp.
Constructor & Destructor Documentation
DipolarDirectSumGpu()
DipolarDirectSumGpu::DipolarDirectSumGpu (double prefactor, int n_replicas)
Definition at line 40 of file dipolar_direct_sum_gpu.cpp.
References n_replicas, Dipoles::Actor< DipolarDirectSumGpu >::prefactor, and Dipoles::Actor< DipolarDirectSumGpu >::set_prefactor().
Member Function Documentation
add_long_range_forces()
void DipolarDirectSumGpu::add_long_range_forces () const
Definition at line 59 of file dipolar_direct_sum_gpu.cpp.
References DipolarDirectSum_kernel_wrapper_force(), get_simulation_box(), System::Leaf< Class >::get_system(), n_replicas, Dipoles::Actor< DipolarDirectSumGpu >::prefactor, and this_node.
init()
void DipolarDirectSumGpu::init () const inline
Definition at line 37 of file dipolar_direct_sum_gpu.hpp.
long_range_energy()
double DipolarDirectSumGpu::long_range_energy () const
Calculate long-range dipolar energy.
The energy is stored on a GPU accumulator, and zero is returned from this method.
Definition at line 84 of file dipolar_direct_sum_gpu.cpp.
References DipolarDirectSum_kernel_wrapper_energy(), get_simulation_box(), System::Leaf< Class >::get_system(), Dipoles::Actor< DipolarDirectSumGpu >::prefactor, and this_node.
on_activation()
void DipolarDirectSumGpu::on_activation () const
Definition at line 48 of file dipolar_direct_sum_gpu.cpp.
References GpuParticleData::prop::dip, GpuParticleData::prop::dip_fld, GpuParticleData::prop::force, System::Leaf< Class >::get_system(), GpuParticleData::prop::pos, and GpuParticleData::prop::torque.
on_boxl_change()
void DipolarDirectSumGpu::on_boxl_change () const inline
Definition at line 33 of file dipolar_direct_sum_gpu.hpp.
on_cell_structure_change()
void DipolarDirectSumGpu::on_cell_structure_change () const inline
Definition at line 36 of file dipolar_direct_sum_gpu.hpp.
on_node_grid_change()
void DipolarDirectSumGpu::on_node_grid_change () const inline
Definition at line 34 of file dipolar_direct_sum_gpu.hpp.
on_periodicity_change()
void DipolarDirectSumGpu::on_periodicity_change () const inline
Definition at line 35 of file dipolar_direct_sum_gpu.hpp.
sanity_checks()
void DipolarDirectSumGpu::sanity_checks () const inline
Definition at line 38 of file dipolar_direct_sum_gpu.hpp.
Member Data Documentation
n_replicas
int DipolarDirectSumGpu::n_replicas
Definition at line 29 of file dipolar_direct_sum_gpu.hpp.
Referenced by add_long_range_forces(), and DipolarDirectSumGpu().
The documentation for this struct was generated from the following files:
dipolar_direct_sum_gpu.hpp
dipolar_direct_sum_gpu.cpp