ESPResSo: DipolarBarnesHutGpu Struct Reference
DipolarBarnesHutGpu Struct Reference
#include <barnes_hut_gpu.hpp>
Public Member Functions
DipolarBarnesHutGpu (double prefactor, double epssq, double itolsq)
~DipolarBarnesHutGpu ()
void on_activation () const
void on_boxl_change () const
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change () const
void init () const
void sanity_checks () const
void add_long_range_forces ()
void long_range_energy ()
Public Member Functions inherited from Dipoles::Actor< DipolarBarnesHutGpu >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
double m_epssq
double m_itolsq
Public Attributes inherited from Dipoles::Actor< DipolarBarnesHutGpu >
double prefactor
Magnetostatics prefactor.
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 29 of file barnes_hut_gpu.hpp.
Constructor & Destructor Documentation
DipolarBarnesHutGpu()
DipolarBarnesHutGpu::DipolarBarnesHutGpu (double prefactor, double epssq, double itolsq)
Definition at line 33 of file barnes_hut_gpu.cpp.
References m_epssq, m_itolsq, Dipoles::Actor< DipolarBarnesHutGpu >::prefactor, and Dipoles::Actor< DipolarBarnesHutGpu >::set_prefactor().
~DipolarBarnesHutGpu()
DipolarBarnesHutGpu::~DipolarBarnesHutGpu () inline
Definition at line 33 of file barnes_hut_gpu.hpp.
References deallocBH().
Member Function Documentation
add_long_range_forces()
void DipolarBarnesHutGpu::add_long_range_forces ()
Definition at line 88 of file barnes_hut_gpu.cpp.
References call_kernel(), ES_OK, forceBH(), System::Leaf< Class >::get_system(), Dipoles::Actor< DipolarBarnesHutGpu >::prefactor, and this_node.
init()
void DipolarBarnesHutGpu::init () const inline
Definition at line 40 of file barnes_hut_gpu.hpp.
long_range_energy()
void DipolarBarnesHutGpu::long_range_energy ()
Definition at line 101 of file barnes_hut_gpu.cpp.
References call_kernel(), energyBH(), ES_OK, System::Leaf< Class >::get_system(), Dipoles::Actor< DipolarBarnesHutGpu >::prefactor, and this_node.
on_activation()
void DipolarBarnesHutGpu::on_activation () const
Definition at line 46 of file barnes_hut_gpu.cpp.
References GpuParticleData::prop::dip, GpuParticleData::prop::force, System::Leaf< Class >::get_system(), m_epssq, m_itolsq, GpuParticleData::prop::pos, setBHPrecision(), this_node, and GpuParticleData::prop::torque.
on_boxl_change()
void DipolarBarnesHutGpu::on_boxl_change () const inline
Definition at line 36 of file barnes_hut_gpu.hpp.
on_cell_structure_change()
void DipolarBarnesHutGpu::on_cell_structure_change () const inline
Definition at line 39 of file barnes_hut_gpu.hpp.
on_node_grid_change()
void DipolarBarnesHutGpu::on_node_grid_change () const inline
Definition at line 37 of file barnes_hut_gpu.hpp.
on_periodicity_change()
void DipolarBarnesHutGpu::on_periodicity_change () const inline
Definition at line 38 of file barnes_hut_gpu.hpp.
sanity_checks()
void DipolarBarnesHutGpu::sanity_checks () const inline
Definition at line 41 of file barnes_hut_gpu.hpp.
Member Data Documentation
m_epssq
double DipolarBarnesHutGpu::m_epssq
Definition at line 30 of file barnes_hut_gpu.hpp.
Referenced by DipolarBarnesHutGpu(), and on_activation().
m_itolsq
double DipolarBarnesHutGpu::m_itolsq
Definition at line 31 of file barnes_hut_gpu.hpp.
Referenced by DipolarBarnesHutGpu(), and on_activation().
The documentation for this struct was generated from the following files:
barnes_hut_gpu.hpp
barnes_hut_gpu.cpp