ESPResSo: BaseThermostat Struct Reference
BaseThermostat Struct Reference
#include <thermostat.hpp>
Public Member Functions
void rng_initialize (uint32_t const seed)
Initialize or re-initialize the RNG counter with a seed.
void rng_increment ()
Increment the RNG counter.
uint64_t rng_counter () const
Get current value of the RNG.
void set_rng_counter (uint64_t value)
bool is_seed_required () const
Is the RNG seed required.
uint32_t rng_seed () const
Detailed Description
Definition at line 111 of file core/thermostat.hpp.
Member Function Documentation
is_seed_required()
bool BaseThermostat::is_seed_required () const inline
Is the RNG seed required.
Definition at line 126 of file core/thermostat.hpp.
References stream.
rng_counter()
uint64_t BaseThermostat::rng_counter () const inline
Get current value of the RNG.
Definition at line 121 of file core/thermostat.hpp.
References Utils::Counter< T >::value().
Referenced by bd_random_walk(), bd_random_walk_rot(), bd_random_walk_vel(), bd_random_walk_vel_rot(), dpd_noise(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), LB::ParticleCoupling::get_noise_term(), propagate_therm0_nptiso(), propagate_thermV_nptiso(), and StokesianDynamics::propagate_vel_pos().
rng_increment()
void BaseThermostat::rng_increment () inline
Increment the RNG counter.
Definition at line 119 of file core/thermostat.hpp.
References Utils::Counter< T >::increment().
rng_initialize()
void BaseThermostat::rng_initialize (uint32_t const seed) inline
Initialize or re-initialize the RNG counter with a seed.
Definition at line 114 of file core/thermostat.hpp.
Referenced by StokesianThermostat::StokesianThermostat().
rng_seed()
uint32_t BaseThermostat::rng_seed () const inline
Definition at line 127 of file core/thermostat.hpp.
Referenced by bd_random_walk(), bd_random_walk_rot(), bd_random_walk_vel(), bd_random_walk_vel_rot(), dpd_noise(), friction_thermo_langevin(), friction_thermo_langevin_rotation(), LB::ParticleCoupling::get_noise_term(), propagate_therm0_nptiso(), propagate_thermV_nptiso(), and StokesianDynamics::propagate_vel_pos().
set_rng_counter()
void BaseThermostat::set_rng_counter (uint64_t value) inline
Definition at line 122 of file core/thermostat.hpp.
References stream.
The documentation for this struct was generated from the following file:
core/thermostat.hpp