ESPResSo: EK::EKWalberla Struct Reference
EK::EKWalberla Struct Reference
#include <EKWalberla.hpp>
Public Types
using ek_container_type = EKContainer< EKinWalberlaBase >
using ek_reactions_type = EKReactions< walberla::EKReactionBase >
Public Member Functions
EKWalberla (std::shared_ptr< ek_container_type > ek_container_instance, std::shared_ptr< ek_reactions_type > ek_reactions_instance)
double get_tau () const
void veto_time_step (double time_step) const
void veto_kT (double kT) const
void sanity_checks (System::System const &system) const
bool is_ready_for_propagation () const noexcept
void propagate ()
void perform_reactions ()
void on_cell_structure_change () const
void veto_boxl_change () const
void on_boxl_change () const
void on_node_grid_change () const
void on_timestep_change () const
void on_temperature_change () const
bool is_gpu () const
Public Member Functions inherited from System::Leaf< EKWalberla >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
std::shared_ptr< ek_container_type > ek_container
std::shared_ptr< ek_reactions_type > ek_reactions
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< EKWalberla >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< EKWalberla >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 47 of file EKWalberla.hpp.
Member Typedef Documentation
ek_container_type
using EK::EKWalberla::ek_container_type = EKContainer<EKinWalberlaBase>
Definition at line 48 of file EKWalberla.hpp.
ek_reactions_type
using EK::EKWalberla::ek_reactions_type = EKReactions<walberla::EKReactionBase>
Definition at line 49 of file EKWalberla.hpp.
Constructor & Destructor Documentation
EKWalberla()
EK::EKWalberla::EKWalberla (std::shared_ptr< ek_container_type > ek_container_instance, std::shared_ptr< ek_reactions_type > ek_reactions_instance) inline
Definition at line 53 of file EKWalberla.hpp.
Member Function Documentation
get_tau()
double EK::EKWalberla::get_tau () const
Definition at line 48 of file EKWalberla.cpp.
References ek_container.
is_gpu()
bool EK::EKWalberla::is_gpu () const
Definition at line 46 of file EKWalberla.cpp.
References ek_container.
is_ready_for_propagation()
bool EK::EKWalberla::is_ready_for_propagation () const noexcept
Definition at line 50 of file EKWalberla.cpp.
References ek_container, and stream.
on_boxl_change()
void EK::EKWalberla::on_boxl_change () const inline
Definition at line 70 of file EKWalberla.hpp.
References veto_boxl_change().
on_cell_structure_change()
void EK::EKWalberla::on_cell_structure_change () const inline
Definition at line 66 of file EKWalberla.hpp.
on_node_grid_change()
void EK::EKWalberla::on_node_grid_change () const inline
Definition at line 71 of file EKWalberla.hpp.
on_temperature_change()
void EK::EKWalberla::on_temperature_change () const inline
Definition at line 75 of file EKWalberla.hpp.
on_timestep_change()
void EK::EKWalberla::on_timestep_change () const inline
Definition at line 74 of file EKWalberla.hpp.
perform_reactions()
void EK::EKWalberla::perform_reactions ()
Definition at line 108 of file EKWalberla.cpp.
References ek_reactions, and stream.
Referenced by propagate().
propagate()
void EK::EKWalberla::propagate ()
Definition at line 71 of file EKWalberla.cpp.
References LB::Solver::connect(), ek_container, System::get_system(), System::System::lb, perform_reactions(), runtimeErrorMsg, and stream.
sanity_checks()
void EK::EKWalberla::sanity_checks (System::System const & system) const
Definition at line 125 of file EKWalberla.cpp.
References ek_container, stream, walberla_agrid_sanity_checks(), and walberla_tau_sanity_checks().
veto_boxl_change()
void EK::EKWalberla::veto_boxl_change () const inline
Definition at line 67 of file EKWalberla.hpp.
Referenced by on_boxl_change().
veto_kT()
void EK::EKWalberla::veto_kT (double kT) const
Definition at line 118 of file EKWalberla.cpp.
References ek_container, and stream.
veto_time_step()
void EK::EKWalberla::veto_time_step (double time_step) const
Definition at line 114 of file EKWalberla.cpp.
References ek_container, and walberla_tau_sanity_checks().
Member Data Documentation
ek_container
std::shared_ptr<ek_container_type> EK::EKWalberla::ek_container
Definition at line 50 of file EKWalberla.hpp.
Referenced by get_tau(), is_gpu(), is_ready_for_propagation(), propagate(), sanity_checks(), veto_kT(), and veto_time_step().
ek_reactions
std::shared_ptr<ek_reactions_type> EK::EKWalberla::ek_reactions
Definition at line 51 of file EKWalberla.hpp.
Referenced by perform_reactions().
The documentation for this struct was generated from the following files:
EKWalberla.hpp
EKWalberla.cpp