ESPResSo: ParticlePosition Struct Reference
ParticlePosition Struct Reference
Positional information on a particle.
#include <Particle.hpp>
Public Member Functions
Utils::Vector3d calc_director () const
unit director calculated from the quaternion
template<class Archive >
void serialize (Archive &ar, long int)
Public Attributes
Utils::Vector3d p = {0., 0., 0.}
periodically folded position.
Utils::Vector3i i = {0, 0, 0}
index of the simulation box image where the particle really sits.
Utils::Quaternion< double > quat = Utils::Quaternion<double>::identity()
quaternion to define particle orientation
Utils::Vector3d p_last_timestep = {0., 0., 0.}
particle position at the previous time step (RATTLE algorithm)
Detailed Description
Positional information on a particle.
Information that is communicated to calculate interactions with ghost particles.
Definition at line 295 of file Particle.hpp.
Member Function Documentation
calc_director()
Utils::Vector3d ParticlePosition::calc_director () const inline
unit director calculated from the quaternion
Definition at line 305 of file Particle.hpp.
References Utils::convert_quaternion_to_director(), and quat.
Referenced by Particle::calc_director().
serialize()
template<class Archive > void ParticlePosition::serialize (Archive & ar, long int) inline
Definition at line 315 of file Particle.hpp.
References i, p, p_last_timestep, quat, and stream.
Member Data Documentation
i
Utils::Vector3i ParticlePosition::i = {0, 0, 0}
index of the simulation box image where the particle really sits.
Definition at line 299 of file Particle.hpp.
Referenced by Particle::image_box(), Particle::image_box(), and serialize().
p
Utils::Vector3d ParticlePosition::p = {0., 0., 0.}
periodically folded position.
Definition at line 297 of file Particle.hpp.
Referenced by Particle::pos(), Particle::pos(), and serialize().
p_last_timestep
Utils::Vector3d ParticlePosition::p_last_timestep = {0., 0., 0.}
particle position at the previous time step (RATTLE algorithm)
Definition at line 312 of file Particle.hpp.
Referenced by Particle::pos_last_time_step(), Particle::pos_last_time_step(), and serialize().
quat
Utils::Quaternion<double> ParticlePosition::quat = Utils::Quaternion<double>::identity()
quaternion to define particle orientation
Definition at line 303 of file Particle.hpp.
Referenced by calc_director(), Particle::quat(), Particle::quat(), and serialize().
The documentation for this struct was generated from the following file:
Particle.hpp