ESPResSo: StokesianDynamics Struct Reference
StokesianDynamics Struct Reference
#include <sd_interface.hpp>
Public Member Functions
StokesianDynamics ()=default
StokesianDynamics (double viscosity, std::unordered_map< int, double > radii, int flags)
void propagate_vel_pos (ParticleRangeStokesian const &particles, StokesianThermostat const &stokesian, double time_step, double kT) const
Take the forces and torques on all particles and compute velocities.
Public Attributes
double viscosity = 0.
std::unordered_map< int, double > radii = {}
int flags = 0
Detailed Description
Definition at line 52 of file sd_interface.hpp.
Constructor & Destructor Documentation
StokesianDynamics() [1/2]
StokesianDynamics::StokesianDynamics () default
StokesianDynamics() [2/2]
StokesianDynamics::StokesianDynamics (double viscosity, std::unordered_map< int, double > radii, int flags)
Definition at line 97 of file sd_interface.cpp.
References radii, stream, and viscosity.
Member Function Documentation
propagate_vel_pos()
void StokesianDynamics::propagate_vel_pos (ParticleRangeStokesian const & particles, StokesianThermostat const & stokesian, double time_step, double kT) const
Take the forces and torques on all particles and compute velocities.
Act globally on particles on all nodes; i.e. particle data is gathered from all nodes and their velocities and angular velocities are set according to the Stokesian Dynamics method.
Definition at line 115 of file sd_interface.cpp.
References comm_cart, flags, Utils::Mpi::gather_buffer(), radii, BaseThermostat::rng_counter(), BaseThermostat::rng_seed(), Utils::Mpi::scatter_buffer(), sd_update_locally(), ParticleRange::size(), stream, and viscosity.
Referenced by stokesian_dynamics_step_1().
Member Data Documentation
flags
int StokesianDynamics::flags = 0
Definition at line 55 of file sd_interface.hpp.
Referenced by propagate_vel_pos().
radii
std::unordered_map<int, double> StokesianDynamics::radii = {}
Definition at line 54 of file sd_interface.hpp.
Referenced by propagate_vel_pos(), and StokesianDynamics().
viscosity
double StokesianDynamics::viscosity = 0.
Definition at line 53 of file sd_interface.hpp.
Referenced by propagate_vel_pos(), and StokesianDynamics().
The documentation for this struct was generated from the following files:
sd_interface.hpp
sd_interface.cpp