ESPResSo: AssignForces< cao > Struct Template Reference
AssignForces< cao > Struct Template Reference
Public Member Functions
template<typename combined_ranges >
void operator() (p3m_data_struct &p3m, double force_prefac, combined_ranges const &p_q_force_range) const
Detailed Description
template<int cao>
struct AssignForces< cao >
Definition at line 364 of file p3m.cpp.
Member Function Documentation
operator()()
template<int cao> template<typename combined_ranges > void AssignForces< cao >::operator() (p3m_data_struct & p3m, double force_prefac, combined_ranges const & p_q_force_range) const inline
Definition at line 366 of file p3m.cpp.
References p3m_interpolation_cache::cao(), force, p3m_data_struct::inter_weights, p3m_interpolation_cache::load(), p3m_data_struct::local_mesh, Utils::make_const_span(), and p3m_interpolate().
The documentation for this struct was generated from the following file:
p3m.cpp