ESPResSo: PressureKernel Struct Reference
PressureKernel Struct Reference
#include <pressure_cabana.hpp>
Public Member Functions
PressureKernel (BondedInteractionsMap const &bonded_ias_, InteractionsNonBonded const &nonbonded_ias_, Coulomb::Solver const &coulomb_, Coulomb::ShortRangeForceKernel::kernel_type const *coulomb_f_kernel_, Coulomb::ShortRangePressureKernel::kernel_type const *coulomb_p_kernel_, BoxGeometry const &box_geo_, DPDThermostat const *dpd_, std::vector< Particle * > const &unique_particles_, Kokkos::View< double **, Kokkos::LayoutRight > const &local_pressure_, PressureBinLayout layout_, CellStructure::AoSoA_pack const &aosoa_, Kokkos::View< int * > mol_id_view_, double system_max_cutoff_, int thermo_switch_)
KOKKOS_INLINE_FUNCTION void operator() (std::size_t i, std::size_t j) const
Public Attributes
BondedInteractionsMap const & bonded_ias
InteractionsNonBonded const & nonbonded_ias
Coulomb::Solver const & coulomb
Coulomb::ShortRangeForceKernel::kernel_type const * coulomb_f_kernel
Coulomb::ShortRangePressureKernel::kernel_type const * coulomb_p_kernel
BoxGeometry const & box_geo
DPDThermostat const * dpd
std::vector< Particle * > const & unique_particles
Kokkos::View< double **, Kokkos::LayoutRight > local_pressure
PressureBinLayout layout
CellStructure::AoSoA_pack const & aosoa
Kokkos::View< int * > mol_id_view
double system_max_cutoff
int thermo_switch
Detailed Description
Definition at line 98 of file pressure_cabana.hpp.
Constructor & Destructor Documentation
PressureKernel()
PressureKernel::PressureKernel (BondedInteractionsMap const & bonded_ias_, InteractionsNonBonded const & nonbonded_ias_, Coulomb::Solver const & coulomb_, Coulomb::ShortRangeForceKernel::kernel_type const * coulomb_f_kernel_, Coulomb::ShortRangePressureKernel::kernel_type const * coulomb_p_kernel_, BoxGeometry const & box_geo_, DPDThermostat const * dpd_, std::vector< Particle * > const & unique_particles_, Kokkos::View< double **, Kokkos::LayoutRight > const & local_pressure_, PressureBinLayout layout_, CellStructure::AoSoA_pack const & aosoa_, Kokkos::View< int * > mol_id_view_, double system_max_cutoff_, int thermo_switch_) inline
Definition at line 116 of file pressure_cabana.hpp.
Member Function Documentation
operator()()
KOKKOS_INLINE_FUNCTION void PressureKernel::operator() (std::size_t i, std::size_t j) const inline
Definition at line 143 of file pressure_cabana.hpp.
References aosoa, bonded_ias, box_geo, calc_central_radial_force(), calc_non_central_force(), CellStructure::AoSoA_pack::charge, coulomb_f_kernel, PressureBinLayout::coulomb_idx(), coulomb_p_kernel, CellStructure::AoSoA_pack::director, do_nonbonded(), dpd, dpd_active(), PressureBinLayout::dpd_idx(), dpd_noise(), dpd_pair_force(), Utils::flatten(), gay_berne_active(), InteractionsNonBonded::get_ia_param(), BoxGeometry::get_mi_vector(), CellStructure::AoSoA_pack::get_vector_at(), CellStructure::AoSoA_pack::has_exclusion(), CellStructure::AoSoA_pack::id, layout, local_pressure, mol_id_view, PressureBinLayout::nb_inter_idx(), PressureBinLayout::nb_intra_idx(), nonbonded_ias, Utils::Vector< T, N >::norm2(), P, CellStructure::AoSoA_pack::position, stream, system_max_cutoff, PressureBinLayout::tensor_offset(), Utils::tensor_product(), thermo_switch, thole_active(), thole_pair_force(), CellStructure::AoSoA_pack::type, unique_particles, CellStructure::AoSoA_pack::velocity, and BoxGeometry::velocity_difference().
Member Data Documentation
aosoa
CellStructure::AoSoA_pack const& PressureKernel::aosoa
Definition at line 111 of file pressure_cabana.hpp.
Referenced by operator()().
bonded_ias
BondedInteractionsMap const& PressureKernel::bonded_ias
Definition at line 99 of file pressure_cabana.hpp.
Referenced by operator()().
box_geo
BoxGeometry const& PressureKernel::box_geo
Definition at line 104 of file pressure_cabana.hpp.
Referenced by operator()().
coulomb
Coulomb::Solver const& PressureKernel::coulomb
Definition at line 101 of file pressure_cabana.hpp.
coulomb_f_kernel
Coulomb::ShortRangeForceKernel::kernel_type const* PressureKernel::coulomb_f_kernel
Definition at line 102 of file pressure_cabana.hpp.
Referenced by operator()().
coulomb_p_kernel
Coulomb::ShortRangePressureKernel::kernel_type const* PressureKernel::coulomb_p_kernel
Definition at line 103 of file pressure_cabana.hpp.
Referenced by operator()().
dpd
DPDThermostat const* PressureKernel::dpd
Definition at line 106 of file pressure_cabana.hpp.
Referenced by System::System::calculate_pressure(), and operator()().
layout
PressureBinLayout PressureKernel::layout
Definition at line 110 of file pressure_cabana.hpp.
Referenced by operator()().
local_pressure
Kokkos::View<double **, Kokkos::LayoutRight> PressureKernel::local_pressure
Definition at line 109 of file pressure_cabana.hpp.
Referenced by operator()().
mol_id_view
Kokkos::View<int *> PressureKernel::mol_id_view
Definition at line 112 of file pressure_cabana.hpp.
Referenced by operator()().
nonbonded_ias
InteractionsNonBonded const& PressureKernel::nonbonded_ias
Definition at line 100 of file pressure_cabana.hpp.
Referenced by operator()().
system_max_cutoff
double PressureKernel::system_max_cutoff
Definition at line 113 of file pressure_cabana.hpp.
Referenced by operator()().
thermo_switch
int PressureKernel::thermo_switch
Definition at line 114 of file pressure_cabana.hpp.
Referenced by operator()().
unique_particles
std::vector<Particle *> const& PressureKernel::unique_particles
Definition at line 108 of file pressure_cabana.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
pressure_cabana.hpp