ESPResSo: EnergyBinLayout Struct Reference
EnergyBinLayout Struct Reference
#include <energy_cabana.hpp>
Public Member Functions
EnergyBinLayout (std::size_t n_bonded_, std::size_t n_types_)
KOKKOS_INLINE_FUNCTION std::size_t nb_inter_idx (int t1, int t2) const
KOKKOS_INLINE_FUNCTION std::size_t nb_intra_idx (int t1, int t2) const
KOKKOS_INLINE_FUNCTION std::size_t dipolar_idx () const
KOKKOS_INLINE_FUNCTION std::size_t coulomb_idx () const
KOKKOS_INLINE_FUNCTION std::size_t bonded_idx (int b) const
Public Attributes
std::size_t n_bonded
std::size_t n_types
std::size_t off_bonded = 0
std::size_t off_nb_inter
std::size_t off_nb_intra
std::size_t off_coulomb
std::size_t off_dipolar
std::size_t total
Detailed Description
Definition at line 40 of file energy_cabana.hpp.
Constructor & Destructor Documentation
EnergyBinLayout()
EnergyBinLayout::EnergyBinLayout (std::size_t n_bonded_, std::size_t n_types_) inline
Definition at line 50 of file energy_cabana.hpp.
References n_bonded, n_types, off_bonded, off_coulomb, off_dipolar, off_nb_inter, off_nb_intra, stream, and total.
Member Function Documentation
bonded_idx()
KOKKOS_INLINE_FUNCTION std::size_t EnergyBinLayout::bonded_idx (int b) const inline
Definition at line 74 of file energy_cabana.hpp.
References off_bonded.
Referenced by reduce_cabana_energy().
coulomb_idx()
KOKKOS_INLINE_FUNCTION std::size_t EnergyBinLayout::coulomb_idx () const inline
Definition at line 73 of file energy_cabana.hpp.
References off_coulomb.
Referenced by EnergyKernel::operator()(), and reduce_cabana_energy().
dipolar_idx()
KOKKOS_INLINE_FUNCTION std::size_t EnergyBinLayout::dipolar_idx () const inline
Definition at line 72 of file energy_cabana.hpp.
References off_dipolar.
Referenced by EnergyKernel::operator()(), and reduce_cabana_energy().
nb_inter_idx()
KOKKOS_INLINE_FUNCTION std::size_t EnergyBinLayout::nb_inter_idx (int t1, int t2) const inline
Definition at line 61 of file energy_cabana.hpp.
References Utils::lower_triangular(), off_nb_inter, and stream.
Referenced by EnergyKernel::operator()(), and reduce_cabana_energy().
nb_intra_idx()
KOKKOS_INLINE_FUNCTION std::size_t EnergyBinLayout::nb_intra_idx (int t1, int t2) const inline
Definition at line 67 of file energy_cabana.hpp.
References Utils::lower_triangular(), off_nb_intra, and stream.
Referenced by EnergyKernel::operator()(), and reduce_cabana_energy().
Member Data Documentation
n_bonded
std::size_t EnergyBinLayout::n_bonded
Definition at line 41 of file energy_cabana.hpp.
Referenced by EnergyBinLayout(), and reduce_cabana_energy().
n_types
std::size_t EnergyBinLayout::n_types
Definition at line 42 of file energy_cabana.hpp.
Referenced by EnergyBinLayout().
off_bonded
std::size_t EnergyBinLayout::off_bonded = 0
Definition at line 43 of file energy_cabana.hpp.
Referenced by bonded_idx(), and EnergyBinLayout().
off_coulomb
std::size_t EnergyBinLayout::off_coulomb
Definition at line 46 of file energy_cabana.hpp.
Referenced by coulomb_idx(), and EnergyBinLayout().
off_dipolar
std::size_t EnergyBinLayout::off_dipolar
Definition at line 47 of file energy_cabana.hpp.
Referenced by dipolar_idx(), and EnergyBinLayout().
off_nb_inter
std::size_t EnergyBinLayout::off_nb_inter
Definition at line 44 of file energy_cabana.hpp.
Referenced by EnergyBinLayout(), and nb_inter_idx().
off_nb_intra
std::size_t EnergyBinLayout::off_nb_intra
Definition at line 45 of file energy_cabana.hpp.
Referenced by EnergyBinLayout(), and nb_intra_idx().
total
std::size_t EnergyBinLayout::total
Definition at line 48 of file energy_cabana.hpp.
Referenced by EnergyBinLayout().
The documentation for this struct was generated from the following file:
energy_cabana.hpp