ESPResSo: DipolarLayerCorrection Struct Reference
DipolarLayerCorrection Struct Reference
Adapt a magnetostatics solver to remove contributions from the z-direction.
#include <dlc.hpp>
Public Types
using BaseSolver = std::variant< std::shared_ptr< DipolarP3M >, std::shared_ptr< DipolarDirectSum > >
Public Member Functions
DipolarLayerCorrection (dlc_data &&parameters, BaseSolver &&solver)
void on_activation ()
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change () const
void init ()
void sanity_checks () const
void recalc_box_h ()
void recalc_far_cut ()
double long_range_energy () const
Calculate long-range dipolar energy with corrections.
void add_long_range_forces () const
Accumulate long-range dipolar forces with corrections.
double energy_correction () const
Calculate the dipolar energy correction.
void add_force_corrections () const
Add the dipolar force and torque corrections.
void adapt_solver ()
void release_solver ()
Public Member Functions inherited from Dipoles::Actor< DipolarLayerCorrection >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
dlc_data dlc
BaseSolver base_solver
Magnetostatics solver that is adapted.
Variables from the adapted solver.
double prefactor
double epsilon
double epsilon_correction
Public Attributes inherited from Dipoles::Actor< DipolarLayerCorrection >
double prefactor
Magnetostatics prefactor.
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Adapt a magnetostatics solver to remove contributions from the z-direction.
For details see [9].
Definition at line 78 of file dlc.hpp.
Member Typedef Documentation
BaseSolver
using DipolarLayerCorrection::BaseSolver = std::variant< std::shared_ptr<DipolarP3M>, std::shared_ptr<DipolarDirectSum> >
Definition at line 79 of file dlc.hpp.
Constructor & Destructor Documentation
DipolarLayerCorrection()
DipolarLayerCorrection::DipolarLayerCorrection (dlc_data && parameters, BaseSolver && solver)
Definition at line 529 of file dlc.cpp.
References adapt_solver().
Member Function Documentation
adapt_solver()
void DipolarLayerCorrection::adapt_solver ()
Definition at line 490 of file dlc.cpp.
References base_solver, epsilon, epsilon_correction, P3M_EPSILON_METALLIC, and stream.
Referenced by DipolarLayerCorrection().
add_force_corrections()
void DipolarLayerCorrection::add_force_corrections () const
Add the dipolar force and torque corrections.
Definition at line 304 of file dlc.cpp.
References Particle::calc_dip(), calc_slab_dipole(), Particle::dipm(), dipolar_force_corrections(), dlc, epsilon, epsilon_correction, dlc_data::far_cut, Particle::force(), System::Leaf< Class >::get_system(), P3M_EPSILON_METALLIC, prefactor, ParticleRange::size(), stream, Particle::torque(), and vector_product().
Referenced by add_long_range_forces().
add_long_range_forces()
void DipolarLayerCorrection::add_long_range_forces () const
Accumulate long-range dipolar forces with corrections.
Definition at line 535 of file dlc.cpp.
References add_force_corrections(), and base_solver.
energy_correction()
double DipolarLayerCorrection::energy_correction () const
Calculate the dipolar energy correction.
Definition at line 357 of file dlc.cpp.
References calc_slab_dipole(), dipolar_energy_correction(), dlc, epsilon, epsilon_correction, dlc_data::far_cut, System::Leaf< Class >::get_system(), P3M_EPSILON_METALLIC, prefactor, Utils::sqr(), stream, and this_node.
Referenced by long_range_energy().
init()
void DipolarLayerCorrection::init () inline
Definition at line 125 of file dlc.hpp.
References recalc_box_h(), and recalc_far_cut().
long_range_energy()
double DipolarLayerCorrection::long_range_energy () const
Calculate long-range dipolar energy with corrections.
Definition at line 541 of file dlc.cpp.
References base_solver, and energy_correction().
on_activation()
void DipolarLayerCorrection::on_activation () inline
Definition at line 98 of file dlc.hpp.
References System::Leaf< Class >::m_system, recalc_box_h(), and recalc_far_cut().
on_boxl_change()
void DipolarLayerCorrection::on_boxl_change () inline
Recalculate all box-length-dependent parameters.
Definition at line 110 of file dlc.hpp.
References recalc_box_h(), and recalc_far_cut().
on_cell_structure_change()
void DipolarLayerCorrection::on_cell_structure_change () const inline
Definition at line 122 of file dlc.hpp.
on_node_grid_change()
void DipolarLayerCorrection::on_node_grid_change () const inline
Definition at line 115 of file dlc.hpp.
on_periodicity_change()
void DipolarLayerCorrection::on_periodicity_change () const inline
Definition at line 118 of file dlc.hpp.
recalc_box_h()
void DipolarLayerCorrection::recalc_box_h ()
Definition at line 518 of file dlc.cpp.
References dlc_data::box_h, dlc, dlc_data::gap_size, System::Leaf< Class >::get_system(), and stream.
Referenced by init(), on_activation(), and on_boxl_change().
recalc_far_cut()
void DipolarLayerCorrection::recalc_far_cut () inline
Definition at line 137 of file dlc.hpp.
References dlc, dlc_data::far_calculated, and dlc_data::far_cut.
Referenced by init(), on_activation(), and on_boxl_change().
release_solver()
void DipolarLayerCorrection::release_solver () inline
Definition at line 154 of file dlc.hpp.
References epsilon, epsilon_correction, and prefactor.
sanity_checks()
void DipolarLayerCorrection::sanity_checks () const inline
Definition at line 131 of file dlc.hpp.
Member Data Documentation
base_solver
BaseSolver DipolarLayerCorrection::base_solver
Magnetostatics solver that is adapted.
Definition at line 94 of file dlc.hpp.
Referenced by adapt_solver(), add_long_range_forces(), and long_range_energy().
dlc
dlc_data DipolarLayerCorrection::dlc
Definition at line 91 of file dlc.hpp.
Referenced by add_force_corrections(), energy_correction(), recalc_box_h(), and recalc_far_cut().
epsilon
double DipolarLayerCorrection::epsilon
Definition at line 88 of file dlc.hpp.
Referenced by adapt_solver(), add_force_corrections(), energy_correction(), AdaptSolver::operator()(), AdaptSolver::operator()(), and release_solver().
epsilon_correction
double DipolarLayerCorrection::epsilon_correction
Definition at line 89 of file dlc.hpp.
Referenced by adapt_solver(), add_force_corrections(), energy_correction(), and release_solver().
prefactor
double DipolarLayerCorrection::prefactor
Definition at line 87 of file dlc.hpp.
Referenced by add_force_corrections(), energy_correction(), AdaptSolver::operator()(), AdaptSolver::operator()(), and release_solver().
The documentation for this struct was generated from the following files:
dlc.hpp
dlc.cpp