ESPResSo: PairBondsPressureKernel Struct Reference
PairBondsPressureKernel Struct Reference
#include <bond_pressure_kokkos.hpp>
Public Member Functions
PairBondsPressureKernel (BondsPressureKernelData data_, LocalBondState::PairBondlistType bond_list_, LocalBondState::PairBondIDType bond_ids_, Coulomb::ShortRangeForceKernel::kernel_type const *coulomb_f_kernel_)
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION void operator() (std::size_t idx) const
Public Attributes
BondsPressureKernelData data
LocalBondState::PairBondlistType bond_list
LocalBondState::PairBondIDType bond_ids
Coulomb::ShortRangeForceKernel::kernel_type const *const coulomb_f_kernel
Detailed Description
Definition at line 48 of file bond_pressure_kokkos.hpp.
Constructor & Destructor Documentation
PairBondsPressureKernel()
PairBondsPressureKernel::PairBondsPressureKernel (BondsPressureKernelData data_, LocalBondState::PairBondlistType bond_list_, LocalBondState::PairBondIDType bond_ids_, Coulomb::ShortRangeForceKernel::kernel_type const * coulomb_f_kernel_) inline
Definition at line 54 of file bond_pressure_kokkos.hpp.
Member Function Documentation
operator()()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION void PairBondsPressureKernel::operator() (std::size_t idx) const inline
Definition at line 63 of file bond_pressure_kokkos.hpp.
References BondsPressureKernelData::aosoa, bond_broken_error(), bond_ids, bond_list, BondsPressureKernelData::bonded_ias, BondsPressureKernelData::box_geo, calc_bonded_virial_pressure_tensor(), coulomb_f_kernel, data, Utils::flatten(), BondsPressureKernelData::layout, BondsPressureKernelData::local_pressure, and stream.
Member Data Documentation
bond_ids
LocalBondState::PairBondIDType PairBondsPressureKernel::bond_ids
Definition at line 51 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
bond_list
LocalBondState::PairBondlistType PairBondsPressureKernel::bond_list
Definition at line 50 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
coulomb_f_kernel
Coulomb::ShortRangeForceKernel::kernel_type const* const PairBondsPressureKernel::coulomb_f_kernel
Definition at line 52 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
data
BondsPressureKernelData PairBondsPressureKernel::data
Definition at line 49 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
bond_pressure_kokkos.hpp