ESPResSo: MpiContainerUnitTest Struct Reference
MpiContainerUnitTest Struct Reference
#include <communication.hpp>
Public Member Functions
MpiContainerUnitTest (int argc, char **argv)
~MpiContainerUnitTest ()
Public Attributes
std::shared_ptr< boost::mpi::environment > m_mpi_env
Detailed Description
Definition at line 134 of file core/communication.hpp.
Constructor & Destructor Documentation
MpiContainerUnitTest()
MpiContainerUnitTest::MpiContainerUnitTest (int argc, char ** argv) inline
Definition at line 136 of file core/communication.hpp.
References Communication::init(), m_mpi_env, and mpi_init().
~MpiContainerUnitTest()
MpiContainerUnitTest::~MpiContainerUnitTest () inline
Definition at line 140 of file core/communication.hpp.
References Communication::deinit().
Member Data Documentation
m_mpi_env
std::shared_ptr<boost::mpi::environment> MpiContainerUnitTest::m_mpi_env
Definition at line 135 of file core/communication.hpp.
Referenced by MpiContainerUnitTest().
The documentation for this struct was generated from the following file:
core/communication.hpp