ESPResSo: fft_plan Struct Reference
fft_plan Struct Reference
#include <fft.hpp>
Public Attributes
int dir
plan direction: forward or backward FFT (enum value from FFTW).
fftw_plan our_fftw_plan
plan for the FFT.
void(* pack_function)(double const *const, double *const, int const *, int const *, int const *, int)
packing function for send blocks.
Detailed Description
Definition at line 86 of file fft.hpp.
Member Data Documentation
dir
int fft_plan::dir
plan direction: forward or backward FFT (enum value from FFTW).
Definition at line 88 of file fft.hpp.
Referenced by fft_init().
our_fftw_plan
fftw_plan fft_plan::our_fftw_plan
plan for the FFT.
Definition at line 90 of file fft.hpp.
Referenced by fft_init(), fft_perform_back(), and fft_perform_forw().
pack_function
void(* fft_plan::pack_function) (double const *const, double *const, int const *, int const *, int const *, int)
packing function for send blocks.
Definition at line 92 of file fft.hpp.
Referenced by anonymous_namespace{fft.cpp}::back_grid_comm(), fft_init(), and anonymous_namespace{fft.cpp}::forw_grid_comm().
The documentation for this struct was generated from the following file:
fft.hpp