ESPResSo: anonymous_namespace{p3m.cpp}::AssignCharge< cao > Struct Template Reference
anonymous_namespace{p3m.cpp}::AssignCharge< cao > Struct Template Reference
Public Member Functions
void operator() (p3m_data_struct &p3m, double q, Utils::Vector3d const &real_pos, p3m_interpolation_cache &inter_weights)
void operator() (p3m_data_struct &p3m, double q, Utils::Vector3d const &real_pos)
template<typename combined_ranges >
void operator() (p3m_data_struct &p3m, combined_ranges const &p_q_pos_range)
Detailed Description
template<int cao>
struct anonymous_namespace{p3m.cpp}::AssignCharge< cao >
Definition at line 303 of file p3m.cpp.
Member Function Documentation
operator()() [1/3]
template<int cao> template<typename combined_ranges > void anonymous_namespace{p3m.cpp}::AssignCharge< cao >::operator() (p3m_data_struct & p3m, combined_ranges const & p_q_pos_range) inline
Definition at line 327 of file p3m.cpp.
References p3m_data_struct::inter_weights.
operator()() [2/3]
template<int cao> void anonymous_namespace{p3m.cpp}::AssignCharge< cao >::operator() (p3m_data_struct & p3m, double q, Utils::Vector3d const & real_pos) inline
Definition at line 317 of file p3m.cpp.
References P3MParameters::ai, p3m_data_struct::local_mesh, p3m_interpolate(), and p3m_data_struct_base::params.
operator()() [3/3]
template<int cao> void anonymous_namespace{p3m.cpp}::AssignCharge< cao >::operator() (p3m_data_struct & p3m, double q, Utils::Vector3d const & real_pos, p3m_interpolation_cache & inter_weights) inline
Definition at line 304 of file p3m.cpp.
References P3MParameters::ai, p3m_data_struct::local_mesh, p3m_interpolate(), p3m_data_struct_base::params, and p3m_interpolation_cache::store().
The documentation for this struct was generated from the following file:
p3m.cpp