ESPResSo: DebyeHueckel Struct Reference
DebyeHueckel Struct Reference
Debye-Hückel parameters.
#include <debye_hueckel.hpp>
Public Member Functions
DebyeHueckel (double prefactor, double kappa, double r_cut)
void on_activation () const
void on_boxl_change () const
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change () const
void init () const
void sanity_checks () const
Utils::Vector3d pair_force (double const q1q2, Utils::Vector3d const &d, double const dist) const
Compute the pair force.
double pair_energy (double const q1q2, double const dist) const
Compute the pair energy.
Public Member Functions inherited from Coulomb::Actor< DebyeHueckel >
void set_prefactor (double new_prefactor)
void sanity_checks_charge_neutrality () const
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
double kappa
Ionic strength.
double r_cut
Interaction cutoff.
Public Attributes inherited from Coulomb::Actor< DebyeHueckel >
double prefactor
Electrostatics prefactor.
double charge_neutrality_tolerance
Relative tolerance for the charge excess during neutrality checks.
Additional Inherited Members
Static Public Attributes inherited from Coulomb::Actor< DebyeHueckel >
static auto constexpr charge_neutrality_tolerance_default
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Debye-Hückel parameters.
Definition at line 44 of file debye_hueckel.hpp.
Constructor & Destructor Documentation
DebyeHueckel()
DebyeHueckel::DebyeHueckel (double prefactor, double kappa, double r_cut) inline
Definition at line 50 of file debye_hueckel.hpp.
References kappa, Coulomb::Actor< DebyeHueckel >::prefactor, r_cut, and Coulomb::Actor< DebyeHueckel >::set_prefactor().
Member Function Documentation
init()
void DebyeHueckel::init () const inline
Definition at line 68 of file debye_hueckel.hpp.
on_activation()
void DebyeHueckel::on_activation () const inline
Definition at line 63 of file debye_hueckel.hpp.
References sanity_checks().
on_boxl_change()
void DebyeHueckel::on_boxl_change () const inline
Definition at line 64 of file debye_hueckel.hpp.
on_cell_structure_change()
void DebyeHueckel::on_cell_structure_change () const inline
Definition at line 67 of file debye_hueckel.hpp.
on_node_grid_change()
void DebyeHueckel::on_node_grid_change () const inline
Definition at line 65 of file debye_hueckel.hpp.
on_periodicity_change()
void DebyeHueckel::on_periodicity_change () const inline
Definition at line 66 of file debye_hueckel.hpp.
pair_energy()
double DebyeHueckel::pair_energy (double const q1q2, double const dist) const inline
Compute the pair energy.
Parameters
q1q2 Product of the charges on p1 and p2.
dist Distance between p1 and p2.
Definition at line 95 of file debye_hueckel.hpp.
References kappa, Coulomb::Actor< DebyeHueckel >::prefactor, r_cut, and stream.
pair_force()
Utils::Vector3d DebyeHueckel::pair_force (double const q1q2, Utils::Vector3d const & d, double const dist) const inline
Compute the pair force.
Parameters
[in] q1q2 Product of the charges on p1 and p2.
[in] d Vector pointing from p1 to p2.
[in] dist Distance between p1 and p2.
Definition at line 77 of file debye_hueckel.hpp.
References kappa, Coulomb::Actor< DebyeHueckel >::prefactor, r_cut, and stream.
sanity_checks()
void DebyeHueckel::sanity_checks () const inline
Definition at line 70 of file debye_hueckel.hpp.
References Coulomb::Actor< DebyeHueckel >::sanity_checks_charge_neutrality().
Referenced by on_activation().
Member Data Documentation
kappa
double DebyeHueckel::kappa
Ionic strength.
Definition at line 46 of file debye_hueckel.hpp.
Referenced by DebyeHueckel(), pair_energy(), and pair_force().
r_cut
double DebyeHueckel::r_cut
Interaction cutoff.
Definition at line 48 of file debye_hueckel.hpp.
Referenced by DebyeHueckel(), pair_energy(), and pair_force().
The documentation for this struct was generated from the following file:
debye_hueckel.hpp