ESPResSo: GatherParticleTraits< T > Struct Template Reference
GatherParticleTraits< T > Struct Template Reference abstract
Gather particle properties (or any derived quantities) on MPI rank 0.
Public Member Functions
virtual T kernel (Particle const &) const =0
virtual ~GatherParticleTraits ()=default
void fetch (CellStructure const &cell_structure, int pid)
auto join ()
Detailed Description
template<typename T>
struct GatherParticleTraits< T >
Gather particle properties (or any derived quantities) on MPI rank 0.
The data is collected into an unordered map.
Definition at line 50 of file statistics_chain.cpp.
Constructor & Destructor Documentation
~GatherParticleTraits()
template<typename T > virtual GatherParticleTraits< T >::~GatherParticleTraits () virtual default
Member Function Documentation
fetch()
template<typename T > void GatherParticleTraits< T >::fetch (CellStructure const & cell_structure, int pid) inline
Definition at line 59 of file statistics_chain.cpp.
References CellStructure::get_local_particle(), GatherParticleTraits< T >::kernel(), and stream.
Referenced by calc_re(), and calc_rh().
join()
template<typename T > auto GatherParticleTraits< T >::join () inline
Definition at line 67 of file statistics_chain.cpp.
References comm_cart, Utils::Mpi::gather_buffer(), and stream.
kernel()
template<typename T > virtual T GatherParticleTraits< T >::kernel (Particle const &) const pure virtual
Implemented in GatherPos, GatherCom, and GatherMass.
Referenced by GatherParticleTraits< T >::fetch().
The documentation for this struct was generated from the following file:
statistics_chain.cpp