ESPResSo: CellStructure Struct Reference
CellStructure Struct Reference
Describes a cell structure / cell system.
#include <CellStructure.hpp>
Public Member Functions
CellStructure (BoxGeometry const &box)
void update_particle_index (int id, Particle *p)
Update local particle index.
void update_particle_index (Particle &p)
Update local particle index.
void update_particle_index (ParticleList &pl)
Update local particle index.
void clear_particle_index ()
Clear the particles index.
Particle * get_local_particle (int id)
Get a local particle by id.
const Particle * get_local_particle (int id) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
template<class InputRange , class OutputIterator >
void get_local_particles (InputRange ids, OutputIterator out)
CellStructureType decomposition_type () const
Utils::Vector3d max_cutoff () const
Maximal cutoff supported by current cell system.
Utils::Vector3d max_range () const
Maximal pair range supported by current cell system.
ParticleRange local_particles () const
ParticleRange ghost_particles () const
Particle * add_particle (Particle &&p)
Add a particle.
Particle * add_local_particle (Particle &&p)
Add a particle.
void remove_particle (int id)
Remove a particle.
int get_max_local_particle_id () const
Get the maximal particle id on this node.
void remove_all_particles ()
Remove all particles from the cell system.
ParticleDecomposition const & decomposition () const
Get the underlying particle decomposition.
void set_resort_particles (Cells::Resort level)
Increase the local resort level at least to level.
unsigned get_resort_particles () const
Get the currently scheduled resort level.
void clear_resort_particles ()
Set the resort level to sorted.
bool check_resort_required (Utils::Vector3d const &additional_offset={}) const
Check whether a particle has moved further than half the skin since the last Verlet list update, thus requiring a resort.
auto get_le_pos_offset_at_last_resort () const
void ghosts_count ()
Synchronize number of ghosts.
void ghosts_update (unsigned data_parts)
Update ghost particles.
void update_ghosts_and_resort_particle (unsigned data_parts)
Update ghost particles, with particle resort if needed.
void ghosts_reduce_forces ()
Add forces from ghost particles to real particles.
void ghosts_reduce_rattle_correction ()
Add rattle corrections from ghost particles to real particles.
void resort_particles (bool global_flag)
Resort particles.
auto is_verlet_skin_set () const
Whether the Verlet skin is set.
auto get_verlet_skin () const
Get the Verlet skin.
void set_verlet_skin (double value)
Set the Verlet skin.
void set_verlet_skin_heuristic ()
Set the Verlet skin using a heuristic.
void update_verlet_stats (int n_steps, int n_verlet_updates)
auto get_verlet_reuse () const
Average number of integration steps the Verlet list was re-used.
void set_atom_decomposition ()
Set the particle decomposition to AtomDecomposition.
void set_regular_decomposition (double range, std::optional< std::pair< int, int > > fully_connected_boundary)
Set the particle decomposition to RegularDecomposition.
void set_hybrid_decomposition (double cutoff_regular, std::set< int > n_square_types)
Set the particle decomposition to HybridDecomposition.
template<class BondKernel >
void bond_loop (BondKernel const &bond_kernel)
Bonded pair loop.
template<class PairKernel >
void non_bonded_loop (PairKernel pair_kernel)
Non-bonded pair loop.
template<class PairKernel , class VerletCriterion >
void non_bonded_loop (PairKernel pair_kernel, const VerletCriterion &verlet_criterion)
Non-bonded pair loop with potential use of verlet lists.
void check_particle_index () const
Check that particle index is commensurate with particles.
void check_particle_sorting () const
Check that particles are in the correct cell.
Cell * find_current_cell (const Particle &p)
Find cell a particle is stored in.
template<class Kernel >
bool run_on_particle_short_range_neighbors (Particle const &p, Kernel &kernel)
Run kernel on all particles inside local cell and its neighbors.
Public Member Functions inherited from System::Leaf< CellStructure >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
bool use_verlet_list = true
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< CellStructure >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< CellStructure >
std::weak_ptr< System > m_system
Detailed Description
Describes a cell structure / cell system.
Contains information about the communication of cell contents (particles, ghosts, ...) between different nodes and the relation between particle positions and the cell system. All other properties of the cell system which are not common between different cell systems have to be stored in separate structures.
Definition at line 134 of file CellStructure.hpp.
Constructor & Destructor Documentation
CellStructure()
CellStructure::CellStructure (BoxGeometry const & box)
Definition at line 54 of file CellStructure.cpp.
Member Function Documentation
add_local_particle()
Particle * CellStructure::add_local_particle (Particle && p)
Add a particle.
Moves a particle into the cell system, if it belongs to this node. Otherwise this does not have an effect and the particle is discarded. This can be used to add a particle without knowledge where it should be placed by calling the function on all nodes, it will then add the particle in exactly one place.
Parameters
p Particle to add.
Returns
Pointer to particle if it is local, null otherwise.
Definition at line 128 of file CellStructure.cpp.
add_particle()
Particle * CellStructure::add_particle (Particle && p)
Add a particle.
Moves a particle into the cell system. This adds a particle to the local node, irrespective of where it belongs.
Parameters
p Particle to add.
Returns
Pointer to the particle in the cell system.
Definition at line 139 of file CellStructure.cpp.
References decomposition(), ParticleDecomposition::local_cells(), Cells::RESORT_GLOBAL, Cells::RESORT_LOCAL, and set_resort_particles().
Referenced by Mpiio::mpi_mpiio_common_read(), and CollisionDetection::place_vs_and_relate_to_particle().
bond_loop()
template<class BondKernel > void CellStructure::bond_loop (BondKernel const & bond_kernel) inline
Bonded pair loop.
Parameters
bond_kernel Kernel to apply
Definition at line 652 of file CellStructure.hpp.
References local_particles().
Referenced by add_oif_global_forces(), calc_oif_mesh(), and compute_correction_vector().
check_particle_index()
void CellStructure::check_particle_index () const
Check that particle index is commensurate with particles.
For each local particles is checked that has a correct entry in the particles index, and that there are no excess (non-existing) particles in the index.
Definition at line 57 of file CellStructure.cpp.
References get_local_particle(), get_max_local_particle_id(), Particle::id(), and local_particles().
Referenced by resort_particles().
check_particle_sorting()
void CellStructure::check_particle_sorting () const
Check that particles are in the correct cell.
This checks for all local particles that the result of particles_to_cell is the cell the particles is actually in, e.g. that the particles are sorted according to particles_to_cell.
Definition at line 90 of file CellStructure.cpp.
References decomposition(), and ParticleDecomposition::local_cells().
Referenced by resort_particles().
check_resort_required()
bool CellStructure::check_resort_required (Utils::Vector3d const & additional_offset = {}) const inline
Check whether a particle has moved further than half the skin since the last Verlet list update, thus requiring a resort.
Parameters
additional_offset Offset which is added to the distance the particle has travelled when comparing to half the Verlet skin (e.g., for Lees-Edwards BC).
Returns
Whether a resort is needed.
Definition at line 394 of file CellStructure.hpp.
Referenced by correct_position_shake(), and vs_relative_update_particles().
clear_particle_index()
void CellStructure::clear_particle_index () inline
Clear the particles index.
Definition at line 204 of file CellStructure.hpp.
clear_resort_particles()
void CellStructure::clear_resort_particles () inline
Set the resort level to sorted.
Definition at line 383 of file CellStructure.hpp.
References Cells::RESORT_NONE.
Referenced by update_ghosts_and_resort_particle().
decomposition()
ParticleDecomposition const & CellStructure::decomposition () const inline
Get the underlying particle decomposition.
Should be used solely for informative purposes.
Returns
The active particle decomposition.
Definition at line 357 of file CellStructure.hpp.
Referenced by add_particle(), check_particle_sorting(), ghost_particles(), ghosts_count(), ghosts_reduce_forces(), ghosts_reduce_rattle_correction(), ghosts_update(), local_particles(), max_cutoff(), max_range(), remove_all_particles(), remove_particle(), and run_on_particle_short_range_neighbors().
decomposition_type()
CellStructureType CellStructure::decomposition_type () const inline
Definition at line 262 of file CellStructure.hpp.
find_current_cell()
Cell * CellStructure::find_current_cell (const Particle & p) inline
Find cell a particle is stored in.
For local particles, this returns the cell they are stored in, otherwise nullptr is returned.
Parameters
p Particle to find cell for
Returns
Cell for particle or nullptr.
Definition at line 710 of file CellStructure.hpp.
References get_resort_particles(), and Particle::is_ghost().
Referenced by run_on_particle_short_range_neighbors().
get_le_pos_offset_at_last_resort()
auto CellStructure::get_le_pos_offset_at_last_resort () const inline
Definition at line 403 of file CellStructure.hpp.
get_local_particle() [1/2]
Particle * CellStructure::get_local_particle (int id) inline
Get a local particle by id.
Parameters
id Particle to get.
Returns
Pointer to particle if it is local, nullptr otherwise.
Definition at line 237 of file CellStructure.hpp.
Referenced by BondBreakage::actions_for_breakage(), CollisionDetection::add_bind_centers(), check_particle_index(), ScriptInterface::Analysis::check_topology(), GatherParticleTraits< T >::fetch(), get_ibm_particle_position(), get_local_particles(), CollisionDetection::get_part(), ScriptInterface::Particles::get_real_particle(), get_reference_particle(), ScriptInterface::Particles::local_add_exclusion(), ScriptInterface::Particles::local_remove_exclusion(), BondBreakage::execute::operator()(), BondBreakage::execute::operator()(), BondBreakage::execute::operator()(), update_ghosts_and_resort_particle(), and vs_relative_pressure_tensor().
get_local_particle() [2/2]
const Particle * CellStructure::get_local_particle (int id) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 247 of file CellStructure.hpp.
get_local_particles()
template<class InputRange , class OutputIterator > void CellStructure::get_local_particles (InputRange ids, OutputIterator out) inline
Definition at line 257 of file CellStructure.hpp.
References get_local_particle().
get_max_local_particle_id()
int CellStructure::get_max_local_particle_id () const
Get the maximal particle id on this node.
This returns the highest particle id on this node, or -1 if there are no particles on this node.
Definition at line 153 of file CellStructure.cpp.
Referenced by check_particle_index().
get_resort_particles()
unsigned CellStructure::get_resort_particles () const inline
Get the currently scheduled resort level.
Definition at line 378 of file CellStructure.hpp.
Referenced by find_current_cell().
get_verlet_reuse()
auto CellStructure::get_verlet_reuse () const inline
Average number of integration steps the Verlet list was re-used.
Definition at line 471 of file CellStructure.hpp.
get_verlet_skin()
auto CellStructure::get_verlet_skin () const inline
Get the Verlet skin.
Definition at line 454 of file CellStructure.hpp.
Referenced by lb_tracers_propagate().
ghost_particles()
ParticleRange CellStructure::ghost_particles () const inline
Definition at line 274 of file CellStructure.hpp.
References decomposition(), and Cells::particles().
Referenced by correct_position_shake(), correct_velocity_shake(), lb_tracers_add_particle_force_to_fluid(), update_ghosts_and_resort_particle(), and vs_relative_back_transfer_forces_and_torques().
ghosts_count()
void CellStructure::ghosts_count ()
Synchronize number of ghosts.
Definition at line 186 of file CellStructure.cpp.
References decomposition(), System::Leaf< CellStructure >::get_system(), ghost_communicator(), and GHOSTTRANS_PARTNUM.
Referenced by update_ghosts_and_resort_particle().
ghosts_reduce_forces()
void CellStructure::ghosts_reduce_forces ()
Add forces from ghost particles to real particles.
Definition at line 194 of file CellStructure.cpp.
References decomposition(), System::Leaf< CellStructure >::get_system(), ghost_communicator(), and GHOSTTRANS_FORCE.
Referenced by ICCStar::iteration(), and vs_relative_back_transfer_forces_and_torques().
ghosts_reduce_rattle_correction()
void CellStructure::ghosts_reduce_rattle_correction ()
Add rattle corrections from ghost particles to real particles.
Definition at line 199 of file CellStructure.cpp.
References decomposition(), System::Leaf< CellStructure >::get_system(), ghost_communicator(), and GHOSTTRANS_RATTLE.
Referenced by correct_position_shake(), and correct_velocity_shake().
ghosts_update()
void CellStructure::ghosts_update (unsigned data_parts)
Update ghost particles.
Update ghost particles with data from the real particles.
Parameters
data_parts Particle parts to update, combination of Cells::DataPart
Definition at line 190 of file CellStructure.cpp.
References decomposition(), System::Leaf< CellStructure >::get_system(), ghost_communicator(), and map_data_parts().
Referenced by correct_position_shake(), correct_velocity_shake(), ICCStar::iteration(), update_ghosts_and_resort_particle(), and vs_relative_update_particles().
is_verlet_skin_set()
auto CellStructure::is_verlet_skin_set () const inline
Whether the Verlet skin is set.
Definition at line 451 of file CellStructure.hpp.
Referenced by set_verlet_skin_heuristic().
local_particles()
ParticleRange CellStructure::local_particles () const inline
Definition at line 270 of file CellStructure.hpp.
References decomposition(), and Cells::particles().
Referenced by bond_loop(), calc_total_charge(), check_particle_index(), correct_position_shake(), correct_velocity_shake(), lb_tracers_add_particle_force_to_fluid(), lb_tracers_propagate(), ScriptInterface::System::rescale_particles(), ScriptInterface::System::rotate_system(), vs_relative_back_transfer_forces_and_torques(), vs_relative_pressure_tensor(), and vs_relative_update_particles().
max_cutoff()
Utils::Vector3d CellStructure::max_cutoff () const inline
Maximal cutoff supported by current cell system.
Definition at line 265 of file CellStructure.hpp.
References decomposition(), and ParticleDecomposition::max_cutoff().
Referenced by set_verlet_skin_heuristic().
max_range()
Utils::Vector3d CellStructure::max_range () const inline
Maximal pair range supported by current cell system.
Definition at line 268 of file CellStructure.hpp.
References decomposition(), and ParticleDecomposition::max_range().
Referenced by set_verlet_skin_heuristic().
non_bonded_loop() [1/2]
template<class PairKernel > void CellStructure::non_bonded_loop (PairKernel pair_kernel) inline
Non-bonded pair loop.
Parameters
pair_kernel Kernel to apply
Definition at line 661 of file CellStructure.hpp.
Referenced by force_calc_icc().
non_bonded_loop() [2/2]
template<class PairKernel , class VerletCriterion > void CellStructure::non_bonded_loop (PairKernel pair_kernel, const VerletCriterion & verlet_criterion) inline
Non-bonded pair loop with potential use of verlet lists.
Parameters
pair_kernel Kernel to apply
verlet_criterion Filter for verlet lists.
Definition at line 671 of file CellStructure.hpp.
References use_verlet_list.
remove_all_particles()
void CellStructure::remove_all_particles ()
Remove all particles from the cell system.
This allows linear time removal of all particles from the system, removing each particle individually would be quadratic.
Definition at line 160 of file CellStructure.cpp.
References decomposition(), and ParticleDecomposition::local_cells().
Referenced by Mpiio::mpi_mpiio_common_read().
remove_particle()
void CellStructure::remove_particle (int id)
Remove a particle.
Removes a particle and all bonds pointing to it. This is a collective call.
Parameters
id Id of particle to remove.
Definition at line 101 of file CellStructure.cpp.
References Utils::contains(), decomposition(), ParticleDecomposition::local_cells(), and update_particle_index().
resort_particles()
void CellStructure::resort_particles (bool global_flag)
Resort particles.
Definition at line 219 of file CellStructure.cpp.
References check_particle_index(), check_particle_sorting(), and System::Leaf< CellStructure >::get_system().
Referenced by update_ghosts_and_resort_particle().
run_on_particle_short_range_neighbors()
template<class Kernel > bool CellStructure::run_on_particle_short_range_neighbors (Particle const & p, Kernel & kernel) inline
Run kernel on all particles inside local cell and its neighbors.
Parameters
p Particle to find cell for
kernel Function with signature double(Particle const&, Particle const&, Utils::Vector3d const&)
Returns
false if cell is not found, otherwise true
Definition at line 729 of file CellStructure.hpp.
References ParticleDecomposition::box(), decomposition(), find_current_cell(), and ParticleDecomposition::minimum_image_distance().
set_atom_decomposition()
void CellStructure::set_atom_decomposition ()
Set the particle decomposition to AtomDecomposition.
Definition at line 241 of file CellStructure.cpp.
References comm_cart, System::Leaf< CellStructure >::get_system(), and NSQUARE.
set_hybrid_decomposition()
void CellStructure::set_hybrid_decomposition (double cutoff_regular, std::set< int > n_square_types)
Set the particle decomposition to HybridDecomposition.
Parameters
cutoff_regular Interaction cutoff_regular.
n_square_types Particle types to put into n_square decomposition.
Definition at line 264 of file CellStructure.cpp.
References comm_cart, System::Leaf< CellStructure >::get_system(), and HYBRID.
set_regular_decomposition()
void CellStructure::set_regular_decomposition (double range, std::optional< std::pair< int, int > > fully_connected_boundary)
Set the particle decomposition to RegularDecomposition.
Parameters
range Interaction range.
fully_connected_boundary neighbor cell directions for Lees-Edwards.
Definition at line 252 of file CellStructure.cpp.
References comm_cart, System::Leaf< CellStructure >::get_system(), and REGULAR.
set_resort_particles()
void CellStructure::set_resort_particles (Cells::Resort level) inline
Increase the local resort level at least to level.
Definition at line 370 of file CellStructure.hpp.
Referenced by add_particle(), correct_position_shake(), lb_tracers_propagate(), ScriptInterface::System::rotate_system(), and vs_relative_update_particles().
set_verlet_skin()
void CellStructure::set_verlet_skin (double value)
Set the Verlet skin.
Definition at line 278 of file CellStructure.cpp.
References System::Leaf< CellStructure >::get_system().
Referenced by set_verlet_skin_heuristic().
set_verlet_skin_heuristic()
void CellStructure::set_verlet_skin_heuristic ()
Set the Verlet skin using a heuristic.
Definition at line 285 of file CellStructure.cpp.
References System::Leaf< CellStructure >::get_system(), is_verlet_skin_set(), max_cutoff(), max_range(), and set_verlet_skin().
update_ghosts_and_resort_particle()
void CellStructure::update_ghosts_and_resort_particle (unsigned data_parts)
Update ghost particles, with particle resort if needed.
Update ghost particles with data from the real particles. Resort particles if a resort is due.
Parameters
data_parts Particle parts to update, combination of Cells::DataPart
Definition at line 299 of file CellStructure.cpp.
References clear_resort_particles(), comm_cart, Cells::DATA_PART_BONDS, Cells::DATA_PART_PROPERTIES, get_local_particle(), ghost_particles(), ghosts_count(), ghosts_update(), Cells::RESORT_GLOBAL, Cells::RESORT_NONE, resort_particles(), and update_particle_index().
Referenced by correct_position_shake(), lb_tracers_add_particle_force_to_fluid(), and ScriptInterface::System::rotate_system().
update_particle_index() [1/3]
void CellStructure::update_particle_index (int id, Particle * p) inline
Update local particle index.
Update the entry for a particle in the local particle index.
Parameters
id Entry to update.
p Pointer to the particle.
Definition at line 167 of file CellStructure.hpp.
References Particle::id().
Referenced by anonymous_namespace{CellStructure.cpp}::UpdateParticleIndexVisitor::operator()(), anonymous_namespace{CellStructure.cpp}::UpdateParticleIndexVisitor::operator()(), remove_particle(), update_ghosts_and_resort_particle(), update_particle_index(), and update_particle_index().
update_particle_index() [2/3]
void CellStructure::update_particle_index (Particle & p) inline
Update local particle index.
Update the entry for a particle in the local particle index.
Parameters
p Pointer to the particle.
Definition at line 186 of file CellStructure.hpp.
References Particle::id(), and update_particle_index().
update_particle_index() [3/3]
void CellStructure::update_particle_index (ParticleList & pl) inline
Update local particle index.
Parameters
pl List of particles whose index entries should be updated.
Definition at line 195 of file CellStructure.hpp.
References update_particle_index().
update_verlet_stats()
void CellStructure::update_verlet_stats (int n_steps, int n_verlet_updates) inline
Definition at line 462 of file CellStructure.hpp.
Member Data Documentation
use_verlet_list
bool CellStructure::use_verlet_list = true
Definition at line 156 of file CellStructure.hpp.
Referenced by non_bonded_loop().
The documentation for this struct was generated from the following files:
CellStructure.hpp
CellStructure.cpp