ESPResSo: LangevinThermostat Struct Reference
LangevinThermostat Struct Reference
Thermostat for Langevin dynamics.
#include <thermostat.hpp>
Public Member Functions
void recalc_prefactors (double kT, double time_step)
Recalculate prefactors.
Public Member Functions inherited from BaseThermostat
void rng_initialize (uint32_t const seed)
Initialize or re-initialize the RNG counter with a seed.
void rng_increment ()
Increment the RNG counter.
uint64_t rng_counter () const
Get current value of the RNG.
void set_rng_counter (uint64_t value)
bool is_seed_required () const
Is the RNG seed required.
uint32_t rng_seed () const
Static Public Member Functions
static GammaType sigma (double kT, double time_step, GammaType const &gamma)
Calculate the noise prefactor.
Public Attributes
Parameters
GammaType gamma = sentinel(GammaType{})
Translational friction coefficient \(\gamma_{\text{trans}} \).
GammaType gamma_rotation = sentinel(GammaType{})
Rotational friction coefficient \(\gamma_{\text{rot}} \).
Prefactors
GammaType pref_friction
Prefactor for the friction.
GammaType pref_noise
Prefactor for the translational velocity noise.
GammaType pref_noise_rotation
Prefactor for the angular velocity noise.
Detailed Description
Thermostat for Langevin dynamics.
Definition at line 115 of file thermostat.hpp.
Member Function Documentation
recalc_prefactors()
void LangevinThermostat::recalc_prefactors (double kT, double time_step) inline
Recalculate prefactors.
Needs to be called every time the parameters are changed.
Definition at line 123 of file thermostat.hpp.
References gamma, gamma_rotation, pref_friction, pref_noise, pref_noise_rotation, sigma(), and time_step.
Referenced by thermo_init().
sigma()
static GammaType LangevinThermostat::sigma (double kT, double time_step, GammaType const & gamma) inline static
Calculate the noise prefactor.
Evaluates the quantity \(\sqrt{2 k_B T \gamma / dt} / \sigma_\eta \) with \(\sigma_\eta \) the standard deviation of the random uniform process \(\eta(t) \).
Definition at line 137 of file thermostat.hpp.
References gamma, Utils::sqrt(), and time_step.
Referenced by friction_thermo_langevin(), friction_thermo_langevin_rotation(), and recalc_prefactors().
Member Data Documentation
gamma
GammaType LangevinThermostat::gamma = sentinel(GammaType{})
Translational friction coefficient \(\gamma_{\text{trans}} \).
Definition at line 145 of file thermostat.hpp.
Referenced by friction_thermo_langevin(), mpi_set_langevin_gamma_local(), recalc_prefactors(), and sigma().
gamma_rotation
GammaType LangevinThermostat::gamma_rotation = sentinel(GammaType{})
Rotational friction coefficient \(\gamma_{\text{rot}} \).
Definition at line 147 of file thermostat.hpp.
Referenced by friction_thermo_langevin_rotation(), mpi_set_langevin_gamma_rot_local(), and recalc_prefactors().
pref_friction
GammaType LangevinThermostat::pref_friction
Prefactor for the friction.
Stores \(\gamma_{\text{trans}} \).
Definition at line 154 of file thermostat.hpp.
Referenced by friction_thermo_langevin(), and recalc_prefactors().
pref_noise
GammaType LangevinThermostat::pref_noise
Prefactor for the translational velocity noise.
Stores \(\sqrt{2 k_B T \gamma_{\text{trans}} / dt} / \sigma_\eta \).
Definition at line 158 of file thermostat.hpp.
Referenced by friction_thermo_langevin(), and recalc_prefactors().
pref_noise_rotation
GammaType LangevinThermostat::pref_noise_rotation
Prefactor for the angular velocity noise.
Stores \(\sqrt{2 k_B T \gamma_{\text{rot}} / dt} / \sigma_\eta \).
Definition at line 162 of file thermostat.hpp.
Referenced by friction_thermo_langevin_rotation(), and recalc_prefactors().
The documentation for this struct was generated from the following file:
thermostat.hpp