ESPResSo: DihedralBondsPressureKernel Struct Reference
DihedralBondsPressureKernel Struct Reference
#include <bond_pressure_kokkos.hpp>
Public Member Functions
DihedralBondsPressureKernel (BondsPressureKernelData data_, LocalBondState::DihedralBondlistType bond_list_, LocalBondState::DihedralBondIDType bond_ids_)
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION void operator() (std::size_t idx) const
Public Attributes
BondsPressureKernelData data
LocalBondState::DihedralBondlistType bond_list
LocalBondState::DihedralBondIDType bond_ids
Detailed Description
Definition at line 155 of file bond_pressure_kokkos.hpp.
Constructor & Destructor Documentation
DihedralBondsPressureKernel()
DihedralBondsPressureKernel::DihedralBondsPressureKernel (BondsPressureKernelData data_, LocalBondState::DihedralBondlistType bond_list_, LocalBondState::DihedralBondIDType bond_ids_) inline
Definition at line 160 of file bond_pressure_kokkos.hpp.
Member Function Documentation
operator()()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION void DihedralBondsPressureKernel::operator() (std::size_t idx) const inline
Definition at line 167 of file bond_pressure_kokkos.hpp.
References BondsPressureKernelData::aosoa, bond_broken_error(), bond_ids, bond_list, BondsPressureKernelData::bonded_ias, BondsPressureKernelData::box_geo, calc_bonded_four_body_pressure_tensor(), data, Utils::flatten(), BondsPressureKernelData::layout, BondsPressureKernelData::local_pressure, and stream.
Member Data Documentation
bond_ids
LocalBondState::DihedralBondIDType DihedralBondsPressureKernel::bond_ids
Definition at line 158 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
bond_list
LocalBondState::DihedralBondlistType DihedralBondsPressureKernel::bond_list
Definition at line 157 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
data
BondsPressureKernelData DihedralBondsPressureKernel::data
Definition at line 156 of file bond_pressure_kokkos.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
bond_pressure_kokkos.hpp