ESPResSo: ScriptInterface::Scafacos::ConvertToStringVector Struct Reference
ScriptInterface::Scafacos::ConvertToStringVector Struct Reference
Public Member Functions
auto operator() (std::string const &value) const
template<typename T , typename = std::enable_if_t<!std::is_arithmetic_v<T>>>
result_type operator() (T const &) const
template<typename T , typename = std::enable_if_t<std::is_same_v<T, int>>>
auto operator() (T const &value) const
auto operator() (double const &value) const
auto operator() (result_type const &values) const
auto operator() (std::vector< Variant > const &values) const
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>>
auto operator() (std::vector< T > const &values) const
Detailed Description
Definition at line 53 of file scafacos.cpp.
Member Function Documentation
operator()() [1/7]
auto ScriptInterface::Scafacos::ConvertToStringVector::operator() (double const & value) const inline
Definition at line 67 of file scafacos.cpp.
References operator()().
operator()() [2/7]
auto ScriptInterface::Scafacos::ConvertToStringVector::operator() (result_type const & values) const inline
Definition at line 71 of file scafacos.cpp.
References ScriptInterface::get_value().
operator()() [3/7]
auto ScriptInterface::Scafacos::ConvertToStringVector::operator() (std::string const & value) const inline
Definition at line 55 of file scafacos.cpp.
Referenced by operator()(), and operator()().
operator()() [4/7]
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>> auto ScriptInterface::Scafacos::ConvertToStringVector::operator() (std::vector< T > const & values) const inline
Definition at line 82 of file scafacos.cpp.
References ScriptInterface::get_value().
operator()() [5/7]
auto ScriptInterface::Scafacos::ConvertToStringVector::operator() (std::vector< Variant > const & values) const inline
Definition at line 73 of file scafacos.cpp.
References ScriptInterface::get_value().
operator()() [6/7]
template<typename T , typename = std::enable_if_t<!std::is_arithmetic_v<T>>> result_type ScriptInterface::Scafacos::ConvertToStringVector::operator() (T const &) const inline
Definition at line 58 of file scafacos.cpp.
operator()() [7/7]
template<typename T , typename = std::enable_if_t<std::is_same_v<T, int>>> auto ScriptInterface::Scafacos::ConvertToStringVector::operator() (T const & value) const inline
Definition at line 63 of file scafacos.cpp.
References operator()().
The documentation for this struct was generated from the following file:
scafacos.cpp