ESPResSo: ICCStar Struct Reference
ICCStar Struct Reference
#include <icc.hpp>
Public Member Functions
ICCStar (icc_data data)
void iteration ()
The main iterative scheme, where the surface element charges are calculated self-consistently.
void on_activation () const
void sanity_checks_active_solver () const
void sanity_check () const
Public Member Functions inherited from System::Leaf< ICCStar >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
icc_data icc_cfg
ICC parameters.
Additional Inherited Members
Protected Member Functions inherited from System::Leaf< ICCStar >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< ICCStar >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 88 of file icc.hpp.
Constructor & Destructor Documentation
ICCStar()
ICCStar::ICCStar (icc_data data)
Definition at line 265 of file icc.cpp.
References icc_cfg, and icc_data::sanity_checks().
Member Function Documentation
iteration()
void ICCStar::iteration ()
The main iterative scheme, where the surface element charges are calculated self-consistently.
Definition at line 104 of file icc.cpp.
References icc_data::areas, icc_data::citeration, comm_cart, icc_data::convergence, Cells::DATA_PART_PROPERTIES, icc_data::eps_out, icc_data::epsilons, icc_data::ext_field, icc_data::first_id, force_calc_icc(), System::Leaf< ICCStar >::get_system(), icc_cfg, icc_data::max_iterations, icc_data::n_icc, icc_data::normals, icc_data::relaxation, runtimeErrorMsg, sanity_check(), icc_data::sigmas, stream, and update_aosoa_charges().
on_activation()
void ICCStar::on_activation () const
Definition at line 270 of file icc.cpp.
References System::Leaf< ICCStar >::get_system(), sanity_check(), and stream.
sanity_check()
void ICCStar::sanity_check () const
Definition at line 302 of file icc.cpp.
References System::Leaf< ICCStar >::get_system(), and sanity_checks_active_solver().
Referenced by iteration(), and on_activation().
sanity_checks_active_solver()
void ICCStar::sanity_checks_active_solver () const
Definition at line 311 of file icc.cpp.
References System::Leaf< ICCStar >::get_system(), and stream.
Referenced by sanity_check().
Member Data Documentation
icc_cfg
icc_data ICCStar::icc_cfg
ICC parameters.
Definition at line 90 of file icc.hpp.
Referenced by ICCStar(), and iteration().
The documentation for this struct was generated from the following files:
icc.hpp
icc.cpp