ESPResSo: CoulombP3MGPU Struct Reference
CoulombP3MGPU Struct Reference
#include <p3m_gpu.hpp>
Public Member Functions
void init ()
void on_activation ()
void add_long_range_forces (ParticleRange const &)
void request_gpu () const
CoulombP3M (P3MParameters &&parameters, double prefactor, int tune_timings, bool tune_verbose, bool check_complex_residuals)
Public Member Functions inherited from CoulombP3M
CoulombP3M (P3MParameters &&parameters, double prefactor, int tune_timings, bool tune_verbose, bool check_complex_residuals)
bool is_tuned () const
void init ()
Recalculate all derived parameters.
void on_activation ()
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
void sanity_checks () const
void count_charged_particles ()
Count the number of charged particles and calculate the sum of the squared charges.
void tune ()
Tune P3M parameters to desired accuracy.
void charge_assign (ParticleRange const &particles)
Assign the physical charges using the tabulated charge assignment function.
void assign_charge (double q, Utils::Vector3d const &real_pos, p3m_interpolation_cache &inter_weights)
Assign a single charge into the current charge grid.
void assign_charge (double q, Utils::Vector3d const &real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Utils::Vector3d pair_force (double q1q2, Utils::Vector3d const &d, double dist) const
Calculate real-space contribution of p3m Coulomb pair forces.
double pair_energy (double q1q2, double dist) const
Calculate real-space contribution of Coulomb pair energy.
Utils::Vector9d long_range_pressure (ParticleRange const &particles)
Compute the k-space part of the pressure tensor.
double long_range_energy (ParticleRange const &particles)
Compute the k-space part of energies.
void add_long_range_forces (ParticleRange const &particles)
Compute the k-space part of forces.
double long_range_kernel (bool force_flag, bool energy_flag, ParticleRange const &particles)
Compute the k-space part of forces and energies.
Public Member Functions inherited from Coulomb::Actor< CoulombP3M >
void set_prefactor (double new_prefactor)
void sanity_checks_charge_neutrality () const
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Additional Inherited Members
Public Attributes inherited from CoulombP3M
p3m_data_struct p3m
P3M parameters.
int tune_timings
bool tune_verbose
bool check_complex_residuals
Public Attributes inherited from Coulomb::Actor< CoulombP3M >
double prefactor
Electrostatics prefactor.
double charge_neutrality_tolerance
Relative tolerance for the charge excess during neutrality checks.
Static Public Attributes inherited from Coulomb::Actor< CoulombP3M >
static constexpr auto charge_neutrality_tolerance_default
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Definition at line 40 of file p3m_gpu.hpp.
Member Function Documentation
add_long_range_forces()
void CoulombP3MGPU::add_long_range_forces (ParticleRange const & particles)
Definition at line 52 of file p3m_gpu.cpp.
References get_n_part_safe(), System::Leaf< Class >::get_system(), INTEG_METHOD_NPT_ISO, CoulombP3M::long_range_energy(), npt_add_virial_contribution(), p3m_gpu_add_farfield_force(), Cells::particles(), Coulomb::Actor< CoulombP3M >::prefactor, and this_node.
CoulombP3M()
CoulombP3M::CoulombP3M
Definition at line 97 of file p3m.cpp.
init()
void CoulombP3MGPU::init ()
Definition at line 68 of file p3m_gpu.cpp.
References P3MParameters::alpha, P3MParameters::cao, Utils::Array< T, N >::data(), get_n_part_safe(), System::Leaf< Class >::get_system(), P3MParameters::mesh, CoulombP3M::p3m, p3m_gpu_init(), and p3m_data_struct_base::params.
on_activation()
void CoulombP3MGPU::on_activation () inline
Definition at line 44 of file p3m_gpu.hpp.
References CoulombP3M::is_tuned(), CoulombP3M::on_activation(), and request_gpu().
request_gpu()
void CoulombP3MGPU::request_gpu () const
Definition at line 81 of file p3m_gpu.cpp.
References GpuParticleData::prop::force, System::Leaf< Class >::get_system(), GpuParticleData::prop::pos, and GpuParticleData::prop::q.
Referenced by on_activation().
The documentation for this struct was generated from the following files:
p3m_gpu.hpp
p3m_gpu.cpp