ESPResSo: CoulombP3M Struct Reference
CoulombP3M Struct Reference
P3M solver.
#include <p3m.hpp>
Public Member Functions
CoulombP3M (P3MParameters &&parameters, double prefactor, int tune_timings, bool tune_verbose, bool check_complex_residuals)
bool is_tuned () const
void init ()
Recalculate all derived parameters.
void on_activation ()
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
void sanity_checks () const
void count_charged_particles ()
Count the number of charged particles and calculate the sum of the squared charges.
void tune ()
Tune P3M parameters to desired accuracy.
void charge_assign (ParticleRange const &particles)
Assign the physical charges using the tabulated charge assignment function.
void assign_charge (double q, Utils::Vector3d const &real_pos, p3m_interpolation_cache &inter_weights)
Assign a single charge into the current charge grid.
void assign_charge (double q, Utils::Vector3d const &real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Utils::Vector3d pair_force (double q1q2, Utils::Vector3d const &d, double dist) const
Calculate real-space contribution of p3m Coulomb pair forces.
double pair_energy (double q1q2, double dist) const
Calculate real-space contribution of Coulomb pair energy.
Utils::Vector9d long_range_pressure (ParticleRange const &particles)
Compute the k-space part of the pressure tensor.
double long_range_energy (ParticleRange const &particles)
Compute the k-space part of energies.
void add_long_range_forces (ParticleRange const &particles)
Compute the k-space part of forces.
double long_range_kernel (bool force_flag, bool energy_flag, ParticleRange const &particles)
Compute the k-space part of forces and energies.
Public Member Functions inherited from Coulomb::Actor< CoulombP3M >
void set_prefactor (double new_prefactor)
void sanity_checks_charge_neutrality () const
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
p3m_data_struct p3m
P3M parameters.
int tune_timings
bool tune_verbose
bool check_complex_residuals
Public Attributes inherited from Coulomb::Actor< CoulombP3M >
double prefactor
Electrostatics prefactor.
double charge_neutrality_tolerance
Relative tolerance for the charge excess during neutrality checks.
Additional Inherited Members
Static Public Attributes inherited from Coulomb::Actor< CoulombP3M >
static constexpr auto charge_neutrality_tolerance_default
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
P3M solver.
Definition at line 85 of file p3m.hpp.
Constructor & Destructor Documentation
CoulombP3M()
CoulombP3M::CoulombP3M (P3MParameters && parameters, double prefactor, int tune_timings, bool tune_verbose, bool check_complex_residuals)
Definition at line 287 of file p3m.cpp.
References p3m, p3m_data_struct_base::params, Coulomb::Actor< CoulombP3M >::prefactor, Coulomb::Actor< CoulombP3M >::set_prefactor(), tune_timings, and P3MParameters::tuning.
Member Function Documentation
add_long_range_forces()
void CoulombP3M::add_long_range_forces (ParticleRange const & particles) inline
Compute the k-space part of forces.
Definition at line 225 of file p3m.hpp.
References long_range_kernel(), and Cells::particles().
assign_charge() [1/2]
void CoulombP3M::assign_charge (double q, Utils::Vector3d const & real_pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 359 of file p3m.cpp.
References P3MParameters::cao, p3m, and p3m_data_struct_base::params.
assign_charge() [2/2]
void CoulombP3M::assign_charge (double q, Utils::Vector3d const & real_pos, p3m_interpolation_cache & inter_weights)
Assign a single charge into the current charge grid.
Parameters
[in] q Particle charge
[in] real_pos Particle position in real space
[out] inter_weights Cached interpolation weights to be used.
Definition at line 353 of file p3m.cpp.
References P3MParameters::cao, p3m, and p3m_data_struct_base::params.
Referenced by charge_assign(), and p3m_assign_image_charge().
charge_assign()
void CoulombP3M::charge_assign (ParticleRange const & particles)
Assign the physical charges using the tabulated charge assignment function.
Definition at line 339 of file p3m.cpp.
References P3MParameters::cao, ParticlePropertyRange::charge_range(), p3m_data_struct::inter_weights, p3m_data_struct::local_mesh, p3m, p3m_data_struct_base::params, Cells::particles(), ParticlePropertyRange::pos_range(), p3m_interpolation_cache::reset(), p3m_data_struct::rs_mesh, and P3MLocalMesh::size.
Referenced by long_range_kernel(), and long_range_pressure().
count_charged_particles()
void CoulombP3M::count_charged_particles ()
Count the number of charged particles and calculate the sum of the squared charges.
Definition at line 84 of file p3m.cpp.
References System::Leaf< Class >::get_system(), and Utils::sqr().
Referenced by init(), and tune().
init()
void CoulombP3M::init ()
Recalculate all derived parameters.
Definition at line 246 of file p3m.cpp.
References P3MParameters::alpha, Utils::Vector< T, N >::broadcast(), p3m_data_struct_base::calc_differential_operator(), P3MLocalMesh::calc_local_ca_mesh(), P3MParameters::cao, P3MParameters::cao3, comm_cart, communicator, count_charged_particles(), P3MLocalMesh::dim, p3m_data_struct::E_mesh, p3m_data_struct::fft, fft_init(), System::Leaf< Class >::get_system(), p3m_data_struct_base::ks_pnum, p3m_data_struct::local_mesh, P3MLocalMesh::margin, P3MParameters::mesh, P3MParameters::mesh_off, Communicator::node_grid, p3m, p3m_data_struct_base::params, P3MParameters::recalc_a_ai_cao_cut(), p3m_send_mesh::resize(), p3m_data_struct::rs_mesh, sanity_checks(), and p3m_data_struct::sm.
Referenced by on_cell_structure_change(), and tune().
is_tuned()
bool CoulombP3M::is_tuned () const inline
Definition at line 100 of file p3m.hpp.
Referenced by CoulombP3MGPU::on_activation(), and tune().
long_range_energy()
double CoulombP3M::long_range_energy (ParticleRange const & particles) inline
Compute the k-space part of energies.
Definition at line 220 of file p3m.hpp.
References long_range_kernel(), and Cells::particles().
Referenced by CoulombP3MGPU::add_long_range_forces().
long_range_kernel()
double CoulombP3M::long_range_kernel (bool force_flag, bool energy_flag, ParticleRange const & particles)
Compute the k-space part of forces and energies.
Definition at line 475 of file p3m.cpp.
References P3MParameters::alpha, calc_dipole_moment(), P3MParameters::cao, charge_assign(), ParticlePropertyRange::charge_range(), check_complex_residuals, comm_cart, p3m_data_struct_base::d_op, P3MLocalMesh::dim, p3m_data_struct::E_mesh, P3MParameters::epsilon, p3m_data_struct::fft, fft_perform_back(), fft_perform_forw(), ParticlePropertyRange::force_range(), p3m_data_struct_base::g_energy, p3m_data_struct_base::g_force, p3m_send_mesh::gather_grid(), System::Leaf< Class >::get_system(), INTEG_METHOD_NPT_ISO, p3m_data_struct_base::ks_pnum, p3m_data_struct::local_mesh, Utils::make_span(), fft_forw_plan::new_mesh, fft_forw_plan::new_size, npt_add_virial_contribution(), p3m, P3M_EPSILON_METALLIC, p3m_data_struct_base::params, Cells::particles(), Utils::pi(), fft_data_struct::plan, Coulomb::Actor< CoulombP3M >::prefactor, walberla::lbm::accessor::MomentumDensity::reduce(), p3m_data_struct::rs_mesh, p3m_data_struct::sm, p3m_send_mesh::spread_grid(), Utils::sqr(), Utils::sqrt_pi_i(), p3m_data_struct::square_sum_q, fft_forw_plan::start, p3m_data_struct::sum_q2, this_node, P3MParameters::tuning, and ParticlePropertyRange::unfolded_pos_range().
Referenced by add_long_range_forces(), and long_range_energy().
long_range_pressure()
Utils::Vector9d CoulombP3M::long_range_pressure (ParticleRange const & particles)
Compute the k-space part of the pressure tensor.
Calculate the long range electrostatics part of the pressure tensor. This is part \(\Pi_{\textrm{dir}, \alpha, \beta}\) eq. (2.6) in [18]. The part \(\Pi_{\textrm{corr}, \alpha, \beta}\) eq. (2.8) is not present here since M is the empty set in our simulations.
Definition at line 416 of file p3m.cpp.
References P3MParameters::alpha, charge_assign(), comm_cart, P3MLocalMesh::dim, p3m_data_struct::fft, fft_perform_forw(), p3m_send_mesh::gather_grid(), System::Leaf< Class >::get_system(), p3m_data_struct::local_mesh, fft_forw_plan::new_mesh, p3m, p3m_data_struct_base::params, Cells::particles(), fft_data_struct::plan, p3m_data_struct::rs_mesh, p3m_data_struct::sm, Utils::sqr(), and p3m_data_struct::sum_q2.
on_activation()
void CoulombP3M::on_activation () inline
Definition at line 104 of file p3m.hpp.
References sanity_checks(), and tune().
Referenced by CoulombP3MGPU::on_activation().
on_boxl_change()
void CoulombP3M::on_boxl_change () inline
Recalculate all box-length-dependent parameters.
Definition at line 109 of file p3m.hpp.
on_cell_structure_change()
void CoulombP3M::on_cell_structure_change () inline
Definition at line 112 of file p3m.hpp.
References init().
on_node_grid_change()
void CoulombP3M::on_node_grid_change () const inline
Definition at line 110 of file p3m.hpp.
on_periodicity_change()
void CoulombP3M::on_periodicity_change () const inline
Definition at line 111 of file p3m.hpp.
pair_energy()
double CoulombP3M::pair_energy (double q1q2, double dist) const inline
Calculate real-space contribution of Coulomb pair energy.
Definition at line 202 of file p3m.hpp.
References P3MParameters::alpha, Utils::AS_erfc_part(), p3m, p3m_data_struct_base::params, Coulomb::Actor< CoulombP3M >::prefactor, and P3MParameters::r_cut.
pair_force()
Utils::Vector3d CoulombP3M::pair_force (double q1q2, Utils::Vector3d const & d, double dist) const inline
Calculate real-space contribution of p3m Coulomb pair forces.
Definition at line 181 of file p3m.hpp.
References P3MParameters::alpha, Utils::AS_erfc_part(), p3m, p3m_data_struct_base::params, Coulomb::Actor< CoulombP3M >::prefactor, P3MParameters::r_cut, and Utils::sqrt_pi_i().
sanity_checks()
void CoulombP3M::sanity_checks () const inline
Definition at line 116 of file p3m.hpp.
References Coulomb::Actor< CoulombP3M >::sanity_checks_charge_neutrality().
Referenced by init(), and on_activation().
tune()
void CoulombP3M::tune ()
Tune P3M parameters to desired accuracy.
The parameters mesh, cao, r_cut_iL and alpha_L are tuned to obtain the target accuracy in optimal time. These parameters are stored in the p3m object.
The function utilizes the analytic expression of the error estimate for the P3M method in [23] (eq. (8.23)) in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box. For the real space error the estimate of Kolafa/Perram is used.
Parameter ranges if not given explicitly in the constructor:
mesh explores the range 0-512 (biased toward values less than 128)
cao explores all possible values
alpha_L is tuned for each tuple (r_cut_iL, mesh, cao) and calculated assuming that the error contributions of real and reciprocal space should be equal
After checking if the total error lies below the target accuracy, the time needed for one force calculation is measured. Parameters that minimize the runtime are kept.
The function is based on routines of the program HE_Q.cpp written by M. Deserno.
Definition at line 776 of file p3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, count_charged_particles(), TuningAlgorithm::determine_cao_limits(), CoulombTuningAlgorithm::determine_mesh_limits(), TuningAlgorithm::determine_r_cut_limits(), System::Leaf< Class >::get_system(), init(), is_tuned(), p3m, p3m_data_struct_base::params, Coulomb::Actor< CoulombP3M >::prefactor, P3MParameters::r_cut, P3MParameters::r_cut_iL, CoulombTuningAlgorithm::setup_logger(), p3m_data_struct::sum_qpart, TuningAlgorithm::tune(), tune_timings, tune_verbose, and P3MParameters::tuning.
Referenced by on_activation().
Member Data Documentation
check_complex_residuals
bool CoulombP3M::check_complex_residuals
Definition at line 91 of file p3m.hpp.
Referenced by long_range_kernel().
p3m
p3m_data_struct CoulombP3M::p3m
P3M parameters.
Definition at line 87 of file p3m.hpp.
Referenced by assign_charge(), CoulombTuningAlgorithm::calculate_accuracy(), charge_assign(), charge_assign(), CoulombP3M(), CoulombTuningAlgorithm::determine_mesh_limits(), CoulombTuningAlgorithm::get_params(), CoulombTuningAlgorithm::get_time(), init(), CoulombP3MGPU::init(), long_range_kernel(), long_range_pressure(), modify_p3m_sums(), pair_energy(), pair_force(), CoulombTuningAlgorithm::setup_logger(), and tune().
tune_timings
int CoulombP3M::tune_timings
Definition at line 89 of file p3m.hpp.
Referenced by CoulombP3M(), and tune().
tune_verbose
bool CoulombP3M::tune_verbose
Definition at line 90 of file p3m.hpp.
Referenced by tune().
The documentation for this struct was generated from the following files:
p3m.hpp
p3m.cpp