ESPResSo: ErrorHandling::RuntimeError Struct Reference
ErrorHandling::RuntimeError Struct Reference
A runtime error.
#include <RuntimeError.hpp>
Public Types
enum class ErrorLevel { WARNING , ERROR }
Public Member Functions
RuntimeError ()=default
RuntimeError (ErrorLevel level, int who, std::string what, std::string function, std::string file, int line)
ErrorLevel level () const
The error level.
int who () const
Which MPI node raised the error.
std::string what () const
The Error Message.
std::string function () const
The function where the error occurred.
std::string file () const
The file where the error occurred.
int line () const
The line where the error occurred.
std::string format () const
Get a string representation.
Friends
class boost::serialization::access
Boost serialization.
Detailed Description
A runtime error.
This class describes a runtime error, including where it occurred and its severity.
Definition at line 35 of file RuntimeError.hpp.
Member Enumeration Documentation
ErrorLevel
enum class ErrorHandling::RuntimeError::ErrorLevel strong
Enumerator
WARNING
ERROR
Definition at line 36 of file RuntimeError.hpp.
Constructor & Destructor Documentation
RuntimeError() [1/2]
ErrorHandling::RuntimeError::RuntimeError () default
RuntimeError() [2/2]
ErrorHandling::RuntimeError::RuntimeError (ErrorLevel level, int who, std::string what, std::string function, std::string file, int line) inline
Definition at line 38 of file RuntimeError.hpp.
Member Function Documentation
file()
std::string ErrorHandling::RuntimeError::file () const inline
The file where the error occurred.
Definition at line 53 of file RuntimeError.hpp.
Referenced by format().
format()
std::string ErrorHandling::RuntimeError::format () const
Get a string representation.
Definition at line 28 of file RuntimeError.cpp.
References ERROR, file(), function(), line(), stream, WARNING, what(), and who().
function()
std::string ErrorHandling::RuntimeError::function () const inline
The function where the error occurred.
Definition at line 51 of file RuntimeError.hpp.
Referenced by format().
level()
ErrorLevel ErrorHandling::RuntimeError::level () const inline
The error level.
Definition at line 45 of file RuntimeError.hpp.
line()
int ErrorHandling::RuntimeError::line () const inline
The line where the error occurred.
Definition at line 55 of file RuntimeError.hpp.
Referenced by format().
what()
std::string ErrorHandling::RuntimeError::what () const inline
The Error Message.
Definition at line 49 of file RuntimeError.hpp.
Referenced by format().
who()
int ErrorHandling::RuntimeError::who () const inline
Which MPI node raised the error.
Definition at line 47 of file RuntimeError.hpp.
Referenced by format().
Friends And Related Symbol Documentation
boost::serialization::access
friend class boost::serialization::access friend
Boost serialization.
Definition at line 61 of file RuntimeError.hpp.
The documentation for this struct was generated from the following files:
RuntimeError.hpp
RuntimeError.cpp