ESPResSo: DipolarP3MImpl< FloatType, Architecture > Struct Template Reference
DipolarP3MImpl< FloatType, Architecture > Struct Template Reference
#include <dp3m.impl.hpp>
Public Member Functions
~DipolarP3MImpl () override=default
DipolarP3MImpl (std::unique_ptr< p3m_data_struct_dipoles< FloatType > > &&dp3m_handle, double prefactor, int tune_timings, bool tune_verbose, decltype(tune_limits) tune_limits)
void init () override
void tune () override
void count_magnetic_particles () override
bool is_tuned () const noexcept override
bool is_gpu () const noexcept override
bool is_double_precision () const noexcept override
void on_activation () override
double long_range_energy (ParticleRange const &particles) override
void add_long_range_forces (ParticleRange const &particles) override
void dipole_assign (ParticleRange const &particles) override
Public Member Functions inherited from DipolarP3M
DipolarP3M (P3MParameters const &dp3m_params)
virtual ~DipolarP3M ()=default
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
void sanity_checks () const
ParticleForce pair_force (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist2, double dist) const
Calculate real-space contribution of p3m dipolar pair forces and torques.
double pair_energy (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist2, double dist) const
Calculate real-space contribution of dipolar pair energy.
Public Member Functions inherited from Dipoles::Actor< DipolarP3M >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
p3m_data_struct_dipoles< FloatType > & dp3m
Dipolar P3M parameters.
Public Attributes inherited from DipolarP3M
P3MParameters const & dp3m_params
Public Attributes inherited from Dipoles::Actor< DipolarP3M >
double prefactor
Magnetostatics prefactor.
Protected Member Functions
double long_range_kernel (bool force_flag, bool energy_flag, ParticleRange const &particles)
Compute the k-space part of forces and energies.
double calc_average_self_energy_k_space () const override
void calc_energy_correction () override
void calc_influence_function_force () override
void calc_influence_function_energy () override
double calc_surface_term (bool force_flag, bool energy_flag, ParticleRange const &particles) override
void init_cpu_kernels ()
void scaleby_box_l () override
Protected Member Functions inherited from DipolarP3M
void sanity_checks_boxl () const
Checks for correctness of the k-space cutoff.
void sanity_checks_node_grid () const
void sanity_checks_periodicity () const
void sanity_checks_cell_structure () const
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Additional Inherited Members
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
template<typename FloatType, Arch Architecture>
struct DipolarP3MImpl< FloatType, Architecture >
Definition at line 67 of file dp3m.impl.hpp.
Constructor & Destructor Documentation
~DipolarP3MImpl()
template<typename FloatType , Arch Architecture> DipolarP3MImpl< FloatType, Architecture >::~DipolarP3MImpl () override default
DipolarP3MImpl()
template<typename FloatType , Arch Architecture> DipolarP3MImpl< FloatType, Architecture >::DipolarP3MImpl (std::unique_ptr< p3m_data_struct_dipoles< FloatType > > && dp3m_handle, double prefactor, int tune_timings, bool tune_verbose, decltype(tune_limits) tune_limits) inline
Definition at line 82 of file dp3m.impl.hpp.
References Utils::Vector< T, N >::broadcast(), DipolarP3MImpl< FloatType, Architecture >::dp3m, Dipoles::Actor< DipolarP3M >::prefactor, Dipoles::Actor< DipolarP3M >::set_prefactor(), and stream.
Member Function Documentation
add_long_range_forces()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::add_long_range_forces (ParticleRange const & particles) inline override virtual
Implements DipolarP3M.
Definition at line 126 of file dp3m.impl.hpp.
References CPU, DipolarP3MImpl< FloatType, Architecture >::long_range_kernel(), and stream.
calc_average_self_energy_k_space()
template<typename FloatType , Arch Architecture> double DipolarP3MImpl< FloatType, Architecture >::calc_average_self_energy_k_space () const override protected virtual
Implements DipolarP3M.
Definition at line 116 of file dp3m.cpp.
References System::System::box_geo, comm_cart, and stream.
calc_energy_correction()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::calc_energy_correction () override protected virtual
Implements DipolarP3M.
Definition at line 906 of file dp3m.cpp.
References P3MParameters::alpha_L, System::System::box_geo, p3m_data_struct_dipoles< FloatType >::energy_correction, p3m_data_struct< FloatType >::params, stream, and p3m_data_struct_dipoles< FloatType >::sum_mu2.
calc_influence_function_energy()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::calc_influence_function_energy () override protected virtual
Implements DipolarP3M.
Definition at line 529 of file dp3m.cpp.
References stream.
calc_influence_function_force()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::calc_influence_function_force () override protected virtual
Implements DipolarP3M.
Definition at line 522 of file dp3m.cpp.
References stream.
calc_surface_term()
template<typename FloatType , Arch Architecture> double DipolarP3MImpl< FloatType, Architecture >::calc_surface_term (bool force_flag, bool energy_flag, ParticleRange const & particles) override protected virtual
Implements DipolarP3M.
Definition at line 454 of file dp3m.cpp.
References System::System::box_geo, comm_cart, ParticleRange::size(), and stream.
count_magnetic_particles()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::count_magnetic_particles () override virtual
Implements DipolarP3M.
Definition at line 85 of file dp3m.cpp.
References System::System::cell_structure, comm_cart, and stream.
dipole_assign()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::dipole_assign (ParticleRange const & particles) override virtual
Implements DipolarP3M.
Definition at line 179 of file dp3m.cpp.
References stream.
init()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::init () inline override virtual
Implements DipolarP3M.
Definition at line 101 of file dp3m.impl.hpp.
References CPU, DipolarP3MImpl< FloatType, Architecture >::init_cpu_kernels(), and stream.
init_cpu_kernels()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::init_cpu_kernels () protected
Definition at line 130 of file dp3m.cpp.
References Utils::Vector< T, N >::broadcast(), count_magnetic_particles(), and stream.
Referenced by DipolarP3MImpl< FloatType, Architecture >::init().
is_double_precision()
template<typename FloatType , Arch Architecture> bool DipolarP3MImpl< FloatType, Architecture >::is_double_precision () const inline override virtual noexcept
Implements DipolarP3M.
Definition at line 113 of file dp3m.impl.hpp.
is_gpu()
template<typename FloatType , Arch Architecture> bool DipolarP3MImpl< FloatType, Architecture >::is_gpu () const inline override virtual noexcept
Implements DipolarP3M.
Definition at line 110 of file dp3m.impl.hpp.
References GPU, and stream.
is_tuned()
template<typename FloatType , Arch Architecture> bool DipolarP3MImpl< FloatType, Architecture >::is_tuned () const inline override virtual noexcept
Implements DipolarP3M.
Definition at line 109 of file dp3m.impl.hpp.
long_range_energy()
template<typename FloatType , Arch Architecture> double DipolarP3MImpl< FloatType, Architecture >::long_range_energy (ParticleRange const & particles) inline override virtual
Implements DipolarP3M.
Definition at line 122 of file dp3m.impl.hpp.
References DipolarP3MImpl< FloatType, Architecture >::long_range_kernel().
long_range_kernel()
template<typename FloatType , Arch Architecture> double DipolarP3MImpl< FloatType, Architecture >::long_range_kernel (bool force_flag, bool energy_flag, ParticleRange const & particles) protected
Compute the k-space part of forces and energies.
Definition at line 249 of file dp3m.cpp.
References Utils::Vector< T, N >::broadcast(), comm_cart, for_each_3d(), INTEG_METHOD_NPT_ISO, npt_add_virial_contribution(), P3M_EPSILON_METALLIC, Utils::sqr(), stream, and this_node.
Referenced by DipolarP3MImpl< FloatType, Architecture >::add_long_range_forces(), and DipolarP3MImpl< FloatType, Architecture >::long_range_energy().
on_activation()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::on_activation () inline override virtual
Implements DipolarP3M.
Definition at line 117 of file dp3m.impl.hpp.
References DipolarP3M::sanity_checks(), and DipolarP3MImpl< FloatType, Architecture >::tune().
scaleby_box_l()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::scaleby_box_l () override protected virtual
Implements DipolarP3M.
Definition at line 893 of file dp3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, System::System::box_geo, p3m_data_struct_dipoles< FloatType >::energy_correction, p3m_data_struct< FloatType >::local_mesh, p3m_data_struct< FloatType >::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, P3MParameters::recalc_a_ai_cao_cut(), and P3MLocalMesh::recalc_ld_pos().
tune()
template<typename FloatType , Arch Architecture> void DipolarP3MImpl< FloatType, Architecture >::tune () override virtual
Implements DipolarP3M.
Definition at line 659 of file dp3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, count_magnetic_particles(), p3m_data_struct< FloatType >::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, stream, p3m_data_struct_dipoles< FloatType >::sum_dip_part, and P3MParameters::tuning.
Referenced by DipolarP3MImpl< FloatType, Architecture >::on_activation().
Member Data Documentation
dp3m
template<typename FloatType , Arch Architecture> p3m_data_struct_dipoles<FloatType>& DipolarP3MImpl< FloatType, Architecture >::dp3m
Dipolar P3M parameters.
Definition at line 71 of file dp3m.impl.hpp.
Referenced by DipolarP3MImpl< FloatType, Architecture >::DipolarP3MImpl().
The documentation for this struct was generated from the following files:
dp3m.impl.hpp
dp3m.cpp