ESPResSo: ForcesKernel Struct Reference
ForcesKernel Struct Reference
#include <forces_cabana.hpp>
Public Member Functions
ForcesKernel (BondedInteractionsMap const &bonded_ias_, InteractionsNonBonded const &nonbonded_ias_, Coulomb::ShortRangeForceKernel::kernel_type const *coulomb_kernel_, Dipoles::ShortRangeForceKernel::kernel_type const *dipoles_kernel_, Coulomb::ShortRangeForceCorrectionsKernel::kernel_type const *elc_kernel_, Coulomb::ShortRangeEnergyKernel::kernel_type const *coulomb_u_kernel_, Coulomb::Solver const &coulomb_, Thermostat::Thermostat const &thermostat_, BoxGeometry const &box_geo_, std::vector< Particle * > const &unique_particles_, CellStructure::ForceType const &local_force_, CellStructure::ForceType const &local_torque_, Utils::Vector3d *const global_virial_, CellStructure::VirialType const &local_virial_, CellStructure::AoSoA_pack const &aosoa_, double system_max_cutoff_)
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool gay_berne_active (double dist, IA_parameters const &ia_params) const
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool npt_active () const
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool thole_active (IA_parameters const &ia_params) const
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool dipoles_active () const
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION void operator() (std::size_t i, std::size_t j) const
Public Attributes
BondedInteractionsMap const & bonded_ias
InteractionsNonBonded const & nonbonded_ias
Coulomb::ShortRangeForceKernel::kernel_type const *const coulomb_kernel
Dipoles::ShortRangeForceKernel::kernel_type const *const dipoles_kernel
Coulomb::ShortRangeForceCorrectionsKernel::kernel_type const * elc_kernel
Coulomb::ShortRangeEnergyKernel::kernel_type const *const coulomb_u_kernel
Thermostat::Thermostat const & thermostat
BoxGeometry const & box_geo
std::vector< Particle * > const & unique_particles
CellStructure::ForceType const & local_force
CellStructure::ForceType const & local_torque
Utils::Vector3d *const global_virial
CellStructure::VirialType const & local_virial
CellStructure::AoSoA_pack const & aosoa
CoulombP3M const * p3m
double system_max_cutoff
Detailed Description
Definition at line 47 of file forces_cabana.hpp.
Constructor & Destructor Documentation
ForcesKernel()
ForcesKernel::ForcesKernel (BondedInteractionsMap const & bonded_ias_, InteractionsNonBonded const & nonbonded_ias_, Coulomb::ShortRangeForceKernel::kernel_type const * coulomb_kernel_, Dipoles::ShortRangeForceKernel::kernel_type const * dipoles_kernel_, Coulomb::ShortRangeForceCorrectionsKernel::kernel_type const * elc_kernel_, Coulomb::ShortRangeEnergyKernel::kernel_type const * coulomb_u_kernel_, Coulomb::Solver const & coulomb_, Thermostat::Thermostat const & thermostat_, BoxGeometry const & box_geo_, std::vector< Particle * > const & unique_particles_, CellStructure::ForceType const & local_force_, CellStructure::ForceType const & local_torque_, Utils::Vector3d *const global_virial_, CellStructure::VirialType const & local_virial_, CellStructure::AoSoA_pack const & aosoa_, double system_max_cutoff_) inline
Definition at line 71 of file forces_cabana.hpp.
References p3m, and stream.
Member Function Documentation
dipoles_active()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool ForcesKernel::dipoles_active () const inline
Definition at line 138 of file forces_cabana.hpp.
References dipoles_kernel.
Referenced by operator()().
gay_berne_active()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool ForcesKernel::gay_berne_active (double dist, IA_parameters const & ia_params) const inline
Definition at line 114 of file forces_cabana.hpp.
References stream.
Referenced by operator()().
npt_active()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool ForcesKernel::npt_active () const inline
Definition at line 123 of file forces_cabana.hpp.
References global_virial.
Referenced by operator()().
operator()()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION void ForcesKernel::operator() (std::size_t i, std::size_t j) const inline
Definition at line 144 of file forces_cabana.hpp.
References aosoa, bonded_ias, box_geo, calc_central_radial_force(), calc_opposing_force(), CellStructure::AoSoA_pack::charge, coulomb_kernel, CellStructure::AoSoA_pack::dipm, dipoles_active(), CellStructure::AoSoA_pack::director, do_nonbonded(), Thermostat::Thermostat::dpd, dpd_pair_force(), elc_kernel, gay_berne_active(), gb_pair_force(), InteractionsNonBonded::get_ia_param(), BoxGeometry::get_mi_vector(), CellStructure::AoSoA_pack::get_vector_at(), CellStructure::AoSoA_pack::has_exclusion(), CellStructure::AoSoA_pack::id, local_force, local_torque, local_virial, nonbonded_ias, npt_active(), p3m, CoulombP3M::pair_force(), CellStructure::AoSoA_pack::position, stream, system_max_cutoff, THERMO_DPD, Thermostat::Thermostat::thermo_switch, thermostat, thole_active(), thole_pair_force(), CellStructure::AoSoA_pack::type, unique_particles, and CellStructure::AoSoA_pack::velocity.
thole_active()
ESPRESSO_ATTR_ALWAYS_INLINE KOKKOS_INLINE_FUNCTION bool ForcesKernel::thole_active (IA_parameters const & ia_params) const inline
Definition at line 130 of file forces_cabana.hpp.
References coulomb_kernel, and stream.
Referenced by operator()().
Member Data Documentation
aosoa
CellStructure::AoSoA_pack const& ForcesKernel::aosoa
Definition at line 65 of file forces_cabana.hpp.
Referenced by operator()().
bonded_ias
BondedInteractionsMap const& ForcesKernel::bonded_ias
Definition at line 48 of file forces_cabana.hpp.
Referenced by create_cabana_neighbor_kernel(), and operator()().
box_geo
BoxGeometry const& ForcesKernel::box_geo
Definition at line 55 of file forces_cabana.hpp.
Referenced by operator()().
coulomb_kernel
Coulomb::ShortRangeForceKernel::kernel_type const* const ForcesKernel::coulomb_kernel
Definition at line 50 of file forces_cabana.hpp.
Referenced by operator()(), and thole_active().
coulomb_u_kernel
Coulomb::ShortRangeEnergyKernel::kernel_type const* const ForcesKernel::coulomb_u_kernel
Definition at line 53 of file forces_cabana.hpp.
dipoles_kernel
Dipoles::ShortRangeForceKernel::kernel_type const* const ForcesKernel::dipoles_kernel
Definition at line 51 of file forces_cabana.hpp.
Referenced by dipoles_active().
elc_kernel
Coulomb::ShortRangeForceCorrectionsKernel::kernel_type const* ForcesKernel::elc_kernel
Definition at line 52 of file forces_cabana.hpp.
Referenced by operator()().
global_virial
Utils::Vector3d* const ForcesKernel::global_virial
Definition at line 62 of file forces_cabana.hpp.
Referenced by npt_active().
local_force
CellStructure::ForceType const& ForcesKernel::local_force
Definition at line 57 of file forces_cabana.hpp.
Referenced by operator()().
local_torque
CellStructure::ForceType const& ForcesKernel::local_torque
Definition at line 59 of file forces_cabana.hpp.
Referenced by operator()().
local_virial
CellStructure::VirialType const& ForcesKernel::local_virial
Definition at line 63 of file forces_cabana.hpp.
Referenced by operator()().
nonbonded_ias
InteractionsNonBonded const& ForcesKernel::nonbonded_ias
Definition at line 49 of file forces_cabana.hpp.
Referenced by operator()().
p3m
CoulombP3M const* ForcesKernel::p3m
Definition at line 67 of file forces_cabana.hpp.
Referenced by ForcesKernel(), and operator()().
system_max_cutoff
double ForcesKernel::system_max_cutoff
Definition at line 69 of file forces_cabana.hpp.
Referenced by operator()().
thermostat
Thermostat::Thermostat const& ForcesKernel::thermostat
Definition at line 54 of file forces_cabana.hpp.
Referenced by operator()().
unique_particles
std::vector<Particle *> const& ForcesKernel::unique_particles
Definition at line 56 of file forces_cabana.hpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
forces_cabana.hpp