ESPResSo: ParticleObservables::traits< Particle > Struct Reference
ParticleObservables::traits< Particle > Struct Reference
Template specialization for Particle.
#include <ParticleTraits.hpp>
Public Member Functions
auto id (Particle const &p) const
auto position (Particle const &p) const
auto position_folded (Particle const &p) const
auto velocity (Particle const &p) const
auto force (Particle const &p) const
auto mass (Particle const &p) const
auto charge (Particle const &p) const
auto dipole_moment (Particle const &p) const
auto dipole_field (Particle const &p) const
auto velocity_body (Particle const &p) const
auto angular_velocity (Particle const &p) const
auto angular_velocity_body (Particle const &p) const
auto director (Particle const &p) const
Detailed Description
Template specialization for Particle.
The traits mechanism is used to get indirect access to particle properties. This helps making the implementation of observables independent of the particle type.
Definition at line 34 of file ParticleTraits.hpp.
Member Function Documentation
angular_velocity()
auto ParticleObservables::traits< Particle >::angular_velocity (Particle const & p) const inline
Definition at line 73 of file ParticleTraits.hpp.
References convert_vector_body_to_space(), and Particle::omega().
angular_velocity_body()
auto ParticleObservables::traits< Particle >::angular_velocity_body (Particle const & p) const inline
Definition at line 80 of file ParticleTraits.hpp.
References Particle::omega().
charge()
auto ParticleObservables::traits< Particle >::charge (Particle const & p) const inline
Definition at line 51 of file ParticleTraits.hpp.
References Particle::q().
dipole_field()
auto ParticleObservables::traits< Particle >::dipole_field (Particle const & p) const inline
Definition at line 59 of file ParticleTraits.hpp.
References Particle::dip_fld().
dipole_moment()
auto ParticleObservables::traits< Particle >::dipole_moment (Particle const & p) const inline
Definition at line 52 of file ParticleTraits.hpp.
References Particle::calc_dip().
director()
auto ParticleObservables::traits< Particle >::director (Particle const & p) const inline
Definition at line 87 of file ParticleTraits.hpp.
References Particle::calc_director().
force()
auto ParticleObservables::traits< Particle >::force (Particle const & p) const inline
Definition at line 42 of file ParticleTraits.hpp.
References Particle::force().
id()
auto ParticleObservables::traits< Particle >::id (Particle const & p) const inline
Definition at line 35 of file ParticleTraits.hpp.
References Particle::id().
mass()
auto ParticleObservables::traits< Particle >::mass (Particle const & p) const inline
Definition at line 43 of file ParticleTraits.hpp.
References Particle::is_virtual(), and Particle::mass().
position()
auto ParticleObservables::traits< Particle >::position (Particle const & p) const inline
Definition at line 36 of file ParticleTraits.hpp.
References System::System::box_geo, System::get_system(), Particle::image_box(), and Particle::pos().
position_folded()
auto ParticleObservables::traits< Particle >::position_folded (Particle const & p) const inline
Definition at line 40 of file ParticleTraits.hpp.
References Particle::pos().
velocity()
auto ParticleObservables::traits< Particle >::velocity (Particle const & p) const inline
Definition at line 41 of file ParticleTraits.hpp.
References Particle::v().
velocity_body()
auto ParticleObservables::traits< Particle >::velocity_body (Particle const & p) const inline
Definition at line 66 of file ParticleTraits.hpp.
References convert_vector_space_to_body(), and Particle::v().
The documentation for this struct was generated from the following file:
ParticleTraits.hpp