ESPResSo: DipolarP3M Struct Reference
DipolarP3M Struct Reference abstract
Dipolar P3M solver.
#include <dp3m.hpp>
Public Member Functions
DipolarP3M (p3m_data_struct &dp3m_data, double prefactor, int tune_timings, bool tune_verbose)
virtual ~DipolarP3M ()=default
bool is_tuned () const
virtual bool is_gpu () const noexcept=0
virtual void on_activation ()=0
void on_boxl_change ()
Recalculate all box-length-dependent parameters.
void on_node_grid_change () const
void on_periodicity_change () const
void on_cell_structure_change ()
virtual void init ()=0
Recalculate all derived parameters.
void sanity_checks () const
virtual void count_magnetic_particles ()=0
Count the number of magnetic particles and calculate the sum of the squared dipole moments.
virtual void dipole_assign (ParticleRange const &particles)=0
Assign the physical dipoles using the tabulated assignment function.
virtual void tune ()=0
Tune dipolar P3M parameters to desired accuracy.
virtual double long_range_energy (ParticleRange const &particles)=0
Compute the k-space part of energies.
virtual void add_long_range_forces (ParticleRange const &particles)=0
Compute the k-space part of forces.
ParticleForce pair_force (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist2, double dist) const
Calculate real-space contribution of p3m dipolar pair forces and torques.
double pair_energy (Particle const &p1, Particle const &p2, Utils::Vector3d const &d, double dist2, double dist) const
Calculate real-space contribution of dipolar pair energy.
Public Member Functions inherited from Dipoles::Actor< DipolarP3M >
void set_prefactor (double new_prefactor)
Public Member Functions inherited from System::Leaf< Class >
void bind_system (std::shared_ptr< System > const &system)
void detach_system (std::shared_ptr< System > const &system)
Public Attributes
p3m_data_struct & dp3m
Dipolar P3M parameters.
int tune_timings
bool tune_verbose
Public Attributes inherited from Dipoles::Actor< DipolarP3M >
double prefactor
Magnetostatics prefactor.
Protected Member Functions
virtual double calc_average_self_energy_k_space () const =0
Calculate self-energy in k-space.
virtual void calc_energy_correction ()=0
Calculate energy correction that minimizes the error.
virtual void calc_influence_function_force ()=0
Calculate the influence function for the dipolar forces and torques.
virtual void calc_influence_function_energy ()=0
Calculate the influence function for the dipolar energy.
double calc_surface_term (bool force_flag, bool energy_flag, ParticleRange const &particles)
Compute the dipolar surface terms.
void sanity_checks_boxl () const
Checks for correctness of the k-space cutoff.
void sanity_checks_node_grid () const
void sanity_checks_periodicity () const
void sanity_checks_cell_structure () const
virtual void scaleby_box_l ()
Protected Member Functions inherited from System::Leaf< Class >
auto & get_system ()
auto & get_system () const
Protected Attributes
bool m_is_tuned
Protected Attributes inherited from System::Leaf< Class >
std::weak_ptr< System > m_system
Detailed Description
Dipolar P3M solver.
Definition at line 60 of file dp3m.hpp.
Constructor & Destructor Documentation
DipolarP3M()
DipolarP3M::DipolarP3M (p3m_data_struct & dp3m_data, double prefactor, int tune_timings, bool tune_verbose) inline
Definition at line 71 of file dp3m.hpp.
References Utils::Vector< T, N >::broadcast(), dp3m, m_is_tuned, P3MParameters::mesh, p3m_data_struct::params, Dipoles::Actor< DipolarP3M >::prefactor, Dipoles::Actor< DipolarP3M >::set_prefactor(), tune_timings, and P3MParameters::tuning.
~DipolarP3M()
virtual DipolarP3M::~DipolarP3M () virtual default
Member Function Documentation
add_long_range_forces()
virtual void DipolarP3M::add_long_range_forces (ParticleRange const & particles) pure virtual
Compute the k-space part of forces.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
calc_average_self_energy_k_space()
virtual double DipolarP3M::calc_average_self_energy_k_space () const protected pure virtual
Calculate self-energy in k-space.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
calc_energy_correction()
virtual void DipolarP3M::calc_energy_correction () protected pure virtual
Calculate energy correction that minimizes the error.
This quantity is only calculated once and is cached.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
calc_influence_function_energy()
virtual void DipolarP3M::calc_influence_function_energy () protected pure virtual
Calculate the influence function for the dipolar energy.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
Referenced by scaleby_box_l().
calc_influence_function_force()
virtual void DipolarP3M::calc_influence_function_force () protected pure virtual
Calculate the influence function for the dipolar forces and torques.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
Referenced by scaleby_box_l().
calc_surface_term()
double DipolarP3M::calc_surface_term (bool force_flag, bool energy_flag, ParticleRange const & particles) protected
Compute the dipolar surface terms.
Definition at line 438 of file dp3m.cpp.
References comm_cart, dp3m, P3MParameters::epsilon, System::Leaf< Class >::get_system(), p3m_data_struct::params, Dipoles::Actor< DipolarP3M >::prefactor, and ParticleRange::size().
count_magnetic_particles()
virtual void DipolarP3M::count_magnetic_particles () pure virtual
Count the number of magnetic particles and calculate the sum of the squared dipole moments.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
dipole_assign()
virtual void DipolarP3M::dipole_assign (ParticleRange const & particles) pure virtual
Assign the physical dipoles using the tabulated assignment function.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
init()
virtual void DipolarP3M::init () pure virtual
Recalculate all derived parameters.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
Referenced by on_cell_structure_change().
is_gpu()
virtual bool DipolarP3M::is_gpu () const pure virtual noexcept
Implemented in DipolarP3MImpl< FloatType, Architecture >.
is_tuned()
bool DipolarP3M::is_tuned () const inline
Definition at line 89 of file dp3m.hpp.
References m_is_tuned.
long_range_energy()
virtual double DipolarP3M::long_range_energy (ParticleRange const & particles) pure virtual
Compute the k-space part of energies.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
on_activation()
virtual void DipolarP3M::on_activation () pure virtual
Implemented in DipolarP3MImpl< FloatType, Architecture >.
on_boxl_change()
void DipolarP3M::on_boxl_change () inline
Recalculate all box-length-dependent parameters.
Definition at line 94 of file dp3m.hpp.
References scaleby_box_l().
on_cell_structure_change()
void DipolarP3M::on_cell_structure_change () inline
Definition at line 97 of file dp3m.hpp.
References init(), and sanity_checks_cell_structure().
on_node_grid_change()
void DipolarP3M::on_node_grid_change () const inline
Definition at line 95 of file dp3m.hpp.
References sanity_checks_node_grid().
on_periodicity_change()
void DipolarP3M::on_periodicity_change () const inline
Definition at line 96 of file dp3m.hpp.
References sanity_checks_periodicity().
pair_energy()
double DipolarP3M::pair_energy (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist2, double dist) const inline
Calculate real-space contribution of dipolar pair energy.
Definition at line 221 of file dp3m.hpp.
References P3MParameters::accuracy, P3MParameters::alpha, Utils::AS_erfc_part(), Particle::calc_dip(), Particle::dipm(), dp3m, p3m_data_struct::params, Dipoles::Actor< DipolarP3M >::prefactor, P3MParameters::r_cut, and Utils::sqr().
pair_force()
ParticleForce DipolarP3M::pair_force (Particle const & p1, Particle const & p2, Utils::Vector3d const & d, double dist2, double dist) const inline
Calculate real-space contribution of p3m dipolar pair forces and torques.
If NPT is compiled in, update the NpT virial.
Definition at line 163 of file dp3m.hpp.
References P3MParameters::accuracy, P3MParameters::alpha, Utils::AS_erfc_part(), Particle::calc_dip(), Particle::dipm(), dp3m, npt_add_virial_magnetic_contribution(), p3m_data_struct::params, Dipoles::Actor< DipolarP3M >::prefactor, P3MParameters::r_cut, Utils::sqr(), and vector_product().
sanity_checks()
void DipolarP3M::sanity_checks () const inline
Definition at line 104 of file dp3m.hpp.
References sanity_checks_boxl(), sanity_checks_cell_structure(), sanity_checks_node_grid(), and sanity_checks_periodicity().
Referenced by DipolarP3MImpl< FloatType, Architecture >::on_activation().
sanity_checks_boxl()
void DipolarP3M::sanity_checks_boxl () const protected
Checks for correctness of the k-space cutoff.
Definition at line 808 of file dp3m.cpp.
References P3MParameters::cao_cut, dp3m, System::Leaf< Class >::get_system(), and p3m_data_struct::params.
Referenced by sanity_checks(), and scaleby_box_l().
sanity_checks_cell_structure()
void DipolarP3M::sanity_checks_cell_structure () const protected
Definition at line 842 of file dp3m.cpp.
References communicator, System::Leaf< Class >::get_system(), HYBRID, and REGULAR.
Referenced by on_cell_structure_change(), and sanity_checks().
sanity_checks_node_grid()
void DipolarP3M::sanity_checks_node_grid () const protected
Definition at line 857 of file dp3m.cpp.
References communicator, and Communicator::node_grid.
Referenced by on_node_grid_change(), and sanity_checks().
sanity_checks_periodicity()
void DipolarP3M::sanity_checks_periodicity () const protected
Definition at line 834 of file dp3m.cpp.
References System::Leaf< Class >::get_system().
Referenced by on_periodicity_change(), and sanity_checks().
scaleby_box_l()
void DipolarP3M::scaleby_box_l () protected virtual
Reimplemented in DipolarP3MImpl< FloatType, Architecture >.
Definition at line 865 of file dp3m.cpp.
References P3MParameters::alpha, P3MParameters::alpha_L, calc_influence_function_energy(), calc_influence_function_force(), dp3m, System::Leaf< Class >::get_system(), p3m_data_struct::local_mesh, p3m_data_struct::params, P3MParameters::r_cut, P3MParameters::r_cut_iL, P3MParameters::recalc_a_ai_cao_cut(), P3MLocalMesh::recalc_ld_pos(), and sanity_checks_boxl().
Referenced by on_boxl_change(), and DipolarP3MImpl< FloatType, Architecture >::scaleby_box_l().
tune()
virtual void DipolarP3M::tune () pure virtual
Tune dipolar P3M parameters to desired accuracy.
The parameters mesh, cao, r_cut_iL and alpha_L are tuned to obtain the target accuracy in optimal time. These parameters are stored in the dp3m object.
The function utilizes the analytic expression of the error estimate for the dipolar P3M method in the paper of [9] in order to obtain the rms error in the force for a system of N randomly distributed particles in a cubic box. For the real space error, the estimate in [24] is used.
Parameter ranges if not given explicitly in the constructor:
mesh is set up such that the number of mesh points is equal to the number of magnetic dipolar particles
cao explores all possible values
alpha_L is tuned for each tuple (r_cut_iL, mesh, cao) and calculated assuming that the error contributions of real and reciprocal space should be equal
After checking if the total error lies below the target accuracy, the time needed for one force calculation is measured. Parameters that minimize the runtime are kept.
The function is based on routines of the program HE_Q.cpp for charges written by M. Deserno.
Implemented in DipolarP3MImpl< FloatType, Architecture >.
Member Data Documentation
dp3m
p3m_data_struct& DipolarP3M::dp3m
Dipolar P3M parameters.
Definition at line 62 of file dp3m.hpp.
Referenced by calc_surface_term(), DipolarP3M(), pair_energy(), pair_force(), sanity_checks_boxl(), and scaleby_box_l().
m_is_tuned
bool DipolarP3M::m_is_tuned protected
Definition at line 68 of file dp3m.hpp.
Referenced by DipolarP3M(), and is_tuned().
tune_timings
int DipolarP3M::tune_timings
Definition at line 64 of file dp3m.hpp.
Referenced by DipolarP3M().
tune_verbose
bool DipolarP3M::tune_verbose
Definition at line 65 of file dp3m.hpp.
The documentation for this struct was generated from the following files:
dp3m.hpp
dp3m.cpp