ESPResSo: GatherCom Struct Reference
GatherCom Struct Reference
Public Member Functions
~GatherCom () override=default
GatherCom (BoxGeometry const &box_geo)
Utils::Vector3d kernel (Particle const &p) const override
Public Member Functions inherited from GatherParticleTraits< Utils::Vector3d >
virtual ~GatherParticleTraits ()=default
void fetch (CellStructure const &cell_structure, int pid)
auto join ()
Public Attributes
BoxGeometry const & m_box_geo
Detailed Description
Definition at line 91 of file statistics_chain.cpp.
Constructor & Destructor Documentation
~GatherCom()
GatherCom::~GatherCom () override default
GatherCom()
GatherCom::GatherCom (BoxGeometry const & box_geo) inline
Definition at line 94 of file statistics_chain.cpp.
Member Function Documentation
kernel()
Utils::Vector3d GatherCom::kernel (Particle const & p) const inline override virtual
Implements GatherParticleTraits< Utils::Vector3d >.
Definition at line 95 of file statistics_chain.cpp.
References Particle::image_box(), m_box_geo, Particle::mass(), Particle::pos(), and BoxGeometry::unfolded_position().
Member Data Documentation
m_box_geo
BoxGeometry const& GatherCom::m_box_geo
Definition at line 93 of file statistics_chain.cpp.
Referenced by kernel().
The documentation for this struct was generated from the following file:
statistics_chain.cpp