ESPResSo: symplectic_euler_inline.hpp File Reference
symplectic_euler_inline.hpp File Reference
#include <config/config.hpp>
#include "Particle.hpp"
#include "rotation.hpp"
Functions
void symplectic_euler_propagator_1 (Particle &p, double time_step)
Propagate the velocities and positions.
void symplectic_euler_propagator_2 (Particle &, double)
Final integration step of the Symplectic Euler integrator For symplectic Euler, there is no second step as all updates are done in step 1.
void symplectic_euler_rotator_1 (Particle &p, double time_step)
void symplectic_euler_rotator_2 (Particle &, double)
Function Documentation
symplectic_euler_propagator_1()
void symplectic_euler_propagator_1 (Particle & p, double time_step) inline
Propagate the velocities and positions.
Integration steps before force calculation of the Symplectic Euler integrator:
\[ v(t+\Delta t) = v(t) + \Delta t f(t)/m \]
\[ p(t+\Delta t) = p(t) + \Delta t v(t+\Delta t) \]
Definition at line 32 of file symplectic_euler_inline.hpp.
References Particle::force(), Particle::is_fixed_along(), Particle::mass(), Particle::pos(), stream, and Particle::v().
Referenced by integrator_step_1().
symplectic_euler_propagator_2()
void symplectic_euler_propagator_2 (Particle & , double) inline
Final integration step of the Symplectic Euler integrator For symplectic Euler, there is no second step as all updates are done in step 1.
Definition at line 48 of file symplectic_euler_inline.hpp.
Referenced by integrator_step_2().
symplectic_euler_rotator_1()
void symplectic_euler_rotator_1 (Particle & p, double time_step) inline
Definition at line 54 of file symplectic_euler_inline.hpp.
References Particle::can_rotate(), convert_torque_propagate_omega(), and propagate_omega_quat_particle().
Referenced by integrator_step_1().
symplectic_euler_rotator_2()
void symplectic_euler_rotator_2 (Particle & , double) inline
Definition at line 63 of file symplectic_euler_inline.hpp.
Referenced by integrator_step_2().