ESPResSo: thermostat.cpp File Reference
thermostat.cpp File Reference
#include "config.hpp"
#include "bonded_interactions/thermalized_bond.hpp"
#include "bonded_interactions/thermalized_bond_utils.hpp"
#include "communication.hpp"
#include "dpd.hpp"
#include "event.hpp"
#include "integrate.hpp"
#include "npt.hpp"
#include "thermostat.hpp"
#include <boost/mpi.hpp>
#include <algorithm>
#include <cstdint>
Macros
#define REGISTER_THERMOSTAT_CALLBACKS(thermostat)
Create MPI callbacks of thermostat objects.
Functions
void thermo_init (double time_step)
Initialize constants of the thermostat at the start of integration.
void philox_counter_increment ()
Increment RNG counters.
void mpi_set_brownian_gamma_local (GammaType const &gamma)
void mpi_set_brownian_gamma_rot_local (GammaType const &gamma)
void mpi_set_langevin_gamma_local (GammaType const &gamma)
void mpi_set_langevin_gamma_rot_local (GammaType const &gamma)
void mpi_set_brownian_gamma (GammaType const &gamma)
void mpi_set_brownian_gamma_rot (GammaType const &gamma)
void mpi_set_langevin_gamma (GammaType const &gamma)
void mpi_set_langevin_gamma_rot (GammaType const &gamma)
void mpi_set_thermo_virtual_local (bool thermo_virtual)
void mpi_set_thermo_virtual (bool thermo_virtual)
void mpi_set_temperature_local (double temperature)
void mpi_set_temperature (double temperature)
void mpi_set_thermo_switch_local (int thermo_switch)
void mpi_set_thermo_switch (int thermo_switch)
void mpi_set_nptiso_gammas_local (double gamma0, double gammav)
void mpi_set_nptiso_gammas (double gamma0, double gammav)
Variables
int thermo_switch = THERMO_OFF
Switch determining which thermostat(s) to use.
double temperature = 0.0
Temperature of the thermostat.
bool thermo_virtual = true
True if the thermostat should act on virtual particles.
LangevinThermostat langevin = {}
BrownianThermostat brownian = {}
IsotropicNptThermostat npt_iso = {}
ThermalizedBondThermostat thermalized_bond = {}
DPDThermostat dpd = {}
StokesianThermostat stokesian = {}
Detailed Description
Implementation of thermostat.hpp.
Definition in file thermostat.cpp.
Macro Definition Documentation
REGISTER_THERMOSTAT_CALLBACKS
#define REGISTER_THERMOSTAT_CALLBACKS (thermostat)
Value:
  void mpi_##thermostat##_set_rng_seed(uint32_t const seed) {                  \
    (thermostat).rng_initialize(seed);                                         \
  }                                                                            \
                                                                               \
  REGISTER_CALLBACK(mpi_##thermostat##_set_rng_seed)                           \
                                                                               \
  void thermostat##_set_rng_seed(uint32_t const seed) {                        \
    mpi_call_all(mpi_##thermostat##_set_rng_seed, seed);                       \
  }                                                                            \
                                                                               \
  void mpi_##thermostat##_set_rng_counter(uint64_t const value) {              \
    (thermostat).set_rng_counter(value);                                       \
  }                                                                            \
                                                                               \
  REGISTER_CALLBACK(mpi_##thermostat##_set_rng_counter)                        \
                                                                               \
  void thermostat##_set_rng_counter(uint64_t const value) {                    \
    mpi_call_all(mpi_##thermostat##_set_rng_counter, value);                   \
  }
Create MPI callbacks of thermostat objects.
Parameters
thermostat The thermostat object name
Definition at line 52 of file thermostat.cpp.
Function Documentation
mpi_set_brownian_gamma()
void mpi_set_brownian_gamma (GammaType const & gamma)
Definition at line 172 of file thermostat.cpp.
References Utils::gamma(), mpi_call_all(), and mpi_set_brownian_gamma_local().
mpi_set_brownian_gamma_local()
void mpi_set_brownian_gamma_local (GammaType const & gamma)
Definition at line 149 of file thermostat.cpp.
References brownian, Utils::gamma(), and BrownianThermostat::gamma.
Referenced by mpi_set_brownian_gamma().
mpi_set_brownian_gamma_rot()
void mpi_set_brownian_gamma_rot (GammaType const & gamma)
Definition at line 176 of file thermostat.cpp.
References Utils::gamma(), mpi_call_all(), and mpi_set_brownian_gamma_rot_local().
mpi_set_brownian_gamma_rot_local()
void mpi_set_brownian_gamma_rot_local (GammaType const & gamma)
Definition at line 153 of file thermostat.cpp.
References brownian, Utils::gamma(), and BrownianThermostat::gamma_rotation.
Referenced by mpi_set_brownian_gamma_rot().
mpi_set_langevin_gamma()
void mpi_set_langevin_gamma (GammaType const & gamma)
Definition at line 180 of file thermostat.cpp.
References Utils::gamma(), mpi_call_all(), and mpi_set_langevin_gamma_local().
mpi_set_langevin_gamma_local()
void mpi_set_langevin_gamma_local (GammaType const & gamma)
Definition at line 157 of file thermostat.cpp.
References Utils::gamma(), LangevinThermostat::gamma, langevin, and on_thermostat_param_change().
Referenced by mpi_set_langevin_gamma().
mpi_set_langevin_gamma_rot()
void mpi_set_langevin_gamma_rot (GammaType const & gamma)
Definition at line 183 of file thermostat.cpp.
References Utils::gamma(), mpi_call_all(), and mpi_set_langevin_gamma_rot_local().
mpi_set_langevin_gamma_rot_local()
void mpi_set_langevin_gamma_rot_local (GammaType const & gamma)
Definition at line 162 of file thermostat.cpp.
References Utils::gamma(), LangevinThermostat::gamma_rotation, langevin, and on_thermostat_param_change().
Referenced by mpi_set_langevin_gamma_rot().
mpi_set_nptiso_gammas()
void mpi_set_nptiso_gammas (double gamma0, double gammav)
Definition at line 228 of file thermostat.cpp.
References mpi_call_all(), and mpi_set_nptiso_gammas_local().
mpi_set_nptiso_gammas_local()
void mpi_set_nptiso_gammas_local (double gamma0, double gammav)
Definition at line 220 of file thermostat.cpp.
References IsotropicNptThermostat::gamma0, IsotropicNptThermostat::gammav, npt_iso, and on_thermostat_param_change().
Referenced by mpi_set_nptiso_gammas().
mpi_set_temperature()
void mpi_set_temperature (double temperature)
Definition at line 205 of file thermostat.cpp.
References mpi_call_all(), mpi_set_temperature_local(), and temperature.
mpi_set_temperature_local()
void mpi_set_temperature_local (double temperature)
Definition at line 197 of file thermostat.cpp.
References on_temperature_change(), on_thermostat_param_change(), and temperature.
Referenced by mpi_set_temperature().
mpi_set_thermo_switch()
void mpi_set_thermo_switch (int thermo_switch)
Definition at line 215 of file thermostat.cpp.
References mpi_call_all(), mpi_set_thermo_switch_local(), and thermo_switch.
mpi_set_thermo_switch_local()
void mpi_set_thermo_switch_local (int thermo_switch)
Definition at line 209 of file thermostat.cpp.
References thermo_switch.
Referenced by mpi_set_thermo_switch().
mpi_set_thermo_virtual()
void mpi_set_thermo_virtual (bool thermo_virtual)
Definition at line 193 of file thermostat.cpp.
References mpi_call_all(), mpi_set_thermo_virtual_local(), and thermo_virtual.
mpi_set_thermo_virtual_local()
void mpi_set_thermo_virtual_local (bool thermo_virtual)
Definition at line 187 of file thermostat.cpp.
References thermo_virtual.
Referenced by mpi_set_thermo_virtual().
philox_counter_increment()
void philox_counter_increment ()
Increment RNG counters.
Definition at line 122 of file thermostat.cpp.
References brownian, dpd, langevin, n_thermalized_bonds, npt_iso, BaseThermostat::rng_increment(), stokesian, thermalized_bond, THERMO_BROWNIAN, THERMO_DPD, THERMO_LANGEVIN, THERMO_NPT_ISO, THERMO_SD, and thermo_switch.
Referenced by integrate().
thermo_init()
void thermo_init (double time_step)
Initialize constants of the thermostat at the start of integration.
Definition at line 99 of file thermostat.cpp.
References brownian, dpd_init(), langevin, n_thermalized_bonds, npt_iso, nptiso, NptIsoParameters::piston, LangevinThermostat::recalc_prefactors(), BrownianThermostat::recalc_prefactors(), IsotropicNptThermostat::recalc_prefactors(), temperature, thermalized_bond_init(), THERMO_BROWNIAN, THERMO_DPD, THERMO_LANGEVIN, THERMO_NPT_ISO, THERMO_OFF, thermo_switch, and time_step.
Referenced by on_integration_start().
Variable Documentation
brownian
BrownianThermostat brownian = {}
Definition at line 74 of file thermostat.cpp.
Referenced by bd_random_walk(), bd_random_walk_rot(), bd_random_walk_vel(), bd_random_walk_vel_rot(), brownian_dynamics_propagator(), integrator_step_2(), mpi_set_brownian_gamma_local(), mpi_set_brownian_gamma_rot_local(), philox_counter_increment(), and thermo_init().
dpd
DPDThermostat dpd = {}
Definition at line 80 of file thermostat.cpp.
Referenced by dpd_noise(), Constraints::ShapeBasedConstraint::force(), and philox_counter_increment().
langevin
LangevinThermostat langevin = {}
Definition at line 73 of file thermostat.cpp.
Referenced by friction_thermo_langevin(), friction_thermo_langevin_rotation(), mpi_set_langevin_gamma_local(), mpi_set_langevin_gamma_rot_local(), philox_counter_increment(), thermo_init(), and thermostat_force().
npt_iso
IsotropicNptThermostat npt_iso = {}
Definition at line 76 of file thermostat.cpp.
Referenced by friction_therm0_nptiso(), friction_thermV_nptiso(), mpi_set_nptiso_gammas_local(), philox_counter_increment(), thermo_init(), velocity_verlet_npt_finalize_p_inst(), velocity_verlet_npt_propagate_vel(), and velocity_verlet_npt_propagate_vel_final().
stokesian
StokesianThermostat stokesian = {}
Definition at line 83 of file thermostat.cpp.
Referenced by philox_counter_increment(), and propagate_vel_pos_sd().
temperature
double temperature = 0.0
Temperature of the thermostat.
Definition at line 42 of file thermostat.cpp.
Referenced by integrate(), mpi_set_temperature(), mpi_set_temperature_local(), and thermo_init().
thermalized_bond
ThermalizedBondThermostat thermalized_bond = {}
Definition at line 78 of file thermostat.cpp.
Referenced by ThermalizedBond::forces(), philox_counter_increment(), and ScriptInterface::Interactions::ThermalizedBond::ThermalizedBond().
thermo_switch
int thermo_switch = THERMO_OFF
Switch determining which thermostat(s) to use.
This is a or'd value of the different possible thermostats (defines: THERMO_OFF, THERMO_LANGEVIN, THERMO_DPD THERMO_NPT_ISO). If it is zero all thermostats are switched off and the temperature is set to zero.
Definition at line 41 of file thermostat.cpp.
Referenced by add_non_bonded_pair_force(), Constraints::ShapeBasedConstraint::force(), global_ghost_flags(), integrator_sanity_checks(), mpi_set_thermo_switch(), mpi_set_thermo_switch_local(), philox_counter_increment(), thermo_init(), and thermostat_force().
thermo_virtual
bool thermo_virtual = true
True if the thermostat should act on virtual particles.
Definition at line 43 of file thermostat.cpp.
Referenced by bd_random_walk(), bd_random_walk_vel(), brownian_dynamics_propagator(), force_calc(), friction_thermo_langevin(), mpi_set_thermo_virtual(), and mpi_set_thermo_virtual_local().