ESPResSo: thole.hpp File Reference
thole.hpp File Reference
Routines to calculate the Thole damping potential between particle pairs.
#include <config/config.hpp>
#include "Particle.hpp"
#include "bonded_interactions/bonded_interaction_data.hpp"
#include "electrostatics/coulomb.hpp"
#include "electrostatics/coulomb_inline.hpp"
#include "electrostatics/solver.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <cmath>
Functions
Utils::Vector3d thole_pair_force (Particle const &p1, Particle const &p2, IA_parameters const &ia_params, Utils::Vector3d const &d, double dist, BondedInteractionsMap const &bonded_ias, Coulomb::ShortRangeForceKernel::kernel_type const *kernel)
Calculate Thole force.
double thole_pair_energy (Particle const &p1, Particle const &p2, IA_parameters const &ia_params, Utils::Vector3d const &d, double dist, BondedInteractionsMap const &bonded_ias, Coulomb::Solver const &coulomb, Coulomb::ShortRangeEnergyKernel::kernel_type const *kernel)
Calculate Thole energy.
Detailed Description
Routines to calculate the Thole damping potential between particle pairs.
See [45].
Definition in file thole.hpp.
Function Documentation
thole_pair_energy()
double thole_pair_energy (Particle const & p1, Particle const & p2, IA_parameters const & ia_params, Utils::Vector3d const & d, double dist, BondedInteractionsMap const & bonded_ias, Coulomb::Solver const & coulomb, Coulomb::ShortRangeEnergyKernel::kernel_type const * kernel) inline
Calculate Thole energy.
Definition at line 68 of file thole.hpp.
References Coulomb::Solver::cutoff(), BondedInteractionsMap::pair_bond_exists_between(), and stream.
Referenced by calc_non_bonded_pair_energy().
thole_pair_force()
Utils::Vector3d thole_pair_force (Particle const & p1, Particle const & p2, IA_parameters const & ia_params, Utils::Vector3d const & d, double dist, BondedInteractionsMap const & bonded_ias, Coulomb::ShortRangeForceKernel::kernel_type const * kernel) inline
Calculate Thole force.
Definition at line 45 of file thole.hpp.
References BondedInteractionsMap::pair_bond_exists_between(), and stream.
Referenced by add_non_bonded_pair_force_with_p(), add_non_bonded_pair_virials(), Constraints::ShapeBasedConstraint::force(), and ForcesKernel::operator()().