ESPResSo: tuning.hpp File Reference
tuning.hpp File Reference
#include <stdexcept>
#include <string>
Classes
class TuningFailed
Functions
double benchmark_integration_step (int int_steps)
Benchmark the integration loop.
void tune_skin (double min_skin, double max_skin, double tol, int int_steps, bool adjust_max_skin)
Set the optimal skin between min_skin and max_skin by bisection to tolerance tol.
Function Documentation
benchmark_integration_step()
double benchmark_integration_step (int int_steps)
Benchmark the integration loop.
Call integrate() several times and measure the elapsed time without propagating the system. It therefore doesn't include e.g. Verlet list updates.
Parameters
int_steps Number of integration steps.
Returns
Average time per integration loop in milliseconds.
Definition at line 74 of file tuning.cpp.
References Utils::Statistics::RunningAverage< Scalar >::add_sample(), Utils::Statistics::RunningAverage< Scalar >::avg(), check_statistics(), comm_cart, integrate(), this_node, and throw_on_error().
Referenced by TuningAlgorithm::get_mc_time(), and CoulombMMM1D::tune().
tune_skin()
void tune_skin (double min_skin, double max_skin, double tol, int int_steps, bool adjust_max_skin)
Set the optimal skin between min_skin and max_skin by bisection to tolerance tol.
Definition at line 121 of file tuning.cpp.
References box_geo, cell_structure, BoxGeometry::length(), CellStructure::max_cutoff(), maximal_cutoff(), anonymous_namespace{Correlator.cpp}::min(), mpi_set_skin(), n_nodes, and time_calc().