ESPResSo: utils.cuh File Reference
utils.cuh File Reference
#include "utils.hpp"
#include <cuda.h>
#include <string>
Classes
class cuda_runtime_error_cuda
Macros
#define CUDA_CHECK(statement)
Convert CUDA error codes into runtime errors.
#define cuda_safe_mem(a) cuda_safe_mem_exit((a), __FILE__, __LINE__)
#define KERNELCALL_shared(_function, _grid, _block, _stream, ...)
#define KERNELCALL(_function, _grid, _block, ...) KERNELCALL_shared(_function, _grid, _block, 0, ##__VA_ARGS__)
Functions
void cuda_safe_mem_exit (cudaError_t CU_err, const char *file, unsigned int line)
In case of error during CUDA memory allocation and memory copy, print the error message and exit.
void cuda_check_errors_exit (const dim3 &block, const dim3 &grid, const char *function, const char *file, unsigned int line)
In case of error during a CUDA operation, print the error message and exit.
Variables
cudaStream_t stream [1]
CUDA streams for parallel computing on CPU and GPU.
Macro Definition Documentation
CUDA_CHECK
#define CUDA_CHECK (statement)
Value:
  {                                                                            \
    cudaError_t const error_code = (statement);                                \
    if (error_code != cudaSuccess) {                                           \
      throw cuda_runtime_error_cuda(error_code);                               \
    }                                                                          \
  }
Convert CUDA error codes into runtime errors.
Definition at line 45 of file utils.cuh.
cuda_safe_mem
#define cuda_safe_mem (a) cuda_safe_mem_exit((a), __FILE__, __LINE__)
Definition at line 71 of file utils.cuh.
KERNELCALL
#define KERNELCALL (_function, _grid, _block, ...) KERNELCALL_shared(_function, _grid, _block, 0, ##__VA_ARGS__)
Definition at line 77 of file utils.cuh.
KERNELCALL_shared
#define KERNELCALL_shared (_function, _grid, _block, _stream, ...)
Value:
  _function<<<_grid, _block, _stream, stream[0]>>>(__VA_ARGS__);               \
  cuda_check_errors_exit(_grid, _block, #_function, __FILE__, __LINE__);
Definition at line 73 of file utils.cuh.
Function Documentation
cuda_check_errors_exit()
void cuda_check_errors_exit (const dim3 & block, const dim3 & grid, const char * function, const char * file, unsigned int line)
In case of error during a CUDA operation, print the error message and exit.
Definition at line 28 of file common_cuda.cu.
References block(), and errexit().
Referenced by assign_charges(), and assign_forces().
cuda_safe_mem_exit()
void cuda_safe_mem_exit (cudaError_t CU_err, const char * file, unsigned int line)
In case of error during CUDA memory allocation and memory copy, print the error message and exit.
Parameters
CU_err cuda error code
file .cu file were the error took place
line line of the file were the error took place
Definition at line 42 of file common_cuda.cu.
References errexit().
Variable Documentation
stream
cudaStream_t stream[1] extern
CUDA streams for parallel computing on CPU and GPU.
Definition at line 26 of file common_cuda.cu.
Referenced by GpuParticleData::Storage::copy_particles_to_device(), cuda_init(), and cuda_set_device().