ESPResSo: velocity_verlet_inline.hpp File Reference
velocity_verlet_inline.hpp File Reference
#include "config.hpp"
#include "Particle.hpp"
#include "ParticleRange.hpp"
#include "cell_system/CellStructure.hpp"
#include "integrate.hpp"
#include "rotation.hpp"
Functions
void velocity_verlet_propagate_vel_pos (const ParticleRange &particles, double time_step)
Propagate the velocities and positions.
void velocity_verlet_propagate_vel_final (const ParticleRange &particles, double time_step)
Final integration step of the Velocity Verlet integrator.
void velocity_verlet_step_1 (const ParticleRange &particles, double time_step)
void velocity_verlet_step_2 (const ParticleRange &particles, double time_step)
Function Documentation
velocity_verlet_propagate_vel_final()
void velocity_verlet_propagate_vel_final (const ParticleRange & particles, double time_step) inline
Final integration step of the Velocity Verlet integrator.
\[ v(t+\Delta t) = v(t+0.5 \Delta t) + 0.5 \Delta t f(t+\Delta t)/m \]
Definition at line 62 of file velocity_verlet_inline.hpp.
References Cells::particles(), and time_step.
Referenced by velocity_verlet_step_2().
velocity_verlet_propagate_vel_pos()
void velocity_verlet_propagate_vel_pos (const ParticleRange & particles, double time_step) inline
Propagate the velocities and positions.
Integration steps before force calculation of the Velocity Verlet integrator:
\[ v(t+0.5 \Delta t) = v(t) + 0.5 \Delta t f(t)/m \]
\[ p(t+\Delta t) = p(t) + \Delta t v(t+0.5 \Delta t) \]
Definition at line 35 of file velocity_verlet_inline.hpp.
References Cells::particles(), propagate_omega_quat_particle(), and time_step.
Referenced by velocity_verlet_step_1().
velocity_verlet_step_1()
void velocity_verlet_step_1 (const ParticleRange & particles, double time_step) inline
Definition at line 79 of file velocity_verlet_inline.hpp.
References increment_sim_time(), Cells::particles(), time_step, and velocity_verlet_propagate_vel_pos().
Referenced by integrator_step_1().
velocity_verlet_step_2()
void velocity_verlet_step_2 (const ParticleRange & particles, double time_step) inline
Definition at line 85 of file velocity_verlet_inline.hpp.
References convert_torques_propagate_omega(), Cells::particles(), time_step, and velocity_verlet_propagate_vel_final().
Referenced by integrator_step_2().