ESPResSo: VirtualSitesRelative.cpp File Reference
VirtualSitesRelative.cpp File Reference
#include "VirtualSitesRelative.hpp"
#include "Particle.hpp"
#include "cells.hpp"
#include "errorhandling.hpp"
#include "forces.hpp"
#include "grid.hpp"
#include "integrate.hpp"
#include "rotation.hpp"
#include <utils/Vector.hpp>
#include <utils/math/quaternion.hpp>
#include <utils/math/tensor_product.hpp>
#include <utils/quaternion.hpp>
Functions
static auto connection_vector (Particle const &p_ref, Particle const &p_vs)
Vector pointing from the real particle to the virtual site.
static Utils::Vector3d velocity (Particle const &p_ref, Particle const &p_vs)
Velocity of the virtual site.
static Particle * get_reference_particle (Particle const &p)
Get real particle tracked by a virtual site.
static auto constraint_stress (Particle const &p_ref, Particle const &p_vs)
Constraint force to hold the particle at its prescribed position.
Function Documentation
connection_vector()
static auto connection_vector (Particle const & p_ref, Particle const & p_vs) static
Vector pointing from the real particle to the virtual site.
Returns
Relative distance.
Definition at line 42 of file VirtualSitesRelative.cpp.
References Utils::convert_quaternion_to_director(), Utils::Vector< T, N >::normalize(), Particle::quat(), and Particle::vs_relative().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), constraint_stress(), VirtualSitesRelative::update(), and velocity().
constraint_stress()
static auto constraint_stress (Particle const & p_ref, Particle const & p_vs) static
Constraint force to hold the particle at its prescribed position.
Parameters
p_ref Reference particle.
p_vs Virtual site.
Returns
Constraint force.
Definition at line 97 of file VirtualSitesRelative.cpp.
References connection_vector(), Particle::force(), and Accumulators::tensor_product().
Referenced by VirtualSitesRelative::pressure_tensor().
get_reference_particle()
static Particle* get_reference_particle (Particle const & p) static
Get real particle tracked by a virtual site.
Parameters
p Virtual site.
Returns
Pointer to real particle.
Definition at line 77 of file VirtualSitesRelative.cpp.
References cell_structure, CellStructure::get_local_particle(), Particle::id(), Particle::is_virtual(), runtimeErrorMsg, and Particle::vs_relative().
Referenced by VirtualSitesRelative::back_transfer_forces_and_torques(), VirtualSitesRelative::pressure_tensor(), and VirtualSitesRelative::update().
velocity()
static Utils::Vector3d velocity (Particle const & p_ref, Particle const & p_vs) static
Velocity of the virtual site.
Parameters
p_ref Reference particle for the virtual site.
p_vs Virtual site.
Returns
Velocity of the virtual site.
Definition at line 61 of file VirtualSitesRelative.cpp.
References connection_vector(), convert_vector_body_to_space(), Particle::omega(), Particle::v(), and vector_product().
Referenced by bd_drag_vel(), bd_random_walk_vel(), calc_viscous_force(), friction_thermo_langevin(), lb_lbfluid_print_velocity(), Observables::CylindricalLBVelocityProfile::operator()(), set_u_from_rho_v_pi(), and VirtualSitesRelative::update().