ESPResSo: virtual_sites.hpp File Reference
virtual_sites.hpp File Reference
#include "config.hpp"
#include "Particle.hpp"
#include "virtual_sites/VirtualSites.hpp"
#include <memory>
Functions
const std::shared_ptr< VirtualSites > & virtual_sites ()
Get active virtual sites implementation.
void set_virtual_sites (std::shared_ptr< VirtualSites > const &v)
Set active virtual sites implementation.
void vs_relate_to (int part_num, int relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
void local_vs_relate_to (Particle &p_current, Particle const &p_relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
Function Documentation
local_vs_relate_to()
void local_vs_relate_to (Particle & p_current, Particle const & p_relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
Definition at line 130 of file virtual_sites.cpp.
References calculate_vs_relate_to_params(), Particle::id(), and Particle::vs_relative().
Referenced by place_vs_and_relate_to_particle().
set_virtual_sites()
void set_virtual_sites (std::shared_ptr< VirtualSites > const & v)
Set active virtual sites implementation.
Definition at line 51 of file virtual_sites.cpp.
References anonymous_namespace{virtual_sites.cpp}::m_virtual_sites, and recalc_forces.
Referenced by ScriptInterface::VirtualSites::ActiveVirtualSitesHandle::ActiveVirtualSitesHandle(), and EspressoSystemStandAlone::EspressoSystemStandAlone().
virtual_sites()
const std::shared_ptr<VirtualSites>& virtual_sites ()
Get active virtual sites implementation.
Definition at line 49 of file virtual_sites.cpp.
References anonymous_namespace{virtual_sites.cpp}::m_virtual_sites.
Referenced by force_calc(), integrate(), and update_dependent_particles().
vs_relate_to()
void vs_relate_to (int part_num, int relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
Definition at line 139 of file virtual_sites.cpp.
References calculate_vs_relate_to_params(), get_particle_data(), set_particle_virtual(), and set_particle_vs_relative().