ESPResSo: virtual_sites.cpp File Reference
virtual_sites.cpp File Reference
#include "config.hpp"
#include "virtual_sites.hpp"
#include "Particle.hpp"
#include "communication.hpp"
#include "errorhandling.hpp"
#include "grid.hpp"
#include "integrate.hpp"
#include "nonbonded_interactions/nonbonded_interaction_data.hpp"
#include "particle_data.hpp"
#include "particle_node.hpp"
#include <utils/Vector.hpp>
#include <utils/math/quaternion.hpp>
#include <cmath>
#include <cstdio>
#include <stdexcept>
#include <tuple>
Namespaces
anonymous_namespace{virtual_sites.cpp}
Functions
const std::shared_ptr< VirtualSites > & virtual_sites ()
Get active virtual sites implementation.
void set_virtual_sites (std::shared_ptr< VirtualSites > const &v)
Set active virtual sites implementation.
static std::tuple< Utils::Quaternion< double >, double > calculate_vs_relate_to_params (Particle const &p_current, Particle const &p_relate_to)
Calculate the rotation quaternion and distance between two particles.
void local_vs_relate_to (Particle &p_current, Particle const &p_relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
void vs_relate_to (int part_num, int relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
Variables
std::shared_ptr< VirtualSites > anonymous_namespace{virtual_sites.cpp}::m_virtual_sites
Function Documentation
calculate_vs_relate_to_params()
static std::tuple<Utils::Quaternion<double>, double> calculate_vs_relate_to_params (Particle const & p_current, Particle const & p_relate_to) static
Calculate the rotation quaternion and distance between two particles.
Definition at line 60 of file virtual_sites.cpp.
References box_geo, Utils::convert_director_to_quaternion(), BoxGeometry::get_mi_vector(), get_min_global_cut(), Utils::Quaternion< T >::identity(), min_global_cut, n_nodes, Utils::Vector< T, N >::norm(), Utils::Quaternion< T >::norm2(), Utils::Vector< T, N >::normalize(), Particle::pos(), Particle::quat(), and runtimeErrorMsg.
Referenced by local_vs_relate_to(), and vs_relate_to().
local_vs_relate_to()
void local_vs_relate_to (Particle & p_current, Particle const & p_relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
Definition at line 130 of file virtual_sites.cpp.
References calculate_vs_relate_to_params(), Particle::id(), and Particle::vs_relative().
Referenced by place_vs_and_relate_to_particle().
set_virtual_sites()
void set_virtual_sites (std::shared_ptr< VirtualSites > const & v)
Set active virtual sites implementation.
Definition at line 51 of file virtual_sites.cpp.
References anonymous_namespace{virtual_sites.cpp}::m_virtual_sites, and recalc_forces.
Referenced by ScriptInterface::VirtualSites::ActiveVirtualSitesHandle::ActiveVirtualSitesHandle(), and EspressoSystemStandAlone::EspressoSystemStandAlone().
virtual_sites()
const std::shared_ptr<VirtualSites>& virtual_sites ()
Get active virtual sites implementation.
Definition at line 49 of file virtual_sites.cpp.
References anonymous_namespace{virtual_sites.cpp}::m_virtual_sites.
Referenced by force_calc(), integrate(), and update_dependent_particles().
vs_relate_to()
void vs_relate_to (int part_num, int relate_to)
Setup the vs_relative of a particle so that the given virtual particle will follow the given real particle.
Definition at line 139 of file virtual_sites.cpp.
References calculate_vs_relate_to_params(), get_particle_data(), set_particle_virtual(), and set_particle_vs_relative().