ESPResSo: visitors.hpp File Reference
visitors.hpp File Reference
#include "actor/traits.hpp"
#include <utils/demangle.hpp>
#include <boost/optional.hpp>
#include <boost/variant.hpp>
#include <functional>
#include <memory>
#include <string>
#include <type_traits>
Classes
struct GetActorName
struct GetActorByType< Actor >
Get an actor of a specific type, recursively.
struct HasActorOfType< Actor >
Check if an actor of a specific type is active, recursively.
struct ActorEquality
Check whether two actors are identical by pointer.
Functions
template<class Variant >
auto get_actor_name (Variant const &variant)
Get the symbol name of an actor.
template<typename Actor , typename Variant >
std::shared_ptr< Actor > get_actor_by_type (Variant const &variant)
Get an active actor of a specific type, recursively.
template<typename Actor , typename Variant >
std::shared_ptr< Actor > get_actor_by_type (boost::optional< Variant > const &optional)
template<typename Actor , typename Variant >
auto has_actor_of_type (Variant const &variant)
Check if an actor of a specific type is active, recursively.
template<typename Actor , typename Variant >
auto has_actor_of_type (boost::optional< Variant > const &optional)
template<typename T , class Variant >
bool is_already_stored (std::shared_ptr< T > const &actor, boost::optional< Variant > const &active_actor)
Check if an actor is already stored in an optional.
Function Documentation
get_actor_by_type() [1/2]
template<typename Actor , typename Variant > std::shared_ptr<Actor> get_actor_by_type (boost::optional< Variant > const & optional)
Definition at line 84 of file visitors.hpp.
get_actor_by_type() [2/2]
template<typename Actor , typename Variant > std::shared_ptr<Actor> get_actor_by_type (Variant const & variant)
Get an active actor of a specific type, recursively.
Definition at line 78 of file visitors.hpp.
get_actor_name()
template<class Variant > auto get_actor_name (Variant const & variant)
Get the symbol name of an actor.
Definition at line 42 of file visitors.hpp.
Referenced by Coulomb::add_actor(), and Dipoles::add_actor().
has_actor_of_type() [1/2]
template<typename Actor , typename Variant > auto has_actor_of_type (boost::optional< Variant > const & optional)
Definition at line 125 of file visitors.hpp.
has_actor_of_type() [2/2]
template<typename Actor , typename Variant > auto has_actor_of_type (Variant const & variant)
Check if an actor of a specific type is active, recursively.
Definition at line 120 of file visitors.hpp.
is_already_stored()
template<typename T , class Variant > bool is_already_stored (std::shared_ptr< T > const & actor, boost::optional< Variant > const & active_actor)
Check if an actor is already stored in an optional.
Definition at line 150 of file visitors.hpp.
Referenced by Coulomb::remove_actor(), and Dipoles::remove_actor().