ESPResSo: wca.hpp File Reference
wca.hpp File Reference
#include "config.hpp"
#include "nonbonded_interaction_data.hpp"
#include <utils/Vector.hpp>
#include <utils/math/int_pow.hpp>
#include <utils/math/sqr.hpp>
Functions
int wca_set_params (int part_type_a, int part_type_b, double eps, double sig)
double wca_pair_force_factor (IA_parameters const &ia_params, double dist)
Calculate WCA force factor.
double wca_pair_energy (IA_parameters const &ia_params, double dist)
Calculate WCA energy.
Detailed Description
Routines to calculate the Weeks-Chandler-Andersen potential between particle pairs.
Implementation in wca.cpp.
Definition in file wca.hpp.
Function Documentation
wca_pair_energy()
double wca_pair_energy (IA_parameters const & ia_params, double dist) inline
Calculate WCA energy.
Definition at line 51 of file wca.hpp.
References WCA_Parameters::cut, WCA_Parameters::eps, WCA_Parameters::sig, Utils::sqr(), and IA_parameters::wca.
Referenced by calc_non_bonded_pair_energy().
wca_pair_force_factor()
double wca_pair_force_factor (IA_parameters const & ia_params, double dist) inline
Calculate WCA force factor.
Definition at line 41 of file wca.hpp.
References WCA_Parameters::cut, WCA_Parameters::eps, WCA_Parameters::sig, and IA_parameters::wca.
Referenced by calc_non_bonded_pair_force().
wca_set_params()
int wca_set_params (int part_type_a, int part_type_b, double eps, double sig)
Definition at line 33 of file wca.cpp.
References WCA_Parameters::cut, WCA_Parameters::eps, ES_OK, get_ia_param_safe(), mpi_bcast_ia_params(), WCA_Parameters::sig, and IA_parameters::wca.